### ISSUE TITLE
Problem with generated documentation when a method is named 'exception'

### ISSUE THREAD

**Issue by diegodiasm** [doxygen/doxygen#10006]
The method name in the generated documentation is incorrect when the method is named 'exception'. Instead of using this name,  doxygen uses the name of an argument (cf. `Handler::exception()` in MWE) or the name of an entity which succeeds the method declaration (cf. `Test::exception()` in the MWE). On these cases, I would have expected the name 'exception' to appear as the method name, since this is the name source code.

Attached is a [minimal working example](https://github.com/doxygen/doxygen/files/11332457/mwe-method-named-exception.zip) which illustrates the problem I first observed this problem [here](https://l4re.org/doc/classL4_1_1Exception.html). I developed the minimal working example in doxygen 1.9.1 (taken from the website) running on Ubuntu 22.04.1 LTS.

**Comment by albert-github** [comment]
Problem look like to be the space after the word `exception`, removing it results in the correct output. if is seen as a Corba IDL/Slice exception)
Note the 1.9.1 version is from January 8 2021, the current doxygen version is 1.9.6 (which has the same problem).

I've just pushed a proposed patch, pull request #10008

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.7.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
