### ISSUE TITLE
Consider moving gh-pages branch to a standalone git repository

### ISSUE THREAD

**Issue by hashar** [doxygen/doxygen#10028]
**Describe the bug**

I had not updated my local copy of the Doxygen repository in a long time (since at least 1.9.2), and upon doing a `git pull` I got:
```
Receiving objects: 100% (254828/254828), 1.39 GiB | 1.36 MiB/s, done.
```
Previously the `.git` directory had 138 MBytes of objects and after the pull that went to 1581 MBytes a ten fold increase.

I went to inspect the largest objects in the git repository using https://stackoverflow.com/questions/10622179/how-to-find-identify-large-commits-in-git-history#42544963:
```
git rev-list --objects --all |
  git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' |
  sed -n 's/^blob //p' |
  sort --numeric-sort --key=2 |
  cut -c 1-12,41- |
  $(command -v gnumfmt || echo numfmt) --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest
```
It yields some 11-13MB entries for files such as `Tokens.xml` or `Nodes.xml`. Those large files are from the `gh-pages` branch for example 556ebd9b46b934efe0895579473f739f53b7461f

**Additional information**

The `gh-pages` branch has been created in August 2022 by @doxygen with 60eb7c60633cb793609c37d47f71fb4e7b3aab2a

**Expected behavior**

I would expect the doxygen/doxygen repository to be slimmer and not be encumbered with generated artifacts intended for deployment

Maybe a new repository can be created under the https://github.com/doxygen/ organization such as `gh-page` and the branch be moved them and removed from `doxygen/doxygen`?  That will result in smaller repository.

**Comment by doxygen** [comment]
I've just pushed [this commit](https://github.com/doxygen/doxygen/commit/82fbbd7f2b20ff18541b40fd4efcd0e3db245bc9) to publish the generated pages into a separate doxygen-docs repository, seems to work fine.

**Comment by hashar** [comment]
Solved indeed:
```
$ git count-objects -vH|grep size-pack
size-pack: 63.13 MiB
```
Thank you very much @albert-github
