### ISSUE TITLE
Objective C, Error in generated documentation when using "NS_DESIGNATED_INITIALIZER"

### ISSUE THREAD

**Issue by khc1100** [doxygen/doxygen#10046]
**Describe the bug**
In functions that we declare to be the designated initializer in Objective C using the "NS_DESIGNATED_INITIALIZER" keyword, The last input variable is documented to be named "NS_DESIGNATED_INITIALIZER" instead of given name. 

**Similar to bug:** #7407

**Expected behavior**
Example Objective-C Code:
```- (instancetype)initWithX:(double)inX Y:(double)inY Z:(double)inZ NS_DESIGNATED_INITIALIZER;```
I believe that it should not take the "NS_DESIGNATED_INITIALIZER" to be the variable name and instead take "inZ" as the variable name. 

**Screenshots**

![Screen Shot 2023-05-15 at 12 06 58 PM](https://github.com/doxygen/doxygen/assets/97474403/30f98b28-5788-4d08-b582-894bad6afa7f)

**To Reproduce**

This is the file that I called doxygen on using the "doxygen Test.m" using the unedited template Doxyfile

This is the Objective C code in the Test.m file

```objc
#import <Foundation/Foundation.h>

@interface RRPoint : NSObject 

/// Designated initializer.
/** Creates a point with the given coordinates. */
- (instancetype)initWithX:(double)inX Y:(double)inY Z:(double)inZ NS_DESIGNATED_INITIALIZER;

@end
```

**Version**
The doxygen version I am running is 1.9.6 on macOS Monterey 12.6.5

**Stack trace**
There were no errors produced when running doxygen on this file. I also checked that there were no syntax errors by running the file using the `clang -fsyntax-only Test.m`.

**Comment by doxygen** [comment]
> should we ignore NS_DESIGNATED_INITIALIZER when scanning the file?

No, I think the proposed solution using doxygen's preprocessor is sufficient.

**Comment by seanm** [comment]
>No, I think the proposed solution using doxygen's preprocessor is sufficient.

@doxygen It's certainly a workable solution, but it would be slick if doxygen just knew that `NS_DESIGNATED_INITIALIZER` was a language keyword and just ignored it automagically.

Likewise `NS_UNAVAILABLE`, which is basically what #7407 is about.

In fact, several others too; I just checked, and `NS_REQUIRES_SUPER` causes similar problems.

These keywords are highly likely to exist in every modern Objective-C codebase.

If you're willing to reconsider doxygen automatically ignoring them, I can commit to generating a list of which are currently problematic, and testing. Could maybe attempt a PR too if you could point to where it should be done.

**Comment by albert-github** [comment]
- Is there an official list with all the `NS_...`?
- The `NS_UNAVAILABLE`  is probably quite hard as here the function is in the code but should not appear in the documentation as it is only for internal use at least this what I get so far.
- the place this should be implemented is in `scanner.l` but might have (`NS_UNAVAILABE`) have consequences elsewhere as well.

**Comment by khc1100** [comment]
@albert-github Hey the best official list that we know of is NSObjCRuntime.h contains a lot of the `NS_... ` keywords

I ran a small test and these keywords all were interpreted as either method names or variable names by Doxygen.

Thank you for your time,

**Comment by albert-github** [comment]
It is a bit of a pity that the list (or a reference to an official list is given). A quick search gave a number of links, probably https://github.com/apportable/Foundation/blob/master/System/Foundation/include/Foundation/NSObjCRuntime.h is the best one, though it still is hard to get a good list from this.
