### ISSUE TITLE
how to customize html output with a template html file

### ISSUE THREAD

**Issue by pierce-c** [doxygen/doxygen#10040]
can someone confirm i can change the size of and/or location of and/or existence of the thing that says generated by doxygen

**Comment by doxygen** [comment]
Check [this part](https://www.doxygen.nl/manual/customize.html#minor_tweaks_header_css) of the manual.

**Comment by pierce-c** [comment]
can i remove the thiing though legally?
also on the part of the generated output that says `mylib Documentation` is there a way to make it say `mylib vnum` and to style that part of the output without manually modifying the output html file every time after i run `doxygen`

**Comment by albert-github** [comment]
- What do you mean with:
> can i remove the thing though legally?

You can remove it in the footer.

- regarding changing `mylib Documentation`:

To see what you mean a screenshot of the output where you would like to change it and also (very important) attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

**Comment by pierce-c** [comment]
by legally i mean can i put that in my project if i remove the thing saying "generated by doxygen"

**Comment by doxygen** [comment]
> by legally i mean can i put that in my project if i remove the thing saying "generated by doxygen"

Yes, this is allowed, you can modify the output produced by doxygen in any way you like.
