### ISSUE TITLE
Invalid C++ declaration: Expecting "(" in parameters-and-qualifiers

### ISSUE THREAD

**Issue by cc00010** [doxygen/doxygen#10065]
**Describe the bug**
I'm getting this error: `Invalid C++ declaration: Expecting "(" in parameters-and-qualifiers`
with this code:

```c
PUBLIC int myfunc (const char *addr)
```

`PUBLIC` is:
```c
#define PUBLIC __attribute__((visibility("default")))
```

**Expected behavior**
It should not complain?

**Version**
```bash
doxygen -v
1.9.6
```

**Comment by albert-github** [comment]
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.
- please check also the documentation regarding preprocessing: https://www.doxygen.nl/manual/preprocessing.html

**Comment by cc00010** [comment]
I've tried setting proper values in Doxyfile, but no luck.

I'm actually combining doxygen + sphinx + breathe + cmake. The funny thing is this works:

```c
__attribute__((visibility("default"))) int myfunc(void);
```

but this fails:

```c
#define mymacro

mymacro int myfunc(void);
```

The log is:
```
If the function has no return type:
  Error in declarator or parameters-and-qualifiers
  Invalid C++ declaration: Expecting "(" in parameters-and-qualifiers. [error at 12]
    mymacro int myfunc (void)
    ----------^
If the function has a return type:
  Error in declarator or parameters-and-qualifiers
  If pointer to member declarator:
    Invalid C++ declaration: Expected identifier in nested name, got keyword: int [error at 15]
      mymacro int myfunc (void)
      ----------^
  If declarator-id:
    Invalid C++ declaration: Expected identifier in nested name, got keyword: int [error at 15]
      ETHC_EXPORT int tes (void)
```

Following this "tutorial": https://github.com/smrfeld/cpp_doxygen_sphinx

**Comment by albert-github** [comment]
As there is no Doxyfile / example attached to your comment it is hard to tell. 
It is all unknown what is happening in the sphinx and breathe part but as far as I know they use the xml output (so to say something more sensible we need the example and settings as they are fed into doxygen)
- Maybe sphinx / breathe filters out the `__attribute__`
- Maybe sphinx / breathe sets the `MACRO_EXPANSION=YES`
- the "tutorial": https://github.com/smrfeld/cpp_doxygen_sphinx is nothing as supplied by doxygen 


So all in all:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

**Comment by cc00010** [comment]
Thanks @albert-github 

Setting `MACRO_EXPANSION = YES`, `EXPAND_ONLY_PREDEF = YES` and `PREDEFINED = MACRO_NAME` in `Doxyfile` fixed the issue.

Just forgot to close the issue.
