### ISSUE TITLE
\include and Python

### ISSUE THREAD

**Issue by couet** [doxygen/doxygen#10076]
**Describe the bug**
In the ROOT reference guide (build with Doxygen) we are using `\include` to show the code of tutorials.
Some are in C++ some are in Python. The highlighting looks nice for C++ but does not work very well with 
some Python examples we have. Like the one mentioned here:
https://github.com/root-project/root/issues/12851

**Expected behavior**
The correct highlight of Python code.

**Screenshots**
See https://github.com/root-project/root/issues/12851

**Version**
1.9.5

**Comment by albert-github** [comment]
I can see in the string literals some problems but which other problems do you see?
The source and output from the project mentioned is a moving target so:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

**Comment by couet** [comment]
Yes, the problem is with the string literal. I will test your patch. Thanks

**Comment by couet** [comment]
By the way, I have a question about `\include`: How does it decide which language is the file included / with the file name extension?

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by albert-github** [comment]
Regarding the questing about the `\include` (https://github.com/doxygen/doxygen/issues/10076#issuecomment-1560557820) this is done in the same way as "normal" files i.e. based on the extension.

**Comment by couet** [comment]
Maybe it can be mentioned here: https://www.doxygen.nl/manual/commands.html#cmdinclude ?

**Comment by albert-github** [comment]
Is an idea, but should in that case also be added to other commands like `\snippet`, `\example`, ...

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.8.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Comment by couet** [comment]
It is fixed in 1.9.8. Thanks
