### ISSUE TITLE
1.9.7: Auto-assigned names for anonymous C++ enums missing?

### ISSUE THREAD

**Issue by swt2c** [doxygen/doxygen#10071]
In 1.9.6 and earlier, doxygen would auto-assign names (such as "@0") for anonymous enums.  In 1.9.7, this seems to have been removed.  Was this intentional?  A trivial example that shows the change is attached.

Simple C++ enum:
```
enum
{
    ITEM_1 = 1,
    ITEM_2,
    ITEM_3
}
```

Diff of XML output:
```
$ diff -r xml_1.9.6/test_8h.xml xml_1.9.7/test_8h.xml 
2c2
< <doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.9.6" xml:lang="en-US">
---
> <doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.9.7" xml:lang="en-US">
8c8
<         <name>@0</name>
---
>         <name></name>
```
[example.zip](https://github.com/doxygen/doxygen/files/11533290/example.zip)

**Comment by albert-github** [comment]
Yes this was intentional see: https://github.com/doxygen/doxygen/pull/9976

**Comment by swt2c** [comment]
OK, thanks.  I don't see any reason for having the artificial names - I just have some downstream code that relied on a non-empty name.  Will adapt it.  Thanks.
