### ISSUE TITLE
how to rename 'Modules' to 'Categories' in tree-view of doxygen-generated documentation

### ISSUE THREAD

**Issue by saifikhan** [doxygen/doxygen#10093]
**Describe the bug**

Please see the attached screenshot.
![doxygen_doc](https://github.com/doxygen/doxygen/assets/6829091/3ed7e197-4799-45e3-ab80-218f18f14773)

A review of the word 'Modules' here is warranted to _avoid confusion_ with the use of an identical word 'modules' in the context of **C++ modules**.

Perhaps the word 'Modules' may be _renamed_ to '**Categories**' as used in the context of an organizing principle.

Digging deeper here is what i found

Doxygen has 'Modules' hard-coded everywhere in the code as they have used the word as an organizing principle.

It starts with enum Kind defined in LayoutNavEntry 

https://raw.githubusercontent.com/doxygen/doxygen/master/src/layout.h

All the string-literals related to usage of word 'Modules' are hard-coded in this file.

https://raw.githubusercontent.com/doxygen/doxygen/master/src/translator_en.h

Modules
Modules List
Modules Index

There are additional entries with regard to the usage of the term in Fortran which may be skipped. 

There are multiple translator files on a per-language (human spoken language) basis.

Short of re-compiling the doxygen code with string literal changed to "Components" i can't seem to find any other way.

I also tried the 'custom' layout approach.

The file modified is
/opt/gcc/src/libstdc++-v3/doc/doxygen/DoxygenLayout.xml

<tab type="modules" visible="yes" title="Categories" intro=""/>

But that doesn't seem to work either.

How do i fix this ? any workarounds ?

**Comment by albert-github** [comment]
The term modules / modules can indeed be quite confusing and  in the C++ language added for the 2020 standard (when I'm not mistaken).
I remember that I looked at the problem before and couldn't find a solution (I cannot find the relevant issue though, I think it was in relation to Java or Fortran).

At the moment I don't think there is a solution or workaround for the problem.

(related issues probably #3319 and #3692)

**Comment by aslze** [comment]
Did you try to use a custom DoxygenLayout.xml file, and set the *title*, normally empty, to anything else?

```xml
<navindex>
  <tab type="modules" visible="yes" title="Categories" intro="">
</navindex>
```

**Comment by albert-github** [comment]
> A review of the word 'Modules' here is warranted to avoid confusion with the use of an identical word 'modules' in the context of C++ modules.

Due to the introduction of C++20 modules (in doxygen version 1.9.8) the name "Modules' for the groups was not really valid anymore (and as remarked in the issue and even in the past it was a bit dubious to use it). The original "Modules" (so for the group usage) has been renamed to "Topics".

So I tink the problem has been solved in the mean time (by changing "Modules" to "Topics"), though some more flexibility would always be better (but that is a completely different issue).
