### ISSUE TITLE
VS Code plugin error

### ISSUE THREAD

**Issue by NotWhiteRice** [doxygen/doxygen#10092]
**Describe the bug**
It didn't automatically make annotations, and I had to make them manually, but even after that, they didn't show up when hovering over my functions.

**Expected behavior**
The annotations should be made automatically when I type 3 /'s and the documentation should appear when I hover over my functions.

**Screenshots**
![Screenshot (126)](https://github.com/doxygen/doxygen/assets/42843154/376f9049-9f58-446d-954b-e295fbe216e2)

**To Reproduce**
I don't know how to reproduce it, but VS Code says one uncaught error: "Error: spawn git ENOENT at ChildProcess._handle.onexit (node:internal/child_process:285:19) at onErrorNT (node:internal/child_process:497:16) at process.processTicksAndRejections (node:internal/process/task_queues:83:21)"

All of my code is in https://github.com/NotWhiteRice/the-NWR-Project, and the problem is in nwr/memory/memalloc.hpp.

**Version**
I use Doxygen on VS Code, and it says "PS C:\[REDACTED]\the-NWR-Project\the-NWR-Project> doxygen --version
doxygen: The term 'doxygen' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again." after I type doxygen --version.

**Comment by albert-github** [comment]
I don't think this is a doxygen problem.
- did you install doxygen?
- what happens when you type in a terminal window `doxygen --version`?
