### ISSUE TITLE
How can I make C++ namespaced-functions clickable in html webpage

### ISSUE THREAD

**Issue by zchrissirhcz** [doxygen/doxygen#10102]
**Describe the bug**
I put `hello()` and `world()` functions in changelog.md file, and generate html webpage by specify changelog.md as input. Function `hello()` is clickable, i.e. with hyperlink, but `world()` is no clickable.

`hello()` is an C function, `world()` is an C++ function that within an namespace, both defined in `hello.h`:
```cpp
#pragma once

#ifdef __cplusplus
extern "C" {
#endif

void hello(const char* name);

#ifdef __cplusplus
}
#endif

namespace xx {

void world(int n);

} // namespace xx
```

The chagnelog.md is:
```markdown
# ChangeLog

## 0.0.1
- [feat] Add `hello()`.
- [feat] Add `world()`. It is actually `xx::world()`.
- [docs] Generate doxygen html website.
```

**Expected behavior**

**I expect `world()` also clickable**. i.e. without namespace explicitly specified, match the same name function that found in `hello.h` file.

**Screenshots**

`world()` not clickable in doxygen 1.9.8:
![image](https://github.com/doxygen/doxygen/assets/3831847/c6a9ee9f-54b0-47ed-a9aa-158777a39647)

`world()` clickable in doxygen 1.9.3:
![image](https://github.com/doxygen/doxygen/assets/3831847/958bfa7e-3a2c-4de8-b32d-57f616ae4b89)

`world()` not clickable in doxygen 1.9.5:
![image](https://github.com/doxygen/doxygen/assets/3831847/5bf043b3-3a06-4ab5-9703-0d1e663daa00)

**To Reproduce**

This [y.zip](https://github.com/doxygen/doxygen/files/11600618/y.zip) contains required files:
- Generate `Doxyfile` by running `python generate_doxyfile.py`
- Then call `doxyfile` to generate html directory
- Then serve it via http server ``cd html && python -m http.server 9090`

**Version**
- doxygen: 1.9.8 (dfb85424bc073675c49f815d03fdbd7032cb9eb9*)
- System: Ubuntu 22.04

**Stack trace**
If you encounter a crash and can build doxygen from sources yourself with debug info (`-DCMAKE_BUILD_TYPE=Debug`), a stack trace can be very helpful (especially if it is not possible to capture the problem in a small example that can be shared).

**Additional context**

**Comment by albert-github** [comment]
Actually I think the output of version 1.9.3 was not correct (but  it was convenient).
The function `world` is part of the namespace `xx` and the changelog does not know anything about the namespace, so the function `world` is not in its scope.
In the recent versions the linking rules lave been tightened a bit.

So I think the problem is usage.

**Comment by zchrissirhcz** [comment]
> In the recent versions the linking rules lave been tightened a bit.

Is there any configuration option that I can use, to keep same output as 1.9.3? There is a long changelog.md in my actual project, most of mentioned functions in the changelog.md is not prefixed with `xx::` (the namespace), and I think already released changelog.md should not be modified, and hyperlinked functions are still required.

**Comment by zchrissirhcz** [comment]
By using `git bisect`, I find the first commit that cause this "non-hyperlink" change:
```
b290399fab92df45376103d7c094f053f24495fa is the first bad commit
commit b290399fab92df45376103d7c094f053f24495fa
Author: Dimitri van Heesch <doxygen@gmail.com>
Date:   Tue May 24 08:12:07 2022 +0200

    Refactoring: reimplement getDefs using symbol resolver

 src/classdef.cpp       |  44 ++--
 src/classdef.h         |   6 +-
 src/code.l             |   2 +-
 src/definition.cpp     |   1 +
 src/doxygen.cpp        |  40 ++--
 src/doxygen.h          |   9 +-
 src/symbolresolver.cpp | 568 +++++++++++++++++++++++++++++++++++++++++++------
 src/symbolresolver.h   |  11 +
 src/util.cpp           | 173 +++++++++++++--
 src/vhdldocgen.cpp     |  12 +-
 10 files changed, 741 insertions(+), 125 deletions(-)
```

**Comment by zchrissirhcz** [comment]
There is `getDefs()` and `getDefsOld()` in `src/util.cpp`, and `getDefs()` actually keeps an "dead code":
https://github.com/doxygen/doxygen/blob/cf818b6b68f247b40bafa74cdff15db3ee283c1e/src/util.cpp#L2706C6-L2734

I can temporarily change it to `if (true)` thus using `getDefsOld()` result, i.e. make my markdown files `world()` function with hyperlinks.

@doxygen I wonder is there any plan to make this an configuration option? e.g. `AUTOLINK_SYMBOLS_GLOBALLY`:
- default to `NO`, to keep same output as current doxygen version
- set to `YES`, to call `getDefsOld()` and make functions like `world()` with hyperlinks

**Comment by albert-github** [comment]
Which `world` should be taken when there are 2 namespaces (say `xx` and `yy`) with a function `world`?

**Comment by zchrissirhcz** [comment]
> Which `world` should be taken when there are 2 namespaces (say `xx` and `yy`) with a function `world`?

I think none should be taken, just let it be plain text.

**Comment by albert-github** [comment]
Indeed in that case there is no unique `world`, but at that moment it would be a bit inconsistent (in my opinion) that when there is one namespace that `world` is linked when not the full name is used.
Note one can always use `\ref xx:world() "wold()"`.

**Comment by zchrissirhcz** [comment]
> Note one can always use \ref xx:world() "wold()".

`\ref xx:world() "world()"` is OK for single function. Actually the project that I maintained has many functions, I prefer specify `xx` (the namespace) as candidate prefix when search symbols.

**Comment by doxygen** [comment]
The old routine indeed has problems creating the wrong references, so it has been replaced. 
I do not plan to make the old routine available anymore.

A way around it, is to place the comment inside a namespace, like so

```.cpp
namespace xx
{

/** @page changelog Changelog

# ChangeLog

## 0.0.1
- [feat] Add `hello()`.
- [feat] Add `world()`. It is actually `xx::world()`.
- [docs] Generate doxygen html website.

*/

}
```

Unfortunately, there is no way at the moment to make a Markdown page part of a namespace.
Adding a command to set/change the scope might be a better solution.

**Comment by zchrissirhcz** [comment]
Thank you for explanation and providing this workaroud.

To integrate with CMake build of my C++ project, the pasted snippet(say, name it as `changelog.h`) can be generated via Python script (`generate_changelog_header.py`), which is the method that I prefer. Hope this may help people with similar requirements:

```python
class CodeWriter(object):
    def __init__(self, indent_len):
        self.lines = []
        self.indent_num = 0
        self.indent_len = indent_len

    def write(self, content):
        padding = (self.indent_len * self.indent_num) * ' '
        line = padding + content
        self.lines.append(line)

    def save(self, filename):
        with open(filename, 'w') as fout:
            for line in self.lines:
                fout.write(line + "\n")

    def tab(self):
        self.indent_num += 1

    def backspace(self):
        if (self.indent_num > 0):
            self.indent_num -= 1

if __name__ == '__main__':
    w = CodeWriter(4)

    # write header
    w.write('namespace xx')
    w.write('{')
    w.write('')
    w.write('/** @page changelog Changelog')

    fin = open('CHANGELOG.md')
    for line in fin.readlines():
        w.write(line)
    fin.close()

    # write footer
    w.write('*/')
    w.write('')
    w.write('}')

    w.save('changelog.h')

```

Then, put the generated `changelog.h` in `INPUT` option in Doxyfile, and people may integrate calling `generate_changelog_header.py` within CMakeLists.txt.
