### ISSUE TITLE
markdown file: explicit link request to 'include' could not be resolved

### ISSUE THREAD

**Issue by zchrissirhcz** [doxygen/doxygen#10100]
**Describe the bug**

I use one markdown file to include another markdown file, expect `#include xxx` being processed correctly by C preprocessor. It works on Linux, but on Windows, the Visual Studio's cl.exe not working.

**Expected behavior**
Describe what you would have expected or think is correct.

I expect in the generated html page, the `#include xxx` part is replaced the the contents of the file `xxx`.

**Screenshots**
The actual (taken from Windows, from `a.zip`):
![image](https://github.com/doxygen/doxygen/assets/3831847/92226952-1e20-487e-ada5-06bd20fd2a84)

The expected (taken from Linux, from a minor modified Doxyfile of `a.zip`):
![image](https://github.com/doxygen/doxygen/assets/3831847/6099da95-3cc7-4c05-bee1-b52f5643a62a)

**To Reproduce**

For Windows reproduce, use this zip file: [a.zip](https://github.com/doxygen/doxygen/files/11593295/a.zip)
 to reproduce, it generates required `Doxyfile` which requires full path of where your extract it.

You also have to manually change `cpp.cmd` file with your cl.exe path.

After unzipping:
```batch
python generate_doxyfile.py
doxygen
# edit cpp.cmd
cd html
python -m http.server 9090
```

For Linux reproduce, remove quotes for files in `Doxyfile` then call `doxygen`, i.e.:
```ini
PROJECT_NAME = "x"
GENERATE_TREEVIEW = YES
GENERATE_HTML = YES
GENERATE_LATEX = NO

EXTRACT_ALL = YES
EXTRACT_STATIC = YES

INPUT = hello.h \
        /home/zz/work/dbg/a/docs/root.md \
        /home/zz/work/dbg/a/docs/changelog.md
FILTER_PATTERNS = /home/zz/work/dbg/a/docs/changelog.md="cpp -P "
```

**Version**

- doxygen 1.9.8
- Windows 10
- Visual Studio 2022
 

**Stack trace**
If you encounter a crash and can build doxygen from sources yourself with debug info (`-DCMAKE_BUILD_TYPE=Debug`), a stack trace can be very helpful (especially if it is not possible to capture the problem in a small example that can be shared).

**Additional context**

**Comment by zchrissirhcz** [comment]
Solved by the following steps:
1. Remove quotes around file paths in `Doxyfile`
2. Implement an alternative of `cpp` command (the C Pre-Processor) with Python
    - python is cross-platform
    - only `#include` directive is required for my markdown files, thus the implementation is simple
 
Doxyfile:
```doxyfile
INPUT = hello.h \
        D:/dbg/a/docs/root.md \
        D:/dbg/a/docs/changelog.md
FILTER_PATTERNS = D:/dbg/a/docs/changelog.md="python D:/dbg/a/sledcpp.py "
```

And the content of `sledcpp.py` script is:
```python
import sys
import os

def getLinesOfTextFile(filepath):
    lines = []
    with open(filepath, encoding='utf-8') as fin:
        for line in fin.readlines():
            lines.append(line.strip())
    return lines


def expand_file_once(filepath):
    fileDir = os.path.dirname(filepath)
    with open(filepath) as fin:
        for line in fin.readlines():
            line = line.strip()
            if line.startswith('#include'):
                startPos = len('#include')
                depfile = line[startPos:].strip().split('"')[1]
                deppath = os.path.join(fileDir, depfile)
                deplines = getLinesOfTextFile(deppath)
                for item in deplines:
                    print(item)
            else:
                print(line)


if __name__ == '__main__':
    if len(sys.argv) != 2:
        print('Usage: python {:s} filepath'.format(sys.argv[0]))
        exit(1)
    
    filepath = sys.argv[1]
    expand_file_once(filepath)
```

**Comment by zchrissirhcz** [comment]
I'll try your suggested `\include{doc}` and `\snippet{doc}`. I didn't know those commands well and previously use a Linux machine for daily develop, and `cpp -P` was enough until recently 90% time on Windows machine.

**Comment by albert-github** [comment]
I would have thought the `\include{doc}` would have worked , but I did some quick tests and couldn't get it to work either.
Maybe I should dive into it a bit deeper.

**Comment by zchrissirhcz** [comment]
The `\include {doc}` actually helps me refactor my old docs, several `#include xxx` files now replace by `\include {doc}`.

The `\include {doc}` now does not support highlight for `CMake`. I don't know much about how hightlight implemented in doxygen. If they are not implemented in C++, e.g. in Python, I think it would be fast to add basic support.

**Comment by albert-github** [comment]
Highlighting is not trivial for languages that are not directly supported by doxygen as there are no `...code.l` (wwhere the highlighting is done) for it.

**Comment by zchrissirhcz** [comment]
> Highlighting is not trivial for languages that are not directly supported by doxygen as there are no `...code.l` (wwhere the highlighting is done) for it.

OK,  I didn't know it is not trivial. Since I only have one simple CMake file for highlight, I can just ignore it, let it be plain text like.

**Comment by albert-github** [comment]
I looked a bit deeper and the problem comes from the fact that the `\include{doc}` part contains a section.
The section commands are not directly mentioned in the documentation, but due to de order of processing I think these are not shown either.

@doxygen 
- would this me a useful enhancement
- do you see possibilities how to implement this
- should I create a new issue for it?


A small example: [example.tar.gz](https://github.com/doxygen/doxygen/files/11600815/example.tar.gz)
