### ISSUE TITLE
Brief description in modules not available

### ISSUE THREAD

**Issue by MKHen** [doxygen/doxygen#10103]
**Describe the bug**
If I use the code from https://www.doxygen.nl/manual/grouping.html (The one starting with /** @defgroup group1) I am not able to see the brief output e.g. This is the first group ...

**Expected behavior**
I expected to see the brief description as shown in https://www.doxygen.nl/manual/examples/group/html/modules.html

**Screenshots**
The expected
![image](https://github.com/doxygen/doxygen/assets/84001275/a807db56-81f6-4836-8472-5c3f3c643a52)
My one:
![image](https://github.com/doxygen/doxygen/assets/84001275/f1370ebc-1da8-4401-ab73-bcae14212da8)

**To Reproduce**
Just copy the example from the homepage to a file and launch Doxygen Wizard with the default config.

**Version**
V1.9.7 Windows

**Comment by albert-github** [comment]
The example as defined uses the setting `JAVADOC_AUTOBRIEF = YES` i.e. (from the documentation: https://www.doxygen.nl/manual/config.html#cfg_javadoc_autobrief):
> If the JAVADOC_AUTOBRIEF tag is set to YES then doxygen will interpret the first line (until the first dot) of a Javadoc-style comment as the brief description. If set to NO, the Javadoc-style will behave just like regular Qt-style comments (thus requiring an explicit [@brief](file:///D:/Program%20Files/doxygen/html/commands.html#cmdbrief) command for a brief description.)

**Comment by MKHen** [comment]
I see.
User error.
