### ISSUE TITLE
warning: end of comment block while expecting command is raised

### ISSUE THREAD

**Issue by MKHen** [doxygen/doxygen#10111]
**Describe the bug**
**warning: end of comment block while expecting command** is raised

**Expected behavior**
There should be no warning I think.

**Screenshots**
Sorry, none available.

**To Reproduce**
Just run Doxygen V1.9.7 with a file (main.h) and the following content. Don't forget to set a logfile.
```
/** @file
 *  @copyright XYZ
 *
 *  @brief This file is used as doxygen main page. It holds some general documentation
 *   content.
 */

// Set the content of the mainpage of Doxygen
/*!
 *  @mainpage Overview
 *
 *  @section Prerequisites Prerequisites
 *  - See <a href="group___prerequisites.html">Prerequisites</a> page to get an overview
 *   of needed conditions for the different modules.
 *
 *
 */

// Create the different modules

/** @defgroup group1 group1
 *  @ingroup group0
 *  @brief Just group1
 *  @li <b>Please refer to https://xyz.com as well.
 */
 
 /** @defgroup group2 group2
 *  @ingroup group0
 *  @brief Just group2
 *  @li <b>Please refer to https://abc.com as well.
 */

#pragma once
```

**Version**
V1.9.7 on Windows 10
**Stack trace**
If you encounter a crash and can build doxygen from sources yourself with debug info (`-DCMAKE_BUILD_TYPE=Debug`), a stack trace can be very helpful (especially if it is not possible to capture the problem in a small example that can be shared).

**Additional context**

**Comment by albert-github** [comment]
When I run the given example I get the warnings:
```
main.h:24: warning: end of comment block while expecting command </b>
main.h:30: warning: end of comment block while expecting command </b>
```
and on line 24 I see:
```
<b>Please refer to https://xyz.com as well.
```
but I don't see any `</b>`.  So it looks like thes `</b>` are missing.

I don't get `warning: end of comment block while expecting command` but probably your viewer doesn't show `</b>` / removes  it in the shown output.

I think the problem is usage.

**Comment by MKHen** [comment]
For sure. A user error.

**Comment by MKHen** [comment]
For sure. A user error.
