### ISSUE TITLE
Grouping of snippets doesn't hyperlink

### ISSUE THREAD

**Issue by forcel0** [doxygen/doxygen#10148]
**Describe the bug**
Class members don't seem to hyperlink when building up Doxygen pages with Groups and Snippets.

**Expected behavior**
I would assume page would generate with the hyperlinks and then be separated into the groups. If you look at the page built up with groups it's missing the local hyperlinks
Class Test->APIs->Bar->Sample Apps->C#->Foo Sample
![image](https://github.com/doxygen/doxygen/assets/42810251/2bb50ff6-8233-478d-9930-e9d8f0511698)
Where as the page created from examples has the links. 
Class Test->Examples-foo.cs
![image](https://github.com/doxygen/doxygen/assets/42810251/c0ce53e8-c799-4e67-8656-200c41ad20ec)
If I include the namespace in the first snippet group the local hyperlinks will work but I don't see a way to add the namespace to each subsequent snippet in the group. If there is a different way I should build up the document please advise.

**To Reproduce**
[Foo.zip](https://github.com/doxygen/doxygen/files/11860470/Foo.zip)

**Version**
1.9.8

**Comment by forcel0** [comment]
Still haven't figured out a way to get the snippets to use parsed and hyperlink documentation. Is there a way to force the snippets to generate after the html has been generated? Or is there a way to specify where snippets should point to for the code?

Thanks

**Comment by albert-github** [comment]
Doxygen considers a snippet as a separate standalone piece of code and tries to the best of the local knowledge to place a.o. hyperlinks.
When looking at `locallink.IWantALinkHere();` the name `IWantALinkHere` is from the "usage of Bar" but "Bar" is not included,
adding
```
using System;
using Bar;
```
inside the snippet `[FooCsSampleMain]` so that we get:
```
class Test : ChildClass
{
  /// @[FooCsSampleMain]
using System;
using Bar;
  static void Main()
  {
...
```
looks like to solve the issue.

**Comment by forcel0** [comment]
Hmm. Not sure how to do this. Moving the using statements inside the class would not allow the C# code to compile. On the example (foo.zip) using Bar; is included  towards the top of the C# code. The full C# example code parses as expected but the snippet doesn't seem to pickup the using Bar; statement. I thought the snippets used to parse under an older version but we might have had other changes.  I'll go back and test older versions against the included sample and report the results.
Thanks!

**Comment by albert-github** [comment]
It is all about how important the links for you are.
You could always pace a guard around it, like
```
#if DOXYGEN
using System;
using Bar;
#endif
```

at least when this is allowed in C#.
And don't forget to place `DOXYGEN` in the `PREDEFIEND` settings

**Comment by albert-github** [comment]
In C++ a lot of compilers support the non-standard `#pragma once` for include files (I never use(d) it), maybe there is something similar in C# that can be helpful here.

**Comment by forcel0** [comment]
Thanks. I think we’ll re-work our sample / test code to match the snippet size so Doxygen will parse them as they are as standalone. This should guarantee that the will match any future Doxygen releases.Thanks! On Aug 17, 2023, at 6:02 AM, albert-github ***@***.***> wrote:﻿
In C++ a lot of compilers support the non-standard #pragma once for include files (I never use(d) it), maybe there is something similar in C# that can be helpful here.
