### ISSUE TITLE
HTML does not work in @section (Origin: bugzilla #135808)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1014]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.3.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2004-03-01 02:56:28 +0000, jody@atdesk.com wrote:

    The following code:
    
    @section foo The n<sup>th</sup> Requirement
    
    leaves the HTML commands in the text, and the superscript is not 
    generated.

**Comment by albert-github** [comment]
I think this problem is related to the (new) problem: "Markdown: Links in ATX headings processed incorrectly?" #6998 and "html output from markdown: cannot use formatted text in section titles" 
#7135
