### ISSUE TITLE
Inheritance

### ISSUE THREAD

**Issue by forcel0** [doxygen/doxygen#10143]
**Describe the bug**
We have a C++ library that gets compiled for use with C++ and C# applications.  The example for C++ calls the library directly and works as expected. The C# example is run through automated tests as it calls the C++ call so we use inheritance to setup the frame work and test. We then use Doxygen snippets to pull this code but the inherited methods don't seem to hyperlink though it could absolutely be user error

**Expected behavior**
I would expect Doxygen to link IWantALinkHere(); in the C# example as it does in the C++ example even though the C# is through inhertance.

**Screenshots**
![image](https://github.com/doxygen/doxygen/assets/42810251/1a5f145d-7da6-458e-a93f-2588e64634c9)
![image](https://github.com/doxygen/doxygen/assets/42810251/651aa90b-cb8f-4f53-aa5a-02f6873b6886)

**To Reproduce**
[foo.zip](https://github.com/doxygen/doxygen/files/11806342/foo.zip)

**Version**
1.9.7

**Comment by doxygen** [comment]
@forcel0 Can you verify if the referenced commit fixes the problem for you? Please do not close the issue, this will be done automatically when the next official release is out.

**Comment by forcel0** [comment]
The referenced commit fixes the inheritance issue described in #10143. It uncovered a different issue submitted under [#10148 ](https://github.com/doxygen/doxygen/issues/10148). As it is a different issue and might just be improper usage.

Thanks.

**Comment by albert-github** [comment]
As the fix is not yet part of on official release, please don't close the issue as this will be done at the moment of an official release

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.8.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
