### ISSUE TITLE
Documentation for enum via the @enum command is missed if the @ingroup command is also used

### ISSUE THREAD

**Issue by oblivioncth** [doxygen/doxygen#10151]
**Describe the bug**
Trying to place an enum in a group via the `@ingroup` command results in the documentation for said enum being completely missed by Doxygen if the enum was documented via the `@enum` command.
```
foo.cpp:6: warning: Documentation for undefined enum 'MyEnum' found.
...

foo.h:6: warning: Member MyEnum (enumeration) of namespace NS is not documented.
```

**Expected behavior**
Enums can be placed in a group regardless of how they're documented.

**Screenshots**
N/A

**To Reproduce**
Check MRE.
[Enum in Group MRE.zip](https://github.com/doxygen/doxygen/files/11876752/Enum.in.Group.MRE.zip)

**Version**
Latest stable.
1.9.7 (a2f34e1ed90f83713dc347b5134920f32c455d46)
Windows x64

**Additional context**
The namespace in the MRE is not required to produce the bug, but was included since only a warning is fired without it.

The MRE is correctly processed in  versions <= 1.9.6.

**Comment by oblivioncth** [comment]
Had a moment to delve a little deeper.

Bisect shows the issue was introduced with bd99649d9d2d15cb3c1c7b53167365b79a6aaa5b.

**Comment by albert-github** [comment]
Maybe @sebhub can shine a light on it (as he was the author of the patch providing apparent the problem)

**Comment by sebhub** [comment]
Thanks for the notification. I will have a look at this after my summer holidays in late September.
