### ISSUE TITLE
Why it takes so long to complete "Add enum values to enums..."

### ISSUE THREAD

**Issue by NimmiW** [doxygen/doxygen#10154]
This is not a bug. I am just asking a question.

My project have thousands of files. I just need to create a call graph. I am not interested in enums. How to bypass this enum step?

**Comment by albert-github** [comment]
What is long? How much time does the step take? (one can see the later wit `doxygen -d time` when running).
Simple bypassing the enums is not possible (maybe when you use `EXCLUDE_SYMBOLS` with a list of all enums. Another way would be that they might be ignored when they are not documented).

Furthermore to be able to say something sensible:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.
- Please also specify the **full** doxygen version used (`doxygen -v`).

**Comment by albert-github** [comment]
No response in respect to the comment, setting issue to `invalid` (not complete)
