### ISSUE TITLE
Dynamic call relationships cannot be extracted

### ISSUE THREAD

**Issue by julian5392** [doxygen/doxygen#10152]
Parse_opt is a parser for command-line arguments. It is taken as part of the struct 'argp' as an argument to the command line parsing function argp_parser. Doxygen doesn't seem to be able to extract this dynamic call relationship
```
static error_t parse_opt (int key, char *arg, struct argp_state *state)
static struct argp argp = {
     options,
     parse_opt,
     N_("[FILE]..."),
     doc,
     NULL,
     NULL,
     NULL
};
argp_parse(&argp, argc, argv, ARGP_IN_ORDER, &index, NULL)
```

**Comment by albert-github** [comment]
To be able to see what might be the case:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.
- Please also specify the **full** doxygen version used (`doxygen -v`).

**Comment by julian5392** [comment]
[testcase.zip](https://github.com/doxygen/doxygen/files/11880256/testcase.zip)
The parse_opt and struct argp declare in \testcase\cflow-master\src\main.c.
The argp_parse declares in \testcase\cflow-master\gnu\argp.h
version="1.9.6"

**Comment by albert-github** [comment]
When I see the Doxyfile is see:
- problems are in the XML output?
- in the `EXCLUDE` setting the directory `gnu` is excluded, it this on purpose?
- did you also look at the HTML output (just to check and maybe indicate better where you have problems).

**Comment by julian5392** [comment]
- yes, the XML output lacks the corresponding call information, parse_opt should be called by the argp_parse
- Sorry, that was my misoperation in subsequent use, and GNU does not need to be exclueded
- I have checked the call graph on HTML output, This dynamic call is also not extracted

**Comment by albert-github** [comment]
OK I see I think the problem is a known issue, doxygen is not good in detecting calls that go through pointers (and pointers to structures with function calls)

**Comment by doxygen** [comment]
In the example, it cannot be derived that parse_opt is actually called, only that is might be called. It depends on the implementation of argp_parse. Doxygen will not evaluate runtime behavior (and in this case the implementation of argp_parse is not even part of project).
