### ISSUE TITLE
Legend and actual graphs are different: 

### ISSUE THREAD

**Issue by makelinux** [doxygen/doxygen#10174]
Actual:

![image](https://github.com/doxygen/doxygen/assets/2335185/d3b70d22-8349-4934-b95c-b38c477578aa)

Legend:
![image](https://github.com/doxygen/doxygen/assets/2335185/7493e696-1cd1-4595-9d44-6360378b97be)

**To Reproduce**

Create doxygen for the legend example.

**Comment by albert-github** [comment]
The "Legend" is made for documentation purposes and shows the possibilities. The source code as presented cannot be simple transferred into the required graph, so some special code has been generated to create the legend graph(see: src/dotlegendgraph.cpp).

**Comment by doxygen** [comment]
The graph can actually be generated using these settings:
```
EXTRACT_PRIVATE        = YES
HTML_COLORSTYLE        = LIGHT
HAVE_DOT               = YES
TEMPLATE_RELATIONS     = YES
DOT_GRAPH_MAX_NODES    = 9
```
