### ISSUE TITLE
Restrict Keyword Renders C function unparsable.

### ISSUE THREAD

**Issue by acagliano** [doxygen/doxygen#10170]
Running Doxygen 1.9.7.

Attempting to document a modular exponentiation function within an expansion I am writing for a toolchain.
Function prototype looks like this:
`cryptx_hazmat_powmod(uint8_t size, uint8_t *restrict base, uint24_t exp, const uint8_t *restrict mod);`
Remove the *restrict* keyword and the error disappears.

Default Doxygen config file.
Using `sphinx-build -b html` and the line that triggers the error looks like this:
```
.. doxygenfunction:: powmod
	:project: CryptX
```

The error output looks like this:
```
/Users/acagliano/Repositories/toolchain/src/cryptx/docs/index.rst:333: WARNING: doxygenfunction: Unable to resolve function "cryptx_hazmat_powmod" with arguments "None".
Candidate function could not be parsed. Parsing error is
Error when parsing function declaration.
If the function has no return type:
  Error in declarator or parameters-and-qualifiers
  Invalid C++ declaration: Expected identifier in nested name, got keyword: void [error at 4]
    void cryptx_hazmat_powmod (uint8_t size, uint8_t *restrict base, uint24_t exp, const uint8_t *restrict mod)
    ----^
If the function has a return type:
  Error in declarator or parameters-and-qualifiers
  If pointer to member declarator:
    Invalid C++ declaration: Expected '::' in pointer to member (function). [error at 26]
      void cryptx_hazmat_powmod (uint8_t size, uint8_t *restrict base, uint24_t exp, const uint8_t *restrict mod)
      --------------------------^
  If declarator-id:
    Invalid C++ declaration: Expecting "," or ")" in parameters-and-qualifiers, got "b". [error at 59]
      void cryptx_hazmat_powmod (uint8_t size, uint8_t *restrict base, uint24_t exp, const uint8_t *restrict mod)
      -----------------------------------------------------------^
```

**Comment by albert-github** [comment]
Might indeed be that doxygen is confused by the `restrict`  keyword, to be able to debug it:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

**Comment by acagliano** [comment]
Here it is. 
To build, I just run the script `local-build.sh` which configures the python environment for sphinx, then runs the builder.
An interesting development while I was putting this together is that this issue occurs only in the `.. doxygenfunction` direction. `.. doxygenfile` does not exhibit the issue.

Let me know if more is needed.

[issue_demo.zip](https://github.com/doxygen/doxygen/files/11951509/issue_demo.zip)

**Comment by acagliano** [comment]
This may actually be an issue with Sphinx, not Doxygen.

**Comment by albert-github** [comment]
Indeed it looks like to be a Sphinx issue.

When looking in the resulting xml files )especially: xml/cryptx_8h.xml) I see:
```
<type>const uint8_t *restrict</type>
```

Also the error message does not look like a doxygen error message.

I think this is not a doxygen issue.

**Comment by acagliano** [comment]
Yea, it's Breathe. Apologies. I'll post it there then. Feel free to close.
