### ISSUE TITLE
The XML document generated by Doxygen does not conform to the format at all

### ISSUE THREAD

**Issue by julian5392** [doxygen/doxygen#10173]
**Describe the bug**
The XML document generated by Doxygen does not conform to the format at all. But on other files, the behavior is normal
**To Reproduce**
[testcase.zip](https://github.com/doxygen/doxygen/files/11966849/testcase.zip)

**Version**
doxygen 1.9.6

**Comment by albert-github** [comment]
What do you mean with "The XML document generated by Doxygen does not conform to the format at all.", where are the problems?

The intention of the XML output is an output for further processing by the user to an end user format, the formats like HTML / LaTeX / ... are end user formats.

**Comment by julian5392** [comment]
Its hard to describe it. After you run the testcase and check the xml output, you may know what I mean. I dont know why I can't upload the screen shots

**Comment by julian5392** [comment]
It doesn't matter.It's just that I can't not upload the image in question on github. I want to further process the xml document to extract the relevant information. However, the xml format generated by doxygen in this test case is problematic and cannot be parsed by the relevant Python packages.

**Comment by albert-github** [comment]
- Might it be that your sources are not UTF-8 encoded? Maybe you need another encoding like `INPUT_ENCODING = GB2312`, see the setting `INPUT_ENCODING`
- What kind of errors do you get from the python packages?

**Comment by julian5392** [comment]
- XML documents are opened in Internet Explorer in the wrong format, but open in Notepad is fine. That might be encoding problem.

- The python error report：

xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 660, column 55

**Comment by albert-github** [comment]
Did you try the setting `INPUT_ENCODING=GB2312`?
(Before using this setting I saw similar with `xsltproc combine.xslt index.xml >all.xml`)

**Comment by julian5392** [comment]
Thank you, this worked.
Can I keep this encoding option directly, or depending on the source program

**Comment by albert-github** [comment]
The setting is of course depending on the source code you feed into doxygen.
