### ISSUE TITLE
Toggle button to switch between DARK and LIGHT mode

### ISSUE THREAD

**Issue by couet** [doxygen/doxygen#10177]
In `Doxyfile` version 1.9.8 I see:

```
# The HTML_COLORSTYLE tag can be used to specify if the generated HTML output
# should be rendered with a dark or light theme.
# Possible values are: LIGHT always generate light mode output, DARK always
# generate dark mode output, AUTO_LIGHT automatically set the mode according to
# the user preference, use light mode if no preference is set (the default),
# AUTO_DARK automatically set the mode according to the user preference, use
# dark mode if no preference is set and TOGGLE allow to user to switch between
# light and dark mode via a button.
# The default value is: AUTO_LIGHT.
# This tag requires that the tag GENERATE_HTML is set to YES.

HTML_COLORSTYLE        = TOGGLE
```

I tried to set this flag to `DARK`. It works fine. Then I tried `TOGGLE` (as shown above). But I do not see any button to switch between `DARK` and `LIGHT` mode. Where is supposed to be this button ? Did I miss something ?

**Comment by albert-github** [comment]
The doxygen version 1.9.8 (i.e. current master) is a moving target therefore it is necessary to show the full identification version used.

There should be at the top right be a "sun" button like:
![image](https://github.com/doxygen/doxygen/assets/5223533/39bcf54b-858b-4989-91be-292b92fcb12f)

I'm not sure (anymore) whether or not you changed in the layout (and maybe not updated to the newest version) so the "sun" might have dropped off.

In the current master version (1.9.8 (1a2c2b1fbe6f2dc9cf0b6a16cafaa5600b6185a8)) it should also be possible to switch by means of the `ESC`-key

**Comment by couet** [comment]
```
% doxygen --version
1.9.8 (0ea6a2376f93d1bde432429f58666884e018a07a)
```

I do not have this "sun" button near the search field:

<img width="1033" alt="Screenshot 2023-07-07 at 13 04 14" src="https://github.com/doxygen/doxygen/assets/4697738/7f956b9d-ed87-497d-ae0c-93554ab50697">

**Comment by albert-github** [comment]
- regarding the `ESC`-key, the executable you use (from May 23, 2023 version) does not contain this feature yest (introduced June 7, 2023, integrated June 11, 2023).
- regarding the missing "sun" this might be due to the fact that you use your own layout / css / header files and that these are not up to date.

**Comment by couet** [comment]
Ok. I’ll try a newer version. what should I do to « update these files » ?Le 7 juil. 2023 à 13:23, albert-github ***@***.***> a écrit :﻿

regarding the ESC-key, the executable you use (from May 23, 2023 version) does not contain this feature yest (introduced June 7, 2023, integrated June 11, 2023).
regarding the missing "sun" this might be due to the fact that you use your own layout / css / header files and that these are not up to date.

**Comment by albert-github** [comment]
- first we have to see which `Doxyfile` you use, probably `./documentation/doxygen/Doxyfile`
  Here we see that you use (a.o.)
  - `LAYOUT_FILE            = DoxygenLayout.xml`
  - `HTML_HEADER            = htmlheader.html`
  - `HTML_FOOTER            = htmlfooter.html`
  - `HTML_EXTRA_STYLESHEET  = ROOT.css`

So these files (except probably for the `Root.css` as this file is dedicated to the project) have to be compared with the current versions (`doxygen -w html headerFile footerFile styleSheetFile` and `doxygen -l [layoutFileName]`) and adjusted where necessary.

**Comment by couet** [comment]
It works. Thanks.
