### ISSUE TITLE
Numbered lists are not always rendered correctly

### ISSUE THREAD

**Issue by macawkitty** [doxygen/doxygen#10176]
**Describe the bug**
Numbered lists are not always rendered correctly. Something like this:
```
-# Lorem ipsum
   - dolor sit amet, consectetur adipiscing elit
   - sed do eiusmod tempor incididunt ut
   - labore et dolore magna aliqua
-# Ut enim ad minim veniam
-# quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat
```
is getting rendered as:
1. Lorem ipsum
   - dolor sit amet, consectetur adipiscing elit - sed do eiusmod tempor incididunt ut -labore et dolore magna aliqua -#Ut enim ad minim veniam -#quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat

**Version**
Windows 10 64 bit- 1.9.7

**Additional context**
This problem is not always happening. Also, it wasn't happening at all with version 1.9.1, the content was getting rendered correctly then.

**Comment by albert-github** [comment]
I tried to reproduce the issue but was not able to do this based on the information provided, probably a more extensive example is needed.

The result I got was:
![image](https://github.com/doxygen/doxygen/assets/5223533/02f37513-2f08-4112-b550-9315567529c9)

Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/11979482/example.tar.gz)


- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.
