### ISSUE TITLE
Angular brackets in backticks not rendering correctly

### ISSUE THREAD

**Issue by macawkitty** [doxygen/doxygen#10175]
**Describe the bug**
Angular brackets in backticks not rendering correctly. Something like this:
````Lorem ipsum `<dolor sit amet consectetur adipiscing elit, sed do eiusmod tempor` incididunt ut labore et dolore magna````
is being rendered as:
````Lorem ipsum `<dolor sit amet consectetur adipiscing elit, sed do eiusmod tempor</tt> incididunt ut labore et dolore magna````

Any subsequent backticks get rendered as `<tt>`. Also getting this error - Opening and ending tag mismatch

**Version**
Windows 10 64 bit- 1.9.7

**Additional context**
This problem is not always happening. Also, it wasn't happening at all with version 1.9.1, the content was getting rendered correctly then.

**Comment by albert-github** [comment]
I tried to reproduce the issue but was not able to do this based on the information provided, probably a more extensive example is needed.

The result I got was:
![image](https://github.com/doxygen/doxygen/assets/5223533/a50f4ddb-8cd4-42f0-bab9-4455cf0fa2b8)

Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/11979254/example.tar.gz)

So:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.
