### ISSUE TITLE
Fields do not appear to be "referenced" and "Referencedby" [Methods Are]

### ISSUE THREAD

**Issue by davidcorbin-atmosera** [doxygen/doxygen#10206]
**Describe the bug**
Field (data members) "References and ReferencedBy" does not seem to be working

**Expected behavior**
I would expect the information to show same as methods accessing other methods

**Screenshots**
If useful, add screenshots to help explain your problem.

**To Reproduce**
```
class SimpleNativeClass;
class SimpleClassMethodAccessingFields
{
public:
	void MethodReferencingOurOwnFields()
	{
		m_PointerToSimpleNativeClassField = nullptr;
		m_PointerToConstSimpleNativeClassField = nullptr;
	}

	 SimpleNativeClass* m_PointerToSimpleNativeClassField;
	 SimpleNativeClass const* m_PointerToConstSimpleNativeClassField;

};
```
**Version**
```
-v = 1.9.7 (a2f34e1ed90f83713dc347b5134920f32c455d46)  
```

**Stack trace**
N/A
**Additional context**
I believe all configuration is correct because method calls do seem to have the "References" and "ReferenceBy" elements.

**Comment by albert-github** [comment]
You wrote:
> I believe all configuration is correct because method calls do seem to have the "References" and "ReferenceBy" elements.

Which configuration?
- Please provide the content of the doxygen settings file that differ from the default settings (`doxygen -x Doxyfile`)

Regarding the example, its is preferred to supply this as: 
- a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

And also please learn about the markdown layout and especially about the difference between a single backtick (`` ` ``) and a triple backtick (` ``` `)

**Comment by albert-github** [comment]
I ran your example and I see that the call and caller graphs are present.
I think you refer to the fact that the fields don't show here, which is logical and it are call / caller graphs.
I think that the information you are after for the fields (beside the call information) is given with:
```
REFERENCED_BY_RELATION = YES
REFERENCES_RELATION    = YES
```

**Comment by davidcorbin-atmosera** [comment]
That appears to do the trick... Thanks... marking as closed.
