### ISSUE TITLE
Enable Regex for `PREDEFINED`

### ISSUE THREAD

**Issue by viveksood97** [doxygen/doxygen#10207]
**Describe the bug**
I am unable to use regex for `PREDEFINED`

**Expected behavior**
This should Ideally work

`PREDEFINED+= "*_LOCAL"`

**Screenshots**
If useful, add screenshots to help explain your problem.

**To Reproduce**
`PROJECT_NAME_PUBLIC std::string generate_msg();`

**Version**
`-v = 1.9.1`

**Stack trace**
N/A

**Additional context**
I have a large project with various visibility macros and I don't want to add all `PREDEFINED`'s manually.  If I don't add those I get errors

**Comment by viveksood97** [comment]
@albert-github Thanks for your response.

- Changing `PREDEFINED` was an accident. I am changing it back to `PREDEFINED`
- I will try the INPUT_FILTER setting and report back
- I am currently using version 1.9.1 as that is the what apt installs. I dont want to build from source as my project is containerized and it takes a long time to build

**Comment by albert-github** [comment]
- I am not very familiar with INPUT_FILTER setting. As far as I know It ignores lines from code.
  - The INPUT_FILTER can do whatever with the source code  that is required. (I'm e.g. aware of a filter that tries to change Perl code into c++ code so it can be documented, it moves lines, changes lines, remove lines etc.)
  
- Is there no way to document visibility macros in doxygen v1.9.1?
  - not sure what you mean, where would you line to see them
  - you can always do a `grep "#define"` on your sources
- version obtained by "apt"
  - "apt" should make a newer version available, but some distributions do lack a bit
  - for the issue at hand the 1.9.1 version would do

**Comment by viveksood97** [comment]
- Understood
- I meant that if I use input filter it will remove `EXAMPLE_PKG_PUBLIC` from `EXAMPLE_PKG_PUBLIC std::string generate_msg ()` and I dont want to do that.
![image](https://github.com/doxygen/doxygen/assets/48154838/154c720a-7927-4670-bccb-345d3842fc5a)
- Secondly I wrote an input filter script that should remove `EXAMPLE_PKG_PUBLIC`. But the Doxyfile cant find it. The scripts sits in the same directory as the Doxyfile.

**Comment by albert-github** [comment]
- Secondly I wrote an input filter script that should remove EXAMPLE_PKG_PUBLIC. But the Doxyfile cant find it. The scripts sits in the same directory as the Doxyfile.

it is always a bit tricky when using FILTERS as it will start a pipe from the place where doxygen is started and maybe this is another place than where the Doxyfile resides. It might be useful to start doxygen like `doxygen -d extcmd Doxyfile` so you can see what doxygen will start in respect to external commands.

- version of doxygen used, Ubuntu apparently lags a bit with newer doxygen version on a bit older Ubuntu version, but still supported version. You can always use the release of doxygen (see https://www.doxygen.nl/download.html or https://github.com/doxygen/doxygen/releases/tag/Release_1_9_7). An alternative is to use a GitHub Actions build artifact (but this is of course a moving target and after a little while the "older" artifacts will be removed).

**Comment by viveksood97** [comment]
I'll create a new issue for the INPUT_FILTER. But If I give the full path it does find the script but the docs are empty. 

`Preprocessing /home/vsood-dev/module/src/sample_pkg/include/sample_pkg/sample_pkg.hpp...
Executing popen(/home/vsood-dev/module/docs/input_filter.py "/home/vsood-dev/module/src/sample_pkg/include/sample_pkg/sample_pkg.hpp")`

**Comment by viveksood97** [comment]
No solution for this right @albert-github ?

I meant that if I use input filter it will remove EXAMPLE_PKG_PUBLIC from EXAMPLE_PKG_PUBLIC std::string generate_msg () and I dont want to do that.
![image](https://github.com/doxygen/doxygen/assets/48154838/154c720a-7927-4670-bccb-345d3842fc5a)
