### ISSUE TITLE
Include guards that use #if !defined() not recognized (Origin: bugzilla #136157)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1020]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.3-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2004-03-04 08:59:52 +0000, tim.vanholder@anubex.com wrote:

    It seems that doxygen is smart enough to realize that in
    
      #ifndef FOO
      #define FOO
    
      ....
    
      #endif
    
    FOO is an include guard, and not a real #define.  Accordingly, FOO is not
    placed in the documentation.
    Unfortunately, it fails to apply the same handling to:
    
      #if !defined(FOO)
      #define FOO
    
      ....
    
      #endif
    
    which is a shame.  It's easy enough to work around it by predefining and
    expanding "DOXYGEN" when running doxygen, but having to write:
    
      #if !defined(FOO)
      #if !defined(DOXYGEN)
      #define FOO
      #endif
    
      ....
    
      #endif
    
    is slightly annoying, especially since doxygen handles the #ifndef case
    without needed the extra lines.

On 2004-08-22 15:59:40 +0000, Dimitri van Heesch wrote:

    Why not go for the #ifndef version than? It looks much cleaner to me.

On 2004-08-26 06:03:50 +0000, tim.vanholder@anubex.com wrote:

    We have standardized on using #if for preprocessor conditionals, because #if
    is
    much more flexible than #ifdef.  As such it's mainly a coding standards
    issue;
    there's a workaround so it's not that big a deal, but it would be nice if
    doxygen supported "#if defined" syntax as well.

On 2005-12-22 10:18:56 +0000, Kevin McBride wrote:

    Re-opening bug.  Even if the conditional in a #if...#endif block is not
    defined, the undefined conditional defaults to "0" per the C and C++ coding
    standards.  I am finding this coding more often in software developed by the
    Free Software Foundation.  I will try to confirm this bug.
    
    An example:
    
    #if    HAVE_CONFIG_H=1
    #include "config.h"
    #endif /* HAVE_CONFIG_H */

**Comment by albert-github** [comment]
With version 1.5.3 I can see the "FOO" in case of `#if !defined(FOO)` (I renamed it to "FOO_BB" just for the example) which is not present for `#ifndef FOO` (renamed to "FOO_AA").
In version 1.8.18 neither is present.

It is unclear what is meant bu the "HAVE_CONFIG_H" and no conformation is given either.

I think the problem has been solved in the mean time.
