### ISSUE TITLE
DoxyGen does not handle ANSI [not UTF-8] source material.

### ISSUE THREAD

**Issue by davidcorbin-atmosera** [doxygen/doxygen#10215]
**Describe the bug**
When the source is ANSI, the resulting XML is marked as UTF-8 but may have characters which are not valid [I encoundered this with the degree symbol.

```
	<ref refid="_ngemrutility_01_dll_2_include_2_std_afx_8h_1a8bd145c764f3c7360ec11574144cddc9" kindref="member">_T</ref>(&quot;**°**&quot;), 
```

**Expected behavior**
Characters in XmL file should match the encoding indicated on the XML preamble.

**Screenshots**
N/A

**To Reproduce**
Any file with a degree symbol in a context (such as the initializer..
```
```

**Version**
 1.9.7 (a2f34e1ed90f83713dc347b5134920f32c455d46)

**Stack trace**

**Additional context**
Most code these days is stored in UNICODE [UTF-8 or UTF16], however many files are still ANSI, and when character codes are above 127, the encoding between ANSI and UTF is different.  In this particular case the resultant XML (produced by DoxyGen) contains invalid characters since it is marked as UTF-8, but the source ANSI file characters are inserted verbatim (binary equivalent) to the source files...

**Comment by davidcorbin-atmosera** [comment]
Note: for the degree symbol above... in an ANSI file, it is represented by a single byte of 0xB0... in a UTF-8 file, it is represented by the 2 byte sequence 0xCB 0xB0... Attempting to read a "Raw" 0xB0 with a validating reader causes and error.

**Comment by albert-github** [comment]
Without an example it is not possible to reproduce the problem, so:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.


A first guess would be that the wrong `INPUT_ENCODING` is set.

**Comment by davidcorbin-atmosera** [comment]
@albert-github - here is a zip.
[
[Issue-10215.zip](https://github.com/doxygen/doxygen/files/12267110/Issue-10215.zip)
](url)

One CPP file, only the simple initialization of an array with an ANSI character and the source file saved as ANSI.

 only change to configuration was enable XML (and disable HTML). Look at the initializer of the array, then at line 12 of _a_n_s_i_8cpp.xml

**Comment by albert-github** [comment]
As far as I can see the problem is indeed the `INPUT_ENCODING` which is `UTF-8` setting this like:
```
INPUT_ENCODING         = ISO-8859-1
```
solves the issue.

**Comment by davidcorbin-atmosera** [comment]
Thanks..  I will check those out. Based on a quick read of the manual at https://www.doxygen.nl/manual that may help, but is going to be "tedious as all get out" as this legacy code base [existent over 25 years] is a mixture of ANSI, UTF-8 (with and without BOM) as well as literals in an encoding that does not match the overall file...

```
const wchar_t* u= L"These are Unicode";
const char* a= L"These are Ascii";
```

I am hoping that there are not many, but I am definitely not going to be able to use a solution that is Project or even Pattern wide. Since this is certainly an extreme-code-base I suppose having to write a bit of custom code may be needed (not an problem, as long as I haven't missed anything..
