### ISSUE TITLE
"refid" attribute on "includes" (incType) XML nodes should be marked optional

### ISSUE THREAD

**Issue by michaeljones** [doxygen/doxygen#10212]
**Describe the bug**
The `incType` `refid` attribute is not marked with `use="optional"`.

https://github.com/doxygen/doxygen/blob/682b594f5b4334512dc2f3026be5c4e0d90fb6a1/templates/xml/compound.xsd#L101-L108

**Expected behavior**
It is marked with `use="optional"` as it is only written conditionally:
https://github.com/doxygen/doxygen/blob/682b594f5b4334512dc2f3026be5c4e0d90fb6a1/src/xmlgen.cpp#L1290-L1293

**Screenshots**
None.

**To Reproduce**
The issue is visible when creating a parser for the XML based on the XSD which expects non-optional attributes to be there. This is done in Rust as part of the Docleaf project: https://github.com/docleaf-labs/docleaf

**Version**
I'm using 1.9.7 locally but the issue is visible in the code on `main` (if I correct in my interpretation of the code/xsd.)

**Stack trace**
None

**Additional context**
None

**Comment by michaeljones** [comment]
Yeah, fair. I encountered the code in a somewhat complex set up and lazily hoped the code references would be enough. Sorry about that.

If you look at `xml/example_8h.xml` in the attached zip file, you'll see line 5 is:

```xml
<includes local="yes">my_other_file.h</includes>
```

Which is an `includes` tag without a `refid`. I assume it happens for any inclusion of a file that is outside of the Doxygen code base or that Doxygen can't find.

[includes-xml-refid-error.zip](https://github.com/doxygen/doxygen/files/12263858/includes-xml-refid-error.zip)

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.8.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
