### ISSUE TITLE
error: argument 'foo' of command @param is not found in the argument list of __attribute__((bar))

### ISSUE THREAD

**Issue by PackmanDude** [doxygen/doxygen#10228]
**Describe the bug**
Doxygen's treating GCC attributes as functions, leading to incorrect parsing.

**Expected behavior**
Don't treat GCC attributes as functions.

**Screenshots**

![an error message](https://github.com/doxygen/doxygen/assets/99031872/da6ecb9e-8f76-41bd-93c2-1ee1e53ff518)

**To Reproduce**
https://github.com/doxygen/doxygen/files/12328885/sample-10228.zip

**Version**
1.9.7

**Stack trace**
If you encounter a crash and can build doxygen from sources yourself with debug info (`-DCMAKE_BUILD_TYPE=Debug`), a stack trace can be very helpful (especially if it is not possible to capture the problem in a small example that can be shared).

**Additional context**
None.

**Comment by PackmanDude** [comment]
#6606 may be related.

**Comment by albert-github** [comment]
See the comment at: https://github.com/doxygen/doxygen/issues/6606#issuecomment-1675982613

Did you try the settings:
- `PREDEFINED= __attribute__(x)=`
- `MACRO_EXPANSION=YES`

An image is not a good idea to supply code as it doesn't cut / paste the code:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

**Comment by PackmanDude** [comment]
Oh, well, I tried reproducing the error withing a small example, an couldn't get it right. And then I tried again in the project I was having problem in, and now it seems to have been resolved by itself. I'm so sorry, that caused contributor's time for that.

**Comment by PackmanDude** [comment]
Ok, I got it.

[sample-10228.zip](https://github.com/doxygen/doxygen/files/12328885/sample-10228.zip)

**Comment by PackmanDude** [comment]
```
# Difference with default Doxyfile 1.9.7
EXTRACT_ALL            = YES
WARN_AS_ERROR          = YES
```

causes a meaningful error(warning) from the screenshots.

**Comment by PackmanDude** [comment]
And code is:
```c
/*!
 * \param a a pointer
 * \return 0
 */
__attribute__((access(none, 1)))
int foo(int *a)
{
	return 0;
}

int main(void)
{
	return foo(0);
}
```

That's all, the same is in within the zip archive I've attached.

**Comment by PackmanDude** [comment]
`PREDEFINED= __attribute__(x)=`
and
`MACRO_EXPANSION=YES`
seem to fix it, I'm having preprocessing disabled in the original project, due to one's preference, so I think it's still a bug, and your advice is just a workaround, if it's not. And this is a well-defined, expected behaviour, my bad then.

**Comment by albert-github** [comment]
As written the `__attribute__` is a "GCC attribute" and not a standard in C / C++ statement.
The standard way to define attributes in C / C++ is by means of `[[...]]`.

Having preprocessing disabled disabled will cause this kind of problems and doxygen thinks that the function name is `__attribute__`.

The behavior is well documented.

I think the problem is usage.

**Comment by PackmanDude** [comment]
> As written the `__attribute__` is a "GCC attribute" and not a standard in C / C++ statement.
> The standard way to define attributes in C / C++ is by means of `[[...]]`.
> 
> Having preprocessing disabled disabled will cause this kind of problems and doxygen thinks that the function name is `__attribute__`.
> 
> The behavior is well documented.
> 
> I think the problem is usage.
> 

Well, to use C syntax attributes one must switch to C23 standard, which many won’t. I don’t want to evaluate macros in my source code in the documentation, and keep doxygen reacting to GCC attributes appropriately, what settings I should choose, or any to achieve something similar?

**Comment by albert-github** [comment]
Well the only thing I can think of given the restrictions you specify is to write an `INPUT_FILTER` in doxygen (see: https://www.doxygen.nl/manual/config.html#cfg_input_filter) that would filer out the the `__attribute__(...)` parts.

**Comment by albert-github** [comment]
Depending on your exact reasons for setting `ENABLE_PREPROCESSING=NO` the setting `EXPAND_ONLY_PREDEF` might help as well.

**Comment by PackmanDude** [comment]
I will try it later, thanks.

**Comment by PackmanDude** [comment]
It did the trick.
Thanks a lot!
