### ISSUE TITLE
attributes to <p> tag get lost (Origin: bugzilla #136299)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1025]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.3.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2004-03-05 16:24:13 +0000, Alexander Stippler wrote:

    When using the html <p> tag with any html-attributes, these attributes are
    ignored, e.g. <p align=justify> results in <p>.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6819

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
