### ISSUE TITLE
Combination `'{` in inline code breaks markdown parsing

### ISSUE THREAD

**Issue by Hi-Angel** [doxygen/doxygen#10276]
**Describe the bug**

I'm trying to document some JSON related code and noticed the rendering is completely broken: often inline code has no highlight, and sometimes highlight seemingly arbitrarily goes over multiple lines and then Doxygen also complains about undocumented parameters which are actually documented.

On further inspection it turns out the following two characters when enclosed to inline code completely break Markdown parsing: `'{`

**To Reproduce**

1. In `/tmp` dir create file `test3.c`
    ```C
    /** @addtogroup TEST
        Some test `'{` func */
    void foo();
    ```

    and  `doxygen_config`:

    ```ini
    OUTPUT_DIRECTORY = .
    MARKDOWN_SUPPORT = YES
    INPUT            = test3.c
    ```
2. Execute `doxygen doxygen_config`
3. Open the file `/tmp/html/group__TEST.html` in a browser.

**Expected behavior**

The documentation has no backticks nor odd unicode-double-quotes shown

**Screenshots**

![Screenshot_20230831_135742](https://github.com/doxygen/doxygen/assets/7935057/9aaf3795-fdb3-4f59-8ff4-dc241113faf1)

**Version**

1.9.7

**Comment by Hi-Angel** [comment]
…meanwhile, replacing a single quote with double quote in docs seems to be working around the issue

**Comment by albert-github** [comment]
The usage of the single quote in a single backtick part gives indeed some confusion as also the possibility with a text between single backtick till single quote which translates to  `&lsquo;` and `&rsquo;` is supported.
The way of working here is indeed to use the double backtick as documented in https://www.doxygen.nl/manual/markdown.html#md_codespan

Setting issue to usage.

**Comment by Hi-Angel** [comment]
I see it was closed. So, will it not be fixed? FTR, it's incorrect Markdown rendering. The fact that I could work it around with double quotes doesn't mean you can always do such replacement. Sometimes it has to be a single quote.

**Comment by Hi-Angel** [comment]
It's also a problem even in cases where there is a work around, because a person sees formatting breaks, but it's not obvious why. So you have to spend time on reducing this to a minimal testcase to see what exactly breaks.
