### ISSUE TITLE
How to build the whole documentation in https://www.doxygen.nl/?

### ISSUE THREAD

**Issue by hwhsu1231** [doxygen/doxygen#10277]
Hello, Doxygen Team. 

Recently, I tried to build the Doxygen's Documentation from sources. After preparing prerequisites, the build works successfully. The following commands are what I used:

```
git clone https://github.com/doxygen/doxygen.git
cd doxygen
mkdir build && cd build
cmake .. -Dbuild_doc=ON -Dbuild_doc_chm=ON
cmake --build . --target docs
```

You can see the full log: [log-build-docs.txt](https://github.com/doxygen/doxygen/files/12487219/log-build-docs.txt)

However, I noticed that the artifacts look different than the one in https://www.doxygen.nl/. To be more specific, the generated documentation looks similar with the https://www.doxygen.nl/manual/ part, but still has difference. The following screenshot is what my local artifacts look like.

Therefore, I wonder: **How to build the whole documentation in https://www.doxygen.nl/?**

![image](https://github.com/doxygen/doxygen/assets/71438617/9c9636e0-db2a-4b49-9230-5611a210a88f)

**Comment by albert-github** [comment]
These are 2 things
- the manual
- the doxygen site

In the doxygen site the doxygen manual is embedded and on the site some topics are mentioned that are not useful in the manual (e.g. where to download as when having the manual locally one already has downloaded / build doxygen)
There will be small differences in the layouting to keep a consistent style.

You mention you are missing something, what are you missing?

**Comment by hwhsu1231** [comment]
> You mention you are missing something, what are you missing?

Well, that's exactly what I'm going to ask. There must be a workflow to keep updating https://www.doxygen.nl/ from sources continuously, right? What do I miss so that I can only build the manual instead of the whole doxygen site?

**Comment by albert-github** [comment]
With the 
```
cmake --build . --target docs
```

or
```
cd build
make docs
```
you just locally build the doxygen manual which will be available in the `html` subdirectory of `build` (and in the `latex` subdirectory of the `build` directory you will find the pdf file).

The doxygen site is only updated at the moment of a release (by the release procedure of doxygen, which is not in the github directory).

**Comment by hwhsu1231** [comment]
So it is normal that the generated HTML Documentation is different than the one displayed in the Doxygen Website, right?

**Comment by albert-github** [comment]
The locally generated documentation represents the documentation of the used branch (so most of the times the master version, including all changes since the last release).
The version on the site shows the status of the last release.
(so one of the changes you see is the version number)

**Comment by hwhsu1231** [comment]
@albert-github - I wondered why my locally generated documentation doesn't have this menu bar on the top?

![image](https://github.com/doxygen/doxygen/assets/71438617/69625e33-de39-4d1d-97d4-60fe2cfff13f)

**Comment by albert-github** [comment]
You didn't miss anything, the doxygen documentation is embedded in the doxygen site. So the doxygen site contains some more information as explained before and hence the extra fields on the site.

**Comment by doxygen** [comment]
@hwhsu1231 As Albert already indicated, the website and documentation are different things (though both are generated by doxygen, and partly use the same input material). 

I don't know why you are trying to recreate the website, but if you have plan to create a public mirror of the whole website, then please don't. This will be confusing for users.

**Comment by hwhsu1231** [comment]
@doxygen

Understood. However, the reason I asked is because:

> I noticed that the options available in the menu bar at the top of the page don't seem to be that necessary. This is because the 'navigation bar' on the left side actually already includes the options provided in the 'menu bar'.

I'll use [Eigen](https://eigen.tuxfamily.org/dox/index.html), a well-known library, as a comparison. We see that its documentation does not provide a 'menu bar', only a 'navigation bar'. Therefore, I think: 

> Since the navigation bar can display the complete structure of the document, the existence of the menu bar seems a bit redundant.

![image](https://github.com/doxygen/doxygen/assets/71438617/301c4246-1191-4be6-89e5-4a435792c263)

**Comment by albert-github** [comment]
> I noticed that the options available in the menu bar at the top of the page don't seem to be that necessary.

There are there for convenience / fast access.

> I'll use [Eigen](https://eigen.tuxfamily.org/dox/index.html), a well-known library, as a comparison.

Every product has its own way of presenting the results.
