### ISSUE TITLE
Missing anchor tag for struct of typedef within group (Origin: bugzilla #136694)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1031]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.3.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2004-03-09 22:31:30 +0000, Michael Henry wrote:

    I've encountered what I think is a link generation bug
    related to a struct of function pointers.  I've upgraded
    to the latest Doxygen (v1.3.6) and the problem remains.
    I saw this problem in v1.3.4, and I've not tried any
    earlier versions.
    
    The following short program demonstrates the issue:
    -------------- begin file.c ------------------
    /** @file test.c */
    
    /** @defgroup mygroup MyGroup
    * @{
    */
    
    /** @brief  Typedef of function.
    *
    * Details of function
    */
    typedef void (*FuncType10)(void);
    
    /** @}*/
    
    /** @brief  Struct of function pointers
    */
    struct MyStruct {
       FuncType10 f10;  /**< dummy */
    };
    -------------- end file.c ------------------
    
    I used Doxywizard to generate a Doxyfile, then made just
    enough changes to include file.c and to generate only
    .html output.  To see the problem, run doxygen to generate
    the html output, then click on "Data Structures", then on
    "MyStruct", then on "FuncType10" within the "Typedefs"
    section.  The generated hyperlink ends with:
    ..../html/test_8c.html#a0
    
    Looking at the generated HTML of the file "test_8c.html",
    there is no anchor named "a0", so the link takes you to the
    top of the file, instead of taking you down to the definition of
    FuncType10.
    
    If the @defgroup is removed, everything seems to work fine.
    
    Thanks,
    Michael Henry

**Comment by albert-github** [comment]
I tried to reproduce the issue with 1.3.4 (anchor name is a0) and 1.3.6 (anchor name is ga0) but in both case in didn't find any reference to "test_8c.html" with "#a0" or "#ga0" all references went to "group__mygroup.html" and here the appropriate anchor is present.

So the problem is for me not reproducible.
