### ISSUE TITLE
XML output - Inconsistent file names

### ISSUE THREAD

**Issue by farcas-snps** [doxygen/doxygen#10319]
**Describe the bug**
There is a difference between Windows and Linux with respect to generated XML files. Different naming pattern is used.
Let `randomHeader.h` be our input file.
Linux: `randomHeader_8h.xml`
Windows: `random_header_8h.xml`
Why is it different? Can I control this somehow?

**Expected behavior**
Files with the same name generated on both platforms.

**Version**
1.9.4

**Comment by albert-github** [comment]
This has to do with the system dependent setting of `CASE_SENSE_NAMES`, see https://www.doxygen.nl/manual/config.html#cfg_case_sense_names


Note the current doxygen version is 1.9.8 (is of no influence to this problem though).

**Comment by farcas-snps** [comment]
Setting `CASE_SENSE_NAMES=NO` solves the problem. Thank you for the quick reply!
