### ISSUE TITLE
Doxygen recognize macro errors

### ISSUE THREAD

**Issue by Herxinsasa** [doxygen/doxygen#10318]
**Describe the bug**
i define a macro like this:
#define RPC_CLIENT_RECV(_helper, ...) \
	RPC_CLIENT_RECV_BEGIN(_helper)\
	RPC_CLIENT_RECV_PROCESS(_helper, ##__VA_ARGS__)\
	RPC_CLIENT_RECV_END

but doxygen transfer it to:
#define RPC_CLIENT_RECV	(	 	_helper,
 	... 
)	
Value:
	    RPC_CLIENT_RECV_BEGIN(_helper)\
            RPC_CLIENT_RECV_PROCESS(_helper, ##__VA_ARGS__)\
            RPC_CLIENT_RECV_END

**Expected behavior**
It seems not recognize ‘\’ 
the expected result :
#define RPC_CLIENT_RECV	(	 	_helper,
 	... 
)	RPC_CLIENT_RECV_BEGIN (_helper) RPC_CLIENT_RECV_PROCESS(_helper, ##__VA_ARGS__) RPC_CLIENT_RECV_END

**Screenshots**
![image](https://github.com/doxygen/doxygen/assets/65589596/bab03f92-e1c8-4a53-b59a-36ff44043225)
![image](https://github.com/doxygen/doxygen/assets/65589596/064c54a1-a58e-41b7-b7a9-a199c5a4b276)

**Comment by albert-github** [comment]
It is a bit unclear what is wrong in your case.
- please edit the question so the code parts are better visible (using `` ` `` and ` ``` `)

also:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.
- Please also specify the **full** doxygen version used (`doxygen -v`).

**Comment by Herxinsasa** [comment]
this is the zip file of a small example；
[test.zip](https://github.com/doxygen/doxygen/files/12659781/test.zip)
```
Content:
/**
* @brief		xxxxx
* @param[in]	_helper		xxxxx
* @param[in]	...			xxxxx
*/
#define RPC_CLIENT_RECV(_helper, ...) \
	RPC_CLIENT_RECV_BEGIN(_helper)\
	RPC_CLIENT_RECV_PROCESS(_helper, ##__VA_ARGS__)\
	RPC_CLIENT_RECV_END
```
Result：
```
#define RPC_CLIENT_RECV	(	 	_helper,
 	... 
)		
Value:
    RPC_CLIENT_RECV_BEGIN(_helper)\
    RPC_CLIENT_RECV_PROCESS(_helper, ##__VA_ARGS__)\
    RPC_CLIENT_RECV_END
xxxxx

Parameters
[in]	_helper	xxxxx
[in]	...	xxxxx
```
It  not recognize '\' of this marco

doxygen version:(doxygen -1.9.7)

**Comment by Herxinsasa** [comment]
I think the contents of Value should be appended to the macro definition rather than appearing separately as a value。
actually：
![image](https://github.com/doxygen/doxygen/assets/65589596/d0be9f02-af73-4b42-a969-7c7885c15883)
expect：
![image](https://github.com/doxygen/doxygen/assets/65589596/6b383dc1-1511-4eb7-a127-3999961727d7)

**Comment by Herxinsasa** [comment]
To avoid long macro definitions use \ for line breaks
line break:
```
#define MY_MACRO(a,b) a##b \
                      c##d
```
![image](https://github.com/doxygen/doxygen/assets/65589596/b79b3b8b-f6f2-4165-9e32-a23f705fd752)

without line break:
```
`#define MY_MACRO(a,b) a##b c##d
```
![image](https://github.com/doxygen/doxygen/assets/65589596/eceafd57-7a28-40c9-91bd-a32faa1e5c3b)
'\ 'will be automatically removed in the compiler, the expected result should be the result without line breaks

**Comment by albert-github** [comment]
Doxygen does show the value of the define as is and when it is a multi line define it won't show it at the "#define" but in a separate block as when it is a multi line value it can be very long and disturb the documentation. Your statement:
> To avoid long macro definitions use `\` for line breaks

exactly gives the reasoning how doxygen handles it. And when the user wants to see the "long line" in the documenttaion he should also use it in the code.

> `\` will be automatically removed in the compiler, the expected result should be the result without line breaks

This is true and although doxygen is not  a compiler doxygen will handle it so as well (in the macro expansions). 

I think it is all a matter of usage.

**Comment by albert-github** [comment]
When you mean it should not be shown at all, please have a look at e.g. the command `\hideinitializer`.

**Comment by Herxinsasa** [comment]
Thanks for your reply, I finally chose to hide the macro definition use  the command `\hideinitializer`.
