### ISSUE TITLE
Short comment is hidden by \internal flag even if INTERNAL_DOCS = YES

### ISSUE THREAD

**Issue by yuriishutkin** [doxygen/doxygen#10322]
**Describe the bug**
I have an internal class with a short comment:
```
//! \internal Test short comment
class Test {
	Test() {}
};
```

and enable `INTERNAL_DOCS = YES` in the config.

**Expected behavior**
Test class is shown in the class list with short comment.

**Screenshots**
The class is shown, but short comment is missing.
![2023-09-23_01-29-38](https://github.com/doxygen/doxygen/assets/2951262/1f2b6a55-dd4a-4e02-9565-5475d76dd06a)

**To Reproduce**
Run the test above with enabled INTERNAL_DOCS

**Version**
1.9.8

**Comment by albert-github** [comment]
The intention of the `\internal` command is to provide internal detailed documentation and hence the brief is not shown, though it is possible to show it when explicitly using the `\brief` command:
```
//! \internal
//! \brief Test short comment
class Test {
        Test() {}
};
```

I think the problem is usage.

**Comment by yuriishutkin** [comment]
Ok, I've got this. \brief works fine. I think it can be closed.
