### ISSUE TITLE
ALIASES += foo{2}="\htmlonly ... \endhtmlonly" don't work in Markdown-Code-Style, Rest of HTML works.

### ISSUE THREAD

**Issue by paule32** [doxygen/doxygen#10337]
Hello,
I have an ALIASES in Doxyfile(.ENU):
ALIASES += b_colortext{2}="\htmlonly <font color='\1'><b>\2</b></font> \endhtmlonly"

with two Parameters.
But in Markdown-Code, the ALIAS will not be handled:
- see Lines 24, and followed at file: Application.h
- see the attached screen01.png Picture to make it visual described

I get no Error's. So, it seems the Code is untouched correct - except, it will not replace with the code in the source file.
Thanks for reading
paule32
[packed.zip](https://github.com/doxygen/doxygen/files/12777352/packed.zip)

**Comment by albert-github** [comment]
In the file `Application.h` the line 24 reads:
```
 * b_colortext{yellow,int}    | Ganzzahl
```
touch you want `b_colortext` to be a command so it should read:
```
 * \b_colortext{yellow,int}    | Ganzzahl
```
or
```
 * @b_colortext{yellow,int}    | Ganzzahl
```

So I think the problem is usage.

**Comment by paule32** [comment]
yes, right.
was my mistake - sorry.
