### ISSUE TITLE
Search subpart research after a search

### ISSUE THREAD

**Issue by morgan-mathiaut** [doxygen/doxygen#10351]
**Describe the bug**
In HTML output
When you select a subpart for a search ("Classes" for example), this subpart is reset after a search.

**Expected behavior**
Search subpart is keep after a search

**To Reproduce**
Go to http://eigen.tuxfamily.org/dox/
Select "Classes" on search subpart
Enter "Array" in search
Go to the "Array" doc page
Selected subpart "Classes" is reset to "all"

**Version**
1.9.8

**Comment by albert-github** [comment]
Doxygen has besides also other search possibilities, see https://www.doxygen.nl/manual/searching.html probably you can accomplish with e.g. with an external / server side search the things you would like to see.

**Comment by morgan-mathiaut** [comment]
Thanks to your impressive quick reply :)
Here a small video :
https://github.com/doxygen/doxygen/assets/140616075/074956ac-d3b0-4ea5-9ec4-885b13dba20f
The espected behavior is : keep subpart "Classes" after a search and don't reset it (to "all")
I hope that it's clearer.

Thanks a lot

**Comment by doxygen** [comment]
__[implementation note]__: this means this value should be stored in localstorage (for Chrome) or in a cookie (other browsers), like we do for the darkmode setting (`darkmode_toggle.js`).

**Comment by albert-github** [comment]
@doxygen or should the structure be used that is used in`resize.js`?

**Comment by doxygen** [comment]
@albert-github Yes, it is basically the same idea indeed (i.e. localStorage for Chrome, and cookies otherwise). This dual approach is needed to get it to work with `file://` style URLs.

**Comment by albert-github** [comment]
@doxygen that it should be stored in localStorage / cookie is clear. I'm not completely getting the difference, should the create / read / erase version of `darkmode_toggle.js` be used or the read/write version of `resize.js` ?

Are you looking into it or should I have a look in the coming week?

**Comment by doxygen** [comment]
@albert-github there is no real difference. We probably need a third instance of such functions for this new property. You can have a go at it if you like.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #10381

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.10.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
