### ISSUE TITLE
Cannot import PlantUML diagram on a C file.

### ISSUE THREAD

**Issue by alexamatausa** [doxygen/doxygen#10362]
I am generating documentation for my code in C and I am finding that I cannot insert a graph/diagram made in PlantUML. I have checked that the Doxygen file configuration points to the graph directory, but even so the graph is not generated in image format.

Next, I attach the project with the diagram in the "puml" folder and the code in the "src" folder (which is an example code).
[issue_uml_diagrams.zip](https://github.com/doxygen/doxygen/files/12913644/issue_uml_diagrams.zip)

**Comment by alexamatausa** [comment]
Hi Albert! 

Nice to meet you, and thanks for help me! I'm tried to include the `@startuml` and `@enduml` directives in code, but Doxygen returns errors. I send to you the log from the output produced by Doxygen and I tried to execute the jar file on my terminal and it works. 
[doxygen_log.txt](https://github.com/doxygen/doxygen/files/12914467/doxygen_log.txt)

**Comment by albert-github** [comment]
- Did you also try to execute `java -Djava.awt.headless=true -jar "./utils/plantuml.jar" -charset UTF-8 -tpng "build/html/inline_umlgraph_pnghtml.pu"` as it looks a bit like the plantuml version 1.2023.11 has some problems with reading the dot results.


(I ran with "PlantUML version 1.2023.12beta1 (Unknown compile time)" and had no problems, obtained from https://github.com/plantuml/plantuml/releases/download/snapshot/plantuml-SNAPSHOT.jar)

**Comment by alexamatausa** [comment]
Hi again Albert! 

Thanks for your help. The problem has been solved. Firstly, thanks for your time. I think that the issue is the version from Plant UML I'm using. The snapshot version solved my problem perfectly.

I am attaching to this message the project structure in case it may be useful to someone.

Thanks for all!

Best regards.
[puml_render_solved_using_doxygen.zip](https://github.com/doxygen/doxygen/files/12915756/puml_render_solved_using_doxygen.zip)

**Comment by albert-github** [comment]
I just downloaded from https://github.com/plantuml/plantuml/releases the files plantuml-1.2023.11.jar and plantuml.jar and they are quite a bit bigger than the file you linked with the issue and they did work. Looks like the file you used is a "special" file.
