### ISSUE TITLE
Add VSDoxyHighlighter to the list of extensions

### ISSUE THREAD

**Issue by Sedeniono** [doxygen/doxygen#10372]
Hi, I wrote the [VSDoxyHighlighter](https://github.com/Sedeniono/VSDoxyHighlighter) extension ([marketplace link](https://marketplace.visualstudio.com/items?itemName=Sedenion.VSDoxyHighlighter)) to provide syntax highlighting and autocomplete functionality for Visual Studio 2022 (**not** VS Code). It runs stable for several months now and has ~1300 unique users. Could you add it to the [list of extensions on the doxygen homepage](https://www.doxygen.nl/helpers.html#doxedit_vs)?

Also, as a side note, the EnhancedCommentsCpp extension [listed there](https://www.doxygen.nl/helpers.html#doxedit_vs) is no longer available anywhere for quite some time now (which is the reason why I started writing my own extension in the first place).

Another related question: Do you happen to know some places with doxygen users where I could advertise my extension ([besides reddit](https://www.reddit.com/r/cpp/comments/13fsu9x/vsdoxyhighlighter_highlighting_of_doxygen/))?

**Comment by doxygen** [comment]
@Sedeniono I've added the link to VSDoxyHighligher and removed the EnhancedCommentsCpp link.
Please check if it is ok.

As for promotion: you could try the doxygen users mailing list, although it is not that active as of lately.

**Comment by Sedeniono** [comment]
Thank you very much for adding my extension and for your information 😀
