### ISSUE TITLE
Large variance in runtime

### ISSUE THREAD

**Issue by carlosgalvezp** [doxygen/doxygen#10387]
**Describe the bug**
We observe a large variance in the time it takes for Doxygen to process our project. For example it can go from 3 minutes to 20 minutes without changing anything.

**Expected behavior**
Somewhat consistent time to process the project.

Is there a way we can investigate this further?

**Version**
1.9.8

**Comment by albert-github** [comment]
- Between which versions are you talking about?
- maybe running doxygen with the `-d time`  option (so `doxygen -d time Doxyfile`) might give some clues (don't forget to set `QUIET=NO` when you set it before to `YES`).

**Comment by doxygen** [comment]
Doxygen always does exactly the same with the same inputs, so it is unlikely that it is something in doxygen that is causing the differences. It is more likely something in the environment in which doxygen is run.

So it is good to know what kind of system are you using. It is a physical system with dedicated disks, or a virtualized environment where resources like CPUs are shared, and is the disk is network mounted?

Is the difference between the first and second run only, or also between the second and subsequent runs? Some data, such as dot images, is reused over multiple runs, making the first run slower.

**Comment by carlosgalvezp** [comment]
> Between which versions are you talking about?

It's always on the same version, 1.9.8. What I mean is that I run the exact same doxygen command twice, and one time it can take 3 minutes and another one 20 minutes.

> maybe running doxygen with the -d time option

Thanks, will try it out and report back!

> Is the difference between the first and second run only, or also between the second and subsequent runs?

I haven't been able to observe a clear pattern, it seems a bit random. I would expect the first round to be slower and the subsequent ones have a faster and consistent time, but out of the blue it can be really slow on a new run after the first one.

> Also good to know what the values of DOT_NUM_THREADS and NUM_PROC_THREADS are set to.

We have `NUM_PROC_THREADS=1`, `DOT_NUM_THREADS=0`.

**Comment by albert-github** [comment]
What do you mean with "on a new run after the first one"?
Did you mean that you cleared all output directories? In that case all graphs have to be regenerated, when the old results are still present only changed graphs have to be regenerated.

**Comment by carlosgalvezp** [comment]
No, without any clean operation between runs. 

But ok if the expectation is that doxygen should be somewhat deterministic every run (once results are cached) then there must be something fishy with my system, I will investigate deeper!

**Comment by albert-github** [comment]
Without cleaning the 2nd and 3rd and ... runs should give comparable times, of course it always has some fluctuations due to CPU / Memory / Disk loads

**Comment by carlosgalvezp** [comment]
You are right, I run now on a dedicated system and it's a lot more deterministic. I'll investigate what's up in the machine we are using. Thanks for the help!
