### ISSUE TITLE
Can't link to a tagfile page in DoxygenLayout?

### ISSUE THREAD

**Issue by chris-tallman** [doxygen/doxygen#10388]
**Describe the bug**
I have been struggling to figure out how to reference an external page with a tagfile within my `DoxygenLayout.xml` file. I can reference the page elsewhere in my code with `@ref external.md` and `[external](external.md)`, but not `<tab type="user" title="External" url="@ref external.md"/>` in the layout navindex.

**Expected behavior**
I would expect to be able to reference the external page the same way whether it's linked from a documentation page or from the layout file.

**To Reproduce**
See [TagfileLinkInDoxygenLayout.zip](https://github.com/doxygen/doxygen/files/13193095/TagfileLinkInDoxygenLayout.zip).

With this sample, run `pushd external && doxygen && popd && doxygen` and view the generated html output. Links in the documentation correctly navigate to the external page, but the link in the navigation bar is broken.

**Version**
Observed in version 1.9.7 and 1.9.8

**Comment by albert-github** [comment]
It looks like that the general linking into the "blue bar" and treeview has problems.
I did some tests with
- external
  -  page (your test), does not work
  -  function,  does not work
- internal
  -  page, does not work
  -  function,  works

whilst when having the same `@ref` in running text all links do work.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #10390

**Comment by chris-tallman** [comment]
I tested this branch with my test project and it works as expected. 👍

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.10.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
