### ISSUE TITLE
Reordering of input when using multiple \page commands

### ISSUE THREAD

**Issue by higaski** [doxygen/doxygen#10397]
The following snippet produces reordered output. Instead of text-table-text-table the output produces text-text-table-table.

```cpp
/// \mainpage
/// This is the mainpage.

/// \page page_test Test Page
/// First text
/// | X | Y |
/// | - | - |
/// | A | B |
/// | A | B |

/// \page page_test Test Page
/// Second text
/// | 1 | 2 |
/// | - | - |
/// | A | B |
/// | A | B |
```

![doxygen_pages_issue](https://github.com/doxygen/doxygen/assets/13762516/2c750d63-7875-420d-a0f9-f9716fb44292)

I'm currently running Doxygen 1.9.8. Here is a .zip containing the example:
[doxygen_pages_issue.zip](https://github.com/doxygen/doxygen/files/13271356/doxygen_pages_issue.zip)

**Comment by doxygen** [comment]
@higaski I think the problem is setting `MULTILINE_CPP_IS_BRIEF` to `YES` instead of `NO` (the default). This will treat the line after the `\page` command as a brief description and the table as the detailed description. Since there are two pages with the same name, their brief and detailed descriptions are combined.

**Comment by higaski** [comment]
Thanks for clearing that up!

**Comment by higaski** [comment]
Just leaving this here in case someone else stumbles into this problem.

The actual reason I tend to have multiple \page commands is that some of my documentation contains `// clang-format off` directives which only work when introduced through normal C comments. This creates a break and the current page has to be re-set with a \page command again.

Since I prefer the `MULTILINE_CPP_IS_BRIEF` option set I've settled to using the following pattern to keep text and tables ordered.

```cpp
/// \page page_test Test Page
/// First text
// clang-format off
/// | X | Y |
/// | - | - |
/// | A | B |
/// | A | B |
// clang-format on
/// \page page_test
/// \details
```
