### ISSUE TITLE
Syntax error in example on Web page?

### ISSUE THREAD

**Issue by CRConrad** [doxygen/doxygen#10399]
Hello,

On the page https://www.doxygen.nl/manual/docblocks.html , there is an example illustrating how to include periods in the brief description:

/** Brief description (e.g.\ using only a few words). Details follow. */

I think there should be another backslash, after the first period (the one following the 'e'), not just after the second one (following the 'g').

Because as it is now, it seems to me that the brief description would be just "Brief description (e.", and the detailed description will start with "g.\ using only a few words). Details follow." Or maybe I've misunderstood the rules of syntax?

(I am not using any version of Doxygen on any OS; I just came across it, got interested, and read some pages.)

**Comment by albert-github** [comment]
Thanks for the interest in doxygen.
It is a bit confusing and a difficult topic the usage of abbreviations in brief descriptions but doxygen has some, probably not fail safe, rules with which it decides when a `.` (dot) ends a brief description and when not (also on together with the setting `JAVADOC_AUTOBRIEF` and `QT_AUTPBRIEF`).

I created a small example to show some effects and also invented some abbreviations (I used the current doxygen version 1.9.8).
This example also gives some warnings:
```
.../docbl_test.h:12: warning: Found unknown command '\g'
.../docbl_test.h:20: warning: Found unknown command '\g'
```
and note also the results of abbreviation `e.\n.\ `

Example:  [example.tar.gz](https://github.com/doxygen/doxygen/files/13306476/example.tar.gz)
Result: ![example](https://github.com/doxygen/doxygen/assets/5223533/df1f23e4-592f-41b5-964d-0a213ab71506)
