### ISSUE TITLE
GENERATE_XML generates XML files with erroneous `</codeline>`s in `<programlisting>`

### ISSUE THREAD

**Issue by yous** [doxygen/doxygen#10392]
**Describe the bug**
With `GENERATE_XML = YES`, the generated xml files has a number of erroneous `</codeline>`s.

**Expected behavior**
There are no extra `</codeline>`s.

**Screenshots**
<img width="593" alt="Screenshot 2023-11-05 18 58 37" src="https://github.com/doxygen/doxygen/assets/853977/0da1917b-72f9-4510-bfcb-f0783bf7f24f">

The lines with line number 36-37, 41-42 doesn't have opening `<codeline>` and only has closing `</codeline>`.

**To Reproduce**
- [test_xml.tar.gz](https://github.com/doxygen/doxygen/files/13259236/test_xml.tar.gz)

Run `doxygen Doxyfile`.

**Version**
On Apple silicon macOS:
- 1.10.0 (0dd71c6235993ed91a8179fca597ac78ac30d8ca*)

The 1.9.8 version is okay, so I did run `git bisect`, and it pointed to 3fe542cae77466cf8326cd9c6066866bacd4bf28.

**Comment by doxygen** [comment]
@yous Please verify if the referenced commit fixes the problem for you. Since this bug is not in an official release yet, the report can be closed if it is indeed fixed.

**Comment by yous** [comment]
I can confirm that the problem is fixed.
