### ISSUE TITLE
\includedoc for Markdown pages

### ISSUE THREAD

**Issue by floschulze** [doxygen/doxygen#10413]
**Describe the bug**
Using `\include{doc} some_file.md` inside a second markdown file `second_file.md` does not work, if there are Markdown headers in `some_file.md`. It will include the text until the first header, and then abort.

**Expected behavior**
I expect the contents of the first file `some_file.md` to be copy-pasted to where the `\include{doc}` is used inside the `second_file.md`. Maybe I am misunderstanding the concept, on how the include command is designed to work, some help would be great!

Maybe this issue is also related to Issue #8378.

**To Reproduce**
A simple example would be:

`some_file.md`:
```markdown
Some text before a heading.

## A header

Some text after the header
```

`second_file.md`:
```markdown
\page label Page with a label

We want to give some additional text, and then include the first file.

\include{doc} some_file.md
```

When I generate the documentation, the output corresponds to a page like:
```markdown
\page label Page with a label

We want to give some additional text, and then include the first file.

Some text before a heading.
```

The header and text after in some_file.md is not included.

**Version**
I use Doxygen version 1.9.8 on MacOS

**Additional context**
I want to use this feature, to include the contents of the `CONTRIBUTING.md` file in the documentation of my project. In order to render the `CONTRIBUTING.md` on GitHub, I don't want to have any Doxygen commands in this file. But in the documentation, I would like to have a `\tableofcontents` and create a `\subpage code-style`. My idea was, to exclude the `CONTRIBUTING.md` from Doxygen, and instead use a `doc/contribute.md` file, that would `\include CONTRIBUTING.md`.
Maybe for this use case, there is also an other solution? Any answer would be appreciated!

**Comment by albert-github** [comment]
The problem here is about the moment the `section` / `subsection` (as a result of `#` / `##`) commands are processed.
This problem has also been reported in #7688

I think this issue is a duplicate.

**Comment by floschulze** [comment]
Thanks @albert-github, your mentioned Issue is indeed covering my problem. Must have missed it before
