### ISSUE TITLE
<a href> doesn't allow <img> as visible part? (Origin: bugzilla #137447)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1041]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.3.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2004-03-17 02:08:57 +0000, jdemail@yahoo.com wrote:

    This comment:
      <a href="legend.html"><img src="error.gif"></a>
    
    results in this output:
      <a href="legend.html"></a>
    
    Why does doxygen eat the <img>?
    
    
    Further, this comment:
      <img src="error.gif">
    
    results in this output:
      <div align=center><img src="error.gif"></div>
    
    Why does doxygen take over HTML formatting? I thought HTML was
    generally passed on as-is. I would rather have to add the <center>
    commands myself (and thus control the HTML output) than have
    doxygen take over that much.
    
    John

On 2006-06-19 11:45:46 +0000, jzutt wrote:

    I have the same problem with doxygen-1.4.7-1 (linux/fedora core 5).
    Would be great if this gets solved.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6426

**Comment by albert-github** [comment]
Code has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
