### ISSUE TITLE
Unclear documentation of HTML_COLORSTYLE

### ISSUE THREAD

**Issue by carlosgalvezp** [doxygen/doxygen#10415]
The docs say:

```
# AUTO_LIGHT automatically set the mode according to
# the user preference, use light mode if no preference is set (the default),
```

Where is "the user preference" set, if not right here? Are there other settings other than HTML_COLORSTYLE where the user preference is set?

The reason I ask is that when we bumped from Doxygen 1.9.2 to 1.9.8, some parts of the docs where rendered in dark mode and we could not read any text. The solution was to change from `AUTO_LIGHT` to `LIGHT`. So I wonder if there is a "dark" setting somewhere else that we are not aware of.

**Comment by albert-github** [comment]
The user preference in respect to the dart / light mode is set in the browser settings.

**Comment by carlosgalvezp** [comment]
Alright, thanks! I'm not sure if I should close the issue, I think it makes sense to add this clarification in the code. Up to you :)
