### ISSUE TITLE
namespace clash with tagfile

### ISSUE THREAD

**Issue by aotto1968** [doxygen/doxygen#10427]
**Describe the bug**
I get the following example warning:
```
<unknown>:24283: warning: no matching file member found for 
MQ_EXTERN MK_STR libmqmsgque::MqHelpMsgque(void)
Possible candidates:
 'MQ_EXTERN MK_STR MqHelpMsgque(void)' at line 2910 of file /home/dev1usr/Project/NHI1/html/theLink/tclmqmsgque/tclmqmsgque.tag:msgque_mq.h
 'MQ_EXTERN MK_STR MqHelpMsgque(void)' at line 14011 of file <unknown>
 'MQ_EXTERN MK_STR MqHelpMsgque(void)' at line 5519 of file /home/dev1usr/Project/NHI1/html/theLink/javamqmsgque/javamqmsgque.tag:msgque_mq.h
 'MQ_EXTERN MK_STR MqHelpMsgque(void)' at line 3385 of file /home/dev1usr/Project/NHI1/html/theLink/vbmqmsgque/vbmqmsgque.tag:msgque_mq.h
 'MQ_EXTERN MK_STR MqHelpMsgque(void)' at line 2905 of file /home/dev1usr/Project/NHI1/html/theLink/pymqmsgque/pymqmsgque.tag:msgque_mq.h
 'MQ_EXTERN MK_STR MqHelpMsgque(void)' at line 2905 of file /home/dev1usr/Project/NHI1/html/theLink/rbmqmsgque/rbmqmsgque.tag:msgque_mq.h
 'MQ_EXTERN MK_STR MqHelpMsgque(void)' at line 2905 of file /home/dev1usr/Project/NHI1/html/theLink/phpmqmsgque/phpmqmsgque.tag:msgque_mq.h
 'MQ_EXTERN MK_STR MqHelpMsgque(void)' at line 2905 of file /home/dev1usr/Project/NHI1/html/theLink/perlmqmsgque/perlmqmsgque.tag:msgque_mq.h
 'MQ_EXTERN MK_STR MqHelpMsgque(void)' at line 2906 of file /home/dev1usr/Project/NHI1/html/theLink/gomqmsgque/gomqmsgque.tag:msgque_mq.h
 'MQ_EXTERN MK_STR MqHelpMsgque(void)' at line 3262 of file /home/dev1usr/Project/NHI1/html/theLink/libmqmsgque/libmqmsgque.tag:msgque_mq.h
 'MQ_EXTERN MK_STR MqHelpMsgque(void)' at line 3385 of file /home/dev1usr/Project/NHI1/html/theLink/csmqmsgque/csmqmsgque.tag:msgque_mq.h
 'MQ_EXTERN MK_STR MqHelpMsgque(void)' at line 3520 of file /home/dev1usr/Project/NHI1/html/theLink/ccmqmsgque/ccmqmsgque.tag:msgque_mq.h
 'MQ_EXTERN MK_STR MqHelpMsgque(void)' at line 19003 of file <unknown>
```

The problem is that my **TAGFILES** is composed with the data from a specific-source like *tcl* for *tclmqmsgque* and the data from a common-source called *libmqmsgque*. The "common-source" is required because I use *copybrief* and *copiedetails* from *libmqmsgque* to setup the final documentation for *tclmqmsgque*. At the glory end all *XXXmgsgque* tag **TAGFILES** used to build a kind of *index-documentation* (entry-page) which has links to the *XXXmqmsgque* documentation.

MY problem is that in the *XXXmqmsgque* **TAGFILE** (example: *tclmqmsgque*) also include the documentation from the *libmqmsgque* and THIS create the **FINAL** problem listed above.

**MY REQUIREMENT** 

1) OR → I want to control *WHAT* is documentated in the **TAGFILE**. I my case **NO** *libmqmsgque* definitions in the *tcllibmsgque* **TAGFILE**.
2) OR → If **multiple** TAGFILES are involved I want to chose a **LEADING-TAGFILE** used if a namespace-clash is recognized and finally the **warning** message would disappear

**Expected behavior**
I don't want the "warning"

**To Reproduce**
NO

**Version**
latest, 1.9.8

**Comment by albert-github** [comment]
I can imagine that you don't want the warnings but without an example it is not possible to tell what causes the problem, so:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

**Comment by aotto1968** [comment]
I think you have a problem with error-reporting → I miss a switch like *-debug* to gather all information you need and make it for the enduser maximun easy to report something.

**Comment by albert-github** [comment]
> I think you have a problem with error-reporting → I miss a switch like -debug to gather all information you need and make it for the end-user maximum easy to report something.

Most of the times it is hard to tell where the problem comes from and it is useful to see an example to "see" the thoughts of the end-user / things the end-user does.
Please explain what you mean with this and what you would like to have, maybe you could even write a pull request for it that would add this functionality.

**Comment by aotto1968** [comment]
I found a partial work-around → I take the "tag" file and filter-out the NOT wanted part with a POST-processing shell script. I try some xml-editor examples but finally end up with a TCL script.

**Comment by albert-github** [comment]
As there is no further information provided and OP has found a solution for his case we can conclude that this is not a bug / usage /not reproducible
