### ISSUE TITLE
Cannot find FLEX / BISON - Trouble installing with Windows FIX

### ISSUE THREAD

**Issue by classicrocker883** [doxygen/doxygen#10424]
**Describe the bug**
the follow error has a FIX I wrote below.

if you get this error for FLEX
```r
CMake Error at C:/Program Files/msys64/mingw64/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find FLEX (missing: FLEX_EXECUTABLE)
Call Stack (most recent call first):
  C:/Program Files/msys64/mingw64/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/msys64/mingw64/share/cmake/Modules/FindFLEX.cmake:264 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:156 (find_package)
```
---

or this error for BISON
```r
CMake Error at C:/Program Files/msys64/mingw64/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find BISON (missing: BISON_EXECUTABLE)
Call Stack (most recent call first):
  C:/Program Files/msys64/mingw64/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/msys64/mingw64/share/cmake/Modules/FindBISON.cmake:306 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:160 (find_package)
```
**Expected behavior**

**Screenshots**

**To Reproduce**
>git clone https://github.com/doxygen/doxygen.git
cd doxygen
mkdir build
cd build
cmake -G "Unix Makefiles" ..
make

### you can use `cmake -G "MSYS Makefiles" ..` or use MinGW instead of Unix

**Version**

**Stack trace**

**Additional context**

FIX
---
to fix this, follow these steps:

1. open C:\Program Files\msys64\mingw64\share\cmake\Modules\FindFLEX.cmake : line 111
2. open C:\Program Files\msys64\mingw64\share\cmake\Modules\FindBISON.cmake : line 95
3. add  `PATHS "C:/Program Files/msys64/usr/bin"` after `find_program(FLEX_EXECUTABLE NAMES flex win-flex win_flex` and before `DOCS "path...`
so it is like so:  
```cmake
find_program(FLEX_EXECUTABLE NAMES flex win-flex win_flex PATHS "C:/Program Files/msys64/usr/bin" DOC "path to the flex executable")
```
```cmake
find_program(BISON_EXECUTABLE NAMES bison win-bison win_bison PATHS "C:/Program Files/msys64/usr/bin" DOC "path to the bison executable")
```
you can also add `list(APPEND CMAKE_FIND_LIBRARY_SUFFIXES ".a")`  
and **libfl** to `find_library(FL_LIBRARY NAMES libfl fl
  DOC "Path to the fl library")`

**Comment by albert-github** [comment]
Isn't your fix not a fix that should be applied on the original files `FindFLEX.cmake` and `FindBISON.cmake` and be done by CMake?
Or shouldn't the path where `win-flex` / `win-bison` is installed by "MSYS" be added to the `path` variable of the system?

I don't think this is a doxygen problem (although here doxygen "suffers" from it) but a problem of CMake / MSYS.
