### ISSUE TITLE
Doxygen cannot include .aidl interfaces and enums to the documentation

### ISSUE THREAD

**Issue by golubevdmi** [doxygen/doxygen#10434]
**Describe the bug**
When I add .aidl files with enums and interfaces as a part of the doc, I expect to see there these fields. But seems doxygen ignores data without the public specifier

**Expected behavior**
interfaces and enums from .aidl files are in the doc

**To Reproduce**
Example with .aidl interface and enum that cannot be parsed and java explicit **public** interface and enum that there are in the doc

[issue-example.zip](https://github.com/doxygen/doxygen/files/13438995/issue-example.zip)

**Version**
doxygen 1.9.6, Windows 11 + Ubuntu 22.04 (WSL) 

**Additional context**
Based on the stackoverflow question

https://stackoverflow.com/questions/77448988/doxygen-cannot-include-aidl-interfaces-and-enums-to-the-documentation

**Comment by albert-github** [comment]
A proposed patch, pull request #10402 was created for this problem.

**Comment by golubevdmi** [comment]
> A proposed patch, pull request #10402 was created for this problem.

@albert-github  works for me
![image](https://github.com/doxygen/doxygen/assets/52494528/1d5f4203-b921-4b57-844b-08b145e1cc09)

**Comment by albert-github** [comment]
• Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.10.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
