### ISSUE TITLE
doxygen 1.9.6, and 1.9.8 don't produce CHM files

### ISSUE THREAD

**Issue by paule32** [doxygen/doxygen#10436]
Hello,
I have working under Windows 10, and MinGW64, I have activate:

GENERATE_HTMLHELP = YES
CHM_FILE = E:/Projekte/doc/chm/foo.chm
HHC_LOCATION = "E:/doxygen/hhc/hhc.exe"

nor 1.9.6 or 1.9.8 Version of doxygen produce the chm file.
I get error/warning.txt:
error: failed to run html help compiler on index.hhp

hhc.exe can be execute on the shell/console.

**Comment by albert-github** [comment]
Hard to tell what is wrong.
You wrote:
> hhc.exe can be execute on the shell/console.

does this mean that when you type `E:\doxygen\hhc\hhc.exe index.hhp` in the html directory you get the file `foo.chm` ?

What happens when you execute
```
doxygen -d extcmd Doxyfile
```

**Comment by paule32** [comment]
I double check the **CHM_FILE**.
In the documentation is placed as comment, that I can add a path.
But when I do this, doxygen can't find/produce the resulting path.
E.g.
- the source file root directory is ./doc
- the OUTPUT directive is set to ./doc/html
- the CHM_FILE = foo/bar.chm

then, doxygen will substitute the path to ./doc/html/foo/bar.chm.
and like it seems, it will get the source for .hhp under ./doc/html/foo.
as such, doxygen can't find .hhp project file, and/or don't create extra directory.

So, the current option is, to define:
CHM_FILE = bar.chm

then the .chm file will be created - but under the directory ./doc/html
and not under foo/ bar.chm.

This is not a problem itself, but it is a confusing style of path for others developers that don't know these facts.
Either you update the documentation, or (if it is possible) change the internal/external directory structures.

Hope this Information's can help you
Thanks for reading
paule32

**Comment by paule32** [comment]
In the attachment at Line 1524 (and up)
[packed.zip](https://github.com/doxygen/doxygen/files/13441744/packed.zip)

**Comment by albert-github** [comment]
With the give setting I cannot reproduce the problem
when I set 
```
OUTPUT_DIRECTORY       = doc
CHM_FILE               = foo/GetLastError.chm
```

I can reproduce the problem as an attempt is made to write the chm file as `doc/html/foo/GetLastError.chm` when creating the directory `doc/html/foo` beforehand everything works again.

In the documentation it is stated:
```
`CHM_FILE` The `CHM_FILE` tag can be used to specify the file name of the resulting .chm file. You can add a
path in front of the file if the result should not be written to the html output directory.
```
here it is not clear what is meant with `path`
1. is it a path relative to the current directory
2. is it an absolute path
3. is it a path relative to the `OUTPUT_DIRECTORY/HTML_DIRECTORY`

most likely the user would interpret it as the first possibility.
Furthermore the directory has to exist (most likely tis would be solved by means of the proposed pull request #8444)

**Comment by paule32** [comment]
# at Line: 71
OUTPUT_DIRECTORY = output

# at Lines: 1523/1524
CHM_FILE = chm/GetLastError.chm
# for normal usage, I expect that the directory "chm" will be created, but it does'nt.
# I get warnings.txt message: error: "failed to run html help compiler on index.hhp"

# but: this will work - it produce the .chm file directly in ./output/html
CHM_FILE = GetLastError.chm

# at Line: 1532
HHC_LOCATION = "E:/doxygen/hhc/hhc.exe"

# at Line: 1287
HTML_OUTPUT = html

I get the CHM file, all is done. But I have to copy chm from ./output/html directory
To reproduce, I attach my Doxyfile
[packed.zip](https://github.com/doxygen/doxygen/files/13442780/packed.zip)

**Comment by paule32** [comment]
for me, the issue can be close.
