### ISSUE TITLE
Linked files in IMAGE_PATH are not copied to output

### ISSUE THREAD

**Issue by gregwillits** [doxygen/doxygen#10431]
**Describe the bug**
My project uses Doxygen to generate HTML output from sources and markdown files. I have both png and pdf files in the IMAGE_PATH folder where the png is used as a thumbnail, but the PDF is the actual file to be viewed. So, the png will be used in an image tag, and, the PDF is used in a link, to open for higher resolution.

The PDF files from the /images folder are not being copied to the Doxygen output folder. PDF is not the issue, the same thing happens if a JPG or PNG are used in place of the PDF for the links.

**Expected behavior**
I expected all files that are in the /images folder, regardless of what they are, to be copied to the /html output folder.

I can understand that Doxygen is probably just picking up the files from the image tags, but in this use case, I think the simpler logic is to simply copy anything that is in the IMAGE_PATH to the output path. Or at least have a Copy All Image Path Files (Yes/No) option.

Or maybe there's another way to handle this, that I am not aware of.

**To Reproduce**
For example, I typically have some images in a dox_main.md file at the project root like this:
```
<div class="MImgBox">
<a href="Nifty-Overview-Diagram.pdf">Nifty Project Overview</a>
@image html nifty-overview-diagram.png width=400px
</div>
```

**Version**
1.9.8 on macOS

**Comment by albert-github** [comment]
It is reasonably clear but to be sure what is going on (so no misinterpretations) / make it reproducible:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

**Comment by albert-github** [comment]
Note that `<a href="Nifty-Overview-Diagram.pdf">Nifty Project Overview</a>` is a general link and doxygen does not really interpret the contents of the `href` part, you can copy the file to the html directory to add `Nifty-Overview-Diagram.pdf` to the setting [`HTML_EXTRA_FILES`](https://www.doxygen.nl/manual/config.html#cfg_html_extra_files)

**Comment by gregwillits** [comment]
Attached is a project. I have tried HTML_EXTRA_FILES. This idemonstrated in the project as well.

Thanks for your time.
[DoxIssue10431.zip](https://github.com/doxygen/doxygen/files/13418103/DoxIssue10431.zip)

**Comment by albert-github** [comment]
When I set `HTML_EXTRA_FILES = images\PCore-Block-Diagram.pdf` I see that the file is copied into the html directory and at that moment the link works, so I think that solves the issue (or did I miss something?)

**Comment by gregwillits** [comment]
For me, files from HTML_EXTRA_FILES  are not being copied to the html directory. I redid it several times and watched the output folder. I deleted the entire output every time I tried something different to make sure there was no caching effect happening.

**Comment by gregwillits** [comment]
Just because... here's a screen shot of settings using the GUI app, and results after running.

<img width="1509" alt="Results-10431" src="https://github.com/doxygen/doxygen/assets/248531/2d890468-4980-4e20-9c23-cd786dcf8bf2">

**Comment by albert-github** [comment]
I just noticed in your file that the name of the pdf for the "extra" test is not `PCore-Block-Diagram.pdf` but something like `PCore-Block-Diagram-Extra.pdf`

I see in the screenshot that you have `HTML_EXTRA_FILES = extra`, it should be `HTML_EXTRA_FILES = extra\PCore-Block-Diagram-Extra.pdf`

**Comment by gregwillits** [comment]
OHHHH -- HTML_EXTRA_FILES have to be explicitly named file by file!  (I just discovered that as you were posting as well.)

Yikes. Well, OK, that's functional, but yeah, a lot of extra work (there will be dozens of files in my case). So, feature request then would be to just include everything from a specific folder.

Anyway, I guess as it pertains to the point of my original post, this is closed.
