### ISSUE TITLE
Expression-bodied members (C#) with only <summary> are not hyperlinked in HTML

### ISSUE THREAD

**Issue by CodeSmile-0000011110110111** [doxygen/doxygen#10440]
**Describe the bug**
Several members (methods, properties) that are public and documented do not have a hyperlink in the class' list of properties, methods.

After some investigation it seems this happens under the following conditions:
- the member must be an expression body statement
- the member documentation only includes a summary tag
- EXTRACT_ALL must be false

See these, the light ones are not hyperlinked:
![image](https://github.com/doxygen/doxygen/assets/42713966/7443ea19-48ce-4c73-88e3-96159a5e03e9)

The affected methods do appear in the Classes/Class List navigation tree, but when you click on one, the page actually tries to scroll down, and then instantly jumps up to the list of methods:
![image](https://github.com/doxygen/doxygen/assets/42713966/ae38e02b-c8ad-4dfc-9a1d-3bfcfb758948)

**Expected behavior**
I expect these methods and properties to be fully hyperlinked and have documentation on the page.

**To Reproduce**

Doxyfile and source code is available here:
https://github.com/CodeSmile-0000011110110111/de.codesmile.editor.assetdatabase

I noticed that all affected members are expression-bodied members. Their doc is often notably simple:
```
		/// <summary>
		///     Removes all labels from the asset.
		/// </summary>
		public void ClearLabels() => Label.ClearAll(m_MainObject);
```

I can make them appear as expected in the HTML by merely adding a 'see' tag to the documentation. It seems to me that doxygen stumbles over expression-bodies members that only have a summary.

Note also that I tried renaming this method to BLEARGH and it still had the same issue after renaming or moving it within the file.

Another example, this is in the main file (Asset.cs) of a `public sealed partial class Asset` class:
```
		/// <summary>
		///     Returns the asset's main object.
		/// </summary>
		public Object MainObject
		{
			get => m_MainObject = LoadMain<Object>();
			set
			{
				SubAsset.SetMain(value, m_AssetPath);
				m_MainObject = value;
			}
		}

		/// <summary>
		///     Returns the type of the main asset.
		/// </summary>
		public Type MainObjectType => GetMainType(m_AssetPath);
```

The property with complex getter/setter is documented, the expression bodied member is not:
![image](https://github.com/doxygen/doxygen/assets/42713966/70f33cc6-eabf-4ead-9e32-42bbdce6e95b)

I changed the MainObjectType to normal bracket style and then it appeared as hyperlinked in the HTML output.

Generating documentation with EXTRACT_ALL set to true also documents/links these members correctly.

**Version**
1.9.6 and 1.9.8 both exhibit this behaviour.

**Comment by albert-github** [comment]
I think the main interpretation discrepancy lies in the fact that e.g. `ClearLabels()` has no detailed description, just a brief / summary description. I that case no detailed section for the function is created and hence also no hyperlink in the brief part.
Please have a look at the setting `ALWAYS_DETAILED_SEC=YES`

**Comment by CodeSmile-0000011110110111** [comment]
Thank you! Adding ALWAYS\_DETAILED\_SEC=YES fixed the issue.

I did try a lot of settings, just not that one. ;)
