### ISSUE TITLE
Search engine index generation is non-deterministic

### ISSUE THREAD

**Issue by ivan770** [doxygen/doxygen#10445]
**Describe the bug**

`html/search/*` files are non-deterministic when key collision occurs (`name` and `title` values are equal).

**Expected behavior**
Search engine index doesn't change between builds.

**To Reproduce**

Install Nix tooling, run `nix build nixpkgs#pipewire.doc --rebuild` on two different machines.
This will result in some files inside `html/search` directory being different.

**Version**
doxygen 1.9.7, NixOS 23.11

**Additional context**

I was able to fix this behavior by replacing `std::sort` with `std::stable_sort` here:
https://github.com/doxygen/doxygen/blob/c87ad3cbfbfe67a14e5078250178478719815dbb/src/searchindex_js.cpp#L489-L496

However, I'm not sure if that's a correct solution.

**Comment by albert-github** [comment]
I think that it is not good when results are non-deterministic. The key differences between `std::sort` and `std::stable sort` are (as I can see from https://en.cppreference.com/w/cpp/algorithm/sort and https://en.cppreference.com/w/cpp/algorithm/stable_sort):
- std::sort
  -  Sorts the elements in the range `[first, last)` in non-descending order. The order of equal elements is not guaranteed to be preserved. 
  - Complexity: `O(N·log(N))` comparisons, where `N` is `std::distance(first, last)`.
- std::stable_sort
  - Sorts the elements in the range `[first, last)` in non-descending order. The order of equivalent elements is guaranteed to be preserved. 
  - Complexity: `O(N·log(N)²)`, where `N = std::distance(first, last)` applications of cmp. If additional memory is available, then the complexity is `O(N·log(N))`.

There might be more causes for the non-deterministic  behavior though like the multi threading possibilities.
The extra complexity is also a factor but seen the remark:
> If additional memory is available, then the complexity is `O(N·log(N)).`

not really worrying (in my opinion).

Besides the usage of `std::sort` in `searchindex_js.cpp` there are a number of other places where it is used:
- classdef.cpp
- definition.cpp
- dirdef.cpp
- dotgfxhierarchytable.cpp
- doxygen.cpp
- filedef.cpp
- ftvhelp.cpp
- groupdef.cpp
- htmlhelp.cpp
- index.cpp
- memberlist.h
- moduledef.cpp
- namespacedef.cpp
- reflist.cpp

Though not all of these will require `std::stable_sort` as they are by nature already stable (as their entries are unique).

**Comment by ivan770** [comment]
> I think that it is not good when results are non-deterministic. The key differences between `std::sort` and `std::stable sort` are (as I can see from https://en.cppreference.com/w/cpp/algorithm/sort and https://en.cppreference.com/w/cpp/algorithm/stable_sort):
> 
>     * std::sort
>       
>       * Sorts the elements in the range `[first, last)` in non-descending order. The order of equal elements is not guaranteed to be preserved.
>       * Complexity: `O(N·log(N))` comparisons, where `N` is `std::distance(first, last)`.
> 
>     * std::stable_sort
>       
>       * Sorts the elements in the range `[first, last)` in non-descending order. The order of equivalent elements is guaranteed to be preserved.
>       * Complexity: `O(N·log(N)²)`, where `N = std::distance(first, last)` applications of cmp. If additional memory is available, then the complexity is `O(N·log(N))`.
> 
> 
> There might be more causes for the non-deterministic behavior though like the multi threading possibilities. The extra complexity is also a factor but seen the remark:
> 
> > If additional memory is available, then the complexity is `O(N·log(N)).`
> 
> not really worrying (in my opinion).
> 
> Besides the usage of `std::sort` in `searchindex_js.cpp` there are a number of other places where it is used:
> 
>     * classdef.cpp
> 
>     * definition.cpp
> 
>     * dirdef.cpp
> 
>     * dotgfxhierarchytable.cpp
> 
>     * doxygen.cpp
> 
>     * filedef.cpp
> 
>     * ftvhelp.cpp
> 
>     * groupdef.cpp
> 
>     * htmlhelp.cpp
> 
>     * index.cpp
> 
>     * memberlist.h
> 
>     * moduledef.cpp
> 
>     * namespacedef.cpp
> 
>     * reflist.cpp
> 
> 
> Though not all of these will require `std::stable_sort` as they are by nature already stable (as their entries are unique).

For now, I'll cover the search index since the only place where I caught some key collisions were `all_*.js` files, although a separate issue may be opened later if any generated results are not reproducible.

**Comment by albert-github** [comment]
Code of #10446 has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

(Issue was closed automatically by GitHub due to the used terminology in the pull request)

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.10.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
