### ISSUE TITLE
Additional custom HTML variable and conditional blocks

### ISSUE THREAD

**Issue by xkzl** [doxygen/doxygen#10456]
Hello,

Is there a way to add a custom variable and conditional block similarly to the one described in preprocessing?
```
 <!--BEGIN BLOCKNAME-->
 Some context copied when condition BLOCKNAME holds
 <!--END BLOCKNAME-->
 <!--BEGIN !BLOCKNAME-->
 Some context copied when condition BLOCKNAME does not hold
 <!--END !BLOCKNAME-->
```

I would like to define a custom variable in my Doxyfile PROJECT_GITLAB/PROJECT_GITHUB. 
(a github url to be referenced in my project description)

I also need to add some conditional checks to display github or gitlab logo depending on the url provided. 
Is that something easy to achieve ? Could you maybe help me with that ?

**Comment by albert-github** [comment]
- the mentioned example is not persistent and was also used for issue #10453 so
   - please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce this problem? Please don't add external links as they might not be persistent.
- Please show where you added / changed things as at the moment it is a bit unclear.

**Comment by xkzl** [comment]
The fork i provided contains the necessary information 

I eventually went using cmake for configuring my Doxyfile depending on my needs and environment. Same for any other files. I just turned it into Doxyfile.in

Cmake provides much more flexibility here.

You can close thank you.

**Comment by albert-github** [comment]
> The fork i provided contains the necessary information

The essential problem with this (compared to a compressed tar or a zip file) is that it is not presistent, the master version here might change.

I was not able to find in the repository what was intended.
