### ISSUE TITLE
The declaration of the private functions of the class is not colored in the source code.

### ISSUE THREAD

**Issue by traversebitree** [doxygen/doxygen#10458]
**Describe the bug**
The declaration of the private functions of the class is not colored in the source code.

**Expected behavior**
In the source code, private functions should be colored like public functions. I haven't tested if the protected functions are with the same 
 issue.

**Screenshots**
![image](https://github.com/doxygen/doxygen/assets/30373236/cf767201-7271-430f-9cd4-527c2b4b326d)

**To Reproduce**
Any header file, declare a class with private function declarations.

**Version**
Windows 11, 64-bit
doxygen-1.9.8

**Additional context**
I haven't tested if the protected functions are with the same 
 issue.

**Comment by albert-github** [comment]
With colored  you mean here hyperlinked?

From just the image it is hard to tell what is going on, there might be different reasons for it and from just an image of a par of a class it is hard to tell and not reproducible, so:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.
