### ISSUE TITLE
Markdown: Doxygen markers are taken into account even as part of an inline comment

### ISSUE THREAD

**Issue by enen92** [doxygen/doxygen#10467]
(sorry for opening so many issues, feel free to close)

**Describe the bug**
Not sure if this is a duplicate of https://github.com/doxygen/doxygen/issues/10465 or can be explained by https://github.com/doxygen/doxygen/issues/10465#issuecomment-1837495351 but doxygen markers (`/*!`) are taken into account when including markdown text making the overall include to fail. For example consider this section defined in markdown:

```
### 9.2. Doxygen

New classes and functions are expected to have Doxygen comments describing their purpose, parameters, and behavior in the header file. However, do not describe trivialities - it only adds visual noise. Use the Qt style with exclamation mark (`/*! */`) and backslash for doxygen commands (e.g. `\brief`).
```

When including this file in another page it only renders until `*/`:

<img width="1195" alt="image" src="https://github.com/doxygen/doxygen/assets/7375276/e223aa8e-03cd-46ad-93c9-2ee6be55a22e">

**Expected behavior**
Page stop should be ignored as the closing marker is part of an inline comment which hasn't been yet closed:

<img width="478" alt="image" src="https://github.com/doxygen/doxygen/assets/7375276/a2a3cb72-7877-40b4-ab63-1436c49df57f">

**Screenshots**
See above

**To Reproduce**
Sample project to reproduce:
[closing_tag_markdown.zip](https://github.com/doxygen/doxygen/files/13539543/closing_tag_markdown.zip)

**Version**
Master

**Comment by GerHobbelt** [comment]
🤔  Shouldn't the `` ` `` introducing the inline code chunk suppress the acting on `/*!` ? (Thinking about 'parser modes' here, which can be hairy business indeed as doxygen is not parsing a single "language" but rather a mix.)

Parsing MarkDown chunk --> encountering start of (inline) chunk chunk (`` ` ``) --> switching modes, suppressing `/*!` action and possibly a few others? --> parsing code chunk until terminating `` ` `` --> pop mode stack , switching back to parsing MarkDown, moving on...

(The idea being that `` `\brief` `` is also kept as-is, so surely there's some mode/context switching done already?)

**Comment by albert-github** [comment]
The escaping for the `\brief`  (and other commands) is don on a character by character base in markdown.cpp and more precise in `static QCString escapeSpecialChars(const QCString &s)` (when I'm not mistaken). The handling of things like `/*` / `*/` would be a bit more difficult but not impossible (I think).

@doxygen what do you think about adding the `&zwnj;`?
