### ISSUE TITLE
Enum defined via macro is not correctly resolved when a tagfile is added for the same namespace

### ISSUE THREAD

**Issue by emmenlau** [doxygen/doxygen#10489]
**Describe the bug**
I can successfully generate correct documentation for enum values, as long as I do not add my tagfiles. As soon as one of my tagfiles is added, doxygen will generate the documentation, but the link from the enum to its description is broken.

I think a relevant aspect is that the enum definition is in a namespace, and the tagfile contains definitions for that same namespace.

**Expected behavior**
The link from the enum to its definition should "just work".

**To Reproduce**
Here is the full example: [doxygen-issue-10489.zip](https://github.com/doxygen/doxygen/files/13697599/doxygen-issue-10489.zip)

It contains:
 - Folder `output-without-tagfile`: The correct output, the way I would expect it. Open the file `header_8hh.html` and click on any of the enum definitions (like `enum class bda::TestStandardEnumClass`), the link will work.
 - Folder `output-with-tagfile`: The same output when the supplied tagfile is used in `doxygen.cfg`. The links do not work. Open the file `header_8hh.html` and click on any of the enum definitions (like `enum class bda::TestStandardEnumClass`), the link will not work.

**Version**
1.9.8 (c2fe5c3e4986974eb2a97608b24086683502f07f) installed from the official website, running on Ubuntu 22.04 x86_64.

**Comment by emmenlau** [comment]
Thanks a lot for the consideration @albert-github !

Indeed, what you say matches my (naiive) observation. It looks as if the external namespace from the tagfile takes precedence over the project-local namespace.

When I link the tagfile to the external headers (using `tagfiles/tagfile.tag.xml=/some/path`) then symbols in the project in the namespace link to the external documentation. When the path is left away, the links are just broken and link to non-existing pages.

**Comment by emmenlau** [comment]
Hey, I'm kindly pinging this issue, because it does have quite a big impact for us, when multiple projects share a namespace (should be not too uncommon?)

**Comment by albert-github** [comment]
@emmenlau thanks for the ping, which version did you test last? When not the current doxygen version(1.12.0 released today, August 7, 2024) please test this version.

**Comment by emmenlau** [comment]
Dear @albert-github , indeed I can not reproduce the problem with current doxygen 1.12.0! Thanks a lot!

**Comment by albert-github** [comment]
@emmenlau 
Strange as when I take the example as provided I still have the problem.
Did the tagfiles/tagfile.tag.xml change as well in your case? If so please provide the file.

**Comment by emmenlau** [comment]
Hmm, I did check our documentation and was under the impression that at least one of the enum links worked. However now I can not recall if that enum was indeed in the namespace or not, so closing may have been hasty. I can not reproduce the fix, so the issue seems to persist!
