### ISSUE TITLE
Struct documentation is empty when tab  "classes" is set to visible="off" in layout file

### ISSUE THREAD

**Issue by rayment** [doxygen/doxygen#10500]
**Describe the bug**
Somewhere between 1.9.1 (which was working perfectly) and 1.9.8, a bug or feature has been introduced which is causing struct documentation to appear completely empty if and when the following is set in the layout file:

```xml
<tab type="classes" visible="no" title="">
    ...
</tab>
```

That is, the classes tab is set to invisible.

![Screenshot_20231220_195053](https://github.com/doxygen/doxygen/assets/75439366/7a8b916e-2318-417a-818f-a18e93b0297a)

The brief still appears in the header of the group or file:

![Screenshot_20231220_195225](https://github.com/doxygen/doxygen/assets/75439366/c8a51b97-b86a-4f5d-81f6-b5f2cbeb8f48)

In the screenshots above, this documentation is coming from a page of custom groups that I've defined. This is not related to the issue - generating documentation and viewing it directly from the header file in the Files tab has the same issue.

In the screenshots above, I was using `INLINE_SIMPLE_STRUCTS = YES`. If I set it back to `NO` and open the struct page, I get this:

![Screenshot_20231220_195453](https://github.com/doxygen/doxygen/assets/75439366/5086f8e2-64ae-40e2-b5b4-8f324fa75526)

The page is totally blank.

The struct in question:

```c
/**
 * @brief Single-precision floating-point 2D vector.
 *
 * 2D vectors may used for positions, rotations, velocities and other properties
 * pertaining to 2D space. Each vector @f$\vec{V}@f$has two axis components,
 * namely @f$(x,y)@f$.
 *
 * @since 1.0.0
 */
#ifdef DOXYGEN
typedef struct
Svec2_s
{
	Sfloat x, y;
} Svec2;
#else /* DOXYGEN */
ALIGN(4,
typedef struct
Svec2_s
{
	Sfloat x, y;
}) Svec2;
#endif /* DOXYGEN *
```

Though if I get rid of all the macro garbage, it makes no difference. This can be replicated with the following:

```c
/**
 * @brief Brief for a struct.
 *
 * Info for a struct blablabla.
 */
struct my_struct
{
    int x;
};
```

If I make the classes visible again, I get the 'Data Structures' page which I don't want, but the struct documentation works again:

![Screenshot_20231220_200806](https://github.com/doxygen/doxygen/assets/75439366/72f4933a-c515-44a8-8e7b-5d4d5a903652)

**Expected behavior**
As per the behavior in 1.9.1, the documentation for the struct should still generate and contain information despite hiding the 'Classes' / 'Data Structures' tab in the treeview / header.

**To Reproduce**

- Doxyfile: [Doxyfile.txt](https://github.com/doxygen/doxygen/files/13725148/Doxyfile.txt)
- Layout file: [layout.txt](https://github.com/doxygen/doxygen/files/13725159/layout.txt)

Of course, change the extensions as necessary.

These files have come directly from my public repo **[here](https://github.com/rayment/sticky)** after running `doxygen -u` and regenerating the layout with `doxygen -l layout.xml.new` and doing a quick compare (new features include `topics` and `concepts`).

**Version**
```
$ uname -a
Linux home 6.1.67-gentoo-x86_64 #1 SMP PREEMPT_DYNAMIC Thu Dec 14 18:15:03 AEDT 2023 x86_64 AMD Ryzen 7 PRO 5850U with Radeon Graphics AuthenticAMD GNU/Linux
```

```
$ lsb_release -a
LSB Version:    n/a
Distributor ID: Gentoo
Description:    Gentoo Linux
Release:        2.14
Codename:       n/a
```

```
Gentoo USE flags for Doxygen compilation:

USE="-clang -debug -doc -dot -doxysearch -gui -test (-sqlite%)"
```

```
$ doxygen -v
1.9.8
```

**Comment by albert-github** [comment]
It is hard to get through to the problem you describe, but I think it has to do wit the part you mention:
```
<tab type="classes" visible="no" title="">
...
</tab>
```
when the visibility of the parent is set to `no` this means that the element is not visible and thus also not its children (old situation was a bit inconsistent).
This has been changed in the 1.9.3 version.

So in case of
```
    <tab type="classes" visible="no" title="">
      <tab type="classlist" visible="yes" title="" intro=""/>
      <tab type="classindex" visible="$ALPHABETICAL_INDEX" title=""/>
      <tab type="hierarchy" visible="yes" title="" intro=""/>
      <tab type="classmembers" visible="yes" title="" intro=""/>
    </tab>
```
you now should use, in your case,
```
      <tab type="classlist" visible="yes" title="" intro=""/>
      <tab type="classindex" visible="$ALPHABETICAL_INDEX" title=""/>
      <tab type="hierarchy" visible="yes" title="" intro=""/>
      <tab type="classmembers" visible="yes" title="" intro=""/>
```
So this looks like usage.

When I interpreted the issue incorrect:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).

**Comment by rayment** [comment]
Regarding misinterpreting, I did read that dot-point but was in a bit of a rush sorry... I'll add a proper example once I get home!

I'll try the new XML too. Thanks.

**Comment by rayment** [comment]
@albert-github I suspect you haven't misinterpreted at all. The solution is indeed to simply comment out the entire classes section. This will:

- Hide the 'Data structures' tab and all child pages including the index.
- Still generate struct documentation.

Thank you!

For posterity sake, see here the result: [resolution_10500.zip](https://github.com/doxygen/doxygen/files/13739332/resolution_10500.zip)
