### ISSUE TITLE
no Copy Picture on \code or \endcode

### ISSUE THREAD

**Issue by paule32** [doxygen/doxygen#10523]
Hello,
is it possible to add a picture on left or right side of the \exampe{foo.cc} box,
so I could copy example code to clipboard, to paste it in the developer source code file ?

**Comment by albert-github** [comment]
It is not completely clean what you mean with `example{foo.cpp}`, so:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).
- Please also specify the **full** doxygen version used (`doxygen -v`).

In the 1.10.0 version the setting `HTML_COPY_CLIPBOARD` has been introduced, is this what you are looking for?

**Comment by paule32** [comment]
I get error message:

error: When enabling GENERATE_HTMLHELP the HTML_COPY_CLIPBOARD option should be disabled. I'll adjust it for you.
warning: The selected output language "german" has not been updated
since release 1.8.15.  As a result some sentences may appear in English.

I would create a CHM Windows Helpfile

**Comment by albert-github** [comment]
So when I understand it correctly you would like to have the `HTML_COPY_CLIPBOARD` for HTML Help.

- Is the `HTML_COPY_CLIPBOARD` functionality as visible when **not** using `GENERATE_HTMLHELP=YES` the functionality you are looking for?

It will probably be very hard to have this functionality in HTML Help though due to the limited possibilities of HTML Help and the fact that the native HTML Help is not supported anymore by MicroSoft (since quite a while).

**Comment by paule32** [comment]
No, the functionally will not display - with enabled = YES nor disable it with = NO
This is the (both type) screen shot:

![grafik](https://github.com/doxygen/doxygen/assets/3682603/6788abf3-1cab-44ae-b109-07d39b9950bf)

I am under Windows 10, and compiled HTML Help works - also .CHM files.
But no clipboard feature - thinking that is possible ? because it's html and javascript ?

what is the standard of help under windows `?

**Comment by paule32** [comment]
I am apology me !
The issue does not have to do with \example.
It is the \code{.cpp} issue !

So the Question should be:
Is it possible to add a copy Picture to the \code{.cpp} Option ?

**Comment by paule32** [comment]
in the stylesheet.css I have:
```
.copy-to-clipboard {
    content: "\1F4CB";
    font-family: 'Arial', sans-serif;
    margin-right: 5px;
}
```
I source.cc code I have:
```
/**
* <span class="copy-to-clipboard">CC</span>
 * \code{.cpp}
int foo(void) {
    try {
    ...
    }
    catch (exception& e) {
        handle_exception( e.what() );
        
        return EXIT_FAILURE;
    }   return EXIT_SUCCESS;
}
 * \endcode
 */
```
but no CC or Picture will be displayed.

**Comment by albert-github** [comment]
- So looks like the functionality you require is the functionality of `HTML_COPY_CLIPBOARD`
- So it looks like you are using doxygen 1.10.0
- How did you test the `HTML_COPY_CLIPBOARD` for HTML Help, as by default this functionality is disabled?
- I did a small test with the example: [example.tar.gz](https://github.com/doxygen/doxygen/files/13795104/example.tar.gz) and modified my local doxygen so I didn't have the error about `HTML_COPY_CLIPBOARD`. In the resulting chm file I didn't find an active area to do the copy paste.
- Just adding the image probably will probably not be sufficient.

> what is the standard of help under windows ?

Don't know its name by head but most likely "plain" html   is used, probably a good start to read upon is: https://softwarerecs.stackexchange.com/questions/36123/successor-of-alternative-to-html-help-workshop

**Comment by paule32** [comment]
I found a working example:
https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_copy_clipboard2

I could add above or below the \code Box a Button or Image.
But I would be nice, that I have the possibility, that doxygen does this for me.
But, no problem - it is not to hard to do it manually.
I could try to use it with ALIASES += ...

**Comment by albert-github** [comment]
What do you mean with "I found a working example:"?
I don't think it will work as it uses the same technique as used by doxygen and from my tests that didn't work (see my comment https://github.com/doxygen/doxygen/issues/10523#issuecomment-1872233378)
- best try yourself and report back

**Comment by paule32** [comment]
yes. you right !

![grafik](https://github.com/doxygen/doxygen/assets/3682603/2f766da0-753f-489d-949e-8a9d29d4dd12)
