### ISSUE TITLE
temporary files will not be deleted after compilation

### ISSUE THREAD

**Issue by paule32** [doxygen/doxygen#10524]
After compilation of the sources.cc to generate HTML / CHM Project, I have many temporary files with the Extension .tmp.
They will be not deleted after all - in the root/source/base directory.
I work under Windows 10

**Comment by albert-github** [comment]
- what are the names of these temporary files and on which directory are they located?
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent). **Don't inline the code / Doxyfile but create a compressed, tar or zip file!!**
- Please also specify the **full** doxygen version used (`doxygen -v`).

**Comment by paule32** [comment]
The name begin with a tilde ~
after this tilde two hh
after the two hh hex number
and as extendsion tmp

**Comment by albert-github** [comment]
In my previous comment https://github.com/doxygen/doxygen/issues/10524#issuecomment-1872231477there were 3 request and only of one request an attempt has been made to answer, the other 2 have to be answered as well!

The file name does not ring a bell and therefor an example is necessary / the only way we can try to reproduce the problem.

**Comment by paule32** [comment]
sorry for that:  
[packed.zip](https://github.com/doxygen/doxygen/files/13800809/packed.zip)

**Comment by albert-github** [comment]
When I run the given example (had to disable `HTML_FOOTER` as `empty.html` is not provided and also the file `Doxyfile.Server.Layout` is not provided) I don't see any remaining temporary files,

- Any messages on the terminal when running `doxygen`?
- What is in `warnings.log`?

**Comment by paule32** [comment]
This are the console output:

warning: The selected output language "german" has not been updated
since release 1.8.15.  As a result some sentences may appear in English.

There is a warning.txt instead a warning.log - I have added them to the zip archive.
- no warnings except on line 56 of BoostServer.cc - below \endcond - nowhere else an error.

[packed.zip](https://github.com/doxygen/doxygen/files/13804366/packed.zip)

**Comment by paule32** [comment]
New zip file:
[packed.zip](https://github.com/doxygen/doxygen/files/13804388/packed.zip)

changes in warning.txt (log):
\a_currentVersion  and
\a_currentAuthors

not found.

**Comment by albert-github** [comment]
Strange, On the console I only get the warning about the German translation and in warnings.txt I get:
```
.../BoostServer.cc:413: warning: Conditional section with label 'german' does not have a corresponding \endcond command within this file.
.../BoostServer.cc:198: warning: found documented return type for dBaseRelease::handle_exception that does not return anything
.../BoostServer.cc:483: warning: argument 'uint32_t' of command @param is not found in the argument list of dBaseRelease::responseHeader(uint32_t bcode, uint32_t btype, uint32_t length)
.../BoostServer.cc:483: warning: argument 'uint32_t' of command @param is not found in the argument list of dBaseRelease::responseHeader(uint32_t bcode, uint32_t btype, uint32_t length)
.../BoostServer.cc:483: warning: argument 'uint32_t' of command @param is not found in the argument list of dBaseRelease::responseHeader(uint32_t bcode, uint32_t btype, uint32_t length)
.../BoostServer.cc:483: warning: The following parameters of dBaseRelease::responseHeader(uint32_t bcode, uint32_t btype, uint32_t length) are not documented:
  parameter 'bcode'
  parameter 'btype'
  parameter 'length'
```
(running doxygen 1.10.0 (ebc57c6dd303a980bd19dd74b8b61c8f3f5180ca) on windows 10).

And I don't see any temporary files either.

**Comment by paule32** [comment]
Could it be, that Microsoft Help Compiler HHC.EXE produce a .\temp Directory ?
I don't have test it, yet - but I thinking on ...
And when this Directory is not Empty, the temporary files would not be delete ?

I make a screen shot, so I hope that you can see the Problem.
The picture coming from Windows 10 Desktop 64-Bit Pro.

![grafik](https://github.com/doxygen/doxygen/assets/3682603/9730f289-269d-455a-ab7e-e11af9d079a8)

**Comment by albert-github** [comment]
In the image you show the result of `warnings.deu.log` whilst in the `Doxyfile.Server.chm.DEU.dark.ini` we have the line: `WARN_LOGFILE           = warnings.txt`, so this is weird.

Furthermore I see in `BoostServer.cc`:
```
    411 /**
    412  * \class  Time
    413  * \cond german
    414  * \brief  Informationen für die Klasse Date, die verschiedene Funktionen
    415  *         zur Bearbeitung von Zeit-Werte bereitstellt.
    416  *
    417  * \since  \a_currentVersion
    418  * \author \a_currentAuthors
    419  */
```
so this looks to me like a non-terminated conditional block (also seen that all other blocks are open and closed).


Looks like you use MSYS2, what happens when you use the native (distributed 1.10.0 doxygen version) in a "normal" command prompt?

**Comment by paule32** [comment]
ok. I fixed the mistake, you mentioned.
When I start doxygen.exe -V in MS-DOS (Command Prompt) Console from Microsoft Windows Desktop,
nothing happends.
I change the slashses / to backslashes \ , and double backslashes \\ in Path, and EXE direction.
But nothing happends.

Doxygen.exe is know in the Env-Path Variable, so, when I type:  doxygen.exe -V
I get this output:

E:\…ojekte\RAD11Components\Help\pascal_remote_assembly\src>doxygen Doxyfile.Server.chm.DEU.dark.ini
warning: The selected output language "german" has not been updated
since release 1.8.15.  As a result some sentences may appear in English.

I back-rename  Doxyfile.Server.chm.DEU.dark.ini  to  Doxxfile
and start doxygen with, and without the extend:
E:\doxygen.exe
E:\doxygen.exe Doxyfile

but the same like I describe before - nothing happends - no final output, but warning message.

I used the latest Version 1.10.0 for Windows (the Release zip archive, that you provide on github).

**Comment by albert-github** [comment]
Strange.
You wrote:

> Doxygen.exe is know in the Env-Path Variable, so, when I type: doxygen.exe -V
> I get this output:
> 

is the output part starting with `E:\...`?


- What happens when you give `where doxygen`?
- The above should give a full path plus executable, what happens when you start this with `-V` (might need some double quotes around it when there are special characters in the pathnames.

**Comment by paule32** [comment]
This is on the Microsoft Console:

E:\…ents\Help\pascal_remote_assembly\src\dox\deu\dark\html>where doxygen
E:\msys64\mingw64\bin\doxygen.exe

E:\…ents\Help\pascal_remote_assembly\src\dox\deu\dark\html>doxygen -V
1.10.0 (ebc57c6dd303a980bd19dd74b8b61c8f3f5180ca)
    with sqlite3 3.42.0 and clang support 13.0.0.

**Comment by albert-github** [comment]
This looks all OK.
What happens when you start:
```
E:\msys64\mingw64\bin\doxygen.exe Doxyfile.Server.chm.DEU.dark.ini
```
in the directory where the `Doxyfile.Server.chm.DEU.dark.ini` resides` ?

**Comment by paule32** [comment]
```
Microsoft Windows [Version 10.0.22000.2538]
(c) Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\Jens Kallup>E:

E:\>setpath.bat

E:\>doxygen -V
1.10.0 (ebc57c6dd303a980bd19dd74b8b61c8f3f5180ca)
    with sqlite3 3.42.0 and clang support 13.0.0.

E:\>where doxygen.exe
E:\msys64\mingw64\bin\doxygen.exe

E:\>cd \Projekte\RAD11Components\Help\pascal_remote_assembly\src

E:\Projekte\RAD11Components\Help\pascal_remote_assembly\src>rm -rf dox

E:\Projekte\RAD11Components\Help\pascal_remote_assembly\src>dir Doxyfile.Server.chm.DEU.dark.ini
 Datenträger in Laufwerk E: ist Volume
 Volumeseriennummer: C26D-F39D

 Verzeichnis von E:\Projekte\RAD11Components\Help\pascal_remote_assembly\src

2024-01-01  16:53             8.391 Doxyfile.Server.chm.DEU.dark.ini
               1 Datei(en),          8.391 Bytes
               0 Verzeichnis(se), 396.914.192.384 Bytes frei

E:\Projekte\RAD11Components\Help\pascal_remote_assembly\src>dir dox
 Datenträger in Laufwerk E: ist Volume
 Volumeseriennummer: C26D-F39D

 Verzeichnis von E:\Projekte\RAD11Components\Help\pascal_remote_assembly\src

Datei nicht gefunden

E:\Projekte\RAD11Components\Help\pascal_remote_assembly\src>E:\msys64\mingw64\bin\doxygen.exe Doxyfile.Server.chm.DEU.dark.ini
warning: ignoring unsupported tag 'HTML_CODE_FOLDING' at line 220, file Doxyfile.Server.chm.DEU.dark.ini
warning: ignoring unsupported tag 'HTML_COPY_CLIPBOARD' at line 221, file Doxyfile.Server.chm.DEU.dark.ini

E:\Projekte\RAD11Components\Help\pascal_remote_assembly\src>dir E:\doxygen\bin
 Datenträger in Laufwerk E: ist Volume
 Volumeseriennummer: C26D-F39D

 Verzeichnis von E:\doxygen\bin

2024-01-01  13:08    <DIR>          .
2024-01-01  13:09    <DIR>          ..
2024-01-01  13:08        23.377.920 doxygen.exe
2024-01-01  13:08         1.456.640 doxyindexer.exe
2024-01-01  13:08         1.265.664 doxysearch.cgi.exe
2024-01-01  13:08        15.467.520 doxywizard.exe
2022-08-26  09:56    <DIR>          html
2024-01-01  13:08        81.839.104 libclang.dll
2022-08-26  10:32           221.184 pas2dox.exe
2003-10-13  20:15           430.592 pas2h.exe
               7 Datei(en),    124.058.624 Bytes
               3 Verzeichnis(se), 396.914.192.384 Bytes frei

E:\Projekte\RAD11Components\Help\pascal_remote_assembly\src>E:\doxygen\bin\doxygen -V
1.10.0 (ebc57c6dd303a980bd19dd74b8b61c8f3f5180ca)
    with sqlite3 3.42.0 and clang support 13.0.0.

E:\Projekte\RAD11Components\Help\pascal_remote_assembly\src>E:\doxygen\bin\doxygen.exe Doxyfile.Server.chm.DEU.dark.ini
warning: The selected output language "german" has not been updated
since release 1.8.15.  As a result some sentences may appear in English.


E:\Projekte\RAD11Components\Help\pascal_remote_assembly\src>dir dox
 Datenträger in Laufwerk E: ist Volume
 Volumeseriennummer: C26D-F39D

 Verzeichnis von E:\Projekte\RAD11Components\Help\pascal_remote_assembly\src

Datei nicht gefunden

E:\Projekte\RAD11Components\Help\pascal_remote_assembly\src>

![grafik](https://github.com/doxygen/doxygen/assets/3682603/6777c9e7-9a95-4ad9-aa11-bcdb2a953f6c)

```

**Comment by albert-github** [comment]
You should now have the line:
```
error: tag OUTPUT_DIRECTORY: Output directory './dox/deu/dark' does not exist and cannot be created
```
in the file pointed to by `WARN_LOGFILE`.
- is this correct

When correct create the directory tree `dox/deu/dark`, there is a PR for this (don't know by head which number) to fix this.
- rerun doxygen

**Comment by paule32** [comment]
This is the Windows Console Batch Script:
```
:: -----------------------------------------------------------------
:: File:   doxygen.dos.bat
:: Author: (c) 2024-01-01 Jens Kallup - paule32
:: All rights reserved
::
:: only for education, and non-profit usage !
::
:: This is the Windows 10 64-Bit Pro Command Line Batch File script
:: file to create the documentation.
:: -----------------------------------------------------------------
@echo off

:: Windows Volume E: must be exists !
::
:: DOXYGENPATH = E:\doxygen\bin  -  the path to the doxygen Version 1.10.0
:: DOXYGEN     = doxygen.exe     -  the executable file of doxygen
::
set DOXYGENPATH=E:\doxygen\bin
set DOXYGEN=%DOXYGENPATH%\doxygen.exe

:: set source directory - E:\temp\src
set SRC=E:\temp\src

:: switch to Windows Volume
E:
cd \

:: create directories
md E:\temp
md E:\temp\src

:: enter TEMP directory
cd E:\temp\src

:: make sub directories
mmkdir temp
md  dox
md  dox\deu
md  dox\deu\dark
md  dox\deu\dark\html

:: 1.10.0
echo %DOXYGEN$

:: try to create create the CHM documentation
%DOXYGEN% %SRC%\Doxyfile.Server.chm.DEU.dark.ini
```
And this is the MSYS-2 POSIX like Terminal Script on Windows 10 64 Bit Pro:
```
#!/bin/bash
# -----------------------------------------------------------------
# File:   build.sh
# Author: (c) 2024-01-01 Jens Kallup - paule32
# All rights reserved
#
# only for education, and non-profit usage !
#
# This is the MSYS2 Windows 10 64-Bit Pro MinGW-64 script file to
# create the documentation.
# It will work under MSYS2.
# -----------------------------------------------------------------
PWD=$(pwd)
SRC=$(echo "${PWD}")

TEMP="temp"
TMP=$(echo "${PWD}/${TEMP}")

# 1.10.0
DOXYGEN="/E/doxygen/bin/doxygen.exe"

rm -rf ${SRC}/dox
rm -rf ${TMP}/*.tmp

mkdir -p ${SRC}/dox/deu/dark

${DOXYGEN} ${SRC}/Doxyfile.Server.chm.DEU.dark.ini
cp ${SRC}/dox/deu/dark/html/server.dark.deu.chm ${SRC}/dox/server.dark.deu.chm

#rm -rf ${SRC}/dox/deu
#rm -rf ${TMP}/*.tmp
```
![grafik](https://github.com/doxygen/doxygen/assets/3682603/97ebb922-9e41-4044-acf8-562a7b8086dd)

something Voodoo ?? - seems to work, now.

**Comment by albert-github** [comment]
Well probably systematic searching / looking at paths etc. solved the issue.

So I think the problem was usage.
