### ISSUE TITLE
no Unicode convert from German Umlauts

### ISSUE THREAD

**Issue by paule32** [doxygen/doxygen#10526]
Doxygen does not convert German Umlauts to Entities - like ä for &auml: or Ä for &Auml; and so on for ü. ö. Ü. Ö, and ß.

![grafik](https://github.com/doxygen/doxygen/assets/3682603/2c617dd6-5558-4f01-9df5-5ee9e69a5178)

[packed.zip](https://github.com/doxygen/doxygen/files/13800778/packed.zip)

**Comment by albert-github** [comment]
A bit strange as I would have expected that setting `CHM_INDEX_ENCODING     = UTF-8` would give good results but it doesn't.
When I disable this setting it looks all OK to me though.
(Maybe also a relict from the past).
