### ISSUE TITLE
How to generate docs. in the same namespace in C++ and C#

### ISSUE THREAD

**Issue by ikillery** [doxygen/doxygen#10530]
**Describe the bug**
We are writing API Doc for a SDK, which support C++ and C# API.
As usually, I named the same namespace name for both C++ and C# API
But they are mixed in the docs. generated by doxygen ( C# API definitions are also recognized as C++ API)

**Expected behavior**
I want to generate Doc for C++ and C# API together, within the single doxygen configuration

**Screenshots**
I try to add to different Group (doxygen concept), and this is what I got now.
![image](https://github.com/doxygen/doxygen/assets/52007947/11b52609-dd35-4645-a655-8a71351a0bb6)

**To Reproduce**
in xxx.h
```C++
/**
 *  @defgroup CPPAPI C++ API
 */

/// @ingroup CPPAPI
/// @namespace WindowsPBE
namespace WindowsPBE
{
...
}
```

in xxx.cs
```C++
/**
 *  @defgroup CSAPI C# API
 */

/// @ingroup CSAPI
/// @namespace WindowsPBE
namespace WindowsPBE
{
...
}
```

**Version**
Windows
V1.9.8

**Comment by albert-github** [comment]
Most likely this is caused by the fact that the namespaces have the same name and as such joined together.
To be able to investigate further:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).

**Comment by ikillery** [comment]
> Most likely this is caused by the fact that the namespaces have the same name and as such joined together. To be able to investigate further:
> 
> * Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).

run the build.ps1 in powershell, and the html generated in folder 'html'

![image](https://github.com/doxygen/doxygen/assets/52007947/07eedf87-1dca-49cf-bd4a-2431163a8861)

[doxygen_question.zip](https://github.com/doxygen/doxygen/files/13811212/doxygen_question.zip)

**Comment by albert-github** [comment]
When I understand everything correct it are in fact 2 separate APIs and are not related except probably for the underlying library that is called. The user will only one one of these 2 APIs at the same time, so I think it is more logical to have a separate document for the C++ API and one document for the C# API.

As the code is shown now doxygen sees just 1 namespace and will merge both parts together with the effects as indicated.

**Comment by ikillery** [comment]
> When I understand everything correct it are in fact 2 separate APIs and are not related except probably for the underlying library that is called. The user will only one one of these 2 APIs at the same time, so I think it is more logical to have a separate document for the C++ API and one document for the C# API.
> 
> As the code is shown now doxygen sees just 1 namespace and will merge both parts together with the effects as indicated.

OK. Thanks !
