### ISSUE TITLE
thick space in latex formula causes error

### ISSUE THREAD

**Issue by ajmay81** [doxygen/doxygen#10552]
i.e. the `\;` latex command in math mode. This is a regression in Doxygen 1.10.0, it did not occur with 1.9.8. An example Fortran file `test.f90`:
```
!> test doxygen
!>
!> some formula \f$U^{\;\;i_1}_{ac}\f$ included.
subroutine test
end subroutine test
```
Generates:
```
/host> doxygen Doxyfile 1>/dev/null
/host/test.f90:4: warning: End of comment block while inside formula.
********************************************************************
Error in file /host/test.f90 line: 6, state: 10(ModuleBody)
********************************************************************

```
This was with doxygen built from `doxygen-1.10.0.src.tar.gz`.

**Comment by albert-github** [comment]
Looks like:
b6018c30bcf010fd709aaeec18f9a385b0de5ecc is the first bad commit
~~~
commit b6018c30bcf010fd709aaeec18f9a385b0de5ecc
Author: albert-github <albert.tests@gmail.com>
Date:   Mon Dec 18 16:29:40 2023 +0100

    Incorrect handling of `\include{doc}` for Fortran


 src/commentcnv.l     | 14 +++++++++++---
 src/fortranscanner.l | 42 +++++++++++++++++++++++++++++++++++++++++-
 2 files changed, 52 insertions(+), 4 deletions(-)
~~~

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #10557

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.11.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Comment by ajmay81** [comment]
I don't know if this warrants a new issue or if it's a continuation of this one, but a semi-colon after a formula causes trouble. An example `test.f90`:
```
!> test doxygen
!>
!> A formula \f$A\f$; followed by a semi-colon
subroutine test
end subroutine test
```
Generates:
```
/host> doxygen Doxyfile 1>/dev/null
********************************************************************
Error in file /host/test.f90 line: 6, state: 10(ModuleBody)
********************************************************************
/host> doxygen --version
1.11.0
```
There is no such problem if the semi-colon is changed to a comma.

**Comment by albert-github** [comment]
@ajmay81 Please create a new issue for this.
