### ISSUE TITLE
Incorrectly closed markdown code block causes doxygen to forget about consectuive macro definitions

### ISSUE THREAD

**Issue by Reisz** [doxygen/doxygen#10567]
**Describe the bug**
When a markdown code block is closed incorrectly (extra space at the start of the line), macro definitions after that documentation block to emit `documentation for unknown define` warnings. The macros will also not show up in the generated file documentation.

**Expected behavior**
The markdown error should not affect other items.

**To Reproduce**
```c++
/** @file */

/**
 * ```
 *  ```
 */
void test();

/** test */
#define TEST 123
```

Notice the extra space in line 5.

Swapping the macro and function declaration (with documentation blocks attached) also "fixes" the issue.

**Version**
Doxygen 1.10.0 Windows 64bit

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).
