### ISSUE TITLE
Some of the functions in the resulting xml file end with a line number of -1

### ISSUE THREAD

**Issue by lcf262412** [doxygen/doxygen#10563]
I wanted to parse the xml to get the functions in the project.
I located the <location> tag of each function. I understood that bodystart bodyend in the secondary tag was the start line number of the function, but I found that some functions had bodyend -1 while processing.
The actual example we encountered was this：
```
<location file="eventql/deps/3rdparty/spidermonkey/mozjs/js/src/jit/arm/Simulator-arm.cpp" line="422" column="10" bodyfile="eventql/deps/3rdparty/spidermonkey/mozjs/js/src/jit/arm/Simulator-arm.cpp" bodystart="618" bodyend="-1"/>
```

**Comment by albert-github** [comment]
Without an example it is hard / impossible to tell, so
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).
- Please also specify the **full** doxygen version used (`doxygen -v`).

**Comment by albert-github** [comment]
The version 1.8.17 is a bit old , the current doxygen version is 1.10.0
It looks like the given settings file is not from the 1.8.17 version either but from a newer version (at least 1.9.7)
The given project is not persistent, quite dead and is very large but looking at the file mentioned in the line given I managed to find the file "Simulator-arm.cpp" and run it with doxygen.

Running the file with 1.8.17 I found the mentioned line, running it wit the curren doxygen version the line was corrected to:
```
<location file="Simulator-arm.cpp" line="422" column="10" bodyfile="Simulator-arm.cpp" bodystart="618" bodyend="939"/>
```
(looks like to be corrected since doxygen version 1.9.3)

I think the problem has been solved in the mean time

**Comment by lcf262412** [comment]
it works. After updating to 1.9.7 this issue was resolved, thank you.

**Comment by albert-github** [comment]
Why updating to 1.9.7 and not the current 1.10.0 doxygen version?

**Comment by lcf262412** [comment]
Ok, I tried to use the latest version. Thank you for your advice

**Comment by lcf262412** [comment]
I want the source code of functions to match quickly with function names in XML.
I want to know how the data at the end of names like 'namespacelinenoise__ng_1a645904197c5a052b7585545752067e31' in XML outputs is calculated to resemble a hash value.

**Comment by lcf262412** [comment]
I want the source code of functions to match quickly with function names in XML. If possible, I would like to know how the data at the end of names like 'namespacelinenoise__ng_1a645904197c5a052b7585545752067e31' in the XML output format, resembling a hash value such as '1a645904197c5a052b7585545752067e31', is calculated. I intend to apply a similar process to the source code for swift matching with corresponding functions in the XML.

**Comment by albert-github** [comment]
It is indeed a hash more precise a md5, se deps/libmd5.
I don't know whether it is a good idea to search through the internal md5 hash for outside references, probably better would be to search through the name.

For the implementation see especially the function `MD5SigToString` and its usage in the doxygen code.
Note further that sometimes some extra characters are added in front of the has like `r_` or `g` and that also sometimes there are multiple hashes  concatenated.

**Comment by lcf262412** [comment]
Thank you, this was extremely helpful.
