### ISSUE TITLE
duplicates config tags ?

### ISSUE THREAD

**Issue by paule32** [doxygen/doxygen#10565]
Hello,
I found three DoxyFile config dupplicates, and I don't know why they exist's:
```
DOXYFILE_ENCODING                = UTF-8
INPUT_ECODING                    = UTF-8
INPUT_FILE_ENCODING              = UTF-8
```
not the config Value's confuse me, but the Tag's.

**Comment by albert-github** [comment]
Did you readup in the documentation about these values or in a generated default setting file (i.e. `doygen -g Doxyfile`)?

**Comment by paule32** [comment]
I read it in the generated Doxyfile output (and doxywizard).
Not so confused, but I wonder me, why there are three encodings Tag's.

**Comment by albert-github** [comment]
All for flexibility. serve different purposes:
- DOXYFILE_ENCODING` Encoding of the Doxyfile
- `INPUT_ENCODING` General encoding of source files
- `INPUT_FILE_ENCODING` Specific encoding of some individual source files as in large projects different developers (e.g. from different countries) might use diffrent encodings
