### ISSUE TITLE
Modules list not generated with Doxygen 1.10

### ISSUE THREAD

**Issue by omarcou** [doxygen/doxygen#10562]
**Describe the bug**
The modules list is not (at least not always) generated when using Doxygen 1.10.

**Expected behavior**
In a documentation generated with a previous version of Doxygen (1.9.1 for example), when we define a tab usergroup inside a layout xml file that contains a tab modules:
- A modules.html file is generated.
- When opening the index file, if we hover with the mouse the tab corresponding to the usergroup, a dropdown menu appear with the contents of the usergroup including the modules list among its items.

**Actual behavior**
- No modules.html is generated.
- When opening the index file, if we hover with the mouse the tab corresponding to the usergroup, the dropdown menu does not contain an item for the modules list.

**Screenshots**
![IndexWithDogygen1_9_NoBug](https://github.com/doxygen/doxygen/assets/156814655/1d8f6f01-b724-4bc9-83eb-4a1703a32058)
![IndexWithDogygen1_10_Bug](https://github.com/doxygen/doxygen/assets/156814655/3e7ff398-4b81-4680-bb6b-42db39f94733)

**To Reproduce**
Run the bat script contained in the reproducer (after editing to set some variables appropriately for your machine) contained in file reproducerBugModulesList.zip.
[reproducerBugModulesList.zip](https://github.com/doxygen/doxygen/files/13951146/reproducerBugModulesList.zip)

**Version**
Doxygen version used: 1.10.0
Platform:  Windows 10

**Comment by albert-github** [comment]
Due to the implementation of C++ modules the name "modules" is now used for the C++ modules.
The old "modules" has been renamed to "topics".
See also https://github.com/doxygen/doxygen/issues/3319#issuecomment-1720923984

I think the problem is usage and you have to adapt your layout file.

**Comment by omarcou** [comment]
Thanks for the information, replacing the type "modules" by type "topics" seems to work fine.
