### ISSUE TITLE
Doxyfile works from GUI, but not from CLI

### ISSUE THREAD

**Issue by gregwillits** [doxygen/doxygen#10577]
**Describe the bug**
My project's doxyfile has always used relative source code and destination directories (../Source and ../DoxOut). This has always worked using either eclox Eclipse plugin, or DoxyWizard.

Using CLI `doxygen [doxyfile]` the command complains neither of the directories exist.

The key directory structure is:
```
/Project
    /Source (source code)
    /DoxIn (image, assets, etc.)
    /DoxOut (html output)
```

**Screenshots**

<img width="751" alt="DoxyWizard-Preview" src="https://github.com/doxygen/doxygen/assets/248531/15b2bdfc-631b-4386-ad55-a3a64bcdf476">

<img width="830" alt="Doxygen-CLI-Result" src="https://github.com/doxygen/doxygen/assets/248531/61d614b9-2fd5-46f6-83b6-26f050bb59ba">

**To Reproduce**
Type doxygen, then drag the doxyfile onto Terminal to ensure the correct path is being used.

**Version**
Doxygen 1.9.8 on macOS 

**Additional context**
I have symlinked /Applications/Doxygen/Contents/Resources/doxygen as /usr/local/bin/doxygen

**Comment by albert-github** [comment]
I cannot test it as I don't have a Mac but I'm wondering when starting doxygen from the command line, from which directory are you doing it (image doesn't tell me. but I have the feeling that it is a "root" or "home" directory)? It should be in your case from `.../DoxIn`, here it should be the same as the directory specified in the doxywizard as working directory.

**Comment by doxygen** [comment]
I'm pretty sure the issue is because doxygen is run from the wrong directory indeed.
