### ISSUE TITLE
problem to parse the `/*` ... `*/` C-style-comment in the documentation section.

### ISSUE THREAD

**Issue by aotto1968** [doxygen/doxygen#10589]
Hi, I use a `*.doc` file to add **doxygen-only** documentation to a project. The file look like: `/** ... **/`.

In addition I use the `vim` editor with the `vim:syntax=cpp.doxygen` configuration to highlight *doxygen* code proper.

The problem start if `/*` and `*/` com up in the documentation itself
1. in a `~~~~ ... ~~~~`-section, `\code ... \endcode`-section
2. in a `<tt>...</tt>`-section

for 1) The *code*-section the `/*`.. require NO decoration **BUT** the `vim-plugin` does NOT recognize the *code*-section and **miss**-format the `vim`-editor output. The `*/` is recognized as the `/**` *close*-statement.

If I decorate the `/*` in a *code*-section with `\/\*`.. than the `vim`-plugin is **ok** bit the *doxygen*-output put the `\/\*`... decoration into the *doxgen*-output as it is.

for 2) same issue like (1) for `<tt>...</tt>`-section **but** the `\/\*`…-decoration is **require**, without `\/\*`…-decoration an **parse**-error is reported: `warning: Reached end of file while still inside a (nested) comment..`. The problem is that a `\/\*`…-decoration is required **and** later show-up in the documentation.

→ I would require a **doxygen-only-doc** file WITHOUT the requirement of the `/** ... **/` decoration encapsulation.

**Comment by albert-github** [comment]
I don't understand what the problem is, is t a problem with doxygen or with vim?
In the later case it should be reported with the vim maintainers.
In case it is a doxygen problem please show some code (source+configuration file in a, compressed, tar or zip file!) that gives problems, best to illustrate it as well with some images

**Comment by aotto1968** [comment]
It is primary a *doxygen* problem because the `<tt>...</tt>` (2) section has nothing todo with vim-plugin.

**Comment by albert-github** [comment]
Still I don't understand how it is a doxygen problem so
- please show some code (source+configuration file in a, compressed, tar or zip file!) that gives problems, best to illustrate it as well with some images
- Please also specify the **full** doxygen version used (`doxygen -v`).

**Comment by albert-github** [comment]
This is not valid code as nested comments are not allowed in C / C++.
In some places doxygen is a bit more relaxed about this but I can imagine that e.g. vim does not take this into account.

**Comment by aotto1968** [comment]
~~~~
#INPUT = test-1.doc
INPUT = test-2.doc

GENERATE_HTML = YES

PROJECT_NAME = "Test"
PROJECT_NUMBER = 1.0
PROJECT_BRIEF = "bug with comment in <tt>"
~~~~

============================================================================

test1-doc
~~~~
/**

\mainpage test-comment-bug

<tt> "have some fun" /* a comment */ "finish" </tt>
**/
~~~~

output
~~~~
test-1.doc:6: warning: end of comment block while expecting command </tt>
...
"have some fun" /* a comment 
~~~~

============================================================================

test2-doc
~~~~
/**

\mainpage test-comment-bug

<tt> "have some fun" \/\* a comment \*\/ "finish" </tt>
**/
~~~~

output
~~~~
 "have some fun" \/* a comment *\/ "finish" 
~~~~

**Comment by aotto1968** [comment]
1) One problem is that `<tt>...</tt>` print everything and you can **not** use the `&#ddd;` syntax from *html*.

2) The switch from `*.doc` to `*.md` disable the `vim-plugin` and has some other 'side-effect' with mostly `doc` syntax

**Comment by albert-github** [comment]
ad 1. Indeed doxygen does not support the `&#ddd;` syntax (assuming with the `ddd` you mean a decimal number, but this was not mentioned in the original question as far as I can see.
ad 2. this means that you will need to write search for a plugin for vim to support the syntax.

The `&zwnj;` is indeed a bit of a mean / backdoor trick.

**Comment by aotto1968** [comment]
it would be good to support `&zwnj;` in `\code` or `~~~~` as well (rescue-hint)
