### ISSUE TITLE
INPUT_FILE_ENCODING Format Error

### ISSUE THREAD

**Issue by paule32** [doxygen/doxygen#10597]
I am using doxygen 1.10.0. When running doxygen I get the error:
"**error: Illegal format for option INPUT_FILE_ENCODING, no equal sign ('=') specified for item 'utf-8'** "

when I want to set INPUT_FILE_ENCODING to utf-8:
INPUT_FILE_ENCODING = utf-8  # or:
INPUT_FILE_ENCODING = "utf-8"

**Comment by albert-github** [comment]
In the documentation (see https://www.doxygen.nl/manual/config.html#cfg_input_file_encoding)) it is stated:
> INPUT_FILE_ENCODING
>
 >   This tag can be used to specify the character encoding of the source files that doxygen parses The INPUT_FILE_ENCODING tag can be used to specify character encoding on a per file pattern basis. Doxygen will compare the file name with each pattern and apply the encoding instead of the default [INPUT_ENCODING](https://www.doxygen.nl/manual/config.html#cfg_input_encoding)) if there is a match. The character encodings are a list of the form: pattern=encoding (like `*.php=ISO-8859-1`).
>
>    See INPUT_ENCODING for further information on supported encodings.



The important part here for you would probably be:  
> The character encodings are a list of the form: pattern=encoding (like `*.php=ISO-8859-1`).
