### ISSUE TITLE
Excess empty lines in refman.tex resulting in [1ex] Latex command being added to project id

### ISSUE THREAD

**Issue by marecl** [doxygen/doxygen#10609]
**Describe the bug**
Extra empty line in refman.tex leaves `[1ex]` tag in project ID after generating PDF.  
Also, after comparing output files there is **a lot** of empty lines. which may have similar effect in other .tex files (uncomfirmed).  
After some investigating it turns out, that Doxygen tags in `header.tex` result in empty lines in output `refman.tex` (see screenshots below).  

**Expected behavior**
`[1ex]` tag not showing in project ID  

**Screenshots**
Bugged:
![obraz](https://github.com/doxygen/doxygen/assets/3385735/fcfa8ac0-eb2b-43a0-a2e4-29144586c3ce)
![obraz](https://github.com/doxygen/doxygen/assets/3385735/2994d240-1cd4-41ec-ad78-1e45f965fb6e)
Fixed:
![obraz](https://github.com/doxygen/doxygen/assets/3385735/d6b52774-5619-4ae9-b9ea-1587211ff151)
![obraz](https://github.com/doxygen/doxygen/assets/3385735/52962f62-c343-4f4d-9890-e9b2c9991cd9)
`header.tex` vs `refman.tex` in mentioned commit for 1.11.0
![obraz](https://github.com/doxygen/doxygen/assets/3385735/c961452f-552a-4a41-a95e-0441ff045ca1)
`header.tex` from 1.11.0 vs `refman.tex` generated with release 1.10.0
![obraz](https://github.com/doxygen/doxygen/assets/3385735/1250712f-1e03-426d-8b03-d64aaf1a822f)

**To Reproduce**
1. Create any project with doxywizard
2. Fill in bogus values
3. Enable LaTeX output
4. Run doxygen on created Doxyfile
5. Compile LaTeX

**To Fix**
1. Open refman.tex
2. Search `[1ex]` twice to reach section shown on screenshot
3. Remove empty line as shown
4. Regenerate PDF

Test file attached below:
[Doxyfile.txt](https://github.com/doxygen/doxygen/files/14090228/Doxyfile.txt)

**Version**
Doxygen version used: 1.11.0 (8418c368d41968523978063b89f60068ecc3679f*)  
Windows 10, MikTeX 23.10

**Comment by marecl** [comment]
After even more investigating I've found the culprit.  
Cloning to Windows automatically changes line endings of `refman.tex` to Windows's CRLF while it should be Unix LF only.  
So many hard r's (with force even), detached heads and purged environments to find out it's git who is playing me.

**Comment by albert-github** [comment]
A proposed patch is available as pull request #10610

**Comment by marecl** [comment]
I've managed to reproduce this behaviour on Fedora 39 and texlive.  
For testing use `unix2dos -n refman.tex refman.tex`. Recompiled doxygen, output also has a lot of empty lines, latex tag is also included into project id.  
Clean git clone with patch in !10610 works on both Windows+MiKTeX and Fedora 39+texlive, so most likely this is an issue with how `latexgen.cpp` handles line endings

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.11.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
