### ISSUE TITLE
C++ consteval functions need label

### ISSUE THREAD

**Issue by NichtsHsu** [doxygen/doxygen#10618]
**Describe the bug**
Generate documentation for C++ code, constexpr functions have label and consteval functions don't.

**Expected behavior**
May add a `consteval` label, or still use the `constexpr` label since `consteval` functions are also `constexpr` functions.

**Screenshots**
![screenshot-20240204-180049](https://github.com/doxygen/doxygen/assets/35688135/5f103ad8-a1dd-45eb-9aa8-dc3801431924)

**To Reproduce**
[doxygen-10618-minimal.tar.gz](https://github.com/doxygen/doxygen/files/14156267/doxygen-10618-minimal.tar.gz)

**Version**
1.10.0

**Stack trace**

**Additional context**

**Comment by albert-github** [comment]
Besides `consteval` we should also take `constinit` into account.
(Note: in the code.l `constexpr`, `consteval` and `constinit` are already handled)

@NichtsHsu 
From an image it is not possible to cut/paste the code, so it would have been nice to have:
- attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).

**Comment by NichtsHsu** [comment]
@albert-github Thanks for your reply, I've attached the minimal example.

**Comment by albert-github** [comment]
ve just pushed a proposed patch, pull request #10620

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.11.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
