### ISSUE TITLE
Macros are not expanded recursively

### ISSUE THREAD

**Issue by TommyPec** [doxygen/doxygen#10626]
**Describe the bug**
In ns-3 we have macros, and some of them are creating functions and classes that must be documented.
Since the class name depends on the macro argument, the documentation can not be created normally, and we have to create an accessory header with the documentation of the (to be created) classes. Complicated, but it works - sort of.

The problem arises with nested macros, like:
```cpp
#define ATTRIBUTE_HELPER_CPP(type)                                                                 \
    ATTRIBUTE_CHECKER_IMPLEMENT(type);                                                             \
    ATTRIBUTE_VALUE_IMPLEMENT(type)
```

The first macro is expanded, but the following ones are not, resulting in warnings like:

```
/Users/pecos/workspace/ns-3-dev/doc/introspected-doxygen.h:35588: warning: documented symbol 'Address AddressValue::AddressValue' was not declared or defined.
```

I tried to "unroll" the macros, with little or no success.

**Expected behavior**
Macros expanded recursively, no warnings.

**Screenshots**
n/a

**To Reproduce**
If needed I can provide one, but given the setup complexity it's easier to download ns-3-dev from https://gitlab.com/nsnam/ns-3-dev.git and compile it.
The documentation can be built using `./ns3 docs doxygen`

**Version**
1.11.0 (77cff916c1edfc5de8667e4de683c5dca6764ae2) on MacOS (compiled from sources)

**Stack trace**
n/a

**Additional context**
This bug might be related to #10604

**Comment by albert-github** [comment]
The project is indeed complex, but so will be the building of the ns-3 project (and maybe there are some required dependencies that need to be build / downloaded as well ...).
Therefore a small example would be appreciated, the important part would be that the doxygen preprocessor can be run (i.e. `doxygen -d preprocessor` can show ouput).

**Comment by TommyPec** [comment]
I'm trying to reproduce the problem, but some effects are heavily dependent on the full configuration, and extracting a bare minimum set is complicated.

The good news is that there are no major requirements to build ns-3, just g++, python3, cmake, ninja-build, and git. Of course one will have a lot of missing modules, but that's not a problem.

The compilation can be done with:
```
./ns3 configure --enable-examples --enable-tests
./ns3 build
./ns3 docs doxygen
```
after these 3 steps, the documentation is ready.

One can run the preprocessor by running doxygen manually: `doxygen -d preprocessor doc/doxygen.conf` - and of course the preprocessor output is huge (more than 1 million lines).

However, I'd suggest to first check another issue I opened, as it might contain related clues: #10636

**Comment by albert-github** [comment]
Could ns3-dev also be generated with:
- MSVC toolset, i.e. the MSVC compiler and generating `Nmake files"?
- is theer a restricton on the minimal C++ version supported?
- The `ns3` script is a python script so it should run on Windows as well

Note I don't think issue #10636 is not related to this issue.

**Comment by TommyPec** [comment]
> Could ns3-dev also be generated with:
> 
> * MSVC toolset, i.e. the MSVC compiler and generating `Nmake files"?
> * is theer a restricton on the minimal C++ version supported?
> * The `ns3` script is a python script so it should run on Windows as well
> 
> Note I don't think issue #10636 is not related to this issue.

It should be compatible with Nmake, because cmake can build the corresponding files. I haven't tested it tho.

We usually suggest this:
- g++-9 or later, or LLVM/clang++-10 or later
- Python 3.6 or later
- CMake 3.10 or later
- (macOS only) Xcode 11 or later
- (Windows only) Msys2/MinGW64 toolchain or WSL2

About the minimal C++ version, we require C++20, but we just use the C++20 features that are supported by the above compilers. 

About compiling ns-3 on Windows with the MSVC toolset... it might work, but we didn't test it, perhaps because most of our maintainers are either using Linux, Mac, or WSL. If it works we'll be happy to add it to the list, but for now it's untested.


Further info here: https://www.nsnam.org/docs/installation/html/windows.html

**Comment by TommyPec** [comment]
Update: according to one of our experts on Windows MSVC will *not* be able to run ns-3 due to how the Time class is handled by the linker.

**Comment by TommyPec** [comment]
I have a small update on this problem. I did generate the preprocessing logs (`doxygen -d preprocessor doc/doxygen.conf > log.log`) and I'm attaching the log.

[log.log.gz](https://github.com/doxygen/doxygen/files/14324532/log.log.gz)

I'd suggest to focus on `AddressValue` (one of the classes created through a macro and documented in a separate file).
At line 609407 one can see that the macro `ATTRIBUTE_HELPER_HEADER` has not been expanded, even though it was listed in the `EXPAND_AS_DEFINED` list.

In some other cases the macro has been expanded tho.

However, I do have a small clue. In the log I see:
```
Parsing file /Users/pecos/workspace/ns-3-dev/src/network/model/address.cc...
Preprocessing /Users/pecos/workspace/ns-3-dev/src/network/model/address.h...
#include tag-buffer.h: already processed! skipping...
#include ns3/attribute-helper.h: not found! skipping...
#include ns3/attribute.h: not found! skipping...
#include ostream: not found! skipping...
#include stdint.h: not found! skipping...
Preprocessor output of /Users/pecos/workspace/ns-3-dev/src/network/model/address.h (size: 9313 bytes):
```
so there are some headers that are not found, and perhaps that's why the macros are not expanded.

The problem is: how can they be found?
The headers are copied in `build/include/ns3` by the builder, and `build/include` is added to the include path, however doxygen doesn't know about it.
I tried to add `build/include` to the `INPUT` tag, but it didn't change anything. For sure we can't change the way the files are included, mainly because it's functional to installing ns-3 as a system-wide library.

So... I'm stuck. Is there a way to tell Doxygen where to search for the headers?

**Comment by TommyPec** [comment]
Ok... found it. I feel really dumb now.

`INCLUDE_PATH`. It was set, but it's not recursive.

I mean
- The "right" directory is (in our case) `build/include/ns3/`.
- The headers are included using `#include <ns3/something.h>`
- The `INCLUDE_PATH` must be set to `build/include`

Problem solved. Closing the issue.
