### ISSUE TITLE
Why does the enum HTML docu does NOT show the values

### ISSUE THREAD

**Issue by aotto1968** [doxygen/doxygen#10629]
**Describe the bug**
Why does the enum HTML docu does NOT show the values

**Expected behavior**
The box down should be filled with 1,2,4 to the left

**Screenshots**
![image](https://github.com/doxygen/doxygen/assets/27886664/6cd5a5b2-757b-4ff2-8031-b6aa1d16245a)

**To Reproduce**

**Version**
1.9.8 linux 64bit

unable to upload *.tgz file → tool say: 

We don’t support that file type.

Try again with GIF, JPEG, JPG, MOV, MP4, PNG, SVG, WEBM, CPUPROFILE, CSV, DMP, DOCX, FODG, FODP, FODS, FODT, GZ, JSON, JSONC, LOG, MD, ODF, ODG, ODP, ODS, ODT, PATCH, PDF, PPTX, TGZ, TXT, XLS, XLSX or ZIP.

**Comment by albert-github** [comment]
Actually the same question has been made in #8256 and for this a proposed pull request #8266 is present.

The second box is not intended for the enumeration value but for the brief description as shown by the attached example and the image:
![image](https://github.com/doxygen/doxygen/assets/5223533/c90aa480-30ee-4db3-acf5-3a323e837b52)

Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/14178414/example.tar.gz)


Strange that GitHub refuses the `.tgz`  files although the say they do.
I always use the extension `.tar.gz` and this works well (just use it straight away with the `tar` command or rename the file afterwards in this case).
