### ISSUE TITLE
Scrolling animation can get stuck into infinite loop

### ISSUE THREAD

**Issue by pv** [doxygen/doxygen#10666]
**Describe the bug**
When a TOC item in sidebar is clicked, the view scrolls to the position. If another TOC item is clicked while the page is scrolling, the page starts gets into an infinite loop where it scrolls between the two positions.

**Expected behavior**
Scrolling animation should not get stuck in an infinite loop.

**Screenshots**
[doxy.webm](https://github.com/doxygen/doxygen/assets/35046/040a5d66-fda6-4251-8a34-833c3c82bb04)

**To Reproduce**
1. Open https://doxygen.nl/manual/install.html#install_src_unix
2. In left sidebar, click "Installing the binaries on UNIX"
3. Then rapidly click "Installing from source on UNIX" during the page scrolling animation
4. The page starts to scroll back and forth between the two anchors positions. Only page reload stops the loop.

This can be triggered with also other TOC items, as long as they trigger scrolling on the same page.

**Version**
Appears on Doxygen 1.9.7 and 1.11.0, and probably other versions too.

Browsers: Firefox/122.0.1/Linux; chromium/111.0.5563.64/Linux; Firefox/Android; occurs on all of them.

**Comment by dirkcaesar** [comment]
https://github.com/doxygen/doxygen/assets/143109302/7bd997c0-2ca9-4938-9790-3aed3e76874e

**Comment by doxygen** [comment]
@pv Please verify if the referenced commit fixes the problem for you. Do not close the issue, this will be done automatically when the next official release becomes available.

**Comment by pv** [comment]
Fixed by edb8e9bde2611bac46b72105a11b1131e4b364ed

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.11.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
