### ISSUE TITLE
Parse failure when facing specfic string sequences

### ISSUE THREAD

**Issue by the-Chain-Warden-thresh** [doxygen/doxygen#10694]
**Describe the bug**
doxygen fails to parse the rest of a C file if it meets specfic string sequences such as `  -i, --image [[<output>]:]<path>  `, functions after that will not be included in either `index.xml` or the corresponding xml file.

**Expected behavior**
every functions should be listed in `index.xml`

**Screenshots**
If useful, add screenshots to help explain your problem.

**To Reproduce**
Attach a self contained example that allows us to reproduce the problem.
Such an example typically exist of some source code (can be dummy code) and a doxygen configuration file used (you can strip it using `doxygen -s -u`). After you verified the example demonstrates the problem, put it in a zip (or tarball) and attach it to the bug report. Try to avoid linking to external sources, since they might disappear in the future.
when parsing 
```
static int parse_options(int argc, char **argv, struct swaylock_state *state,
		enum line_mode *line_mode, char **config_path) {
      	    const char usage[] = "  -i, --image [[<output>]:]<path>  ";
	    int c;
    }
static bool file_exists(const char *path) {
	return path && access(path, R_OK) != -1;
}
```
while using [Doxyfile.zip](https://github.com/doxygen/doxygen/files/14421359/Doxyfile.zip) as the configuration file, function `file_exists` isn't included in the `index.xml`

**Version**
The doxygen version is **1.9.1** and I'm using a Ubuntu 22.04.4 LTS. I get doxygen by `apt-get install doxygen`  

**Stack trace**
If you encounter a crash and can build doxygen from sources yourself with debug info (`-DCMAKE_BUILD_TYPE=Debug`), a stack trace can be very helpful (especially if it is not possible to capture the problem in a small example that can be shared).

**Additional context**

**Comment by albert-github** [comment]
When using the doxygen version 1.9.1 I see in index.xml:
```
  <compound refid="aa_8h" kind="file"><name>aa.h</name>
    <member refid="aa_8h_1a7d2491438cadd9ad80394c69b0767f16" kind="function"><name>parse_options</name></member>
  </compound>
```
when using the current doxygen version (1.10.0) I se:
```
  <compound refid="aa_8h" kind="file"><name>aa.h</name>
    <member refid="aa_8h_1a7d2491438cadd9ad80394c69b0767f16" kind="function"><name>parse_options</name></member>
    <member refid="aa_8h_1a0d81e9829afbfca715734b620553e42b" kind="function"><name>file_exists</name></member>
  </compound>
```

So it looks indeed that in the 1.9.1 version the `file_exists`  is missing.
Advise is to update to the current doxygen version

I think the problem has been solved in the mean time.
