### ISSUE TITLE
"unable to resolve reference ... for \ref command" due to nocond

### ISSUE THREAD

**Issue by eyalroz** [doxygen/doxygen#10709]
**Describe the bug**
In a file-level comment `@brief` command, I refer to a class, defined in that file using `@ref`. The forward-declaration is wrapped with @nocond ; but the concrete specializations + definitions - aren't. I get:
```
/path/to/file.hpp:4: warning: unable to resolve reference to 'myclass' for \ref command
```

**Expected behavior**
I expect the reference to be resolved somehow - at worst, resolved as something which should produce no link or extra info, and at best - something which links to the first of the instantiations, or does something else that's intelligent.

Barring this - I expect to be told something about why the `@ref` can't be resolved.

**To Reproduce**
Default-generated `doxygen.cfg`

File `a.hpp`:
```
/**
 * @file
 *
 * @brief contains @ref my_class
 */

///@cond
template <int I> class myclass;
///@endcond

/// This is myclass with 0, it's neat
template <> class myclass<0> { };
```

**Version**
1.11.0 (42d0f98dcbb309dcae08d1495786add326aaeb41*)

**Additional context**

**Comment by doxygen** [comment]
@eyalroz Since you hide the class definition using `@cond` and only define a specialization, you should also reference it as such, i.e.:

```c++
/**
 * @file
 *
 * @brief contains @ref myclass<0>
 */

///@cond
template <int I> class myclass;
///@endcond

/// This is myclass with 0, it's neat
template <> class myclass<0> { };
```
So I think this is falls under wrong expectations/usage.

**Comment by eyalroz** [comment]
> @eyalroz Since you hide the class definition using `@cond` and only define a specialization, you should also reference it as such, 
> ...
> So I think this is falls under wrong expectations/usage.

Oh, I disagree... it is legitimate to refer to an undocumented class. The reference might not get linkified in the generated documentation, but it is true that the file has the definition of the non-instantiated template.

**Comment by albert-github** [comment]
@eyalroz 

The class `myclass` does not show up at all in the documentation (with the used settings) only the class with `<0>` is present.
So where should a `myclass` reference refer to?

**Comment by eyalroz** [comment]
> @eyalroz
> 
> The class `myclass` does not show up at all in the documentation (with the used settings) only the class with `<0>` is present. So where should a `myclass` reference refer to?

to (the template) `myclass`. The class _exists_, it just doesn't have documentation. No documentation for it = no linkification.
