### ISSUE TITLE
[Regression] URLs for markdown pages contains needless _2

### ISSUE THREAD

**Issue by Krinkle** [doxygen/doxygen#10721]
**Describe the bug**
A source file at `/docs/Hooks.md` is published as `md_docs_2Hooks.html` instead of `md_docs_Hooks.html`.

**Screenshots**
Doxygen 1.9.1: <https://doc.wikimedia.org/mediawiki-core/REL1_38/php/md_docs_Hooks.html>
Doxygen 1.9.8: <https://doc.wikimedia.org/mediawiki-core/REL1_39/php/md_docs_2Hooks.html>

As a result, the canonical URL for the latest version, after the upgrade, is now a 404 Not Found:
<https://doc.wikimedia.org/mediawiki-core/master/php/md_docs_Hooks.html>

**Version**
I've reproduced this on the latest release as well.

Doxygen 1.10.0 (on macOS, via Homebrew)

**Additional context**

I suspect this may be a side-effect of https://github.com/doxygen/doxygen/pull/9864, which deals with uncommon characters like `+` or `*`in file names. These need to a deterministic target to disambiguate the two, that makes sense. On the other hand, this uncommon case is now breaking the far more common case of simple a-z file names in a subdirectory. Perhaps the "punishment" can be inverted in some way so as to continue translating slashes to a single underscore?

There does not appear to be an obvious way to avoid all possible conflicts. But, maybe that isn't the intent? The conflict detection and warning logic still exist for other edge cases and manually named pages. In the hypothetical case of both `/docs_foo.md` and `/docs/foo.md` being included in Doxygen input, I imagine this is likely a mistake. I'd certainly prefer to receive a quick warning in that case so that I may rename the conflicting file (or, more likely, remove it, if I left it a copy by accident).

Assuming that the translation remains one-way, I believe we could translate `/` to `_` first, and then call `escapeCharsInString(,,allowUnderscore=true)`. Would that be acceptable?

**Comment by albert-github** [comment]
When running the example:

**docs/Hooks.md**
```
Test
====

This is the Hooks file
```

**Doxyfile**
```
QUIET = YES
RECURSIVE = YES
GENERATE_TREEVIEW = YES
CASE_SENSE_NAMES = YES
```

With the versions up to 1.9.6 we get the file: md_docs_Hooks.html
as of the version 1.9.7 we get the file: md_docs_2Hooks.html

The distinction is made so we can distinguish the generated names for the files:
```
docs/Hooks.md
```
and
```
docs_Hooks.md
```
as they would both map to the same file name i.e. `md_docs_Hooks.html`  

all as indicated in the question.

It is mentioned that "As a result, the canonical URL for the latest version" is not working anymore, but as far as I understand this "canonical URL" is placed outside the scope of doxygen and the generated URLs are intended for "internal"  doxygen use.

So I think this problem is usage.
A fix  for OP would be one of:
- correct the "canonical URL", which is the best solution
- create a redirecting file with the name `md_docs_Hooks.html` that redirects to the real file
- create in the build process a symbolic link 

Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/14545747/example.tar.gz)

**Comment by Krinkle** [comment]
> this "canonical URL" is placed outside the control of doxygen and the generated URLs are intended for "internal" doxygen use.

I'm not sure I understand. I believe Doxygen is for generating and publishing HTML pages to host online and read in a web browser. One of the wonders of the web is the ability to link to a web page.

Is there a recommended and common way in which Doxygen is used such that each page has a separate system in front of it to assign a stable URL to each file?

I thought the motiviation behind https://github.com/doxygen/doxygen/pull/9864, in particular the choice to make the encoding deterministic for all edge cases, was specifically to ensure that files have a stable URL over time. E.g. that whether you start with `foo+bar` and add `foo*bar` later or the other way around, that the first one keeps its original URL. However, that intent implies Doxygen is responsible for canonical URLs — which is what I'm reporting a bug about.

If that is not the intent, perhaps you'd be open to an alternative solution where by we use `_` like before, but automatically `_digit` in the case of a conflict. The allocated numbers would be deterministic by sorting the order. This would restore pre-Doxygen 1.9.7 URLs, whilst still fixing the issue of ensuring similarly-named files get their own unique URL, and that URL will stay consistent between runs when given the same input.

For my use case, I've worked around it by adding `{#filename}` to the page heading in each Markdown file which is an acceptable solution for me.

<https://gerrit.wikimedia.org/g/mediawiki/core/+/5001f914d52052e108a1563506159dc6e636156f%5E!/>

**Comment by albert-github** [comment]
> I'm not sure I understand. I believe Doxygen is for generating and publishing HTML pages to host online and read in a web browser. One of the wonders of the web is the ability to link to a web page.

Well my interpretation is nearly the same only that one can link to the start page (index.html) and that the pages reached from there have "doxygen specific" names. Normally they should be quite stable but sometimes it is necessary to change the name as there are some conflicts.

> I thought the motiviation behind https://github.com/doxygen/doxygen/pull/9864, in particular the choice to make the encoding deterministic for all edge cases, was specifically to ensure that files have a stable URL over time.

This is indeed the case and the names are stable, but for the given case and example a small instability had to be introduced.
The suggestion about the names is hard / impossible to implement as e.g. doxygen doesn't know which version, the `+` or the `*`, was there first.

**Comment by Krinkle** [comment]
> The suggestion about the names is hard / impossible to implement as e.g. doxygen doesn't know which version, the `+` or the `*`, was there first.

I understand, but it appears possible so long as we accept that between different versions of the code (ie. before/after adding the second file) that a file may be given a different name. I.e. when there is only `foo+` it is translated to `foo_.html` and any internal references to `foo+.md` will become `foo_.html`. When both exist, the one that sorts last is given `foo_2.html`. Internal references to `foo+.md` would correctly if it becomes `_2` later, assuming a minimum amount of state during a build to track input-to-output.

In any event, I've worked around it and am reasonably happy with that. Feel free to close this if it isn't something you wish to change and/or would accept a patch for.
