### ISSUE TITLE
Add support for a command legitimizing empty documentation for an item (e.g. @nobrief / @nodocrequired)

### ISSUE THREAD

**Issue by eyalroz** [doxygen/doxygen#10742]
If you leave a documentable item undocumented, you get a warning about it being undocumented. You can make it "go away" with `///@cond` - but you may want it to be visible in the documentation, just with no documentation text, i.e. "nothing to say about this".

Assuming this is possible - the way to do it should, IMHO, be mentioned in the FAQ. On the off chance that it isn't - then it should be possible + should then be mentioned in the FAQ.

**Edit:** @albert-github indicates this is not currently possible. So the ask is for a command which will make Doxygen include the item in the documentation, with an empty brief like an undocumented item, but with no warning about the documentation being missing.

**Comment by albert-github** [comment]
Do you want to have the text:
- nothing to say about this

or
- do you just want an empty field?

In the first case you can define an ALIASES like `ALIASES="nodocu=nothing to say about this"` in the second case you could use:
`ALIASES="nodocu=&nbsp;"`

The example 
**aa.h**
```
/// \file


void foo0();

/// \nodocu
void foo1();

/// \nodocu1
void foo2();
```
**Doxyfile**
```
QUIET = YES
ALIASES += "nodocu=nothing to say about this"
ALIASES += "nodocu1=&nbsp;"
```
would result in:
![image](https://github.com/doxygen/doxygen/assets/5223533/5849a6e3-a47e-4b3d-a7a7-ffe72ee270c6)

Negative aspects for these are that in the first case the function is just documented with the text, in the second case we get the empty line in e.g. the brief description.

It is all up to the taste of the user how everything should look like, so I don't think this is something for the FAQ.

You can also set `WARN_IF_UNDOCUMENTED=NO` but probably you will loose quite a few other warnings as well that you really wanted to see.

Personally I would see more in some commands like `\nodocurequired`, \nobriefrequired` and `\nodetailsrequired` that set a flag to signal the respective documentation is "present".
(@doxygen what do you think about this idea)

Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/14622990/example.tar.gz)

**Comment by eyalroz** [comment]
>     * do you just want an empty field?

This is what I want (the other interpretation is silly).

None of the two options you suggested fit the bill! Why?

1. Not specifying anything results in a warning; and specifying `QUIET = YES` is a non-sequitur, since we definitely want warnings about everywhere else; I just want to indicate that a single item is "legitimately" lacking documentation.
2. An extra line with an NBSP character is distracting and looks like a layout gaffe

> Personally I would see more in some commands like `\nodocurequired`, \nobriefrequired`and`\nodetailsrequired` that set a flag to signal the respective documentation is "present". (@doxygen what do you think about this idea)

So, this bug is now officially about that.

**Comment by albert-github** [comment]
1. You wrote `QUIET=YES` but probably you meant `WARN_IF_UNDOCUMENTED=NO`
2. it is indeed a dirty workaround and a bit disturbing

**Comment by eyalroz** [comment]
@albert-github : Re (1.) : Yes, edited.

**Comment by eyalroz** [comment]
Apparently, I've already suggested this as #7848 ... so, closing this one as a dupe. But please implement this.
