### ISSUE TITLE
`CLANG_ASSISTED_PARSING` is misprocessing `.h` files

### ISSUE THREAD

**Issue by marknelsonengineer** [doxygen/doxygen#10744]
Setup the following Doxyfile configuration:
    
    WARN_AS_ERROR          = YES
    CLANG_ASSISTED_PARSING = YES
    CLANG_OPTIONS +=-I/usr/local/lib/clang/18/include

Write the following program:

    /// The main header file
    /// 
    /// @file main.h
    #pragma once

    /// An enum
    enum blob_e {
       FIRST = 0x01,  ///< The first thing
       SECOND = 0x02  ///< The second thing
    };

and

    /// The main file
    /// 
    /// @file main.c

    #include <stdio.h>

    #include "main.h"

    /// Program entry point
    ///
    /// Reference to #FIRST
    ///
    /// @return The program's result code
    int main() {
       printf( "Hello world\n" );
    }

This generates the following error:

    error: main.h:4:9: warning: #pragma once in main file [-Wpragma-once-outside-header] [clang]

If you disable `CLANG_ASSISTED_PARSING` then the error goes away.

------

Here's another usecase that's broken...

Move `main.h` into `./include`:
- `./main.c`
- `./include/main.h` 

Naturally, Doxygen will complain that `main.c` can't find `main.h`, so we do this:
`CLANG_OPTIONS +=-I./include`

...but now Doxygen throws the following error:

    main.c:12: error: explicit link request to 'FIRST' could not be resolved 

...because Doxygen is not processing the `.h` file.

Adding `INPUT += ./include` to the Doxyfile
...gets us back to `main.h:4:9: warning: #pragma once in main file`

**Expected behavior**
Doxygen w/ `CLANG_ASSISTED_PARSING` should be able to find & process header files

**Version**
    $ doxygen --version
    1.10.0 (GIT-NOTFOUND)

**Comment by marknelsonengineer** [comment]
Note:  Adding this option makes the situation tolerable:  `CLANG_OPTIONS +=-Wno-pragma-once-outside-header` ... but there's still an underlying issue.

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).
(Issue was closed automatically by GitHub due to the used terminology in the pull request)
