### ISSUE TITLE
Add a "Run" menu item key-command to DoxyWizard

### ISSUE THREAD

**Issue by gregwillits** [doxygen/doxygen#10781]
Feature Request &mdash; It would be quite useful (to me) if Doxywizard had a keyboard command to Run (ctl-R, command-R).

Thx.

**Comment by albert-github** [comment]
The current shortcut keys are all connected to menu items. The Run button is a pushbutton (that is only enabled when some preconditions are met).
Doxygen still supports Qt 5 and here I don't directly see a possibility to add a shortcut key to the pushbutton (https://doc.qt.io/qt-5/qpushbutton-members.html), with QT 6 this seems feasible though (https://doc.qt.io/qt-6/qpushbutton-members.html).
There might be a solution 
- use of the method setShortcut (though might only be accessible when the pushbutton is visible)
- add a menu item to run (though where should it be added, the current menu items are geared towards the settings).

**Comment by gregwillits** [comment]
I would think in the Settings menu, adding a menu separator after _Clear recent list_ then add _Run_ menu item would be consistent with the rest of how you've used the Settings menu. If there were other actions worth invoking with key commands, it could be worth adding a new menu, but there just aren't any that stand out to me. So, I don't see a design problem with Settings > Run.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #10785

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by gregwillits** [comment]
Awesome. Thanks!
