### ISSUE TITLE
How to name root node in NavTree, as given by README.md

### ISSUE THREAD

**Issue by bsdooby** [doxygen/doxygen#10780]
**Describe the bug**
*I do not claim this to be a bug!*

In the NavTree to the left I expect the root node to be named acc. to the designated mainpage given by a `README.md`

**Screenshots**

![image](https://github.com/doxygen/doxygen/assets/9528753/cd876b6d-6812-445c-abaf-ecddba5ddf0d)

**To Reproduce**
Use a Markdown file, as set in `USE_MDFILE_AS_MAINPAGE = README.md`

**Expected behavior**
The root node named after some tag or the mainpage title in the Markdown file (or here: `SHOULD-BE-ROOT`), and not the "My Project" default name (or here: `SHOULD-BE-SUPRESSED`)

**Version**
all platforms, 1.10

**Stack trace**
NONE

**Additional context**
NONE

**Comment by albert-github** [comment]
For better / the best understanding of the problem:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).

**Comment by bsdooby** [comment]
A mini project that shows (via comments) what I want to achieve...
[example.tar.gz](https://github.com/doxygen/doxygen/files/14872172/example.tar.gz)

**Comment by albert-github** [comment]
When I set 
```
PROJECT_NAME           = THIS-SHOULD-BE-THE-ROOT-NODE
```
as well I get, as far as I can see, the usage you would like to have.
It is a bit hard to tell as the Readme file is besides the header just empty.

**Comment by bsdooby** [comment]
I want the root node to be named acc. to the top header in the README.md,
and then there should be no other project name mentioned.
Is it possible to suppress also the project name in the top left corner
(outside the NavTree)? The default should not be "My Project" but
empty...

**Comment by bsdooby** [comment]
Yeah, I just did a short test: and by setting PROJECT_NAME to the same name
as the
first main header in the README.md file, I get the desired result. That is
good.

**Comment by albert-github** [comment]
I'm a bit confused as from https://github.com/doxygen/doxygen/issues/10780#issuecomment-2037375404 I understand that in:
![image](https://github.com/doxygen/doxygen/assets/5223533/060798c6-5acf-4167-8fc8-96e1b6b317bd)


you would like to have the top row of the page removed and in: https://github.com/doxygen/doxygen/issues/10780#issuecomment-2037387875
you write about that the result is the desired result.

- What is correct?

Btw. You could always use a project specific header by generating the default header by means of:
```
doxygen -w html ...
```
change the so generated header to your desire and hand that to doxygen by means of the settinge:
```
HTML_HEADER = ...
```

**Comment by bsdooby** [comment]
I admit that my answers are/were a bit confusing. You are right, that, for
my "second" comment/request,
I'd need to adapt the header.html.

By your first suggestion, setting both the PROJECT_NAME and the top header
in the README.md,
I get what I initially wanted.

Therefore, you can close this issue as resolved. Thank you for your support!
