### ISSUE TITLE
Explicit C# event mistaken for property

### ISSUE THREAD

**Issue by ni-gergokozma** [doxygen/doxygen#10799]
**Describe the bug**

Hello Doxygen team!

We accidentally ran into a minor bug with events in C#. Take a look at the following interface:

![image](https://github.com/doxygen/doxygen/assets/78213635/073e102e-d7b5-4749-a944-484b0530b5a0)

We expected to both of these events show up in events section in the XML output. However, the XML output looks like this:

![image](https://github.com/doxygen/doxygen/assets/78213635/73d863a1-ae48-4f88-ab52-301598181043)

As shown above the event without an explicit body (OnEventExtracted) shows up in the correct section. However, the one with an explicit body (OnEventNotExtracted), is considered a property. Which is not the case; it's just an explicit declaration of the add and remove operations (+= and -=) for the event.

**To Reproduce**

Run doxygen on the attached example:
[bug_repro.zip](https://github.com/doxygen/doxygen/files/14975135/bug_repro.zip)

**Expected behavior**
Events defined with explicit bodies should be treated as events and not as properties in the XML output.

**Version**
We are using Doxygen version 1.9.6, but we were able to reproduce this with the latest 1.10.0 version as well.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #10800

(The issue was also visible with other output formats)

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by ni-gergokozma** [comment]
Thank you! That was super quick! :)
