### ISSUE TITLE
Absolute path names of markdown files leak into html output if they are outside of CWD

### ISSUE THREAD

**Issue by stefanct** [doxygen/doxygen#10815]
**Describe the bug**
The absolute path of markdown files gets leaked into various places of the html output.
In my tests this only happens when the markdown file is not within the current working directory or its children.

**To Reproduce**

1. Extract the [attached project](https://github.com/doxygen/doxygen/files/15068914/path_leak.zip) somewhere within your home dir
2. `cd $somwhere/path_leak/dir/`
3. `doxygen`
4. `grep $(id -nu) -r html`

Output something like this:

    html/dir_bde9a48ce7d607c586124b808fdf344c.html:<title>My Project: /home/stefanct/foss/bugs/doxygen/path_leak/otherdir Directory Reference</title>
    html/search/all_0.js:  ['test_0',['test',['../md__home_stefanct_foss_bugs_doxygen_path_leak_otherdir_test.html',1,'']]]
    html/search/pages_0.js:  ['test_0',['test',['../md__home_stefanct_foss_bugs_doxygen_path_leak_otherdir_test.html',1,'']]]
    html/pages.html:<tr id="row_0_" class="even"><td class="entry"><span style="width:16px;display:inline-block;">&#160;</span><a class="el" href="md__home_stefanct_foss_bugs_doxygen_path_leak_otherdir_test.html" target="_self">test</a></td><td class="desc"></td></tr>

Also note, that if you run Doxygen from the top dir, the problem vanishes:

1. `cd ..`
2. `doxygen dir/Doxyfile`
3. `grep $(id -nu) -r html`

Nothing is found.

**Expected behavior**
I don't see any reason why any local paths should appear in the output, even less so in visible parts such as page titles.
But I presume we agree that this is a bug anyway :)
I guess the directories are not correctly filtered under these circumstances...

**Version**
1.9.4 from Debian Bookworm/12's repo (package version 1.9.4-4) (running natively on amd64).

**Comment by albert-github** [comment]
The doxygen version 1.9.4 is from May 5, 2022 the current version is 1.10.0

The problem comes, as noted, from the use of the relative path that first is transformed into a full path.

The following is valid for the 1.9.4 version as well as for the 1.10.0 version.
When using:
```
STRIP_FROM_PATH = /home/stefanct/foss/bugs/doxygen/path_leak
```
the problem is not present anymore.

I think the problem is usage.

**Comment by stefanct** [comment]
Of course but that still leaves some open questions... Why *are* they transformed internally? Why is the behavior different if the file is within the same tree? This doesn't make any sense from a user's PoV.

**Comment by doxygen** [comment]
@stefanct I think the missing piece of information is that by default the directory from which doxygen is run is stripped from the path. So if your code lives in another directory, the default strip path will not do anything and you need to specify the correct path yourself. Doxygen cannot really guess which part of the path is relevant and which part is not.

This should also explain your observation: "Also note, that if you run Doxygen from the top dir, the problem vanishes"

**Comment by stefanct** [comment]
Doxygen would not have to strip anything at all if it would just use relative paths as the user specifies. Nobody gave an explanation yet why doxygen does that at all when rendering (specifically but not limited to) markdown files.

Also, it actually *could* derive a more useful strip path quite easily... iterate over all input paths and find the longest shared path. That's O(n) where n is the number of input paths. It would still be rather surprising from the user's perspective and possibly creating unwanted output though and I wouldn't recommend implementing it.

One problem with using `STRIP_FROM_PATH` as a workaround is that this is obviously depending on the location of the files. But these files usually reside in a repository that is used on many different machines and possibly parsed by automated systems (e.g., for testing and/or CI)...

This leaves as only workaround execution from the common ancestry directory, which can be inconvenient at times.
