### ISSUE TITLE
`param[dir]` doesn't work

### ISSUE THREAD

**Issue by OleksandrKvl** [doxygen/doxygen#10812]
**Describe the bug**
Is `@param[dir]` supposed to work? I've found this [SO answer](https://stackoverflow.com/a/14262130) edited by @albert-github that didn't mention this feature. When I tried to use `@param[opt] ... description`, I got `[opt]` as parameter name and `... description` as a description. This is corresponding HTML:

```html
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">[opt]</td><td>... description </td></tr>
  </table>
  </dd>
</dl>
```

**Expected behavior**
Expected to see correct parameter name and probably some special style for `dir` value.

**Version**
Doxygen 1.10.0 from Homebrew, macOS Sonoma.

**Comment by doxygen** [comment]
The `dir` is a placeholder for the parameter's direction (e.g. input or output or both). Valid values are `@param[in]`, `@param[in, out]`, `@param[inout]`, `@param[out,in]`

**Comment by OleksandrKvl** [comment]
Thanks for a quick reply, you're both right. Probably my eyes misread `out` as `opt` and I missed the warning because it was at the top of a long Doxygen output.
However, as a suggestion, maybe you can consider allowing `opt` or other `dir` values for these cases:
- trailing `...` parameters, for wrapper functions where it can be empty.
- tool-generated functions. In my particular case, I generate a function and its signature based on the external XML file. In order to document its possible interface I use something like

```cpp
#ifdef MY_PROJ_DOXYGEN
//! @brief generated function
//! @param ... parameter list depends on the XML, might be empty
void generated_function(...);
#endif
``` 

And I just thought that it might be nice to mark it as `[opt]` because it can be empty.

Again, thanks for your replies, feel free to close the issue if don't plan any further work on it.
