### ISSUE TITLE
[feature request] need @copyparam

### ISSUE THREAD

**Issue by zhangzq** [doxygen/doxygen#10821]
In many cases, the functions share same parameters with same doc on them. @copyparam will be useful in these cases.

```python
## @brief This is a function. 
# @param a This is parameter.
def function1(a):
    pass

## @brief This is another function.
# @param a @copyparam function1 a
def function2(a):
    pass

```

**Comment by albert-github** [comment]
There are already a number of requests for this feature (even one from yourself).
Setting issue to duplicate.
