### ISSUE TITLE
How to create a sub page within namespace documentation ?

### ISSUE THREAD

**Issue by paule32** [doxygen/doxygen#10837]
Hello,
how can I create a sub page in the table of contents for seperate some groups.
I have added a attachment with screen shot.
In this screen shot, you can see the doxygen generated chm file in action.
Where the arrow, I would have a sub page.
[packed.zip](https://github.com/doxygen/doxygen/files/15153234/packed.zip)

**Comment by albert-github** [comment]
It is not possible to reproduce the problem as I get the errors:
```
error: Tag file 'customtags' does not exist or is not a file. Skipping it...
error: Project logo './doc/img/logo.png' specified by PROJECT_LOGO does not exist!
```
Furthermore in the file `customtags.txt` (which should be the place where to find the external documentation  but it says:
```
\fcolor{blue}
```

You also get warnings about the fact that you split the line of `HHC_LOCATION` over 2 lines (so either these lines should be joined or the second line should have a `#` in front of it.
