### ISSUE TITLE
howto - seperate/prevent display picture in \brief section, but not in detail section, and vice versa ?

### ISSUE THREAD

**Issue by paule32** [doxygen/doxygen#10842]
Hello,
how can I only display a picture in the \brief - and not in the detail section ?
[packed.zip](https://github.com/doxygen/doxygen/files/15167174/packed.zip)

**Comment by paule32** [comment]
seems to be solved

**Comment by albert-github** [comment]
> seems to be solved

This gives no information so other users that might have a similar problem cannot benefit from it.

- How is it solved or is it solved by means of your extra filters in the build.bat?
- which version of doxygen?

**Comment by paule32** [comment]
- I using 1.10.0
- I make a \brief section
- add one blank line after \brief
- and insert a custom tag \dotimg{picture.png}{@ref datatypes}{@ref datatypes_unsigned}{@ref datatypes_signed}
- doxygen will inject the custom tag into the output html file
- my python script will regex for \\dotimg, and split the four paren into string
- these string, I use it to assemble image map coords, and support linking on the different coords areas/regions

Simply add blank comment line after \brief seems to be begin a \details section.
So, I can display pictures in \brief, and \detail sections separately or each one times (by using the \dotimg tag.
No lesser, no more.

But the trick is the idea ;-)
