### ISSUE TITLE
`using` keyword on base class function brings the documentation into derived class

### ISSUE THREAD

**Issue by scott-zhong** [doxygen/doxygen#10843]
**Describe the bug**
`using` keyword on base class function brings the documentation into derived class.

```
/**
 * Base docs
 */
class Base
{
public:
    /**
     * Base fun docs
     */
    void fun(int);
};

/**
 * Derived docs
 */
class Derived : public Base
{
public:
    using Base::fun;

    /**
     * Derived fun docs
     */
    void fun(double);
};
```

**Screenshots**
Doxygen 1.8.13
![image](https://github.com/doxygen/doxygen/assets/32584126/0006397e-c237-4659-b069-63237e1e9b97)

Doxygen 1.8.14 - trunk (85eb55d1b32bfeb474be6485c88348ef5d5d7fd8)
![image](https://github.com/doxygen/doxygen/assets/32584126/c0444bad-ef15-4af9-9837-b3427795bbd9)

**To Reproduce**
[testcase.zip](https://github.com/doxygen/doxygen/files/15167224/testcase.zip)

**Expected behavior**
Base function documentation shouldn't be in Derived class with `using` keyword

**Version**
Doxygen 1.8.14 - trunk (85eb55d1b32bfeb474be6485c88348ef5d5d7fd8)

**Comment by doxygen** [comment]
@scott-zhong I think the later versions of doxygen are actually (more) correct.

If I change your example to
```c++
#include <stdio.h>

/**
 * Base docs
 */
class Base
{
public:
    /**
     * Base fun docs
     */
    void fun(int v) { printf("Base::fun(%d)\n",v); }
};

/**
 * Derived docs
 */
class Derived : private Base
{
public:
    using Base::fun;

    /**
     * Derived fun docs
     */
    void fun(double d) { printf("Derived::fun(%f)\n",d); }
};


int main()
{
  Derived d;
  d.fun(10);
  d.fun(10.0);
}
```
The compiled program will print
```
Base::fun(10)
Derived::fun(10.000000)
```
Even though `Base` is a private base class of `Derived`, so the using statement brings the function into the public scope of `Derived` which is what doxygen shows.

**Comment by scott-zhong** [comment]
@doxygen I disagree, `using Base::fun` does bring the Base's `fun()` into the scope of `Derived`, but should it be documented like `Derived` has defined the function? That is what it feels like if `Base::fun` is included in the `Derived`'s API documentation (it is documented as both `Derived`'s API and public member inherited from `Base` in 1.8.14 and later).  I feel the previous documentation is more correct in that it is referring to see `Base::fun` for the documentation (`Derived` is merely exposing the API rather than defining it).

**Comment by scott-zhong** [comment]
@doxygen That is certainly true.  I am fine with closing this issue.
