### ISSUE TITLE
custom tags give warning

### ISSUE THREAD

**Issue by paule32** [doxygen/doxygen#10840]
Hello,
when I use custom tags, I get warings.
The Doxyfile item
TAGFILES  = customtags.txt=./

is set. The customtags.txt file will be found by doxygen, so the path and file name are correct.
The content of this file is as follows:
\fcolor   set the font text color

Where the first column is the tag-name, the rest of the line are comments.
Like the documentation it said.

And this are the warnings from warnings.log:
E:/Projekte/doc/customtags.txt:1: warning: Unexpected character `\` found
E:/Projekte/doc/customtags.txt:1: warning: Unexpected character `f` found
E:/Projekte/doc/customtags.txt:1: warning: Unexpected character `c` found
E:/Projekte/doc/customtags.txt:1: warning: Unexpected character `o` found
E:/Projekte/doc/customtags.txt:1: warning: Unexpected character `l` found
E:/Projekte/doc/customtags.txt:1: warning: Unexpected character `o` found
E:/Projekte/doc/customtags.txt:1: warning: Unexpected character `r` found
...
The customtags.txt have the utf-8 encoding.
There is no BOM mark present.

**Comment by albert-github** [comment]
Always:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).
- Please also specify the **full** doxygen version used (`doxygen -v`).

Tag files are for referencing to external documentation see e.g https://www.doxygen.nl/manual/external.html and the documentation of the settings `TAGFILES` and `GENERATE_TAGFILE`.

The `\fcolor` doesn't look like a tag in this context.

I think the problem is usage.

**Comment by paule32** [comment]
I hope that the attachment contains all files you need:
[packed.zip](https://github.com/doxygen/doxygen/files/15164366/packed.zip)

I come to a next problem, where the \dot files don't display on top of page.
The version is:
E:\doxygen\bin>doxygen -v
1.10.0 (ebc57c6dd303a980bd19dd74b8b61c8f3f5180ca)

**Comment by paule32** [comment]
forget the warnings.log:

E:/Projekte/fpc-qt/doc/customtags.txt:1: warning: Unexpected character `\` found
E:/Projekte/fpc-qt/doc/customtags.txt:1: warning: Unexpected character `f` found
E:/Projekte/fpc-qt/doc/customtags.txt:1: warning: Unexpected character `c` found
E:/Projekte/fpc-qt/doc/customtags.txt:1: warning: Unexpected character `o` found
E:/Projekte/fpc-qt/doc/customtags.txt:1: warning: Unexpected character `l` found
E:/Projekte/fpc-qt/doc/customtags.txt:1: warning: Unexpected character `o` found
E:/Projekte/fpc-qt/doc/customtags.txt:1: warning: Unexpected character `r` found
E:/Projekte/fpc-qt/doc/doc/std/cstdint.hpp:93: warning: Found unknown command '\fcolor'
E:/Projekte/fpc-qt/doc/doc/std/cstdint.hpp:73: warning: Found unknown command '\fcolor'
E:/Projekte/fpc-qt/doc/doc/std/cstdint.hpp:53: warning: Found unknown command '\fcolor'
E:/Projekte/fpc-qt/doc/doc/std/cstdint.hpp:120: warning: Found unknown command '\fcolor'
E:/Projekte/fpc-qt/doc/doc/std/cstdint.hpp:141: warning: Found unknown command '\fcolor'
E:/Projekte/fpc-qt/doc/doc/std/cstdint.hpp:162: warning: Found unknown command '\fcolor'
E:/Projekte/fpc-qt/doc/doc/std/cstdint.hpp:73: warning: Found unknown command '\fcolor'
E:/Projekte/fpc-qt/doc/doc/std/cstdint.hpp:93: warning: Found unknown command '\fcolor'
E:/Projekte/fpc-qt/doc/doc/std/cstdint.hpp:53: warning: Found unknown command '\fcolor'
E:/Projekte/fpc-qt/doc/doc/std/cstdint.hpp:73: warning: Found unknown command '\fcolor'
E:/Projekte/fpc-qt/doc/doc/std/cstdint.hpp:80: warning: Found unknown command '\fcolor'
E:/Projekte/fpc-qt/doc/doc/std/cstdint.hpp:93: warning: Found unknown command '\fcolor'
E:/Projekte/fpc-qt/doc/doc/std/cstdint.hpp:100: warning: Found unknown command '\fcolor'
E:/Projekte/fpc-qt/doc/doc/std/cstdint.hpp:53: warning: Found unknown command '\fcolor'
E:/Projekte/fpc-qt/doc/doc/std/cstdint.hpp:60: warning: Found unknown command '\fcolor'
E:/Projekte/fpc-qt/doc/doc/std/cstdint.hpp:141: warning: Found unknown command '\fcolor'
E:/Projekte/fpc-qt/doc/doc/std/cstdint.hpp:162: warning: Found unknown command '\fcolor'
E:/Projekte/fpc-qt/doc/doc/std/cstdint.hpp:120: warning: Found unknown command '\fcolor'
E:/Projekte/fpc-qt/doc/doc/std/cstdint.hpp:141: warning: Found unknown command '\fcolor'
E:/Projekte/fpc-qt/doc/doc/std/cstdint.hpp:148: warning: Found unknown command '\fcolor'
E:/Projekte/fpc-qt/doc/doc/std/cstdint.hpp:162: warning: Found unknown command '\fcolor'
E:/Projekte/fpc-qt/doc/doc/std/cstdint.hpp:169: warning: Found unknown command '\fcolor'
E:/Projekte/fpc-qt/doc/doc/std/cstdint.hpp:120: warning: Found unknown command '\fcolor'
E:/Projekte/fpc-qt/doc/doc/std/cstdint.hpp:127: warning: Found unknown command '\fcolor'
E:/Projekte/fpc-qt/src/sources/app-rtl/server/BoostServer.cc:303: warning: found documented return type for BoostRelease::handle_exception that does not return anything
E:/Projekte/fpc-qt/src/sources/app-rtl/server/BoostServer.cc:711: warning: argument 'uint32_t' of command @param is not found in the argument list of BoostRelease::responseHeader(uint32_t bcode, uint32_t btype, uint32_t length)
E:/Projekte/fpc-qt/src/sources/app-rtl/server/BoostServer.cc:711: warning: argument 'uint32_t' of command @param is not found in the argument list of BoostRelease::responseHeader(uint32_t bcode, uint32_t btype, uint32_t length)
E:/Projekte/fpc-qt/src/sources/app-rtl/server/BoostServer.cc:711: warning: argument 'uint32_t' of command @param is not found in the argument list of BoostRelease::responseHeader(uint32_t bcode, uint32_t btype, uint32_t length)
E:/Projekte/fpc-qt/src/sources/app-rtl/server/BoostServer.cc:711: warning: The following parameters of BoostRelease::responseHeader(uint32_t bcode, uint32_t btype, uint32_t length) are not documented:
  parameter 'bcode'
  parameter 'btype'
  parameter 'length'
E:/Projekte/fpc-qt/doc/doc/std/cstdint.hpp:73: warning: Found unknown command '\fcolor'
E:/Projekte/fpc-qt/doc/doc/std/cstdint.hpp:93: warning: Found unknown command '\fcolor'
E:/Projekte/fpc-qt/doc/doc/std/cstdint.hpp:53: warning: Found unknown command '\fcolor'
E:/Projekte/fpc-qt/doc/doc/std/cstdint.hpp:141: warning: Found unknown command '\fcolor'
E:/Projekte/fpc-qt/doc/doc/std/cstdint.hpp:162: warning: Found unknown command '\fcolor'
E:/Projekte/fpc-qt/doc/doc/std/cstdint.hpp:120: warning: Found unknown command '\fcolor'

**Comment by albert-github** [comment]
- ignoring warnings is not always  good idea
- problem with the `HHC_LOCATION` as indicated in #10837 
- warnings:
  ```
  error: file name expected for option GENERATE_TAGFILE, got YES instead. Ignoring...
  warning: source '../src/sources/app-rtl/server/BoostServer.cc' is not a readable file or directory... skipping.
  warning: source '../src/sources/app-rtl/inc/Visitor.cc' is not a readable file or directory... skipping.
  ``` 

> I come to a next problem, where the \dot files don't display on top of page.

mixing issues in one issue is not a good idea.

A `\dot` command is in respect to the `\brief` description (and `section descriptions) a breaking command and will end  the `\brief` command and thus the image will appear in the detailed description. the brief description is intended as a short one line description. So this is by design.

**Comment by paule32** [comment]
I solved/fixed your concerned stuff.

But I get warning much more.
Is there a option to "ignore" by: warnings/severity level/code ?
My content source of documented help is very tiny at current time.
But I can look into the future, when I see to the warnings.log by growing the help documenting source.
Then it could be, that the warning.log is bigger than the final output result that doxygen produce.

**Comment by albert-github** [comment]
> Is there a option to "ignore" by: warnings/severity level/code ?

There are some `WARNING...` settings but explicit warnings or level are not present (there have been thoughts about an enhancement but this would mean checking quite a few warning messages, over 500, and putting them into categories).

**Comment by paule32** [comment]
would be nice at a starting point

**Comment by albert-github** [comment]
The work still remains as the different warnings have to be categorized, which they, partly, are already by means of the different `WARN...` settings.
