### ISSUE TITLE
HowTo - image map and link location of produced doxygen HTML/CHM project ?

### ISSUE THREAD

**Issue by paule32** [doxygen/doxygen#10844]
Hello,
I have concerns about the setting of link locations that resides in static generated image maps.
For image maps I use a online tool that can load images, and produce image map code as HTML code that can be taken to insert it in own HTML projects.

I created a python script, which produce me a dot tooled image.
There are no problems to include the image at doxygen generated HTML stuff.
I use customized tags, that will be parsed by a python script.
Here, I get faced with a problem:
Where can I get the location of an area/region link into the produced HTML/CHM documentation ?
Because, the links of documentation so far I can see can reside into many sub directories that will be created depend on doxygen state.

So, it is for me not possible to determine the link location, that I can put into the custom tag/python script.
Is there a way, to tackle out the location ?
I have add a small example of a chm project that should showing the problem.

Please take a look to the python script.
Thanks for reading
[packed.zip](https://github.com/doxygen/doxygen/files/15175054/packed.zip)

**Comment by albert-github** [comment]
When I understand the issue correct you would like to have the possibility to create inside a node a link to a doxygen entity so when having
```
/// \file
///
/// \ref fie1 "First fie"
///
/// \dot
/// digraph G {
///   N1
///   N2
///   N1 -> N2
/// }
/// \enddot
///
/// \ref fie2 "Second fie"


/// \brief Brief fie 1
///
/// \details Details fie 1
fie1();


/// \brief Brief fie 2
///
/// \details Details fie 2
fie2();
```
Which would give:
![image](https://github.com/doxygen/doxygen/assets/5223533/df26ca0b-dbed-4452-887a-70f78de29586)

and when clicking on `N1` it would jump to `fie1` and when clicking on `N2` it would jump to `fie2`

Dot has the possibility to define an "url" with a node and doxygen has for this the possibility to use `\ref <target>` in it like:
```
/// \dot
/// digraph G {
///   N1 [URL="\\ref fie1"]
///   N2 [URL="\\ref fie2"]
///   N1 -> N2
/// }
/// \enddot
```

The `\ref` can jump to different places also places defined e.g. with the `\anchor` command
See also the documentation of the `\dot` command.

Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/15175329/example.tar.gz)

**Comment by paule32** [comment]
All clarify. \ref was my friend.
You made my day !
