### ISSUE TITLE
Unable to build documentation from "master" branch

### ISSUE THREAD

**Issue by SchweinDeBurg** [doxygen/doxygen#10851]
I've just got the following error message:
```
[274/275] Generating Latex and HTML documentation.
FAILED: doc/CMakeFiles/run_doxygen /home/elijah/.local/rpmbuild/BUILD/doxygen/x86_64-redhat-linux-gnu/doc/CMakeFiles/run_doxygen 
cd /home/elijah/.local/rpmbuild/BUILD/doxygen/x86_64-redhat-linux-gnu/doc && /usr/bin/cmake -E env VERSION=1.11.0 INDEX_DOC=index_html.dox GENERATE_HTML=YES GENERATE_LATEX=NO /home/elijah/.local/rpmbuild/BUILD/doxygen/x86_64-redhat-linux-gnu/bin/doxygen && /usr/bin/cmake -E env VERSION=1.11.0 INDEX_DOC=index_latex.dox GENERATE_HTML=NO GENERATE_LATEX=YES /home/elijah/.local/rpmbuild/BUILD/doxygen/x86_64-redhat-linux-gnu/bin/doxygen
error: Problems running latex. Check your installation or look for typos in _formulas.tex and check _formulas.log!
error: Problems running latex. Check your installation or look for typos in _formulas_dark.tex and check _formulas_dark.log!
ninja: build stopped: subcommand failed.
```
[_formulas.log](https://github.com/doxygen/doxygen/files/15206590/_formulas.log)
[_formulas_dark.log](https://github.com/doxygen/doxygen/files/15206591/_formulas_dark.log)

**Comment by albert-github** [comment]
When specifying "master" version please also specify the full version i.e. `doxygen -v` as the master version is a moving target.

When looking in the log file I see as first line:
```
This is pdfTeX, Version 3.14159265-2.6-1.40.17 (TeX Live 2016) (preloaded format=latex 2023.7.12)
```

It looks like that the used LaTeX version is too old (Tex Live 2016).

What happens when you change in the original `doc/doxygen_manual.tex` (around line 52):
```
\usepackage{ifpdf}
\ifpdf
```
to
```
\usepackage{iftex}
\ifpdftex
``

(In this case: Between 2 runs don't forget to remove the html and latex directory in, probably, /home/elijah/.local/rpmbuild/BUILD/doxygen/x86_64-redhat-linux-gnu)

**Comment by SchweinDeBurg** [comment]
> When specifying "master" version please also specify the full version

I've tired to build from commit `1d674af1933d88038d469271df60bf6dee5a947d` and `doxygen -v` shows `1.11.0`.

> It looks like that the used LaTeX version is too old (Tex Live 2016).

Unfortunately I can not upgrade LaTeX at this time.

> What happens when you change in the original doc/doxygen_manual.tex (around line 52)

Tried and got the same error as above.

**Comment by SchweinDeBurg** [comment]
BTW my last successful build was made from commit `2a7e195933d19c0be78d173b1d4f44b22f29cfc0` .

**Comment by albert-github** [comment]
The fact that 2a7e195933d19c0be78d173b1d4f44b22f29cfc0  (April 10, 2024)was the last successful build is consistent with my idea that he problem is introduced with a92522642d57c6c2319860b5cff2726251aec6e4 or ef7c10113b8eb5ecbd3d58b8f807fcb2de7037a5  which was merged into master(8dd9072f300db992654496eb8cdc84f75dd1aecc ):
```
Commit: 8dd9072f300db992654496eb8cdc84f75dd1aecc [8dd9072]

Date: Friday, April 12, 2024 9:30:50 PM
```

**Comment by albert-github** [comment]
What happens when you run:
```
make tests TEST_FLAGS="--id 28 --xhtml"
```

**Comment by SchweinDeBurg** [comment]
I am using Ninja, so I've added
```
TEST_FLAGS="--id 28 --xhtml" %{__ninja} -C %{CMakeRunDir} %{?_smp_mflags} tests
```
and got the following:
```
[101/101] Running doxygen tests...
FAILED: testing/CMakeFiles/tests /home/elijah/.local/rpmbuild/BUILD/doxygen/x86_64-redhat-linux-gnu/testing/CMakeFiles/tests 
cd /home/elijah/.local/rpmbuild/BUILD/doxygen/x86_64-redhat-linux-gnu/testing && /usr/bin/python3.8 /home/elijah/.local/rpmbuild/BUILD/doxygen/testing/runtests.py --doxygen /home/elijah/.local/rpmbuild/BUILD/doxygen/x86_64-redhat-linux-gnu/bin/doxygen --inputdir /home/elijah/.local/rpmbuild/BUILD/doxygen/testing --outputdir /home/elijah/.local/rpmbuild/BUILD/doxygen/x86_64-redhat-linux-gnu/testing
1..1
not ok - [028_formula.c]: test the \f$, \f[, \f], \f{, and \f} commands
-------------------------------------
error: Problems running latex. Check your installation or look for typos in _formulas.tex and check _formulas.log!
error: Problems running latex. Check your installation or look for typos in _formulas_dark.tex and check _formulas_dark.log!

-------------------------------------
1 out of 1 tests failed
ninja: build stopped: subcommand failed.
```
To be clear: it is with
```
\usepackage{ifpdf}
\ifpdf
```
And there is no ` _formulas*.log` files.

**Comment by albert-github** [comment]
The fact that the log file and tex file are gone is a nuisance althoug doxygen has already a solution for it:
```
make tests TEST_FLAGS="--xhtml --id 28 --keep --doxygen_dbg -d formula"
```
Which will keep the intermediate results and also the log / tex files.

I'm doing some more investigations at the moment (will take a while).

**Comment by SchweinDeBurg** [comment]
> Which will keep the intermediate results and also the log / tex files.

[_formulas.tar.gz](https://github.com/doxygen/doxygen/files/15209532/_formulas.tar.gz)

**Comment by albert-github** [comment]
What happens when you change in src/latexgen.cpp around line 2307 the line:
```
t << "\\ifpdftex\n";
```
into
```
t << "\\ifPDFTeX\n";
```
So 5 characters in uppercase.

and run the `make tests...` again

**Comment by SchweinDeBurg** [comment]
Many thanx! With this change test are passed
```
[101/101] Running doxygen tests...
1..1
ok - [028_formula.c]: test the \f$, \f[, \f], \f{, and \f} commands
All tests passed!
```
and all documentation also built!

**Comment by albert-github** [comment]
Thanks, tomorrow I'll create a proposed patch for this (and some other `\if...` parts.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request https://github.com/doxygen/doxygen/pull/10852

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub.
Since this problem is not appearing in any official release and is fixed before the next release I'll close the issue.
