### ISSUE TITLE
nodiscard C++ attribute could be used for documentation

### ISSUE THREAD

**Issue by pratikpc** [doxygen/doxygen#10882]
**Describe the bug**
In the generated Doxygen output, take advantage of the [nodiscard C++ attribute](https://en.cppreference.com/w/cpp/language/attributes/nodiscard) and document the same. 

This would make it possible for the end users to know from the docs that the output of a specific type/function is mandatory for use.

In C++20, one could also specify an optional string literal too which could be added to the documentation.

```cpp
[[nodiscard("PURE FUN")]] int strategic_value(int x, int y) { return x ^ y; }
```

**Screenshots**
NA

**To Reproduce**
NA

**Expected behavior**
NA

**Version**
NA

**Stack trace**
NA

**Additional context**
NA

**Comment by albert-github** [comment]
In the current doxygen version I see:

![image](https://github.com/doxygen/doxygen/assets/5223533/ffce5947-9c5e-467e-b986-96d8b9d6c2b2)


so here there is the indication of `nodiscard`.
In the doxygen version 1.10.0 version this is not yet present.

I think the problem has been solved in the mean time.

NOTO:
Normaly always:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).
- Please also specify the **full** doxygen version used (`doxygen -v`).

**Comment by pratikpc** [comment]
@albert-github thanks

I ended up using the GitHub master branch code and it seems to work.

I was indeed using an older version.

However, it seems Doxygen seems to not yet take advantage of nodiscard's optional string literal.

The test code contained Doxygen's default config + this simple header

```cpp
/// @brief Class
struct Y{
   /// @brief Function x
   /// @return returns value
   [[nodiscard("PURE FUN")]] int x();
};
```

Sure

The doxygen version is

> 1.12.0 (bcb258b46401035b6e41b08f4a0c2bbefd99fd9e*)

![image](https://github.com/doxygen/doxygen/assets/28534575/8f58c58b-df8a-4a46-be36-76c31666e3fe)

Maybe it would be best to create another issue for the same from my side.

**Comment by pratikpc** [comment]
Duplicate of #10708

**Comment by albert-github** [comment]
Thanks for the remark in https://github.com/doxygen/doxygen/issues/10882#issuecomment-2123310781 i.e not using the optional string with `nodiscard`.
With all C++ attributes  the possible optional string is not taken into account (as far as I can see quickly) and regarding the other possible attributes it looks like they are ignored completely.
As far as I can tell the following attributes exists:
```
deprecated
fallthrough
maybe_unused
nodiscard
noreturn
_Noreturn
unsequenced
reproducible
```

I think the issue #9072 / #5940 / #9064  is also about better handling of attributes. Maybe good to add this enhancement request with #5940.
