### ISSUE TITLE
Improve Markdown support - add support for GitHub's like TOC.

### ISSUE THREAD

**Issue by igormironchik** [doxygen/doxygen#10893]
**Describe the bug**

Link like

```md
* [Example](#example)
```

Where `#example` is linked to

```md
# Example
```

does not work.

**To Reproduce**

```md
* [Example](#example)

Add a lot of text here... :)

# Example
```

**Expected behavior**

I'd like the TOC for `GitHub` to work in `Doxygen`.

**Version**

```
1.12.0 (3d494140a674a8344c165a559d841166bbf3b80f*)
```

```
No LSB modules are available.
Distributor ID: Neon
Description:    KDE neon 6.0
Release:        22.04
Codename:       jammy
```

I've built `Doxygen` from sources.

**Comment by albert-github** [comment]
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).


It might be that you need to set `MARKDOWN_ID_STYLE      = GITHUB`

**Comment by igormironchik** [comment]
You are right. I'm wrong here. Sorry.

`MARKDOWN_ID_STYLE      = GITHUB` solves the issue.
