### ISSUE TITLE
Doxywizard in proposed patches doesn't run

### ISSUE THREAD

**Issue by thom-sch** [doxygen/doxygen#10917]
**Describe the bug**
Calling doxywizard.exe delivered with proposed patches results in an error message at least under windows (other OSes not tested) - see attached screenshot.

**Screenshots**
![grafik](https://github.com/doxygen/doxygen/assets/44623251/69c44980-170d-4181-b861-6dda9ec714f1)

**To Reproduce**
Start doxywizard.exe from any proposed patch

**Expected behavior**
...just a flaw in my eyes

**Version**
- Windows 10 (probably other versions, too)
- Any proposed patch (official releases work fine!)

Regards from Meerbusch
Thomas

**Comment by albert-github** [comment]
The official release of doxygen starts without problems and gives as version information:
![image](https://github.com/doxygen/doxygen/assets/5223533/ce728624-48fb-4d25-8625-e8d21921fae8)

The version from the artifacts (https://github.com/doxygen/doxygen/actions/runs/9336693228) doesn't start and gives:
![image](https://github.com/doxygen/doxygen/assets/5223533/fe3dd787-ea1f-4216-9b77-dfc1874b174f)

@doxygen Is there a difference in the build between the official doxygen release and the GitHub Artifacts (dynamic versus static linking? Maybe the `-Dwin_static=YES` in the official doxygen release build)

As a side note:
My locally build 32 bit version does start (just a little bit older Qt than with the official release i.e. 5.14.0)
My locally build 64 bit version does start (just a little bit newer Qt than with the official release i.e. 6.1.2)

**Comment by thom-sch** [comment]
an additional information:
Replacing the proposed patch version with an "official" doxygen.exe runs without any problem.

Regards from Meerbusch
Thomas

**Comment by albert-github** [comment]
Did you mean doxygen.exe or doxywizard.exe?

I see a big difference in the size of the GitHub Actions doxywizard (673,280 bytes) and the one from the official 11.0.0 release (15,468,544 bytes), definitely indicating a difference between a dynamic and a static build.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #10918 

When it succeeds this will probably result in a bit a larger artifact so we have to see whether we want this or not (though my experience is that after some time the artifact are removed automatically so should not be a real big deal).

**Comment by thom-sch** [comment]
> Did you mean doxygen.exe or doxywizard.exe?

oh, sorry - of course doxywizard.exe... :)

**Comment by albert-github** [comment]
The simple change didn't I tried for the GitHub Actions didn't work ( 😭 )

**Comment by thom-sch** [comment]
Hm 
- running doxygen.exe with option -V from proposed patch 10916 from cli gives
`1.12.0 (ab98e6aed11eb03bac705b229ecb6ccb5b0a7bb4*)`
- replacing doxwizard.exe with the official version 1.11.0 gives
`1.12.0 (ab98e6aed11eb03bac705b229ecb6ccb5b0a7bb4*)`
 see attached screenshots

so it seems the "old" doxywizard.exe (V.1.11.0) uses the "new" doxygen.exe (V.1.12.0 issue 10916)

Regards from Meerbushc
Thomas

Run doxygen from cli:
![grafik](https://github.com/doxygen/doxygen/assets/44623251/30339179-b71b-4003-943d-edc29bc2c61b)

Run replaced doxywizard:
![grafik](https://github.com/doxygen/doxygen/assets/44623251/9cd96781-86cf-479b-ba67-0b2a09f056d6)

**Comment by albert-github** [comment]
It is a bit unclear to me what you tested exactly and where the different executables reside.
Did you know that also the doxywizard has a command line argument to see the version (`doxywizard --version`).

It is, probably, all about where you start the exe and which exe the `doxywizard` prefers the `doxygen.exe` on the directory where it starts.
When I run `"d:\Program Files\doxygen\bin\doxywizard.exe"` (which is the official 11.0.0 executable) and start it in the directory where the artifact versions of `doxywizard.exe` and `doxygen.exe` are the `doxywizard` started in this way will use the `d:\Program Files\doxygen\bin\doxygen.exe`.

When I copy `:\Program Files\doxygen\bin\doxywizard.exe` to the directory where the artifact `doxygen.exe` resides and start this copyed / official `doxywizard.exe` it will use the artifact `doxygen.exe`.

**Comment by thom-sch** [comment]
> When I copy `:\Program Files\doxygen\bin\doxywizard.exe` to the directory where the artifact `doxygen.exe` resides and start this copyed / official `doxywizard.exe` it will use the artifact `doxygen.exe`.

This is exactly what I've done.

**Comment by albert-github** [comment]
Did you start `doxywizard.exe` as `doxywizard.exe` or `.\doxywizard.exe`.
Please also check the version of the started `doxywizard` as I don't see the problem at my place.

**Comment by thom-sch** [comment]
In my directory there is the artifact doxygen.exe and the "official" doxywizard.exe:

![grafik](https://github.com/doxygen/doxygen/assets/44623251/01b2c7cb-8269-441d-85cf-ee91c3fa9a02)

In fact I've had started doxywizard.exe by simply doubleclicking via Windows-Explorer.

Running doxywizard from CLI with option `--version`:
`c:\Anwendungen\DocTools\doxygen_1.12.0_10916\bin>doxywizard --version`
and
`c:\Anwendungen\DocTools\doxygen_1.12.0_10916\bin>.\doxywizard --version`
both gives
![grafik](https://github.com/doxygen/doxygen/assets/44623251/c3a26b24-1c4b-4e0e-a3b3-d7981442e1b1)

Running doxywizard itself from CLI:
`c:\Anwendungen\DocTools\doxygen_1.12.0_10916\bin>doxywizard`
and
`c:\Anwendungen\DocTools\doxygen_1.12.0_10916\bin>.\doxywizard`
both gives
![grafik](https://github.com/doxygen/doxygen/assets/44623251/67735418-85ac-4ca7-a546-c0322ee3f9c1)

Running the original (artifact) doxywizard from this directory via CLI in both cases results in the error message:
![grafik](https://github.com/doxygen/doxygen/assets/44623251/da4599f2-a7af-48f8-b206-e344fa15a16b)

Regards from Meerbusch
Meerbusch

**Comment by albert-github** [comment]
So in fact you were able to run the 1.11.0 doxywizard (there have been no changes yet in the "1.12.0" / master version of the doxywizard) together with the update "1.12.0" / master version doxygen.exe as create by the GitHub Action.

**Comment by albert-github** [comment]
In the proposed PR @doxygen did the suggestion to perform the steps (in *nix terminology):
```
- curl -O https://download.qt.io/official_releases/online_installers/qt-unified-windows-x64-online.exe
- ./qt-unified-windows-x64-online.exe \
  --accept-licenses \
  --default-answer \
  --confirm-command install \
  qt.qt5.5152.win64_msvc2019_64
```
I didn't do the second step as I found a directory where I already did this a couple of years ago and for me it was sufficient to add the `bin` directory of this installation to the path.

You can always perform the installation manually by means of the GUI that will appear when you start the `qt-unified-windows-x64-online.exe` and follow the possible choices there.
I would certainly advise to use the "custom installation" and select "archive" on the "Select components" page and run "filter" here so you can select the "5.15.2" version.


So I think this issue is more a usage issue and something that won't be fixed.

**Comment by thom-sch** [comment]
Thanks for figuring ot the reason for the error message.
As I wrote in my opening issue: I see it as a small flaw an so I agree that this won't be fixed.
As far as I understood the reason is the missing Qt-runtime on my machine; so when I get the chance I will try your suggestion.

Thanks for the time you spent on this minor bug which obviously wasn't a problem for most of the users...

Thanks again - feel free to close this issue as solved.

Regards
Thomas
