### ISSUE TITLE
`qualifier` element has no type in `compound.xsd`

### ISSUE THREAD

**Issue by pcolby** [doxygen/doxygen#10913]
**Describe the bug**

Not really a bug, more of a to-do.

There's two `qualifier` elements in the `compound.xsd` file (under [`compounddefType`](https://github.com/doxygen/doxygen/blob/3192bd6992de727664f17107022aa36de3a0d9d3/templates/xml/compound.xsd#L35) and [`memberdefType`](https://github.com/doxygen/doxygen/blob/3192bd6992de727664f17107022aa36de3a0d9d3/templates/xml/compound.xsd#L196)).

In both cases, there is no `type` attribute provided (`type` is provided for every other element). So what type is it? I also can't see any `qualifier` elements in any of the test files, so presumably this feature is not being tested as far as XML output goes, so I can't infer its type from there either.

Cheers.

**Screenshots**

N/A

**To Reproduce**

N/A

**Expected behavior**

I expect those elements to have `type` attributes specified in `compound.xsd` 🙂

**Version**

All versions from v1.9.6 to the current `master`.

**Stack trace**

N/A

**Additional context**

N/A

**Comment by albert-github** [comment]
The `qualifier` elements in the compound.xsd contain just a string with all possible characters, so no validation is necessary end thus the `type` attribute has been omitted like in other cases where no further checking is done (see also the lines:
```
34:      <xsd:element name="scope" />
35:      <xsd:element name="name" />
44:      <xsd:element name="definition" minOccurs="0" />
45:      <xsd:element name="argsstring" minOccurs="0" />
46:      <xsd:element name="name" />
47:      <xsd:element name="qualifiedname" minOccurs="0"/>
48:      <xsd:element name="read" minOccurs="0" />
49:      <xsd:element name="write" minOccurs="0" />
50:      <xsd:element name="bitfield" minOccurs="0" />
69:      <xsd:element name="name" />
74:      <xsd:element name="attributes" minOccurs="0" />
76:      <xsd:element name="declname" minOccurs="0" />
77:      <xsd:element name="defname" minOccurs="0" />
78:      <xsd:element name="array" minOccurs="0" />
84:      <xsd:element name="label" />
87:      <xsd:element name="edgelabel" minOccurs="0" maxOccurs="unbounded"/>
```

As far as I remember this is done on purpose.

(same reasoning also for e.g the default `maxOccurs="unbounded"` that is sometimes omitted in combination with `minOccurs`).

**Comment by pcolby** [comment]
Ok, thanks. I shall treat them all as unrestricted strings then. Thanks :)
