### ISSUE TITLE
Wrong param and exception style in RTF output (Origin: bugzilla #141919)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1092]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.3.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2004-05-05 15:31:50 +0000, Frank HJ Cuypers wrote:

    For method descriptions, the paragraphs that form the text 
    of 'parameters', 'preconditions', 'exceptions' etc.. is output 
    in 'DescContinue 2' style. That style does not have hanging indents, which 
    becomes unreadable when you have multiple @param or @exception tags with 
    descriptions that take more then one line. I propose to output @param and 
    @exception info in another style.
    
    Current output is of the form:
    Parameters:
        <i>param1</i> this is the description
        of parameter 1. 
        <i>param2</i> this is the description
        of parameter 2. 
    
    I would prefer:
    Parameters:
        <b>param1</b>: this is the description
            of parameter 1. 
        <b>param2</b>: this is the description
            of parameter 2.

**Comment by albert-github** [comment]
With version 1.3.5 I could reproduce the indicated problems.
- The parameters are now placed in a table and there the problem does not occur anymore.
- The exceptions are now placed in a table and there the problem does not occur anymore, though in HTML the "exception object" looks like to be horizontally centered.
- The precondition is just a string of text and thus has no problem with a hanging indent (it is just a paragraph), maybe in case of multiple preconditions it would be good to have a little separation between the preconditions like with normal paragraphs.

Also the output for the other formats (at least LaTeX, doxbook) should be checked

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6811 for the other problems.

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
