### ISSUE TITLE
How remove vertical scrollbar in HTML content frame?

### ISSUE THREAD

**Issue by marwaygreg** [doxygen/doxygen#10936]
I was using 1.9.8, and updated to 1.11.0, macOS 14.5

Having generated HTML output for the project, tall web page content is now encompassed by a vertical scrollbar in the content wrapper block. This did not exist in the 1.9.8 output.  I can see where maybe this was intentional to maintain a fixed header location, but I want the normal browser window to do the scrolling, not an inset frame. I've looked through docs, settings, CSS file, and I don't see where this is being triggered.

I do use an extra CSS file (which limits the content width which is why you see the horizontal gap between the content scrollbar and the window edge). I have disabled my CSS to compare the result, and the problem still exists. I see the scrollbar is now at the very edge of the window so it that it *looks like* a normal scroll bar, but I still don't want that.

How do I remove this scrollbar?

(BTW, I see the Run menu item — woohoo, thanks.)

Thanks -- greg

![Dox-scrollbar-in-wrong-place](https://github.com/doxygen/doxygen/assets/167826709/8ca71333-86c0-4e6a-88b5-be3cfb9e5cbd)

**Comment by albert-github** [comment]
> I can see where maybe this was intentional to maintain a fixed header location, but I want the normal browser window to do the scrolling, not an inset frame.

It was indeed intentional as the scrollbar is between the "blue header" and the "blue footer", when removing the mentioned scrollbar it is very likely that the "blue footer" will also "float" upwards ore contain unwanted text.

**Comment by albert-github** [comment]
Maybe you could also have a look at the settings as shown in https://www.doxygen.nl/manual/customize.html

**Comment by albert-github** [comment]
Regarding the scroll bar it looks like it is steered (partial) by the `#doc-content` in the `navtree.css`.

**Comment by marwaygreg** [comment]
Yep. Been reading all through there, trying different CSS overrides. CSS inspector not really helping tell me where the scroll rule comes from either. Whatever. I'll just keep poking at it...

**Comment by marwaygreg** [comment]
Thanks — will check those clues out. (BTW, the "whatever" was for the inspector, not you! Usually I can find something via the inspector quickly.)

**Comment by marwaygreg** [comment]
Yep — adding the following override in my CSS worked. No side effects (at least for the way I have reworked the XML template). I see how I should have found it... but just wasn't seeing it.

Thanks.
```
#doc-content {
  overflow: visible;
  }
```

**Comment by albert-github** [comment]
Normally it is indeed quite easy to find settings using the inspector, though this was also for me not visible. I just found it (`#doc-content`) by a bit of trial and error.
