### ISSUE TITLE
Option USE_MDFILE_AS_MAINPAGE seems to not work correctly

### ISSUE THREAD

**Issue by TheScarfix** [doxygen/doxygen#10946]
**Describe the bug**
I want to use the README.md as main page for the documentation. I added it as first entry to the INPUT, and set it as the USE_MDFILE_AS_MAINPAGE option. But it doesn't show up as the main page.

**Expected behavior**
After adding README.md to INPUT and setting it as the USE_MD_FILE_AS_MAINPAGE option the content of README.md should be shown as the main page.

**Comment by albert-github** [comment]
Based on the given information it is not possible to tell what is the problem as there might be many causes, so essential:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).
- Please also specify the **full** doxygen version used (`doxygen -v`).

**Comment by TheScarfix** [comment]
I am trying from a fresh install right now and it seems to work now.
