### ISSUE TITLE
doxygen_bug__syntax_in_page_header

### ISSUE THREAD

**Issue by aotto1968** [doxygen/doxygen#10942]
**Describe the bug**
there is a problem between the usage of `@mainpage` and `@page`, the `@mainpage` show the **syntax** of the page-name in the example as *red-text* for `@mainpage` and *green-text* for `@page`. the *color-text* is used for the `@mainpage` header **and** for the `@page` reference. → GOOD

**but** on the `@page` itself the syntax is broken and displayed as **text** → BAD

**Screenshots**
1) the mainpage (color is used → good)
![image](https://github.com/doxygen/doxygen/assets/27886664/939955b3-e755-4197-9262-dc195c497794)
2) the "other" page (color is *not* used, syntax is added as **text** → bad)
![image](https://github.com/doxygen/doxygen/assets/27886664/b52c4fae-e414-4bb9-9690-1cf1cffbc93f)

**To Reproduce**
use the attachment.

**Expected behavior**
both, the `@mainpage` and the `@page` should display the *syntax* (color red)

**Version**
Doxygen version used: 1.10.0 (ebc57c6dd303a980bd19dd74b8b61c8f3f5180ca)
Linux linux02 5.14.21-150500.55.65-default #1 SMP PREEMPT_DYNAMIC Thu May 23 04:57:11 UTC 2024 (a46829d) x86_64 x86_64 x86_64 GNU/Linux

**Additional context**
attachment: 
[doxygen_bug__syntax_in_page_header.tar.gz](https://github.com/user-attachments/files/15836454/doxygen_bug__syntax_in_page_header.tar.gz)

**Comment by albert-github** [comment]
I think this problem has the same background / is the same as noted in #6998, so I mark this as a duplicate

**Comment by aotto1968** [comment]
good to know that the focus is already set → because this is important for my project. → thanks.

**Comment by albert-github** [comment]
FYI
This issue has been fixed in the current doxygen master 1.14.0 (18b0d0598af474f5c371979132044d4841356a1a) and will be available in the forthcoming 1.14.0 (planned to be released in the next few weeks).
