### ISSUE TITLE
extra <BR> at start using snippet{doc}

### ISSUE THREAD

**Issue by aotto1968** [doxygen/doxygen#10954]
**Describe the bug**
after using `snippet{doc}` I discovered an extra \<BR> at the start of the paragraph which corrupt the layout in a table

**Screenshots**
![image](https://github.com/doxygen/doxygen/assets/27886664/86dfa8fd-4482-413b-b544-cfb3d49d66ec)
after delete the \<BR> with the help of the browser HTML dev-tool the layout is ok
![image](https://github.com/doxygen/doxygen/assets/27886664/762c2272-4731-4899-a416-1f47f52bc370)

**To Reproduce**
use attachment 
[doxygen_bug__snipet_doc.tar.gz](https://github.com/user-attachments/files/15935662/doxygen_bug__snipet_doc.tar.gz)

**Expected behavior**
no \<BR> at startup

**Version**
latest from git

**Comment by albert-github** [comment]
Please specify "latest from git" as this is a moving target (so show the result of the command  `doxygen -v`.

**Comment by aotto1968** [comment]
> doxygen -v
1.12.0 (d51b6dfbd0a992199442039f3f5e4f2f23616384)

**Comment by aotto1968** [comment]
on, doxgen 1.10 is ok
![image](https://github.com/doxygen/doxygen/assets/27886664/e9062e58-9f84-4439-99bc-9fd4f53ffb9c)
doxygen 1.11 has the extra \<BR>
![image](https://github.com/doxygen/doxygen/assets/27886664/048bcfc8-a081-41a6-8927-d37f777ccd26)

**Comment by aotto1968** [comment]
sorry → this is a false report my shortcut was **not** on doxygen latest but on doxygen 1.11 → latest seems to be ok
![image](https://github.com/doxygen/doxygen/assets/27886664/f8437542-5614-405f-b939-52a3a0e7ef1f)
> doxygen-1.12.0 -v
1.12.0 (7673d22af1cea4d84bdc00164d9c9a25d693a714)
