### ISSUE TITLE
HTML comment affects output

### ISSUE THREAD

**Issue by MarkCallow** [doxygen/doxygen#10955]
**Describe the bug**
An HTML comment in a Doxygen comment affects both HTML and Man output. Extra space is added in HTML output while indentation is affected in Man output.

**Screenshots**
HTML output without HTML comment
<img width="2327" alt="Screenshot 2024-06-22 at 16 24 29" src="https://github.com/doxygen/doxygen/assets/2244683/039532be-32be-4133-b9c6-019fcb8c4207">

HTML output with HTML comment. Note the extra space (blank line)
<img width="2333" alt="Screenshot 2024-06-22 at 16 24 44" src="https://github.com/doxygen/doxygen/assets/2244683/c5cf146e-b8f6-40c0-8824-3a872f5c12da">

Man output without HTML comment
<img width="556" alt="Screenshot 2024-06-22 at 16 28 26" src="https://github.com/doxygen/doxygen/assets/2244683/8b077f6a-e514-4725-83ae-6c52aa853a7d">

Man output with HTML comment. Note the incorrect indent of the last paragraph which is next after the comment.
<img width="552" alt="Screenshot 2024-06-22 at 16 28 37" src="https://github.com/doxygen/doxygen/assets/2244683/f2910a2b-5536-4143-8b6f-153246b0832a">

**To Reproduce**
Use [html-comment-affects-output.tar.gz](https://github.com/user-attachments/files/15935688/html-comment-affects-output.tar.gz)

**Expected behavior**
I expected identical output with and without the embedded HTML comment.

**Version**
I'm using v1.11.0 on macOS Sonoma, the DMG downloaded from doxygen.nl. The issue is not new to 1.11.0. It has been around for a while.

**Stack trace**
n/a

**Additional context**
n/a

**Comment by albert-github** [comment]
First evaluation gives the impression that the embedded newline (not the `<br />`) causes the problem.

**Comment by MarkCallow** [comment]
> First evaluation gives the impression that the embedded newline (not the `<br />`) causes the problem.

Yes. In my testing I deleted the `<br />` from inside the comment. It made no difference to the result.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #10958

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.12.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
