### ISSUE TITLE
Feature Request: Option to generate searchdata.xml while retaining internal indexing

### ISSUE THREAD

**Issue by Philippe91** [doxygen/doxygen#10963]
**searchdata.xml** is extremely useful beyond its initial purpose: it can be parsed easily and allows users to locate a HTML page + anchor from a specific symbol. I use it to navigate to the Doxygen help from my IDE, thanks to a small custom app.

Currently, searchdata.xml is generated only when both SERVER_BASED_SEARCH and EXTERNAL_SEARCH are set to YES. Unfortunately, this configuration disables internal indexing, which is regrettable.

Therefore, I wish to have both internal indexing and the ability to generate searchdata.xml. I believe this could be achieved simply by adding an option, since all the necessary functionality is already in place.

**Comment by albert-github** [comment]
You wrote (in my words) that you use the HTML page name plus the  anchor to navigate and that you extract this from **searchdata.xml** .
I'm wondering why don't you use the tag file for the (`GENERATE_TAGFILE`) as the tag file can be generated at the same moment as the "internal search index".
Did you miss something in the tag file that is present in the `searchdata.xml`?

I added a small example with the resulting `searchdata.xml` and tag file as well (I generated here the tag file and the `searchdata.xml` in one go for my convenience): [example.tar.gz](https://github.com/user-attachments/files/16010489/example.tar.gz)

**Comment by Philippe91** [comment]
Thanks for your help. I did not know that tag file could embed somehow the same data. I will check it out more closely in the next days and come back.

**Comment by Philippe91** [comment]
@albert-github I confirm that a tag file fulfills the requirement 🙂 Thank you again for your help, and the issue can be closed.

Note: I am unsure if this is intentional or a bug, but while `searchdata.xml` is created in the `OUTPUT_DIRECTORY`, `tag.xml` is created in the directory of the `doxyfile `unless I specify an absolute path. This is at least an inconsistency.

**Comment by albert-github** [comment]
> Note: I am unsure if this is intentional or a bug, but while searchdata.xml is created in the OUTPUT_DIRECTORY, tag.xml is created in the directory of the doxyfile unless I specify an absolute path. This is at least an inconsistency.

Indeed I see the tag file on the current directory and the searchdata.xml on the `OUTPUT_DIRECTORY`.
@doxygen should the atg file also land on the `OUTPUT_DIRECTORY`?
