### ISSUE TITLE
Extra `void`s being added to function return

### ISSUE THREAD

**Issue by pzich** [doxygen/doxygen#10965]
**Describe the bug**
Looking at the [member function list](https://esphome.io/api/classesphome_1_1display_1_1_display) for the various `printf()` and `strftime()` functions, you can see an increasing number of `void`s being added to the return types. However, if you click on the links for these, you can see the individual results only have a single `void`. If you look at [the source](https://github.com/esphome/esphome/blob/dev/esphome/components/display/display.h#L383) you can also see that no such additional voids are written.

**Screenshots**
<img width="1180" alt="extra voids" src="https://github.com/doxygen/doxygen/assets/706138/43d7013b-0aa8-4b8d-8b67-17f2d8692281">

<img width="645" alt="single voids shown for the function details" src="https://github.com/doxygen/doxygen/assets/706138/9f0752d2-3312-4fa0-bb2f-8b30ab26a091">

**To Reproduce**
I have not been able to get this to occur in a separate test file so have not been able to create a minimal repro. Any help diagnosing what is happening in the existing codebase would be appreciated.

**Expected behavior**
Only a single `void` should be shown before each line.

**Version**
1.9.4 running on macOS 13.6

**Comment by albert-github** [comment]
It might have been a problem in the doxygen 1.9.4 version, the current doxygen version is 1.11.0
- what happens when you use the current doxygen version?
- what is in your `Doxyfile`?

**Comment by albert-github** [comment]
What happens when you set:
```
PREDEFINED = __attribute__(x)=
MACRO_EXPANSION = YES
```

**Comment by albert-github** [comment]
In the experiment I did the solution given in https://github.com/doxygen/doxygen/issues/10965#issuecomment-2192227493 and documented in the doxygen manual (see https://www.doxygen.nl/manual/preprocessing.html) gives correct results.
Setting issue to usage
