### ISSUE TITLE
Support C++ specialization with explicit scope

### ISSUE THREAD

**Issue by mglisse** [doxygen/doxygen#10984]
**Describe the bug**
With the program below, doxygen complains
> /tmp/dox/a.cc:5: warning: Internal inconsistency: scope for class std::hash< AAA > not found!

**To Reproduce**
```c++
#include <functional>
/** blabla */
struct AAA {};
/** hello */
template<>struct std::hash<AAA>{};
```

**Expected behavior**
I would expect the same behavior as
```c++
#include <functional>
/** blabla */
struct AAA {};
namespace std {
/** hello */
template<>struct hash<AAA>{};
}
```
which does not complain

**Version**
1.9.8 (debian binary package 1.9.8+ds-2+b1)
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux trixie/sid
Release:	n/a
Codename:	trixie

I still see the same issue with the 1.11.0 binaries from the doxygen website.

**Comment by albert-github** [comment]
Small question is: how should doxygen know that `std` is a namespace? (a human reader knows that in cpp `std` is a namespace, but the problem is more general).
In the output doxygen assumes it is a namespace but in fact this is a bit dubious in my opinion as when specifying:
```
class std {};
```
doxygen will see `std` as a class in the global namespace and handle as such.

**Comment by mglisse** [comment]
> how should doxygen know that `std` is a namespace?

That's a very good question :thinking: 
If you defer the decision enough, clang may be able to tell you, or hitting the inconsistency mentioned in the error message could be taken as a hint. But locally the syntax does not disambiguate indeed.
A special case for `std` may be better than nothing.

**Comment by mglisse** [comment]
Ah, indeed, I did not know about BUILTIN_STL_SUPPORT, it looks like the special case I was asking for already exists :smile: 
Thank you.

**Comment by mattgodbolt** [comment]
I have a similar set of errors/warnings over other specialisations. I stumbled over this setting through google searches and it fixes the `std::hash<>` issues, but things like:

* fmt::formatter
* nlohman::adl_serializer
* ankerl::unordered_dense::hash

all error out with stl-like issues. Is there a more general workaround for these cases?

```
/home/mgodbolt/dev/wave/src/wave/Squ.hpp:43: error: Internal inconsistency: scope for class ankerl::unordered_dense::hash< wave::Squ > not found!
/home/mgodbolt/dev/wave/src/wave/Squ.hpp:50: error: Internal inconsistency: scope for class nlohmann::adl_serializer< wave::Squ > not found!
/home/mgodbolt/dev/wave/src/wave/TimestampFmt.hpp:13: error: Internal inconsistency: scope for class fmt::formatter< std::chrono::time_point< wave::WaveClock< ClockTag > > > not found!
/home/mgodbolt/dev/wave/src/wave/cstring_view.hpp:64: error: Internal inconsistency: scope for class fmt::formatter< wave::cstring_view > not found!
/home/mgodbolt/dev/wave/src/wave/join_up_to.hpp:29: error: Internal inconsistency: scope for class fmt::formatter< wave::join_up_to_view< It, Sentinel, Char >, Char > not found!
```

**Comment by mattgodbolt** [comment]
I have warnings as errors in my project so I have to skip these, so I don't know. They're helper functions I'd rather not document anyway honestly.
