### ISSUE TITLE
Doxygen 1.11.0 for macOS reports 'sh: latex: command not found'

### ISSUE THREAD

**Issue by aeronautomat** [doxygen/doxygen#10987]
**Bug Description**
When starting the macOS GUI App 'Doxygen.app', downloaded fom https://www.doxygen.nl/files/Doxygen-1.11.0.dmg it reports

    sh: latex: command not found

when klicking 'Run doxygen' at the 'Run' tab in the app.

However, on my system 'latex' _does exist_ in directory `/Library/TeX/texbin`.

The command `doxygen` (the command line version) executed in a bash shell does finds 'latex'.

Doxygen.app does not seem to utilise a proper PATH environment variable.

Interestingly, doxygen provides configuration variables for setting the location of (only) _some_ executables, like e.g. `DOT_PATH`. Such a provision does not exist for 'latex', however.

Please either provide a configuration variable like e.g. `TEX_PATH` or set up the app accordingly.

**Version**
doxygen 1.11.0
macOS Sonoma 14.5
GNU bash, Version 5.2.26(1)-release

**Comment by albert-github** [comment]
Disclaimer: I'm not a MacOS user

It looks like to me that when running `doxygen` from the `doxywizard` (this is what happens as for as I can see)  a shell is started 
but that this shell does not use the `PATH` as it would when using `doxygen` from  the "command line".
- did it work for older versions of doxygen? Which ones did you test / use?

This looks to me like a problem in the startup files of the used shell.
- what happens when you start a separate shell and subsequently start doxygen like:
  - `sh`
  - goto the right directory
  - `doxygen`

**Comment by aeronautomat** [comment]
I answered your question(s) in my post above: Invoked from a shell doxygen does not exhibit the reported behavior.

No offence, but please don’t rely on unconfirmed assumptions:

>This looks to me like a problem in the startup files of the used shell.

Do macOS Apps (in `/Applications` directory) use a shell? If yes, what are the used startup files?

This seem to lead to the wrong track …

**Comment by albert-github** [comment]
>I answered your question(s) in my post above: Invoked from a shell doxygen does not exhibit the reported behavior.
>
> No offence, but please don’t rely on unconfirmed assumptions:

A system has in general multiple shells and it was / is not clear which shell is used in the different cases . Each shell can lead to different problems (and I've seen a few ...) and I see that from the `doxywizard the `sh` shell is started and from the command line the `bash` shell and they don't have to be the same shells.

**Comment by aeronautomat** [comment]
I can’t answer this, I’m afraid.

**To reproduce**
- download the app (link provided above)
- install the app
- run the app

**Comment by albert-github** [comment]
One thing you might be able to answer, what are the answers from the followin commands on the command line:
- echo $SHELL
- which sh

**Comment by aeronautomat** [comment]
$ echo $SHELL
    /bin/bash

    $ which sh
    /bin/sh

**Comment by albert-github** [comment]
OK, and what gives:
- ls -ls /bin/bash
- ls -ls /bin/sh
- Md5sum /bin/bash /bin/sh

**Comment by doxygen** [comment]
@aeronautomat I suggest to edit you `~/.bashrc` file and add
```sh
export PATH="/Library/TeX/texbin/:$PATH"
```
After that open a new terminal and type `which latex`. If that lists the correct path, doxywizard should also be able to find it. 

Note that the default shell on MacOS is zsh, not bash, so it could be that this is used and you need to add the above line to `~/.zshrc` instead (create the file if it doesn't exist).

**Comment by aeronautomat** [comment]
$ ls -ls /bin/bash
    1368 -r-xr-xr-x  1 root  wheel  1310352  7 Mai 09:01 /bin/bash

    $ ls -ls /bin/sh
    24 -rwxr-xr-x  1 root  wheel  101232  7 Mai 09:01 /bin/sh

    $ md5sum /bin/bash /bin/sh
    ce49481a54cd33907c3e34002c4f5275  /bin/bash
    cfdcfe06a48ba4a7736163827f2eaceb  /bin/sh

**Comment by albert-github** [comment]
@aeronautomat so we see that the shells are different and I think the comment @doxygen made in https://github.com/doxygen/doxygen/issues/10987#issuecomment-2211744256 might solve your issue.

**Comment by albert-github** [comment]
On *nix system normally there are a few ways to solve the issue
- move the `sh` aside and create a symbolic link from `zsh` to `sh`
- adjust the startup file used by `sh`, by head this could be the `.profile` file

**Comment by doxygen** [comment]
@aeronautomat I see what you mean now. The environment for launching GUI applications is set by `launchctl`. In MacOS versions <14 this could be manipulated via `environment.plist`. It seems like as of MacOS 14 (Sonoma) things have been made worse by ignoring the PATH variable set this way. I found this on the topic: https://www.reddit.com/r/MacOS/comments/12ryky5/add_systemwide_environmentvariables_in_macos/

For now, the only way out I see is to indeed add an `EXTRA_PATHS` kind of option to doxygen that appends paths to the standard search path before doxygen launches external commands. Next to `latex` doxygen can also runs `gs`, `dvips`, `perl`, `epstopdf`, `pdf2svg`. `inkscape`, `htags` and more, so a single `TEXBIN_PATH` may be too limiting.

**Comment by doxygen** [comment]
@aeronautomat Please verify if the referenced commit fixes the problem for you. Do not close the issue, this will be done automatically when the next official release becomes available.

Note the new option's name is `EXTERNAL_TOOL_PATHS`

**Comment by MarkCallow** [comment]
> @aeronautomat I see what you mean now. The environment for launching GUI applications is set by `launchctl`. In MacOS versions <14 this could be manipulated via `environment.plist`. It seems like as of MacOS 14 (Sonoma) things have been made worse by ignoring the PATH variable set this way. I found this on the topic: https://www.reddit.com/r/MacOS/comments/12ryky5/add_systemwide_environmentvariables_in_macos/
> 

Apple hasn't supporting setting the PATH variable for launchctl-launched apps via any mechanism for many releases now. Even `launchctl setenv` doesn't work. I think macOS Lion may have been the first without the support.

> For now, the only way out I see is to indeed add an `EXTRA_PATHS` kind of option to doxygen that appends paths to the standard search path before doxygen launches external commands.

Given the above, yes. When adding `EXTRA_PATHS` the code should probably check for the directories' presence in PATH first as they may already be there when `doxygen` is run from a shell.

**Comment by doxygen** [comment]
> > For now, the only way out I see is to indeed add an `EXTRA_PATHS` kind of option to doxygen that appends paths to the standard search path before doxygen launches external commands.
> 
> Given the above, yes. When adding `EXTRA_PATHS` the code should probably check for the directories' presence in PATH first as they may already be there when `doxygen` is run from a shell.

Not sure what you mean here. Do you mean that the directory `EXTRA_PATHS` should be searched first (i.e. `NEW_PATH=$EXTRA_PATHS:$PATH`), or do you mean the standard `PATH` should be searched first (i.e. `NEW_PATH=$PATH:$EXTRA_PATHS`)?

**Comment by MarkCallow** [comment]
> Not sure what you mean here. Do you mean that the directory `EXTRA_PATHS` should be searched first (i.e. `NEW_PATH=$EXTRA_PATHS:$PATH`), or do you mean the standard `PATH` should be searched first (i.e. `NEW_PATH=$PATH:$EXTRA_PATHS`)?

Neither. I mean the code should search for each item in EXTRA_PATHS in the PATH environment variable it is already using and only if that item is not already present add it to the PATH environment variable. It is a small thing that may help avoid breaking a search order someone has carefully set up for their shell.

I don't think it matters too much whether you add the new items at the front or end of $PATH but you should document the choice you make.

**Comment by albert-github** [comment]
My 2 cents
I think it matters quite a bit  where it is added as when the `EXTERNAL_TOOL_PATHS` path contains a program (say) `X` and another program `X` is present in the "old" `PATH`, the chosen `X` is depending on the order!
I think best would always to have that the user specified path has precedence, so `EXTERNAL_TOOL_PATHS` should be before the "old" `PATH`.

**Comment by MarkCallow** [comment]
For running in the GUI it doesn't matter because the initial PATH will be limited to what Apple's default path which is has only a handful of system directories, where only Apple can install code, and possibly /usr/local/bin. I don't have time to check the latter right now.

For running from the shell my proposal to check for a directory already being in the path is intended to mitigate some of the issues but indeed it doesn't help if there are 2 copies of a program in different directories in the path. I agree `EXTERNAL_TOOL_PATHS` should be inserted at the front of `PATH`.

By the way, plural is not needed in the attribute name. A path is a list of directories.

**Comment by doxygen** [comment]
As suggested, I committed two more changes:

- Renamed `EXTERNAL_TOOL_PATHS` to `EXTERNAL_TOOL_PATH`
- Prepend directories to `PATH` instead of appending them.

Behavior is now also better documented.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.12.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
