### ISSUE TITLE
JAVADOC_AUTOBRIEF=NO ignored when JAVADOC_BANNER=YES

### ISSUE THREAD

**Issue by ChrisIdema** [doxygen/doxygen#10983]
**Describe the bug**
I have a source file with Javadoc style comments. I set JAVADOC_BANNER=YES so I can extract commands from javadoc style comments and not just from doxygenstyle comments. I set JAVADOC_AUTOBRIEF=NO so I do not extract non-doxygen style commands and only explicit briefs. I expect all functions with briefs to be documented and all functions without briefs not documented. But this is not the case.

**To Reproduce**
I've attached files to replicate the problem:
[a.c.txt](https://github.com/user-attachments/files/16097339/a.c.txt)
[Doxyfile.txt](https://github.com/user-attachments/files/16097146/Doxyfile.txt)
Remove the txt extension and run Doxywizard.
correct: I see function b() and function d() documented under "Functions".
Incorrect: I see function a() documented under "Function Documentation".
Incorrect: I do not see function b() and function d()  documented under "Function Documentation".
correct: I do not see function c() documented at all

**Expected behavior**
```
# If the JAVADOC_AUTOBRIEF tag is set to YES then doxygen will interpret the
# first line (until the first dot) of a Javadoc-style comment as the brief
# description. If set to NO, the Javadoc-style will behave just like regular Qt-
# style comments (thus requiring an explicit @brief command for a brief
# description.)
# The default value is: NO.
```

function b() and function d() documented under "Functions" and under "Function Documentation".
function a() and c() NOT documented at all as autobrief is disabled and these have no brief

**Version**
Doxygen 1.11.0. Windows 11. 
I also tried Doxygen 1.9.6 and it had different, but also incorrect behavior.

**Comment by albert-github** [comment]
In the example the `JAVADOC_AUTOBRIEF is set to `NO`, so no special handling.

We see that the functions `b` and `d` only have an explicit `\brief` documentation and hence the brief documentation is mentioned under "Functions", they have no detailed documentation and also the `ALWAYS_DETAILED_SEC=NO` so no they are not mentioned under "Function Documentation".

The functions `a` and `c` have no brief documentation but just detailed documentation so in the "Functions" list only the name of the function is mentioned and the detailed section "Function Documentation" these 2 functions are mentioned.

It looks all OK to me or did I miss a point?

**Comment by ChrisIdema** [comment]
> The functions `a` and `c` have no brief documentation but just detailed documentation so in the "Functions" list only the name of the function is mentioned and the detailed section "Function Documentation" these 2 functions are mentioned.
>

They have no doxygen commands and no autobrief, so there is neither a brief nor other doxygen commands. So why does doxygen treat the text as detailed documentation? I want blocks without any doxygen commands to not be processed.
Is there a way to turn off this feature? Something like AUTODETAIL=NO. I would like to hide a and c but show b and d.

> We see that the functions `b` and `d` only have an explicit `\brief` documentation and hence the brief documentation is mentioned under "Functions", they have no detailed documentation and also the `ALWAYS_DETAILED_SEC=NO` so no they are not mentioned under "Function Documentation".

I didn't know that. That helps. I've turned that on and that at least puts b and d there. Now I just need a way to hide a and c.

**Comment by albert-github** [comment]
> So why does doxygen treat the text as detailed documentation?

Doxygen handles all comment blocks that start with doxygen specific comment marker (like `/**`, see https://www.doxygen.nl/manual/docblocks.html). 

> I want blocks without any doxygen commands to not be processed.
> Is there a way to turn off this feature?

This can be done by using non doxygen specific comment markers (so like `/*` or with a banner like `/* **********`).

**Comment by ChrisIdema** [comment]
> 
> > I want blocks without any doxygen commands to not be processed.
> > Is there a way to turn off this feature?
> 
> This can be done by using non doxygen specific comment markers (so like `/*` or with a banner like `/* **********`).

This doesn't work with JAVADOC_BANNER=YES

**Comment by albert-github** [comment]
What do you mean with `JAVADOC_BANNER=YES` ? 
Please give a smal example

**Comment by ChrisIdema** [comment]
HIDE_UNDOC_MEMBERS=YES didn't help. I guess what I want is impossible. I just want to be able to use javadoc style comments and only document them if they have explicit doxygen comments in them. But I guess that option is not available since any text in a comment block doxygen sees as a doxygen comment block will be seen as a detailed description.
Correct me if I'm wrong.

**Comment by albert-github** [comment]
>  I just want to be able to use javadoc style comments and only document them if they have explicit doxygen comments in them. But I guess that option is not available since any text in a comment block doxygen sees as a doxygen comment block will be seen as a detailed description.

I think this summarizes it quite well.
When you want a visible line in a bit of a javadoc style to separate parts of the code, the only thing I see is what I wrote in https://github.com/doxygen/doxygen/issues/10983#issuecomment-2209321143 in respect to `/* *******`

**Comment by ChrisIdema** [comment]
```
/** **************************************************************************
 * \brief alternative doxygenstyle 1a
 *****************************************************************************/
void e(void)
{	 
}

/*!***************************************************************************
 * \brief alternative doxygenstyle 2a
 *****************************************************************************/
void h(void)
{	 
}    

/*! **************************************************************************
 * \brief alternative doxygenstyle 2c
 *****************************************************************************/
void I(void)
{	 
}    
```

I experimented up with a few alternative styles that are more aesthetically pleasing. But these brief commands end up being interpreted as detailed comments. In the documentation of doxygen it is not explained why this would not work. Only examples are given, no exact rules.

**Comment by albert-github** [comment]
```
/** **************
```
should be:
```
/* ***************
```

**Comment by albert-github** [comment]
Did some misinterpretation of the comment https://github.com/doxygen/doxygen/issues/10983#issuecomment-2210585150
comment https://github.com/doxygen/doxygen/issues/10983#issuecomment-2210591235 should be ignored.

Might it be that it is a combination of `REPEAT_BRIEF = YES` and `ALWAYS_DETAILED_SEC = YES`

**Comment by ChrisIdema** [comment]
I now see doxygen converts the asterisks to a long thin blue line. I give up. I'll just stick to the ugly comments.
