### ISSUE TITLE
Function parsing fails on "[["

### ISSUE THREAD

**Issue by jpsilverberg** [doxygen/doxygen#10981]
**Describe the bug**
Whenever a string is added which is "[[", the function does not parse.

**Screenshots**
In the XML output for the location, bodyend="-1"

**To Reproduce**
Add:    std::string l_String("[["); to any function

**Expected behavior**
I would expect the function to parse.

**Version**
doxygen 1.9.1
Distributor ID:	Pop
Description:	Pop!_OS 22.04 LTS
Release:	22.04
Codename:	jammy

from apt.

**Additional context**
"[" + "[" is ok.

**Comment by albert-github** [comment]
The description is quite meager so in future always:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).

The doxygen version 1.9.1 already a bit older (January 8, 2021) the current doxygen version is 1.11.0

I tried with:
```
/// \file

/// the fie_0
void fie0()
{
}

/// the fie_1
void fie1()
{
  std::string l_String("[[");
}

/// the fie_2
void fie2()
{
}
```
And in the XML output with doxygen version 1.9.1 I see for `fie1` the `bodyend="-1"` and `fie2` does not appear at all, also the HTML output signals this quite clearly:
![image](https://github.com/doxygen/doxygen/assets/5223533/5c58c963-0b88-45bd-83f5-232b68c26194)

When using the current doxygen version (1.11.0) we see in the XML output for the `fie1` is `bodyend="12"` and also the `fie2` is properly visible and the HTML output looks like;
![image](https://github.com/doxygen/doxygen/assets/5223533/fc034a36-3359-4f55-a731-8e45bf13f769)


So I think the problem has been solved in the mean time

**Comment by jpsilverberg** [comment]
I built 1.11.0 and I concur, I think the problem has been solved.  Thank you so much.
