### ISSUE TITLE
Preprocessor warning for defined variable

### ISSUE THREAD

**Issue by albert-github** [doxygen/doxygen#11005]
In case we have the simple program:
```
#define APLOG_MAX_LOGLEVEL

#define APLOG_TRACE1 8

#ifdef  APLOG_MAX_LOGLEVEL
#if     APLOG_MAX_LOGLEVEL < APLOG_TRACE1
#endif
#endif
```
And a default doxygen settings file, we get the error:
```
bb.h:8: warning: preprocessing issue while doing constant expression evaluation: syntax error:
    input='     APLOG_MAX_LOGLEVEL < APLOG_TRACE1'
    doxygen interpretation '      < 8 '
```

Shouldn't the `APLOG_MAX_LOGLEVEL ` take the value `0` in case it is defined (but has no value) and is preceded or followed by a  numerical / boolean test (i.e. like `+`, `-`, `<`) operator?

Tested with current master: 1.12.0 (e5845fa4399700adeb922433f2fcd5939c7c8618)

Example: [example.tar.gz](https://github.com/user-attachments/files/16249186/example.tar.gz)

(Found by fossies for the httpd package)

**Comment by doxygen** [comment]
> Shouldn't the `APLOG_MAX_LOGLEVEL` take the value `0` in case it is defined (but has no value) and is preceded or followed by a numerical / boolean test (i.e. like `+`, `-`, `<`) operator?

No, an undefined value should resolve to an empty string, rendering the expression invalid.

If you run this through a normal preprocessor, it will also produce an error, i.e.

`g++ -E test.cpp`

gives

```
test.cpp:6:28: error: invalid token at start of a preprocessor expression
#if     APLOG_MAX_LOGLEVEL < APLOG_TRACE1
                           ^
```

**Comment by albert-github** [comment]
I thought that that I remembered that the value was taken as 0, but this might have been the case in an old (fulty) compiler.
I could also not find any evidence in K&R.
