### ISSUE TITLE
highlight Fenced Code Blocks with highlight.js

### ISSUE THREAD

**Issue by zhangzq** [doxygen/doxygen#11017]
Currently doxygen outputs html codes for Fenced Code Blocks internally. Can doxygen output the code blocks in `<pre/>` and let hightlight.js (or similar frontend syntax highlighter) to highlight the code in frontend?

This will make the highlight be more customizable (and prettier, I think).

For example, highlight.js can automatically check the language type, and choose the most suitable color schema, and lots of other features.

I think this also decrease the work of doxygen itself.

ref: <https://highlightjs.org/>

**Comment by albert-github** [comment]
Which version of doxygen are we talking about?

Doxygen already chooses the code highlighting based on the language (and is possible to specify it by means of e.g ` ```{.cpp} ` or ` ```{.py} `.
Furthermore all colors are mentioned in the `doxygen.css` file on the resulting html directory and these colors can be adjusted and fed to doxygen (see also `HTML_EXTRA_STYLESHEET`).

What are you missing?

**Comment by zhangzq** [comment]
I use the latest version.

For the ` ```{.cpp}`, I know doxygen already highlight base on the language, but here is more:

- the indent code block can't specifiy the language.
- highlight.js has more features, for example, can automatically check the language type when user not specify the language.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.12.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
