### ISSUE TITLE
compound.xsd is missing types for some elements

### ISSUE THREAD

**Issue by ilitzroth** [doxygen/doxygen#11013]
**Describe the bug**
When I run the xsd program (https://www.codesynthesis.com/products/xsd/) on the compound.xsd that is generated by doxygen it complains of the following missing type attributes:
>>>
compound.xsd:35:75: warning F001: element 'qualifier' is implicitly of anyType
compound.xsd:35:75: info: did you forget to specify 'type' attribute?
compound.xsd:68:35: warning F001: element 'scope' is implicitly of anyType
compound.xsd:68:35: info: did you forget to specify 'type' attribute?
compound.xsd:69:34: warning F001: element 'name' is implicitly of anyType
compound.xsd:69:34: info: did you forget to specify 'type' attribute?
compound.xsd:187:54: warning F001: element 'definition' is implicitly of anyType
compound.xsd:187:54: info: did you forget to specify 'type' attribute?
compound.xsd:188:54: warning F001: element 'argsstring' is implicitly of anyType
compound.xsd:188:54: info: did you forget to specify 'type' attribute?
compound.xsd:189:34: warning F001: element 'name' is implicitly of anyType
compound.xsd:189:34: info: did you forget to specify 'type' attribute?
compound.xsd:190:56: warning F001: element 'qualifiedname' is implicitly of anyType
compound.xsd:190:56: info: did you forget to specify 'type' attribute?
compound.xsd:191:48: warning F001: element 'read' is implicitly of anyType
compound.xsd:191:48: info: did you forget to specify 'type' attribute?
compound.xsd:192:49: warning F001: element 'write' is implicitly of anyType
compound.xsd:192:49: info: did you forget to specify 'type' attribute?
compound.xsd:193:52: warning F001: element 'bitfield' is implicitly of anyType
compound.xsd:193:52: info: did you forget to specify 'type' attribute?
compound.xsd:196:75: warning F001: element 'qualifier' is implicitly of anyType
compound.xsd:196:75: info: did you forget to specify 'type' attribute?
compound.xsd:278:34: warning F001: element 'name' is implicitly of anyType
compound.xsd:278:34: info: did you forget to specify 'type' attribute?
compound.xsd:295:54: warning F001: element 'attributes' is implicitly of anyType
compound.xsd:295:54: info: did you forget to specify 'type' attribute?
compound.xsd:297:52: warning F001: element 'declname' is implicitly of anyType
compound.xsd:297:52: info: did you forget to specify 'type' attribute?
compound.xsd:298:51: warning F001: element 'defname' is implicitly of anyType
compound.xsd:298:51: info: did you forget to specify 'type' attribute?
compound.xsd:299:49: warning F001: element 'array' is implicitly of anyType
compound.xsd:299:49: info: did you forget to specify 'type' attribute?
compound.xsd:320:35: warning F001: element 'label' is implicitly of anyType
compound.xsd:320:35: info: did you forget to specify 'type' attribute?
compound.xsd:329:74: warning F001: element 'edgelabel' is implicitly of anyType
compound.xsd:329:74: info: did you forget to specify 'type' attribute?
>>>

**To Reproduce**
run the xsd program on the compound.xsd in the repo under 
templates/xml

**Expected behavior**
No warnings, i.e. the types of all the elements is specified.

**Version**
1.11.0, but also tested on the repo.

**Additional context**
I'm trying to write a convertor from the xml produced by doxygen to texinfo.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #11014

**Comment by ilitzroth** [comment]
That is the fix I applied locally :-)

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.12.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
