### ISSUE TITLE
Documentation is not clear using preprocessor options

### ISSUE THREAD

**Issue by kdschlosser** [doxygen/doxygen#11025]
I am looking to have doxygen expand the macros. I have `ENABLE_PREPROCESSING` turned on and I also have `MACRO_EXPANSION` turned on as well and I am trying to use the `PREDEFINED` setting but it doesn't seem to be working. The documentation is not 100% clear on what is usable and when. For example the config option `EXPAND_ONLY_PREDEF`  it states the following

```
If the EXPAND_ONLY_PREDEF and MACRO_EXPANSION tags are both set to YES then
the macro expansion is limited to the macros specified with the PREDEFINED and
EXPAND_AS_DEFINED tags.
```

That leads me to believe that doxygen will ONLY expand the macros seen in `EXPAND_AS_DEFINED ` and in `PREDEFINED` but it will no longer expand any of the macros in the source files. That is the only mention of PREDEFINED which leads me to believe that it is not used at all unless the `EXPAND_ONLY_PREDEF` is set. The reason why I am saying this is because there are macros that I have listed in `PREDEFINED` but they are not being expanded when doxygen is run even tho I have the `MACRO_EXPANSION` and `ENABLE_PREPROCESSING` turned on. 

If someone could give me a little clarification on how to all works that would be a HUGE help...

**Comment by albert-github** [comment]
To be able to help you (as I don't experience problems):
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).
- Please also specify the **full** doxygen version used (`doxygen -v`).
