### ISSUE TITLE
File member menu entry is not available unless EXTRACT_ALL is used.

### ISSUE THREAD

**Issue by ghosty141** [doxygen/doxygen#11027]
**Describe the bug**

With this [config](https://github.com/user-attachments/files/16373604/config.txt) I can't get the "File Members" menu entry to generate even though I have freestanding functions with documentation in the code (C++ project). The only way that menu entry shows up is if I use `EXTRACT_ALL=YES` which has the "bad" consequence of adding everything to the documentation which is not desired.

Is there anything I'm missing? Currently the menu looks like this: 
![image](https://github.com/user-attachments/assets/658d28ab-3a3c-49b4-bd27-a8e322ab07c8)

**Comment by albert-github** [comment]
Without an example it is not possible to say something, so:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).
- Please also specify the **full** doxygen version used (`doxygen -v`).

**Comment by ghosty141** [comment]
Thanks for the quick reply. I created a small example project: [Test.zip](https://github.com/user-attachments/files/16375710/Test.zip)

It exhibits the same problem, the file members menu entry only shows if `EXTRACT_ALL` is set to `YES`.

Version: 1.11.0 (9b424b03c9833626cd435af22a444888fbbb192d)

**Comment by albert-github** [comment]
Sometimes doxygen thinks that a file has nothing to display, in those cases it is best to document the file with the `\file` command or at least add the line:
```
/// \file
```
to the file.

@doxygen should we qualify this as a bug?

**Comment by ghosty141** [comment]
> Sometimes doxygen thinks that a file has nothing to display, in those cases it is best to document the file with the `\file` command or at least add the line:
> 
> ```
> /// \file
> ```
> 
> to the file.
> 
> @doxygen should we qualify this as a bug?

Thanks! This works although I believe this definitely should be classified as a bug. In C++ it's quite common to have files that just hold a bunch of functions without a namespace and adding the file tag there seems a bit odd since if it's a class it would "just work" and the fact that I'm documenting functions or classes should not be that influential.

**Comment by albert-github** [comment]
@doxygen 
It looks like that in index.cpp the function `Index::addFileMemberNameToIndex` is the "problem".
Here we have:
```
  const FileDef *fd=md->getFileDef();
  if (fd && fd->isLinkableInProject() && md->isLinkableInProject())
```
and both `fd->isLinkableInProject()` and `md->isLinkableInProject()` return `false` so the adding is skipped (all due to the fact that the file is not documented).

**Comment by doxygen** [comment]
This behavior has been like this from the start. It is also mentioned in the FAQ.
https://www.doxygen.nl/manual/faq.html#faq_extract_all

Since people may depend on hiding the non-interesting files this way, I don't think it is good idea to change this.

**Comment by ghosty141** [comment]
Alright, thanks for the quick support though!
