### ISSUE TITLE
unable to add a `..` code section with "@alias" string WITHOUT expanding the alias

### ISSUE THREAD

**Issue by aotto1968** [doxygen/doxygen#11034]
**Describe the bug**
I try to add a  *code-section* `abc @TO xyz` with a `@TO` substring **but** the `TO` is an alias.
- I'm not able to *disable* the alias substitution **in** a *code-section*

**Screenshots**
![image](https://github.com/user-attachments/assets/cf021956-7709-484f-9dcc-d0620d7813f9)

**To Reproduce**
use the attachment: 
[doxygen_bug__inline_code_with_alpha.tar.gz](https://github.com/user-attachments/files/16402517/doxygen_bug__inline_code_with_alpha.tar.gz)

**Expected behavior**
a *trick* to disable the **alias**

**Version**
1.12.0 (14fc65f92184f8d788d5fb2723fb28e773dc4a5a)
    with sqlite3 3.42.0.

**Comment by albert-github** [comment]
Unfortunately you probably forgot to add the attachment with the example to reproduce the problem.

**Comment by aotto1968** [comment]
add attachment done.

**Comment by albert-github** [comment]
The only way I see here is to replace
```
- test: `abc @TO xyz`
```
by
```
- test: <tt>abc @@TO xyz</tt>
```
or by the probably less easy to implement:
 ```
 - test: \c abc \c @@TO \c xyz
 ```

**Comment by aotto1968** [comment]
the `@TO` still not working with `<tt>...</tt>` in my code 
- have to replace `@TO` with `@TO_SYSTEM` (note: `-` to `_`)

and now as **bonus** with `<tt>` the `__` are replaced by *bold*
- `__parser__global__` became now **parser_global**
- ![image](https://github.com/user-attachments/assets/cf6d38c1-7236-44f5-acdb-284f166ea6ca)

→ still not happy → I just miss a *do-nothing-and-put-everything-unchanged-in-a-verbose-text* mode

**Comment by albert-github** [comment]
- Regarding the `@TO` within `<tt>` I don't understand the test I supplied looks OK
- Regarding the underscores when using them insite the `<tt>` you have to escape them as well.

My tests:
```
/**

\mainpage bug

Problem: unable to add a \@TO \b string into a \`...\` code section if a \c TO alias exists.

config: <TT> ALIASES += "TO=xxx"</TT>

- test: `abc @TO xyz`
- test: <tt>abc @@TO xyz</tt>
- test: \c abc \c \@TO \c xyz
- test: `abc \@TO xyz`
- test: `abc @@TO xyz`

- now the underscores: `__parser__global__`
- now the underscores: <tt>\__parser\__global\__</tt>

**/
```
Result:
![image](https://github.com/user-attachments/assets/1aa80a99-5f7f-471f-99ca-815d4347ef1e)

Example: [example.tar.gz](https://github.com/user-attachments/files/16404321/example.tar.gz)

**Comment by aotto1968** [comment]
ok I have to create a better test case … In my real code are more "aliases" involved as in the easy example.

**Comment by albert-github** [comment]
Where is the attachment? please add it as a separate comment.
