### ISSUE TITLE
GitHub markdown alerts do not work

### ISSUE THREAD

**Issue by samwarring** [doxygen/doxygen#11037]
**Describe the bug**
I'm trying to use GitHub alerts in markdown files (described [here](https://www.doxygen.nl/manual/markdown.html) at the end of the page). No matter what I do, I cannot get `[!note]` blocks to render as `\note`.

**Screenshots**
The simple markdown page:
```
# Doxygen Test

Hello!

> [!note]
> This is a note, as a GitHub alert.

\note
This is a doxygen-native note.
```

is rendered as:

![image](https://github.com/user-attachments/assets/24938278-4e06-4273-b496-87e38a1ba095)

**To Reproduce**
The attached zip contains a default-generated Doxyfile and the README.md shown above. The only edit to the Doxyfile after generation was setting `USED_MDFILE_AS_MAINPAGE = README.md`.

**Expected behavior**
I expect both the GitHub alert and doxygen-native note to appear the same.

**Version**
```
$ doxygen --version
1.9.8

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04 LTS
Release:        24.04
Codename:       noble
```

(Ubuntu is running on Windows 11 via WSL)

**Additional context**
I've tried running Doxygen with the `-d Markdown` flag, and I'm finding that the `> ![note]` string is not being replaced with `\note`, but instead with `<blockquote>&zwj;[!note]`

Thank you in advance for your help!

**Comment by albert-github** [comment]
You are using doxygen 1.9.8 and the GitHub style alerts were introduced in version 1.11.0
(see https://www.doxygen.nl/manual/changelog.html second bullet point in features of the 1.11.0 version and https://github.com/doxygen/doxygen/issues/10608)

So looks like you have to update your version.

**Comment by samwarring** [comment]
Oh, I did not realize that. Thank you for pointing it out!
