### ISSUE TITLE
The body of a macro entirely defined on 1 line gets sucked into the synopsis

### ISSUE THREAD

**Issue by duncan-roe** [doxygen/doxygen#11036]
**Describe the bug**
If the body of a macro definition is contained in a single line you don't get the separate **Value:** window. Instead the body of the macro is shown in the window with the macro parameters. _man_ pages have the same fault: the body of the macro is shown as part of the synopsis.

**Screenshots**
In the screenshot below, I've circled in green how I think _foo_ and _bar_ should both display, and I've circled _foo_ in red because it doesn't display that way.
Just noticed descriptions slightly different: fixed in the reproducer.
![html](https://github.com/user-attachments/assets/b278d1a9-e162-4eca-af7d-dfbe15cbbe61)

**To Reproduce**
Untar, **cd reproducer** then **./run.sh** will display the generated man page. <_your browser_> **html/index.html** will show the HTML doc'n.
[reproducer.tar.gz](https://github.com/user-attachments/files/16407714/reproducer.tar.gz)

**Expected behavior**
I would prefer if the body of a macro would always display in a **Value:** window. If the current behaviour is intentional, please can you treat this report as an enhancement request for a Doxyfile directive to make it work the way I prefer.

**Version**
Running under Slackware Linux 15.0. Have seen this behaviour  in Slackware 14.2 doxygen 1.8.9.1 to latest snapshot 1.12.0 (14fc65f92184f8d788d5fb2723fb28e773dc4a5a). Built that muself, 1.8.9.1 is from distributor.

**Comment by albert-github** [comment]
The shown output is intentionally, it is also the case for other instances.
Checkout the results of:
```
/**
 * the first var
 */
int x1[] = {1
  };

/**
 * the second var
 */
int x2[] =
  {1};

/**
 * the third var
 */
int x3[] = {1};

/**
 * the fourth var
 */
int x4[]
 = {1};
```

Example: [example.tar.gz](https://github.com/user-attachments/files/16409988/example.tar.gz)

@doxygen 
We have the setting `MAX_INITIALIZER_LINES` that runs from 0 ... 10000 (for individual entities it can be further steered with `\howinitilalizer` and `\hideinitializer`). Maybe also negative numbers should be allowed for `MAX_INITIALIZER_LINES` having the same meaning as the positive value but in case the initializer line is just 1 line it will still be shown as initialization "block".
What do you think?

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #11039

**Comment by duncan-roe** [comment]
I tried adding **\showinitializer** to foo, but this does not put the 1-line body into its own box as I hoped it would.
[reproducer2.tar.gz](https://github.com/user-attachments/files/16434190/reproducer2.tar.gz)
My preference would be if _showinitializer_ is updated to put the 1-line body into its own box.
Adding **MAX_INITIALIZER_LINES = -30** to Doxyfile produces a warning
[reproducer3.tar.gz](https://github.com/user-attachments/files/16434200/reproducer3.tar.gz)
which only goes away at the next doxygen release; while adding **\showinitializer** has no effect until the next release, when it starts to do what I'm asking for.

**Comment by albert-github** [comment]
The `\showinitializer` command has as  disadvantage:
- it is now an "on / off" switch so it would mean that the command would need an extra option to stay compatible with the current version
- the `\showinitializer` is not global but just for the one entry.

Regarding the negative sign,
- true that you cannot use the negative value in older versions, but it new, optional, features never can be used in older versions (there is the exception with some commands where one can use the command in older versions when one defines (i.e. removes) the command by means of an `ALIASES`)

Besides the negative number for the `MAX_INITIALIZER_LINES` I also thought about an extra setting, but there are already that many settings so I choose this implementation (though it would be easy the revert this implementation in favor of another settings. Another setting though has also the "disadvantage" that it can only be used in newer versions without a warning).

**Comment by duncan-roe** [comment]
AFAICS `\showinitializer` simply sets _initLines_ to 100000 (at src/commentscan.l:3673). If it could set a marker that it had been used, then memberdef.cpp could take action on that marker. Sure that would change appearance if someone had coded `\showinitializer` for a 1-liner but is that a show-stopper?
It's fine with me that `\showinitializer` is local to the entry. I would expect to review generated documentation and insert `\showinitializer`  as required.

**Comment by albert-github** [comment]
For me both points are show stoppers.

**Comment by duncan-roe** [comment]
point 1: Sure I'm proposing to change the behaviour of `\showinitializer`, but stuff changes all the time. F.I. we just went from Modules to Topics in 1.11. And dates disappeared from the bottom of **man** pages (at 1.9.x IIRC, thanks for that change btw). The currently advertised use for `\showinitializer` is to show multiple-line entries. How likely is it that anyone is using it on a single-liner?

point 2: Huh? You mean sentence starting _It's fine with me_? That's just my preference. Or were you referring to something else?

It's perhaps unfortunate that doxygen treats variable _initializers_ and macro _definitions_ the same way. 1-line macro definitions are typically longer than variable initializers and so more likely to benefit from being shown in an initialization "block".

**Comment by doxygen** [comment]
Maybe a simpler solution is to distinguish between function like macros and plain macros and treat function like macros always as multiline, e.g. given

```C++
#define PI          3.14152965
#define MAX(x,y)    ((x)>(y)?(x):(y))
#define MAX_ML(x,y) ((x)>(y)? \
                     (x):(y))
```
The macro `PI` would have 3.14152965 shown inline, whereas `MAX`'s definition is shown in a separate "value" section, just like `MAX_ML` already would now. For variables, nothing will change.

**Comment by duncan-roe** [comment]
On Sun, Aug 04, 2024 at 04:27:38AM -0700, Dimitri van Heesch wrote:
> Maybe a simpler solution is to distinguish between function like macros and plain macros and treat function like macros always as multiline, e.g. given
>
> ```C++
> #define PI          3.14152965
> #define MAX(x,y)    ((x)>(y)?(x):(y))
> #define MAX_ML(x,y) ((x)>(y)? \
>                      (x):(y))
> ```
> The macro `PI` would have 3.14152965 shown inline, whereas `MAX`'s definition is shown in a separate "value" section, just like `MAX_ML` already would now. For variables, nothing will change.
>
Hey I like that a LOT. Can you guys do it?

**Comment by doxygen** [comment]
@duncan-roe @albert-github I've implemented the alternative solution.

**Comment by albert-github** [comment]
I create a small example like:
```
/// \file

/** just pi */
#define pi 3.14159265359

/** two pi */
#define two_pi pi * 2

/** n pi */
#define n_pi(x) pi * x
```

and I'm not really liking the distinction between the normal macro and  the (small) function macro:
![image](https://github.com/user-attachments/assets/0588ce26-0ee3-4487-9e6c-39b2f2c8efc5)


Example; [example.tar.gz](https://github.com/user-attachments/files/16511394/example.tar.gz)

**Comment by duncan-roe** [comment]
Looks good to me, bearing in mind **n_pi** is an atypically short macro. Here are a couple of macros from Linux kernel before 79bbf23a8
![page](https://github.com/user-attachments/assets/dcb764fa-0ca1-413e-8f3c-e9e6370539ad)
And here they are afterwards
![page](https://github.com/user-attachments/assets/0fa87d8e-7f16-42cb-9823-69a4a067e9c3)
The improvement is more obvious in the man pages. This is _before_:

```
Macros(3)                  Library Functions Manual                  Macros(3)

NAME
       Macros - Sample macros from linux/include/linux/list.h

SYNOPSIS
   Macros
       #define list_for_each_continue(pos,  head)           for (pos =
           pos->next; !list_is_head(pos, (head)); pos = pos->next)
       #define list_entry(ptr,  type,  member)           container_of(ptr,
           type, member)

Detailed Description
       Kerneldoc minimally translated to doxygen

Macro Definition Documentation
   #define list_entry( ptr,  type,  member)           container_of(ptr, type,
       member)
       list_entry - get the struct for this entry

       Parameters
           ptr the &struct list_head pointer.
           type the type of the struct this is embedded in.
           member the name of the list_head within the struct.

       Definition at line 25 of file list.h.

   #define list_for_each_continue( pos,  head)           for (pos = pos->next;
       !list_is_head(pos, (head)); pos = pos->next)
       list_for_each_continue - continue iteration over a list

       Parameters
           pos the &struct list_head to use as a loop cursor.
           head the head for your list.

       Continue to iterate over a list, continuing after the current position.

       Definition at line 16 of file list.h.

Author
       Generated automatically by Doxygen for sample macros from the source
```

And this is _after_:
```
Macros(3)                  Library Functions Manual                  Macros(3)

NAME
       Macros - Sample macros from linux/include/linux/list.h

SYNOPSIS
   Macros
       #define list_for_each_continue(pos,  head)
       #define list_entry(ptr,  type,  member)

Detailed Description
       Kerneldoc minimally translated to doxygen

Macro Definition Documentation
   #define list_entry( ptr,  type,  member)
       Value:
               container_of(ptr, type, member)

       list_entry - get the struct for this entry

       Parameters
           ptr the &struct list_head pointer.
           type the type of the struct this is embedded in.
           member the name of the list_head within the struct.

       Definition at line 25 of file list.h.

   #define list_for_each_continue( pos,  head)
       Value:
               for (pos = pos->next; !list_is_head(pos, (head)); pos = pos->next)

       list_for_each_continue - continue iteration over a list

       Parameters
           pos the &struct list_head to use as a loop cursor.
           head the head for your list.

       Continue to iterate over a list, continuing after the current position.

       Definition at line 16 of file list.h.

Author
       Generated automatically by Doxygen for sample macros from the source
       code.

sample macros                     Version 0.1                        Macros(3)
```
Here's the source:
[example.tar.gz](https://github.com/user-attachments/files/16517870/example.tar.gz)

**Comment by doxygen** [comment]
@albert-github 
> I'm not really liking the distinction between the normal macro and the (small) function macro:

This is of course a matter of taste. You could have the same argument for short one line functions and function macro, i.e. the following are now treated similarly (with `INLINE_SOURCES=YES`):

```c++
/** short function macro */
#define F(x) (x)*10
/** short function */
inline int f(int x) { return x*10; }
```

**Comment by albert-github** [comment]
@doxygen certainly a matter of taste.

The inline function is a nice point as a function macro is more or less an inline function, so it looks like the fact that a function macro is not shown inline is actually more consistent.

It also shows that due to the enhancements in the underlying standards (in K&R there were no inline functions as far as I know) brings new concepts, possibilities and ideas and to keep the documentation consistent is quite hard.

Giving the possibilities of extra special commands, like the e.g. `\callgraph` / `hidecallgraph` give a nice possibility of granularity, maybe some thoughts should be spent on this (although giving more flexibility it gives also more complexity, not only for the users but also, mainly complexity, in the implementation).
