### ISSUE TITLE
define the TOC - Table of Contents of a CHM Project, handled by Doxygen ?

### ISSUE THREAD

**Issue by paule32** [doxygen/doxygen#11047]
Hello,
is it possible, to change the TOC (also the generated TreeList of CHM Topics) per Tag ?
So, I can give the Topic, and Subtopic's a reference to a Page and/or Link/Anchor.
Because, Doxygen generates in some aspects double Items, that refer to different Anchor, but on same Page.
E.g.:
- Item 1   links to Page A *1
- Item 1   links to Page A *2
- Item 1   links to Page A *3

So, I would prefer, to specify:
- Item 1 A
- Item 1 B
- Item 1 C

in the generated TOC Tree

**Comment by albert-github** [comment]
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).
- Please also specify the **full** doxygen version used (`doxygen -v`).

**Comment by paule32** [comment]
Hello,
I using Doxygen 1.12.0 (222753f956f54f5e8ae6b6db79eee38a0759a4d4*)
I can proof the .hhc, which is generated by Doxygen CHM Project.
But I was thinking, it give extra Commands by Doxygen, that help, to create a Index TOC (Table Of Contents)

**Comment by paule32** [comment]
with \defgroup and \ingroup, I can build nested/sub Topics, which will see under "Topics" (at first Level/Top of the TOC-Tree).
is it possible, to add Topics, that are not appear in/under the main Bookmark Link "Topics" ?
Currently I have this TOC structure:

+ Topics
   +-- SubTopic A
        +-- SubTopic A2
  +-- SubTopic B
        +-- SubTopic B2
+ Namespaces
+ Data structures

But I would like add other Root-Topics, and I would lable it other than "Topics" like:
+ Topics C++
   + SubTopic
+ Topics Pascal
+ Topics LISP

How can this be done in CHM HTML Project's ?

**Comment by albert-github** [comment]
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).
