### ISSUE TITLE
documenting C typedef types

### ISSUE THREAD

**Issue by paule32** [doxygen/doxygen#11048]
Hello,
I wanted to documenting the typedef size_t.
But I am lost the challenge.
So, how can I add stuff to my CHM Project with typedef Documentation for size_t ?
The same is, when I would like documenting wchar_t - the Documentation will not be created:

[packed.zip](https://github.com/user-attachments/files/16478834/packed.zip)
![grafik](https://github.com/user-attachments/assets/78c27e6a-ebb1-452c-bddd-71ff260d469e)

**Comment by doxygen** [comment]
The typedef is a member of file `stddef.h` so you need to do one of these

1. enable files `SHOW_FILES = YES` or 
2. add the typedef to a group (using `\ingroup`) or 
3. make it related to a class (using `\relates`) 

in order to see it.

**Comment by paule32** [comment]
Thanks, this helps a lot.
You made my day :-)
