### ISSUE TITLE
How to adjust Doxygen config to incorporate contents of contradictory source code `if` statements?

### ISSUE THREAD

**Issue by cpompeo** [doxygen/doxygen#11059]
**Describe the bug**
I have some C header files that contain `if` statements whose contents I want to include in my generated API reference docs.

`#IF !TARGET_SURFACE`
`function a`
`function b`

`#IF TARGET_SURFACE`
`function c`
`function d`

Right now, putting `PREDEFINED += TARGET_SURFACE` in my list of predefined macro names means that `function c` and `function d` appear in the generated API reference files (because `TARGET_SURFACE` evaluates to true) but that `function a` and `function b` don't appear in the generated API reference files (because `!TARGET_SURFACE` does not evaluate to true).

How can I ensure that the resulting static website/doc includes all four functions?

**Version**
Doxygen version 1.11.0
on most recent Macbook Air

**Comment by albert-github** [comment]
The `#if` statements are evaluated always so you have to resort to extending the `#if` condition like 
```
#if !TARGET_SURFACE || defined(DOXYGEN)
```
and add to the doxygen settings:
```
PREDEFINED  = DOXYGEN
MACRO_EXPANSION = YES
```

The full example: [example.tar.gz](https://github.com/user-attachments/files/16520015/example.tar.gz)

Normally always attach to your issue:
- a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).
