### ISSUE TITLE
Partial specialization of C++ variable template is missing from Doxygen output

### ISSUE THREAD

**Issue by LouisStrous** [doxygen/doxygen#11085]
When I declare a C++ variable template and a partial specialization of that template and annotate both with Doxygen style comments then only the primary template gets mentioned in the resulting HTML files.  I expected the specialization to be mentioned, too.

**Reproduction**

Generate a Doxygen configuration file using `Doxygen -g`. In the Doxyfile, set `INPUT = foo.cc`.  The contents of foo.cc (in the same directory as Doxyfile) are:

    /// \file

    /// The primary template.
    template<typename T, typename U, typename Dummy = void>
    constexpr bool has_foo_v = false;

    /// The template specialization.
    template<typename T, typename U>
    constexpr bool has_foo_v<T,
                             U,
                             std::void_t<decltype(T::foo(std::declval<U>()))>>
    = true;

Run Doxygen.  It produces no warnings.  Look at the foo.cc page in the HTML results.  It describes the primary template but there is no sign of the template specialization.  See the screenshot.

![image](https://github.com/user-attachments/assets/f782f2ac-1fcd-4777-865b-88f0b4721ec4)

**Expected behavior**

I expected the template specialization to be described on the produced web page for the source file.

**Version**

Doxygen 1.12.0 (c73f5d30f9e8b1df5ba15a1d064ff2067cbb8267) on Windows 11 Business version 23H2.  Downloaded from the Doxygen website.

**Comment by doxygen** [comment]
@LouisStrous Please verify if the referenced commit fixes the problem for you. Do not close the issue, this will be done automatically when the next official release becomes available.

**Comment by LouisStrous** [comment]
The referenced commit fixes the problem for me.  Thank you.

**Comment by LouisStrous** [comment]
Sorry, I misunderstood the "Close with comment" option so unintentionally closed the issue, even though you asked me not to.  I hope that reopening the issue allows your preferred workflow to proceed.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.13.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Comment by LouisStrous** [comment]
Doxygen 1.13.0 (3fc9e7f98b8d1156ec627cd3ee6f23984bf4e1b1) fixes the problem.
