### ISSUE TITLE
Graphical glitch with lists and text spilling over on a new line.

### ISSUE THREAD

**Issue by OADINC** [doxygen/doxygen#11116]
**Describe the bug**
When a line is to long it gets chopped broken up and the rest is displayed on the new line, as it should. But when this happens in a list, the numerator gets placed in front of the wrong line.

Obligatory English is not my first language. I'm not quite sure what all the correct terms are in English, but the provided picture should show the issue clearly.

**Screenshots**
At 90% zoom.
![Doxygen_Good](https://github.com/user-attachments/assets/39ab0490-8b84-43dd-bd65-af797e2f3932)
At 100% zoom.
![Doxygen_Bad](https://github.com/user-attachments/assets/e4512666-7bd7-473d-aa04-9ae65ef619dc)

**To Reproduce**
[Doxygen.zip](https://github.com/user-attachments/files/16871641/Doxygen.zip)
In this example you have to zoom in a bit further

**Expected behaviour**
I would expect the numerator be on the correct line. (The previous line)

**Version**
Doxygen 1.12.0, 64 windows 11.
Glitch tested in and happens in both MS Edge and Firefox. 
HTML output

**Additional context**
The original Doxygen comment can be found in the zip.

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.13.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
