### ISSUE TITLE
Doxygen 1.12.0 mishandles Markdown section header following "<pre>" HTML markup.

### ISSUE THREAD

**Issue by ncbrowns** [doxygen/doxygen#11114]
**Describe the bug**
While porting some documentation to use Doxygen 1.12.0 (was using 1.9.7), I discovered a problem in the handling of Markdown content like the following where a top-level parent section ending with `<pre>` markup is followed by a second-level section header.  When the content is rendered in HTML, the "##" prefix for the "Second Level" section header appears to be interpreted as if the first "#" character is literal text at the end of the prior section and the second "#" specifies a top-level section header (like "Top Level").
```
[TOC]
 
# Top Level
 
1. This is a list item.

2. So is this.

3. So it this, but I also have some
<pre>
preformatted content
</pre>

## Second Level

This is a second level section.
```

**Screenshots**
Here's the HTML rendering of the example above:

![image](https://github.com/user-attachments/assets/30f6d52f-2892-4a8a-8d5a-1cef3b48ae53)

**To Reproduce**
Attach a self contained example that allows us to reproduce the problem.

[example.zip](https://github.com/user-attachments/files/16860188/example.zip)

This was built from a brand-new Doxyfile pointing at the file "test.md", with no other content.

**Expected behavior**
The header "Second Level" should be rendered as a child of "Top Level", not as a peer.

**Version**
Doxygen 1.12.0 (pre-built binaries from zip package on the main site) on Windows 11.

**Stack trace**
If you encounter a crash and can build doxygen from sources yourself with debug info (`-DCMAKE_BUILD_TYPE=Debug`), a stack trace can be very helpful (especially if it is not possible to capture the problem in a small example that can be shared).

**Additional context**

**Comment by albert-github** [comment]
There is also the extra `#` in the output.
As far as I can tell an extra newline, before the `##`, will work around the problem.

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by ncbrowns** [comment]
Thanks for addressing this issue so quickly.  I have verified that your proposed workaround of adding a blank line works with our real documentation in addition to the example.

**Comment by albert-github** [comment]
@ncbrowns Did you also try the real fix (you build the doxygen version based on the current master or get a build from the github actions artifacts, e.g. https://github.com/doxygen/doxygen/actions/runs/10741154727from the bottom of the page).

**Comment by ncbrowns** [comment]
@albert-github At the time of my previous update, I had tested only the workaround.  However, I just tested the Windows MSVC Release build from your GitHub Actions link against documentation with the workaround removed and found that it worked fine.
