### ISSUE TITLE
Unable to copydoc on global function documentation when it is a friend of a struct or class

### ISSUE THREAD

**Issue by scott-zhong** [doxygen/doxygen#11133]
**Describe the bug**
Unable to `copydoc` on global function documentation when it is a friend of a struct or class

```
/**
 * Y docs
 */
struct Y
{
};

/**
 * X docs
 */
struct X
{
  /**
   * operator==(const struct X&, const struct X&)
   */
  friend bool operator==(const struct X&, const struct X&);
};

/**
 * \relates Y
 * \copydoc operator==(const struct X&, const struct X&)
 */
bool operator==(const struct Y&, const struct Y&);
```

produces the following warning

```
test.h:21: warning: @copybrief or @copydoc target 'operator==(const struct X&, const struct X&)' not found
```

The current work around is to prefix the global function with the struct or class where it is documented.

```
/**
 * \relates Y
 * \copydoc X::operator==(const struct X&, const struct X&)
 */
bool operator==(const struct Y&, const struct Y&);
```

That doesn't seem right because the function is a global function, it isn't a function of `struct X`.

**To Reproduce**
[testcase.zip](https://github.com/user-attachments/files/16966872/testcase.zip)

**Comment by albert-github** [comment]
Normally you mention the doxygen version you use, but I don't see it here...

**Comment by scott-zhong** [comment]
@albert-github Sorry about that.  The version is

Doxygen 1.11.0 - trunk (7e1860534d163a9d8882ce3ebb620719f74e75eb)

**Comment by albert-github** [comment]
I'm not sure if this is a bug or just a wrong warning. Looking at:
```
/**
 * \relates Y
 * \copydoc operator==(const struct X&, const struct X&)
 */
bool operator==(const struct Y&, const struct Y&);
```
the question is which documentation should be copied, I would think it looks like its own documentation. In the later case I would have expected something like:
```
warning: Found recursive @copybrief or @copydoc relation for argument ...
````
like given for functions.

**Comment by scott-zhong** [comment]
I would expect it to copy the global function documentation as it were similar to

```
/**
 * Y docs
 */
struct Y
{
};

/**
 * X docs
 */
struct X
{
};

/**
 * operator==(const struct X&, const struct X&)
 */
bool operator==(const struct X&, const struct X&);

/**
 * \relates Y
 * \copydoc operator==(const struct X&, const struct X&)
 */
bool operator==(const struct Y&, const struct Y&);
```

**Comment by scott-zhong** [comment]
The `friend` keyword gives the global function access to the members of the struct or class but it doesn't make the global function a part of the struct or class, i.e., it doesn't make it `X::operator==(const X&, const X&)`.

**Comment by doxygen** [comment]
For Doxygen, a friend declaration inside a class is inserted as a member of the class (even though the scope is global) since it is also shown in the class documentation. 

If there is also a definition of the function outside the class, then both are joined together and a reference without `X::` also works.

Take for instance this modified example:
```c++
/**
 * Y docs
 */
struct Y
{
};

/**
 * X docs
 */
struct X
{
  /**
   * @brief Brief description
   */
  friend bool operator==(const struct X&, const struct X&);
};

/**
 * \relates Y
 * \copydoc operator==(const struct X&, const struct X&)
 */
bool operator==(const struct Y&, const struct Y&);

/**
 * Equality operator for X
 */
bool operator==(const struct X&, const struct X&);
```

It is a bit difficult to fix this as the insert/lookup mechanism is based on the container a member is inserted in. Assuming it is not too inconvenient to add the `X::` if the friend is documented in the class, I prefer to keep it like this.

**Comment by scott-zhong** [comment]
@doxygen we're fine on using the work around if it is too difficult to fix.
