### ISSUE TITLE
\xrefitem broken with Markdown blockquotes

### ISSUE THREAD

**Issue by joergpichler** [doxygen/doxygen#11155]
**Describe the bug**
In Doxygen 1.8.11 we used \xrefitem with a following blockquote and it worked as we expected. Somewhere in the 1.9.x branch the behavior we relied upon broke which we recently just found with the 1.12 release because of a newly emitted warning

**Screenshots**
1.8.11
![image](https://github.com/user-attachments/assets/fa1738f0-f7f9-4906-83e8-4b607cf5756d)
![1 8_2](https://github.com/user-attachments/assets/439e5751-9ad3-4139-bde6-77250dd27df3)

1.9.6 till 1.12.0
![image](https://github.com/user-attachments/assets/1ab2b698-6bb8-4fa0-b7cd-03942427045e)
![1 9_2](https://github.com/user-attachments/assets/01addc1c-a1b5-4290-a5fe-97ef5efe9a53)

**To Reproduce**
Use this in a .md file
```
# Title

\xrefitem architectural_decisions "" "Design Decisions" > **Decision**
>
> * We want to do it that way
> 
> **Reasons**
> 
> * A
> * B
> * C
```

**Expected behavior**
Same as with version 1.8.x

**Version**
1.9.6 and later (might be that earlier 1.9.x version also cause this

**Comment by albert-github** [comment]
Looks lie a bit of a strange construct starting a blockquote in a `\xrefitem`. The following:
```
# Title

\xrefitem architectural_decisions "" "Design Decisions"
\parblock
> **Decision**
>
> * We want to do it that way
>
> **Reasons**
>
> * A
> * B
> * C

\endparblock
```
does work in the current 1.12.0 doxygen version on the related page, though on the file page (Title") it looks like it didn't work properly.

Looks like the main difference has been introduced in 1.8.15, but also in some subsequent versions I see further differences in the output / warnings.
The issue has to be investigated a bit further though.

**Comment by joergpichler** [comment]
The fix you suggested does not unfortunately not output anything on the file page at all :( So its not a feasible workaround

**Comment by doxygen** [comment]
@joergpichler If you fill in the second parameter of `\xrefitem` Albert's suggestion should work, i.e.

```.markdown
# Title

Some text on this page.

\xrefitem architectural_decisions "Design Decision" "Design Decisions" \parblock
> **Decision**
>
> * We want to do it that way
>
> **Reasons**
> * A
> * B
> * C

\endparblock
```
The command `\xrefitem` should typically be used as part of an alias, so if you define

```
ALIASES  += "decision=\xrefitem architectural_decisions \"Design Decision\" \"Design Decisions\" \parblock <blockquote> **Decision**^^" \
            "reason=<p> **Reasons**" \
            "enddecision=</blockquote> \endparblock"
```

Then you can write

```.markdown
# Title

Some text on this page.

\decision
* We want to do it simple
\reason
* D
* E
* F
\enddecision
```
