### ISSUE TITLE
"Functional Parts" disappeared.

### ISSUE THREAD

**Issue by couet** [doxygen/doxygen#11164]
**Describe the bug**
Since doxgen 1.10 the menu entry "Functional Parts" disappeared from our documentation.

**Screenshots**
On the left what we got with 1.9 on the right what we get since 1.10
<img width="531" alt="Screenshot 2024-10-01 at 12 14 54" src="https://github.com/user-attachments/assets/10817972-956b-4431-9acb-868e99faa971">

**To Reproduce
We ran our build without change. Just changing the doxygen version shows this behavior.

**Expected behavior**
We would like to see this menu entry back.

**Version**
see above.

**Comment by albert-github** [comment]
Without an example it is impossible to tell what the problem might be.

- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).

**Comment by couet** [comment]
It is a bit difficult to produce a simple one as our doc is huge. I thought something may have changed which could explain why this menu is present with 1.9 and not anymore with 1.10... I will try to see if there is something in the documentation about that.

**Comment by albert-github** [comment]
I assume you are talking about the root project.
How can one from the command line build the documentation? (something like `make  docs`)

This, in this case necessary, information would at least give some possibilities to look in a direction the problem finding.

**Comment by couet** [comment]
Yes, the ROOT project. I see I should investigate the `DoxygenLayout.xml` file.  I will try to understand what changed there. Thanks for your help.

**Comment by albert-github** [comment]
I found a directory documentation\doxygenand did a search for "Functional Parts"  here and found:
```
DoxygenLayout.xml:    <tab type="modules" visible="yes" title="Functional Parts" intro=""/>
```
In version 1.9.8 support for C++ Modules was added and the term "modules" collided with the term used in doxygen for "groups". In doxygen we renamed the (old) "modules" to "topics".

You didn't specify the doxygen version where the "Functional Parts" was present, 1.9 is far to general, but I expect it will be 1.9.7 or before.

So when changing this is in the mentioned file I think you will have your item back.

**Comment by couet** [comment]
In 1.9.8 it was ok: https://root.cern/doc/master/index.html (version is printed in the footer)

**Comment by albert-github** [comment]
Strange that 1.9.8 was OK, didn't expect it.
Still I think you should update your layout file so it is conform the used version.

**Comment by couet** [comment]
Indeed it is enough to rename "modules" to "topics". Thanks
