### ISSUE TITLE
- The hash should be persistent over different runs (and different doxygen versions).

### ISSUE THREAD

**Issue by Qaisfaris** [doxygen/doxygen#11193]
- The hash should be persistent over different runs (and different doxygen versions). 
- moving items in a header file doesn't change the hash, the hash is based on the, input, filename not the content

_Originally posted by @albert-github in https://github.com/doxygen/doxygen/discussions/11191#discussioncomment-11013529_

**Comment by albert-github** [comment]
@Qaisfaris What is your intention here?

**Comment by albert-github** [comment]
Closed as spam.
