### ISSUE TITLE
replace "_self" with customizable Frame target for topics.html ... ?

### ISSUE THREAD

**Issue by paule32** [doxygen/doxygen#11198]
Hello,
Currently, I faced with a little Problem to navigate through my own TOC (Table of Contents) structure.
Doxygen create the following output:

```html
    <table class="directory">
        <tr id="row_0_"         class="even">
            <td class="entry">
                <span style="width:0px;display:inline-block;">&#160;</span>
                <span id="arr_0_" class="arrow" onclick="dynsection.toggleFolder('0_')">&#9660;</span>
                <a class="el" href="/miniFPC/group__fpc__compiler.html"
                target="content-frame">
                Der Free Pascal Compiler - FPC</a>
            </td><td class="desc"></td></tr>
...

```
I have shortened and break up the line(s).
And the Problem of my Concerns are the **target** directive.
On normal translation Run, **_self** will be inject.
But I need a customizable target for **content-frame**.

What can I do with Doxygen - is there a Doxyfile Setting ?

**Comment by albert-github** [comment]
From the information it is not clear what you want / why you need need a customizable target.
Also a full example and used doxygen version would be in place.
Furthermore it looks like this is not an issue, but something for discussions...

**Comment by paule32** [comment]
to be continued in discussions...
