### ISSUE TITLE
Doxygen takes over 1 Minute(s) to finish up Translation of an HTML and CHM Project

### ISSUE THREAD

**Issue by paule32** [doxygen/doxygen#11192]
Hello,
the latest Version of Doxygen (1.12) takes over one minute to finish up the Translation of an HTML and CHM Project.
After download and installing, the old File size was about 10 Megabytes, and now, they are about 25 Megabytes.

So, the Question is, what does Doxygen do that such time-consuming take in effect ?
For me, it is very important for speed-up because I translate 8 Projects at same time.

I have attached some Files that may help to reproduce the issue.
Note: I work under Windows 11 64-Bit Pro.

Thanks for feedback

**Comment by paule32** [comment]
BTW: How can I upload Files after writing a Posting there ?

[packed.zip](https://github.com/user-attachments/files/17471170/packed.zip)

**Comment by albert-github** [comment]
- looks like you found a way to upload an example in a new comment. When it is needed in the an old comment or in the original issue you edit the item and by means of drag / drop you can add and example. Note that of changes to the original issue or to an existing comment no notification is send to other participants.

Back to the issue in question
- what is the old version?
- the reason might lie in the fact that you use `CREATE_SUBDIRS         = YES` and at the end doxygen tries to remove empty directories.
- size difference, no explanation as I have no insight what is the old and what is in the different versions.

**Comment by paule32** [comment]
before Version 1.12.0 I used Version 1.10.0 and 1.11.
With older Version's all is fine.
I delete the old crap with a Windows Console Batch File, so Doxygen don't need to delete the old Folders.
It can be that the Avast Anti-Virus Secure the FileSystem - but I had share/open an Exception for the doc folder.

**Comment by albert-github** [comment]
> I delete the old crap with a Windows Console Batch File, so Doxygen don't need to delete the old Folders.

Here we have a small misunderstanding . What I menat with:
> the reason might lie in the fact that you use CREATE_SUBDIRS         = YES and at the end doxygen tries to remove empty directories.

is that doxygen, initially creates a tree with `html/d0/d00` till `html/df/dff` (so 16+4096 directories, also steerable by means of `CREATE_SUBDIRS_LEVEL`) and not all these directories are being populated by doxygen and the empty directories are removed.


- What did you use for time measuring? (`doxygen -d time` ?)

**Comment by paule32** [comment]
hurry up :-)
Thank you for the Hint for **CREATE_SUBDIRS_LEVEL** and **CREATE_SUBDIRS** - it worked extremely faster as before.
Currently I use the following settings:

CREATE_SUBDIRS = **NO**
CREATE_SUBDIRS_LEVEL = **8**

It takes about 5 Seconds in approxymal for each Setting File.

Thank you, you made my day.

**Comment by paule32** [comment]
found Solution, Thank you for the helping Hand
