### ISSUE TITLE
Markdown links to internal anchors broken

### ISSUE THREAD

**Issue by attipaci** [doxygen/doxygen#11207]
**Describe the bug**
Markdown documents often contain anchors internally, which can be linked by `#` followed by the anchor name, as per the HTML standard. As of 1.12.0, these links to internal anchors are broken, since links starting with `#` are now interpreted as `\ref` links to Doxygen tags.

**To Reproduce**

Consider the following markdown document to be included with Doxygen documentation:

```markdown
# Markdown example

## Table of Contents
- Link to [Section](#section-link)

<a name="section-link"></a>
##  Section
```

When Compiling this markdown document with Doxygen, an error is produced, such as:

```
error: unable to resolve reference to 'section-link' for \ref command
```

**Expected behavior**
Doxygen should compile the included markdown document without and error, and the compiled document should have an internal link the section header. It worked with Doxygen 1.10.0 and prior versions.

**Version**
1.12.0, Fedora Linux (`doxygen-2:1.12.0-1.fc41.x86_64.rpm`)

**Comment by albert-github** [comment]
A quick test with the current master version showed that the problem is gone again.
- can you test the current master version (either by compiling the version yourself or by using an artifact from github Actions se https://github.com/doxygen/doxygen/actions e.g.  bottom m of page https://github.com/doxygen/doxygen/actions/runs/11541328284)

Looks like a duplicate of #11135 (fixed by #11140)

**Comment by attipaci** [comment]
> Looks like a duplicate of #11135 (fixed by #11140)

Indeed. I did not realize it before since #11135 is rather thin on the description. :-)

Do you know when the next release might happen? I am maintaining a Fedora package that uses Doxygen for the documentation, but am unable to update / build that package until the Fedora `doxygen` package (currently 1.12.0) is bumped to include the fix. I assume I'm not the only one who is affected and is stuck with releasing packages until the Doxygen update is released, and adopted by Fedora (or other distros)... So, I hope an updated release is on its way sooner than later...

**Comment by albert-github** [comment]
The last release was in August, so I don't expect soon probably in a couple of months.

If you don't want / cannot use the current master as solution might be to adjust and rebuild the 1.12.0 version with just this fix.

Note the used construct is of course a mix of HTML and markdown. in the past doxygen did not support links to markdown sections (like `## Section`)  but by setting `MARKDOWN_ID_STYLE=GITHUB` this translates `## Section` to 
```
@section section Section
```

**Comment by attipaci** [comment]
Thanks for the info!

I filed a bug report against the downstream Fedora package. As such I hope they can rebuild their 1.12.0 with the patch to cure the regression.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.13.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Comment by thomthom** [comment]
I'm seeing this in 1.14 with a .md file I have included in my documentation. Even though I have a `<a name="foo">Foo</a>` anchor I get warnings for `[Foo](#foo)` markdown links saying it cannot resolve `foo for \ref command`.

1.14.0 (cbe58f6237b2238c9af7f51c6b7afb8bbf52c866)

Has this regressed?

**Comment by albert-github** [comment]
@thomthom 

Sorry for the late response.

I tried with the example given in the issue the doxygen versions:
- 1.12.0 problem present
- 1.13.0 problem gone
- 1.14.0, and 1.15.0 (the current version) problem gone

So I cannot reproduce your observations so when persistent:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem?
   Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).

**Comment by thomthom** [comment]
I'm still seeing this with 1.14.

Example.md:

```md
# Example

## <a name="index">Index</a>

- [Basics](#basics)
	- [Events](#events)
	- [Functions](#functions)

## <a name="basics">Basics</a>

Lorem ipsum dolor sit amet.

### <a name="events">Events</a>

Lorem ipsum dolor sit amet.

### <a name="functions">Functions</a>
```

Console output:
```sh
$ doxygen -q
C:/Users/Thomas/SourceTree/doxytest/example.md:5: warning: unable to resolve reference to 'basics' for \ref command
C:/Users/Thomas/SourceTree/doxytest/example.md:6: warning: unable to resolve reference to 'events' for \ref command
C:/Users/Thomas/SourceTree/doxytest/example.md:7: warning: unable to resolve reference to 'functions' for \ref command
```

Generated HTML:

<img width="1364" height="940" alt="Image" src="https://github.com/user-attachments/assets/41f7d1dc-06e1-4bbc-aaf9-cca1b3b42cd8" />

Zip archive with `Doxyfile` and `Example.md` to reproduce:

[Example.zip](https://github.com/user-attachments/files/23798127/Example.zip)

**Comment by thomthom** [comment]
I also updated to 1.15 and see the same thing.

```sh
doxygen --version
1.15.0 (7cca38ba5185457e6d9495bf963d4cdeacebc25a)
```

**Comment by albert-github** [comment]
I see where the problem lies there is a small difference between your type of usage:
```
## <a name="basics">Basics</a>
```
and the usage in the original example:
```
<a name="basics"></a>
## Basics
```
So it looks like the like the construct is not allowed in a section header.

Setting issue to enhancement

**Comment by thomthom** [comment]
Ah! I didn't notice that.

Yea, when I change the anchors to empty links it works.

> Setting issue to enhancement

👍 Sounds good. Having the text the anchor refer to is better HTML semantic and better for accessibility.
