### ISSUE TITLE
`@copydoc` from external documentation (tagfile)

### ISSUE THREAD

**Issue by matekelemen** [doxygen/doxygen#11212]
Suppose I'm using an external project that generates documentation with doxygen and produces a tagfile. In my project, I link to that tagfile and attempt to reference annotations in the external project with `@copydoc`, but doxygen reports
```
warning: @copybrief or @copydoc target '<referenced class/function>' found but is from a tag file, skipped
``` 

and the referenced docs don't appear in my project's documentation.

Is there a setting to make `@copydoc` work with external projects?

**Comment by albert-github** [comment]
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).
- Please also specify the **full** doxygen version used (`doxygen -v`).

**Comment by matekelemen** [comment]
That's unfortunate, but thanks for looking into it.
