### ISSUE TITLE
Generated documentation for the IDL interface has wrong quotes

### ISSUE THREAD

**Issue by kazssym** [doxygen/doxygen#11227]
**Describe the bug**
Generated documentation for the IDL interface has wrong quotes for `import` as:
```idl
import <File.idl;
```

**Screenshots**

**To Reproduce**
Generate documentation for IDL interfaces.

**Expected behavior**
Correct quotes are used as:
```idl
import "File.idl";
```

**Version**
1.12.0 (c73f5d30f9e8b1df5ba15a1d064ff2067cbb8267)

**Stack trace**
If you encounter a crash and can build doxygen from sources yourself with debug info (`-DCMAKE_BUILD_TYPE=Debug`), a stack trace can be very helpful (especially if it is not possible to capture the problem in a small example that can be shared).

**Additional context**

It looks like these functions are inconsistent.

https://github.com/doxygen/doxygen/blob/6a822eea5bf5a8deada330bdef3adf5de8a97675/src/filedef.cpp#L75
https://github.com/doxygen/doxygen/blob/6a822eea5bf5a8deada330bdef3adf5de8a97675/src/filedef.cpp#L88

**Comment by albert-github** [comment]
To be able to reproduce the problem:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).

**Comment by albert-github** [comment]
I found an example see pull request #11228.

I've just pushed a proposed patch, pull request #11228

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.13.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
