### ISSUE TITLE
Undefined control sequence. <argument> \g__tbl_row_int

### ISSUE THREAD

**Issue by abn6** [doxygen/doxygen#11254]
# Description
See [doc_lib.log](https://github.com/user-attachments/files/17933767/doc_lib.log), error starts at line 1247. After that error, DoxyParams then presents many "Missing $ inserted.". Might be related?

Could be something related to tabu since it is not maintained.

I have a header file that's used in the config file as `LATEX_HEADER = my_header.tex`, maybe that's relevant.

I am not very experienced with this, you probably need more info than what I am providing. Just ask.

## Version
I've tried Doxygen 1.11 and 1.12.

**Comment by albert-github** [comment]
Indeed some more information is needed (including the adjusted latex header).
- what happens when you run without the adjusted latex header?
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).

**Comment by abn6** [comment]
I believe this should be able to reproduce the error: [doxytest.zip](https://github.com/user-attachments/files/17935332/doxytest.zip)

**Comment by albert-github** [comment]
Unfortunately it doesn't reproduce the problem. 
Even there is nothing doxygen can run I ran doxygen (1.12.0) and copied the 2 `tex`  files in the `out/latex` directory and afterwards I ran in the `out/latex` directory `pdflatex doc_lib.tex` and didn't get an error.

- Did you run the given text files as well?
- Seen the output in the original log file it is necessary to
  - attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).
  
  and not just some output tex files.

**Comment by albert-github** [comment]
What do you mean with:
> compiling doc_lib.tex 

I preformed the following steps (wheer doxygen points toi the 1.11.0 version):
- place `doc_lib.tex ` and `test.tex` in the current directory
- `doxygen -g Doxyfile`
- `doxygen`
- `cd latex`
- `copy ..\doc_lib.tex  .`
- `copy ..\test.tex .`
- `pdflatex doc_lib.tex` and this doesn't result in any error. We cannot use the provided make.bat as that would not use the `doc_lib.tex` (the doxygen step is there just to get the sty files).

So steps for you to preform:
- show **exact** steps you used
- provide resulting `latex` directory 

It might indeed be a problem of the installation of MikTex but that is hard to tell without the exact input information you used.

**Comment by abn6** [comment]
> What do you mean with:
> 
> > compiling doc_lib.tex
> 
> I preformed the following steps (wheer doxygen points toi the 1.11.0 version):
> 
> * place `doc_lib.tex ` and `test.tex` in the current directory
> * `doxygen -g Doxyfile`
> * `doxygen`
> * `cd latex`
> * `copy ..\doc_lib.tex  .`
> * `copy ..\test.tex .`
> * `pdflatex doc_lib.tex` and this doesn't result in any error. We cannot use the provided make.bat as that would not use the `doc_lib.tex` (the doxygen step is there just to get the sty files).
> 
> So steps for you to preform:
> 
> * show **exact** steps you used
> * provide resulting `latex` directory
> 
> It might indeed be a problem of the installation of MikTex but that is hard to tell without the exact input information you used.

I ran exactly the same steps as you described. [Here](https://github.com/user-attachments/files/17936089/latex.zip) is my latex folder. [Here](https://github.com/user-attachments/files/17936093/error_log.txt) is the complete log of `pdflatex doc_lib.tex`.

**Comment by abn6** [comment]
I uninstalled MikTex and installed an older version (22.10). The problem still happens.

**Comment by albert-github** [comment]
I don't have a real clue.
Older versions are most of the time not the best idea.
You said:
> I uninstalled MikTex and installed an older version (22.10).

did you install / uninstall in user mode or in administrator mode of MikTeX.
I use, which is as far as I know also advised on multiple places, administrator mode and that the packages etc. are available for all users.

**Comment by abn6** [comment]
I used user mode

**Comment by albert-github** [comment]
Might be an explanation, can you try administrator mode?

**Comment by abn6** [comment]
I think I managed to fix the problem without administrator mode.

I simply opneed Miktex Console, checked for updates, and **updated all packages**. Seems like the problem was (probably) the version of a specific package. Only thing is I don't know which one. Regardless, seems to work now.

Seems like this fixes the simple example we were working on, but not my complete project. Overall, this is a version-related problem. Doxygen 1.9 used to work, but when upgrading to 1.11 or 1.12, something breaks.

**Comment by abn6** [comment]
I've run some tests. It seems that \text{} inside $$ are no being parsed correctly. More specifically, underscores are not being escaped in this environment, when they should. 

For example: `Word_one_two` would produce `$\text{Word_one_two}$` instead of `$\text{Word\_one\_two}$`

**Comment by albert-github** [comment]
@abn6 

The `$$` might here a problem but to be able to reproduce and fix this problem we will need some source code:
- an attached, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).

**Comment by abn6** [comment]
[Here](https://github.com/user-attachments/files/17948060/test.zip) is a small, self contained example:

There is a dummy cpp funcion with a comment containing `\f$\text{some_text_with_underscores}\f$`. The `\text{}` command is included with the `amsmath` package, so:
- if it is **not** included in EXTRA_PACKAGES, the command seems to be ingored, and everything inside is treated as in math mode.
- if it is included in EXTRA_PACKAGES, the underscores are not escaped in the .tex file, so an error is thrown.

I included a .bat file with the following steps:
- doxygen -g Doxyfile
- doxygen
- cd latex
- pdflatex refman.tex

You may run this once to see the effect of not including the package. Then edit the configuration file to include it and run `pdflatex refman.tex`

**Comment by abn6** [comment]
Indeed `\_` fixes the issue.
