### ISSUE TITLE
Doxygen

### ISSUE THREAD

**Issue by LaloQuera710** [doxygen/doxygen#11252]
**Describe the bug**
Describe what you see that (you think) is wrong.

**Screenshots**
If useful, add screenshots to help explain your problem.

**To Reproduce**
Attach a self contained example that allows us to reproduce the problem.
Such an example typically exist of some source code (can be dummy code) and a doxygen configuration file used (you can strip it using `doxygen -s -u`). After you verified the example demonstrates the problem, put it in a zip (or tarball) and attach it to the bug report. Try to avoid linking to external sources, since they might disappear in the future.

**Expected behavior**
Describe what you would have expected or think is correct.

**Version**
Mention the version of doxygen used (output of `doxygen --version`) and the platform on which you run doxygen (e.g. Windows 10, 64 bit). If you run doxygen under Linux please also mention the name and version of the distribution used (output of `lsb_release -a`) and mention if you compiled doxygen yourself or that you use a binary that comes with the distribution or from the doxygen website.

**Stack trace**
If you encounter a crash and can build doxygen from sources yourself with debug info (`-DCMAKE_BUILD_TYPE=Debug`), a stack trace can be very helpful (especially if it is not possible to capture the problem in a small example that can be shared).

**Additional context**

**Comment by albert-github** [comment]
Just the template.

**Comment by LaloQuera710** [comment]
> **Describe the bug**
> Describe what you see that (you think) is wrong.
> 
> **Screenshots**
> If useful, add screenshots to help explain your problem.
> 
> **To Reproduce**
> Attach a self contained example that allows us to reproduce the problem.
> Such an example typically exist of some source code (can be dummy code) and a doxygen configuration file used (you can strip it using `doxygen -s -u`). After you verified the example demonstrates the problem, put it in a zip (or tarball) and attach it to the bug report. Try to avoid linking to external sources, since they might disappear in the future.
> 
> **Expected behavior**
> Describe what you would have expected or think is correct.
> 
> **Version**
> Mention the version of doxygen used (output of `doxygen --version`) and the platform on which you run doxygen (e.g. Windows 10, 64 bit). If you run doxygen under Linux please also mention the name and version of the distribution used (output of `lsb_release -a`) and mention if you compiled doxygen yourself or that you use a binary that comes with the distribution or from the doxygen website.
> 
> **Stack trace**
> If you encounter a crash and can build doxygen from sources yourself with debug info (`-DCMAKE_BUILD_TYPE=Debug`), a stack trace can be very helpful (especially if it is not possible to capture the problem in a small example that can be shared).
> 
> **Additional context**
> Add any other context about the problem here.
> 

4rd_hSM4kLCLg_aem_YXg_Db5a7oDCL6ycJEK4yg           <
[1] 22671
[2] 22672
rofilecard/?igsh=MWc1dGhuajdhZWVlbA==              <
/system/bin/sh: https://www: inaccessible or not found
[2] + Done                 view=graph%2Fstrdev%40cyberservices.comLaloska1%40%401998
[1] - Done                 \set https://console-openshift-console.apps.sandbox-m3.1530.p1.openshiftapps.com/topology/ns/strdev-dev?utm_source=pocket_saves
uentes Vazquez Eduardo Fuentes Fuentes Vazquez     <
/system/bin/sh: [Mobile]: inaccessible or not found
127|:/ $ [Mobile] 524426784197
/system/bin/sh: [Mobile]: inaccessible or not found
127|:/ $ [Mobile] +5294100001410
/system/bin/sh: [Mobile]: inaccessible or not found
127|:/ $ [Mobile] 442 678 4197
/system/bin/sh: [Mobile]: inaccessible or not found
127|:/ $ [Other] strdev@cyberservices.com
/system/bin/sh: [Other]: inaccessible or not found
127|:/ $ [Home] strdev@cyberservices.com
/system/bin/sh: [Home]: inaccessible or not found
127|:/ $ [Work] joedfuva@gmail.com
/system/bin/sh: [Work]: inaccessible or not found
127|:/ $ [_$!<School>!$_] joedfuva710@gmail.com
/system/bin/sh: can't open School: No such file or directory
1.openshiftapps.com/] strdev@cyberservices.com     <
/system/bin/sh: [https://console-openshift-console.apps.sandbox-m3.1530.p1.openshiftapps.com/]: inaccessible or not found
127|:/ $ [Home] Juan Maldonado
/system/bin/sh: [Home]: inaccessible or not found
127|:/ $ Queretaro, Queretaro 76118
/system/bin/sh: Queretaro,: inaccessible or not found127|:/ $ Mexico
/system/bin/sh: Mexico: inaccessible or not found
127|:/ $ [Organization] STR
/system/bin/sh: [Organization]: inaccessible or not found
andbox-m3.1530.p1.openshiftapps.com/               <
/system/bin/sh: [Organization]: inaccessible or not found
ge] https://strcozumel.000webhostapp.com/          <
/system/bin/sh: [Homepage]: inaccessible or not found127|:/ $ [Birthday] 1998-06-29
/system/bin/sh: [Birthday]: inaccessible or not found127|:/ $ [Anniversary] 2021-12-07
/system/bin/sh: [Anniversary]: inaccessible or not found
ole.apps.sandbox-m3.1530.p1.openshiftapps.com/     <
/system/bin/sh: https://console-openshift-console.apps.sandbox-m3.1530.p1.openshiftapps.com/https://console-openshift-console.apps.sandbox-m3.1530.p1.openshiftapps.com/: inaccessible or not found
127|:/ $ [Mobile] 4424812662
/system/bin/sh: [Mobile]: inaccessible or not found
.p1.openshiftapps.com/] +528000407777              <
/system/bin/sh: [https://console-openshift-console.apps.sandbox-m3.1530.p1.openshiftapps.com/]: inaccessible or not found
127|:/ $ [Mobile] +52 800 040 7777
/system/bin/sh: [Mobile]: inaccessible or not found
127|:/ $ [Work] +52 442 481 2662
/system/bin/sh: [Work]: inaccessible or not found
.p1.openshiftapps.com/] +52 442 678 4197           <
/system/bin/sh: [https://console-openshift-console.apps.sandbox-m3.1530.p1.openshiftapps.com/]: inaccessible or not found
e.apps.sandbox-m3.1530.p1.openshiftapps.com/       <
/system/bin/sh: [Home]: inaccessible or not found
127|:/ $ [Organization] Banco Azteca
/system/bin/sh: [Organization]: inaccessible or not found
127|:/ $ [Other] HomeHome
/system/bin/sh: [Other]: inaccessible or not found
127|:/ $ https://maps.app.goo.gl/ie46mMDgjfrXJVzTA
/system/bin/sh: https://maps.app.goo.gl/ie46mMDgjfrXJVzTA: inaccessible or not found
127|:/ $ https://maps.app.goo.gl/ie46mMDgjfrXJVzTA
/system/bin/sh: https://maps.app.goo.gl/ie46mMDgjfrXJVzTA: inaccessible or not found
.&ftid=0x0:0x16c1532167d0d5b8&entry=gps            <
internal error: j_async: bad nzombie (28)
[1] 22674
[2] 22675
onsole.apps.sandbox-m3.1530.p1.openshiftapps.com//system/bin/sh: [Other]: inaccessible or not found

/system/bin/sh: https://console-openshift-console.apps.sandbox-m3.1530.p1.openshiftapps.com/: inaccessible or not found
[2] + Done                 ftid=0x0:0x16c1532167d0d5b8
[1] - Done (127)           \[Other] https://maps.google.com/?q=Home+Juan+Maldonado+52%2C+Rosendo+Salazar%2C+76118+Santiago+de+Quer%C3%A9taro%2C+Qro.
127|:/ $
127|:/ $
127|:/ $
127|:/ $
