### ISSUE TITLE
Ubuntu22.04 Install doxygen. And LLVM ERROR: inconsistency in registered CommandLine options

### ISSUE THREAD

**Issue by GaoXiangYa** [doxygen/doxygen#11255]
**Describe the bug**
When I install doxygen on the Ubuntu22.04, `sudo apt install doxygen`. And I use `doxygen --version` , the output is:
```
:CommandLine Error: Option 'openmp-ir-builder-optimistic-attirbutes` registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```
The installed doxygen version is 1.9.8

**Comment by albert-github** [comment]
I don't think this is a direct doxygen problem but an Ubuntu distribution / distributor problem.
Probably best to get in touch with the person(s) that created the apt package of doxygen for Ubuntu, see: https://launchpad.net/ubuntu/+source/doxygen

Note also that the current doxygen version is 1.12.0

Maybe some other interesting pointers as well:
- https://gist.github.com/UbuntuEvangelist/47a4d1d4b6d5f25f42579922972ab00c
- https://askubuntu.com/questions/1291874/how-to-install-doxygen-on-ubuntu

**Comment by GaoXiangYa** [comment]
Thanks, I solved the problem by rebuild the doxygen from the source code.
