### ISSUE TITLE
tcl_mkkernel.doc:1675: warning: end of comment block while expecting command </div>

### ISSUE THREAD

**Issue by aotto1968** [doxygen/doxygen#11263]
**Describe the bug**

there is obviously a `</div>` missing, but the _line number_ displayed is the _line number_ at the end of the document and **not** the _line number_ that the initial `<div>` started with.

**Version**
1.13.0 (8007b6cfff3fdbafb38c15b484afeac12b2bb812*)

**Comment by albert-github** [comment]
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).

**Comment by aotto1968** [comment]
there is no *small* example because it is the end of the entire project. IF I would know the initial *buggy* command I wouldn't create this issue

**Comment by albert-github** [comment]
And how should we be able to give an advise / solve the problem without any information? Not even having the used settings (might be usage of an old header.html or footer.html).

**Comment by aotto1968** [comment]
so I have done some research.

* the problematic command is an *alias* called

```
ALIASES             += "includeBLUE{1}=## Using the \self package ... ^^ \include{doc} \1"
```

the `^^` together with `\include` create broken code

if I do *not* use the *alias* and write

```
## Using the \self package ...
\include{doc} ...
``` 
it works.

the include code is

```
\par TCL package libraries
\parblock
<dl>
  <dt> `lib\self.so` </dt>
    <dd>  A *shared library* or *shared object* is a *computer file* that contains *executable code* designed to be used 
          by multiple *computer programs* or other *libraries* at *runtime*.
  <dt> `lib\self.la` </dt>
    <dd>  A **.la** file is a *text file* used by the GNU *libtools* package to describe the files that make up the 
          corresponding library.
</dl>
\endparblock

\par > man n env
\parblock
To access the \libself package the environment variable \c TCLLIBPATH have to include the directory.

\verbatim
TCLLIBPATH
      If set, then it must contain a valid Tcl list giving directories to search during auto-load operations.
      Directories must be specified in Tcl format, using “/” as the path separator, regardless of platform.  
      This variable is only used when initializing the auto_path variable.
\endverbatim
\endparblock

\par > man n pkg_create
\verbatim
::pkg::create is a utility procedure that is part of the standard Tcl library.
It is used to create an appropriate `package ifneeded` command for a given package specification.
It can be used to construct a `pkgIndex.tcl` file for use with the package mechanism.
\endverbatim

\par The syntax of the `pkgIndex.tcl` file is simple
\verbatim
package ifneeded NAME 9.0 [list load [file join $dir libNAME.so]]
\endverbatim
```

**Comment by albert-github** [comment]
So now it would be possible to:
- create and attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).

**Comment by aotto1968** [comment]
after adding my updated code now the `include` (the `snippet` also) adding huge amount of WS in front of the text above 
![image](https://github.com/user-attachments/assets/6470632e-fe9d-4d81-a2a5-09a8200f4861)

in addition the `include` brake the entire format if the include start with an **empty-line**.

**Comment by albert-github** [comment]
I'm not sure how to get an example showing the problem from the above images.

Regarding the warning I tried to generate a bit a better warning but due to the lack of a good example it is hard to test this, for this I've just pushed a proposed patch, pull request #11266

**Comment by aotto1968** [comment]
close with issue, I restart with → bug - include start with empty line #11267

**Comment by aotto1968** [comment]
the `^^` seems NOT to be the root-clause of the problem -> read more at #11267

**Comment by aotto1968** [comment]
Now it works:
→ there is a __MASSIVE__ bug in `github`

I had the environment variable `GIT_WORK_TREE` set and **some** checkout `git pull origin master` go into directory specified in `GIT_WORK_TREE` **but** the compilation seems to ignore parts of the *new* files and end up in a *good* executable (`doxygen -V` was right) missing *essential* updates → this create a huge amount of __disorder__ probably for *all* updates of `git` code.

![image](https://github.com/user-attachments/assets/49df0614-83fe-4eaa-914a-9565c6e98395)
