### ISSUE TITLE
C++ 20 Concepts not found in search when inside a namespace

### ISSUE THREAD

**Issue by AlexWorx** [doxygen/doxygen#11283]
**Describe the bug**
Doxygen's search does not find C++ 20 Concepts which are located in a namespace.

**To Reproduce**
A brief main.cpp file is attached to this bug report.
It contains 2 classes and 2 concepts, one of each in global namespace and
one in namespace "a":

class   MyClass
concept MyConcept
class   a::MyClassInA
concept a::MyConceptInA

Steps:
- run:  doxygen -g doxygen.ini
- run:  doxygen doxygen.ini
- open "index.html" in a web-browser
- type "My" into search box.

**Expected behavior**
It should pop up 4 results:
- MyClass,
- MyClassInA,
- MyConcept, and
- MyConceptInA.

However, the latter is not included in the list.

My assumption is that C++ 20 Concepts inside namespaces are not found. But, of course, it may be some other bug as well.

**Version**
- Current Doxygen release 1.12.0
- Current github Version 1.13.0 as of today (December 18th 2024)

- System: Linux Arch 6.12.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 09 Dec 2024 14:31:57 +0000 x86_64

**Attachment**
The simple "main.cpp" is attached.

[doxygenMissingConceptsInSearch.zip](https://github.com/user-attachments/files/18185040/doxygenMissingConceptsInSearch.zip)

**Comment by albert-github** [comment]
It is strange that the concept `MyConceptInA` does not show up when searching for `My` but the class `MyClassInA` does show up.
When w are searching for `a` (i.e. the namespace name)we get
![image](https://github.com/user-attachments/assets/aa571f27-e747-4cff-b3b2-0df062049d63)

So here we get the concept (but not the class).

**Comment by AlexWorx** [comment]
Positive! **This commit fixed the issue for me**.  Thank you!

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.13.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
