### ISSUE TITLE
Functions declaration in nameless namespace generate a second entry in the doc (Origin: bugzilla #144043)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1150]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.3.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2004-06-09 17:53:00 +0000, Patryck Rouleau wrote:

    In C++, a function in a nameless namespace is like an static function.
    Doxygen generate two entries in the doc, probably one for the declaration
    and
    one for its definition. As the first doesn't have any doc attached on it, it
    generate an empty entry.
    
    Step to reproduce: 
    - Copy the code sample in a file.
    - Generate a default doxyfile
    - Activate the following options:
      - EXTRACT_ALL = YES
      - EXTRACT_STATIC = YES
    - Generate the code
    - Look in the html page that contains the functions documentation.
    
    === Code sample ===
    
    namespace foo
    {
    
    // forward declaration of fcts Y
    static void staticY();
    
    namespace // nameless
    {
    void 
        namelessY();
    } // namelessspace
    
    /**
     * Description of function X
     */
    void
        X()
    {
        staticY();
        namelessY();
    }
    
    /**
     * Description of staticY
     */
    void 
        staticY()
    {
    }
    
    namespace // nameless
    {
    
    /**
     * Description of namelessY
     */
    void 
        namelessY()
    {
    }
    
    } // namelessspace
    
    } // namespace foo

**Comment by albert-github** [comment]
With version 1.3.8 I see the problem as indicated.
With version 1.8.15 the entire mentioning of the anonymous namespace is gone unless the configuration setting `EXTRACT_ANON_NSPACES` is set to `YES` (possible since version 1.5.3), in the later case the `namelessY` is only shown once.

I think the problem has been solved in the mean time.
