### ISSUE TITLE
Doxygen incorrectly links members of a code snippet (Origin: bugzilla #145154)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1165]
status NEW severity *normal* in component *documentation* for *---*
Reported in version *1.3.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2004-06-29 17:26:17 +0000, Stephen Gross wrote:

    If you doxygenate the follow code snippet, you'll see that the documented
    code
    for foo2() is incorrect. Doxygen shows the first and third line of the
    function
    as linked. It *should* show only the second and third line as linked!
    
    Code follows:
    ===========================================================
    
    /// top-level namespace
    namespace TOP  
    {
            
            /// bottom-level namespace # 1
            namespace BOTTOM1  
            {       
                   
                    /// foo1   
                    void foo1()
                    {}
            
            } // End namespace BOTTOM1
    
            /// bottom-level namespace # 2
            namespace BOTTOM2  
            {
    
                    /// foo2
                    void foo2()
                    {
                            foo1();
                            BOTTOM1::foo1();
                            TOP::BOTTOM1::foo1();
                    }
    
            } // End namespace BOTTOM2
    
    } // End namespace TOP

**Comment by albert-github** [comment]
With the 1.3.1 version of doxygen we indeed see that the first and third call are linked.
With the doxygen version 1.9.5 we see that the second and third call are linked.

I think the problem has been solved in the mean time.
