### ISSUE TITLE
HTML and PDF hyperlinks pointing to themselves. (Origin: bugzilla #150713)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1220]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.5.3-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[mytest.cc](https://sourceforge.net/projects/doxygen/files/attachments/bug150713_30808_mytest.cc/download/download)_ (ID 30808)
- _[doxygen-patch](https://sourceforge.net/projects/doxygen/files/attachments/bug150713_30809_doxygen-patch/download/download)_ (ID 30809)

On 2004-08-21 11:49:32 +0000, zaffanella@cs.unipr.it wrote:

    Find attached a simple test program. The HTML documentation for the method
      int Brief()
    which has no detailed comment, is pointing to itself.
    This is annoying (in much larger projects) since one cannot easily
    distinguish those method having just the brief description from those
    that do have a detailed description.
    
    The "bug" shows up when using a standard configuration file, i.e.,
      doxygen -s -g
      doxygen Doxygen
    
    I am using the doxygen-1.3.8-20040812 CVS tarball.
    
    I am attaching a (simple!) patch to this problem.
    It seems to solve the problem on our project documentation.

On 2004-08-21 11:50:54 +0000, zaffanella@cs.unipr.it wrote:

    Created attachment 30808
    Test case.

On 2004-08-21 11:51:54 +0000, zaffanella@cs.unipr.it wrote:

    Created attachment 30809
    An attempt of a patch against doxygen-1.3.8-20040812

On 2004-08-22 10:28:26 +0000, Dimitri van Heesch wrote:

    This used to be the way things were, but then an undocumented method looks
    very
    much like a method with only a brief description (both are not linked). Now
    you
    know that if there is no link there is no documentation. I'm not sure which
    is
    better, so I'll make it as a feature enhancement for now.

**Comment by albert-github** [comment]
- In the 1.3.8 version I see the described phenomena
- In the 1.9.1 version we see that the links are still present, but also that in case of a detailed description present there is the word "More..." with a link to the detailed description (for the HTML version)
- in the current master (1.9.2 (60732c55c4bd92cb7ac11f173183b93ff63509f7)) we see that `Brief()` has no link anymore but the rest of the information / links are present (and thus in the LaTeX version there is also no link for `Brief()` anymore as requested)

I thin the problem has been fixed but not released.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.2.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
