### ISSUE TITLE
Inheritance diagrams difficult to read for dark backgrounds (Origin: bugzilla #152708)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1250]
status NEW severity *minor* in component *build* for *---*
Reported in version *1.3.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2004-09-15 10:37:49 +0000, Richard A wrote:

    I altered the stylesheet to use light text on a dark background. This makes
    parts of the diagrams (black with transparent background) hard to read...
    
    Solutions:
    - Add 'class="diag"' or similar to the img tags so I can set a light
    background
    in the stylesheet. Although this doesn't look very nice, it is better than
    nothing.
    - Provide an option to invert all colours in the images, or even to set all
    the
    colours that the image uses
    - Leave the background of the image transparent, but make the background of
    the
    "current class" white

**Comment by albert-github** [comment]
Since doxygen 1.9.5 doxygen has defines a light and a dark theme that should, automatically, solve this issue.
Besides the text it also handles the generated images.
See the setting `HTML_COLORSTYLE` in the documentation

I think the problem has been solved in the mean time.
