### ISSUE TITLE
With DETAILS_AT_TOP=YES, doxygen needs a <br> after details and before #includes (Origin: bugzilla #153364)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1264]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.3.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2004-09-22 05:13:10 +0000, Matthias Klose wrote:

    [forwarded from http://bugs.debian.org/264499]
    
    When the doxygen configuration file has
    
    DETAILS_AT_TOP = YES
    
    it generates html for the files that does this:
    
    Definition in file <a class="el"
    href="mq-local_8c-source.html">mq-local.c</a>.<code>#include
    "mq.h"</code><br>
    
    Which runs the #include text immediately after the preceding link to
    the file's source code, and it is mostly rendered on the same line by
    the browser (depending on window width).
    
    A <br> or <p> tag (or some other way to separate the two sections) is
    required after the link to the source code, and before the first
    #include.

On 2017-07-10 16:21:38 +0000, Thadeus Fleming wrote:

    This bug concerns an obsolete configuration option and can probably be
    closed.

**Comment by albert-github** [comment]
With version 1.3.8 I can reproduce the problems as indicated.
With 1.8.15 the problem is obsolete as `DETAILS_AT_TOP` has become obsolete (with version 1.5.7 though in version 1.5.6 the problem was gone).
From the change log of version 1.5.7:
> Added new option LAYOUT_FILE which can be used to specify a layout template file that tells doxygen in which order to generate the output and which titles to use for headings and how the navigation index will look; Read this for more info. As a result the following options are now obsolete since they can now only be controlled via the layout file: DETAILS_AT_TOP, ALPHABETICAL_INDEX. The following options can also be set via the layout file, but for convenience and backward compatibility reasons they are still also part of the configuration file: SHOW_INCLUDE_FILES, SHOW_USED_FILES, CLASS_GRAPH, COLLABORATION_GRAPH, GROUP_GRAPHS, INCLUDE_GRAPH, INCLUDED_BY_GRAPH. Run doxygen with the -l option to generate the default layout file.

The problem is also not present in 1.8.15 when we have a dedicated LAYOUT_FILE (in `<file>` section the `<detaileddescription title=""/>` directly before the `<includes visible="yes"/>`

So I think the problem has been solved in the mean time.
