### ISSUE TITLE
Fails to recognize class template members with changed parameter names (Origin: bugzilla #153366)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1266]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.3.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2004-09-22 05:16:38 +0000, Matthias Klose wrote:

    [forwarded from http://bugs.debian.org/235576]
    
    Doxygen seems lost when you changed the name of a parameter in class
    templates.  Consider the following piece of code, where the
    declaration of foo and its implementation differ on the name of
    parameter: Key, or K:
    
    /**
     ** \file misc/set.hh
     **/
    
    /// Wrapper around std::set.
    template < typename Key >
    class set
    {
      /// Union with another set \a s.
      void foo (const set& s) const;
    }; // class set
    
    // Union with another set \a s.
    template < class K >
    void
    set<K>::foo (const set<K>& s) const
    {
    }
    
    Doxygen reports:
    
    Searching for member function documentation...
    /tmp/misc/set/set.hh:17: Warning: no matching class member found for
      template < K >
      void set< K >::foo(const set< K > &s) const
    Possible candidates:
      void set< Key >::foo(const set &s) const
    
    If you use the same parameter name it works in both case.  Also, it
    seems that the problem is not in recognizing that both are related to
    the class set<K>, it seems to be related to the argument of `foo'.
    Indeed, if `foo' takes void, or int, as argument, the problem is
    solved, independently of the name of the template parameter.
    
    Worse yet: Doxygen accepts happily the following incorrect C++ code,
    where I have used `set' without template parameters inside the
    implementation of `foo':
    
    --------------------------------------------------
    /**
     ** \file misc/set.hh
     **/
    
    /// Wrapper around std::set.
    template < typename Key >
    class set
    {
      /// Union with another set \a s.
      void foo (const set& s) const;
    }; // class set
    
    // Union with another set \a s.
    template < class K >
    void
    set<K>::foo (const set& s) const
    {
    }
    --------------------------------------------------
    
    Searching for enumerations...
    Searching for member function documentation...
    Searching for members imported via using declarations...
    Building page list...

On 2006-08-01 11:29:22 +0000, Selim Belbachir wrote:

    I confirm the same problem with doxygen 1.4.7.
    
    
    template <class T_ITEM> 
    class AbstractList : public lang::Object
    {
    public :
    
        typedef T_ITEM* Iterator;
    
        void remove(Iterator it);
    };
    
    template <class T_ITEM> 
    void util::AbstractList<T_ITEM>::remove
       (typename util::AbstractList<T_ITEM>::Iterator  it) 
    {
    //...
    }
    
    result in
    
    AbstractList.h:224: Warning: no matching class member found for
      template < T_ITEM >
      void remove(util::AbstractList< T_ITEM >::T_ITEM *it)
    Possible candidates:
      void util::AbstractList< T_ITEM >::remove(Iterator it)

**Comment by albert-github** [comment]
When using doxygen version 1.3.6. on the original example I see the warnings as indicated, when running version 1.8.20 these warnings are gone.

Regarding the second example in the original issue (the wrong syntax), doxygen is not a compiler so when there is a language error the behavior is undefined.

Regarding the second issue, whit doxygen version 1.4.7 I get the warnings as indicated, with version 1.8.20 these warnings are gone.

Used doxygen settings:
```
QUIET=YES
EXTRACT_ALL=YES
EXTRACT_PRIVATE=YES
```

I think the problems have been solved in the mean time
