### ISSUE TITLE
complaining about static functions being documented elsewhere (Origin: bugzilla #153368)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1267]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.3.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2004-09-22 05:19:03 +0000, Matthias Klose wrote:

    [forwarded from http://bugs.debian.org/216195]
    
    home/davh/xxx/load/xxx.cc:628: Warning: member
    signal_handler: ignoring the detailed description found here, since
    another one was found at line 1583 of file
    /home/davh/xxx/load/yyy.cc!
    
    It should not complain about a static function in a file being available
    in several files!

On 2005-08-02 22:47:15 +0000, Charles Morison wrote:

    Instead of opening a new bug I am appending to this one, since I think my
    complaint is similar.
    
    If the name of a static method appears in more than one module of a project
    doxygen becomes confused when it cross references this static method for the
    "referenced by" links.  It lists all methods in all modules of the project
    that
    call the static method (even though the methods are referencing different
    static
    methods in different modules that just happen to have the same name) and it
    links all methods in all modules of the project that call the static method
    to
    the same static method which is usually just the first occurrence that
    doxygen
    found (instead of the static method in each module).
    
    This is not very good if the documentation is being used to provide a call
    graph
    since it is linking to the wrong method(s).

On 2013-05-27 18:29:25 +0000, bastien roucaries wrote:

    Any news of this bug ?

**Comment by albert-github** [comment]
The original problem looks like to be solved in the mean time, in the version 1.8.20 I see both static functions with their respective files.
Example:
File1.c and File2.c:
```
/** Documented */
static int hest() { return 0;}
```
in the default doxygen configuration file set:
```
EXTRACT_STATIC=YES
```

Regarding the second problem:
File1.c
```
/// \file

/** Documented in first */
static int hest() { return 0;}

/** the first fie */
void fie_1(void)
{
  hest();
}
```
File2.c
```
/// \file

/** Documented in second */
static int hest() { return 0;}

/** the second fie */
void fie_2(void)
{
  hest();
}
```
in the doxygen configuration file also set:
```
REFERENCED_BY_RELATION = YES
REFERENCES_RELATION    = YES
```
The results with the 1.8.20 version indicates that the `References hest().` link to the correct `hest` function.

Example 1: [example1.tar.gz](https://github.com/doxygen/doxygen/files/5561858/example1.tar.gz)

Example 2: [example2.tar.gz](https://github.com/doxygen/doxygen/files/5561861/example2.tar.gz)

I think both problems have been solved in the mean time.
