### ISSUE TITLE
SORT_MEMBER_DOCS doesn't work on inherited members (Origin: bugzilla #153381)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1272]
status NEW severity *minor* in component *general* for *---*
Reported in version *1.2.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2004-09-22 05:37:31 +0000, Matthias Klose wrote:

    [forwarded from http://bugs.debian.org/155355
     forwarded by email as well, but no trace in the BTS]
    
    Hi Dimitri,
    
    Please let me know if you perceive the following to be a problem:
    
      SORT_MEMBER_DOCS appears to sort members from a class but it doesn't
      sort all the members (including those inherited) as a single unit;
      they appear sorted below the local members.  I assume sorting all
      members was intended which is why I'm filing this bug.  Hope this
      helps.
    
    Thanks, Luca
    
    
    
    I hope this finds you well.  Sorry for the late reply on this.  I've
    tested the latest and greatest doxygen package and I'm still seeing
    some problems.  The SORT_MEMBER_DOCS appears to do the right thing on
    the "List of all members" pages but not on the "Class reference"
    pages.
    
    I'm using doxygen 1.2.16 from .deb with version 1.2.16-3.  I've built
    some documentation that exibits the problem.  Class
    framework::configuration inherits from
    framework::configuration_interface.  configuration overrides all the
    public members it inherits except configuration_interface::is_empty.
    
    On the "List of all members" page for configuration the members are
    listed in alphabetical order.  On the "Class reference" for
    configuration is_empty appears at the bottom of the list instead of in
    the middle before is_parent.
    
    Correctly sorted "List of all members":
    http://unmind.org/~jkakar/framework/classframework_1_1configuration-
    members.html
    
    Incorrectly sorted "Class reference":
    http://unmind.org/~jkakar/framework/classframework_1_1configuration.html
    
    I'll keep the documentation available at the above links for a couple
    of weeks.  Thanks a lot for following up on this.

On 2013-05-27 18:32:34 +0000, bastien roucaries wrote:

    Any news ?

**Comment by albert-github** [comment]
In the mean time a new setting has been introduced (in 1.3.6) `SORT_BRIEF_DOCS` and also the meaning / description of the items has been adjusted.

The 1.9.5 documentation reads:
> SORT_MEMBER_DOCS
>
>    If the SORT_MEMBER_DOCS tag is set to YES then doxygen will sort the (detailed) documentation of file and class members alphabetically by member name. If set to NO, the members will appear in declaration order.
>
 >   The default value is: YES.

> SORT_BRIEF_DOCS
>
 >   If the SORT_BRIEF_DOCS tag is set to YES then doxygen will sort the brief descriptions of file, namespace and class members alphabetically by member name. If set to NO, the members will appear in declaration order. Note that this will also influence the order of the classes in the class list.
>
>    The default value is: NO.

When setting `SORT_BRIEF_DOCS=YES` the brief (and inherited) functions descriptions are sorted.

I think the problem has been solved in the mean time.
