### ISSUE TITLE
Automatically extract FIXME's. (Origin: bugzilla #153382)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1273]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.2.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2004-09-22 05:39:42 +0000, Matthias Klose wrote:

    [forwarded from http://bugs.debian.org/122154
     forwarded by email as well, but no trace in the BTS]
    
    bug submitter writes:
    
    I realise that doxygen has a facility for TODO items but these only
    seem to be extracted if they are listed in the doxygen comment block
    OUTSIDE of a function definition.  I don't think I'm unique in that I
    put FIXME comments at the location of the potential problem.  It'd be
    lovely if doxygen had an option to extract these FIXME's and list them
    both as part of the class/individual source documentation and to
    generate a project-wide list akin to how the TODO functionality work.

On 2005-01-15 17:33:14 +0000, Chris Reed wrote:

    Actually, doxygen does support this to some extent. If you put the detailed
    documentation comment in
    the source file, it will pick up \todo commands mixed in the function
    definition just like you want. But,
    if you put the detailed comment in the header file, it won't work. This is
    because doxygen only allows a
    single detailed comment. See bug # 163033.

**Comment by albert-github** [comment]
I create a small example:
```
/// \file


/// the fie
///
/// \todo do write detailed first fie
void fie1();

/// the fie
///
void fie2()
{
  int a = 42;
  /// \todo do write internal second fie
}
```
and with the 1.2.18 version of doxygen the "internal" `\todo` was not shown.

With the current doxygen version (1.12.0) the "internal" `\todo` is shown.

Example: [example.tar.gz](https://github.com/user-attachments/files/16731842/example.tar.gz)


I think the problem has been solved in the mean time
