### ISSUE TITLE
FILE_PATTERNS doesn't have effect for some PHP file extensions (Origin: bugzilla #154556)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1284]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.3.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2004-10-05 12:29:21 +0000, Petr Dousa wrote:

    Doxygen 1.3.8 on Windows.
    
    I'm not able to process PHP files with .pinc extension. I have config file
    with
    just this line:
    
    FILE_PATTERNS = *.pinc
    
    and I have test.pinc file:
    
    <?php
    /**
    * @file test.pinc
    */
    
    /**
    * cool function
    */
    function helloWorld() {
    echo 'Hello World!';
    }
    ?>
    
    Doxygen says:
    
    Parsing file C:/Program Files/doxygen/bin/test.pinc...
    
    but nothing appears in HTML output. No warning is issued. When I renamed the
    file to .php or .inc, it worked.

On 2005-05-21 23:56:09 +0000, Michael Reiczyk wrote:

    I have the same problem with the .cxe extension even though I had it to the 
    FILE_PATTERNS parameter.

On 2005-08-15 19:47:31 +0000, Daniel Stobbe wrote:

    I have the same Problem with ".php5" under linux & wine with v 1.4.4
    
    this works:
    
    require_once(POS_ROOT_DIR."pos-config/pos.class.config.php");
    
    
    this works not:
    
    require_once(POS_ROOT_DIR."pos-config/pos.class.config.php5");
    
    
    error-desc:
    
    no html-output found
    
    Thats a big problem for me. :(
    

On 2006-03-16 20:16:48 +0000, Axel Kollmorgen wrote:

    not a bug. FILE_PATTERNS does *not* associate file extensions with
    languages, but merely filters a list of *predefined* extension-to-language
    mappings. from the manual:
    
    Doxygen looks at the file's extension to determine how to parse a file.
    [...] files with the extensions .php, .php4, .inc or .phtml are treated as
    PHP sources. Any other extension is parsed as if it is a C/C++ file
    [...]
    Only files that match one of the patterns [of FILE_PATTERNS] will be parsed
    (if the patterns are omitted a list of source extensions is used).
    
    ie. if you add *.pinc, *.cxe, *.php5 or any other pattern not among the
    predefined ".php, .php4, .inc or .phtml", the file might be parsed, but not
    as of type PHP.
    
    to my knowledge, there is no way currently to configure additional/custom
    extension-to-language mappings, so the only wordaround is to patch the
    source (search for '.php' and add your costum extensions) and recompile. i
    think there is a feature request for dynamic configuration somewhere (can't
    find it right now), and some progress toward this goal has been made
    recently (getLanguageFromFileName()), but we aren't there yet.
    

On 2006-03-20 21:38:54 +0000, Kevin McBride wrote:

    Marking as enhancement.  Custom handlers need to be put in doxygen.
    
    I am also making this bug dependent of another bug I filed.
    
    Axel:  This IS a bug.  php5 is an appropriate PHP extension, and needs to be
    recognized by doxygen as a PHP file.

On 2007-10-20 18:10:33 +0000, Axel Kollmorgen wrote:

    the original feature request for "Configurable mapping from extension to
    language parser" is at http://bugzilla.gnome.org/show_bug.cgi?id=131496 . so
    i guess this one can be closed / marked duplicate.

**Comment by albert-github** [comment]
Doxygen supports by default for php the following extension (in version 1.9.0): `php`, `php4`, `php5`, `inc` and `phtml`.
When you want to use another extension you should add it to the `FILE_PATTERNS` for it as well as setup the correct mapping by means of `EXTENSION_MAPPING`.

See also #944 (i.e. the original bug 131496).

I think this problem has been solved in the mean time.
