### ISSUE TITLE
Documentation for elements outside class but inside namespace missed (Origin: bugzilla #155859)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1308]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.3.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2004-10-19 17:04:49 +0000, Joel Sherrill wrote:

    We had been using Doxygen 1.3.6 and were updating to 1.3.9.1 and started to
    get a lot of warnings.  This file is enough to show that it works outside a 
    namespace and inside a class but not inside the namespace/outside the class.
    This error seems to occur with more than simple variable members.  We have 
    also seen it with typedefs.   
     
     
    /*! @file constint.h */ 
     
    /*!  This one is processed OK.  */ 
    const int outsideNamespace = 2; 
     
    namespace Examples { 
     
      /*! 
       *  @relates Examples::ConstInt 
       * A constant integer whose documentatioan is taken. 
       */ 
      const int Examples::constIntOutsideClass = 2; 
     
      /*! This one is claimed to be undocumented with 1.3.9.1.  */ 
      const int anotherConstIntOutsideClass = 2; 
     
      /*! @class ConstInt 
       *  Constant Integer example class 
       */ 
     
      class ConstInt { 
        public: 
        /*! Another constant integer whose documentation is accepted. */ 
        const int constInt = 2; 
      }; 
    };

On 2005-09-21 04:45:13 +0000, Dominik Grabiec wrote:

    A simple fix for this problem is to document the namespace to which the
    members
    belong, this will then generate a page for that namespace where the detailed
    documentation of those members will reside.
    
    Also adding them to a group fixes this problem.

**Comment by albert-github** [comment]
In the 1..3.6 and 1.9.5 version we don't see any warnings and the output looks OK.
In the 1.3.9.1 version we see the warning:
```
constint.h:15: Warning: Member anotherConstIntOutsideClass of namespace Examples is not documented.
```

I think the problem has been solved in the mean time.
