### ISSUE TITLE
Doesn't support quotes in HTML code embedded into a PHP script (Origin: bugzilla #156160)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1310]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.3-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2004-10-22 14:47:22 +0000, Jean-Marc Molina wrote:

    Try to generate the Doxydoc for the following PHP script. Note the double
    quote
    in the Â« "Viewing the test class... Â» string, if you remove it, the
    Doxydoc is
    successfully generated, if you leave it, the Doxydoc of the class is not
    generated, like if the parser skept it because it was not a valid PHP
    script.
    
    <?php
    
    /**
    A test class.
    */
    
    class test_class
    {
    	/**
    	Constructor.
    	*/
    	
    	public function __construct ()
    	{
    		?>
    		<p>
    		Function 'construct' called.
    		</p>
    		<?php
    	}
    
    	/**
    	View test class.
    	*/
    	
    	function view ()
    	{
    		?>
    		<p>
    		"Viewing the test class...
    		</p>
    		<?php
    	}
    }
    
    ?>

On 2007-09-28 05:19:05 +0000, Adam H Peterson wrote:

    I have what may be a related or the same bug.  With the following files:
    
    Doxyfile_____________________
    PROJECT_NAME           = "Test Project"
    OUTPUT_DIRECTORY       = doxy
    INPUT                  = .
    ------------------------------
    
    
    main.cpp______________________
    //!	\file
    //!	
    
    //!	<dl>
    //!	<dt>file</dt>
    //!	<dd>
    //!		equivalent to "<b>source</b> <i>dest</i>".
    //!	</dd>
    //!	</dl>
    int main() {
    }
    ------------------------------
    
    
    If I run Doxygen right now, the HTML documentation generated for main() puts
    the <b> and <i> tags in as verbatim text, but if the quotes are removed, the
    content is properly bolded/italicized.  So something isn't quite right with
    quote handling in some contexts.  Maybe this test case will help nail it
    down?
    

On 2007-09-28 05:21:25 +0000, Adam H Peterson wrote:

    Follow up comment to the above.  This is with:
    Doxygen 1.5.1
    OS: Ubuntu Feisty

On 2007-10-15 19:40:40 +0000, Dimitri van Heesch wrote:

    This bug's version was set to "latest". Since this is a moving target, I
    changed it to 1.5.3-SVN. If you believe this has already been fixed, then
    please change the status accordingly.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6536

The problem mentioned by Adam H Peterson is correct behavior (as the tags are inside a string as denoted by the double quotes).

**Comment by albert-github** [comment]
Code has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
