### ISSUE TITLE
Slightly wrong TC field format in RTF (Origin: bugzilla #157137)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1320]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.3.x* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[tc.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug157137_34569_tc.zip/download/download)_ (ID 34569)

On 2004-11-02 15:21:31 +0000, Dmitry Kormalev wrote:

    Doxygen generates TC fields in RTF output in the form
    {TC [options] "Name"}
    while MS Word recommends
    {TC "Name" [options]}
    This results in duplication of "Name" text in the document body when saving 
    edited RTF. "Name" is repeated as many times as the document is saved. The 
    effect appears after the document is re-opened.
    This effect is not reproduced if RTF is saved as DOC.
    (Checked with Word 2000 & XP)

On 2004-12-05 17:46:04 +0000, Dimitri van Heesch wrote:

    Do you mean putting the \v after the \tc "name"? 
    If I do that I get a \ after the name in the TOC!

On 2004-12-07 05:23:21 +0000, Dmitry Kormalev wrote:

    Created attachment 34569
    .doc and .rtf that demonstrate the bug

On 2004-12-07 05:23:56 +0000, Dmitry Kormalev wrote:

    No, I mean that Doxygen can generate e.g. the following field in the
    resulting
    RTF:
    {TC \l 2 "namespace\:\:Class"}
    Word doesn't like it. Try to save the attached file as RTF. 
    My Word 2000 saves it as 
    namespace::Class{TC \l 2 "namespace\:\:Class"}
    Then edit it and save it again (still as RTF)... It will be
    namespace::Classnamespace::Class{TC \l 2 "namespace\:\:Class"}
    And so on.
    If the field is written as
    {TC "namespace\:\:Class" \l 2 }
    then there is no problem.
    (See the attachment)

On 2006-08-13 19:53:05 +0000, AndrÃ© Klapper wrote:

    reopening as requested information has been provided.

**Comment by albert-github** [comment]
- Unfortunately the attachment only contains a rtf and doc file and no original source code from which the RTF is generated.
- the supplied rtf file looks like it only is an excerpt from the doxygen generated RTF output
- the `TC` in relation to RTF output cannot be found in the, old, source code


So I think the problem is not reproducible (anymore) and incomplete.
