### ISSUE TITLE
Nested classes are not documented properly in specialised class templates (Origin: bugzilla #157809)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1330]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.3.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2004-11-10 00:32:00 +0000, Christian Holm Christensen wrote:

    The below should be run through doxygen with any configuration.  It will
    complain that 
    
      foo.cxx:65: Warning: no matching class member found for
        mother< double >::daughter::daughter(const mother< data_type > &m)
      Possible candidates:
        mother< double >::daughter::daughter(const mother< data_type > &m)
      foo.cxx:70: Warning: no matching class member found for
        void mother< double >::daughter::print() const
      Possible candidates:
        void mother< double >::daughter::print() const
    
    As you can see, the alternative is the same as the complaint! 
    
    Here's the code 
    
    
    // Start of foo.cxx 
    //
    //
    //
    #ifndef __IOSTREAM__
    # include <iostream>
    #endif
    /** @file    foo.cxx
        @author  Christian Holm Christensen <cholm@nbi.dk>
        @date    Wed Nov 10 01:03:07 2004
        @brief   Test
    */
    
    template <typename Type>
    class mother;
    
    //____________________________________________________________________
    template <>
    class mother<double>
    {
    public:
      /** Type of data stored */
      typedef double data_type;
    private:
      /** Data stored */
      double _data;
    public:
      /** Make a mother object
          @param d Data to store  */
      mother(const data_type& d);
      /** Get the stored data
          @return value of stored data  */
      const data_type& value() const { return _data; }
      /** Print info on standard out */
      void print() const;
    
      class daughter
      {
      private:
        /** Reference to data stored */
        const data_type& _data;
      public:
        /** Create a daughter object
            @param m Reference to mother */
        daughter(const mother<data_type>& m);
        /** Print info on standard out */
        void print() const;
      };
    };
    
    //____________________________________________________________________
    mother<double>::mother(const data_type& d)
      : _data(d)
    {}
    
    //____________________________________________________________________
    void
    mother<double>::print() const
    {
      std::cout << _data << std::endl;
    }
    
    //____________________________________________________________________
    mother<double>::daughter::daughter(const mother<data_type>& m)
      : _data(m.value())
    {}
    
    //____________________________________________________________________
    void
    mother<double>::daughter::print() const
    {
      std::cout << _data << std::endl;
    }
    
    //____________________________________________________________________
    int
    main()
    {
      mother<double> m(3.14);
      mother<double>::daughter d(m);
      m.print();
      d.print();
      return 0;
    }
    //____________________________________________________________________
    //
    // EOF
    //

**Comment by albert-github** [comment]
With the 1.3.9.1 version I do see the warnings as indicated (together with some, correct, warnings about not documented Compounds / functions).
With the 1.9.5 version I see only the correct warnings about not documented Compounds / functions.

I think the problem has been solved in the mean time.
