### ISSUE TITLE
HIDE_IN_BODY_DOCS Seems to be always on if  MULTILINE_CPP_IS_BRIEF is off (Origin: bugzilla #158045)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1333]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.3.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2004-11-12 14:14:38 +0000, Mikko LaitamÃ¤ki wrote:

    Doxygen doesn't include documentation defined in C++ methods body if 
    MULTILINE_CPP_IS_BRIEF = NO in config file.

**Comment by albert-github** [comment]
Most likely is that here is a misunderstanding about when the documentation should be show (and which documentation) though due to a missing example it is not possible to see what is exactly the case.

I think the issue is incomplete
