### ISSUE TITLE
@see does not work correctly for methods with ellipsis (...) parameter (Origin: bugzilla #158688)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1338]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.3.x* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxy.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug158688_33930_doxy.zip/download/download)_ (ID 33930)

On 2004-11-19 10:35:20 +0000, Gerlinde Steininger wrote:

    Please describe the problem:
    I defined several signatures for a method. As it was not possible to specify
    the number and type of all argument expected, the methods were declared by 
    terminating the list of argument declarations with the ellipsis (...) which 
    means, that some more arguments may follow.
        void f2(int arg1, char* arg2,  ...);
        void f2(int arg1,  ...);
        void f2(bool argbool, int arg1, char* arg2,  ...);
    Then I wanted to include a reference to the 2nd method in the other two
    methods
    and included
    @see #f2(int, ...)
    I expected, that if I click on the reference in the generated document (or 
    html), that it would navigate to the 2nd method. But it navigated to one of
    the
    other ones. If I removed the (...) from the signatures, everything worked as
    expected.
    
    
    Steps to reproduce:
    1. Define several signatures for one method name, e.g.
        void f2(int arg1, char* arg2,  ...);
        void f2(int arg1,  ...);
        void f2(bool argbool, int arg1, char* arg2,  ...);
    2. Include @see which references one of these signatures
    @see #f2(int, ...)
    3. run doxygen
    4. open generated document and klick on reference generated from @see
    
    
    
    Actual results:
    It does not navigate to the requested signature. It navigates to one of the 
    other ones
    
    
    Expected results:
    Navigation to the request signature. In the above example to the 2nd one.
    
    Does this happen every time?
    yes
    
    Other information:

On 2004-11-19 10:44:15 +0000, Gerlinde Steininger wrote:

    Created attachment 33930
    Short program
    
    Class contains method f2 with 3 signature which contain ellipsis (...)
    parameter. Here navigation does not work.
    It furthermore contains methods f1 with same signatures as in f2, but
    without
    the ellipses. Here the navigation is ok.

**Comment by albert-github** [comment]
I tested the problem with version 1.3.8 and could observe a wrong link, same accounted for other versions (including 1.8.14) with version 1.8.15 the problem is gone.

I think the problem has been solved in the mean time.
