### ISSUE TITLE
@copydoc cannot span multiple lines (Origin: bugzilla #161451)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1367]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.3.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2004-12-16 14:40:27 +0000, Matt Fowles wrote:

    @copydoc cannot span multiple lines.  This is especially annoying with large
    argument lists.

On 2004-12-16 18:56:30 +0000, Dimitri van Heesch wrote:

    Not sure if it helps in your case, but if you do not use function
    overloading
    you can use func() to refer to a function named "func" regardless of the
    argument list.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #8977

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.3.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
