### ISSUE TITLE
Typedef of template arguments confuses Doxygen when used as function arguments (Origin: bugzilla #163562)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1398]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-01-10 14:02:10 +0000, Tanguy Fautre wrote:

    The attached test case generates the following warning:
    
    foo.cpp:23: Warning: no matching class member found for
      template < T >
      foo< T > & foo< T >::function_1(value_type Value)
    Possible candidates:
      foo & foo< T >::function_1(T Value)
    
    foo.cpp:31: Warning: no matching class member found for
      template < T >
      foo< T > & foo< T >::function_2(value_type Value)
    Possible candidates:
      foo & foo< T >::function_2(T Value)
    
    foo.cpp:39: Warning: no matching class member found for
      template < T >
      foo< T > & foo< T >::function_3(T Value)
    Possible candidates:
      foo & foo< T >::function_3(value_type Value)
    
    Note: With the test case, Doxygen seems to be able to find a possible
    candidate
    (which is in this case should be the class member to be used) but in a more
    complex project that suffers from the same bug, it does not find any
    candidate.
    
-------------------------------------------------------------------------------
    foo.cpp
-------------------------------------------------------------------------------
    
    template <class T>
    class foo
    {
    public:
    
    	typedef T value_type;
    
    	foo & function_1(T Value);				// Goes OK with Doxygen
        foo & function_2(T Value);                              // Doxygen
    generares a warning, it does not seem
    to understand that T and value_type are the same
        foo & function_3(value_type Value);             // Doxygen generares a
    warning, it does
    not seem to understand that T and value_type are the same
    
    private:
    
    };
    
    
    
    template <class T>
    inline foo<T> & foo<T>::function_1(value_type Value)
    {
    	return (* this);
    }
    
    
    
    template <class T>
    inline foo<T> & foo<T>::function_2(value_type Value)
    {
    	return (* this);
    }
    
    
    
    template <class T>
    inline foo<T> & foo<T>::function_3(T Value)
    {
    	return (* this);
    }
    
    
    
    int main()
    {
    
    }

On 2005-01-10 14:06:49 +0000, Tanguy Fautre wrote:

    Small error in the test case (to stay coherent with the comments):
    
    inline foo<T> & foo<T>::function_1(value_type Value)
    should be
    inline foo<T> & foo<T>::function_1(T Value)
    
    And of course Doxygen won't generate any warning for function_1() then.

**Comment by albert-github** [comment]
With the doxygen 1.4.0 version I see the warnings as indicated in the current doxygen version (1.12.0) the warnings are gone.

I think the problem has been solved in the mean time.
