### ISSUE TITLE
Bad hyperlinks in native(non-english) language (Origin: bugzilla #163807)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1405]
status NEW severity *normal* in component *documentation* for *---*
Reported in version *1.5.3-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-01-12 14:13:01 +0000, Alexander wrote:

    In options I have 
    OUTPUT_LANGUAGE = Russian
    
    But hyperlinks like file://c:/ÐÐ¾ÐºÑÐ¼ÐµÐ½ÑÐ°ÑÐ¸Ñ/Ð¤Ð°Ð¹Ð».doc aren't
    parsed.
    If filenames and paths are in english - all is ok

On 2007-10-15 19:40:42 +0000, Dimitri van Heesch wrote:

    This bug's version was set to "latest". Since this is a moving target, I
    changed it to 1.5.3-SVN. If you believe this has already been fixed, then
    please change the status accordingly.

**Comment by albert-github** [comment]
From the given information it is not possible to (try to) reproduce the issue.

Setting it to not complete / invalid issue.
