### ISSUE TITLE
\section title not displayed (when using tagfile containing same section Id) (Origin: bugzilla #163919)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1407]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-01-13 10:40:21 +0000, Paul Kamphuis wrote:

    Two project with both on their main page: (related pages not checked)
    
    \section intro_sec Introduction
    
    When using the tagfile of the first project in the second project, the
    generated
    main page html contains the following html:
    
    <h2><a class="anchor" name="intro_sec">intro_sec</a></h2>

**Comment by albert-github** [comment]
Till version 1.9.1 I get a warning like:
```
p2/mainpage.md:3: warning: multiple use of section label 'intro_sec' while adding section, (first occurrence: index.html)
```
later on this warning is gone and the output looks OK.

I think the problem has been solved in the mean time.

Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/9794230/example.tar.gz)
