### ISSUE TITLE
There should be a tag to conditionally omit a class or member from the documentation (Origin: bugzilla #164076)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1414]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-01-14 13:27:44 +0000, Georg Schwab wrote:

    It is sometimes useful to omit classes, members, pages, groups etc. from
    being
    included in the documentation. Currently this can be achieved either with 
    preprocessor directives, with \cond and \endcond directives, or by omitting
    the
    documentation of the entity and setting HIDE_UNDOC_XXX to YES.
    
    It would, however, improve the readability of the code considerably if a tag
    (e.g. \extractif) similar to \cond or \if could be used to exclude the
    entity
    that is being documented unless a certain section is enabled. e.g.:
    
    /*!
     * \class NetworkInterface
     * \brief Base class for all network interfaces
     * \extractif networking_extensions
     */

**Comment by albert-github** [comment]
Since doxygen version 1.5.2 there exists the setting `EXCLUDES_SYMBOLS` and by setting this to `EXCLUDE_SYMBOLS=NetworkInterface` I think the wanted enhancement exits.

I think the problem has been solved in the mean time
