### ISSUE TITLE
Make namespace list hierachical in tree view (like Class hierarchy) (Origin: bugzilla #164673)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1426]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.3.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-01-20 09:00:11 +0000, Marcel Loose wrote:

    Currently, the Namespace List in the treeview provides a flat view of all
    namespaces.
    It would be nice if namespaces were presented in a hierachical way, similar
    to, e.g.,
    the class hierarchy.

On 2005-03-20 12:54:06 +0000, Dimitri van Heesch wrote:

    I agree.

On 2007-12-15 15:16:12 +0000, Dimitri van Heesch wrote:

    *** Bug 316603 has been marked as a duplicate of this bug. ***

**Comment by albert-github** [comment]
In the current version the Namespace is shown in tree form analogous to class.

I think the problem has been solved in the mean time.
