### ISSUE TITLE
Multiple links to same class in module listing (Origin: bugzilla #166664)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1451]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.3-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-02-08 13:15:12 +0000, Inge Korbu wrote:

    Please describe the problem:
    The Module list shows multiple links to the same class.
    This error was not reproduced in version 1.3.9
    
    Steps to reproduce:
    Use \addtogroup tag to group classes in modules.
    Run doxygen and check the Module link in the output.
    
    Actual results:
    
    
    Expected results:
    
    
    Does this happen every time?
    Yes
    
    Other information:

On 2007-10-15 19:40:42 +0000, Dimitri van Heesch wrote:

    This bug's version was set to "latest". Since this is a moving target, I
    changed it to 1.5.3-SVN. If you believe this has already been fixed, then
    please change the status accordingly.

**Comment by albert-github** [comment]
The issue contains hardly any information and with the sparse information I have not been able to reproduce the problem wit the 1.4.0 or 1.4.1 version (i.e. the versions after 1.3.9 that were present at the moment of the writing of the issue).

The issue is in my opinion incomplete.
