### ISSUE TITLE
Introduce documentation categories (Origin: bugzilla #167507)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1465]
status NEW severity *enhancement* in component *build* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-02-15 18:34:15 +0000, Timothy Madden wrote:

    I would like to document my sources for the users of my classes and for the
    other people going to take over my work or already working with my on my
    classes. And I would like to write documentation in my sources intended to
    be
    made public and released.
    
    These are three diferent categories of audience for my sources.
    Documentation
    intended to be public is very important for the company's image on the
    market
    and for my image in the company. Documentation intended for users of my
    classes
    (possible coleags of mine) must not refer to implementation details.
    Documentation for a future maintainer of my code would have to include every
    little detail about what I have done. And I could think of another
    documentatin
    category, describing code that I have written for test purposes only and now
    has
    to be deleted. This category would be intended only for me. Or maybe I have
    documentation in the sources that has already been released and now must be
    not
    touched.
    
    I would like doxygen to have some commands like \ImplementationDoc,
    \PublicDoc,
    \ReleaseDoc, \DocCategory <TrashCode>, \DocCategoryGroup @{...@}. This would
    include some predefined documentation categories and generic doc categories.
    
    And also some commands to selectivly include/exclude doc categories in the
    generated output, and commands to customise the appearance of a given
    category,
    like:
    /**
    \OutputEffects
      DocCategory <TrashCode>
       text-color: dimmed
      ImplemetationDoc
       background: color(240, 240, 255) 
     */

**Comment by albert-github** [comment]
In doxygen it is already possible to select parts of the documentation / code by means of the `\if ... \endif` by setting the correct `ENABLED_SECTIONS` it is possible to select the right part. By means of `ALIASES` these commands can even be wrapped in "user friendly" commands.


So I think the problem is usage
