### ISSUE TITLE
source #included inside a namespace does not get good definition location (Origin: bugzilla #168380)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1471]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.3-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[a.cpp](https://sourceforge.net/projects/doxygen/files/attachments/bug168380_37888_a.cpp/download/download)_ (ID 37888)
- _[a.h](https://sourceforge.net/projects/doxygen/files/attachments/bug168380_37889_a.h/download/download)_ (ID 37889)
- _[a.inl](https://sourceforge.net/projects/doxygen/files/attachments/bug168380_37890_a.inl/download/download)_ (ID 37890)
- _[Doxyfile](https://sourceforge.net/projects/doxygen/files/attachments/bug168380_37891_Doxyfile/download/download)_ (ID 37891)

On 2005-02-24 11:57:39 +0000, David Geldreich wrote:

    If you have something like
    
    a.h:
    
    namespace test {
    
    class A {
    public:
        int GetVal() const;
    };
    
    #include "a.inl"
    
    }
    
    The definition of A::GetVal is in a.inl but doxygen indicates its location
    inside a.h and do not manage to inline the source in the documentation.
    
    However documentation information is extracted properly.

On 2005-02-24 11:58:36 +0000, David Geldreich wrote:

    Created attachment 37888
    Source example a.cpp

On 2005-02-24 11:59:30 +0000, David Geldreich wrote:

    Created attachment 37889
    source example a.h

On 2005-02-24 12:00:06 +0000, David Geldreich wrote:

    Created attachment 37890
    source example a.inl

On 2005-02-24 12:00:46 +0000, David Geldreich wrote:

    Created attachment 37891
    Doxyfile used to compile the documentation and show the bug

On 2005-02-26 17:54:34 +0000, Dimitri van Heesch wrote:

    A #include inside curly brackets is included verbatim by the preprocessor.
    This
    has it's uses by as you observed also some limitations. To fix this, either
    avoid such contructs or set ENABLE_PREPROCESSING to NO.
     

On 2005-02-27 19:52:57 +0000, David Geldreich wrote:

    Yes but in this special case, the included file is processed but as the was 
    done to include it in a namespace.
    
    So void test::A::GetVal() const is not documented as doxygen only sees it as
    A::GetVal()
    
    The code I am trying to document is not mine. Otherwise, I will do the
    include
    outside the namespace braces.
    
    So I was thinking, it will probably possible to keep the namespace level 
    information while including the #include file.
    
    
    

On 2007-10-15 19:40:43 +0000, Dimitri van Heesch wrote:

    This bug's version was set to "latest". Since this is a moving target, I
    changed it to 1.5.3-SVN. If you believe this has already been fixed, then
    please change the status accordingly.

**Comment by albert-github** [comment]
With the 1.4.1 version we see that `GetVal` has:
```
Definition at line 16 of file a.h.
```
with the 1.9.5 version we get:
```
Definition at line 2 of file a.inl.
```

I think the problem has been solved in the mean time.
