### ISSUE TITLE
Symbols from namespaces sometimes don't get cross referenced in Examples. (Origin: bugzilla #169022)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1481]
status NEW severity *major* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-03-02 20:45:49 +0000, SK wrote:

    Distribution/Version: XP
    
    The header file and the example file source code are below. When I generate
    the
    html documentation, the lines of code in testdoxyexample.cpp that are
    commented
    are not cross-referenced. In the configuration for generation, the example
    file
    is excluded from being documented, because that is the way I want it.
    
    Here are the header file and example file.
    
-------------------------------------------------------------------------------
    testdoxy.h
-------------------------------------------------------------------------------
//////////////////////////////////////////////////////////////////////////////
    ///
    /// @file testdoxy.h
    ///  
//////////////////////////////////////////////////////////////////////////////
    
////////////////////////////////////////////////////////////////////////////////
    ///
    /// @brief My namespace
    ///
////////////////////////////////////////////////////////////////////////////////
    
    namespace Mine {
    
///////////////////////////////////////////////////////////////////////////////
    ///
    /// @brief My Class
    ///
///////////////////////////////////////////////////////////////////////////////
    template<typename T>
    class Foo {
    public:
        bool operator*() {
            return true;
        }
    };
    
///////////////////////////////////////////////////////////////////////////////
    ///
    /// @brief My function 1
    ///
///////////////////////////////////////////////////////////////////////////////
    template<typename T>
    Foo<T> Fn(T& _t) {
        return Foo<T>();
    }
    
///////////////////////////////////////////////////////////////////////////////
    ///
    /// @example testdoxyexample.cpp
    ///
///////////////////////////////////////////////////////////////////////////////
    
    }
    
-------------------------------------------------------------------------------
    testdoxyexample.cpp
-------------------------------------------------------------------------------
    #include "testdoxy.h"
    
    #define EXTERN_C    extern "C"
    
    // Mine::Foo<int> does not get cross referenced here. 
    EXTERN_C __declspec(dllexport) void Bar(Mine::Foo<int> _f) {
    }
                         
    template<typename T>
    void Bat(const T& _t) {
    }
    
    void main (int argc, char *argv[])
    {
        int i;
        Mine::Foo<int> f;
        Bar(f);
        Mine::Fn(f);
        // Mine::Fn does not get cross referenced here.
        Bat(*Mine::Fn(f));
    }

**Comment by albert-github** [comment]
Given the example:
- 1.4.1 the links are not present in the example
- 1.8.14 the links are present in the example

I think the problem has been solved in  the mean time.
