### ISSUE TITLE
xml output does not copy images to xml directory (Origin: bugzilla #169789)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1496]
status REOPENED severity *minor* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-03-10 00:31:26 +0000, Michael S. Scherotter wrote:

    Version details: 1.4.1
    
    Add an image to the documentation like this:
    ///\image html objectModel.jpeg
    
    the following XML is generated
    <image type="html" name="objectModel.jpeg" />
    but the file objectModel.jpeg is not copied to the output xml directory.
    
    I know that the image could be found because the file is correctly in the
    html
    directory

On 2005-03-11 21:18:53 +0000, Dimitri van Heesch wrote:

    Good point. I always considered the \image command to be output type
    specific
    (i.e. depending on the first parameter), but for the XML output I can
    imagine it
    is convenient to have the output copied for any \image command.

On 2005-03-29 18:15:53 +0000, Dimitri van Heesch wrote:

    Should be fixed in 1.4.2.

On 2005-05-19 22:08:10 +0000, Michael S. Scherotter wrote:

    It is not fixed in 1.4.3.
    \image html optionPanes.jpg "Option Panes appear in the Tools...Options
    dialog"
    does not copy optionPanes.jpg to the xml output directory.

**Comment by albert-github** [comment]
With version 1.4.1 I can reproduce the problem, with version 1.4.2 and 1.4.3 I cannot (nor with the current 1.8.15 version).
The only thing I can think of regarding the message from 2005-05-19 22:08:10 +0000, Michael S. Scherotter is that there is a typo in the file name (in the original problem report the file name was `objectModel.jpeg` and in the mentioned comment `objectModel.jpg` so without `e`).

I think the problem has been solved in the mean time.
