### ISSUE TITLE
Support for D-style "extern" (Origin: bugzilla #170234)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1498]
status NEW severity *enhancement* in component *build* for *---*
Reported in version *1.5.3-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-03-13 21:05:57 +0000, Anders F BjÃ¶rklund wrote:

    In D, an "extern" can prefix a declaration like so:
    
        extern (C) char *strerror (int);
        extern (C) int strlen (char *);
        extern (C) int getErrno ();
    
    Otherwise it gets D (mangled) name, when linking.
    
    It also supports the "extern(C) { ... }" block style like C++.
    Other linking modes are extern(Windows), extern(Pascal), etc.
    
    
    In current Doxygen, the "C" shows up in the end documentation:
    
    C char* strerror  	(   	int   	  	 ) 
    C int strlen  	(   	char *   	  	 ) 
    C int getErrno  	(   	  	 ) 
    
    It should probably just be ignored instead, or shown differently ?

On 2005-09-22 13:06:56 +0000, Stewart Gordon wrote:

    It should support align and pragma in the same way.  See also bug 300164.
    But
    since that goes into more detail, maybe this should be a duplicate of that?

On 2007-10-15 19:40:43 +0000, Dimitri van Heesch wrote:

    This bug's version was set to "latest". Since this is a moving target, I
    changed it to 1.5.3-SVN. If you believe this has already been fixed, then
    please change the status accordingly.

**Comment by albert-github** [comment]
Issue " Doxygen doesn't recognise D keywords 'extern', 'align' and 'pragma' (Origin: bugzilla 300164)" #1563 signals some pmore missing keywords.
Setting this one to duplicate
