### ISSUE TITLE
Scope not stripped from members in todo lists (Origin: bugzilla #171970)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1524]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-03-29 12:23:37 +0000, Luigi Ballabio wrote:

    Version details: 1.4.2
    
    When a class member is included in a todo/bug/test list and HIDE_SCOPE_NAMES
    is
    set, the scope is not stripped from the corresponding entry in the list.
    The following (somewhat ugly) patch fixes the output.
    
    diff -r -C 3 doxygen-1.4.2/src/memberdef.cpp
    doxygen-1.4.2-patched/src/memberdef.cpp
    *** doxygen-1.4.2/src/memberdef.cpp     Sun Mar 13 18:41:25 2005
    --- doxygen-1.4.2-patched/src/memberdef.cpp     Tue Mar 29 12:30:27 2005
    ***************
    *** 2099,2109 ****
        {
          if (Config_getBool("OPTIMIZE_OUTPUT_JAVA"))
          {
    !       memName.prepend(pd->name()+".");
          }
          else
          {
    !       memName.prepend(pd->name()+"::");
          }
        }
        if (xrefListItems())
    --- 2099,2115 ----
        {
          if (Config_getBool("OPTIMIZE_OUTPUT_JAVA"))
          {
    !       if (!Config_getBool("HIDE_SCOPE_NAMES"))
    !         memName.prepend(pd->name()+".");
    !       else
    !         memName.prepend(getClassDef()->displayName()+".");
          }
          else
          {
    !       if (!Config_getBool("HIDE_SCOPE_NAMES"))
    !         memName.prepend(pd->name()+"::");
    !       else
    !         memName.prepend(getClassDef()->displayName()+"::");
          }
        }
        if (xrefListItems())

On 2005-04-10 13:09:47 +0000, Dimitri van Heesch wrote:

    If I remember correctly the scope was explicitly *not* stripped in this
    case,
    because otherwise the same name could appear multiple times in the todo list
    (think of a field name that appears in multiple structs for instance).
    

On 2005-04-11 07:10:14 +0000, Luigi Ballabio wrote:

    My apologies---I should have made myself more clear.
    It is true that, in order to prevent ambiguities, the class name should be
    left
    in the output.
    But the current implementation adds the whole scope, including
    namespaces---which should be stripped by HIDE_SCOPE_NAMES, as for classes.
    Right
    now an input file such as:
    
    namespace Foo {
    
        /*! a class
            \todo Do this */
        class Bar {};
    
        //! another class
        class Baz {
          public:
            /*! \todo do that */
            void quux();
        };
    
    }
    
    causes Doxygen to output a todo list like:
    
     Class Bar
              Do this
    
     Member Foo::Baz::quux ()
              do that
    
    which uses inconsistent stripping (the latter should be Baz::quux())
    
    Thanks,
        Luigi

**Comment by albert-github** [comment]
I checked with version 1.4.2 and saw the output as shown in the more explicit comment.
With version 1.8.14 the output is:

>  Class Bar
>           Do this
> 
>  Member Baz::quux ()
>           do that

This is as described wanted, so I think the problem has been solved in the mean time.
