### ISSUE TITLE
An enum obscures ObjC documentation (Origin: bugzilla #172048)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1526]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.3-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-03-30 00:11:45 +0000, Scott Lindsey wrote:

    Please describe the problem:
    The existence of an enum causes doxygen comments to be
    obscured/skipped/ignored.
    EXTRACT_LOCAL_METHODS  = YES
    EXTRACT_ALL            = YES
    
    Steps to reproduce:
    Process the sample ObjC source below, as a .m file, with
    EXTRACT_LOCAL_METHODS=YES and
    EXTRACT_ALL = YES
    
    enum { firstThing = 0, secondThing, thirdThing };
    
    //!
    //! My class description
    
    @interface MyClass
    {
    	int x;  //!< this is X
    }
    
    - (id) init;
    
    @end
    
    @implementation MyClass
    
    //! Initialize things
    - (id) init
    {
    }
    @end
    
    
    Actual results:
    Just the ObjC message [MyClass init] is documented.
    
    Expected results:
    Expected that the class description and member variables be documented as
    well.
    
    Does this happen every time?
    Yes.
    
    Other information:

On 2007-10-15 19:40:45 +0000, Dimitri van Heesch wrote:

    This bug's version was set to "latest". Since this is a moving target, I
    changed it to 1.5.3-SVN. If you believe this has already been fixed, then
    please change the status accordingly.

**Comment by albert-github** [comment]
I can see that in version 1.4.2 (the current version at the moment of writing the issue) not all information was present.
With the current version (1.9.1) I think all information is present.

I think the problem has been solved in the mean time.
