### ISSUE TITLE
Todo stops at first sentence. (Origin: bugzilla #172256)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1535]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[example.taz](https://sourceforge.net/projects/doxygen/files/attachments/bug172256_253049_example.taz/download/download)_ (ID 253049)

On 2005-03-31 14:07:40 +0000, David Parsons wrote:

    Version details: 1.4.2
    Distribution/Version: XP SP2
    
    Documentation says 
    
    \todo { paragraph describing what is to be done }
    
    but V1.4.2 with JAVADOC_AUTOBRIEF on writes only the first sentence as part
    of
    the todo list and treats the rest as a separate comment in the general class
    description. It omits it entirely on the Todo list page. V1.3.9 behaved as 
    documented - always included the full paragraph.
    
    Example
    /// @todo Item1. More text.
    /// @todo Item2. More text 2.
    class ...
    
    Produces (in class description)
    Todo: Item1.
    
          Item2.
    
    More text. More text 2. [In the same paragraph.]

On 2005-06-17 11:44:37 +0000, Martin Krogmann wrote:

    I have a similar bug. When I have two Doxygen comments for one function, for
    example one long comment in the header file and a @todo in the source file,
    then
    only the first sentence of the long comment is printed in the header file
    documentation. This bug also occures if I remove the @todo flag and put
    another
    normal /** hallo welt */ comment in the source file within the function.

On 2013-08-25 08:48:27 +0000, albert wrote:

    Created attachment 253049
    example of second reported problem
    
    I tested the original problem with version 1.4.2 and could reproduce the the
    problem. With version 1.3.9 it was not present. It depends on
    JAVADOC_AUTOBRIEF = YES.
    In version 1.8.5 it is not present either.
    
    I think this problem has been solved in the mean time
    
    
    The second problem as submitted by Martin Krogmann is in my opinion in 1.8.5
    still present. It is independent of the setting of JAVADOC_AUTOBRIEF.
    When we look in the attached example th the results for cc / tst_c we see
    that the detailed description is completely gone. When looking at bb /tst we
    see that the information is present.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #8671

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.2.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
