### ISSUE TITLE
Accesses my floppy drive when using INPUT_FILTER (Origin: bugzilla #172786)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1550]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-04-06 10:47:16 +0000, Stewart Gordon wrote:

    Version details: 1.4.2
    Distribution/Version: 98SE
    
    If I am using an INPUT_FILTER, Doxygen accesses my floppy drive while
    reading
    each code file, for no apparent reason at all.
    
    
    Steps to reproduce:
    1. Set an INPUT_FILTER
    2. Have no disk in the floppy drive (I haven't tried it with one in)
    3. Run Doxygen
    
    
    Actual results:
    My floppy drive springs into action as Doxygen is parsing each input file,
    even
    though my project doesn't depend on files on a floppy in any way, shape or
    form.
     No error is reported, but it wastes time, and I'm scared my floppy drive is
    going to wear out one of these days!
    
    
    Expected results:
    Left my floppy drive alone.
    
    
    Does this happen every time?
    Yes

On 2005-04-09 13:55:40 +0000, Dimitri van Heesch wrote:

    Doxygen is unaware of floppy drives so it will not access them unless you
    explicily tell it to do so. So this must be the filter you use that is
    causing
    this. I assume this *only* happens when using the input filter, right?

On 2005-04-12 09:46:39 +0000, Stewart Gordon wrote:

    Please see bug 172782 comment 2.  The same testcase reproduces this bug as
    well.
    
    > So this must be the filter you use that is causing this.
    
    I have the source of the filter program, and there's nothing telling it to
    access the floppy drive.  And indeed, it doesn't mess with my floppy drive
    when
    I run the filter directly from the command line.
    
    > I assume this *only* happens when using the input filter, right?
    
    Yes.

On 2005-04-16 12:02:20 +0000, Dimitri van Heesch wrote:

    I need to be able to reproduce this problem in order to be able to fix, so
    if
    you can send or attach an example that has this behaviour (so including the
    filter source) I'll take a look. Otherwise I stick with my conclusion that
    it is
    a bug in the filter.

On 2005-04-18 11:13:16 +0000, Stewart Gordon wrote:

    Since I'm using the same projects and testcases to reproduce both this and
    bug
    172782, I'm keeping the attachments that apply to both these bugs in one
    place.
     Please see that bug for both the doxyfile and the filter source.

On 2005-04-19 09:12:24 +0000, Stewart Gordon wrote:

    I noticed another oddity: If I replace the backslashes with forwardslashes
    in
    the INPUT_FILTER value, then my floppy drive only makes noises once (when it
    starts to process the source) for my small test project, and twice for my
    real
    project of 20-odd files.  However, when this is done, Doxygen ends up
    processing
    _empty_ source files.  There didn't seem to be a "Bad command or file name"
    or
    similar error.
    
    Doxygen (or Doxywizard?) can't seem to make up its mind which path separator
    to
    use.  But I haven't as yet had time to investigate it in detail.

On 2005-04-20 20:06:34 +0000, Dimitri van Heesch wrote:

    I assume that the following is used for reading the input file into a
    string:
    
    data = cast(char[]) read(args[1]);
    
    if so then my guess is that this statement alone (int the body of a main
    function) will also trigger the problem. Can you verify this? If this is the
    case then something is wrong with the read() function. Your observation with
    the
    back/forward slashes strengthens my believe that this indeed the source of
    the
    problem. You could also print the value of args[1] to see what doxygen
    passes to
    the filter.

On 2005-04-25 09:12:01 +0000, Stewart Gordon wrote:

    I've done some more testing.  Doxygen is indeed passing the file path with
    forward slashes to the filter, but these all make no difference at all:
    
    - adding a search/replace call to the filter to change them into backslashes
    - using a filter that merely reads the file and does nothing with it
    - using a plain main(){} as the filter, whether in D or C
    - specifying the full path or just the name of the INPUT_FILTER
    - having all the files on C: or D: drive
    
    So obviously the problem is in Doxygen or in the method by which it invokes
    the
    filter.  Moreover, couldn't you have done half of this testing yourself?
    

On 2005-04-25 21:44:44 +0000, Dimitri van Heesch wrote:

    I've tried your example on a WinXP machine with a floppy drive. No accessing
    of
    the drive was visible/audible during a run of doxygen with or without floppy
    in
    the drive. Of course it could still be a Win98 only issue (but I do not run
    Win98 anymore), or it could be that something is intercepting file I/O on
    your
    machine (a virus scanner, virus, adware/malware for instance) and then also
    accessing the floppy drive. Are you sure you are running this on a clean
    machine? and does this also happen on Win2000 or later?

On 2005-05-05 13:57:29 +0000, Stewart Gordon wrote:

    I've discussed this over on the D newsgroup, and the answer we've come up
    with
    is that it's a bug affecting more than one brand of antivirus software.  On
    my
    machine, it correlates with the 'Scan floppies on' 'Access' option in
    McAfee.
    
    I've reduced the problem using minimal test programs to the use of popen and
    pclose.  The bug doesn't manifest if the Windows CreateProcess API is used
    instead.  When/if I manage to get the Doxygen sources to compile on my
    system
    (and if someone doesn't get there first), I'll see what I can do here.

**Comment by albert-github** [comment]
No recent information provided (and floppy drives are not really in use anymore ...).
There have not been further reports of this or similar problems.
