### ISSUE TITLE
Tag-files do not store group memberships (Origin: bugzilla #172964)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1556]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-04-07 15:13:37 +0000, necker@ikr.uni-stuttgart.de wrote:

    Please describe the problem:
    If the documentation of a project is included via a tag-file, the group
    membership of class members is lost. For example, if I have two projects,
    and in
    one project I derive a class from another class in the other project, all
    non-redefined methods of the base-class will appear flat before the new
    grouped
    methods of my derived class, which looks kind of awkqard and is difficult to
    read. Therefore, I suggest that group membership information should be
    stored
    along in tag-files.
    
    Steps to reproduce:
    
    
    Actual results:
    
    
    Expected results:
    
    
    Does this happen every time?
    
    
    Other information:

**Comment by albert-github** [comment]
It is a bit unclear what is meant with " but in the 1.4.x version we see above "Public Member Functions" the link "List of all members."all non-redefined methods of the base-class will appear flat before the new grouped methods of my derived class" which redirects to a page with "This is the complete list of members for [cls_p2](file:///D:/speeltuin/bug_172964/p2/html/classcls__p2.html), including all inherited members.".

In the current 1.9.3 (c0b9eafbfb53286ce31e75e2b6c976ee4d345473) version we see:

![image](https://user-images.githubusercontent.com/5223533/161590526-5399b1b5-5945-4f0e-9a6c-3a1dc2c77d03.png)

I.e. the inherited members under (I expanded already) headings with "Public Member Functions inherited from ..."

I think the problem has been solved in the mean time.

Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/8411533/example.tar.gz)
