### ISSUE TITLE
anonymous enums on class page provide a line number link that is invalid. (Origin: bugzilla #303620)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1609]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-05-10 01:51:55 +0000, Pamela Duffy wrote:

    Our C++ code has anonymous enums in it.
    The class pages contain "anonymous enum", the enumeration values and a link
    to
    the correct line number in the source hpp file.  In the source hpp file, the
    line number is not a link.
    
    This was tested with the doxgyen 1.4.2 stable release.
    I could not test it with the latest cvs version due to our version of flex -
    sorry.
    
    This is possibly related to 168159 but as it referred to enums but not
    anonymous
    enums I thought it was worth entering in.

On 2007-04-26 05:13:16 +0000, Denis wrote:

    I have a similar problem with the following code snippet...
    struct
    {
    	enum
    	{
    		SI_SPI_CPHA		= 0x01U,
    		SI_SPI_CPOL		= 0x02U,
    		SI_SPI_MSTR		= 0x04U,
    		SI_SPI_SPE		= 0x08U,
    		SI_SPI_ISS		= 0x10U,
    		SI_SPI_ASS		= 0x20U,
    	}  control;
    	enum
    	{
    		SI_SPI_SPIF	= 0x80U,
    		SI_SPI_WCOL	= 0x40U,
    		SI_SPI_BUSY	= 0x20U,
    		SI_SPI_MODF	= 0x10U,
    		SI_SPI_OVFL	= 0x08U
    	} status;
    } spi;
    which appears in doxygen output as:
    struct {
    	enum  	{
    	  SI_SPI_CPHA = 0x01U,
    	  SI_SPI_CPOL = 0x02U,
    	  SI_SPI_MSTR = 0x04U,
    	  SI_SPI_SPE = 0x08U,
    	  SI_SPI_ISS = 0x10U,
    	  SI_SPI_ASS = 0x20U
    	}
    	enum  	{
    	  SI_SPI_SPIF = 0x80U,
    	  SI_SPI_WCOL = 0x40U,
    	  SI_SPI_BUSY = 0x20U,
    	  SI_SPI_MODF = 0x10U,
    	  SI_SPI_OVFL = 0x08U
    	}
       enum io_type:: { ... } ::@77   control
       enum io_type:: { ... } ::@78   status
    } spi;
    
    ... which is quite confusing 

On 2007-04-26 05:15:48 +0000, Denis wrote:

    I forgot to mention that I am using version 1.5.1

**Comment by albert-github** [comment]
Regarding the first issue, is hard to reproduce as it is missing an example, but in the example I created I don't see a link on the line number for the enum values with version 1.4.2  but with version 1.9.1 these links are present.

Regarding the second issue, with version 1.5.1 I get the similar output as OP (just not the io_type) with version 1.9.1. these lines are gone and the enums have a name (control and status).

I think the problem has been solved in the mean time.
