### ISSUE TITLE
Conflict between TAGFILES and @page (Origin: bugzilla #304062)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1616]
status NEEDINFO severity *normal* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doc.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug304062_46606_doc.zip/download/download)_ (ID 46606)

On 2005-05-13 14:08:15 +0000, Christian Arnault wrote:

    Version details: 1.4.1
    Distribution/Version: Scientific Linux CERN Release 3.0.4 (SL)
    
    When the TAGFILES is not empty the @page construct generates nothing, and in
    particular the "Related pages" top menu item is not generated at all.
    
    Commenting out the TAGFILES= line in Doxyfile is enough to reactivate the
    production of the "Related pages" top menu item.

On 2005-05-17 20:14:57 +0000, Dimitri van Heesch wrote:

    I fail to see the connection. Please try the latest version, and if the
    problem
    persists, attach a self-contain example (i.e. source file + config file in a
    zip) so I can reproduce the problem myself.

On 2005-05-18 13:55:00 +0000, Christian Arnault wrote:

    Created attachment 46606
    Standalone example showing the problem

On 2005-05-18 14:10:20 +0000, Christian Arnault wrote:

    
    Ok I have built a little demo and standalone stuff which - I think -
    reproduces
    the problem. However I have not tested it yet against the most recent
    doxygen
    version. It's still against 1.4.1
    
    In the doc.zip I have:
    
    Doxyfile
    mainpage
    A.tag
    A.txt
    
    The FILE_PATTERNS statement gets all *.txt files:
    
    FILE_PATTERNS          = *.cxx *.h *.py *.xml *.mk *.txt
    
    A.txt contains a @page keyword:
    
    /** @page used Used Packages
    */
    
    
    
    In Doxyfile I have a TAGFILES statement
    
    TAGFILES =   A.tag
    
    when I comment out this statement the "Related pages" item appears on the
    main page.
    
    when it's there the "Related pages" item disappears
    
    
    
    

On 2006-09-29 17:40:30 +0000, AndrÃ© Klapper wrote:

    reopening as requested information has been provided.
    christian, do you still face this issue?

On 2014-02-03 00:17:43 +0000, Bryan Clingman wrote:

    I can confirm this behavior.  Is there a known workaround?

On 2014-04-20 08:21:40 +0000, Dimitri van Heesch wrote:

    Hi Bryan,
    
    I couldn't reproduce the above problem anymore (with version 1.8.6). The
    related page just appeared fine.
    
    So if you see a similar issues with version 1.8.6 please attach a self-
    contained example.

**Comment by albert-github** [comment]
I just did some tests with 1.4.1. and 1.9.1.
With 1.4.1 I saw the indicated behavior and with version 1.9.1 everything looked OK to me (as reported also for version 1.8.6).

I think the problem has been solved in the mean time.
