### ISSUE TITLE
Input filter problem (Origin: bugzilla #304384)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1621]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-05-16 17:27:54 +0000, Stefan Hoops wrote:

    The following input filter stopped working:
    INPUT_FILTER           = "grep -v '@dia:'"
    
    This was working up to 1.3.7 and broke after update to 1.4.3. The problem
    seems
    to be the new quoting mechanism, which interprets the above as the program
    "grep
    -v '@dia:'", which of course is not found. Instead it should interpret it as
    the
    program grep with the arguments -v, '@dia:'. The new mechanism prevents
    parsing
    arguments to the filter program.

On 2005-05-19 08:25:00 +0000, ruediger haertel wrote:

    This problem does not exist in 1.4.2. A code change in src/pre.cpp (version
    1.4.3) has created this behaviour. The lines in pre.cpp are 1964 and 5887.
    The
    buggy code is still in CVS (19-05-05).
    
    However this change was not done in src/util.cpp which also read the value
    of
    INPUT_FILTER

On 2006-05-16 15:10:09 +0000, Frieder Ferlemann wrote:

    The bug seems to still exist in 1.4.6.
    
    I had been using indent as input filter to get
    consistent formatting on the source code.
    
    INPUT_FILTER           = indent -o -
    
    Unfortunately this doesn't work any more (and cannot
    be persuaded to work with any combination of '"' or '\' I tried)
    
    Without the input filter the generated documentation is 
    not of much use to me: Quite a few source code lines 
    are too long (sigh) and extend beyond the right 
    margin and are thus partially lost.

On 2006-05-16 15:22:54 +0000, Stefan Hoops wrote:

    Hello Frieder,
    
    A possible workaround is to create a shell script "doxygen_filter"
    which contains just the following line:
    indent -o - $@
    
    Stefan

On 2006-05-16 15:57:55 +0000, Frieder Ferlemann wrote:

    Thanks Stefan,
    I gave it a try but unfortunately doxygen seems to wait endlessly for the
    output.
    The command shows up in the process list as:
    
    31282  0.0  0.1   3908  1272 pts/5    S+   17:52   0:00 sh -c ./input_filter
    "/home/job/t/Software/src/auswert.c"
    31283  0.0  0.0   1556   620 pts/5    S+   17:52   0:00 indent -o -
    /home/job/t/Software/src/auswert.c
    
    (shell is GNU bash, version 3.00.16(1))
    
    Greetings,
    Frieder

On 2006-05-16 16:18:06 +0000, Stefan Hoops wrote:

    Hello Frieder,
    
    My fault the last option '-' instructs indent to expect input from stdin
    instead from a file, i.e., it waits forever.
    
    So please try,
      indent -st $@
    or 
      cat $@ | indent -o -
    
    Stefan

On 2006-05-16 17:15:26 +0000, Frieder Ferlemann wrote:

    Hello Stefan,
    thanks a lot, both variants you provided are working workarounds:)

**Comment by albert-github** [comment]
The original problem was a problem with the 1.4.3. version of doxygen and has been solved in the 1.4.4. version (and is still working for the current 1.9.3 (c0b9eafbfb53286ce31e75e2b6c976ee4d345473) version.

The problem with the `indent` program is a problem as indicated in the last comment as indicated by Stefan Hoops, an incorrect usage of the indent program.

I think the original problem has been solved in the mean time.
