### ISSUE TITLE
Volatile declaration is missing for variables in XML output (Origin: bugzilla #305773)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1657]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-05-28 20:28:34 +0000, narechk wrote:

    Volatile declaration is missing for variables (member and non-member) in XML
    output. The <memberdef> tag has attribute volatile="no" although it should
    be
    "yes". The following code reproduces the bug:
    
    /**
     *	A volatile variable bar.
     */
    volatile int bar;

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #8333

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.2.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
