### ISSUE TITLE
Wrong title when \ref refers to external sections (Origin: bugzilla #306025)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1662]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-05-31 11:13:58 +0000, Fabrizio Ferrandi wrote:

    Please describe the problem:
    Let us consider a doxygen documentation for a project that includes the 
    following lines: 
    /*! 
      \mainpage partitioning Subproject 
     
      This subproject is further divided in  
        - Subproject \ref src_codesign_partitioning_graph_partitioning_page  
       
    */ 
     
    and an external documentation with the following doxygen lines: 
    /*! 
      \mainpage graph_partitioning Subproject 
      \section src_codesign_partitioning_graph_partitioning_page Graph Based 
    partitioning 
     
      WIP 
       
    */ 
     
    The HTML produced for the first project creates a link 
    tosrc_codesign_partitioning_graph_partitioning_page 
    instead of Graph Based partitioning. 
    The work around is to add the title to the \ref command but I would prefer
    that
    doxygen computes by itself that title. Moreover by using command \page 
    everything works properly 
     
    Best Regards, 
     
    Fabrizio Ferrandi 
     
    
    Steps to reproduce:
    1. 
    2. 
    3. 
    
    
    Actual results:
    
    
    Expected results:
    
    
    Does this happen every time?
    yes 
    
    Other information:

**Comment by albert-github** [comment]
With the 1.4.3 version I can see the problem as indicated, with the current (1.9.3 (c0b9eafbfb53286ce31e75e2b6c976ee4d345473)) version the text is "Graph Based" as was expected.

I think the problem has been solved in the mean time
