### ISSUE TITLE
Proposal to generate C/C++ header files (Origin: bugzilla #306189)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1669]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-06-01 20:14:35 +0000, Richard J. Mathar wrote:

    Version details: 1.4.3
    
    The code tree produced by doxygen could well be used to generate standard
    C/C++ header files: I am thinking of a functionality similar to cextract,
    with
    the improvment that (i) include files, (ii) cpp definitions class and struct
    definitions, (iii) enumerations, and static (C++) or global (C) variable
    declarations would be created. With a C/C++ source file like
    
     myfile.C
     
      #include <math.h>
      #define MYDEF 33
      class myclass {
           myclass() ;
           myclassdoesth()
           {
             callit() ;
           }
      };
    
    one could automatically generate "myfile.h" by walking through
    the code tree, ignoring all the "brief", "detailed" tags.
    The disadvantage of cextract is that it "outsources" merely the function
    prototypes, whereas the structs, class interfaces etc are usually important
    as well.
    I quickly hacked s.th. like this, parsing the perlmod output:
    http://www.strw.leidenuniv.nl/~mathar/progs/doxygen2hdr .
    This way of producing a "header" output would be very helpful and
    could actually be another "representation" along the currently
    supported perl, latex, html, xml. Since I am not a seasoned perl
    programmer, and would also need a lot of time to get into the structure
    of the doxygen coding, anyone else is invited to step in.

**Comment by albert-github** [comment]
I don't think that this is a task for doxygen.
When something is needed I think it would even be better to use the xml output as a base and process these files (nowadays te xml output is better maintained than the perlmod output).

I think this enhancement issue won't be fixed by doxygen.
