### ISSUE TITLE
Source blocks are grey and empty (Origin: bugzilla #310209)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1729]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-07-13 11:33:22 +0000, John Dubery wrote:

    Please describe the problem:
    Similar to bug 165909: Grey blocks are often empty, but has a different
    cause
    from that described in the comments for that one.
    
    Present whenm viewing output from Doxygen 1.4.3 using either Opera 7.5 or IE
    6 on
    my work winXP machine. No nice colourised, hyperlinked source code is
    visible,
    just a blank grey box of an appropriate size.
    
    Some winXP/IE machines at work display the source code OK; mine doesn't.
    
    On Opera, forcing an alternate style sheet makes the source code visible 
    suggesting a style sheet issue.
    
    I've tracked this to DOXYGEN.CSS ...
    [this causes the problem]
    .fragment {
           font-family: Fixed, monospace;
           font-size: 95%;
    }
    
    [this works fine]
    .fragment {
           font-family: monospace;
           font-size: 95%;
    }
    
    I'm not a CSS expert - the above is definately a hack, but I hope is useful.
    
    cheers
    
    John Dubery
    
    
    Steps to reproduce:
    Present in all output from Doxygen 1.4.3 on my winXP machine.
    
    Actual results:
    It seems to work fine; the output does not display correctly in some
    browsers.
    
    Expected results:
    
    
    Does this happen every time?
    Yes
    
    Other information:

On 2005-10-22 15:55:50 +0000, Bryan T. Vold wrote:

    I think I may have found some new information.  I was experiencing the above
    problem as well.  The problem seems to be that Microsoft installs a font in
    XP
    called "Fixed Meriam Transparent".  It just so happens that it collates in 
    front of "fixedsys", which I assume is the correct font (at least in
    Windows).
    The order matters here - if you change the order from font-family:Fixed, 
    monospace to font-family:monospace,Fixed,   Windows XP will correctly use a 
    monospaced font, and not used the font "Fixed Meriam Transparent" - which
    is,
    well, transparent.  Hope this helps.

On 2005-11-06 18:30:48 +0000, Kevin McBride wrote:

    Running a test compile.

On 2005-11-06 20:02:06 +0000, Kevin McBride wrote:

    No problems here, even though I am using Fedora Core 3.  Will remind Dimitri
    in
    a few days if he doesn't give a new status to this bug report.

**Comment by albert-github** [comment]
Seen the fact that this issue is over 14 years old and that the doxygen HTML handling has been changed considerably since that time as well as there have not been similar issues / I haven't seeen the problem I think w can safely say that the problem has been solved in the mean time.
