### ISSUE TITLE
Module order can be strange (Origin: bugzilla #310491)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1731]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[order-latex-pages.1.4.3.patch](https://sourceforge.net/projects/doxygen/files/attachments/bug310491_49412_order-latex-pages.1.4.3.patch/download/download)_ (ID 49412)

On 2005-07-15 13:31:56 +0000, Michael McTernan wrote:

    When using groups with sub-groupings, the LaTeX output and to some extent
    HTML
    output lists sub-groups in declaration order.  For HTML, this is merely
    inconvenient when there are large numbers of modules, where as for LaTeX it
    causes the page order to be strange.
    
    The following is an example input file:
    
    /** \defgroup SysParts Parts
     * \ingroup Sys
     * Parts of the system.
     *@{
     */
    
    
    /** \defgroup SysPartsC Part C 
     * Part C.
     */
    
    
    /** \defgroup SysPartsB Part B
     * Part B.
     */
    
    /** \defgroup SysPartsA Part A
     * Part A.
     */
    
    
    /** @} */
    
    
    /** \defgroup Sys System
     * This is the entire system.
     */
    
    The module index that is generated is as follows:
    
    Here is a list of all modules:
    System . . . . . . . . . . . . . . . . . . . . . . 7
      Parts  . . . . . . . . . . . . . . . . . . . . . 3
        Part C . . . . . . . . . . . . . . . . . . . . 4
        Part B . . . . . . . . . . . . . . . . . . . . 5
        Part A . . . . . . . . . . . . . . . . . . . . 6
    
    It would be better if this could be alphabetically sorted, and if the
    documentation for 'System' were to be on an earlier page than its sub-
    sections -
    right now it is in declaration order at the bottom of the document!

On 2005-07-19 18:10:12 +0000, Michael McTernan wrote:

    Created attachment 49412
    Patch to fix issue by ordering \includes for modules such that page order is
    dictated by group heirachy
    
    This patch is based on Doxygen 1.4.3.  It changes the LaTeX generator to
    sort
    the order of the \include commands such that pages are ordered according to
    the
    group heirachy.  The sort uses a recursive function to do supply the desired
    ordering of includes at each level of the index.  Groups are ordered by the
    first group in which they appear, such that a group with multiple parents is
    sorted by the first location in the index.
    
    Apply patch like this:
    
    $ tar -xzf doxygen.1.4.3
    $ patch -bl -p1 < order-latex-pages.1.4.3.patch
    patching file src/groupdef.h
    patching file src/latexgen.cpp
    patching file src/latexgen.h
    $

**Comment by albert-github** [comment]
With the doxygen 1.4.3 version we see:
**HTML**
![image](https://github.com/doxygen/doxygen/assets/5223533/313c3c8e-5a0d-45e7-9d2e-a65f601e0491)

**LaTeX**
![image](https://github.com/doxygen/doxygen/assets/5223533/b347ed9a-a4fc-479e-b4d9-8dba11889789)


With the current doxygen version (1.9.8) we see:
**HTML**
![image](https://github.com/doxygen/doxygen/assets/5223533/187ebe8e-b555-4630-8edc-748bf546dbfd)


**LaTeX**
![image](https://github.com/doxygen/doxygen/assets/5223533/99cba21f-bc5d-4c0a-bff3-df3d0dd87df4)


So some improvement regarding the nesting of the groups.

Sin doxygen version 1.5.5 the setting `SORT_GROUP_NAMES` exists and results in:
**HTML**
![image](https://github.com/doxygen/doxygen/assets/5223533/b67a3c4c-f19f-4fb7-b19d-aa3b6d9e86ea)

**LateX**
![image](https://github.com/doxygen/doxygen/assets/5223533/1b58ddc1-e126-40e5-addd-82cd7e6990e1)


So also the groups are sorted now.

The provided patch only handled LaTeX, but with the setting `SORT_GROUP_NAMES` all output formats are handled.

I think the problem has been solved in the mean time
