### ISSUE TITLE
Cannot document non-existant defines with \def (Origin: bugzilla #310895)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1735]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doc-missing-def.1.4.3.patch](https://sourceforge.net/projects/doxygen/files/attachments/bug310895_49415_doc-missing-def.1.4.3.patch/download/download)_ (ID 49415)

On 2005-07-19 17:11:04 +0000, Michael McTernan wrote:

    The following input file will not produce output, but will create a warning:
    
     /** \def ENABLE_NEW_FUNC
      * This define enables some new functionality that maybe
      * desired by some people.
      * \warn This is not fully tested, so not a default option.
      */
     /* #define ENABLE_NEW_FUNC */
    
    Because the actual define does not exist, a warning is produced:
    
     example.c:43: Warning: documentation for unknown define ENABLE_NEW_FUNC
    found.
    
    This is okay, but it would be desirable to define the switch as though it
    existed.  Unfortunately there seems to be no simple way to do this without
    using
    and extra switch and some hidious construct such as the following:
    
    #if defined(DOXYGEN_COMPILING)
    # ifndef ENABLE_NEW_FUNC
    #  define ENABLE_NEW_FUNC
    #  undef  ENABLE_NEW_FUNC
    # else
    #  undef  ENABLE_NEW_FUNC  
    #  define ENABLE_NEW_FUNC
    # endif
    #endif
    
    As an enhancement request, it would be nice if Doxygen still produced
    documentation for the \def.

On 2005-07-19 18:32:54 +0000, Michael McTernan wrote:

    Created attachment 49415
    Patch to document missing defines if \def explicitly set
    
    Attached is a patch.
    
    This essentially causes Doxygen to behave as is the define was defined at
    the
    point where the \def command was found.  The warning is additionally still
    produced.

**Comment by albert-github** [comment]
I think that implicitly defining a `#define` would be against the philosophy  of doxygen and should not be done.
Doxygen always tries to link the documentation to an entity and here there s on entity so there should not be documentation either. 

I think this would be in the category won't fix.
