### ISSUE TITLE
Opened namespaces are not considered when matching class member definitions with their declaration (Origin: bugzilla #310967)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1737]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-07-20 09:36:27 +0000, Mads Kiilerich wrote:

    Version details: 1.4.3
    
    Running doxygen 1.4.3 on:
    
     #include<string>
     struct foo {
      void m2(std::string arg);
     };
     using namespace std;
     void foo::m2(string arg) {}
     main(){}
    
    warns:
    
    Computing class relations...
    /data/mk/foo.cpp:3: Warning: Compound foo is not documented.
    Searching for enumerations...
    Searching for member function documentation...
    /data/mk/foo.cpp:9: Warning: no matching class member found for
      void foo::m2(string arg)
    Possible candidates:
      void foo::m2(std::string arg)
    
    If std:: is used in the definition no warning is given. Rewriting the code
    to
    not use opened namespaces is however not an option.

On 2005-07-21 10:15:51 +0000, Dimitri van Heesch wrote:

    The problem and solution are related the question 15 of the FAQ (see
    http://www.doxygen.org/faq.html). One of the things on my todo list is to
    add
    STL support to doxygen.

On 2005-07-21 14:44:38 +0000, Mads Kiilerich wrote:

    I see, thanks.
    
    I understood the FAQ entry as if STL internals not was known by Doxygen. But
    obviously my problem is that the standard library isn't known by Doxygen at
    all.
    
    Using a tagfile as mentioned on
    http://gcc.gnu.org/onlinedocs/libstdc++/libstdc++-html-USERS-3.4/index.html
    seems to do it for me. Perhaps such a tag file is a solution to your request
    for
    a dummy STL file... A hint about that in the FAQ would have helped me ;-)

**Comment by albert-github** [comment]
With the 1.4.3 version we get the warnings about no matching class member found foras indicated, with the 1.9.5 version these warnings are gone.

I think the problem has been solved in the mean time.

Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/10098538/example.tar.gz)
