### ISSUE TITLE
If a variable is defined after try/catch, it can not produce "referenced by" infomation (Origin: bugzilla #313298)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1769]
status REOPENED severity *normal* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-08-12 07:46:24 +0000, arw_tw@yahoo.com.tw wrote:

    Version details: 1.4.4 and 1.4.4-20050806 CVS
    Distribution/Version: XP
    
    Doxyfile:
    
      EXTRACT_ALL = YES
      SOURCE_BROWSER = YES
    
    x.cpp:
    
    #include <stdio.h>
    #include <exception>
    void throw_fun()
    try
    {
    }
    catch(std::exception &e)
    {
      const char *str = e.what();
    }
    int var;
    void ref_fun()
    {
      var = 10;
    }
    
    in HTML output, File members -> var, the output is:
    
     Variable Documentation
     int var
     Definition at line 11 of file x.cpp.
    
    The infomation "referenced by ref_fun()" is missing.
    
    But, if we comment throw_fun, like this:
    
    #include <stdio.h>
    #include <exception>
    /*void throw_fun()
    try
    {
    }
    catch(std::exception &e)
    {
      const char *str = e.what();
    }*/
    int var;
    void ref_fun()
    {
      var = 10;
    }
    
    The documentation for var becomes:
    
     Variable Documentation
     int var
     Definition at line 11 of file x.cpp.
     Referenced by ref_fun().
    
    This is the correct output.
    
    Doxygen version is 1.4.4, and 1.4.4-20050806 CVS also has this problem.
    I run it on Windows XP

On 2005-08-12 14:58:47 +0000, Dimitri van Heesch wrote:

    I just found out that is throw_fun() is legal C++ syntax also known as a
    function-try-block. So as you might guess, doxygen's parser doesn't support
    it
    yet ;-)
    
    

On 2005-08-12 16:33:18 +0000, Dimitri van Heesch wrote:

    Correction. Doxygen's input parser does support function-try-blocks (I only
    forgot I already added it), but the code parser (used for source browsing
    and
    cross-referencing) doesn't.

On 2005-08-12 16:57:23 +0000, Dimitri van Heesch wrote:

    Should be fixed in the next CVS update.

On 2005-08-19 14:12:37 +0000, arw_tw@yahoo.com.tw wrote:

    Yes, it is fixed in 1.4.4-20050817 CVS version. But if I change source code 
    like this, remove const char *str = e.what(); and add empty catch(...)
    block:
     
    #include <stdio.h>
    #include <exception>
    void throw_fun()
    try
    {
    }
    catch(std::exception &e)
    {
      //const char *str = e.what();
    }
    catch(...)
    {
    }
    int var;
    void ref_fun()
    {
      var = 10;
    }
     
    The bug appears again. The documenation for var is:
     
     Variable Documentation
     int var
     Definition at line 14 of file x.cpp.
     
    Maybe the parser has some problems when it encounters catch(...) block?
    

On 2005-10-04 18:39:13 +0000, Dimitri van Heesch wrote:

    This bug was resolved to status "FIXED" as part of a group change. Please
    verify
    that this bug is indeed fixed in doxygen version 1.4.5 (or later). If not
    then
    please reopen the bug, so it stays on my radar.

On 2005-10-06 03:20:24 +0000, arw_tw@yahoo.com.tw wrote:

    No, I tested it in Doxygen 1.4.5(Windows version), but this bug still
    exists.
    

On 2005-10-06 03:22:50 +0000, arw_tw@yahoo.com.tw wrote:

    1.4.5 still has this bug, Reopen it.

**Comment by albert-github** [comment]
With the 1.4.5 version the `Referenced by` is missing:

![image](https://user-images.githubusercontent.com/5223533/204140768-a7ab7273-7d16-4f0c-a210-aa37a1f65889.png)

in the 1.9.5 version the information is present:

![image](https://user-images.githubusercontent.com/5223533/204140790-a96feb57-7581-47cc-b399-18cd7ee912c9.png)

(I needed to set
```
REFERENCED_BY_RELATION = YES
REFERENCES_RELATION    = YES
```
as otherwise there would be no `Referenced by` information at all 1.9.5  version, I set it for both versions).


I think the problem has been solved in the mean time.

Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/10098512/example.tar.gz)
