### ISSUE TITLE
Classes within C++ namespaces are not documented correctly (Origin: bugzilla #313777)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1773]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-08-18 01:11:41 +0000, Gordon Paynter wrote:

    Please describe the problem:
    When a \class command is used within a C++ namespace, it is unclear whether
    the
    given class name should be relative to the namespace or relative to the
    global
    namespace.  It turns out that it does not matter which you use, as both are
    handled incorrectly by Doxygen.
    
    Note that this does not appear to be a problem if the class if it is the
    first
    major piece of code declared within the namespace. 
    
    Steps to reproduce:
    1. Create a test file as follows:
    
    ---begin file ---
    /** \file  test.h
     *  \brief Test a problem case I have found running Doxygen over C++.
     */
    
    namespace OuterNamespace {
    
    /** \enum   AnEnum
     *  \brief  An Enumeration used later.
     */
    enum AnEnum {
            VALUE_ONE, //!< The First Value.
            VALUE_TWO  //!< The Second Value.
    };
    
    /** \class  ProblemClass
     *  \brief  A base clase that exhibits a problem.
     *
     *  Doxygen will not show any documentation for this class, but it
     *  will show the class name twice on the "Class List" page.
     */
    class ProblemClass {
            /** The name of a member of the problem class. */
            std::string member_name_;
    }
    
    } // OuterNamespace ends.
    ---end file ---
    
    2. Generate documentation with Doxygen.
    
    
    
    Actual results:
    Doxygen will not generate documentation for the class, only for the
    namespace
    and enum.  It will recognise that the class is there: in fact, the class is
    listed *twice* in the class list.  However, there is no documentation for
    the
    class itself or any of its members.  
    
    If I use "\class OuterNamespace::ProblemClass" in the documentation instead,
    then a different problem occurs: Doxygen generates documentation for a
    non-existant class "OuterNamespace::OuterNamespace::ProblemClass" in
    addition to
    the main class.
    
    If I move the class documentation block anywhere else in the scope of the
    Namespace, the problem persists.  If I move it outside the namespace, the
    problem is solved.
    
    If I eliminate the enum or the namespace then it works as expected.
    
    If I elimiate the "\class" line from the documentation block and leave it
    immediately before the class, then it works as expected.
    
    Expected results:
    I expect the correct documentatrion.
    
    Does this happen every time?
    Yes.
    
    Other information:
    I suspect this is the same problem as in bug 130333 and possibly bugs
    156811,
    151959, 135276 and the other reported C++ class + namespace bugs.

**Comment by albert-github** [comment]
That the class member is missing is logical as this is a private member and most likely the `EXTRACT_PRIVATE` has not been set.

I cannot reproduce the problem with a 1.4.x version but with version 1.9.1 I see all information.

I think the problem has been solved in the mean time.
