### ISSUE TITLE
inline implementation confuses grouping \{ ... \} (Origin: bugzilla #315843)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1802]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-09-09 16:59:10 +0000, Sascha wrote:

    Please describe the problem:
    If there are inline functions like "virtual bool Test1() {return true;};"
    the
    groups are not closed properly.
    
    For "virtual bool Test1() =0;" no problems !
    
    
    Steps to reproduce:
    I have a number > 20 of inline funtions with a default inline implementation
    :
    
    //! \defgroup PBS C
    //! \{
    //! \} close C
    
    
    //! \defgroup PBS1 1
    //! \ingroup PBS
    //! some blah
    //! \note blah           
    //! \{
    virtual bool Test1() {return true;};
    .
    .
    .
    virtual bool Testn() {return true;};
    //! \} close 1
    
    //! \defgroup PBS2 2
    //! \ingroup PBS
    //! some blah
    //! \note blah           
    //! \{
    virtual bool Testx1() {return true;};
    .
    .
    .
    virtual bool Testxn() {return true;};
    //! \} close 2
    
    Actual results:
    I get following structure
    
    C
    |-1
      |-2
    |-2
    
    
    Expected results:
    C
    |-1
    |-2
    
    
    Does this happen every time?
    Yepp
    
    Other information:

On 2006-03-17 14:45:29 +0000, Sascha wrote:

    Retested ... doxygen can not handle :
    In Header / Inline Code :
    Multiple lines with this style in groups :
    
    virtual bool Testx1() {return true;}; //!<I know it is bad style.
    
    The ; at the end generates this problem, without it works fine.
    Doxygen should at least show a warning.
    (The GNU compiler does not)

**Comment by albert-github** [comment]
Regarding the first problem:
with doxygen version 1.4.4 we see:
![image](https://github.com/doxygen/doxygen/assets/5223533/48ac0b15-cb92-4956-b7ad-ac096cddf7b7)

with the current doxygen version (1.9.8) we see:
![image](https://github.com/doxygen/doxygen/assets/5223533/fa616bc2-0901-4b31-810e-2483cc125b87)

I think this problem has been solved in the mean time.

The problem regarding the `;` is a different problem. After the closing `}` the function is completed and a new statement starts (which is empty) and that statement is ended by means of the `;` and the following comment is thus for the the "empty statement" and as there is no statement doxygen has no place to put the documentation.
I think here we have to do with a misinterpretation of what the compiler does and for doxygen this means the second problem is usage.
