### ISSUE TITLE
redundancy in nested groups. (Origin: bugzilla #316171)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1804]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-09-13 10:23:09 +0000, Lamesch wrote:

    Version details: 1.4.4
    Distribution/Version: 2000
    
    Doxygen version: 1.4.4
    System: Win2000
    
    /** \defgroup grp1 group one
    * text1
    
    //@{
      /** \defgroup grp2 group two
      * text2
    
      //@{
        /** \defgroup grp3 group three
        * text3
      //@}
    //@}
    
    produces
    - grp1
      * grp2
        - grp3
      * grp3
    
    Problem did not exit in version 1.3.8

**Comment by albert-github** [comment]
In the description a number of closing comments (`*/`) are missing, when added we see the problem with the 1.4.4 version.

With the current version (1.9.3 (c0b9eafbfb53286ce31e75e2b6c976ee4d345473)) the doubling is gone.
The `\defgroup` are the to level groups by default (ignoring the shown "block" commands), to have the nesting structure one needs the `\ingroup` commands after the `\defgroup` commands.

I think the problem has been solved in the mean time.
