### ISSUE TITLE
Spurious semicolons cause classes to appear in the same group multiple times (Origin: bugzilla #316509)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1810]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.3-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-09-16 19:14:09 +0000, res wrote:

    Create docs for:
    
    /**\addtogroup group
     * @{ */
    
    ; /* comment/uncomment ... */
    
    /// Foo.
    struct Foo
    {
      /// Bar.
      int bar;
    };
    
    /** @} */
    
    The "Foo" class will appear twice in the "group" group (also, in the list of
    groups Foo is in, "group" appears twice as well). Removing the spurious ';'
    gets
    rid of the issue.

**Comment by albert-github** [comment]
With doxygen 1.4.4. I can see the indicated problem, with the current doxygen version (1.9.3 (c0b9eafbfb53286ce31e75e2b6c976ee4d345473)) the problem is gone.

I think the problem has been solved in the mean time.
