### ISSUE TITLE
use package.html in java class directories (Origin: bugzilla #317279)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1819]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-09-26 20:59:19 +0000, alan ezust wrote:

    Even if the .html files are not specified in the 
    INPUT variable, Doxygen should "pick up"
    any package.html file that exists in each source directory,
    and insert it into the documentation for each package.

On 2007-05-14 01:52:50 +0000, John Smart wrote:

    I think this feature would be a valuable addition for Java developers. It
    would allow Javadoc-compatible package documentation at relatively low cost
    to the developer.

On 2014-04-10 12:44:18 +0000, simon.watts@physics.org wrote:

    Since Java 5 - 'package.html' has been deprecated in favor of 'package-
    info.java' for package-level documentation and annotations.
    
    Doxygen processes 'package-info.java' correctly.
    
    For legacy projects, could an input filter be used to convert 'package.html'
    to a 'package-info.java'?

**Comment by albert-github** [comment]
Seen the last comment (and unfortunately the time between the issue / comment) I think the problem is now obsolete and something that doesn't need fixing
