### ISSUE TITLE
Member Groups - C++ Enumerations and Function Names the Same but Output Abnormal (Origin: bugzilla #317446)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1823]
status REOPENED severity *normal* in component *documentation* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-09-28 15:47:45 +0000, Ryan H Kawicki wrote:

    Two member groups: Types and Accessors.
    Types contains documentation not at the source.
    /** @name Types */
    //@{
    /** \enum CText::Alignment
      * \brief Brief
      * Description
      */
    /** \var CText::Alignment CText::LEFT
      * \brief Left
      * Description
      */
    //@}
    
    /** @name Accessors */\
    //@{
    /**
    \brief Returns the alignment.
    \return Alighment value.
    */
    int CTest::Alignment( ) const
    {
      return m_nAlignment;
    }
    //@}
    
    I would expect to see the enumeration in the grouping of 'Types' and the
    function to be in the grouping of 'Accessors', but the function gets moved
    out
    of 'Accessors' and placed into 'Types' and the enumeration is only
    associated to
     the defalut of 'Public Types'.

On 2005-09-28 19:29:06 +0000, Dimitri van Heesch wrote:

    Hi Ryan, can you attach a more complete example (e.g. including the CTest
    class)? Please also mention the version of doxygen you are using (doxygen
    --version from the command box).

On 2005-09-28 20:26:15 +0000, Ryan H Kawicki wrote:

    ---------- In CTest.h ----------
    /**
    \brief A test class
    
    This test class will be used to test member grouping in Doxygen.
    */
    class CTest
    {
    public:
    	// public enumeration
    	enum Alignment
    	{
    		ENUM_1,
    		ENUM_2,
    		NUM_ENUM
    	};
    
    	// returns a number
    	int Alignment( ) const;
    };
    
    ---------- In CTest.cpp ----------
    #include "CTest.h"
    
    /** @name types */
    //@{
    /**
    \enum CTest::Alignment
    \brief Alignment enum.
    
    Alignment enumeration.
    */
    
    /**
    \var CTest::Alignment CTest::ENUM_1
    \brief Enum 1.
    
    Alignment enumeration 1.
    */
    
    /**
    \var CTest::Alignment CTest::ENUM_2
    \brief Enum 2.
    
    Alignment enumeration 2.
    */
    
    /**
    \var CTest::Alignment CTest::NUM_ENUM
    \brief Max Enums.
    
    Maximum alignment enumerations.
    */
    //@}
    
    /** @name Accessors */
    //@{
    int CTest::Alignment( ) const
    {
    	return 0;
    }
    //@}
    
    ---------- Generated In HTML ----------
    Types
        int Alignment( ) const
    
    Public Types
      Accessors
        enum Alignment { ... }
    
    This is wrong.  The function should be in the Accessors and the enumeration
    in
    the Types.
    
    Doxygen version 1.4.4
    Copyright Dimitri van Heesch 1997-2005

On 2005-10-02 14:09:53 +0000, Dimitri van Heesch wrote:

    Confirmed. The problem was due to the use of Alignment as a function *and*
    an
    enum, while documenting the enum using \enum and having both items in a
    member
    group. Should be fixed in the next release.

On 2005-10-04 18:38:41 +0000, Dimitri van Heesch wrote:

    This bug was resolved to status "FIXED" as part of a group change. Please
    verify
    that this bug is indeed fixed in doxygen version 1.4.5 (or later). If not
    then
    please reopen the bug, so it stays on my radar.

On 2005-10-10 16:17:48 +0000, Ryan H Kawicki wrote:

    Using the same test scenario from above, the generated HTML sets the
    enumeration
    correctly but drops the Accessors group completely, so the function that
    would
    be apart of Accessors is not visible.

**Comment by albert-github** [comment]
The fact that the `Alignment()` function is not shown in the 1.4.5 and in the 1.9.5 versions is due to the fact that the function is not documented and this is correct (as no Doxyfile is given we assume a default Doxyfile).
With the 1.4.5  version we don't get a warning but with the 1.9.5. version we do:
```
CTest.h:18: warning: Member Alignment() const (function) of class CTest is not documented.
```

So I think the problem has been solved in the mean time (warning) and further is usage.
