### ISSUE TITLE
Global variable misidentified as a function. (Origin: bugzilla #318058)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1836]
status NEW severity *major* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-10-05 21:45:03 +0000, cruff@ruffspot.net wrote:

    Version details: 1.4.5
    
    When the contents of t.h are directly incorporated in t.cc, the variable is
    correctly documented.
    
    /*!
     *@file t.h
     *
     *@brief Make the bugs surface.
     */
    
    #include <string>
    
    /*!
     *@brief Cause a variable declaration to look similar to a function
    declaration.
     */
    template <typename T>
    class A
    {
    public:
            /*!
             *@brief Constructor.
             */
            A(const std::string& n, T v);
    };
    
    typedef A<std::string>  AType;
    
    /*!
     *@file t.cc
     *
     *@brief Make the bugs surface.
     */
    
    #include "t.h"
    
    /*!
     *@brief Document a_variable.
     */
    AType   a_variable("name", "value");

**Comment by albert-github** [comment]
In the 1.4.5 version we see in the splitted version:
![image](https://user-images.githubusercontent.com/5223533/146361828-66ff3ca0-50be-4ded-b164-5a3d2d63b5e0.png)

and in the combined version:
![image](https://user-images.githubusercontent.com/5223533/146361970-8d91a120-8d46-4919-bca5-44ffca9352f1.png)


In the 1.9.2 version we see in both cases:
![image](https://user-images.githubusercontent.com/5223533/146362482-aec6457b-70b3-47f7-9df2-672b7dc737b1.png)


So I think the problem with `t.h` saying `a_variable` is a function has been solved in the mean time
