### ISSUE TITLE
Similar image file names not found (Origin: bugzilla #318118)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1839]
status NEEDINFO severity *normal* in component *build* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-10-06 14:07:54 +0000, Larry Waibel wrote:

    Distribution/Version: XP
    
    In v1.4.4 on Windows XP NTFS file system: create an image such as 
    xyz_123.gif.  Then create another as xyz_123.jpg.  Using a '\image' command,
    Doxygen will find the first image if given that name but will report that it
    can't find it in the IMAGE_PATH if given the second name.

On 2014-05-26 18:52:44 +0000, albert wrote:

    I've not been able to reproduce this problem on my Windows 7 system with a
    standard Doxyfile with the IMAGE_PATH set to the directory wheer the images
    resided
    I created a page with a gif and a jpg image for html as well as for latex.
    
    Please check if the problem still occurs with the current version of doxygen
    
    If you still see this issue with the latest version of doxygen please add a
    self-contained example (source+config file in a zip or tar).

**Comment by albert-github** [comment]
Seen the period of no response and the fact that with the supplied information the problem is not reproducible I think the problem should be closed as 'invalid' i.e. 'not complete or not reproducible'
