### ISSUE TITLE
Brief descriptions detailed in Classes/Data Structures while BRIEF_MEMBER_DESC = NO (Origin: bugzilla #318119)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1840]
status NEW severity *normal* in component *build* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-10-06 14:10:19 +0000, Stephane Drouard wrote:

    Version details: 1.4.5
    
    With this code:
    
    /**
     * @defgroup Test Test
     * @{
     */
    
    /**
     * @brief A structure.
     *
     * Details...
     */
    struct dummy {
      int dummy;
    };
    
    /**
     * @brief A function.
     *
     * Details...
     */
    void test(void)
    {
    }
    /** @} */
    
    Doxyfile: BRIEF_MEMBER_DESC = NO
    
    Result: in the Test module page, the function's brief description is not 
    written (correct), while the structure brief description is (wrong).
    
    Regards

**Comment by albert-github** [comment]
With the 1.4.5 version we get a warning:
```
aa.c:12: Warning: Member dummy of class dummy is not documented.
```

and we see:

![image](https://user-images.githubusercontent.com/5223533/204138824-a4ab59d4-6e15-49e3-a6bb-79b97eb1c360.png)

With the 1.9.5. version the warning is gone and we see:

![image](https://user-images.githubusercontent.com/5223533/204138856-6c80943f-16de-4125-b1bb-cce51ab4d392.png)


So in the 1.9.5 version the brief description is gone as was expected.

I think the problem has been solved in the mean time.
