### ISSUE TITLE
Incorrect main page & links (Origin: bugzilla #318502)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1848]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.5.3-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-10-10 20:00:27 +0000, Adrian Sheard wrote:

    Please describe the problem:
    Using 2 (or 1 when trying to diagnose problem) external chm files (built
    with
    doxygen) & their tag files my project's main page is always the last
    included
    tag file's main page - The .html output is fine and all pages/links are
    good,
    the problem only occurs when compiling to chm!
    
    Steps to reproduce:
    1. Generate a chm file & tag file from a (simple) project
    2. Generate another project that includes tags from first project
    3. Build to chm !
    
    
    Actual results:
    Incorrect main page (i.e. of included project) displayed
    
    Expected results:
    Correct main page (i.e. of outer project) displayes
    
    Does this happen every time?
    Yes
    
    Other information:
    Brilliant application - has saved me loads of time (up until this little
    issue)

On 2007-10-15 19:40:48 +0000, Dimitri van Heesch wrote:

    This bug's version was set to "latest". Since this is a moving target, I
    changed it to 1.5.3-SVN. If you believe this has already been fixed, then
    please change the status accordingly.

**Comment by albert-github** [comment]
I tried to reproduce the problem with the 1.4.5 version of doxygen (the actual version at the moment of the issue) but failed to reproduce the problem (I also tried some older version but also failed to reproduce).

Unfortunately an incomplete report (even with the description) setting to not reproducible.
