### ISSUE TITLE
Would like list of which other methods call this one.  (Origin: bugzilla #318830)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1866]
status NEW severity *enhancement* in component *documentation* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-10-14 03:48:11 +0000, Sarah George wrote:

    Distribution/Version: Debian
    
    There is an option to make a call graph of what other methods are called by
    this
    one, which is very useful.
    
    It would be equally useful to list which of the other methods that doxygen
    is
    processing call this one. That way when a method is changed it's obvious
    which
    parts of the system need to be re-tested. It's also easy to get some
    examples of
    "how is this method used in practise?" which aids understanding.

On 2010-08-11 14:37:09 +0000, Anne wrote:

    There is an option at Expert/SourceBrowser/Referenced_By_Relation that says
    it will list all documented functions that reference it.
    
    However, using Doxygen 1.6.3, I cannot get any listing to be produced. Other
    people here seem to have gotten it to work at one time. My code is all C#.

**Comment by albert-github** [comment]
Seen the comment from Anne about the `REFERENCED_BY_RELATION` and the counter part `REFERENCES_RELATION`, the age of the issue, the improvements in the past and also a missing example.

I  think this problem has been solved in the mean time.
