### ISSUE TITLE
Reports ignoring brief description, but doesn't. (Origin: bugzilla #319085)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1869]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-10-17 16:03:25 +0000, Tad wrote:

    Distribution/Version: XP
    
    Have a header file with this:
    
    /// The main namespace for the 'TLX' project.
    namespace TLX
    {
        /// Factory method for a parser.
        TLX_EXPORT TLXParserI *         __stdcall   CreateParser( void );
    };
    
    Have .cpp file with this:
    
    /// CreateParser
    ///
    /// @return The parser.
    TLXParserI * __stdcall TLX::CreateParser( void )
    {
       return new TLXParser;
    }
    
    Documentation states that it should take the brief description from the 
    declaration and the long description from the definition.  It does do this--
    the
    correct output appears in the HTML.  However, it generates the following 
    warning:
    
    W:/Frameworks/TemplateLanguage/TLX.h:18: Warning: member CreateParser:
    ignoring
    the brief 
    description found here, since another one was found at line 15 of file 
    W:/Frameworks/TemplateLanguage/TLX.cpp!

**Comment by albert-github** [comment]
I tried to reproduce the problem with the 1.4.0 ... 1.4.5 version but I could not get the mentioned warning unless I set `JAVADOC_AUTOBRIEF=YES`
With the current version I don't see the mentioned warning anymore

I think the problem has been solved in the mean time.
