### ISSUE TITLE
namespace in \mainpage breaks latex output (Origin: bugzilla #319383)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1877]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-10-21 09:23:52 +0000, Stefan HÃ¼hne wrote:

    Version details: 1.4.4
    Distribution/Version: Win2000
    
    Using a namespace in the \mainpage title breaks the latex output. The
    generated
    refman.aux is almost empty. Suppressing the automatic link generation with
    '%'
    solves the problem.
    Example: 
    namespace foobar { ...
    
    /**
     * \mainpage Broken documentation for foobar ...
     * \mainpage Working documentation for %foobar ...
     */

On 2005-10-25 11:23:08 +0000, Stefan HÃ¼hne wrote:

    Version 1.4.5 is different: %foobar works for Latex/PDF output (there, the %
    is
    suppressed). But the % now shows in the HTML output :-( Without % the HTML-
    output is clean, but the Latex/PDF-output is broken again.

**Comment by albert-github** [comment]
With the given versions I was able to reproduce the problems as indicated.
(Note for the 1.4.x versions don't forget to set `PDF_HYPERLINKS = YES` and `USE_PDFLATEX = YES`)
With version 1.8.17 these problems are gone.

I think the problem has been solved in the mean time
