### ISSUE TITLE
Wrong warning concerning multiple brief documentation (Origin: bugzilla #319724)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1884]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-10-25 12:06:26 +0000, Stefan HÃ¼hne wrote:

    Version details: 1.4.5
    Distribution/Version: Win2000
    
    Having a brief doc at the declaration and the definition of an item results
    in
    a warning. 
    In this warning the locations of definition and declaration are mixed up. 
    I.e. "module.h:xx: Warning: member foo: ignoring the brief description found
    here, since another one was found at line yy of file module.cpp!". In fact -
    and as documented - the brief doc from module.h is used and the one from 
    module.cpp is ignored.

**Comment by albert-github** [comment]
With the 1.4.5 version I have not been able to reproduce the warning.

I think the issue is incomplete.
