### ISSUE TITLE
Documention does not inherit without qualifier (Origin: bugzilla #320450)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1894]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-11-01 23:01:59 +0000, Jim OLeary wrote:

    Version details: 1.4.5
    Distribution/Version: XP
    
    When a method in a derived class does not use the qualifier of the base
    class
    with the parameter, doxygen does not inherit the documentation from the
    method
    in the base class to the method in the derived class.
    
    Example:
    
    myMethod(BaseClass::myParameter)
    //Doxygen inherits documentation for this parameter and method.
    
    myMethod((myParameter)
    //Doxygen does not inherit documentation for this parameter and method.
    
    Using doxygen 1.4.5.

On 2005-11-06 15:57:13 +0000, Dimitri van Heesch wrote:

    Hi Jim, can you please provide a more complete example, as I cannot tell if
    this
    is a bug or wrong usage.

On 2005-11-07 14:27:22 +0000, Jim OLeary wrote:

    Here is a more complete example.
    
    (in base class)
    /**
      * @brief This method in the base class "BaseClass" executes something. The
      * CustomType
      * parameter is an enumerator that is in this base file. It is not
    qualified,
      * but doxygen produces documentation for this base class.   
      */
      virtual MyReturn execute(int start, int end, CustomType type)=0;
      
      
    In  the derived class we add no documentation, because we are expecting
    doxygen to inherit the base method documentation. However, we have not used
    the qualifier for CustomType, so doxygen does not inherit the documentation
    from the base class. If I instead write "BaseClass::CustomType", doxygen
    does inherit the execute() documentation from the base class. Below are two 
    examples.
    
    (in derived class)
    // doxygen will NOT inherit the documentation from the base class
    virtual MyReturn execute(int start, int end, CustomType type);
    
    (in derived class, having added the qualifier)
    // doxygen WILL inherit the documentation from the base class
    virtual MyReturn execute(int start, int end, BaseClass::CustomType type);

**Comment by albert-github** [comment]
I tried with 1.4.5 and with the current version (1.8.15) and in both cases the version **without** the `BaseClass::` before the `CustomType` does have the documentation . The version **with** `BaseClass::CustomType`  **doesn't** have the documentation.

Used example: [code.zip](https://github.com/doxygen/doxygen/files/2845502/code.zip)

Suggest to close this issue as invalid.
