### ISSUE TITLE
Changed enum syntax in MS Visual Studio 2005 CLR C++ (Origin: bugzilla #320854)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1904]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-11-07 08:24:57 +0000, Helgi Runar Theodorsson wrote:

    Version details: 1.4.5
    
    Changed enum syntax in MS Visual Studio 2005 CLR C++
    
    was
    	
    	public __value enum MyEnum { v1, v2 };
    
    now
    
    	public enum class MyEnum { v1, v2 };
    
    	or
    
    	public enum struct MyEnum { v1, v2 };
    
    Results in enum not being documented.
    
    Doxygen Warning: documented function `public enum class MyEnum' was not
    defined.

On 2005-11-13 14:37:04 +0000, Dimitri van Heesch wrote:

    Can you give me a pointer where this change is announced? I didn't find it
    here:
    http://msdn2.microsoft.com/en-us/library/ms177253.aspx
    

On 2005-11-13 21:49:07 +0000, Helgi Runar Theodorsson wrote:

    This page summarizes the changed language syntax (lots more than just the
    enum
    syntax has been changed): 
    
    http://msdn2.microsoft.com/en-us/library/b23b94s7.aspx 
    
    This should not be reported as a bug in your good product.  This is just 
    Microsoft figuring out that they did not do a good job with Managed C++ 
    Extensions for .NET.  Not the fist time they donât get things right the
    first
    time around...
    

On 2006-10-26 13:36:37 +0000, Kris Cruickshank wrote:

    will the fix to this also fix doxygen for the other new formats described by
    Helgi Runar Theodorsson comment?
    
    http://msdn2.microsoft.com/en-us/library/b23b94s7.aspx 
    
    I have written filters for filtering lots of the new formatting to normal
    C++. This fixes most of the problems with doxygen and the new Managed C++
    format, but does not fix properties.
    
    Thanks

**Comment by albert-github** [comment]
As written in the comments it looks like MicroSoft had some non standard features and replaced them with standard features.
Also it was written: "This should not be reported as a bug in your good product.".

So I think this is not a doxygen bug
