### ISSUE TITLE
When the \param tag is used inside a function argument, redundant trail of Parameters appear for each function arguments (Origin: bugzilla #322177)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1922]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-11-22 21:17:16 +0000, Hao Nguyen wrote:

    1.  Insert this portion into the code
    CFEICompPropSheet::CFEICompPropSheet(
    
    	/*!@param[in]*/ CODComponentSet* pCompSet, 
    	/*!@param[in]*/ CODViewport* pViewport, 
    	/*!@param[in,out]*/ UINT nIDCaption, 
    
    	/*!@param[in,out]*/ UINT nPageFlags, 
    	/*!@param[in,out]*/ CWnd* pParentWnd , 
    	/*!@param[out]*/ UINT iSelectPage)
    
    :CODCompPropSheet(pCompSet, pViewport, nIDCaption, nPageFlags,
    
    	pParentWnd = NULL, iSelectPage)
    2.  Compile the code and output to HTML
    3.  Notice the following result
    CFEICompPropSheet::CFEICompPropSheet  (  CODComponentSet *  pCompSet,  
      CODViewport *  pViewport,  
      UINT  nIDCaption,  
      UINT  nPageFlags = OD_PROPPAGE_ALL,  
      CWnd *  pParentWnd = NULL,  
      UINT  iSelectPage = 0 
     )   
       
    Parameters: 
    pCompSet  Parameters:
    [in]     
     
    pViewport  Parameters:
    [in]     
     
    nIDCaption  Parameters:
    [in,out]     
     
    nPageFlags  Parameters:
    [in,out]     
     
    pParentWnd  Parameters:
    [in,out]     
     
    iSelectPage  Parameters:
    [out]

On 2005-11-27 15:51:45 +0000, Dimitri van Heesch wrote:

    The @param command is intended for situations where the parameter
    documentation
    is NOT in front of the parameter. The syntax is 
    
    @param name docs 
    
    (where [in,out] can be used as options). 
    
    You cannot indicate an in/out direction when documenting a parameter inline
    at
    the moment. I intent to add support for something like /*![in]...*/ in the
    future and I'll treat this bug report as an enhancement request for this.

On 2006-06-29 23:06:38 +0000, Aaron Birenboim wrote:

    If adding [in] [out] [in,out] to inline parameter documenting
    will solve this problem, you may want to attach this bug to 143218
    
    As a new doxygen bug reporter, I'm hesitant to make a dependency
    between these bugs.

**Comment by albert-github** [comment]
Seen the remark about the usage and about bug 143218 (#1130) that is now working, also for this case when we leave out the `@param`,
I think this problem is a combination of usage and solved in the mean time
