### ISSUE TITLE
#pragma mark breaks doc. generation in Obj-C .m file (Origin: bugzilla #323040)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1937]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2005-12-02 16:56:44 +0000, Serge Cohen wrote:

    Any doxygen comments in a .m file after the first #pragma mark is ignored.
    Here is an example (try to remove the #pragma mark to see how they differ).
    
    -- WAApplicationController.m
    //
    //  WAApplicationController.m
    //  Wafle
    //
    //  Created by Serge Cohen on 21/11/05.
    //  Copyright 2005 Serge Cohen. All rights reserved.
    //
    
    /** 
    @file WAApplicationController.m
    @brief Implementation file for class WAApplicationController.
    */
    
    #import "WAApplicationController.h"
    
    #import "WafleDefinitions.h"
    
    /**
    @brief An array holding the information of which file can be opened, and
    how.
    */
    static NSMutableArray	*WAImportDocFormat;
    
    /**
    @class WAApplicationController
    @brief The Application Controller class for Wafle
    @author Serge Cohen
    @version 0.1
    @date 21/11/2005
    
    This is the class which is the application delegates. It performs
    most of the action required at application level. Somehow this is the unique
    'document' of the Wafle application.
    
    In the documentation of this class we use the term 'environement' to name
    the list
    of all signals (and other WAObjects conforming objects) that are present in
    the
    objectArrayController.
    */
    @implementation WAApplicationController
    
    #pragma mark Static methods
    + (void) initialize
    {
    }
    
    #pragma mark Life Cycle
    - (id) init
    {
    }
    
    - (void) dealloc
    {
    }
    
    - (void) awakeFromNib
    {
    }
    
    #pragma mark Interface callbacks :
    - (BOOL) validateMenuItem:(NSMenuItem *) anItem
    {
    }
    
    #pragma mark Interface actions :
    #pragma mark File Menu :
    /**
    @brief Empty the environement.
    @param sender The object sending the message.
    
    This will empty the environement : the enseble of signals and other object
    stored by the application. In future it should propose to save if it is
    relevant.
    */
    - (IBAction) newEnvironement:(id) sender
    {
    }
    
    /**
    @brief Replace teh enviroenement by the one contained in a file.
    @param sender The object sending the message.
    
    This opens up a sheet to select a file to open ... all the rest is performed
    by the openPanelDidEnd:returnCode:contextInfo: call-back method.
    
    <b>NOT IMPLEMENTED YET/CALLBACK MISSING</b>
    */
    - (IBAction) openEnvironement:(id) sender
    {
    }
    
    /**
    @brief This will save the enviroenement to the current URL. 
    @param sender The object sending the message.
    
    This method is supposed to save the environement. If ever the URL is nil, it
    will call saveEnvironementAs:.
    
    <b>NOT IMPLEMENTED YET/CALLBACK MISSING</b>
    */
    - (IBAction) saveEnvironement:(id) sender
    {
    }
    
    /** 
    @brief Saving the current enviroenement under a specific filename.
    @param sender The object sending the message.
    
    This opens up a sheet to define the filename under which the environement
    should be saved.
    Indeed this method is doing nothing else. All the rest is done in the
    savePanelDidEnd:returnCode:contextInfo: call-back method.
    
    <b>NOT IMPLEMENTED YET</b>
    */ 
    - (IBAction) saveEnvironementAs:(id) sender
    {
    }
    
    /**
    @brief Revert the environement to what was saved to disk
    @param sender The object sending the message.
    
    If the environement was never saved (more precisely, if the URL is not set),
    then this action will indeed perform nothing. Indeed this is the case where
    by 'reverting' one
    means 'make a new <b>empty</b>' environement. For that use newEnvironement:.
     
    <b>NOT IMPLEMENTED YET</b>
    */ 
    - (IBAction) revertEnvironement:(id) sender
    {
    }
    
    /**
    @brief Openning files containing object to be added to the environement.
    @param sender The object sending the message.
    
    This method is merely responsible for opening the sheet asking for
    files to be opened. All the rest is performed in the  
    importPanelDidEnd:returnCode:contextInfo: method.
    */
    - (IBAction) importObject:(id) sender
    {
    }
    
    
    /**
    @brief Export the currently selected object(s) to a file
    @param sender The object sending the message.
    
     This method is merely responsible to open a sheet asking the name of
     the file you want to save the exported object(s) to. All the rest is
    performed in the
     exportPanelDidEnd:returnCode:contextInfo: call-back method.
     
    <b>NOT IMPLEMENTED YET</b>
     */
    - (IBAction) exportObject:(id) sender
    {
    }
    
    #pragma mark Other menus :
    /**
    @brief Opens the help window...
     @param sender The object sending the message.
     
     Nothing done so far ... still have to define what to do here...
     
     <b>NOT IMPLEMENTED YET</b>
     */
    - (IBAction) help:(id) sender
    {
    }
    
    /**
    @brief Opening the preferences window
    @param sender The object sending the message.
    
     So far there is NO preferences window to open ... so do absolutely nothing
    !!!
     
     <b>NOT IMPLEMENTED YET</b>
     */
    - (IBAction) preferences:(id) sender
    {
    }
    
    
    #pragma mark Full Input/Output
    /**
    @brief Returning the full environement as a NSData object
    @param typeName The type of data to provide.
    @param outError A pointer that can set to an encountered error (output).
    @return The environement encoded using a NSKeyedArchiver.
     
     This method will use a NSKeyedArchiver to encode all the content of the
    environement into
     a NSData object which can be used to save to disk, or send accross
    network...
     If an error is encountered during the process, it will generate a NSError
    (or get the underlying one)
     and transfer it to the caller using the outError parameter.
     
     So far it supports only the 'wafle' format.
    */
    - (NSData *) dataOfType:(NSString *) typeName error:(NSError **) outError
    {
    }
    
    /**
    @brief Reading the environement from a NSdata object.
    @param data The data containing the environement to read.
    @param typeName The type/format the data is in.
    @param outError The error (potentially) encountered during the read.
    @return YES upon success (NO otherwise)
    
     This method will empty the environement and fill it with the objects
     contained in data. If an error is encountered during the process, it will
    generate
     a NSError (or get the underlying one) and transfer it to the caller using
    the
     outError parameter.
     
     So far it supports only the 'wafle' format.
     */
    - (BOOL) readFromData:(NSData *) data ofType:(NSString *) typeName
    error:(NSError **) outError
    {
    }
    
    /**
    @brief Writing the environement to a URL.
    @param absoluteURL The URL to which the data should be writen.
    @param typeName The type of data to provide.
    @param outError A pointer that can set to an encountered error (output).
    @return YES upon successull completion.
    
     This method is writing the full content of the environement at a given URL.
     It uses @link dataOfType:error: dataOfType @/link method to format the data
    into the given
     format. See the documentation of this method to see which formats are
    supported.
    */
    - (BOOL) writeToURL:(NSURL *) absoluteURL ofType:(NSString *) typeName
    error:(NSError **) outError
    {
    }
    
    /**
    @brief Reading the environement from a URL.
    @param absoluteURL The URL from which the data should be read.
    @param typeName The type of data to read.
    @param outError A pointer that can set to an encountered error (output).
    @return YES upon successull completion.
    
     This method is reading the full content of the environement from a given
    URL.
     It uses @link readFromData:ofType:error: readFromData @/link method to
    decode the data from the
    given
     format. See the documentation of this method to see which formats are
    supported.
    */
    - (BOOL) readFromURL:(NSURL *) absoluteURL ofType:(NSString *) typeName
    error:(NSError **) outError
    {
    }
    
    #pragma mark Partial Input/Output
    /**
    @brief Call-back method when a file is selected to be imported.
    @param sheet The sheet object used to select the file.
    @param returnCode The code of the button that was clicked in the sheet.
    @param contextInfo The context provided to the sheet before opening it
    (useless here).
    
     This will get the list of files that were selected, and using there
    extension and the
     WAImportDocFormat array will select the proper object/class and method to
    parse it
     into a valid <WAObject> object.
     */ 
    - (void) importPanelDidEnd:(NSOpenPanel *) sheet returnCode:(int) returnCode
    contextInfo:(void *)
    contextInfo
    {
    }
    
    /**
    @brief Adding the content of a .wafle file to the environement.
    @param iFile The file handle to use to ge the data.
    @param iController The controller to which the WAObject objects should be
    added.
    @return nil (objects are already added at the end of the method).
     
     This method is using direct access to the controller (indeed 'self') to add
    the read-in objects.
     Hence it returns 'nil', so objects are not added twice.
     */ 
    - (id) importFromWafleFile:(NSFileHandle *) iFile
    forController:(WAApplicationController *) iController
    {
    }
    
    #pragma mark NSApplication Delegate :
    /**
    @brief Finishing the preparation of the class.
    @param aNotification The notification of the fact that the NSApplication is
    ready to run.
    
     So far this method is only instantiating and filling the content of the
    WAImportDocFormat
     array. It might be better to indeed but hthis code in another place : it
    should rather be in
     class method (to avoid the risk of the code to be called more than once).
     */
    - (void) applicationWillFinishLaunching:(NSNotification *) aNotification
    {
    }
    
    
    #pragma mark Accessors :
    @end
    
    -- WAApplicationController.h
    //
    //  WAApplicationController.h
    //  Wafle
    //
    //  Created by Serge Cohen on 21/11/05.
    //  Copyright 2005 Serge Cohen. All rights reserved.
    //
    
    /** 
    @file WAApplicationController.h
    @brief Interface definition for class WAApplicationController.
    */
    
    
    #import <Cocoa/Cocoa.h>
    
    #import "WafleDefinitions.h"
    
    
    
    @interface WAApplicationController : NSObject
    {
    #pragma mark Outlets :
    	IBOutlet NSApplication			*application;		
    			/**< The application object itself. */
    	IBOutlet NSWindow					*mainWindow;	
    				/**< The main window (having the list of objects). */
    	
    #pragma mark Instance Variables :
    	NSURL									*fileURL;
    						/**< The URL to which the environement should be saved. */
    }
    
    #pragma mark Static methods
    + (void) initialize;
    
    #pragma mark Life Cycle
    - (id) init;
    - (void) dealloc;
    - (void) awakeFromNib;
    
    #pragma mark Interface callbacks :
    - (BOOL) validateMenuItem:(NSMenuItem *) anItem;
    
    #pragma mark Interface actions :
    #pragma mark File Menu :
    /** @name File Menu actions */
    /*@{*/
    - (IBAction) newEnvironement:(id) sender;
    - (IBAction) openEnvironement:(id) sender;
    - (IBAction) saveEnvironement:(id) sender;
    - (IBAction) saveEnvironementAs:(id) sender;
    - (IBAction) revertEnvironement:(id) sender;
    - (IBAction) importObject:(id) sender;
    - (IBAction) exportObject:(id) sender;
    /*@}*/ // end of group
    
    #pragma mark Other menus :
    /** @name Other Menus */
    /*@{*/
    - (IBAction) help:(id) sender;
    - (IBAction) preferences:(id) sender;
    /*@}*/ // end of group
    
    #pragma mark Full Input/Output
    /** @name Full input/ouput (all env. at once). */
    /*@{*/
    - (NSData *) dataOfType:(NSString *) typeName error:(NSError **) outError;
    - (BOOL) readFromData:(NSData *) data ofType:(NSString *) typeName
    error:(NSError **) outError;
    - (BOOL) writeToURL:(NSURL *) absoluteURL ofType:(NSString *) typeName
    error:(NSError **) outError;
    - (BOOL) readFromURL:(NSURL *) absoluteURL ofType:(NSString *) typeName
    error:(NSError **) outError;
    /*@}*/ // end of group
    
    #pragma mark Partial Input/Output :
    /** @name Partial Input/Output (import/export). */
    /*@{*/
    - (void) exportPanelDidEnd:(NSOpenPanel *) sheet returnCode:(int) returnCode
    contextInfo:(void *)
    contextInfo;
    - (void) importPanelDidEnd:(NSOpenPanel *) sheet returnCode:(int) returnCode
    contextInfo:(void *)
    contextInfo;
    - (id) importFromWafleFile:(NSFileHandle *) iFile
    forController:(WAApplicationController *) iController;
    - (void) openPanelDidEnd:(NSOpenPanel *) sheet returnCode:(int) returnCode
    contextInfo:(void *)
    contextInfo;
    - (void) savePanelDidEnd:(NSOpenPanel *) sheet returnCode:(int) returnCode
    contextInfo:(void *)
    contextInfo;
    /*@}*/ // end of group
    
    #pragma mark NSApplication Delegate :
    - (void) applicationWillFinishLaunching:(NSNotification *) aNotification;
    
    #pragma mark Accessors :
    /** @name Accessors */
    /*@{*/
    /*@}*/ // end of group
    
    @end

**Comment by albert-github** [comment]
With version 1.4.5. I see that the method `newEnvironement` is not documented. Removing the `#pragma` statements before the `.m` does result in a documented `newEnvironement` method.
When running the problem with 1.8.15 (and all `#pragma` statements) I see that `newEnvironement` (and other methods are documented.

I think the problem has been solved in the mean time.
