### ISSUE TITLE
Doxygen does not find/relate definitions of many methods (C++) (Origin: bugzilla #324823)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1970]
status REOPENED severity *normal* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[Doxyfile](https://sourceforge.net/projects/doxygen/files/attachments/bug324823_56308_Doxyfile/download/download)_ (ID 56308)

On 2005-12-22 17:29:51 +0000, Sascha Ruppert wrote:

    Doxygen does not find the definitions of many C++ methods, or at least can't
    relate them to their declarations.
    
    Indication 1: In the generated XML, the file/line location of those method's
    definition is missing; the location tag does not contain the attributes
    "bodyfile", "bodystart", "bodyend", but only "file" and "line" (as you would
    expect for abstract methods).
    
    Indication 2: The references relation is also broken for those methods.
    
    Unfortunately I can't see any relevant differences in the code between
    methods with and without the full location information. I also can't find
    information about possible problems when reading the respective definition
    files in the doxygen log file.
    
    In our source files, Doxygen finds approx. 170k methods but does not see the
    definitions of 50k methods.
    
    The problem can be reproduced by running doxygen on its own source files
    (1.4.5 src distribution). I picked some example methods for which the
    information is missing (and a method for which it works as expected):
    
    All declarations in src/config.h, definitions in src/config.cpp; line
    numbers:
     Config::substituteEnvironmentVars, decl 523, def 2554-2562
     Config::parseString,               decl 537, def 4574-4589
     Config::create,                    decl 548, def 2943-4514
    (Config::getInt,                    decl 397, def 742-756   )
    
    The xml location tags of the above methods in class_config.xml look like :
     <location file="...src/config.h" line="523"/>
     <location file="...src/config.h" line="537"/>
     <location file="...src/config.h" line="548"/>
    (<location file="...src/config.h" line="397" bodyfile="...src/config.cpp"
    bodystart="742" bodyend="756"/>)

On 2005-12-22 17:35:51 +0000, Sascha Ruppert wrote:

    Created attachment 56308
    doxyfile
    
    This is the doxyfile for reproducing. The input to doxygen (1.4.5) was the
    src dir of the 1.4.5 src distribution of doxygen.

On 2005-12-24 14:52:08 +0000, Dimitri van Heesch wrote:

    I found something that causes doxygen's code parser get off-track. It fixes
    the problems seen in the config.cpp file (which was generated from config.l
    by the way). If you have an easy way to check this on all of doxygen's
    sources that let me know (you apparently did this and I assume not by hand
    ;)
    
    I'll include my fix in the next CVS update.
    
    
    

On 2005-12-30 17:48:39 +0000, Dimitri van Heesch wrote:

    This bug had the status ASSIGNED (which meant it was fixed, but not
    officially released), so now doxygen release 1.4.6 is out I've given it the
    status FIXED.
    
    Nevertheless, I would like to ask you to verify that this bug is indeed
    fixed in release 1.4.6. If not, then please reopen the bug.
    

On 2006-01-05 11:52:23 +0000, Sascha Ruppert wrote:

    The problem is still there in doxygen 1.4.6 (1.4.6-NO). In the same source
    files, doxygen 1.4.6 misses/finds exactly the same function definitions as
    1.4.5 did.

**Comment by albert-github** [comment]
I had a look at the sources from doxygen 1.4.5 and in these sources we see that the files `config.h` and `config.l` are present but `config.cpp` is not present, the later is logical as it is a generated files from `config.l` and `*.l` files are not processed. 
As `config.cpp` is not present (and `config.l` is not processed) it is logical that the mentioned information is missing.
When converting the `config.l` to `config.cpp` by removing the lex information and running with 1.4.5 we see that with the exception for `Config::writeTemplate` at line 509 of `config.h` the information is present. When running with 1.9.1 all the information for location is present.

I think that the problem here is a mix of usage and solved in the mean time (the last especially for the problem mentioned in respect to line 509).
