### ISSUE TITLE
Missing CRLF in generated RTF document. (Origin: bugzilla #325620)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1981]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.3-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2006-01-03 13:20:47 +0000, L. A. Weber wrote:

    The generated RTF docuements have missing CRLF's in "Field Documentation",
    see following example:
    
    Field Documentation
    int CINTBUFF_T::buffer[BUFFSIZE]
    Buffer of BUFFSIZE integers 
    
    Definition at line 14 of file cbuff.h.
    Referenced by cbuffIncInsert().int* CINTBUFF_T::extract (missing CRLF after
    .)
    Buffer data extraction point 
    
    Definition at line 16 of file cbuff.h.
    Referenced by cbuffDataSize().int* CINTBUFF_T::insert (missing CRLF after .)
    Buffer data insertion point 
    
    Definition at line 15 of file cbuff.h.
    Referenced by cbuffDataSize(), cbuffIncInsert(), and cbuffPutInt().
    
    This also causes problems with text formatting (i.e. bolding of the
    "Referenced" lines that contain the next field name).

On 2007-10-15 19:40:50 +0000, Dimitri van Heesch wrote:

    This bug's version was set to "latest". Since this is a moving target, I
    changed it to 1.5.3-SVN. If you believe this has already been fixed, then
    please change the status accordingly.

**Comment by albert-github** [comment]
With the version 1.4.6 I was able to reproduce the problem. With version 1.8.15 the problem is gone.

I think the problem has been solved in the mean time.
