### ISSUE TITLE
excessive  warning messages when no output active (Origin: bugzilla #325741)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1984]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.3-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[testcase - 325741.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug325741_57007_testcase - 325741.zip/download/download)_ (ID 57007)

On 2006-01-04 09:29:41 +0000, Lars Friedrich wrote:

    Found in Doxygen version 1.4.5 and 1.4.6-NO (exists maybe earlier, too)
    
    When all output methods (HTML, LaTeX etc.) are set to NO, doxygen will
    generate:
    
    Warning: parameters of member DummyFunc are not (all) documented
    Warning: return type of member DummyFunc is not documented
    
    warnings for all functions, although the functions are properly documented.
    If GENERATE_HTML output is then set to YES without any other changes, the
    warning messages will disappear. The warnings appear in addition to any
    other normal (correct) warnings and also if no warnings are expected.
    
    //-- Function: DummyFunc
    -------------------------------------------------------
    ///
    ///  This function solely exists to prevent that the arm linker removes a
    ///  desired input section.
    ///
    ///  \return  Always 0
    ///
//------------------------------------------------------------------------------
    static int DummyFunc(void)
    {  
      return 0;
    }

On 2006-01-05 04:22:10 +0000, Kevin McBride wrote:

    Kevin -> Dimitri: By setting all outputs to NO, the purpose of using doxygen
    would be defeated, correct?  If so, then I don't think this is a bug that we
    should fix.  Doxygen can't even be debugged unless it is allowed to produce
    output.

On 2006-01-05 07:11:27 +0000, Lars Friedrich wrote:

    The purpose is to check a large project for missing Doxygen tags, resp.
    trigger the Doxygen warning messages for undocumented members and functions.
    If I'm looking for missing Doxygen tags it doesn't make sense to generate
    output - after all, the output is guaranteed to be incomplete/false.

On 2006-01-06 19:15:16 +0000, Dimitri van Heesch wrote:

    I did not get the warnings you reported when using your example, so there
    must be something else. Please attach a self-contained example (config file
    + source file) so I can reproduce it.

On 2006-01-09 07:55:14 +0000, Lars Friedrich wrote:

    Created attachment 57007
    Testcase for excessive warning messages
    
    This testcase generates excessive warning messages:
    
    >doxygen
    actask.c:18: Warning: parameters of member DoInitcalls are not (all)
    documented
    actask.c:18: Warning: return type of member DoInitcalls is not documented
    actask.c:3: Warning: parameters of member DummyFunc are not (all) documented
    actask.c:3: Warning: return type of member DummyFunc is not documented

On 2006-02-18 10:09:19 +0000, Kevin McBride wrote:

    Confirmed with CVS releases 20060115 and 20060202.

On 2007-10-15 19:40:51 +0000, Dimitri van Heesch wrote:

    This bug's version was set to "latest". Since this is a moving target, I
    changed it to 1.5.3-SVN. If you believe this has already been fixed, then
    please change the status accordingly.

On 2013-05-04 18:04:08 +0000, albert wrote:

    The results as described above can be confirmed with the mentioned versions.
    
    When running with version 1.8.3.1 there is only one message left:
      actask.c:5: warning: return type of member DummyFunc is not documented
    although the return type of the function is set. When enabling one of the
    GENERATE_<output_format> has been set the message does not appear.
    
    Looks like the return type is not set properly when no <output_format> has
    been set, the routine hasDocumentedReturnType returns when no
    <output_format> has been selected a FALSE, in case of a selected
    <output_format> the routine returns TRUE at the place where the message is
    printed. tracing back gives calls to setHasDocumentedReturnType,
    validatingParseDoc, parseDoc. The last one is called at multiple places but
    apparently once it is not called.

**Comment by albert-github** [comment]
With the given attachment we get:
- version 1.4.5
  ```
  ../actask.c:18: Warning: parameters of member DoInitcalls are not (all) documented
  ../actask.c:18: Warning: return type of member DoInitcalls is not documented
  ../actask.c:3: Warning: parameters of member DummyFunc are not (all) documented
  ../actask.c:3: Warning: return type of member DummyFunc is not documented
  ```
- version 1.8.3.1
  ```
  warning: No output formats selected! Set at least one of the main GENERATE_* options to YES.
  ../actask.c:5: warning: return type of member DummyFunc is not documented
  ```
- version 1.9.1
  ```
  warning: No output formats selected! Set at least one of the main GENERATE_* options to YES.
  ../actask.c:27: warning: documented empty return type of DoInitcalls
  ```

The warning with version 1.9.1 is correct as we have a void function.

I think the problem has been solved in the mean time
