### ISSUE TITLE
\dir command sees duplicate directories that aren't (Origin: bugzilla #329687)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2022]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2006-02-02 23:48:17 +0000, Paul F. Kunz wrote:

    I get the following Warnings from Doxygen...
    
    /home/pfkeb/hippodraw/reps/reps.dir:1 Warning: \dir command matches multiple
    directories.
      Applying the command for directory /home/pfkeb/hippodraw/datareps/
      Ignoring the command for directory /home/pfkeb/hippodraw/reps/
    
    /home/pfkeb/hippodraw/xml/xml.dir:1 Warning: \dir command matches multiple
    directories.
      Applying the command for directory /home/pfkeb/hippodraw/qtxml/
      Ignoring the command for directory /home/pfkeb/hippodraw/xml/
    
    Part the the directory names matches, but not all.
    
    Hoever the resultant html under the directories tabbed panel is correct.

On 2010-01-29 19:26:36 +0000, itroot wrote:

    It is because doxygen applying your dir command to first matching directory.
    If 2 directories have the same name, it will choose first. You can try to
    specify additional path fragments.
    Also, if bug 608480 will be fixed, you will able to apply documentation to
    current directory.

**Comment by albert-github** [comment]
Tested with 1.4.5 and here we see the mentioned warnings, with version 1.9.1 these warnings are gone (and output looks OK too).

I think the problem has been solved in the mean time.
