### ISSUE TITLE
'sa' doesn't create hyperlink for some files (Origin: bugzilla #329754)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2024]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2006-02-03 10:16:43 +0000, albrecht.dress@arcormail.de wrote:

    Please describe the problem:
    Usually, the "\sa" command can be used to reference to a source file. This
    works
    fine if the file name contains only letters, e.g.
    
    \sa foo.h, foo.c   <--- creates hyperlinks
    
    but /not/ if the file name contains a "-" (and maybe other) chars:
    
    \sa foo-bar.h, foo-bar.c <--- does /not/ create hyperlinks
    
    /Automatic/ links created by doxygen (i.e. "documentation generated from the
    following file") work, though.
    
    Steps to reproduce:
    1. create a project with files above
    2. enter the \sa commands above
    3. no hyperlinks for files with the "-" char in the name
    
    
    Actual results:
    see above
    
    Expected results:
    a proper hyperlink
    
    Does this happen every time?
    yes
    
    Other information:
    reproducible with doxygen-1.4.6-2.i386.rpm on a FC3 box

**Comment by albert-github** [comment]
I tested with version 1.4.6 and here the files with a `-` in their names are not linked with the `\sa` command.
With version 1.8.15 the files with a `-` in their name are linked.

I think the problem has been solved in the mean time.
