### ISSUE TITLE
template explicite instantiation (Origin: bugzilla #331519)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2044]
status NEW severity *minor* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2006-02-17 09:16:12 +0000, Seweryn Habdank-WojewÃ³dzki wrote:

    Please describe the problem:
    When in the code is used template explicite instantiation then doxygen
    interpret
    it as something like operator().
    
    Steps to reproduce:
    The example of that problem is below. In my file configuration.cpp I have
    explicit instantiation of the template - is shown in \code section.
    
    \code
    	template Loki::SingletonHolder < Configuration >;
    \endcode
    
    Loki - Andrei Alexandrescu namespace for Loki library.
    SingletonHolder - template class.
    Configuration - my own class.
    
    Such a construction is allowed in C++, see "C++ Templates, The Complete
    Guide",
    Vandevoorde D., Josuttis N.M.
    
    Actual results:
    and doxygen produces:
    
    \verbatim
    
    configuration.cpp:21: Warning: no matching class member found for template
    config::Loki::SingletonHolder< Configuration >()
    
    \endverbatim
    
    It tries to fit explicit instantiation as member function of the class, it
    is
    not correct.
    
    Expected results:
    Either omit such a place or proper recognize it.
    
    Does this happen every time?
    Yes.
    
    Other information:
    I think that Doxygen is the best one :-).

**Comment by albert-github** [comment]
With the given information I have not been able to reproduce the problem i.e. I don't see the `()`, The waring I get (with dioxygen 1.4.6 (as well as with the current 1.12.0 doxygen version, is:
```
configuration.cpp:12: Warning: documented function `template Loki::SingletonHolder< Configuration >' was not defined.
```
used example:
```
/// \file


/// \brief Andrei Alexandrescu namespace for Loki library.
namespace Loki {

/// \brief my own class.
class Configuration {};

}
/// \brief  template class.
template Loki::SingletonHolder < Configuration >;
```

I think the issue is incomplete.
