### ISSUE TITLE
Managed C++ keyword "__interface" handled incorrectly (Origin: bugzilla #332239)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2052]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.3-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2006-02-22 20:17:25 +0000, Ken Hagin wrote:

    Please describe the problem:
    In Managed C++ (VS 2003), __interface is seen as a member variable rather
    than
    a "class" level entity.  I have a working fix.  Here is the added code:
    Version: 1.4.6, file: scanner.l, date Dec 27, 2005, output from Cygwin
    "diff":
    1111a1112,1122
    > <FindMembers>{B}*"__interface"{BN}+ 	{ // Managed C++ interface
    > 					  lineCount();
    >   					  isTypedef=FALSE;
    > 					  current->section = 
    Entry::INTERFACE_SEC;
    > 					  addType( current ) ;
    > 					  current->type += " interface" ;
    > 					  current->fileName  = yyFileName;
    > 					  current->startLine = yyLineNr;
    > 					  current->bodyLine  = yyLineNr;
    > 					  BEGIN( CompoundName );
    >   					}
    
    
    Steps to reproduce:
    1. 
    2. 
    3. 
    
    
    Actual results:
    
    
    Expected results:
    
    
    Does this happen every time?
    
    
    Other information:

On 2007-10-15 19:40:53 +0000, Dimitri van Heesch wrote:

    This bug's version was set to "latest". Since this is a moving target, I
    changed it to 1.5.3-SVN. If you believe this has already been fixed, then
    please change the status accordingly.

**Comment by albert-github** [comment]
I don't think `__interface` is a standard C++ keyword, but an extension from Microsoft  (see e.g. https://docs.microsoft.com/en-us/cpp/cpp/interface?redirectedfrom=MSDN&view=msvc-160), it should be handled in the same way as e.g. `__declspec` )see the doxygen documentation about Preprocessing).

I think this is usage.
