### ISSUE TITLE
nested namespaces causes tag file error (Origin: bugzilla #333331)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2065]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2006-03-04 03:52:44 +0000, Bradford Castalia wrote:

    Nested C++ namespaces result in a tag file (GENERATE_TAGFILE) which, when
    read
    by doxygen during processing of another module, generates and error and the
    functions in the same namespaces of the second module are then not seen.
    
    From the following file:
    
    namespace UA
    {
    namespace HiRISE
    {
    /** foobar
    */
    void foobar ();
    }
    }
    
    doxygen produces the following tag file:
    
    <?xml version='1.0' encoding='ISO-8859-1' standalone='yes'?>
    <tagfile>
      <compound kind="page">
        <name>index</name>
        <title></title>
        <filename>index</filename>
      </compound>
      <compound kind="file">
        <name>Overview.doxygen</name>
        <path>/usr/local/PIRL/src/HiRISE/libHiRISE/</path>
        <filename>Overview_8doxygen</filename>
      </compound>
      <compound kind="file">
        <name>try.cc</name>
        <path>/usr/local/PIRL/src/HiRISE/libHiRISE/</path>
        <filename>try_8cc</filename>
        <includes id="try_8hh" name="try.hh" local="yes"
    imported="no">try.hh</includes>
        <namespace>UA</namespace>
        <namespace>UA::HiRISE</namespace>
        <member kind="function">
          <type>void</type>
          <name>foobar</name>
          <anchor>a0</anchor>
          <arglist>()</arglist>
        </member>
      </compound>
      <compound kind="file">
        <name>try.hh</name>
        <path>/usr/local/PIRL/src/HiRISE/libHiRISE/</path>
        <filename>try_8hh</filename>
        <namespace>UA</namespace>
        <namespace>UA::HiRISE</namespace>
      </compound>
      <compound kind="namespace">
        <name>UA</name>
        <filename>namespaceUA.html</filename>
        <namespace>UA::HiRISE</namespace>
      </compound>
      <compound kind="namespace">
        <name>UA::HiRISE</name>
        <filename>namespaceUA_1_1HiRISE.html</filename>
        <member kind="function">
          <type>void</type>
          <name>foobar</name>
          <anchor>a0</anchor>
          <arglist>()</arglist>
        </member>
      </compound>
    </tagfile>
    
    The <namespace> inside the first <compound kind="namespace"> is the source
    of
    the following error when doxygen is Reading this tag file (TAGFILES):
    
    Error: Unexpected tag `namespace' found
    
    Later, after this error has occured, doxygen reports Warnings that each
    function "of namespace UA::HiRISE is not documented."
    
    The tag file read Error does not occur if only one namespace is used.
    The "not documented" problem does not occur if the tag file is removed
    from the list of TAGFILES.

**Comment by albert-github** [comment]
In version 1.4.1 I could see that in de project that uses the tag file the message:
```
Error: Unexpected tag `namespace' found
```

In newer versions  the message is not present anymore.

I think the problem has been solved in the mean time
