### ISSUE TITLE
'using' does not work as expected (Origin: bugzilla #333647)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2067]
status NEW severity *normal* in component *general* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2006-03-06 19:32:43 +0000, Hector C wrote:

    In the following code, 'DoxygenRocks::x' was made public by 'using'.
    However, it doesn't show in the documentation of 'DoxygenChokes'.
    
    Regards,
    
    ++Hector C.
    
    ---------------------------------
    
    /// Really rocks
    class DoxygenRocks
    {
    public:
        int x;  //!< Sometimes chokes
    };
    
    /// This is one case where it chokes
    class DoxygenChokes : private DoxygenRocks
    {
    public:
        /// This should be shown as public
        using DoxygenRocks::x;
    };

**Comment by albert-github** [comment]
With the doxygen 1.4.6 version we see:

![image](https://github.com/doxygen/doxygen/assets/5223533/09c723fd-8b08-4b6c-9b36-f886543bdc96)

and

![image](https://github.com/doxygen/doxygen/assets/5223533/a1a79d8a-2573-488a-bf68-2fcf9005110e)

so x is shown as private variable.

with the current, 1.9.8, doxygen version we see:

![image](https://github.com/doxygen/doxygen/assets/5223533/b3c04c29-c389-4ad5-a234-4fde26744cfa)

I think the problem has been solved in the mean time.
