### ISSUE TITLE
scope of enums not properly handled - members with same name get same value (Origin: bugzilla #334388)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2075]
status NEW severity *major* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2006-03-13 07:28:49 +0000, Lars Friedrich wrote:

    Example:
    
    file a.c
    enum A {
     SAME_NAME = 511;
    };
    
    file b.c
    enum B {
     SAME_NAME = 711;
    };
    
    Doxygen generates documentation:
    
    file a.c
    Enumeration A
    SAME_NAME 511
    
    file b.c
    Enumeration B
    SAME_NAME 511

On 2006-06-20 09:28:39 +0000, Frans Englich wrote:

    
    A slightly related bug report is:
    
    Enchancement, "Automatically link to enums":
    http://bugzilla.gnome.org/show_bug.cgi?id=334388
    
    
    Frans
    

On 2006-10-10 09:48:50 +0000, Martin Hack wrote:

    I'd like to supply another example that might help to track down this bug.
    
    I'm using doxygen 1.4.7 and html-output.
    
    Look at the following C# code:
    
    begin >>>>>
    namespace doxytest
    {
    	enum firstEnum
    	{
    		sameMember,	//!< comment in firstEnum
    		firstUnique	//!< unique comment in firstEnum
    	}
    	enum secondEnum
    	{
    		sameMember,	//!< comment in secondEnum
    		secondUnique	//!< unique comment in secondEnum
    	}
    }
    <<<< end
    
    I would expect that the documentation contains the two enums with their own
    two values each, but the value 'sameMember' is listed twice in both enums.
    It seems as if all instances of any member named 'sameMember' are listed in
    each enum documentation no matter in which enum they are declared. The
    'copies' use even the comment found at their own declaration.
    
    The resulting html documentation is: 
    
    begin >>>>
    
    doxytest Namespace Reference
    
    Enumerations
    enum  	firstEnum { sameMember, sameMember, firstUnique }
    enum  	secondEnum { sameMember, sameMember, secondUnique }
    
    Enumeration Type Documentation
    
    enum doxytest::firstEnum
    Enumerator:
        sameMember 	comment in firstEnum
        sameMember 	comment in secondEnum
        firstUnique 	unique comment in firstEnum
    
    enum doxytest::secondEnum
    Enumerator:
        sameMember 	comment in firstEnum
        sameMember 	comment in secondEnum
        secondUnique 	unique comment in secondEnum
    
    <<<< end

On 2007-04-30 22:16:46 +0000, Katie Knobbs wrote:

    I am finding that values are getting added together for enumuarations in
    different namespaces with same names.
    
    EX:
    
    namespace xxx.yyy {  
    
      public enum test1 {
        value1 = 0, value2, value3 
      }
    }
    
    namespace xxx.zzz {  
    
      public enum test2 {
        value1 = 0, value4, value5 
      }
    }
    
    OUTPUT
    
    enum doxytest::test1
    Enumerator:
        value1
        value2
        value3
        value1
        value4
        value5
    
    enum doxytest::test2
    Enumerator:
        value1
        value2
        value3
        value1
        value4
        value5
    
    with both enumurations showing up in the correct namespace.

**Comment by albert-github** [comment]
We see in this issue 3 sub issues:
1. Original by  Lars Friedrich, unfortunately I have not been able to reproduce this example (with doxygen 1.4.6), so looks like to be incomplete
2. Problem by Martin Hack, with doxygen 1.4.7 I can reproduce this problem. With the current, 1.12.0, doxtgen version this problem is gone so this part is in my opinion solved in the mea time.
3. Problem by Katie Knobbs, unfortunately I have not been able to reproduce this example (with doxygen 1.4.7), so looks like to be incomplete
