### ISSUE TITLE
False warning "no matching class member" involving namespace (Origin: bugzilla #335140)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2082]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2006-03-19 17:16:19 +0000, Frans Englich wrote:

    With Doxygen 1.4.6 I get the warning:
    
    Warning: no matching class member found for
      void ANamespace::AClass::aFunction(ANamespace::ClassB)
    Possible candidates:
      void ANamespace::AClass::aFunction(ClassB)
    
    
    For the code:
    
    -------------------------------------
    namespace ANamespace
    {
        class ClassB
        {
        };
    
        class AClass
        {
            void aFunction(ClassB);
        };
    }
    
    void ANamespace::AClass::aFunction(ANamespace::ClassB)
    {
    }
    -------------------------------------
    
    
    The code is valid, reasonable(IMHO), C++ code.
    
    A weird thing: if I rename "AClass" to something else, such as "KClass", the
    warning seems to go away. Strange.
    
    
    Regards,
    Frans

On 2006-03-19 17:21:05 +0000, Frans Englich wrote:

    
    Let me know if test cases are useful, I got a heap of warnings which all are
    slight variants of the same type.
    
    
    Also, a related bug is:
    
    http://bugzilla.gnome.org/show_bug.cgi?id=335131
    
    
    Frans

On 2006-05-11 11:21:40 +0000, Christian Matuszewski wrote:

    I have the same problem.
    
    The bug:
    
    http://bugzilla.gnome.org/show_bug.cgi?id=319458
    
    seems to be a related bug too.

On 2006-08-11 18:44:09 +0000, Dimitri van Heesch wrote:

    Frans: I couldn't reproduce the problem with the latest CVS version, but
    also not with version 1.4.5, 1.4.6, or 1.4.7, so if you still see the
    problem, reopen the bug, re-check the above example, turn it into a self
    contained example (with config file) and attach that to this bug report.

On 2006-10-29 20:56:51 +0000, Frans Englich wrote:

    With 1.5.1 I still have tons of bogus warnings. Here's steps to reproduce:
    
    1. svn co svn://anonsvn.kde.org/home/kde/trunk/kdenonbeta/kdom/patternist
    2. cd patternist/
    3. doxygen
    4. view html/doxygen.log
    
    
    Frans

On 2006-10-29 21:26:46 +0000, Frans Englich wrote:

    I don't get why Doxygen must report these things. Why would the user want to
    know if doxygen does or does not find a certain class member/definition?
    (perhaps there is a reason, I don't know!) If it concerns the doxygen
    comments it can of be useful, but if it's only that doxygen thinks it's
    invalid C++, I think it should suppress the warnings(since doxygen doesn't
    get it right, and the user has the C++ compiler for verifying the code).
    
    
    Frans
    

On 2006-10-29 21:41:20 +0000, Dimitri van Heesch wrote:

    Hi Frans, 
    
    Thanks for your new example. I'll look into it.
    
    As to the why of the warning:
    
    Consider the following example:
    
    /** This is a class */
    class Test
    {
      public:
        void func();
    };
    
    /** this is a function */
    void Test::func()
    {
    }
    
    If doxygen cannot find a match between the declaration and definition of
    func(), it cannot add the documentation to the class Test. So the warning
    needs to be resolved in such cases. The same holds for the source browser
    (i.e. know at which line func() is defined).
    
    So such a warning typically means that doxygen has a problem with the code,
    which may or may not be a problem.
    
    

On 2014-01-25 15:43:41 +0000, chris.sherlock79@gmail.com wrote:

    According to the changelogs, this was fixed in 1.5.0!
    
    Do Doxygen maintainers not close their bugs? Thanks for fixing though.

**Comment by albert-github** [comment]
Seen the last comment I think the problem has been solved in the mean time.
