### ISSUE TITLE
API Names link in their own scope (Origin: bugzilla #335259)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2083]
status NEW severity *normal* in component *documentation* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2006-03-20 18:36:40 +0000, Jim OLeary wrote:

    This problem arose between 1.4.5 and 1.4.6.
    
    Doxygen has never linked to an API name that we cite in its own scope.
    Example:
    
    /**
      * The WhatEver class declares methods for...
      *
      */
    class WhatEver()
    {
    
    }
    
    With 1.4.6, WhatEver is linked.

**Comment by albert-github** [comment]
I think this is by design and can be prevented by meas of `%WhatEver` or by reformulation of the text.

I think this is usage
