### ISSUE TITLE
second class defined in C++ header not hyperlinked properly in source listing (Origin: bugzilla #335586)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2087]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2006-03-22 22:25:28 +0000, John Calcote wrote:

    Please describe the problem:
    The second class defined in a C++ header files is not hyperlinked correctly
    in
    the source listing for the header file (HTML output). The class name and the
    member function names are not hyperlinked. The first class is hyperlinked
    completely correctly, but classes other than the first are not. In my
    examples,
    the members contain inline code, and functions called within the inline
    bodies
    are marked up correctly, but the names of the members in the class are not.
    
    Steps to reproduce:
    1. define a C++ header with more than one class definition
    2. run doxygen with source listings enabled
    3. check the source listings for the header file.
    
    
    Actual results:
    non-primary class definition source listings are not hyperlinked.
    
    Expected results:
    all class names and member functions are hyperlinked to their respective
    documentation pages.
    
    Does this happen every time?
    yes
    
    Other information:
    The tests I've run all involve only a single header file - no C++ source
    files,
    but the documentation for these members are all contained within the header
    anyway, as the are all inline functions (this is a thin wrapper class around
    a
    set of handle-based C functions).

**Comment by albert-github** [comment]
I tried to reproduce the problem but I didn't succeed (with the 1.4.6 version that was current at that moment).
The description is a bit vague.
In the newer versions of doxygen the line counting has been improved and also the linking, so in that case the problems might have been solved in the mean time as well.

I think the problem can be set to not reproducible
