### ISSUE TITLE
HTML link incorrect when using tagfile (Origin: bugzilla #335614)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2089]
status NEW severity *minor* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2006-03-23 06:49:31 +0000, Torsten Ihben wrote:

    Please describe the problem:
    When I create a doxygen documentation and I reference to a different
    documentation using a tag file the created link is not correct. Instead
    of the correct form 'href="file:///c/..."' a link of the form
    'href="c:\..."' is created. Using Internet Explorer this is just fine,
    this browser corrects the link. But Firefox is not so forgiving; when I
    click on this link I receive an error message that "c is not a
    registered protocol".
    
    Steps to reproduce:
    1. Create a tag file for any documentation.
    2. Create a different documentation of a project in a different directory
    referencing items from the other documentation using this tag file.
    3. Open the second documentation in Firefox, click on a link referencing an
    item
    of the other documentation.
    
    
    Actual results:
    An error message "c is not a registered protocol" is displayed.
    
    Expected results:
    The correct page is shown
    
    Does this happen every time?
    Yes!
    
    Other information:
    I already posted this problem to the developer mailing list, but no one
    answered
    and nothing happened.

On 2006-03-24 19:04:20 +0000, Dimitri van Heesch wrote:

    What does your TAGFILES line in the config file look like? 

On 2006-03-27 07:02:32 +0000, Torsten Ihben wrote:

    (In reply to comment # 1)
    > What does your TAGFILES line in the config file look like? 
    
    My TAGFILES line looks like this:
    TAGFILES = C:\SRC\doxygen\Tagfile.tag=C:\SRC\doxygen\html
    
    The Tagfile looks fine, it contains lines like these:
    
      <compound kind="file">
        <name>AdditionalFile.cpp</name>
        <path>C:/src/</path>
        <filename>AdditionalFile_8cpp</filename>
        <includes id="stdafx_8h" name="stdafx.h" local="yes"
    imported="no">stdafx.h</includes>
        <includes id="stdinc_8h" name="stdinc.h" local="yes"
    imported="no">stdinc.h</includes>
        <includes id="AdditionalFile_8h" name="AdditionalFile.h" local="yes"
    imported="no">AdditionalFile.h</includes>
      </compound>
    
    The folder C:\SRC\doxygen\html contains the created doxygen documentation,
    there is for example a file AdditionalFile_8cpp.html and a
    AdditionalFile_8h.html.
    
    The created reference looks like this:
    
    <h1>OtherFile.cpp File Reference</h1><code>#include &quot;<a class="elRef"
    doxygen="Tagfile.tag:C:\SRC\doxygen\html/"
    href="C:\SRC\doxygen\html/stdafx_8h.html">stdafx.h</a>&quot;</code><br>
    
    This is not valid HTML, in HTML the href tag must begin with a protocol like
    file://.
    
    One thing I tried after I wrote this so far: I replaced the line "TAGFILES =
    C:\SRC\doxygen\Tagfile.tag=C:\SRC\doxygen\html" with "TAGFILES =
    C:\SRC\doxygen\Tagfile.tag=file:///C:/SRC/doxygen/html", since all hrefs are
    relative when no tagfile is used. When a tagfile is used it seems that the
    given path is simply added to the filename - and this was the solution!
    
    Perhaps you could change doxygen nevertheless: If a Windows path is given
    the path is converted to a hyperlink. Or you could state this in the
    documentation. There I can read "...loc2 can be relative or absolute paths
    or URLs" which is wrong: Absolute paths don't work.
    
    Regards, Torsten

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7286

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.17.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
