### ISSUE TITLE
Problem parsing comments and generation of "Reference" relations. (Origin: bugzilla #337348)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2109]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.3-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[test.cpp](https://sourceforge.net/projects/doxygen/files/attachments/bug337348_62787_test.cpp/download/download)_ (ID 62787)

On 2006-04-05 11:38:12 +0000, Janak Porwal wrote:

    Please describe the problem:
    Doxygen's lexer/parser's mechanism of parsing C++ comments has
    a bug that affects the generation of reference relations. 
    
    The following valid C++ comment confuses doxygen (due to the
    presence of the sequence /*/):  
    
    /*/////////////////////////////
      Test comment
    ///////////////////////////////*/
    
    Apparently, Doxygen treats the comment as unterminated (but only 
    as far as generation of reference relations is concerned).
    
    
    
    Steps to reproduce:
    The following is a simple example (which I have copied from a previous bug
    report which again had to do with generation of reference relations) 
    to reproduce the problem.
    
    (The REFERENCED_BY_RELATION and REFERENCES_RELATION options should be set to
    yes)
    
    Example:
    
    /** Example class. */
    
    class Example {
        /** sample member. */
        member(int arg1, int arg2) {}
    
        /** predicate */
        bool predicate() { return false; }
    };
    
    /*/////////////////////////////
      Test comment
    //////////////////////////////////*/
    
    /** test function.
         @param x The object
        */
    
    void testfn(Example *x) {
        if (x->predicate()) {
            return;
        }
        x->member();
    }
    
    
    Actual results:
    When "Test comment" is removed, the reference relations are correct. With
    the comment, the code following it is ignored, and hence the all 
    the 'references' and 'referenced by' relations are empty in this case.
    
    (I am curious as to why the problem manifests only in generating reference
    relations but not while generating other types of documentation).
    
    
    Expected results:
    
    
    Does this happen every time?
    
    
    Other information:

On 2006-04-05 11:41:10 +0000, Janak Porwal wrote:

    Created attachment 62787
    Test code
    
    C++ source file to reproduce the error.

On 2007-10-15 19:40:54 +0000, Dimitri van Heesch wrote:

    This bug's version was set to "latest". Since this is a moving target, I
    changed it to 1.5.3-SVN. If you believe this has already been fixed, then
    please change the status accordingly.

**Comment by albert-github** [comment]
With the current version (1.8.14) we get the message:
```
test1.cpp:25 warning: Reached end of file while still inside a (nested) comment. Nesting level 2 (probable line reference: 12, 10)
```

In the older versions there was no warning and but the rest was silently ignored.

I think the problem has been solved in the mean time by issuing a warning message.
