### ISSUE TITLE
Warning: no matching class member found... with nested c++ namespaces (Origin: bugzilla #337601)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2112]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2006-04-07 09:13:59 +0000, Guido Schneider wrote:

    Please describe the problem:
    When "using namespace" is used with an incomplete "path" of a nested
    namespace
    the the warning "Warning: no matching class member found..." appears.
    
    Steps to reproduce:
    1. Analyze the following source code with the options EXTRACT_..=YES.
    namespace level_1 {
      namespace level_2 {
        class CTest {
          CTest();
          ~CTest();
        };
      };
    };
    
    using namespace level_1;
    
    //doxygen "Warning: no matching class member found for..."
    using namespace level_2;
    
    //doxygen OK
    //using namespace level_1::level_2;
    
    CTest::CTest() {
    }
    
    CTest::~CTest() {
    }
    
    
    
    Actual results:
    These warnings appear:
    t.cpp(18) : Warning: no matching class member found for
      CTest::CTest()
    Possible candidates:
      level_1::level_2::CTest::CTest()
    t.cpp(21) : Warning: no matching class member found for
      CTest::~CTest()
    Possible candidates:
      level_1::level_2::CTest::~CTest()
    
    The documentation contains a namespace level_2.
    Th class member definitions are missing from the documentation.
    
    Expected results:
    No warnings should appear. 
    The documentation contains only the namespaces level_1 and level_1::level_2.
    The documentation contains only the class member definitions.
    
    Does this happen every time?
    Yes
    
    Other information:

**Comment by albert-github** [comment]
When only enabling `level_2` in the version 1.4.7 I get the warnings as indicated, with the version 1.9.3 these warnings are gone.
The output in the 1.9.3 version looks also OK to me.

I think the problem has been solved in the mean time.
