### ISSUE TITLE
mangled console output - probably need to flush cout or cerr (Origin: bugzilla #337697)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2113]
status NEW severity *minor* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2006-04-08 07:25:52 +0000, Ivan Vecerina wrote:

    When warnings are generated to the console output [e.g. for undocumented
    classes] they get interpersed with other output of doxygen. Some
    buffer/stream
    probably needs to be flushed.
    Example output:
    
    c:/dev/ivec_smc/mot/BufferedPath.cpp(98) : Warning: Member Impl(Device &dev,
    int
    bn, int const axes[], int pageSize, double
    ms_posFixedPeriod_or_negMinInterval)
    of class motion::BufferedPath::Impl is not documented.
    c:/dev/ivec_smc/mot/BufferedPath.cpp(78) : Warning: Member prog_ of class
    motion::BufferedPath::Impl is not documented.
    c:/dev/ivec_smc/mot/BufferedPath.cpp(79) : Warning: Member axisCount_ of
    class
    motion::BufferedPath::Impl is not documented.
    c:/dev/ivec_smc/mot/BufferedPath.cpp(80) : Warning: Member dataWidth_ of
    class
    motion::BufferedPath::Impl is not documented.
    c:/dev/ivec_smc/mot/BufferedPath.cpp(81) : Warning: Member pageSize_ of
    class
    motion::BufferedPath::Impl is not documented.
    c:/dev/ivec_smc/mot/BufferedPath.cpp(82) : Warning: Member
    ms_posFixedPeriod_or_negMinInterval_ of class motion::BufferedPath::Impl is
    not
    documented.
    c:/dev/ivec_smc/mot/BufferedPath.cpp(84) : Warning: Member data_ of class
    motion::BufferedPath::Impl is not documented.
    c:/dev/ivec_smc/mot/BufferedPath.cpp(85) : Warning: Member nextDataRow_ of
    class
    motion::BufferedPath::Impl is not documented.
    c:/dev/ivec_smcested compound StentScanRun::Impl...
    Generating docs for compound TraceConfig...
    Generating docs for compound TraceLenParams...
    Generating docs for compound TracePath...
    Generating docs for compound TraceScan...
    [...]
    Generating namespace member index...
    Generating page index...
    Generating graph info page...
    Generating graphical class hierarchy...
    /mot/BufferedPath.cpp(86) : Warning: Member log_ of class
    motion::BufferedPath::Impl is not documented.
    c:/dev/ivec_smc/mot/motion.h(26) : Warning: Member Device(std::string const
    &address=std::string()) of class motion::Device is not documented.
    c:/dev/ivec_smc/mot/motion.h(27) : Warning: Member ~Device() of class
    motion::Device is not documented.
    c:/dev/ivec_smc/mot/motion.h(45) : Warning: Member get() of class
    motion::Device
    is not documented.
    
    Observe how the line "c:/dev/ivec_smc/mot/BufferedPath.cpp(86)..." gets spit
    before /mot.  Other mix-ups seem to appear.
    
    Some buffer somewhere probably needs to be flushed explicitly, or both
    outputs
    (warnings and std output) should be sent to a same stream buffer...
    
    Other information:

**Comment by albert-github** [comment]
This is already quite an old issue and lately there have not been seen any of these type of split messages.

I think the problem has been solved in the mean time.
