### ISSUE TITLE
Can't link to an objective-c category (Origin: bugzilla #338209)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2115]
status NEW severity *normal* in component *documentation* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2006-04-12 12:36:33 +0000, Ben Suffolk wrote:

    Version : 1.4.6
    O/S : Darwin dexter.internal.vanilla.net 8.5.0 Darwin Kernel Version 8.5.0:
    Sun
    Jan 22 10:38:46 PST 2006; root:xnu-792.6.61.obj~1/RELEASE_PPC Power
    Macintosh
    powerpc
    
    Or to put it another way: Mac OS 10.4.5
    
    I have defined an informal protocol in the standard way: as a category of
    NSObject. I want to add an @see directive to link to the definition, but it
    does not work.
    
    Probably easier if I show you an example. I want to link to this page :-
    
http://www.usbdmx.com/LightsOnDocs/category_n_s_object(_l_o_dimmer_curve_view_delegate).html
    
    In the same was as the automatic link thats generated from this page :-
    
    http://www.usbdmx.com/LightsOnDocs/_l_o_dimmer_curve_view_delegate_8h.html
    
    Both the above pages are generated from the following header file (Most
    methods removed for size considerations) :-
    
    /**
     *
     * Informal protocol for delegates of the LODImmerCurveView
     *
     * @see LODimmerCurveView
     *
     **/
    @interface NSObject (LODimmerCurveViewDelegate)
    
    /**
     *
     * Called when editing of the dimmer curve started
     *
     * @param theCurve The dimemr curve being editied
     *
     **/
    - (void)didStartEditingDimmerCurve:(LODimmerCurve *)theCurve;
    
    @end;

**Comment by albert-github** [comment]
It indeed looks like, with a simple Doxyfile and some code found at https://www.usbdmx.com/LightsOn/doxygen/_l_o_dimmer_curve_view_8h-source.html: [example.tar.gz](https://github.com/doxygen/doxygen/files/8379632/example.tar.gz)
it looks like the link is missing. When setting `EXTRACT_ALL=YES` the link is present.
In the 1.9.3 version it looks like the link is present independent of the `EXTRACT_ALL` setting.

In the file https://www.usbdmx.com/LightsOn/doxygen/interface_n_s_object_07_l_o_dimmer_curve_view_delegate_08.html, which is build with doxygen 1.5.8, we see also the link present.

I think the problem has been solved in the mean time.
