### ISSUE TITLE
Using the @example tag does not generate an example link in function documentation (Origin: bugzilla #338754)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2120]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[example_link.jpg](https://sourceforge.net/projects/doxygen/files/attachments/bug338754_63670_example_link.jpg/download/download)_ (ID 63670)

On 2006-04-17 07:24:53 +0000, Alok Narula wrote:

    I have used the @example tag to link my examples with the APIs. Doxygen says
    that when I use the @example tag, the name of the file containing the
    example will be inserted just after the documentation and the name will link
    to the example file. When I run Doxygen I find that it has created the
    Examples list and I can open an example file by clicking its name in the
    Examples list. When I click a function, the backward link from the example
    to the function works. However, I cannot go from the function to the example
    because Doxygen hasn't created the forward link to the example file.
    
    To resolve this cross-referencing problem, I open the HTML version of the
    Example file created by Doxygen and get the anchor for the function that I
    want to cross-reference. Then I start an @htmlonly and @endhtmlonly block in
    my function documentation block and insert the link to the anchor inside
    this
    block. The cross-reference is created and I can link forward. But this is a
    work-around.

On 2006-04-17 07:48:39 +0000, Alok Narula wrote:

    Created attachment 63670
    Screenshot showing the link that should come below function documentation
    
    The screenshot attached with this bug shows the link that should appear
    before the function documentation. Because this link doesn't appear, I'm
    starting a documentation  block and using the @htmlonly and @endhtmlonly
    tags to create a link to the anchor created by Doxygen.
    
    Below is my modified documentation block. If Doxygen creates the link to the
    example as it should, then the @htmlonly and @endhtmlonly tags and the
    information included in these tags is redundant.
    
    /**
    
    * @ingroup ext_devices
    
    * The gmADAC_Init function initializes the DAC. To configure the DAC, the
    sampling frequency is set to 44.1 KHz and the data format is set to 24 bit
    right justified data. All the channels are enabled. Digital de-emphasis is
    disabled for all the channels. The attenuation for all channels is set to
    255 (No attenuation).
    
    
    
    * @retval ADAC_SUCCESS Audio DAC initialized successfully
    
    * @retval ADAC_ERR_ALREADY_INITIALIZED Audio DAC already initialized
    
    * @retval ADAC_ERR_OPEN_FAILED Unable to open Audio DAC
    
    *
    
    * @htmlonly
    
    <dl compact><dt><b>Examples: </b></dt><dd>
    
    <a class="el" href="_audio___d_a_c___example_8cpp-
    example.html#a0">AUDIO_DAC_Example.cpp</a>
    
    </dl>
    
    * @endhtmlonly
    
    */

**Comment by albert-github** [comment]
I think the problem here is the interpretation of the meaning of the `\example` command. In the documentation we see:
> Indicates that a comment block contains documentation for a source code example

in other words it is documenting a file, not placing a reference.

When we add a separate documentation block in one `INPUT` files with just the `\example` command and the file name of the example and in the documentation there will be with the functions  / classes / ... a reference to these entities as far as they are used in the example.

This looks like to work for the doxygen 1.4.4. version and also for the current, 1.12.0, doxygen version.

I think the problem is usage.
