### ISSUE TITLE
standard error output not working under windows (Origin: bugzilla #338829)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2121]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.3-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2006-04-17 21:57:32 +0000, Jason Remillard wrote:

    Please describe the problem:
    Under windows XP, running the doxygen program with a 2>&1 or 2>error.txt
    fails
    to capture the error messages to a file.
    
    Steps to reproduce:
    1. run doxygen from windows command line (cmd.exe) like this: doxygen 2>&1 >
    output.txt
    
    
    
    Actual results:
    The error/warning messages still comes out to the console rather than being
    put
    into output.txe.
    
    Expected results:
    All of the output to be placed into output.txt. I am attempting to setup an
    automated build and I cannot capture the full output of the program in my
    build log.
    
    Does this happen every time?
    yes
    
    Other information:
    If you want to send me a hint on where to look I can try to fix it.

**Comment by albert-github** [comment]
Handling stdout and stderr on windows is always tricky.
The order of the redirection is, to the best of my knowledge, so that a `2>&1` can only be used after file `1` i.e. `>` is given. 
Working syntax is:
`doxygen >output.txt 2>&1`

I think this is usage.
