### ISSUE TITLE
PATCH Call graph is not generated when using Filters (Origin: bugzilla #338929)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2122]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxygen.patch](https://sourceforge.net/projects/doxygen/files/attachments/bug338929_63819_doxygen.patch/download/download)_ (ID 63819)

On 2006-04-18 19:30:35 +0000, Greg Rowe wrote:

    Steps to reproduce:
    
    1.  Use a filter, such as the matlab filter linked from the doxygen.org
    website.
    2.  Turn on CALL_GRAPH
    3.  Turn OFF FILTER_SOURCE_FILES
    
    Doxygen will not create call graphs for functions.  If you turn
    FILTER_SOURCE_FILES on call graphs are generated as expected.
    
    I apologize for not submitting an appropriately formatted patch file.
    
    I believe an appropriate fix is to do the following:
    
    In doxygen.cpp::generateFileSources
              if (fd->generateSourceFile() && (!Config_getBool("CALL_GRAPH")))
              {
                   msg("Generating code for file %s...\n",fd->docName().data());
                   fd->writeSource(*outputList);
              }
              else if (!fd->isReference() &&
                 (Doxygen::parseSourcesNeeded || Config_getBool("CALL_GRAPH")))
              {
                   msg("Parsing code for file %s...\n",fd->docName().data());
                   fd->parseSource();
              }
    
    And in filedef.cpp::parseSource
              parseCode(devNullIntf,0,
                        fileToString(absFilePath(),
                                     Config_getBool("FILTER_SOURCE_FILES") ||
                                     Config_getBool("CALL_GRAPH")),
                        FALSE,0,this);

On 2006-04-18 19:40:23 +0000, Greg Rowe wrote:

    Created attachment 63819
    Proposed patch for call graphs to work correctly with filters
    
    This patch was made against 1.4.6.

On 2006-05-07 15:33:20 +0000, Dimitri van Heesch wrote:

    I don't think this fix is right. If you now set SOURCE_BROWSING to YES and
    CALL_GRAPH to NO, you do not get any sources, since the condition
    
    fd->generateSourceFile() && (!Config_getBool("CALL_GRAPH"))
    
    is false!
    
    Isn't it so that if doxygen parses the sources with FILTER_SOURCE_FILES off
    it doesn't parse the functions properly? so it has to stay enabled.
    
    I guess the proper solution would be to parse the sources two times. Once
    for output (i.e. do fd->writeSource() with the filtering and call graph
    extraction disabled) and once for call graphs (with output disabled and
    filtering enabled).
    
    I'm not sure FILTER_SOURCE_FILES will always imply that a two pass parsing
    is required, so I think another config option would be required to select
    the desired behaviour.

**Comment by albert-github** [comment]
I can imagine that hen using a filter there is a problem with a call graph due to the fact that the filter might have changed some names and therefore there is no correct call graph generated (or no call graph at all). To determine the doxygen needs the filtered sources again.
I was able to reproduce the problem with the following source (aa.cpp):
```
/// \file

/// \brief the first fie
/// \details the first fie
void fie1(){}

/// \brief the second fie
/// \details the second fie
void fie2() {fie1()}



/// \brief the third fie
/// \details the third fie
void fie3() {fie2()}
```
and the following settings:
```
QUIET = YES
CALL_GRAPH = YES
CALLER_GRAPH = YES
HAVE_DOT = YES
INPUT_FILTER = "sed -e 's/fie/gie/g'"
FILTER_SOURCE_FILES = YES
```
when `FILTER_SOURCE_FILES = YES` the call graph is shown (between the `gie...` functions), with `FILTER_SOURCE_FILES = NO` no call graph is shown.

Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/10094357/example.tar.gz)

I think the problem is not a bug but usage.
