### ISSUE TITLE
The call graph misses some calls (Origin: bugzilla #339031)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2123]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2006-04-19 14:05:49 +0000, Eric Hamilton wrote:

    In doxygen version 1.4.6-NO a generated call graph (dot format) is missing
    one of the four functions called. I have a short function that shows the
    problem. How do I attach it to this bug report?

**Comment by albert-github** [comment]
The bug report is missing a test case so it is impossible to tell where the problem comes from.

I think the issue should be closed as incomplete.
