### ISSUE TITLE
Multiple and identical \name sections listed multiple times (Origin: bugzilla #339523)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2127]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2006-04-24 05:28:16 +0000, David Baird wrote:

    Please describe the problem:
    If I list \name sections in my class definition with the same heading
    several
    times, then the documentation of the class lists the heading several times.
    This
    is a problem when the definition of a class spans several files, or when
    grouping class members automatically in a source file filter.
    
    Steps to reproduce:
    1. Create several \name sections of the same header in a class
    2. Run Doxygen
    
    
    
    Actual results:
    In the Class definition output, the header is repeated
    
    Expected results:
    Class members grouped with several \name sections of the same header should
    be
    listed in the group, but the group should combine all members under a
    unified
    heading.
    
    Does this happen every time?
    Yes.
    
    Other information:
    This is useful when filtering non-supported languages which behave like C++,
    but
    have more classifications of function like members. My example is Vera. I
    have a
    source filter, and want to create more member class groupings for language
    elements which look like functions, but are not.

**Comment by albert-github** [comment]
I tried this with a small example:
```
/// \file

/// the class
class cls
{
  public:
  /// @name The name
  /// @{

  /// the fie 1
  void fie1();
  /// the fie 2
  void fie2();

  /// @}

  /// @name The name1
  /// @{

  /// the fie 1_1
  void fie1_1();
  /// the fie 2_1
  void fie2_1();

  /// @}

  /// @name The name
  /// @{

  /// the fie 1_2
  void fie1_2();
  /// the fie 2_2
  void fie2_2();

  /// @}
};
```
and with the doxygen 1.4.5 version I got:
![image](https://github.com/user-attachments/assets/50091383-6725-4998-8007-328ff9e82c63)

and with the current 1.12.0 doxygen version I got:
![image](https://github.com/user-attachments/assets/4e35f536-69f8-449f-afd0-ffc2a8473475)

Example: [example.tar.gz](https://github.com/user-attachments/files/17880036/example.tar.gz)


So I think the problem is solved in the mean time
