### ISSUE TITLE
@code: static_cast, const_cast, etc C++ keywords (Origin: bugzilla #340202)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2128]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2006-04-30 15:36:36 +0000, Frans Englich wrote:

    In C++, the following identifiers are keywords:
    
    static_cast
    const_cast
    dynamic_cast
    reinterpret_cast
    
    I think they should be recognized, as such, just as for 'for' and 'while'
    is. That is, when those appears inside @code/@endcode sections, they should
    be marked up as such.
    
    
    Regards,
    Frans

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7275

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.17.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
