### ISSUE TITLE
Implement differential generation of documentation (Origin: bugzilla #341581)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2138]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2006-05-12 20:00:38 +0000, ergosys@gmail.com wrote:

    Differential generation (don't regenerate documentation and intermediate
    files
    which aren't affected by source changes) would save most users a lot of
    time,
    especially when doing frequent round-trips between editting and doxygen.

On 2007-08-09 10:52:16 +0000, HaJo Gurt wrote:

    For checking the doxygen-output while working on a single file,
    it might be sufficent if doxygen could be made to process
    just this one file, i.e. by specifying its filename
    on the commandline.

**Comment by albert-github** [comment]
This would be very complex as a change in a source file can have an influence on other files as well (we can think here about call / caller graphs, grouping etc.)
