### ISSUE TITLE
java 'this' hides call (Origin: bugzilla #342813)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2147]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2006-05-24 15:04:31 +0000, relson@osagesoftware.com wrote:

    Please describe the problem:
    Doxygen shows method calls differently for the following java constructs:
    
       instance_variable.method1()
       this.instance_variable.method2()
    
    The first will be shown as "here.method --> there.method1" and the second
    isn't
    show at all
    
    Steps to reproduce:
    Here are the files:
    
    #### Begin file Door.java ####
    public class Door {
    
        public Door ( ) {
    	// dummy
        }
    
        public void open ( ) {
    	// dummy
        }
    
        public void close ( ) {
    	// dummy
        }
    }
    #### End file Door.java ####
    
    #### Begin file Main.java ####
    public class Main {
    
        private Port port;
        private Door door;
    
        public static void main(String[] args) {
    	port = new Port();
    	door = new Door();
    
    	port.open();
    	this.port.close();
        }
    }
    #### End file Main.java ####
    
    #### Begin file Port.java ####
    public class Port {
    
        public Port ( ) {
    	// dummy
        }
    
        public void open ( ) {
    	// dummy
        }
    
        public void close ( ) {
    	// dummy
        }
    }
    #### End file Port.java ####
    
    #### Begin file Doxyfile ####
    
    # Doxyfile 1.4.6
    
    #---------------------------------------------------------------------------
    # Project related configuration options
    #---------------------------------------------------------------------------
    PROJECT_NAME           = "Doxygen Test"
    PROJECT_NUMBER         = 
    OUTPUT_DIRECTORY       = c:/80561/Doxytest
    CREATE_SUBDIRS         = NO
    OUTPUT_LANGUAGE        = English
    USE_WINDOWS_ENCODING   = YES
    BRIEF_MEMBER_DESC      = YES
    REPEAT_BRIEF           = YES
    ABBREVIATE_BRIEF       = "The $name class" \
                             "The $name widget" \
                             "The $name file" \
                             is \
                             provides \
                             specifies \
                             contains \
                             represents \
                             a \
                             an \
                             the
    ALWAYS_DETAILED_SEC    = NO
    INLINE_INHERITED_MEMB  = NO
    FULL_PATH_NAMES        = NO
    STRIP_FROM_PATH        = c:/80561/Doxytest
    STRIP_FROM_INC_PATH    = 
    SHORT_NAMES            = NO
    JAVADOC_AUTOBRIEF      = NO
    MULTILINE_CPP_IS_BRIEF = NO
    DETAILS_AT_TOP         = NO
    INHERIT_DOCS           = YES
    SEPARATE_MEMBER_PAGES  = NO
    TAB_SIZE               = 8
    ALIASES                = 
    OPTIMIZE_OUTPUT_FOR_C  = YES
    OPTIMIZE_OUTPUT_JAVA   = YES
    BUILTIN_STL_SUPPORT    = NO
    DISTRIBUTE_GROUP_DOC   = NO
    SUBGROUPING            = YES
    #---------------------------------------------------------------------------
    # Build related configuration options
    #---------------------------------------------------------------------------
    EXTRACT_ALL            = YES
    EXTRACT_PRIVATE        = YES
    EXTRACT_STATIC         = YES
    EXTRACT_LOCAL_CLASSES  = YES
    EXTRACT_LOCAL_METHODS  = YES
    HIDE_UNDOC_MEMBERS     = NO
    HIDE_UNDOC_CLASSES     = NO
    HIDE_FRIEND_COMPOUNDS  = NO
    HIDE_IN_BODY_DOCS      = NO
    INTERNAL_DOCS          = NO
    CASE_SENSE_NAMES       = NO
    HIDE_SCOPE_NAMES       = NO
    SHOW_INCLUDE_FILES     = YES
    INLINE_INFO            = YES
    SORT_MEMBER_DOCS       = YES
    SORT_BRIEF_DOCS        = NO
    SORT_BY_SCOPE_NAME     = NO
    GENERATE_TODOLIST      = NO
    GENERATE_TESTLIST      = NO
    GENERATE_BUGLIST       = NO
    GENERATE_DEPRECATEDLIST= NO
    ENABLED_SECTIONS       = 
    MAX_INITIALIZER_LINES  = 30
    SHOW_USED_FILES        = YES
    SHOW_DIRECTORIES       = YES
    FILE_VERSION_FILTER    = 
    #---------------------------------------------------------------------------
    # configuration options related to warning and progress messages
    #---------------------------------------------------------------------------
    QUIET                  = NO
    WARNINGS               = YES
    WARN_IF_UNDOCUMENTED   = YES
    WARN_IF_DOC_ERROR      = YES
    WARN_NO_PARAMDOC       = NO
    WARN_FORMAT            = "$file:$line: $text"
    WARN_LOGFILE           = 
    #---------------------------------------------------------------------------
    # configuration options related to the input files
    #---------------------------------------------------------------------------
    INPUT                  = C:/80561/Doxytest
    FILE_PATTERNS          = *.java
                             *.dox
    RECURSIVE              = YES
    EXCLUDE                = 
    EXCLUDE_SYMLINKS       = NO
    EXCLUDE_PATTERNS       = 
    EXAMPLE_PATH           = 
    EXAMPLE_PATTERNS       = *
    EXAMPLE_RECURSIVE      = NO
    IMAGE_PATH             = 
    INPUT_FILTER           = 
    FILTER_PATTERNS        = 
    FILTER_SOURCE_FILES    = NO
    #---------------------------------------------------------------------------
    # configuration options related to source browsing
    #---------------------------------------------------------------------------
    SOURCE_BROWSER         = YES
    INLINE_SOURCES         = NO
    STRIP_CODE_COMMENTS    = YES
    REFERENCED_BY_RELATION = YES
    REFERENCES_RELATION    = YES
    USE_HTAGS              = NO
    VERBATIM_HEADERS       = YES
    #---------------------------------------------------------------------------
    # configuration options related to the alphabetical class index
    #---------------------------------------------------------------------------
    ALPHABETICAL_INDEX     = YES
    COLS_IN_ALPHA_INDEX    = 5
    IGNORE_PREFIX          = 
    #---------------------------------------------------------------------------
    # configuration options related to the HTML output
    #---------------------------------------------------------------------------
    GENERATE_HTML          = YES
    HTML_OUTPUT            = 
    HTML_FILE_EXTENSION    = .html
    HTML_HEADER            = 
    HTML_FOOTER            = 
    HTML_STYLESHEET        = 
    HTML_ALIGN_MEMBERS     = YES
    GENERATE_HTMLHELP      = NO
    CHM_FILE               = 
    HHC_LOCATION           = 
    GENERATE_CHI           = NO
    BINARY_TOC             = NO
    TOC_EXPAND             = NO
    DISABLE_INDEX          = NO
    ENUM_VALUES_PER_LINE   = 4
    GENERATE_TREEVIEW      = YES
    TREEVIEW_WIDTH         = 250
    #---------------------------------------------------------------------------
    # configuration options related to the LaTeX output
    #---------------------------------------------------------------------------
    GENERATE_LATEX         = NO
    LATEX_OUTPUT           = latex
    LATEX_CMD_NAME         = latex
    MAKEINDEX_CMD_NAME     = makeindex
    COMPACT_LATEX          = NO
    PAPER_TYPE             = a4wide
    EXTRA_PACKAGES         = 
    LATEX_HEADER           = 
    PDF_HYPERLINKS         = NO
    USE_PDFLATEX           = NO
    LATEX_BATCHMODE        = NO
    LATEX_HIDE_INDICES     = NO
    #---------------------------------------------------------------------------
    # configuration options related to the RTF output
    #---------------------------------------------------------------------------
    GENERATE_RTF           = NO
    RTF_OUTPUT             = rtf
    COMPACT_RTF            = NO
    RTF_HYPERLINKS         = NO
    RTF_STYLESHEET_FILE    = 
    RTF_EXTENSIONS_FILE    = 
    #---------------------------------------------------------------------------
    # configuration options related to the man page output
    #---------------------------------------------------------------------------
    GENERATE_MAN           = NO
    MAN_OUTPUT             = man
    MAN_EXTENSION          = .3
    MAN_LINKS              = NO
    #---------------------------------------------------------------------------
    # configuration options related to the XML output
    #---------------------------------------------------------------------------
    GENERATE_XML           = NO
    XML_OUTPUT             = xml
    XML_SCHEMA             = 
    XML_DTD                = 
    XML_PROGRAMLISTING     = YES
    #---------------------------------------------------------------------------
    # configuration options for the AutoGen Definitions output
    #---------------------------------------------------------------------------
    GENERATE_AUTOGEN_DEF   = NO
    #---------------------------------------------------------------------------
    # configuration options related to the Perl module output
    #---------------------------------------------------------------------------
    GENERATE_PERLMOD       = NO
    PERLMOD_LATEX          = NO
    PERLMOD_PRETTY         = YES
    PERLMOD_MAKEVAR_PREFIX = 
    #---------------------------------------------------------------------------
    # Configuration options related to the preprocessor   
    #---------------------------------------------------------------------------
    ENABLE_PREPROCESSING   = YES
    MACRO_EXPANSION        = NO
    EXPAND_ONLY_PREDEF     = NO
    SEARCH_INCLUDES        = YES
    INCLUDE_PATH           = 
    INCLUDE_FILE_PATTERNS  = 
    PREDEFINED             = 
    EXPAND_AS_DEFINED      = 
    SKIP_FUNCTION_MACROS   = YES
    #---------------------------------------------------------------------------
    # Configuration::additions related to external references   
    #---------------------------------------------------------------------------
    TAGFILES               = 
    GENERATE_TAGFILE       = 
    ALLEXTERNALS           = NO
    EXTERNAL_GROUPS        = YES
    PERL_PATH              = /usr/bin/perl
    #---------------------------------------------------------------------------
    # Configuration options related to the dot tool   
    #---------------------------------------------------------------------------
    CLASS_DIAGRAMS         = NO
    HIDE_UNDOC_RELATIONS   = YES
    HAVE_DOT               = YES
    CLASS_GRAPH            = YES
    COLLABORATION_GRAPH    = YES
    GROUP_GRAPHS           = YES
    UML_LOOK               = NO
    TEMPLATE_RELATIONS     = NO
    INCLUDE_GRAPH          = YES
    INCLUDED_BY_GRAPH      = YES
    CALL_GRAPH             = YES
    GRAPHICAL_HIERARCHY    = YES
    DIRECTORY_GRAPH        = YES
    DOT_IMAGE_FORMAT       = png
    DOT_PATH               = 
    DOTFILE_DIRS           = 
    MAX_DOT_GRAPH_WIDTH    = 1024
    MAX_DOT_GRAPH_HEIGHT   = 1024
    MAX_DOT_GRAPH_DEPTH    = 1000
    DOT_TRANSPARENT        = NO
    DOT_MULTI_TARGETS      = NO
    GENERATE_LEGEND        = YES
    DOT_CLEANUP            = YES
    #---------------------------------------------------------------------------
    # Configuration::additions related to the search engine   
    #---------------------------------------------------------------------------
    SEARCHENGINE           = NO
    
    
    Actual results:
    only method1 is shown as being referenced from main.
    
    Expected results:
    I'd expect to see references to both method1 and method2
    
    Does this happen every time?
    yes
    
    Other information:

On 2007-01-26 15:56:41 +0000, Kevin McBride wrote:

    *** Bug 398942 has been marked as a duplicate of this bug. ***

**Comment by albert-github** [comment]
With version 1.4.6 I see that in `main` `open` is referenced but not `close`.
In version 1.9.1 I see that both `open` and close` are referenced in `main`.

I think the problem has been solved in the mean time.
