### ISSUE TITLE
Function not linked when there are extra spaces (Origin: bugzilla #344742)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2164]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.3-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2006-06-13 07:38:52 +0000, Murray Cumming wrote:

    The first of these lines generates a link, but the second one (with 2 spaces
    between the parameter type and name) doesn't:
    
     /** 
     * @see void Something::do_something(int thing) 
     * @see void Something::do_something(int  thing)
     */

On 2007-10-15 19:40:55 +0000, Dimitri van Heesch wrote:

    This bug's version was set to "latest". Since this is a moving target, I
    changed it to 1.5.3-SVN. If you believe this has already been fixed, then
    please change the status accordingly.

**Comment by albert-github** [comment]
With version 1.5.3 the second reference is not hyperlinked (given an original definition with one space), with version 1.8.16 both versions are hyperlinked.

I think the problem has been solved in the mean time.
