### ISSUE TITLE
Separate line info from code in code listing (Origin: bugzilla #345661)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2181]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[separateLineListing.html](https://sourceforge.net/projects/doxygen/files/attachments/bug345661_67848_separateLineListing.html/download/download)_ (ID 67848)
- _[dynamic_linenumbers.tgz](https://sourceforge.net/projects/doxygen/files/attachments/bug345661_68428_dynamic_linenumbers.tgz/download/download)_ (ID 68428)

On 2006-06-22 15:10:34 +0000, Frans Englich wrote:

    When selecting code in code listings, one can't do it without also selecting
    the column containing the line numbers. This is highly unpractical since one
    can't simply copy&paste.
    
    I think this can be fixed with CSS or tables. Visit any of the code snippets
    listed here:
    http://rafb.net/paste/results.html
    
    This is achieved with tables, although a CSS solution is preferable.
    
    
    Frans

On 2006-06-22 15:17:47 +0000, Frans Englich wrote:

    Created attachment 67848
    A reduced sample demonstrating how separating the two columns is done and
    looks.

On 2006-07-05 19:39:46 +0000, Dimitri van Heesch wrote:

    Good idea, but to simplify code generation it is easier to keep the lines
    and the code together.
    
    Another option with the same effect would be to allow the user to toggle the
    visibility of the line numbers. This can be done using a bit of DHTML and
    Javascripting.
    
    I'll attached a handcrafted prototype. Let me know what you think.

On 2006-07-05 19:41:38 +0000, Dimitri van Heesch wrote:

    Created attachment 68428
    Demonstration of dynamic toggling of line number visibility

On 2006-07-05 20:12:27 +0000, Frans Englich wrote:

    Nice alternative. Comments:
    
    Perhaps it would be less visually intrusive if the check box was at the
    bottom? On the other hand that makes it harder to find, but this feature is
    perhaps rarely needed.
    
    In either case I think it has some drawbacks:
    
    * It's a dynamic interface. That the interface changes is a usability
    drawback.
    * You can't look at the line numbers and select text at the same time. One
    must /first/ disable, and /then/ select. And do that back and forth, in the
    worst case. The user must be aware of this enable/disable thingy.
    
    So I think a static view is preferred, but this dynamic one is better than
    nothing.
    
    So if changing the table layout is too labour intensive, can CSS be used,
    perhaps? I know it has stuff for numbering things, at least.
    
    
    Frans

**Comment by albert-github** [comment]
With version 1.4.7 the case was that when doing a multi=line select the line numbers were selected as well.
With version 1.9.1 this was not the case anymore. One, annoying, space at the beginning of each line was present but this has been fixed as well but is not yet released.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.2.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
