### ISSUE TITLE
Add support for allowing a portion of initial white-space to be ignored in @code/@verbatim blocks (Origin: bugzilla #346917)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2196]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2006-07-07 15:58:34 +0000, Timothy Strelchun wrote:

    It would be very helpful for source code formatting purposes to add support
    for allowing a user-defined portion of initial white-space to be ignored in
    @code/@verbatim blocks.
    
    If there was a new doxygen command set added (such as @matchstartingcolumn
    and @ignorestartingcolumn) it could be used to control the state of how
    documentation was generated for subsequent @code/@verbatim blocks.
    
    If @matchstartingcolumn was defined, it would result in the initial portion
    of the white-space on subsequent lines in the @code/@verbatim block (until
    the @endcode/@endverbatim) to be ignored.  The initial portion of the white-
    space that is ignored and not used in the generated documentation would be
    defined as all white-space up to the column in which the @code/@verbatim
    command was located.  For example, if the following was in a header
    processed by doxygen:
    
    /**
            @matchstartingcolumn
            @code
            IFXRESULT   IFXCreateComponent( 
                            IFXREFCID   componentId, 
                            IFXREFIID   interfaceId, 
                            void**      ppInterface );
            @endcode
    */
    
    Then the resulting code block in the HTML would be:
    
    IFXRESULT   IFXCreateComponent( 
                    IFXREFCID   componentId, 
                    IFXREFIID   interfaceId, 
                    void**      ppInterface );
    
    The following documentation would be the default behavior and if
    @ignorestartingcolumn was used instead (this is the current behavior):
    
            IFXRESULT   IFXCreateComponent( 
                            IFXREFCID   componentId, 
                            IFXREFIID   interfaceId, 
                            void**      ppInterface );
    
    This would allow the commenting in source code to look nicer and be more
    readable for developers looking at the actual source code.
    
    BTW:  This was a feature request embedded in issue # 168903 not
    addressed/discussed.

On 2008-07-11 09:03:02 +0000, Jens Miltner wrote:

    I'd like to second this request:
    our documentation is not only read in the 'final' production form, but also
    by developers from the header files.
    Often times, this requires some pretty heavy inset for the documentation
    comments, e.g. if it's a @code section in an @note of the documentation for
    a member of a class in a namespace - that's about 4 tab stops inset. So
    essentially, we often end up with documentation formatted like this:
    
    namespace foo {
      class bar {
         public:
            /*! The die method
                  @note never do this:
                               @code
                               bar->die();
                               @endcode
            */
            void die();
       };
    }
    
    Obviously, the current (1.5.3) version produces a code section that has a
    _lot_ of leading white space!
    In this case, my intuitive expectation would be to have no leading space in
    the code section (the code section is already correctly aligned with the
    @note paragraph).

**Comment by albert-github** [comment]
For the first example we see with the doxygen 1.4.6 version:
![image](https://github.com/doxygen/doxygen/assets/5223533/13a64f14-b1ae-4d9a-a229-a16a8412f6cb)

and with the current, 1.9.8 version:
![image](https://github.com/doxygen/doxygen/assets/5223533/cb7f7a8e-9280-4754-b6a0-759c1f01eab3)

For the second example we see with the dpxygen 1.5.3 version:
![image](https://github.com/doxygen/doxygen/assets/5223533/1749f23c-a03c-45c4-a828-70aac7217baf)

and with the current, 1.9.8 version:
![image](https://github.com/doxygen/doxygen/assets/5223533/b2c20e75-8801-4779-b539-50ead211e2d2)


So I think the problem is solved in the mean time as the "excessive" white space at the beginning of the code block is automatically removed.
