### ISSUE TITLE
Protected attributes being classified as properties. (Origin: bugzilla #358341)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2251]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.3-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2006-09-29 17:07:09 +0000, Ian Sellon wrote:

    Please describe the problem:
    When using doxygen on C# source files, you must declare all protected
    members before defining any properties. After the first property
    declaration, any subsequent protected member declarations are listed as
    Properties in the output.
    
    Steps to reproduce:
    1. Create a C# source file.
    2. Declare a property.
    3. Declare a protected member.
    4. Generate output.
    
    
    Actual results:
    Two properties will be listed in the output.
    
    Expected results:
    A property and a protected attribute will be listed in the output.
    
    Does this happen every time?
    Always.
    
    Other information:

On 2007-10-15 19:40:58 +0000, Dimitri van Heesch wrote:

    This bug's version was set to "latest". Since this is a moving target, I
    changed it to 1.5.3-SVN. If you believe this has already been fixed, then
    please change the status accordingly.

**Comment by albert-github** [comment]
With version 1.4.7 (the version at the moment of writing the issue)  I was able to reproduce the problem.
The problem was gone in version 1.5.3 (and in the current version, 1.8.17)

I think the problem has been solved in the mean time.
