### ISSUE TITLE
Warning: no matching class member found (Origin: bugzilla #362945)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2262]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.3-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2006-10-17 19:40:00 +0000, Paul F. Kunz wrote:

    Starting with version 1.5.0, I get many additionnal warings of the type
    
    /home/pfkeb/hippodraw/datasrcs/DataSource.cxx:297 Warning: no matching class
    member found for
      void setLabels(conststd::vector< std::std::string > &v)
    Possible candidates:
      virtual void hippodraw::DataSource::setLabels(const std::vector<
    std::string > &v)
    
    Note no space between `const' and `std::'.   The source code point at by
    this message is
    
    void
    DataSource::
    setLabels ( const std::vector < std::string > & v )
    {
    
    There's a "using namespace hippodraw;" before the first member function
    implementation in this .cxx file.

On 2006-10-17 21:21:00 +0000, Dimitri van Heesch wrote:

    Hi Paul,
    
    I've been able to reproduce the issue. As it was easy to fix I decided to
    re-release doxygen (under the same version number) but with this issue
    fixed. Can you check for me if this issue is not indeed fixed?
    

On 2006-10-17 22:28:41 +0000, Paul F. Kunz wrote:

    Indeed fixed.   Thanks for super turnaround on this bug.

On 2006-10-17 22:43:21 +0000, Paul F. Kunz wrote:

    The fix also fixed some other warnings of similar nature that did not occur
    very often, so I could never fin it down.

On 2007-10-15 19:40:59 +0000, Dimitri van Heesch wrote:

    This bug's version was set to "latest". Since this is a moving target, I
    changed it to 1.5.3-SVN. If you believe this has already been fixed, then
    please change the status accordingly.

**Comment by albert-github** [comment]
According to the description it is solved in the mean time
