### ISSUE TITLE
Internal error: invalid header for entry in storage file (Origin: bugzilla #363219)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2267]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.3-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2006-10-18 19:35:20 +0000, Paul F. Kunz wrote:

    OS Red Hat Enterprise 3
    
    I get
    
    Building namespace list...
    Building file list...
    Searching for included using directives...
    Building class list...
    Internal error: Invalid header for entry in storage file: 0. Disk full?
    make[1]: *** [libdocs] Error 1
    make[1]: Leaving directory `/u1/ki/pfkeb/hippodraw-BUILD/doc'
    make: *** [docs] Error 2
    
    Compilation exited abnormally with code 2 at Wed Oct 18 12:26:35
    
    There's plenty of disk space ...
    
    ki-rh19> df
    Filesystem           1K-blocks      Used Available Use% Mounted on
    /dev/sda1             10080488   3934728   5633692  42% /
    none                    511972         0    511972   0% /dev/shm
    /dev/sda2              1004052     27900    925148   3% /scswork
    /dev/sda3              1004052     17280    935768   2% /tmp
    /dev/sda8             61796904  13756260  44901548  24% /u1
    /dev/sda5              1004024    728604    224416  77% /usr/vice/cache
    /dev/sda6              1004024    127504    825516  14% /var
    AFS                    9000000         0   9000000   0% /afs
    mailstore:/vol/vol0/mail
                          31457280  28613952   2843328  91%
    /a/mailstore/vol/vol0/mail
    surrey01:/vol/vol2/g.ek.cvs
                           2097152   1831232    265920  88%
    /a/surrey01/vol/vol2/g.ek.cvs
    surrey10:/vol/vol0/g.ki.ki04
                         209715200 182131136  27584064  87%
    /a/surrey10/vol/vol0/g.ki.ki04
    ki-rh19>
    
    Same code does not have from on my Fedora Core 5 laptop.

On 2006-10-18 19:45:28 +0000, Paul F. Kunz wrote:

    For this bug, I also have no problem with Red Hat Enterprise 4.
    Something to do with the 2.4 kernal on RHEL3 ?
    

On 2006-10-19 05:16:59 +0000, Kevin McBride wrote:

    Is this bug replicatable using the following tarball?
    
    ftp://ftp.slac.stanford.edu/users/pfkeb/hippodraw/HippoDraw-1.18.8.tar.gz

On 2006-10-19 15:17:11 +0000, Paul F. Kunz wrote:

    No it doesn't, that's curious, hardly any changes between that release and
    my CVS HEAD.
    
    Upon further investigation, the crash occurs when I do
    
    > make -j2 docs
    
    on a dual processor RHEL 3 machine, but not when I leave off the `-j2'.   As
    you probably know, the -j2 option allows make to start multiple threads.

On 2006-10-19 19:00:35 +0000, Dimitri van Heesch wrote:

    Ah, I think I understand.
    
    Running "make docs" would start doxygen I suppose.
    
    Running make -j2 runs make twice and thereby possibly also runs doxygen
    twice on the same sources. This is a bit silly but used to be quite
    harmless.
    
    However, since doxygen now uses a temporary file to store its intermediate
    findings, both instances of doxygen will write to the same file! Hence that
    files gets corrupted and doxygen stops with an error when reading back the
    data.
    
    I guess I could make each doxygen process use a different temp file, by
    using the process id in the name (or something similar).
    
    In the meantime: don't run doxygen twice on the same input! 
    

On 2006-10-19 19:13:17 +0000, Paul F. Kunz wrote:

    Yes, "make docs" starts doxygen.
    
    Running make -j2 allows make to start up to two thread in parallel, and in
    the make file I have
    
    docs: helpdocs libdocs
    
    helpdocs: userdocs pydocs
    
    So, yes, doxygen is run on the helpdocs target in parallel with the libdocs
    target (the first is user documentation, the second lis library
    documentation).
    
    > I guess I could make each doxygen process use a different temp file, by
    using
    > the process id in the name (or something similar).
    
    I believe that is the usual practise.   Theres's some standard function to
    get a tmp file name that is unique.   I think it is tmpfile(),
    
    
    > In the meantime: don't run doxygen twice on the same input! 
    
    Understood.   Thanks for looking into this so quickly.
    

On 2007-10-15 19:40:59 +0000, Dimitri van Heesch wrote:

    This bug's version was set to "latest". Since this is a moving target, I
    changed it to 1.5.3-SVN. If you believe this has already been fixed, then
    please change the status accordingly.

**Comment by albert-github** [comment]
The complete handling of the "entry" has been changed in the mean time and no storing is done anymore.

I think the problem has been solved in the mean time.
