### ISSUE TITLE
Bulleted lists with links don't work (Origin: bugzilla #363253)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2269]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.3-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2006-10-18 21:52:28 +0000, Dustin Voss wrote:

    A comment such as 
    
    /**
    Here are sub-pages
    
    - @subpage page1
    - @subpage page2
    - @subpage page3
    */
    
    shows up as
    
      Here are sub-pages
    
      - Page 1 Title - Page 2 Title - Page 3 Title
    
    instead of a bulleted list as expected.

On 2006-10-18 22:02:47 +0000, Dustin Voss wrote:

    /**
    - @ref ref1
    - @ref ref2
    */
    seems to work fine.

On 2006-10-19 19:08:00 +0000, Dimitri van Heesch wrote:

    I set the severity to normal as this is a layout inconvenience that (I
    guess) can be worked-around using \li style lists.

On 2006-10-19 20:47:16 +0000, Dustin Voss wrote:

    Yes, this is true. Forgot about \li, I've confirmed that it is a workaround.

On 2006-10-19 21:04:48 +0000, Dustin Voss wrote:

    ...except for indented lists, such as
    
    - Here is a group
      - \subpage a
      - \subpage b
    - Here is another group
      - \subpage c
    
    Using \li instead of a hyphen does not preserve indentation, though, at
    least for HTML docs, you can use <ul> and <li>.

On 2007-10-15 19:40:59 +0000, Dimitri van Heesch wrote:

    This bug's version was set to "latest". Since this is a moving target, I
    changed it to 1.5.3-SVN. If you believe this has already been fixed, then
    please change the status accordingly.

**Comment by albert-github** [comment]
I tried to reproduce the problem but failed with the different 1.5.x and 1.4.x versions all looked OK to me.
Also with the current version 1.9.1 the output looks OK.

So either the problem is not reproducible or solved in the mean time.
