### ISSUE TITLE
Tooltips are not shown in dot-generated graphs (Origin: bugzilla #363762)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2274]
status ASSIGNED severity *minor* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2006-10-20 20:53:10 +0000, Topi MÃ¤enpÃ¤Ã¤ wrote:

    Please describe the problem:
    Dot-generated graphs miss the title attribute in the image maps. This is
    most likely because doxygen seems to use the -Timap output type that is
    intended for server-side image maps and therefore omits the tooltips. Recent
    dot versions support -Tcmapx, which should be used for client-side maps.
    
    Steps to reproduce:
    1. Create a dot graph that has a "tooltip" attribute within a @dot/@enddot
    pair.
    2. Generate the documentation with doxygen.
    3. Look at the html source. The "title" attribute in the image map is
    missing.
    
    
    Actual results:
    
    
    Expected results:
    
    
    Does this happen every time?
    
    
    Other information:

On 2018-06-07 16:06:30 +0000, albert wrote:

    The basic problem mentioned in this issue was already solved in Mai 2009
    (version 1.5.8 or earlier), in case a brief description is present this is
    displayed otherwise the node number is specified)
    A remaining thing was that the tooltip with the root nodes (gray nodes) was
    always something like Node0 irrespective of the brief description. This has
    been solved here.
    
    I've just pushed a proposed patch to github (pull request 758,
    https://github.com/doxygen/doxygen/pull/758).

On 2018-06-10 10:00:58 +0000, albert wrote:

    Code has been integrated in master on github.

On 2018-06-10 10:33:21 +0000, albert wrote:

    Small extension: In case no brief description present, no tooltip is shown.
    
    I've just pushed a proposed patch to github (pull request 759,
    https://github.com/doxygen/doxygen/pull/759).

**Comment by albert-github** [comment]
Pull request #759 integrated, issue can be labeled as `fixed but not released`.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
