### ISSUE TITLE
Collaboration Diagram does not Show Up in RTF Documents (Origin: bugzilla #373644)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2308]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2006-11-11 01:38:47 +0000, John Pham wrote:

    use doxygen to generate RTF manual only
    has dot 
    however, when the RTF generated, the documentation 
    file does not have any collaboration diagram.
    
    I set diagram collabration flag set yes or no, it has 
    no effects.

On 2006-11-11 06:38:59 +0000, Kevin McBride wrote:

    I confirm this bug exists in 1.5.1-1.

**Comment by albert-github** [comment]
I tried to reproduce the problem with a small program:
```
/// \file

/// first class
class A
{
  public:
    /// first fie
    void fie1();
};

/// second class
class B: A
{
  public:
    /// second fie
    void fie2();
};
```
and setting
```
GENERATE_HTML          = NO
GENERATE_LATEX         = NO
GENERATE_RTF           = YES
HAVE_DOT               = YES
```
but with version 1.5.1 and with version 1.9.1 I see for the collaboration diagram.

I think the problem is, due to lack of information, not reproducible.
