### ISSUE TITLE
caller graph can be improved by having caller on left and callee on right (Origin: bugzilla #395343)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2354]
status NEW severity *minor* in component *general* for *---*
Reported in version *1.5.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-01-11 10:56:24 +0000, Banibrata Dutta wrote:

    Currently in the caller graph we have caller on right & callee on left,
    which is somewhat unnatural and not obvious. The readability, obviousness
    will increase many fold, if the order is reversed.
    
    Other information:

On 2018-06-10 13:25:30 +0000, albert wrote:

    I've just pushed a proposed patch to github (pull request 761,
    https://github.com/doxygen/doxygen/pull/761).

**Comment by albert-github** [comment]
Code has been integrated in master on github.

**Comment by albert-github** [comment]
As written before the code is integrated in master on github and available in the 1.8.15 version.

So problem has been solved in the mean time.
