### ISSUE TITLE
Brief descriptions and constructor / destructor methods are not listed (Origin: bugzilla #396206)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2355]
status NEEDINFO severity *normal* in component *doxywizard* for *---*
Reported in version *1.5.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-01-13 18:54:58 +0000, Hartwig wrote:

    Please describe the problem:
    class Test
    {
    public:
    /// Test constructor
    Test(void);
    
    };
    
    The constructor is not listed in the brief method summary (since version
    1.5.0).
    
    Steps to reproduce:
    1. see above
    2. default settings
    3. 
    
    
    Actual results:
    
    
    Expected results:
    Listing of the constructor in the brief method description list (all other
    methods besides the constructor and destructor are working correctly since
    1.5.1; was not the case in 1.5.0)
    
    Does this happen every time?
    yes
    
    Other information:
    In version 1.4.3 the bug was not present.

On 2013-08-07 17:55:48 +0000, albert wrote:

    I've tried to reproduce the problem, but with teh mentioned versions and
    with version 1.8.4
    I'm seeing more or less the same so I must overlook something.
    
    Can you test the problem with the latest version of doxygen?
    If you still see this issue with the latest version of doxygen please add a
    self-contained example (source+config file in a zip or tar).

**Comment by albert-github** [comment]
With all my tests I saw the constructor.

Seen the period of no response and the fact that with the supplied information the problem is not reproducible I think the problem should be closed as 'invalid' i.e. 'not complete or not reproducible'
