### ISSUE TITLE
SORT_BRIEF_DOCS produces wrong results (Origin: bugzilla #399222)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2363]
status NEW severity *major* in component *general* for *---*
Reported in version *1.5.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[test.hpp](https://sourceforge.net/projects/doxygen/files/attachments/bug399222_80850_test.hpp/download/download)_ (ID 80850)
- _[Doxyfile](https://sourceforge.net/projects/doxygen/files/attachments/bug399222_80851_Doxyfile/download/download)_ (ID 80851)

On 2007-01-22 01:15:03 +0000, Daniele Benegiamo wrote:

    When DISTRIBUTE_GROUP_DOC and SORT_BRIEF_DOCS are both enabled, if a group
    contains a member in the wrong sorting order, the documentation is not
    "distributed" and the "unsorted" member is not reported in detailed section,
    resulting in wrong/absent final documentation.

On 2007-01-22 01:18:02 +0000, Daniele Benegiamo wrote:

    Created attachment 80850
    Test source header file.

On 2007-01-22 01:19:18 +0000, Daniele Benegiamo wrote:

    Created attachment 80851
    Doxygen configuration file used.

On 2013-05-18 18:44:18 +0000, albert wrote:

    With version 1.5.1 the description is not copied, with version 1.8.3.1 the
    documentation is copied.
    
    Still the functions are not sorted in the section "Public Member Functions",
    in the section "Member Function Documentation" they are sorted. The used
    Doxyfile, it the standard Doxyfile with the SORT_..,  ALWAYS_DETAILED_SEC
    and DISTRIBUTE_GROUP_DOC set to YES.
    
    So part of the problem is solved.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6834

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
