### ISSUE TITLE
Relative links don't work inside \{ member group \} descriptions (Origin: bugzilla #402081)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2371]
status NEW severity *minor* in component *general* for *---*
Reported in version *1.5.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-01-29 12:45:21 +0000, daniel@warum-ada.de wrote:

    Please describe the problem:
    When trying to link to another documented member from inside member group
    descriptions (blocks between "\name" and "\{") of the same class doxygen
    fails to create the link, emitting a warning if the link was requested
    explicitly.
    Neither to members inside nor outside the member group does linking work.
    Absolute names _do_ work.
    
    Steps to reproduce:
    1. Example C++ source file:
    
    //------------------------------------------------------------
    /** Class with a member group */
    class A {
    
    public:
    
        /** @name member_group
         **
         ** Refer to #field_outside_group.
         ** Refer to #field_inside_group. */
        //@{
    
        /** @brief Data field inside the member group  */
        int field_inside_group;
    
        //@}
    
        /** @brief Data field outside any member group */
        int field_outside_group;
    };
    //------------------------------------------------------------
    
    2. echo "QUIET=YES" | doxygen -
    
    
    
    Actual results:
    Warnings:
    [generated]:-1: Warning: explicit link request to 'field_outside_group'
    could not be resolved
    [generated]:0: Warning: explicit link request to 'field_inside_group' could
    not be resolved
    
    In the generated HTML the strings "field_outside_group" and
    "field_inside_group" appear as simple non-link text.
    
    
    Expected results:
    Links to documentation of the data fields should be created.
    
    Does this happen every time?
    Yes.
    
    Other information:
    The absolute links in the following variation of the code do work, but
    produce not-so-nice absolute names in the documentation (could of course be
    worked around with \link ... \endlink constructs):
    
    //------------------------------------------------------------
    /** Class with a member group */
    class A {
    
    public:
    
        /** @name member_group
         **
         ** Refer to A#field_outside_group.
         ** Refer to A#field_inside_group. */
        //@{
    
        /** @brief Data field inside the member group  */
        int field_inside_group;
    
        //@}
    
        /** @brief Data field outside any member group */
        int field_outside_group;
    };
    //------------------------------------------------------------
    
    OS: Linux, Fedora Core 4
    Doxygen compiled from source tarball.

**Comment by albert-github** [comment]
With the version 1.5.1 I get the warnings as well.
With the current version 1.9.3 (c0b9eafbfb53286ce31e75e2b6c976ee4d345473) the messages are gone and the links are present.

I think the problem has been solved in the mean time.
