### ISSUE TITLE
Invalid link for function in namespace when same namespace is in tagfile (Origin: bugzilla #403302)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2378]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[Bug403302TestCase.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug403302_81687_Bug403302TestCase.zip/download/download)_ (ID 81687)
- _[Doxygen403302.patch](https://sourceforge.net/projects/doxygen/files/attachments/bug403302_96538_Doxygen403302.patch/download/download)_ (ID 96538)
- _[Doxygen403302.patch](https://sourceforge.net/projects/doxygen/files/attachments/bug403302_96579_Doxygen403302.patch/download/download)_ (ID 96579)
- _[Doxygen403302.patch](https://sourceforge.net/projects/doxygen/files/attachments/bug403302_96717_Doxygen403302.patch/download/download)_ (ID 96717)

On 2007-02-01 18:29:28 +0000, Ãric Malenfant wrote:

    Please describe the problem:
    (See attached files for an example)
    When a module defines a function in a namespace that is also present in a
    tagfile that this module links with (via the TAGFILES option in the
    doxyfile), the documentation for this function is not generated, and an
    invalid link to the documentation of the namespace is generated.
    
    Steps to reproduce:
    1. See attached files
    2. Run doxygen on Module1.doxyfile
    3. Run doxygen on Module2.doxyfile
    4. Look at the documentation generated in module2/html
    
    Actual results:
    A::SomeFunction is not documented in Module2
    The documentation for file "SomeFunction.h" in Module2 shows a link to
    A::SomeFunction(), but this link points to a (non-existent) definition in
    the documentation for namespace A in Module1
    
    Expected results:
    The Module2 should contain a documentation for namespace A, containing a
    link to the documentation for A::SomeFunction()
    
    Does this happen every time?
    Yes
    
    Other information:

On 2007-02-01 18:33:44 +0000, Ãric Malenfant wrote:

    Created attachment 81687
    Source and doxyfiles to reproduce the bug (zip)
    
    See "how to reproduce" instructions to use these files

On 2007-10-02 18:57:45 +0000, Ãric Malenfant wrote:

    Created attachment 96538
    Proposed patch
    
    In Doxygen.cpp:
    When importing a namespace from a tagfile, don't load the tagInfo. This way,
    the namespace will always be considered as "local".
    The problem this corrects is the following:
    - Module1 defines namespace A
    - Module2 also defines namespace A
    - Module2 depends on Module1, so its documentation imports Module1's tagfile
    - Doxygen loads tagfiles before parsing the code so, when building docs for
    Module2, it will first see Module1's definition of namespace A, create a new
    NamespaceDef for it, and associate Module1's tagInfo to it.
    - The result is that Module2 then sees namespace A as an external namespace,
    and  the members of namespace A defined in Module2 will not be documented.
    Moreover, references to these members will incorrectly point the Module1's
    definition of the namespace.
    
    In memberdef.cpp:
    When a MemberDef has its own reference (which is happens for namespace
    members imported from a tagfile), use it instead of its container's
    
    New behavior with this patch:
    - Inside a module, namespaces are always documented in their own page,
    regardless of if this namespace is found in this module, in tagfiles, or
    both.
    - This namespace documentation page contains all namespace members,
    regardless of if they were found in the current module or in tagfiles.
    - In this namespace documentation page, members found in a tagfile are only
    links to the namespace documentation page of the module they are defined in.

On 2007-10-02 19:00:18 +0000, Ãric Malenfant wrote:

    About the attached patch:
    I forgot to mention that it was generated against the sources of release
    1.5.3 (doxygen-1.5.3.src.tar.gz)

On 2007-10-03 17:50:09 +0000, Ãric Malenfant wrote:

    Created attachment 96579
    Updated patch
    
    This updated patch includes the former.
    
    What's new in it is that it prevents writing elements from a namespace
    (i.e., members, classes, namespaces) to the tagfile if they are references
    to external documentation. Otherwise, we end up with unnecessarily large
    tagfiles and, more importantly, invalid references for the user of the
    tagfile.

On 2007-10-05 17:37:37 +0000, Ãric Malenfant wrote:

    Created attachment 96717
    Updated patch (again)
    
    Some more refinements over the previous patch:
    - I missed the special handling of the enum members when writing the
    tagfile.
      References to external enum members were thus (erroneously) written to the
      tagfile.
    - Instead of always ignoring the reference information of a namespace (to 
      force its local documentation), we only force it when we discover that the
      current module defines something in a namespace. (This is made by the
    calls
      to "clearReference()" in NamespaceDef). The effect of this is that the 
      documentation of a namespace will appear in a given module only if this 
      module defines something in it.
    
    I successfully ran the patched doxygen on our codebase, and did not notice
    anything wrong in the results so, hopefully, this patch is the final one!

On 2007-10-23 11:32:06 +0000, Pavel Minaev wrote:

    I have exactly the same problem.

On 2007-10-23 13:07:05 +0000, Ãric Malenfant wrote:

    (In reply to comment # 6)
    > I have exactly the same problem.
    > 
    
    Pavel,
    
    Could you try the patch attached?

On 2007-11-11 12:56:06 +0000, Pavel Minaev wrote:

    (In reply to comment # 7)
    > Could you try the patch attached?
    
    I did, and it worked for me, though the patch as offered is not complete
    (it's missing the diff for the .h file).
    
    There is one more issue remaining when namespaces and tagfiles are mixed as
    described. When generating a CHM file, an entry is generated in the TOC for
    the namespace. If the namespace is actually defined in another Doxygen
    project, and there are some classes in that project which are derived from
    in the current project, there are TOC entries generated for both foreign
    namespace and foreign classes. The problem is that installdox does not patch
    index.hhc, so that the links in the TOC remain invalid (since the actual
    .html files for those entries are elsewhere!). And an HTML Help project with
    invalid links in the TOC simply does not compile...

**Comment by albert-github** [comment]
With version 1.5.1 I could see the incorrect link to module1.
With version 1.8.14 the link was correct (and the documentation present)

I think the problem has been solved in the mean time
