### ISSUE TITLE
BINARY_TOC breaks html help contents (Origin: bugzilla #404608)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2379]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.5.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-02-05 14:49:58 +0000, Waclaw Schiller wrote:

    Setting BINARY_TOC to YES in Doxyfile makes the expected change to
    index.hhp, but as well a few unexpected changes to index.hhc, the contents
    file. The changes are in main level 'folders'. When BINARY_TOC is not set,
    clicking on folder gives e.g. modules.html. With BINARY_TOC nothing happens.
    Blame goes to a single tag i .hhc file
    
    The example correct tag is:
    <LI><OBJECT type="text/sitemap"><param name="Name" value="Modules"><param
    name="Local" value="modules.html"><param name="ImageNumber"
    value="1"></OBJECT>
    
    The incorrect, generated with BINARY_TOC
    <LI><OBJECT type="text/sitemap"><param name="Name" value="Modules"><param
    name="ImageNumber" value="1"></OBJECT>
    
    The difference is <param name="Local" value="modules.html">, which is
    missing in the second tag.
    Same goes to everything that can be unfolded. The bug is present in 1.2.15
    as well, so probably since then.

**Comment by albert-github** [comment]
Looking at the `index.hhc` file from I see in the 1.5.1 with and without the `BINARY_TOC` enabled the difference as indicated.
Running with the 1.9.1 version this difference is gone.

i think the problem has been solved in the mean time.
