### ISSUE TITLE
New font used for dot graphs results in warnings/incorrect character tracking (Origin: bugzilla #410275)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2397]
status NEW severity *minor* in component *general* for *---*
Reported in version *1.5.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[dotfont.png](https://sourceforge.net/projects/doxygen/files/attachments/bug410275_83012_dotfont.png/download/download)_ (ID 83012)
- _[test.png](https://sourceforge.net/projects/doxygen/files/attachments/bug410275_83897_test.png/download/download)_ (ID 83897)

On 2007-02-21 04:48:46 +0000, phoenix1701@gmail.com wrote:

    Sometime in the last few releases, doxygen apparently changed the default
    font it uses when generating graphs in dot to something that looks like
    Verdana.  In older versions of dot (< 1.8), this results in the following
    warning being printed out repeatedly to the console as doxygen is generating
    graphs:
    
    Warning: ATSUFindFontFromName status = -8796
    
    and dot renders all its text in Lucida Grande.
    
    In newer versions of dot (2.12) this warning does not occur, and the graphs
    appear in a font resembling Verdana, presumably as intended.  However, the
    character tracking is badly off, almost to the point of illegibility.  It
    may therefore be a good idea to use a different default font (perhaps Arial,
    if a sans-serif typeface is desired), at least on Mac OS X.

On 2007-02-21 04:50:24 +0000, phoenix1701@gmail.com wrote:

    Created attachment 83012
    A small screen capture of bad dot font metrics.
    
    This is a small screen capture of the bad font metrics.

On 2007-03-04 15:53:09 +0000, Dimitri van Heesch wrote:

    To avoid such issues, doxygen now comes bundled with dot on the mac 
    (you can find it in /Applications/Doxygen.app/Contents/Resources). 
    
    This version produces much better results than yours. I'll attach the
    picture of my example. Could you try your example also with this version of
    dot?
    
    ----- example.cpp ----------------------------
    class base
    {
    };
    
    class assistantwizardcontroller : public base
    {
    };
    -----------------------------------------------
    

On 2007-03-04 15:54:43 +0000, Dimitri van Heesch wrote:

    Created attachment 83897
    Images produced by dot

On 2007-03-04 15:55:27 +0000, Dimitri van Heesch wrote:

    Please let me know the results. 

On 2007-04-11 17:28:07 +0000, phoenix1701@gmail.com wrote:

    I can confirm that using the built-in version of dot does indeed fix the
    tracking, although the lack of anti-aliasing in the graphs is a little
    irritating from a Mac-zealot point of view. ;)  Thanks, and sorry for the
    delay in confirming this!

**Comment by albert-github** [comment]
In the version 1.5.0 till 1.7.1 the dot program was bundled with doxygen. With the newer version this is not the case anymore.
There are no, recent, reports about problems with fonts in relation to dot and the Mac

I think the problem has been solved in the mean time.
