### ISSUE TITLE
ifdef-ed namespaces generate "endif" namespace (C#) (Origin: bugzilla #411629)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2401]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-02-24 17:22:45 +0000, Ferenc Veres wrote:

    Using this file start:
    
    00001 using System;
    00002 using System.Collections;
    00003 using System.Data;
    00004 //using System.Web;
    00005 using System.Text;
    00006 using System.Xml;
    00007 using System.Xml.Schema;
    00008 using System.Text.RegularExpressions;
    00009 
    00010 #if !MIGRATEME
    00011 using Moonbase;
    00012 using Moonbase.Controls;
    00013 using WPS.Modules;
    00014 #endif
    00015 
    00016 #if MIGRATEME2
    00017 namespace MigrateMe2
    00018 #else
    00019 namespace WPS
    00020 #endif
    00021 {
    00028         public class LinkerLinksItem
    00029         {
    ...
    
    Generates the LinkerLinksItem as being in the endif namespace!
    
    Acutal result:
    Headline from the class documentation: 
    
    endif.LinkerLinksItem Class Reference
    
    Expected result:
    
    It should be either
    
    WPS.LinkerLinksItem
    or 
    MigrateMe2.LinkerLinksItem
    
    (Can I specify somewhere what build DEFs are defined? To let Doxygen
    correctly choose between these two?)
    
    Thanks!

On 2016-10-18 02:23:19 +0000, Harry Moffat wrote:

    Hi,
      I just ran into this error with the latest doxygen 1.8.12. Unfortunately,
    it actually happened one out of about 100 times, and I can not distinguish
    why it happened in the one case from why it didn't happen in the other 99
    cases.
    But it happened!
    
    A namespace with the name "endif" showed up in my list of namespaces.

**Comment by albert-github** [comment]
In cpp this behavior can be reproduced when `ENABLE_PREPROCESSING= NO`, in the scanner lines starting with a preprocessor directive should be ignored.
The results might not be as expected but it is the user's choice to disable the `ENABLE_PREPROCESSING`.

I've just pushed a proposed patch, pull request #8871

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.3.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
