### ISSUE TITLE
Warnings when documenting members of classes in unnamed namespaces (Origin: bugzilla #412978)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2403]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.3-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-02-28 07:46:59 +0000, Braden wrote:

    Please describe the problem:
    Using doxygen 1.5.1-20070219, I'm getting warnings that look like this:
```    
/home/braden/src/openvrml/openvrml-0.16/src/libopenvrml/openvrml/vrml97node.cpp:12276:
    Warning: no uniquely matching class member found for
      font_style_node::font_style_metatype
    Possible candidates:
      friend class @29::font_style_node::font_style_metatype at line 3056 of
    file
    /home/braden/src/openvrml/openvrml-0.16/src/libopenvrml/openvrml/vrml97node.cpp
/home/braden/src/openvrml/openvrml-0.16/src/libopenvrml/openvrml/vrml97node.cpp:12282:
    Warning: no matching class member found for
      openvrml::mfstring font_style_node::family_
    Possible candidates:
      mfstring @29::font_style_node::family_
```    
    
    Corresponding doc-comments:
    
        /**
         * @var font_style_node::font_style_metatype
         *
         * @brief Class object for FontStyle nodes.
         */
    
        /**
         * @var openvrml::mfstring font_style_node::family_
         *
         * @brief family field.
         */
    
    font_style_metatype is a friend class; family_ is a member variable. This
    seems to be happening for all @var documentation where the class is in an
    unnamed namespace.
    
    
    Steps to reproduce:
    
    
    
    Actual results:
    
    
    Expected results:
    
    
    Does this happen every time?
    
    
    Other information:

**Comment by AlexisWilke** [comment]
I (and I'm sure many others) have run in the same problem.

I get the same error:

> Searching for member function documentation...
> /tmp/sample.cpp:73: warning: no uniquely matching class member found for 
>   void anonymous_namespace sample A::anonymous_namespace{sample.cpp}::A::cpp::D::init()

From the following `sample.cpp` file:

    /** \file
     * \brief Sample to test the problem with a no-name namespace.
     *
     * There seems to be a problem with name spaces that are unamed
     * and overloaded functions.
     */
    
    
    /** \brief Named namespaces seem okay.
     *
     * When you give the namespace a valid name, it looks like it works as
     * expected.
     */
    namespace A
    {
    
    
    /** \brief Base class
     *
     * This is the base class.
     */
    class B
    {
    public:
    	virtual void	init();
    };
    
    
    /** \brief Base class init info.
     *
     * This is the init() function in the base class.
     */
    void B::init()
    {
    }
    
    
    } // A namespace
    
    
    
    // usually in another file
    namespace A
    {
    
    /** \brief Make sure the derived class is anonymous.
     *
     * In C++ we use unnamed namespaces instead of "static" like in C.
     * This is in part because "static" doesn't work against classes
     * and many other declarations. It pretty much only works for
     * variables and functions. In C++ that can be a problem, though.
     */
    namespace
    {
    
    /** \brief Derived class.
     *
     * We derive D from the base class B.
     */
    class D : public B
    {
    public:
    	virtual void	init();
    };
    
    
    
    /** \brief Derived class init info.
     *
     * This should show up in the D class init function documentation.
     */
    void D::init()
    {
    }
    
    
    } // no name namespace
    
    
    } // A namespace

And a pretty standard `sample.doxy` file as follow:

    DOXYFILE_ENCODING      = UTF-8
    PROJECT_NAME           = "sample"
    PROJECT_NUMBER         = 1.2
    PROJECT_BRIEF          = "sample showing the failing unnamed namespace"
    PROJECT_LOGO           =
    OUTPUT_DIRECTORY       = docs
    CREATE_SUBDIRS         = NO
    ALLOW_UNICODE_NAMES    = NO
    OUTPUT_LANGUAGE        = English
    BRIEF_MEMBER_DESC      = YES
    REPEAT_BRIEF           = NO
    ABBREVIATE_BRIEF       =
    ALWAYS_DETAILED_SEC    = NO
    INLINE_INHERITED_MEMB  = YES
    FULL_PATH_NAMES        = YES
    STRIP_FROM_PATH        =
    STRIP_FROM_INC_PATH    =
    SHORT_NAMES            = NO
    JAVADOC_AUTOBRIEF      = NO
    QT_AUTOBRIEF           = NO
    MULTILINE_CPP_IS_BRIEF = NO
    INHERIT_DOCS           = YES
    SEPARATE_MEMBER_PAGES  = NO
    TAB_SIZE               = 4
    ALIASES                = "TODO=@todo" \
                             "FIXME=@todo" \
                             "TBD=@todo"
    TCL_SUBST              =
    OPTIMIZE_OUTPUT_FOR_C  = NO
    OPTIMIZE_OUTPUT_JAVA   = NO
    OPTIMIZE_FOR_FORTRAN   = NO
    OPTIMIZE_OUTPUT_VHDL   = NO
    EXTENSION_MAPPING      =
    MARKDOWN_SUPPORT       = YES
    AUTOLINK_SUPPORT       = YES
    BUILTIN_STL_SUPPORT    = NO
    CPP_CLI_SUPPORT        = NO
    SIP_SUPPORT            = NO
    IDL_PROPERTY_SUPPORT   = YES
    DISTRIBUTE_GROUP_DOC   = NO
    GROUP_NESTED_COMPOUNDS = NO
    SUBGROUPING            = YES
    INLINE_GROUPED_CLASSES = NO
    INLINE_SIMPLE_STRUCTS  = NO
    TYPEDEF_HIDES_STRUCT   = NO
    LOOKUP_CACHE_SIZE      = 0
    EXTRACT_ALL            = YES
    EXTRACT_PRIVATE        = YES
    EXTRACT_PACKAGE        = NO
    EXTRACT_STATIC         = YES
    EXTRACT_LOCAL_CLASSES  = YES
    EXTRACT_LOCAL_METHODS  = NO
    EXTRACT_ANON_NSPACES   = YES
    HIDE_UNDOC_MEMBERS     = NO
    HIDE_UNDOC_CLASSES     = NO
    HIDE_FRIEND_COMPOUNDS  = NO
    HIDE_IN_BODY_DOCS      = NO
    INTERNAL_DOCS          = YES
    CASE_SENSE_NAMES       = YES
    HIDE_SCOPE_NAMES       = NO
    HIDE_COMPOUND_REFERENCE= NO
    SHOW_INCLUDE_FILES     = YES
    SHOW_GROUPED_MEMB_INC  = NO
    FORCE_LOCAL_INCLUDES   = NO
    INLINE_INFO            = YES
    SORT_MEMBER_DOCS       = YES
    SORT_BRIEF_DOCS        = YES
    SORT_MEMBERS_CTORS_1ST = YES
    SORT_GROUP_NAMES       = NO
    SORT_BY_SCOPE_NAME     = NO
    STRICT_PROTO_MATCHING  = NO
    GENERATE_TODOLIST      = YES
    GENERATE_TESTLIST      = YES
    GENERATE_BUGLIST       = YES
    GENERATE_DEPRECATEDLIST= YES
    ENABLED_SECTIONS       =
    MAX_INITIALIZER_LINES  = 30
    SHOW_USED_FILES        = YES
    SHOW_FILES             = YES
    SHOW_NAMESPACES        = YES
    FILE_VERSION_FILTER    =
    LAYOUT_FILE            =
    CITE_BIB_FILES         =
    QUIET                  = NO
    WARNINGS               = YES
    WARN_IF_UNDOCUMENTED   = YES
    WARN_IF_DOC_ERROR      = YES
    WARN_NO_PARAMDOC       = YES
    WARN_AS_ERROR          = NO
    WARN_FORMAT            = "$file:$line: $text"
    WARN_LOGFILE           =
    INPUT                  = .
    INPUT_ENCODING         = UTF-8
    FILE_PATTERNS          = *.h \
                             *.h.in \
                             *.hpp \
                             *.hpp.in \
                             *.cpp \
                             *.c
    RECURSIVE              = YES
    EXCLUDE                =
    EXCLUDE_SYMLINKS       = NO
    EXCLUDE_PATTERNS       =
    EXCLUDE_SYMBOLS        =
    EXAMPLE_PATH           = .
    EXAMPLE_PATTERNS       = *example*.cpp
    EXAMPLE_RECURSIVE      = NO
    IMAGE_PATH             =
    INPUT_FILTER           =
    FILTER_PATTERNS        =
    FILTER_SOURCE_FILES    = NO
    FILTER_SOURCE_PATTERNS =
    USE_MDFILE_AS_MAINPAGE =
    SOURCE_BROWSER         = YES
    INLINE_SOURCES         = NO
    STRIP_CODE_COMMENTS    = YES
    REFERENCED_BY_RELATION = YES
    REFERENCES_RELATION    = YES
    REFERENCES_LINK_SOURCE = YES
    SOURCE_TOOLTIPS        = YES
    USE_HTAGS              = NO
    VERBATIM_HEADERS       = YES
    CLANG_ASSISTED_PARSING = NO
    CLANG_OPTIONS          =
    ALPHABETICAL_INDEX     = YES
    COLS_IN_ALPHA_INDEX    = 5
    IGNORE_PREFIX          = m_
    GENERATE_HTML          = YES
    HTML_OUTPUT            = html
    HTML_FILE_EXTENSION    = .html
    HTML_HEADER            =
    HTML_FOOTER            =
    HTML_STYLESHEET        =
    HTML_EXTRA_STYLESHEET  =
    HTML_EXTRA_FILES       =
    HTML_COLORSTYLE_HUE    = 220
    HTML_COLORSTYLE_SAT    = 100
    HTML_COLORSTYLE_GAMMA  = 80
    HTML_TIMESTAMP         = YES
    HTML_DYNAMIC_SECTIONS  = NO
    HTML_INDEX_NUM_ENTRIES = 100
    GENERATE_DOCSET        = NO
    DOCSET_FEEDNAME        = "Doxygen generated docs"
    DOCSET_BUNDLE_ID       = org.doxygen.Project
    DOCSET_PUBLISHER_ID    = org.doxygen.Publisher
    DOCSET_PUBLISHER_NAME  = Publisher
    GENERATE_HTMLHELP      = NO
    CHM_FILE               =
    HHC_LOCATION           =
    GENERATE_CHI           = NO
    CHM_INDEX_ENCODING     =
    BINARY_TOC             = NO
    TOC_EXPAND             = NO
    GENERATE_QHP           = NO
    QCH_FILE               =
    QHP_NAMESPACE          = org.doxygen.Project
    QHP_VIRTUAL_FOLDER     = doc
    QHP_CUST_FILTER_NAME   =
    QHP_CUST_FILTER_ATTRS  =
    QHP_SECT_FILTER_ATTRS  =
    QHG_LOCATION           =
    GENERATE_ECLIPSEHELP   = NO
    ECLIPSE_DOC_ID         = org.doxygen.Project
    DISABLE_INDEX          = NO
    GENERATE_TREEVIEW      = NO
    ENUM_VALUES_PER_LINE   = 1
    TREEVIEW_WIDTH         = 250
    EXT_LINKS_IN_WINDOW    = NO
    FORMULA_FONTSIZE       = 10
    FORMULA_TRANSPARENT    = YES
    USE_MATHJAX            = YES
    MATHJAX_FORMAT         = HTML-CSS
    MATHJAX_RELPATH        = http://cdn.mathjax.org/mathjax/latest
    MATHJAX_EXTENSIONS     =
    MATHJAX_CODEFILE       =
    SEARCHENGINE           = NO
    SERVER_BASED_SEARCH    = NO
    EXTERNAL_SEARCH        = NO
    SEARCHENGINE_URL       =
    SEARCHDATA_FILE        = searchdata.xml
    EXTERNAL_SEARCH_ID     =
    EXTRA_SEARCH_MAPPINGS  =
    GENERATE_LATEX         = YES
    LATEX_OUTPUT           = latex
    LATEX_CMD_NAME         = latex
    MAKEINDEX_CMD_NAME     = makeindex
    COMPACT_LATEX          = NO
    PAPER_TYPE             = a4
    EXTRA_PACKAGES         =
    LATEX_HEADER           =
    LATEX_FOOTER           =
    LATEX_EXTRA_STYLESHEET =
    LATEX_EXTRA_FILES      =
    PDF_HYPERLINKS         = YES
    USE_PDFLATEX           = YES
    LATEX_BATCHMODE        = NO
    LATEX_HIDE_INDICES     = NO
    LATEX_SOURCE_CODE      = NO
    LATEX_BIB_STYLE        = plain
    LATEX_TIMESTAMP        = NO
    GENERATE_RTF           = NO
    RTF_OUTPUT             = rtf
    COMPACT_RTF            = NO
    RTF_HYPERLINKS         = NO
    RTF_STYLESHEET_FILE    =
    RTF_EXTENSIONS_FILE    =
    RTF_SOURCE_CODE        = NO
    GENERATE_MAN           = YES
    MAN_OUTPUT             = man
    MAN_EXTENSION          = .3
    MAN_SUBDIR             =
    MAN_LINKS              = NO
    GENERATE_XML           = NO
    XML_OUTPUT             = xml
    XML_PROGRAMLISTING     = YES
    GENERATE_DOCBOOK       = NO
    DOCBOOK_OUTPUT         = docbook
    DOCBOOK_PROGRAMLISTING = NO
    GENERATE_AUTOGEN_DEF   = NO
    GENERATE_PERLMOD       = NO
    PERLMOD_LATEX          = NO
    PERLMOD_PRETTY         = YES
    PERLMOD_MAKEVAR_PREFIX =
    ENABLE_PREPROCESSING   = YES
    MACRO_EXPANSION        = NO
    EXPAND_ONLY_PREDEF     = NO
    SEARCH_INCLUDES        = YES
    INCLUDE_PATH           =
    INCLUDE_FILE_PATTERNS  =
    PREDEFINED             =
    EXPAND_AS_DEFINED      =
    SKIP_FUNCTION_MACROS   = YES
    TAGFILES               =
    GENERATE_TAGFILE       =
    ALLEXTERNALS           = NO
    EXTERNAL_GROUPS        = YES
    EXTERNAL_PAGES         = YES
    PERL_PATH              = /usr/bin/perl
    CLASS_DIAGRAMS         = YES
    MSCGEN_PATH            =
    DIA_PATH               =
    HIDE_UNDOC_RELATIONS   = YES
    HAVE_DOT               = YES
    DOT_NUM_THREADS        = 0
    DOT_FONTNAME           = Helvetica
    DOT_FONTSIZE           = 10
    DOT_FONTPATH           =
    CLASS_GRAPH            = YES
    COLLABORATION_GRAPH    = YES
    GROUP_GRAPHS           = YES
    UML_LOOK               = NO
    UML_LIMIT_NUM_FIELDS   = 10
    TEMPLATE_RELATIONS     = NO
    INCLUDE_GRAPH          = YES
    INCLUDED_BY_GRAPH      = YES
    CALL_GRAPH             = NO
    CALLER_GRAPH           = NO
    GRAPHICAL_HIERARCHY    = YES
    DIRECTORY_GRAPH        = YES
    DOT_IMAGE_FORMAT       = png
    INTERACTIVE_SVG        = NO
    DOT_PATH               =
    DOTFILE_DIRS           =
    MSCFILE_DIRS           =
    DIAFILE_DIRS           =
    PLANTUML_JAR_PATH      =
    PLANTUML_INCLUDE_PATH  =
    DOT_GRAPH_MAX_NODES    = 150
    MAX_DOT_GRAPH_DEPTH    = 0
    DOT_TRANSPARENT        = NO
    DOT_MULTI_TARGETS      = YES
    GENERATE_LEGEND        = YES
    DOT_CLEANUP            = YES

I ran the command line:

    doxygen sample.doxy

and get the error message mentioned above. Also, the documentation of the `D::init()` function is completely ignored (not present in the final HTML documentation.)

From other things I've seen in Doxygen, it feels like the unnamed namespaces are given a name which is the name of the file in which they appear and the line number. It seems to me that this is unique enough to end up with a clearly distinct name for each element in such a block.

Current fix for those who do not mind is to give the `namespace` a name. So in my example above, I could change:

    namespace
    {

With:

    namespace internals
    {

and Doxygen is all happy and gets it right.

**Comment by AlexisWilke** [comment]
Here is another reference where someone reported a problem with an unnamed namespace.

[Doxygen complains about overloaded functions that take same template but with different template parameter](https://stackoverflow.com/questions/41987147/)

**Comment by albert-github** [comment]
@AlexisWilke  The example is nice but it is preferred to have it as an attached, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent. Saves a lot of cutting and pasting.

**Comment by AlexisWilke** [comment]
The sample code from above in a tarball.

[sample.tar.gz](https://github.com/doxygen/doxygen/files/3292151/sample.tar.gz)

**Comment by albert-github** [comment]
With the doxygen 1.8.16 version we get the warning as indicated for the example given by @AlexisWilke .
With the current doxygen version (1.9.6) this warning is gone (and as far as I can see the documentation is as intended).

Also for the original problem the indicated warnings are gone.

I think the problem has been solved in the mean time.
