### ISSUE TITLE
XML output and EXTRACT_PRIVATE = NO ouputs private functions (Origin: bugzilla #413236)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2405]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-02-28 22:04:47 +0000, Ion GaztaÃ±aga wrote:

    I've been using doxygen with the Boost C++ documentation framework to
    generate reference files for Boost libraries. Although I specify the
    EXTRACT_PRIVATE = NO option, private functions were displayed in the
    documentation. I've written an small example of a simple class, using
    Doxywizard, requesting both XML and HTML outputs. In the HTML outputs,
    private functions are not displayed, but the XML ouput displays them.
    
    I'm attaching the Doxyfile and a very simple header file. I'm using Doxygen
    1.5.1/Windows XP. The same happens with older Doxygen versions.
    
    Thanks,
    
    Ion
    
    8<---8<---8<---8<---8<---8<---8<---8<---8<---8<---8<---8<---8<---8<---
    
    # Doxyfile 1.5.1-p1
    
    #---------------------------------------------------------------------------
    # Project related configuration options
    #---------------------------------------------------------------------------
    PROJECT_NAME           = 
    PROJECT_NUMBER         = 
    OUTPUT_DIRECTORY       = C:\doxygen
    CREATE_SUBDIRS         = NO
    OUTPUT_LANGUAGE        = English
    USE_WINDOWS_ENCODING   = YES
    BRIEF_MEMBER_DESC      = YES
    REPEAT_BRIEF           = YES
    ABBREVIATE_BRIEF       = "The $name class" \
                             "The $name widget" \
                             "The $name file" \
                             is \
                             provides \
                             specifies \
                             contains \
                             represents \
                             a \
                             an \
                             the
    ALWAYS_DETAILED_SEC    = NO
    INLINE_INHERITED_MEMB  = NO
    FULL_PATH_NAMES        = YES
    STRIP_FROM_PATH        = "C:/Archivos de programa/doxygen/bin/"
    STRIP_FROM_INC_PATH    = 
    SHORT_NAMES            = NO
    JAVADOC_AUTOBRIEF      = NO
    MULTILINE_CPP_IS_BRIEF = NO
    DETAILS_AT_TOP         = NO
    INHERIT_DOCS           = YES
    SEPARATE_MEMBER_PAGES  = NO
    TAB_SIZE               = 8
    ALIASES                = 
    OPTIMIZE_OUTPUT_FOR_C  = NO
    OPTIMIZE_OUTPUT_JAVA   = NO
    BUILTIN_STL_SUPPORT    = NO
    DISTRIBUTE_GROUP_DOC   = NO
    SUBGROUPING            = YES
    #---------------------------------------------------------------------------
    # Build related configuration options
    #---------------------------------------------------------------------------
    EXTRACT_ALL            = NO
    EXTRACT_PRIVATE        = NO
    EXTRACT_STATIC         = NO
    EXTRACT_LOCAL_CLASSES  = YES
    EXTRACT_LOCAL_METHODS  = NO
    HIDE_UNDOC_MEMBERS     = YES
    HIDE_UNDOC_CLASSES     = YES
    HIDE_FRIEND_COMPOUNDS  = NO
    HIDE_IN_BODY_DOCS      = NO
    INTERNAL_DOCS          = NO
    CASE_SENSE_NAMES       = NO
    HIDE_SCOPE_NAMES       = NO
    SHOW_INCLUDE_FILES     = YES
    INLINE_INFO            = YES
    SORT_MEMBER_DOCS       = YES
    SORT_BRIEF_DOCS        = NO
    SORT_BY_SCOPE_NAME     = NO
    GENERATE_TODOLIST      = YES
    GENERATE_TESTLIST      = YES
    GENERATE_BUGLIST       = YES
    GENERATE_DEPRECATEDLIST= YES
    ENABLED_SECTIONS       = 
    MAX_INITIALIZER_LINES  = 30
    SHOW_USED_FILES        = YES
    SHOW_DIRECTORIES       = YES
    FILE_VERSION_FILTER    = 
    #---------------------------------------------------------------------------
    # configuration options related to warning and progress messages
    #---------------------------------------------------------------------------
    QUIET                  = NO
    WARNINGS               = YES
    WARN_IF_UNDOCUMENTED   = YES
    WARN_IF_DOC_ERROR      = YES
    WARN_NO_PARAMDOC       = NO
    WARN_FORMAT            = "$file:$line: $text"
    WARN_LOGFILE           = 
    #---------------------------------------------------------------------------
    # configuration options related to the input files
    #---------------------------------------------------------------------------
    INPUT                  = C:\doxygen
    FILE_PATTERNS          = *.c \
                             *.cc \
                             *.cxx \
                             *.cpp \
                             *.c++ \
                             *.d \
                             *.java \
                             *.ii \
                             *.ixx \
                             *.ipp \
                             *.i++ \
                             *.inl \
                             *.h \
                             *.hh \
                             *.hxx \
                             *.hpp \
                             *.h++ \
                             *.idl \
                             *.odl \
                             *.cs \
                             *.php \
                             *.php3 \
                             *.inc \
                             *.m \
                             *.mm \
                             *.dox
    RECURSIVE              = NO
    EXCLUDE                = 
    EXCLUDE_SYMLINKS       = NO
    EXCLUDE_PATTERNS       = 
    EXAMPLE_PATH           = 
    EXAMPLE_PATTERNS       = *
    EXAMPLE_RECURSIVE      = NO
    IMAGE_PATH             = 
    INPUT_FILTER           = 
    FILTER_PATTERNS        = 
    FILTER_SOURCE_FILES    = NO
    #---------------------------------------------------------------------------
    # configuration options related to source browsing
    #---------------------------------------------------------------------------
    SOURCE_BROWSER         = NO
    INLINE_SOURCES         = NO
    STRIP_CODE_COMMENTS    = YES
    REFERENCED_BY_RELATION = NO
    REFERENCES_RELATION    = NO
    REFERENCES_LINK_SOURCE = YES
    USE_HTAGS              = NO
    VERBATIM_HEADERS       = NO
    #---------------------------------------------------------------------------
    # configuration options related to the alphabetical class index
    #---------------------------------------------------------------------------
    ALPHABETICAL_INDEX     = NO
    COLS_IN_ALPHA_INDEX    = 5
    IGNORE_PREFIX          = 
    #---------------------------------------------------------------------------
    # configuration options related to the HTML output
    #---------------------------------------------------------------------------
    GENERATE_HTML          = YES
    HTML_OUTPUT            = html
    HTML_FILE_EXTENSION    = .html
    HTML_HEADER            = 
    HTML_FOOTER            = 
    HTML_STYLESHEET        = 
    HTML_ALIGN_MEMBERS     = YES
    GENERATE_HTMLHELP      = NO
    CHM_FILE               = 
    HHC_LOCATION           = 
    GENERATE_CHI           = NO
    BINARY_TOC             = NO
    TOC_EXPAND             = NO
    DISABLE_INDEX          = NO
    ENUM_VALUES_PER_LINE   = 4
    GENERATE_TREEVIEW      = NO
    TREEVIEW_WIDTH         = 250
    #---------------------------------------------------------------------------
    # configuration options related to the LaTeX output
    #---------------------------------------------------------------------------
    GENERATE_LATEX         = NO
    LATEX_OUTPUT           = latex
    LATEX_CMD_NAME         = latex
    MAKEINDEX_CMD_NAME     = makeindex
    COMPACT_LATEX          = NO
    PAPER_TYPE             = a4wide
    EXTRA_PACKAGES         = 
    LATEX_HEADER           = 
    PDF_HYPERLINKS         = NO
    USE_PDFLATEX           = NO
    LATEX_BATCHMODE        = NO
    LATEX_HIDE_INDICES     = NO
    #---------------------------------------------------------------------------
    # configuration options related to the RTF output
    #---------------------------------------------------------------------------
    GENERATE_RTF           = NO
    RTF_OUTPUT             = rtf
    COMPACT_RTF            = NO
    RTF_HYPERLINKS         = NO
    RTF_STYLESHEET_FILE    = 
    RTF_EXTENSIONS_FILE    = 
    #---------------------------------------------------------------------------
    # configuration options related to the man page output
    #---------------------------------------------------------------------------
    GENERATE_MAN           = NO
    MAN_OUTPUT             = man
    MAN_EXTENSION          = .3
    MAN_LINKS              = NO
    #---------------------------------------------------------------------------
    # configuration options related to the XML output
    #---------------------------------------------------------------------------
    GENERATE_XML           = YES
    XML_OUTPUT             = xml
    XML_SCHEMA             = 
    XML_DTD                = 
    XML_PROGRAMLISTING     = YES
    #---------------------------------------------------------------------------
    # configuration options for the AutoGen Definitions output
    #---------------------------------------------------------------------------
    GENERATE_AUTOGEN_DEF   = NO
    #---------------------------------------------------------------------------
    # configuration options related to the Perl module output
    #---------------------------------------------------------------------------
    GENERATE_PERLMOD       = NO
    PERLMOD_LATEX          = NO
    PERLMOD_PRETTY         = YES
    PERLMOD_MAKEVAR_PREFIX = 
    #---------------------------------------------------------------------------
    # Configuration options related to the preprocessor   
    #---------------------------------------------------------------------------
    ENABLE_PREPROCESSING   = YES
    MACRO_EXPANSION        = NO
    EXPAND_ONLY_PREDEF     = NO
    SEARCH_INCLUDES        = YES
    INCLUDE_PATH           = 
    INCLUDE_FILE_PATTERNS  = 
    PREDEFINED             = 
    EXPAND_AS_DEFINED      = 
    SKIP_FUNCTION_MACROS   = YES
    #---------------------------------------------------------------------------
    # Configuration::additions related to external references   
    #---------------------------------------------------------------------------
    TAGFILES               = 
    GENERATE_TAGFILE       = 
    ALLEXTERNALS           = NO
    EXTERNAL_GROUPS        = YES
    PERL_PATH              = /usr/bin/perl
    #---------------------------------------------------------------------------
    # Configuration options related to the dot tool   
    #---------------------------------------------------------------------------
    CLASS_DIAGRAMS         = NO
    HIDE_UNDOC_RELATIONS   = YES
    HAVE_DOT               = NO
    CLASS_GRAPH            = YES
    COLLABORATION_GRAPH    = YES
    GROUP_GRAPHS           = YES
    UML_LOOK               = NO
    TEMPLATE_RELATIONS     = NO
    INCLUDE_GRAPH          = YES
    INCLUDED_BY_GRAPH      = YES
    CALL_GRAPH             = NO
    CALLER_GRAPH           = NO
    GRAPHICAL_HIERARCHY    = YES
    DIRECTORY_GRAPH        = YES
    DOT_IMAGE_FORMAT       = png
    DOT_PATH               = 
    DOTFILE_DIRS           = 
    MAX_DOT_GRAPH_WIDTH    = 1024
    MAX_DOT_GRAPH_HEIGHT   = 1024
    MAX_DOT_GRAPH_DEPTH    = 1000
    DOT_TRANSPARENT        = NO
    DOT_MULTI_TARGETS      = NO
    GENERATE_LEGEND        = YES
    DOT_CLEANUP            = YES
    #---------------------------------------------------------------------------
    # Configuration::additions related to the search engine   
    #---------------------------------------------------------------------------
    SEARCHENGINE           = NO
    
    8<---8<---8<---8<---8<---8<---8<---8<---8<---8<---8<---8<---8<---8<---
    
    //! Documented class
    class myclass
    {
       private:
       //! Non-copyable
       myclass(const myclass &);
    
       //! Non-assignable
       myclass& operator=(const myclass &);
    
       public:
       //! Constructor
       myclass();
    
       //! Public static function
       static public_static_func();
    
       private:
       //! Private static function
       static private_static_func();
    };

On 2012-02-17 10:45:52 +0000, Philipp Moeller wrote:

    I can confirm this for Linux and doxygen 1.7.6.1-1. Addtionally, the XML
    output is oblivious to the options HIDE_UNDOC_* as well. Should I file a new
    bug for this? It seems that all of them should/can be fixed in one sweep.

**Comment by JamesRandom** [comment]
bump

**Comment by albert-github** [comment]
I think the problem here is the interpretation of the goal of the XML output. Contrary to the output formats like HTML. LaTeX, RTF, Docbook it is intended as an intermediate output format that further can be processed by the user. To give the user all flexibility doxygen does not impose all the restrictions laid out by the doxygen settings and as a result e.g. private members are shown in the XML output even when `EXTRACT_PRIVATE=NO`. 

An interesting proposed pull request in this matter is #8463

So I don't think the problem is a bug but usage.
