### ISSUE TITLE
Missing images and header problem (Origin: bugzilla #413384)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2406]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-03-01 10:03:04 +0000, Thomas Lehmann wrote:

    Please describe the problem:
    1) Missing images
    I've created a documentation for a more or less small amount
    of sources -> working!
    
    I've created a documentation for a really big amount of
    sources -> missing images (partially - not all)
    Big amount: generation needs more than the half of a day!
    
    2) Header Problem
    When using generation of all files in one folder it's possible to
    have an own (simple) header for all pages.
    When using generation with subfolders the own (simple) header isn't
    displayed
    in all pages!
    
    Steps to reproduce:
    1. Big amount of sources
    2. Using subfolder generation
    
    for 1.: maybe you shouldn't try to find the missing images visually!
    Write a simple script for searching in each html fetching the image url's
    and
    look wether all images are present!
    
    
    Actual results:
    
    
    Expected results:
    
    
    Does this happen every time?
    Yes
    
    Other information:

**Comment by albert-github** [comment]
It is unclear what the missing images are and also what the content of the header is.
Regarding missing images / problems with user defined headers there have not been reports.

I think the issue is incomplete to reproduce and seen the lack of new issues I thin the problem might have been solved in the mean time.
