### ISSUE TITLE
c# attributes, not parsing correctly (Origin: bugzilla #420158)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2421]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-03-19 15:58:09 +0000, rassol wrote:

    Please describe the problem:
    1.
    class with attributes containing to slashes // wont appear in the doc
    e.g.
    
    [WebService(Namespace="http://tempuri.org")]
    public class A
    ...
    
    2.
    The following raises a "member with no name" warning
    
    [WebMethod]
    [XmlInclude(typeof(A.B.C))]
    public A B()
    ...
    
    
    Steps to reproduce:
    1. See description
    2. 
    3. 
    
    
    Actual results:
    the classes and methods does not appear in the generated doc.
    
    Expected results:
    the classes and methods should appear in the generated doc.
    
    Does this happen every time?
    yes
    
    Other information:

**Comment by albert-github** [comment]
When creating the examples based on the information  in the issue with the 1.5.1 version the class wit attribute containing `//` doesn't appear and we get the warning as indicated. 
With the current (1.9.8) doxygen version the class appears and the warning is gone (all looks OK to me).

I think the problem has been solved in the mean time.

Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/12648538/example.tar.gz)
