### ISSUE TITLE
"if"/"while" sometimes interpreted as funcs when in multi-line macros in .h files (Origin: bugzilla #420654)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2423]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[image_src.jpg](https://sourceforge.net/projects/doxygen/files/attachments/bug420654_372684_image_src.jpg/download/download)_ (ID 372684)

On 2007-03-20 18:58:24 +0000, Sheena wrote:

    Please describe the problem:
    If there is a multi-line (all-caps) macro with "\"s in a C header file that
    includes an "if" or a "while", it sometimes gets interpreted as a function.
    
    I got it to reproduce on a very small header file.
    
    Steps to reproduce:
    1. Create a file myheader.h with just the following lines in it:
    #define MYLOCK(foo) \
    { \	
    		while ((foo)->flags & MY_SHARED) { \
    			(foo)->flags |= MY_WAIT; \
    		}\
    		dosleep(blah); \
    }
    
    #define MYLOCK2(foo) \
    { \	
    		if ((foo)->flags & MY_SHARED) { \
    			(foo)->flags |= MY_WAIT; \
    		}\
    		dosleep(blah); \
    }
    
    2. Run doxygen on it.  It seems to happen with SKIP_FUNCTION_MACROS togged
    on or off.
    3. See the html output for it.
    
    
    Actual results:
    Here is the doxygen output, which shows "if" and "while" as functions:
    
    Defines
    #define 	MYLOCK(foo)   { \
    #define 	MYLOCK2(foo)   { \
    
    Functions
     	while ((foo)->flags &MY_SHARED)
     	dosleep (blah)
     	if ((foo)->flags &MY_SHARED)
    
    Expected results:
    "if" and "while" should not be interpreted as functions
    
    Does this happen every time?
    With this syntax, it always happens.  There are other cases of having "\"
    and ifs within macros that do not exhibit this problem
    
    Other information:
    I could get rid of this problem by removing all the "\"s and putting the
    macro on one long line.
    
    Also, I couldn't put the actual code that triggered it on here, so I changed
    a few things around.  It's possible I missed a character so it wouldn't
    compile even if all the macros were defined, but the production code I ran
    this on definitely compiles!
    
    I am running on windows.
    
    The doxyfile is pretty generic -- I picked mostly default options -- but
    here it is anyway:
    # Doxyfile 1.5.1-p1
    
    #---------------------------------------------------------------------------
    # Project related configuration options
    #---------------------------------------------------------------------------
    PROJECT_NAME           = doxybug
    PROJECT_NUMBER         = 1.0
    OUTPUT_DIRECTORY       = "C:/Documents and Settings/Administrator/My
    Documents/work/doxybugdoc"
    CREATE_SUBDIRS         = NO
    OUTPUT_LANGUAGE        = English
    USE_WINDOWS_ENCODING   = YES
    BRIEF_MEMBER_DESC      = YES
    REPEAT_BRIEF           = YES
    ABBREVIATE_BRIEF       = "The $name class" \
                             "The $name widget" \
                             "The $name file" \
                             is \
                             provides \
                             specifies \
                             contains \
                             represents \
                             a \
                             an \
                             the
    ALWAYS_DETAILED_SEC    = NO
    INLINE_INHERITED_MEMB  = NO
    FULL_PATH_NAMES        = YES
    STRIP_FROM_PATH        = "C:/Documents and Settings/Administrator/"
    STRIP_FROM_INC_PATH    = 
    SHORT_NAMES            = NO
    JAVADOC_AUTOBRIEF      = NO
    MULTILINE_CPP_IS_BRIEF = NO
    DETAILS_AT_TOP         = NO
    INHERIT_DOCS           = YES
    SEPARATE_MEMBER_PAGES  = NO
    TAB_SIZE               = 8
    ALIASES                = 
    OPTIMIZE_OUTPUT_FOR_C  = YES
    OPTIMIZE_OUTPUT_JAVA   = NO
    BUILTIN_STL_SUPPORT    = NO
    DISTRIBUTE_GROUP_DOC   = NO
    SUBGROUPING            = YES
    #---------------------------------------------------------------------------
    # Build related configuration options
    #---------------------------------------------------------------------------
    EXTRACT_ALL            = YES
    EXTRACT_PRIVATE        = YES
    EXTRACT_STATIC         = YES
    EXTRACT_LOCAL_CLASSES  = YES
    EXTRACT_LOCAL_METHODS  = YES
    HIDE_UNDOC_MEMBERS     = NO
    HIDE_UNDOC_CLASSES     = NO
    HIDE_FRIEND_COMPOUNDS  = YES
    HIDE_IN_BODY_DOCS      = NO
    INTERNAL_DOCS          = NO
    CASE_SENSE_NAMES       = YES
    HIDE_SCOPE_NAMES       = NO
    SHOW_INCLUDE_FILES     = YES
    INLINE_INFO            = YES
    SORT_MEMBER_DOCS       = YES
    SORT_BRIEF_DOCS        = NO
    SORT_BY_SCOPE_NAME     = YES
    GENERATE_TODOLIST      = YES
    GENERATE_TESTLIST      = YES
    GENERATE_BUGLIST       = YES
    GENERATE_DEPRECATEDLIST= YES
    ENABLED_SECTIONS       = 
    MAX_INITIALIZER_LINES  = 30
    SHOW_USED_FILES        = YES
    SHOW_DIRECTORIES       = NO
    FILE_VERSION_FILTER    = 
    #---------------------------------------------------------------------------
    # configuration options related to warning and progress messages
    #---------------------------------------------------------------------------
    QUIET                  = NO
    WARNINGS               = YES
    WARN_IF_UNDOCUMENTED   = YES
    WARN_IF_DOC_ERROR      = YES
    WARN_NO_PARAMDOC       = NO
    WARN_FORMAT            = "$file:$line: $text"
    WARN_LOGFILE           = 
    #---------------------------------------------------------------------------
    # configuration options related to the input files
    #---------------------------------------------------------------------------
    INPUT                  = E:/doxybug
    FILE_PATTERNS          = *.c \
                             *.cc \
                             *.cxx \
                             *.cpp \
                             *.c++ \
                             *.d \
                             *.java \
                             *.ii \
                             *.ixx \
                             *.ipp \
                             *.i++ \
                             *.inl \
                             *.h \
                             *.hh \
                             *.hxx \
                             *.hpp \
                             *.h++ \
                             *.idl \
                             *.odl \
                             *.cs \
                             *.php \
                             *.php3 \
                             *.inc \
                             *.m \
                             *.mm \
                             *.dox \
                             *.py
    RECURSIVE              = YES
    EXCLUDE                = 
    EXCLUDE_SYMLINKS       = NO
    EXCLUDE_PATTERNS       = 
    EXAMPLE_PATH           = 
    EXAMPLE_PATTERNS       = *
    EXAMPLE_RECURSIVE      = NO
    IMAGE_PATH             = 
    INPUT_FILTER           = 
    FILTER_PATTERNS        = 
    FILTER_SOURCE_FILES    = NO
    #---------------------------------------------------------------------------
    # configuration options related to source browsing
    #---------------------------------------------------------------------------
    SOURCE_BROWSER         = YES
    INLINE_SOURCES         = NO
    STRIP_CODE_COMMENTS    = YES
    REFERENCED_BY_RELATION = YES
    REFERENCES_RELATION    = YES
    REFERENCES_LINK_SOURCE = YES
    USE_HTAGS              = NO
    VERBATIM_HEADERS       = YES
    #---------------------------------------------------------------------------
    # configuration options related to the alphabetical class index
    #---------------------------------------------------------------------------
    ALPHABETICAL_INDEX     = YES
    COLS_IN_ALPHA_INDEX    = 5
    IGNORE_PREFIX          = 
    #---------------------------------------------------------------------------
    # configuration options related to the HTML output
    #---------------------------------------------------------------------------
    GENERATE_HTML          = YES
    HTML_OUTPUT            = html
    HTML_FILE_EXTENSION    = .html
    HTML_HEADER            = 
    HTML_FOOTER            = 
    HTML_STYLESHEET        = 
    HTML_ALIGN_MEMBERS     = YES
    GENERATE_HTMLHELP      = NO
    CHM_FILE               = 
    HHC_LOCATION           = 
    GENERATE_CHI           = NO
    BINARY_TOC             = NO
    TOC_EXPAND             = NO
    DISABLE_INDEX          = NO
    ENUM_VALUES_PER_LINE   = 4
    GENERATE_TREEVIEW      = NO
    TREEVIEW_WIDTH         = 250
    #---------------------------------------------------------------------------
    # configuration options related to the LaTeX output
    #---------------------------------------------------------------------------
    GENERATE_LATEX         = YES
    LATEX_OUTPUT           = latex
    LATEX_CMD_NAME         = latex
    MAKEINDEX_CMD_NAME     = makeindex
    COMPACT_LATEX          = NO
    PAPER_TYPE             = a4wide
    EXTRA_PACKAGES         = 
    LATEX_HEADER           = 
    PDF_HYPERLINKS         = NO
    USE_PDFLATEX           = NO
    LATEX_BATCHMODE        = NO
    LATEX_HIDE_INDICES     = NO
    #---------------------------------------------------------------------------
    # configuration options related to the RTF output
    #---------------------------------------------------------------------------
    GENERATE_RTF           = NO
    RTF_OUTPUT             = rtf
    COMPACT_RTF            = NO
    RTF_HYPERLINKS         = NO
    RTF_STYLESHEET_FILE    = 
    RTF_EXTENSIONS_FILE    = 
    #---------------------------------------------------------------------------
    # configuration options related to the man page output
    #---------------------------------------------------------------------------
    GENERATE_MAN           = NO
    MAN_OUTPUT             = man
    MAN_EXTENSION          = .3
    MAN_LINKS              = NO
    #---------------------------------------------------------------------------
    # configuration options related to the XML output
    #---------------------------------------------------------------------------
    GENERATE_XML           = NO
    XML_OUTPUT             = xml
    XML_SCHEMA             = 
    XML_DTD                = 
    XML_PROGRAMLISTING     = YES
    #---------------------------------------------------------------------------
    # configuration options for the AutoGen Definitions output
    #---------------------------------------------------------------------------
    GENERATE_AUTOGEN_DEF   = NO
    #---------------------------------------------------------------------------
    # configuration options related to the Perl module output
    #---------------------------------------------------------------------------
    GENERATE_PERLMOD       = NO
    PERLMOD_LATEX          = NO
    PERLMOD_PRETTY         = YES
    PERLMOD_MAKEVAR_PREFIX = 
    #---------------------------------------------------------------------------
    # Configuration options related to the preprocessor   
    #---------------------------------------------------------------------------
    ENABLE_PREPROCESSING   = YES
    MACRO_EXPANSION        = NO
    EXPAND_ONLY_PREDEF     = NO
    SEARCH_INCLUDES        = YES
    INCLUDE_PATH           = 
    INCLUDE_FILE_PATTERNS  = 
    PREDEFINED             = 
    EXPAND_AS_DEFINED      = 
    SKIP_FUNCTION_MACROS   = YES
    #---------------------------------------------------------------------------
    # Configuration::additions related to external references   
    #---------------------------------------------------------------------------
    TAGFILES               = 
    GENERATE_TAGFILE       = 
    ALLEXTERNALS           = NO
    EXTERNAL_GROUPS        = YES
    PERL_PATH              = /usr/bin/perl
    #---------------------------------------------------------------------------
    # Configuration options related to the dot tool   
    #---------------------------------------------------------------------------
    CLASS_DIAGRAMS         = NO
    HIDE_UNDOC_RELATIONS   = YES
    HAVE_DOT               = NO
    CLASS_GRAPH            = YES
    COLLABORATION_GRAPH    = YES
    GROUP_GRAPHS           = YES
    UML_LOOK               = NO
    TEMPLATE_RELATIONS     = NO
    INCLUDE_GRAPH          = YES
    INCLUDED_BY_GRAPH      = YES
    CALL_GRAPH             = YES
    CALLER_GRAPH           = YES
    GRAPHICAL_HIERARCHY    = YES
    DIRECTORY_GRAPH        = YES
    DOT_IMAGE_FORMAT       = png
    DOT_PATH               = "C:/Program Files/ATT/Graphviz/bin"
    DOTFILE_DIRS           = 
    MAX_DOT_GRAPH_WIDTH    = 1024
    MAX_DOT_GRAPH_HEIGHT   = 1024
    MAX_DOT_GRAPH_DEPTH    = 1000
    DOT_TRANSPARENT        = NO
    DOT_MULTI_TARGETS      = NO
    GENERATE_LEGEND        = YES
    DOT_CLEANUP            = YES
    #---------------------------------------------------------------------------
    # Configuration::additions related to the search engine   
    #---------------------------------------------------------------------------
    SEARCHENGINE           = YES

On 2018-06-14 09:51:38 +0000, albert wrote:

    Created attachment 372684
    Image of the source code
    
    When looking at the output it is already a bit strange that just the first
    line of the initialization of the define is present in the brief description
    instead of the entire define as value in the detailed description.
    When looking closer at the source code the lines wit `{ \` are not just this
    but there is a <tab> character behind it (I selected the text in the bug
    report and here we see this also quite nice).
    
    For a line to be signaling that it is a to be continued the `\` has to be
    the last character and that is clearly not the case.
    
    Removing the <tab> character solves the problem.
    
    I think this is not a bug but usage.

**Comment by albert-github** [comment]
As written in the previous comment I think think is usage. The `\` has to be the last character of the line.
Also a C compiler will give an error.
