### ISSUE TITLE
C++ code: throw in function definition sometimes interpreted as function name. (Origin: bugzilla #426598)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2439]
status NEW severity *minor* in component *general* for *---*
Reported in version *1.5.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-04-05 13:47:08 +0000, Maarten wrote:

    Please describe the problem:
    When I format a function definition as:
    
      //! Calculate the checksum (CRC32) of a file.
      /*!
       *  \param filename Filename of the file to process.
       *  \return CRC32 of the processed file.
       *  
       *  \exception std::filesystem_error
       */
      unsigned
      CRC32 (const filesystem::path & filename)
      throw (filesystem::filesystem_error)
      {
        ...
      }
    
    Doxygen handles throw as a function name (attaches the given documentation
    to a "throw" function and gives the warning message "Warning: Member
    CRC32(const filesystem::path &filename) (function) of namespace fuzzyfrf is
    not documented.").
    
    When I format the same definition as:
      //! Calculate the checksum (CRC32) of a file.
      /*!
       *  \param filename Filename of the file to process.
       *  \return CRC32 of the processed file.
       *  
       *  \exception std::filesystem_error
       */
      unsigned CRC32 (const filesystem::path & filename) throw
    (filesystem::filesystem_error)
      {
        ...
      }
    
    (so the full definition on one line, or even the "unsigned CRC32 (const
    filesystem::path & filename)" on one line and the "throw
    (filesystem::filesystem_error)" on the next line, the documentation is
    correctly generated.
    
    When formatting more than one function in the problematic format, I also get
    a warning that "Warning: member throw: ignoring the detailed description
    found here, since another one was found at line 40 of file ...".
    
    Steps to reproduce:
    See problem description.
    
    Actual results:
    See problem description.
    
    Expected results:
    Since the C++ standard allows linebreaks between the return type and the
    function name, I would expect Doxygen to generate the correct (second
    formatting in the problem description) documentation, whether there is a
    linebreak or a space between the return type and the function name.
    
    Does this happen every time?
    Yes.
    
    Other information:
    The problem is quite easy to avoid by formatting the source code as in the
    second example in the problem description.

On 2007-04-06 14:46:37 +0000, Maarten wrote:

    This seems to happen only for 'standalone' functions, not for class members.

**Comment by albert-github** [comment]
This is a problem of the using of `SKIP_FUNCTION_MACROS=YES` (the default setting:
> `SKIP_FUNCTION_MACROS` If the `SKIP_FUNCTION_MACROS` tag is set to YES then doxygen's preprocessor
will remove all references to function-like macros that are alone on a line, have an all uppercase name, and
do not end with a semicolon. Such function macros are typically used for boiler-plate code, and will confuse
the parser if not removed.

The multi-line definition fits this description. When setting `SKIP_FUNCTION_MACROS=NO` everything goes smooth (doxygen version 1.5.1 and the current, 1.9.8, version).

I think the problem is usage.
