### ISSUE TITLE
Manpages may be installed with wrong permissions (Origin: bugzilla #426854)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2442]
status NEW severity *minor* in component *build* for *---*
Reported in version *1.5.2* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-04-06 08:36:28 +0000, Martni Petricek wrote:

    I noticed nothing like "chmod" or "install" when building manpages for
    doxygen
    If root is too paranoid and have umask set to 077, it may result in
    installed manpages to be unreadable to anyone except root, if installing for
    first time. Chmodding the installed manpages shoud fix this.
    
    How to reproduce:
    
    run "./configure" and "make" first, then:
    
    root@__:/home/source/doxygen-1.5.2# rm /usr/local/man/man1/doxy*
    root@__:/home/source/doxygen-1.5.2# umask 077
    root@__:/home/source/doxygen-1.5.2# make install
    /usr/bin/install -d /usr/local/bin
    /usr/bin/install -m 755 bin/doxygen    /usr/local/bin
    /usr/bin/install -m 755 bin/doxytag    /usr/local/bin
    /usr/bin/install -d /usr/local/man/man1
    cat doc/doxygen.1    | sed -e "s/DATE/April 2007/g" -e "s/VERSION/1.5.2/g" >
    /usr/local/man/man1/doxygen.1 ; \
            cat doc/doxytag.1    | sed -e "s/DATE/April 2007/g" -e
    "s/VERSION/1.5.2/g" > /usr/local/man/man1/doxytag.1 ; \
            cat doc/doxywizard.1 | sed -e "s/DATE/April 2007/g" -e
    "s/VERSION/1.5.2/g" > /usr/local/man/man1/doxywizard.1 ;
    root@medv3d2:/home/source/doxygen-1.5.2# ls -l /usr/local/man/man1/doxy*
    -rw------- 1 root root 1421 2007-04-06 10:26 /usr/local/man/man1/doxygen.1
    -rw------- 1 root root  687 2007-04-06 10:26 /usr/local/man/man1/doxytag.1
    -rw------- 1 root root  336 2007-04-06 10:26
    /usr/local/man/man1/doxywizard.1
    root@__:/home/source/doxygen-1.5.2#
    
    Only root can read these manpages ...

**Comment by albert-github** [comment]
This has probably to do with the used `umask` and is outside the scope of doxygen and I think it is usage.
