### ISSUE TITLE
Doxygen loses current directory during nested #includes (Origin: bugzilla #428460)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2447]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.2* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-04-11 01:55:47 +0000, John Burger wrote:

    +++ This bug was initially created as a clone of Bug # 373229 +++
    
    Thank you for adding the Warning in 1.5.2, since it allowed me to give you
    more information on the problem. I left the original bug report from the
    Clone operation below, with its follow-up information.
    
    Now I get the following warning (or equivalent, around 30 times):
    
    C:/Projects/Client/Status//Cells/Cell.ipp:38: Warning: include file
    ../PopUps/PopUp.ipp not found, perhaps you forgot to add its directory to
    INCLUDE_PATH?
    
    Note the full path name includes a // instead of a / - it is at the place
    you had to manipulate the directory name to process the #include. My theory
    is that when you manipulate the directory a second time it causes a /// to
    appear, which probably won't parse!
    
    === Original bug report, with follow-up information ===
    
    I ensure that every class is in its own file - even nested classes.
    I do that by using #include as follows:
    
    // Outer.hpp
    class Outer {
    public:
       class Middle;
    #include "Middle.ipp"
    }; // Outer
    
    DOxygen handles that fine - although it ignores #includes at file scope, it
    seems to recognise that this #include is within a context, so it reads the
    indicated file. This is why the nested files use the .ipp extension, to stop
    DOxygen reading them "out of context" with "FILE_PATTERN=*.hpp *.cpp".
    
    Now look at Middle.ipp and Middle.cpp:
    
    // Middle.ipp
    class Middle {
    public:
       class Inner;
    #include "Inner.ipp"
       Middle();
    }; // Middle
    
    // Middle.cpp
    #include "Outer.hpp"
    Outer::Middle::Middle() {
    } // Middle::Middle()
    
    And now at Inner.ipp and Inner.cpp:
    
    // Inner.ipp
    class Inner {
    public:
       Inner();
    }; // Inner
    
    // Inner.cpp
    #include "Outer.hpp"
    Outer::Middle::Inner::Inner() {
    } // Inner::Inner()
    
    DOxygen processes this whole hierarchy correctly IF all of the files are in
    the project's "home" directory.
    
    If however they are in a subdirectory, and the configuration file has either
    RECURSIVE=YES or the explicit directory added to the INPUT= line, then a
    warning is issued, and Inner is not mentioned anywhere in the results:
    
    SubDir/Inner.cpp:3: Warning: documented function
    `Outer::Middle::Inner::Inner' was not declared or defined.
    
    Note that it doesn't complain about Outer::Middle::Middle, which is also
    declared inside a #include - DOxygen does it correctly the first time, just
    not any nested ones.
    
    In my actual project, I also get the following types of warnings (mapped to
    this example, since I can't reproduce them):
    
    Warning: no matching class member found for
        unsigned int Outer::Middle::Inner::Num() const
    
    Warning: no uniquely matching class member found for
        const char * Outer::Middle::Inner::Name() const
    
    Again, no problems with any of the Outer::Middle functions
    
    I have over three hundred (300) sub-directories, up to four
    levels deep - I need to use the implicit "current directory" concept simply
    to
    maintain my sanity. All of my #includes use relative path names (#include
    "../../Library1/SubDir2/Header.hpp")
    
    I always use forward declarations, except when I can't:
    
    class Outer {
    public: // Classes
       class Middle;
       #include "Middle.ipp"
    private: // Variables
       Middle &ref;     // This could use a forward declaration
       Middle internal; // This, unfortunately, can't
    }; // Outer
    
    I can't use forward declarations around 100 times in my project. Of those
    100,
    around 30 have their own internal classes that can't use forward
    declarations.
    All of my warnings at the moment are complaining about those
    classes-inside-classes-inside-classes.
    
    Middle.ipp is found without any problems.
    Why should Inner.ipp (in the same subdirectory) be any different?

**Comment by albert-github** [comment]
With the 1.5.2 version we get the warning:
```
Middle.ipp:11: Warning: include file Inner.ipp not found, perhaps you forgot to add its directory to INCLUDE_PATH?
```
with the current doxygen version (1.9.8) the warning is gone.
Also when adding `INCLUDE_PATH = Subdir` in the setup for the 1.5.2. version the warning is gone.


I think this problem has been solved in the mean time.
