### ISSUE TITLE
\version before \brief in file documentation generates wrong output (Origin: bugzilla #429261)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2450]
status NEEDINFO severity *normal* in component *general* for *---*
Reported in version *1.5.2* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-04-13 08:43:58 +0000, Lars Friedrich wrote:

    /// \file mbduconf.h
    ///
    /// \version 0.1
    ///
    /// \brief Header file for the configuration data unit
    
    generates the output:
    
    Version:
      0.1Header file for the configuration data unit
    
    (The \brief documentation is appended directly to the version paragraph.
    Note also that there is no period at the end of the \brief)
    
    switching the position of the Doxygen commands:
    /// \file mbduconf.h
    ///
    /// \brief Header file for the configuration data unit
    ///
    /// \version 0.1
    
    generates the expected outout:
    
    Header file for the configuration data unit. 
    
    Version:
      0.1
    
    (\brief documentation and version in different paragraphs, period at the end
    of the \brief description was added (correctly).)

On 2014-06-08 17:27:40 +0000, albert wrote:

    I tried to reproduce the problem but was not able to (not with version 1.5.2
    or 1.5.1, 1.4.0 or 1.3.1).
    
    Please check if the problem still occurs with the current version of
    doxygen.
    
    If you still see this issue with the latest version of doxygen please add a
    self-contained example (source+config file in a zip or tar).

**Comment by albert-github** [comment]
As written before, the problem is not reproducible.
