### ISSUE TITLE
Member function reference incorrectly interpreted as a call (Origin: bugzilla #429355)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2452]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.2* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-04-13 13:41:54 +0000, Michael Macnair wrote:

    The call graph for the following function displays two calls - one to foo
    and one to ClassName::bar.  This is incorrect, as there is only one call -
    that to foo.
    
    void UseReference()
    {
      foo(&ClassName::bar);
    }
    
    I can see how showing bar's calls would be useful (there is no direct way of
    seeing them if foo calls bar, as seems likely), however the call graph is
    still wrong.

**Comment by albert-github** [comment]
Based on the given information it is not possible to reproduce the problem. It is unclear how `foo` and `bar` are defined .

I think the problem is incomplete.
