### ISSUE TITLE
ODL - MemberType: Missing properties and using id as property name and property name as type (Origin: bugzilla #432893)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2463]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.2* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-04-24 09:21:55 +0000, Andreas Laag wrote:

    Please describe the problem:
    If you run doxygen on ODL files from MFC ActiveX Controls that contains
    dispinterfaces and member properties in the section properties:, the names
    of the properties will not be used. Instead the disp-id-Tag will be used as
    name of the property. The name of the property becomes the type of the
    property in the documentation. Also are some of the properties missing in
    the documentation.
    
    
    
    
    Steps to reproduce:
    1. Use example autoclik from MSDN
    	dispinterface IAClick
    	{
    		properties:
    			[id(1)] BSTR text;
    			[id(2)] short x;
    			[id(3)] short y;
    			[id(4)] IDispatch* Position;
    			
    		methods:
    			// ...
    	};
    2. and run doxygen
    
    
    
    Actual results:
    The output will contain the following data:
    
    Properties 
    x  id 
    Position  id 
    The properties text and Position are missing. The names of the properties
    are id, the type are the names.
    
    Expected results:
    Properties
    BSTR text
    short x
    short y
    IDispatch* Position
    
    Does this happen every time?
    
    
    Other information:

On 2007-04-26 14:05:39 +0000, Andreas Laag wrote:

    Changing Property to Method in the following code in scanner.l solves the
    problem for me, but it needs to be tested if it still works for C++ Builder.
    
    <FindMembers>{B}*("properties"){BN}*":"{BN}*  { 
    // IDL or Borland C++ builder property
        //OLD CODE: current->mtype = mtype = Property;
        current->mtype = mtype = Method; // FIXES PROBLEM, but maybe causes new
    ones
    

On 2009-07-24 21:56:12 +0000, david r clarke wrote:

    I have seen this with both 1.4.7 and 1.5.9.
    Apparently, this method of declaring properties isn't as widely used as
    the "[id(1), propget, bindable, defaultbind, displaybind] long x();" style.
    
    
    1. Workaround
    Based on the example in description "Steps to reproduce".
    Use the method described in Doxygen's "Frequently Asked Questions"
      4. How can I make doxygen ignore some code fragment?
    
    And thus:
                #ifndef DOXYGEN_SHOULD_SKIP_THIS
                    properties:
                #else
                    methods:
                #endif
    
                            [id(1)] BSTR text;
                            [id(2)] short x;
                            [id(3)] short y;
                            [id(4)] IDispatch* Position;
    
                #ifndef DOXYGEN_SHOULD_SKIP_THIS
                    methods:
                #endif
    
    Doxygen treats these declarations as "Public Attributes" and happily
    documents them.
    
    
    2. Additional info re bug:
    Any methods following the properties are also mishandled. They are lumped
    with Properties, and generally have incorrect outputs and in some cases,
    mangled parameters.
    
    Also, if the example is reconfigured like so:
                            /** One: text */
                            [id(1)] BSTR text;
                            /** Two: x */
                            [id(2)] short x;
                            /** Three: y */
                            [id(3)] short y;
                            /** Four: Position */
                            [id(4)] IDispatch* Position;
    
    The output will be more like this:
    
    Properties 
      x  id 
      One: text
    
      Position  id 
      Three: y
    
    

On 2011-06-28 15:43:55 +0000, mgray88@gmail.com wrote:

    This is still a bug in 1.7.4
    
    Thankfully, David's workaround still works

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.13.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
