### ISSUE TITLE
Handling of unnamed parameters (C/C++) unclear (Origin: bugzilla #436883)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2478]
status NEW severity *minor* in component *general* for *---*
Reported in version *1.5.2* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-05-08 13:28:30 +0000, Victor V. Terber wrote:

    Handling of unnamed parameters at least unclear
    
    If unnamed parameters are used, as for example
    
    testFunction (const char * const, const double param2);
    
    Doxygen might emit
     
    G:/test.h:25: Warning: The following parameters of testFunction (const char
    * const, const double param2) are not documented:
    parameter const
    
    It doesn't help if I document the parameter with an arbitrary name. I just
    get a different warning.
    
    I understand that this might be related to feature enhancement 152990
    ("Allow to document unnamed function arguments in prototypes", but still
    looks slightly different, as I assumed that Doxygen's parser would identify
    the "const" keyword and there have the knowledge that it is no possible
    variable name.
    
    Is this the intended behaviour?
    
    Thank you very much for your ongoing support of this great software!

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6396, second part.
See also issue #2859

**Comment by albert-github** [comment]
Code has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
