### ISSUE TITLE
URLs in a @dotfile are difficult with CREATE_SUBDIRS (Origin: bugzilla #438533)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2486]
status NEW severity *normal* in component *general* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-05-15 08:14:12 +0000, Peter Steiner wrote:

    When you create your own dot files and include them in the documentation
    with the @dotfile command, URLs in the dot file are not expanded (the $ sign
    is ignored).
    
    You can use relative URLs in the dot file, but these are difficult if you
    use CREATE_SUBDIRS=YES, because you have to find out the correct directory
    (e.g d3/d8c/some_link.html).

On 2008-10-22 14:34:23 +0000, Peter Dittmann wrote:

    It is not necessary in dot files to use relative URLs.
    Simly use URL="\ref name" with symbolic names that link to symbolic names in
    the documentation.
    Doxygen will then generate the link automaticly.
    
    Example *.dot file cut:
    
    digraph mtk_tld_main {
        node [shape=plaintext, fontname=Helvetica, fontsize=10, labeljust=L,
    fontcolor=grey ];
        l_appl [label="Application Layer", labeljust=L, URL="\ref application"];
        l_serv [label="Service Layer", labeljust=L, URL="\ref service"];
        l_logdrv [label="Device or Logical\nDriver Level", labeljust=L,
    URL="\ref driver_log"];
        l_phydrv [label="Bus Driver Level"; labeljust=L, URL="\ref driver_bus"];
        l_hw [label="Hardware Driver Level"; labeljust=L, URL="\ref driver_hw"];
            }
    
    For instance "driver_bus" and "driver_log" link to defined groups in another
    documantation source file:
    
    /*! \defgroup driver_log Device or Logical Drivers
    
    	Device or Logical Drivers.
    
    */
    
    /*! \defgroup driver_bus Bus Drivers
    
    	Drivers for Bus systems
    
    */
    
    
    
    

On 2008-12-22 14:10:18 +0000, Dimitri van Heesch wrote:

    I agree with comment # 1. I'll leave this bug open in case others run into
    the same issue.

**Comment by albert-github** [comment]
A noted in the comments on the issue the linking is typically done by means of the `\ref` command.

I think the problem (as also suggested by the last comment) is usage
