### ISSUE TITLE
Lower case class names are not auto-linked (Origin: bugzilla #440234)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2488]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.5.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-05-21 17:55:24 +0000, Andreas Kloeckner wrote:

    I have a C++ library that's written according to STL/Boost naming
    conventions [1], i.e. using all-lower-case class names. Doxygen does not
    auto-link these class names. I was wondering if there is a way to change
    that, or if not, maybe such an option could be added.
    
    Thanks!
    
    [1] http://www.boost.org/more/lib_guide.htm#Guidelines

**Comment by albert-github** [comment]
The documentation states:

> All  words in the documentation that correspond to a documented class and contain at least one non-lower case character will automatically be replaced by a link to the page containing the documentation of the class. If you want to prevent that a word that corresponds to a documented class is replaced by a link you should put a % in front of the word. To link to an all lower case symbol, use \ref.

A test (in 1.8.15) also shows that this is still the case.

@doxygen 
- is there a special reason why lower case class names are not automatically linked?
- is it useful to fix this ?

**Comment by albert-github** [comment]
As documented this is by design and, probably, done so that "normal" words that are also used as class names are not automatically linked. As written there are possibilities to link to these class names (like `\ref` but also by means of `#`)

I think the problem is usage.
