### ISSUE TITLE
Incorrect processing of "using namespace" wtih EXTRACT_ALL (Origin: bugzilla #440638)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2491]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.2* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-05-23 07:44:44 +0000, Alexei Alexandrov wrote:

    When processing the following example code
    
    namespace my_namespace
    {
        using namespace some_external_namespace;
    }
    
    int main()
    {
        return 0;
    }
    
    with EXTRACT_ALL set to 'yes', the list of namespaces contains
    'some_external_namespace'. This is not expected, since this namespace is
    just used by my namespace and I don't declare any members in that namespace.

**Comment by albert-github** [comment]
With the doxygen version 1.5.2 we see:
![image](https://github.com/doxygen/doxygen/assets/5223533/8108efc8-331d-4842-b94e-9b383238ef19)
and
![image](https://github.com/doxygen/doxygen/assets/5223533/824a8676-1468-4297-a12b-b7e43c825e09)


with the current doxygen version (1.9.8) we see:
![image](https://github.com/doxygen/doxygen/assets/5223533/19d7af79-40b5-4b24-9dfd-616a6ffe60ae)
and
![image](https://github.com/doxygen/doxygen/assets/5223533/24385d58-599f-4df0-b614-daa73b619310)


I think the problem has been solved in the mean time.
