### ISSUE TITLE
forward declaration and namespace listing (c++) (Origin: bugzilla #440703)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2493]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-05-23 13:37:10 +0000, Antonio Bulgheroni wrote:

    Please describe the problem:
    If I forward declare a class belonging to another external namespace like
    this:
    
    [code]
    namespace OtherNamespace {
       class OtherClass;
    }
    [/code]
    then in the Namespace List, OtherNamespace will appear even if not
    documented.
    
    Steps to reproduce:
    1. Try to write the example above into a piece of code
    2. Run doxygen
    3. look at the html output
    
    
    Actual results:
    OtherNamespace will appear even if not documented. 
    
    Expected results:
    The namespace list should be empty! 
    
    Does this happen every time?
    yes
    
    Other information:
    Linux 2.6.20-1.2948.fc6 # 1 SMP Fri Apr 27 19:18:54 EDT 2007 x86_64 x86_64
    x86_64 GNU/Linux
    
    gcc (GCC) 4.1.1 20070105 (Red Hat 4.1.1-51)

**Comment by albert-github** [comment]
I tried to reproduce the problem with doxygen version 1.5.1 but was not able to with the limited information.
I used:
**Doxyfile**:
```
QUIET = YES
```
and the file 
**a.h**
```
namespace OtherNamespace {
   class OtherClass;
}
```

So I think the issue is not reproducible due to lack of information.
