### ISSUE TITLE
Ability to group "related pages" (Origin: bugzilla #441186)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2497]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.5.3-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-05-25 12:58:29 +0000, Jonathan Lynch wrote:

    Ability to group "related pages" in a hierarchy (generated with xrefitem)

On 2007-10-15 19:41:05 +0000, Dimitri van Heesch wrote:

    This bug's version was set to "latest". Since this is a moving target, I
    changed it to 1.5.3-SVN. If you believe this has already been fixed, then
    please change the status accordingly.

**Comment by albert-github** [comment]
It is unclear what exactly is meant with: Ability to group "related pages" in a hierarchy (generated with xrefitem)

I think the problem is incomplete
