### ISSUE TITLE
Select folder for STRIP_FROM_PATH (Origin: bugzilla #445536)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2512]
status NEW severity *enhancement* in component *doxywizard* for *---*
Reported in version *1.5.2* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-06-08 15:49:16 +0000, Christian Moritz wrote:

    It would be rather nice if one could select the path to be stripped by a
    dialog, like the OUTPUT_DIRECTORY, instead of having to type it in.
    
    That would reduce the risk of mistakes in the paths.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #9231

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).
