### ISSUE TITLE
No brief docs for duplicate filenames (in sep. directories) (Origin: bugzilla #459499)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2551]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.2* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-07-23 11:13:11 +0000, duelli@melosgmbh.de wrote:

    Consider the following scenario
    a/test.c
    b/test.c
    
    Both files have an entry like
    /*!
    \file test.c
    \author ...
    \date ...
    
    \brief Brief desc for test.c
    */
    
    
    When documentation is generated, *no* short help is generated for either
    file.
    If one file is renamed, documentation is generated.

**Comment by albert-github** [comment]
With version 1.5.2 and a standard Doxyfile with only `RECURSIVE=YES` we get for the 1.5.2. version:
```
.../a/test.c:2: Warning: the name `test.c' supplied as the second argument in the \file statement matches the following input files:
   .../a/test.c
   .../b/test.c
Please use a more specific name by including a (larger) part of the path!
.../b/test.c:2: Warning: the name `test.c' supplied as the second argument in the \file statement matches the following input files:
   .../a/test.c
   ../b/test.c
```

With version 1.9.1 we get no warnings and we see the brief documentation for both.

I think the problem has been solved in the mean time
