### ISSUE TITLE
Enums in classes not shown if SEPARATE_MEMBER_PAGES is set to YES (Origin: bugzilla #460487)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2555]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.2* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[patch.enum.txt](https://sourceforge.net/projects/doxygen/files/attachments/bug460487_130359_patch.enum.txt/download/download)_ (ID 130359)

On 2007-07-26 08:07:54 +0000, John Madsen wrote:

    Please describe the problem:
    If setting SEPARATE_MEMBER_PAGES to YES (with NO everything works) the
    detailed documentation of an enum defined within a class does not show. Also
    the documentation of each value is not shown.
    
    Steps to reproduce:
    1. Save the following file
    /**
     * @brief My brief description.
     */
    class MyClass
    {
      public:
        /**
         * @brief My brief enum description.
         *
         * My detailed description (now shown?).
         */
        enum MyEnum
        {
          MY_VALUE1,  ///< My description of value 1 (now shown?).
          MY_VALUE2,  ///< My description of value 2 (now shown?).
          MY_VALUE3   ///< My description of value 3 (now shown?).
        }
    };
    
    2. Let doxygen generate a default Doxyfile and change INPUT to the above
    created file. Also set SEPARATE_MEMBER_PAGES to YES. Then run doxygen to
    produce the html output. In a web browser the problem is shown when trying
    to access the detailed documentation of the enumeration.
    
    Actual results:
    
    
    Expected results:
    
    
    Does this happen every time?
    
    
    Other information:

On 2009-03-07 00:42:46 +0000, Michael Dilworth wrote:

    This still happens in 1.5.8, when SEPARATE_MEMBER_PAGES is yes, the html
    page for the enum is blank. However in the class page the values are listed,
    so doxygen is parsing the enum, just not outputting the html for the
    member docs.
    
    If SEPARATE_MEMBER_PAGES is set to no, or the enum is defined outside
    (global)
    of the class everything works as expected.

On 2009-03-10 00:49:39 +0000, Michael Dilworth wrote:

    Created attachment 130359
    Temporary fix...
    
    Comments in the "svn diff" patch explain the problem.
    Someone seems to have a plan for enum values, but it is 
    incomplete.

On 2009-03-19 17:45:51 +0000, Simon Trahan wrote:

    The patch does help, indeed. However, special tags within the enum
    documentation are not correctly parsed; in my case, it's the \bug tag that
    does not do what it's supposed to ("Bug" header and information on the
    "Bugs" page).

**Comment by albert-github** [comment]
With the 1.5.2 version we see on the detailed page, when `SEPARATE_MEMBER_PAGES=YES`:

![image](https://user-images.githubusercontent.com/5223533/177561414-ea15c044-26d4-4dd7-abf3-69fceb38bd7c.png)

and when `SEPARATE_MEMBER_PAGES=NO`:

![image](https://user-images.githubusercontent.com/5223533/177561671-3fe0690f-a4b0-421e-9eec-4b154e8d4503.png)


For the 1.9.4 version we see in both cases:

![image](https://user-images.githubusercontent.com/5223533/177561793-79124d2c-28b9-42e1-baea-1d2ce675930b.png)


I think the problem has been solved in the mean time.
