### ISSUE TITLE
Commandline-parameter for quiet operation (Origin: bugzilla #464997)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2575]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.5.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-08-09 10:44:55 +0000, HaJo Gurt wrote:

    A commandline-parameter (like -q) for overriding
    the "QUIET=NO" - setting in Doxyfile would be nice,
    to force a quiet operation, i.e. only show errors 
    and warnings.
    
    Other information:

On 2007-08-12 09:05:23 +0000, Dimitri van Heesch wrote:

    I'll mark this as an enhancement request.
    
    Note that you can already do it like this on Unix:
    
    (cat Doxyfile ; echo "QUIET=YES") | doxygen -

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #8651

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.2.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
