### ISSUE TITLE
Formatting-options for $datetime (Origin: bugzilla #466064)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2580]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.5.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-08-12 21:01:40 +0000, HaJo Gurt wrote:

    For localizing the date and time on the generated html-pages,
    it would be nice if the format used by $datetime could be
    specified, just like for strftime.
    
    Also, there is $date, but no $time.

**Comment by albert-github** [comment]
Regarding the `$time` I've just pushed a proposed patch, pull request #9692

Since doxygen 1.9.5 we have the command `\showdate`, maybe this can be used for / as base for a commend `$showdate(fmt)`

**Comment by albert-github** [comment]
Regarding the format possibility I've just pushed a proposed patch, pull request https://github.com/doxygen/doxygen/pull/9696 adding a `$showdate(format)`

**Comment by albert-github** [comment]
Proposed pull request #9696 is open.

**Comment by albert-github** [comment]
A different version has been implemented (see https://github.com/doxygen/doxygen/commit/6c4c78fabd428bb58e78645402bf4aee74778972)

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.7.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
