### ISSUE TITLE
Add/fix build support for Visual Studio 6.0, 2002, and/or 2003 (Origin: bugzilla #466073)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2581]
status NEW severity *enhancement* in component *build* for *---*
Reported in version *1.5.3* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-08-12 22:08:29 +0000, jmckesson@ca.rr.com wrote:

    Please describe the problem:
    Doxygen's windows build includes projects for VS2005, but these project
    files are not backwards compatible with VS2003 or VS2002.
    
    The very old VS6.0 build files do not work either. Attempting to compile
    them in VS2003 causes a number of linker errors.
    
    Steps to reproduce:
    1. Attempt to load the VS2005 files in VS2003, but VS2003 will report an
    error.
    2. Attempt to load the VS6.0 under VS2003 and compile. Compile fails.
    3. 
    
    
    Actual results:
    You cannot compile.
    
    Expected results:
    You should be able to compile.
    
    Does this happen every time?
    Yes.
    
    Other information:

On 2007-08-17 19:57:49 +0000, Dimitri van Heesch wrote:

    Only VS2005 (including the free Express version) is supported as a build
    environment for Windows.
    
    I do not have time to maintain older build environments myself, but I'll
    accept patches and will mark this as an enhancement request.

On 2008-12-22 11:55:54 +0000, Raja Kajiev wrote:

    BTW, why not use Eclipse IDE?

**Comment by albert-github** [comment]
In the year doxygen has changed the build usage from `qmake` to `cmake` (doxygen version 1.8.10) so the versions as supported by `cmake` are more or less supported automatically to build doxygen

So I think this problem has been solved in the mean time.
