### ISSUE TITLE
Broken anonymous union data in XML (Origin: bugzilla #473140)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2604]
status REOPENED severity *normal* in component *general* for *---*
Reported in version *1.5.3* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[test.h](https://sourceforge.net/projects/doxygen/files/attachments/bug473140_94857_test.h/download/download)_ (ID 94857)
- _[Doxyfile](https://sourceforge.net/projects/doxygen/files/attachments/bug473140_94858_Doxyfile/download/download)_ (ID 94858)

On 2007-09-03 12:06:10 +0000, Denis Shergin wrote:

    The following C++ code fragment seems to be processed in the wrong way with
    XML output, while it's OK with HTML one (the same is for classes with
    anonymous unions inside):
    
    struct test_struct_a {
    	union {
    		struct {
    			float x,y,z;
    		};
    		float v[3];
    	};
    };
    
    Doxygen produces this useless output:
    <definition>union test_struct_a::@0 test_struct_a::@1</definition>
    while there are no definitions for @0 and @1 elements.
    
    So one can't assemble back the information about anonymous union from this
    XML files, while these unions are processed correctly into HTML format by
    Doxygen.
    
    Named unions are processed without such problems.
    
    The bug reproduces with 1.4.7 (Slackware 11.0), 1.5.1 (Ubuntu 7.0.4), 1.5.3
    (Slackware 11.0).

On 2007-09-03 12:07:56 +0000, Denis Shergin wrote:

    Created attachment 94857
    test source code

On 2007-09-03 12:08:17 +0000, Denis Shergin wrote:

    Created attachment 94858
    Doxyfile

On 2007-09-19 18:41:10 +0000, Dimitri van Heesch wrote:

    Confirmed. Should be fixed in the next CVS update.

On 2007-10-27 09:14:24 +0000, Dimitri van Heesch wrote:

    This bug had the status ASSIGNED, which means that the problem should be
    fixed in doxygen version 1.5.4 which has just been released. If this is not
    the case then please reopen the bug (and provide additional information if
    needed).

On 2008-04-22 16:43:15 +0000, Mark Courtney wrote:

    This doesn't appear to be fully resolved in the XML output for doxygen
    version 1.5.4.
    
    Using the original example, x, y, and z are output as immediate members of
    test_struct_a, like:
    <definition>float test_struct_a::x</definition>
    
    No information about the anonymous inner union or anonymous inner struct is
    output in the XML output. This makes it impossible to reconstruct an
    accurate definition.
    
    The best that can be achieved is:
    struct test_struct_a {
       float x,y,z;
       float v[3];
    };
    
    However, an accurate definition is created for doxygen's HTML output, with
    anonymous union and anonymous struct in place.
    
    From the original problem...
    <definition>union test_struct_a::@0 test_struct_a::@1</definition>
    ...this definition probably still needs to appear but with @0 and @1
    properly defined somewhere in the XML output in order recreate the entire
    definition.
    

On 2008-04-22 16:55:48 +0000, Mark Courtney wrote:

    The following also produces anonymous union definition problems in XML
    output:
    
    typedef struct test_struct_b {
       union {
           struct {
               float a,b;
           } s;
       };
    };
    
    XML result fragment:
    <memberdef kind="variable" [...snip...]>
       <type>struct test_struct_b::@0::@2</type>
       <definition>struct test_struct_b::@0::@2  test_struct_b::s</definition>
       <argsstring></argsstring>
       <name>s</name>
       [...snip...]
    
    Again, @0 and @2 are not defined anywhere else in the XML output.
    
    (This latest output was produced with doxygen version 1.5.5 on Windows Vista
    SP1.)

On 2008-05-06 20:52:38 +0000, Dimitri van Heesch wrote:

    Reopened on request.

On 2008-05-06 20:53:07 +0000, Dimitri van Heesch wrote:

    *** Bug 531715 has been marked as a duplicate of this bug. ***

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #9976

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).
