### ISSUE TITLE
False positive warnings when matching C++ signatures (Origin: bugzilla #479826)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2630]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.3* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-09-24 14:08:33 +0000, Frans Englich wrote:

    Please describe the problem:
    doxygen prints many false positive warnings when trying to match signatures.
    For instance:
    
    virtual xsDecimal Patternist::AbstractFloat< isDouble >::toDecimal() const
    at line 78 of file
    /home/fenglich/dev/qt/src/xml/query/data/qabstractfloat_p.h
    /home/fenglich/dev/qt/src/xml/query/data/qabstractfloat.cpp:200: Warning: no
    uniquely matching class member found for
    
    The C++ is valid, it compiles with several different compilers, but doxygen
    fails to understand it.
    
    
    Steps to reproduce:
    1. Download a recent source snapshot of Qt from
    http://trolltech.com/developer/downloads/qt/snapshots. For instance
    ftp://ftp.trolltech.com/qt/snapshots/qt-x11-opensource-
    src-4.4.0-snapshot-20070924.tar.bz2
    2. Unpack it, and set the environment variable QTSRCDIR to the folder of the
    snapshot
    3. do `svn checkout svn://labs.trolltech.com/svn/internet/patternist'
    4. do `cd patternist && doxygen'
    
    Wait until the 26'th with reproducing this, since the snapshot needs an
    update.
    
    Actual results:
    
    
    Expected results:
    That doxygen understood the C++ and generated call graphs and so forth.
    
    If this is not doable, it would be preferable if the warnings are not
    reported, since one cannot do anything about them, and they are not useful.
    
    Does this happen every time?
    Yes.
    
    Other information:

On 2009-02-06 15:04:08 +0000, Frans Englich wrote:

    Is it possible that this get fixed? It's very hard to make use of
    doxygen(which is total kick-ass) when the warning log is *filled* with
    things that doesn't need fixing! :)

**Comment by albert-github** [comment]
I downloaded the current Qt version (5.12.2) and started doxygen in the directory qtxmlpatterns\src\xmlpatterns 
- doxygen 1.5.3: got 147 'no uniquely matching class member found' messages
- doxygen 1.8.15: got 1 message and looking at this I think it is correct that the message is given (qualified and unqualified class name).
  - message on:
     - QXmlNodeModelIndex MyTreeModel::nextFromSimpleAxis(SimpleAxis axis, const QXmlNodeModelIndex &ni) const
  - possibilities:
       - virtual QXmlNodeModelIndex nextFromSimpleAxis(QAbstractXmlNodeModel::SimpleAxis, const QXmlNodeModelIndex&) const;
       - virtual QXmlNodeModelIndex nextFromSimpleAxis(SimpleAxis axis, const QXmlNodeModelIndex &origin) const = 0;

I think the problem has been solved in the mean time
