### ISSUE TITLE
ru translation improvement (Origin: bugzilla #480725)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2633]
status NEW severity *minor* in component *general* for *---*
Reported in version *1.5.3* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-09-26 19:12:06 +0000, ÐÐµÑÑÐ¸Ð½ Ð®ÑÐ¸Ð¹ wrote:

    virtual QCString trDocumentation()
        { return decode("- Ð¿ÑÐ¾Ð³ÑÐ°Ð¼Ð¼Ð½Ð°Ñ Ð´Ð¾ÐºÑÐ¼ÐµÐ½ÑÐ°ÑÐ¸Ñ"); }
    
    
    Other information:
    Ð ÑÐ¾ ÐºÐ°Ðº-ÑÐ¾ Ð½Ðµ ÑÐ¸ÑÐ°ÐµÑÑÑ, Ð½Ðµ Ð¿Ð¾-ÑÑÑÑÐºÐ¸ ÑÑÐ¾:
    Doxygen ÐÐ¾ÐºÑÐ¼ÐµÐ½ÑÐ°ÑÐ¸Ñ
    Ð»ÑÑÑÐµ Ð½Ð°Ð¾Ð±Ð¾ÑÐ¾Ñ, Ð¸Ð»Ð¸ ÑÐ¾ÑÑ Ð±Ñ:
    Doxygen - Ð¿ÑÐ¾Ð³ÑÐ°Ð¼Ð¼Ð½Ð°Ñ Ð´Ð¾ÐºÑÐ¼ÐµÐ½ÑÐ°ÑÐ¸Ñ

On 2007-09-26 19:14:39 +0000, ÐÐµÑÑÐ¸Ð½ Ð®ÑÐ¸Ð¹ wrote:

    ÐÑÑÐ°Ð»ÑÐ½ÑÐµ Ð·Ð°Ð³Ð¾Ð»Ð¾Ð²ÐºÐ¸ ÑÐ¾ÑÐ¾ÑÐ¾ Ð±Ñ ÑÐ°Ðº Ð¶Ðµ
    Ð´Ð¾ÑÐ°Ð±Ð¾ÑÐ°ÑÑ Ð¿Ð¾ Ð²Ð¾Ð·Ð¼Ð¾Ð¶Ð½Ð¾ÑÑÐ¸.
    The same is true for all other titles.

On 2007-09-29 11:09:16 +0000, Dimitri van Heesch wrote:

    Thanks but can you please attach an updated version of translator_ru.h in
    zip to this bug report. I doesn't work if I copy&paste the texts from the
    web browser.

On 2007-10-01 07:16:50 +0000, ÐÐµÑÑÐ¸Ð½ Ð®ÑÐ¸Ð¹ wrote:

    Actually you should make a little refactoring to solve this problem. No
    header update required (because of multi-context it is not possible to solve
    this by only header update).
    
    It is good to write in title: 'DoxyGen Documentation', 'DoxyGen Files' etc
    in English.
    But Russian language requires inverted order: 'ÐÐ¾ÐºÑÐ¼ÐµÐ½ÑÐ°ÑÐ¸Ñ
    DoxyGen', 'Ð¤Ð°Ð¹Ð»Ñ DoxyGen' etc.

**Comment by albert-github** [comment]
During the translation from Bugzilla to Github some information is lost so it is unclear what the original intentions was.
Also the request for an updated translator_ru.h has not been honored.
According to the doxygen manual the Russian translation is up to date with 1.8.15, so it might be that the problem mentioned in the issue has been solved as well.
