### ISSUE TITLE
cond/endcond cannot be used in aliases (Origin: bugzilla #485773)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2655]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.3* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-10-11 15:47:00 +0000, Ambroise Confetti wrote:

    Please describe the problem:
    In version 1.5.2, I used to have the following aliases:
    
    ALIASES = foodev="\cond FooDev" \
              endfoodev="\endcond"
    
    In version 1.5.3, on most uses of these aliases (not all!) I get "unknown
    command: \cond" or "unknown command: \endcond" errors.
    
    All errors disappear when I use \cond FooDev and \endcond directly.
    
    Steps to reproduce:
    
    
    Actual results:
    
    
    Expected results:
    
    
    Does this happen every time?
    
    
    Other information:

On 2009-07-30 13:28:32 +0000, jani.mikkonen@gmail.com wrote:

    Still happening on 1.5.9

On 2018-06-18 10:48:23 +0000, albert wrote:

    Due to the moment of parsing \cond and \endcond cannot be used in ALIASES,
    added note to the documentation.
    
    I've just pushed a proposed, documentation, patch to github (pull request
    769, https://github.com/doxygen/doxygen/pull/769).

**Comment by albert-github** [comment]
Pull request #769 integrated, issue can be labeled as `fixed but not released`.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
