### ISSUE TITLE
Configure the tool for sequence charts (Origin: bugzilla #486757)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2661]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.5.3* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-10-15 08:35:08 +0000, Thomas Spitzer wrote:

    In Version 1.5.3 doxygen uses the tool "mscgen" to generate message sequence
    charts.
    
    The tool "Trace2UML" (http://trace2uml.tigris.org/) is call compatible with
    "mscgen" and can be used for drawing sequence charts, too.
    
    At the moment it has to be renamed to "mcsgen" because the toolname is
    hardcoded inside doxygen.
    
    It would be nice, if you could select the drawing tool inside doxygen
    configuration.

**Comment by albert-github** [comment]
MSCGEN is now integrated into doxygen, see alternative implementation in pull request #6885
