### ISSUE TITLE
ambiguity when combining using directives and anonymous namespaces (Origin: bugzilla #486804)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2662]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.3-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-10-15 11:52:26 +0000, Christoph Schulz wrote:

    Given the following test case and EXTRACT_ANON_NSPACES = NO:
    
    /// @file test.cc
    
    /// N.
    namespace N {
    /// N::Module.
    class Module {};
    }
    using namespace N;
    
    /// unnamed.
    namespace {
    /// unnamed::Module.
    class Module {
    public :
    /// i.
    static int i;
    };
    int Module::i = 42;
    }
    
    doxygen 1.5.3 produces the warning:
    
    test.cc:18: Warning: no matching class member found for
      int Module::i()
    Possible candidates:
      static int @0::Module::i
    
    doxygen 1.5.3-20071008 produces the warning:
    
    test.cc:18: Warning: no matching class member found for
      int Module::i()
    Possible candidates:
      static int Module::i
    
    The following modifications let the warning go away:
    - set EXTRACT_ANON_NSPACES = YES in the configuration file
    - remove "using namespace N;" (line 8)
    - remove "class Module" (lines 5-6)
    - remove the whole namespace "N" (lines 3-8)
    
    I expect the EXTRACT_ANON_NSPACES setting to only affect the generation of
    the documentation and not to change the meaning of name lookup. So, in all
    cases doxygen should not emit any warnings.

**Comment by albert-github** [comment]
With the doxygen 1.5.3. version I see the warning. With the current doxygen 1.12.0 version the warning is gone.
I think the problem has been solved in the mean time
