### ISSUE TITLE
mscgen is not found when PATH contains paths with dot-dot (Origin: bugzilla #487144)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2663]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.3* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-10-16 13:30:12 +0000, Alexei Alexandrov wrote:

    I have mscgen.exe on the system and path to it added to PATH. It's added in
    a form where one of elements is "..", namely path is
    
    D:\program\\..\util\mscgen
    
    The problem I get is that mscgen.exe is not found in this case. The
    MSCGEN_PATH value is empty. From file system logs I can see that doxygen
    tries to locate mscgen as
    
    D:\program\util\mscgen\mscgen.exe
    
    instead of D:\util\mscgen\mscgen.exe
    
    I don't know if its double backslash or dot-dot that caused this behavior,
    but it's a bug anyway.

On 2007-10-16 13:34:22 +0000, Alexei Alexandrov wrote:

    OK, it's seems it's double backslash that causes it

**Comment by albert-github** [comment]
MSCGEN is now integrated into doxygen, see alternative implementation in pull request #6885

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
