### ISSUE TITLE
Wrong MSC syntax rejected *silently* (Origin: bugzilla #489766)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2684]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.3* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-10-24 11:58:04 +0000, Olivier Croquette wrote:

    Please describe the problem:
    By upgrading from version 1.5 to 1.5.3, the following syntax to make MSC
    diagrams stopped working.
    
    The major problem is that the user doesn't get any useful error message.
    
    Steps to reproduce:
    1. Create a MSC with the following syntax:
    
     *\msc
     * msc
     * {
    ...
     * }
     *\endmsc
    
    2. run Doxygen
    
    
    
    Actual results:
    Somewhere in the output, the following error messages appear:
    
    Error: Problems running epstopdf. Check your TeX installation!
    epstopdf: The input file does not exist.
    
    
    Expected results:
    I would expect to have a clear error message about the wrong syntax, and in
    which source file the problem occured.
    
    Does this happen every time?
    Yes
    
    Other information:

**Comment by albert-github** [comment]
The `\msc` command has been added in version 1.5.2 and in the documentation it is stated:

> The text fragment should only include the part of the message sequence chart that is within the msc
> {...} block.

So this syntax can never have worked.

The possibility about an error /warning message has to be investigated further.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7055

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
