### ISSUE TITLE
Parse Function Bodies in Doxygen (Origin: bugzilla #490547)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2688]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.5.3* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-10-26 15:11:53 +0000, Alex McCarthy wrote:

    It would be great if Doxygen could parse function bodies. This would allow
    me to use doxygen's perlmod output to write a tool that finds unnecessary
    includes in C++ files, which would be a great help for large projects.
    
    Thanks a bunch!

**Comment by albert-github** [comment]
It is unclear what is required here as no example is given.

I think the problem is incomplete.
