### ISSUE TITLE
dependency graph generation with Template inheritance of itself fails (Origin: bugzilla #493781)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2704]
status NEW severity *normal* in component *general* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-11-05 16:08:31 +0000, patrick wrote:

    dependency graph generation with the following input fails
    
    class A : public BaseOject<A>

**Comment by albert-github** [comment]
It is unclear what is missing as no example and  / or settings have been provided.
with the example:
```
/// \file

/// the the base
template <typename T>
class BaseOject
{
  public:
    /// the value
    T* value;
    /// the function
    T* method();
};

/// the inherited self class
class A : public BaseOject<A>
{
    // ...
};
```

and settings :
```
QUIET = YES
HAVE_DOT = YES
UML_LOOK               = YES
```
I see in the 1.5.3 and the current master (1.9.6 (6bc5f864d0c847a74944d6e9e4a42346e8c18b28)) all the expected graphs independent of the settings of `HAVE_DOT` / `UML_LOOK`.
(Note: also in the 1.9.5 version I see all the expected graphs though this version has a small deficit when `UML_GRAH` is set).

I think the problem description is incomplete.

Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/10075280/example.tar.gz)
