### ISSUE TITLE
Doxygen can't find template memeber docs if definition is not in same haeder as declaration (Origin: bugzilla #495221)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2716]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.4* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-11-09 08:21:00 +0000, Tomislav AdamiÄ wrote:

    Please describe the problem:
    If you create class template in header1.hpp but make member function
    definition in header2.hpp (which is included by header1.hpp) doxygen doesn't
    find documentation for members in header2.hpp with warning "Warning: no
    matching class member found for..." followed by fully classified name of
    member function.
    
    Steps to reproduce:
    Here are two simple headers that reproduce the bug. You can use code here
    with default Doxyfile generated by doxygen to reproduce bug.
    
    ---------------- classA.hpp----------------------------
    /** @file  */
    #ifndef CLASS_A_HEADER_INCLUDED
    #define CLASS_A_HEADER_INCLUDED
    
    /** namepace */
    namespace some_namespace {
    
    /** This is classA */
    template<class someT>
    class A {
    public: 
    	void some_member (const someT& t) const;
    };
    
    #include "classAimplementation.hpp"
    
    } // namespace some_namespace
    
    #endif // CLASS_A_HEADER_INCLUDED
    ------------ end of classA.hpp-------------
    
    ----------classAimplementation.hpp---------
    /** @file  */
    #ifndef CLASS_A_IMPLEMENTATION_HPP_INCLUDED
    #define CLASS_A_IMPLEMENTATION_HPP_INCLUDED
    
    /** This is some member  */
    template<class someT>
    void classA<someT>::
    some_member (const someT& t) const {
    }
    
    #endif //  CLASS_A_IMPLEMENTATION_HPP_INCLUDED
    -----enf of classAimplementation.hpp-------
    
    Actual results:
    
    
    Expected results:
    
    
    Does this happen every time?
    
    
    Other information:

**Comment by albert-github** [comment]
When I use with the doxygen version 1.5.4 the setup:
```
QUIET = YES
INPUT = classA.hpp
INCLUDE_PATH = .
```
I get the warning:
```
.../classA.hpp:23: Warning: no matching class member found for
  template < someT >
  void some_namespace::classA::some_member(const someT &t) const
```
with the current (1.9.8) doxygen version I don't get a warning and the output looks also OK to me.

Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/12621773/example.tar.gz)

I think the problem has been solved in the mean time.
