### ISSUE TITLE
Tagfile reference in inheritance graph seems to fail when contains a dash as part of name (Origin: bugzilla #500195)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2739]
status NEW severity *minor* in component *general* for *---*
Reported in version *1.5.3* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-11-28 13:40:33 +0000, Bjarne Roe wrote:

    When the tagfile name contains a dash (-) the dash seems to be converted
    into &# 45; when used for tagfile location into the HTML inheritance chart
    on the class reference page. The html node in question is <area
    doxygen="3party&# 45;lib&# 45;commoncpp.tagfile:"> located within the <div
    class="dynsection"> node.
    
    The tagfile is named 3party-lib-commoncpp.tagfile. Renaming the tagfile to
    3party_lib_commoncpp.tagfile solved the problem. This applies to both Linux
    and windows platforms with the same version.
    
    The bug causes installdox to not find all entries of the doxygen="tagfile:"
    thus not correcting the path of <area href="">
    
    
    Snippet from the inheritance chart (where the error has occured):
    ----8<--------8<--------8<--------8<--------8<--------8<----
    <div class="dynsection">
    <p><center><img src="class_g_s_m_handler__inherit__graph.png" border="0"
    usemap="#_g_s_m_handler__inherit__map" alt="Inheritance graph"></center>
    <map name="_g_s_m_handler__inherit__map">
    <area shape="rect" doxygen="3party&# 45;lib&# 45;commoncpp.tagfile:"
    href="classost_1_1_serial.html" title="ost::Serial" alt=""
    coords="5,5,80,32"><area shape="rect" doxygen="3party&# 45;lib&#
    45;commoncpp.tagfile:" href="classost_1_1_thread.html" title="ost::Thread"
    alt="" coords="104,5,187,32"></map>
    <center><font size="2">[<a
    href="graph_legend.html">legend</a>]</font></center></div>
    ----8<--------8<--------8<--------8<--------8<--------8<----
    
    
    Snippet from the member declaration (where it is correct):
    ----8<--------8<--------8<--------8<--------8<--------8<----
    <tr><td class="memItemLeft" nowrap align="right" valign="top"><a
    class="elRef" doxygen="3party-lib-
    commoncpp.tagfile:../../../3party/lib/commoncpp/"
    href="../../../3party/lib/commoncpp/classost_1_1_mutex.html">ost::Mutex</a>&nbsp;</td><td
    class="memItemRight" valign="bottom"><a class="el"
    href="class_g_s_m_handler.html#
    8bbcc9f844e372f686a1f19b02c29800">read_buffer_mutex</a></td></tr>
    ----8<--------8<--------8<--------8<--------8<--------8<----

**Comment by albert-github** [comment]
The script program is not part of doxygen anymore (since 1.8.0).

So issue is obsolete.
