### ISSUE TITLE
JAVADOC_AUTOBRIEF messes addtogroup (Origin: bugzilla #503318)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2756]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.4* on platform *Other*
Assigned to: Dimitri van Heesch

On 2007-12-12 20:54:18 +0000, Gilles wrote:

    Please describe the problem:
    +++ This bug is similar to  Bug # 318038 +++
    
    I already have a large number of groups, and having too many groups makes it
    difficult to choose in which group a class/function/typedef should be
    placed.
    
    I thus prefer to use \defgroup to define a group. And then close to the
    documented item use \addtogroup to write an other chunks of text close to
    the items.
    
    This works fine until one switch on JAVADOC_AUTOBRIEF. after that, all \par
    titles are slided to the top of the group.
    
    Example: with this file (as a fake for scattered text over several files)
    
    /**
     * \file addtogroup.cpp
     * \brief demonstrates conflict between addtogroup and AUTOBRIEF
     */
     
    /**
     * \defgroup group1 My Group1
     * 
     * Group1 is described here with some more text scattered close
     * to the implementation at other places
     *
     * \par A paragraph in group1 
     *
     * with text in paragraph
     *
     * \par Another  paragraph in group1 
     *
     * with text in another paragraph
     */
     
    //skipped
    
    /**
     * \addtogroup group1
     * \par More for group 1
     *
     * In this paragraph close to the implementation we have more text
     * for group 1.
     */
    
    //skipped
    
    /**
     * \addtogroup group1
     * \par Yet another extra paragraph for group 1
     *
     * In this paragraph close to the implementation we have further text
     * for group1..
     */
    
    //skipped
    
    /**
     * \addtogroup group1
     * \par Yet another paragraph for groupe 1
     *
     * In this paragraph close to the implementation we have further text
     * for group1..
     */
    EOF
    
    Then the commands:
    doxygen -s -g
    doxygen 
    
    produces this group1 text:
    
    My Group1
     
    Group1 is described here with some more text scattered close to the
    implementation at other places
    
    A paragraph in group1 
    with text in paragraph
    
    Another paragraph in group1 
    with text in another paragraph
    
    More for group 1
    In this paragraph close to the implementation we have more text for group 1.
    
    Yet another extra paragraph for group 1
    In this paragraph close to the implementation we have further text for
    groupe1..
    
    Yet another paragraph for group 1
    In this paragraph close to the implementation we have further text for
    groupe1..
    EOF
    
    
    That is what i expect.
    But if i set JAVADOC_AUTOBRIEF = YES, then i get:
    
    My Group1
    Group1 is described here with some more text scattered close to the
    implementation at other places. More...
    
    Yet another paragraph for group 1
    Yet another extra paragraph for group 1
    More for group 1
    A paragraph in group1 
    with text in paragraph
    
    Another paragraph in group1 
    with text in another paragraph
    In this paragraph close to the implementation we have more text for group 1.
    
    In this paragraph close to the implementation we have further text for
    groupe1..
    EOF
    
    That is surprising, and rather useless.
    We found out, that to prevent the reordering, one can rewrite
    
    /**
     * \addtogroup group1
     * \par Yet another extra paragraph for group 1
     *
    To
    /**
     * \addtogroup group1
     * \par
     * \par Yet another extra paragraph for group 1
     *
    
    My current workaround is to define a parametrized macro
    that expands
    /**
     * \myaddtogroup{group1}
     to 
    /**
     * \addtogroup group1
     * \par
    
    But this is a hack.
    Is there a chance to remove the surprising side effect of JAVADOC_AUTOBRIEF?
    Thanks
    Gilles
    
    Steps to reproduce:
    1. 
    2. 
    3. 
    
    
    Actual results:
    
    
    Expected results:
    
    
    Does this happen every time?
    
    
    Other information:
    files and doxyfile can be provided if needed

**Comment by albert-github** [comment]
Looking at the original problem with the doxygen 1.5.4 version we see:
![image](https://github.com/doxygen/doxygen/assets/5223533/535013dc-21da-4520-aa0f-67454e679ca1)


and when setting `JAVADOC_AUTOBRIEF = YES` we see:
![image](https://github.com/doxygen/doxygen/assets/5223533/93fc321e-3eba-4ef8-94ed-c4e2bac5e96c)


With the current doxygen version we see:
![image](https://github.com/doxygen/doxygen/assets/5223533/f6802cce-00ac-49a4-bd48-1f50daa924b2)

and when setting `JAVADOC_AUTOBRIEF = YES` we see:
![image](https://github.com/doxygen/doxygen/assets/5223533/e8599f30-1786-4d9e-a37c-d2c0aba47c6d)


This all looks OK in the 1.9.8 version.
The double line:
> Group1 is described here with some more text scattered close to the implementation at other places. 

is due to the fact that by default `REPEAT_BRIEF = YES` and as `JAVADOC_AUTOBRIEF = YES` the first line is interpreted as brief documentation.

I think the problem has been solved in the mean time.
