### ISSUE TITLE
multi-line '///' comment incorrectly parsed in presence of '*/' (Origin: bugzilla #506243)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2771]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.4* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[php_name_bad-end-comment.tar.gz](https://sourceforge.net/projects/doxygen/files/attachments/bug506243_229723_php_name_bad-end-comment.tar.gz/download/download)_ (ID 229723)

On 2007-12-29 13:06:51 +0000, Konstantin Serebryany wrote:

    Please describe the problem:
    If I have a two-line '///' comment which has '*/' in the second line, it is
    interpreted as comment terminator.
    
    % ls
    Doxyfile  b.h
    % head *
    ==> Doxyfile <==
    INPUT=b.h
    PROJECT_NAME=FOO
    GENERATE_HTML=YES
    GENERATE_LATEX=NO
    
    ==> b.h <==
      /// @file b.h
    
      /// Two-line comment,
      /// second line has misleading */ comment terminator.
      void AAAAA();
    % doxygen > /dev/null 2>&1
    % lynx -dump html/b_8h.html
    ...
    Functions
    
       comment terminator *void  [4]AAAAA ()
    ...
    Function Documentation
    
       comment terminator* void AAAAA (  )
    
       Two-line comment, second line has misleading
    
    Steps to reproduce:
    
    
    Actual results:
    
    
    Expected results:
    
    
    Does this happen every time?
    
    
    Other information:

On 2012-11-23 12:54:06 +0000, Michel D'HOOGE wrote:

    I have a similar problem... with version 1.8.1.2
    
    If the following line is present in a PHP file, the file is parsed but
    completely ignored. After removing the end-of-comment, doxygen works as
    expected.
    
      /// \name Test name */
    
    See attached sample.

On 2012-11-23 12:55:02 +0000, Michel D'HOOGE wrote:

    Created attachment 229723
    Mixing /// with */ makes doxygen ignore the file

**Comment by albert-github** [comment]
The problem here is that doxygen converts the multi-line `///` comments to `/** ... */` type comments and thus the original `*/` is seen as end comment.

With the both examples and the versions used here I see the problem her.
In the 1.9.1 version the problem is gone as doxygen recognizes the `*/` and replaces it wit `*&zwj/` (i.e. inserts a non printing character into it.
The problem is solved in this way in version 1.8.16.

I think the problem has been solved in the mean time.
