### ISSUE TITLE
Problem hiding some typedef structs using TYPEDEF_HIDES_STRUCT (Origin: bugzilla #511365)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2795]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.7.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2008-01-22 20:25:43 +0000, Liam O'Boyle wrote:

    The hiding of typedef structs, enabled with TYPEDEF_HIDES_STRUCT, does not
    hide structs if they are formatted in a certain way.  The following
    structure is not hidden correctly, the output is the same with
    TYPEDEF_HIDES_STRUCT enabled or disabled.
    
    typedef struct _BondObject BondObject;
     struct _BondObject
      {
      ...
      };

On 2008-12-27 14:22:55 +0000, Dimitri van Heesch wrote:

    This bug report had the version set to "latest". Since this is a moving
    target I changed it to 1.5.7.1. If you happen to see that the problem is
    fixed in 1.5.8, then please close it.

On 2009-05-15 21:30:36 +0000, Peter wrote:

    The ChangeLog for 1.5.8 includes this note:
    
    * TYPEDEF_HIDES_STRUCT did not work correctly if the typedef did a forward
    declaration of the struct/union
    
    I was doing some regression testing of typedef structs with the latest
    doxygen, so I added this to my test and compared the tags files from 1.5.5
    and 1.5.9.  The latest version of doxygen does appear to behave correctly
    now, hiding the "typedef" and only listing the "struct".

**Comment by albert-github** [comment]
With the doxygen version 1.5.7.1 we see independent of the setting of `TYPEDEF_HIDES_STRUCT `:
![image](https://github.com/doxygen/doxygen/assets/5223533/4c0189d4-76a4-4103-ad1d-cde12ae2d0f5)

As indicated by the comments it should be solved in the 1.5.8 version and here we see when `TYPEDEF_HIDES_STRUCT`  is not set:
![image](https://github.com/doxygen/doxygen/assets/5223533/69096646-4cae-40f6-8d63-bcc15f63dafe)

and when it is set:
![image](https://github.com/doxygen/doxygen/assets/5223533/ffc3e6de-bfd9-4531-97f0-867a5a3d34d2)


with the current, 1.9.8, doxygen version we see
![image](https://github.com/doxygen/doxygen/assets/5223533/ed7a153b-f6e4-473f-8ed3-5724205f08df)

and
![image](https://github.com/doxygen/doxygen/assets/5223533/dea5a08d-0a95-4fe6-9145-d93b96cb8ee7)


So I think indeed that the problem has been solved in the mean time.
