### ISSUE TITLE
Some preprocessor conditionals not handled correctly (Origin: bugzilla #514477)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2809]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.4* on platform *Other*
Assigned to: Dimitri van Heesch

On 2008-02-05 08:42:34 +0000, Bob Cousins wrote:

    In the following snippet:
    
    #define SOUP
    
    /*! this is referenced by main() */
    void serve_soup (void)
    {
    	printf ("Soup for you\n");
    }
    
    /*! this should not be referenced by main()? */
    void no_soup (void)
    {
    	printf ("No soup for you\n");
    }
    
    int main (int argc, char *argv[])
    {
    #ifdef SOUP
    	serve_soup();
    #else
    	no_soup();
    #endif
    }
    
    Both serve_soup and no_soup are listed as being referenced by main(). This
    is despite the preprocessor output:
    
    00001 #define SOUP
    00002
    00003 /*! this is referenced by main() */
    00004 void serve_soup (void)
    00005 {
    00006   printf ("Soup for you\n");
    00007 }
    00008
    00009 /*! this should not be referenced by main()? */
    00010 void no_soup (void)
    00011 {
    00012   printf ("No soup for you\n");
    00013 }
    00014
    00015 int main (int argc, char *argv[])
    00016 {
    00017
    00018   serve_soup();
    00019
    00020
    00021 }
    00022

On 2008-02-05 08:51:00 +0000, Bob Cousins wrote:

    This may be related to bug # 504025.

On 2008-04-29 10:18:41 +0000, Bob Cousins wrote:

    Also related, bug # 520118.
    
    I would also note that variables inside preprocessor conditionals work as
    expected, e.g.
    
    #define SOUP
    
    #ifdef SOUP
    int soup_result;	/*!< this is referenced in callgraph */
    #else
    int bad_soup;		/*!< this is not referenced in callgraph*/
    #endif
    
    HTH

**Comment by albert-github** [comment]
This is the same problem as with:  
> code that is disabled by preprocessor directives, has influence on generating call/caller graphs (Origin: bugzilla 520118) #2853

i.e. the preprocessor is not obayed in the code generation (which is used to generate call / caller graphs as well) , setting issue to duplicate.
