### ISSUE TITLE
Generic Classes in Java are not recognized correctly (Origin: bugzilla #516656)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2835]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.5* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[Example 1.7z](https://sourceforge.net/projects/doxygen/files/attachments/bug516656_105434_Example 1.7z/download/download)_ (ID 105434)

On 2008-02-15 11:43:46 +0000, Rico Beier wrote:

    Please describe the problem:
    Generic Classes in Java (like Set<Foo>) should Reference to Foo and Set in
    some case.
    I wrote an application containing Vector<Category> in my Session class.
    The UML-Diagram references to the superclass, to Vector, but not to
    Category.
    
    Steps to reproduce:
    1. write a generic class
    2. produce a doxygen-configuration
    3. look at the diagrams
    
    Actual results:
    The generic class will not be correcly recognized
    
    Expected results:
    
    
    Does this happen every time?
    Yes
    
    Other information:

On 2008-02-16 15:11:37 +0000, Dimitri van Heesch wrote:

    Can you please attach a self-contained example (source + config file in a
    zip) that allows me to reproduce the problem?

On 2008-02-17 13:49:29 +0000, Rico Beier wrote:

    Created attachment 105434
    7z compressed folder containing source, doc, config and readme
    
    Please read the ReadMe.txt inside the compressed file.
    thanks

On 2008-02-28 15:34:47 +0000, Rico Beier wrote:

    Could I help you with the attachment?

**Comment by albert-github** [comment]
When looking at the collaboration diagram of the 1.5.5 version we get:
![image](https://github.com/doxygen/doxygen/assets/5223533/a1314cf1-a83b-428a-bf0d-b5c3eacd36cc)


When looking at the collaboration diagram of the current 1.9.6 version we get:

![image](https://github.com/doxygen/doxygen/assets/5223533/41601a59-4d10-4471-874a-fe7a1d449dd3)

We see, as far as I can judge, all the required relatins.

I think the problem has been solved in the mean time.
