### ISSUE TITLE
The "globals" tab should be on the top level instead of hidden in the "files" tab. (Origin: bugzilla #517201)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2839]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2008-02-18 12:12:14 +0000, jeberger wrote:

    From a user point of view, there is no real reason why the "Globals" tab is
    a sub-tab of "Files". It should instead be on the top-level so that it is
    directly accessible (on a par with the "Classes" tab).
    
    This is even more true when OPTIMIZE_OUTPUT_FOR_C is set to yes: in that
    case, the "Globals" tab is almost certainly what the user will want to see.
    
    IMO, it should at least be an option

**Comment by jeberger** [comment]
Why does my email appear in clear in the bug description?

**Comment by albert-github** [comment]
Because it was clearly readable in the original bugzilla bug report as well.

**Comment by jeberger** [comment]
No it wasn't, only the `jeberger` part was visible, the part after the `@` sign wasn't (same as for my comments here).

**Comment by jeberger** [comment]
That's only for people who are logged in though, not for everyone. On github it has become visible to every web crawler out there.

**Comment by jeberger** [comment]
So can you please edit the bug description (and that of #6352) to remove my email address from both.

**Comment by jeberger** [comment]
Thanks

**Comment by albert-github** [comment]
With the 1.9.5 and defining a local layout file (see `doxygen -l`) and moving here the item:
```
      <tab type="globals" visible="yes" title="" intro=""/>
```
out of the
```
      <tab type="files" visible="yes" title="">
```
part we can define it as main category and this is, as far as I can see, the required functionality.
With the 1.5.5. version this didn't work.

I think the problem has been solved in the mean time.

Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/10303454/example.tar.gz)

(I assume that `OPTIMIZE_OUTPUT_FOR_C=YES` has been set).
