### ISSUE TITLE
Unnamed parameters parsed incorrectly (Origin: bugzilla #520975)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2859]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.5* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[t.cc](https://sourceforge.net/projects/doxygen/files/attachments/bug520975_106773_t.cc/download/download)_ (ID 106773)
- _[Doxyfile](https://sourceforge.net/projects/doxygen/files/attachments/bug520975_106774_Doxyfile/download/download)_ (ID 106774)

On 2008-03-07 12:36:49 +0000, Paul Melis wrote:

    Please describe the problem:
    Giving a valid class declaration like
    
    class C
    {
    public:
        float   f(unsigned int);
    };
    
    float
    C::f(unsigned int)
    {
        return 10.0f;
    }
    
    the XML output generated by doxygen contains the following section for f():
    
          <memberdef kind="function"
    id="classC_10c0d7af11816e28bca64dee3f85ce8b5" prot="public" static="no"
    const="no" explicit="no" inline="no" virt="non-virtual">
            <type>float</type>
            <definition>float C::f</definition>
            <argsstring>(unsigned int)</argsstring>
            <name>f</name>
            <param>
              <type>unsigned</type>
              <declname>int</declname>
            </param>
    
    The parameter type is parsed incorrectly, as the "int" part is seen as the
    parameter name.
    
    
    Steps to reproduce:
    1. Run doxygen on attached files
    2. 
    3. 
    
    
    Actual results:
    
    
    Expected results:
    
    
    Does this happen every time?
    
    
    Other information:

On 2008-03-07 12:37:37 +0000, Paul Melis wrote:

    Created attachment 106773
    C++ testcase

On 2008-03-07 12:37:50 +0000, Paul Melis wrote:

    Created attachment 106774
    Doxyfile

On 2008-03-09 11:03:22 +0000, Dimitri van Heesch wrote:

    Hi Paul,
    
    I do not know how I can fix this (at least in general).
    
    Doxygen does not know "unsigned" and "int" are keywords, and even if it
    would, someone could come up with the following (unlikely but valid)
    example:
    
    ---------------------------
    #ifdef USE_NAME
    #define TYPE_OR_NAME name
    #else 
    #define TYPE_OR_NAME int
    #endif
    
    float f(unsigned TYPE_OR_NAME);
    ---------------------------
    
    where the USE_NAME could be defined in e.g. a Makefile
    
    A workaround would of course be to use a typedef or macro
    
    ---------------------------
    typedef unsigned int uint;
    float f(uint);
    ---------------------------
    
    If you have a suggestion for how this should be fixed, let me know.

On 2008-03-10 08:45:08 +0000, Paul Melis wrote:

    Well, for your first counter-example using the #define I don't see a way to
    solve this without preprocessing.
    
    But I think that a parameter name is not allowed to be the name of a keyword
    in C++, so if doxygen parses a parameter name as being "int"/"long"/"char"
    perhaps you can catch it right then and there. I can't think of many types
    where this problem might occur, only for signed int/char/long and unsigned
    int/char/long.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6396.

**Comment by albert-github** [comment]
Code has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Comment by Enyby** [comment]
Weird solution. What if U use language where this words not a keywords?
https://github.com/doxygen/doxygen/blob/0fc0de19ba79068ff7b6bad1e161393adcd865b8/src/defargs.l#L109
I got error
`warning: argument 'double' of command @param is not found in the argument list of gg::unrandomizer(long qword=nil, long qincr=nil, double double=nil, double dincr=nil)`
It must be option in config file for disable this.
Or better, in config must be option where you can specify list of words which are is keywords for typename.

Also in your list even `uint64_t` not exists. You plan update this list forever or maybe allow users do it via config?

**Comment by doxygen** [comment]
@enyby: double as a parameter is not allowed by the language. [Here](https://gameguardian.net/help/classgg.html#a731e37ee1e891c708dc58d61e7005dab) `double_` is used, which should work fine. I'll add the missing types. Note that this indeed only works for standard types, not for user defined types, but there this is not really a problem, i.e. you cannot have `MyLong MyInt` to denote a single type and be confused with `MyLong MyParamName` like you can with `long int` and `long param_name` (unless you typedef keywords of course which is rather pointless).

**Comment by Enyby** [comment]
@doxygen 
> double as a parameter is not allowed by the language.
In C. In other languages it can be allowed. Lua for example.
>  Here double_ is used, which should work fine.
Of course I change it, because I not want wait while you fix it.
And because I can not use latest Doxygen even if you fix it fast.
Doxygen 1.8.16+ break something and not show brief descriptions for class and member declaration.
I suppose it is not parse brief description and think it is empty.
I use doxygen 1.8.13 and 1.8.15 and it is work fine. But in 1.8.16+ - no.
I use `JAVADOC_AUTOBRIEF      = YES`. Config is same.
I do not start new issue because it really horrible make short example for essence. And eat lot of time. So I decide stay on Doxygen 1.8.15.
