### ISSUE TITLE
cpp directives in \code fragments breaks subsequent links replacement (Origin: bugzilla #526008)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2916]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.5* on platform *Other*
Assigned to: Dimitri van Heesch

On 2008-04-03 16:54:39 +0000, HervÃ© Lemarchand wrote:

    It is known that names in code fragments may be not replaced by links.
    But when a cpp directive is present in a \code fragment, automatic link
    replacement feature is disabled for the rest of the \code fragment.
    
    //////////////////////////begin/////////////////////////////
    /** @file */
    
    /** @brief A brief description for DEF */
    #define DEF 0x01
    
    /** @brief A brief description for var
        @code
        any_t var = DEF;
        #define ANY
        any_t var = DEF;
        @endcode
    */
    any_t var = DEF;
    ///////////////////////////end//////////////////////////////
    
    Here is a part of the generated html output file:
    
    <span class="preprocessor">    #define ANY</span>
    <span class="preprocessor">    any_t var = DEF;</span>

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #8870

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.3.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
