### ISSUE TITLE
Incorrect HTML output for source files (Origin: bugzilla #526893)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2920]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.7.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2008-04-08 08:53:25 +0000, Bas Ploeger wrote:

    The HTML output of Doxygen 1.5.5 for source files does not yet adhere to the
    new structure introduced in 1.5.5, which is, by the way, very nice. The
    output is currently of the following form:
    
    <div class="navigation" id="top">
      <div class="tabs"> [here are the tabs] </div>
    </div>
    </div>
    <h1>FILENAME</h1>
    <a href="HTMLFILE">Go to the documentation of this file.</a>
    <div class="fragment">
      <pre class="fragment">
      [here's the formatted source code]
      </pre>
    </div>
    </div>
    
    In short, there are too many </div>'s and the page contents are not
    contained in a block of class "contents".
    
    The problem can be easily resolved by replacing the redundant </div> below
    the "navigation" block by the following:
    <div class="contents">
    
    This <div> would then match the </div> at the end of the HTML code above.
    Also, it would allow for the page contents to be styled using CSS
    definitions for class "contents", like the other HTML code that Doxygen
    generates.

On 2008-05-02 13:13:20 +0000, eric wrote:

    I would like to confirm this bug and to report a variation of it.
    
    My project specifies html headers and footers (HTML_HEADER/HTML_FOOTER).  In
    this case the doxygen-generated content simply contains one <div> and two
    </div>s.  Here is a snippet of the output:
    
    
    
    <h1>all.hpp</h1><a href="all_8hpp.html">Go to the documentation of this
    file.</a><div class="fragment"><pre class="fragment">
    [here's the formatted source code]
    </pre></div></div>
    
    
    I am using doxygen on Windows.

On 2008-05-26 13:59:31 +0000, Bas Ploeger wrote:

    This bug seems to have been fixed in Doxygen 1.5.6, although this is not
    mentioned in the Changelog on the Doxygen website. If so, status can be
    changed to FIXED.

On 2008-12-12 15:23:06 +0000, Bas Ploeger wrote:

    Nope, it seems this bug has NOT yet been fixed. It can be triggered by
    setting SHOW_DIRECTORIES to NO in Doxygen version 1.5.7.1.
    
    More precisely, when SHOW_DIRECTORIES is set to YES, I get output of the
    following form, which is correct:
    
    <div class="navigation" id="top">
      <div class="tabs">
        [TABS]
      </div>
      <div class="navpath">[PATH TO FILE]
      </div>
    </div>
    <div class="contents">
    <h1>[FILENAME]</h1>
    <a href="[HTMLFILE]">Go to the documentation of this file.</a>
    <div class="fragment">
      <pre class="fragment">
      [SOURCE CODE]
      </pre>
    </div>
    </div>
    
    However, when I set SHOW_DIRECTORIES to NO, I get the following, incorrect
    output:
    
    <div class="navigation" id="top">
      <div class="tabs">
        [TABS]
      </div>
    <h1>[FILENAME]</h1>
    <a href="[HTMLFILE]">Go to the documentation of this file.</a>
    <div class="fragment">
      <pre class="fragment">
      [SOURCE CODE]
      </pre>
    </div>
    </div>
    
    In this output the following two lines should be inserted above the level 1
    heading:
    </div>
    <div class="contents">

**Comment by albert-github** [comment]
The layout has ben changed considerably since the mentioned issues. Furthermore quite a b it has been changed in respect to the consistency of the HTML tags.
Unfortunately no input example is present.

I think the problem has been solved in the mean time.
