### ISSUE TITLE
Caller and Call Graph Functions are incorrectly recursive (Origin: bugzilla #527049)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2923]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.5* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[cyclic-bug-sample.tar.bz2](https://sourceforge.net/projects/doxygen/files/attachments/bug527049_108899_cyclic-bug-sample.tar.bz2/download/download)_ (ID 108899)
- _[doxygen187_recursive_function.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug527049_278449_doxygen187_recursive_function.zip/download/download)_ (ID 278449)

On 2008-04-09 01:17:07 +0000, Josh wrote:

    Please describe the problem:
    The DOT "call" and "caller" graphs that are generated show functions
    incorrectly calling themselves. The attached tar file shows a simple
    example. The problem seems to be correctable by turning on EXTRACT_ALL or by
    adding the /**@file*/ tag to the provided 'src/source.c' file.
    However, this example project was reduced from a larger project, in which
    only turning on EXTRACT_ALL fixes the problem.
    
    Steps to reproduce:
    1. extract the tar file
    2. view doc/html/d2/ddc/test_8h.html
    3. turn on EXTRACT_ALL or add the /**@file*/ header to the file
    'src/source.c'
    4. run doxygen, view doc/html/d2/ddc/test_8h.html, problem corrected
    
    
    Actual results:
    
    
    Expected results:
    
    
    Does this happen every time?
    
    
    Other information:

On 2008-04-09 01:18:13 +0000, Josh wrote:

    Created attachment 108899
    sample project with source files and pregenerated output

On 2014-06-14 16:56:04 +0000, Cornelius wrote:

    The bug is still open in DoxyGen Version 1.8.7
    Here is on additional example:
    -------------------
    void tic() 
    {
        tac();
    }
    void tac() 
    {
        toc();
    }
    void toc() 
    {
        tic();
    }
    
    int fact(int n)
    {    
        int x=1;    
    
        while(n>1)    
        {    
            x=n*fact(n-1);    
        }    
    
        return(x);    
    }    
    
    void main() 
    {
     	fact(5);
    	tic();
    
    }

On 2014-06-14 16:57:04 +0000, Cornelius wrote:

    Created attachment 278449
    Call graph does not show recursive functions.

**Comment by albert-github** [comment]
With doxygen version 1.8.4 I see the problem, with the current 1.9.1 version the problem is gone (as well as with the current master 1.9.2 (ce032dd509862a2af10c389c0609a5736540ef61)

I think the problem has been solved in the mean time
