### ISSUE TITLE
Hang on templated class typedefs (Origin: bugzilla #531637)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2946]
status NEW severity *critical* in component *general* for *---*
Reported in version *1.5.5-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxybug.tar.gz](https://sourceforge.net/projects/doxygen/files/attachments/bug531637_110507_doxybug.tar.gz/download/download)_ (ID 110507)
- _[itempayloadinternals_p.h](https://sourceforge.net/projects/doxygen/files/attachments/bug531637_169668_itempayloadinternals_p.h/download/download)_ (ID 169668)

On 2008-05-05 23:52:42 +0000, Andrew White wrote:

    Steps to reproduce:
    Source Code...
    /**************************************/
    #include <iterator>
    
    template <class T>
    class ListItem {};
    
    template <class BASE, class T>
    class DervivedList : public BASE {
    
        template <class BB, class TT>
        class bidirectional_iterator : public std::iterator<
    std::bidirectional_iterator_tag, ListItem<TT> >
        {};
    
        typedef bidirectional_iterator<BASE,T> iterator;
    };
    
    int main()
    {
        return 0;
    }
    /**********************************************/
    At the command line...
    $doxygen 
    
    
    Stack trace:
    
    
    Other information:
    Hangs at "Computing class inheritance relations..."

On 2008-05-06 01:04:37 +0000, Andrew White wrote:

    I just noticed something. This appears to be a recursive name lookup issue.
    When I changed the typedef from iterator to foobar all was well. So
    shouldn't doxygen take the namespace into account in this case?
    
    #include <iterator>
    
    template <class T>
    class ListItem {};
    
    template <class BASE, class T>
    class DervivedList : public BASE {
    
        template <class BB, class TT>
        class bidirectional_iterator : public std::iterator<
    std::bidirectional_iterator_tag, ListItem<TT> >
        {};
        
        // change this from iterator to foobar and all is well!!
        typedef bidirectional_iterator<BASE,T> foobar;
    };
    
    int main()
    {
        return 0;
    }

On 2008-05-06 14:39:33 +0000, Andrew White wrote:

    Sorry about this, but once last clarification. The core issue occurs when
    the derived class matches the typedef. In this case iterator is the typedef
    and iterator is the base class for the nested class...
    
    /// This hangs...
        template <class BB, class TT>
        class bidirectional_iterator : public iterator<...>
        {};
    
        typedef bidirectional_iterator<BASE,T> iterator;
    
    /// This works...
        template <class BB, class TT>
        class bidirectional_iterator : public std::iterator<...>
        {};
    
        typedef bidirectional_iterator<BASE,T> iterator;
    
    So my first comment on the bug was incorrect, but I believe this
    clarification should narrow down the issue.

On 2008-05-06 20:58:53 +0000, Dimitri van Heesch wrote:

    To avoid any confusion it is best to attach a self-contained example (source
    + config file in a zip) to this bug report so that I can more easily
    reproduce the problem.
    
    Can you still do this?

On 2008-05-07 03:07:42 +0000, Andrew White wrote:

    Created attachment 110507
    Source+config

On 2008-05-07 03:09:39 +0000, Andrew White wrote:

    Comment on attachment 110507
    Source+config
    
    The attached code and config will demo the problem completely. This should
    resolve all confusions

On 2010-08-12 20:18:49 +0000, Allen Winter wrote:

    I'd like to add this doxygen 1.7.1 is also hanging on code similar to what
    Andrew posted.
    
    The code is part of KDE and is extensive.  But I can point you to it if you
    want to take a look.

On 2010-09-06 19:26:24 +0000, Dimitri van Heesch wrote:

    Seems the issue in the attached example has been fixed since version 1.6.2,
    so if you have another example that still hangs doxygen I'm very interested.

On 2010-09-07 14:18:44 +0000, Allen Winter wrote:

    Created attachment 169668
    Akonadi source file that hangs Doxygen

On 2010-09-07 14:19:34 +0000, Allen Winter wrote:

    Hi Dimitri.
    
    I'm using doxygen 1.7.1.
    
    The code in question is the Akonadi library that is part of the KDE project
    and is much too large to attach to this bug report.  It is available at
    http://websvn.kde.org/trunk/KDE/kdepimlibs/akonadi
    
    or from svn using
    svn co svn://anonsvn.kde.org/home/kde/trunk/KDE/kdepimlibs/akonadi
    
    The specific file showing the hang is itempayloadinternals_p.h (attached).
    It has many templates.
    
    You'll notice that I put a big @cond PRIVATE block around the code in that
    file to get around the hang problem, so to test it you'll want to remove
    that Doxygen conditional.

On 2010-10-25 16:45:41 +0000, Tobias Mueller wrote:

    Reopening as an example has been provided.

**Comment by albert-github** [comment]
Looks like the problem is solved by means of commit d2b8ae16cb99621827f5dd860222c27e629f5a7f  it is not hanging / crashing anymore.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.17.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
