### ISSUE TITLE
Python: Backslash prevent showing the proper preview (Origin: bugzilla #531817)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2949]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.5* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[Doxyfile](https://sourceforge.net/projects/doxygen/files/attachments/bug531817_110475_Doxyfile/download/download)_ (ID 110475)
- _[test.py](https://sourceforge.net/projects/doxygen/files/attachments/bug531817_110476_test.py/download/download)_ (ID 110476)
- _[test.py](https://sourceforge.net/projects/doxygen/files/attachments/bug531817_110478_test.py/download/download)_ (ID 110478)
- _[test.py](https://sourceforge.net/projects/doxygen/files/attachments/bug531817_110562_test.py/download/download)_ (ID 110562)

On 2008-05-06 19:29:47 +0000, Carsten Grohmann wrote:

    Backslashes are used sometimes to put the content of a assignment to a new
    line. But doxygen doesn't show content currently. The backslash is shown
    instead.
    
    Current:
    test::test_1 = \
    
    Expected:
    test::test_1 = "Test 1"
    
    A example test file as well as a proper configuration will be attached.
    
    Regards,
    Carsten

On 2008-05-06 19:31:06 +0000, Carsten Grohmann wrote:

    Created attachment 110475
    Test Doxyfile

On 2008-05-06 19:31:35 +0000, Carsten Grohmann wrote:

    Created attachment 110476
    Some test cases

On 2008-05-06 19:40:41 +0000, Carsten Grohmann wrote:

    Created attachment 110478
    Some test cases

On 2008-05-08 08:06:55 +0000, Carsten Grohmann wrote:

    Created attachment 110562
    Python source code to reproduce the behaviour

On 2008-05-08 08:07:51 +0000, Carsten Grohmann wrote:

    Sorry, but the source file had some spelling mistakes.

On 2008-11-12 17:03:08 +0000, prz@net4u.ch wrote:

    import has same issue
    
    from django_framework.common_services.ThreadWrapper import
    ReconfigurableThreadWrapper
    
    on same line sees ReconfigurableThreadWrapper but 
    
    from django_framework.common_services.ThreadWrapper import \
               ReconfigurableThreadWrapper
    
    does not

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #9433

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.5.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
