### ISSUE TITLE
Verbage of generated documentation for Obj-C (Origin: bugzilla #532966)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2955]
status NEW severity *minor* in component *general* for *---*
Reported in version *1.5.5-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2008-05-13 14:54:20 +0000, Timothy Reaves wrote:

    When I generate my documentation, my class methods are under "Static Public
    Member Functions".  This should be "Class Public Member Functions".  There
    may be other places in the generation process where this would need to be
    corrected too.

**Comment by albert-github** [comment]
I tried to reproduce the problem with the 1.5.5. and 1.5.6 versions of doxygen, but didn't succeed.

As there is no case showing the problem I think the problem can be closed as incomplete.
