### ISSUE TITLE
C# consts incorrectly placed under instance variables (Origin: bugzilla #535853)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2976]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.2-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2008-05-30 22:48:42 +0000, Joshua Valentine wrote:

    Please describe the problem:
    C# consts are implicitly static.  The compiler complains if they are
    explicitly tagged with static.  However, Doxygen incorrectly places consts
    in the instance subgroup.  Ideally, consts should be listed by themselves as
    they are not actually variables.
    
    Steps to reproduce:
    1. doxyfile: SUBGROUPING = YES
    2. C# source:
    /// <summary>
    /// Incorrectly groups const c1 with instance rather than static vars.
    /// </summary>
    public class HasConsts
    {
    	/// <summary>const (implicitly static) var</summary>
    	public const int c1 = 0;
    	/// <summary>static var</summary>
    	public static int s1;
    	/// <summary>instance var</summary>
    	public int i1;
    }
    
    Actual results:
    The const variable is listed with instance variables.
    
    Expected results:
    The const variable is listed with static variables.
    
    Does this happen every time?
    Yes
    
    Other information:
    This may be due to the fact that Doxygen does not have a C# output option,
    but uses Java instead.

On 2012-11-18 11:07:55 +0000, Dimitri van Heesch wrote:

    Changed version 'latest' to '1.8.2-SVN' so I can remove 'latest' as an
    option as it is a moving target.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7048

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
