### ISSUE TITLE
HTML_DYNAMIC_SECTIONS results in incorrect links (Origin: bugzilla #536236)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2978]
status NEW severity *normal* in component *documentation* for *---*
Reported in version *1.5.5* on platform *Other*
Assigned to: Dimitri van Heesch

On 2008-06-02 13:31:07 +0000, B McMillan wrote:

    When large diagrams are hidden using HTML_DYNAMIC_SECTIONS, Iâve noticed
    that the links donât scroll to the correct locations.  Its like the
    browser still thinks the diagram is being shown; and you always have to
    scroll up to find the method or attribute youâre looking for.
     
    Can be seen on:
    Firefox: 2.0.0, IE: 5.5, Opera: 8.5

On 2008-06-22 11:43:48 +0000, Dimitri van Heesch wrote:

    I have seen this problem as well, but have no idea how I can fix it.
    
    The problem is that, by default, the dynamic sections are visible, and a
    script will be triggered on the page load to hide the sections (needed to
    deal with the case where javascript is disabled). During this time the
    browser jumps to the anchor, and sometimes jumps to the anchor at the
    position before the section was hidden. Pressing return in the URL bar of
    the browser will make it jump to the right spot again.
    
    I would say this is a browser issue (race condition), and it is shared by
    all browsers apparently.

**Comment by albert-github** [comment]
I did some tests with the current FireFox (109.0.1) and the results from the internal documentation generation (see e.g. http://doxygen.github.io/doxygen/d0/d47/commentcnv_8l.html) and did see all expected jumps.

I think this problem as been solved in the mean time (either in doxygen or by the browser).
