### ISSUE TITLE
Python docstrings: indentation issue (Origin: bugzilla #537416)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2988]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.6* on platform *Other*
Assigned to: Dimitri van Heesch

On 2008-06-09 15:01:46 +0000, Stephane Drouard wrote:

    With the example code:
    
    ##
    # Test class description.
    #
    class Test(object):
    
        ##
        # Foo description.
        #
        # @param self           Instance.
        #
        def foo(self):
            """Foo docstring."""
            pass
    
        ##
        # Foo description.
        #
        # @param self           Instance.
        #                        - blah.
        #
        def foo2(self):
            """Foo docstring."""
            pass
    
        ##
        # Foo description.
        #
        # - blah.
        #
        def foo3(self):
            """Foo docstring."""
            pass
    
    The generated documentation shows "Foo docstring." at the same indentation
    level as the last documented item.
    
    Cheers,
    Stephane

On 2016-01-30 14:23:28 +0000, albert wrote:

    Behavior is present in 1.8.11.
    
    When looking at an equivalent C example (and this will probably also be the
    case for other languages), we see analogous behavior when multiple
    documentation blocks are involved.
    
    Question here is the intentional behavior, in that case the bug report can
    be set to not a bug.

On 2016-08-24 16:21:04 +0000, albert wrote:

    I did some re-evaluation and saw in the documentation (paragraph: Comment
    blocks in Python):
    For Python there is a standard way of documenting the code using so called
    documentation strings. Such strings are stored in doc and can be retrieved
    at runtime. Doxygen will extract such comments and assume they have to be
    represented in a preformatted way.
    
    Seen this I think the behavior is intended and report can be closed as not a
    bug.

**Comment by albert-github** [comment]
It looks like the problem is not present anymore in the current doxygen version (1.9.4) as here the python doc-strings are indented like belonging to the method and not to the parameter as ir was done in the 1.5.6 version

I think the problem has been solved in the mean time.
