### ISSUE TITLE
C Preprocessor enum printing trick not handled properly by Doxygen... (Origin: bugzilla #539818)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3000]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[Doxygen_Test.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug539818_113294_Doxygen_Test.zip/download/download)_ (ID 113294)

On 2008-06-23 20:24:05 +0000, Greg Bednarek wrote:

    This C preprocessor trick seems to be attributed to a Stefan Ram. 
    
    It allows for the string representation of enums to be easily printed.
    
    Consider the following code:
    
    #include <stdio.h>
    
    #ifdef ENUMIFY
    #undef ENUMIFY
    #endif
    
    #define NAMES ENUMIFY(RED) \
                  ENUMIFY(GREEN) \
                  ENUMIFY(BLUE)
    
    #define ENUMIFY(x) x,
    
    /*!
     * This is an enumeration created with a preprocessor trick!
     */
    enum color { NAMES COUNT };
    
    #undef ENUMIFY
    
    #define ENUMIFY(x) #x,
    
    const char * const color_name[] = { NAMES };
    
    int main( void ) 
       { 
       printf( "The color is %s.\n", color_name[ RED ]);  
       printf( "There are %d colors.\n", COUNT ); 
       }
    
    The expected output to stdout would be:
    
        The color is RED. 
        There are 3 colors.
    
    
    When attempting to document the color enum above using Doxygen, the only
    entry that appears in the resulting documentation is the COUNT entry; the
    entries which should be contained in the NAMES entry do not appear.

On 2008-06-23 20:58:34 +0000, Greg Bednarek wrote:

    Created attachment 113294
    Testcase for C enum printing preprocessor trick that Doxygen is not
    recognizing properly...
    
    Attached is a ZIP file containing a simple C program (test.c) demonstrating
    the C enum printing preprocessor trick (originally attributed to Stefan
    Ram), as well as a Doxygen config file.
    
    The Doxygen output generated using this config file on the file test.c does
    not properly document the code due to problems interpreting the C
    preprocessor tricks used in the file.

On 2008-07-08 18:03:48 +0000, Greg Bednarek wrote:

    
    Oops...it seems that everything looks OK.
    
    It turns out that I had the MACRO_EXPANSION flag in the Doxygen
    configuration file set to NO.
    
    When I set it to YES, everything seems to work OK.
    
    In any case, the behavior I see when MACRO_EXPANSION is set to NO is at a
    minimum confusing, and likely is still a bug.

**Comment by albert-github** [comment]
The problem regarding showing the values might have been solved by means of `MACRO_EXPANSION` though there were some links that should not be present (i.e. links to `GREEN` and `BLUE` in the strings.
I've just pushed a proposed patch, pull request #9435

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.5.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
