### ISSUE TITLE
BUILTIN_STL_SUPPORT and inconsistent method declaration/implementation (Origin: bugzilla #540321)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3004]
status REOPENED severity *minor* in component *general* for *---*
Reported in version *1.5.8* on platform *Other*
Assigned to: Dimitri van Heesch

On 2008-06-26 13:48:46 +0000, mathias_lorente@yahoo.fr wrote:

    Please describe the problem:
    If you declare following class:
      #include <string>
      #include <vector>
    
      using std::string;
      using std::vector;
    
      class foo {
        void bar(string param);
        void bar(vector<int> param);
      };
    
    And you implement it in different way (prepending std::)
      #include "foo.h"
      void foo::bar(string param) { /* string */ }
      void foo::bar(std::vector<int> param) { /* vector of integers */ }
    
    When you build the documentation with BUILTIN_STL_SUPPORT=YES, you get
    following warning:
      ../foo.cpp:4: Warning: no matching class member found for
        void foo::bar(string param)
      Possible candidates:
        void foo::bar(string param)
        void foo::bar(vector< int > param)
    
    
    Steps to reproduce:
    1. Copy and paste above code in two different files in the same directory.
    2. Generate a default doxyfile using doxygen and set BUILTIN_STL_SUPPORT,
    EXTRACT_ALL and SOURCE_BROWSER to YES in the generated file.
    3. Build the documentation ($ doxygen Doxyfile).
    
    
    Actual results:
    You get the warning mentioned above and the documentation is not built
    correctly.
    
    Expected results:
    No warning should be raised and the documentation should be built correctly.
    
    Does this happen every time?
    Yes
    
    Other information:

On 2008-12-23 18:57:39 +0000, Dimitri van Heesch wrote:

    Problem was that the "using std::string;" in the header file was not picked
    up in the source file. Should be fixed in the next subversion update.

On 2008-12-27 14:12:47 +0000, Dimitri van Heesch wrote:

    This bug was previously marked ASSIGNED, which means it should be fixed in
    doxygen version 1.5.8. Please verify if this is indeed the case and reopen
    the
    bug if you think it is not fixed (include any additional information that
    you
    think can be relevant).
    

On 2009-01-13 15:31:36 +0000, mathias_lorente@yahoo.fr wrote:

    The problem is solved for the specific test case above but if you consider
    following code:
    - declaration
    
      #include <string>
      #include <vector>
    
      using std::vector;
    
      class foo {
        void bar(std::string param);
        void bar(vector<int> param);
      };
    
    - implementation
      #include "foo.h"
      void foo::bar(string param) { /* string */ }
      void foo::bar(std::vector<int> param) { /* vector of integers */ }
    
    You get the following error message:
    .../foo.cpp:2: Warning: no matching class member found for void
    foo::bar(string param)
    Possible candidates:
      void foo::bar(std::string param)
      void foo::bar(vector< int > param)

**Comment by albert-github** [comment]
As noted the first problem was already solved.

When trying to compile the second problem with gcc we get the error:
```
foo.cpp:2:6: error: variable or field 'bar' declared void
    2 | void foo::bar(string param) { /* string */ }
      |      ^~~
foo.cpp:2:15: error: 'string' was not declared in this scope; did you mean 'std::string'?
    2 | void foo::bar(string param) { /* string */ }
      |               ^~~~~~
      |               std::string
In file included from /usr/lib/gcc/x86_64-pc-cygwin/11/include/c++/string:39,
                 from foo.h:1,
                 from foo.cpp:1:
/usr/lib/gcc/x86_64-pc-cygwin/11/include/c++/bits/stringfwd.h:79:33: note: 'std::string' declared here
   79 |   typedef basic_string<char>    string;
      |                                 ^~~~~~
```
and similar with the Microsoft C++ compiler:
```
Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\xlocale(319): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
foo.cpp(2): error C2065: 'string': undeclared identifier
foo.cpp(2): error C2146: syntax error: missing ')' before identifier 'param'
foo.cpp(2): error C2143: syntax error: missing ';' before '{'
foo.cpp(2): error C2447: '{': missing function header (old-style formal list?)
```

adding:
```
using std::string;
```
solves the compilation issue.

So the code is not correct code and thus it is rightful that doxygen gives a warning.
So I think this part us usage.
