### ISSUE TITLE
doxygen doesn't treat INCLUDE_PATH recursively (Origin: bugzilla #542132)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3018]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.5.6* on platform *Other*
Assigned to: Dimitri van Heesch

On 2008-07-09 02:48:20 +0000, Joshua Cranmer wrote:

    If I specify INCLUDE_PATH=include, it doesn't search include/sub1/ and
    include/sub2/ recursively for files to preprocess.
    
    I'd be fine with having to specify another attribute to turn on recursive
    inclusion.

**Comment by albert-github** [comment]
When we would have the cpp program in the src directory:
```
#include <stdio.h>
#include "aa.h"

int main(int argc, char **argv)
{
  printf("txt = %s\n",txt);
}
```
and compile it with:
```
gcc -I include src/aa.cpp
```
we would get:
```
src/aa.cpp:2:10: fatal error: aa.h: No such file or directory
    2 | #include "aa.h"
      |          ^~~~~~
compilation terminated.
```
when the `aa.h` is in the directory `include/sub1`.
Analogous when having the `Doxyfile`:
```
QUIET = YES
INCLUDE_PATH = include
INPUT = src
RECURSIVE = YES
```
and running `doxygen -d preprocessor` we would get:
```
#include stdio.h: not found! skipping...
#include aa.h: not found! skipping...
Preprocessor output of D:/speeltuin/bug_542132/src/aa.cpp (size: 67 bytes):
---------
00001
00002
00003
00004 int main(int argc, char **argv)
00005 {
00006   printf("txt = %s\n",txt);
00007 }
00008
---------
No macros accessible in this file (D:/speeltuin/bug_542132/src/aa.cpp).

tested with doxygen version 1.9.5 (2f6875a5ca481a69a6f32650c77a667f87d25e88).


I think the problem is not a bug but usage and conform the usage of a compiler.

Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/10068117/example.tar.gz)
