### ISSUE TITLE
no warnings for undocumented members in groups (Origin: bugzilla #542885)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3019]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.5.6* on platform *Other*
Assigned to: Dimitri van Heesch

On 2008-07-14 08:10:05 +0000, Sebastian Tusk wrote:

    In the following example doxygen does not warn that "method" is
    undocumented. If the grouping is removed doxygen warns as expected.
    
    class A
    {
    public:	
    	/**
    	 * \{
    	 * \name group_title
    	 */
    	
    	void method( );
    
    	/**
    	 * \}
    	 */
    };

On 2008-12-24 09:08:07 +0000, Dimitri van Heesch wrote:

    This is by design. People often like to provide some documentation for a
    group of things (bunch of #defines or constants) without having to document
    every single item just to avoid warnings.
    
    I'll turn this bug report into an enhancement request to add an option that
    would produce warnings in such cases.

**Comment by albert-github** [comment]
With version 1.5.6. no warning is given
With version 1.8.15 a warning is given:
```
warning: Member method() (function) of class A is not documented.
```

In both cases wit a default Doxyfile.

I think the problem has been solved in the mean time
