### ISSUE TITLE
Examples are not linked in mainpage (Origin: bugzilla #543283)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3021]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.6* on platform *Other*
Assigned to: Dimitri van Heesch

On 2008-07-16 13:59:14 +0000, Ed Smith-Rowland wrote:

    I have a mainpage sort of like this:
    
    ///
    /// \mainpage
    ///
    ///  ...
    ///  See TiremExampleAPI.cpp for an example.
    ///
    ///  ...
    ///  See TiremExampleDLL.cpp for an example.
    ///
    ///  \section references References
    ///
    ///  - TIREM / SEM HANDBOOK, David Eppink and Wolf Kuebler
    ///
    
    
    ///
    ///  \example TiremExampleAPI.cpp
    ///  This is an example of how to use the TIREM API calls.
    ///
    ///  \example TiremExampleDLL.cpp
    ///  This is an example of how to use TIREM by finding and calling the
    ///  API entry points.
    ///
    
    
    I would like the example file names turned into links into their respective
    pages.
    
    So in main.html (I have frames) the raw file name:
    ... TiremExampleAPI.cpp ...
    would be replaced by a link:
    ... <a class="el" href="TiremExampleAPI_8cpp-
    example.html">TiremExampleAPI.cpp</a> ...
    
    Thank you.

**Comment by albert-github** [comment]
Automatic liking doesn't work but by writing:
```
 See \ref TiremExampleDLL.cpp for an example.
```
there will be the required link (with 1.5.6 and also with the current version)

So I think this is usage.
