### ISSUE TITLE
Alternative syntax for external links and inline code (Origin: bugzilla #544669)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3028]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.5.6* on platform *Other*
Assigned to: Dimitri van Heesch

On 2008-07-25 10:55:40 +0000, Ben Rimmington wrote:

    SUMMARY:
    
    Markdown preserves a document's readability by using a syntax comprised of
    carefully chosen punctuation characters.
    
    <http://daringfireball.net/projects/markdown/syntax#philosophy>
    
    My suggestion for Doxygen is a Markdown-like syntax for external links and
    inline code.
    
    EXAMPLES:
    
    /**
     ** Example 1: An alternative to CODE or TT tags.
     **
     ** Grave accent characters for marking `inline monospaced` code.
     **/
    
    /**
     ** Example 2: An alternative to A tags.
     **
     ** An inline [Doxygen] <http://www.doxygen.org/> link.
     ** A reference-style [Apple Developer Connection] link.
     ** Another reference-style [Wikipedia] link.
     **
     ** @links
     ** [Apple Developer Connection] <http://developer.apple.com/>
     ** [Wikipedia]                  <http://en.wikipedia.org/>
     ** @endlinks
     **/
    
    /**
     ** Example 3: An alternative to Class::method or Class#method.
     **
     ** +[Class classMethod] and -[Class instanceMethod].
     **/
    
    NOTES:
    
    Example 2 uses a simpler syntax than Markdown. It assumes that the [link]
    text is unique within a comment block, and therefore a separate link label
    isn't required. It also uses <URL> instead of (URL) for compatibility with
    Xcode's text editor.
    
    [Doxygen] <http://www.doxygen.org/> would be converted into <a
    href="http://www.doxygen.org/" title="http://www.doxygen.org/"
    target="_parent">Doxygen</a>.
    
    For large comment blocks, more than one @links list could be included, to
    keep the URLs and references close together.
    
    Example 3 uses a native syntax for Objective-C method references (see bugs
    155660, 170591, 301724 and 541330). I've mentioned it here because Doxygen
    would need to distinguish Objective-C method references from external links.

On 2009-04-17 23:07:37 +0000, Quinn Taylor wrote:

    I'd love to see this as well, particularly Examples 2 and 3. Especially if
    Example 2 could be combined with the @see tag. And the output for
    Objective-C auto-links (e.g. Class#method) should match the format shown in
    Example 3, which is what Obj-C programmers expect to see. Seeing
    Class::method is more confusing than helpful, since it looks out of place,
    and like C++.

**Comment by albert-github** [comment]
On the doxygen 1.5.6 version there was no Mardown support, neither in the version from April; 17, 20089 ( maximal 1.5.8 version).
In the doxygen version 1.8.0 February 25, 2012 the support for Markdown was supported, in special markdown files as well in other comment blocks.

I think the problem has been solved in the mean time
