### ISSUE TITLE
@mainpage with "notitle" isn't ignored in navpath (Origin: bugzilla #548904)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3050]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.7.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2008-08-21 18:54:37 +0000, Tony Cebzanov wrote:

    Please describe the problem:
    I have a @mainpage with the "notitle" argument, which is supposed to create
    a main page without a title at the top.  This works, but any other @subpages
    get generated with the text "notitle" in the "navpath" DIV at the top.  This
    would not seem to be the desired effect.
    
    In my opinoin, the use of "notitle" is a bit hackish to begin with.  Instead
    of printing a default title when @mainpage has no arguments, it should
    default to not having a title.
    
    Steps to reproduce:
    1. Use @mainpage directive with notitle argument.
    2. Add a @subpage.
    3. Generate docs.
    4. Click on the subpage.
    
    
    Actual results:
    The navpath at the top has the text "notitle" in it.
    
    Expected results:
    No title should be shown.
    
    Does this happen every time?
    Yes.
    
    Other information:

On 2008-12-27 14:22:59 +0000, Dimitri van Heesch wrote:

    This bug report had the version set to "latest". Since this is a moving
    target I changed it to 1.5.7.1. If you happen to see that the problem is
    fixed in 1.5.8, then please close it.

**Comment by albert-github** [comment]
I used the example (from the manual, with just setting `notitle` instead of the actual title):
```
/*! \mainpage notitle
Some general info.
This manual is divided in the following sections:
- \subpage intro
- \subpage advanced "Advanced usage"
*/
//-----------------------------------------------------------
/*! \page intro Introduction
This page introduces the user to the topic.
Now you can proceed to the \ref advanced "advanced section".
*/
//-----------------------------------------------------------
/*! \page advanced Advanced Usage
This page is for advanced users.
Make sure you have first read \ref intro "the introduction".
*/
```

With 1.5.7.1 on e.g. the introduction page a reference to "notitle". This is not visible in 1.8.16 anymore (actually since 1.7.3 it is not present anymore)

I think the problem has been solved in the mean time.
