### ISSUE TITLE
Dot PDF Output Support (Origin: bugzilla #552800)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3086]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2008-09-18 17:04:11 +0000, Schmalls wrote:

    I was messing around with the Latex header file trying to get the fonts that
    I wanted (I finally figured out how to get the TTF fonts to embed in PDF
    properly). I was then trying to figure out how to do the same for the dot
    graphics included in the PDF. The problem is that as far as I can tell
    doxygen uses -Tps whether we will be producing a PDF or PS output, and this
    seems to force us to use a Type 1 font.
    
    This isn't such a big deal, but with a lot of dot files in the final output,
    you will get just as many Type1 fonts in the output. However, with recent
    versions of dot, there is a -Tpdf option which will allow us to use TrueType
    fonts, which don't seem to be endlessly embedded. I have been able to
    accomplish my desired output by setting doxygen to leave the dot files
    behind, and then running the following bat file before the make pdf call:
    
    for /f %%a in ('dir /b *.dot') do (dot -Tpdf -o%%~na.pdf %%a)
    
    (note that this is on windows). Would it be possible to provide an option
    for doxygen to provide this functionality?

**Comment by albert-github** [comment]
When looking at the code from 1.5.6 and the current code I see that now in case `USE_PDFLATEX` is set the format `pdf` is used in case of 1.5.6 there was unconditional the format `ps` and in case of `USE_PDFLATEX` there was a conversion to `pdf` with `epstopdf`.

I think the problem has been solved in the mean time.
