### ISSUE TITLE
DETAILS_AT_TOP  = YES   missin in 1.5.7.1 (Origin: bugzilla #556110)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3121]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.7.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2008-10-13 09:41:49 +0000, Gilles wrote:

    Hi,
    in all our Doxygen projects, we use DETAILS_AT_TOP=YES.
    The option seems to be missing in 1.5.7.1  (It is no longer documented, and
    it has no effect on the output.)
    
    Is there any chance that you resupport the option?
    Thanks
    Gilles

On 2008-12-24 14:53:47 +0000, Dimitri van Heesch wrote:

    The functionality has not been removed, but is now part of the layout file.
    
    To get the DETAILED_AT_TOP=YES behaviour do the following:
    1) generate a layout file with doxygen -l
    2) Edit DoxygenLayout.xml by searching for detaileddescription 
       and moving that line up to where you want it to appear (do for all 5 
       occurrences).
    3) Specify the layout file in the Doxyfile (e.g.
    LAYOUT_FILE=DoxygenLayout.xml)
    
    I'll leave this bug open as a placeholder for others who might run into the
    same issue.

**Comment by albert-github** [comment]
As mentioned this is usage as the feature `DETAILS_AT_TOP` has been moved to the layout file.
