### ISSUE TITLE
Python Package functions are not documented if EXTRACT_ALL is off (Origin: bugzilla #556466)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3125]
status NEW severity *normal* in component *documentation* for *---*
Reported in version *1.5.5* on platform *Other*
Assigned to: Dimitri van Heesch

On 2008-10-15 20:19:39 +0000, Randy Merkel wrote:

    Doxygen generated links to functions in a Python Package will be broken
    unless EXTRACT_ALL is YES.
    
    Example:
        MyPackage/__init__.py
            ## \file MyPackage/__init__.py
            #  ...
            #  \package MyPackage
            #  ....
            __all__ = ["moduleA", "moduleB"]
    
        MyPackage/moduleA.py
            ## \file MyPackage/moduleA.py
            #  ...
            def foo ():
                Pass
    
        MyPackage/moduleB.py
            ## \file MyPackage/moduleA.py
            #  ...
            def bar ():
                Pass
    
    
    Unless EXTRACT_ALL is Yes, the package documentation will not contain
    references to moduleA/B and the file documentation for moduleA/B.py will
    have broken links to foo & bar's documentation.
    
    Workaround is to set EXTRACT_ALL to YES.
    
    Doxyfile:
    
    JAVADOC_AUTOBRIEF = YES
    TAB_SIZE = 4
    OPTIMIZE_OUTPUT_JAVA = YES
    EXTRACT_ALL = YES
    SORT_BRIEF_DOCS = YES
    QUITE = YES
    RECURSIVE = YES
    HAVE_DOT = YES
    CALL_GRAPH = YES
    SEARCH_ENGINE = YES

**Comment by albert-github** [comment]
In the 1.5.5 version I see that when not using `EXTRACT_ALL=YES` the link to `moduleA.foo` in `module_a_8py.html` is a broken link.
When using version 1.9.1 the link is not broken, it points to itself  (note in the current master (1.9.2 (9271e09d9aacba067e6a95340c9fbedbff9a2085)) the link doesn't even exists as there is actually nowhere / no detailed section to jump to).

I think the problem has been solved in the mean time.
