### ISSUE TITLE
unable to resolve references after @brief and @b (Origin: bugzilla #556572)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3127]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.5.6* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[moduleconfig](https://sourceforge.net/projects/doxygen/files/attachments/bug556572_121104_moduleconfig/download/download)_ (ID 121104)

On 2008-10-16 15:53:20 +0000, steve mancey wrote:

    Please describe the problem:
    After upgrading from 1.5.2 to 1.5.6 doxygen is generating lots of warnings,
    predominately after @b (bold) and @brief complaining about unresolved
    references:
    
    Warning: unable to resolve reference to 'x' for \ref
    
    No warnings were present with the same code base using version 1.5.2
    
    In some cases i also notice the reference to the same object will succeed in
    some places in the file and fail in others (e.g. on the line after the @b
    keyword).
    
    Any ideas?
    
    Steps to reproduce:
    1. 
    2. 
    3. 
    
    
    Actual results:
    
    
    Expected results:
    
    
    Does this happen every time?
    Yes
    
    Other information:

On 2008-10-18 12:31:26 +0000, Dimitri van Heesch wrote:

    Can you try with version 1.5.7.1? If the problem is still there please
    attach a small example (source+config file) that allows me to reproduce the
    problem.

On 2008-10-22 09:32:07 +0000, steve mancey wrote:

    Hi. Have tried with 1.5.7.1 and problem still exists. Have also tried
    reproducing with an isolated source file (containing pasted code that caused
    a reference warning in our main build) and the problem is not reported.
    
    I then came across what looked like a similar issue another user had seen:
    http://www.nabble.com/uses-doxygen-buffers-with-static-size--td17667363.html
    
    'Hello world,
    
    my final temporary cure to heal my problem with too small buffers is to
    modify src/increasebuffer.pl to be the following:
    
    while (<>)
    {
             s/YY_BUF_SIZE 16384/YY_BUF_SIZE 262144/g;
             s/YY_READ_BUF_SIZE 8192/YY_READ_BUF_SIZE 262144/g;
             print $_;
    }
    
    Would be nice, if anybody could confirm my problem and if one of the
    developers either commit the new increasebuffer.pl or do a better cure.'
    
    This looked promising, but i notice the changes have already been brought
    into 1.5.7.1.
    
    Do you think something similar to this fixed issue might be causing the
    problem?
    
    If i manage to narrow down the issue further i will attach source / config
    files etc, but i haven't had any success so far. I will attach our current
    main build config in case this helps (the source base is large).
    
    Regards,
    Steve
    
    
    
    

On 2008-10-22 09:59:33 +0000, steve mancey wrote:

    Created attachment 121104
    doxy config file being used

On 2008-12-24 15:01:10 +0000, Dimitri van Heesch wrote:

    Without an example that shows how to reproduce the problem there's not much
    I can do...

**Comment by albert-github** [comment]
In the mean time a number of improvements in the different lex files have been implemented, but as mentioned in the last comment:
> Without an example that shows how to reproduce the problem there's not much
> I can do...

So I think this issue is either solved or incomplete, setting it to incomplete.
