### ISSUE TITLE
Different HTML file extensions in tag files leads to dead links (Origin: bugzilla #557216)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3140]
status NEW severity *critical* in component *general* for *---*
Reported in version *1.5.7.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[msdn.tag](https://sourceforge.net/projects/doxygen/files/attachments/bug557216_217933_msdn.tag/download/download)_ (ID 217933)

On 2008-10-21 10:08:34 +0000, Bas Ploeger wrote:

    When supplying a tag file that contains different HTML file extensions than
    specified by the HTML_FILE_EXTENSION config variable, the output will
    contain dead links.
    
    More specifically, and for reproducing this bug, first generate a tag file
    using the following settings:
      HTML_FILE_EXTENSION = .html
      GENERATE_TAGFILE = tagfile.tag
    
    The generated tag file will contain anchorfile-entries of the following
    form:
      <anchorfile>filename.html</anchorfile>
    
    Now generate documentation with a different HTML file extension (e.g.
    ".php") that links to the entities in tagfile.tag using the following
    settings:
      HTML_FILE_EXTENSION = .php
      TAGFILES = tagfile.tag=/location/of/external/docs
    
    In the output ".php"-files, links to the external entities in tagfile.tag
    now have the following form:
      <a ... href="filename.html.php"> ... </a>
    
    Which should obviously be:
      <a ... href="filename.html"> ... </a>
    
    The ".php" extension should not have been added to the file links.

On 2012-07-03 13:24:56 +0000, Matthew wrote:

    I am having this same issue with tag files I created to point to MSDN which
    uses the ".aspx" extension.  It seeks wanting to add ".html" after the
    ".aspx" extension.

On 2012-07-03 13:25:53 +0000, Matthew wrote:

    Created attachment 217933
    Short sample MSDN tag file.

On 2012-07-03 15:05:01 +0000, Matthew wrote:

    (In reply to comment # 1)
    > I am having this same issue with tag files I created to point to MSDN
    which
    > uses the ".aspx" extension.  It seeks wanting to add ".html" after the
    ".aspx"
    > extension.
    
    I should note that I can reproduce this event in 1.8.1.1

**Comment by albert-github** [comment]
The problem is the same problem as with issue HTML link incorrect when using tagfile (Origin: bugzilla #335614) (#2089) that has a proposed patch #7286

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.17.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
