### ISSUE TITLE
WARN_NO_PARAMDOC does not report complete "param" list missing (Origin: bugzilla #557285)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3141]
status NEW severity *enhancement* in component *doxywizard* for *---*
Reported in version *1.5.7* on platform *Other*
Assigned to: Dimitri van Heesch

On 2008-10-21 17:56:20 +0000, Ron wrote:

    +++ This bug was initially created as a clone of Bug # 557164 +++
    
    Please describe the problem:
    WARN_NO_PARAMDOC does not report complete "param" list missing. When
    WARN_NO_PARAMDOC is set to YES the doxywizard should report missing @param
    (\param) when the function has parameters (i.e., an undocumented parameter).
    Doxygen will warn for missing/mispelled parameters when a partial parameter
    list exists but it will not warn if the complete list is missing.
    
    Steps to reproduce:
    1. Create a function that contains a parameter
    2. Document the function with the exception of the parameter
    3. Run Doxywizard with WARN_NO_PARAMDOC set to YES
    
    
    Actual results:
    Doxywizard does not report any warnings.
    
    Expected results:
    Doxywizard reporting the undocumented parameters.
    
    Does this happen every time?
    Yes, when the complete list is missing.
    
    Other information:

On 2013-07-25 01:21:41 +0000, Jonathan wrote:

    I re-confirmed this issue with version 1.8.4.  The following source code
    replicates this error.
    
    /// @brief This should result in a doxygen warning when WARN_NO_PARAMDOC 
    ///	is set as the param is not documented
    void TestFunction(int i)
    {
       // do something
    }
    
    This issue is quite irritating as it prevents Doxygen from reporting missing
    parameters for single parameter functions when WARN_NO_PARAMDOC is
    specified.  That being said, this should be an error not an enhancement.

**Comment by albert-github** [comment]
With version 1.8.4 I don't see a warning.
With version 1.8.14 I see the warning:
```
warning: parameters of member TestFunction are not (all) documented
```

I think the problem has been solved in the mean time.
