### ISSUE TITLE
Generated perlmod contains syntax error. (Origin: bugzilla #557564)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3144]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.7.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2008-10-23 08:09:49 +0000, Mark Toller wrote:

    I have a header file containing :
    
    ///@brief Return satellite Id.
    ///@details used by TPDBStorageManager template class.
    ///@see TPDBStorageManager.
    ///@return unsigned int satellite Id.
    unsigned int getId( void );
    
    And the generated perlmod contains :
    
    detailed => {
                  doc => [
                    { 
                      type => 'text',
                      content => 'used by TPDBStorageManager template class. ,
                      see => [TPDBStorageManager. '
                      }
                    ],
                    return => [
                      {
                        type => 'text',
                        content => 'unsigned int satellite Id.'
                      }
                    ]
                  ]                                     
                },                                                      
    
    Adding a blank line between @details and @see, i.e. 
    
    ///@brief Return satellite Id.
    ///@details used by TPDBStorageManager template class.
    ///
    ///@see TPDBStorageManager.
    ///@return unsigned int satellite Id.
    unsigned int getId( void );
    
    Fixes the problem, and the generated perlmod is :
    
    detailed => {
                  doc => [  
                    {
                      type => 'text',
                      content => 'used by TPDBStorageManager template class.'
                    },
                    {
                      type => 'parbreak'
                    },
                    see => [
                      {
                        type => 'text',
                        content => 'TPDBStorageManager. '
                      }
                    ],
                    return => [
                      {
                        type => 'text',
                        content => 'unsigned int satellite Id.'
                      }
                    ]
                  ]
                },

On 2008-10-23 08:49:05 +0000, Mark Toller wrote:

    Incorrect doxygen formatting with the \struct tag also generates bad perl :
    
    /*!
    \struct CA system ID list
    \brief This struct give the header of CA system ID array and length of it
    \remarks  pu16Ca_SystemID - CA system ID header
        u16Ca_SystemIDNum - length of CA system ID array
    */
    typedef struct 
    {
        unsigned short int*    pu16CaSystemID;
        unsigned short int    u16CaSystemIDNum;
    } CA_SYSID_LIST;
    
    
    Changing the \struct line to 
    
    \struct CA_SYSID_LIST
    
    generates good perl results.

On 2009-09-30 04:50:51 +0000, Gisbert wrote:

    *** Bug 596813 has been marked as a duplicate of this bug. ***

**Comment by albert-github** [comment]
With the 1.5.7.1 I see that incorrect perl files are generated for the 2 examples (though the second example gives some warnings like:
```
 Warning: the name `system' supplied as the argument of the \class, \struct, \union, or \include command is not an input file
 Warning: Compound CA_SYSID_LIST is not documented.
```
though the resulting perl file still should be correct).

With the version 1.9.3 (c0b9eafbfb53286ce31e75e2b6c976ee4d345473) I don't see the perl problems anymore (the warnings of course remain).

I think the problem has been solved in the mean time.
