### ISSUE TITLE
"no matching file member found" error apparently connected to namespaces (Origin: bugzilla #558411)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3154]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.7.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2008-10-29 16:03:59 +0000, Robert Lupton wrote:

    In this piece of C++, there are 2 #defined variables.  If
    either is true doxygen (with a default config file, as generated
    with doxygen -g) processes the files correctly.  If both are
    false, I get
    foo.cc:41: Warning: no matching file member found for 
    MaskT lsst::detection::foo(image::Mask< MaskT > mask)
    Possible candidates:
      MaskT foo(typename lsst::image::Mask< MaskT > mask)
```    
    //!
    // \file
    //
    // If either or both of these is true, doxygen handles foo correctly;
    // if both are false:
    //    foo.cc:41: Warning: no matching file member found for 
    //        MaskT lsst::detection::foo(image::Mask< MaskT > mask)
    //    Possible candidates:
    //        MaskT foo(typename lsst::image::Mask< MaskT > mask)
    //
    #define EXPLICIT_NAMESPACE 0
    #define DEFINE_MASK 0
    
    namespace lsst {
    #if DEFINE_MASK
        namespace image {
            /// \brief Hello World
            template<typename T> struct Mask { };
        }
    #endif
    
        namespace detection {
            template<typename MaskT>
            MaskT foo(typename lsst::image::Mask<MaskT> mask);
        }
    }
    
/************************************************************************************************************/
    /**
     * \brief OR bitmask into all the pixels in footprints
     *
     * \return bitmask
     */
    template<typename MaskT>
    MaskT lsst::detection::foo(
    #if EXPLICIT_NAMESPACE
                               typename lsst::image::Mask<MaskT> mask ///< Mask
    to set
    #else
                               typename       image::Mask<MaskT> mask ///< Mask
    to set
    #endif
                                             ) {
    }
```

**Comment by albert-github** [comment]
The specified code does not compile (when both defines are set to 0), it only compiles when both are set to 1 or at least `DEFINE_MASK` is set to 1. So with both set to 0 it is not valid code and one of the requirements for doxygen is to have valid code.

I think the problem is usage.
