### ISSUE TITLE
pointer of pointer to class not recognized (Origin: bugzilla #559219)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3162]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.5.7.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2008-11-04 02:02:08 +0000, xiangming wrote:

    doxygen does not recognize class if it is used as pointer of pointer. for
    example, 'myclass' is a class that has member function called 'func'
    
    myclass **cl;
    
    (*cl)->func();
    
    Generated source document(SOURCE_BROWSE=YES) will not link it to the
    function/class definition.

On 2008-11-04 02:03:10 +0000, xiangming wrote:

    btw, it worked in 1.3.9 release.

**Comment by albert-github** [comment]
When having the source code (aa.cpp):
```
 void fie (void)
 {
   myclass **cl;
  
   (*cl)->func();
 }
```
and include file (aa.h):
```
/// a class
class myclass
{
  public:
    /// a function
    void func();
};


/// a fie
void fie (void);
```

With the 1.5.7.1 we don't see a link in the source code of the cpp file for `func`, in the version 1.9.0 we see the link.

Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/5760326/example.tar.gz)


I think the problem has been solved in the mean time.
