### ISSUE TITLE
EXPAND_ONLY_PREDEF neglected within function macro expansions (Origin: bugzilla #559489)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3165]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.5* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[test.h](https://sourceforge.net/projects/doxygen/files/attachments/bug559489_122050_test.h/download/download)_ (ID 122050)
- _[Doxyfile](https://sourceforge.net/projects/doxygen/files/attachments/bug559489_122051_Doxyfile/download/download)_ (ID 122051)

On 2008-11-05 19:23:14 +0000, Martin Baeuml wrote:

    If a macro A is used inside another macro B, A is expanded even if
    EXPAND_ONLY_PREDEF = YES and A is not in the predefined list.
    
    Example (see also attached files):
    
    #define AUTO 1
    #define DEFAULT(x) = x
    int test_function(int p DEFAULT(AUTO));
    
    expected documentation:
    
     int test_function(int p = AUTO); 
    
    wrongly generated documentation:
    
     int test_function(int p = 1); 
    
    with doxygen settings
    MACRO_EXPANSION    = YES
    EXPAND_ONLY_PREDEF = YES
    EXPAND_AS_DEFINED  = DEFAULT

On 2008-11-05 19:24:52 +0000, Martin Baeuml wrote:

    Created attachment 122050
    test case

On 2008-11-05 19:25:13 +0000, Martin Baeuml wrote:

    Created attachment 122051
    Doxyfile for test case

**Comment by albert-github** [comment]
I've just extended the proposed patch, pull request #9341, for this case.

**Comment by albert-github** [comment]
With the fix https://github.com/doxygen/doxygen/commit/387f508b2e41179a9f70b2914132c2bf12d07b43 a number of issues regarding the `EXPAND_AS_DEFINED ` have been solved but this issue is still present.

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.5.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
