### ISSUE TITLE
Support for Changelog / History of Changes (maybe implemented as general table support?) (Origin: bugzilla #560304)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3169]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2008-11-11 09:41:29 +0000, Ian Hubbertz wrote:

    It would be nice if there is some special formatting for a "History of
    changes" of a file, class or any other structure.
    
    I suggest to add a \hoc command that creates a table with the help of a
    delimiter like '|'.
    
    For example:
    
    /**
    @class myClass
    @hoc
    20081107|Added HOC-support             |IanH    | 12345
    20081108|Fixed HOC-support for classes |IanH    | 12346
    */
    
    would build a table inside the documentation of class myClass and the table
    would be named "History of Change".
    
    You can also think of automatically recognizing a bug-tracker ID (in my
    example 12345 and 12346) and add them to the list of bugs from the \bug
    keyword.

**Comment by albert-github** [comment]
In my opinion this is nothing else but a Markdown type of table and can be handled as such. The Markdown support has been introduced in doxygen in version 1.8.0.

I think the problem has been solved in the mean time
