### ISSUE TITLE
Class graph does not differentiate same classes in different namespace (Origin: bugzilla #560861)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3175]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.5.7.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[dox.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug560861_122698_dox.zip/download/download)_ (ID 122698)

On 2008-11-14 22:03:18 +0000, Christophe Winkler wrote:

    When generating the doc for the following classes:
    
    /*! class Root */
    class Root {
    };
     
    namespace A {
        /*! class A::Class1 */
        class Class1 : public Root {
        };
    }
    
    namespace B {
        /*! class B::Class1 */
        class Class1 : public Root {
        };
    }
    
    the class graph does not differentiate A::Class1 and B::Class1 when hiding
    the scope names.
    
    Compile the 4 docs of the attached project and look at the class graph of
    Root. For the short_graph version, the class graph is corrupted.
    
    
    BTW, it would be great to be able to strip a part of the namespace scope. My
    company policy is to have the following root namespaces:
    
    namespace my_company {
    namespace project {
    // code, with possibly internal namespaces
    }
    }
    
    I would love to drop the my_company::project from the fullt scoped name,
    while keeping the internal namespaces. Would that be possible?

On 2008-11-14 22:10:37 +0000, Christophe Winkler wrote:

    Created attachment 122698
    Minimal cpp code with doxygen settings showing the issue,
    
    Minimal cpp code featuring the observed issue. Contains 4 different doxygen
    configuration, one of them (short_graphs) generates a buggy class graph.

On 2008-11-15 11:41:00 +0000, Christophe Winkler wrote:

    *** Bug 560859 has been marked as a duplicate of this bug. ***

On 2008-11-15 11:42:08 +0000, Christophe Winkler wrote:

    *** Bug 560860 has been marked as a duplicate of this bug. ***

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #8321

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.2.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
