### ISSUE TITLE
Doxygen can not parse classes correctly when keywords appear after "class". (Origin: bugzilla #561471)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3179]
status NEW severity *major* in component *general* for *---*
Reported in version *1.5.7.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2008-11-19 07:40:31 +0000, I love registering usernames. wrote:

    Doxygen does not parse classes correctly when a keyword appears between the
    "class" keyword and the name of the class. For example, in MS C++:
    
       class __declspec(dllexport) SomeClass {
       };
    
    Doxygen incorrectly parses "__declspec(dllexport)" as the name of the class.
    
    As a workaround, Doxygen can be forced to generate correct class
    documentation by using the "/class" command with an acceptable level of
    convenience. However, forcing Doxygen to generate correct documentation for
    class members (and to associate those members with SomeClass rather than
    __declspec(dllexport)) with the /fn command is considerably more tedious and
    error prone.

On 2008-11-19 07:42:30 +0000, I love registering usernames. wrote:

    I'm sorry, I should have specified this is when parsing C++ source (although
    it's probably clear from the example).

On 2008-12-09 18:59:38 +0000, Dimitri van Heesch wrote:

    Well, strictly speaking it is not valid C++, which is why doxygen doesn't
    parse it, unless you tell doxygen's preprocessor to remove the __declspec()
    stuff as explained in the preprocessor chapter of the user manual...

On 2008-12-27 14:23:01 +0000, Dimitri van Heesch wrote:

    This bug report had the version set to "latest". Since this is a moving
    target I changed it to 1.5.7.1. If you happen to see that the problem is
    fixed in 1.5.8, then please close it.

On 2008-12-29 07:54:00 +0000, I love registering usernames. wrote:

    (In reply to comment # 2)
    > Well, strictly speaking it is not valid C++, which is why doxygen doesn't
    parse
    > it, unless you tell doxygen's preprocessor to remove the __declspec()
    stuff as
    > explained in the preprocessor chapter of the user manual...
    
    Why would somebody read the preprocessor chapter of the user manual when
    looking for information about __declspec support?
    

On 2008-12-29 12:31:36 +0000, Dimitri van Heesch wrote:

    > Why would somebody read the preprocessor chapter of the user manual when
    > looking for information about __declspec support?
    
    Good point. But I would think that the same someone is smart enough to type
    the words "doxygen __declspec" in google and follow the first hit (which
    leads to the preprocessor chapter of the user manual).

**Comment by Maturin** [comment]
I found the preprocessor chapter via google. But even after setting

```
WARN_AS_ERROR          = YES
ENABLE_PREPROCESSING   = YES
MACRO_EXPANSION        = YES
EXPAND_ONLY_PREDEF     = YES
PREDEFINED             = __declspec(x)=
```

I receive an error message, that my compound is not documented. Is this a bug or am I missing something?

Below you find the sample code and the configuration file.

Thanks,
- Lars

[doxygentest.zip](https://github.com/doxygen/doxygen/files/3081040/doxygentest.zip)

**Comment by albert-github** [comment]
Unfortunately you missed something.

You documented the members of class Test but you didn't document the class itself.

Suggest to close the issue as usage.

**Comment by Maturin** [comment]
You are right, I missed documenting the class itself. Thanks for pointing that out. 

While fixing this, I also figured out, that the class, was not in the namespace. So, I tried different versions of defining a class in a namespace. And it seems to me, that doxygen has a problem with the macro in connection with namespaces. 

The cpp file is in all cases the same. 

h2. Scenario 1: No Namespace, working

```
#pragma once
#include "ExportMacros.h"

namespace Outer
{
  namespace Inner
  {
    class Test;
  }
}

/// This is very nice class. 
class EXPORT_API Test
{
 public:
  /// Creates a new test object.
  Test();

  /// This method does something special.
  void doSomething();
};
```

h2. Scenario 2: Forward declaration in namespace, not working

```
#pragma once
#include "ExportMacros.h"

namespace Outer
{
  namespace Inner
  {
    class Test;
  }
}

/// This is very nice class. 
class EXPORT_API Outer::Inner::Test
{
 public:
  /// Creates a new test object.
  Test();

  /// This method does something special.
  void doSomething();
};
```
Error:
```
/mnt/c/Simi/doxygentest/test.cpp:7: error: no matching class member found for Test::Test()
```

h2. Scenario 3: Forward declaration in namespace, no DLL API,  working

```
#pragma once
#include "ExportMacros.h"

namespace Outer
{
  namespace Inner
  {
    class Test;
  }
}

/// This is very nice class. 
class Outer::Inner::Test
{
 public:
  /// Creates a new test object.
  Test();

  /// This method does something special.
  void doSomething();
};
```

h2. Scenario 4: Class definition in namespace, working

```
#pragma once
#include "ExportMacros.h"

namespace Outer
{
  namespace Inner
  {
    /// This is very nice class. 
    class EXPORT_API Test
    {
    public:
      /// Creates a new test object.
      Test();

      /// This method does something special.
      void doSomething();
    };

  }
}
```

After moving all my forwarded class definitions into the namespace, as shown in scenario 4, I was also able to build the documentation of my real world project. But that for that project it is not the preferred way of writing the code.

**Comment by albert-github** [comment]
Seen the different topic I think it would be better to submit a new issue for the later problem.

**Comment by Maturin** [comment]
I agree and I created issue #6933.

Thanks,
\- Lars
