### ISSUE TITLE
Can you create a @unimplemented special command? (Origin: bugzilla #561738)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3184]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.5.6* on platform *Other*
Assigned to: Dimitri van Heesch

On 2008-11-20 22:03:21 +0000, ckaran@arl.army.mil wrote:

    I'm looking for something that is exactly like @deprecated, but is for as
    yet unimplemented features.  I figure something like @unimplemented would be
    right.  If you're feeling really bored and want to do extra work, if we
    could put a string after it that can be printed as a
    reason/version/whatever, that would be handy too... kind of like
    "@unimplemented Planned future feature for version 37.12" or "@unimplemented
    Will implement version 3.14159"

On 2008-11-24 12:07:24 +0000, Dimitri van Heesch wrote:

    You can already define such a command yourself using \xrefitem and ALIASES,
    see http://www.stack.nl/~dimitri/doxygen/commands.html#cmdxrefitem
    for more info.

**Comment by albert-github** [comment]
As mentioned in the comment it is already possible by means of an `\xreflist`.

Suggest to close as usage
