### ISSUE TITLE
Membergroups don't work correctly inside of groups (Origin: bugzilla #562986)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3185]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.7.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[memgrp.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug562986_124154_memgrp.zip/download/download)_ (ID 124154)

On 2008-12-02 15:31:54 +0000, frankyfm wrote:

    Please describe the problem:
    If you use the the \name command <mgrp-name> to create a member group for
    certain Defines, than the File Reference contains a section with the name
    <mgrp-name> under the Defines section which groups those Defines. Later in
    the Define Documentation you can find all the details about.
    If you add certain of those grouped Defines to a group by using \addtogroup
    or \ingroup than in the Defines section of the appropriate Module
    Documentation those Defines are missing completely instead of being
    displayed in groups. But later the Define Documentation displays the
    details.
    If you add all your Defines to both, the group and the member group, than
    the section Defines is completely missing in the Module Documentation
    (overview).
    The same thing applies also to Functions and maybe to other entities.
    
    Steps to reproduce:
    Do the things in the problem description.
    
    Actual results:
    See problem description.
    
    Expected results:
    I would expect that entities which are both, in a group as well as in a
    member group are shown in a grouped manner in the Module Documentation as
    they are in the File Reference.
    
    Does this happen every time?
    yes
    
    Other information:

On 2008-12-08 11:23:57 +0000, frankyfm wrote:

    Created attachment 124154
    Example files showing the problem 
    
    The zip contains the files which can be used see the problem. The _memgrp.c
    is the documented file. The memgrp.cfg is the doxygen configuration. To
    build the example I used the following commands on the commandline:
    "doxygen memgrp.cfg" and "make -C memgrp\latex".
    This creates amongst others the file refman.pdf in the directory
    memgrp/latex.
    
    I did the same with different versions of doxygen (1.5.2 and 1.5.7.1.) and
    got two different results. I also added those corresponding files to the zip
    (refman-1.5.2.pdf and refman-1.5.7.1.pdf). That shows that doxygen 1.5.7.1
    does anything wrong with member groups.

**Comment by albert-github** [comment]
I checked with the current (1.9.8) doxygen version the results and the pdf looks again like the 1.5.2 version also the current HTML output looks like expected. 
The 1.5.7.1 version is indeed missing some information.

Note:
There are a number of lines like:
```
/* @} end of member group Global Functions */
```
these are corrected to:
```
/** @} */ /* end of member group Global Functions */
```
this is due to the fact the `/*` is not seen anymore by doxygen as doxygen comment. This change has no influence on the 1.5.7.1 results though.

I think the problem has been solved in the mean t9ime.
