### ISSUE TITLE
HTML output for pure virtual function with "throws()" hint is wrong (Origin: bugzilla #564252)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3196]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.7.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2008-12-12 14:00:56 +0000, Sascha Cunz wrote:

    For a C++ class-member-function specified as
        virtual void foo() const throw() = 0;
    
    doxygen outputs in HTML (Method overview on class page)
        virtual void foo() const = 0 throw()
    
    throw() gets pushed to the end. This output cannot be copied to a new class
    and compiled.
    
    One might argue that it is pointless to give the throw() hint at a pure
    virtual method. However, i know that throw() will not be propagated to
    children.
    
    So its purpose is soley for documentation - saying "when calling that
    function we never expect it to throw an exception".

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #9493

**Comment by albert-github** [comment]
An alternative code update, compared to #9493, has been made in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.7.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
