### ISSUE TITLE
[Doxygen-develop] Let us choose the amount of detail for the class diagrams (Origin: bugzilla #565473)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3204]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.5.7.1-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2008-12-23 15:47:45 +0000, Raja Kajiev wrote:

    Originally posted here:
https://sourceforge.net/mailarchive/message.php?msg_name=268608.22300.qm%40web38801.mail.mud.yahoo.com
    
    ----
    From: Pietro Mele <pietromele@ya...> - 2008-11-24 14:49 
    
    To reduce the size of the class diagrams, it would be useful to be able to
    select theamount of detail shown for the classes. Going from the most
    compact representation to the most detailed one, show:
    
    - Just the class name (with eventual template stuff).
    
    - Just the public member functions, with and without their parameters.
    
    - All member functions and attributes without their parameters.
    *** In this case, if there are some overloaded functions, do NOT show them
    all. It is useless to have a list of, e.g., 10 overoladed Print() functions
    which are shown in the same way because the parameters are omitted. This is
    an incredible waste of space on the screen and on paper, that makes diagrams
    appear huge even if they can be reduced to a more manageble size. Just use a
    simbol to indicate that the function is overloaded (e.g. #), and print it
    just once. ***
    
    - All member functions and attributes with their parameters and return type.
    
    - Show everything.
    ----

**Comment by albert-github** [comment]
I think the possibilities when `UML_LOOK=YES` and the in doxygen 1.9.0 introduced `DOT_UML_LOOK` are addressing this issue.
In case other requirements are present a new issue should be opened (whith an appropriate example).

I think this issue has been solved in the mean time.
