### ISSUE TITLE
Fortran: Does not recognize backslash at end of documentation line (Origin: bugzilla #565713)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3206]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.7.1-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2008-12-26 19:41:02 +0000, albert wrote:

    Fortran does not recognise backslash at end of documentation line (inside
    line works OK)
    
    Example code:
    =============
    MODULE bug_escape
      !> @code
      !! Documentation with \ (backslash) at the end of a line does not show it
      !!   line does not show \
      !! @endcode
      integer : dummy
    END MODULE bug_escape
    
    Resulting documentation:
    ========================
    bug_escape Namespace Reference
    
    Variables
    integer 	dummy
    Variable Documentation
    integer bug_escape::dummy
    
     Documentation with \ (backslash) at the end of a line does not show it
       line does not show 
    
    Definition at line 6 of file bug_esc.f90.

On 2010-12-23 22:24:46 +0000, Daniel Franke wrote:

    Confirmed for r749.
    
    Note 1: if preprocessing is disabled, the '\' at the end of the line shows
    up.
    
    Note 2: An equivalent C-example ...
    
    /**
     * @code
     * Documentation with \ (backslash) at the end of a line does not show it
     *   line does not show \
     * @endcode
     */
    void foo() {}
    
    ... shows the trailing '\' independent of preprocessing?!

On 2018-06-27 13:33:47 +0000, albert wrote:

    The problem in the C code was in the 1.8.14 version already solved.
    
    For the Fortran problem I've just pushed a proposed patch to github (pull
    request 778, https://github.com/doxygen/doxygen/pull/778).

**Comment by albert-github** [comment]
Code has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
