### ISSUE TITLE
unable to resolve links to java functions with array arguments (Origin: bugzilla #566109)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3211]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.8* on platform *Other*
Assigned to: Dimitri van Heesch

On 2008-12-31 09:18:55 +0000, bauke wrote:

    While generating the documentation of a java file containing:
    
    /** x */
    public class test {
    	/** {@link #main(String[])}
    	 *  {@link #foo(Object...)}
    	 * @param args */
    	public static void main(String[] args) {}
    	/** */
    	public void foo(Object...s){}
    }
    
    The following warnings were generated:
    src/test.java:3: Warning: unable to resolve link to `#main(String[])' for
    \link command
    src/test.java:4: Warning: unable to resolve link to `#foo(Object...)' for
    \link command
    
    Both links should be able to resolve.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7047

**Comment by albert-github** [comment]
An alternative approach has been implemented in the master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
