### ISSUE TITLE
Wrong picture of recursive function (Origin: bugzilla #566128)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3212]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.8* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[bug_r.tar](https://sourceforge.net/projects/doxygen/files/attachments/bug566128_125574_bug_r.tar/download/download)_ (ID 125574)
- _[doxygen187_recursive_function.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug566128_278448_doxygen187_recursive_function.zip/download/download)_ (ID 278448)

On 2008-12-31 12:58:26 +0000, albert wrote:

    When having a recursive function, the function is depicted wrong in the call
    graph in the .h file and in the caller graph with the .c file.
    (This function might be related to bug 527049 which deals with a non
    recusive function but defined in .h file as well).
    
    Example code:
    bug_r.h:
    int bug_r(int val);
    
    bug_r.c:
    #include "bug_r.h"
    
    int bug_r(int val)
    {
      if (val <= 1) return 1;
      return(val * bug_r(val -1));
    }

On 2008-12-31 13:03:02 +0000, albert wrote:

    Created attachment 125574
    Project with source files and resulting doxygen output

On 2010-11-08 21:39:32 +0000, albert wrote:

    In case of Fortran no graph is displayed at all.
    
    Example code:
    recursive integer function rec_fie(i)
      integer i
      if (i == 0) then
        rec_fie = 0
      else
        rec_fie = i + rec_fie(i-1)
      endif
    end
    
    recursive subroutine rec_sub(i, res)
      integer i
      integer res
    
      if (i == 0) then
        res = 0
      else
        call rec_sub(i-1, res)
        res = res + i
      endif
    end

On 2014-06-14 16:46:26 +0000, Cornelius wrote:

    Bug is still open in DoxyGen Version 1.8.7. 
    Here is one additional example.
    
    -----------------
    void tic() 
    {
        tac();
    }
    void tac() 
    {
        toc();
    }
    void toc() 
    {
        tic();
    }
    
    int fact(int n)
    {    
        int x=1;    
    
        while(n>1)    
        {    
            x=n*fact(n-1);  //recursive function in C 
        }    
    
        return(x);    
    }    
    
    void main() 
    {
     	fact(5);
    	tic();
    
    }

On 2014-06-14 16:49:51 +0000, Cornelius wrote:

    Created attachment 278448
    Call graph does not show recursive functions
    
    Call graph does not show recursive functions

**Comment by albert-github** [comment]
I checked the problem wit the mentioned versions and saw the problems.
With the add of commit ce032dd509862a2af10c389c0609a5736540ef61 and pull request #8631 the problem will be fixed.

Setting issue to fixed but not yet released.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.2.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
