### ISSUE TITLE
bad html in search results -> destroys layout (Origin: bugzilla #566814)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3216]
status NEW severity *normal* in component *general* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-01-06 20:23:12 +0000, Danny GÃ¶tte wrote:

    The following html should not appear in that way.
    
    
    &nbsp;
    <div class="qindex">
      <form class="search" action="search.php" method="get">
    
                <td><input type="text" name="query" value="CreateWindow"
    size="20" accesskey="s"/></td>
              </tr>
            </table>
          </form>
        </li>
      </ul>
    </div>
    &nbsp;
    <div class="searchresults">
    ...

On 2009-02-14 18:51:56 +0000, Dimitri van Heesch wrote:

    How did you make doxygen produce this output?
    Could you please attach a self contained example (source+config file) that
    allows me to reproduce the problem?

On 2009-02-27 17:40:51 +0000, Danny GÃ¶tte wrote:

    * result is here: http://www.reactos.org/generated/doxygen/
    * config:
    http://svn.reactos.org/svn/reactos/trunk/reactos/Doxyfile?revision=38559
    * code:
      * webview: http://svn.reactos.org/svn/reactos/trunk/reactos/
      * svn: svn://svn.reactos.org/reactos/trunk/reactos

**Comment by albert-github** [comment]
I tried to reproduce the problem with the current version of reactos.
With 1.5.8 I don't get the situation as specified but something similar (though html output looks OK):
```
<!-- Generated by Doxygen 1.5.8 -->
<div class="navigation" id="top">
  <div class="tabs">
    <ul>
      <li><a href="main.html"><span>Main&nbsp;Page</span></a></li>
      <li class="current"><a href="pages.html"><span>Related&nbsp;Pages</span></a></li>
      <li><a href="modules.html"><span>Modules</span></a></li>
      <li><a href="namespaces.html"><span>Namespaces</span></a></li>
      <li><a href="annotated.html"><span>Classes</span></a></li>
      <li><a href="files.html"><span>Files</span></a></li>
      <li><a href="examples.html"><span>Examples</span></a></li>
    <li>
      <form action="search.php" method="get">
        <table cellspacing="0" cellpadding="0" border="0">
          <tr>
            <td><label>&nbsp;<u>S</u>earch&nbsp;for&nbsp;</label></td>
            <td><input type="text" name="query" value="" size="20" accesskey="s"/></td>
          </tr>
        </table>
      </form>
    </li>
    </ul>
  </div>
</div>
```
when running with 1.8.15 this part is completely gone due to changes in the page layout and search possibilities.

I think the problem has been solved in the mean time.
