### ISSUE TITLE
Unable to hide navigation tabs in HTML output (Origin: bugzilla #567208)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3222]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.5.8* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-01-09 23:12:16 +0000, Kevin Canney wrote:

    I've used the DoxygenLayout.xml file to attempt to turn off navigation tabs
    when generating HTML, but I'm still seeing some tabs in my output.
    
    An excerpt from my layout file follows this description.
    
    On every page, I still have a tab that links back to the project's main page
    (changing the title in the XML file works, but setting the visible attribute
    to no does not hide the tab).
    
    On some pages, I have tabs for showing All/Functions/Variables as well as
    alphabetical tabs. I'm not sure whether this is the same issue as the
    previous or if I need to add more tab types to the XML file for those tab
    types.
    
    
      <navindex>
        <tab type="mainpage" visible="no" title=""/>
        <tab type="pages" visible="no" title=""/>
        <tab type="modules" visible="no" title=""/>
        <tab type="namespaces" visible="no" title="">
          <tab type="namespaces" visible="no" title=""/>
          <tab type="namespacemembers" visible="no" title=""/>
        </tab>
        <tab type="classes" visible="no" title="">
          <tab type="classes" visible="no" title=""/>
          <tab type="classindex" visible="no" title=""/> 
          <tab type="hierarchy" visible="no" title=""/>
          <tab type="classmembers" visible="no" title=""/>
        </tab>
        <tab type="files" visible="no" title="">
          <tab type="files" visible="no" title=""/>
          <tab type="globals" visible="no" title=""/>
        </tab>
        <tab type="dirs" visible="no" title=""/>
        <tab type="examples" visible="no" title=""/>  
      </navindex>

**Comment by albert-github** [comment]
With doxygen version 1.5.8 I see that the tab "main page" is still present, with version 1.8.16 this tab is gone as well.

I think the problem has been solved in the mean time.
