### ISSUE TITLE
dvips behaves differnetly on Win32 and *nix (Origin: bugzilla #567622)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3233]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.8* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-01-13 16:29:16 +0000, Robert Szerwinski wrote:

    When using latex to create formula output for html, only the first page of
    the generated DVI file can be accessed by the Win32 version (v5.96,
    TeXLive2007) of dvips.
    All other pages will raise the following error: "dvips: ! DVI file contains
    unexpected Omega command (121)".
    
    This seems to be due to an incompatibility of Win32 dvips and the *nix
    version, cf. for instance http://www.tug.org/pipermail/tex-
    live/2007-November/015137.html.
    Both proposed solutions:
      (1) add the -noomega0 switch
      (2) use odvips instead of dvips
    fix the problem, but I cannot confirm whether this won't break *nix dvips.
    
    Proposal: make the name of the dvips tool configurable (seems to be used in
    formula.cpp), and try to auto-detect it from the platform if not configured.

**Comment by albert-github** [comment]
I never encountered the problem on Windows and there are no futher reports on it. Also seen the discussion on the tug platform I think the problem has been solved in the more recent distributions of TexLive. 

I think the problem is / wasn't a doxygen problem.
Problem has been solved in the mean time,
