### ISSUE TITLE
anonymous member groups inherit membership in last named member group declared (Origin: bugzilla #568855)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3245]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.8* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[foo.h](https://sourceforge.net/projects/doxygen/files/attachments/bug568855_127097_foo.h/download/download)_ (ID 127097)

On 2009-01-23 15:17:12 +0000, simon80@gmail.com wrote:

    Please describe the problem:
    The following code illustrates the breakage:
    
    /** A class. Details */
    class Test
    {
      public:
        /** \name Named group */
        //@{
        void func1InGroup1();
        void func2InGroup1();
        //@}
    
        //@{
        /** Same documentation for both members. Details */
        void func1InGroup2();
        void func2InGroup2();
        //@}
    
        /** \name Another named group */
        //@{
        void func1InGroup3();
        void func2InGroup3();
        //@}
    };
    
    /** Another class. Details */
    class Test2
    {
      protected:
        //@{
        /** Same documentation for both members. Details */
        void func1InGroup4();
        void func2InGroup4();
        //@}
    };
    
    Steps to reproduce:
    1. Paste the above code into a .h file
    2. Run Doxygen file.h
    3. View the HTML docs
    
    Actual results:
    Observe that the unnamed groups inherit the name of the last named group,
    even if they're in a different class. Also, "Same documentation for both
    members" doesn't appear on both members
    
    Expected results:
    The behaviour advertised in
    http://www.stack.nl/~dimitri/doxygen/grouping.html#memgroup should be
    followed, with no unexpected side effects that don't make sense.
    
    Does this happen every time?
    Yes
    
    Other information:

On 2009-01-23 15:18:39 +0000, simon80@gmail.com wrote:

    Created attachment 127097
    An attachment of the example code

**Comment by albert-github** [comment]
I think the problem is caused by the fact that the grouping isn't done correctly.
Doxygen did accept in the past `//@{` / `//@}` as grouping but these are in fact non doxygen comments and should be ignored. The results are according to what is expected when using `///@{` / `///@}`.

I think the problem is usage.
