### ISSUE TITLE
\a command doesn't warn when you reference non-existing argument names (Origin: bugzilla #568968)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3247]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.5.7.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-01-24 11:51:27 +0000, Francesco Montorsi wrote:

    When using the special command \a passing a wrong argument name, no warnings
    are generated, but they should as otherwise in the generated docs users may
    found references to unexisting argument names and the description of the
    function may result incomprehensible.
    
    Example:
    
    /** A Test class.
     *  More details about this class.
     */
    class Test
    {
      public:
        /** An example member function.
         *  More details about this function. The \a argh is dummy.
         */
        void example(int arg);
    };
    
    (in the example above the argument name is 'arg' but in \a 'argh' was
    passed)

**Comment by albert-github** [comment]
In the manual it says:

> 24.130 \a \<word\>
> Displays the argument \<word\> in italics. Use this command to emphasize words. Use this command to refer to
> member arguments in the running text.
> Example:
> ... the \a x and \a y coordinates are used to ...
> This will result in the following text:
> ... the <em>x</em> and <em>y</em> coordinates are used to ...
> Equivalent to \e and \em. To emphasize multiple words use \<em\>multiple words\</em\>.

I think the confusing part is here "Displays the argument \<word\> in italics." where "argument" is not meant as "argument" in the sense of a function argument but as an argument to the `\a` command. From the "To emphasize multiple words..." it is just another way for e.g. `\e`.

I think it is usage / interpretation.
