### ISSUE TITLE
\\\< does not work for php constants (Origin: bugzilla #570798)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3258]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.8* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-02-06 16:12:28 +0000, Jaroslav Fojtik wrote:

    \\\< does not work for php contants
    
    
    This is a file that demonstrates a bug:
    <?php
    @file
    Test doxy bug.
    
    define('aDAVOLT_k', (-(1<<14)) ); ///< AD5663 voltage to binary linear
    transform
    define('aDAVOLT_q', (1<<15) );  ///< AD5663 voltage to binary linear
    transform
    
    function testTCTMController()
    {
        $result = msg_send(1);
    }
    
    ?>
    
    
    And this is unexpected result:
    
    Enumerations
    enum  	aDAVOLT_k
    enum  	aDAVOLT_q
     	< AD5663 voltage to binary linear transform More...
    
    Functions
     	testTCTMController ()
     	< AD5663 voltage to binary linear transform

On 2011-11-22 01:30:34 +0000, Clancy Hood wrote:

    I confirm this is still a problem in 1.7.5.1 for class variables
    
    namespace foo{
    
      class bar{
    
        var $baz; ///< baz is a british endearment for people called Barry
        var $tux; ///< tux is a daft name for a penguin
    
      }
    
    }
    
    
    expected:
    ========
    
    Public Attributes;
    
      $baz
      baz is a british endearment for people called Barry
    
      $tux
      tux is a daft name for a penguin
    
    
    actual result:
    =============
    
    Public Attributes;
    
      $baz
    
      $tux
      < baz is a british endearment for people called Barry
    
    
    OS: Ubuntu 10.10

On 2011-11-22 18:38:10 +0000, Dimitri van Heesch wrote:

    Hi Clancy,
    
    While the original bug report still holds, your example works fine for me.
    Can you attach a self-contained example (source+config file) that
    demonstrates the problem?

On 2011-11-22 19:14:28 +0000, Clancy Hood wrote:

    Dimitri - I am so sorry, it seems I can't get it to break now. I've just
    tried moving the comments in a file and the output is fine.
    
    I've just documented an entire project avoiding putting doxy tags after the
    declaration because I found exactly the problem described in the bug early
    on in my efforts, and was convinced it was class var declarations that
    broke. However, exactly which file it was in I forget, and having proved it
    to work on var declarations no longer trust my memory - perhaps it was a
    define block after all.
    
    Sorry for confirming without running the code myself. I'll carry on trying
    doc blocks after member declarations and if it breaks and is not define()
    will post it here.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7297

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.17.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
