### ISSUE TITLE
C++: Incorrect constructor's throw() tag parsing (Origin: bugzilla #571537)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3271]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.8* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-02-12 20:39:59 +0000, Kriz wrote:

    Please describe the problem:
    Hello,
    
    today I got some strange warnings from Doxygen which I never got before. The
    parser didn't handle the C++ throw() tag in constructors in the correct
    manner. If the throw() tag is located in the next line below the constructor
    
    namespace Foo
    {
        class Bar
        {
            /**
             * @param  i                      The foobar value.
             * @throw  std::invalid_argument  Oops, it happened again.
             */
            Bar(int i)
            throw(std::invalid_argument);
        };
    }
    
    Doxygen warns me that it cannot find any parameter i for argument @param i
    in Foo::throw(std::invalid_argument). That is because Doxygen seems to skip
    Foo(int i). In the API docs there is only an entry like:
    
    throw(std::invalid_argument)
    ...doc text...
    
    If the throw() tag is located behind the constructor in the same line
    
    namespace Foo
    {
        class Bar
        {
            /**
             * @param  i                      The foobar value.
             * @throw  std::invalid_argument  Oops, it happened again.
             */
            Bar(int i) throw(std::invalid_argument);
        };
    }
    
    everything is alright with correct output in the API docs. This seems to be
    very strange because the first code example did always work before in
    previous versions of Doxygen. And... only constructors are affected, methods
    aren't.
    
    Here the original log from Doxygen:
    
    H:/CBPro/khlwad.cpp:61: Warning: no matching class member found for
      WAD(const std::string &name)
    Possible candidates:
      WAD::WAD()
      WAD::WAD(const Textures &tex)
      WAD::WAD(const std::string &name, const Textures &tex)
      WAD::WAD(const WAD &wad)
    H:/CBPro/khlwad.hpp:62: Warning: argument 'name' of command @param is not
    found in the argument list of WAD::throw(InvalidArgument)
    
    The four candidates do have their throw() tag in line and the complained one
    in the next line.
    
    Steps to reproduce:
    1. Try to implement something similar in C++ and run Doxygen.
    
    Actual results:
    
    
    Expected results:
    
    
    Does this happen every time?
    Yes.
    
    Other information:

On 2009-02-12 22:06:06 +0000, Kriz wrote:

    Hm... It seems that Doxygen has big problems with the class name "WAD".
    After I've changed it to "Foobar" everything was alright. Changing it back
    to something else like "PAX" let the bugs come out again. Then I changed the
    class name to "Vox" (no 3 uppercase letters) and Doxygen took it without any
    comments.
    
    So maybe Doxygen doesn't like 3 uppercase letters as identifiers? But why?

On 2009-02-12 22:13:37 +0000, Kriz wrote:

    Ok, tried out "WAd" (2 uppercase and 1 lowercase letter): Works fine, too.

**Comment by albert-github** [comment]
The problem here is the so called `SKIP_FUNCTION_MACROS`:
> `SKIP_FUNCTION_MACROS` If the `SKIP_FUNCTION_MACROS` tag is set to `YES` then doxygen's preprocessor
will remove all references to function-like macros that are alone on a line, have an all uppercase name, and
do not end with a semicolon. Such function macros are typically used for boiler-plate code, and will confuse
the parser if not removed.
The default value is: `YES`.

In the above case we have 
```
        BAR(int i)
        throw(std::invalid_argument);
```
this constitutes the requirements for `SKIP_FUNCTION_MACROS=YES` as set by default and the resulting problem. By changing the case of the routine / class or by setting `SKIP_FUNCTION_MACROS=NO` the problem can be solved.

I think the problem is usage.
