### ISSUE TITLE
Support underlining text (Origin: bugzilla #571986)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3275]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.5.7* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-02-16 12:51:18 +0000, Frans Englich wrote:

    It would be useful if doxygen supported underlining text. That is, something
    along \u word, perhaps something similar in HTML so multiple words can
    easily be marked. Note that <u>, is deprecated in HTML.

**Comment by albert-github** [comment]
In issue "Bug 667993 - HTML tags <u> and </u> not supported" (#4529) a similar request was made.
This has been implemented in #6384 and the code has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
