### ISSUE TITLE
brief documentation is not being extracted correctly (Origin: bugzilla #572010)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3278]
status NEW severity *normal* in component *documentation* for *---*
Reported in version *1.5.7.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-02-16 14:43:14 +0000, Oren Ben Simhon wrote:

    Please describe the problem:
    In the following code the brief documentation is not extracted:
    
    /** \ingroup Constraints*/ /**@{*/   
       //! This test constrains most, but not all, of the tag and set bits. 
     /*! 
     * I'm not exactly sure what the purpose of this test, but I'm assuming it 
     * is to reduce the set and tag space to create more evictions. 
     * 
     * Disable this on victim_request because that forces 
     * address[10:5] to match DU_addr[10:5] which can conflict with
    L2WayTest[10:9].
     * 
     * Disable on l2_cacheable_miss because the L2 set is specified and may
    conflict.
     * 
     * Disable on l2_tag_read_space so aren't always reading same l2 tag. 
     * 
     * @todo I think that this test is most obsolete because of the improved L2 
     * address generation that was introduced in v3. 
     */ 
    public: void L2WayTest_constraint () {    
    ...
    } /** @} */
    
    Steps to reproduce:
    
    /** \ingroup Constraints*/ /**@{*/   
       //! This test constrains most, but not all, of the tag and set bits. 
     /*! 
     * I'm not exactly sure what the purpose of this test, but I'm assuming it 
     * is to reduce the set and tag space to create more evictions. 
     * 
     * Disable this on victim_request because that forces 
     * address[10:5] to match DU_addr[10:5] which can conflict with
    L2WayTest[10:9].
     * 
     * Disable on l2_cacheable_miss because the L2 set is specified and may
    conflict.
     * 
     * Disable on l2_tag_read_space so aren't always reading same l2 tag. 
     * 
     * @todo I think that this test is most obsolete because of the improved L2 
     * address generation that was introduced in v3. 
     */ 
    public: void L2WayTest_constraint () {    
    ...
    } /** @} */
    
    Actual results:
    no brief documentation
    
    Expected results:
    brief documentation
    
    Does this happen every time?
    yes
    
    Other information:

**Comment by albert-github** [comment]
I think the problem here looks like a combination of usage and solved in the mean time.
The usage part in the example is the `public:`, indicating that it should e in a class (I assume this is C++ or is it another language?).

With version 1.8.16 after adding the `class` around the methods I do see all the documentation.
