### ISSUE TITLE
Better MAKEFILE support - doxygen may return 'errorlevel' result codes? (Origin: bugzilla #572043)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3281]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.5.8* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-02-16 17:30:58 +0000, Mai-Kee Reiss wrote:

    Stopping MAKE or script files when encountering an doxygen error would be
    very, very helpful. Not only for automated release build processes.
    
    With "doxygen errorlevel", I'm meaning adding return codes to doxygen's
    main() function
    
    I would like to see:
    0 = all went fine
    1 = there where some warnings about the parsed input
    2 = there where some errors about the parsed input
    3 = there where some errors in doxygen, configuration or environment
    
    And one configurable option to set/unset the reporting of return code 1.
    STOP_ON_WARNINGS = NO 
    as default preset.

**Comment by albert-github** [comment]
The handling of the exit codes has improved in time and as of doxygen version 1.8.11 (December 30, 2015) the setting `WARN_AS_ERROR` exists. In version 1.9.0 this setting has been extended by the possibility `FAIL_ON_WARNINGS`.
Note: in name there are errors and warnings coming from doxygen but, in most cases, this is just in the name and doxygen handles them similar 

From the current documentation (1.9.1):
>WARN_AS_ERROR
> If the WARN_AS_ERROR tag is set to YES then doxygen will immediately stop when a warning
is encountered. If the WARN_AS_ERROR tag is set to FAIL_ON_WARNINGS then doxygen will continue
running as if WARN_AS_ERROR tag is set to NO, but at the end of the doxygen process doxygen will return
with a non-zero status.
>
> Possible values are: NO, YES and FAIL_ON_WARNINGS.
>
> The default value is: NO.

I think this enhancement request has been solved in the mean time.
