### ISSUE TITLE
No paragraph break after moving detaileddescription to top of layout (Origin: bugzilla #572339)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3283]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.5.8* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-02-18 23:06:38 +0000, Gail wrote:

    I just upgraged to 1.5.8 and learned DETAILS_AT_TOP was gone.
    
    My docs must have details at the top, so I moved all the detaileddescription
    XML tags to the top of the page for their sections. (all of them)
    
    As a result, now when I generate the docs, the detail show up just fine at
    the top of the page, but there is NO LINE BREAK before the next item in the
    output. The end of the detail description has no paragraph break and the
    beginning of the next item appears concatenated to it, specifically the
    #includes.
    
    So what should look like this:
    
    This driver supports operations like rotation, color conversion, and gamma
    correction.
    
    #include "init.h"
    #include "color.h" 
    
    Instead looks like this:
    
    This driver supports operations like rotation, color conversion, and gamma
    correction. #include "init.h"
    #include "color.h" 
    
    I tried adding <br \> after the detaileddescription tag, but it caused an
    error and this did not work.
    
    Would you please send me a workaround right away, so I don't have to revert
    to earlier doxygen releases to ship my docs. Thanks!

**Comment by albert-github** [comment]
With the version 1.5.6 the `DETAILS_AT_TOP` works, with 1.5.8 and the modified `DoxygenLayout.xml` so that the `detaileddescription` is before `briefdescription` the we see the problem as indicated. With version 1.9.1 this problem is gone.

I think the problem has been solved in the mean time.

Use test file
```
/// \file
/// The brief description.
///
/// The detailed description.

#include "inc1.h"
#include "inc2.h"
```

I think the problem has been solved in the mean time.
