### ISSUE TITLE
@dontinclude et al: support excluding the markers (Origin: bugzilla #572389)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3285]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.5.8* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-02-19 09:52:29 +0000, Frans Englich wrote:

    It would be useful with a mechanism for including code, without the markers
    that signal the start and end of the snippet.
    
    Consider this example file:
    
    random content
    // MARKER
    this
    should
    be included
    // MARKER
    random content
    // MARKER_B
    this
    should
    be included
    // MARKER_B
    random content
    
    The closest I get with existing doxygen is:
    
    Â * @dontinclude include.h
    Â * @skipline MARKER
    Â * @until MARKER
    
    Although they avoid the random content before and after, it includes the 
    markers.
    
    I'm essentially looking for an alias which allows one to do: \snippet 
    {includeFile, marker}, and then it includes the stuff in-between the marker 
    from the include file.)
    
    See mail "@dontinclude: avoiding markers to be included", 2009-02-16, by
    Frans Englich, on mailing list doxygen-users.

**Comment by albert-github** [comment]
In the 1.7.5 version of doxygen the `\snippet` command is introduced (August 14, 2011).
I think this solves the situation that is described here.

So I think the problem has been solved in the mean time.
