### ISSUE TITLE
paragraph merging of brief and author (Origin: bugzilla #572820)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3296]
status NEW severity *minor* in component *general* for *---*
Reported in version *1.5.8* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-02-23 08:08:17 +0000, Daniel wrote:

    Please describe the problem:
    In Doxygen 1.5.8, the paragraph of a brief command is merged with the
    paragraph of a preceding author command. This was not yet the case in
    Doxygen 1.5.4.
    
    Steps to reproduce:
    Compile the following code snippet:
    --cut--
    /**
    * @defgroup RAYGUN Ray Gun
    * @author James Bond
    * @brief This thing is the coolest gadget you can imagine
    *
    * The Ray Gun is one of my favourite tools.
    * Mainly because nobody else has one
    */
    --cut--
    
    Actual results:
    It creates output with an author section that reads as follows:
    --cut--
    Author:
    James Bond The Ray Gun is one of my favourite tools. Mainly because nobody
    else has one
    --cut--
    
    Expected results:
    The author section should be limited to what is contained in the author
    paragraph.
    
    Does this happen every time?
    Yes
    
    Other information:

On 2009-09-15 15:09:31 +0000, MÃ¡rton NÃ©meth wrote:

    This problem also happens with Doxygen 1.6.1 with the following fragment:
    --cut--
    //! @date       2009-09-15
    //! @author     John Smith
    //!
    //
    **************************************************************************
    //! @file
    //! @brief Short description of this file.
    //!
    //! A detailed description of this file.
    --cut--
    
    Actual result:
    --cut--
    Author:
      John Smith A detailed description of this file. 
    --cut--
    
    
    If the line with the stars is deleted then the output is correct. Here is
    the code fragment which is working correctly:
    --cut--
    //! @date       2009-09-15
    //! @author     John Smith
    //!
    //! @file
    //! @brief Short description of this file.
    //!
    //! A detailed description of this file.
    --cut--

**Comment by albert-github** [comment]
With the version 1.8.7 I was still able to reproduce the problem as described. With the version 1.9.0 the problem was gone.

I think the problem has been solved in the mean time.
