### ISSUE TITLE
Call graph C++ static class method mix (Origin: bugzilla #573993)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3308]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.8* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-03-03 22:38:09 +0000, Jacquelin Potier wrote:

    The following example will fail
    
    Class B
    {
    public:
       static void Show() { };
    }
    
    Class A
    {
    public:
       static void Show() { };
       void f1 (){A::Show();};
       void f2 (){B::Show();};
    }
    
    The generated call graph makes f1 and f2 point to the same Show function;
    although this is 2 different methods in different classes

On 2010-02-19 15:17:04 +0000, maaltan wrote:

    This sounds similar to my issue recorded in bug # 582350

**Comment by albert-github** [comment]
With the 1.5.8 version I see the behavior as described.
When testing the example with doxygen version 1.9.1 all the references are OK.

I think the problem has been solved in the mean time.
