### ISSUE TITLE
Links are missing to these header files whose path case differs from the path case of the INPUT variable (Origin: bugzilla #574946)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3320]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.8* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[Bug574946_IncludeCase_sample.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug574946_130463_Bug574946_IncludeCase_sample.zip/download/download)_ (ID 130463)

On 2009-03-11 14:20:28 +0000, Bartosz BieÅ wrote:

    Please describe the problem:
    I have the following files:
    
    D:/projects/doc/test/kernel/include1.h
    D:/projects/doc/test/kernel/include2.h
    D:/projects/doc/test/app/main.cpp
    D:/projects/doc/test/app/alt.cpp
    
    In main.cpp, there is #include "kernel/include1.h" statement.
    In alt.cpp, there is #include "Kernel/include1.h" statement (uppercase 'K').
    
    The doxyfile is as follows:
    
    DOXYFILE_ENCODING      = UTF-8
    PROJECT_NAME           = Test
    PROJECT_NUMBER         = 090305
    OUTPUT_DIRECTORY       = D:/projects/doc/out_test
    CREATE_SUBDIRS         = YES
    
    FULL_PATH_NAMES        = YES
    STRIP_FROM_PATH        = D:/projects/doc/test
    
    EXTRACT_ALL            = YES
    CASE_SENSE_NAMES       = YES
    HIDE_SCOPE_NAMES       = NO
    SHOW_INCLUDE_FILES     = YES
    
    INPUT                  = D:/projects/doc/test/app
    D:/projects/doc/test/kernel
    
    REFERENCED_BY_RELATION = YES
    REFERENCES_RELATION    = YES
    REFERENCES_LINK_SOURCE = NO
    
    CLASS_DIAGRAMS         = YES
    HAVE_DOT               = YES
    CLASS_GRAPH            = YES
    COLLABORATION_GRAPH    = YES
    INCLUDE_GRAPH          = YES
    INCLUDED_BY_GRAPH      = YES
    CALL_GRAPH             = NO
    CALLER_GRAPH           = YES
    GRAPHICAL_HIERARCHY    = NO
    DIRECTORY_GRAPH        = YES
    
    GENERATE_LATEX         = NO
    
    Steps to reproduce:
    See the above description.
    
    Actual results:
    There is no link to "Kernel/include1.h" - neither in #include statements,
    nor in the include graph on the File Reference page for alt.cpp.
    
    Expected results:
    Link to the "Kernel/include1.h" has to be generated and set to the same
    value as "kernel/include1.h" in the other file.
    
    Does this happen every time?
    Yes, and of course with larger projects as well.
    
    Other information:
    This only influences the directory part. If I #include "kernel/Include1.h"
    (uppercase 'I') in alt.cpp, everything is correct.

On 2009-03-11 14:22:40 +0000, Bartosz BieÅ wrote:

    Created attachment 130463
    Files needed to reproduce the bug.

On 2009-03-11 14:26:00 +0000, Bartosz BieÅ wrote:

    BTW, my platform is PC / Windows XP Home SP3.

**Comment by albert-github** [comment]
The problem here has to do with the `kernel` versus `Kernel` directory name on windows there is no distinction between these 2 names and they point to the same directory on *nix this is not the case.

In version 1.5.8 (on windows) the indicated link is not present, in version 1.8.14 the link is present.

I think the problem has been solved in the mean time.
