### ISSUE TITLE
Code in Method Not Displayed (Origin: bugzilla #575116)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3322]
status NEW severity *major* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-03-12 17:46:54 +0000, Kent Eschenberg wrote:

    When a detailed comment is provided for a C++ method in the header file then
    the comments in the body of the method in the code file is not shown by
    DOxygen. Otherwise it is. Here's a simple test case:
    
    app.hh:
    class myclass{
    /// method1: header file, comment line 1
    /// method2: header file, comment line 2
    int method1(void);
    int method1(void);
    }
    
    app.cc:
    int myclass::method1(void){
    /// method1: code file, comment in code
       i = 1; return(i);}
    int myclass::method2(void){
    /// method2: code file, comment in code
       i = 1; return(i);}
    
    In the html page produced by DOxygen for this class I see something like
    this:
    
       int myclass::method1( void )[private]
       method1: header file, comment line 1 method1: header file, comment line 2
    
       int myclass::method2( void )[private]
       method2: code file, comment in code
    
    HIDE_IN_BODY_DOCS is set to NO so I would expect that ALL in body
    documentation is shown no matter where the method's detailed documentation
    is given.
    
    The missing comments did not appear when I added comments before the method
    in the code file.

On 2009-03-13 15:12:52 +0000, Kent Eschenberg wrote:

    Typo: the second comment in app.hh should be:
    // method1: header file, comment line 2
    
    That is, there are two lines of comments for method1 and none for method2.
    Those 2 lines will be considered a "detailed description" and this triggers
    the bug. If there was instead only 1 line of comment for method1 it would be
    considered a "brief description" and that doesn't trigger the bug.

**Comment by albert-github** [comment]
With versions 1.4.7 and 1.5.8 I could not really reproduce the problem (I didn't see anything, even when setting `EXTRACT_PRIVATE=YES`). With version 1.8.18 I see all the documentation as expected.

I think the problem has been solved in the mean time.
