### ISSUE TITLE
manonly-sections should strip space after â*â (Origin: bugzilla #575246)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3325]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.8* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-03-13 13:07:26 +0000, gnome@oss.m-berberich.de wrote:

    At the moment in a manonly-section (\manonly â¦ \endmanonly) spaces after
    leading â*â are not striped, so in
    
    /**
     * @manonly
     * bla
     * @endmanonly
     */
    
    gives 
    
     bla
    
    with a leading space in the manpage. This is fatal, as most nroff/troff-
    commands are of the form â.[COMMAND]â and the â.â has to be in the
    first column.

**Comment by albert-github** [comment]
I tried the problem qwith 1.5.8 but here I got:
```
Warning: reached end of file while inside a manonly block!
The command that should end the block seems to be missing!
```
this is fixed in 1.5.9 and with this version I can reproduce the problem with the following code:
```
/** \file
 * \brief The brief of the file
 *
 * @manonly
 * bla
 * @endmanonly
 *
 * Other text
 */

/**
 * \brief The brief of the function
 */
void fie(void);
```
When running the code with 1.8.16 the problem does not occur (actually as of 1.8.1/2).

I think the problem has been solved in the mean time.
