### ISSUE TITLE
wrong documentation generation for template classes (Origin: bugzilla #576770)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3337]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.8* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxygen-bug-576770.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug576770_131382_doxygen-bug-576770.zip/download/download)_ (ID 131382)

On 2009-03-25 21:18:47 +0000, Alexey Semenyuk wrote:

    Use doxygen 1.5.8 on Windows Vista. Input that confuses doxygen:
    ---
    template <class T>
    class A : public T
    {
    };
    
    template <class T>
    class B : public A<T>
    {
    };
    ---
    
    Interesting part of doxygen log output:
    ---
    Generating member index...
    Generating docs for compound A...
    Generating docs for compound B...
    Generating docs for compound T...
    Generating namespace index...
    ---
    
    The bug is that doxygen generates documentation for T type while it
    shouldn't.
    
    doxygen properly handles the following slightly modified sources:
    ---
    template <class T>
    class A : public T
    {
    };
    
    template <class T>
    class B
    {
    };
    ---
    and this is OK as well:
    ---
    template <class T>
    class A
    {
    };
    
    template <class T>
    class B : public A<T>
    {
    };
    ---
    For both OK versions of input doxygen produces expected log output:
    ---
    Generating member index...
    Generating docs for compound A...
    Generating docs for compound B...
    Generating namespace index...
    Generating namespace member index...
    ---
    i.e. doxygen doesn't generate documentation for T template parameter.

On 2009-03-25 21:29:17 +0000, Alexey Semenyuk wrote:

    Created attachment 131382
    test case
    
    test case to reproduce issue. Detailed archive contents description:
     - doxyfile.txt: Doxygen configuration to run test case and reproduce bug;
     - sample-bug.h: source file that confuses Doxygen;
     - sample-ok2.h: source file that doesn't confuse Doxygen;
     - sample-ok.h: source file that doesn't confuse Doxygen;
     - html/ - bug output that Doxygen produces for the sample-bug.h source file
    when executed with doxyfile.txt from this archive.

On 2009-05-25 16:46:25 +0000, Alexey Semenyuk wrote:

    still the case with Doxygen 1.5.9

**Comment by albert-github** [comment]
With version 1.5.8 the `<T>` is being documented  in doxygen
in version 1.8.14 this is not the case

I think the problem has been solved in the mean time
