### ISSUE TITLE
Dot graph for multiple inheritance of struct gives private inheritance for second base (Origin: bugzilla #577359)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3343]
status NEW severity *minor* in component *general* for *---*
Reported in version *1.5.6* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-03-30 20:26:56 +0000, Adam H Peterson wrote:

    Please describe the problem:
    When using Doxygen to document the class hierarchy below and to produce an
    inheritance diagram, the diagram mistakenly labels B as a private base of C
    (although it is a public base):
    
    struct A { };
    struct B { };
    struct C : A, B { };
    
    Steps to reproduce:
    1. Create a .cpp file with the above three struct definitions.
    2. Configure Doxygen to produce an inheritance diagram with Dot.
    3. Generate documentation.
    
    
    Actual results:
    The inheritance diagram shows C publicly inheriting from A (correct), and
    privately inheriting from B (incorrect).`
    
    Expected results:
    C should be shown to publicly inherit from both bases.
    
    Does this happen every time?
    Yes
    
    Other information:

**Comment by albert-github** [comment]
With the 1.5.6 version we see the wrong inheritance as explained in the the issue.
With the 1.9.1 version the both inheritance are public inheritances.

I think the problem has been solved in the mean time.
