### ISSUE TITLE
Global Enumeration Not Auto Linked in html files (Origin: bugzilla #577383)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3344]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.5.8* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-03-31 00:46:38 +0000, Ann Bui wrote:

    Please describe the problem:
    When documenting a global enumeration, doxygen creates a proper entry.
    However, if html file that refers to the documentation and then is
    doxygenated, the resulting html file does not automatically link to the the
    enumeration in regular documentation.  However oddly enough, doxygen
    recognizes the global enumeration in the same file's sample code block and
    links it.
    
    Steps to reproduce:
    1. Create a test.h file.  Copy the example provided in the doxygen
    documentation at http://www.stack.nl/~dimitri/doxygen/autolink.html
    beginning where class Test is defined to the end of the example.
    2. Run doxygen on test.h with configuration for it to create a tag file.
    3. Create a test.html file.  Copy the example provided in the doxygen
    documentation at
    http://www.stack.nl/~dimitri/doxygen/autolink.html with section starting
    with Testing automatic link generation.  Also add the following text:
    
    \code
      	GlobEnum myEnum = MyStandAloneFunction();
    	
    \endcode
    
    4. Run doxygen on this test.html file with a reference to the created tag
    file in step 2.  The doxgenated test.html file will have automatic links for
    everything except GlobEnum, GVal2 and ABS(x).  However, in the sample code
    area, GlobEnum will be automatically linked.
    
    Actual results:
    The global enumeration is not automatically linked in the regular html but
    linked in sample code.
    
    Expected results:
    Global Enumeration is automatically linked in the regular html and linked in
    sample code.
    
    Does this happen every time?
    Yes
    
    Other information:
    Dear Dmitri, if you would like to send you the samples that show this
    scenario, please let me know.  I will zip them up and send them to you.
    Thanks.  Ann

**Comment by albert-github** [comment]
I tested the problem with version 1.5.8 and the problems as indicated are present (note the class has been renamed in the mean time to Autolink_Test).
In version 1.8.14 all the mentioned links were present.

I think the problem has been solved in the mean time.
