### ISSUE TITLE
using @defgroup and @ingroup clutters documentation (Origin: bugzilla #577707)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3348]
status NEW severity *minor* in component *general* for *---*
Reported in version *1.5.8* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-04-02 11:20:52 +0000, Paul Schwann wrote:

    Please describe the problem:
    If I use 
    
    @defgroup X 
    @{
    ..
    @}
    
    in a .h and 
    
    @ingroup X
    @{
    ..
    @}
    
    in a source file, the resulting module documentation page (HTML) is
    cluttering functions, enumerations, variables a.s.o. of that module.
    
    Steps to reproduce:
    1. 
    2. 
    3. 
    
    
    Actual results:
    
    
    Expected results:
    
    
    Does this happen every time?
    
    
    Other information:
    Everything works fine if I use 
    
    @addtogroup X
    @{
    ...
    @}
    
    instead of @defgroup/@ingroup

**Comment by albert-github** [comment]
It is unclear what teh user means by "cluttering functions, enumerations, variables a.s.o. of that module" and due to a missing proper example not possible to reproduce.

Setting the issue to incomplete.
