### ISSUE TITLE
Merging of consecutive repeated commands creates poorly-structured HTML (Origin: bugzilla #579628)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3361]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.8* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[dl-compact-b.patch](https://sourceforge.net/projects/doxygen/files/attachments/bug579628_132977_dl-compact-b.patch/download/download)_ (ID 132977)

On 2009-04-20 17:30:12 +0000, Quinn Taylor wrote:

    Many Doxygen commands (including \author, \see, \attention, \warning, \bug,
    \todo, etc.) are automatically merged into a single section when they appear
    multiple times consecutively. However, the HTML which results from the merge
    is arguably poorly structured, especially when custom CSS styling is
    desired.
    
    For example, the following commenting:
    
    @author Ted
    @author Fred
    @author Jed
    
    generates the following HTML:
    
    <dl class="author" compact><dt><b>Author:</b></dt><dd>Ted <p>
    Fred <p>
    Jed </dd></dl>
    
    but should generate the following:
    
    <dl
    class="author"><dt>Author:</dt><dd>Ted</dd><dd>Fred</dd><dd>Jed</dd></dl>
    
    There are a few key differences, and several reasons why the change would be
    nice:
    
    1) The nested `<p>` tags for each additional value after the first one make
    it difficult to style individual entries, among other reasons because `<p>`
    tags can have their own styling and make the first entry look different.
    
    2) Consecutive `<dd>` tags is also more semantically correct, and `<p>`
    inside `<dt>` is not valid in XHTML (looking forward, hopefully), especially
    with unclosed `<p>` tags.
    
    3) The "compact" attribute is deprecated for `<ol>` and `<ul>`, and doesn't
    seem to exist for `<dl>` elements. This applies to other occurrences of
    `<dt>` as well.
    
    4) Hard-coded `<b>` tags complicate styling the `<dt>` elements in a
    different way. It would be preferable to have a CSS rule that makes all
    `<dt>` tags bolded.

On 2009-04-20 18:44:52 +0000, Quinn Taylor wrote:

    Created attachment 132977
    Remove `<dl>`"compact" attribute and `<b>` tags within `<dt>`, plus CSS fix.

On 2009-04-20 18:45:27 +0000, Quinn Taylor wrote:

    WRT the "compact" attribute, while some browsers do actually support it
    (although none handle the display:compact CSS property correctly) it seems
    undesirable to compact `<dl>` entries, especially since several commands
    create distinct `<dl>` blocks, so the `<dd>` tags wouldn't line up
    correctly, diminishing readability. IMHO, getting rid of compact altogether
    would be more consistent.
    
    Attached is a patch to handle points 3 and 4 above. I haven't been able to
    figure out where exactly the nested `<p>` tags are generated.

**Comment by albert-github** [comment]
Most issues from this report were already implemented.
Regarding the rest: I've just pushed a proposed patch, pull request #6402

**Comment by albert-github** [comment]
Code has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
