### ISSUE TITLE
Taking advantage of multicore arch (Origin: bugzilla #580284)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3367]
status NEW severity *enhancement* in component *build* for *---*
Reported in version *1.5.8* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-04-26 12:29:16 +0000, Yaakov D. wrote:

    doxygen could execute dot in parallel by running it in several processes.
    This is especialy interesting since doxygen + dot is quite slow.

**Comment by cmorty** [comment]
Can't this be closed?

**Comment by albert-github** [comment]
Dot is run already in parallel since doxygen 1.7.0.

I think the problem has been solved in the mean time.
