### ISSUE TITLE
c++ header ACE_THROW_SPEC exception (Origin: bugzilla #581698)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3378]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.9* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[vhf_modul_i.h](https://sourceforge.net/projects/doxygen/files/attachments/bug581698_134171_vhf_modul_i.h/download/download)_ (ID 134171)
- _[vhf_modul_i.cpp](https://sourceforge.net/projects/doxygen/files/attachments/bug581698_134172_vhf_modul_i.cpp/download/download)_ (ID 134172)

On 2009-05-07 07:01:44 +0000, Dalibor Skrobak wrote:

    Please describe the problem:
    in c++ header file with ACE_THROW_SPEC exception :
    
      virtual void start_transmit (
        ::CORBA::ULong tx
      )
      ACE_THROW_SPEC ((
        CORBA::SystemException,
        ::art::RUNTIME
      ));
    
    when doxygen generated documentation in log was message: 
    "Warning: Found ';' while parsing initializer list! (doxygen could be
    confused by a macro call without semicolon)"
    In documentation isn't this function (start_transmit). I suppose doxygen
    doesn't parse this part of c++ header file.
    
    Steps to reproduce:
    1. use c++ header file with this exception:
    
      virtual void start_transmit (
        ::CORBA::ULong tx
      )
      ACE_THROW_SPEC ((
        CORBA::SystemException,
        ::art::RUNTIME
      ));
    
    2. generate doxygen documentation
    3. look for this function in documentation (unfortunately there are no
    function)
    
    
    Actual results:
    in documentation isn't any record of this function
    
    Expected results:
    I want to see function with ACE_THROW_SPEC exception in documentation
    
    Does this happen every time?
    yes
    
    Other information:
    when doxygen parse cpp file with define this function in log show this
    warning:
    "Warning: documented function `void art_vhf_modul_i::change_filter' was not
    declared or defined"

On 2009-05-07 07:30:39 +0000, Dalibor Skrobak wrote:

    Created attachment 134171
    c++ header file for test bug

On 2009-05-07 07:31:48 +0000, Dalibor Skrobak wrote:

    Created attachment 134172
    cpp file for test bug

**Comment by albert-github** [comment]
The `ACE_THROW_SPEC` is not an element that is mentioned, as far as I know, in a standard.
When the `ACE_THROW_SPEC` is defined as `#define ACE_THROW_SPEC(x) throw(x)` and the appropriate settings are done or the `ACE_THROW_SPEC` is `PREDEFINED` as setting (and in the `.h` file the one `ACE_THROW_SPEC` with single round brackets is corrected) there are no warnings anymore.

I think the problem is usage.
