### ISSUE TITLE
<listheader> and <item> XML commands in C# code cause problems in XML output (Origin: bugzilla #582204)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3384]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.8.2-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-05-11 17:17:28 +0000, Ray Lefuel wrote:

    Please describe the problem:
    Doxygen is supposed to support the <list type="table">, <listheader> and
    <item> XML commands, but these tags create a problem in the generated XML
    output.
    
    For example: I have created the following table in the source code comments:
    
    <list type="table">
    	<listheader>
    		<term>Column A</term>
    		<term>Column B</term>
    		<term>Column C</term>
    		<term>Column D</term> 
    	</listheader>
    	<item>
    		<term>1st A item</term>
    		<term>1st B item</term>
    		<term>1st C item</term>
    		<term>1st D item</term> 
    	</item>
    	<item>
    		<term>2nd A item</term>
    		<term>2nd B item</term>
    		<term>2nd C item</term>
    		<term>2nd D item</term> 
    	</item>
    	<item>
    		<term>3rd A item</term>
    		<term>3rd B item</term>
    		<term>3rd C item</term>
    		<term>3rd D item</term> 
    	</item>
    </list>
    
    When Doxygen generates the XML output, I get the following result:
    
    <table rows="4" cols="4"><row>
    <entry thead="yes"><para>Column A</bold> <bold></para></entry><entry
    thead="yes"><para>Column B</bold> <bold></para></entry><entry
    thead="yes"><para>Column C</bold> <bold></para></entry><entry
    thead="yes"><para>Column D</bold>  </para></entry></row>
    <row>
    <entry thead="no"><para>1st A item</bold> <bold></para></entry><entry
    thead="no"><para>1st B item</bold> <bold></para></entry><entry
    thead="no"><para>1st C item</bold> <bold></para></entry><entry
    thead="no"><para>1st D item</bold>  </para></entry></row>
    <row>
    <entry thead="no"><para>2nd A item</bold> <bold></para></entry><entry
    thead="no"><para>2nd B item</bold> <bold></para></entry><entry
    thead="no"><para>2nd C item</bold> <bold></para></entry><entry
    thead="no"><para>2nd D item</bold>  </para></entry></row>
    <row>
    <entry thead="no"><para>3rd A item</bold> <bold></para></entry><entry
    thead="no"><para>3rd B item</bold> <bold></para></entry><entry
    thead="no"><para>3rd C item</bold> <bold></para></entry><entry
    thead="no"><para>3rd D item</bold>  </para></entry></row>
    </table>
    
    In the output, the <bold> tag is used exensively and a </bold> tag is used
    first.  This causes "Opening and ending tag mismatch" errors when I use
    combine.xslt to create a single XML file.  The bold tag is not used anywhere
    else in the file.
    
    Steps to reproduce:
    1. Create a properly formatted cs file that uses the <list type="table">,
    <listheader> and <item> XML commands as stated in the description above.
    2. Generate XML output using Doxygen.
    3. Review the XML file that contains the converted XML commands.
    4. Use combine.xslt to create a single XML file.
    
    
    Actual results:
    When I use combine.xslt to create an XML file, I get multiple parser errors,
    such as the following:
    413: parser error : Opening and ending tag mismatch: para line 413 and bold
    <entry thead="yes"><para>Column A</bold> <bold></para></entry><entry
    thead="yes"
                                            ^
    413: parser error : Opening and ending tag mismatch: bold line 413 and para
    <entry thead="yes"><para>Column A</bold> <bold></para></entry><entry
    thead="yes"
                                                          ^
    413: parser error : Opening and ending tag mismatch: para line 413 and bold
    ra>Column A</bold> <bold></para></entry><entry thead="yes"><para>Column
    B</bold>
^
    413: parser error : Opening and ending tag mismatch: bold line 413 and para
    old> <bold></para></entry><entry thead="yes"><para>Column B</bold>
    <bold></para>
^
    413: parser error : Opening and ending tag mismatch: para line 413 and bold
    ra>Column B</bold> <bold></para></entry><entry thead="yes"><para>Column
    C</bold>
^
    413: parser error : Opening and ending tag mismatch: bold line 413 and para
    old> <bold></para></entry><entry thead="yes"><para>Column C</bold>
    <bold></para>
^
    413: parser error : Opening and ending tag mismatch: para line 413 and bold
    ra>Column C</bold> <bold></para></entry><entry thead="yes"><para>Column
    D</bold>
    
    ... and so on....
    
    
    Expected results:
    Doxygen should either strip all <bold> and </bold> tags from the generated
    table, or use the <bold> tags appropriately.
    
    Does this happen every time?
    Yes.  I've tried modifying the table several times (i.e. adding <b> tags,
    adding </b> tags, putting the <term> items on a single line, etc) but I
    cannot get it to format properly.
    
    Other information:
    Please let me know when a fix is available or if additional information is
    required.

On 2012-11-18 11:07:33 +0000, Dimitri van Heesch wrote:

    Changed version 'latest' to '1.8.2-SVN' so I can remove 'latest' as an
    option as it is a moving target.

**Comment by albert-github** [comment]
With version 1.6.1 ( the latest version available when submitting the issue) I can reproduce the problem.
With the current version (1.8.15) the problem is gone.

I think the problem has been solved in the mean time.
