### ISSUE TITLE
Reimplemented methods that call inherited parent implementation link to self (Origin: bugzilla #582350)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3386]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.7* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[reimp.rar](https://sourceforge.net/projects/doxygen/files/attachments/bug582350_134503_reimp.rar/download/download)_ (ID 134503)

On 2009-05-12 15:01:42 +0000, maaltan wrote:

    Please describe the problem:
    Given a class structure as follows:
    
    class parent
    {
        public:
            parent()
            {}
            ~parent()
            {}
    
            virtual int met(int A)
            {
                str = A;
                return str;
            }
        private:
            int str;
    };
    
    class ch1: public parent 
    {
        public:
            ch1()
            {}
            ~ch1()
            {}
    
        private:
            int str;
    };
    
    
    class ch2: public ch1 
    {
        public:
            ch2()
            {}
            ~ch2()
            {}
    
            virtual int met(int A)
            {
                ch1::met(A);
                str = A;
                return str;
            }
        private:
            int str;
    };
    
    
    the documention for ch2::met(int) is wrong.  the call to  "ch1::met(A);"
    links to ch2::met(int)
    
    Steps to reproduce:
    see above
    
    Actual results:
    see attached html output
    
    Expected results:
    Ch1::met(A) should link to parent::Met(int).  this worked in doxygen 1.5.2
    
    
    
    Does this happen every time?
    yes.  Possibly happens with other inheritance scenarios also, but this was
    simplest to demonstrate
    
    Other information:

On 2009-05-12 15:03:47 +0000, maaltan wrote:

    Created attachment 134503
    Contains source and generated html of test case

On 2010-02-19 15:12:33 +0000, maaltan wrote:

    This still exists in 1.6.2 and also appears to happen with any explict call
    to a method with the same name, no matter what the inheritance pattern is:
    
    
    ex:
    
    class1::Method()
    {
       class2::Method();
       class3::Method(); 
       class4::Method();
    }
    
    all the Initializes link back to class1::Method().  This is a more severe
    problem because it requires manually navigating to the documentation for
    each of the other classes to see it's Method.

On 2010-10-20 22:58:32 +0000, maaltan wrote:

    This defect was introduced in 1.5.7 in SVN revision 652.   I have not
    located the problem yet. It may have been caused by the resolution of bug
    549022 (a guess based on a comment in the new code in code.l, no basis in
    reality yet)

**Comment by albert-github** [comment]
In version 1.5.6 the `ch1::met` call (in the source code) mapped to `parent::met` as it should, in version 1.5.7 it mapped to itself i.e. `ch2::met`.
In version 1.8.15 the mapping of `ch1::met` is again to  `parent::met` as it should be.

I think the problem has been solved in the mean time.
