### ISSUE TITLE
Doxygen unable to document for functions in .cpp which have some code after function definition (Origin: bugzilla #585312)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3419]
status NEEDINFO severity *major* in component *general* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-06-10 07:12:56 +0000, ashish.agarwal@renishaw.com wrote:

    Please describe the problem:
    
    I have a .cpp file and found that doxygen is unable to document function
    which contains the following format:
    
    //! 
    //! \brief Test 
    //! and perform operations on those points. 
    
    //! void CTest::TestTri() 
    
    EH_Start("CTest::TestTri") 
    { 
    } 
    EH_Stop
    
    The EH_Start and EH_Stop are exception handling mechanisem and causing
    issues. How can we exclude those? Awaiting for an early positive reply.
    
    
    Steps to reproduce:
    files contains EH_Start* and EH_Stop just after the function start and ends.
    Doxygen is unable to document this format. Moreover if any one of the
    function have this then it wont document further function. I want to exclude
    this statement. If I remove EH_Start and EH_Stop â it works fine.
    
    
    Actual results:
    Dont have the links as well.
    
    Expected results:
    It should document for all functions
    
    Does this happen every time?
    Yes
    
    Other information:

On 2009-06-10 09:16:14 +0000, ashish.agarwal@renishaw.com wrote:

    //! 
    //! \brief Test 
    //! and perform operations on those points. 
    
    void CTest::TestTri() 
    
    EH_Start("CTest::TestTri") 
    { 
    } 
    EH_Stop
    
    
    Cosmetic modified the code....

On 2009-06-11 03:54:55 +0000, ashish.agarwal@renishaw.com wrote:

    EH_Start and EH_Stop are macros.
    I tried to enable MACRO_EXPANSION option to yes but still its not working.
    I using 1.5.8 and also tested with 1.5.9.

On 2013-12-23 19:18:09 +0000, albert wrote:

    Although it is quite a while ago that this bug report has been filed.
    
    I tried to reproduce the problem as reported in this bug report with the
    1.5.9 version of doxygen, but was not able to reproduce it as it is lacking
    a good example and I also was not able to create an example.
    
    - Is this problem still present in the current version of doxygen (1.8.5 or
    even better 1.8.5-git)?
    - if it is still present is it possible to create a small self contained
    example (source files and include files together with the used Doxyfile) and
    attach that to this bug report?

**Comment by albert-github** [comment]
Seen the lack of a good example I think this issue is incomplete / invalid.
