### ISSUE TITLE
undocumented items visible even though EXTRACT_ALL=NO (Origin: bugzilla #587416)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3438]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.9* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-06-30 11:46:46 +0000, Joachim Reichel wrote:

    Please describe the problem:
    Sometimes, undocumented items are visible even though EXTRACT_ALL=NO is set.
    This seems to happen if there is an undocumented class derived from a
    documented class.
    
    
    Steps to reproduce:
    /// class Foo, documented
    class Foo {
    };
    
    //  class Bar, undocumented
    class Bar : public Foo
    {
    };
    
    Doxyfile: default of 1.5.9 plus GENERATE_XML=YES
    
    Actual results:
    1) On the "Foo Class Reference" page I see "Inherited by Bar."
    2) If I set HAVE_DOT=YES, the inheritance diagrams shows the undocumented
    class Bar.
    3) In the XML output there is even a file classBar.xml.
    
    Expected results:
    1) 2) Since the "Bar" class itself is undocumented and does not show up in
    other places (like the Class List for example), I would expect not to see it
    in the inheritance relations as well.
    3) I would expect that there are no references to class "Bar" at all.
    
    Does this happen every time?
    Yes
    
    Other information:

**Comment by albert-github** [comment]
I think we have 2 problems here:

- the problem XML is the interpretation of the goal of the XML output. Contrary to the output formats like HTML. LaTeX, RTF, Docbook it is intended as an intermediate output format that further can be processed by the user. To give the user all flexibility doxygen does not impose all the restrictions laid out by the doxygen settings and as a result e.g. undocumented members are shown in the XML output even when EXTRACT_ALL=NO.
  An interesting proposed pull request in this matter is #8463
- the problem of the inheritance diagram in HTML, though as `class Bar` inherits from `class Foo` it can be seen as "documentation"
