### ISSUE TITLE
[xml] some items inside namespace missing in file reference pages (Origin: bugzilla #588067)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3443]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.9* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-07-08 12:43:01 +0000, Joachim Reichel wrote:

    Please describe the problem:
    Enums, typedefs, variables, and functions do not appear in the XML output
    for file reference pages if these items are inside a namespace.
    
    Steps to reproduce:
    /// \file foo.C
    
    /// enum e_Foo
    enum e_Foo { e_FOO = 1 };
    /// typedef t_Foo
    typedef int t_Foo;
    /// variable v_Foo;
    int v_Foo;
    /// function f_Foo
    void f_Foo() {}
    
    /// namespace N
    namespace N {
      /// enum e_Bar
      enum e_Bar { e_BAR = 1 };
      /// typedef t_Bar
      typedef int t_Bar;
      /// variable v_Bar;
      int v_Bar;
      /// function f_Bar
      void f_Bar() {}
    }
    
    Doxyfile: default of 1.5.9 plus GENERATE_XML=YES
    
    Actual results:
    In the HTML output for "foo.C File Reference" there are all four *_Bar
    items. In the XML file foo_8C.xml, the *_Bar items are not mentioned (apart
    from the source code listing).
    
    Expected results:
    I would expect to find them as well in foo_8C.xml (similar to classes and
    namespaces).
    
    Does this happen every time?
    Yes.
    
    Other information:

**Comment by albert-github** [comment]
Contrary to HTML / LaTeX / RTF the definition of the different '*_Bar' parts are not present on the 'File definition page' for 'foo.C'. 
On the page `xml/foo_8_c.xml` there is a reference to the 'namespace N' by means of:

```
<innernamespace refid="namespace_n">N</innernamespace>
```

and in the file `xml/namespace_n.xml` we have:
```
  <compounddef id="namespace_n" kind="namespace" language="C++">
    <compoundname>N</compoundname>
```

so it is possible to navigate to the values of the 'namespace N' and thus its members. 
From a consistency point of view one would have expected that the definitions are also in the 'File definition pages' but seen that 'xml' is a version to be 'post processed' I think it is correct not to have the data mentioned double and thus that it is an usage / interpretation problem.
