### ISSUE TITLE
order of member groups changes (Origin: bugzilla #589402)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3456]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.9* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-07-22 16:14:49 +0000, Joachim Reichel wrote:

    Please describe the problem:
    The order of member groups changes depending on the type of contained items.
    
    Steps to reproduce:
    /// Some class
    class Foo
    {
    public:
      /// \name Member group 1 does not create a subgroup
      /// Description of member group 1
      //@{
      /// Method foo1
      void foo1 () {};
    protected:
      /// Method bar1
      void bar1 () {};
      //@}
    
      /// \name Member group 2 does not create a subgroup
      /// Description of member group 2
      //@{
    public:
      /// Method foo2
      void foo2 () {};
    protected:
      /// Method bar2
      void bar2 () {};
    public:
      /// Enum Baz2
      enum Baz2 { BAZ2 };
      //@}
    };
    
    Doxyfile: default of 1.5.9 plus GENERATE_XML = YES
    
    
    Actual results:
    The order of both member groups changes when the enum is removed.
    
    Expected results:
    I would expect that the order does not change. I would expect the member
    groups to appear in the same order as in the source code.
    
    Does this happen every time?
    Yes.
    
    Other information:
    1. I don't know if there is a similar problem for member subgroups, but I
    couldn't find a simple way to influence their order based on the items in
    them.
    
    2. If SORT_BRIEF_DOCS is set to YES, then the order does not change if the
    enum is removed. I don't know whether SORT_BRIEF_DOCS is meant to apply to
    member (sub)groups themselves. If yes: I don't know what string is used to
    sort the member groups, but at least they are not sorted alphabetically by
    the \name argument.

On 2009-07-23 06:56:12 +0000, Joachim Reichel wrote:

    I should have mentioned that at least HTML and XML output are affected.

**Comment by albert-github** [comment]
With version 1.5.9 we see when the enum is present first Member group 2 followed by Member group 1.
Without the order is Member group 1 followed by Member group 2 (as expected).
With version 1.8.15 (and 1.8.15) the expected order is present.

I think the problem has been solved in the mean time.
