### ISSUE TITLE
[html] wrong <title> value, missing title in page for "Members" pages (Origin: bugzilla #594746)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3512]
status NEW severity *minor* in component *general* for *---*
Reported in version *1.5.9* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-09-10 14:02:47 +0000, Joachim Reichel wrote:

    Steps to reproduce:
    
    any C++ project with namespaces, global entities, and \file statements
    default Doxyfile of doxygen 1.5.9
    
    Actual results:
    
    1. The <title> tag inside <head> for the Namespace Members and File Members
    pages has the value "Class members".
    
    2. The title on the page itself (inside <body>) is missing on all the
    Namespace Members, File Members and Class Members pages.
    
    Expected results:
    
    1. Correct <title> values for the Namespace Members and File Members pages.
    
    2. Visible titles for the three Members pages, as for all other pages.
    
    Other information:
    Also happens with doxygen 1.6.0 and 1.6.1.

**Comment by albert-github** [comment]
Point 1):
With version 1.5.9. I see the problems as indicated.
With version 1.8.14 the namespace parts are labeled "Namespace Members" and the files parts as "File Members"

Point 2:
Still present in 1.8.14

**Comment by albert-github** [comment]
Regarding the point 2 is meant when selecting according to:

![readme_0](https://user-images.githubusercontent.com/5223533/211027701-bda152ea-8f59-40a2-8d80-64bd51e3edc3.png)


we get:

![readme_1](https://user-images.githubusercontent.com/5223533/211027744-5bd9cb2c-d287-4474-b9ca-2559242249c4.png)

here we only see the members and not a "descriptive" text.

Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/10360630/example.tar.gz)

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #9778

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.7.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
