### ISSUE TITLE
Fortran: Backslashes in literals are always treated as special chars (Origin: bugzilla #596872)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3544]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.6.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[backslash.f90](https://sourceforge.net/projects/doxygen/files/attachments/bug596872_176987_backslash.f90/download/download)_ (ID 176987)
- _[Doxyfile](https://sourceforge.net/projects/doxygen/files/attachments/bug596872_176988_Doxyfile/download/download)_ (ID 176988)
- _[backslash.diff](https://sourceforge.net/projects/doxygen/files/attachments/bug596872_177013_backslash.diff/download/download)_ (ID 177013)
- _[doxycrash2_fortran.tgz](https://sourceforge.net/projects/doxygen/files/attachments/bug596872_181928_doxycrash2_fortran.tgz/download/download)_ (ID 181928)

On 2009-09-30 13:15:26 +0000, arthur@van-dam.net wrote:

    In Fortran code one may write a literal 'foo\bar' and the \ will be
    considered a literal backslash (at least with command line option -fno-
    backslash, with -fbackslash it *is* considered a metacharacter).
    
    The doxygen parser crashes on this, by stating an error at line n+1 (where n
    is nr of lines in file).
    For example:
    ********************************************************************
    Error in file D:/dam_ar/MultiGridClass.f90 line: 2675, state: 20
    ********************************************************************
    R6025
    - pure virtual function call
    (the file has 2674 lines)
    
    A command-line option for the fortran-mode of doxygen could solve this.

On 2010-12-23 21:58:46 +0000, Daniel Franke wrote:

    Please attach a fully self-contained testcase, i.e. a fortran file with
    which doxygen shows above error plus the corresponding doxyfile.
    
    This ...
    
    program x
      print *, 'foo\bar \n'
    end program
    
    ... does not show any problems.

On 2010-12-24 08:37:14 +0000, arthur@van-dam.net wrote:

    Created attachment 176987
    Minimal test file with literal backslashes that cause crash.

On 2010-12-24 08:38:59 +0000, arthur@van-dam.net wrote:

    Created attachment 176988
    Doxyfile for use with backslash.f90
    
    Nothing special about this Doxyfile, so just for completeness.

On 2010-12-24 12:37:38 +0000, Daniel Franke wrote:

    *** Bug 602952 has been marked as a duplicate of this bug. ***

On 2010-12-24 12:38:31 +0000, Daniel Franke wrote:

    *** Bug 630580 has been marked as a duplicate of this bug. ***

On 2010-12-24 12:45:24 +0000, Daniel Franke wrote:

    Created attachment 177013
    Potential patch
    
    This patch solves the issue, but the rules it removes where probably
    introduced with a reason. Needs to be carefully checked for regressions.

On 2011-02-25 16:32:59 +0000, Richard Ash wrote:

    I've hit this same bug independently, applied the patch onto 1.7.3 release,
    and it builds the documentation for my mixed set of C, C++ and Fortran
    packages without crashing, which is good. I haven't yet had time to check
    the docs for any other changes introduced by the patch.

On 2011-02-25 16:34:36 +0000, Richard Ash wrote:

    Created attachment 181928
    Another test case that causes Doxygen to crash
    
    This is another test case which is different but triggers the same bug (I
    believe, it is certainly fixed by the same patch).
    
    This is an issue regardless of whether the Preprocessor is enabled or not,
    it crashes with both settings.

On 2011-09-15 10:40:43 +0000, Soeren Huettemann wrote:

    Any progress on this issue?
    Bug 623296 and Bug 596872 prevent us from using Doxygen with our Fortran
    Projects.
    I really would like to use Doxygen. I am willing to test bug fixes.

On 2018-06-27 14:44:15 +0000, albert wrote:

    The issue in this bug report the use of the backslash.
    
    This has ben solved by my proposed patch on github (pull request 773,
    https://github.com/doxygen/doxygen/pull/773).
    
    The mentioned bug_623296 (by Soeren Huettemann, I taken the liberty to add
    him on the CC list of that issue) is a different problem and will be
    investigated with that bug report.

**Comment by albert-github** [comment]
Pull request #773 integrated, issue can be labeled as `fixed but not released`.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
