### ISSUE TITLE
PHP input sources don't have <script language=['"]php['"]>...</script> tags recognized. (Origin: bugzilla #596902)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3545]
status RESOLVED severity *normal* in component *general* for *---*
Reported in version *1.5.8* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[test.php](http://ftp.stack.nl/pub/users/dimitri/bugzilla/attachments//bug596902_144427_test.php)_ (ID 144427)

On 2009-09-30 18:14:28 +0000, Adam H Peterson wrote:

> Created attachment 144427
> An example source file showing PHP code that Doxygen doesn't parse.
> 
> When Doxygen is given a PHP source file, it recognizes PHP source code between
> "<?php ... ?>" tags, but ignores code between "<script language='php'> ...
> </script>" tags.
> 
> Steps to reproduce:
> 1. In an empty directory, create this file (minus the line numbers) as
> "test.php":
>      1    #!/usr/bin/env php
>      2    <script language="php">
>      3    /**
>      4     * @brief A test class for PHP Doxygen support.
>      5     */
>      6    class TestClass {
>      7        /**
>      8         * @brief The constructor.
>      9         */
>     10        public function __construct() { }
>     11    };
>     12    </script>
> 2. Run Doxygen:
>     doxygen -g Doxyfile
>     doxygen Doxyfile
> 3. View the generated html/index.html
> 
> Desired results:
> Doxygen should produce a "Classes" tab in the HTML documentation, which when
> clicked would show the documentation for "TestClass".
> 
> Actual results:
> The class documentation is not present, presumably because the <script...> tag
> was interpreted as HTML output rather than parsed as PHP source delimiters.  If
> line 2 is changed to "<?php" and line 12 is changed to "?>", the documentation
> is produced.

On 2009-10-10 14:40:41 +0000, Dimitri van Heesch wrote:

> Confirmed. Should be fixed in the next subversion update.

On 2009-12-30 13:38:57 +0000, Dimitri van Heesch wrote:

> This bug was previously marked ASSIGNED, which means it should be fixed in
> doxygen version 1.6.2. Please verify if this is indeed the case and reopen the
> bug if you think it is not fixed (include any additional information that you
> think can be relevant).

**Comment by hashar** [comment]
That has been fixed by adding PHP7 support #680 / 22b67836d678cea695b977ec648c0aa013339c55
