### ISSUE TITLE
C# Private and internal setters get listed in docs (Origin: bugzilla #597922)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3556]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-10-09 16:17:38 +0000, rjordan@pobox.com wrote:

    public long Id
            {
                get;
                private set;
            }
    
    gets documented as
    long  Id [get, set] 
    
    I would expect
    long  Id [get] 
    
    unless EXTRACT_PRIVATE was set

**Comment by albert-github** [comment]
Needed to make the example slightly different to:
```
public class cls
{
  public long Id
  {
    int get {Preturn 42;};
    private set {};
  }
}
```
with the 1.5.9 version we get:
![image](https://user-images.githubusercontent.com/5223533/226295971-976a4a01-39c2-43dc-8121-196907c381c7.png)


With the current (1.9.6) version we get:
![image](https://user-images.githubusercontent.com/5223533/226296388-db737de1-4451-4c3f-9d24-092d99cf6620.png)


I think the problem has been solved in the mean time.
