### ISSUE TITLE
ALLEXTERNALS=Yes, but external classes will not be listed in the class index (Origin: bugzilla #597928)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3557]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.6.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[External.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug597928_145153_External.zip/download/download)_ (ID 145153)

On 2009-10-09 17:19:14 +0000, Carl R. Werth wrote:

    Created attachment 145153
    example projects for bug with ALLEXTERNALS
    
    One project is generating a tag-file, the other project is using the tag-
    file
    with configuration "ALLEXTERNALS = YES", but the external classes will not
    be
    listet in the class index of the second project.
    
    By the way:
    If there is an external class (TestX from project A) with the same name as
    an
    internal class (TestX in project B), then there will be no entry at all with
    that name.
    This is very nasty, especially if 2 projects share some source files
    (Share\Share.cpp).
    
    An example is attached as zip-file.
    First generate project A, which will create TagfileA.
    Then generate project B.

On 2009-10-22 19:45:10 +0000, Lou Hafer wrote:

    I'll confirm that external classes are not listed in the class index even
    when ALLEXTERNALS is set. All external classes do show in the hierarchical
    index. A bit of poking in the code says that inclusion in the hierarchical
    index is determined by ClassDef::isVisibleInHierarchy, which considers the
    ALLEXTERNALS option. Inclusion in the annotated and alphabetical indices is
    determined by ClassDef::isLinkableInProject, which does not consider
    ALLEXTERNALS (external references are unconditionally excluded).

On 2009-12-29 10:23:47 +0000, Roland Fischer wrote:

    I can confirm, too. with the attached example and in my own test projekts
    none of the external classes, parsed files and namespaces are included.

On 2017-06-06 05:34:16 +0000, Fabian wrote:

    I can confirm, too. There is a stackoverflow question regarding this.
    
    https://stackoverflow.com/questions/43752927/how-to-link-a-doxygen-
    documentation-in-html-to-another-one
    
    Will it be fixed in the near future?

**Comment by albert-github** [comment]
With the doxygen 1.6.1 version we see:
![image](https://github.com/doxygen/doxygen/assets/5223533/ad2ef8f5-9216-4466-9aec-fbe6f073bb57)

With the current 1.9.8 version we see:
![image](https://github.com/doxygen/doxygen/assets/5223533/5d6f1496-ef03-4162-a868-c1f79bc7b18d)


So I think the problem has been solved in the mean time
