### ISSUE TITLE
linking to typedefs, enums, enum values, and variables in namespaces (Origin: bugzilla #600829)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3575]
status RESOLVED severity *normal* in component *general* for *---*
Reported in version *1.6.3* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-11-05 15:24:27 +0000, Joachim Reichel wrote:

> Linking to typedefs, enums, enum values, and variables in namespaces does not work as expected. Consider this example:
> 
> --------------------------------------------
> /// \file
> 
> /// namespace N
> namespace N {
> 
> /// typedef T
> typedef int T;
> 
> /// enum E
> enum E {
>      V = 0 //!< enum value V
> };
> 
> /// global variable G
> int G;
> 
> } // namespace N
> 
> /// typdef: #N::T, ::N::T, N::T
> /// enum: #N::E, ::N::E, N::E
> /// enum value: #N::V, ::N::V, N::V
> /// global variable: #N::G, ::N::G, N::G
> int main (int argc, char* argv[])
> {
>    return 0;
> }
> --------------------------------------------
> 
> I would prefer to use explicit links (# or :: prefix) to get warnings 
> when these items get renamed. But that does not work:
> 
> 1. The link tests with # and :: prefix do not generate any link. The 
> third link test in each row (without # or :: prefix) does generate a 
> link. I would expect that all of them (or at least the first two) 
> generated a link.
> 
> 2. The first test (# prefix) generates a warning which I do not 
> understand since it works without prefix.
> 
> 3. The second test (:: prefix) does not even generate a warning.
> 
> The problem is related to the namespace. Without namespaces everything 
> works as expected. I also haven't noticed any such problems with 
> classes, member functions, and (global) functions.

On 2010-06-09 07:47:17 +0000, Joachim Reichel wrote:

> This bug still exists with doxygen 1.6.3.
> 
> I wonder about the importance of this bug (for me it is quite annoying). Is it considered less important than other bugs that get fixed, or does it require a large amount of work?

On 2010-06-12 17:21:46 +0000, Dimitri van Heesch wrote:

> Hi Joachim,
> 
> I've found the problem. Should be corrected in the next release.

On 2010-06-15 11:21:33 +0000, Dimitri van Heesch wrote:

> This bug was previously marked ASSIGNED, which means it should be fixed in
> doxygen version 1.7.0. Please verify if this is indeed the case. Reopen the
> bug if you think it is not fixed and please include any additional information
> that you think can be relevant.

**Comment by Mekk** [comment]
Looks like this problem is back in 1.8.13 – I can't find a way to @ref EnumDef or @ref ENUM_ELEMENT while inside namespace (still, enum is nicely documented and signature of the method which has param of enum type links to enum definition properly) …

**Comment by albert-github** [comment]
I checked the problem with the following versions:
- 1.6.3 some links missing
- 1.7.0 all links present
- 1.8.13 all links present
- 1.8.16 all links present

@Mekk 
In case you think there is a bug, please try also with the current version (1.8.16 or with the master version from github). When persistent please:
- open a new issue
- specify the version you used to test
- attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.
 - specify (image ?) where you are missing something
