### ISSUE TITLE
Doxygen runs out of memory in 32 bit mode (Origin: bugzilla #602817)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3592]
status NEEDINFO severity *critical* in component *general* for *---*
Reported in version *1.6.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[attachment.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug602817_148517_attachment.zip/download/download)_ (ID 148517)
- _[assert.jpg](https://sourceforge.net/projects/doxygen/files/attachments/bug602817_148827_assert.jpg/download/download)_ (ID 148827)
- _[attachment.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug602817_148984_attachment.zip/download/download)_ (ID 148984)
- _[stacktrace.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug602817_151025_stacktrace.zip/download/download)_ (ID 151025)

On 2009-11-24 10:14:43 +0000, Marek Janacek wrote:

    We are running doxygen (1.6.1) on our sources in C++ (about 21,500 source
    files with 2,850,000 lines of code and 1,070,000 lines of comments).
    
    After 5 hours of run we get an error: "doxygen.exe has encountered a problem
    and needs to close". With older doxygen versions (1.5.4) we got another
    error:
    "In file ..\qtools\qgarray.cpp, line 229: Out of memory", unless we excluded
    significant amount of source files (1,050 source files with 100,000 lines of
    code and 40,000 lines of comments). However excluding files helps us no more
    with version 1.6.1
    
    OS: Windows XP SP3
    
    Few last lines before crash from standart output:
    Preprocessing
    C:/projectdoc/src1/src/Tools/PrintT/ssprintpropsrvmode/precomp.hxx...
    Parsing file
    C:/projectdoc/src1/src/Tools/PrintT/ssprintpropsrvmode/precomp.hxx...
    Preprocessing
    C:/projectdoc/src1/src/Tools/PrintT/ssprintpropsrvmode/private.hxx...
    Parsing file
    C:/projectdoc/src1/src/Tools/PrintT/ssprintpropsrvmode/private.hxx...
    Preprocessing
    C:/projectdoc/src1/src/Tools/PrintT/ssprintpropsrvmode/ssprintpropsrvmode.cxx...
    Parsing file
    C:/projectdoc/src1/src/Tools/PrintT/ssprintpropsrvmode/ssprintpropsrvmode.cxx...
    Preprocessing
    C:/projectdoc/src1/src/Tools/PrintT/ssprintpropsrvmode/ssprintpropsrvmode.hxx...
    Parsing file
    C:/projectdoc/src1/src/Tools/PrintT/ssprintpropsrvmode/ssprintpropsrvmode.hxx...
    Preprocessing
    C:/projectdoc/src1/src/Tools/PrintT/ssprintpropsrvmode/ssprintpropsrvmode.inl...
    Parsing file
    C:/projectdoc/src1/src/Tools/PrintT/ssprintpropsrvmode/ssprintpropsrvmode.inl...
    Preprocessing
    C:/projectdoc/src1/src/Tools/PrintT/ssprintpropsrvmode/ssprintpropsrvmode_svc.cxx...
    Parsing file
    C:/projectdoc/src1/src/Tools/PrintT/ssprintpropsrvmode/ssprintpropsrvmode_svc.cxx...
    Preprocessing
    C:/projectdoc/src1/src/Tools/PrintT/ssprintsrvmode/precomp.hxx...
    Parsing file
    C:/projectdoc/src1/src/Tools/PrintT/ssprintsrvmode/precomp.hxx...
    Preprocessing
    C:/projectdoc/src1/src/Tools/PrintT/ssprintsrvmode/private.hxx...
    Parsing file
    C:/projectdoc/src1/src/Tools/PrintT/ssprintsrvmode/private.hxx...
    Preprocessing
    C:/projectdoc/src1/src/Tools/PrintT/ssprintsrvmode/SSPreviewFile.cxx...
    Parsing file C:/projectdoc/src1/s

On 2009-11-25 08:47:48 +0000, Alfred Staufner wrote:

    Hi Marek!
    We have the same problem and the only fast solution was to activate 3GB
    virtually address space in XP. Under vista the application can allocate a
    little bit more memory as under XP. We have try with different settings of
    SYMBOL_CACHE_SIZE in the range 0 to 5 nothing was helping.

On 2009-11-25 08:52:17 +0000, Alfred Staufner wrote:

    Maybe itâs possible to compile the windows binaries with
    /LARGEADDRESSAWARE a default.

On 2009-11-25 18:55:45 +0000, Dimitri van Heesch wrote:

    Seems Visual Studio comes with a tool called editbin.exe which you can use
    to patch an existing .exe to enable 3GB an address space for this
    executable, which would then work for Windows versions that support 3GB.
    
    I would be interested to hear if this helps in your situation.

On 2009-11-26 08:01:20 +0000, Alfred Staufner wrote:

    Hi Dimitri!
    Yes I know this tool, but I don't have use it. I have recompile doxygen
    (1.5.9) with largeaddressaware active and this helps. Doxygen use with our
    project after ~ 2.8GB virtual address size. After ~4(!) days the html
    documentation is finish.
    On my XP PC was not so much virtual memory available. This machine don't
    boot with 3GB, only when is limited to 2.9GB. On a vista PC this was not a
    problem. In general some PC's are bitchy with the 3GB option active.
    In our case the memory finish when the files are scanned do build the
    symbolist. On different locations, some time only when the memory for a
    string (some bytes) was allocated. Maybe depends form the heap fragmentation
    or something else. The same output as described in the defect. When you have
    need for the exactly stack context it's necessary to start this
    investigating again and this will take a little time. In the first I was
    expected SYMBOL_CACHE_SIZE will help but don't do it. A other idea what
    appear was to compile for vista64. Did you have experience about this? In
    the last this will be the ultimate solution for this problem.

On 2009-11-26 10:47:29 +0000, Marek Janacek wrote:

    Created attachment 148517
    minidump, history graph of doxygen memory allocation and exception analysis
    from WinDbg
    
    Hi,
    
    Thank you for your answers and tips, but the problem with out of memory was
    in version 1.5.4 and probaly it is not related to our main problem. Our
    biggest problem is with unhandled exception in version 1.6.1 as I wrote in
    my first post and I think this problem has nothing to do with "run out of
    memory" becouse our virtual address size was about 1,760MB at the crash
    moment.
    
    In attachment I post minidump from exception, history graph of doxygen
    memory allocation and exception analysis from WinDbg.

On 2009-11-26 19:22:32 +0000, Dimitri van Heesch wrote:

    Hi Alfred,
    
    The symbol cache size is not a control for all memory usage indeed (but I
    would have expected it is responsible for the majority). It would be
    interesting to know why so much memory is needed (maybe there is a memory
    leak),
    but I guess that's rather hard to figure out.
    
    Hi Marek,
    
    Is it also possible for you to compile doxygen from source (with debug
    symbols) and do a stack trace when it crashes? The only info I get from your
    attachment is that doxygen has crashed somewhere which is not very helpful.

On 2009-12-01 15:41:50 +0000, Marek Janacek wrote:

    Created attachment 148827
    Debug assertion failed screen
    
    Hi,
    
    We have compiled doxygen with debug symbols and started it. Now doxygen is
    still running and we wait when the unhandled exception appears. However
    several times we got debug assertion failed (details in srcreen in
    attachment). We choose to ignore it. Is there any way, how to ignore this
    automatically?

On 2009-12-03 06:44:20 +0000, Marek Janacek wrote:

    Created attachment 148984
    Memory dump from crash and excetpion analysis (stack trace)
    
    Hi,
    
    I post memory dump and exception analysis (stack trace) from crash of
    doxygen, that was compiled with debug symbols.

On 2009-12-23 14:51:12 +0000, Dimitri van Heesch wrote:

    For comment # 7: I would like to see a stack trace when the assert happens.
    For comment # 8: It seems the exception happens due to a new operator
    failing to allocate memory, so one obvious reason could be that your system
    has ran out of memory. If that's the case, then there is not much I can do.
    You could try if splitting your project into smaller parts helps.

On 2010-01-08 07:45:50 +0000, Marek Janacek wrote:

    Created attachment 151025
    stack traces from asserts
    
    Hi,
    
    thanks for your answer. I am sending stack traces from first and second time
    when the asserts happened. There were more asserts until the crash, but all
    of them were the same: (unsigned)(c+1) <= 256

On 2010-02-11 10:09:25 +0000, Marek Janacek wrote:

    Hi all,
    
    We have discovered quite interesting thing. With version 1.5.4 patched by
    editbin.exe with parameter \LARGEADDRESSAWARE, our run was successful.
    However we also tried to patch version 1.6.1 the same way, but again we got
    an unhandled exception error. Doxygen used about 2400MB virtual address size
    just before the exception happened, so there was probably decent amount of
    free memory to 3GB. Has anyone any idea what could be our problem except not
    enough free memory? Thanks for your answers.
    
    Marek

On 2010-02-20 11:23:19 +0000, Dimitri van Heesch wrote:

    (In reply to comment # 10)
    I think this can be fixed with a simple expression reordering in isId() in
    util.h:
    
    inline bool isId(int c)
    {
      return c=='_' || isalnum(c) || c>=128 || c<0;
    }
    
    should become
    
    inline bool isId(int c)
    {
      return c=='_' || c>=128 || c<0 || isalnum(c);
    }
    
    so the "invalid" characters are not passed to isalnum.

On 2010-04-01 05:35:41 +0000, Marek Janacek wrote:

    Hi, 
    
    we have tried Doxygen versions from 1.5.4 to most actual 1.6.3 and
    successful runs were only with 1.5.4 and 1.5.5. With newer versions we were
    getting errors about ârun out of memoryâ or simply Doxygen crashed on
    unhandled exception. Do later Doxygen versions need more memory, or what can
    be cause of this behavior?
    
    Marek

On 2013-10-12 21:36:17 +0000, Dimitri van Heesch wrote:

    Can you check if this problem still occurs with doxygen version 1.8.5?
    (which installs as 64bit if you use a 64bit OS)

**Comment by albert-github** [comment]
Seen:
- the period passed
- the fix in #4177
- the different build system (cmake)
- different compilers
- most common is 64-bit systems
- no "recent" reports about this type of issue

I think this problem can been closed as solved in the mean time
