### ISSUE TITLE
bad links in source code browser for multiple functions of same name (Origin: bugzilla #610166)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3676]
status NEW severity *minor* in component *general* for *---*
Reported in version *1.6.2-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxygen_test.tgz](https://sourceforge.net/projects/doxygen/files/attachments/bug610166_153933_doxygen_test.tgz/download/download)_ (ID 153933)

On 2010-02-16 16:11:24 +0000, Stan Holenda wrote:

    Created attachment 153933
    Example code with doxyfile
    
    Consider a C project consisting of more binaries, there will be several
    functions of same name (at least main functions).
    
    Doxygen correctly detects, there are separate "main" functions (shown e.g.
    in Globals) and creates separate pages for them.
    
    However if you go to the source code the links to the "main" function all
    point to first occurrence of "main" in project (see attached example code).
    
    Expected behavior (in this example) is clicking on "main" in e.g. test3.c
    should lead to test3.c page not test1.c.
    
    
    Tested with 1.6.2-20100208 SVN rev. 720

On 2010-10-01 15:37:50 +0000, doxygen.dumper@antichef.com wrote:

    I'm experiencing the same issue. In my case, I have 10s and even hundreds of
    source files, most with a "main" and a "mainline" function, some with
    "finalization" functions. When you click on the link for these functions,
    they take you to a different source file with the same function. If you're
    not careful and are not looking at the source name which is often just in
    the header, this can be confusing to the user.
    
    Also, I noticed that the call graph for functions with names like "main"
    will more often than not represent the interactions in a different source
    file.

**Comment by albert-github** [comment]
I tested the original example with version 1.6.2 and saw the problem as indicated.
When testing the same problem with version 1.9.1 the problem does not occur.

I think the problem has been solved in the mean time.
