### ISSUE TITLE
<![CDATA[ is not handled inside C# comments (Origin: bugzilla #610436)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3677]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.6.2* on platform *Other*
Assigned to: Dimitri van Heesch

On 2010-02-19 09:33:37 +0000, tkrotoff@gmail.com wrote:

    Example of a C# valid comment:
    
    /// <code>
    /// <![CDATA[
    ///     <<
    ///     >>
    /// ]]>
    /// </code>
    
    <<
    >> is the piece of text we want to show inside a code tag.
    Since < and > and reserved characters by XML, we have to "escape" them using
    <![CDATA[ otherwise Visual Studio 2008 will complain.
    
    Problem with Doxygen 1.6.2 is that the generated HTML documentation contains
    <![CDATA[ and should not.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6398.

**Comment by albert-github** [comment]
Code has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
