### ISSUE TITLE
Python function names include full module namespace when documented - often unreadably long. (Origin: bugzilla #611173)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3687]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.6.3* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[test_case.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug611173_154747_test_case.zip/download/download)_ (ID 154747)

On 2010-02-26 12:08:41 +0000, sentrydesign@yahoo.co.uk wrote:

    In my Python project I am using a typical module structure - about four or
    five levels deep - to namespace a large project on disc.
    
    Doxygen currently reflects the entire package namespace when naming the
    function in the HTML documentation which is quite often unreadable. This is
    great for the class name, but a but of a pain for individual functions
    within that class.
    
    e.g. For the class: 
    
        mpd.utilities.PriorityQueue.PriorityQueue._PQueueEntry.
    
    ... the function definitions are similar to:
     
        def mpd.utilities.PriorityQueue.PriorityQueue._PyQueueEntry.__cmp__(...)
    
    
    For documentation clarity it would be much better if they were simply:
    
        def __cmp__(...)
    
    as the namespace is implicitly inside the parent class.

On 2010-02-26 12:17:25 +0000, sentrydesign@yahoo.co.uk wrote:

    Created attachment 154747
    Simplified test case.
    
    Added simplified test case.

**Comment by albert-github** [comment]
With the 1.6.3 version I see:
![image](https://github.com/doxygen/doxygen/assets/5223533/0d8ab934-f207-4cca-bedc-28f4eee3d787)

with the current doxygen version (1.9.7) I see:
![image](https://github.com/doxygen/doxygen/assets/5223533/14864ac7-6ce1-4120-9022-be523d0ff00a)

so the standard change of the layout of the output makes it more readable and still all information is present.

I think the problem has been solved in the mean time.
