### ISSUE TITLE
Main page duplicate in index.qhp (Origin: bugzilla #612854)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3707]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.6.3* on platform *Other*
Assigned to: Dimitri van Heesch

On 2010-03-14 10:41:24 +0000, Bastiaan wrote:

    Hi,
    
    If I supply a \mainpage and generate Qt Help, a duplicate of the main page
    is nested under the real main page in the TOC. E.g., the generated index.qhp
    may have this:
    
        <toc>
          <section title="My Project" ref="index.html">
            <section title="My Project" ref="index.html" />
            <section title="Other Info" ref="page___other_info.html" />
          </section>
        </toc>
    
    The second reference to index.html is one too many.
    
    Thanks,
    Bastiaan.

**Comment by albert-github** [comment]
I tried with version 1.6.3 and the mainpage example as given in the documentation with the \\mainpage command but I was not able to reproduce the output. I see that when specifying as title for the mainpage the same name as for the project ('My Project') there are 2 lines in the index.qhp with 'My Project', one with 'index.html' and one with 'main.html'. Whit the current version (1.8.14) this double line is gone.
Furthermore with the current version everything looks consistent with the TREEVIEW as generated in HTML pages (also in case of a different  mainpage title).
