### ISSUE TITLE
Program Icon under Windows (Origin: bugzilla #615500)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3730]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2010-04-12 08:53:22 +0000, 127.0.0.0@gmx.de wrote:

    Ok, my wish is a simple nice to have wish. 
    
    But under windows it is always nice to have a icon representing it's
    program. For example if you want to open word i always see a document icon
    containing a small w.
    
    So can you please assign a simple program icon to doxygen / doxywizard ???
    If you want i can made any suggestions for it.

On 2010-04-17 11:53:28 +0000, AndrÃ© Klapper wrote:

    Can you please provide concrete exact steps where this icon is shown?

On 2010-04-19 09:51:04 +0000, 127.0.0.0@gmx.de wrote:

    (In reply to comment # 1)
    > Can you please provide concrete exact steps where this icon is shown?
    
    It's a little bit surprising to me, because you can see this icon whenever
    you open the bin folder of Doxygen via the windows explorer. So if i run
    "explorer c:\Programme\doxygen\bin" on my pc, explorer shows me the bin
    folder containing doxygen.exe, doxytag.exe and doxywizard.exe. And all
    executables have the same standard icon.
    
    This icon can also be shown if you start doxywizard and change the program
    context via the [alt]+[tab] shortcut. It is also shown in the left upper
    corner of the doxywizard dialog.

On 2013-04-21 16:32:44 +0000, albert wrote:

    I see that a start has been made with an icon for the DoxyWizard.
    Is there am icon available that can be used for all doxygen executables or
    is there a plan to create such an icon?

On 2013-04-21 19:25:16 +0000, Dimitri van Heesch wrote:

    Only doxywizard has a GUI and is meant to be started via an icon. The other
    tools are command line based, so I don't see a need for an icon.

On 2013-04-22 06:25:14 +0000, albert wrote:

    I do agree that only doxywizard has a GUI and therefore it seems logical
    that only this application has an icon. The icon is not only used for
    starting the application, but is also shown when a directory listing is made
    in the explorer.
    Therefore I think it might be useful that all executables have ab icon. A
    second argument is that it does some name branding / makes executables more
    recognizable.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #9938

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.7.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
