### ISSUE TITLE
doxygen result by nested comment incorrectly (Origin: bugzilla #616379)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3746]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.6.3* on platform *Other*
Assigned to: Dimitri van Heesch

On 2010-04-21 09:07:14 +0000, kulow.f@googlemail.com wrote:

    bad nested comment
    in source TB_VAR.H:
    ----------------
    ///neu                            ***/
    ///alt
    int copy;
    ----------------
    the result (txt):
    ----------------
    TB_VAR.H File Reference
    
    Go to the source code of this file.
    Variables
    alt *int 	copy
    Variable Documentation
    alt* int copy
    
    neu
    
    Definition at line 3 of file TB_VAR.H.
    
    -------------
    the result (html):
    --------------
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
    <html xmlns="http://www.w3.org/1999/xhtml">
    <head>
    <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
    <title>TB_VAR.H File Reference</title>
    <link href="../../tabs.css" rel="stylesheet" type="text/css"/>
    <link href="../../doxygen.css" rel="stylesheet" type="text/css"/>
    </head>
    <body>
    
    <div class="navigation" id="top">
      <div class="tabs">
        <ul>
          <li><a href="../../main.html"><span>Main&nbsp;Page</span></a></li>
    
          <li class="current"><a
    href="../../files.html"><span>Files</span></a></li>
        </ul>
      </div>
      <div class="tabs">
        <ul>
          <li><a href="../../files.html"><span>File&nbsp;List</span></a></li>
          <li><a href="../../globals.html"><span>Globals</span></a></li>
    
        </ul>
      </div>
    </div>
    <div class="contents">
    <h1>TB_VAR.H File Reference</h1>
    <p><a href="../../HTML/S/9.html">Go to the source code of this file.</a></p>
    <table border="0" cellpadding="0" cellspacing="0">
    <tr><td colspan="2"><h2>Variables</h2></td></tr>
    <tr><td class="memItemLeft" align="right" valign="top">alt
    *int&nbsp;</td><td class="memItemRight" valign="bottom"><a class="el"
    href="../../d8/d26/_t_b___v_a_r_8_h.html#a27cad837d6c267ddcd21d3f2e951698c">copy</a></td></tr>
    </table>
    
    <hr/><h2>Variable Documentation</h2>
    <a class="anchor" id="a27cad837d6c267ddcd21d3f2e951698c"></a>
    <div class="memitem">
    <div class="memproto">
          <table class="memname">
            <tr>
              <td class="memname">alt* int <a class="el"
    href="../../d8/d26/_t_b___v_a_r_8_h.html#a27cad837d6c267ddcd21d3f2e951698c">copy</a></td>
            </tr>
          </table>
    
    </div>
    <div class="memdoc">
    <p>neu </p>
    
    <p>Definition at line <a class="el" href="../../HTML/S/9.html#L3">3</a> of
    file <a class="el" href="../../HTML/S/9.html">TB_VAR.H</a>.</p>
    
    </div>
    </div>
    </div>
    <hr class="footer"/><address style="text-align: right;"><small>Generated on
    Wed Apr 21 10:56:58 2010 by&nbsp;
    
    <a href="http://www.doxygen.org/index.html">
    <img class="footer" src="../../doxygen.png" alt="doxygen"/></a> 1.6.3
    </small></address>
    </body>
    </html>

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6649

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
