### ISSUE TITLE
SEARCHENGINE and Command Line use (Origin: bugzilla #617075)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3753]
status NEW severity *normal* in component *general* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2010-04-28 12:57:38 +0000, DUCHENE wrote:

    The Doxyfile with following configuration raise problem:
    GENERATE_HTML = NO;
    SEARCHENGINE = YES;
    
    When I execute the command
    doxygen Doxyfile
    whit this Doxyfle I obtain this error message:
    "Could not create search results directory 'html/search/search'"
    
    And so generating stop.

**Comment by albert-github** [comment]
With the 1.6.2 version I can reproduce the problem, with the current (1.9.6) version the warning is gone.

I think the problem has been solved in the mean time
