### ISSUE TITLE
Directories with non-ascii characters are not handled properly on Windows (Origin: bugzilla #617871)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3766]
status RESOLVED severity *normal* in component *general* for *---*
Reported in version *1.6.3* on platform *Other*
Assigned to: Dimitri van Heesch

On 2010-05-06 09:02:09 +0000, tsansoni@beo.fr wrote:

> Hello,
> 
> I am using Doxygen 1.6.3 and it is impossible to me to give a directory with a french accent.
> 
> My project is in a directory called : GalilÃ©e 2000 and in the INPUT tag this name crashed the software. I have this message :
> 
> Warning: tag INPUT: input source `../GalilÃÂ©e 2000/GalilÃÂ©e 2000' does not exist
> Warning: source ../GalilÃÂ©e 2000/GalilÃÂ©e 2000 is not a readable file or directory... skipping.
> *** Doxygen has finished
> 
> Could someone help me or give me a tip.
> 
> Thanks

On 2010-06-11 11:17:24 +0000, Dimitri van Heesch wrote:

> The problem is that on Windows (unlike Linux or MacOSX), the stdio functions (fopen and friends) cannot handle UTF-8 encoded strings, which doxygen uses internally. I'll have to use the wide characters versions (i.e. _wfopen) and do a proper UTF-8 to UCS2 conversion internally. Should work in the next release.

On 2010-06-15 11:21:49 +0000, Dimitri van Heesch wrote:

> This bug was previously marked ASSIGNED, which means it should be fixed in
> doxygen version 1.7.0. Please verify if this is indeed the case. Reopen the
> bug if you think it is not fixed and please include any additional information
> that you think can be relevant.

**Comment by MarioBosse** [comment]
Not fixed in 1.10

**Comment by albert-github** [comment]
Special characters in directory names / file names as used by French / German users are quite hard to reproduce as they most of the time depend on a number of, local, settings that are not reproducible on systems that don't use these settings or different settings (on *nix e.g `LC_CTYPE`).
- Which OS are you using?
- What are the environment settings (Windows and *nix) result of the `set` command.
- To see the directory file names  etc.: Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).
