### ISSUE TITLE
DoxyParamCaption doesnt have a proper example to provide formatting (Origin: bugzilla #618949)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3778]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2010-05-18 02:28:20 +0000, Murali wrote:

    The patch added via
    http://sourceforge.net/mailarchive/message.php?msg_name=4AAE09D0.8020002%40obssys.com
    is quite nice, but doesnt provide us instructions on how to achieve the
    table-like layout for DoxyParamCaption. May be the option to form a table
    should be added in Doxygen as a config and enable users to automatically
    choose that method, rather than make them construct a sty file just to get
    that option.
    
    thanks

**Comment by albert-github** [comment]
In doxygen 1.7.0 the DoxyParamCaptionwas introduced for LaTeX code as an internal LaTeX environment. Later on the (doxygen version 1.8.0) the LaTeX environments have been placed in a doxygen.sty file, so it is also accessible by the user.

I think the problem has been solved in the mean time.
