### ISSUE TITLE
EXTENSION_MAPPING for C# not working (Origin: bugzilla #619728)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3783]
status RESOLVED severity *normal* in component *general* for *---*
Reported in version *1.6.3-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxygen_1.6.3-20100507_csharp_util.cpp.patch](http://ftp.stack.nl/pub/users/dimitri/bugzilla/attachments//bug619728_162024_doxygen_1.6.3-20100507_csharp_util.cpp.patch)_ (ID 162024)
- _[doxygen_1.6.3-20100507_cs_extension_fix.patch](http://ftp.stack.nl/pub/users/dimitri/bugzilla/attachments//bug619728_162025_doxygen_1.6.3-20100507_cs_extension_fix.patch)_ (ID 162025)

On 2010-05-26 15:26:27 +0000, Vsevolod Kukol wrote:

> Created attachment 162024
> patch to rename c# parser to csharp, so it gets recognized in EXTENSION_MAPPING
> 
> I'm working on a new VB.NET filter and wanted to generate C# code.
> Therefor I had to map *.vb files to the C# parser, but it doesn't work.
> 
> Configuration:
> 
> EXTENSION_MAPPING      = .vb=C#
> FILE_PATTERNS          = *.vb
> OPTIMIZE_OUTPUT_JAVA   = YES
> EXTRACT_ALL            = YES
> 
> With *.cs files renamed to *.vb Doxygen still uses the default C parser configuration.
> 
> After a closer look at the code, I've found several problems with this configuration.
> 
> 1. EXTENSION_MAPPING = .vb=C# can't work, because the "#" is recognized as a comment.
> I've patched the util.cpp to use "csharp" insted of "c#".
> 
> 2. there are some lines with a hrdcoded detection of *.cs files.
> docparser.cpp 4984
> filedef.cpp   96   (BTW: line 95 for Java as well, bug 567774)
> pre.l         134
> 
> applying attached patches solves this problem.

On 2010-05-26 15:27:25 +0000, Vsevolod Kukol wrote:

> Created attachment 162025
> fix hardcoded checks for *.cs extension

On 2010-06-04 16:02:01 +0000, Dimitri van Heesch wrote:

> Thanks for the reminder Vsevolod, I'll include your patches in the next release.

On 2010-06-15 11:22:09 +0000, Dimitri van Heesch wrote:

> This bug was previously marked ASSIGNED, which means it should be fixed in
> doxygen version 1.7.0. Please verify if this is indeed the case. Reopen the
> bug if you think it is not fixed and please include any additional information
> that you think can be relevant.

On 2011-10-05 12:23:02 +0000, Patrick Kursawe wrote:

> Please reopen this bug until you have fixed the documentation. There is not even a slight hint that you have to write "csharp" instead of "C#".

On 2011-10-05 12:31:52 +0000, Patrick Kursawe wrote:

> (In reply to comment # 4)
> > Please reopen this bug until you have fixed the documentation. There is not
> > even a slight hint that you have to write "csharp" instead of "C#".
> 
> To be more precise, config.html#cfg_extension_mapping gives no hint.
> The help of the GUI frontend has a different problem: It lists C and C++ twice.

**Comment by albert-github** [comment]
Regarding the lasy 2 remarks:
- double mentioning of C / C++ was already corrected
- incorrect mentioning of c#, I've just pushed a proposed patch, pull request #6397

**Comment by albert-github** [comment]
Pull request #6397 integrated.
