### ISSUE TITLE
HtmlHelp (chm) shows wrong main page when tag files are used (Origin: bugzilla #620571)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3791]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.6.3* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[Example.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug620571_162754_Example.zip/download/download)_ (ID 162754)

On 2010-06-04 13:46:30 +0000, csuehara@gmail.com wrote:

    Created attachment 162754
    Example source and doxyfiles that show the tagfile project's main.html in
    the generated .chm file
    
    Generate documentation that uses a tagfile with .chm generation. If we have
    the following structure:
    
    proj1/
    proj2/
    doc/proj1/HTML
    doc/proj2/HTML
    
    and the doxyfile in src/proj1 includes:
    
    GENERATE_HTMLHELP = YES
    TAGFILES = ../doc/proj2/proj2.tag=../../../../proj2/html
    
    opening doc/proj1/HTML/proj1.chm will show doc/proj2/main.html as its main
    page. The generated html files for proj1 are correct (i.e.,
    doc/proj1/HTML/main.html shows the main page for proj1).

**Comment by albert-github** [comment]
With the 1.6.3. version we indeed see:

![image](https://user-images.githubusercontent.com/5223533/162443394-37ea366c-9c66-4baa-8d8a-b7a8892fdb7f.png)

With the 1.9.3 (c0b9eafbfb53286ce31e75e2b6c976ee4d345473) version we see:

![image](https://user-images.githubusercontent.com/5223533/162443541-f57a57e5-bd2e-4c6e-ae01-a4d9222dc572.png)

so we properly refer to the other output.


So I think the problem has been solved in the mean time.
