### ISSUE TITLE
\relates does not find class if it is in an anonymous namespace (Origin: bugzilla #621171)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3798]
status NEW severity *minor* in component *general* for *---*
Reported in version *1.6.3* on platform *Other*
Assigned to: Dimitri van Heesch

On 2010-06-10 07:47:09 +0000, christian.kotz@gmx.net wrote:

    Test case:
    place a class and and a binary operator== or that class in an anonymous
    namespace and document the operator== with tag \relates.
    
    Note: the usual workaround to use a full qualified name in the \relates
    clause does not work, because the full qualified name of a class in an
    anonymous namespace cannot be spelled out.
    
    Example:
            namespace
            {
    
                class Get_X
                {
    ...
                };
    
                // Doxygen has problems to find class in anonymous namespace
                ///\relates Get_X
                inline
                bool operator==(Get_X const & a, Get_X const & b)
                {
                    return a.equal(b);
                }
           }

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #9743

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.6.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
