### ISSUE TITLE
subgroups are incorrect in html output (Origin: bugzilla #622643)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3821]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.7.0* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[Doxytest.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug622643_164535_Doxytest.zip/download/download)_ (ID 164535)

On 2010-06-24 18:04:51 +0000, christof hahn wrote:

    Created attachment 164535
    test for the problem
    
    by creating subgroups like
    
    @defgroup X
    {@
    
    @defgroup X2...
     
    The Html-Output is inkrorekt. X2 will be added twice in the treeview like:
    
      X
       - X2
      X2
    
    In the doxygentestfile in the added zip-file i've made a short demo of the
    problem. The File copy.png shows a screenshot of the generatet html-output.
    Whitch is generated was doxygen 1.7 and the full.doxyfile. The Module
    Zusatzlibraries is two times in the output.

On 2010-07-19 16:46:50 +0000, christof hahn wrote:

    !!! CH: Change to Critical, because doxygen can not be stable!!!

On 2010-07-19 18:31:38 +0000, Dimitri van Heesch wrote:

    A critical bug is something that crashes doxygen, crashes your OS, or
    destroys your data. What you see is merely a render bug, annoying perhaps,
    but not critical.

**Comment by albert-github** [comment]
The usage of the `\defgroup` and  `\{` ... `\}` constructs is quite sensitive and the results were not to bad although there were some errors in the code.
There are 2 types of problems:
- usage if comment, `/*@{*/` is not a doxygen type of comment
- sensitivity of the usage of `@{`

We see in the code constructs like:
```
/** @defgroup hal 1 HAL Hardware Abstraktion Layer
  * @brief Basisschicht. Stellt die untersten, meist hardwareabhängigen, Programmteile bereit, die nötig sind,
  *        das Betriebssystem zu starten.
  */
/*@{*/
```

```
/** @defgroup hal 1 HAL Hardware Abstraktion Layer
  * @brief Basisschicht. Stellt die untersten, meist hardwareabhängigen, Programmteile bereit, die nötig sind,
  *        das Betriebssystem zu starten.
  * @{ */
```

Doing this for all the `@{` constructs leads, in my opinion, to the right output.

I think the problems come from usage.
