### ISSUE TITLE
bitmaps for formulas in HTML cannot be generated with xelatex ! (Origin: bugzilla #625339)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3868]
status NEW severity *normal* in component *build* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2010-07-26 17:14:40 +0000, lisonic.g@gmail.com wrote:

    I've just installed doxygen 1.7.1 and noticed a problem in generating the
    png files from formulas for HTML with xelatex.
    
      With Latex_cmd_name setted xelatex, I got information as follows:
          Output written on _formulas.pdf (2 pages)
          Transcript written on _formulas.log
          Generating image form_0.png for formula
          dvips: DVI file can't be opened: _formulas.dvi: No such files or
    directory.
    
      As we all know, xelatex generate *.pdf directly without *.dvi for
    translating, while the png files for formulas will allways generated from
    the *.dvi as generated by latex or pdflatex. This is not a serious problem,
    but indeed inconvenient for xelatex users for CJK-compatibility.
      
      Best regards!

**Comment by albert-github** [comment]
In the version 1.8.14 version this problem is still present.
In the current master version the problem has been solved.

I think the problem can be set to `fixed but not released`

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
