### ISSUE TITLE
Function overloads are not actually sorted in member function list (Origin: bugzilla #626582)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3897]
status NEW severity *enhancement* in component *documentation* for *---*
Reported in version *1.7.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[test.h](https://sourceforge.net/projects/doxygen/files/attachments/bug626582_167550_test.h/download/download)_ (ID 167550)

On 2010-08-10 23:31:54 +0000, Travis Vitek wrote:

    The SORT_MEMBER_DOCS flag description indicates that it should force member
    functions to appear in sorted order in the member function list. This
    appears to work for functions with unique names, but it does not appear to
    work for function overloads.
    
    The attached testcase will illustrate the problem with both doxygen-1.6.2
    and doxygen-1.7.1. Here is the member function list generated...
    
      virtual void get (F *v)=0
      virtual void get (C *v)=0
      virtual void get (B *v)=0
      virtual void get (A *v)=0
      virtual void get (E *v)=0
      virtual void get (D *v)=0
      virtual void getString (G *s)=0
    
    It would be nice if the overloads appeared in sorted order (including the
    parameter type names).
    
      virtual void get (A *v)=0
      virtual void get (B *v)=0
      virtual void get (C *v)=0
      virtual void get (D *v)=0
      virtual void get (E *v)=0
      virtual void get (F *v)=0
      virtual void getString (G *s)=0

On 2010-08-10 23:34:00 +0000, Travis Vitek wrote:

    Created attachment 167550
    Testcase

On 2010-08-10 23:53:33 +0000, Travis Vitek wrote:

    My comment above about the member function list being in sorted order is
    wrong. The description actually says...
    
      If the SORT_MEMBER_DOCS tag is set to YES (the default) then
      doxygen will sort the (detailed) documentation of file and
      class members alphabetically by member name. If set to NO the
      members will appear in declaration order.
    
    The list of detailed descriptions is not sorted either. I actually get
    different results between doxygen-1.6.2 and doxygen-1.7.1. The detailed
    descriptions appear in this order with 1.6.2...
    
      virtual void Test::get (D* v)
      virtual void Test::get (E* v)
      virtual void Test::get (A* v)
      virtual void Test::get (B* v)
      virtual void Test::get (C* v)
      virtual void Test::get (F* v)
      virtual void Test::getString(G* s)
    
    And they appear in this order with 1.7.1...
    
      virtual void Test::get (F* v)
      virtual void Test::get (C* v)
      virtual void Test::get (D* v)
      virtual void Test::get (E* v)
      virtual void Test::get (A* v)
      virtual void Test::get (B* v)
      virtual void Test::getString(G* s)
    
    So, if by '(detailed) documentation', you mean the functions and their
    descriptions (not the function list, but the actual function documentation
    blocks), then this is actually a two bugs (one for the member list and one
    for the detailed documentation), not just one.

**Comment by albert-github** [comment]
've just pushed a proposed patch, pull request #6826

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
