### ISSUE TITLE
single '-' in <pre> busts nesting levels (Origin: bugzilla #628022)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3917]
status NEW severity *normal* in component *documentation* for *---*
Reported in version *1.7.2-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[ipa3a.f](https://sourceforge.net/projects/doxygen/files/attachments/bug628022_168796_ipa3a.f/download/download)_ (ID 168796)
- _[ipa3a.f](https://sourceforge.net/projects/doxygen/files/attachments/bug628022_168797_ipa3a.f/download/download)_ (ID 168797)

On 2010-08-26 10:02:55 +0000, Julika wrote:

    Created attachment 168796
    Fortran example source
    
    Dear doxygen support,
    
    attached you can find a short fortran example.
    If I call doxygen for this file I get the following warnings:
    
    Warning: found </pre> tag while expecting </pre>
    Warning: end of comment block while expecting command </pre>
    
    As you can see in the example the order of pre is correct.
    It has something to do with the contents of the pre area.
    If I delete the lines the warnings disapear.
    Which characters are the problem of this warnings?
    
    best regards,
    Julika Burger

On 2010-08-26 10:04:25 +0000, Julika wrote:

    Created attachment 168797
    correct attachment
    
    first example is wrong

On 2010-08-26 10:06:11 +0000, Julika wrote:

    Comment on attachment 168796
    Fortran example source
    
    the first example source is wrong

On 2010-12-21 02:20:40 +0000, Daniel Franke wrote:

    Confirmed, but not fortran specific.
    Small testcase for C (the '-' being the culprit):
    
    /**
     * <pre>
     *    -
     * </pre>
     */
    void foo() {}
    
    warning: found </pre> at different nesting level (5) than expected (2)
    warning: end of comment block while expecting command </pre>

On 2010-12-21 18:15:27 +0000, Dimitri van Heesch wrote:

    The - is a special command that starts a list. Inside the first list element
    there is a </pre> command which is unexpected, hence the warning.
    
    Maybe it would be possible in such cases for the parser to end the list, and
    continue evaluating the </pre> in the parent's scope, which would at least
    prevent the warning in this case.

On 2011-01-10 08:20:00 +0000, Julika wrote:

    ah ok, thanks for the explaination!
    So it should help to add a empty line before the </pre> tag!

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #9933

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.7.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
