### ISSUE TITLE
Parenthesized function names result in incorrect generated documentation (Origin: bugzilla #629200)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3933]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2010-09-09 18:09:45 +0000, Travis Vitek wrote:

    Given the following testcase:
    
    #if !defined(DOXYGEN)
       // some compilers #define macros min and max in their system
       // headers. fake that here for illustration.
    #  define min(x,y) ((x) < (y) ? (x) : (y))
    #  define max(x,y) ((y) < (x) ? (x) : (y))
    #endif
    
    /**
     * Integer.
     */
    struct Integer
    {
        // the parens around min and max below are used to prevent the
        // preprocessor from expanding the names as macros. this is
        // required so that the code will compile on systems that have
        // macros for min and max.
    
        /**
         * Returns the minimum of self or other.
         */
        Integer (min)(const Integer& other) const;
    
        /**
         * Returns the maximum of self or other.
         */
        Integer (max)(const Integer& other) const;
    };
    
    Doxygen will generate the following html...
    
    Member Function Documentation
    
      Integer() Integer::max(const Integer& other) const
      Returns the maximum of self or other.
    
      Integer() Integer::min(const Integer& other) const
      Returns the minimum of self or other.
    
    Notice that the return type appears as if it were a function taking no
    arguments and returning Integer? This is incorrect. The return type is just
    Integer.
    
    The workaround we have is to #define a helper macro to strip the parens when
    using doxygen.
    
    #if defined(DOXYGEN)
    #  define PREVENT_MACRO_EXPANSION(x) x
    #else
    #  define PREVENT_MACRO_EXPANSION(x) (x)
    #endif
    
    It isn't pretty, but it does the trick.

**Comment by albert-github** [comment]
With doxygen 1.7.1 we see:
![image](https://github.com/user-attachments/assets/528195a5-e4c6-4da5-81ea-784af87a3302)

With the current 1.12.0 doxygen version we see:
![image](https://github.com/user-attachments/assets/05f54565-ed38-434e-a223-4889631e0f50)

so the `()` are gone.

I think the problem has been solved in the mean time.
