### ISSUE TITLE
Highlighting lines in a dot graph (Origin: bugzilla #630661)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3952]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.7.1-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2010-09-26 20:01:00 +0000, albert wrote:

    In complex dot graphs it is often hard to see where all the lines go. It
    would be nice to have a possibility to highlight these lines, i.e if one
    hovers over the box of a function all lines leaving and entering this
    function should be highlighted.
    Another directly connected item is that if one hovers over a line the line
    should be highlighted so it is easier to follow this line.
    
    It is suggested to use the separate program zgrviewer
    (http://zvtm.sourceforge.net/zgrviewer.html) to view the dot files. The
    following measures have to be taken:
    -	Java runtime has to be present
    -	The item DOT_CLEANUP in the Doxyfile has to be set to NO.
    -   The dot executable has to be in the path (i.e. the Graphviz binary
    directory).
    
    It would be nice if the functionality of the zgrviewer would be incorporated
    in the Doxygen output.

**Comment by albert-github** [comment]
Some remarks about the current status (1.9.7 (19420b7ae5fb764654df9d949d62429ae1432df2)):
- since version 1.8.4 edges are highlighted (in red) in graphs that are "interactive svg" graphs i.e. `INTERACTIVE_SVG = YES` and graphs are "large / complex enough" when hovered over.

Some future work:
- make an edge graphs highlighted when `INTERACTIVE_SVG = YES` independent of its size /complexity
- make nodes highlighted when hovered over
- make connected edges highlighted when hovered over a node

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #9974 

@doxygen "make an edge graphs highlighted when INTERACTIVE_SVG = YES independent of its size /complexity" is this an enhancement that also should be implemented?

**Comment by doxygen** [comment]
@albert-github I think this could be useful as well. Of course, it is more useful for complexer graphs, but also for graphs without navigation aids, the highlighting is still a nice feature.

**Comment by albert-github** [comment]
Code of #9974 has been integrated in master on GitHub

**Comment by albert-github** [comment]
For the "simple" graphs I've just pushed a proposed patch, pull request #9982

**Comment by albert-github** [comment]
Code of #9982 has been integrated in master on GitHub.

 (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.7.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
