### ISSUE TITLE
nest namespaces not handled properly (Origin: bugzilla #630747)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3954]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[NestedNamespace.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug630747_171224_NestedNamespace.zip/download/download)_ (ID 171224)

On 2010-09-27 17:29:35 +0000, Carl R. Werth wrote:

    Created attachment 171224
    doxygen configuration file and source files a.h/a.cpp
    
    The nested statement "namespace X {namespace Y {" is not recognized as
    namespace X::Y.
    
    An example is attached to this bug.
    
    a.h:
    namespace X {namespace Y {
    {
        class A
        {
        public:
            int a();
        };
    }}}
    
    a.cpp:
    using namespace X::Y;
    
    /** Method of A. */
    int A::a()
    { return 0; }
    
    
    --> warning: documented function `int A::a' was not declared or defined.

On 2010-09-27 17:46:02 +0000, Carl R. Werth wrote:

    This seems to be the same bug as  # 151959, but I don't know how to reopen
    that old bug.

**Comment by albert-github** [comment]
The problem here comes from the extra set of curly brackets around the class definition.
When they are removed the problem goes away.

I'm not sure whether this is usage or not.

**Comment by doxygen** [comment]
running the example through g++ gives:

```
$ g++ -Wall -c test.cpp 
test.cpp:2:1: error: expected unqualified-id
{
^
1 error generated.
```
so it is invalid C++.
