### ISSUE TITLE
\cond after @string literal containing backslash fails in C# (Origin: bugzilla #630931)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3958]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.7.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2010-09-29 18:54:49 +0000, Jon Bradley wrote:

     class Program
     {
         static void Main(string[] args)
         {
         }
         /// <summary>
         /// Returns two, always.
         /// </summary>
         /// <returns></returns>
         public int getDeuce()
         {
             return 2;
         }
         //note the @"literal" string, with a slash in it.
         public string x = @"\hello\";
 
         /// \cond DEVELOPER
 
         /// <summary>
         ///  This returns 3 but you should never see it
         /// </summary>
         /// <returns></returns>
         
         public int blaBlah()
         {
             return 3; 
         }
         /// \endcond 
     }

 
    
    
    Yields  warning: Found unknown command `\cond'
    
    This is probably another symptom of the problem pointed at by bug # 628495

On 2018-06-18 12:45:56 +0000, albert wrote:

    I've just pushed a proposed patch to github (pull request 770,
    https://github.com/doxygen/doxygen/pull/770).

**Comment by albert-github** [comment]
Code has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
