### ISSUE TITLE
Doxygen produces wrong LaTeX code for \dot graphics (Origin: bugzilla #631090)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3961]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2010-10-01 12:43:45 +0000, slxviper@yahoo.de wrote:

    When using the \dot command doxygen outputs
    "\includegrapchics{inline_dotgraph_X}". Many graphics are quite large and
    won't fit nicely in the final document but will be cropped if they are too
    large for the page. The INCLUDE_GRAPH graphics are sometimes even larger but
    are scaled correctly, though.
    
    Doxygen should output
    "\includegrapchics[width=\textwidth]{inline_dotgraph_X}" instead. An
    optional "size" parameter like the one \image provides would be a nice
    feature.
    
    A possible but rather ugly workaround until this will be fixed: using
    size="5.87,8.94" (for a4wide paper; for normal a4: size="4.77,8.27") in the
    dot code.

On 2010-10-06 19:19:06 +0000, Dimitri van Heesch wrote:

    Confirmed. For now I'll use [width=\textwidth] until a better way is found.

**Comment by albert-github** [comment]
With the 1.7.1 version the resulting image can overflow the page boundary.
With the 1.9.2 version the resulting image will be scaled down. Furthermore the `\dot` command has the possibility of "size indicators".

I think the problem has been solved in the mean time.
