### ISSUE TITLE
\htmlinclude in \brief not included in brief section but in details (Origin: bugzilla #631094)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3962]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.1-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2010-10-01 13:29:17 +0000, Jukka Partanen wrote:

    Example fragment:
    
    /** @file
    * \brief \htmlinclude block_aim/description.txt
    *
    * \htmlinclude result_help.txt
    * \verbinclude block_aim/auto_result.txt
    */
    
    In versions up to 1.5.4 (Debian) above fragment caused Doxygen to put text
    from given file to brief descriptions on the files page. In later versions
    (tried 1.5.5, 1.5.6, 1.7.1 and svn trunk) the included text does not appear
    on the brief listings, but in the details. Like \htmlinclude always ends the
    \brief.
    
    I could not find anything in the Changelog and in the manual that this
    change in behavior has been intentional. I also couldn't find any
    configuration option that affects the behavior.
    
    We have been using Doxygen successfully in maybe a little creative way to
    annotate the files listing page of test code with additional information
    from our test framework. We have found that feature very useful and are thus
    also using it a lot. Please consider restoring the functionality.

**Comment by albert-github** [comment]
When running version 1.71 (and some earlier versions) on the example the message:

`warning: included file block_aim/description.txt is not found. Check your EXAMPLE_PATH`


is given (although the the `EXAMPLE_PATH` is set and the file `block_aim/description.txt` exists).
In version 1.7.2 and .8.14 the message is not given and the brief text is shown at the 'brief' place.

I think the problem has been solved in the mean time.
