### ISSUE TITLE
brief description lost when same as detailed description (Origin: bugzilla #631429)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3965]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxygen_bug_new.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug631429_171771_doxygen_bug_new.zip/download/download)_ (ID 171771)

On 2010-10-05 14:20:48 +0000, Mark Courtney wrote:

    Created attachment 171771
    Source code, doxygen configurations, and output for reproducing.
    
    Given the following code where a brief description is explicitly specified
    even though it is the same as the detailed description:
    
    /// @brief Description here.
    /// 
    /// Description here.
    void func();
    
    The brief description does not appear in the Doxygen output, likely because
    it is flagged as duplicating the detailed description.
    
    Since it is explicitly specified, it should appear in the output as the
    brief description. (The detailed description should continue to appear as it
    currently does.)
    
    This change appears to have been introduced in Doxygen version 1.5.9 since
    prior versions worked as expected.

**Comment by albert-github** [comment]
When running version 1.5.8 the brief description was present, with the versions 1.5.9 and 1.7.1 it was gone but with version 1.8.14 it was present again.

I think the problem has been solved in the mean time.
