### ISSUE TITLE
Many Java Generics arguments messes up the generated documentation (Origin: bugzilla #632028)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3970]
status NEEDINFO severity *enhancement* in component *documentation* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2010-10-13 05:37:41 +0000, Jimmy wrote:

    When using Java classes with long generic arguments the HTML documentation
    generated could be a real mess.
    See demo: http://usoog.com/api/tdcore/annotated.html
    Click any messy class for more messy pages ;)
    
    There are a few ways to solve this by adding some new settings:
     1. Hide the generic arguments except for on the actual class documentation.
     2. Hide the extends part of the arguments, as suggested by Dimitri van
    Heesch. The longer descriptions could be placed at the parameter
    documentation under "Detailed Description".
    
    I personally would like to see the second solution. It might not be perfect
    but it will make it a little cleaner.

On 2013-07-28 11:46:05 +0000, albert wrote:

    I cannot access the given link (html message 403 forbidden).
    
    If you still see this issue with the latest version of doxygen. Add a self-
    contained example (source+config file in a zip or tar) if possible.

**Comment by albert-github** [comment]
It is a bit unclear what is wrong and as no example is provided it is hard to guess to.

Setting issue to incomplete.
