### ISSUE TITLE
If INPUT_FILTER used to insert groups and INLINE_SOURCES = YES and FILTER_SOURCE_FILES = NO, inline source blocks corrupted (Origin: bugzilla #632089)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3975]
status NEW severity *major* in component *general* for *---*
Reported in version *1.7.2* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxbug.rar](https://sourceforge.net/projects/doxygen/files/attachments/bug632089_172298_doxbug.rar/download/download)_ (ID 172298)

On 2010-10-13 19:35:55 +0000, maaltan wrote:

    Created attachment 172298
    example source + output
    
    if INPUT_FILTER used to insert grouping comments and INLINE_SOURCES = YES
    and FILTER_SOURCE_FILES = NO, inline source blocks are
    misaligned/truncated/etc.
    
    Once FILTER_SOURCE_FILES is set to YES, everything appears to work properly.
    
    You can see this behavior in the attached file located at:
    out/html/d0/df8/group__component.htm
    
    In my small example, it is only truncating the methods.  Things get more
    dramatic if applied to a CPP file with lots of methods.
    
    From glancing at definition.cpp->readCodeFragment(..), it appears that it
    assuming that the file line numbers are the same as the initially processed.
    the filter needs to be run at this phase also so that everything lines up.
    (enabled by FILTER_SOURCE_FILES ).
    
    This may just be a documentation issue (clarify the usage of
    FILTER_SOURCE_FILES ), but the behavior is definitely unexpected.
    
    This also occurs at least as far back as 1.7.0

On 2010-10-13 19:41:37 +0000, maaltan wrote:

    (just noticed that doxygen threw an warning about EOF before end of group in
    the rar file.  doxygen is very picky when the end tag is inserted via input
    filter for some reason.  This does not affect the issue reported, but may be
    a bug in and of itself(a minor one))

On 2012-01-18 20:09:12 +0000, Robb Surridge wrote:

    I ran into exactly the same problem.
    
    Suggested fix options:
    a) Always filter the source file if INLINE_SOURCES is on. In definition.cpp
    line 544, set
      static bool filterSourceFiles = Config_getBool("FILTER_SOURCE_FILES") |
    Config_getBool("INLINE_SOURCES");
    
    or
    
    b) Just mention in the documentation of INPUT_FILTER and INLINE_SOURCES that
    if your filter adds newlines to the output, you must also set
    FILTER_SOURCE_FILES to true so that the implementations will be retrieved
    from the right places in the headers.

**Comment by albert-github** [comment]
The main problem of the filter is that it inserts newlines by means of:
```
my $component = '\n/*! \addtogroup component '."\n".'*  @{'."\n".'*/\n\n';

my $end = '\n/*! \@}*/\n';
```
and the  resulting write"
```
print $component.$text.$end;
```
some  help can be obtained by the mentioned `FILTER_SOURCE_FILES` but this is apparently not sufficient.

A better solution is to use the internal doxygen command `\ilinebr` (this command was not yet available at the moment that the issue was created). Th e`\ilinebr` will act as a  `\n` in the parsing but won't  advance line counters.
the settings in the filter would become:
```
my $component = '\\ilinebr /*! \addtogroup component '."\\ilinebr ".'*  @{'."\\ilinebr ".'*/\\ilinebr \\ilinebr ';

my $end = '\\ilinebr /*! \@}*/\\ilinebr ';
```

Seen this solution I think the problem is solved in the mean time and now is usage.
