### ISSUE TITLE
doxygen should not ignore class declarations otherwise argument matching can fail (Origin: bugzilla #632193)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3978]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2010-10-15 05:59:09 +0000, Craig Scott wrote:

    See the following code sample:
    
    namespace NS_A { class Foo; }
    namespace NS_B {
        /**
         * \brief Blah
         */
        struct Bar
        {
            void  func(NS_A::Foo& foo);
        };
    
        using namespace NS_A;
        
        /**
         * \param foo  Stuff
         */
        void  Bar::func(Foo& foo) {}
    }
    
    
    Doxygen complains with:
    
    /somepath/funcs.cpp:16: warning: no matching class member found for 
      void NS_B::Bar::func(Foo &foo)
    Possible candidates:
      void NS_B::Bar::func(NS_A::Foo &foo)
    
    This code sample is valid and compiles, it's just that doxygen is not
    finding Foo in NS_A after the using namespace directive.

On 2011-01-02 13:42:25 +0000, Dimitri van Heesch wrote:

    Problem with the example is not the using directive, but the fact that Foo
    is only declared, not defined and doxygen basically ignores forward
    declarations.
    
    If you use
    
    namespace NS_A { class Foo {}; }
    
    instead, it will work.

On 2011-01-02 23:27:26 +0000, Craig Scott wrote:

    It would be a concern if it did work for doxygen given that doxygen would be
    getting presented with two different definitions for NS_A::Foo, one with the
    actual definition of Foo (in a separate file to the example above) and one
    with Foo having an empty definition in place of the real Foo. The only case
    where you could get away with it is if Foo is defined in a header that
    doxygen never sees. In that case, there would be no error, but the
    documentation generated would still have misleading information about Foo by
    making the user think it is an empty class when in fact it might not (and
    typically won't) be an empty class.

**Comment by albert-github** [comment]
With the doxygen 1.7.1 version I get the warnings as indicated. With the current doxygen version 1.9.6 the warnings are gone.

I think the problem has been solved in the mean time.
