### ISSUE TITLE
The \copydoc Command Requires The Use of C++ Syntax in C# Code (Origin: bugzilla #632754)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3987]
status NEW severity *normal* in component *general* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2010-10-21 02:02:20 +0000, Bradley Ward wrote:

    I use Doxygen to document my C# code. I tried to use the following copydoc
    command, but it did not work:
    
    \copydoc Fully.Qualified.ClassName
    
    At Dimitri's suggestion, I tried using C++ syntax and it worked:
    
    \copydoc Fully::Qualified::ClassName 
    
    The bug is that on this particular command, you cannot use the appropriate
    syntax for C#. Other commands with virtually idental syntax (like \see
    Fully.Qualified.ClassName) work fine.
    
    Thanks Dimitri!

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7042

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
