### ISSUE TITLE
Doxygen does not properly handle anonymous arguments in C (Origin: bugzilla #632796)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3988]
status NEW severity *minor* in component *general* for *---*
Reported in version *1.7.2* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[ap.cpp](https://sourceforge.net/projects/doxygen/files/attachments/bug632796_172938_ap.cpp/download/download)_ (ID 172938)
- _[Doxyfile](https://sourceforge.net/projects/doxygen/files/attachments/bug632796_172939_Doxyfile/download/download)_ (ID 172939)

On 2010-10-21 13:59:29 +0000, Gilles wrote:

    Created attachment 172938
    Sample source
    
    When one has a function that does not use its argument, the C-compilers
    issue a warning.  To avoid the warning, the easiest solution is to leave out
    the argument name.  Doxygen sometimes handles this properly, and sometimes
    not:
    
    int func3(int p1, const char * /*p2*/)
    is properly handled by Doxygen. While
    
    int func1(int p1, char * const /*p2*/)
    is not properly handled. one gets:
    ap.cpp:8: warning: The following parameters of func1(int p1, char *const)
    are not documented:
      parameter 'const'
    
    Attached are a sample file that contains a kludgy workaround for the issue.
    But since Doxygen can handle some of the case one could hope that it could
    handle more.
    
    Thanks
    Gilles

On 2010-10-21 14:00:21 +0000, Gilles wrote:

    Created attachment 172939
    Doxyfile for test

On 2010-10-21 14:00:47 +0000, Gilles wrote:

    The issue is observed with 1.5.6 and 1.7.2

**Comment by albert-github** [comment]
Code has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
