### ISSUE TITLE
Reference to a value of array of typedef is not highlighted. (Origin: bugzilla #633633)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3997]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.7.2* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[func.c](https://sourceforge.net/projects/doxygen/files/attachments/bug633633_173594_func.c/download/download)_ (ID 173594)

On 2010-10-31 13:29:38 +0000, lovelylovelyflora@ab.auone-net.jp wrote:

    00001 typedef struct {int v1; int v2;} v1v2_t;
    00002 
    00003 int var0;
    00004 v1v2_t var1[10];  /*** array of typedef ***/
    00005 int var2[10];
    00006 struct {int v1; int v2;} var3[10];
    00007 
    00008 int func()
    00009 {
    00010    var0 = 1;
    00011    var1[0].v1 = 2; /*** var1 is NOT HIGHLIGHTED ****/  
    00012    var2[0] = 2;     
    00013    var3[0].v1 = 2;
    00014    return 0;
    00015 }
    00016

On 2010-10-31 13:33:26 +0000, lovelylovelyflora@ab.auone-net.jp wrote:

    Created attachment 173594
    A source code to reproduce the issue

**Comment by albert-github** [comment]
When using version 1.7.2 `var1`  inside the function `func` was not hyperlinked (despite setting all `EXTRACT_...` to `YES`).
With version 1.8.14 the variable as hyperlinked.

I think the problem has been solved in the mean time.
