### ISSUE TITLE
Add support to list supported values for parameters (Origin: bugzilla #634222)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4007]
status NEW severity *enhancement* in component *build* for *---*
Reported in version *1.7.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2010-11-07 15:13:08 +0000, axos88@gmail.com wrote:

    It would be nice to be able to docuemnt constraints on the parameters, in a
    more standard way, instead of doing:
    
    /***
    ....
     *  @param con Connection status
     *  <ul>
     *  <li> 0 - Disconnect
     *  <li> 1 - Connect
     *  </ul>
    */
    
    Be able to do something like
    
     @param con Connection status
     @paramvalue 0 - Disconnect
     @paramvalue 1 - Connect
    
    This applied to cases where parameters are actually bitfields, like
      @param EPAddr Endpoint Address
      @paramvalue [0..3] Endpoint Logical Address
      @paramvalue [7] Endpoint Direction
      
      @return Endpoint Physical Address

**Comment by albert-github** [comment]
With the command `\return` there is also the command `\retval` so a similar construct for `\param` could be an idea as well though the mentioned syntax has the flaw that it is not known to which parameter the value belongs. This could be overcome by means of a syntax line
```
\paramval <var_id> <value_string> <description>
```

In the example the construct with `<ul>` etc. is used., it is possible to use:
```
/***
....
 *  @param con Connection status
 *  - 0 - Disconnect
 *  - 1 - Connect
*/
```

Advantage of a `\paramval` command would be that some nicer layout / table layout is possible.

Another construct would be by means of `ALIASES`, 2 examples, one with a markdown table and one with a standard HTML table:
The `ALIASES`:
```
ALIASES += paramvalstart1="|value|Description| ^^ | --- | ---|"
ALIASES += paramval1{2}="|\1|\2|"
ALIASES += paramvalstart2="<table> ^^ <tr><th> Value </th><th> Description </th></tr>"
ALIASES += paramval2{2}=" <tr>    <td> \1 \ilinebr </td> <td> \2 </td>  </tr>"
ALIASES += paramvalend2="</table>"
```
the source code:
```
void fie1(int con);
/**
 *  @param con Connection status
 *  \paramvalstart1
 *  \paramval1{0,Disconnect}
 *  \paramval1{1,Connect}
*/
void fie2(int con);
/**
 *  @param con Connection status
 *  \paramvalstart2
 *  \paramval2{0,Disconnect}
 *  \paramval2{1,Connect}
 *  \paramvalend2
*/
void fie3(int con);
```
Advantages here are that specific fine tuning can be done specifying certain attributes by the user.

Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/6902472/example.tar.gz)

@doxygen do you think this covers the complete issue here or should there still be a dedicated `\paramval` command (with the proposed syntax with 3 elements)?

**Comment by albert-github** [comment]
Revisiting this issue I think that given the examples this gives enough possibilities to have a flexible way to support parameter values.

So I think we can categorize this issue as usage.
