### ISSUE TITLE
Automatic links don't work correctly with operator< and operator<= (Origin: bugzilla #634830)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4013]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.2* on platform *Other*
Assigned to: Dimitri van Heesch

On 2010-11-14 16:51:48 +0000, Cleo Saulnier wrote:

    Here is some sample code.
    
    -------------------------
    //! LessThan Operator (\ref forwardcontainer)
    /*!
      \param left first list to compare
      \param right second list to compare
      \return true if left is less than right.  false, otherwise.
    */
    template <class T, class R>
    bool operator<(const IndexedSkipList<T,R> &left, const IndexedSkipList<T,R>
    &right)
    {
      return
    lexicographical_compare(left.begin(),left.end(),right.begin(),right.end(),left.value_comp());
    }
    
    //! LessThanOrEqual Operator (\ref forwardcontainer)
    /*!
      \param left first list to compare
      \param right second list to compare
      \return true if left is less than or equal to right.  false, otherwise.
    */
    template <class T, class R>
    bool operator<=(const IndexedSkipList<T,R> &left, const IndexedSkipList<T,R>
    &right)
    {
      return !(right < left);
    }
    --------------
    
    The first argument type (for left) in each function is not automatically
    linked.  The second argument type (for right) is linked correctly so that if
    you click on it, it goes to the class docs for IndexedSkipList.  I think
    it's the < sign from operator< and the closing > at the end of the type of
    the first parameter closes it.
    
    As a side-bug, types that have multiple < and > brackets are not matched
    correctly.  Doxygen takes the first closing bracket.  It's fine in most
    cases because you can always click on the name and first part of the type.
    But it looks weird.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6430

**Comment by albert-github** [comment]
Code has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
