### ISSUE TITLE
Doxygen does not recognize external statements for functions in fixed format code (Origin: bugzilla #635232)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4024]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.2* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxygen-1.7.1-external.patch](https://sourceforge.net/projects/doxygen/files/attachments/bug635232_174816_doxygen-1.7.1-external.patch/download/download)_ (ID 174816)

On 2010-11-19 00:55:26 +0000, bnorman@kent.edu wrote:

    Created attachment 174816
    Patch src/fortrancode.l to recognize and link externally defined functions
    
    We are using Doxygen in a large codebase of fixed-format F77 code.  Doxygen
    would not generate links to any functions (subroutines were fine), even when
    they were declared with external statements (because they were first
    classified as local variables due to the type declaration).  The provided
    patch respects the external statement and generates links for externals
    which are found to be valid functions.  It was made against 1.7.1, but the
    patched file is identical in 1.7.2

On 2012-02-03 13:44:56 +0000, AndrÃ© Klapper wrote:

    Comment on attachment 174816
    Patch src/fortrancode.l to recognize and link externally defined functions
    
    [Setting "patch" flag and correcting mime type so this can actually be
    queried for.]

**Comment by albert-github** [comment]
I created a small example:
```
      !> \file
      !> The fortran file

      !> The subroutine
      subroutine subr
        integer local_var
        integer ext_fie
        external ext_fie


        local_var = ext_fie(5)
      end subroutine

      !> The external function
      integer function ext_fie(inp)
        integer inp
        ext_fie = inp
      end function
```
with the settings:
```
QUIET=YES
SOURCE_BROWSER = YES
STRIP_CODE_COMMENTS = NO
```

With version 1.7.1 there is no link for the call too ext_fie, for 1.8.20 the link is present.
Also the `fortrancode.l` gives some evidence in this direction

I think the problem has been solved in the mean time.

example: [example.tar.gz](https://github.com/doxygen/doxygen/files/5203239/example.tar.gz)
