### ISSUE TITLE
Unable to resolve reference for methods with several parameters in Objective C (Origin: bugzilla #636813)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4044]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.3* on platform *Other*
Assigned to: Dimitri van Heesch

On 2010-12-08 21:27:08 +0000, Matthias Lamoureux wrote:

    For an Objective C method with more than one parameter, for example :
    
    - (void) mySuperMethodWithTheFirstParameter:(NSInteger) aFirstParam
    andASecondParameter:(NSInteger) aSecondParam;
    
    the \ref (@ref) command is unable to resolve the reference, while the \see
    (@see) does.
    
    Example : 
    
    \ref mySuperMethodWithTheFirstParameter:andASecondParameter:
    
    throws the warning :
    
    unable to resolve reference to `mySuperMethodWithTheFirstParameter:' for
    \ref command
    
    and doesn't seem to be aware of the second part of the method signature
    contrary to the \see method which resolves correctly the reference.

**Comment by albert-github** [comment]
With the limited information available I still get the link (when I document the function or use `EXTRACT_ALL=YES`) otherwise I get indeed a (logical) warning (tested with doxyggen 1.7.3).

So the issue is either incomplete or it is usage
