### ISSUE TITLE
Handling of Objective-C categories (Origin: bugzilla #638678)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4074]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.3* on platform *Other*
Assigned to: Dimitri van Heesch

On 2011-01-04 17:53:17 +0000, Alan Duncan wrote:

    When documenting Objective-C categories, categories on undocumented base
    classes are documented separately.  This is the expected behavior.
    
    When documenting Objective-C categories on documented base classes, all of
    the category methods are combined with the base class methods.  This makes
    it impossible to discern where methods actually reside when someone reviews
    the documentation.
    
    The expected behavior is for Doxygen to document all Objective-C categories
    as separate entities in the class list.

**Comment by albert-github** [comment]
As no example is given it is hard to see what exactly is meant.

I think the issue is incomplete.
