### ISSUE TITLE
Update README file (Origin: bugzilla #638713)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4076]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.2* on platform *Other*
Assigned to: Dimitri van Heesch

On 2011-01-05 02:56:52 +0000, Perry Smith wrote:

    Currently the readme points the new user to:
    
    It is recommended to also install GraphViz, so doxygen can use the 'dot'
    tool to render better diagrams.
    For installation instruction see http://www.ryandesign.com/graphviz/
    The installer will install dot in /usr/local/graphviz-x.y/bin/dot
    To use dot from within doxygen, set HAVE_DOT to YES and DOT_PATH to
    /usr/local/graphviz-x.y/bin
     (where x.y is the version of graphviz you installed, e.g. 2.14).
    
    GraphViz.org now produces their own Mac version and it installs the commands
    in /usr/local/bin (e.g. /usr/local/bin/dot).  The path to the download page
    is:
    
    http://www.graphviz.org/Download..php
    
    Setting:
    
    DOT_PATH               = /usr/local/bin/dot
    
    and using 2.26 of GraphViz is working for me.

On 2011-01-22 12:08:40 +0000, Dimitri van Heesch wrote:

    Hi Perry,
    
    Which readme are you referring to?

On 2011-03-15 01:26:07 +0000, Fabio DurÃ¡n Verdugo wrote:

    Closing this bug report as no further information has been provided. Please
    feel free to reopen this bug if you can provide the information asked for.
    Thanks!

On 2012-11-18 13:51:27 +0000, Perry Smith wrote:

    I didn't see the request for new data.  I'm sorry about that.
    
    The Readme is called README.rtf inside the Mac .dmg image.  It now reads:
    
    It is recommended to also install GraphViz, so doxygen can use the 'dot'
    tool to render better diagrams.
    See http://www.graphviz.org/Download_macos.php
    To use dot from within doxygen, set HAVE_DOT to YES and DOT_PATH to
    /usr/local/bin
    
    I can't find it in the source tree.  However, while searching, I did
    discover this paragraph in doc/doxywizard_usage.doc (in the source tar
    ball):
    
    Doxygen can produce a number of diagrams. Using the diagrams tab you
    can select which ones to generate. For most diagrams the
    dot tool of the <a href="http://www.graphviz.org">GraphViz</a> package
    is needed (if you use the binary packages for MacOSX this
    tool is already included).
    
    So, perhaps the README.rtf needs to be updated again?

**Comment by albert-github** [comment]
The text of the doxywizard_usage.doc is still as indicated but in the latest release I did find a graphviz version it is in the .Trashes folder and it looks like a bit an old version (2.20.3). As non-Mac user it is hard to see whether or not graphviz is installed or not.

**Comment by albert-github** [comment]
In the mean time (the not yet released version 1.9.0) the text in the doxywizard has been updated and the problem with the `.Trashes` folder has been brought to the attention of @doxygen, so should be fixed in the mentioned release.

The `README.rtf` is a Mac special file and is not in the normal doxygen source tree, but is added during the relase to the Mac release image.

Looking at the `README.rtf` this file looks OK to me.

So I think the problem can be set to solved in the mean time.
