### ISSUE TITLE
Strange XML output when using varargs (Origin: bugzilla #638764)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4078]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.3* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxygen_varargs_xml.tgz](https://sourceforge.net/projects/doxygen/files/attachments/bug638764_177608_doxygen_varargs_xml.tgz/download/download)_ (ID 177608)

On 2011-01-05 19:28:54 +0000, mbolivar@leaflabs.com wrote:

    Created attachment 177608
    Minimal setup to reproduce issue
    
    Doxygen's generated XML output for functions that use varargs is strange and
    harder to parse than it should be.  Here is some example source to use to
    illustrate this behavior:
    
    /**
     * @file varargs_bug.h
     * @brief File for reproducing issue with varargs in XML output
     */
    
    /** f takes a single int argument, then varargs */
    void f(int x ...) {
    }
    
    In the generated XML output for this file, the following appears:
    
            <param>
              <type>int</type>
              <declname>x...</declname>
            </param>
    
    I am not very familiar with the XML schema used by Doxygen, but I would have
    expected something more along the lines of:
    
            <param>
              <type>int</type>
              <declname>x</declname>
            </param>
            <param>
              <type>...</type>
            </param>
    
    I have attached a file (doxygen_varargs_xml.tgz) with a minimal setup for
    reproducing this behavior.
    
    Steps to reproduce:
    1) tar xzf doxygen_varargs_xml.tgz
    2) cd doxygen_varargs_xml
    3) doxygen
    4) cat xml/varargs__bug_8h.xml
    
    The Doxyfile was made by modifying the output of
    
    $ doxygen -s -g Doxyfile
    
    The diff from the file originally output by Doxygen is as follows:
    
    $ doxygen -s -g - | diff -Nu - Doxyfile
    --- -	2011-01-05 14:24:22.000000000 -0500
    +++ Doxyfile	2011-01-05 14:11:27.000000000 -0500
    @@ -126,7 +126,7 @@
#---------------------------------------------------------------------------
     # configuration options related to the HTML output
#---------------------------------------------------------------------------
    -GENERATE_HTML          = YES
    +GENERATE_HTML          = NO
     HTML_OUTPUT            = html
     HTML_FILE_EXTENSION    = .html
     HTML_HEADER            =
    @@ -175,7 +175,7 @@
#---------------------------------------------------------------------------
     # configuration options related to the LaTeX output
#---------------------------------------------------------------------------
    -GENERATE_LATEX         = YES
    +GENERATE_LATEX         = NO
     LATEX_OUTPUT           = latex
     LATEX_CMD_NAME         = latex
     MAKEINDEX_CMD_NAME     = makeindex
    @@ -207,11 +207,11 @@
#---------------------------------------------------------------------------
     # configuration options related to the XML output
#---------------------------------------------------------------------------
    -GENERATE_XML           = NO
    +GENERATE_XML           = YES
     XML_OUTPUT             = xml
     XML_SCHEMA             =
     XML_DTD                =
    -XML_PROGRAMLISTING     = YES
    +XML_PROGRAMLISTING     = NO
#---------------------------------------------------------------------------
     # configuration options for the AutoGen Definitions output
#---------------------------------------------------------------------------
    
    Configuration information:
    
    $ doxygen --version
    1.7.3
    
    I am running the OS X 10.6 Universal Binary distribution obtained here:
    ftp://ftp.stack.nl/pub/users/dimitri/Doxygen-1.7.3.dmg
    
    My machine is running a fully-updated OS X 10.6.5.

**Comment by albert-github** [comment]
As far as I can see the line:
`void f(int x ...) {`
is not correct and should read:
`void f(int x, ...) {`

I think this is usage.
