### ISSUE TITLE
Enum/parameter inconsistent continuation of ///< specifier (Origin: bugzilla #639434)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4089]
status NEW severity *minor* in component *general* for *---*
Reported in version *1.7.3* on platform *Other*
Assigned to: Dimitri van Heesch

On 2011-01-13 16:01:29 +0000, Thad Smith wrote:

    When ///< is used to comment an enumeration constant, a comment continuation
    line must be started with ///.  If ///< used, the extracted comment contains
    "<".
    
    When ///< is used to comment a function parameter, a contuation line must
    started with ///<.  If /// is used, the comment from the continuation line
    is applied to the following parameter:
    void foo(
      a, ///< all about a
         ///  fizzle
      b  ///< all about b
    );
    
    If this form is used the output is 
    Parameters:
       a  all about a
       b  fizzle all about b
    .

**Comment by albert-github** [comment]
I tried to reproduce, with doxygen 1.7.3 and the scarce information present, to reproduce the problem. I was not able to obtain in any way a `<` in the output or garbled documentation in any other way.

Setting issue to not reproducible.
