### ISSUE TITLE
Doxygen misinterprets "struct" and "union" with attributes (Origin: bugzilla #640384)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4104]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.3* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[CCanNode.hpp](https://sourceforge.net/projects/doxygen/files/attachments/bug640384_179134_CCanNode.hpp/download/download)_ (ID 179134)

On 2011-01-24 08:17:16 +0000, boblapique@yahoo.fr wrote:

    Created attachment 179134
    example of a class definition with confusing code.
    
    In the attached class definition, I use structure and union attributes
    "__attribute__ ((__packed__))" with which Doxygen gets confused. It
    interprets the union or struct as a function.

On 2013-08-24 17:14:37 +0000, albert wrote:

    When using the PREDEFINED __attribute__(x)= and setting the right flags for
    MACRO expansion (see in the documentation the chapter about preprocesing)
    the struct and union are not seen anymore as function.
    
    
    Furthermore I think this bug is related to bug_655115 and bug_693529

**Comment by albert-github** [comment]
As noted in the comment before the user has to set:
```
MACRO_EXPANSION        = YES
PREDEFINED             = __attribute__(x)=
```
to get the good result.  See the chapter "Preprocessing" (https://doxygen.nl/manual/preprocessing.html) in the manual.

I think the problem is usage.
