### ISSUE TITLE
Allow arbitrary latex sections in HTML as PNG and concatenation of in-body comments. (Origin: bugzilla #640553)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4108]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2011-01-25 17:07:52 +0000, David Brockley wrote:

    I've been trying to use Doxygen to generate detailed documentation of
    algorithms by putting many comments within the body of a C function. For
    simple stuff, this works ok, however I would like to use one of the LaTeX
    algorithm documentation packages like these
    http://en.wikibooks.org/wiki/LaTeX/Algorithms_and_Pseudocode
    
    I can do this within my function ok:
    
        /**
         * Some preamble.
         *
           \f[
           \]
           \begin{algorithmic}
           \FOR{$i = 0$ \TO $N_1$}
             \IF{ $R_\mathrm{fail}$[i] or $h_\mathrm{fail}$[i] }
               \STATE $d_\mathrm{surf}[i] = \mathrm{unknown}$
             \ENDIF
           \ENDFOR
           \end{algorithmic}
           \[
           \f]
    
         */
    
    However, what I would like to do is break this comment so that the actual C
    code for the for loop is in between. This causes a LaTeX error, even with
    the simple change below:
    
        /**
         * Some preamble.
         *
           \f[
           \]
           \begin{algorithmic}
           \FOR{$i = 0$ \TO $N_1$}
         */
        /**
             \IF{ $R_\mathrm{fail}$[i] or $h_\mathrm{fail}$[i] }
               \STATE $d_\mathrm{surf}[i] = \mathrm{unknown}$
             \ENDIF
           \ENDFOR
           \end{algorithmic}
           \[
           \f]
         */
    
    Gives
    
    
    ! LaTeX Error: Something's wrong--perhaps a missing \item.
    
    See the LaTeX manual or LaTeX Companion for explanation.
    Type  H <return>  for immediate help.
     ...                                              
                                                      
    l.6 ...\mathrm{fail}$[i] or $h_\mathrm{fail}$[i] }
                                                       \STATE
    $d_\mathrm{surf}[i...
    
    ? 
    
    
    
    So what I'd like is firstly to be able to split commands like \f[ stuff \f]
    across multiple comments in the body of a function and secondly, ideally,
    have an environment that allows any latex whatsoever and puts the PNG
    generated from it in the HTML output.
    
    I don't want to use latexonly as I'd like to have at least the PNG version
    in the HTML.
    
    Any thoughts about whether you like this or if it is possible?

On 2011-01-26 11:22:20 +0000, David Brockley wrote:

    Some more thought on this.
    
    I guess what I am after is an equivalent to '\f[ stuff \f]' which sends
    'stuff' to latex to be turned into a PNG, but not in math mode.
    
    Let's presume the new commands are \foo[ and \foo]
    
    So I want to be able to do 
    
    /** \foo[
    Latex describing my for loop
    /*
    
    for( i = 0; i < 10; i++ )
    {
    
    /**
    Latex describing my function call
    */
        func_call();
    }
    
    /**
    Latex describing the end of the loop
    \foo]
    
    */
    
    So I get the algorithm defined in the latex doc and a PNG representation of
    that in the HTML.

On 2011-01-26 11:55:06 +0000, David Brockley wrote:

    Almost got it working:
    
    /**
    \f{algorithmic}{
    \REQUIRE $n \geq 0 \vee x \neq 0$
    \ENSURE $y = x^n$
    \STATE $y \Leftarrow 1$
    \IF{$n < 0$}
    \STATE $X \Leftarrow 1 / x$
    \STATE $N \Leftarrow -n$
    \ELSE
    \STATE $X \Leftarrow x$
    \STATE $N \Leftarrow n$
    \begin{comment}
    */
    
    
        for( unsigned long long uk_loop = 0;
             uk_loop < uk_InterpolationArraySize;
             uk_loop++ )
        {
     /**
    \end{comment}
    \ENDIF
    \WHILE{$N \neq 0$}
    \IF{$N$ is even}
    \STATE $X \Leftarrow X \times X$
    \STATE $N \Leftarrow N / 2$
    \ELSE[$N$ is odd]
    \STATE $y \Leftarrow y \times X$
    \STATE $N \Leftarrow N - 1$
    \ENDIF
    \ENDWHILE
    \f}
    */
    
    Will do what I want except that latex throws away all of the input after the
    \end{comment} as that needs a newline after it.
    
    Is there any way to force the newlines in the latex to be carried over into
    _formulas.tex?

On 2011-01-26 13:22:57 +0000, David Brockley wrote:

    Line 3187 of commentscan.cpp in v1.7.3 in the function
    
    Change to:
    
      //QCString fText=formulaText.simplifyWhiteSpace();
    	QCString fText=formulaText;
    
    This preserves the newlines in the latex and allows the hack using
    \begin{comment} to work. I'm not sure what having the whitespace from the
    source code present in the LaTeX could break though... Perhaps do some
    parsing to collapse multiple spaces and tab to space but not remove
    newlines?
    
    So, with that out of the way, the problem becomes the need for the
    \begin{comment} hack. Where the documentation says that comments in the body
    of a function are concatenated, that concatenation occurs after parsing, so
    breaking a \f[ \f] pair across different comments results in all of the
    source code between getting pulled in.
    
    What I think I now need to do is look at the parser and see if there is a
    way to get it to concatenate all of the comments in the body of a function
    and then process the concatenated text, rather than processing the comments
    one at a time and concatenating the results of the processing.

**Comment by albert-github** [comment]
The version of David Brockley works with the doxygen version 1.9.4 when we set:
```
EXTRA_PACKAGES = comment
EXTRA_PACKAGES += algorithmic
```
(and complete the for loop of the C code).

I think the problem has been solved in the mean time.
