### ISSUE TITLE
full indexes are missing (Origin: bugzilla #640619)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4111]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2011-01-26 08:04:06 +0000, bugzilla.gnome.org@poelzi.org wrote:

    Currently doxygen generates index pages with prefix paginators only and also
    scatters them on many subpages. This makes it extremely hard to find
    signatures of functions partially known or to search for a keyword in the
    name.
    You need to know a lib quite good to find documentation and that is not very
    helpful.
    
    I personally find doxygen docs more or less useless as they don't generate a
    full index like the glib doc generator.
    
    Example of a good full index:
    http://library.gnome.org/devel/glib/2.26/api-index-full.html

**Comment by apolukhin** [comment]
Looks like a redy-to-use solution is now available https://lunrjs.com/

The API is quite close to the current search engine

**Comment by apolukhin** [comment]
There's a ready to use solution that does not require third party languages and tools https://github.com/divideconcept/DoxygenDeepSearch

**Comment by albert-github** [comment]
Code of #10218 has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.8.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
