### ISSUE TITLE
Search frame breaks HTML of Treeview (Origin: bugzilla #640926)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4126]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.2-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxygen-search-frame-position.patch](https://sourceforge.net/projects/doxygen/files/attachments/bug640926_179620_doxygen-search-frame-position.patch/download/download)_ (ID 179620)

On 2011-01-30 01:28:04 +0000, Haffmans wrote:

    Created attachment 179620
    Fix search frame position
    
    The Javascript search adds an iFrame and some other code at the end of the
    page. However, if Treeview is enabled and a custom footer page is used, this
    breaks the HTML. The Treeview's <ul> tag of the navigation bar at the bottom
    isn't closed (this is expected to be done by the custom footer), when the
    search's elements are inserted.
    
    Note that this does not occur if the server-side search is used.
    
    Attached patch will write these elements before the navigation bar if a
    custom footer is enabled.

On 2012-11-18 11:06:58 +0000, Dimitri van Heesch wrote:

    Changed version 'latest' to '1.8.2-SVN' so I can remove 'latest' as an
    option as it is a moving target.

**Comment by albert-github** [comment]
This issue is, unfortunately, quite old and since 2011 quite a lot has changed regarding the handling of the HTML output.
There haven't been problems reported against recent versions.

I think the problem has been solved in the mean time.
