### ISSUE TITLE
Nested structs not correctly labelled in collaboration diagram (Origin: bugzilla #641112)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4132]
status NEW severity *major* in component *general* for *---*
Reported in version *1.6.3* on platform *Other*
Assigned to: Dimitri van Heesch

On 2011-02-01 07:19:23 +0000, John Pye wrote:

    In our project we have some data structures declared that contain nested
    structs, for example see
    
    http://ascend.cheme.cmu.edu/doxy/da/d16/structsystem__structure.html
    
    The resulting collaboration diagram is not usable because it only contains
    the 'tail' of the nested struct name, and not its full details (eg should be
    'whens.master' instead of 'master').
    
    Would be great if a fix or workaround for this could be worked out.

**Comment by albert-github** [comment]
Unfortunately no example and also the mentioned page cannot be reached anymore.

The issue is incomplete
