### ISSUE TITLE
C# abstract/sealed class attributes are not stored in XML output (Origin: bugzilla #641149)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4134]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.2-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[sample.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug641149_179795_sample.zip/download/download)_ (ID 179795)

On 2011-02-01 14:37:27 +0000, Ray Lefuel wrote:

    Created attachment 179795
    XML outputs for the 4 sample classes, sample code, and my Doxygen
    configuration file.
    
    I'm not sure if this is a feature request or a bug, but there doesn't seem
    to be a means of distinguishing a regular C# class from a sealed, abstract,
    or sealed abstract class in the XML output.  They're all tagged as public
    non-virtual classes, and the "abstract" or "sealed" words seem to be
    stripped from the syntax.
    
    As a workaround, I'm currently running a preprocessor python script that
    looks for the words "class" along with "sealed" and/or "abstract" so that I
    can append a custom tag to the class docs and retain the lost information.
    
    Source sample:
    
    namespace Sample.API {
        /// SampleClassA docs.
        public class SampleClassA : DbConnectionStringBuilder {
            /// Code goes here.
        }
    
        /// SampleClassB docs.
        public abstract class SampleClassB : DbConnectionStringBuilder {
            /// Code goes here.
        }
    
        /// SampleClassC docs.
        public sealed class SampleClassC : DbConnectionStringBuilder {
            /// Code goes here.
        }
    
        /// SampleClassD docs.
        public abstract sealed class SampleClassD : DbConnectionStringBuilder {
            /// Code goes here.
        }
    }
    
    I've attached the XML outputs for the 4 sample classes, the above code, and
    my Doxygen configuration file.

On 2012-11-18 11:07:18 +0000, Dimitri van Heesch wrote:

    Changed version 'latest' to '1.8.2-SVN' so I can remove 'latest' as an
    option as it is a moving target.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #10121

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.8.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
