### ISSUE TITLE
Wrong line numbers in warnings involving C++ files (Origin: bugzilla #641851)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4144]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.8.3.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[Doxyfile](https://sourceforge.net/projects/doxygen/files/attachments/bug641851_180399_Doxyfile/download/download)_ (ID 180399)
- _[Bug 641851.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug641851_237284_Bug 641851.zip/download/download)_ (ID 237284)
- _[Bug 694690.tar](https://sourceforge.net/projects/doxygen/files/attachments/bug641851_237395_Bug 694690.tar/download/download)_ (ID 237395)

On 2011-02-08 17:41:29 +0000, Heinz Ozwirk wrote:

    Created attachment 180399
    Doxyfile used with the code above
    
    The line numbers reported in warning messages do not refer to the faulty
    line, but often to the first line of a comment block. For the following
    code, Doxygen reports warnings on lines 1, 16 and 10 (in that order).
    
    /// 
    /// @file		main.cpp
    /// @author		heinz@ozwirk
    /// @date		27.01.2011 File created
    ///
    
    #include "stdafx.h"
    #include "DoxyTest.h"
    
    ///
    /// @parm This is not the main function.
    ///
    void foo()
    {}
    
    /**
     *	@paran This is the main function.
     */
    int _tmain()
    {}
    
    D:/Source/DoxyTest/main.cpp(1) : warning: Found unknown command `\ozwirk'
    D:/Source/DoxyTest/main.cpp(16) : warning: Found unknown command `\paran'
    D:/Source/DoxyTest/main.cpp(10) : warning: Found unknown command `\parm'

On 2012-07-20 08:41:41 +0000, Philipp wrote:

    The same (or related) problem happens in Markdown files. The following .md
    file (between the ---):
    
-------------------------------------------------------------------------------------------------
    Demonstrates wrong line problem         {#WrongLine}
    ===============================
    
    
    # Introduction                          {#WrongLine_Introduction}
    
    Some introduction
    
    More important stuff
    
    # The details                           {#WrongLine_TheDetails}
    
    As described in the \ref DemoWrongLine_Introduction, blah blah blah.
    
    And some more blah blah.
-------------------------------------------------------------------------------------------------
    
    will report:
    
    WrongLine.md(7): warning : unable to resolve reference to
    `DemoWrongLine_Introduction' for \ref command
    
    (7) being the reported line number. The problem is actually on line 13.

On 2012-08-15 13:16:24 +0000, Philipp wrote:

    While this is not much of a problem for unresolved references (can be found
    with 'search' in text editor), it is quite painful to find the cause of e.g.
    the following warning in a rather long markdown file:
    
     warning : Unexpected subsubsection command found inside section!

On 2012-10-11 09:13:28 +0000, Philipp Moeller wrote:

    I can confirm this on svn r833 and on the 1.8.2 release.

On 2013-02-24 15:13:18 +0000, james.q.arnold@boeing.com wrote:

    When this happens for me, the line number reported in the warning
    message is lower than the line where the problem occurs.  I suspect
    some input lines are being discarded without updating a line number
    counter.  Perhaps a clue.
    
    As a related (?) issue, I had a @ref command without the definition.
    Got the following:
    
        page-main.dox:2151: warning: unable to resolve reference to
    `bsidx_qs_valid' for \ref command
    
    The file page-main.dox had only 430 lines.  It was not really
    C code, used no #include files, etc.  I don't know where the
    line 2151 came from.

On 2013-02-24 16:31:41 +0000, Kevin McBride wrote:

    Created attachment 237284
    My Testcase with Output

On 2013-02-24 16:34:37 +0000, Kevin McBride wrote:

    On 1.8.3.1, this bug does not reproduce.  I am closing this bug as "resolved
    - fixed".  If my attachment fails to work for you, or the bug otherwise
    reproduces itself with the latest version of doxygen, attach a testcase in a
    tar or zip and reopen this bug.

On 2013-02-24 17:01:21 +0000, Philipp Moeller wrote:

    The issue persists when using Markdown as outlined in my post above. The
    original issue seems to be fixed. I don't know if I should open a new bug or
    reopen this one.

On 2013-02-24 17:48:42 +0000, Dimitri van Heesch wrote:

    Hi Philipp, please open a new bug report and attach a self-contained example
    (i.e. a zip containg both the source code and a configuration file) so that
    I can easily reproduce the problem. Please don't paste the example in the
    bug report text.

On 2013-02-24 18:16:34 +0000, Philipp Moeller wrote:

    The new bug-report is here https://bugzilla.gnome.org/show_bug.cgi?id=694610

On 2013-02-25 22:43:41 +0000, Kevin McBride wrote:

    Created attachment 237395
    Testcase from Bug 694690

On 2013-02-25 22:46:40 +0000, Kevin McBride wrote:

    *** Bug 694690 has been marked as a duplicate of this bug. ***

On 2013-02-25 22:47:52 +0000, Kevin McBride wrote:

    Per bug 694690 and attachment in comment # 10, I am reopening this bug.

**Comment by albert-github** [comment]
I see for the given examples the problems with the different versions of doxygen.
- With the current master (1.9.2 (fc67a8291551fcd1a752eb89d18c80603a51627a)) these problems are gone when setting `JAVADOC_AUTOBRIEF=NO`
- When using `JAVADOC_AUTOBRIEF=YES` the problems are, probably gone when the proposed pull request #8489 has been integrated

**Comment by albert-github** [comment]
The code of the proposed pull request #8489 indeed solves the rest of the line count mismatches in this issue.
Code of proposed pull request #8489 has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.3.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
