### ISSUE TITLE
@mscfile <filename> does not process mscgen code (Origin: bugzilla #642126)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4148]
status NEW severity *minor* in component *build* for *---*
Reported in version *1.7.0* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[Bug_Msgfile_New_Format_IS_w_Index.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug642126_180686_Bug_Msgfile_New_Format_IS_w_Index.zip/download/download)_ (ID 180686)

On 2011-02-11 20:22:30 +0000, Lori Boyters wrote:

    Created attachment 180686
    @mscfile workaround
    
    This does not work as indicated in the Doxygen Manual. However, I did find a
    way to make it work so that you don't need to put the mscgen code inside the
    header file.
    
    @msc 
    @latexonly \input{mscgen_callflows/msc_callflow_sample.txt} @endlatexonly
    @endmsc 
    
    Also, the mscgen source file, should not include the msc {} for this to
    work, example:
    
      hscale="0.7";
    
      CS,WS,Init;
    
      CS->CS [ label = "cs()" ] ;
      CS->Init [ label = "Init(TRUE)", ID="1"];
      Init=>CS [ label = "process(1)" ];
      Init=>CS [ label = "process(2)" ];
      CS box Init [label="Sample box"];
      ...;
      Init=>Init [ label = "process(n)" ];
      Init=>Init [ label = "process(END)" ];
      CS rbox WS [ label = "Round box with blue border", linecolour="# 0000ff"];
      CS<<=Init [ label = "callback()"];
      ---  [ label = "If more to run", ID="*" ];
      WS->WS [ label = "next()"];
      WS->Init [ label = "ac1()\nac2()"];
      Init<-WS [ label = "Init(TRUE)"];
      WS abox Init [ label = "Angular box with red text", textcolour="red" ];
      Init->Init [ label = "stalled(...)"];
      WS<-Init [ label = "ws() = FALSE"];
    
    If you want to include a figure caption that will show up in the toc,you can
    also add the following LaTeX code in your header file just below.
    
    @msc 
    @latexonly \input{mscgen_callflows/msc_callflow_sample.txt} @endlatexonly
    @endmsc 
    
    @latexonly
      \begin{figure}[H]
      \centering
      \renewcommand{\thefigure}{\thechapter-\arabic{figure}}
      \caption{Sample Call Flow}
      \label{fig:Sample Call Flow}
    \end{figure}
    @endlatexonly

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7082with a small clarification about the usage.

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
