### ISSUE TITLE
C# "here-docs" not correctly parsed (Origin: bugzilla #642168)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4152]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.7.3* on platform *Other*
Assigned to: Dimitri van Heesch

On 2011-02-12 12:24:29 +0000, Neil MacMullen wrote:

    Doxygen does not seem to correctly parse C# 'here documents' designated by
    the '@' character.
    
    For example after running doxygen over this code:
    
     /// <summary>Class demonstrating incorrect here-doc parsing</summary>
        class HereDocs
        {
            private string Dummy()
            {
                return @"\";
            }
    
            /// <summary> A description </summary>
            public int Count
            {
                get { return 1; }
            }
        }
    
    The properties list contains 
    
    >>int 	Count = \" [get]
    >> 	A description.
    
    (ie, part of the here-doc has 'leaked' into the property)

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #9446

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.5.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
