### ISSUE TITLE
\ref links to anchors in mainpage link to main.html instead of index.html (Origin: bugzilla #642289)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4153]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.7.3* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxygenbug.tar.gz](https://sourceforge.net/projects/doxygen/files/attachments/bug642289_180822_doxygenbug.tar.gz/download/download)_ (ID 180822)

On 2011-02-14 13:17:58 +0000, Dirk Osswald wrote:

    Created attachment 180822
    minimal example to reproduce the bug
    
    When I add a \ref link to an anchor "foo" that is located in the \mainpage
    then the hyperlink generated by doxygen links to a non existing file
    "main.html#foo" instead of the existing "index.html#foo".
    
    This does not happen with the "doxygen -s -u Doxyfile" standard settings.
    Instead it seems to be related with the new (and beautiful :-) non-frame
    layout.
    
    I prepared a minimal example to demostrate the bug, see attachment:
    - mainpage.dox: the \mainpage description containing a labeled \section
    anchor to link to
    - dummy.c: a dummy code file that tries to link to the labeled anchor
    - Doxyfile: Doxyfile settings that reproduce the error

On 2011-08-10 11:12:59 +0000, johannes.schlatow@googlemail.com wrote:

    Same problem here with 1.7.4!
    
    With GENERATE_TREEVIEW=NO the \ref link is generated correctly.

**Comment by albert-github** [comment]
With the 1.7.4 version there are, as mentioned, references to main.html. In the current doxygen version (1.9.6) there are no references to main.html the references are now to index.html.

I think the problem has been solved in the mean time.
