### ISSUE TITLE
\"\subpage the_id\" doesn't work inline (Origin: bugzilla #642841)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4166]
status NEW severity *minor* in component *build* for *---*
Reported in version *1.8.2-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[aa.c](https://sourceforge.net/projects/doxygen/files/attachments/bug642841_235736_aa.c/download/download)_ (ID 235736)

On 2011-02-21 00:01:45 +0000, rmp wrote:

    If I do the text
    
    Older versions are listed in \"\subpage Changelog_deprecated\" it won't show
    this page as subpage:
    
    /*!
    \page Changelog Changelog
    
    <em class="note">All entrys are ordered by version and alphabetically.
    Older versions are listed in \"\subpage Changelog_deprecated\".</em>
    
    */

On 2012-11-18 11:07:26 +0000, Dimitri van Heesch wrote:

    Changed version 'latest' to '1.8.2-SVN' so I can remove 'latest' as an
    option as it is a moving target.

On 2013-02-11 19:40:06 +0000, albert wrote:

    When using &quot; instead of \" will make it work in 1.8.3.1 (as far as I
    can see).

On 2013-02-11 19:40:59 +0000, albert wrote:

    Created attachment 235736
    Extended test case

**Comment by albert-github** [comment]
I did some tests with the 1.8.14 version and on the page I do see the double quotes when escaped.

I think the problem has been solved in the mean time
