### ISSUE TITLE
Reference to external documentation using tags no longer working. (Origin: bugzilla #643035)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4168]
status NEW severity *major* in component *general* for *---*
Reported in version *1.7.3* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxygen_bug.7z](https://sourceforge.net/projects/doxygen/files/attachments/bug643035_182752_doxygen_bug.7z/download/download)_ (ID 182752)

On 2011-02-23 02:39:51 +0000, Richard Harding wrote:

    I recently upgraded to 1.7.3 and found that none of my external
    documentation was being linked when using the tags/installdox mechanism.
    
    Downgrading to 1.6.3 fixed some of the issues, but referencing an external
    function still does not work. Prior to these issues, I was using something
    in the 1.5.x range.
    
    It looks as though the \ref tags for the external function is simply not
    generating any anchor information in the HTML, therefore when installdox is
    executed it does not find the "doxygen=" pattern for substitution.
    
    I have a piece of documentation (let's say foo.dox) that looks like:
    
    - \ref myExternalFunction
    - \ref myExternalSection
    
    The reference to the external section works in 1.6.3 (but does not in
    1.7.3), but not for the external function. Doxygen outputs a message:
    "Warning: unable to resolve reference to `myExternalFunction` for \ref
    command".
    
    The generated HTML (before installdox looks like):
    
    <li>myExternalFunction</li>
    <li><a class="elRef" doxygen="external.tag:"
    href="index.html#myExternalSection">myExternalSection</a></li>
    
    The tag information for the external function does exist in the external.tag
    file.
    
    Again...this all worked fine prior to 1.6.x?????

On 2011-02-24 02:17:42 +0000, Richard Harding wrote:

    I did some more checking and downgraded all the way to 1.5.3, but it seems
    that the reference to an external function still does not work which means I
    may have been mistaken on that count. But, references to external elements
    (e.g. sections) via tags/installdox are broken for me in 1.7.3, but do work
    in 1.6.3.
    
    Perhaps I am incorrectly referencing a function in an external documentation
    set?

On 2011-02-25 22:28:00 +0000, Dimitri van Heesch wrote:

    Can you please attach a self-contained example (source+config file in a tar
    or zip) that allows me to reproduce the problem?

On 2011-03-07 19:54:32 +0000, Richard Harding wrote:

    Created attachment 182752
    Broken tag file example for 1.7.3

**Comment by albert-github** [comment]
Checked with 1.6.3 problem works
Checked with 1.7.3 problem failed.
The script program is not part of doxygen anymore (since 1.8.0).

Checked the given example with 1.8.14 (after updating the test.cfg to reflect right tag file (syntax): 
```TAGFILES               = ./test1/html/test_1.tag=../test1/html ./test2/html/test_2.tag=../test2/html```
and it all worked.

I think the problem has been solved in the mean time.
