### ISSUE TITLE
New diagram implementing environment (Origin: bugzilla #644899)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4195]
status NEW severity *enhancement* in component *build* for *---*
Reported in version *1.7.3* on platform *Other*
Assigned to: Dimitri van Heesch

On 2011-03-16 10:07:41 +0000, Marcin Bajer wrote:

    Recently I found out an interesting envoriment for preparing
    diagrams/graphics in LaTeX. Please have a look at:
    
    http://www.texample.net/tikz/examples/
    
    Is it possible to use it inside the code to include into documentation?
    Maybe it would be resonable to think about adding this feature if it not
    require a lot of work.
    
    Regards,
    Marcin

On 2011-03-16 12:07:29 +0000, Akhil Laddha wrote:

    is bug 644900 different from bug 644899 ?

On 2011-03-16 19:11:38 +0000, Dimitri van Heesch wrote:

    *** Bug 644900 has been marked as a duplicate of this bug. ***

On 2011-03-16 19:11:48 +0000, Dimitri van Heesch wrote:

    *** Bug 644902 has been marked as a duplicate of this bug. ***

On 2011-03-16 19:11:59 +0000, Dimitri van Heesch wrote:

    *** Bug 644903 has been marked as a duplicate of this bug. ***

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #9088

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.4.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
