### ISSUE TITLE
Include struct member documentation with struct documentation (Origin: bugzilla #645464)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4205]
status NEEDINFO severity *major* in component *documentation* for *---*
Reported in version *1.7.0* on platform *Other*
Assigned to: Dimitri van Heesch

On 2011-03-21 21:30:22 +0000, Lori Boyters wrote:

    Struct member documentation is not included with the struct documentation as
    expected. examples attached

On 2013-05-10 14:29:42 +0000, Dimitri van Heesch wrote:

    Hi Lori,
    
    Seems like the attachements are missing from the bug report. If this is
    still an issue please attach then.

**Comment by albert-github** [comment]
No example has been provided, setting issue to incomplete / invalid
