### ISSUE TITLE
Bad class list when template derives from template using arg member (Origin: bugzilla #645641)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4207]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.3-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[bug_sample.tar.bz2](https://sourceforge.net/projects/doxygen/files/attachments/bug645641_184179_bug_sample.tar.bz2/download/download)_ (ID 184179)
- _[bug_sample_2.tar.bz2](https://sourceforge.net/projects/doxygen/files/attachments/bug645641_184399_bug_sample_2.tar.bz2/download/download)_ (ID 184399)

On 2011-03-24 00:09:16 +0000, ceastbz@lavabit.com wrote:

    Created attachment 184179
    Sample code and configuration file.
    
    OVERVIEW:
    This bug is not easy to summarize succinctly. It arises when there is a
    class template which takes at least one argument, and inherits from it. A
    second class, also a template, takes a single class as an argument, and
    assumes that argument has a member, that is a type, with a specific name. An
    additional problem arises when they are enclosed in a namespace, as shown.
    
    Example:
    (Note: This is worded to imply that the culprit type is a typedef, but it
    just has to be a member that names a type)
    
    namespace foo {
    
    	// First class; it inherits from its only template argument
    	template <class some_typedef>
    	class inherits_from_typedef : public some_typedef {};
    
    	// Second class; it inherits from the first class,
    	// and assumes its template parameter has a member
    	// called BAD_PARSE that is a type. It passes that
    	// member as the argument to inherits_from_typedef,
    	// and inherits from it.
    	template <class class_with_typedef>
        class final : public inherits_from_typedef<typename
    class_with_typedef::BAD_PARSE> {};
    
    } // namespace foo
    
    PROBLEM:
    Running doxygen on a file containing the above yields an incorrect class
    list in the resultant html documentation. Rather than the expected
    documentation, "BAD_PARSE" appears in the class list, by itself, with no
    namespace qualifications-- it is given its own class documentation where it
    is a free-standing class and is not a member of foo (although BAD_PARSE does
    also appear in namespace foo's page as it should).
    
    Additionally, the inheritance diagram for final (class 2) is incorrect. The
    diagram correctly indicates that it inherits from inherits_from_typedef
    (class 1), but posits that inherits_from_typedef (class 1) inherits from
    BAD_PARSE. It does, of course-- but in this case, BAD_PARSE appears to be
    unqualified by either its enclosing class or a namespace and links to the
    standalone BAD_PARSE class page. Because there's nothing *to* link to
    (since BAD_PARSE is a member of a template argument) doxygen shouldn't
    generate links for it at all. (Speculation: Perhaps this is *why* doxygen is
    confused)
    
    As for the class page for inherits_from_typedef (class 1), there is no
    mention of BAD_PARSE-- there is no inheritance diagram at all. If using
    multiple inheritance, a diagram is generated with the other base class,
    still no BAD_PARSE. Since this is the same behavior that is exhibited when
    any class inherits from a template argument (as far as I can tell), if it's
    a bug, it probably belongs in a separate report.
    
    STEPS TO REPRODUCE:
    1) Extract the attachment somewhere, cd to directory
    2) `doxygen doxyfile`
    3) The problem should be apparent in the resultant classes list
    (doc/html/annotated.html) and in the classes' respective pages.
    (100% reproducible on my end)
    
    ADDITIONAL INFO:
    Whether the member BAD_PARSE is a typedef, class, struct, or enum is
    irrelevant to this bug. It is reproducible regardless of whether a class
    with a member called BAD_PARSE even *exists*, since doxygen is parsing an
    uninstantiated template, so it follows that the issue does not arise
    specifically from BAD_PARSE being a typedef, but from a more general parsing
    error.
    
    I don't know whether this yields anything fishy in any other kind of output
    (man/LaTeX/etc).
    
    Included are the above sample and the config file I'm using. This is
    submitted for version 1.7.3 SVN, but also exists in version 1.7.1 from the
    Ubuntu Maverick repos.
    
    Attached: the above sample and my configuration file.

On 2011-03-26 10:50:02 +0000, Dimitri van Heesch wrote:

    Seems like the attachment is corrupted/incomplete. Can you attach it again?

On 2011-03-27 23:39:31 +0000, ceastbz@lavabit.com wrote:

    Created attachment 184399
    Sample code and configuration file take 2
    
    Sorry about that! Seems it didn't upload properly. Trying again, then.

On 2011-04-08 04:41:26 +0000, Akhil Laddha wrote:

    Information provided.

**Comment by albert-github** [comment]
With the 1.7.3 version we see that `BAD_PARSE` is seen as a separate class:
![image](https://github.com/doxygen/doxygen/assets/5223533/4fb7d1fc-0eda-4c29-bb0f-71a1f09ef948)

with the current version (1.9.7) this is not the case anymore:
![image](https://github.com/doxygen/doxygen/assets/5223533/9ce9010c-ac29-49a2-bd3a-b4c3e334b4a7)


I think the problem has been solved in the mean time
