### ISSUE TITLE
Segfault on recursion while parsing "\subpage A" in "\page A" (Origin: bugzilla #645910)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4211]
status NEW severity *major* in component *general* for *---*
Reported in version *1.7.3* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxygen_bug.tar.gz](https://sourceforge.net/projects/doxygen/files/attachments/bug645910_185685_doxygen_bug.tar.gz/download/download)_ (ID 185685)

On 2011-03-28 09:19:05 +0000, Mickey86 wrote:

    With all version tested (from 1.7.1 to 1.7.3), when "\subpage A" appears in
    "\page A" doxygen segfaults when parsing.
    
    By the way this recursion-scheme is a mistake (I used this as for linking
    "\page A" in "\page A"), but it would be great if it could be detected and
    reported as an error by doxygen itself.
    
    I spent a lot of time to figure out the origin of this segfault.
    
    Anyway, thanks for this great application !
    
    --
    Mickey86

On 2011-04-09 19:09:05 +0000, Dimitri van Heesch wrote:

    Can you please attach a self-contained example (source+config file in a tar
    or zip) that allows me to reproduce the problem?
    
    I tried with: 
    
    ---------------------------------
    /** @page A Some page
     *  Some text
     *  @subpage B
     */
    
    /** @page B Some other page
     *  Some text
     *  @subpage A
     */
    
    /** @page C Yet another page
     *  @subpage C
     */
    ---------------------------------
    
    This does not crash doxygen but gives:
    
    ---------------------------------
    page defined at line 1 of file test.cpp with label A is a subpage of itself!
    Please remove this cyclic dependency.
    
    Exiting...
    ---------------------------------

On 2011-04-11 08:19:34 +0000, Mickey86 wrote:

    Created attachment 185685
    source and config files that raises the bug.
    
    It is just the buggy partâ¦ 
    The whole documentation is far bigger, the Doxyfile has been generated by
    doxywizard of doxygen-1.7.3 (but same symptoms with 1.7.1 and 1.7.2), only
    few paths were modified (no effect on bug) to generate this attachment.

On 2011-04-11 08:21:25 +0000, Mickey86 wrote:

    Here are the source and config filesâ¦
    
    Note that Doxyfile is in "./doc" while the root of dox-scan is "./".
    
    Hope it will help.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6857

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
