### ISSUE TITLE
Special command \fn fails when first argument of PHP function is call-by-reference (Origin: bugzilla #647654)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4239]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.4-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2011-04-13 13:43:22 +0000, Themroc wrote:

    With 1.7.1 and also with svn 2011-04-13 revision 763 i get these warnings:
    
    /tmp/doxygen/test.php:24: warning: documented function `$ref' was not
    declared or defined.
    /tmp/doxygen/test.php:27: warning: documented function `$ref $data' was not
    declared or defined.
    /tmp/doxygen/test.php:30: warning: documented function `$ref $data' was not
    declared or defined.
    /tmp/doxygen/test.php:16: warning: Member e(&$ref, $data) (function) of file
    test.php is not documented.
    
    Unedited Doxyfile from doxygen -g, test.php looks like this:
    
    <?php
    /** @file */
    
    /** func a */
    function a ($data) {}
    
    /** func b */
    function b ($data, &$ref) {}
    
    /** func c */
    function c (&$ref) {}
    
    /** func d */
    function d (&$ref, $data) {}
    
    function e (&$ref, $data) {}
    
    /** @fn a ($data)
    append a works */
    
    /** @fn b ($data, &$ref)
    append b works */
    
    /** @fn c (&$ref)
    append c fails */
    
    /** @fn d (&$ref, $data)
    append d fails */
    
    /** @fn e (&$ref, $data)
    func e also fails */
    
    ?>
    
    Both html and latex output lack "append c fails", "append d fails" and "func
    e also fails".

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7981

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
