### ISSUE TITLE
Fortran: tagfile.tag:789: warning: Unknown compound attribute `type' found! (Origin: bugzilla #648180)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4244]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.4-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[testCase4f90Type.tgz](https://sourceforge.net/projects/doxygen/files/attachments/bug648180_186638_testCase4f90Type.tgz/download/download)_ (ID 186638)

On 2011-04-19 07:14:51 +0000, Simppa wrote:

    Fortran tag file cannot be read. A segmentation fault results.
    Latest tested version is svn rev 763.
    
    The original piece of code to be documented:
    --------------------------------------------
      Type, Public :: FIPC_ctxt
         Private
         !> \private
         Logical             , Pointer :: initialized => Null() 
         !> \private
         Type( communicator ), Pointer :: world_comm
         !> \private
         Type( communicator ), Pointer :: intra_comm
         !> \private
         Type( communicator ), Pointer :: extra_comm
         !> \private
         Integer                       :: semid
      End Type FIPC_ctxt
    
    
    The generated problematic tag is:
    ---------------------------------
      <compound kind="type">
        <name>FIPC_module::FIPC_ctxt</name>
        <filename>type_f_i_p_c__module_1_1_f_i_p_c__ctxt.html</filename>
      </compound>
    
    The output of the code while trying to use the tag later is:
    ------------------------------------------------------------
    ...
    Reading and parsing tag files
    Reading tag file `tagfile.tag'...
    tagfile.tag:789: warning: Unknown compound attribute `type' found!
    
    Segmentation fault
    $

On 2011-04-22 14:40:59 +0000, Dimitri van Heesch wrote:

    I cannot reproduce the problem with only the tagfile.
    Can you please attach a self-contained example (source+config file in a tar
    or zip) that allows me to reproduce the problem?

On 2011-04-23 10:51:36 +0000, Simppa wrote:

    (In reply to comment # 1)
    > I cannot reproduce the problem with only the tagfile.
    > Can you please attach a self-contained example (source+config file in a
    tar or
    > zip) that allows me to reproduce the problem?
    
    Will do, stand by some days. :-)

On 2011-04-26 06:58:29 +0000, Simppa wrote:

    Created attachment 186638
    Test case for the "Unknown compound attribute `type' found!"
    
    To reproduce the bug do following:
    
    tar -xzvf testCase4f90Type.tgz
    cd main_folder/sub_folder/
    doxygen Doxyfile
    cd ..
    doxygen Doxyfile
    
    Thank you very much for the help!

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6401.

**Comment by albert-github** [comment]
Code has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
