### ISSUE TITLE
@deprecated list extends into margin in PDF (Origin: bugzilla #648909)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4250]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.0* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[refman.pdf](https://sourceforge.net/projects/doxygen/files/attachments/bug648909_188774_refman.pdf/download/download)_ (ID 188774)

On 2011-04-29 00:01:09 +0000, Lori Boyters wrote:

    In the PDF, the Deprecated List chapter, long deprecated code names extend
    into the right margin.

On 2011-04-29 00:03:03 +0000, Lori Boyters wrote:

    Dimitri, This bug is in support of our SOW Task 2e.

On 2011-04-30 07:57:08 +0000, Dimitri van Heesch wrote:

    See PM for the questions I have.

On 2011-05-27 16:55:09 +0000, Lori Boyters wrote:

    Created attachment 188774
    Sample PDF
    
    Added the sample PDF to show how this looks.

**Comment by albert-github** [comment]
I tested with the first prototype as specified in the deprecated list (due to missing example) and with version 1.7.0 I could see the problem as indicated.
With version 1.8.14 the problem is gone.

I think the problem has been solved in the mean time.
