### ISSUE TITLE
Doxygen "references" field confuses overloads (Origin: bugzilla #649970)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4260]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[DoxygenIssue.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug649970_187635_DoxygenIssue.zip/download/download)_ (ID 187635)

On 2011-05-11 14:56:11 +0000, Brian D Szuter wrote:

    Created attachment 187635
    Files to reproduce the problem
    
    In the attached project, notice that there are two overloads of the
    "CreateProperty" method, one that takes two CStrings, and one that takes two
    UINTs.
    The Doxygen output (also enclosed), improperly shows that
    CMFCPropertyGridPropertyFactory::CreateProperty is referenced by both
    CallsStringOverloads() and CallsStringOverloads() when in fact it is only
    referenced by CallsStringOverloads().
    
    Please see
    ./PlayGround/PlayGround/GUIDocs/html/classCMFCPropertyGridPropertyFactory.html
    in the enclosed files.

**Comment by albert-github** [comment]
Looking at the example provided we see that this is a same / similar problem as reported in #4357
