### ISSUE TITLE
C# examples called out with \example tag are not cross-referenced (Origin: bugzilla #650705)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4271]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.4* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[example_tag.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug650705_188261_example_tag.zip/download/download)_ (ID 188261)

On 2011-05-20 23:40:12 +0000, wamai222@gmail.com wrote:

    Created attachment 188261
    Complete VS2008 C# example comparing C++ and C# \example behavior
    
    Doxygen works beautifully on C# source.  However, under Doxygen 1.7.3 and
    1.7.4 on Windows XP, C# examples called out with the \example tag do not
    have cross references from the examples back to the source or vice versa.
    
    While experimenting, we found if C++ syntax is used to refer to the
    namespace, then the example is properly cross referenced both from the
    example to the source and from the source to the example.
    
    Attached is a complete VS2008 C# example.  Compare the files Program.cs and
    Program.cpp.  This is the only line that is different:
    
    In Program.cs (*no* cross references created):
    
      API.ApiClass apiClass = new API.ApiClass();
    
    In Program.cpp (cross references *are* created):
    
      API::ApiClass apiClass = new API::ApiClass();
    
    The file extension does not matter.  Doxygen cross references Program.cs
    properly if "API::ApiClass" is used in it (but the example isn't C# now and
    won't compile).
    
    Please confirm if this is a bug.  A comment-stripped Doxyfile is included to
    help you help us.  Thanks!

**Comment by albert-github** [comment]
In the doxygen 1.7.4 version the links are indeed missing.
In the current doxygen (1.9.8) version the links are present.

I think the problem has been solved in the mean time.
