### ISSUE TITLE
put function documentation in the same line with declaration with ///<. (Origin: bugzilla #650947)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4274]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.7.4* on platform *Other*
Assigned to: Dimitri van Heesch

On 2011-05-24 10:18:13 +0000, Slava wrote:

    At the moment it only works with data members. Functions always take the
    documentation from the line above.

**Comment by albert-github** [comment]
It is unclear what is meant as in the doxygen 1.7.4 version the following:
```
void fie1(); ///< after fie
```
results inn
![image](https://github.com/doxygen/doxygen/assets/5223533/f044ff49-59b0-4fd4-9d62-270f6ee81684)

So I think the issue is incomplete.
