### ISSUE TITLE
@defgroup generates manpage warning. (Origin: bugzilla #651850)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4285]
status NEW severity *major* in component *general* for *---*
Reported in version *1.7.4* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxygen-man.patch](https://sourceforge.net/projects/doxygen/files/attachments/bug651850_189210_doxygen-man.patch/download/download)_ (ID 189210)

On 2011-06-04 12:19:53 +0000, Mattias Ellert wrote:

    Created attachment 189210
    An attempt at a patch that addresses the problem.
    
    A declaration like
    
    @groupdef mygroup My Group
    
    generates a man page that displays as
    
    NAME
           My Group -
    
    This is badly formed and causes manpage-has-bad-whatis-entry warnings from
    lintian.
    
    See: http://lintian.debian.org/tags/manpage-has-bad-whatis-entry.html
    
    A better and more compliant rendering would be:
    
    NAME
           mygroup - My Group
    
    An attempt at a patch that addresses the problem is attached.

On 2014-08-31 17:31:04 +0000, Mattias Ellert wrote:

    https://github.com/doxygen/doxygen/pull/213

**Comment by albert-github** [comment]
I think this issue has been solved in the mean time (probably as of doxygen version 1.8.9) as the mentioned patch #213 has been merged
