### ISSUE TITLE
Index anchor missing #whatever in qhp files (Origin: bugzilla #651991)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4287]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.2-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxtest.tgz](https://sourceforge.net/projects/doxygen/files/attachments/bug651991_189323_doxtest.tgz/download/download)_ (ID 189323)

On 2011-06-06 13:42:00 +0000, Ole Jacob wrote:

    Created attachment 189323
    Selfcontained test example
    
    Just switched from Doxygen v 1.6.1 to 1.7.3. I create documentation for 
    use in QT assistant.
    
    The index.qhp file contained lines like this in the <keywords> section 
    in version 1.6.1:
    <keyword name="support" id="support" ref="gettingstarted.html#support" />
    
    Now in 1.7.3 the "#support" part is gone with the result that all clicks 
    from the index in assistant ends up on top of the page, not at the 
    correct anchor.
    
    Also tested with Doxygen SVN a couple of weeks old.
    
    Attached an example case. Run "doit.sh"

On 2011-06-06 20:29:45 +0000, Dimitri van Heesch wrote:

    Hi Ole,
    
    Are you sure the example is complete? 
    I only see an introduction.doc, not the gettingstarted.html you mention
    above.

On 2011-06-07 07:31:03 +0000, Ole Jacob wrote:

    Well, yes the description and the example isn't entirely in sync, but if you
    open the example in assistant you will see that the indexes doesn't have a
    "#sometag" so they all refer to the top of the document rather than to the
    correct anchor.

On 2011-12-09 14:08:00 +0000, Ole Jacob wrote:

    Tested this some more, and have tracked it down to changes done between
    version 1.7.1 and 1.7.2. Don't know yet what is the reason is, but I notice
    that there are some changes to the interface Qhp::addIndexItem

On 2012-11-18 11:07:12 +0000, Dimitri van Heesch wrote:

    Changed version 'latest' to '1.8.2-SVN' so I can remove 'latest' as an
    option as it is a moving target.

**Comment by albert-github** [comment]
I tested wit Qt 5.15.2 assistent:
- with 1.7.1 and the jump is to the correct place.
- with 1.7.2 and the jump is to the top of the file
- with 1.9.2 and the jump is to the correct place (and in the index.qhp we see the #index... again).


I think the problem has been solved in the mean time.
