### ISSUE TITLE
Error when there is more than one function with the same name but different parameters passed to it. (Origin: bugzilla #652087)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4290]
status NEEDINFO severity *normal* in component *doxywizard* for *---*
Reported in version *1.7.4* on platform *Other*
Assigned to: Dimitri van Heesch

On 2011-06-07 23:41:53 +0000, akraus@vorum.com wrote:

    I have 2 functions with the same name but have different parameters passed
    to it.  When I try to generate the HTML output I get the following error:
    
    @param is not found in the argument list.
    
    Example:
    
    long TestClass::lTestFunc(float fVal)
    {
    }
    
    long TestClass::lTestFunc(int iVal)
    {
    }

On 2013-08-11 11:06:31 +0000, albert wrote:

    I've tried to reproduce the problem with the version 1.7.4 but I have not
    been able to reproduce the problem.
    
    Can you test the problem with the latest version of doxygen?
    If you still see this issue with the latest version of doxygen please add a
    self-contained example (source+config file in a zip or tar).

**Comment by albert-github** [comment]
Seen the period of no response and the fact that with the supplied information the problem is not reproducible I think the problem should be closed  as 'invalid' i.e. 'not complete or not reproducible'
