### ISSUE TITLE
PHP operator <<< confuses Doxygen (Origin: bugzilla #653006)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4309]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.4* on platform *Other*
Assigned to: Dimitri van Heesch

On 2011-06-20 13:44:50 +0000, contact@happycontent.com wrote:

    The syntax
    
    
    $var = <<<EOF
     some random
     string on multiple
     lines
    EOF;
    
    
    confuses Doxygen.
    
    In some cases it'll parse correctly, in other cases this leads to ignoring
    the whole file this construct appears.

**Comment by albert-github** [comment]
Unfortunately not a complete example, but from the doxygen source code end the changelog we can see that in version 1.7.6 the support for a PHP heredoc has been added.
(See: Support PHP heredoc syntax (Origin: bugzilla #607305) #3637)

I think the problem has been solved in the mean time.
