### ISSUE TITLE
EXPORT macro appears to be part of function return types. (Origin: bugzilla #653243)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4311]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.2-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2011-06-23 15:56:37 +0000, Stephen wrote:

    The generated documentation for 'free' functions includes the EXPORT macro,
    while the same is not true for classes.
    
    That is, the documentation for 
    
    
    /**
        This is someMethod
     */
    SOMELIB_EXPORT bool someMethod();
    
    is listed as 
    SOMELIB_EXPORT bool someMethod   (  )
    
    The export macro should not really exist in the generated documentation. The
    workaround I use is this:
    
    MACRO_EXPANSION        = YES
    PREDEFINED             = SOMELIB_EXPORT=
    
    Can doxygen be fixed to not extract the macro in the first place?
    
    I left 
    
    MACRO_EXPANSION        = NO 
    
    in the attachment so the issue is easily reproducible.
    
    Thanks,

On 2012-11-18 11:07:53 +0000, Dimitri van Heesch wrote:

    Changed version 'latest' to '1.8.2-SVN' so I can remove 'latest' as an
    option as it is a moving target.

**Comment by albert-github** [comment]
Unfortunately the attachment is missing, so an exact reconstruction of tyhe problem is not possible.
Using the code from the question.

In the question it is already indicated that using `MACRO_EXPANSION` and `PREDEFINED` solves the issue. As a small note there is also `EXPAND_ONLY_PREDEF` for some fine tuning.

I see this in a similar way as `__declspec` (see chapter Preprocessing in the documentation).

I don't think this is a bug but usage.
