### ISSUE TITLE
end of line comment on c++ constructor ///< attached to wrong method (Origin: bugzilla #653261)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4312]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.4* on platform *Other*
Assigned to: Dimitri van Heesch

On 2011-06-23 17:41:15 +0000, throwaway.email13@yahoo.com wrote:

    I have some struct, wherein it is written (more or less):
    
    struct MyStruct
    {
        OneType* member;                         ///< Some member variable
        typename SomeType AnotherType;           ///< Hey! a typedef
        SOME_SORT_OF_MACRO(ThisClass);           ///< This class needs this
    macro
    private:
        MyStruct() {};                           ///< Private constructor
        ~MyStruct() {};                          ///< Private destructor
        void NoOp() {};                          ///< Does nothing
        void SomeMethod() { perform_action(); }; ///< Does something
    };
    
    Sadly, doxygen produces this:
    
    Public Member Functions
     	SOME_SORT_OF_MACRO(ThisClass)
     	This class needs this macro
    Public Attributes
    OneType * 	member
     	Some member variable
    SomeType 	AnotherType
     	Hey! a typedef
    Private Member Functions
     	MyStruct ()
     	~MyStruct ()
     	Private constructor
    void 	NoOp ()
     	Private destructor
    void 	SomeMethod ()
     	Does nothing
    
    It's all right, until the constructor, at which point it permanently throws
    it off by one.
    
    This wasn't just a one-shot thing, either... I'm seeing this exact behavior
    in multiple places.

**Comment by albert-github** [comment]
Problem here is that the documentation is written after the implementation of the function and not after the definition.
We have currently
```MyStruct() {};                           ///< Private constructor```

Solutions are:
 ```
MyStruct_bb      /// Private constructor
    (){};
```
```
/// Private constructor
MyStruct() {};
```

I think this is not a bug but usage.
