### ISSUE TITLE
HTML help contents generation ignores visible="no" (Origin: bugzilla #653639)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4319]
status NEW severity *minor* in component *build* for *---*
Reported in version *1.7.4* on platform *Other*
Assigned to: Dimitri van Heesch

On 2011-06-29 12:47:42 +0000, Roderick Kennedy wrote:

    The layout xml allows hiding treeview folders using the 'visible="no"' tag.
    But there is no code to support this in index.cpp for CHM generation. This
    can be fixed by adding the following check after every instance of
    "LayoutNavEntry *lne =":
    
    if(lne->visible())
    {
        ... restore stack and return,
    }

**Comment by albert-github** [comment]
I did a ,small, test with the current doxygen version (1.9.6) and the CHM index obeyed the `visible="no"` settings from the layout filei whilst the 1.7.4 version didn't do it.

I think the problem has been solved in the mean time.
