### ISSUE TITLE
Error state 21 when using ?? as string in Fortran code (Origin: bugzilla #653797)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4322]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.4* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[test.for](https://sourceforge.net/projects/doxygen/files/attachments/bug653797_191098_test.for/download/download)_ (ID 191098)

On 2011-07-01 09:01:08 +0000, Soeren Huettemann wrote:

    Doxygen produces an error with the following statement in Fortran
    
    datum='??????????'
    
    It seems that it does not like more than one question mark (?) in a string
    declaration. Maybe it is only a Fortran related problem.

On 2011-07-01 10:43:51 +0000, Soeren Huettemann wrote:

    It does not like
    data='d2spec\' either
    
    I can replace the question marks, but right now I have no clue how to
    replace the back slash (\) in the string.
    
    Would really appreciate if someone could fix this.

On 2011-07-01 14:17:45 +0000, Oleg Batrashev wrote:

    I tried both with 1.7.4-20110629 and 1.7.4, but do not see any error. Could
    you give more elaborate example. Here is my code
    
    program p
      character*20 :: datum
    
      datum = '??????????'
      datum = 'd2spec\'
      print *, datum
    
    end program p

On 2011-07-01 14:39:14 +0000, Soeren Huettemann wrote:

    Created attachment 191098
    string error example
    
    In this more complex example Doxygen produces the error.
    If commenting out the data='??????' it does not produce the error.
    Strange.

On 2011-07-02 08:04:36 +0000, Oleg Batrashev wrote:

    Ok, I looked more carefuly. Your example fails with 1.7.4 but works with
    1.7.4-20110629. Mine actually fails with both versions. I have some time in
    the middle of the next week, so I'll figure this out.

On 2011-07-06 15:23:34 +0000, Oleg Batrashev wrote:

    Ok, I figured it out but haven't yet fixed.
    
    It appears that ??' is a trigraph sequence in C preprocessor and is replaced
    by ^.
    http://www.delorie.com/gnu/docs/gcc/cpp_2.html
    This is fixed in 1.7.4-20110629 because now only files with capitalized
    fortran extensions are being preprocessed.
    
    The second problem is how to treat backslashes in strings. It seems like
    treating them as normal characters is a convention but not strict.
http://sunsite.ualberta.ca/Documentation/Gnu/gcc-2.95.2/html_node/g77_659.html
    Historically, this was in doxygen fortran parser from the beginning. To be
    on the safe side, we should probably introduce some PARAMETER in
    configuration that defines the behavior.
    
    Oleg

On 2011-07-06 17:31:57 +0000, albert wrote:

    the ?? problem, isn't this a duplicate of bug623296 ?
    the backslash problem isn't this also mentioned in bug596872 ?

On 2011-07-07 12:59:12 +0000, Oleg Batrashev wrote:

    (In reply to comment # 6)
    > the ?? problem, isn't this a duplicate of bug623296 ?
    > the backslash problem isn't this also mentioned in bug596872 ?
    
    Yes, they are. I'm going to fix backslash problem with better patch that
    takes into account some FORTRAN_BACKSLASH config variable. Supposingly on
    Sunday.

On 2011-08-17 15:00:30 +0000, Soeren Huettemann wrote:

    Any news ?
    Problem still exists in Doxygen 1.7.5.

On 2011-12-19 12:31:13 +0000, Soeren Huettemann wrote:

    Ok i found a solution for me. You have to use double back slashes. Even if
    the compiler does not care Doxygen needs the second back slash when used in
    string variables.
    I changed my source code and use double back slashes now.

On 2011-12-19 12:32:12 +0000, Soeren Huettemann wrote:

    Do get rid of the error messages when using ? in strings you have to disable
    the preprocessor in doxygen.

**Comment by albert-github** [comment]
With version 1.7.4 I see the problems having problems.
With version 1.9.1 I don't seen any warnings

I think the problem has been solved in the mean time
