### ISSUE TITLE
Manpages don't contain a short description (Origin: bugzilla #654870)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4342]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.4* on platform *Other*
Assigned to: Dimitri van Heesch

On 2011-07-18 20:07:50 +0000, Bas Wijnen wrote:

    When generating manpages, the NAME line consists of the name, followed by a
    - and then nothing. It should be followed by the short description. This is
    important because apropos (aka man -k) searches through and displays these
    parts.
    
    The syntax already allows providing both a short and a long description. The
    short description of the object of which the file is made (for example the
    C++ class) should be used here.
    
    I checked the source to see if I was doing something wrong. In
    mangen.cpp:endTitleHead is the code that outputs the parts I'm seeing. It
    does leave room for the missing part, since the final newline is not
    printed.
    
    I'm not sure what comes after that, the code is too complicated to quickly
    see. It seems some "intro" text is printed, but I can't find anywhere where
    that would be defined.

**Comment by albert-github** [comment]
When having something like:
```
/// \file
/// \brief brief of file
```

we see with the doxygen 1.7.4 version:
![image](https://github.com/doxygen/doxygen/assets/5223533/6923cfa5-215f-4e6a-8756-9fb63197e7f8)

and with the current, 1.9.8, doxygen version:
![image](https://github.com/doxygen/doxygen/assets/5223533/9e02c286-dbff-4919-8f6a-dc14cdc45867)


Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/13742957/example.tar.gz)

I think the problem has been solved in the mean time.
