### ISSUE TITLE
unbalanced div tags when using HTML_HEADER HTML_FOOTER (Origin: bugzilla #655894)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4351]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.4* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[Doxyfile](https://sourceforge.net/projects/doxygen/files/attachments/bug655894_193152_Doxyfile/download/download)_ (ID 193152)
- _[doxygen_bug_655894.tar.gz](https://sourceforge.net/projects/doxygen/files/attachments/bug655894_197273_doxygen_bug_655894.tar.gz/download/download)_ (ID 197273)

On 2011-08-03 10:24:59 +0000, Andrea Vedaldi wrote:

    Created attachment 193152
    Doxygen config
    
    Doxygen 1.7.4 generates an unbalanced HTML file when the HTML_HEDAER,
    HTML_FOOTER options are used. For example, the almost empty project:
    
    code.c:
    void main() {}
    
    empty.html:
    
    
    with the attached Doxygen configuration generates the file html/index.html
    
    $ cat html/index.html 
    
    
      <div id="navrow1" class="tabs">
        <ul class="tablist">
          <li class="current"><a href="index.html"><span>Main&#
    160;Page</span></a></li>
        </ul>
      </div>
    </div>
    <div class="contents">
    </div>
    
    
    which contains an extra </div> tag. This was not an issue with 1.7.2.

On 2011-08-18 07:23:59 +0000, Dimitri van Heesch wrote:

    Hi Andrea,
    
    Can you check if this problem has been fixed with version 1.7.5?

On 2011-09-22 11:04:26 +0000, Joel Rosdahl wrote:

    I'm running 1.7.5.1 and the bug is still left but in another form (note the
    first </div>):
    
    
    </div>
    <div class="header">
      <div class="headertitle">
    <div class="title">KreaTV TOI Reference Documentation</div>  </div>
    </div>
    <div class="contents">
    <ul>      <li><a href="index.html"><span>Main&# 160;Page</span></a></li>
    </ul>
    </div>

On 2011-09-22 11:20:19 +0000, Joel Rosdahl wrote:

    And this actually doesn't seem related to usage of HTML_HEADER/HTML_FOOTER
    at all (in 1.7.5.1, that is), because even with the default header and
    footer, the </div> shows up. See for instance the error on line 33 on
    http://www.stack.nl/~dimitri/doxygen/arch.html here:
    
http://validator.w3.org/check?uri=http%3A%2F%2Fwww.stack.nl%2F~dimitri%2Fdoxygen%2Farch.html&charset=%28detect+automatically%29&doctype=XHTML+1.0+Transitional&group=0

On 2011-09-22 13:21:28 +0000, Joel Rosdahl wrote:

    Removing the </div> output from HtmlGenerator::endQuickIndices seems to fix
    it (and that seems reasonable to me since HtmlGenerator::startQuickIndices
    has an empty implementation), but I don't have any other insight in this
    since I'm not familiar with the code.

On 2011-09-22 17:11:46 +0000, Dimitri van Heesch wrote:

    Hi Joel,
    
    Can you please attach a self-contained example (source+config file in a tar
    or zip) that allows me to reproduce the problem?

On 2011-09-22 17:59:56 +0000, Joel Rosdahl wrote:

    Created attachment 197273
    Config for reproducing the bug
    
    Certainly. Attached is a tar file containing a doxygen config and a source
    file that produce the following html/index.html:
    
    
      <div id="navrow1" class="tabs">
        <ul class="tablist">
          <li class="current"><a href="index.html"><span>Main&#
    160;Page</span></a></li>
        </ul>
      </div>
    </div>
    <div class="contents">
    </div>
    
    I.e., there are two <div> and three </div> when using an empty header and
    footer.
    
    By the way, I was probably mistaken in comment # 3: I guess the issue in the
    pages under http://www.stack.nl/~dimitri/doxygen/ is because the used
    HTML_HEADER doesn't contain the
    
    <div id="top">
    
    that the default header has.

On 2011-09-22 20:00:48 +0000, Dimitri van Heesch wrote:

    Using an empty header and footer will not work.
    This not a bug, but wrong usage. 
    
    You need to follow this procedure when customizing the headers and footers:
    http://www.doxygen.org/customize.html#minor_tweaks
    
    Let me know if you still see problems when using this approach.

On 2011-09-22 21:22:16 +0000, Joel Rosdahl wrote:

    (In reply to comment # 7)
    > Using an empty header and footer will not work.
    > This not a bug, but wrong usage. 
    
    The real issue for me is this:
    
    * I have a custom header and footer. (Actually, they are auto-generated and
    vary for different Doxygen invocations.)
    * The header and footer work well with a previous Doxygen version.
    * I upgraded to Doxygen 1.7.5.1.
    * The generated pages now become faulty.
    
    If it's not expected that custom headers and footers can be reused without
    modification when upgrading Doxygen, I understand your position, but then
    that fact should perhaps be documented somewhere?
    
    And, as mentioned in comment # 6, you seem to have been hit by the same
    behaviour change yourself for the public Doxygen HTML pages. :-)
    
    But regardless, would it be hard to make the HTML between the header and the
    footer balanced like before?
    
    > You need to follow this procedure when customizing the headers and
    footers:
    > http://www.doxygen.org/customize.html#minor_tweaks
    > 
    > Let me know if you still see problems when using this approach.
    
    If you mean that "doxygen -w html ..." should be run whenever the
    header/footer is to be customized, then that is a problem for me since my
    header and footer are generated by a script. It's of course no problem to
    generate an extra <div> in the header (that matches the extra </div> from
    Doxygen), but it's just surprising that it needs to be done after an upgrade
    that only increments that last number in the version (1.7.2 -> 1.7.5.1). :-)

**Comment by albert-github** [comment]
The combination of header and footer file from a version are consistent (in XHTML sense), when using files from an older version problems might arise/

From the documentation (paragraph: Header, Footer, and Stylesheet changes) :
> Warning
> The structure of headers and footers may change after upgrading to a newer version of doxygen, so if you are using a custom header or footer, it might not produce valid output anymore after upgrading.

An update strategy of the header / footer files between versions is not feasible due to the differences that can have been included by the user.

So I think this bug can be closed as usage.
