### ISSUE TITLE
doxygen vs spell checking (Origin: bugzilla #656774)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4368]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.6.3* on platform *Other*
Assigned to: Dimitri van Heesch

On 2011-08-17 20:27:19 +0000, Imre PÃ©ntek wrote:

    I think it would be nice if there would be a way to spellcheck
    (aspell/hunspell) doxygen comments

**Comment by ferdymercury** [comment]
A workaround is to use https://github.com/CJCombrink/SpellChecker-Plugin

**Comment by albert-github** [comment]
Code spelling is quite important as spelling errors are always catching the eyes (once when spotted) and are annoying.
It is the main responsibility of the code developer to have these correct and it would be nice when there are tools that support the user with it.

I think there are a number of spell checkers available like the already mentioned aspell, hunspell but also https://github.com/codespell-project/codespell.git

It looks like https://github.com/CJCombrink/SpellChecker-Plugin is mainly geared towards usage by QtCreator and uses under the hood Hunspell

**Comment by albert-github** [comment]
As already noted before code spelling is quite important But I think it is outside the scope of doxygen (and something not to be done by doxygen).
