### ISSUE TITLE
Wrong formatting and wrong line brakes in RTF (Origin: bugzilla #657090)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4373]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.5.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2011-08-22 16:15:09 +0000, Hans wrote:

    The html and TeX documentation is OK, but in rtf the brief of
    FNAME_tstPathInfo is formatted as heading and with next heading "Defines" in
    one line (see screen shots of PDFs generated from TeX and rtf - the page
    brake in the TeX-PDF is by chance).
    
    In my fname.h I have
    
    #ifdef DOS
      #define MaxFNameLen   12      /*!< \brief Max.\ Laenge von Dateinamen
    (name.ext).
         \remark .... */
    #else
      #define MaxFNameLen   FILENAME_MAX    /*!< \brief Max.\ LÃ¤nge fÃ¼r
    Dateinamen (aus stdio.h).
        \remark ... */
    #endif
    
    
    /***********************************************************************//*!
    
    \brief FNAME_tenPathType: Typ fuer Dateipfad
    
    \remark
    - Drive und DriveRoot gibt es nur bei DOS/Win
    - Die Reihenfolge ist signifikant, es darf >FNAME_nenPTRoot oder
      >= FNAME_nenPTHost abgefragt werden
    */
    typedef enum {
      FNAME_nenPTNone,      /*!< \brief Leerstring oder NULL */
      ...
    } FNAME_tenPathType, *FNAME_tpenPathType;
    
    
    /***********************************************************************//*!
    
    \brief FNAME_tstPathInfo: Ergebnis von FNAME_enAnalysePath
    
    \remark
    - Index als "xo" da Typ tSize in POOL
    ...
    */
    typedef struct {
      int8          en8PathType;    /*!< \brief Typ, siehe FNAME_tenPathType */
      ...
    } FNAME_tstPathInfo, *FNAME_tpstPathInfo;
    
    
    
<https://lh6.googleusercontent.com/-RUWmuXG8qZ8/TklPRxUJ2eI/AAAAAAAAKO4/bAYG6G9Zw7o/s800/Update32
    -TeX-Ok.jpg>
    
<https://lh5.googleusercontent.com/-MacGZ72x8YA/TklPSLZnTsI/AAAAAAAAKO8/rAcQYyXWH8c/s800/Update32
    -rtf-Error.jpg>
    
    Tested with doxygen 1.7.4 and 1.7.5.1

**Comment by albert-github** [comment]
With version 1.7.4 I see the problem as indicated in the rtf file.
In version 1.8.16 the separation is done properly

I think the problem has been solved in the mean time
