### ISSUE TITLE
\ingroup does not terminate \brief description (Origin: bugzilla #657612)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4383]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.5.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2011-08-29 12:43:36 +0000, j6t@kdbg.org wrote:

    Consider the following file:
    
    --- 8< ---
    /*! \class Foo
     *  \brief Short description ends here
     *  \ingroup Bla
     *
     *  Long description begins here.
     */
    
    class Foo
    {
    };
    --- 8< ---
    
    With a standard Doxyfile, the class list (annotated.html) shows the
    following:
    
    Foo	Short description ends hereLong description begins here 
    
    If the \ingroup line is removed or moved above the \brief line, then the
    result is as expected, which is:
    
    Foo	Short description ends here

On 2011-08-30 11:43:45 +0000, j6t@kdbg.org wrote:

    FWIW, the behavior was introduced in 1.5.5 (1.5.4-20080123 behaves as
    expected).
    
    From the code change in 1.5.5 it seems that \ingroup should not terminate a
    brief description. But what about the subsequent paragraph break (empty
    line) - shouldn't it end the brief description like it does when \ingroup is
    not present?

**Comment by albert-github** [comment]
With version 1.7.5.1. I see the behavior as described.
This behavior is not present in version 1.5.4 (as indicated as well) and it is also not present in version 1.8.20

I think the problem has been solved in the mean time.
