### ISSUE TITLE
Automatic crash reporting (Origin: bugzilla #658181)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4394]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2011-09-04 14:37:10 +0000, Oleg wrote:

    To make doxygen more stable it is very helpful to automatically generate and
    send crash reports.
    Generating crash report manually and manually submitting it into bug tracker
    is very complicated procedure for most of the users. And even these how can
    make it prefer to not waste their time.
    Automatic submission (by one click or no clicks at all) raises crash reports
    flow in thousands times.
    That big flow can drive developer's efforts to a right direction when these
    bugs fixed first that affects most users and not one that has a time to
    submit it in a bug tracker. There is a statistics that 1 percent of top
    crash bugs fixes 50% of all crashes: Â«In recent months, Microsoft has
    learned that 80 percent of the errors and crashes in Windows and Office are
    caused by 20 percent of the entire pool of bugs detected, and that more than
    50 percent of the headaches derive from a mere 1 percent of all flawed
    code.Â»
    http://www.crn.com/news/security/18821726/microsofts-ceo-80-20-rule-applies-
    to-bugs-not-just-features.htm
    
    I represent http://www.crash-server.com a crash reporting and analyzing
    service.
    I would like to suggest adding to doxygen of crash report sending feature
    for free.
    
    In very short it looks like this: doxygen crashes, the user is offered to
    send the crash report to the manufacturer. The report is uploaded, system
    analyzes it and then group it with similar problems. Further developers can
    download the interesting memory dump, open it in a debugger and try to find
    and fix a bug.
    Key feature is that all of that does automatically in âone clickâ.
    Experience shows that almost no users send a crash report if this require
    any difficult actions (sending an e-mail or registering in bug tracker is
    difficult enough). One click is so easy way that some users do it (many
    users do not do even this).
    Other key feature is that all preprocessing of crash reports is done for
    you. You have no need to open each report and see that you already has fixed
    it.
    
    The small description and demonstration are accessible here:
    http://www.crash-server.com/Demo/Demo.aspx
    
    Also you can open a demo project and browse a little:
    http://www.crash-server.com/Applications.aspx?ClientID=sample (Login as
    Guest)
    
    I will be happy to answer any your questions, comments and opinions at info
    @crash-server.com

**Comment by albert-github** [comment]
It looks nice to get automatic crash reports but a good crash report for doxygen will, normally, also have to include the used source code and this is quite often not really wanted by the user. Also a stack trace would be useful, but this requires a debug version that will be quite slow.
When a user won't take the time and effort to report a crash the user most likely won't respond to subsequent questions either and it might be very hard / not possible to solve the crash.

Also users are quite reluctant to software that is communicating with the outside world and especially when it is communicating not with the developers directly but, at first, with a third party.

pinging the address http://www.crash-server.com or https://www.crash-server.com was not successful.

I think this is something doxygen should not have.
