### ISSUE TITLE
Nesting in external modules is not displayed (Origin: bugzilla #658430)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4396]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.4* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxygen-bug.tar.gz](https://sourceforge.net/projects/doxygen/files/attachments/bug658430_195841_doxygen-bug.tar.gz/download/download)_ (ID 195841)

On 2011-09-07 04:00:18 +0000, Jitse Niesen wrote:

    Created attachment 195841
    Example exhibiting the bug
    
    If an external module contains external submodules, the module listing does
    not display the nesting.
    
    The attached example illustrates what I mean. There are four files:
    
       doc/Doxyfile-main
       doc/Doxyfile-unsupported
       src/modules.c
       unsupported/src/unsupported-modules.c
    
    Doxyfile-main generates the documentation for src/modules.c which contains
    two modules, 'Module A' and 'Module B'.
    
    Doxyfile-unsupported generates the documentation for unsupported/src
    /unsupported-modules.c which contain one module called 'Unsupported
    modules'. That module contains two submodules, 'Module U1' and 'Module U2'.
    
    Both sets of documentation exchange information via tag files.
    
    The module list generated by Doxyfile-unsupported is as expected:
    
       * Unsupported modules
           * Module U1
           * Module U2
       * Module A [external]
       * Module B [external]
    
    However, the module list generated by Doxyfile-main is NOT as expected:
    
       * Module A 
       * Module B
       * Unsupported modules [external]
       * Module U1 [external]
       * Module U2 [external]
    
    It does not indicate that 'Module U1' and 'Module U2' are submodules of
    'Unsupported modules'. I would like to say this:
    
       * Module A 
       * Module B
       * Unsupported modules [external]
           * Module U1 [external]
           * Module U2 [external]
    
    This looks similar to bug 172964, but that is a very old report, and it also
    states that tag files do not store group membership, while it seems to me
    that they do indicate group membership but that it is not used when
    generating the module list.

**Comment by albert-github** [comment]
In the 1.7.4. version we see the output as indicated:

![image](https://user-images.githubusercontent.com/5223533/161593161-14fbf0cc-ac72-49d8-abc6-cda11be1585a.png)

and

![image](https://user-images.githubusercontent.com/5223533/161593213-d0966dd5-1963-4901-b436-65f26dcee3b7.png)

With the current 1.9.3 (c0b9eafbfb53286ce31e75e2b6c976ee4d345473) version we see:

![image](https://user-images.githubusercontent.com/5223533/161593333-1c96e7ac-9ea9-4292-bf25-f3c42e4e7bb6.png)

and

![image](https://user-images.githubusercontent.com/5223533/161593397-bbb46927-367e-4fb7-8670-23b1681a8d87.png)


I think the problem has been solved in the mean time.
