### ISSUE TITLE
interactive svg zoom and display problems (with partial solution) (Origin: bugzilla #658549)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4398]
status NEW severity *major* in component *general* for *---*
Reported in version *1.7.5.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[svgpan.js](https://sourceforge.net/projects/doxygen/files/attachments/bug658549_195981_svgpan.js/download/download)_ (ID 195981)

On 2011-09-08 12:45:01 +0000, plasmahh@gmx.net wrote:

    Created attachment 195981
    a working version
    
    Hi,
    
    I encountered several problems with the new interactive svg feature. 
    
    For svgs included via the mainpage (e.g. by using \dotinclude within a
    \mainpage section), the path to the svgpan.js file is wrong (the two
    relative .. are too much).
    
    Especially in that case, it tries to call
    p.window.registerShow(sectionId,show); but sectionId is not fonud, which
    causes  the whole script to abort.
    
    The calculation of the intial zoom and position is wrong, zoom factor as
    well as position are way of (depending on the actual svg contents). Instead
    of the viewWdith, the svgs bounding box width needs to be used.
    
    I have simply made my svgpan.js work fine for me, completely removing the
    registerShow call, and replacing the  viewHeight by bb.height.

**Comment by albert-github** [comment]
Due to a missing example it is unclear what has been done to show te problem and make it reproducible.
In the mean time also the handling of the dot images has changed as well as the resulting svg images.

I think that the issue does not exist anymore, but in the current state it is incomplete.
