### ISSUE TITLE
preprocessor stops expanding macros after nested comment (Origin: bugzilla #659262)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4413]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.5.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxytest.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug659262_197449_doxytest.zip/download/download)_ (ID 197449)
- _[doxytest_2.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug659262_197450_doxytest_2.zip/download/download)_ (ID 197450)

On 2011-09-16 15:28:20 +0000, digitalfreak@gmx.de wrote:

    I have used the following settings to remove some macros within a c-header:
    
    ENABLE_PREPROCESSING = YES
    MACRO_EXPANSION = YES
    EXPAND_ONLY_PREDEF = YES
    PREDEFINED = TRC_EXPLAIN()= 
    
    After a nested comment sequence like this:
    
    /****/
    /**
    /****/
    
    the preprocessors seems to stop expanding all remaining macros in this file.

On 2011-09-25 14:37:59 +0000, Dimitri van Heesch wrote:

    Nested comments are not really legal C, but I didn't notice a problem with
    doxygen handling them.
    
    Can you please attach a self-contained example (source+config file in a tar
    or zip) that allows me to reproduce the problem?

On 2011-09-26 08:24:02 +0000, digitalfreak@gmx.de wrote:

    Created attachment 197449
    Example

On 2011-09-26 08:26:02 +0000, digitalfreak@gmx.de wrote:

    Comment on attachment 197449
    Example
    
    I know that it is not realy allowed but our compiler handles this very
    laxly. I already removed it from the real code.
    
    The attached example results in a very unexpected HTML output. A "doxygen -d
    Preprocessor" shows the problem.

On 2011-09-26 08:36:41 +0000, digitalfreak@gmx.de wrote:

    Comment on attachment 197449
    Example
    
    Sorry this example was realy bad c. I was in a rush.

On 2011-09-26 08:37:48 +0000, digitalfreak@gmx.de wrote:

    Created attachment 197450
    Example
    
    Improved example.

On 2012-11-14 14:28:33 +0000, digitalfreak@gmx.de wrote:

    I can still reproduce this bug with 1.8.2
    
    Why is this bug still unconfirmed even if I have provided a proper example?

**Comment by albert-github** [comment]
As written in the comments the code is not really legal C but some compilers support it./
With the 1.7.5.1 version of doxygen we don't get a warning and the macro is not expanded.
With the current version (1.9.4 (5d15657a55555e6181a7830a5c723af75e7577e2)) we get a warning in the form:
```
test.h:30: warning: Reached end of file while still inside a (nested) comment. Nesting level 1 (probable line reference: 14)
```
and the macro is not expanded.

Seen the fact that this is not really legal C code I think this is usage (with now a warning about the nested comment).
