### ISSUE TITLE
Concatenation of strings for initializer of C variable fails (Origin: bugzilla #660948)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4422]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.5.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[concaterror.tar.gz](https://sourceforge.net/projects/doxygen/files/attachments/bug660948_198290_concaterror.tar.gz/download/download)_ (ID 198290)

On 2011-10-05 05:22:27 +0000, Baard Nossum wrote:

    Created attachment 198290
    Doxyfile and a small source file that show the error
    
    Only the last part of a string initialization is documented when the
    initializer is written as several strings.
    
    
    The following:
    
    /** @a aConcat initialization is not shown correctly */
    char *aConcat = "A C-string can be the result" "of concatenation\n";
    
    give:
    
    Variables
    char * 	aConcat = "of concatenation\n"
    
    while it should give:
    char *  aConcat = "A C-string can be the resultof concatenation\n"

**Comment by albert-github** [comment]
With version 1.7.5.1 I could reproduce the problem.
With version 1.8.20 the problem is gone (looks like it is gone since 1.8.2)

I think the problem has been solved in the mean time.
