### ISSUE TITLE
Doxygen is not able to document parameter types for Python code (Origin: bugzilla #661370)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4425]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.5.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2011-10-10 11:35:27 +0000, Sorin Sbarnea wrote:

    While doxygen is able to document parameter types for PHP, it is not able to
    do the same for Python code.
    
    PHP example:
    
    @param list $arg description ...
    @param list|string $arg2 description ...
    @return list|False
    
    The main problem is that having $ in the generated documentation does make
    any sense in Python.
    
    Also, I do understand that the parsing would not be possible without $.
    
    I can see two possible workarounds for this: 
    # 1 drop `$` from when generating doc for py files
    # 2 require braces for the parameter type
    
    @param (list|string) $arg2 description ...

On 2015-05-01 15:50:33 +0000, Fabian Raab wrote:

    You can also use the `:` notation:
    
    @param list|string arg: description
    
    related issue: https://bugzilla.gnome.org/show_bug.cgi?id=748758

**Comment by albert-github** [comment]
Seen the description (but no example) here and the description in #6544 (and corresponding issue #6462), I think,  this problem is also fixed.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
