### ISSUE TITLE
Missing <dl> class for parameters and exceptions. (Origin: bugzilla #661736)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4430]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.7.5.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2011-10-14 07:30:01 +0000, doxygen@ca.sh13.net wrote:

    @exception, @param and friends result in
    <dl><dt><b>Exceptions:</b></dt></dl> which cannot be styled with CSS as
    there is no matching rule to identify whether this is the "Exceptions" part
    or the "Parameters" part. Adding a class to the <dt> would be very helpful.

On 2011-10-14 08:09:51 +0000, doxygen@ca.sh13.net wrote:

    This should be probably handled by
    HtmlGenerator::startSimpleSectstartSimpleSect.

On 2011-11-28 08:39:55 +0000, doxygen@ca.sh13.net wrote:

    That seems to be fixed in the latest release.

On 2011-11-28 08:53:25 +0000, doxygen@ca.sh13.net wrote:

    Ah no, it's there for return, note, remark, warning, but not for parameters
    and exceptions.

**Comment by albert-github** [comment]
With version 1.7.5.1. I see that parameters and exceptions don't have the `class=` attribute with `<dl>` with version 1.8.15 this is present.

I think the problem has been solved in the mean time
