### ISSUE TITLE
Conditional compilation omits documentation in #if EXPR ... #endif (Origin: bugzilla #662007)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4434]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.7.6.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[TestDoxygen.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug662007_199218_TestDoxygen.zip/download/download)_ (ID 199218)
- _[TestDoxygen120305.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug662007_208988_TestDoxygen120305.zip/download/download)_ (ID 208988)

On 2011-10-17 14:27:22 +0000, jroyston@gmx.de wrote:

    Created attachment 199218
    zip file of program to reproduce the problem, with Doxyfile
    
    The application(in C for AVR/GCC with Atmel AVR Studio 5) has the form:
    
    // In the file config.h 
    #include "options.h"  // contains #define MAX7456OSD 2
    #define VTIDEVICE MAX7456OSD
    // The file MAX7456.c contains in part:
    #include "config.h"
    // Now the problem part:
    #if VTIDEVICE == MAX7456OSD
    // Functions, variables and Doxygen comments follow
    #endif /* VTIDEVICE == MAX7456OSD */
    
    The output from Doxygen contains no documentation for the part of MAX7456.c
    between
    #if VTIDEVICE == MAX7456OSD and #endif
    AVR/GCC compiles the program correctly, it produces code in the conditional
    part.
    
    Workaround:
    If we #define VTIMAX7456OSD in options.h and use #ifdef VTIMAX7456OSD
    instead of
    #if VTIDEVICE == MAX7456OSD, then Doxygen produces the expected
    documentation.
    
    The attached zip file demonstrates the problem. It contains the Doxyfile
    used.
    The application is a small part of a project, all the .c files containing
    #if Expr
    #endif showed the problem.
    
    PS Thanks for a great application

On 2012-03-03 18:59:01 +0000, Dimitri van Heesch wrote:

    Problem seems to be fixed since version 1.7.6, can you please verify this?

On 2012-03-05 10:23:52 +0000, jroyston@gmx.de wrote:

    Created attachment 208988
    Example C code with Doxyfile
    
    File is in ZIP format. See coments in bug report

On 2012-03-05 10:28:14 +0000, jroyston@gmx.de wrote:

    The comments which I just entered disappeared
    The attached ZIP file contains an example and the Doxyfile
    It would be expected that lines 76 and 86 in the file config_rules would
    produce output in the documentation
    The variables used are defined in file config.h
    Thanks for the help, Jerry

**Comment by albert-github** [comment]
In the second example we see that in the file `config.h` we have (at the end):
```
#include "config_rules.h"
```
and in the file `config_rules.h` we have:
```
#include "SIMRCV.h"
#include "config.h"
#ifndef _CONFIG_RULES_H_
        #define _CONFIG_RULES_H_
```
so when processing  `config_rules.h` the define `_CONFIG_RULES_H_` is set in `config.h` so nearly all of `config_rules.h` is skipped.

As doxygen does nor keep the documentation content of the included file in the original file the content is "lost".
Probably best solution would be:
```
#ifndef _CONFIG_RULES_H_
        #define _CONFIG_RULES_H_
#include "SIMRCV.h"
#include "config.h"
```

I think this problem is a combination of usage and solved in the mean time.
