### ISSUE TITLE
Add head lines of pages, groups etc to the search index (Origin: bugzilla #662089)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4438]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2011-10-18 12:55:21 +0000, Henning StrÃ¶ker wrote:

    Currently it is possible to search for documented elements of the source
    code only. While a complete full text search might not be easy to implement
    (maybe not even desirable), it should be possible to search for words in
    group or page headlines.

**Comment by albert-github** [comment]
With the previous (1.9.7) doxygen version the page / group titles are present but are a bit cumbersome to search (one has to start with the first word)
With the current (1.9.8) doxygen version one can input any word in the title, furthermore also the titles from sections / subsectctions /... are added.

I think the problem has been solved in the mean time
