### ISSUE TITLE
overflowing line with long c++ template types as arguments (Origin: bugzilla #662661)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4448]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.5.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxygen_test.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug662661_199909_doxygen_test.zip/download/download)_ (ID 199909)

On 2011-10-25 09:36:32 +0000, magnus.wahrenberg@gmail.com wrote:

    Created attachment 199909
    a test cpp, doxyfile as well as images of the output.
    
    c++ templates that nest can form rather long typenames. Usually these would
    be typedef:ed into something smaller, but if a long typename is used in a
    function declaration, doxygen generates a very long line, that overflows the
    css background. (see overflow0.png and overflow1.png in the zip-file)
    
    See also: http://stackoverflow.com/questions/7877074/doxygen-line-breaks-
    for-lenghty-c-template-types
    
    
    If the .paramname and .paramtype 's white-space tag is set to normal rather
    than no-wrap, thing appear to behave much better.

**Comment by albert-github** [comment]
With the doxygen version 1.7.5.1. I can see the problem.
The layout since that time has been changed considerably and for version 1.8.16 I don´t see the problem anymore.

I think the problem has been solved in the mean time
