### ISSUE TITLE
token pasting/concatenation does not work. (Origin: bugzilla #663104)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4452]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.7.5.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2011-10-31 14:51:39 +0000, Irun Walberg wrote:

    Hi,
    
    I would like the following c-code:
    
    #define part_is_defined(part) \
         (defined(__ ## part ## __) || defined(__AVR_ ## part ## __))
     
    // A1 Family
    #define XMEGA_A1 ( \
             part_is_defined(ATxmega64A1) || \
             part_is_defined(ATxmega64A1U) || \
             part_is_defined(ATxmega128A1) || \
             part_is_defined(ATxmega128A1U)   \
    )
    
    
    To evaluate XMEGA_A1 as true when __AVR_ATxmega64A1__ is a predefined macro
    in a project. This works fine with our C preprocessors. Using XMEGA_A1 gives
    me the following warning:
    
    preprocessing issue while doing constant expression evaluation: syntax error
    
    It seems like doxygen isn't able to parse the
    #define part_is_defined(part) \
         (defined(__ ## part ## __) || defined(__AVR_ ## part ## __))
    
    and replace it with
    #define part_is_defined(ATxmega64A1) \
         (defined(__ATxmega64A1__) || defined(__AVR_ATxmega64A1__))
    
    In advance, thank you for your time.

On 2012-04-26 07:22:26 +0000, Dean Camera wrote:

    Additional: this appears to be a bug in the Doxygen preprocessor. A minimal
    test case for the bug is the following C file run through Doxygen with
    default settings:
    
    // TEST.c:
    #define part_is_defined(part) \
         (defined(__ ## part ## __) || defined(__AVR_ ## part ## __))
    	 
    #if part_is_defined(ATxmega64A1)
    	#define TEST
    #endif
    // END TEST.c
    
    With the definition of part_is_defined() changed to remove the outer braces:
    
    #define part_is_defined(part) \
         defined(__ ## part ## __) || defined(__AVR_ ## part ## __)
    
    The code is parsed by Doxygen without warnings, however the warning is still
    generated if part_is_defined() is used elsewhere with braces. With the
    modified macro definition above this will not produce a warning:
    
    #if part_is_defined(ATxmega64A1)
    
    But this will:
    
    #if (part_is_defined(ATxmega64A1))

**Comment by albert-github** [comment]
With version 1.7.6.1 I can reproduce the problem, with version 1.8.17 the problem is gone.

I think the problem has been solved in the mean time.
