### ISSUE TITLE
Group in Latex does not work (Origin: bugzilla #663157)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4454]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.5.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2011-11-01 12:58:39 +0000, duongtu wrote:

    The @defgroup and @addtogroup are work when create html, but does not work
    when working with pdf :(.
    
    I've attached my example.
    
    Please help me fix it, or work arround with this issue.
    
    Regards,
    Tu

**Comment by albert-github** [comment]
There is no attachment, so hard to reproduce (small test worked).
