### ISSUE TITLE
Preprocessor unable to properly handle "iso646.h" keywords in "complex?" conditionals expressions. (Origin: bugzilla #663194)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4456]
status NEW severity *major* in component *general* for *---*
Reported in version *1.7.5.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2011-11-01 20:51:13 +0000, Matthew wrote:

    When attempting to parse a source file that contains certain expressions in
    the #if and #elif directives, Doxygen produces the following warning:
    
    warning : preprocessing issue while doing constant expression evaluation:
    syntax error
    
    An example of such an directive would be this:
    #if (not defined(_WIN64) or not _WIN64) and (not defined(DOXYGEN) or not
    DOXYGEN)
    #endif
    
    Converting the expression to use the operators themselves does not have an
    issue with the expression.
    
    The following expression is parsed and treated just fine.
    #if not defined(_WIN64) or not _WIN64
    #endif

**Comment by albert-github** [comment]
With the 1.7.5.1 version I get the warning as indicated.
With the current version (1.9.4 (5d15657a55555e6181a7830a5c723af75e7577e2))) this warning is gone.

Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/9093605/example.tar.gz)


I think the problem has been solved in the mean time.
