### ISSUE TITLE
Incorrect processing of the \date command in C++ (Origin: bugzilla #664652)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4473]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.5.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[class_c_w_a_p_m_m_s_filter.html](https://sourceforge.net/projects/doxygen/files/attachments/bug664652_202007_class_c_w_a_p_m_m_s_filter.html/download/download)_ (ID 202007)

On 2011-11-23 16:04:53 +0000, Marian Kechlibar wrote:

    Created attachment 202007
    The incorrectly formatted HTML (Date: is wrong).
    
    Situation: Only happens in documentation of a C++ class, and only in case if
    the \date command is used as the last-but-one, and is followed by the \brief
    command. I wasn't able to find any other situations triggering this
    behavior. Even simple permutations of the commands will result in correct
    HTML.
    
    Example of the offending documentation (from production code):
    
    /**
     * \class CWAPMMSFilter
     * \author CircleTech, s.r.o.
     * \version 1.0
     * \date 2010
     * \brief Removes APs whose names contain MMS or WAP.
     * 
     * This filter removes all APs whose bearer is GPRS and whose name contains
    the string MMS or the string WAP. The search is case-sensitive
     * (thus, 'mms' would still be accepted). 
     * 
     * All WLAN APs are accepted by the filter, regardless of name.
     * 
     * Usually, the WAP/MMS APs aren't suitable for networking.
     */
    
    Result: The resulting HTML is not correctly indented. The date header
    doesn't form its own paragraph, and is immediately followed by the
    documentation text that follows. I have added the resulting HTML as an
    attachment.
    
    The problem persists for several releases of Doxygen, as far back as I
    remember (surely back to 1.6.0).

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7037

**Comment by albert-github** [comment]
Checked against:
- 1.8.16: problem present
- 1.8.19: problem present
- 1.8.20: problem gone

So I think the problem has been solved in the mean time.

Example used: [example.tar.gz](https://github.com/doxygen/doxygen/files/5135944/example.tar.gz)
