### ISSUE TITLE
The parameters/exceptions/etc. lists shouldn't use <b> (Origin: bugzilla #665010)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4479]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.7.5.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2011-11-28 08:55:47 +0000, doxygen@ca.sh13.net wrote:

    Currently, the lists for Parameters etc. use <dl><dt><b>... but it would be
    better to style this with CSS only. I.e. by adding an additional label to
    the <dl>, the <b> tag could be removed and replaced with a CSS rule, making
    it easier to style.
    
    For instance, use
    
    <dl class="return item"><dt>foo:</dt>...
    
    And then style using dl.item dt { font-weight: bold; }
    
    Gives the same result, makes the markup easier. Right now, I have to use two
    CSS rules to result <dl><dt> (which I'm using elsewhere) and <dl><dt><b>
    (otherwise, the <b> overrides the other rule.)

**Comment by albert-github** [comment]
For the `Parameters` we see in the 1.7.5.1. version:
```
<dl><dt><b>Parameters:</b></dt><dd>
```
and in the 1.9.4 version:
```
<dl class="params"><dt>Parameters</dt><dd>
```

Similar constructs are there for other entities.

I think the problem has been solved in the mean time.
