### ISSUE TITLE
Arguments implemented with get_func_args() are rejected (Origin: bugzilla #665117)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4481]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.0* on platform *Other*
Assigned to: Dimitri van Heesch

On 2011-11-29 10:08:05 +0000, Samu Voutilainen wrote:

    PHP allows argument implementation in addition of classic foo($bar, $baz) to
    implement free-form arguments with get_func_args() and get_num_args() which
    in a way works quite like int main(..):n argc and argv.
    
    When arguments are implemented using this kind of way, there isnât
    arguments defined in the function (you may not pass arguments for every time
    at all, for example). Currently Doxygen does not allow @param definitions
    without those arguments, causing the documentation of arguments be lost.
    
    Foo.php:85: warning: argument 'first' of command @param is not found in the
    argument list of Foo::add()
    Foo.php:85: warning: argument 'operator' of command @param is not found in
    the argument list of Foo::add()
    Foo.php:85: warning: argument 'second' of command @param is not found in the
    argument list of Foo::add()

On 2012-01-24 12:00:05 +0000, Samu Voutilainen wrote:

    *** Bug 668176 has been marked as a duplicate of this bug. ***

On 2012-03-12 10:41:46 +0000, Samu Voutilainen wrote:

    Happens with 1.8.0 still.

**Comment by albert-github** [comment]
The problem here is the special meaning of the function `func_get_args()` and as doxygen is not a compiler it has no knowledge of this function and its intentions.  Furthermore the function`func_get_args()` will return an array and this would anyway be seen by doxygen as 1 argument.

I don't think this is a bug but usage.
