### ISSUE TITLE
CHM indexing with tag files (Origin: bugzilla #665404)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4484]
status NEW severity *normal* in component *general* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[index_hhc.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug665404_202620_index_hhc.zip/download/download)_ (ID 202620)

On 2011-12-02 14:54:15 +0000, Will Powell wrote:

    I wondered if this is the same as issue 122095, but didn't understand the
    entries well enough.
    
    Basically the insersion of tags work really nicely between CHMs iff they are
    in the HTML doxygen generates. However, the additional tags are missing in
    the generated hhc. I wrote a python script to add them, so I can get around
    this issue, but it would be nice if doxygen added them to the hhc.
    
    (If doxygen doesn't do this, I can't click on links in the left contents
    pane tree and move from one CHM to another the way I'd expect)
    
    Attached are a ".old" and a ".hhc". The .old is what doxygen generates, and
    the ".hhc" is how my python script modifies the doxygen generated hhc.
    
    Hope this improves doxygen :)

On 2011-12-02 14:55:20 +0000, Will Powell wrote:

    Created attachment 202620
    index.hhc and index.old as in BZ description

**Comment by albert-github** [comment]
It is unclear what is going on as a project is missing and thus also no Doxyfile present.


Setting issue to incomplete.
