### ISSUE TITLE
FILE_VERSION_FILTER incorrectly run for file references from a tagfile with filename "<tagfile>:/my/path" (Origin: bugzilla #665439)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4485]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.2-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2011-12-02 22:54:29 +0000, Yves wrote:

    Steps to reproduce:
    1. Generate a tagfile for a project with EXTRACT_ALL set to YES --> e.g.,
    "project.tags"
    2. From another project, refer to "project.tags" and set FILE_VERSION_FILTER
    3. During build, the script selected by FILE_VERSION_FILTER is run for all
    file references contained in the tagfile, resulting in output of the form:
    
    Input 
    Project1:
     GENERATE_TAGFILE       = project.tags
     EXTRACT_ALL            = YES
    
    Project2:
     TAGFILES               = ../project/project.tags
     FILE_VERSION_FILTER = "/bin/sh version_script.sh"
    
     $ cat version_script.sh
     echo "\"Filename=$1\""
    
    Output building docs for project2:
     <snip>
     Reading and parsing tag files
     Reading tag file `../project/project.tags'...
     Version of project.tags:/<snip>/project/main.cpp :
    "Filename=project.tags:/<snip>/project/main.cpp"
     Version of project.tags:/<snip>/project/main.h :
    "Filename=project.tags:/<snip>/project/main.h"
     <snip>
    
    The input for the version script appears to be of the form
    "project.tags:/my/path/myfile.cpp", which is not a valid filename (and hence
    does not exist) causing a 'normal' version-checking script to fail on this
    input.
    
    Thanks for a very nice and useful tool.

On 2012-11-18 11:07:00 +0000, Dimitri van Heesch wrote:

    Changed version 'latest' to '1.8.2-SVN' so I can remove 'latest' as an
    option as it is a moving target.

**Comment by albert-github** [comment]
There are 2 issues here:
- name if the file, as indicated in the external command just the file name of the tag file is used, this is not correct and has been solved in the mean time (1.9.4 (5d15657a55555e6181a7830a5c723af75e7577e2))
- the question "Should the FILE_VERSION_FILTER be applied to a tag file?". I don't think so.
  I've just pushed a proposed patch, pull request #9443

**Comment by albert-github** [comment]
Adjusted code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.7.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
