### ISSUE TITLE
Participate in DocSpec (Origin: bugzilla #667160)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4518]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2012-01-03 02:51:47 +0000, gossi wrote:

    Hi,
    
    I currently worked out a specification to make results of DocTools
    interoperable. This is completely new and the spec is just one day old. The
    idea of this spec is, that doctools deliver their output in this
    interoperable format and generating the output can be done by others, that
    don't want to work on the parsing part.
    
    The benefits would be:
    
    - End users can choose whatever doctool they want and which output generator
    they want.
    - Doctool developers can focus on parsing the code, generate a standardised
    output and leave the output generation to the end users
    
    My blog post with my motivation for creating this: http://gos.si/blog
    /docspec-as-interoperable-file-format-between-doctools
    
    As I said the DocSpec is not older than a day, you are invited to join here.
    Also if you feel like this idea suits your doctool, feel free to jump over
    to express your interesst in participating as an implementor.
    
    The DocSpec is on github, ready to fork: https://github.com/gossi/docspec
    
    Thank you
    gossi

On 2012-01-03 10:50:27 +0000, AndrÃ© Klapper wrote:

    Which people from which projects are working on / reviewing this? Are there
    plans to make this a Freedesktop.org specification? What is the process for
    discussing and implementing improvements? Is there a public mailing list?

On 2012-01-03 14:39:07 +0000, gossi wrote:

    Hi Andre,
    
    I released this yesterday and put this into various bugtrackers of several
    doctools I found. Mvriel from docblox raised the first questions here. At
    the moment this is very rudimental and discussions are done, using github's
    issues: https://github.com/gossi/docspec/issues
    
    Regarding the standardizing process, this is the issue for you:
    https://github.com/gossi/docspec/issues/7

On 2012-01-03 15:06:30 +0000, AndrÃ© Klapper wrote:

    Not sure if bugtrackers are really the way to go in an early stage that
    normally rather needs discussions and high architecture reviews.
    "gnome-doc-list at gnome.org" mailing list might be a first potential
    contact.

**Comment by albert-github** [comment]
Since January 2012 there is no progress in the mentioned repository.
I think this is not a doxygen issue.
