### ISSUE TITLE
Class collaboration graphs shows non class members even if "HIDE_UNDOC_RELATIONS" is set to Yes (Origin: bugzilla #667334)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4522]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.7.6.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[class_e_qadc_analog_input__coll__graph.png](https://sourceforge.net/projects/doxygen/files/attachments/bug667334_204663_class_e_qadc_analog_input__coll__graph.png/download/download)_ (ID 204663)

On 2012-01-05 05:53:21 +0000, Anil Choudhury wrote:

    Created attachment 204663
    Class diagram
    
    Hi,
    
    I am interested in generating class diagrams across classes only.
    
    I have set "HIDE_UNDOC_RELATIONS" to true
    
    See the detailed dot settings:
    
    #---------------------------------------------------------------------------
    # Configuration options related to the dot tool
    #---------------------------------------------------------------------------
    CLASS_DIAGRAMS         = YES
    MSCGEN_PATH            = 
    HIDE_UNDOC_RELATIONS   = YES
    HAVE_DOT               = YES
    DOT_NUM_THREADS        = 2
    DOT_FONTNAME           = FreeSans
    DOT_FONTSIZE           = 10
    DOT_FONTPATH           = 
    CLASS_GRAPH            = YES
    COLLABORATION_GRAPH    = YES
    GROUP_GRAPHS           = YES
    UML_LOOK               = YES
    TEMPLATE_RELATIONS     = YES
    INCLUDE_GRAPH          = YES
    INCLUDED_BY_GRAPH      = YES
    CALL_GRAPH             = YES
    CALLER_GRAPH           = YES
    GRAPHICAL_HIERARCHY    = YES
    DIRECTORY_GRAPH        = YES
    DOT_IMAGE_FORMAT       = png
    INTERACTIVE_SVG        = NO
    DOT_PATH               = "D:/Program Files/Graphviz 2.28/bin"
    DOTFILE_DIRS           = 
    MSCFILE_DIRS           = 
    DOT_GRAPH_MAX_NODES    = 50
    MAX_DOT_GRAPH_DEPTH    = 0
    DOT_TRANSPARENT        = NO
    DOT_MULTI_TARGETS      = YES
    GENERATE_LEGEND        = YES
    DOT_CLEANUP            = YES
    
    
    As the documentation of "HIDE_UNDOC_RELATIONS" says:
    If set to YES, the inheritance and collaboration graphs will hide
    inheritance and usage relations if the target is undocumented or is not a
    class.
    
    Then why the collaboration graphs shows structures in the class diagram?

**Comment by albert-github** [comment]
It is hard to imagine what exactly is requested.

I think the most likely cause here is the setting of `UML_LOOK = YES` setting this to `NO` will remove the members.

I think this is usage.
