### ISSUE TITLE
HTML tags <u> and </u> not supported (Origin: bugzilla #667993)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4529]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.6.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[TestDocs.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug667993_205341_TestDocs.zip/download/download)_ (ID 205341)

On 2012-01-16 10:08:13 +0000, Bernd Giesen wrote:

    Created attachment 205341
    Sample project for "HTML tags <u> and </u> not supported"
    
    Unlike the <b></b> and <i></i> the <u></u> tags for underlining comment text
    are not supported in doxygen comment blocks. See the "Detailed class
    description" in the attached sample project (Test.chm)

**Comment by albert-github** [comment]
I've just pushed a proposed patch #6384

**Comment by albert-github** [comment]
Code has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
