### ISSUE TITLE
Default LATeX header misses $-placeholders (Origin: bugzilla #668003)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4530]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.7.6.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2012-01-16 12:35:20 +0000, Stefan wrote:

    Generating the default header for LaTeX doesn't use the $-placeholders
    ($title, $project..., etc.) for the project information.
    
    Steps to reproduce:
    
    1) create a new empty folder and change into it
    2) execute "doxygen -g Doxyfile"
    3) execute "doxygen -w latex header.tex footer.tex doxygen.sty Doxyfile"
    4) examine the header and notice no $-placeholders are contained
    
    Thanks in advance,
    Stefan

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #8309

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.2.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
