### ISSUE TITLE
Fortran ENTRY support (Origin: bugzilla #668605)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4551]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.7.6.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2012-01-24 19:02:40 +0000, mooreb@research.ge.com wrote:

    Fortran supports functions and subroutines that can have multiple entry
    points.  It seems that Doxygen 1.7.6.1 does not appear to currently
    recognize the 'ENTRY' keyword.
    
    See:  http://www.fortran.com/F77_std/rjcnf-15.html#sh-15.7
    
    I attempted to quickly just add 'ENTRY' to src/fortranscanner.l, but as
    'ENTRY' provides an alternative entry into an existing Scope, rather than
    creating a new Scope, that mechanism didn't quite work.

**Comment by albert-github** [comment]
In Fortran 2008 the `ENTRY` statement has been declared obsolescent.
