### ISSUE TITLE
\copyXXX not working for \page elements (Origin: bugzilla #668731)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4554]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.6.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2012-01-26 11:26:21 +0000, Fabrizio Da Ros wrote:

    Hello,
    
    Usually I write documentation of project into separate .doxy file. The basic
    structure is
    /**
    \page   id_201201031218   Notes
    
    this is the brief descritpion.
    
    While this line is part of the detailed text.
    
    \section id_201101161000   To develop / Ideas / Proposal to discuss
    
    ...
    
    \subsection id_201201260940    Date 26/January/2012
    
    ...
    */
    
    Then I use the \subpage command to create a tree to access all pages.
    
    1) \copybrief \copydetails \copydoc are not working as expected (by what
    I've understood, at least!). I would like to have into a different .doxy
    file:
    \subpage id_201201031218. \copybrief id_201201031218
    
    to result into 
    Notes. this is the brief descritpion.
    
    But the 2nd text is not appearing. \copydoc seems to work but stops at the
    first \section.
    
    Thank you,
    Fabrizio.

**Comment by albert-github** [comment]
The problem here is that a page doesn't have a brief description unless the user specifically specifies:
```
\brief this is the brief description.
```

Note this didn't work for the 1.7.6.1 but does work for 1.8.15.

I think the problem was besides usage a problem that has been solved in the mean time
