### ISSUE TITLE
.HHC file lists excluded class, causing broken link. (Origin: bugzilla #670706)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4581]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.6.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2012-02-23 19:52:32 +0000, Eric Bakeman wrote:

    With "SHOW_NAMESPACES=YES" and "GENERATE_HTMLHELP=YES" to generate .CHM
    file, a local class excluded from documentation by EXTRACT_LOCAL_CLASSES=NO
    is correctly excluded from HTML documentation, but is incorrectly listed in
    generated INDEX.HHC file under "Namespace List".  The latter causes a broken
    link where the class is listed in the .CHM Contents (since no page is
    generated for the excluded class).  In general: INDEX.HHC file lists
    excluded program items (classes, functions, etc.) causing broken links in
    .CHM file.

**Comment by albert-github** [comment]
Unfortunately there is no example with the issue.

When having a `.cpp` file like:
```
/// \file

/// the namespace
namespace ns_cpp
{
    /// class in the namespace
    class ns_cpp_Local {
      public:
       /// A local operator
       bool operator()(int n, int m) {
           return n > m;
       }
    };
};
```
we see for the 1.7.6.1. version the behavior is as described. With the version 1.8.20 the "local class" is not shown anymore.

I think the problem has been solved in the meant time.

As a side node when having the similar code in a `.h` file the "local class" is shown independent of the setting of `EXTRACT_LOCAL_CLASSES`.
Looking in the documentation we see:

> EXTRACT_LOCAL_CLASSES 
> If the EXTRACT_LOCAL_CLASSES tag is set to YES, classes (and structs) defined locally in source files will be included in the documentation. If set to NO, only classes defined in header files are included. Does not have any effect for Java sources.

Here there is explicitly written <b>source  files</b> and a `.h` file is not seen as source file but as an include / header file, so this is also correct.
