### ISSUE TITLE
PREDEFINED tag cannot be overridden by directives in the source code (Origin: bugzilla #670809)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4583]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.6* on platform *Other*
Assigned to: Dimitri van Heesch

On 2012-02-25 20:20:29 +0000, Florian wrote:

    If a macro has been defined in PREDEFINED, it cannot be undefined via an
    #undef in the source code any more.
    
    Quickly glancing at the code, I assume this has been introduced with
    revision 783, with the new DefineManager class. Its method isDefined() does
    not do what the static isDefined() function used to do.
    
    See also: Bug 149899

**Comment by albert-github** [comment]
It is a bit hard to find nowadays the revision 783 but it looks like it is between 1.6.3 and 1.7.0

When having the problem
**aa.h**
```
/// \file

int i_1 = TO_OVERRULE;

#undef TO_OVERRULE
int i_2 = TO_OVERRULE;

#define TO_OVERRULE 4243
int i_3 = TO_OVERRULE;
```
and
**Doxyfile**
```
QUIET = YES
MACRO_EXPANSION = YES
PREDEFINED = TO_OVERRULE=42
```

we get with the version 1.6.3:
![image](https://github.com/doxygen/doxygen/assets/5223533/e26e5bbf-6c13-4f69-9b0c-45ebe6fc09a1)

with the version 1.7.6 (and also with 1.70):
![image](https://github.com/doxygen/doxygen/assets/5223533/9efdf331-09f3-40d7-9596-4dd35a073b1e)

so here the `i_2` is replaced although just before it was the `#undef`

with the current 1.9.8 doxygen version we get:
![image](https://github.com/doxygen/doxygen/assets/5223533/597e861f-7fcd-4830-a85d-c06ae485a42b)


So I think the problem has been solved in the mean time.

Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/12918067/example.tar.gz)
