### ISSUE TITLE
C++: Members in the global namespace don't get documented unless file is explicitly marked (Origin: bugzilla #671122)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4596]
status NEW severity *normal* in component *general* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2012-03-01 11:35:44 +0000, alxvasilev@gmail.com wrote:

    Unless the source file has some header directive, (such as \file I believe),
    members of the global namespace, such as free functions don't even appear
    with their names in the documentation. This makes it impossible to document
    code that was not specificly documented with Doxygen in mind. AFAIK a lot of
    people complain about this.

**Comment by albert-github** [comment]
There is no example with the issue showing the problem and the description is a bit vague / general so it not possible say something sensible about the specific problem here.

Setting issue to incomplete.
