### ISSUE TITLE
ref command does not support java generic type (Origin: bugzilla #671654)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4612]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.8.0* on platform *Other*
Assigned to: Dimitri van Heesch

On 2012-03-08 15:24:49 +0000, lorie.pisicchio@gmail.com wrote:

    In project documentation, I try to make a reference to a Generic type with a
    custom label like :
    @ref my.package.MyGenericClass<T> "MyGenericClass".
    
    The result output after compilation is : 
    my.package.MyGenericClass<T> "MyGenericClass"
    
    and my.package.MyGenericClass<T> is not formatted as a link to the Javadoc.
    
    I would expect to see : 
    MyGenericClass
    with MyGenericClass formatted as a link to the Javadoc of
    my.package.MyGenericClass<T> class.

**Comment by albert-github** [comment]
I used the example from bug 516656 (#2835) and placed in the Main.jave:
```
@ref example1::MyContainer<T> "MyGenericClass".
```
with the 1.8.0 versoi\ion we got warnings and the link was not present but shown as just the text.
With the current 1.9.6 version of doxygen there is no warning and the link is present and points to the generic class.

I think the problem has been solved in the mean time.
