### ISSUE TITLE
Markdown syntax not full supported in \subpage argument (Origin: bugzilla #672977)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4640]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.0-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2012-03-28 08:04:23 +0000, opensource@torbjoern-klatt.de wrote:

    With the \subpage command, the Markdown syntax is not fully supported in the
    title argument.
    
    The following code
    
        \subpage pageThisIsMySubpage "This is **bold** and *italic* text"
    
    evaluates to the following HTML code
    
        <a class="el" href="page_this_is_my_subpage.html">This is
    &lt;strong&gt;bold&lt;/strong&gt; and &lt;em&gt;italic&lt;/em&gt; text</a>
    
    
    Sidemark: Would be nice, the general Markdown syntax for links is applicable
    to \subpage as well. E.g. the above Markdown would be
    
        [This is **bold** and *italic* text](@subpage pageThisIsMySubpage)
    
    Unfortunately, this does not work currently.

**Comment by albert-github** [comment]
I think this issue is identical to #6998 as in the markdown processing phase the line:
```
\page pagee This is page **bold** and *italic* text
```
is translated into
```
\page md_aa This is page <strong>bold</strong> and <em>italic</em> text\ilinebr @anchor pagee
```
