### ISSUE TITLE
Crop png formula environnment problem for HTML output (Origin: bugzilla #674005)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4665]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.0-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[DoxyBug.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug674005_211947_DoxyBug.zip/download/download)_ (ID 211947)

On 2012-04-12 18:08:36 +0000, Guillaume Jacquenot wrote:

    Created attachment 211947
    3 files that allow to reproduce the problem
    
    I would like to use a command \f{}{....\f} to insert a specific LaTeX
    environnement as proposed on
    http://www.stack.nl/~dimitri/doxygen/formulas.html
    
    The specific environnement is a tikz picture.
    I know I can include an image with the command \image, however I wanted to
    insert a tikzpicture in my LaTeX reports.
    
    The problem is that doxygen does not succeed in determining the bounding box
    of image and the html output displays a partial part of the image. In the
    pdf output, the image looks fine.
    
    To see the problem, one needs to generate the HTML output and the LaTeX PDF
    output.
    
    I send data so that one can reproduce the problem.
    The problem is not really a doxygen bug, but consists in finding the correct
    bounding box of the latex document generated.
    
    The attached file is a zip containing 3 files
    1) a doxyfile to generate the example
    2) a text file with doxygen command, specially several \f{}{....\f} command
    3) a tex file containing the image I want to display
    
    Best regards
    Guillaume Jacquenot

On 2012-04-30 17:49:08 +0000, Dimitri van Heesch wrote:

    The formulas are put into a .tex file, which is compiled to a .dvi file.
    In the next step an .eps is create per formula (each formula put on a
    separate page)
    
    Looks like 
    
    dvips -E -o page.eps formula.dvi
    
    does not produce the correct bounding box for your TikZ picture.
    
    I have no idea how to work around this.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7251

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.17.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
