### ISSUE TITLE
Parameters omitted at typedef functions (Origin: bugzilla #674332)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4668]
status NEW severity *major* in component *build* for *---*
Reported in version *1.8.0* on platform *Other*
Assigned to: Dimitri van Heesch

On 2012-04-18 13:37:45 +0000, heht wrote:

    I have code like this in a header file:
    /**
    Bla bla bla.
    @returns Something.
    */
    typedef return_type_t (SOME_API * function_name)(
        arg1, /**< Argument 1. */
        arg2, /**< Argument 2. */
        );
    
    The doc comments should result in doxygen specifying the parameters, but
    this is not the case. So one can't see important information which makes
    doxygen obsolete.

**Comment by albert-github** [comment]
I think the problem here is the fact that just `arg1` and `arg2` are used (note the `,` should not be there after the `arg2` either) and not something in the form of `type1 arg1` so doxygen sees `arg1` as type and has no parameter name to attach the description to.

I think the problem is usage.
