### ISSUE TITLE
CREATE_FOLDERS should not create unused folders (Origin: bugzilla #674442)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4672]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.8.0* on platform *Other*
Assigned to: Dimitri van Heesch

On 2012-04-19 22:46:50 +0000, sbkarlsson@gmail.com wrote:

    Creating a lot of unused folders will clutter up the hard-disk, so it would
    be nice if this could be changed so that only the used folders are created,
    especially when doxygen is used on many small projects.
    
    Just as an example, In the folder where I store some of my projects there is
    just over 10000 files and 177000 folders, so there is alot of empty folders.

On 2015-05-17 16:10:35 +0000, albert wrote:

    When looking at the output with CREATE_SUBDIRS I get just over 4100 files
    per output format. So I cannot come to 177000 directories.
    
    Can you share some more information about this problem?

On 2015-05-18 00:16:08 +0000, sbkarlsson@gmail.com wrote:

    With just one source file, a "main.c" that contain:
    
    #include <stdio.h>
    
    int main(int argc, char *argv[])
    {
       printf("Hello World!\n");
    }
    
    Running doygen with all default settings, except CREATE_SUBDIRS, which is
    active
    
    In the html folder (and recursively) there is now a total of 34 files and
    4113 folders.
    
    The reason why I, in my example wrote 10000 files and 177000 folders, is
    because it (as I wrote) contains MULTIPLE projects, each with its own html-
    folder.

On 2015-05-18 16:21:20 +0000, albert wrote:

    When choosing the option CREATE_SUBDIRS is chosen one chooses for the over
    4000 subfolders. The choice for CREATE_SUBDIRS should therefore not be made
    lighthearted. The possibilities that I see for doxygen would be to heck on
    each open call if the directory already exists (quite an overhead in larger
    projects) or at the end  check all directories if they are empty or not and
    in case a directory is empty remove it.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #8595 with chosen solution "at the end  check all directories if they are empty or not and in case a directory is empty remove it"

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.2.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
