### ISSUE TITLE
The files contains "Data" string are getting filtered out (Origin: bugzilla #674447)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4673]
status NEEDINFO severity *major* in component *doxywizard* for *---*
Reported in version *1.7.4* on platform *Other*
Assigned to: Dimitri van Heesch

On 2012-04-20 05:29:12 +0000, Abhay wrote:

    In project, there three classes as XXXDataDecoding, XXXFirmDataManager,
    XXXGaDataManager. There .h and .cpp files are getting filter out and I am
    not able to see the documentation of these file. There no common thing
    between these files are the "Data" word. The classes derived from base
    classes of these files are getting documented.

On 2013-08-11 13:09:31 +0000, albert wrote:

    I tried to reproduce the problem with version 1.7.4 but I have not been able
    to do this, probably I'm missing something.
    
    Please check if the problem still occurs with the current version of doxygen
    
    If you still see this issue with the latest version of doxygen please add a
    self-contained example (source+config file in a zip or tar).

**Comment by albert-github** [comment]
Seen the period of no response and the fact that with the supplied information the problem is not reproducible I think the problem should be closed as 'invalid' i.e. 'not complete or not reproducible'
