### ISSUE TITLE
Group Pages Not Sorted when SORT_GROUP_NAMES=YES (Origin: bugzilla #674749)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4679]
status NEW severity *major* in component *general* for *---*
Reported in version *1.8.0-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[groupdef.diff](https://sourceforge.net/projects/doxygen/files/attachments/bug674749_212727_groupdef.diff/download/download)_ (ID 212727)

On 2012-04-24 18:55:12 +0000, Jake Colman wrote:

    Created attachment 212727
    groupdef.diff
    
    The SORT_GROUP_NAMES=YES only works with the index tree but it does not sort
    the entries on the group page itself.
    
    The attached diff against 1.8.0-SVN fixes the problem.

**Comment by albert-github** [comment]
Looks to me that this patch went into the Release-1.8.0-20120429

I think the problem has been solved in the mean time.
