### ISSUE TITLE
Left navigation pane should allow expand/collapse without resetting to current page (Origin: bugzilla #676512)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4706]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.7.5.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2012-05-21 17:56:45 +0000, brian_donnelly@ltxc.com wrote:

    It would preferable for the left navigation pane to show an item that is
    currently in focus only when you click somewhere in the right pane.
    
    More details: Let's say my Doxygen-generated HTML output includes two high-
    level categories. In the left navigation pane we see: Modules and Classes.
    Now let's say I navigate to a sub-category in the Classes section (using the
    left navigation pane expand/collapse arrows) and open a specific page in the
    Classes section. If I try to use the left navigation pane expand/collapse
    arrows to explore the content in the Modules section, the left navigation
    pane continually resets based on the current page displayed in the right
    pane.
    
    I don't believe these settings can be controlled via the configuration file.

**Comment by albert-github** [comment]
I did some tests with the doxygen internal documentation.
With the 1.7.5.1 version when I'm in the "Class List: and select here "QCString" then the "QCString" appears nicely in the right [ane. When I now scroll upward to module and use here the expand/collapse of  "Modules: the "Modules" nicely expands but the scroll position returns  back to the "QCString".

When doing the same with the current 1.9.4 version the scroll position does not move so we case easily select further.

I think the problem has been solved in the mean time.
