### ISSUE TITLE
HTAGS and interactive SVG link not good (Origin: bugzilla #676880)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4711]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[docbug.7z](https://sourceforge.net/projects/doxygen/files/attachments/bug676880_215080_docbug.7z/download/download)_ (ID 215080)

On 2012-05-26 13:13:25 +0000, sugeng anto wrote:

    1. I use USE_HTAGS option of source browser. But after compilation of
    documentation,
    the link of source code seems like:
    
    /docs/html/.html
    
    Which of course cannot be found by browser. Also the link from
    
    Definition at line 57 of file conf_ebi.h.
    
    Is just open folder browser (kind of ftp browser). The internal source
    browser is far better.
    
    2. The "arrow link" on interactive svg cannot be opened in browser. It needs
    prefix "file:///" so the link can be opened in browser. Also it better to
    write file path relative from doxygen configuration  instead full path to
    make it looks cleaner.

On 2012-05-26 15:48:53 +0000, Dimitri van Heesch wrote:

    Please don't file multiple problems in one bug report.
    That said: item 2 is a known issue and will be fixed.
    
    As for 1: can you please attach a self-contained example (source+config file
    in a tar or zip) that allows me to reproduce the problem?

On 2012-05-26 22:58:27 +0000, sugeng anto wrote:

    Created attachment 215080
    source+config+log+result

On 2012-05-26 22:59:13 +0000, sugeng anto wrote:

    I am sorry about that...
    So here I attach the file. The actual file is too much, but this simple
    source is able to reproduce problems. Also I don't know the meaning of HTAGS
    warning. But it does not issue warning if I run HTAGS from command prompt
    (just HTAGS with no parameter).
    
    The problem is shown at file list, show source code.
    Also definition link to the source

On 2012-05-27 07:55:49 +0000, Dimitri van Heesch wrote:

    Thanks for your example. I tried it, but it worked as expected!
    So I think something is wrong with your global/htags configuration (I don't
    see it running when looking at the output of doxygen).
    
    To help diagnose the problem you can run doxygen from the command line with
    the -d ExtCmd option. Then it will tell how it invoked htags, it should say
    something like:
    
    Executing external command `htags  -g -s -a -n -v -w -t "ASF docs-3.1.3"
    "/tmp/docbug/html"`
    
    When you run this command from command line yourself, do you see the htags
    output? i.e. something like this:
    
    [Sun May 27 09:52:02 CEST 2012] Gtags started.
     Using default configuration.
    [Sun May 27 09:52:02 CEST 2012] Creating 'GTAGS' and 'GRTAGS'.
     [1] extracting tags of fat.c
     [2] extracting tags of fat.h
     [3] extracting tags of fat_unusual.c
     [4] extracting tags of file.c
     [5] extracting tags of file.h
     [6] extracting tags of fs_com.h
     [7] extracting tags of fsaccess.c
     [8] extracting tags of fsaccess.h
     [9] extracting tags of nav_automatic.c
     [10] extracting tags of nav_automatic.h
     ...
    
    At the end of the run inside the html output directory a HTML/FILEMAP file
    should be created and this file is needed by doxygen to make the correct
    links.

On 2012-05-27 13:22:05 +0000, sugeng anto wrote:

    I see something like 'htags -g -s ......'
    
    But I don't see the output of gtags.
    Also I see "error:htags(1) ended normally but failed to load the file map"
    
    Just for you to know, I just copy all globals binary to doxygen binary
    folder since that folder is included in system path. I try to run global
    from command prompt and it created HTML folder. That is how I test the
    installation.
    
    Actually, I don't know what the result should be.

On 2012-05-27 13:44:47 +0000, Dimitri van Heesch wrote:

    Please be more specific. What is the exact command you see, and does it
    produce the HTML/FILEMAP file in the HTML output directory if you run this
    command manually from the command line?
    
    The error comes from htags not having run (properly), so it could very well
    be that it is not properly installed. I find it hard to help you if I don't
    have all data.

On 2012-05-27 14:43:11 +0000, sugeng anto wrote:

    So here is what I have done:
    1. Install the doxygen. It create entry to the PATH. Only installer have
    doxywizard.
    2. extract global binary from http://adoxa.110mb.com/global/index.html as
    directed from GNU GLOBAL website.
    3. Put all files to doxygen folder. This means all the GLOBAL executable can
    be accessed via PATH
    4. I test by issuing gtags. It create GPATH, GRTAGS, and GTAGS.
    5. Another test by issuing htags. It create folder HTML.
    6. I delete the three files and HTML folder.
    
    By now I assume the HTAGS is installed properly since it can run from
    commandline.
    
    After I run doxygen from command line, the issued command to htags is :
    -----------------------------------------------------------------------
    Executing external command 'htags -g -s -a -n -v -w -t "ASF Docs 3.1.3"
    "G:/asf_repo/doctest/html"
    error: htags(1) ended normally but failed to load the filemap.
    -----------------------------------------------------------------------
    For complete result is just like in the log.

On 2012-05-27 14:49:11 +0000, Dimitri van Heesch wrote:

    Ok, and now run 
    
    htags -g -s -a -n -v -w -t "ASF Docs 3.1.3" "G:/asf_repo/doctest/html"
    
    from the command line in the same dir you have run doxygen, and tell me what
    that does.
    
    It should create a file G:/asf_repo/doctest/html/HTML/FILEMAP, which doxygen
    needs (but cannot find it seems).

On 2012-05-27 14:55:14 +0000, sugeng anto wrote:

    In case of something i'm missing, please include detailed explanation at the
    doxygen help.

On 2012-05-27 15:24:26 +0000, sugeng anto wrote:

    'C:\Program' is not recognized as an internal or external command, operable
    program or batch file.
    htags: cannot execute gtags(1) command.
    
    So it because it run from C:\Program Files\doxygen\bin
    which has space.
    
    After I move the executable to another path G:\MingW\bin. It works like it
    should (as you mentioned before) until encounter error
    --------------
    cp: cannot stat 'G:\\MingW\\bin\\..\\share/gtags/style.css.tmpl':No such
    file
    or directory
    Done.
    --------------
    So it create the FILEMAP. 
    
    I delete the output folder and re-run doxygen again via doxywizard.
    It not work and issued error that it can find the directory
    ../config/usb_conf.h
    
    So I change the input to the directory ../config
    And it works. But the output result is much better if using internal source
    browser (syntax color, strip code comments)
    
    It is good to mention this at the doxygen docs.
    You did a good job, thanks

**Comment by albert-github** [comment]
I think the problem with not being able to load the FILEMAP file is due to the fact that the programs has a problem during the loading phase analogue to the problem reported in Bug 781306 - *** Error in `doxygen': realloc(): invalid pointer: 0x0000000001d45ba0 @ exit (issue #6193) for which  I've just pushed a proposed patch, pull request #6984.

Seen the remark about the point 2) of the original question and now the fix for the crash (point 1) I think the problem can be closed as Solved in the mean time (point 2) and duplicate  (point 1).
