### ISSUE TITLE
HIDE_SCOPE_NAMES also hides template declarations of template member functions in detail description (Origin: bugzilla #676971)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4718]
status NEW severity *normal* in component *documentation* for *---*
Reported in version *1.8.1-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2012-05-28 15:22:19 +0000, Philipp Moeller wrote:

    Using HIDE_SCOPE_NAMES will not only hide the scope in a detail description
    of a member function but also the template parameters itself.
    
    e.g.
    
    /// A foo class.
    class foo {
      /// A foo template member function.
      template<typename InputIterator>
      void fun(InputIterator begin, InputIterator end);
    };
    
    The detail description of fun with HIDE_SCOPE_NAMES = yes will be
    
    void fun(InputIterator begin, InputIterator end);
    
    without
    
    template<typename InputIterator>
    foo::fun(InputIterator begin, InputIterator end)
    
    The second case gets rather ugly for template members of class templates.
    It would be better if the template<...> weren't omitted in if
    HIDE_SCOPE_NAMES = yes is set and maybe another option to hide those were
    provided.

**Comment by simevo** [comment]
reproducible with this minimal sample: [test.zip](https://github.com/doxygen/doxygen/files/9125828/test.zip)

results in:
![image](https://user-images.githubusercontent.com/8254819/179356527-4904088c-c57c-4ea8-abdd-2610db5e41fd.png)

whereas if you unset `HIDE_SCOPE_NAMES`:
![image](https://user-images.githubusercontent.com/8254819/179356559-d744146e-2a82-4722-b01d-88e04f1140a8.png)

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #9452

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.7.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
