### ISSUE TITLE
single quote in HTML section of PHP breaks doxygen (Origin: bugzilla #677092)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4725]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.6.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2012-05-30 12:43:00 +0000, Andrew Pimlott wrote:

    If I run doxygen with the default configuration on this PHP file:
    
        <?php
        class A {
          public function a() {
        ?>
        foo'bar
        <?php
          }
        }
        ?>
    
    ... it creates no output at all for the class.  If I remove the single
    quote, the class is processed as expected.

On 2013-01-16 00:39:42 +0000, Gaetano Giunta wrote:

    Dupe of bug # 15160 ?

On 2013-01-16 00:40:43 +0000, Gaetano Giunta wrote:

    (In reply to comment # 1)
    > Dupe of bug # 15160 ?
    
    woops, I meant Bug 156160

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6536

**Comment by albert-github** [comment]
Code has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
