### ISSUE TITLE
Class list is empty when a class is in an undocumented namespace (Origin: bugzilla #677364)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4730]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2012-06-03 00:09:37 +0000, Thomas D wrote:

    Here is the testcase:
    
    /// Namespace documentation
    namespace Empty {
    
    /// Brief description of class Test
    class Test {
    public:
        //! Constructor
        Test() {}
        //! Destructor
        ~Test() {}
    };
    
    }
    
    This generates correct documentation. But, if you remove the first line:
    /// Namespace documentation
    
    then the class list is empty.
    
    This is a new behavior in 1.8.1. With 1.7.5.1, class list is generated with
    and without the namespace documentation line (same Doxyfile)

**Comment by albert-github** [comment]
In the 1.7.5.1 version the class is shown irrespective whether or not the namespace is documented or not.
In the 1.8.1 version the class in the not documented namespace is not shown
With the current doxygen version (1.9.6) the class is shown again in the not documented namespace
( all using a default Doxyfile)

I think the problem has been solved in the mean time
