### ISSUE TITLE
Xcode docsets - namespace list shows up as subpage of the last page in "explore documentation" tab (Origin: bugzilla #678026)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4744]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.1.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[foo.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug678026_216400_foo.zip/download/download)_ (ID 216400)

On 2012-06-13 15:00:56 +0000, kaiserludi@gmx.de wrote:

    but only, if there has not been specified any other subpage for this last
    page

On 2012-06-13 15:32:30 +0000, kaiserludi@gmx.de wrote:

    It looks, like this has got broken relatively recently:
    It works correctly with doxygen 1.7.2, but not with 1.8.1.1 anymore.
    I have not tested the versions in between.

On 2012-06-13 21:38:14 +0000, Dimitri van Heesch wrote:

    Can you please attach a self-contained example (source+config file in a tar
    or zip) that allows me to reproduce the problem?

On 2012-06-14 10:32:28 +0000, kaiserludi@gmx.de wrote:

    Created attachment 216400
    minimal reproduction case
    
    Here comes the requested reproduction case.

**Comment by albert-github** [comment]
With version 1.8.1.1 I see (in the Nodes.xml):
```
       <Node>
        <Name>Page2</Name>
        <Path>_page2.html</Path>
        <Subnodes>
         <Node>
          <Name>Namespace List</Name>
          <Path>namespaces.html</Path>
          <Subnodes>
           <Node>
            <Name>Foo</Name>
            <Path>namespace_foo.html</Path>
```
and in 1.9.1:
```
         <Node>
          <Name>Page2</Name>
          <Path>_page2.html</Path>
         </Node>
        </Subnodes>
       </Node>
       <Node>
        <Name>Namespaces</Name>
        <Path>namespaces.html</Path>
        <Subnodes>
         <Node>
          <Name>Namespace List</Name>
          <Path>namespaces.html</Path>
          <Subnodes>
           <Node>
            <Name>Foo</Name>
            <Path>namespace_foo.html</Path>
```

So we see that now the namespace is not a subnode of page2 anymore.

I think the problem has been solved in the mean time.
