### ISSUE TITLE
C++ private members can be listed as reimplemented in derived classes (Origin: bugzilla #678082)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4747]
status NEW severity *minor* in component *build* for *---*
Reported in version *1.8.1.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2012-06-14 09:28:22 +0000, phillip.cavanagh@selexgalileo.com wrote:

    Overview
    Given a class with a private member and a subclass with a member of the same
    name, the base class's member has a "Reimplemented in" line, and the derived
    class has a "Reimplemented from" line. These two members are not related, as
    the derived class knows nothing of the base class's private members.
    
    
    Steps to reproduce
    Run Doxygen on the following (documenting private members):
    
    class Base {
     private:
      /** Base class member */
      int myInt;
    };
    
    class Derived : public Base {
     private:
      /** Derived class member */
      int myInt;
    };
    
    
    This may also occur in other languages, but I have not checked this.

**Comment by albert-github** [comment]
With the version 1.8.1.1 I see the message that the private member is reimplemented, with the version 1.8.1.2 this message is gone.

I think the problem has been solved in the mean time.
