### ISSUE TITLE
Let Doxygen show the changes in documentations as âred linesâ (Origin: bugzilla #678101)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4750]
status NEW severity *enhancement* in component *documentation* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2012-06-14 14:11:33 +0000, peyman p wrote:

    Issue:
    
    Change management is an important process in software engineering. After the
    first revision of new software is developed, most of the developerâs time
    is spent on changing the existing software and reviewing the changes.
    
    For source code, reviewing the changes are easy. One can use power full
    comparison tools like "Beyond Compare". But to review the changes in
    documentation, if it is created using Doxygen, reviewing the changes using
    "Beyond Compare" or similar tools is not very easy. "Beyond Compare" can
    compare the HTML source or the source codes that contain the comments from
    which the Doxygen creates the documents. Both HTML source and the comments
    in source code are difficult to read. This makes the task of reviewing the
    changes in documentation very difficult and time consuming.
    
    Improvement:
    
    It would be great if Doxygen can read the old and new source codes (that are
    located in two different directories) and create a documentation output that
    contains the new documentation but with changes appear as âred linesâ
    (Like MS Word that can track changes). Or Doxygen can highlight the changes
    using another method that is more appropriate.
    
    For changes in text this is not too difficult. For graphical changes, this
    can be a little bit difficult (May be only the new picture should be
    displayed and some how with a click of button the old picture appears as
    well)

On 2013-02-05 11:59:34 +0000, Simon A Watts wrote:

    I think that to support this directly through Doxygen would be a hard
    problem.  However, there may be an alternative (I haven't tried this)...
    
    If you produce RTF output, can you use MS Word to compare the two files (old
    and new revisions)?
    
    We use this method to review changes in Word documents (it works better than
    Word's attempt at document versioning!) - but I don't know whether RTF
    produced by Doxygen would be consistent enough to allow this.

**Comment by albert-github** [comment]
Comparing versions of an output document is not an easy task (as already noted before) and is outside the scope of doxygen.
One always has  to define what to compare:
- which output format
- comparing 2 documents generated with the same (doxygen version) software but a (small) difference in the input
- comparing 2 versions of the input with the same (doxygen version) software

When doing a search over the internet for e.g. "compare html documents" a number of hits will be given (e.g. https://www.w3.org/wiki/HtmlDiff for a small overview) and the user can choose the product best suited.
Analogous searches can be made for e.g. pdf documents.

As said I think this is not a doxygen problem.
