### ISSUE TITLE
Markdown auto-numbering broken (Origin: bugzilla #678240)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4757]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[DoxyBugs_1.8.0.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug678240_216642_DoxyBugs_1.8.0.zip/download/download)_ (ID 216642)
- _[DoxyBugs_1.8.1.1.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug678240_216643_DoxyBugs_1.8.1.1.zip/download/download)_ (ID 216643)

On 2012-06-17 08:01:00 +0000, nullable.type@gmail.com wrote:

    Input (Markdown):
    1. one
    1. two
    1. three
    
    Expected Output:
    1. one
    2. two
    3. three
    
    Actual Output:
    1. one
    1. two
    1. three
    
    This applies also to version 1.8.1.1 and to the linux versions.

On 2012-06-18 06:53:41 +0000, nullable.type@gmail.com wrote:

    Created attachment 216642
    Test project to demonstrate the good case.

On 2012-06-18 06:54:19 +0000, nullable.type@gmail.com wrote:

    Created attachment 216643
    Test project to demonstrate the bad case (with doxygen 1.8.1.1)

On 2012-06-24 11:39:41 +0000, Dimitri van Heesch wrote:

    This is a deliberate deviation from the Markdown standard. I will document
    it.
    Below is the proposed documentation. Let me know if that helps.
    
    
    ---------------------------
    
    With Markdown the actual numbers you use to mark the list have no effect on
    the HTML output Markdown produces. I.e. it treats the following as a list
    with 3 numbered items:
    
    1. Item1
    1. Item2
    1. Item3
    
    Doxygen however requires that the numbers used as marks are in strictly
    ascending order; an item with an equal or lower number than the preceding
    item, will start a new list. For example:
    
    1. Item1 of list 1
    3. Item2 of list 1
    2. Item1 of list 2
    4. Item2 of list 2
    
    will produce:
    
        1. Item1 of list 1
        2. Item2 of list 1
    
        1. Item1 of list 2
        2. Item2 of list 2

On 2012-06-25 06:44:50 +0000, nullable.type@gmail.com wrote:

    Lets see if a got it right...
    
    If i want to have a numbered list in a markdown file (processed by doxygen),
    i have to use numbers which are strict ascending (otherwise it starts a new
    list).
    
    The following description is not clear for me:
    >> With Markdown the actual numbers you use to mark the list have no effect
    on the
    >> HTML output Markdown produces. I.e. it treats the following as a list
    with 3
    >> numbered items:
    
    In particular "... have no effect ..." vs. ".. . treats the following as a
    list with 3 numbered items:". For me, if it treats that piece of code as a
    list with 3 items, it has an effect on the html output.
    
    Did i mess up the things now?

**Comment by NyanKiyoshi** [comment]
Still there.

**Comment by albert-github** [comment]
In the comment of June 24, 2016, Dimitri van Heesch wrote:

> This is a deliberate deviation from the Markdown standard. I will document it.
> Below is the proposed documentation. Let me know if that helps.

In this description is (at least one) small mistake the `3.` should be `2.`
In the documentation Paragraph "Lists Extensions" of the chapter about markdown support ( see e.g. http://www.doxygen.org/manual/markdown.html#mddox_lists) gives the exception.

@NyanKiyoshi 
Does this answer your problem? When not please be a bit more specific about the problem you have and can you please attach a, small, self contained example (source+config file in a tar or zip) that allows us to reproduce the problem?
Please also specify the doxygen version used (doxygen -v), "Still there" is a bit vague.

**Comment by albert-github** [comment]
@NyanKiyoshi 

In the mentioned paragraph of the documentation it is stated:

> With Markdown the actual numbers you use to mark the list have no effect on the HTML output Markdown produces. I.e. standard Markdown treats the following as one list with 3 numbered items:
> 
> 1\. Item1
> 1\. Item2
> 1\. Item3
> 
> Doxygen however requires that the numbers used as marks are in strictly ascending order, so the above example would produce 3 lists with one item.

**Comment by NyanKiyoshi** [comment]
Yes, it is.
>but the docs says it's normal behavior

But, then I said:
> I'm not sure why this design was chosen, there is no such information on the documentation.
 
I was referencing to this:
> On 2012-06-24 11:39:41 +0000, Dimitri van Heesch wrote:
>     This is a deliberate deviation from the Markdown standard. I will document it.
>     Below is the proposed documentation. Let me know if that helps.

There is no argumentation on why this design was chosen, why is it a deliberate deviation? That's my wonder, I don't need an answer to my question though! I guess this issue can be closed.

**Comment by albert-github** [comment]
Seen the fact that the documentation has been updated I think the problem has been solved in the mean time.
