### ISSUE TITLE
Unexpected conversion of -- (minus, minus) in inline block of markdown input (Origin: bugzilla #678288)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4759]
status RESOLVED severity *normal* in component *general* for *---*
Reported in version *1.8.1.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[DoxyBugs_1.8.0.zip](http://ftp.stack.nl/pub/users/dimitri/bugzilla/attachments//bug678288_216646_DoxyBugs_1.8.0.zip)_ (ID 216646)
- _[DoxyBugs_1.8.1.1.zip](http://ftp.stack.nl/pub/users/dimitri/bugzilla/attachments//bug678288_216647_DoxyBugs_1.8.1.1.zip)_ (ID 216647)

On 2012-06-18 07:46:19 +0000, nullable.type@gmail.com wrote:

> The -- in a markdown inline block gets converted to &ndash; which is not as expected.

On 2012-06-18 07:46:46 +0000, nullable.type@gmail.com wrote:

> Created attachment 216646
> Demonstration project for the good case

On 2012-06-18 07:47:16 +0000, nullable.type@gmail.com wrote:

> Created attachment 216647
> Demonstration project for the bad case

On 2012-06-18 19:27:55 +0000, Dimitri van Heesch wrote:

> Confirmed. Should be fixed in the next subversion update.

On 2012-07-12 15:42:02 +0000, Dimitri van Heesch wrote:

> This bug was previously marked ASSIGNED, which means it should be fixed in
> doxygen version 1.8.1.2. Please verify if this is indeed the case. Reopen the
> bug if you think it is not fixed and please include any additional information
> that you think can be relevant.

**Comment by mjm2017** [comment]
This bug is coming up again. 
The char used for minus minus is not an Ascii code. 
Look at this code generated by doxygen 
  for(i=360,i>=0,i−−) {
that should be -- .. If you look at the shape, and size .. its obvious that is not --

I have the latest doxygen.
