### ISSUE TITLE
Virtual override not marked virtual (Origin: bugzilla #678442)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4763]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.1.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[DoxyBugs.7z](https://sourceforge.net/projects/doxygen/files/attachments/bug678442_216781_DoxyBugs.7z/download/download)_ (ID 216781)

On 2012-06-20 06:16:01 +0000, john.x.foster@nab.com.au wrote:

    Created attachment 216781
    7z archive of files and output
    
    The override of a base class virtual method in a derived class is also
    virtual, whether marked virtual or not. The documentation is not showing
    this.
    
    		/// Base class
    	class Base
    	{
    	public:
    
    			/// A method does something
    		virtual void method();
    
    	};
    
    		/// Derived class
    	class Derived: public Base
    	{
    	public:
    
    		void method();
    
    	};
    
    Derived::method should be flagged as virtual.

**Comment by albert-github** [comment]
For the 1.8.1.1 version (but also for the current 1.8.20 version) we see as detailed description for the base method:
![base](https://user-images.githubusercontent.com/5223533/94582340-6a722d80-027c-11eb-9a25-10ec5ce82f0b.jpg)

and for the derived method:
![derived](https://user-images.githubusercontent.com/5223533/94582319-66461000-027c-11eb-8a63-3bc5faa94d81.jpg)

We see that both have the label "virtual" at the right had side. The base version also has in the signature the word virtual.

With the brief descriptions we see for the base version:
![base_brief](https://user-images.githubusercontent.com/5223533/94582483-92fa2780-027c-11eb-8d20-81f81e11c78f.jpg)

and for the derived version:
![derived_brief](https://user-images.githubusercontent.com/5223533/94582509-99889f00-027c-11eb-899a-57088fd1577e.jpg)

here we see no indication of being "virtual" of the derived method.

The question is is it sufficient that the detailed description is marked with the "virtual" label or should also the signature be extended with "virtual" in case of the derived method?

@doxygen what to do?

**Comment by doxygen** [comment]
@albert-github In my opinion doxygen should not show something else than what is written in the code. Only if the developer wanted to mark the derived function explicitly as virtual he/she should add the virtual keyword and doxygen should also show it. That the function is effectively virtual (and inline) is shown with the "virtual" label, so I would say this is intended behavior.
