### ISSUE TITLE
installing on x64 edition doesn't remove old release (Origin: bugzilla #678492)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4767]
status NEW severity *major* in component *general* for *---*
Reported in version *1.8.1.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2012-06-20 19:08:10 +0000, Stefan wrote:

    I upgraded from v1.7.6.1 to v1.8.1.1 and the previous installation was not
    removed.
    
    I think this is due to the change from being only a 32-bit application to
    support 32-bit and 64-bit natively.
    
    Sure it is relatively easy to remove the previous version myself, but
    usually an upgrade just does that for me ;-)
    
    Thanks in advance,
    Stefan

**Comment by albert-github** [comment]
It would have been nice when this was done but since quite a while now the 32-bit Windows version is not distributed (though doxygen can still be compiled as 32-bit executable), so there is no real need for this anymore.

Setting to won't fix
