### ISSUE TITLE
when removing doxygen the path variable is not updated to remove the doxygen path (Origin: bugzilla #678494)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4768]
status NEW severity *major* in component *general* for *---*
Reported in version *1.8.1.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2012-06-20 19:13:31 +0000, Stefan wrote:

    The path to the bin folder of doxygen is included in the PATH environment
    variable, but when doxygen is removed from the system by uninstalling it,
    the path variable still contains the path added by the doxygen installer.
    
    Would you mind removing the path from the PATH variable?
    
    Thanks in advance,
    Stefan

**Comment by albert-github** [comment]
It is unclear which OS this concerns.

So I think the issue is incomplete
