### ISSUE TITLE
Namespaces appear in class documentation (Origin: bugzilla #679135)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4779]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.8.1.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[annotated.html](https://sourceforge.net/projects/doxygen/files/attachments/bug679135_217609_annotated.html/download/download)_ (ID 217609)

On 2012-06-29 12:39:47 +0000, Simon Platt wrote:

    Created attachment 217609
    HTML class list containing extraneous documentation for namespaces without
    classes..
    
    For example, this file:
    
    /** @file
    This is a source file for testing doxygen.
    */
    
    /// An anonymous namespace with no classes in it.
    namespace {
    	int foo;	///< A silly name.
    	double bar;	///< Another silly name.
    }
    
    /// A named namespace with no classes in it.
    namespace  foo {
    	char hello[] = "Hello";			///< A friendly greeting
    	char *greeting(){return hello;}	///< To greet friendlily
    }
    
    results in both namespaces being listed in the class list ("Here are the
    classes, structs, unions and interfaces with brief descriptions:"), as shown
    by annotated.html, attached.
    
    Factory default configuration used.
    
    I can reproduce this whenever there is a class defined *somewhere else*.

**Comment by albert-github** [comment]
With version 1.8.1.1 I can reproduce the described behavior (after defining a file with a class).
In version 1.8.15 this behavior is gone and it looks all correct to me.

I think the problem has been solved in the mean time.
