### ISSUE TITLE
Missing images from generated qhp file (Origin: bugzilla #679192)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4780]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.1.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxygen_bug.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug679192_217722_doxygen_bug.zip/download/download)_ (ID 217722)
- _[doxygen_bug.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug679192_217771_doxygen_bug.zip/download/download)_ (ID 217771)

On 2012-06-30 13:17:31 +0000, spiceycannedham@gmail.com wrote:

    Created attachment 217722
    Test project
    
    Logo image is missing from generated qhp file.
    Nested group relation graphs are missing from qhp file.
    
    Attached package to reproduce the error.

On 2012-07-01 14:15:01 +0000, spiceycannedham@gmail.com wrote:

    Created attachment 217771
    Test project
    
    Re-upped. Forgot to remove password from zip.

**Comment by albert-github** [comment]
With the 1.8.1.1 (and also the current 1.9.2) version we see that when we move the qch  (generated from qhp file with qhelpgenerator.exe that the logo and the doxygen image are not shown:

![image](https://user-images.githubusercontent.com/5223533/131996803-1b77d8a7-7928-4046-9602-371e6daa525c.png)

I've just pushed a proposed patch, pull request #8758

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.3.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
