### ISSUE TITLE
boost::assign::map_list_of functionality produces an horizontal scroll bar (Origin: bugzilla #679270)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4781]
status NEW severity *minor* in component *general* for *---*
Reported in version *1.8.1.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[test.7z](https://sourceforge.net/projects/doxygen/files/attachments/bug679270_217860_test.7z/download/download)_ (ID 217860)

On 2012-07-02 17:43:50 +0000, Mihai Todor wrote:

    Created attachment 217860
    Demo of the issue.
    
    This issue is caused by excessive space introduced in the code for
    formatting purposes. If the items in the list are pushed too much to the
    right, Firefox 13.0.1 will display a horizontal scroll bar and oversize the
    "Initial value" box, even though it shouldn't.
    
    I have attached a demonstration of this behavior in the latest version,
    1.8.1.1. Actually, it looked worse on 1.8.0, because it kept the formatting
    from the code.

On 2012-07-19 12:30:46 +0000, Dimitri van Heesch wrote:

    Seems like a Firefox specific render bug, both Chrome and Safari show the
    box properly.
    
    Maybe there is a trick to get Firefox behave correctly, but I don't know it.

**Comment by albert-github** [comment]
I don't have Firefox 13.0.1 available, but it look to me that the problem in the current version of Firefox isn't present anymore.

I think that the problem has been solved in the mean time by Firefox.
