### ISSUE TITLE
Markdown break tags ignored (Origin: bugzilla #679710)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4792]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.5* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[line-breaks.diff](https://sourceforge.net/projects/doxygen/files/attachments/bug679710_267062_line-breaks.diff/download/download)_ (ID 267062)

On 2012-07-10 21:40:03 +0000, Craig wrote:

    I have a "readme.txt" file with the following text:
    
    Project Name (#mainpage)
    ========
    
    Website: <blah>  
    Author: name  
    Version: 1.0  
    etc...
    
    There are two spaces at the end of each non-header line above which should
    force a <br /> in the generated html. Instead, I get all the text run
    together on a single line.

On 2013-10-02 21:26:32 +0000, Andrew Simmons wrote:

    I have the same problem on Linux (doxygen 1.8.4) and OSX (doxygen 1.8.5).

On 2013-10-03 02:00:30 +0000, Kevin McBride wrote:

    Setting to new as suggested on Comment # 1

On 2014-01-23 16:39:55 +0000, Alex Merry wrote:

    Created attachment 267062
    Add support for line breaks
    
    This adds support for line breaks in paragraphs.

On 2014-04-19 12:35:15 +0000, albert wrote:

    Pull request 142 has been send to github by Alex Merry

**Comment by albert-github** [comment]
The mentioned pull request has been integrated in version 1.8.14

I think the problem has been solved in the mean time
