### ISSUE TITLE
warning: unexpected command endcode (Origin: bugzilla #679889)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4797]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.1.2* on platform *Other*
Assigned to: Dimitri van Heesch

On 2012-07-13 19:50:02 +0000, Charles Karney wrote:

    The input file, foo.hpp,
    
    namespace foo {
      /**
       * \code
    double lat = -1, lon = 123;
       \endcode
       **********************************************************************/
      void Forward();
    }
    
    gives
    
      foo.hpp:7: warning: unexpected command endcode
    
    and generates garbled output.
    
    Workarounds:
    
      * Use version 1.8.0 which does not have this problem.
      * Inserting two spaces before "double" makes the error go away.  
    
    I reported a similar problem with 1.8.1.1 (Bug 678231) but this is a
    simpler example.

On 2012-07-25 05:44:19 +0000, Dirk O. Schweier wrote:

    Hi Charles,
    
    I guess I had the same problem with doxygen 1.8.1.2. I found Bug 678068 and
    there Dimitri asked user to set MARKDOWN_SUPPORT to NO.
    
    In my configuration file it was set to YES and after switching to NO
    everything worked like I expected. So this migth be a solution for you as
    well.
    
    Regards
    Dirk

On 2012-07-25 11:56:59 +0000, Charles Karney wrote:

    Indeed MARKDOWN_SUPPORT = NO makes the problem go away.  Thanks!
    
    I'd be interested to understand how the markdown process changed
    the input to trigger this error...
    
     --Charles

On 2012-07-25 12:25:49 +0000, Dimitri van Heesch wrote:

    This has to do with the indentation.
    
    In your case the line with \code is indented >=4 characters with respect to
    the rest of the comment block (in particular the line starting with
    'double'), so it is treated as a verbatim section by Markdown rules. The
    \endcode is less than 4 characters indented so it is left alone.
    
    Here is an improved version (note that doxygen will strip the leading indent
    and '*' from your code block), which also looks better IMHO:
    
    namespace foo {
      /**
       * \code
       * double lat = -1, lon = 123;
       * \endcode
       **********************************************************************/
      void Forward();
    }
    
    You can debug Markdown issues using the -d Markdown option, then doxygen
    will show what the result after Markdown processing becomes.

On 2012-07-25 13:16:33 +0000, Charles Karney wrote:

    Thanks for the explanation.  Now I have a mental model of the process
    I can handle the changed behavior easily.  Note however that for verbatim
    blocks I would need, e.g.,
    
    namespace foo {
      /**
       * \verbatim
       double lat = -1, lon = 123;
       \endverbatim
       **********************************************************************/
      void Forward();
    }
    
    to avoid getting '*'s its the verbatim block.

On 2012-07-25 13:22:28 +0000, Dimitri van Heesch wrote:

    Yes, but then it makes sense to actually make use of Markdown (so you can
    keep the '*'s), i.e. use
    
    /// a namespace
    namespace foo {
     /**
      * Some introduction text.
      *
      *     double lat = -1, lon = 123;
      **********************************************************/
     void Forward();
    }

On 2012-07-25 13:36:30 +0000, Charles Karney wrote:

    OK.  Thanks for the tip!

**Comment by albert-github** [comment]
In 1.8.1.2 the original problem is present, but in version 1.8.15 it is gone.

I think the problem has been solved in the mean time.
