### ISSUE TITLE
macro function is not detected (Origin: bugzilla #679902)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4798]
status NEW severity *major* in component *general* for *---*
Reported in version *1.8.1.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxygen bug 1.7z](https://sourceforge.net/projects/doxygen/files/attachments/bug679902_218775_doxygen bug 1.7z/download/download)_ (ID 218775)

On 2012-07-14 00:01:39 +0000, sugeng anto wrote:

    SeparatedmMacro function is not recognized and concatenated with the next
    line function. Maybe it is because the macro does not end by semicolon or
    curly bracket.
    
    The code:
    
    META_NodeVisitor("osgUtil","Simplifier")
    
    void setSampleRatio(float sampleRatio) { _sampleRatio = sampleRatio; }
    
    The result from doxygen:
    
    META_NodeVisitor("osgUtil","Simplifier") void setSampleRatio(float
    sampleRatio) { _sampleRatio = sampleRatio; }

On 2012-07-14 00:03:16 +0000, sugeng anto wrote:

    Created attachment 218775
    sample file and generated html

On 2018-05-12 09:15:52 +0000, albert wrote:

    Problem here is that we have a type of define:
      META_NodeVisitor("osgUtil","Simplifier")
    that doxygen cannot distinguish as a define and also not as a function
    prototype as it has no ';' at the end or has an implementation.
    
    Similar problems are noted for Qt, in the manual there are some tips in this
    respect.
    
    Some possibilities:
    - place a ; at the end of the line, doxygen will see it as a function
    prototype (probably not the best solution)
    - make a define in the doxygen configuration file where the META_NodeVisitor
    is replaced by nothing
    - use the real expansion for the META_NodeVisitor
    
    I don't think this is a bug.

**Comment by albert-github** [comment]
As indicated in the comment from 2018-05-12 09:15:52I still think this is not a bug but usage.
(there is no information where to get the information about / definition of `META_NodeVisitor`, from a bit older documentation on github.io, http://podsvirov.github.io/osg/reference/openscenegraph/a01205.html#afc198548b993ad0954b9c5483712de73, we learn that there are multiple defines, one is
```
#define META_NodeVisitor (library, name) = \
virtual const char* libraryName() const { return #library; }\
        virtual const char* className() const { return #name; }
```
