### ISSUE TITLE
Doxygen 1.8.1.2 docset Missing Index Entries (Origin: bugzilla #680440)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4819]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.1.2* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[Doxygen 1.8.1.2 docset Index.pdf](https://sourceforge.net/projects/doxygen/files/attachments/bug680440_219479_Doxygen 1.8.1.2 docset Index.pdf/download/download)_ (ID 219479)
- _[embed1.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug680440_219901_embed1.zip/download/download)_ (ID 219901)

On 2012-07-23 12:08:54 +0000, Rei Vilo wrote:

    Created attachment 219479
    Doxygen 1.8.1.2 docset Missing Index Entries
    
    In the docset, many entries are missing from the index compared with the
    PDF, as class index and file index.
    
    
    PDF, HTML and .docset are available at
    http://embeddedcomputing.weebly.com/download.html

On 2012-07-30 14:12:32 +0000, Dimitri van Heesch wrote:

    Can you attach a minimal example (source + config file in a tar or zip) that
    allows me to reproduce the problem? (only output files doesn't help).

On 2012-07-30 15:15:39 +0000, Rei Vilo wrote:

    Please find a minimal example.
    
    Feel free to remove line 49 of file LocalLibrary.h to see what happens!
    
    /// @todo	Add default values

On 2012-07-30 15:16:27 +0000, Rei Vilo wrote:

    Created attachment 219901
    Minimal example with index issue

On 2012-08-06 18:52:01 +0000, Dimitri van Heesch wrote:

    (In reply to comment # 2)
    > Please find a minimal example.
    > 
    > Feel free to remove line 49 of file LocalLibrary.h to see what happens!
    > 
    > /// @todo    Add default values
    
    It is better to tell me what happened for you, so I can check that here.
    I only see the todo list being removed (which is what I would expect if
    there are no more todo items).

On 2012-08-07 03:39:07 +0000, Rei Vilo wrote:

    Without the @todo line, I have the right index
    
    . embed1
    . . File List
    . . . embed1.pde
    . . . LocalLibrary.h
    . . File Members
    . . . All
    . . . Functions
    . . . Variables
    
    
    When there is a @todo line, the Todo entry appears on the index but includes
    all other entries under it:
    
    . embed1
    . Todo list 
    . . File List
    . . . embed1.pde
    . . . LocalLibrary.h
    . . File Members
    . . . All
    . . . Functions
    . . . Variables
    
    when I expected 
    
    . embed1
    . Todo list 
    
    . . File List
    . . . embed1.pde
    . . . LocalLibrary.h
    . . File Members
    . . . All
    . . . Functions
    . . . Variables

On 2012-09-12 21:02:44 +0000, Rei Vilo wrote:

    Info provided.

**Comment by albert-github** [comment]
With version 1.8.1.2 I see in the Nodes.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<DocSetNodes version="1.0">
  <TOC>
    <Node>
      <Name>Root</Name>
      <Path>index.html</Path>
      <Subnodes>
       <Node>
        <Name>embed1</Name>
        <Path>index.html</Path>
       </Node>
       <Node>
        <Name>Todo List</Name>
        <Path>a00004.html</Path>
        <Subnodes>
         <Node>
          <Name>File List</Name>
          <Path>files.html</Path>
```
in version 1.9.1 I see:
```
<?xml version="1.0" encoding="UTF-8"?>
<DocSetNodes version="1.0">
  <TOC>
    <Node>
      <Name>Root</Name>
      <Path>index.html</Path>
      <Subnodes>
       <Node>
        <Name>Todo List</Name>
        <Path>a00011.html</Path>
       </Node>
       <Node>
        <Name>Files</Name>
        <Path>files.html</Path>
        <Subnodes>
         <Node>
          <Name>File List</Name>
          <Path>files.html</Path>
```
Looking at the nesting we see that in version 1.8.1.2 the nesting isn't correct, with version 1.9.1 this looks correct ("Files" is not a node as subnode of the ToDo list anymore)

I think the problem has been solved in the mean time.
