### ISSUE TITLE
EXCLUDE not working as expected for files (Origin: bugzilla #680857)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4831]
status NEEDINFO severity *normal* in component *doxywizard* for *---*
Reported in version *1.8.1.2* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[exclude-fail.tgz](https://sourceforge.net/projects/doxygen/files/attachments/bug680857_300427_exclude-fail.tgz/download/download)_ (ID 300427)

On 2012-07-30 17:24:15 +0000, Steve Eckhardt wrote:

    The EXCLUDE box in my project has 9 files in it, including cpdbtree.h and
    cptkanal.h.  Here are the lines from the Doxyfile:
    
    EXCLUDE                = amprcf.h \
                             amutlf.h \
                             cdglobal.h \
                             cpdbtree.h \
                             cpioutil.h \
                             cptkanal.h \
                             cptkndef.h \
                             license.h \
                             msglobal.h \
                             stddde.h
    
    However, the output of a run ends with:
    
    finalizing index lists...
    symbol cache used 4731/65536 hits=383361 misses=4731
    lookup cache used 3607/65536 hits=27040 misses=3637
    finished...
    src/aminc/cpdbtree.h:43: warning: Member pdata (variable) of class CPdbentry
    is not documented.
    C:/Users/Steve/Documents/Visual Studio
    2010/Projects/OSLO_complete/OSLOsrc/aminc/cpdbtree.h:42: warning: Member
    pkey (variable) of class CPdbentry is not documented.
    C:/Users/Steve/Documents/Visual Studio
    2010/Projects/OSLO_complete/OSLOsrc/aminc/cptkanal.h:59: warning: Member id
    (variable) of class CPtkntable is not documented.
    C:/Users/Steve/Documents/Visual Studio
    2010/Projects/OSLO_complete/OSLOsrc/aminc/cptkanal.h:57: warning: Member
    pstring (variable) of class CPtkntable is not documented.
    C:/Users/Steve/Documents/Visual Studio
    2010/Projects/OSLO_complete/OSLOsrc/aminc/cptkanal.h:58: warning: Member
    type (variable) of class CPtkntable is not documented.
    ...
    *** Doxygen has finished
    
    where the ... represents some lines with real problems.
    It would be nice to have the missing characters on the line after
    "finished...", but I can live without them.  Of more concern are the
    warnings on the files I had specifically excluded.  Is there a way to
    suppress these warnings?  Shouldn't Doxygen be skipping these files?  Is it
    my syntax?

On 2012-08-03 15:48:49 +0000, Steve Eckhardt wrote:

    In addition, all of the EXCLUDEd files are shown in the file list with
    documentation.  This is definitely not what I expect EXCLUDE to do.

On 2013-08-11 13:22:21 +0000, albert wrote:

    To be able to reproduce the problem some more information is needed
    
    Can you please check if the problem still occurs with the current version of
    doxygen
    
    If you still see this issue with the latest version of doxygen please add a
    self-contained example (source+config file in a zip or tar).

On 2015-03-26 08:57:55 +0000, csaba_22@yahoo.co.uk wrote:

    Still occurs with doxygen 1.8.9.1

On 2015-03-26 10:37:04 +0000, albert wrote:

    (In reply to csaba_22 from comment # 3)
    > Still occurs with doxygen 1.8.9.1
    
    Can you please supply a small example, so we can try to reproduce the
    problem.

On 2015-03-27 10:32:01 +0000, csaba_22@yahoo.co.uk wrote:

    Created attachment 300427
    Example project and generated html

**Comment by albert-github** [comment]
With the 1.8.9.1. version we get the warnings:
```
.../aws/sdk/src/services/dynamodb/internal/hasher.h:33: warning: include file string.h not found, perhaps you forgot to add its directory to INCLUDE_PATH?
.../aws/sdk/src/services/dynamodb/internal/hasher.h:85: warning: Compound aws::Perfect_Hash is not documented.
.../aws/sdk/src/services/dynamodb/internal/hasher.h:89: warning: Member in_word_set(const char *str, unsigned int len) (function) of class aws::Perfect_Hash is not documented.
```
and in the Class List we see:

![image](https://user-images.githubusercontent.com/5223533/162966643-da341ce5-8bdc-4731-9008-c96bf3564776.png)

In the current version (1.9.3 (c0b9eafbfb53286ce31e75e2b6c976ee4d345473)) the warnings are gone and in the Class List we see:

![image](https://user-images.githubusercontent.com/5223533/162966892-00cc2626-e41c-49c5-a55c-be2e1cb00bca.png)


I think the problem has been solved in the mean time
