### ISSUE TITLE
HTML Help Page Navigation Tree generation (Origin: bugzilla #681427)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4843]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.1.2* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxygen_test.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug681427_221016_doxygen_test.zip/download/download)_ (ID 221016)

On 2012-08-08 05:55:22 +0000, Tobias Appl wrote:

    When using doxygen to produce a HTML Help File for API documentation with
    some introduction and tutorial pages the HTML Help navigation tree for the
    introduction and tutorials isn't generated correctly.
    
    The content pages (introduction and tutorials) are linked with \page and
    \subpage while the topmost (hierachically) page is defined as \mainpage.
    
    1. Problem: Adding 
        <tab type="mainpage" visible="yes" title="" /> 
    to the doxygen style XML file's <navindex> item only produces a link to the
    mainpage itself in the HTML Help navigation tree. The subpages, which should
    appear as leaf nodes to mainpage's node aren't shown.
    
    2. Problem: Manually created link to a page in the doxygen style XML file to
    e.g. a page named "tutorial1" with
       <tab type="user" href="@ref tutorial1" title="tutorial1" />
    the corresponding html page is generated as "tut1.html". 
    The resulting link in the HTML Help navigation tree is dead, when inspecting
    the generated ".hhc" file the link target to the page is "!tut1.html.html"
    instead of "tut1.html".
    
    This happened using Windows 7 and the HTML Help v1.3 .

On 2012-08-09 08:24:56 +0000, Dimitri van Heesch wrote:

    Problem 2 is known and will be correct.
    Can you attach a self-contained example (source+config file in a zip) for
    the first problem?

On 2012-08-09 10:30:50 +0000, Tobias Appl wrote:

    I'm very sorry, but our source files are confidential, i can't release any
    code from them.
    
    Maybe i can explain the problem more in detail:
    Usually when you have a mainpage with subpages, the html help nav tree
    should look something like this:
    
    +Mainpage
       |
       â-Subpage1
       â-Subpage2
       ...
    
    I encountered the problem, that the subpages do not get shown at all in the
    HTML Help navigation tree, the mainpage does not even have the symbol to
    expand the tree. The hhc file also does not show them as subnodes to the
    mainpage node.

On 2012-08-09 11:39:18 +0000, Dimitri van Heesch wrote:

    I'm not asking to release any confidential code. Just make a dummy example
    that has the problem. Is that possible? or does the problem not occur then?

On 2012-08-13 12:38:25 +0000, Tobias Appl wrote:

    Created attachment 221016
    test project
    
    So,
    i'm sorry it took me so so long to come up with an example.
    I attached a zip file containing a doxygen test project which includes even
    the used hhc.exe (Path to hhc.exe in doxygen config file is absolute, you
    will have to change it).
    I really need all of the mainpage's subpages displayed in the subtree of
    mainpage in the HTML Help naviation tree and not on the same tree level as
    the mainpage as it would happen if i set the pages tag's visible attribute
    to "yes".
    I could not include the used doxygen executeable into the archive because of
    the the file size limitations but i used doxygen 1.8.2 windows x64.
    
    I hope this helps you.
    
    -Tobias

**Comment by albert-github** [comment]
Regarding the 2 problems:
1. With version 1.8.1.2. (and 1.8.2) the tree that should be underneath the main page is not shown there but as separate items, in version 1.8.20 the relevant tree is underneath the mainpage. Note same problem occurred in the normal HTML output.
2. The syntax was not completely correct it should be:
    ```
    <tab type="user" url="@ref tutorial_tutorial1" title="tutorial1" />
    ```
    with version 1.8.1.2. it showed the behavior as descrived in the issue, with version 1.8.2 it was solved (and looks still OK with version 1.8.20).

I think the problems have been solved in the mean time.
