### ISSUE TITLE
Functions in group ignore scope when linking (Origin: bugzilla #682614)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4861]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.2* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxygen_682614.patch](https://sourceforge.net/projects/doxygen/files/attachments/bug682614_222566_doxygen_682614.patch/download/download)_ (ID 222566)

On 2012-08-24 14:45:49 +0000, Philipp Moeller wrote:

    Given
    
    namespace foo {
    
    /*!
      Foobar!
     */
    class X
    {
    
    };
    
    }
    
    /// \defgroup yada
    
    /// asdf.
    namespace foo {
    /*!
      \ingroup yada
    
      The argument type is not linked. Neither will ::X generate a link.
    */
    void my_func(X arg);
    
    }
    
    with a default doxygen configuration, there will be no links in the argument
    list of my_func even though X is in the same scope as my_func.
    
    Adding the namespace to everything makes the code unnecessarily verbose, the
    documentation harder to read, and is unnecessary because the function name
    is already prefixed with the scope.
    
    The problem seems to be in line 222 of memberdef.cpp where the scope is only
    used when looking at a class.

On 2012-08-27 17:23:16 +0000, Philipp Moeller wrote:

    Created attachment 222566
    Patch to fix function argument links in file and group documentation
    
    This patch makes use of the associated namespace of a function when
    linkifying an argument list.

On 2012-08-27 17:34:27 +0000, Philipp Moeller wrote:

    I added a patch to fix the issue in all places I have found so far. There
    are possibly more.

On 2015-06-02 09:31:45 +0000, viric@viric.name wrote:

    I am experiencing the same problem with doxygen 1.8.9.1.
    
    Here is my example. If you look at the HTML "Namespace name" page, String is
    properly autolinked to the String type. If you look at the "Group 1" page,
    String is not a link. It would be a link if it said: open(name::String
    name). It seems that the context (inside namespace "name") is lost in the
    Group pages, when autolinking.
    
    ----------------------
    /**
     * \defgroup group1 Group 1
     * */
    
    /// Namespace name
    /// \ingroup group1
    namespace name {
        /// \brief String type
        /// \ingroup group1
        typedef std::string String;
    
        /// \brief Open function
        /// \ingroup group1
        void open(String name);
    };
    
    /// Namespace name
    /// \ingroup group2
    namespace name {
        /// \brief Open Fast function
        /// \ingroup group2
        void openFast(String name);
    };
    ----------------------

**Comment by albert-github** [comment]
Taking the original example ([example.tar.gz](https://github.com/doxygen/doxygen/files/12540150/example.tar.gz)) in the 1.8.2 version we get:
![image](https://github.com/doxygen/doxygen/assets/5223533/17be3e9e-f767-4baf-8a6f-55ff79257880)

where none of the `X` is linked

in the current (1.9.8) doxygen version we get:
![image](https://github.com/doxygen/doxygen/assets/5223533/eaba7ae9-432a-4e9e-9923-1d37dd6141fd)

where the `X`s in the functions are linked.

The `::X` iin the comment is not linked as here we refer to a global entity and `X` is not global but part of a namespace

Analogous results for the second example.

I think the problem has been solved in the mean time.
