### ISSUE TITLE
Identification of doxygen version in generated configuration / template files (Origin: bugzilla #682718)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4863]
status REOPENED severity *normal* in component *general* for *---*
Reported in version *1.8.1.2-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[patch_682718.res](https://sourceforge.net/projects/doxygen/files/attachments/bug682718_222455_patch_682718.res/download/download)_ (ID 222455)

On 2012-08-26 11:31:56 +0000, albert wrote:

    A number of configuration / template files generated with Doxygen have the
    version number with which they are generated included (e.g. Doxyfile,
    extensionsFile.rtf) other files don't have this (files generated with
    doxygen -w and doxygen -l).
    The advantage is that one can easily see which which version of doxygen
    these files have initially been generated.

On 2012-08-26 11:37:42 +0000, albert wrote:

    Created attachment 222455
    PATCH: Adding version information to all generated / template files
    
    This patch sees to it that all generated / template files have the version
    number in them. A number of template files / configuration files are hard
    coded, so here the versionString is added, some files go through a header
    file (e.g header_html.h), in this case the version has been coded as
    $doxygen_version (with underscore! so it is not confused with the normal
    $doxygenversion replacements) and in the code automatically replaced by
    versionString.

On 2012-09-22 17:04:59 +0000, Dimitri van Heesch wrote:

    Thanks, I'll include it (with some minor adaptions) in the next subversion
    update.

On 2012-10-07 16:13:49 +0000, albert wrote:

    Just checked the implementation of this patch in svn version 833
    (Doxygen-1.8.2-20120930) and I see that (at least for the html footer and
    header) the line:
    "\n"
    is missing, this file puts the version with which the file is generated in
    the output file, so it can be traced with which version the file was
    generated.
    The $doxygenversion is replaced during runtime of Doxygen and thus gives the
    version that is running at that moment.
    
    latexgen.cpp looks OK
    layout_default.h has same problem as html header and footer

On 2012-12-26 16:08:55 +0000, Dimitri van Heesch wrote:

    This bug was previously marked ASSIGNED, which means it should be fixed in
    doxygen version 1.8.3. Please verify if this is indeed the case. Reopen the
    bug if you think it is not fixed and please include any additional
    information
    that you think can be relevant.

On 2013-01-06 10:32:35 +0000, albert wrote:

    See comment 3, checked against svn version 838 / Doxygen 1.8.3

**Comment by albert-github** [comment]
I looked at the results of version 1.8.15 cand here all the mentioned files had the 1.8.15 identification.

I think the problem has been solved in the mean time.
