### ISSUE TITLE
markdown: images are not included in latex (Origin: bugzilla #683112)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4868]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.2* on platform *Other*
Assigned to: Dimitri van Heesch

On 2012-08-31 14:59:23 +0000, Markus Raab wrote:

    When using the markdown syntax
    ![Title](image.png)
    
    The latex output does not contain the image.
    
    Expected is that
    \image latex image.png "Title" width=\textwidth
    will embedded.
    
    But instead the generated code is only:
    @image html actors.png "Actors"
    
    It would be beneficial if the user can choose the width with some markdown
    extension and if the image would be added into RTF too.

On 2015-07-10 11:41:31 +0000, N wrote:

    Images in Markdownfiles are still ignored in Latex-Output.
    ==========================================================
    
    While Doxygens own Syntax (`@image latex Picture.png "Bild3"
    width=\textwidth`) works fine the Markdownsyntax (`![Bild](Picture.png)`) is
    ignored in latexoutput.
    
    Below you will find an example.
    
    
    About my system:
    ----------------
    
    * Linux-Mint 17.1
    * Doxygen
        * version 1.8.6 (installed from the usual trusty/main-Repo)
        * I tried version 1.8.11 from the git-repo too (same problem)
        * Doxygen's default configuration
    
    
    Example
    -------
    
    ````
    ### An example markdownfile with images ###
    
    This will work for html but NOT work for LaTeX (but should):
    
    ![Bild](Picture.png)
    
    
    But this works fine:
    
    @image html Picture.png "Bild2"
    @image latex Picture.png "Bild3" width=\textwidth
    
    End of example
    ````
    
    
    See also
    --------
    
    * Bug # 719541 - Error with inserting images to PDF with Markdown

**Comment by albert-github** [comment]
With version 1.8.6 the image from `![Bild](Picture.png)` is not present. With version 1.8.15 the image is present.

I think the problem has been solved in the mean time.
