### ISSUE TITLE
Error generating RTF when an Objective-C class includes a Protocol (Origin: bugzilla #683587)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4879]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.2* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[TestClass.h](https://sourceforge.net/projects/doxygen/files/attachments/bug683587_223776_TestClass.h/download/download)_ (ID 223776)

On 2012-09-07 17:07:10 +0000, Adam Fedor wrote:

    Created attachment 223776
    Objective-C Test class
    
    Doxygen does not generate proper RTF when an Objective-C class includes a
    Protocol.  Attached is a simple test case. This produces an error like:
    
    Combining RTF output...
    error: problems opening rtf file
    /Users/fedor/Source/Doxygen/Test/rtf/refman.rtf for reading
    An error occurred during post-processing the RTF files!
    
    
    although other problems are possible, including generating invalid RTF
    (hopefully that case is related, other wise I'll have to submit another bug
    report). I can submit the configuration file separately, but it is a basic
    configuration that is set to generate RTF.

**Comment by albert-github** [comment]
With version 1.8.2 I see the mentioned  problem.
With version 1.8.15 this problem is gone (and a refman.rtf) is generated (already in 1.8.3).

I think the problem has been solved in the mean time.
