### ISSUE TITLE
Docset info.plist file doesn't include feed URL (Origin: bugzilla #683640)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4881]
status NEW severity *minor* in component *general* for *---*
Reported in version *1.8.2* on platform *Other*
Assigned to: Dimitri van Heesch

On 2012-09-08 20:42:46 +0000, Steve Pucci wrote:

    The Info.plist file generated by doxygen doesn't include the key
    DocSetFeedURL, required for packaging the docset as an atom feed.  To be
    analogous to DocSetFeedName, I suggest adding a DOCSET_FEEDURL configuration
    parameter that will pass through.

**Comment by albert-github** [comment]
've just pushed a proposed patch, pull request #8745

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.3.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
