### ISSUE TITLE
Failure to generate HTML Help contents file (.HHC) (Origin: bugzilla #684394)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4891]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.2* on platform *Other*
Assigned to: Dimitri van Heesch

On 2012-09-19 18:24:41 +0000, xltoolbox@gmx.net wrote:

    Doxygen 1.8.2 no longer creates propery HTML Help contents files (.HHC).
    
    It worked well with 1.7.6.1 with the very same project files.
    
    The problem is that Doxygen generates only a single TOC entry, for the main
    page. All other pages are now ignored. The resulting .HHC file is very
    small.

**Comment by albert-github** [comment]
Unfortunately there is nothing here to work with / search the problem.

The HTML Help files that are, currently, generated look OK to me.

Setting the issue to incomplete / invalid
