### ISSUE TITLE
markdown reference in first line of file not recognized (Origin: bugzilla #684481)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4892]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.2* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[test1.md](https://sourceforge.net/projects/doxygen/files/attachments/bug684481_224840_test1.md/download/download)_ (ID 224840)
- _[test2.md](https://sourceforge.net/projects/doxygen/files/attachments/bug684481_224841_test2.md/download/download)_ (ID 224841)
- _[doxygen-atx-header-id.diff](https://sourceforge.net/projects/doxygen/files/attachments/bug684481_266830_doxygen-atx-header-id.diff/download/download)_ (ID 266830)

On 2012-09-20 14:55:41 +0000, Mark.Moll@gmail.com wrote:

    If a markdown file starts with this line:
    {{{
    # Hello {#test1}
    }}}
    then the output file is not named test1.html, and, more importantly, other
    pages cannot use "\ref test1".
    
    This equally valid markdown syntax does work, however:
    {{{
    Hello {#test2}
    ==============
    }}}

On 2012-09-20 14:57:07 +0000, Mark.Moll@gmail.com wrote:

    Created attachment 224840
    markdown file that shows problem

On 2012-09-20 14:57:41 +0000, Mark.Moll@gmail.com wrote:

    Created attachment 224841
    markdown file that shows a workaround

On 2012-09-20 15:02:19 +0000, Mark.Moll@gmail.com wrote:

    BTW, it'd great if a file called foo.md would:
    (1) turn into foo.html rather than md_foo.html.
    (2) implicitly make "\ref foo" resolve to foo.html

On 2014-01-21 01:27:31 +0000, Alex Merry wrote:

    Created attachment 266830
    Patch to fix id extraction

On 2014-01-21 01:32:12 +0000, Alex Merry wrote:

    A comment about the patch:
    
    isAtxHeader() parses out the id and the title into the appropriate
    variables.  The subsequent call to extractTitleId() would then have the
    trimmed title (without the id ref) as input, and hence always set id to be
    empty.

**Comment by albert-github** [comment]
Whit version 1.8.2 the link is not present and a warning (test2.md:1: warning: unable to resolve reference to `test1' for \ref command) is given. With version 1.8.15 the link is present and no warning. 
With version 1.8.2 we have the files md_test1.html and test2.html, with version1.8.15 we have test1.html and test2.html.

I think the problem has been solved in the mean time.
