### ISSUE TITLE
Problem with <pre> and @verbatim (Origin: bugzilla #684674)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4895]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.2-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[example_pre_verbatim_problem.taz](https://sourceforge.net/projects/doxygen/files/attachments/bug684674_225031_example_pre_verbatim_problem.taz/download/download)_ (ID 225031)

On 2012-09-23 18:21:13 +0000, albert wrote:

    Created attachment 225031
    Example for described problems
    
    This bug report contains a number of problems regarding the <pre> tag and
    the @verbatim tag, both alone and in combination with the @par tag.
    I've created an example for Fortran and 2 examples for C (one with ///
    comments and one with /** ... */ comments).
    Furthermore I've ran the problem with and without Markdown support.
    
    I'm going to try to sum up the problems I see:
    Fortran (aa.f90):
    ========
    pre_test: missing second empty line in the pre section (is it necessary to
    have </pre><pre> tags when there are one or more empty lines ?)
    pre_test_par: output is completely garbled
    verbatim_test: OK
    verbatim_test_par: OK
    
    C with /// comments (bb.c):
    ===========================
    c_pre_test: See Fortran
    c_pre_test_par: See Forran
    c_verbatim_test: Completely garbled when using MARKDOWN (see error message
    below). When not using MARKDOWN looks OK, except for the fact that the
    comment signs are still present.
    c_verbatim_test_par: Completely garbled when using MARKDOWN (see error
    message below). When not using MARKDOWN looks OK, except for the fact that
    the comment signs are still present.
    When running with MARKDOWN support I also get the error messages:
    D:/bb.c:24: warning: unexpected command endverbatim
    D:/bb.c:52: warning: unexpected command endverbatim
    
    C with /** ... */ comments (cc.c):
    ==================================
    c_pre_test: See Fortran
    c_pre_test_par: See Fortran
    c_verbatim_test: OK, note that now there are no comment signs either as this
    is a block comment.
    c_verbatim_test_par: OK , note that now there are no comment signs either as
    this is a block comment.

On 2012-11-18 11:07:27 +0000, Dimitri van Heesch wrote:

    Changed version 'latest' to '1.8.2-SVN' so I can remove 'latest' as an
    option as it is a moving target.

**Comment by albert-github** [comment]
I checked the provided output (1.8.2 version) and here are the problems as indicated.
In the current doxygen version (1.9.6) all he comment block look OK (and are as expected).

I think the problem has been solved in the mean time
