### ISSUE TITLE
@page adds <b> text at hte top of the page if JAVADOC_AUTOBRIEF is set to YES (Origin: bugzilla #685277)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4910]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.2* on platform *Other*
Assigned to: Dimitri van Heesch

On 2012-10-02 11:49:35 +0000, Hubert Mackenberg wrote:

    In @page sections text insided <b> ... </b> tags is not properly handled if
    JAVADOC_AUTOBRIEF is set to YES. All that text will appear a second time at
    the top of the generated page.
    
    The problem can be reproduced in this way:
    
    1. Create a file test.h with this content:
    
        /** @page test_page Test
         **/
    
        /** @page test_page
         ** <br>
         ** <H1>Header</H1>
         **/
    
        /** @page test_page
         **
         ** <b>Section 1</b>
         ** - some text
         **/
    
        /** @page test_page
         **
         ** <b>Section 2</b>
         ** - some text
         **/
    
    
    2. Create an default configuration file using:
    
          doxygen -g
    
    3.  In Doxfile, set:
    
         INPUT               = test.h
         JAVADOC_AUTOBRIEF   = YES
    
    4. Run doxygen:
    
         doxygen
    
    Load html\index.html and go to Related Pages -> Test.
    There is additional text 'Section 2' and 'Section 1' at top of the page.

**Comment by albert-github** [comment]
When running with version 1.8.15 I see the texts:
<b>Section 2</b> and Section 1 at the top

With the current master version (June 6, 2019) these texts are gone.

I think the problem is 'fixed but not released' yet.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
