### ISSUE TITLE
false positives reporting parameters or return value not being documented (Origin: bugzilla #685714)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4918]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.2* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[DOX.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug685714_226033_DOX.zip/download/download)_ (ID 226033)

On 2012-10-08 11:58:46 +0000, ng (ice-dev) wrote:

    Created attachment 226033
    Sample dox file + source code demonstrating the problem
    
    The files attached when running doxygen report the following warnings
    despite being fully commented:
    
    BugDoxygen.cpp(12) : warning: parameters of member CBugDoxygen::CBugDoxygen
    are not (all) documented
    BugDoxygen.cpp(12) : warning: return type of member CBugDoxygen::CBugDoxygen
    is not documented
    BugDoxygen.h(19) : warning: parameters of member CBugDoxygen::GetDummy are
    not (all) documented
    BugDoxygen.h(19) : warning: return type of member CBugDoxygen::GetDummy is
    not documented
    BugDoxygen.h(23) : warning: parameters of member CBugDoxygen::GetDummy are
    not (all) documented
    BugDoxygen.h(23) : warning: return type of member CBugDoxygen::GetDummy is
    not documented
    *** Doxygen has finished

On 2012-10-09 13:22:00 +0000, ng (ice-dev) wrote:

    it seems the incriminated parameter is
    echo GENERATE_HTML          = NO

On 2012-10-09 13:33:18 +0000, ng (ice-dev) wrote:

    (In reply to comment # 1)
    > it seems the incriminated parameter is
    > echo GENERATE_HTML          = NO
    
    ignore the echo it is part of a batch file used to generate a dox file on
    the fly

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6905

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
