### ISSUE TITLE
Doxygen does not recognize unicode path/folder (Origin: bugzilla #687393)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4938]
status NEW severity *normal* in component *general* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[Uniode_Path_ä¸­æè·¯å¾.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug687393_227861_Uniode_Path_ä¸­æè·¯å¾.zip/download/download)_ (ID 227861)

On 2012-11-02 02:10:04 +0000, yangke0323@hotmail.com wrote:

    Created attachment 227861
    An example project to produce the problem.
    
    I am using:
    - Doxygen 1.8.2;
    - Windows 7 (English Language Pack);
    
    Problem Description:
    If source code files are located in a folder that contains Chinese, doxygen
    cannot open map files generated by graphviz. Therefore, all graphs are
    missing from the output chm file.
    
    It seems that this problem is not limited to Chinese. If the folder name
    contains any Unicode, Doxygen cannot open map files.

On 2012-11-17 14:11:03 +0000, Dimitri van Heesch wrote:

    The name of the zip contains Chinese characters which display properly on my
    systems (Mac and Windows 7). If I unzip the file however I get a directory
    with Unicode_path and then some garbled characters, so I wonder what the
    encoding of the directory name is, but it doesn't seem unicode or something
    that my (English) OSes support. I don't know how I can debug the problem
    now. Any ideas?

On 2012-11-23 14:25:26 +0000, yangke0323@hotmail.com wrote:

    Thanks for looking into this problem.
    
    It is very likely that my Windows uses the character set called "GBK" or
    "GB2312" to encode the folder.
    
    I am sorry that I was misleading in my description. Later I checked and I
    realize that Chinese characters have multiple (and overlapping) character
    sets. They are
     - unicode;
     - GBK     (used in Windows, some versions of Linux, and many PC software);
     - GB2312  (Simplified Chinese only);
     - BIG5    (Traditional Chinese only);
     - GB18030 (latest mainland China standard, supposedly the superset of GBK);
     - others.
    
    In that case, the problem should be doxygen unable to open map files if the
    path of map files contains GBK or GB2312 characters.
    
    The Chinese character set is a bit confusing. If you name the folder in
    Chinese, could doxygen correctly open map files in that way? Please let me
    know if you could make the problem occur.
    
    
    (In reply to comment # 1)
    > The name of the zip contains Chinese characters which display properly on
    my
    > systems (Mac and Windows 7). If I unzip the file however I get a directory
    with
    > Unicode_path and then some garbled characters, so I wonder what the
    encoding of
    > the directory name is, but it doesn't seem unicode or something that my
    > (English) OSes support. I don't know how I can debug the problem now. Any
    > ideas?

**Comment by albert-github** [comment]
Unfortunately the attachment cannot be found anymore (by me), seen the usage of `ghc::filesystem` (see also test 61) the possibility exists that the problem has been solved as well.
I think the problem is incomplete.
