### ISSUE TITLE
Custom LaTeX header doesn't support placeholders (Origin: bugzilla #687574)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4940]
status NEEDINFO severity *enhancement* in component *build* for *---*
Reported in version *1.8.2* on platform *Other*
Assigned to: Dimitri van Heesch

On 2012-11-04 15:49:02 +0000, Stefan wrote:

    If one uses a custom LaTeX header he has to create one header for each paper
    size.
    
    It would be really helpful to support a placeholder for the paper size.
    
    In addition none of the other regular placeholders are supported inside the
    custom LaTeX header, footer and style files.
    This is very annoying and a regression compared to the functionality
    available for HTML generation.
    
    Thanks in advance,
    Stefan

On 2014-04-19 13:49:53 +0000, albert wrote:

    Can you please attach a self-contained example (source+config file in a tar
    or
    zip) that allows us to reproduce the problem? With an indication where
    exactly the problem regarding the regular placeholders exists.

**Comment by albert-github** [comment]
I think this problem has a similar problem as "Default LATeX header misses $-placeholders (Origin: bugzilla #668003)" (#4530) and has been tackled with pull request #8309.

I think the problem is fixed but not released.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.2.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
