### ISSUE TITLE
namespace links break when the namespace also exists in a tag (Origin: bugzilla #688100)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4946]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.2-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[broken_namespaces_with_tags.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug688100_228700_broken_namespaces_with_tags.zip/download/download)_ (ID 228700)

On 2012-11-11 16:39:30 +0000, Philipp Moeller wrote:

    Created attachment 228700
    Contains two doxygen files and two source files. One generates a tag with a
    documented namespace, the other one uses it.
    
    If a namespace appears in a tag file and is documented again in the current
    project, no page will be generated for it. Links in breadcrumbs will point
    to that namespace, but will be broken.
    
    To reproduce:
    
    - unzip the attached archive
    - doxygen Doxyfile1 && doxygen Doxyfile2
    - goto prj2/html/classASDF_1_1Y.html
    - click the ASDF link in the breadcrumb -> 404
    
    I have also seen missing namespaceASDF.tex files for latex output, but
    cannot reproduce it currently.
    
    Preferably, the links to the namespace would lead to the tag file it was
    generated from.

On 2013-07-22 12:13:55 +0000, Thomas wrote:

    This seems to be a duplicate of Bug
    https://bugzilla.gnome.org/show_bug.cgi?id=403302

**Comment by albert-github** [comment]
With version 1.8.2 the click on the mentioned item in the breadcrum resulted in 1 "404" error.
With version 1.8.14 the click went to the right page

I think the problem has been solved in the mean time.
