### ISSUE TITLE
JavaDoc @see doesn't generate a link (Origin: bugzilla #688383)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4950]
status NEW severity *minor* in component *build* for *---*
Reported in version *1.8.2* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[show.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug688383_229165_show.zip/download/download)_ (ID 229165)

On 2012-11-15 12:10:11 +0000, Adam Badura wrote:

    In my C++ code I have never managed to make @see generate a link to code
    component. It is always just a plain text.
    
    Doxygen does not generate any warning on broken link. Also the very same
    text within {@link } in the same comment does work well and makes a link.

On 2012-11-15 20:18:57 +0000, Dimitri van Heesch wrote:

    Can you please attach a self-contained example (source+config file in a tar
    or zip) that allows me to reproduce the problem?

On 2012-11-16 17:03:27 +0000, Adam Badura wrote:

    Created attachment 229165
    Examples for few bugs
    
    Archive contains a Doxygen configuration file and a short C++ header file
    with a class and few functions showing bugs in Doxygen handling of JavaDoc
    formatted comments.
    
    Examples for:
    - Bug 688381,
    - Bug 688383,
    - Bug 688384,
    - Bug 688385,
    - Bug 688386,
    - Bug 688387.

On 2018-02-26 13:10:32 +0000, albert wrote:

    I was able to create links in the "see also" section (1.8.2 and 1.8.14):
    @see \ref linkTarget()
    @see \link linkTarget() \endlink
    @see {@link linkTarget()}

On 2018-02-27 10:30:25 +0000, albert wrote:

    One of the other issues in this series states that AUTOLINK_SUPPORT is
    turned off, when turned on the links are all shown.
    
    The other items in this bug report have a @link and are thus shown.
    
    I don't think this is a bug, but usage.

**Comment by albert-github** [comment]
As mentioned in a comment the `AUTOLINK_SUPPORT` should be turned on, I think the issue is usage.
