### ISSUE TITLE
JavaDoc @link does not use code font (Origin: bugzilla #688384)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4951]
status NEW severity *minor* in component *build* for *---*
Reported in version *1.8.2* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[show.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug688384_229166_show.zip/download/download)_ (ID 229166)

On 2012-11-15 12:18:02 +0000, Adam Badura wrote:

    Links entered with {@link ...} are not shown in HTML with code font. While
    they should since link in ordinary font is done with {@linkplain ...}.

On 2012-11-15 20:19:13 +0000, Dimitri van Heesch wrote:

    Can you please attach a self-contained example (source+config file in a tar
    or zip) that allows me to reproduce the problem?

On 2012-11-16 17:03:59 +0000, Adam Badura wrote:

    Created attachment 229166
    Examples for few bugs
    
    Archive contains a Doxygen configuration file and a short C++ header file
    with a class and few functions showing bugs in Doxygen handling of JavaDoc
    formatted comments.
    
    Examples for:
    - Bug 688381,
    - Bug 688383,
    - Bug 688384,
    - Bug 688385,
    - Bug 688386,
    - Bug 688387.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #8951

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.3.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
