### ISSUE TITLE
JavaDoc @code generates link (Origin: bugzilla #688385)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4952]
status NEW severity *minor* in component *build* for *---*
Reported in version *1.8.2* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[show.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug688385_229167_show.zip/download/download)_ (ID 229167)

On 2012-11-15 12:25:07 +0000, Adam Badura wrote:

    If text within {@code ...} happens to be a name of code component it is made
    a link even thou it should not since @code should only change font and
    remove special meaning from characters < and >.
    
    I do have AUTOLINK_SUPPORT set to NO and the very same text placed in the
    same comment but without {@code ...} does not make any link.

On 2012-11-15 20:19:49 +0000, Dimitri van Heesch wrote:

    Can you please attach a self-contained example (source+config file in a tar
    or zip) that allows me to reproduce the problem?

On 2012-11-16 17:04:33 +0000, Adam Badura wrote:

    Created attachment 229167
    Examples for few bugs
    
    Archive contains a Doxygen configuration file and a short C++ header file
    with a class and few functions showing bugs in Doxygen handling of JavaDoc
    formatted comments.
    
    Examples for:
    - Bug 688381,
    - Bug 688383,
    - Bug 688384,
    - Bug 688385,
    - Bug 688386,
    - Bug 688387.

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.3.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
