### ISSUE TITLE
JavaDoc @literal is not recognized (Origin: bugzilla #688386)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4953]
status NEW severity *enhancement* in component *build* for *---*
Reported in version *1.8.2* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[show.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug688386_229169_show.zip/download/download)_ (ID 229169)

On 2012-11-15 12:27:30 +0000, Adam Badura wrote:

    Doxygen does not recognize {@literal ...} and issues a warning:
    
    warning: Found unknown command `\literal'

On 2012-11-16 17:05:01 +0000, Adam Badura wrote:

    Created attachment 229169
    Examples for few bugs
    
    Archive contains a Doxygen configuration file and a short C++ header file
    with a class and few functions showing bugs in Doxygen handling of JavaDoc
    formatted comments.
    
    Examples for:
    - Bug 688381,
    - Bug 688383,
    - Bug 688384,
    - Bug 688385,
    - Bug 688386,
    - Bug 688387.

On 2018-02-26 19:06:30 +0000, albert wrote:

    Not all JavaDoc commands are valid in doxygen, doxygen is not a clone of
    JavaDoc and, I think, it is doubtful whether or not all JavaDoc commands
    should be and can be valid in doxygen.
    
    Same reasoning is, in my opinion, valid for the command @linkplain
    (Bug_688387 which also has another problem mentioned).

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #8949

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.3.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
