### ISSUE TITLE
JavaDoc @linkplain is not recognized (Origin: bugzilla #688387)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4954]
status ASSIGNED severity *normal* in component *build* for *---*
Reported in version *1.8.2* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[show.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug688387_229170_show.zip/download/download)_ (ID 229170)

On 2012-11-15 12:30:52 +0000, Adam Badura wrote:

    Not only Doxygen does not recognize @linkplain. It also misunderstands it
    for a misspelled {@link ...} without (expected) white space after "link"
    issuing a warning:
    
    warning: expected whitespace after javalink command
    
    This is especially bad since resulting documentation not only misses the
    link but also shows closing } from the {@linkplain ...}.

On 2012-11-16 17:05:25 +0000, Adam Badura wrote:

    Created attachment 229170
    Examples for few bugs
    
    Archive contains a Doxygen configuration file and a short C++ header file
    with a class and few functions showing bugs in Doxygen handling of JavaDoc
    formatted comments.
    
    Examples for:
    - Bug 688381,
    - Bug 688383,
    - Bug 688384,
    - Bug 688385,
    - Bug 688386,
    - Bug 688387.

On 2018-02-26 19:08:08 +0000, albert wrote:

    Regarding the support of @linkplain see discussion in Bug_688386 (@literal).

On 2018-02-26 19:22:49 +0000, albert wrote:

    I've just pushed a proposed patch to github (pull request 667,
    https://github.com/doxygen/doxygen/pull/667) so that in case of @linkplain
    an understandable waring message.

On 2018-03-05 15:55:57 +0000, albert wrote:

    *** Bug 620332 has been marked as a duplicate of this bug. ***

On 2018-04-22 12:30:48 +0000, albert wrote:

    Code has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Comment by albert-github** [comment]
For the `{@javaplain ...}` implementation, I've just pushed a proposed patch, pull request #8951

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub.
