### ISSUE TITLE
"Browse to file"-Button uses slash / instead of backslash \ required (Origin: bugzilla #689532)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4977]
status NEW severity *minor* in component *doxywizard* for *---*
Reported in version *1.8.2* on platform *Other*
Assigned to: Dimitri van Heesch

On 2012-12-03 14:01:07 +0000, sabrina.lehrer@etas.com wrote:

    DoxyWizard-Expert-HTML-CHM_FILE
      "Browse to file"-Button uses slash / instead of backslash \ required

On 2012-12-06 02:31:34 +0000, Kevin McBride wrote:

    I see that the doxywizard uses the unix style slash:
    
    C:/Users/Kevin/Bug 688647
    
    I will let Dimitri decide if he wants to fix this bug.  For windows, it
    should be \ but NT and above accept both \ and / in filenames anyway.  I do
    not feel that this bug really needs to be fixed.

On 2012-12-06 02:35:48 +0000, Kevin McBride wrote:

    *** Bug 689531 has been marked as a duplicate of this bug. ***

**Comment by albert-github** [comment]
As indicated by Kevin McBride on modern systems there is no problem with the slashes. 

So there is here no real problem, setting issue to no won't fix.
