### ISSUE TITLE
Markdown tables do not support line breaks in source files. (Origin: bugzilla #690000)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4987]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.2* on platform *Other*
Assigned to: Dimitri van Heesch

On 2012-12-10 19:01:29 +0000, Adam Shapiro wrote:

    Currently, the markdown table support does not appear to support continuing
    a table row on another line in a source file. This can cause issues when a
    row's text is very long, especially in environments where character limits
    are in use.
    
    For example, on our project we use an 80 character limit (possibly outdated,
    I know, but done for compatibility with developers' editor choices). I'm
    trying to build a table of parameter/description pairs, however most of the
    descriptions require more than the 80 characters allowed. The table displays
    properly when I do not add any line breaks in each of the descriptions, but
    stops as soon as a line break is inserted. We have an automated style
    checking tool that will add newlines after 80 characters, so this can be
    quite frustrating.
    
    In the following table, the setting2 row and the rest of the table are
    completed after the word "Doxygen". The row below is displayed as regular
    text on the page.
    
    Parameter  | Required | Description
    :--------- | :------: |
    :----------------------------------------------------
    `setting1` |    No    | This setting will display fine, despite its length,
    since it does not have a line break.
    `setting2` |    No    | This setting will end the table as soon as Doxygen
                            encounters the line break above at "Doxygen".
    `setting3` |    No    | No longer part of the table because of the error.
    
    I have tried all combinations of adding and removing |s - before and after
    each line, adding them where the column specifiers should be, etc. - but
    nothing has worked so far.

On 2012-12-12 18:43:29 +0000, Dimitri van Heesch wrote:

    This is a limitation of how markdown extra style tables work. 
    You can try it here for yourself:
    http://michelf.ca/projects/php-markdown/dingus/
    (set the filter to PHP markdown extra)

On 2012-12-12 22:30:55 +0000, Adam Shapiro wrote:

    Ah that's unfortunate. Is an HTML table the next-best alternative? I having
    the table described horizontally in the code in markdown since it's a lot
    more readable when looking at the source file, but I guess that may not be
    possible for us.

On 2012-12-12 22:49:06 +0000, Dimitri van Heesch wrote:

    You could wrap the html commands in an alias, i.e. use
    
      \paramtable
      \paramrow{setting1,No,This setting will display fine\, despite its
    length\,
                            since it does not have a line break.}
      \paramrow{setting2,No,This setting will end the table as soon as Doxygen
                            encounters the line break above at "Doxygen".}
      \paramrow{setting3,No,No longer part of the table because of 
                            the error.}                       
      \endparamtable
    
    in combination with the following definitions in the config file:
    
    ALIASES =
    paramtable="<table><tr><th>Parameter<th>Required<th>Description</tr>" \
              paramrow{3}="<tr><td>\1<td align=\"center\">\2<td>\3</tr>" \
              endparamtable="</table>"
    
    Note that you have to escape the commas in the text.

On 2012-12-14 15:21:53 +0000, Adam Shapiro wrote:

    Interesting. I guess that's what we'll do - not perfect I suppose, but it
    should work. More flexible table entry might be something worth considering
    in a future release I guess.
    
    Thanks Dimitri!

**Comment by albert-github** [comment]
I think the issue here is an usage issue, as can be seen from the comments.
