### ISSUE TITLE
Fortran Structures (Origin: bugzilla #690059)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4988]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.2* on platform *Other*
Assigned to: Dimitri van Heesch

On 2012-12-11 18:37:22 +0000, K Kazinski wrote:

    The current version of doxygen does not parse the keyword STRUCTURE.  The
    STRUCTURE keyword was not deprecated in F90.

On 2012-12-12 21:29:48 +0000, albert wrote:

    In the Doxygen Forum Davide Cesari wrote:
    Well, the STRUCTURE keyword in Fortran is a pre-f90 nonstandard
    extension provided by some compilers and, as far as I know, is not
    supported by Doxygen; since Fortran 90 structures have been replaced by
    derived types (TYPE keyword) which are now a standard and work well in
    Doxygen.

**Comment by albert-github** [comment]
As written `STRUCTURE` never has been a Fortran keyword and Fortran uses the `TYPE` keyword for this I think this is not a doxygen bug and an interpretation issue.
