### ISSUE TITLE
friend class wrongly placed in global namespace (Origin: bugzilla #690741)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5003]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.3-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[friend-wrong-namespace.tar.xz](https://sourceforge.net/projects/doxygen/files/attachments/bug690741_232247_friend-wrong-namespace.tar.xz/download/download)_ (ID 232247)

On 2012-12-26 17:25:42 +0000, Matthew Woehlke wrote:

    Created attachment 232247
    complete example demonstrating the problem
    
    Given some code like:
    
    namespace animals
    {
      template <typename T> class milk_provider;
    
      /// Moo!
      class cow
      {
        template <typename T> friend class milk_provider;
      };
    }
    
    Doxygen wrongly believes that milk_provider lives in the global namespace.
    As a result, a bogus class entry is generated, and links within the
    friending class are wrong.
    
    Complete example attached. Note that two entries are created for
    'milk_provider'; one in the 'animals' namespace (the correct one, from the
    definition and documentation of the class), and one in the global namespace
    (wrong, from the friend declaration in 'cow').

**Comment by albert-github** [comment]
With version 1.8.3 we see the, wrong, behavior as indicated:

![image](https://user-images.githubusercontent.com/5223533/127149873-b0fff8a3-72ac-4fd8-96be-94e3162b6a9e.png)

when running 1.9.1 we see:

![image](https://user-images.githubusercontent.com/5223533/127149940-6f39b962-6021-49a5-b01c-f3cf22d74d8f.png)

this looks OK to me, so I think the problem has been solved in the mean time.
