### ISSUE TITLE
Line numbers for examples (Origin: bugzilla #691689)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5032]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.8.3-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[EXAMPLE_WITH_LINES.diff](https://sourceforge.net/projects/doxygen/files/attachments/bug691689_233467_EXAMPLE_WITH_LINES.diff/download/download)_ (ID 233467)

On 2013-01-14 05:08:21 +0000, Karl Rupp wrote:

    Each of the @example files is listed in a dedicated HTML file without line
    numbers. There seems to be no switch for enabling line numbers. An option
    for adding line numbers to the example listings would be helpful (cf.
    \includelineno vs. \include).

On 2013-01-14 20:35:46 +0000, Karl Rupp wrote:

    Created attachment 233467
    Suggested patch for 1.8.3-SVN enabling/disabling line numbers in example
    listings.

On 2018-06-28 17:56:08 +0000, albert wrote:

    Instead of a new tag in the doxygen configuration file (Doxyfile) a more
    consistent and flexible command has been introduced: \examplelineno.
    - consistent with \include / \includelineno, \snippet / \snippetlineno
    - more flexible as per example it can be decided whether or not line numbers
    are required
    
    I've just pushed a proposed patch to github (pull request 780,
    https://github.com/doxygen/doxygen/pull/780)

**Comment by albert-github** [comment]
Alternative method has been implemented.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
