### ISSUE TITLE
Image references (Origin: bugzilla #692168)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5041]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.8.3.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2013-01-21 08:05:59 +0000, Alfonso wrote:

    It would be great if you could add the possibility to refer to images
    directly (without the need for anchors). This is important when working with
    the xml output.

On 2013-01-21 08:07:34 +0000, Alfonso wrote:

    Some comments on the background of this request (I submitted this in an
    email to the user list):
    
    "In my workflow I transform the xml output from Doxygen to a docbook
    xml document (this is done with a custom xsl transform). In my final
    document I would like to have references of the kind "For more
    information look at Figure 3":
    
    -For that I think I need to be able to generate an id for the image in
    the docbook document. However, as far as I have understood images
    cannot be directly refered to in Doxygen, but we are supposed to use
    anchors for it.
    
    -This means that I cannot proceed as I would like to: simply
    translating the \ref in Doxygen to an xref in docbook, and copy the id
    of the figure in Doxygen to the id of the figure in Docbook.
    
    -Translating the reference to an anchor in Doxygen as a reference to
    an anchor would, as far as I understand, not really solve my problem
    in Doxygen."

**Comment by albert-github** [comment]
Wit the proposed pull request #8692 it will be possible to define an anchor with an image and refer to this anchor.
An automatic anchor is not possible as this might not be persistent and thus references might fail. 
I think this proposed pull request will solve this issue.

**Comment by albert-github** [comment]
The mentioned proposed pull request has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.2.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
