### ISSUE TITLE
Element Documentation generated changed and inconsistant. (Origin: bugzilla #692703)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5047]
status NEW severity *major* in component *general* for *---*
Reported in version *1.8.3* on platform *Other*
Assigned to: Dimitri van Heesch

On 2013-01-28 12:36:35 +0000, Paul. wrote:

    I have sucessfully used the following method for documenting elements in
    structures and global variable in 1.7.xx
    
    _U8 u8Simple;         ///< Something short.
    _U8 u8ComplexElement; ///< Some information on this element which because of
    it
                          ///< complexity, or to keep lines to reasonable
    length,
                          ///< I extended to a seconds or even third line.
    _U8 u8AnotherElement; ///< Some information on this element which because of
    it
                         ///< complexity, or to keep lines to reasonable length,
                         ///< I extended to a seconds or even third line.
    
    In 1.8.x the output has changed and is inconsistant.
    
    u8Simple is documented correctly in its brief and extended sections.
    
    u8ComplexElement has no brief description and its extended description is
    split with the first line being in a box separated from the next two lines.
    
    u8AnotherElement has a minor indentation change to the comments, it still
    has no brief description but its extended description now has the text
    correctly displayed as a single block.

**Comment by albert-github** [comment]
Unfortunately no exact version numbers given but dwith the given date of the issue I could trace the problem back to 1.8.3 / 1.8.3.1 

With the version 1.7.6.1 we get:
![image](https://github.com/doxygen/doxygen/assets/5223533/148bb8ea-4de7-419b-aeb3-a0092a5a2438)

with version 1.8.3.1 we see:
![image](https://github.com/doxygen/doxygen/assets/5223533/1140d7c9-54b0-42d3-b200-90145812fb22)

Note the "code" sections in the detailed descriptions.


with the current (1.9.8) doxygen version we again have (actually already with 1.8.4):
![image](https://github.com/doxygen/doxygen/assets/5223533/17fe672a-b5c7-4d61-a069-652ebfd94ac5)


So I think the problem has been solved in the mean time.
