### ISSUE TITLE
multi paragraph user sections (Origin: bugzilla #693470)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5065]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.3.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2013-02-09 10:20:02 +0000, Liviu Ionescu wrote:

    I'm trying to use a user section (\par Description) where to enter the
    documentation that otherwise would go in the \details section, but I could
    not enter multi paragraph user sections, the <p> definition is not
    understood to be part of the user section, but part of the unnamed non
    indented section:
    
        /// \par Description
        /// first line
        /// <p>second line
     
    is translated into
    
        Description
            first line
    
        second line
    
    This behaviour seems somehow explained by the lack of section reordering
    reported in bug 693467, but I think that even if the reordering is not
    fixed, there should be a way to enter multi paragraph user sections.
    
    The current workaround I found was to use multiple \n lines
    
        /// \par Description
        /// first line
        /// \n\n
        /// second line
    
    but this translates into multiple <br> html lines, not a <p>, which is quite
    different.
    
    
    Liviu

On 2013-02-09 11:03:20 +0000, Liviu Ionescu wrote:

    I thought I can outsmart the parser and tried a syntax like
    
        /// \par Description
        /// first line<p>second line
    
    but even so the second line was displayed outside the user section :-(
    
    
    Liviu

On 2013-02-10 16:27:40 +0000, AndrÃ© Klapper wrote:

    *** Bug 693469 has been marked as a duplicate of this bug. ***

**Comment by albert-github** [comment]
In the issue there is already a workaround given.
Furthermore there are the possibilities:
- using an "empty" `\par` command
   ```
  /// \par Description
  /// first line
  /// \par
  /// second line
   ```
- using the `\parblock` command (available since doxygen version 1.8.6)
  ```
  /// \par Description
  /// \parblock
  /// first line
  ///
  /// second line
  /// \endparblock
  ```

So the problem is a combination of usage and solved in the mean time
