### ISSUE TITLE
The 'Examples:' section; bad/missing style and incorrect spelling (Origin: bugzilla #693515)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5068]
status NEW severity *minor* in component *general* for *---*
Reported in version *1.8.3.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2013-02-10 07:44:10 +0000, Liviu Ionescu wrote:

    I recently started using the \example command, and the functionality is
    fine, but the word 'Examples:' is positioned slightly to the right.
    
    Using the browser inspector revealed the following html
    <dl>
      <dt>
        <b>Examples: </b>
      </dt>
      <dd>...</dd>
    </dl>
    
    The default style for dl, as from the doxygen.css, is
    
    dl {
    padding: 0 0 0 10px;
    }
    
    The culprit is the 10px left padding.
    
    The workaround is to define a custom.css and set the left padding to 0px.
    
    However, I would suggest to add a style to this <div>, for example <div
    class="examples">, in order to make it configurable more specifically
    without affecting other page elements.
    
    Also, I would suggest to remove the terminating colon, to bring the aspect
    in line with the other sections, like Parameters, or Return values, that
    have no terminating colon.
    
    
    Liviu

On 2018-06-29 14:47:21 +0000, albert wrote:

    I've just pushed a proposed patch to github (pull request 781,
    https://github.com/doxygen/doxygen/pull/781).

**Comment by albert-github** [comment]
Code has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
