### ISSUE TITLE
__attribute__((unused)) not ignored, confuses the parser (Origin: bugzilla #693529)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5069]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.3.1-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2013-02-10 15:37:16 +0000, Liviu Ionescu wrote:

    If the GCC __attribute__((unused)) is used in method definitions, the parser
    is confused, and errors are issued on the stderr, although the program
    proceeds.
    
    A simple test to trigger the bug is below:
    
    ---------------------
    /// \brief Test
    
    class Test
    {
    public:
        /// \brief Constructor
        Test();
        /// \brief A better constructor
        Test(int argc, char* argv[]);
    }
    
    Test::Test()
    {
        ;
    }
    
    Test::Test(int argc __attribute__((unused)), char* argv[]
    __attribute__((unused)))
    {
        ;
    }
    ---------------------
    
    the configuration I uses is:
    
    ---------------------
    INPUT                  = .
    OUTPUT_DIRECTORY       = .
    ALWAYS_DETAILED_SEC    = YES
    INLINE_INHERITED_MEMB  = YES
    EXTRACT_PRIVATE        = YES
    EXTRACT_STATIC         = YES
    CASE_SENSE_NAMES       = YES
    SORT_MEMBERS_CTORS_1ST = YES
    SHOW_USED_FILES        = NO
    FILE_PATTERNS          = *.cpp
    RECURSIVE              = YES
    SOURCE_BROWSER         = YES
    INLINE_SOURCES         = YES
    HTML_DYNAMIC_SECTIONS  = YES
    GENERATE_TREEVIEW      = YES
    GENERATE_LATEX         = NO
    ENABLE_PREPROCESSING   = NO
    ---------------------
    
    the errors issued are:
    
    ---------------------
    Searching for member function documentation...
    /Users/ilg/My Files/MacBookPro Projects/Doxygen/tests/attribute/t.cpp:18:
    warning: no matching class member found for
      Test::Test(int argc(unused) __attribute__(unused), char *argv[]
    __attribute__(unused))
    Possible candidates:
      Test::Test()
      Test::Test(int argc, char *argv[])
    
    Building page list...
    ---------------------
    
    I ran a 'grep -r __attribute__' and it looks like the parser is not aware of
    the GNU __attribute__ extensions, which explains the behaviour.
    
    
    I suggest you add the __attribute__((...)) to the recognised syntax; as
    functionality.. I don't know, my first thought was to silently ignore them,
    but probably the GNU manuals should be checked.
    
    I also ran a 'grep -r __asm__' and it also looks like the parser is not
    aware of the GNU __asm__ extensions; I would suggest to add it too, and save
    a Bugzilla ticket ;-)
    
    
    Liviu

On 2013-02-10 16:18:11 +0000, Dimitri van Heesch wrote:

    Doxygen does indeed not support al sorts of compiler specific extensions
    (people often wrap these in macros to make their code portable, so it
    wouldn't help much if doxygen would support these).
    
    See here how to deal with __attribute__: 
    http://www.doxygen.org/manual/preprocessing.html

On 2013-02-10 17:11:16 +0000, Liviu Ionescu wrote:

    > people often wrap these in macros
    
    modern C++ strongly advocates against using macros, and I fully agree with
    this.
    
    my projects are GNU/LLVM only, and I do not think it is reasonably to alter
    my code only to keep Doxygen happy, especially considering that I currently
    run it with preprocessing disabled.
    
    > ... not support all sorts of compiler specific extensions
    
    well, right, probably supporting ALL possible compiler extensions would not
    be realistic, but, as the mostly used compiler, I think that supporting the
    GNU extensions would be a plus for Doxygen.
    
    to better understand your position, are you against extending the Doxygen
    parser with GNU extensions, or you simply do not have the resources to
    implement them?
    
    in your opinion, how difficult would be to expand the parser to accept the
    __attribute__ and __asm__ extensions? If I provide you a patch, will you
    consider including it in Doxygen?
    
    can this be reclassified as a feature request?
    
    
    regards,
    
    Liviu

On 2013-02-10 19:37:18 +0000, Dimitri van Heesch wrote:

    Using doxygen's built-in C preprocessor you can already make doxygen remove
    the __attribute__ before the parser sees it, so doxygen has "support" for
    these, with a bit of work from the user.

On 2013-02-10 20:04:31 +0000, Liviu Ionescu wrote:

    I considered this solution, and selectively controlling macro expansion with
    
      MACRO_EXPANSION = YES 
      EXPAND_ONLY_PREDEF = YES 
    
    are nice options to have, but I would also need an option to selectively
    enable/disable the #if/#ifdef processing.
    
    I'm currently working on a large component library, with multiple different
    implementations of various classes. Each source file has a specific
    #if/#endif enabling/disabling the given component, based on some application
    specific #defines (in fact dynamically generated from a Command Description
    Language that manages dependences)
    
    So, my source files look line
    
    #if defined(OS_INCLUDE_PORTABLE_INFRA_TESTSUITE)
    ...
    #endif
    
    If I run the source tree through Doxygen with preprocessing enabled, there
    is practically no output, since without specific #defines all sources are
    simply skipped.
    
    To use the built-in C preprocessor only to remove the __attribute__, the
    disadvantage is that I need to manually define a PREDEFINED line for each
    new component added to the library, which will probably lead to hundreds of
    such definitions.
    
    I appreciate your suggestions, is there any other idea on how to handle this
    quite large application?
    
    Liviu

On 2013-02-11 09:02:49 +0000, Liviu Ionescu wrote:

    > doxygen has "support" for these, with a bit of work from the user.
    
    well, since manually maintaining the list of all possible definitions used
    to include my components is just not maintainable, I experimented with an
    workaround:
    
    #if defined(OS_INCLUDE_PORTABLE_INFRA_TESTSUITE) || defined(__DOXYGEN__)
    ...
    #endif
    
    plus adding a single definition to PREDEFINED, instead of hundreds.
    
    It seems functional, but I still wouldn't consider it 'a bit of work from
    the user'. :-(
    
    Doxygen is a nice tool, but in this case the lack of a small feature like
    ignoring a quite common compiler '__attribute__((..))' definition during
    parsing can be compensated only by manually adding patches to hundreds of
    files.
    
    Regards,
    
    Liviu

On 2013-02-11 19:17:48 +0000, Dimitri van Heesch wrote:

    If you cannot use doxygen's preprocessor, then you can still write an input
    filter (see INPUT_FILTER in the config file) to remove the __attribute__(x)
    stuff on the fly.
    
    I do find it weird that you do not want any macros in your code, and at the
    same time have everything in conditional sections. I'm sure that's also not
    something modern C++ advocates either ;-)

On 2013-02-11 20:01:27 +0000, Liviu Ionescu wrote:

    > I do find it weird that you ... have everything in conditional sections.
    I'm sure that's also not
    > something modern C++ advocates either
    
    You are perfectly right, I know that this breaks the MISRA C++ rules, and I
    am concerned about this, but currently could not find a better solution.
    
    Since my project is multiplatform, and the sources for all platforms reside
    in the same component repository, I need to use the preprocessor to avoid
    useless/illegal inclusions of files related to one platform in the build
    specific for another platform, similarly to using the preprocessor to avoid
    multiple inclusions of the same header file.
    
    After some more experimenting it seems that running a multiplatform project
    through Doxygen is even more complicated, since all platform specific is
    handled with constructs like
    
    #if defined(INCLUDE_PLATFORM1)
    #include "platform1.h" 
    #elif  defined(INCLUDE_PLATFORM2)
    #include "platform2.h" 
    #else
    #error "no implementation available"
    #endif 
    
    will probably need some changes on the #else branch to include some default
    definitions just to keep Doxygen as much as possible in line with the
    reality.
    
    From the build point of view, some tricks can be imagined with the list of
    the folders searched for the include files, but in this case things are even
    worse, since Doxygen will encounter classes with identical names in
    different places...
    
    things are difficult anyway, and adding Doxygen to the game makes things
    even more complicated... (I know it isn't your fault, I'm just giving you an
    example of a complex configuration)
    
    > then you can still write an input filter
    
    ah, ok, great tip, thank you.
    
    
    Liviu

On 2013-02-11 23:11:23 +0000, Liviu Ionescu wrote:

    >  built-in C preprocessor you can already make doxygen remove the
    > __attribute__
    
    I did some tests and PREDEFINED = __attribute__()= does not work properly,
    the following lines:
    
        TestSuiteImplementation::TestSuiteImplementation(
            int argc __attribute__((unused)), char* argv[]
    __attribute__((unused)))
    
    triggered the following error
    
    /Users/ilg/My Files/MacBookPro Projects/uOS/micro-os-plus-
    se.git/packages/portable/infra/src/TestSuiteImplementation.cpp:39: warning:
    no uniquely matching class member found for
      os::infra::TestSuiteImplementation::TestSuiteImplementation(int argc)
    
    Probably the regular expression used is too greedy, and 'eats' the second
    parameter.
    
    > you can still write an input
    > filter (see INPUT_FILTER in the config file) to remove the
    __attribute__(x)
    > stuff on the fly.
    
    the following definition seems to work properly for the above lines:
    
    INPUT_FILTER           = "perl -p -e 's/__attribute__\s*[(][(].*?[)][)]//g'"
    
    SInce this is not exactly trivial for those not familiar with regular
    expressions, I would add this as a sample in the manual.
    
    
    Liviu

On 2013-02-11 23:44:18 +0000, Kevin McBride wrote:

    Adding "documentation" keyword per comment # 8.

**Comment by albert-github** [comment]
The `PREDEFINED = __attribute__()=` indeed does not give the expected result but either `PREDEFINED = __attribute__(x)=` or `PREDEFINED = __attribute__(...)=` should be used.

I don't think that there are issues that are not answered I thin this issue can be closed as usage (I don't see any need for some documentation that is not yet present).
