### ISSUE TITLE
copybrief breaks HTML lists (Origin: bugzilla #693585)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5071]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.3.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2013-02-11 12:41:48 +0000, Antoine Pierlot-Garcin wrote:

    The following source:
    
    -------------
    /**
     * @brief foo brief
     */
    void foo(void);
    
    /**
     * @brief bar brief
     */
    void bar(void);
    
    /**
     * @page pipo Pipo
     *
     * List:
     *   - foo : @copybrief foo
     *   - bar : @copybrief bar
     */
    -------------
    
    gives the HTML output (snippet):
    
    -------------
    <div class="textblock"><p>List:</p>
    <ul>
    <li>foo :</li>
    </ul>
    <p>foo brief </p>
    <ul>
    <li>bar :</li>
    </ul>
    <p>bar brief </p>
    </div>
    -------------
    
    Each brief is copied outside of the list. Instead of having 1 list of 2
    elements (each element containing 1 brief description), we get 2 lists of 1
    element, with the brief description below.
    
    This doesn't happen with 1.8.2.

On 2013-02-11 12:48:10 +0000, Antoine Pierlot-Garcin wrote:

    Precision: I'm using 1.8.3.1 with the patch from
    https://bugzilla.gnome.org/show_bug.cgi?id=692320.

On 2013-02-14 22:14:05 +0000, Josh Klontz wrote:

    Experiencing the same problem. Forced me to revert back to 1.8.2. A fix
    would be greatly appreciated!

**Comment by albert-github** [comment]
With version 1.8.2 I do see the list to be properly shown
With 1.8.3.1 the list is messed up

With version 1.8.15 everything looks OK to me again (same output as 1.8.2).

I think the problem has been solved in the mean time.
