### ISSUE TITLE
Doxygen uses too many threads to run 'dot': "Problems running dot: exit code=-1" (Origin: bugzilla #693619)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5073]
status NEW severity *minor* in component *general* for *---*
Reported in version *1.8.0* on platform *Other*
Assigned to: Dimitri van Heesch

On 2013-02-11 20:35:59 +0000, John Berendsen wrote:

    I use Doxygen to document a library of approximately 30 classes.  Doxygen
    uses multi-threading to run dot faster.  However, it seems to sometimes
    think it can use a very large number of threads, and that backfires:
    
    finalizing index lists...
    Generating dot graphs using 25 parallel threads...
    Problems running dot: exit code=-1,
    command='/home/utils/graphviz-2.18/bin/dot', arguments='...'
    Problems running dot: exit code=-1,
    command='/home/utils/graphviz-2.18/bin/dot', arguments='...'
    <many similar failures>
    
    I can work around the problem by limiting Doxygen to 4 threads with the
    DOT_NUM_THREADS configuration variable.
    
    However, this default behavior of sometimes picking a large number of
    threads can be irritating to folks not taking the time to figure out what is
    going on...

**Comment by albert-github** [comment]
In doxygen the number of threads can be set explicitly (i.e. a value between 1 and 32 for the setting `DOT_NUM_THREADS`) or implicitly using 0 for `DOT_NUM_THREADS`. In the later case the number of processors is set to the number of available processors plus 1, nowadays this is determined by means of `std::thread::hardware_concurrency()` (in the past by means of: `QThread::idealThreadCount()`). The value is the number of 'logical processors".
In the mentioned case there probably will have been 12 hyperthreaded processors resulting in the count of 12*2+1=25 parallel threads. 

I don't think this is a doxygen problem but usage.
