### ISSUE TITLE
@copydoc not working properly (Origin: bugzilla #693776)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5074]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.3.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[Copydoc Version Comparison.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug693776_236024_Copydoc Version Comparison.zip/download/download)_ (ID 236024)

On 2013-02-14 09:52:13 +0000, Fabrizio Da Ros wrote:

    Created attachment 236024
    @copydoc results between 3 Doxygen versions 1.7.6.1, 1.8.3, 1.8.3.1
    
    Hi,
    
    The version 1.8.3.1 does not fix the @copydoc issue submitted in version
    1.8.3.
    It truncates the html page, while the version 1.8.3 was only missing the
    paragraph separattion.
    The best (and correct) result is to be found in version 1.7.6.1.
    
    I have packed up and attached an example with input and HTML pages generated
    by Doxygen versions
    - 1.7.6.1
    - 1.8.3
    - 1.8.3.1
    To make easy comparison between results.
    
    version 1.7.6.1 index.html page is the expected result.
    
    
    Thanks!
    Fabrizio.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #8982

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.3.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
