### ISSUE TITLE
Comment beginning with "// Author" suppresses doc generation (Origin: bugzilla #694218)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5082]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.8.3.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2013-02-19 22:39:13 +0000, Doug Kramer wrote:

    PROBLEM:
    When I run doxygen on Objective-C source code with the following code block,
    no documentation is generated for that method -- no signature, parameters or
    doc comment.
    
    CAUSE:
    I tracked the cause down to this:
    A comment line that starts with the string "// Author" prevents the entire
    documentation for that method from being generated
    
    SOLUTION:
    Add a word before "Author", such as "// The authorization has finished"
    enables the method's documentation to be generated
    
    -------------------------------------------------------------
    // A protocol implemented by the client.
    @protocol MyClassDelegate
    
    // Authorization is finished
    - (void)finishedWithAuth:(OAuth2Authentication *)auth;
    
    @end
    --------------------------------------------------------------
    
    $ doxygen --version
    1.8.3.1

**Comment by albert-github** [comment]
Quite unclear what is meant here as in the given example there are no doxygen comments at all also there is no example of the used settings nor of how the good code would look like.

Problem looks like to be incomplete
