### ISSUE TITLE
[PATCH] Improved LaTeX output (Origin: bugzilla #694760)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5101]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.8.3.1-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[latex_output.patch](https://sourceforge.net/projects/doxygen/files/attachments/bug694760_237466_latex_output.patch/download/download)_ (ID 237466)

On 2013-02-26 18:57:14 +0000, Markus Geimer wrote:

    Created attachment 237466
    Patch implementing the described fixes/enhancements
    
    Please find a patch against 1.8.3.1-20130209 (i.e., SVN r841) attached which
    addresses a number of issues in doxygen's LaTeX output generation. In
    particular, these are:
    
     - Fix page number/hyperlink of index in ToC (off by one)
    
     - Fix page numbers in index (requires an additional run of makeindex &
    LaTeX)
    
     - Add bibliography to ToC
    
     - Remove redundancies and obsolete commands/packages
    
     - The header file now loads all packages required by the LaTeX output
    generator and sets up the general appearance of the document (i.e., page
    layout, headers, footers, fonts, etc.). This allows, for example, to change
    the document font via a custom header w/o also providing a custom style file
    (where the use of Helvetica was pretty much hard-coded).
    
     - The style file only loads packages that are required by itself and
    defines the appearance of doxygen-specific sections (using the various
    'Doxy...' commands).
    
     - The style file can now be written in one batch, i.e., the calling source
    code could be simplified a bit.
    
    The generated output is visually almost identical to before, i.e., the
    average user shouldn't notice any difference. Only people using custom
    headers or style files might need to slightly adjust their files (since some
    stuff was rearranged), but they should already be aware of potential
    changes.

**Comment by albert-github** [comment]
As far as I can see from the updates for version 1.8.3.1-20130324 the patch has been integrated in this version.
