### ISSUE TITLE
Incorrect recursive call of chain of \copydoc detected (Origin: bugzilla #695229)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5112]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.3.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[macro.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug695229_238144_macro.zip/download/download)_ (ID 238144)

On 2013-03-05 16:52:54 +0000, Travis Vitek wrote:

    Created attachment 238144
    Test case
    
    The attached test case used to work fine with prior versions of doxygen
    (last tested 1.7.4), but it now produces a warning about a recursive call
    chain.
    
    Steps to reproduce:
    - extract files from the attached zip archive
    - run doxygen using the attached doxygen configuration file as `doxygen
    Doxyfile'
    
    Actual results:
    You will see a warning message relating to recursive \copydoc.
    
    
    Expected results:
    I would expect that there to be no warning.
    
    Does this happen every time?
    Yes
    
    Other information:
    This issue appears to be similar to 463990 and 683595, but is also
    sufficiently differently that I've decided it is more appropriate to file a
    separate bug.

**Comment by albert-github** [comment]
With version 1.7.4 I don't see the warning
With version 1.8.3.1 I do see the recursive warning
With version1.8.15  I don't see the warning.

I think the problem has been solved in the mean time.
