### ISSUE TITLE
Proposed CSS changes for better default formatting (Origin: bugzilla #695263)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5113]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.8.3.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2013-03-06 03:02:06 +0000, Matt Busche wrote:

    I have two proposed changes.  (Maybe I should have created two enhancement
    requests.)
    
    ONE:
    
    For each method description found in section Constructor & Destructor
    Documentation there is a gray line graphic separating the introductory
    method declaration and the description detail.  This gray line is FAT
    compared to the 1-point-thin rounded bounding box that surrounds the entry
    as a whole.  To my eyes, the gray line has greater visual significance than
    the surrounding box, almost giving the appearance that the declaration goes
    with description of the previous method.  (Actually since there's a double
    line between entries, the whole thing just looks visually confusing to my
    eyes.)
    
    I found that by fattening up the entry bounding box from 1 to 3 points
    things looked much better to me:
    
    .memproto, dl.reflist dt {
            border-top: 3px solid #A8B8D9;
            border-left: 3px solid #A8B8D9;
            border-right: 3px solid #A8B8D9;
            ....
    
    and
    
    .memdoc, dl.reflist dd {
            border-bottom: 3px solid #A8B8D9;
            border-left: 3px solid #A8B8D9;
            border-right: 3px solid #A8B8D9;
            ....
    
    I suppose another way to go would be to reduce the thickness of the gray
    line to a single point.  I haven't tried that.
    
    TWO:
    
    In the Exceptions section of my method descriptions, some of the exception
    descriptions (which appear to the right of the exception type) span multiple
    lines.  The exception type on the left is displaying with centered vertical
    alignment which looks weird (especially when there are multiple exceptions
    listed).  I modified .paramname to have vertical-align: top;
    
    .paramname {
        color: # 602020;
        white-space: nowrap;
        vertical-align: top;
    }
    
    This makes things look better to me, though I don't know if this same css
    class is used for other purposes where this change might be inappropriate.

**Comment by albert-github** [comment]
The problem here is that what is nice for one person is not nice for another. 
The user can redefine the current doxygen css settings by means of his own stylesheet that redefines some of the properties that better fit his needs. The extra stylesheet can be added by means of the `EXTRA_HTML_STYLESHEET` setting.

I think this problem is a mater of taste and can be easily be "corrected", defining this issue as usage.
