### ISSUE TITLE
Inline HTML containing a single apostrophe (') appears to interfere with Doxygen parsing. (Origin: bugzilla #695337)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5117]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[TestClass.class.php](https://sourceforge.net/projects/doxygen/files/attachments/bug695337_238268_TestClass.class.php/download/download)_ (ID 238268)

On 2013-03-07 01:53:16 +0000, tarnjp@yahoo.co.jp wrote:

    When running Doxygen with the attached file in the Doxygen input path, the
    generated documentation does not include the class defined therein. Remove
    the apostrophe, and the class shows up without flaw.
    
    It doesn't seem to matter where the apostropge occurs within the region of
    inline HTML.

On 2013-03-07 01:56:15 +0000, tarnjp@yahoo.co.jp wrote:

    Created attachment 238268
    This class is not included in the generated documentation.

On 2013-03-07 01:59:44 +0000, tarnjp@yahoo.co.jp wrote:

    I neglected to mention in the original description that I encountered this
    problem whilst producing documentation for a number of PHP classes.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6536

**Comment by albert-github** [comment]
Code has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
