### ISSUE TITLE
C++ confuses between static function and global variable (Origin: bugzilla #697854)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5141]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.3.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[case.tar.gz](https://sourceforge.net/projects/doxygen/files/attachments/bug697854_241327_case.tar.gz/download/download)_ (ID 241327)

On 2013-04-12 08:56:50 +0000, Ruey-Shi Rau wrote:

    Created attachment 241327
    Testcase refered in description
    
    test.cxx:
    
    static void test()
    {
        for (int i = 0; i < 100; ++i)
            continue;
        return;
    }
    
    int main(void)
    {
        test();
        return 0;
    }
    
    test2.cxx:
    bool test = false;
    
    Doxyfile: Turn on
    EXTRACT_ALL            = YES
    EXTRACT_STATIC         = YES
    REFERENCED_BY_RELATION = YES
    REFERENCES_RELATION    = YES
    
    Note that in test.cxx we don't declare "extern bool test;". Thus, main()
    refers to static function test() instead of global variable "bool test".
    However, the generated HTML document claims that main() references variable
    "test" but not function "test()".

**Comment by albert-github** [comment]
With the 1.8.3.1 version we see, as indicated:
![image](https://github.com/doxygen/doxygen/assets/5223533/48be8c98-c1c5-4836-87dc-da38c09ae5ed)

With the current (1.9.8) version we see the correct behavior and links:
![image](https://github.com/doxygen/doxygen/assets/5223533/8cafd907-40b0-4fd3-a320-4a497357fcbc)


I think the problem has been solved in the mean time.
