### ISSUE TITLE
Add GENERATE_DASH_DOCSET command (Origin: bugzilla #698110)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5146]
status NEW severity *enhancement* in component *build* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2013-04-16 06:54:24 +0000, Bogdan Popescu wrote:

    Currently, to generate a Dash-optimised (http://kapeli.com/dash) docset, one
    must use the following
    options:
    
    GENERATE_DOCSET = YES
    SEARCHENGINE = NO
    DISABLE_INDEX = YES
    GENERATE_TREEVIEW = NO
    
    It would be nice if you could add a GENERATE_DASH_DOCSET command, which when
    set to YES would overwrite the values for the options I listed above, and
    when set to NO would have no effect.

**Comment by albert-github** [comment]
It is a bit unclear what the difference between a normal docset and a Dash-optimised docset is.
Seen the instructions it is easy to adjust the settings and an extra setting doesn't bring a lot  (just an extra setting), when really necessary a better solution would be the give the `GENERATE_DOCSET` the values:
- `NO` don't generate docsets
- `YES` generate the docsets according to the doxygen settings
- `DASH`  generate the docsets according to the doxygen settings but overrule settings as mentioned in question.

Currently I think we should consider this as won't fix.
