### ISSUE TITLE
HIDE_SCOPE_NAMES does not hide namespace scope for functions within it (Origin: bugzilla #698167)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5147]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.3.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[scopeTest.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug698167_241694_scopeTest.zip/download/download)_ (ID 241694)

On 2013-04-16 22:26:07 +0000, Charlie wrote:

    Created attachment 241694
    example input file and config file to reproduce the issue
    
    When setting HIDE_SCOPE_NAMES to YES, I expected that a function within a
    namespace would have its scope hidden.  It does not.
    
    I attached an example with a config file.  However here is the even shorter
    version of the "code":
    
    namespace Namespace1 {
        functionInNamespace();
    };
    
    On the namespace page, it will show the function as
    
    Namespace1::functionInNamespace even if you have set HIDE_SCOPE_NAMES to
    YES.

On 2017-10-14 20:46:51 +0000, Yannick DuchÃªne wrote:

    I see the same issue with Python source using Doxygen 1.8.14-GIT.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #9270

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.4.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
