### ISSUE TITLE
C++11 keyword alignas not supported (Origin: bugzilla #698223)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5149]
status RESOLVED severity *normal* in component *general* for *---*
Reported in version *1.8.3.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[Bug 698223.zip](http://ftp.stack.nl/pub/users/dimitri/bugzilla/attachments//bug698223_241787_Bug 698223.zip)_ (ID 241787)

On 2013-04-17 18:27:50 +0000, w.shane.grant@gmail.com wrote:

> C++11 introduces a new alignment specifier, alignas (http://en.cppreference.com/w/cpp/language/alignas), that Doxygen seems to not support yet.
> 
> If a class or struct is declared with alignas, the specifier will appear between "struct/class" and the name of the struct or class, e.g.:
> 
> struct alignas(16) MyStruct {};
> 
> Doxygen will not interpret this as a struct or class and fail to produce any documentation.

On 2013-04-18 01:18:43 +0000, Kevin McBride wrote:

> Created attachment 241787
> Testcase

On 2013-04-18 01:20:51 +0000, Kevin McBride wrote:

> Thank you for taking time to report this bug.  I have confirmed the bug as shown in my testcase.  Hopefully, a doxygen developer will be willing to take on the task of implementing the C++11 extension alignas().

On 2013-05-01 19:52:02 +0000, Dimitri van Heesch wrote:

> Confirmed. Should be fixed in the next subversion update.

On 2013-05-19 12:35:43 +0000, Dimitri van Heesch wrote:

> This bug was previously marked ASSIGNED, which means it should be fixed in
> doxygen version 1.8.4. Please verify if this is indeed the case. Reopen the
> bug if you think it is not fixed and please include any additional information
> that you think can be relevant.

**Comment by cppljevans** [comment]
doxygen on the following code:
`
        static constexpr size_t
      Size = std::max( { sizeof( T)...})
        ;
        alignas(T...) std::byte
      buffer[Size]{}
      ;
`
also does not show the alignas(T...) in the .html file.

**Comment by albert-github** [comment]
Unfortunately you didn't show the used settings (especially in this case `EXTRACT_STATIC`) seen the time elpased time since this issue was solved: please create a new issue with the following information:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem?
   Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).
- Please also specify the full doxygen version used (doxygen -v).

**Comment by cppljevans** [comment]
larry@larry-Precision-3581:~/prog_dev/c++/standard/construct_at$ doxygen -v
1.9.8
larry@larry-Precision-3581:~/prog_dev/c++/standard/construct_at$ 

[test_doxygen_alignas.tar.gz](https://github.com/user-attachments/files/22492488/test_doxygen_alignas.tar.gz)

**Comment by albert-github** [comment]
@cppljevans 

I see in the file html when running  doxygen 1.14.0 I see:

<img width="660" height="108" alt="Image" src="https://github.com/user-attachments/assets/4fbd4878-5864-4693-bba1-bc721ae1d732" />

- where / what do you miss in respect to the alignas?

**Comment by cppljevans** [comment]
> [@cppljevans](https://github.com/cppljevans)
> 
> I see in the file html when running doxygen 1.14.0 I see:
> <img alt="Image" width="660" height="108" src="https://private-user-images.githubusercontent.com/5223533/492903793-4fbd4878-5864-4693-bba1-bc721ae1d732.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTg2NDUxNTMsIm5iZiI6MTc1ODY0NDg1MywicGF0aCI6Ii81MjIzNTMzLzQ5MjkwMzc5My00ZmJkNDg3OC01ODY0LTQ2OTMtYmJhMS1iYzcyMWFlMWQ3MzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDkyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA5MjNUMTYyNzMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWRiZWU3YTQxYjBlOTc0MjVlM2FhOWU5MmE2MjFjMjU3ODQzMTY3OTE3NGMzYWZjMDBlMmMwMDc4MTdkODhlZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.8m4bZ1HBUn3X11pthuJMmUUScp7f8dJfvPZHRF0njkg">
> 
>     * where / what do you miss in respect to the alignas?

I don't see alignas(T...)  in the .html file:

  file:///home/larry/prog_dev/c++/standard/construct_at/html/structtest.html

which just shows, in my firefox browser:
```c++
  static Public Attributes
    static char 	c {'a'}
 	show that doxygen doesn't put alignas(T...) in the generated .html file. 
```
showing no **alignas(T...)** whereas the source code has:

```c++ 
  alignas(T...) static char c{'a'}
  /**<@brief
   * show that doxygen doesn't put alignas(T...) in the generated .html file.
   */
   ;

```

**Comment by albert-github** [comment]
With the current doxygen version 1.15.0 I see in the brief description:

<img width="405" height="155" alt="Image" src="https://github.com/user-attachments/assets/1ee7cdb1-7e7d-4c62-a981-a4da992a7826" />

So no mentioning of `T` or `alignas`.

In the detailed description (using `ALWAYS_DETAILED_SEC = YES`) I see:

<img width="389" height="202" alt="Image" src="https://github.com/user-attachments/assets/1ec2333f-8ea7-435e-87de-cd47d8ed8d19" />

So `T` is mentioned but not `alignas`.

@doxygen is this correct behavior or ...
