### ISSUE TITLE
Normal paragraphs incorrectly processed as markdown code blocks when \return used (Origin: bugzilla #700370)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5173]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.3.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[Doxyfile](https://sourceforge.net/projects/doxygen/files/attachments/bug700370_244284_Doxyfile/download/download)_ (ID 244284)
- _[DSHAlertItem.h](https://sourceforge.net/projects/doxygen/files/attachments/bug700370_244285_DSHAlertItem.h/download/download)_ (ID 244285)

On 2013-05-15 08:46:50 +0000, vince.negri@gmail.com wrote:

    Created attachment 244284
    Doxyfile
    
    See attached specimen Doxyfile and header file.
    
    When run through, the ordinary description text is treated as a code block
    and shown as such in the HTML documentation for the class.
    
    Removing the "\return" line, or removing the overall indent of the comment
    block (so it is hard against the left hand side) stops the problem
    occurring.
    
    It is as if the \return line somehow screws up the logic wherein the indent
    of the text is interpreted relative to the previous paragraph, and instead
    the absolute indent is being used.

On 2013-05-15 08:47:21 +0000, vince.negri@gmail.com wrote:

    Created attachment 244285
    Header file for use with Doxyfile

**Comment by albert-github** [comment]
When running wit the doxygen 1.8.3.1 version we get  strange results like:
![image](https://github.com/doxygen/doxygen/assets/5223533/f322bdb5-eef5-435e-9caf-59ab97a01235)

When running with the current (1.9.8) doxygen version the output is:
![image](https://github.com/doxygen/doxygen/assets/5223533/df1d78f9-b71e-4cc3-969f-095c140ff6ae)

So I think the problem has been solved in the mean time.
