### ISSUE TITLE
<tt> blocks replace multiple dashes with a simple &ndash; entity (Origin: bugzilla #700645)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5183]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.4* on platform *Other*
Assigned to: Dimitri van Heesch

On 2013-05-19 17:28:46 +0000, Dean Camera wrote:

    When multiple dashes are placed next to one-another inside a verbatim-like
    element, only a single &ndash; is generated in the output. Since <tt> blocks
    are primarily for small code snippets (or, rather, computer output
    fragments) this can cause user confusion.
    
    Test case:
    
    /** \mainpage
     *
     * Use the <tt>--test-flag</tt> flag.
     */
    
    Output:
    
    <div class="textblock"><p>Use the <code>&ndash;test-flag</code> flag. </p>

On 2013-05-20 17:57:09 +0000, Dimitri van Heesch wrote:

    If you have MARKDOWN_SUPPORT enabled you can do
    
    /** \mainpage
     *
     * Use the `--test-flag` flag.
     */
    
    to get the desired effect.

**Comment by albert-github** [comment]
Doxygen is interpreting the content of the `<tt>` tags and hence the markdown processing changes the 2 dashes into a `&ndash;`
As written in the comment a solution is to use backticks. 

I think the issue is by design and usage.
