### ISSUE TITLE
Unable to build refman.pdf from FreeBSD port of doxygen (Origin: bugzilla #700858)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5193]
status NEEDINFO severity *major* in component *build* for *---*
Reported in version *1.8.6* on platform *Other*
Assigned to: Dimitri van Heesch

On 2013-05-22 19:51:55 +0000, Naram Qashat wrote:

    Hi, I'm the maintainer of the FreeBSD port of doxygen, and I'm attempting to
    update the port to 1.8.4. When it tries to build the PDF docs, LaTeX stops
    at a prompt when trying to build refman.pdf. I get the following:
    
    Chapter 26.
    (./langhowto.tex
    
    ! LaTeX Error: Environment longtable undefined.
    
    See the LaTeX manual or LaTeX Companion for explanation.
    Type  H <return>  for immediate help.
     ...
    
    l.13 \begin{longtable}
                          {|l|l|l|l|}
    
    As far as I can tell, none of the changes that have been made to the files
    through the FreeBSD port are affecting this.
    
    FreeBSD now does have access to TeXLive, but I currently still have the
    teTeX version of LaTeX installed, and I'm sure not everyone will have
    switched to TeXLive yet, so I would like to see about fixing this to work
    with the old version of LaTeX that FreeBSD still offers.
    
    This is my LaTeX version:
    
    pdfeTeX 3.141592-1.21a-2.2 (Web2C 7.5.4)
    kpathsea version 3.5.4
    Copyright (C) 1997-2004 Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
    Kpathsea is copyright (C) 1997-2004 Free Software Foundation, Inc.
    There is NO warranty.  Redistribution of this software is
    covered by the terms of both the pdfeTeX copyright and
    the GNU General Public License.
    For more information about these matters, see the files
    named COPYING and the pdfeTeX source.
    Primary author of pdfeTeX: Peter Breitenlohner (eTeX)/Han The Thanh
    (pdfTeX).
    Kpathsea written by Karl Berry and others.

On 2013-05-24 20:03:44 +0000, Dimitri van Heesch wrote:

    I have too little information to analyse the problem. Some questions:
    - Is the longtable package installed? 
    - Did it work before 1.8.4? 
    - Is there a \RequirePackage{longtable} in your doxygen.sty?
    - Can you attach the full doxygen_manual.log?
    - What changes were made for the FreeBSD port?

On 2013-05-27 17:31:41 +0000, Naram Qashat wrote:

    Sorry it took me so long to get back to you on this.
    
    It appears that longtable was not installed. However, I installed the
    FreeBSD port print/latex-ltablex, which says it contains the features of the
    tabularx and longtable packages, but it still does not build.
    
    This did work before 1.8.4.
    
    doxygen.sty does contain \RequirePackage{longtable}, although it did not
    complain about until the place I mentioned above.
    
    My build folder does not contain a doxygen_manual.log file to attach. :(
    
    As it stands right now, the current changes were made for the FreeBSD port:
    * Examples are not being build when docs are being build.
    * Paths for QT4 utilities are corrected as they are named differently under
    FreeBSD (such as qmake is actually qmake-qt4).
    * Uses the system's MD5 implementation instead of the one provided with
    doxygen. (This was done before I took over maintenance of the port, and has
    not negatively affected how it operates.)
    * One instance of Q_UINT32 was replaced with uintptr_t to prevent a warning,
    I believe. I forget the exact reason for this one, I'd have to look at the
    previous commits to the FreeBSD ports tree.

On 2014-03-05 12:06:56 +0000, albert wrote:

    You wrote:
    It appears that longtable was not installed. However, I installed the
    FreeBSD
    port print/latex-ltablex, which says it contains the features of the
    tabularx
    and longtable packages, but it still does not build.
    
    I'm not a LaTeX expert, but is the package longtable available or is just
    similar functionality available in package print/latex-ltablex?

On 2014-03-05 12:17:18 +0000, Naram Qashat wrote:

    As far as I can tell, the print/latex-ltablex package uses tabularx but
    includes longtable as one of it's required packages. It's odd that it says
    longtable doesn't exist when I do have it in /usr/local/share/texmf-
    dist/tex/latex/tools/longtable.sty, which is provided by the print/teTeX-
    texmf package.
    
    I had tried to add \usepackage{longtable} after \RequirePacakge{longtable}
    in doxygen.sty, but that didn't help either. I don't use LaTeX myself, so I
    don't know what the issue is.
    
    Although I currently have teTeX installed, I had also tried this at one
    point with TeXLive as well, back when I was trying to compile 1.8.4.
    
    Although possibly unrelated, regarding the changes made for the FreeBSD
    port, I've temporarily removed the patches that stop examples from being
    built and that replaces that instance of Q_UINT32. The other changes are
    still being done.

On 2014-06-14 14:15:27 +0000, Kurt Jaeger wrote:

    See
    
    https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=190943
    
    for some patches that allowed refman.pdf to build on FreeBSD for the
    port devel/doxygen in version 1.8.7.
    
    While not perfect (it does not really indent to the level the
    chapter 28 (perl_mod_tree) requests, it builds and the chapter
    can be read.
    
    If Naram approves, this bug can be closed.

On 2014-06-14 17:25:56 +0000, Naram Qashat wrote:

    I'm fine with closing the bug, although on the other hand, I would like to
    find a more accurate solution to the problem. Having the port build is more
    important, though.

**Comment by albert-github** [comment]
Seen the last comment and the fact that there are no further problems reported regarding this problem, the time elapsed. I think it is save to set this issue to solved in the mean time.
