### ISSUE TITLE
Include code from source being parsed (Origin: bugzilla #701783)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5202]
status NEW severity *enhancement* in component *documentation* for *---*
Reported in version *1.8.4* on platform *Other*
Assigned to: Dimitri van Heesch

On 2013-06-07 11:57:13 +0000, geoff@telesiscomputing.com.au wrote:

    I've been documenting some testing functions and the truth is that in most
    cases there is little to say that isn't said clearer by the source code
    itself.  And, besides which, often the test functions themselves contain
    code that is useful as examples.  Since I am linking to test cases from
    tested member functions for my own reference, it would be convenient if the
    documentation was able to show selected pieces of the code - both as
    explanation and as possible examples.
    
    Probably easiest if I show you what I mean.  Something like this:
    
    /*! \brief Confirm that AClass::member does what it should. */
    void my_test_case_for_member()
    {
        //! \includecode
        AClass x;
        if (x.member(1, 2, 3) != 6)
            report_error();
        //! \endincludecode
    }
    
    Could produce documentation like:
    
        Confirm that AClass::member does what it should.
        +---------------------------------------------+
        |  AClass x;                                  |
        |  if (x.member(1, 2, 3) != 6)                |
        |      report_error();                        |
        +---------------------------------------------+
    
    Where the box is just a normal code example box.  Or to phrase this another
    way, the above would be the equivalent of this:
    
    /*! \brief Confirm that AClass::member does what it should. */
    void my_test_case_for_member()
    {
        //! \code
        //! AClass x;
        //! if (x.member(1, 2, 3) != 6)
        //!     report_error();
        //! \endcode
        AClass x;
        if (x.member(1, 2, 3) != 6)
            report_error();
    }
    
    without having to duplicate the code.
    
    I did try doing clever things with \dontinclude and similar features, but
    there are issues with where some of these are available (apparently just
    pages not code entities), and besides which they're messy compared something
    like the \includecode example above.

On 2013-06-08 19:11:08 +0000, Dimitri van Heesch wrote:

    Setting INLINE_SOURCES to YES will already do this at a global level:
    http://www.doxygen.org/manual/config.html#cfg_inline_sources

On 2013-06-08 21:37:38 +0000, geoff@telesiscomputing.com.au wrote:

    Sure, but it's a overkill in a big way.  I don't need or want to show the
    implementation of the function itself, just snippets of code from the test
    case collection (via links to the test case documentation that I was going
    to have anyway).  Many of the test cases provide ready-made example examples
    of how to use the function and it seems shame to copy and paste the pieces
    into comments.  Even if INLINE_SOURCES was selective, including the entire
    body of the test function (which tends to also have a lot of test macros
    going on) would be less helpful and clear than being able to pick out the
    bits I wanted.
    
    Obviously it's no huge deal, a bit of copy and paste never hurt anyone, it
    just seemed like an interesting idea.

On 2013-06-11 02:45:43 +0000, geoff@telesiscomputing.com.au wrote:

    It turns out there is a peculiarity with doxygen's preprocessor that makes
    it possible to achieve what I want with PREDEFINED.  doxygen, currently,
    allows you to embed C comment markers in the macro (something that is not
    possible the actual C/C++ source).  So these two macros:
    
    PREDEFINED             = "TEST_CODE_DOC_BEGIN=/** \code" \
                             "TEST_CODE_DOC_END=\endcode */" \
    
    Can be used in my above example like this:
    
    /*! \brief Confirm that AClass::member does what it should. */
    void my_test_case_for_member()
    {
        TEST_CODE_DOC_BEGIN
        AClass x;
        if (x.member(1, 2, 3) != 6)
            report_error();
        TEST_CODE_DOC_END
    }
    
    (And obviously in the actual source code at compile time these macros would
    resolve to blank lines so that the code would be active.)
    
    This appears to work and do exactly what I want.  My question is whether
    there is any reason to suppose that doxygen might "fix" the current
    peculiarity and stop this little trick from working?
    
    If you think this can be considered safe in the long term then I will be
    happy to mark this item as resolved.

On 2013-08-19 23:26:50 +0000, ronw.mrmx@gmail.com wrote:

    I agree this behavior of the Doxygen preprocessor is useful.
    
    I also suspect it was not intended. I can see how it got in to the
    preprocessor. In a traditional C/C++ preprocessor, one of its jobs is to
    strip out comments os the compiler's lexical analyzer doesn't have to deal
    with them. Doxygen, however, wants the comments, so the preprocessor doesn't
    strip them out. Also, the macro definitions are taken from a separate file.
    
    On the one hand, keeping this functionality would be easy and would require
    only updating Doxygen's design documentation to explicitly include this as a
    feature.
    
    On the other hand, the @includecode proposal is both clearer and safer.
    Clearer because @includecode would be an actual Doxygen command. Safer
    because like any other Doxygen command, it would be inside a comment, so no
    chance of accidentally inserting something unintended into the code.
    
    While personally, I like this "feature" of the Doxygen preprocessor,
    professionally, I recommend the @includecode command.

On 2014-08-01 08:48:01 +0000, milasudril@gmail.com wrote:

    (In reply to comment # 3)
    > It turns out there is a peculiarity with doxygen's preprocessor that makes
    it
    > possible to achieve what I want with PREDEFINED.  doxygen, currently,
    allows
    > you to embed C comment markers in the macro (something that is not
    possible the
    > actual C/C++ source).  So these two macros:
    > 
    > PREDEFINED             = "TEST_CODE_DOC_BEGIN=/** \code" \
    >                          "TEST_CODE_DOC_END=\endcode */" \
    > 
    > Can be used in my above example like this:
    > 
    > /*! \brief Confirm that AClass::member does what it should. */
    > void my_test_case_for_member()
    > {
    >     TEST_CODE_DOC_BEGIN
    >     AClass x;
    >     if (x.member(1, 2, 3) != 6)
    >         report_error();
    >     TEST_CODE_DOC_END
    > }
    > 
    > (And obviously in the actual source code at compile time these macros
    would
    > resolve to blank lines so that the code would be active.)
    > 
    > This appears to work and do exactly what I want.  My question is whether
    there
    > is any reason to suppose that doxygen might "fix" the current peculiarity
    and
    > stop this little trick from working?
    > 
    > If you think this can be considered safe in the long term then I will be
    happy
    > to mark this item as resolved.
    
    I would say that you cannot see that my_test_case_for_member refers to
    AClass::member and report_error.

On 2014-08-01 09:30:21 +0000, geoff@telesiscomputing.com.au wrote:

    (In reply to comment # 5)
    > I would say that you cannot see that my_test_case_for_member refers to
    > AClass::member and report_error.
    
    Note my original post says: "Since I am linking to test cases from tested
    member
    functions for my own reference,"
    
    So I already have the explicit links that I want, I just wanted to be able
    to have the documentation (when referenced) show some useful code examples.
    Code that I've already written and that I know works because it's part of
    the regularly executed test cases.  Also, any changes to the test code would
    automatically be reflected in the documentation (something that cut-n-paste
    often misses), but code that doesn't have to show the entire function with
    all its set-up and clean-up (as INCLUDE_SOURCES would do), because including
    too much just obscures the useful parts of the code when it comes to look
    for examples.

**Comment by albert-github** [comment]
I think that the setting of `INLINE_SOURCES` might be a bit of an overkill. In the current master (1.10.0 (e8c5f5596fc73ee329dec03f0c8ebdd8247a10dd)) the command `showinlinesource` is available and this enables just for the given function the "INLINE_SOURCES".

Another possibility is to use the `\snippet` command (available since version 1.7.5) which gives the possibility to take e.g. part of the code.

It is all illustrated by means of the example:
```
/// \file

/*! \brief Confirm that AClass::member does what it should.
*/
void my_test_case_for_member_org()
{
    //! \code
    //! AClass x;
    //! if (x.member(1, 2, 3) != 6)
    //!     report_error();
    //! \endcode
    AClass x;
    if (x.member(1, 2, 3) != 6)
        report_error();
}

/*! \brief Confirm that AClass::member does what it should.

  \showinlinesource{nolineno}
*/
void my_test_case_for_member_show()
{
    AClass x;
    if (x.member(1, 2, 3) != 6)
        report_error();
}
/*! \brief Confirm that AClass::member does what it should.

  The snippet:
  \snippet this snip
*/
void my_test_case_for_member_snip()
{
    // [snip]
    AClass x;
    if (x.member(1, 2, 3) != 6)
        report_error();
    // [snip]
}
```

Which results in:
![image](https://github.com/doxygen/doxygen/assets/5223533/a9bd5ea3-9c1d-4885-8576-0448430e6b3f)


Seen the possibilities I think the solution is a combination of fixed but not release and usage.


Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/13503449/example.tar.gz)
