### ISSUE TITLE
Parser cannot handle C++11 delegating constructors. (Origin: bugzilla #701977)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5208]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.8.4* on platform *Other*
Assigned to: Dimitri van Heesch

On 2013-06-11 05:51:34 +0000, Daryle Walker wrote:

    I'm using Doxygen through the Windows IDE Code::Blocks.  It looks to use
    standard settings.
    
    I discovered an error in my generated docs right before a check-in.  Looking
    at where the HTML screwed up, it seems that Doxygen can't handle the
    delegating constructor feature.  It's a feature added to C++ 2011, where a
    constructor doesn't have to have an initializer list of bases and members
    (or no list at all), but can use a single call to a sibling constructor.
    This is a brand new use of a class ID within the class itself, so you
    probably missed it.  (The parser tries to make a new entry out of it.)
    
    As an example look at:
     My project at: <https://github.com/CTMacUser/Complex>
     The file at: "include/boost/math/complex_rt.hpp"
     Version: "SHA: f62f2c4dccc8a99a123a644e733858ea9e629d91" (in case I update
    again)
     In branch: "master"
    
    The problem class is the UNspecialized version of "boost::math::complex_rt."
    The last couple constructors use the delegating feature.  The summary list
    gets screwed at the first constructor that uses delegation.  Later members
    don't show up, and some hidden code gets entries instead.

On 2013-06-11 05:53:03 +0000, Daryle Walker wrote:

    It doesn't matter if the delegating call uses braces or parentheses to
    surround the initializer.

On 2013-06-11 06:43:23 +0000, Daryle Walker wrote:

    Of course, after posting this, I realized I screwed my commit message.  I
    fixed it, but that torches the old ID.  The new SHA for the commit is:
    
    SHA: ac944dc0a8ff0cf2157eb51d78087b8bbf6728c5
    
    (Sorry!)

On 2013-06-12 02:57:22 +0000, Daryle Walker wrote:

    I upgraded the Doxygen installation on my 32-bit Windows 8 Pro system to the
    latest, 1.8.4.  [It seems that Code::Blocks simply calls the installed
    Doxygen.]  The problem still exists.

On 2013-06-15 18:21:35 +0000, Dimitri van Heesch wrote:

    Doxygen does support delegating constructors. 
    Can you create a more minimal example that shows the problem?

On 2013-06-16 03:01:46 +0000, Daryle Walker wrote:

    Something weird is going on.  I printed out the problem classes taken from
    my latest commit (SHA: SHA: ada0c7702136ed6e83a37b8216769a200643bce2).
    
    complex_it has 5 constructors, but only lists the first two in the
    documentation.  All of them are in the file-contents view, and all the
    constructors are linked, but those latter three are linked to the default
    constructor.
    
    The base case of complex_rt comes out OK.
    
    The recursive case is totally messed up.  The first two constructors are
    documented and linked in the file-contents view.  The 3rd through 6th get
    linked to the default constructor again.  The 7th through 9th don't have
    links at all.  There are 6 private constructors, they aren't linked, but
    half of them show up in the class summary unlinked.  The screwed-up parser
    adds 4 unlinked entries for public attributes; only "barrage_type" should be
    there.  The description part of the documentation only has the first two
    public constructors.  The member data documentation shows chunks of code,
    thinking them as initializers for data.
    
    You can see it for yourself; I've uploaded the print-outs of the three files
    to my Dropbox at
    <https://dl.dropboxusercontent.com/u/370209/complex_t%20printouts.7z>.

**Comment by albert-github** [comment]
Unfortunately the dropbox version was gone and the github version already had a lot of changes though switching to the commit ada0c7702136ed6e83a37b8216769a200643bce2 was possible.
Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/13603675/example.tar.gz)

Looking at the brief description of
- complex_it
  - doxygen version 1.8.4 we see the 2 constructors all with links
  - current doxygen version, 1.9.8 we see the 5 constructors all with links
- complex_rt< Number, Rank >
  - doxygen version 1.8.4 we see the 2 constructors with hyperlinks and 3 without hyperlinks
  - current doxygen version, 1.9.8 we see the 9 constructors all with links
- complex_rt< Number, 0u >
  - doxygen version 1.8.4 we see the 6 constructors with hyperlinks
  - current doxygen version, 1.9.8 we see the 6 constructors all with links

Regratding the `barrage_type` this is now mentioned as "public type" and the rest is not present als type or attribute.


I think this problem has been solved in the mean time.
