### ISSUE TITLE
Generated Doxyfile differs from result of doxygen -u (Origin: bugzilla #702265)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5213]
status NEW severity *minor* in component *doxywizard* for *---*
Reported in version *1.8.5-GIT* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[whitespace.patch](https://sourceforge.net/projects/doxygen/files/attachments/bug702265_255679_whitespace.patch/download/download)_ (ID 255679)

On 2013-06-14 13:49:42 +0000, Roland Clobus wrote:

    The Doxyfile that is generated by doxywizard differs from the Doxyfile that
    is generated by doxygen.
    
    Steps to reproduce:
    1) Generate the files
    $ doxygen -g sampleconfig
    $ cp samplefonfig generated
    $ doxygen -u sampleconfig
    $ cp sampleconfig updated
    $ doxywizard sampleconfig (and Save)
    $ cp sampleconfig wizard
    $ doxygen -u sampleconfig
    $ cp sampleconfig wizardupdated
    $ doxywizard (Save as wizardgenerated)
    
    2) Look at the differences
    $ diff generated updated
    -> No difference
    $ diff generated wizard
    -> Many differences, mainly whitespace
    $ diff generated wizardupdated
    -> No difference
    $ diff wizard wizardgenerated
    -> A few differences in the settings of some parameters
    
    Expected behaviour:
    - No difference in the configuration files
    
    I've used the git SHA: 8cd4425a523965a5541d46a84828fb7e16f98bae, but older
    versions (1.8.1.2-2 in Debian) also have this behaviour.

On 2013-06-14 17:10:13 +0000, albert wrote:

    Work is in progress regarding the Doxyfile as generated by doxygen and the
    Doxywizard. The given command will be taken into account to to evaluate the
    results.

On 2013-08-24 16:08:08 +0000, albert wrote:

    According to my knowledge this problem should be fixed now.

On 2013-08-24 16:50:32 +0000, Dimitri van Heesch wrote:

    Setting to fixed as suggested.

On 2013-09-25 10:35:30 +0000, Roland Clobus wrote:

    Thank you for the changes.
    
    I did some tests with the current git version (SHA:
    bf8ecf7749d846a1f1b28ab01953ad55989b87a8)
    
    Things have changed, but I still see differences.
    
    $ diff generated wizard
    -> Many differences, but they are only whitespace
    $ diff wizard wizardgenerated
    -> Different settings for the parameters: ABBREVIATE_BRIEF,
    CASE_SENSE_NAMES, FILE_PATTERNS, EXAMPLE_PATTERNS

On 2013-09-25 10:36:53 +0000, Roland Clobus wrote:

    (Updated the version found from 1.8.4-GIT to 1.8.5-GIT)

On 2013-09-25 11:56:26 +0000, Roland Clobus wrote:

    Created attachment 255679
    Draft patch for making the whitespace identical
    
    This patch contains 2 changes:
    * convertToComment: the extra replace will make the empty comment lines
    contain just a hash, and not a hash and a space
    * saveTopic: Not functional. It requires a new pure virtual function in the
    class Input : isNotEmpty. When a valid is empty, the writeValue method does
    not need to be called.
    
    This patch can solve the whitespace differences that I see with
    $ diff generated wizard

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6538

See to it that line endings are correct and no extra white space (conform suggestions of Roland Clobus)

**Comment by albert-github** [comment]
Pull request has been integrated.

**Comment by saimen** [comment]
I think this issue should be closed and `fixed but not released`  should be removed since this was fixed when #6538 was merged in October 2018.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
