### ISSUE TITLE
Feature request: Variation of \code environment which allows XML entity resolution. (Origin: bugzilla #704091)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5238]
status NEEDINFO severity *enhancement* in component *build* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2013-07-12 13:02:24 +0000, merlin@mailinator.com wrote:

    Suppose that I have some \code:
    
    /// \code
    /// if (i < j) k++;
    /// \endcode
    
    This generates XML processing errors (e.g. if one wants to a generate .NET
    xml documentation file as well), so this kind of solution would be
    preferred:
    
    \code{xmlentities}
    if (i &lt; j) k++;
    \endcode
    
    or:
    
    \code_xmlentities
    if (i &lt; j) k++;
    \endcode

On 2014-04-26 17:25:45 +0000, albert wrote:

    I tried to reproduce the problem with a simple aa.h with contents:
    /// \code
    /// if (i < j) k++;
    /// \endcode
    
    The Doxyfile is the standard Doxyfile with just the GENERATE_XML set to YES
    as well.
    In the resulting xml file I see:
    <codeline><highlight class="normal"><sp/></highlight><highlight
    class="keywordflow">if</highlight><highlight
    class="normal"><sp/>(i<sp/>&lt;<sp/>j)<sp/>k++;</highlight></codeline>
    
    
    so with &lt;
    I see this also for a number of older versions of doxygen. 
    
    Please check if the in the latest version (see www.doxygen.org) the problem
    still
    exists / if I formulated the problem correctly and if the problem still
    exists please add a (small) self-contained example (source+config file in a
    zip or tar) to reproduce the problem.

**Comment by albert-github** [comment]
Seen the age of the issue and the fact that there has not been a reaction either the problem has been solved / it is usage / the formulation is unclear.

I think best to set this to invalid.
