### ISSUE TITLE
Allow \ref-ing of images (Origin: bugzilla #705341)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5256]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.8.4* on platform *Other*
Assigned to: Dimitri van Heesch

On 2013-08-02 10:12:14 +0000, TM wrote:

    Feature suggestion to add a referencing to \images.
    
    In HTML this would be the same as an anchor and link to same.
    
    Main advantage is in LaTeX where this could act similar to the manner in
    which current cross reference links work when, for example, functions are
    mentioned by name. This would allow images to be placed at locations that
    better suits the flow of text on the page and reduce white space from vbox-
    ing, etc.
    
    An example
    
    
    /** \page My Example Page
    
    
    Some text here and suddenly I need to talk about a diagram I placed in 
    \ref myExampleImage1.eps [figure 1.1.] 
    
    But then this is followed by a load of other text that may
    flow over to the next page, or multiple pages.
    
    So - Lorem ipsum etc ....
    
    
    ...
    
    \image myExampleImage1.eps "This is an image" width=10cm
    
    
    
    Some text here and suddenly I need to talk about a diagram I placed in 
    \ref mEIRef2 [figure 1.2.] 
    
    ...
    
    \image myExampleImage2.eps "This is an image" width=10cm ref=mEIRef2
    
    */

On 2014-10-08 09:51:31 +0000, milasudril@gmail.com wrote:

    If not implemented, I really need this feature. Tables, equations, ... there
    are many thins that should accept a label. I invented my own stuff using the
    input filter, but I need to run Doxygen twice to get rid of unresolved
    references. If supported nativly, it could be done in a better way.

**Comment by albert-github** [comment]
In principle this is already possible by means of the `\anchor` command where the user can define an unique anchor and can later on refer to it. In this case automatic anchors would have the problem that the same anchor would be generated nultiple times when an image is included multiple times (an thus there wouldn't be an unique anchor).

I think the problem is usage.
