### ISSUE TITLE
Code block not in DoxyDocs.pm (Origin: bugzilla #706346)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5269]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.4* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[Doxy_Stripped.txt](https://sourceforge.net/projects/doxygen/files/attachments/bug706346_252322_Doxy_Stripped.txt/download/download)_ (ID 252322)

On 2013-08-20 00:08:46 +0000, ronw.mrmx@gmail.com wrote:

    Using the attached Doxyfile, this peice of code:
    
    /**  Something complex to chew on.
         A little bit of detail. Then a code block.
         \code
         LetsSeeWhatWeGet();
         InTheParseTree();
         \endcode
    */
    UINT8 complex;
    
    Did not produce a code block in the DoxyDocs.pm:
    
    {
      kind => 'variable',
      name => 'complex',
      virtualness =>'non_virtual',
      protection => 'public',
      static => 'no',
      brief => {
      doc => [
          {
            type => 'text',
            content => 'Something complex to chew on. '
          }
        ]
      },
      detailed => {
        doc => [
          {
            type => 'text',
            content => 'A little bit of detail. Then a code block.  '
          }
        ]
      },
      type => 'UINT8'
    }

On 2013-08-20 00:10:16 +0000, ronw.mrmx@gmail.com wrote:

    Created attachment 252322
    Doxygen configuration

**Comment by albert-github** [comment]
In the 1.8.4 version there is no block for the preformatted code:
![image](https://user-images.githubusercontent.com/5223533/153765906-55f6ade0-1f4f-4f49-bdd3-ee7cac58bdf6.png)


In the 1.9.3 (c0b9eafbfb53286ce31e75e2b6c976ee4d345473) version there is the block:
```
                {
                  type => 'preformatted',
                  content => 'LetsSeeWhatWeGet();
InTheParseTree();'
                },
```


I think the problem has been solved in the mean time.
