### ISSUE TITLE
\, causes confusion in alias arguments (Origin: bugzilla #707041)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5277]
status NEW severity *normal* in component *doxywizard* for *---*
Reported in version *1.8.5* on platform *Other*
Assigned to: Dimitri van Heesch

On 2013-08-29 11:57:25 +0000, Andreas wrote:

    I found the following bug in version 1.8.5. In contrast, version 1.6.3 works
    correctly.
    
    Consider a configuration file with the following aliases:
    Test1{2}=abc
    Test2{1}=\Test1{def,\1}
    Test3=\Test2{ghi jkl}
    Test4=\Test2{ghi\, jkl}
    
    Run Doxygen to document the following C++ code:
    /// Class Test
    class Test
    {
    public:
       /// Function test
       /** Details Function test
           \Test3
           \Test4
           \Test2{gfi\, jkl}
       */
       void test();
    };
    
    Then you will get the following warning for the line with \Test4:
    Warning: Found unknown command `\Test1'
    
    The warning is obviously caused by \, in the definition of Test4 because the
    line with \Test3 does not cause a warning. But also the line with
    \Test2{gfi\, jkl} (i.e. with the definition of Test4) does not cause a
    warning. Therefore Doxygen seems to have problems with \, in the definition
    of certain kinds of aliases.

On 2013-08-29 12:56:09 +0000, Andreas wrote:

    If you add the alias Comma=\, and replace the definition of Test4 by
    \Test2{ghi\Comma jkl} then Doxygen works correctly.

On 2013-11-16 20:17:54 +0000, albert wrote:

    Due to the nested usage the \, is when Test2 is resolved seen as a ,. For
    this case there are probably 2 possible solution (besides the one mentioned
    with \Comma):
    - double backslahs \\,
    - double definition of Test1 once with 2 and once with 3 arguments

On 2013-11-17 09:34:02 +0000, albert wrote:

    Small correction, didn't look at the output as it just outputs "abc"
    everywhere  just looked at the warning.
    
    As far as I can see the intended output is:
    Test3: abc def ghi jkl
    Test4: abc def ghi, jkl
    Test2: abc def ghi, jkl
    
    with input part:
           Test3: \Test3<br>
           Test4: \Test4<br>
           Test2: \Test2{ghi\, jkl}
    
    When using the following ALIASES I get the intended output:
    ALIASES += "Test1{2}=abc \1 \2"
    ALIASES += "Test2{1}=\Test1{def,\1}"
    ALIASES += "Test3=\Test2{ghi jkl}"
    ALIASES += "Test4=\Test2{ghi\\, jkl}"
    so with a double backslash in the definition of Test4
    
    With version 1.6.3 I got the same problem in the original version and the
    correct answer with the proposed solution.

**Comment by albert-github** [comment]
I checked the original problem with version 1.8.5 and I see the warning:
```
warning: Found unknown command `\Test1'
```
with the version 1.9.2. this warning is gone.

Note: due to the usage of spaces and commas in the ALIASES we have to place the individual aliases in quotes:
```
ALIASES += Test1{2}=abc
ALIASES += "Test2{1}=\Test1{def,\1}"
ALIASES += "Test3=\Test2{ghi jkl}"
ALIASES += "Test4=\Test2{ghi\, jkl}"
```

I think the problem has been solved in the mean time
