### ISSUE TITLE
Use Clang for preprocessing (Origin: bugzilla #710637)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5324]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.8.5* on platform *Other*
Assigned to: Dimitri van Heesch

On 2013-10-22 11:53:34 +0000, Domagoj Å ariÄ wrote:

    It great that you've added Clang assisted parsing (though you forgot to
    close the related ticket https://bugzilla.gnome.org/show_bug.cgi?id=691251
    ;) but please also use it for preprocessing too. Doxygen's preprocessor
    isn't capable of parsing complex preprocessor metaprogramming that uses the
    Boost.Preprocessor library...

On 2013-10-26 13:36:18 +0000, Dimitri van Heesch wrote:

    Doxygen has a very specific way in which it pre-processes the code, to allow
    documentation of macros while still correctly processing conditional
    sections, so I can't just replace it with something else.
    
    If you have an example where doxygen's preprocessor fails then please report
    this as a bug.

**Comment by albert-github** [comment]
> If you have an example where doxygen's preprocessor fails then please report
this as a bug.

No example has been given, so issue is incomplete.
