### ISSUE TITLE
"\throws  @c int etc" shows as Exceptions:  @c int etc (Origin: bugzilla #710968)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5330]
status NEW severity *minor* in component *general* for *---*
Reported in version *1.8.5* on platform *Other*
Assigned to: Dimitri van Heesch

On 2013-10-27 17:31:50 +0000, Paul A. Bristow wrote:

    \throws  @c int
    
    shows as
    
    Exceptions
        @c	int 
    
    instead of making int in the code font.
    
    similarly for @b int.
    
    But putting some text before the @c or @b works OK.
    
     "\throws An @c int etc" 
    
    shows as
    
    Exceptions
    	An int etc
    
    Other commands like \returns \pre \post work OK.

**Comment by albert-github** [comment]
The syntax of `\throws`  is (`\throws` is synonymous to `\throw`  and `\exception`):
> \exception <exception-object> { exception description }

when looking at: `\throws  @c int`
we have here as the `<exception-object>` : `@c` but `@c` isn't an exception object but a command.

I think this is usage.
