### ISSUE TITLE
Patch for linking to TCL class members with 'dot' in their name (Origin: bugzilla #711387)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5342]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.5* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxygen-1.8.5-no-dot-scope-separator-v3-stripped.patch.gz](https://sourceforge.net/projects/doxygen/files/attachments/bug711387_258906_doxygen-1.8.5-no-dot-scope-separator-v3-stripped.patch.gz/download/download)_ (ID 258906)
- _[dot-scope-separator-issue.tar.gz](https://sourceforge.net/projects/doxygen/files/attachments/bug711387_258907_dot-scope-separator-issue.tar.gz/download/download)_ (ID 258907)

On 2013-11-04 10:29:12 +0000, Tom Ghyselinck wrote:

    Created attachment 258906
    Patch for retry without substituting '.' as scope separator
    
    Hi all,
    
    There is a bug in doxygen-1.8.5 with TCL classes and class members with a
    dot in their name.
    
    When we want to use \link to these members, the resolution of the name
    fails.
    
    This is due to the fact that the any dot in a name is substituted by '::' as
    if it was a scope separator.
    This is very suitable and convenient for C++ / Java / etc., where a dot
    in function names and class members is not allowed,
    but TCL does allow a dot in function names.
    
    I wrote a (quick and (maybe not so) dirty) patch for doxygen-1.8.5.
    
    The function resolveRef in util.h/util.c now has an additional
    argument dotIsScopeSeparator. When this is set to FALSE,
    a 'dot' in the reference name won't be translated to '::'.
    
    For compatibility, it defaults to TRUE.
    The Q&D part now exists in the fact that, the rest of the code
    still uses the compatible call. The function itself tries to resolve
    with dotIsScopeSeparator = FALSE when resolving with
    dotIsScopeSeparator = TRUE fails.
    
    I added a simple test project with several links as suggested by
    http://www.stack.nl/~dimitri/doxygen/manual/autolink.html
    
    With best regards,
    Tom.

On 2013-11-04 10:31:25 +0000, Tom Ghyselinck wrote:

    Created attachment 258907
    Sample TCL source
    
    Contains Doxyfile + test.tcl
    To reproduce the link issue with class member functions with a 'dot' in
    their name

**Comment by albert-github** [comment]
• By means of commit 58ea5cf320f08ae2ec3e5fbd02d82ca0ba4477a7  the support has been removed from doxygen.
