### ISSUE TITLE
Doxygen forgets about grouping block created using /// @{...///@} (Origin: bugzilla #711625)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5343]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.8.3.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2013-11-07 17:16:58 +0000, Lori Boyters wrote:

    After changing all the /// comment blocker markers to /**...*/, everything
    shows
    up as expected. However, /// is advertised to work, so should work.
    
    Hi Lori,
    
    A quick first investigation shows that doxygen seems to 'forget' about the
    grouping block created using /// @{ ... /// @} somewhere along the parsing
    of the code. Not sure why yet. A workaround is to explicitly use \ingroup
    for each class as I've shown in the attached file.
    Let me know if that works for you and if you want me to spend more time on
    finding and fixing the problem or if you can live with this workaround.
    
    Regards,
      Dimitri
    
    On Oct 15, 2013, at 20:56 , "Boyters, Lori" <lboyters@qti.qualcomm.com>
    wrote:
    
    > 
    > On Oct 14, 2013, at 4:01 , "Boyters, Lori" <lboyters@qti.qualcomm.com>
    wrote:
    > 
    > Hi Dimitri,
    > Unable to get Doxygen to include the markup and code below in the output
    documentation, even when I add the following to the  PREPROCESSOR. Any
    ideas?
    > 
    > ENABLE_PREPROCESSING   = YES
    > MACRO_EXPANSION        = NO
    > EXPAND_ONLY_PREDEF     = NO
    > SEARCH_INCLUDES        = YES
    > INCLUDE_PATH           = ../include
    > INCLUDE_FILE_PATTERNS  =
    > PREDEFINED             = ONLY_FOR_DOXYGEN \
    >                          _MSC_VER
    > EXPAND_AS_DEFINED        =
    > SKIP_FUNCTION_MACROS = YES
    > 
    > /// TODO LORI: the comments and code below do not show up in doc.
    > /// Not sure why yet.
    > /// \brief Stores the blah blah blah for a task. Use /// 
    > create_tbd_attrs(...)  to create a tbd_attrs object.
    > class tbd_attrs {
    > public:
    >  /// \brief Copy DoxyDescconstructor
    >  /// \param other DoxyDescOriginal tbd_attrs #ifndef _MEC_VIR
    >  constexpr
    > #endif
    >    tbd_attrs(tbc_attrs const& other):
    >    _mask(other._mask)
    >  {}
    > 
    > <attrobjs.hh><Doxy_Config.ldd>

On 2013-11-07 17:18:11 +0000, Lori Boyters wrote:

    If you change all the /// to /**...*/, everything works fine.

**Comment by albert-github** [comment]
In the issue as it is there are no references (anymore) to `/// @{...///@}`.
The resulting part (providing getting the layout correct and the `};` at the end is OK.

So I think the problem is incomplete
