### ISSUE TITLE
md files are getting merged for some reason (Origin: bugzilla #711781)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5346]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.1.2* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[example_of_bug.tar.gz](https://sourceforge.net/projects/doxygen/files/attachments/bug711781_259532_example_of_bug.tar.gz/download/download)_ (ID 259532)

On 2013-11-10 14:52:35 +0000, Peter Bena wrote:

    I have multiple md files with various docs, for some reason they all get
    merged into 1 html page, that is labeled by first header of random md file
    (in my case it's unit tests:
    http://tools.wmflabs.org/huggle/docs/head/md_README.html)
    
    however this page contains of more md files mixed together, so that it looks
    weird and makes no sense... I need md files to be stored as separate pages
    (1 page for every md file)

On 2013-11-10 18:29:47 +0000, albert wrote:

    The used version is 1.8.1.2, does this problem still occur with version
    1.8.5 or 1.8.5-git?
    If the problem still occurs please attach a self contained example to this
    bug report including Doxyfile (preferably in a compressed form)

On 2013-11-11 08:05:43 +0000, Peter Bena wrote:

    Created attachment 259532
    Documentation doxy
    
    this is example of bug including configuration file which is in /docs/huggle

On 2013-11-11 08:06:21 +0000, Peter Bena wrote:

    Yes it happens in 1.8.5 which seems to have even more troubles, mainpage.md
    which contained the index page is now somehow not parsed properly.
    
    Index page is empty and link to "Huggle documentation" which is header of
    mainpage document is linking to nonexistent 404 document

On 2013-11-11 08:50:41 +0000, Peter Bena wrote:

    I was wrong, in 1.8.5 it seems not to happen, I didn't notice the README.md
    was parsed as "huggle3-qt-lx" but mainpage is indeed broken

**Comment by albert-github** [comment]
We have here a number of problems (as far as I can see).
- main page not shown at the right place
  - use `USE_MDFILE_AS_MAINPAGE = mainpage.md`, available since 1.8.3
- the reference `[README.md](md_README.html)`
  - the reference `md_README.html` must exist (or generated). In this case a file will be generated based on `README.md` with the name:
     - `md__r_e_a_d_m_e.html` in case of `CASE_SENSE_NAMES       = NO`
     - `md_README.html` in case of `CASE_SENSE_NAMES       = YES`
   - a better solution for this is to use:
      - `[README.md](\ref README.md)`

I think the issues are usage issues.
