### ISSUE TITLE
A command that will generate a warning during compilation (Origin: bugzilla #712291)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5349]
status NEW severity *enhancement* in component *build* for *---*
Reported in version *1.8.5* on platform *Other*
Assigned to: Dimitri van Heesch

On 2013-11-14 13:05:56 +0000, mah@danfoss.com wrote:

    As does many we use a template for our code. This template contains the
    mandatory doxygen comments, but with dummy values
    ex:
    
    /**
     * @brief write short desvription here
     *
     * More extensive doc here, if needed
     *
     * @param foo describe parameter here
     * @param bar describe parameter here
     */
     void zoo( int bar, int foo)
    ...
    
    
    Problem is that i can make doxygen warn about undocumentet code, but this is
    seen as documentet and thus no warning, thus it is forgotten
    
    I would like if i could give a command like "#warning" in C, by writing
    something in the direction of
    
    /**
     * @warnNoDoc
     * @brief write short desvription here
     *
     * More extensive doc here, if needed
     *
     * @param foo describe parameter here
     * @param bar describe parameter here
     */
     void zoo( int bar, int foo)
    ...
    
    And get a undocumented warning during compile.
    Or
    /**
     * @brief @raisewarning write short desvription here
     *
     * More extensive doc here, if needed
     *
     * @param @raisewarning foo describe parameter here
     * @param @raisewarning bar describe parameter here
     */
     void zoo( int bar, int foo)
    ...
    
    
    Or any other similar solution giving the same result.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #8926

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.3.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
