### ISSUE TITLE
Doxygen docsets are not showing in Xcode 5 (Origin: bugzilla #720168)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5377]
status RESOLVED severity *normal* in component *general* for *---*
Reported in version *1.8.5* on platform *Other*
Assigned to: Dimitri van Heesch

On 2013-12-10 03:05:13 +0000, Jasper Blues wrote:

> Xcode5 states that it supports both HeaderDoc and Doxygen formats. 
> 
> However, after building a docset and installing it into Xcode it is not viewing. 
> 
> I have no idea why. . Others are reporting the same issue. Eg: https://github.com/couchbase/couchbase-lite-ios/issues/132

On 2013-12-10 08:17:37 +0000, Jasper Blues wrote:

> The root cause: 
> 
> Xcode 5 changed the metadata format for describing the nodes. In previous versions they used flat list of tokens.xml files but with Xcode 5 the format is folder structure with xml files as leafs. The result is docset that should still be searchable but not showing any nodes when browsing in Xcode docs sidebar. 
> 
> Here's a related GH issue: https://github.com/tomaz/appledoc/issues/409
> 
> . . and apparently Doxygen works again in the latest Xcode preview. 
> 
> So maybe no action required. Just though you might like to know.

On 2013-12-10 10:04:33 +0000, Jasper Blues wrote:

> Just checked latest Xcode 5.1 DevPreview1 - still not working. 
> 
> So the new format _is_ required.

On 2013-12-10 19:59:24 +0000, Dimitri van Heesch wrote:

> Please explain what you mean with "new format". How should it look like?

On 2013-12-10 19:59:34 +0000, Dimitri van Heesch wrote:

> 
> 
> *** This bug has been marked as a duplicate of bug 710914 ***

On 2013-12-11 01:54:02 +0000, Jasper Blues wrote:

> Sorry - "new format" wasn't a good description. 
> 
> We're clear now that this issue has already been logged in another ticket, so I won't repeat myself.

**Comment by ferdymercury** [comment]
updated link to duplicate: https://github.com/doxygen/doxygen/issues/5328
