### ISSUE TITLE
Description / strings in docbookgen.cpp (Origin: bugzilla #721592)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5392]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.8.6* on platform *Other*
Assigned to: Dimitri van Heesch

On 2014-01-05 18:20:49 +0000, albert wrote:

    When looking in the docbookgen.cpp file I see the string "File documentation" but this means that, independent of the chosen language this string will always appear in the generated docbooks although there us a translation routine for this string: trFileDocumentation().
    There are many more strings here that can be translated straight away.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6446

**Comment by albert-github** [comment]
Proposed patch #6446 has been closed, issue has been solved in proposed patch with a new implementation of the docbook generator, pull request #6487

**Comment by albert-github** [comment]
Code of #6487 has been integrated in master on github.
