### ISSUE TITLE
Escape preprocessors, etc, in `code spans` (Origin: bugzilla #722062)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5398]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.6* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxy-codespan.tar.gz](https://sourceforge.net/projects/doxygen/files/attachments/bug722062_359463_doxy-codespan.tar.gz/download/download)_ (ID 359463)

On 2014-01-12 21:51:10 +0000, Josh @ Dreamland wrote:

    There's no way to escape preprocessors inside code spans denoted by markdown
    backticks. My options are to have variable-width preprocessors, or have
    Doxygen gripe,
    
     warning: explicit link request to 'if' could not be resolved
     warning: explicit link request to 'ifdef' could not be resolved
     warning: explicit link request to 'ifndef' could not be resolved
    
    A backslash in the code span is printed literally.
    
    Using <code> explicitly fixes this issue (correctly handles escape
    sequences), but is preposterously verbose and makes the documentation
    comments difficult to read.

On 2014-01-12 22:36:05 +0000, Dimitri van Heesch wrote:

    Can you please explain what you want to see differently, preferrably by
    attaching a self-contained example (source+config file in a tar or zip) that
    demonstrates the issue?
    
    Note that doxygen has support for Markdown style fenched code blocks:
    http://www.stack.nl/~dimitri/doxygen/manual/markdown.html#md_fenced
    if that is what you are looking for?

On 2014-01-13 05:47:32 +0000, Josh @ Dreamland wrote:

    I am looking for inline code spansâspecifically, the ones Markdown denotes
    with backticks. A simple example is the following line:
    
    An example of a preprocessor is `#pragma`. Others include `#if`, `#include`,
    and `#define`.
    
    Doxygen will throw a warning for each of those. Adding a backslash inside
    the backticks does not fix the warning, and instead is printed literally as
    though \\ were used.
    
    The tarball you requested is here:
    https://dl.dropboxusercontent.com/u/1052740/attachments/doxy-codespan.tar.gz

On 2014-01-30 15:57:04 +0000, DTJF wrote:

    We can work-around the preprocessor issue by using \#`include`, \#`if`, ...
    
    But I couldn't find a work-around for markdown like
    
      `rm src/*.c`
    
    which results in the warning
    
      "Reached end of file while still inside a (nested) comment. Nesting level
    2"
    
    since Doxygen interprets the characters "/*" as the start of a new comment.
    Also the end of a comment like "*/" in a code block confuses Doxygen.
    
    It seems that all code blocks are broken in version 1.8.6 (@code, fenced
    code blocks and code spans).

On 2016-04-20 18:04:56 +0000, David Hammen wrote:

    The problem appears to be that the special characters in doxygen (e.g., $,
    @, \, & ~, <, >, #, %, ", ., and |) cannot be escaped in doxygen-flavored
    markdown. I've experimented with #, and a few more. The hash symbol and
    backslash are particularly problematic. (I suspect $, @, and % are also
    problematic.)
    
    A simple solution: Document that backtick-delimited code spans must not
    contain doxygen special characters. An even better solution is to document
    which doxygen special characters don't work in the context of a backtick-
    delimited code span. An even better solution: Make the treatment of a
    backtick-delimited code span be identical to that of a code span enclosed by
    <tt> and </tt>.

On 2017-09-10 10:08:19 +0000, albert wrote:

    I wanted to look at the attachment (even I don't like it to be elsewhere).
    but it disappeared. Josh @ Dreamland can you attach the attachment again,
    but now to this bug report?

On 2017-09-10 13:54:59 +0000, Josh @ Dreamland wrote:

    Created attachment 359463
    Self-contained example.

On 2017-09-10 13:59:47 +0000, albert wrote:

    Thanks for the quick reaction.

**Comment by albert-github** [comment]
In the 1.8.6 version we get the warning as indicated.
With the 1.9.2 version the warnings are gone and the output looks also OK to me.

I think the problem has been solved in the mean time.
