### ISSUE TITLE
'function' is displayed as C++ keyword (green) in HTML output (Origin: bugzilla #722111)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5399]
status NEW severity *minor* in component *general* for *---*
Reported in version *1.8.6* on platform *Other*
Assigned to: Dimitri van Heesch

On 2014-01-13 15:26:35 +0000, Gerard Torrent wrote:

    The HTML output of the following C++ code (see below) draws the word
    'function' in line 'static const function functions[];' in green color (like
    a keyword, but 'function' is not a C++ keyword
    -http://en.cppreference.com/w/cpp/keyword-).
    
    
    namespace XXX {
    
    class Expr
    {
      ... omited
    
      private:
    
        //! Internal struct
        struct constant
        {
          //! Constant name
          const char id[3];
          //! Constant value
          double x;
        };
    
        //! Internal struct
        struct operador
        {
          //! Operator identifier
          const char id[2];
          /**
           * @brief Operator precedence.
           * @see http://en.wikipedia.org/wiki/Order_of_operations
           */
          char prec;
          /**
           * @brief Operator associativity.
           * @see http://en.wikipedia.org/wiki/Operator_associativity
           */
          bool left;
          //! Pointer to function
          ffunc2 func;
        };
    
        /**
         * @brief Internal struct
         * @todo Add flag force_eval (eg. rand()).
         */
        struct function
        {
          //! Function name
          const char id[5];
          //! Number of arguments. 0 is used for minus and plus signs functions.
          int args;
          //! Pointer to function
          void *ptr;
        };
    
      private:
    
        //! List of operators
        static const operador operators[];
        //! List of functions
        static const function functions[];
    
      --- omited
    
    };
    
    }

On 2014-02-16 18:31:57 +0000, Gerard Torrent wrote:

    The attached files (src + config + image) of bug 722112 are also valid for
    this one.

On 2016-09-10 13:47:58 +0000, albert wrote:

  I've just pushed a proposed patch to github (pull request #520)

**Comment by albert-github** [comment]
I've just pushed a new proposed patch to github (pull request #8729) superseding the proposed pull request #520

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.3.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
