### ISSUE TITLE
C++11 enum cannot doc two enums with the same value out-of-line (Origin: bugzilla #722363)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5402]
status NEW severity *major* in component *documentation* for *---*
Reported in version *1.8.6* on platform *Other*
Assigned to: Dimitri van Heesch

On 2014-01-16 18:33:50 +0000, Reece H. Dunn wrote:

    Using a standard `doxygen -g` generated Doxyfile with:
    
    	EXTRACT_ALL            = YES
    
    Given:
    
    	namespace test2 {
    		/** @brief This is A. */
    		enum class A {
    			a, /**< This is A::a */
    			b, /**< This is A::b */
    		};
    		/** @brief This is B. */
    		enum class B {
    			b, /**< This is B::b */
    			c, /**< This is B::c */
    		};
    	}
    
    the documentation for test2::A::b and test2::B::b are correctly associated
    with the correct enumeration.
    
    However, for out-of-line documentation:
    
    	namespace test1 {
    		enum class A {
    			a,
    			b,
    		};
    		enum class B {
    			b,
    			c,
    		};
    	}
    
    	/**
    
    	\enum test1::A
    	\brief This is A.
    
    	\var test1::A test1::A::a
    	\brief This is A::a.
    
    	\var test1::A test1::A::b
    	\brief This is A::b.
    
    	\enum test1::B
    	\brief This is B.
    
    	\var test1::B test1::B::b
    	\brief This is B::b.
    
    	\var test1::B test1::B::c
    	\brief This is B::c.
    
    	*/
    
    the documentation for test1::A::b and test1::B::b are associated with
    test1::A::b. That is, test1::A::b has the documentation:
    
    	This is A::b.
    
    	This is B::b. 
    
    while the documentation for test1::B::b is blank.
    
    This impacts documentation for a project of mine, where I keep documentation
    in a separate file from the source code and I have encountered this bug
    trying to document the enumeration values.
    
    NOTE: This is also present in 1.8.5.

**Comment by albert-github** [comment]
With the doxygen 1.8.6 version we see for the "out-of-line documentation":
![image](https://github.com/doxygen/doxygen/assets/5223533/78098b88-04fd-40c9-a537-88d04f062b70)

with the current (1.9.8) doxygen version we see:
![image](https://github.com/doxygen/doxygen/assets/5223533/075ce369-d891-4256-87da-c3e55199e135)

So I think the problem has been solved in the mean time.
