### ISSUE TITLE
Missing jquery.js when SEARCHENGINE is off (Origin: bugzilla #722507)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5405]
status NEEDINFO severity *normal* in component *general* for *---*
Reported in version *1.8.6* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[example.tar.gz](https://sourceforge.net/projects/doxygen/files/attachments/bug722507_282838_example.tar.gz/download/download)_ (ID 282838)

On 2014-01-18 20:40:19 +0000, Josef Kufner wrote:

    When generating documentation for PHP project, there is no jquery.js file in
    ./doxygen/html/ directory. This makes collapsed sections of generated
    documentation inaccessible. The dynsections.js is present as expected, only
    jquery.js is missing.
    
    Steps to reproduce:
    
      0. Go to some empty dir
      1. Run: doxywizzard Doxygen
      2. Uncheck SEARCHENGINE in Expert / HTML
      3. Run: doxygen Doxygen
      4. jquery.js is missing
      5. Check SEARCHENGINE in Expert / HTML
      6. Run: doxygen Doxygen
      4. jquery.js is present

On 2014-02-08 09:45:45 +0000, Dimitri van Heesch wrote:

    Hi Josef,
    
    I wasn't able to reproduce the problem with the above procedure, and looking
    at the code the jquery.js is created unconditionally (at least when the HTML
    output is enabled).
    
    Can you check if you see the same behavior when running doxygen from the
    command line? Does the output that is produced indicate (at the bottom right
    of each page) that it is generated by Doxygen 1.8.6 or perhaps a much older
    version?

On 2014-08-07 17:38:21 +0000, Kjell Ahlstedt wrote:

    Created attachment 282838
    Configuration file and some input
    
    I can confirm this behaviour with doxygen 1.8.6.
    
    Expand the attached gz file, and run
      doxygen
    in directory example.
    
    jquery.js is not copied to example/html when SEARCHENGINE = NO.
    
    Note that doxygen does not clear the html directory. If you first test with
    SEARCHENGINE = YES, jquery.js is copied to example/html. If you then test
    with SEARCHENGINE = NO without removing jquery.js, it will remain in
    example/html.

On 2014-08-13 17:13:35 +0000, Kjell Ahlstedt wrote:

    Comment 2 concerns the version of doxygen that I installed with the Synaptic
    package manager in Ubuntu 14.04. 'doxygen --version' says it's version
    1.8.6.
    
    Now I've also built doxygen 1.8.6 and 1.8.7 from the tarballs in
    ftp://ftp.stack.nl/pub/users/dimitri/. Both of them copies jquery.js to
    the html directory even if SEARCHENGINE = NO.
    
    The missing jquery.js is a bug in Ubuntu's doxygen 1.8.6, which is not
    identical to Doxygen's doxygen 1.8.6!
    
    Josef, from where have you got your doxygen 1.8.6?

On 2014-08-13 17:18:26 +0000, Josef Kufner wrote:

    From Debian packages.

On 2014-08-13 17:28:34 +0000, Dimitri van Heesch wrote:

    :-( That explains why I cannot reproduce it myself.
    Can you please inform the package manager about this?

On 2014-08-13 17:44:39 +0000, Josef Kufner wrote:

    I just tested it again with doxygen 1.8.7 and it is still bugged.
    
    And it looks like it is reported already: https://bugs.debian.org/cgi-
    bin/bugreport.cgi?bug=751727&archived=False&mbox=no

On 2014-08-14 08:16:47 +0000, Kjell Ahlstedt wrote:

    I can't find an Ubuntu bug about this at https://bugs.launchpad.net/ubuntu,
    but since Ubuntu is based on Debian, I suppose it will be fixed in Ubuntu
    once
    it's fixed in Debian.
    
    I found the file doxygen-jquery.patch in the archive file
https://launchpad.net/ubuntu/+archive/primary/+files/doxygen_1.8.6-2.debian.tar.xz
    
      Index: doxygen/src/htmlgen.cpp
      ===================================================================
      --- doxygen.orig/src/htmlgen.cpp	2013-11-09 19:18:19.000000000 +0100
      +++ doxygen/src/htmlgen.cpp	2013-11-09 19:18:19.000000000 +0100
      @@ -1560,6 +1560,7 @@
           fprintf(stderr,"Warning: Cannot open file %s for
    writing\n",fileName.data());
         }
       
      +  if (Config_getBool("GENERATE_TREEVIEW") ||
    Config_getBool("SEARCHENGINE"))
         {
           QFile f(dname+"/jquery.js");
           if (f.open(IO_WriteOnly))
    
    That patch is the bug, I guess.
    It's also included in doxygen_1.8.7-3.debian.tar.xz.

On 2014-08-14 13:32:44 +0000, Dimitri van Heesch wrote:

    Indeed.

**Comment by albert-github** [comment]
Seen the discussion I don't think this is a doxygen bug but a bug introduced by the maintainer of tyhe Debian package.
In the mean time also the complete construct regarding jquery.js copy (still in doxygen unconditional) has changed.

I think this issue can be closed as not a doxygen problem.
