### ISSUE TITLE
EXCLUDE_PATTERN kicks all files (Origin: bugzilla #723143)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5419]
status NEEDINFO severity *major* in component *general* for *---*
Reported in version *1.8.6* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxybug.tar.bz2](https://sourceforge.net/projects/doxygen/files/attachments/bug723143_267379_doxybug.tar.bz2/download/download)_ (ID 267379)

On 2014-01-28 03:45:23 +0000, Alex Turbov wrote:

    Created attachment 267379
    sample "project" to reproduce the porblem
    
    EXCLUDE_PATTERNS =  */tests/*
    
    this EXCLUDE_PATTERNS (or presence of '*/tests/*' in it, to be precise)
    makes doxygen skip all files in a project... any other similar patterns are
    handled Ok

On 2014-02-03 19:14:08 +0000, Dimitri van Heesch wrote:

    I couldn't reproduce this with your example.
    
    Are you sure the whole project isn't in a directory called tests?
    If not, can you show the output that doxygen prints to stdout?
    
    For instance this is what I see for your example:
    
    ...
    
    Parsing files
    Preprocessing /data/doxygen/mail/1.8.6/bug723143/doxybug/bin-test/main.cc...
    Parsing file /data/doxygen/mail/1.8.6/bug723143/doxybug/bin-test/main.cc...
    Preprocessing /data/doxygen/mail/1.8.6/bug723143/doxybug/foocxx/foo.cc...
    Parsing file /data/doxygen/mail/1.8.6/bug723143/doxybug/foocxx/foo.cc...
    Preprocessing /data/doxygen/mail/1.8.6/bug723143/doxybug/foocxx/foo.hh...
    Parsing file /data/doxygen/mail/1.8.6/bug723143/doxybug/foocxx/foo.hh...
    Building group list...
    
    ...

**Comment by albert-github** [comment]
Seen the fact that no reaction on the last comment was given and the given example processes properly, I think we can say that this is usage.
