### ISSUE TITLE
Problem with enum / union with HIDE_UNDOC_RELATION = NO (Origin: bugzilla #723239)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5420]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.8.6* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[example.taz](https://sourceforge.net/projects/doxygen/files/attachments/bug723239_267533_example.taz/download/download)_ (ID 267533)

On 2014-01-29 14:51:26 +0000, albert wrote:

    When a typedef has an enum or union as a member and HAVE_DOT = YES as well
    as HIDE_UNDOC_RELATIONS = NO in the standard Doxyfile the following messaeg
    is shown:
    QGDict::hashAsciiKey: Invalid null key
    
    See the attached compressed tar example file for a case showing the problem
    with an enum.

On 2014-01-29 14:57:32 +0000, albert wrote:

    Created attachment 267533
    Example showing the problem

On 2014-01-29 16:59:05 +0000, albert wrote:

    Two observations I forgot to mention:
    - problem occurs at line 2595 of dot.cpp (github version of January 29,
    2014):
       DotNode *bn = m_usedNodes->find(className);
    - in case the enum / union is not anonymous (e.g.
        enum enu {
               MULTIPLE ///< docu MULT
             } member ;
      the problem disappears.

**Comment by albert-github** [comment]
Ran problem with version 1.8.6 and I see the messages.
With version 1.8.14 the messages are gone (actually since 1.8.11).

I think the problem has been solved in the mean time.
