### ISSUE TITLE
searchengine html problem (Origin: bugzilla #724285)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5426]
status NEEDINFO severity *major* in component *general* for *---*
Reported in version *1.8.5* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxygen_bug.jpg](https://sourceforge.net/projects/doxygen/files/attachments/bug724285_269000_doxygen_bug.jpg/download/download)_ (ID 269000)

On 2014-02-13 12:47:13 +0000, Daniel Scholz wrote:

    Created attachment 269000
    opend the file the smaler monitor
    
    Hello Team,
    
    If you have the setup like me:
    .....
    SEARCHENGINE           = YES
    SERVER_BASED_SEARCH    = NO
    EXTERNAL_SEARCH        = YES
    SEARCHENGINE_URL       = 
    SEARCHDATA_FILE        = searchdata.xml
    EXTERNAL_SEARCH_ID     = 
    EXTRA_SEARCH_MAPPINGS  = 
    .....
    
    My System:
    Win 8 
    Monitor 1: 1280*1024
    Monitor 2: 1680*1050
    
    and you use two LCD's with different sizes and solutions. Than you may get
    the same problem as I did.
    
    As I tried to use the searchtoolbar I allways got no result. And I was
    wondering why I didn't got one, like yesterday.
    
    1. open the html files from doxygen and size down the window
    2. try the searchbar in the right upper corner
    3. you should not get a result 
    4. you can see the result if you scroll sideways to the right side
    
    As you can see in the Picture the result is pinned towards the scrollbar on
    the right site.
    
    I hope I could give you a reproducable discription.
    
    If not please let me know.
    
    kind regards
    
    Daniel Scholz

On 2014-02-15 13:24:10 +0000, Dimitri van Heesch wrote:

    Does this problem happen only with IE or also with other browsers (Chrome,
    Firefox)?

On 2014-02-18 06:35:34 +0000, Daniel Scholz wrote:

    (In reply to comment # 0)
    > Created an attachment (id=269000) [details]
    > opend the file the smaler monitor
    > 
    > Hello Team,
    > 
    > If you have the setup like me:
    > .....
    > SEARCHENGINE           = YES
    > SERVER_BASED_SEARCH    = NO
    > EXTERNAL_SEARCH        = YES
    > SEARCHENGINE_URL       = 
    > SEARCHDATA_FILE        = searchdata.xml
    > EXTERNAL_SEARCH_ID     = 
    > EXTRA_SEARCH_MAPPINGS  = 
    > .....
    > 
    > My System:
    > Win 8 
    > Monitor 1: 1280*1024
    > Monitor 2: 1680*1050
    > 
    > and you use two LCD's with different sizes and solutions. Than you may get
    the
    > same problem as I did.
    > 
    > As I tried to use the searchtoolbar I allways got no result. And I was
    > wondering why I didn't got one, like yesterday. 
    > 
    > 1. open the html files from doxygen and size down the window
    > 2. try the searchbar in the right upper corner
    > 3. you should not get a result 
    > 4. you can see the result if you scroll sideways to the right side
    > 
    > As you can see in the Picture the result is pinned towards the scrollbar
    on the
    > right site. 
    > 
    > I hope I could give you a reproducable discription.
    > 
    > If not please let me know.
    > 
    > kind regards
    > 
    > Daniel Scholz
    
    (In reply to comment # 1)
    > Does this problem happen only with IE or also with other browsers (Chrome,
    > Firefox)?
    
    I only had it once with IE.

On 2014-02-20 20:21:05 +0000, Dimitri van Heesch wrote:

    So then I expect it is more like a glitch in IE...
    Do you agree?
    
    If not then please attach a self-contained example (source+config file in a
    tar or zip) that allows me to reproduce the problem

On 2014-02-24 05:56:43 +0000, Daniel Scholz wrote:

    (In reply to comment # 3)
    > So then I expect it is more like a glitch in IE...
    > Do you agree?
    > 
    > If not then please attach a self-contained example (source+config file in
    a tar
    > or zip) that allows me to reproduce the problem
    
    Hello Dimitri,
    
    I think thats a bug from the IE, I had this bug several times but right now
    I can't reproduce it myself.
    
    But thanks for your time.
    
    Kind regards
    
    Danny

**Comment by albert-github** [comment]
Problem (according to the last comment) looks like to be solved and otherwise just a problem with IE.
Also seen the time gone bye and no further comments I think that is it save to say it is not a doxygen bug or that it has been solved in the mean time.
