### ISSUE TITLE
Imported tagfile with namespace A blocks generation of namespace A file in importing library. (Origin: bugzilla #725201)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5430]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.4* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[DoxygenNameSpaceProblem.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug725201_270354_DoxygenNameSpaceProblem.zip/download/download)_ (ID 270354)

On 2014-02-26 08:15:01 +0000, diarmuid.kieran@pdgm.com wrote:

    Created attachment 270354
    Source files of libLegs and libFeet libraries
    
    The library libFeet includes a tagfile from the library libLegs.
    
    In the below, all classes and namespaces have Doxygen comments describing
    them.
    
    libLegs has a class Shin within the namespace LEG
    libLegs has a class Ankle within the namespace FOOT
    
    libLegs generates two namespace files - namespaceLEG.html and
    namespaceFOOT.html
    libLegs also generates a libLegs.tag file
    
    libFeet has a class Sock within the namespace CLOTHES
    libFeet has a class Tendon within the namespace FOOT
    
    libFeet uses the libLegs.tag file.
    libFeet generates ONLY ONE namespace file - namespaceCLOTHES.html
    It should generate namespaceFOOT.html too, but it does not. If I remove the
    libLegs tagfile from its makefile.doxygen, then libFeet will generate
    namespaceFOOT.html. This shows that the namespaceFOOT.html of the libLegs
    tagfile is preventing somehow the generation of namespaceFOOT.html by
    libFeet
    
    Please find attached source files.

**Comment by albert-github** [comment]
With the doxygen 1.8.4 version only the `namespaceCLOTHES.html` is generated in the `libFeet ` output directory.
With the current doxygen version (1.9.8) also the file `namespaceFOOT.html` is generated.

I think the problem has been solved in the mean time.
