### ISSUE TITLE
Graphs show in 1.8.6 when told not to and contain absolute paths (Origin: bugzilla #725616)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5433]
status NEEDINFO severity *blocker* in component *general* for *---*
Reported in version *1.8.6* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[1.8.2_output_correct_vs_1.8.6_output.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug725616_270846_1.8.2_output_correct_vs_1.8.6_output.zip/download/download)_ (ID 270846)

On 2014-03-03 21:21:38 +0000, Gail wrote:

    Created attachment 270846
    See bug description for the list of files contained in this ZIP.
    
    We would like to upgrade to 1.8.6, but using 1.8.6 on the same code base as
    1.8.2 results in these issues:
    
    1) Graphs appear on Files > file.h pages, although configuration settings
    are the same as in 1.8.2 where NO GRAPHS APPEAR (the desired behavior).
    2) In the graph the absolute paths to SOME of the files appear (seemingly
    randomly).
    
    1.8.2 output has neither issue.
    
    Attaching 1.8.6 versions of:
    doxyfile
    layout.xml
    JPG showing output
    
    Attaching 1.8.2 (BUILT ON THE SAME CODE) versions of:
    doxyfile
    layout.xml
    JPG showing output

On 2014-03-23 18:54:46 +0000, Dimitri van Heesch wrote:

    Hi Gail,
    
    I don't know why the absolute paths appear either (if you run doxygen from a
    directory other than the root of the source tree you may want to check
    STRIP_FROM_PATH, and STRIP_FROM_INC_PATH).
    
    You did enable generation of include graphs, so if you don't want them set
    INCLUDE_GRAPH and INCLUDED_BY_GRAPH to NO.
    
    If you need further help, please include a self-contained example (so config
    file and source files) so I can actually reproduce them problem at my end.

**Comment by albert-github** [comment]
As written in the comment the settings of `INCLUDE_GRAPH` (and `INCLUDED_BY_GRAPH`) makes in the 1.8.6 a difference, probably the handling of these have been improved between the mentioned versions. Setting them to `NO` in the current doxygen version (1.9.6) also results in no graph.

Regarding the absolute paths , this is not reproducible due to a missing example.

I think the problem was usage.
