### ISSUE TITLE
Generates oddly named "Directory Reference" man pages including build path (Origin: bugzilla #727796)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5446]
status NEEDINFO severity *normal* in component *general* for *---*
Reported in version *1.8.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxytest.tar.gz](https://sourceforge.net/projects/doxygen/files/attachments/bug727796_280561_doxytest.tar.gz/download/download)_ (ID 280561)

On 2014-04-08 06:17:07 +0000, Helmut Grohne wrote:

    I am quoting the original Debian bug report at
    http://bugs.debian.org/742871:
    
    > when generating man pages via doxygen, newer versions of doxygen (can't
    > exactly tell when this behaviour changed), now generate a "Directory
    > Reference" man page. This file is oddly named though and includes the
    > full build path. In my case (libdaemon), it generated
    > 
    > /usr/share/man/man3/_tmp_buildd_libdaemon-0.14_libdaemon_.3.gz
    > 
    > [...]
    > 
    > libdaemon 0.14-2, which was built with doxygen 1.6.2-1 [1], doesn't show
    > this behaviour. So something must have changed between 1.6.2 and 1.8.6
    > 
    > I tried to find documentation about how to influence the generation of
    > this Directory Reference man page, i.e. to either convince it to use a
    > proper name or not generate it at all. If there is such a configuration
    > switch and I need to update my doxygen.conf [2], please let me know.
    > Otherwise this looks like a genuine bug in doxygen.
    
    The relevant package sets FULL_PATH_NAMES=NO, but changing that to
    FULL_PATH_NAMES=YES and leaving STRIP_FROM_PATH at its default does not
    solve
    the issue.
    
    I narrowed the intrusion of this behaviour to a version window of 1.7.6.1 to
    1.8.1, but I couldn't find the offending change in the mess of
    bison generated/flex generated/uglified javascript files.

On 2014-04-12 11:53:47 +0000, Dimitri van Heesch wrote:

    Can you please attach a self-contained example (source+config file in a tar
    or zip) that allows me to reproduce the problem?

On 2014-07-12 20:51:54 +0000, David Bremner wrote:

    Created attachment 280561
    test case
    
    The file is not created if notmuch.h is in the same directory as doxygen.cfg

On 2015-02-21 13:55:24 +0000, Bastiaan wrote:

    Are you able to reproduce this? We are hit by the same problem using 1.8.8,
    sources are in https://bitbucket.org/Coin3D/coin/branch/CMake.
    
    Thanks,
    Bastiaan.

On 2018-04-17 15:10:10 +0000, Paolo Greppi wrote:

    This commit:
    https://github.com/doxygen/doxygen/commits/master/src/dirdef.cpp
    resolves the issue on the test case attached to this bug report.

On 2018-04-17 17:20:15 +0000, albert wrote:

    @Paolo Greppi you refer to a file not to a commit, please clarify. Do you
    suggest that the problem is solved in the current version of doxygen i.e.
    1.8.14?

On 2018-04-17 17:35:19 +0000, Paolo Greppi wrote:

    Sorry I meant:
    https://github.com/doxygen/doxygen/commit/SHA:
    38987846ec0752b8deee7bab69c7890aa861af00
    
    Yes, the issue is resolved in 1.8.14 which includes this commit, at least
    for the test case attached to this bug report.
    
    But I'd wait a bit before marking this bug as closed as I am in the process
    of testing a few more complex test cases from the originating Debian bug:
    https://bugs.debian.org/742871
    
    I'll report back when I'm 100% sure that they are all solved now.

On 2018-04-17 17:39:20 +0000, albert wrote:

    Thanks, please don't set to closed (even when it is resolved), make a
    comment saying that the problem is solved in the mean time (or similar
    wording) and set status back to "New". In that way it can, possible, be
    handled in release notes etc.

**Comment by albert-github** [comment]
As indicated in the comment (and verified with the current doxygen version (1.9.6)) the problem is solved in the mean time.
