### ISSUE TITLE
Ability to load a PREDEFINED file (Origin: bugzilla #727958)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5447]
status NEEDINFO severity *enhancement* in component *general* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2014-04-10 12:33:40 +0000, Mr Aras wrote:

    I'd like to be able to load a file which contains a list of macros. Similar
    to the PREDEFINED setting, but the list is loaded via a file.
    
    I have a large multi-target project which has a configuration script that
    produces a header/config file which is included at the gcc stage.
    
    None of the source code files include this file, it's passed to gcc via "-D"
    options. (yes, this is crazy, but it's legacy code and I'm stuck with it).
    
    This makes using Eclipse's indexing a pain, and it means that Doxygen can't
    fully parse all the files as most the source is wrapped in #ifdef which
    referenced the macros found in the configuration file.
    
    This configuration file has over 100 entries so there is no easy way to
    enter this list in to Doxygen's configuration file.
    
    It would be great if I could load this file either as a #define list of
    macros, or simply as a flat file with one macro per line.
    
    e.g.
    
    #define FOO
    #define BAR
    #define DEBUG
    
    or
    
    FOO
    BAR
    DEBUG

On 2014-04-12 11:50:52 +0000, Dimitri van Heesch wrote:

    This is already possible if you make a list with
    
    PREDEFINED += FOO
    PREDEFINED += BAR
    PREDEFINED += DEBUG
    
    and include that in the Doxyfile using @INCLUDE
    
    Let me know if this work for you.

**Comment by albert-github** [comment]
The feature is available in doxygen as mentioned in the comment of the issue.
As there is no answer it is assumed that it works for OP as well.

The problem is usage.
