### ISSUE TITLE
Support GFM backticks for fenced code blocks (Origin: bugzilla #728260)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5455]
status NEW severity *enhancement* in component *documentation* for *---*
Reported in version *1.8.6* on platform *Other*
Assigned to: Dimitri van Heesch

On 2014-04-15 12:46:09 +0000, JÃ¸rgen Ibsen wrote:

    Unless it results in issues with other doxygen elements, would it be
    possible to support using backpings to start a fenced code block as well as
    tildes?
    
    GitHub appears to support both, but only backpings are documented at the
    moment [1]. Support in other systems seem to be divided [2].
    
    [1]: https://help.github.com/articles/github-flavored-markdown
    [2]: http://meta.stackoverflow.com/a/143705

**Comment by albert-github** [comment]
Since version 1.8.11 doxygen supports both types of syntax (tilde and back-tick).

 I think the problem has been solved in the mean time.
