### ISSUE TITLE
Linking to source file directly from markdown does not work (Origin: bugzilla #728648)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5457]
status NEW severity *minor* in component *general* for *---*
Reported in version *1.8.7* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[foobar.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug728648_274804_foobar.zip/download/download)_ (ID 274804)

On 2014-04-21 12:33:00 +0000, JÃ¸rgen Ibsen wrote:

    Created attachment 274804
    Small example of the issue
    
    In the attached example, README.md contains a direct link to the file
    foobar.h, which is also included in the generated documentation.
    
    Doxygen generates a link to the nonexistent foobar.h in the doc/html folder,
    instead of foobar_8h.html, which is the generated html page for the file.

**Comment by albert-github** [comment]
In the doxygen documentation it is stated:
> For an inline link the link text is followed by a URL and an optional link title which together are enclosed in a set of
regular parenthesis. The link title itself is surrounded by quotes.
>
> Examples:
> `[The link text](http://example.net/)`
> `[The link text](http://example.net/ "Link title")`
> `[The link text](/relative/path/to/index.html "Link title")`
> `[The link text](somefile.html)`
>
> In addition doxygen provides a similar way to link a documented entity:
> `[The link text](@ref MyClass)`

So I think doxygen contains the possibility and the request here is usage
