### ISSUE TITLE
\copyright only ends its paragraph on an empty line, not an empty starred line (Origin: bugzilla #729182)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5466]
status NEEDINFO severity *normal* in component *general* for *---*
Reported in version *1.8.7-GIT* on platform *Other*
Assigned to: Dimitri van Heesch

On 2014-04-29 12:31:57 +0000, mike@eon-consult.be wrote:

    description: the output (html and latex) is not what I would intuitively
    expect.
    
    In the snippet below the empty line between \copyright and 'This is a bug
    report' is ignored.
    This results in the copyright being: "(c) 2014 - Bug report This is a bug
    report"
    
    /**
     * \copyright (c) 2014- Bug report
     *
     * This is a bug report
     */
    
    The snippet below actually does what would be expected, here the copyright
    is: "(c) 2014- Bug report"
    
    /**
     * \copyright (c) 2014- Bug report
     
     * This is a bug report
     */

On 2014-04-29 14:47:03 +0000, albert wrote:

    I tried to reproduce the problem (on windows), but was not successful.
    Created 2 files with in bot just one of the parts together with a \file
    command. Used the a default Doxyfile.
    
    Please add a (small) self-contained example (source+config
    file in a zip or tar) to reproduce / showing the problem.

**Comment by albert-github** [comment]
Unfortunately no response, setting to incomplete problem report.
(as mentioned in earlier comment the problem was also not reproducible with the already given information, all texts were shown).
