### ISSUE TITLE
Spurious warning when documenting friend template (Origin: bugzilla #729237)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5468]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.7* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[singleton.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug729237_275466_singleton.zip/download/download)_ (ID 275466)

On 2014-04-30 06:10:05 +0000, john.x.foster@nab.com.au wrote:

    Created attachment 275466
    Zip containing simpe code and config file
    
    This bug was reported as 678139. It is still occurng under 1.8.7. A warning
    is geerated when documentin the code.

On 2017-12-25 13:24:56 +0000, Dimitri van Heesch wrote:

    *** Bug 776986 has been marked as a duplicate of this bug. ***

**Comment by albert-github** [comment]
Tested with 1.8.7 and I saw the warning message.
With version 1.8.14 the message is gone.

I think the problem has been solved in the mean time.
