### ISSUE TITLE
Ignoring an items when / or \ is placed after \addindex (Origin: bugzilla #729344)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5471]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.7* on platform *Other*
Assigned to: Dimitri van Heesch

On 2014-05-01 16:57:00 +0000, albert wrote:

    When I take from the installation the install.doc and place a \ (backslash)
    after the \addindex of installation and the \addindex of flex than the first
    is
    mentioned but the second one is silently ignored and installation and flex
    does
    not show up in the pdf index.
    
    Placing a / (slash) after the \addindex command results also in a silent
    ignoring of the \addindex command (in case e.g. a 's' is placed after the
    \addindex command, so \addindexs, than this is noted) and no mentioning in
    the
    pdf index.
    
    (This bug results from tests done for the now solved bug_728530)

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #11122

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.13.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
