### ISSUE TITLE
A list of missing documentation features (Origin: bugzilla #730115)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5480]
status NEW severity *normal* in component *build* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2014-05-14 10:51:10 +0000, milasudril@gmail.com wrote:

    There are several missing features in the documentation language. To deal
    with it, I have written a macro processor that turns my custom markup into
    something that doxygen understands. The implemented macros are part of the
    set of features I would like to have. The macro processor can be found here:
    
    http://github.com/milasudril/doxymax

**Comment by albert-github** [comment]
@milasudril Did you test it already?
In case of problems: 
- please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.
- Please also specify the full doxygen version used (`doxygen -v`).

**Comment by milasudril** [comment]
I would close this issue for now
