### ISSUE TITLE
<content> tag on partial classes is ignored in C# XML comments (Origin: bugzilla #730579)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5490]
status NEW severity *minor* in component *build* for *---*
Reported in version *1.8.6* on platform *Other*
Assigned to: Dimitri van Heesch

On 2014-05-22 12:05:16 +0000, Georges DupÃ©ron wrote:

    The use of the <content> tag to document partial classes is recommended by
    StyleCop, a source analysis tool for C# (see
    http://stylecop.soyuz5.com/SA1601.html), even though it is not part of the
    official Microsoft list of recommended tags.
    
    Example:
    
    // <summary>The summary.</summary>
    // <content>The content.</content>
    public partial class MyClass { }
    
    // <content>Generated code.</content>
    public partial class MyClass { }
    
    Generated HTML:
    
        The summary.
        <content>The content.</content>
        <content>Generated code.</content>
    
    Expected result: Something similar to:
    
        The summary
        <h2>Contents of partial class in <a
    href="path/to/filename.cs">path/to/filename.cs</a></h2>
        The content
        <h2>Contents of partial class in <a
    href="path/to/generated.cs">path/to/generated.cs</a></h2>
        The Generated

On 2014-05-22 12:12:16 +0000, Georges DupÃ©ron wrote:

    Link to the list of tags recommended by Microsoft for XML comments in C#:
    http://msdn.microsoft.com/en-us/library/5ast78ax.aspx

**Comment by albert-github** [comment]
> The use of the <content> tag to document partial classes is recommended by
StyleCop, a source analysis tool for C# (see
http://stylecop.soyuz5.com/SA1601.html), even though it is not part of the
official Microsoft list of recommended tags.

It is still (2024-09-03) not mentioned on the given in http://msdn.microsoft.com/en-us/library/5ast78ax.aspx / https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags?redirectedfrom=MSDN nor in the ECMA-334 7th-edition December 2023 standard.

It is also unclear what the `<content>` tag should do.

Seen the above I think it is not something that should be included in doxygen
