### ISSUE TITLE
Public and protected properties are listed together (Origin: bugzilla #732817)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5516]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.7* on platform *Other*
Assigned to: Dimitri van Heesch

On 2014-07-07 01:33:42 +0000, qwertie256@gmail.com wrote:

    Doxygen does not distinguish at all between public and protected properties.
    They are in the same section and the word "protected" does not appear on
    protected properties.

On 2014-07-07 01:35:01 +0000, qwertie256@gmail.com wrote:

    (This bug applies to C#.)

**Comment by albert-github** [comment]
There is no example given so it is hard to imagine what is wrong

Setting issue to incomplete
