### ISSUE TITLE
Apitags.xml is incorrectly generated for base classes (Origin: bugzilla #733531)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5523]
status NEEDINFO severity *normal* in component *build* for *---*
Reported in version *1.8.7* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[files.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug733531_281360_files.zip/download/download)_ (ID 281360)
- _[ZipCallback.h](https://sourceforge.net/projects/doxygen/files/attachments/bug733531_281361_ZipCallback.h/download/download)_ (ID 281361)
- _[files.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug733531_284358_files.zip/download/download)_ (ID 284358)

On 2014-07-22 08:03:10 +0000, Tadeusz Dracz wrote:

    Created attachment 281360
    All files mentioned in the description
    
    Starting from version 1.8.3, base classes have incorrectly generated
    <compound> elements (the <member> elements are missing).
    
    Having a structure as in the attached ZipCallback.h, the expected <compound>
    element is presented in the expected.txt file (that's how Doxygen versions
    prior to 1.8.3 generate it). But starting from version 1.8.3 the generated
    element looks as in the current.txt file (no <member> elements).
    
    The missing <member> elements from the <compound> element related to
    CZipCallback  struct are instead placed in the <compound> element related to
    the CZipActionCallback struct, which derives from CZipCallback.

On 2014-07-22 08:04:05 +0000, Tadeusz Dracz wrote:

    Created attachment 281361
    ZipCallback.h

On 2014-08-08 13:02:40 +0000, Dimitri van Heesch wrote:

    Hi Tadeusz,
    
    I assume that Apitags.xml is the name of the tag file generated by doxygen
    (GENERATE_TAGFILE option).
    
    I don't see anything wrong or missing in that file, so can you please attach
    a self-contained example (source+config file in a tar or zip) for which you
    verified it contains the problem?

On 2014-08-24 20:52:29 +0000, Tadeusz Dracz wrote:

    Created attachment 284358
    Full project

On 2014-08-24 20:56:15 +0000, Tadeusz Dracz wrote:

    (In reply to comment # 2)
    
    Yes, I meant the tag file generated by the GENERATE_TAGFILE option.
    
    I attached the full project. In older versions, the section for 
    <compound kind="struct">
        <name>CZipCallback</name>
    
    looks like in the expected.txt file. 
    
    The new versions generate the same section as empty. So there is no
    "Callback" function tag in that section and no "m_szExternalFile" variable.
    Both belong to CZipCallback.
    
    If you need anything else, just let me know.
    
    Regards,
    Tadeusz Dracz

**Comment by albert-github** [comment]
Generating the tag files for the versions 1.8.2, 1.8.3 and 1.9.1. I see in 1.8.2:
```
  <compound kind="struct">
    <name>CZipCallback</name>
    <filename>structCZipCallback.html</filename>
    <member kind="function" virtualness="pure">
      <type>virtual bool</type>
      <name>Callback</name>
      <anchorfile>structCZipCallback.html</anchorfile>
      <anchor>a27652d72804471adabcdcc18274bbbf5</anchor>
      <arglist>(ZIP_SIZE_TYPE uProgress)=0</arglist>
    </member>
    <member kind="variable">
      <type>CZipString</type>
      <name>m_szExternalFile</name>
      <anchorfile>structCZipCallback.html</anchorfile>
      <anchor>a132345e5a62fd08a249cabc01383af6f</anchor>
      <arglist></arglist>
    </member>
  </compound>
```
in  1.8.3:
```
  <compound kind="struct">
    <name>CZipCallback</name>
    <filename>structCZipCallback.html</filename>
  </compound>
```
in 1.9.1:
```
  <compound kind="struct">
    <name>CZipCallback</name>
    <filename>structCZipCallback.html</filename>
    <member kind="function" virtualness="pure">
      <type>virtual bool</type>
      <name>Callback</name>
      <anchorfile>structCZipCallback.html</anchorfile>
      <anchor>a27652d72804471adabcdcc18274bbbf5</anchor>
      <arglist>(ZIP_SIZE_TYPE uProgress)=0</arglist>
    </member>
    <member kind="variable">
      <type>CZipString</type>
      <name>m_szExternalFile</name>
      <anchorfile>structCZipCallback.html</anchorfile>
      <anchor>a132345e5a62fd08a249cabc01383af6f</anchor>
      <arglist></arglist>
    </member>
  </compound>
```

So it looks to me that the requested information is present and the problem has been solved in the mean time.
