### ISSUE TITLE
copydoc of a copydoc across classes does not generate documentation (Origin: bugzilla #733937)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5530]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.7* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[test.h](https://sourceforge.net/projects/doxygen/files/attachments/bug733937_281978_test.h/download/download)_ (ID 281978)
- _[Doxyfile](https://sourceforge.net/projects/doxygen/files/attachments/bug733937_281979_Doxyfile/download/download)_ (ID 281979)

On 2014-07-29 21:09:36 +0000, David Ritter wrote:

    Created attachment 281978
    Test Case
    
    Using doxygen 1.8.7 32-bit on Windows 7.
    
    Using the attached test case I see proper documentation for Class B
    generated, but the method in Class C does not have any generated
    documentation (it is a copydoc reference to a copydoc in class B).
    
    This was previously working in doxygen 1.8.3
    
    Attached are the testcase and doxygen file I used to reproduce this issue.

On 2014-07-29 21:09:58 +0000, David Ritter wrote:

    Created attachment 281979
    Doxygen project file

**Comment by cmorty** [comment]
As I'm also affected by this and the links are broken:

[Doxyfile](https://github.com/doxygen/doxygen/files/3186638/Doxyfile.txt)
[test.h](https://github.com/doxygen/doxygen/files/3186639/test.h.txt)

Note, I can only upload `.txt` files.

**Comment by albert-github** [comment]
@cmorty can you be a bit more specific about "the links are broken"?

**Comment by cmorty** [comment]
@albert-github Ok, my problem was that doxygen was confused by an __attribute__. None the less the test case presented still fails.

**Comment by albert-github** [comment]
In the test case we have that in the class C there is a reference to an operator in class B and this operator references another operator in the same class as itself.

When using copydoc it says: 

> Copies a documentation block from the object specified by <link-object> and pastes it at the location of the command.

So in the class C we have:
```
* @copydoc B::operator[](char)const
```
this translates into:
```
* @copydoc operator[](char)
```
but in the class C we don't have `operator[](char)` so we get the warning message.
When in `class B` with the `B::operator[](char)const` we repolace:
```
* @copydoc operator[](char)
```
with
```
* @copydoc B::operator[](char)
```
it does work.

So when wants to use use `@copy...` command in a nested way one should always use a full qualified path.

I think this is usage.

**Comment by cmorty** [comment]
Hmm, the documentation _can_ be interpreted otherwise:

> Qualified names are only needed if the context in which the documentation block is found requires them.
>
> The \copydoc command can be used recursively, but cycles in the \copydoc relation will be broken and flagged as an error.

http://www.doxygen.nl/manual/commands.html#cmdcopydoc

I'd expect that if doxygen sees a copydoc it will recursively continue searching in that context.
