### ISSUE TITLE
Documentation page for empty class is not generated with SEPARATE_MEMBER_PAGES=YES (Origin: bugzilla #734332)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5541]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.8* on platform *Other*
Assigned to: Dimitri van Heesch

On 2014-08-06 06:03:08 +0000, kashej@sharklasers.com wrote:

    With SEPARATE_MEMBER_PAGES=YES  empty class documentation page is supposed
    to exist, but is not actually generated.
    
    Example code:
    namespace test {
      //! @brief Hidden
      class Hidden {
      };
      //! @brief Visible
      class Visible{
        private:
      };
    }
    
    Expected result: classes Hidden and Visible are documented on separate pages
    and listed as members of namespace "test".
    
    Actual result: classes Hidden and Visible are listed as members of namespace
    "test". The page for class Hidden is not generated. Links to Hidden
    documentation  are created in class list and in namespace "test"
    documentation, but are broken as they lead to non-existing page
    "html/classtest_1_1_hidden.html#classtest_1_1_hidden". Documentation page
    and links for class Visible are generated correctly.

On 2014-08-28 06:02:16 +0000, kashej@sharklasers.com wrote:

    This changed somewhat in 1.8.8, but the bug essentially is still there.
    
    Example C++ code (file test.h):
    //! @file
    namespace test {
      //! @brief Hidden
      //! @details Hidden details
      class Hidden {};
    }
    
    Expected result: separate page generated for class Hidden, with detailed
    description.
    
    Actual result: no separate page is generated for class Hidden; the detailed
    description of Hidden is put into file page; detailed description of Hidden
    is omitted from namespace page; links to Hidden lead to namespace page.

**Comment by albert-github** [comment]
The problems are reported against doxygen version 1.8.8 but at the time of reporting the first problem doxygen 1.8.8 was not yet release (it was released on August 21, 2014).
I tried to reproduce the problem (even with the versions 1.8.7 and 1.70 but didn't succeed so the original issue is incomplete
All tested with a Doxyfile just containing: `SEPARATE_MEMBER_PAGES=YES`


Also for the second issue it is unclear what is the problem.

Setting issue to incomplete
