### ISSUE TITLE
"remove" is treated as a keyword (green) in the source browser for C++ (Origin: bugzilla #734820)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5547]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.6* on platform *Other*
Assigned to: Dimitri van Heesch

On 2014-08-14 21:07:26 +0000, Adam Weiss wrote:

    but "remove" is not a keyword in C++.
    
    If you run this:
    
    -- test.cc
    void remove() { return; }
    main() { remove(); }
    --
    
    -- Doxyfile
    EXTRACT_ALL=YES
    SOURCE_BROWSER=YES
    --
    
    You'll see in html/test_8cc_source.html that remove has been treated as a
    keyword (green).  Also, as of recently in the master branch in git, I noted
    that remove is defined as a keyword in the parser in src/code.l:
    
    KEYWORD
    ("asm"|"__assume"|"auto"|"class"|"const"|"delete"|"enum"|"explicit"|"extern"|"false"|"friend"|"gcnew"|"gcroot"|"get"|"inline"|"internal"|"mutable"|"namespace"|"new"|"nullptr"|"override"|"operator"|"pin_ptr"|"private"|"protected"|"public"|"raise"|"register"|"remove"|
    ...
    
    Hope this helps!

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request#6410

**Comment by albert-github** [comment]
Code has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
