### ISSUE TITLE
Doxygen should support variadic predefined macros (Origin: bugzilla #735162)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5557]
status NEW severity *enhancement* in component *documentation* for *---*
Reported in version *1.8.7-GIT* on platform *Other*
Assigned to: Dimitri van Heesch

On 2014-08-21 13:57:32 +0000, pdaouadi@aldebaran.com wrote:

    When using the PREDEFINED option in the doxyfile, it is not allowed to make
    variadic macros, like:
    
    PREDEFINED= MYMACRO(...)=something
    
    It would be nice if we could also use the arguments:
    
    PREDEFINED= MYMACRO(...)=myfunction(__VA_ARGS__)

**Comment by albert-github** [comment]
In the version 1.8.7 (till 1.91) the variadic macros were not supported.
In version 1.9.2 the variadic macros are supported, see issue #8542 and pull #8544

So I think the problem has been solved in the mean time
