### ISSUE TITLE
DOT_GRAPH_MAX_NODES value in Doxyfile too low (Origin: bugzilla #736042)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5608]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.8* on platform *Other*
Assigned to: Dimitri van Heesch

On 2014-09-04 11:25:19 +0000, Richard Lloyd wrote:

    The default value of 50 for DOT_GRAPH_MAX_NODES (set in Doxyfile) is too low
    to process some of the files actually in doxygen's own source tree!
    
    Steps to reproduce:
    
    * Configure/build/install doxygen from source code (I was using version
    1.8.8).
    
    * At the top level of the doxygen source tree, type "doxygen".
    
    * Some of the files processed spit out warnings:
    
    warning: Included by graph for 'config.h' not generated, too many nodes.
    Consider increasing DOT_GRAPH_MAX_NODES.
    warning: Include graph for 'doxygen.cpp' not generated, too many nodes.
    Consider increasing DOT_GRAPH_MAX_NODES.
    warning: Included by graph for 'message.h' not generated, too many nodes.
    Consider increasing DOT_GRAPH_MAX_NODES.
    warning: Included by graph for 'util.h' not generated, too many nodes.
    Consider increasing DOT_GRAPH_MAX_NODES.
    
    To fix this, I edited Doxyfile to double the limit:
    
    DOT_GRAPH_MAX_NODES    = 100
    
    The warnings then disappeared when I cleaned/re-built the source code and
    re-ran doxygen on its own source code, so I suggest that this might be a
    suitable fix.

**Comment by albert-github** [comment]
It is up to the user to set the values in the doxygen configuration file and the default value of 50 for `DOT_GRAPH_MAX_NODES` looks like a sensible value to be able to see something in the graphs (especially when the format is png, for svg it could be larger as here we have better zoom possibilities).

For compatibility the value is left at 50.

Setting the issue to usage.
