### ISSUE TITLE
[PATCH] Cleanup not needed local variables in src/definition.cpp (Origin: bugzilla #736392)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5615]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.8-GIT* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[fix_CID-49998.patch](https://sourceforge.net/projects/doxygen/files/attachments/bug736392_285804_fix_CID-49998.patch/download/download)_ (ID 285804)

On 2014-09-10 09:15:18 +0000, Ettl Martin wrote:

    Created attachment 285804
    proposed fix
    
    Please review the attached patch. It simply cleans up two not needed
    variables in src/definition.cpp.
    
    This fixes Coverity Scan Issue CID-49998.
    
    Best regards and many thanks
    
    Martin Ettl

**Comment by albert-github** [comment]
In the current version the mentioned 2 lines are gone.

I think the problem has been solved in the mean time.
