### ISSUE TITLE
[PATCH] Fix another potential null pointer dereference in src/index.cpp (Origin: bugzilla #736393)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5616]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.8-GIT* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[fix_CID-49812.patch](https://sourceforge.net/projects/doxygen/files/attachments/bug736393_285805_fix_CID-49812.patch/download/download)_ (ID 285805)

On 2014-09-10 09:21:35 +0000, Ettl Martin wrote:

    Created attachment 285805
    proposed fix
    
    Please review the attached patch. It fixes a potential null pointer
    dereference in src/index.cpp.
    
    This fixes Coverity Scan Issue CID-49812.
    
    Best regards and many thanks
    
    Martin Ettl

**Comment by albert-github** [comment]
Checked the code and looks lie this fix has been applied by 48ced3ea8 (Fixed various issues found by PVS-Studio.) and is in 1.8.11

 I think the problem has been solved in the mean time.
