### ISSUE TITLE
[PATCH] Return with error in case a null pointer is provided to QBuffer::writeBlock (Origin: bugzilla #736394)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5617]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.8-GIT* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[fix_CID-49782.patch](https://sourceforge.net/projects/doxygen/files/attachments/bug736394_285806_fix_CID-49782.patch/download/download)_ (ID 285806)

On 2014-09-10 09:32:52 +0000, Ettl Martin wrote:

    Created attachment 285806
    proposed fix
    
    Please review the attached patch. It ensures, an error is returned in case a
    null pointer is provided to QBuffer::writeBlock().
    
    This fixes Coverity Scan Issue CID-49782.
    
    Best regards and many thanks
    
    Martin Ettl

**Comment by albert-github** [comment]
I think that applying this patch would be a good idea though I never saw the message associated with problem nor have I seen an issue regarding it.

**Comment by albert-github** [comment]
The qbuffer has been removed from doxygen (as have other Qt functions, some Qt names remain but got a new implementation).

I think the problem has been solved in the mean time.
