### ISSUE TITLE
[PATCH] Use const reference for read-only parameter in src/filedef.cpp (Origin: bugzilla #736513)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5619]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.8-GIT* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[cleanup.patch](https://sourceforge.net/projects/doxygen/files/attachments/bug736513_285965_cleanup.patch/download/download)_ (ID 285965)

On 2014-09-11 23:10:22 +0000, Ettl Martin wrote:

    Created attachment 285965
    proposed improvement
    
    Please review the attached patch. It simply changes a const parameter into a
    const reference for a function (read-only) parameter.
    
    Best regards and many thanks
    
    Martin Ettl

**Comment by albert-github** [comment]
Looks like the function that was using this function was commented out for a long time and now the code in this respect has been removed (in the current master).

I think that the problem has been solved in the mean time (as the routine was not called and now the code is removed).
