### ISSUE TITLE
Nested cond-endcond not working as expected (Origin: bugzilla #736553)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5620]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.8.8* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[checked_ptr.hh](https://sourceforge.net/projects/doxygen/files/attachments/bug736553_349627_checked_ptr.hh/download/download)_ (ID 349627)

On 2014-09-12 09:15:32 +0000, Peter Zajac wrote:

    The documentation of the \cond command states that conditional sections can
    be nested, however, it seems that the first \endcond command closes all
    nested \conds.
    
    Steps to reproduce:
    Copy and paste the example code below into a .cpp file and run doxygen
    without defining any of the conditional sections.
    
    Expected results:
    The documentation should contain only the empty namespace 'Foo', as the
    'Bar' class and all of its contents are hidden by the '\cond dummy' block.
    
    Actual results:
    The function 'visible' appears as a function inside the namespace 'Foo'.
    
    
    Example Code:
    /// Foo namespace
    namespace Foo
    {
      /// \cond dummy
      class Bar
      {
        /// \cond dummy2
        void invisible();
        /// \endcond
    
        void visible();
      };
      /// \endcond
    }

On 2017-04-10 21:37:24 +0000, Vlad Zolotarov wrote:

    The same issue with the Linux build: both with the in-box Ubuntu 16.04
    (1.8.11-1) and with the one built from the git (hash SHA:
    b91f4665693f52d02f18ee626ef201a8113321ff).
    
    In the code sample below the functions from the 'internal' namespace are
    'visible' in the generated documentation:
    
    
    ```
    /// \cond internal
    namespace internal {
    
    /// \name seastar::checked_ptr::get() helpers
    /// Helper functions that simplify the seastar::checked_ptr::get()
    implementation.
    /// @{
    
    /// Invokes the get() method of a smart pointer object.
    /// \param ptr A smart pointer object
    /// \return A pointer to the underlying object
    template <typename T>
    /// \cond GCC6_CONCEPT_DOC - nested '\ cond' doesn't seem to work
    GCC6_CONCEPT( requires requires (T ptr) {
        ptr.get();
    })
    /// \endcond
    inline typename std::pointer_traits<std::remove_const_t<T>>::element_type*
    checked_ptr_do_get(T& ptr) {
        return ptr.get();
    }
    
    /// Return a pointer itself for a naked pointer argument.
    /// \param ptr A naked pointer object
    /// \return An input naked pointer object
    template <typename T>
    inline T* checked_ptr_do_get(T* ptr) noexcept {
        return ptr;
    }
    /// @}
    }
    /// \endcond
    ```
    
    ```
    doxygen 2>&1 | grep checked_ptr
    Preprocessing /home/vladz/work/urchin/seastar/core/checked_ptr.hh...
    Parsing file /home/vladz/work/urchin/seastar/core/checked_ptr.hh...
    /home/vladz/work/urchin/seastar/core/checked_ptr.hh:100: warning: Compound
    checked_ptr is not documented.
    Generating code for file core/checked_ptr.hh...
    Gene/home/vladz/work/urchin/seastar/core/checked_ptr.hh:64: warning: Member
    checked_ptr_do_get(T &ptr) (function) of namespace seastar is not
    documented.
    Generating docs for file core/checked_ptr.hh...
    /home/vladz/work/urchin/seastar/core/checked_ptr.hh:121: warning: Member
    checked_ptr(std::nullptr_t) noexcept(std::is_nothrow_default_constructible<
    checked_ptr< Ptr, NullDerefAction >>::value) (function) of class checked_ptr
    is not documented.
    /home/vladz/work/urchin/seastar/core/checked_ptr.hh:122: warning: Member
    checked_ptr(Ptr &&ptr) noexcept(std::is_nothrow_move_constructible< Ptr
    >::value) (function) of class checked_ptr is not documented.
    /home/vladz/work/urchin/seastar/core/checked_ptr.hh:123: warning: Member
    checked_ptr(const Ptr &p) noexcept(std::is_nothrow_copy_constructible< Ptr
    >::value) (function) of class checked_ptr is not documented.
    Generating docs for compound checked_ptr...
    /home/vladz/work/urchin/seastar/core/checked_ptr.hh:64: warning: Member
    checked_ptr_do_get(T &ptr) (function) of namespace seastar is not
    documented.
    Generating docs for compound seastar::checked_ptr_is_null_exception...
    Generating docs for compound std::hash< seastar::checked_ptr< T > >...
    ```

On 2017-04-10 21:41:00 +0000, Vlad Zolotarov wrote:

    So, as you may see there is this:
    
    /home/vladz/work/urchin/seastar/core/checked_ptr.hh:64: warning: Member
    checked_ptr_do_get(T &ptr) (function) of namespace seastar is not
    documented.
    
    warning while this function should not have been processed at all.
    
    Removing the nested \cond \endcond section makes the issue disappear.

On 2017-04-10 21:45:04 +0000, Vlad Zolotarov wrote:

    Created attachment 349627
    The actual file to reproduce the issue

**Comment by albert-github** [comment]
The first problem is present in the 1.8.8 version but it is gone in the current doxygen version (1.9.6).
The second problem is present in the 1.8.13 version but is gone in the current doxygen version (1.9.6).

I think the problem has been solved in the mean time.
