### ISSUE TITLE
[PATCH] Remove not needed initialization of local variable in src/diagram.cpp (Origin: bugzilla #736793)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5625]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.8-GIT* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[cleanup.patch](https://sourceforge.net/projects/doxygen/files/attachments/bug736793_286361_cleanup.patch/download/download)_ (ID 286361)

On 2014-09-17 11:50:09 +0000, Ettl Martin wrote:

    Created attachment 286361
    proposed cleanup
    
    Please review the attached patch. It simply removes a not needed
    initialization of a local variable in src/diagram.cpp
    
    Best regards and many thanks
    
    Martin Ettl

**Comment by albert-github** [comment]
I've just moved this proposed patch in a bigger git proposed patch, pull request #8834

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.3.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
