### ISSUE TITLE
[PATCH] Improved const correctness in addon/doxmlparser/src/graphhandler.cpp (Origin: bugzilla #736948)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5629]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.8-GIT* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[cleanup.patch](https://sourceforge.net/projects/doxygen/files/attachments/bug736948_286581_cleanup.patch/download/download)_ (ID 286581)

On 2014-09-19 07:19:34 +0000, Ettl Martin wrote:

    Created attachment 286581
    proposed improvement
    
    Please review the attached patch. It simply improves const correctness in
    addon/doxmlparser/src/graphhandler.cpp.
    
    Best regards and many thanks
    
    Martin Ettl

**Comment by albert-github** [comment]
The doxmlparser has completely be rewritten in python, so the file graphhandler.cpp is not present anymore.

I think the patch / issue is obsolete.
