### ISSUE TITLE
[PATCH] Fix missing break in switch case statement (src/namespacedef.cpp) (Origin: bugzilla #737234)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5637]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.8-GIT* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[fix_CID-60551.patch](https://sourceforge.net/projects/doxygen/files/attachments/bug737234_286945_fix_CID-60551.patch/download/download)_ (ID 286945)

On 2014-09-24 06:16:01 +0000, Ettl Martin wrote:

    Created attachment 286945
    proposed fix
    
    Please review the attached patch. It fixes a missing break in
    src/namespacedef.cpp.
    
    This fixes coverity scan id 60551.
    
    Best regards and many thanks
    
    Martin

**Comment by albert-github** [comment]
At the moment of writing the issue there was a missing break statement in the switch / case (in NamespaceDef::writeTagFile). 
Currently all the cases have a break statement.

So I think the problem has been solved in the mean time.
