### ISSUE TITLE
[PATCH] Cleanup unused code in src/index.cpp (Origin: bugzilla #737244)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5640]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.8-GIT* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[cleanup.patch](https://sourceforge.net/projects/doxygen/files/attachments/bug737244_286953_cleanup.patch/download/download)_ (ID 286953)

On 2014-09-24 08:49:29 +0000, Ettl Martin wrote:

    Created attachment 286953
    proposed cleanup
    
    Please review the attached patch. It cleans up unused code in src/index.cpp.
    
    This fixes Coverity Scan Id: 49777
    
    Best regards and many thanks
    
    Martin Ettl

**Comment by albert-github** [comment]
The code as indicated in the patch is in the current version of doxygen.

I think the problem has been solved in the mean time
