### ISSUE TITLE
Ignore multi-line macro symbol for comments (Origin: bugzilla #737388)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5641]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.8.6* on platform *Other*
Assigned to: Dimitri van Heesch

On 2014-09-25 20:52:44 +0000, TheSpiritXIII@gmail.com wrote:

    If you have a macro such as this one in C/C++:
    #define FOO_FUNCTION \
     /** @brief This is a brief description of a \
                function. It spans multiple \
                lines. */
     void foo_function()
    
    Then, insert it into a struct:
    struct SomeClass
    {
     FOO_FUNCTION
    }
    
    Doxygen will then generate a brief comment for SomeClass::foo_function() of
    "This is a brief description of a \ function. It spans multiple \ lines" The
    '\' do not belong and should be filtered out.

**Comment by albert-github** [comment]
Assuming that when generating the issue the `\` after the last comment line and the `;` after the `()` got lost we see the problem with the 1.8.6 version of doxygen. With the current doxygen version (1.9.8) all looks OK:
![image](https://github.com/doxygen/doxygen/assets/5223533/9af1d509-0d33-4bac-b7cf-4e6fd63d8226)


So I think the problem has been solved in the mean time
