### ISSUE TITLE
[PATCH] Cleanup unused local variable in src/msc.cpp (Origin: bugzilla #737416)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5642]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.8-GIT* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[cleanup.patch](https://sourceforge.net/projects/doxygen/files/attachments/bug737416_287139_cleanup.patch/download/download)_ (ID 287139)

On 2014-09-26 09:49:07 +0000, Ettl Martin wrote:

    Created attachment 287139
    proposed cleanup
    
    Please review the attached patch. It cleans up an unused variable in
    src/msc.cpp.
    
    Best regards and many thanks
    
    Martin Ettl

**Comment by albert-github** [comment]
The MSC code has been integrated into doxygen and the mentioned file has slightly changed. The result of the process gives an exit code that is also used in the warning message.

I think the problem has been solved in the mean time.
