### ISSUE TITLE
Automatic details part ends up in wrong tag (Origin: bugzilla #737964)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5648]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.8* on platform *Other*
Assigned to: Dimitri van Heesch

On 2014-10-06 00:06:00 +0000, Ilya Ivanchenko wrote:

    Doxygen 1.8.8 generates unexpected and incorrect result for the following .c
    file:
    
    <code>
    /**
     * @file        somefile.c
     * @author      Some Dude (s.dude@somewhere.com)
     * @copyright   (c) 2014, SomeWhere, Inc.
     * @version     0.11
     * @date        5 October, 2014
     * @brief       Algorithms.
     *
     * Algorithms for some program.
     */
    </code>
    
    The output looks like this:
    ...
    Detailed Description
    
    Algorithms.
    
    Author
       Some Dude (s.dude@somewhere.com)
    Copyright
       (c) 2014, SomeWhere, Inc.
    Version
        0.11
    Date
        5 October, 2014 Algorithms for some program.
    
    The text "Algorithms for some program." that is expected to be in details,
    ends up as part of Date tag. In HTML markup it is inside "dd" tag for Date
    field.
    
    Adding @details before "Algorithms for some program." fixes the problem.

**Comment by albert-github** [comment]
In the 1.8.8 version we see:

![image](https://user-images.githubusercontent.com/5223533/122780398-19ddad00-d2af-11eb-89d8-1d4aff0e4779.png)

In the 1.9.1 version we see:
![image](https://user-images.githubusercontent.com/5223533/122780527-3548b800-d2af-11eb-9a0d-fa73cf0d531e.png)

this looks OK to me.

I think the problem has been solved in the mean time.
