### ISSUE TITLE
Inheritance by non-documented classes shows the name of the undocumented class (Origin: bugzilla #738840)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5661]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.6-GIT* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[br1.tgz](https://sourceforge.net/projects/doxygen/files/attachments/bug738840_288882_br1.tgz/download/download)_ (ID 288882)

On 2014-10-20 06:58:52 +0000, Sebastien Loriot wrote:

    Created attachment 288882
    test case
    
    Hi,
    
    I have the following example:
    
        /// this class is documented
        struct documented{};
    
        struct hidden : public documented {};
    
    setting HIDE_UNDOC_CLASSES     = YES
    
    Then in the documentation page of `documented` I can see:
    
        Inherited by hidden.
    
    Is it expected or is it a bug?
    Tested with 2eece646.
    
    
    Thanks,
    
    Sebastien.

**Comment by scott-zhong** [comment]
This bug is also affecting us.  Verified the problem exists with Doxygen 1.8.5, 1.8.9.1, 1.8.14 and master.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6633

**Comment by abbeybreeding** [comment]
This is still an issue in 1.11.0

**Comment by doxygen** [comment]
@abbeybreeding @scott-zhong Please verify if the referenced commit fixes the problem for you. Do not close the issue, this will be done automatically when the next official release becomes available.

**Comment by abbeybreeding** [comment]
@doxygen  Hello Dmitri,

I am still able to reproduce this with the current Doxygen main trunk in our source code. Is there anything else I should try?

Thanks :)

**Comment by abbeybreeding** [comment]
@doxygen Hello Dmitri!

Please ignore any previous message you saw from me. This latest commit did indeed fix our issue. 

Thank you so much, we look forward to the next release! :)

**Comment by scott-zhong** [comment]
@doxygen I have verified the fix. Thank you!!!

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.12.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
