### ISSUE TITLE
SQL Database Output (Origin: bugzilla #740687)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5682]
status NEW severity *enhancement* in component *build* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2014-11-25 13:49:43 +0000, pnordberg@googlemail.com wrote:

    Output the content of the documentation into a set of relational database
    tables.
    
    For example, a table of all the classes (with columns for the names, parent
    class etc.), another for the properties of classes (foreign keyed to the
    classes table), another for the functions of classes).
    
    This data is most readily available in the Data Organiser, before conversion
    to output formats.
    
    The benefit would be a documentation output format that is easily queried
    and restructured to suit integration into other systems.

On 2015-03-10 02:25:40 +0000, Travis wrote:

    Dual-purpose response:
    1.) pnordberg, there's already been a patch provided early last year which
    allows doxygen to output an sqlite3 database from the run.
    
    2.) the current implementation isn't complete or well-documented; many
    elements aren't converted at all, some which are have absent properties, and
    a number of the present properties are probably only decipherable to someone
    fairly aware of doxygen's internals.

**Comment by albert-github** [comment]
As written by Travis there is a sqlite3 implementation with a number of restrictions.
In case the current implementation is not sufficient a new issue should be opened indicating what is missing, together with an example etc.

I think this enhancement request is solved in the mean time.
