### ISSUE TITLE
build fails on ppc 10.5.8 (Origin: bugzilla #742884)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5718]
status NEEDINFO severity *normal* in component *build* for *---*
Reported in version *1.8.7* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[main.log](https://sourceforge.net/projects/doxygen/files/attachments/bug742884_295981_main.log/download/download)_ (ID 295981)

On 2015-01-13 21:33:25 +0000, xlf@gmx.com wrote:

    attempting to build (in gnuradio or stand alone) i repeatedly stumble:
    
    SyntaxError: invalid syntax
    gnumake[2]: *** [../generated_rc/doxygen/configoptions.cpp] Error 1
    gnumake[2]: Leaving directory
    '/opt/local/var/macports/build/_opt_local_var_macports_sources_rsnc.macports.org_release_ports_textproc_doxygen/doxygen/work/doxygen-1.8.7/src'
    gnumake[1]: *** [all] Error 2
    gnumake[1]: Leaving directory
    '/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_ports_textproc_doxygen/doxygen/work/doxygen-1.8.7/src'
    gnumake: Leaving directory
    '/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_ports_textproc_doxygen/doxygen/work/doxygen-1.8.7'
    Command failed:  cd
    "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_ports_textproc_doxygen/doxygen/work/doxygen-1.8.7"
    && /usr/bin/gnumake -w all
    Exit code: 2
    Error: org.macports.build for port doxygen returned: command execution
    failed
    DEBUG:Error code: CHILDSTATUS 13418 2
    DEBUG:Backtrace: command execution failed while executing
    system -nice () $fullcmdstring
         ("eval" body line 1)
         invoked from within
    "eval system $notty $nice \$fullcmdstring"
         invoked from within
    "command_exec build"
         (procedure "portbuild::build_main" line 8)
         invoked from within
    "portbuild::build_main org.macports.build"
         ("eval" body line 1)
         invoked from within
    "eval $procedure $targetname"
    Warning: targets not executed for doxygen: org.macports.activate
    org.macports.build org.macports.destroot org.macports.install
    Please see the log file for port doxygen for details:
/opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_release_ports_textproc_doxygen/doxygen/main.log
    To report a bug, follow the instructions in the guide:
         http://guide..macports.org/#project.tickets
    Error: Processing of port doxygen failed
    bash-3.2$

On 2015-01-15 18:40:50 +0000, Dimitri van Heesch wrote:

    > SyntaxError: invalid syntax
    
    I need to file/line where this error happens. It seems to be missing from
    the report.
    
    Can you please also check with the latest version (1.8.9.1)?

On 2015-02-02 21:28:49 +0000, xlf@gmx.com wrote:

    Created attachment 295981
    main log

On 2015-02-04 17:16:05 +0000, Daniel Macks wrote:

    Here's the key:
    
    :info:build   File "configgen.py", line 563
    :info:build     except Exception as inst:
    :info:build                       ^
    :info:build SyntaxError: invalid syntax
    
    That syntax is only valid for python >= 2.6, but OS X 10.5 comes with
    python2.5. Here's some info on the variously-supported ways:
    
    http://stackoverflow.com/questions/2535760/python-try-except-comma-vs-as-in-
    except
    
    Looks like there's *no* single syntax that's supported back as far as 2.5
    while also being supported into python3.

On 2015-02-20 03:41:30 +0000, xlf@gmx.com wrote:

    So, I've downloaded Python 2.6.
    
    It's my understanding I can not (or should not) REPLACE 2.5 with 2.6 as OS X
    10.5.8 requires 2.5 (for something(s)).
    
    Can I download Doxygen using 2.6, and if so, what would that command line
    look like?

On 2015-02-21 10:44:20 +0000, albert wrote:

    I don't know if you will run into other problems with python 2.5 but you
    could also try to replace the:
      except Exception as inst:
    by
      except Exception:
    
    and 
      print(inst)
    by something like:
      print("Problem reading the 'config.xml' file")

On 2015-02-21 17:49:25 +0000, Daniel Macks wrote:

    You definitely shouldn't replace apple-supplied (/usr/bin /usr/lib and
    friends) things. But you can install separately at other places
    (/usr/local/bin for example). Then you can put your new bin in your PATH env
    var and it will be seen. Or many build scripts let you pass an explicit
    PYTHON=/usr/local/bin/python2.6 or similar in order to hardcode exactly what
    python to use rather than searching various places.

On 2015-07-21 12:08:06 +0000, albert wrote:

    Seen the fact that the documentation of doxygen states that python has to be
    v2.6 or higher and the fact that it is possible to use a newer version of
    python than the supplied one with the OS (seen the discussion above). I
    think the bug should be set RESOLVED WONTFIX

**Comment by albert-github** [comment]
As written in the last comment I think that the status could be set to won't fix.
