### ISSUE TITLE
When generating csharp documentation "package" is used instead of "namespace" in several places (Origin: bugzilla #744670)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5737]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.9.1-GIT* on platform *Other*
Assigned to: Dimitri van Heesch

On 2015-02-17 15:57:20 +0000, rconde01@hotmail.com wrote:

    This can be seen on Namespace reference pages.

On 2015-02-17 16:39:01 +0000, rconde01@hotmail.com wrote:

    https://github.com/doxygen/doxygen/pull/300

**Comment by albert-github** [comment]
I think the problem can be solved by means of the pull request #300
