### ISSUE TITLE
C# enum members are not marked as strong (Origin: bugzilla #744671)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5738]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.9.1-GIT* on platform *Other*
Assigned to: Dimitri van Heesch

On 2015-02-17 16:01:15 +0000, rconde01@hotmail.com wrote:

    This causes them to be listed in the namespace when in fact they are not
    namespace members.

On 2015-02-17 16:39:23 +0000, rconde01@hotmail.com wrote:

    https://github.com/doxygen/doxygen/pull/301

**Comment by albert-github** [comment]
The mentioned pull request #301 has been integrated in master on GitHub (available in 1.8.10)

I think the problem has been solved in the mean time.
