### ISSUE TITLE
<tt> blocks cause error "end of comment while expecting command </code>" (Origin: bugzilla #744840)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5745]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.9.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxygen-1.8.9.1-expectig-code-command.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug744840_297482_doxygen-1.8.9.1-expectig-code-command.zip/download/download)_ (ID 297482)

On 2015-02-20 05:37:55 +0000, Mikael Egevig wrote:

    I have a source file with this snippet in:
    
    -----------------------------------
    /** \file
     *  The definition of a reference to a non-terminal AST node (typically
    written <tt>... Name ...</tt>).
     */
    
    using System.Collections.Generic;
    
    using Org.Braceless.Bracell.Toolbox;
    
    namespace Org.Braceless.Bracell.Syntax
    {
        /** Represents a reference to a non-terminal on the \b left side of the
    equal sign: <tt>Node = ... Name ...</tt>. */
    	public class ReferenceNode : Node
    	{
    ---------------------------------
    
    Whenever Doxygen gets to parse this file, it emits these errors:
    
    ------------------------------------
    u:\Braceless\src\Bracell\src>doxygen
    (U:/Braceless/src/Bracell/src/Syntax/ReferenceNode.cs 32) warning: end of
    comment block while expecting command </code>
    (U:/Braceless/src/Bracell/src/Syntax/ReferenceNode.cs 22) warning: end of
    comment block while expecting command </code>
    (U:/Braceless/src/Bracell/src/Syntax/ReferenceNode.cs 32) warning: end of
    comment block while expecting command </code>
    (U:/Braceless/src/Bracell/src/Syntax/ReferenceNode.cs 22) warning: end of
    comment block while expecting command </code>
    (U:/Braceless/src/Bracell/src/Syntax/ReferenceNode.cs 21) warning: found
    </c> tag without matching <c>
    (U:/Braceless/src/Bracell/src/Syntax/ReferenceNode.cs 32) warning: end of
    comment block while expecting command </code>
    (U:/Braceless/src/Bracell/src/Syntax/ReferenceNode.cs 32) warning: end of
    comment block while expecting command </code>
    (U:/Braceless/src/Bracell/src/Syntax/ReferenceNode.cs 32) warning: end of
    comment block while expecting command </code>
    (U:/Braceless/src/Bracell/src/Syntax/ReferenceNode.cs 31) warning: found
    </c> tag without matching <c>
    (<U:/Braceless/src/Bracell/src/Syntax/> 2) warning: end of comment block
    while expecting command </code>
    (U:/Braceless/src/Bracell/src/Syntax/ReferenceNode.cs 32) warning: end of
    comment block while expecting command </code>
    (U:/Braceless/src/Bracell/src/Syntax/ReferenceNode.cs 32) warning: end of
    comment block while expecting command </code>
    (U:/Braceless/src/Bracell/src/Syntax/ReferenceNode.cs 22) warning: end of
    comment block while expecting command </code>
    -------------------------------------
    
    There are several issues:
    
    1. The comment in the source file is correct to be best of my knowledge.
    2. Doxygen spits out errors as if there were dozens of errors in the
    comments.

On 2015-02-20 18:18:49 +0000, albert wrote:

    I tried the small example with a default Doxyfile (doxygen -g) but I didn't
    get any warning message. When enabling GENERATE_DOCBOOK I didn't get any
    warnings either (did a quick grep in the source code and it looks like this
    is set).
    
    Can you please attach a self-contained example (source+config file in a tar
    or zip) that allows me to reproduce the problem?

On 2015-02-21 08:46:12 +0000, Mikael Egevig wrote:

    Created attachment 297482
    Source to reproduce bug 744840
    
    As requested, this source archive reproduces the issue.  Simply unpack to a
    newly created temporary directory and run "doxygen" without any arguments.

On 2015-02-21 10:20:20 +0000, albert wrote:

    With the supplied example the problem is reproducible.
    
    The problem is caused by the setting of JAVADOC_BRIEF=YES. In this case the
    ... is seen as the end of the brief description of the namespace / file and
    thus splitting the <tt> </tt> pair over the brief and detailed description.
    Solution is to set either JAVADOC_BRIEF to NO or to use &hellip; to
    represent the 3 dots.

On 2015-02-21 10:41:23 +0000, Mikael Egevig wrote:

    Thank you.  I will use &hellip;.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #8611

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.2.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
