### ISSUE TITLE
Revert default of HMTL_TIMESTAMP or remove time stamp altogether (Origin: bugzilla #745316)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5751]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.8.8* on platform *Other*
Assigned to: Dimitri van Heesch

On 2015-02-28 00:06:49 +0000, W. Martin Borgert wrote:

    For reproducible builds, time stamps are annoying. Doxygen creates such time
    stamps by default. It would be nice to either remove the time stamps
    completely, or at least change the default to not generating them. IMHO,
    tools should make reproducible builds easy and by default. People at Debian,
    S.u.S.E. and others are working on reproducible builds and such a change
    would help them.

**Comment by simevo** [comment]
this is how we patch it:
https://salsa.debian.org/paolog-guest/doxygen/blob/master/debian/patches/no-timestamps.diff

**Comment by albert-github** [comment]
There was also the request #5753 (PATCH: please consider making doxygen output byte for byte identical between individual runs by default) which was incorporated in the 1.8.10 version, so the default for `HTML_TIMESTAMP` is now `NO`

So I think the problem has been solved in the mean time.
