### ISSUE TITLE
Alignment of msc images (Origin: bugzilla #745364)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5752]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.8.8* on platform *Other*
Assigned to: Dimitri van Heesch

On 2015-03-01 12:11:42 +0000, roykrikke@gmail.com wrote:

    How can I align msc images in doxygen? See example in attachment.
    
    To align normal images I use a project css file with:
    .image
    {
        text-align: left;
    }
    
    The HTML code of a image looks something like:
    <div class="image">
    <img src="image.jpg" alt="image.jpg">
    </div>
    
    In doxygen my msc:
      \msc
      arcgradient = 8;
      a [label="Client"],b [label="server"];
      a=>b [label="COMMAND"];
      \endmsc
    
    Compared to an msc image:
    <div align="center">
    <img src="msc_inline_mscgraph_1.png" alt="msc_inline_mscgraph_1"
    usemap="#msc_inline_mscgraph_1.map" border="0">
    <map name="msc_inline_mscgraph_1.map" id="msc_inline_mscgraph_1.map"></map>
    </div>
    
    There is no div class for the msc images. So how to align them to the
    left for example?

On 2015-03-01 12:34:31 +0000, roykrikke@gmail.com wrote:

    I think a change is file: htmldocvisitor.cpp @line number 464 is needed.
    
    For example:
    [code]
    m_t << "<div align=\"center\">" << endl;
    [/code]
    to
    [code]
    m_t << "<div class=\"image\">" << endl;
    [/code]
    
    This is the same behavior at function "void
    HtmlDocVisitor::visitPre(DocImage *img)" of line 1423 (exact line number
    1435).

**Comment by albert-github** [comment]
In pull request #529 (in doxygen version 1.8.13) an even more flexible approach has been chose by using `mscgraph`, `dotgraph` and `plantumlgraph` as classes.

I think the problem has been solved in the mean time.
