### ISSUE TITLE
Link to function is pointing to wrong file when there are two files with similar names (Origin: bugzilla #746140)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5758]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.9.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[example.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug746140_299289_example.zip/download/download)_ (ID 299289)

On 2015-03-13 09:38:52 +0000, Uwe Scholz wrote:

    Created attachment 299289
    Minimal example for this bug report
    
    Initial situation:
    ==================
    
    Consider two files, foo.c and foo_1.c. In each of these files the function
    "short bar(short a)" is defined. In foo.c, bar(short) is referred to in the
    file documentation via "@link bar(short) @endlink"
    
    Actual result:
    ==============
    
    When bar(short) is referred with a link in foo.c, the HTML link points to
    bar(short) in foo_1.c.
    
    Expected result:
    ================
    
    The HTML link which is generated with the @link command should point to
    bar(short) in foo.c, as this is the closest occurrence of that function.
    
    
    Remarks:
    ========
    
    The link points to bar(short) in foo[XXX].c, where [XXX] can be anything, I
    tested several cases like foo_2.c, foo1.c and fooXXX.c. Even when the second
    file is named "xxxfoo.c", the HTML link for bar(short) points to bar() in
    xxxfoo.c!
    
    The link does correctly point to bar() in foo.c only when the second file is
    renamed from foo_1.c to e.g. sample.c.
    
    I have generated a minimal example and attached it to this report.

**Comment by albert-github** [comment]
The suggestion "generated with the @link command should point to bar(short) in foo.c, as this is the closest occurrence of that function." sounds at first glance reasonable though the problem here is that the function bar in the 2 files cannot be distinguished and that the code in this way isn't valid C code (as it cannot be used together).

I think the problem is usage.
