### ISSUE TITLE
Broken link in python documentation for module level methods (Origin: bugzilla #746264)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5762]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.9.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxygenBrokenLinkFiles.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug746264_299478_doxygenBrokenLinkFiles.zip/download/download)_ (ID 299478)

On 2015-03-16 01:08:30 +0000, Vince wrote:

    Created attachment 299478
    simple python file, config file, and resulting html documentation with
    broken link
    
    I have python code with module level functions and classes. The classes and
    its methods are documented fine in the html. When I try to document the
    module level functions, special commands such as @param aren't showing up in
    the documentation. I get the description and a link to "more", but the link
    doesn't go anywhere. The method signature also doesn't show up.
    
    I've been testing the problem on this simple python file:
    
    ## @file testfile.py
    #  @author me
    
    ##
    # a method
    # @param p - an integer
    def method(p):
        pass
        
    class b:
        ## @param self - this object
        def cl(self):
            pass
    
    So, the module level function "method" gets put under 
    the file "testfile.py" in the documentation.

On 2015-03-24 16:58:59 +0000, Vince wrote:

    I resolved this problem by switching all of the @file to @package and
    removing the .py extension from the file name. So, I don't know if the
    original problem is actually a bug, or if it was done that way by design.

**Comment by albert-github** [comment]
I tested it with version 1.8.9.1 and the problem as described exists
When running it with version 1.8.14 the problem does not exist anymore (the detailed description of the method 'method' is shown with the file, but the link is NOT OK).
When testing with the current development version the link is also OK, change probably due to #720.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
