### ISSUE TITLE
\todo at end of C# XML comment breaks following todo's (Origin: bugzilla #746419)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5765]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.9.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[todoBug.cs](https://sourceforge.net/projects/doxygen/files/attachments/bug746419_299764_todoBug.cs/download/download)_ (ID 299764)
- _[todoBug.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug746419_302444_todoBug.zip/download/download)_ (ID 302444)
- _[Doxygen-Bug-746419.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug746419_372119_Doxygen-Bug-746419.zip/download/download)_ (ID 372119)

On 2015-03-18 20:47:40 +0000, Arthur Ward wrote:

    Created attachment 299764
    Example C# file with a working and broken \todo command.
    
    When using C# XML documentation comments, the \todo command must be followed
    by a blank comment line. Otherwise, each of the remaining todo's in the code
    base will cause the following to be output by Doxygen, and the formatting of
    the remaining todo's on the todo page is lost:
    
    ASSERT: "0" in ..\src\docparser.cpp (5666)
    todo:2: warning: Unexpected tag <dd> found

On 2015-04-26 10:49:02 +0000, Dimitri van Heesch wrote:

    Hi Arthur,
    
    I didn't manage to trigger the assert or the warning while running
    doxygen-1.8.9.1 on your example using a default configuration file.
    
    Can you please attach a more complete example (source + config file in a zip
    or tar) for which you verified it triggers the problem?

On 2015-04-27 14:08:18 +0000, Arthur Ward wrote:

    Created attachment 302444
    Input, config, stdout & stderr from run, and output showing bug.
    
    Sorry, I didn't realize it wasn't exactly the default config. I've included
    the result of "doxygen > build.log 2>&1" as well so you can see what happens
    for me. Thanks for looking in to this!

On 2018-05-16 10:36:30 +0000, Clemens wrote:

    Created attachment 372119
    minimal working example

On 2018-05-16 10:43:47 +0000, Clemens wrote:

    Hello
    
    With Doxygen 1.8.14 I have the same issue with the \todo command being used
    inside C# XML comments.
    
    Warnings are generated inside the log-file:
      "warning:Unexpected tag dd found"
    
    Except the warning, the problem is that the HTML output of the TODO list (at
    "related pages") is damaged.
    
    Note that technically the TODO list is made from a HTML "description list"
    which may explain the mysterious warning about the <dd> tag.
    
    I have attached a minimal working example.
    
    I can confirm that entering a empty comment line after the \todo
    mysteriously improve the situation.
    In my example code entering an empty comment line between line 38 and 39 is
    kind of work around.
    
    My suspicion is that Doxygen misses to "close" the \todo block at the moment
    when the </remarks> end-tag appears.
    
    best regards
    Clemens

On 2018-05-16 17:13:09 +0000, albert wrote:

    I've just pushed a proposed patch to github (pull request 728,
    https://github.com/doxygen/doxygen/pull/728).

On 2018-05-16 17:31:38 +0000, albert wrote:

    *** Bug 780174 has been marked as a duplicate of this bug. ***

**Comment by albert-github** [comment]
Pull request #728 integrated.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Comment by arthurward** [comment]
Confirmed fixed. Thank you!
