### ISSUE TITLE
Problem locating unresolvable @ref in case of a MSC image. (Origin: bugzilla #746577)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5767]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.8.9.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[msc_ref.taz](https://sourceforge.net/projects/doxygen/files/attachments/bug746577_300033_msc_ref.taz/download/download)_ (ID 300033)

On 2015-03-21 17:09:36 +0000, albert wrote:

    Created attachment 300033
    Problem locating unresolvable @ref in case of a MSC image.
    
    In case of an unresolvable @ref and textual documentation the warning
    message is like:
      msc_ref.h:3: warning: unable to resolve reference to `it' for @ref command
    
    In case the @ref is in an inline MSC image the warning message is like:
      <unknown>:11: warning: unable to resolve reference to `it' for \ref
    command
    in case of a large code base / lot of MSC images it is hard to locate the
    unresolvable @ref.
    (similar accounts for the @mscfile command).

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #10270

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request https://github.com/doxygen/doxygen/pull/10280 with an analogous fix for dot images

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.10.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
