### ISSUE TITLE
File not processed when using a Filter (Origin: bugzilla #748186)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5778]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.8* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[bash_test.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug748186_302002_bash_test.zip/download/download)_ (ID 302002)

On 2015-04-20 14:27:48 +0000, romanleitner@gmail.com wrote:

    Created attachment 302002
    example project
    
    I use the sed filter (https://github.com/Anvil/bash-doxygen) to document a
    bash/sh file and saw that starting from doxygen version 1.8.8 onwards the
    bash file will not be parsed anymore.
    
    
    >> LOG 
      Reading and parsing tag files
      Parsing files
      Preprocessing PATHTOFOLDER/bash_test/test.bash...
    << LOG
    
    I tried with version 1.8.7 and this works fine.
    
    >> LOG 
      Reading and parsing tag files
      Parsing files
      Preprocessing PATHTOFOLDER/bash_test/test.bash...
      Parsing file  PATHTOFOLDER/bash_test/test.bash...
    << LOG
    
    I saw the issue on Macosx Yosemite, LinuxMint 17.1 and RedHat6.
    
    I have attached a small zip file so that you can reproduce the behaviour
    
    br,
    Roman

**Comment by albert-github** [comment]
By default files were handled as C files, but this changed.
By setting `EXTENSION_MAPPING = bash=C` one gets the requested documentation again.

I think this is usage.
