### ISSUE TITLE
Inline comment at the end of comment blocks loose their brief description (Origin: bugzilla #748214)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5780]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.9.1-GIT* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[test.c](https://sourceforge.net/projects/doxygen/files/attachments/bug748214_302026_test.c/download/download)_ (ID 302026)
- _[test_8c.html](https://sourceforge.net/projects/doxygen/files/attachments/bug748214_302027_test_8c.html/download/download)_ (ID 302027)
- _[0001-Fixes-bug-748214-inline-comments-being-mis-rendered-.patch](https://sourceforge.net/projects/doxygen/files/attachments/bug748214_302028_0001-Fixes-bug-748214-inline-comments-being-mis-rendered-.patch/download/download)_ (ID 302028)

On 2015-04-20 20:33:25 +0000, Jonathan Duncan wrote:

    Created attachment 302026
    Test case that highlights error.
    
    An inline comment at the end of a comment block can sometimes loose it's
    brief description if the comment block is ended using the same doxygen
    comment syntax as the inline comment.
    
    For example:
    
        /// \name The first group
        ///@{
        #define DEFINE1 1 ///< define 1 
        #define DEFINE2 2 ///< define 2
        #define DEFINE3 3 ///< define 3
        ///@}
    
        /// \name The second group
        ///@{
        #define DEFINE4 4 ///< define 4 
        #define DEFINE5 5 ///< define 5
        #define DEFINE6 6 ///< define 6
        /**@*/
    
    DEFINE3 does not have a brief comment assigned to it but DEFINE6 does.

On 2015-04-20 20:34:18 +0000, Jonathan Duncan wrote:

    Created attachment 302027
    Invalid output of test case

On 2015-04-20 20:37:07 +0000, Jonathan Duncan wrote:

    Created attachment 302028
    patch of proposed fix.
    
    A github pull request has also been made.

On 2015-04-21 20:06:50 +0000, Jonathan Duncan wrote:

    The previous patch is a bad fix and breaks several tests.

**Comment by albert-github** [comment]
The example has a small flaw, the last line should not read (no warning with the doxygen 1.8.9.1 version but with the current 1.12.0 doxygen version):
```
/**@*/
```
but
```
/**@}*/
```

When using the example with the doxygen 1.8.9.1 version we see:
![image](https://github.com/user-attachments/assets/a47d291e-99cd-452a-9d6c-7c84161e3597)
and the "Macro Definition documentation" should not be there.

When changing the last line into
```
///@}
```
we not only get the "Macro Definition documentation"  for `Define2` but also for `Define6`.

When using the current 1.12.0 doxygen version the problem with the `/**@}*/` as well as the problems with the `///@}` are fixed i.e. no "Macro Definition documentation"  shown.

I think the problem has been solved in the mean time
