### ISSUE TITLE
Doxygen not creating call graphs for C# methods if namespace contains the classname (Origin: bugzilla #749049)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5784]
status NEW severity *normal* in component *general* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[DoxygenTestCases.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug749049_303001_DoxygenTestCases.zip/download/download)_ (ID 303001)
- _[Doxyfile_DoxygenTest2](https://sourceforge.net/projects/doxygen/files/attachments/bug749049_303002_Doxyfile_DoxygenTest2/download/download)_ (ID 303002)

On 2015-05-07 00:40:38 +0000, Ron Cresswell wrote:

    Created attachment 303001
    Contains 2 folders, each with project, Doxyfile and output.
    
    I am using Doxygen to create call and caller graphs for a large C# project
    which is a SharePoint 2010 solution. This solution has many components and I
    noticed that some of them (console applications for example) will happily
    create call graphs for the methods, but Workflows failed to create any call
    graphs.
    
    Further information - it does not appear to be the replicated namespace that
    triggers this, but possibly the depth.
    
    So - namespace DoxygenTest.Workflow1 containing class Workflow1 -> no graphs
    namespace DoxygenTest.WF containing class Workflow1 -> no graphs
    namespace DoxygenTest containing class Workflow1 -> graphs!
    
    Possibly the existence of a namespace with no classes (only sub namespaces)?
    
    I have attached two Visual Studio projects (DoxygenTest and DoxygenTest2).
    They are identical except that in the second I have replaced all occurances
    of "DoxygenTest2.Workflow1" in the namespace declarations with
    "DoxygenTest2" - this second project creates call and caller graphs as
    expected.

On 2015-05-07 00:46:06 +0000, Ron Cresswell wrote:

    Note: The Doxyfile zipped up with DoxygenTest2 might need some directories
    updating - the html output is ok, but I hadn't saved the Doxyfile when I
    zipped up the directories. I'll add the Doxyfile as another attachment for
    completeness.

On 2015-05-07 00:47:55 +0000, Ron Cresswell wrote:

    Created attachment 303002
    Updated Doxyfile for DoxygenTest2 project

**Comment by albert-github** [comment]
Pull request has been integrated in master.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
