### ISSUE TITLE
Logging useless (Origin: bugzilla #749998)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5792]
status NEEDINFO severity *normal* in component *general* for *---*
Reported in version *1.8.6* on platform *Other*
Assigned to: Dimitri van Heesch

On 2015-05-27 22:34:58 +0000, mattator@gmail.com wrote:

    I wish doxygen could log successful events along with warnings, it would
    help track down problems. I've spent a lot of time tracking down why my code
    was not documented, ie, due to a not closed "\verbatim".
    Maybe add a warning when doxygen reaches the end of a file without seeing
    \endverbatim ?

On 2015-05-28 16:32:27 +0000, albert wrote:

    Please check version 1.8.9.1. In case the problem persists in this version
    please attach an example (source + config file in a zip or tar) for which
    you verified it triggers the problem?

**Comment by albert-github** [comment]
Seen the facts:
- in case `\endverbatim` is missing currently a warning is emitted
- no further information is provided


I think the problem has been solved in the mean time
