### ISSUE TITLE
Detailed file documentation is being rolled into the author field (Origin: bugzilla #750331)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5795]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.9.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[testcase.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug750331_304482_testcase.zip/download/download)_ (ID 304482)

On 2015-06-03 11:14:15 +0000, Phil Pemberton wrote:

    Created attachment 304482
    Test case
    
    I have a project which includes Doxygen tags. These all follow the same
    pattern:
    
    /***
     * @file
     * @copyright Copyright goes here
     * @author Author name
     * @brief Brief description
     *
     * Detailed description goes here. And some more
     */
    
    The problem I have is that the detailed description is being erroneously
    rolled into the author field, contrary to how Doxygen's documentation says
    this should work (the author field ends at EOL and the brief description
    ends at the paragraph break).
    
    If I add an @details tag before the detailed description, this works as
    expected.
    
    I've attached a test case which demonstrates the bug.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6537

**Comment by albert-github** [comment]
Problem looks like to be solved in the mean time (tested against doxygen 1.9.2).
