### ISSUE TITLE
add option to build man pages without timestamps (Origin: bugzilla #750447)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5797]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2015-06-05 10:19:40 +0000, marivalenm@gmail.com wrote:

    Hello,
    
    Doxygen offers the option to omit HTML timestamps by setting HTML_TIMESTAMP
    option to NO but, it does not offer the option the omit timestamps from man
    pages.
    
    This will allow to generate documentation that is bit-wise identical between
    different compilation runs which makes it easier to verify that a given
    binary was indeed generated from a given source.
    
    This issue is similar to the following bugs: 
    - Bug 745439 - PATCH: please consider making doxygen output byte for byte
    identical between individual runs by default
    - Bug: 744938 - PATCH: add option to build latex without timestamps
    - Bug: 646436 I'd like a man output configuration option like HTML_TIMESTAMP
    for footers.
    
    So maybe instead it makes sense to add an option to disable timestamps
    everywhere as suggested by a comment in bug 744938?
    
    Kind Regards,
    akira

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #10045

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.7.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
