### ISSUE TITLE
Doxygen apparently does not search all directories listed in the PATH environment variable. (Origin: bugzilla #750814)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5802]
status NEEDINFO severity *normal* in component *general* for *---*
Reported in version *1.8.9* on platform *Other*
Assigned to: Dimitri van Heesch

On 2015-06-11 23:13:00 +0000, Jack Bennett wrote:

    In order to avoid the "... not found; check your TEX installation!" warning
    when generating Latex output, I had to create two links in /usr/bin:
       sudo ln -s /usr/texbin/epstopdf /usr/bin/epstopdf
       sudo ln -s /usr/local/bin/gs /usr/bin/gs
    However, both epstopdf and gs were already available from the command line
    via directories listed in the PATH environment variable. I conclude that
    Doxygen does not look at all paths listed in PATH to find all its necessary
    components. This seems like odd behavior.
    
    I run Doxygen 1.8.9 using DoxyWizard on Mac OS X Yosemite.

On 2015-07-30 19:13:20 +0000, Dimitri van Heesch wrote:

    doxygen doesn't search the path itself, the shell (=bash) does this.
    
    If you run doxygen from doxywizard, and launch doxywizard from the finder,
    it will use the path environment as set globally by the system, which is
    probably different from the path you have set in your local bash shell.
    
    So you probably need to set the path in /etc/bashrc or run doxywizard from
    your terminal that has the correct path set.
    
    Let me know if this helps.

On 2015-07-30 21:38:28 +0000, Jack Bennett wrote:

    Thanks for the explanation, Dmitri. No doubt this was the problem -- I do
    run Doxywizard from the Finder, but I was looking at the shell's PATH. I
    didn't know they were different. I'll adjust the path in /etc/bashrc.

**Comment by albert-github** [comment]
Seen the comments, this is not a doxygen problem but usage.
