### ISSUE TITLE
Predefined macros are handled incorrectly in source browser (Origin: bugzilla #751023)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5805]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.9.1-GIT* on platform *Other*
Assigned to: Dimitri van Heesch

On 2015-06-16 01:29:32 +0000, Mikhail Maltsev wrote:

    Consider the following example:
    
    $ cat ./Doxyfile
    EXTRACT_ALL            = YES
    SOURCE_BROWSER         = YES
    GENERATE_HTML          = YES
    GENERATE_LATEX         = NO
    MACRO_EXPANSION        = YES
    EXPAND_ONLY_PREDEF     = YES
    PREDEFINED             = GTY(x)=
    
    $ cat ./test.cpp
    #define GTY(x)
    struct GTY("%") bug {
      int field;
    };
    
    $ doxygen ./Doxyfile
    
    Doxygen seems to parse the source correctly, i.e. "struct bug" and it's data
    member are both present in the generated documentation. However, the source
    code page is generated incorrectly: identifiers "bug" and "field" are
    highlighted as if they were inside a string literal, and no links are
    created.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #9342

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.5.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
