### ISSUE TITLE
functions of the class are  not documented in the .h file (Origin: bugzilla #751399)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5810]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.8.9.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2015-06-23 16:55:44 +0000, itia wrote:

    functions of the class are not documented in the .h file in the
    documentation. And are displayed on a separate page at the beginning of the
    documentation in section of  "brief description of classes".
    What can I do  (how to documentthe .h file and what configuration  should I
    specify in doxywizard)to eliminate this section "brief description of
    classes" at the beginning documentation,  and to display in RTF(in
    documentation)  all the functioons of the class in .h file.
    
    Thank you very much for your help.

**Comment by albert-github** [comment]
It is a bit unclear what the user wants to see, but most likely this can be accomplished by means of the settings in the layout file.
As there is no example it is a bit hard to test.

Setting the issue to  not complete.
