### ISSUE TITLE
Main page absent in TOC of CHM, if PROJECT_NAME is empty (Origin: bugzilla #751700)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5818]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.10* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[result.png](https://sourceforge.net/projects/doxygen/files/attachments/bug751700_306369_result.png/download/download)_ (ID 306369)
- _[example.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug751700_306370_example.zip/download/download)_ (ID 306370)

On 2015-06-30 07:59:07 +0000, Eugene wrote:

    Created attachment 306369
    Examples for non-empty and empty PROJECT_NAME
    
    If PROJECT_NAME is set to none (empty string), main page does not appear in
    table of contents of HtmlHelp (CHM).

On 2015-06-30 08:00:47 +0000, Eugene wrote:

    Created attachment 306370
    Example for reproduction

On 2015-06-30 08:36:52 +0000, Eugene wrote:

    More info: if PROJECT_NAME is equal to title of mainpage, again the same
    problem takes place (main page does not appear in TOC).

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6542

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
