### ISSUE TITLE
Warning about clang options and clang assisted parsing appear on previously run doxyfiles (Origin: bugzilla #751706)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5820]
status NEEDINFO severity *minor* in component *doxywizard* for *---*
Reported in version *1.8.10* on platform *Other*
Assigned to: Dimitri van Heesch

On 2015-06-30 09:34:23 +0000, Paul A. Bristow wrote:

    Doxywizard opens a command windows (DOS box) whne starting the doxywizard
    (that didn't happen before 1.8.10)
    
    and running previously OK doxyfiles always produces messages like this.
    
    warning: ignoring unsupported tag `CLANG_ASSISTED_PARSING' at line 1046,
    file I:
    /modular-boost/libs/fixed_point/doc/doxygen/fixed_point_doxyfile.txt
    warning: ignoring unsupported tag `CLANG_OPTIONS' at line 1054, file
    I:/modular-
    boost/libs/fixed_point/doc/doxygen/fixed_point_doxyfile.txt
    Invalid option: CLANG_OPTIONS
    Invalid option: CLANG_ASSISTED_PARSING
    
    Line 1046 contains this
    
    VERBATIM_HEADERS       = YES
    
    and 1054 is a comment, so I think the line numbers are confusing.
    There are no mentions of 'clang' in the text.
    
    There is no settings for parsing except Microsoft CLI.
    
    Adding to the end of the doxyfile
    
    CLANG_ASSISTED_PARSING = NO
    
    leads to this message
    
    warning: ignoring unsupported tag `CLANG_ASSISTED_PARSING' at line 2437,
    file I:
    /modular-boost/libs/fixed_point/doc/doxygen/fixed_point_doxyfile.txt
    Invalid option: CLANG_OPTIONS
    Invalid option: CLANG_ASSISTED_PARSING
    
    
    (actually I'd like to use Clang for template-heavy C++, but examples of
    setup would be helpful).

On 2018-02-28 13:55:59 +0000, albert wrote:

    I tried to reproduce the behavior (on Windows 7) as described in the bug
    report, but was not able to.
    
    - When starting the 1.8.10 version of doxywizard no command window appeared
    - I was not able to get the CLANG warning messages either (looks like an
    older version of doxygen is run from the GUI, but I cannot confirm this does
    not happen in my tests).
    
    Please recheck with the current version of doxywizard and doxygen.
    
    In case the problem persists please
    - describe the steps taken (including the starting point  / files present)
    - attach a small example with the used Doxyfile and other relevant files.

**Comment by albert-github** [comment]
Looks like there is no new information. Also the current version is 1.9.1 so I think this issue can be closed as "not complete".
