### ISSUE TITLE
make.bat on UNC paths will start to erase files from c:\windows\system32 (Origin: bugzilla #752410)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5828]
status NEEDINFO severity *critical* in component *general* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2015-07-15 09:37:15 +0000, Lorenzo Delana wrote:

    I'll report the problem that come with the make.bat on the latex folder for
    Windows platforms, when you run that from a network folder,
    the problem is that the cd will fail to enter the UNC path and the purging
    del /s /f will start immediately on c:\windows...
    
    Repro:
    ---------
    to try that please edit the make.bat and insert a pause before the delete
    command and comment it out for security too, you will see the batch fail to
    change folder and will stay on c:\windows
    
    pause
    rem del /s /f *.ps *.dvi *.aux *.toc *.idx *.ind *.ilg *.log *.out *.brf
    *.blg *.bbl refman.pdf
    
    Fix:
    ---------
    I suggest to insert a double check after the cd /D to verify if the current
    working path is the one expected, and if not prompr that and don't continue.

On 2015-07-18 18:08:08 +0000, Dimitri van Heesch wrote:

    a better solution may be to use pushd.
    
    Can you check if it works correctly if you replace the commands
    
    set Dir_Old=%cd%
    cd /D %~dp0
    
    at the start of the batch file by
    
    pushd %~dp0
    
    ?

On 2015-07-18 21:01:58 +0000, Lorenzo Delana wrote:

    It works thanks, I readed about pushd command but I wasn't sure that it
    could works if all unit letters A-Z of drives are already allocated ( it may
    happens ).
    
    I suggest then to add an extra check like the follow :
    
    @echo off
    
    rem set Dir_Old=%cd%
    rem cd /D %~dp0
    
    pushd %~dp0
    
    if exist doxygen.sty goto pathok
    	
    echo ----
    echo Failed to change path to %~dp0"
    echo ----
    pause
    exit
    
    :pathok
    
    del /s /f *.ps *.dvi *.aux *.toc *.idx *.ind *.ilg *.log *.out *.brf *.blg
    *.bbl refman.pdf
    
    pdflatex refman
    ...

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #9872

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.7.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
