### ISSUE TITLE
PLANTUML_JAR_PATH Environment Variable Needs Documenting (Origin: bugzilla #753629)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5844]
status NEW severity *normal* in component *documentation* for *---*
Reported in version *1.8.9.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2015-08-14 13:03:15 +0000, Marc Alff wrote:

    Using doxygen 1.8.9.1 and PLANTUML
    
    File Doxyfile contains
    PLANTUML_JAR_PATH = /home/malff/plantuml/plantuml.jar
    
    The jar file itself contains
    jar -xf /home/malff/plantuml/plantuml.jar META-INF/MANIFEST.MF
    cat META-INF/MANIFEST.MF
    Manifest-Version: 1.0
    Ant-Version: Apache Ant 1.9.4
    Created-By: 1.8.0_31-b13 (Oracle Corporation)
    Main-Class: net.sourceforge.plantuml.Run
    
    And doxygen invokes PLANTUML with something similar to
    java -jar <<value of PLANTUML_JAR_PATH>> pufile
    
    Generation of UML diagrams with @startuml @enduml works fine,
    -- on my local machine only --.
    
    Now, working in a distributed team, where different developers
    or build hosts all look at the same source code (in git),
    generation of PLANTUML diagrams is broken for other people,
    because the plantuml.jar file is not installed in the same place.
    
    Expectation:
    The content of Doxyfile should not contain paths
    that ultimately depends on the platform / machine running doxygen,
    so that file Doxyfile can be checked in with source control management.
    
    Suggestion:
    Do not invoke java with a -jar file, use this instead:
    
    1) When PLANTUML_JAR_PATH is specified in Doxyfile,
    
    java -classpath <<value of PLANTUML_JAR_PATH>> net.sourceforge.plantuml.Run
    pufile
    
    This allows backward compatibility, for people who happen to use a well
    defined,
    known, stable, PLANTUML_JAR_PATH.
    
    Or consider just dropping PLANTUML_JAR_PATH, see 2) below.
    
    2) When PLANTUML_JAR_PATH is not specified in Doxyfile,
    
    Document that users must set their CLASSPATH environment variable
    before invoking doxygen with plantuml, as in
    
    export CLASSPATH=/home/malff/plantuml/plantuml.jar
    
    Invoke plantuml with
    java net.sourceforge.plantuml.Run pufile
    trusting the classpath to be correct.
    
    Note that the previous documented behavior,
    "PLANTUML_JAR_PATH is empty and therefore @startuml is ignored"
    can not longer be supported.
    
    Thanks for this great tool, and for considering to fix this bug.

On 2015-08-14 13:25:11 +0000, Marc Alff wrote:

    I don't think it matters, but adding version info about plantuml just in
    case:
    
    malff@linux-4b1j:doxygen> java -jar /home/malff/plantuml/plantuml.jar
    -version
    PlantUML version 8028 (Fri Jul 10 21:00:41 CEST 2015)
    (GPL source distribution)
    OpenJDK Runtime Environment
    OpenJDK 64-Bit Server VM
    1.7.0_85-b01
    Linux

On 2015-08-15 14:05:15 +0000, albert wrote:

    When working in a team I assume you will have a common setup and there will
    also be environment variables setup for all members.
    When you setup e.g. YOUR_PLANTUML_PATH to the the plantuml.jar to be used
    and in the Doxyfile you specify:
    PLANTUML_JAR_PATH      = $(YOUR_PLANTUML_PATH)
    it should all work, without paths in the Doxyfile.
    
    Please have a look at this.

On 2015-08-17 08:08:23 +0000, Marc Alff wrote:

    
    Thanks Albert.
    
    Using an environment variable works well, so there is no bug in the tool
    itself, as this feature is already supported.
    
    Now, the fact that doxygen supports environment variables is new to me.
    Upon reading the doc again, the only reference I could find is:
    
    Section http://www.stack.nl/~dimitri/doxygen/manual/config.html
    which contains a single line about it:
      "Environment variables can be expanded using the pattern
    $(ENV_VARIABLE_NAME)."
    
    As other users are likely to miss this also, changing this report to
    category Documentation.
    
    Please consider making environment variables more covered (a dedicated
    section within config.html, that can be referenced ?), and/or add a
    reference to env variables from this text:
    
    # When using plantuml, the PLANTUML_JAR_PATH tag should be used to specify
    the
    # path where java can find the plantuml.jar file. If left blank, it is
    assumed
    # PlantUML is not used or called during a preprocessing step. Doxygen will
    # generate a warning when it encounters a \startuml command in this case and
    # will not generate output for the diagram.
    
    because the value of PLANTUML_JAR_PATH is very likely to depend on the
    environment, unlike other parameters.
    
    Regards,
    -- Marc

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #8832

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.3.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Comment by MarcoSauter** [comment]
@doxygen
Hey, I tried to render the PlantUML-Files with the doxygen version 1.9.3 but the PlantUML doesnt show up. I also added the PLANTUML_JAR_PATH Environment Variable. The not-rendered-PlantUML-text is also showing up a bit delayed. It shows up around 10 lines of text later.

**Comment by albert-github** [comment]
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

**Comment by MarcoSauter** [comment]
[example.zip](https://github.com/doxygen/doxygen/files/8563275/example.zip)

I created a small example. There is also the output in html.

**Comment by MarcoSauter** [comment]
[example.zip](https://github.com/doxygen/doxygen/files/8563349/example.zip)

I attached a small example with a example PlantUML.

**Comment by albert-github** [comment]
I tried your example with the 1.9.3 version and I got the the plantuml image.
- which wanings / errors did you get ? 
- can you rerun with `doxygen -q -d extcmd` and post the console output (don't forget to remove the `output` directory beforehand, as otherwise doxygen might think the images are already present)?

**Comment by MarcoSauter** [comment]
C:\Users\...\Documents\test>doxygen -q -d extcmd
C:/Users/.../Documents/test/src/example.md:1: warning: explicit link request to 'Example' could not be resolved
Executing external command `java -Djava.awt.headless=true -jar "../../Downloads/plantuml.jar" -o "C:/Users/.../Documents/test/output/html" -charset UTF-8 -tpng "C:/Users/.../Documents/test/output/html/inline_umlgraph_pnghtml.pu" `
Executing external command `dot "C:/Users/sauter-8/Documents/test/output/html/graph_legend.dot" -Tpng -o "C:/Users/.../Documents/test/output/html/graph_legend.png"`
C:/Users/.../Documents/test/output/html/graph_legend.dot:1: error: Problems running dot: exit code=-1, command='dot', arguments='"C:/Users/.../Documents/test/output/html/graph_legend.dot" -Tpng -o "C:/Users/.../Documents/test/output/html/graph_legend.png"'

**Comment by albert-github** [comment]
Strange.
- the plantuml command looks like to finish correctly (which version of plantuml are you using? `java -Djava.awt.headless=true -jar "../../Downloads/plantuml.jar"  -version`
- what happens when you run `java -Djava.awt.headless=true -jar "../../Downloads/plantuml.jar" -o "C:/Users/.../Documents/test/output/html" -charset UTF-8 -tpng "C:/Users/.../Documents/test/output/html/inline_umlgraph_pnghtml.pu" in a console window?
- when downloading your example and extracting it an trying to execute `output\htm\index.html` I got `Access is denied.`, might there be something with permission?
- regarding the `Problems running dot` you either haven't installed graphviz dot or it is not reachable through the PATH, but this has no influence on the plantuml problem.

**Comment by MarcoSauter** [comment]
So now its working. There was a little mistake with the Markdown-File...
The Header was `#Example` and I changed it to `# Example`.
After that fix your command just worked.
**BUT**
When I used the Doxywizard, the PNG of the PlantUML-Diagram was not created in the output folder.

**Comment by albert-github** [comment]
Very strange as I ran the source you provided and I got the right results (there was the `#Example` in the html file, instead of that it was put in the header), so this cannot explain why you didn't get the image.
Regarding the doxywizard, might be that it is started from a place you didn't expect and thus cannot fine some things. 
- did you get any warnings in the doxywizard?
- you can use in the `Specify additional ...` line in the run tab the `-q and -d extcmd` as well.

**Comment by MarcoSauter** [comment]
There are no warnings in Doxywizard.
Even with the parameters in `Specify additional ...` it's not working.
It's not creating an image of the PlantUML.
So I guess there is a other problem with Doxywizard.
When I used the Command Prompt to execute the doxygen command, it just worked.

**Comment by albert-github** [comment]
It looks like there is a small problem in the doxywizard as I see the warning:
```
D:/.../src/example.md:41: warning: ignoring \startuml command because PLANTUML_JAR_PATH is not set
```
although in the  expert tab I see that the `PLANTUML_JAR_PATH`is set to `..\plantuml.jar`.

I tried the current master version of the doxywizard:
![image](https://user-images.githubusercontent.com/5223533/165324727-e369dc62-3c28-4420-ba75-8920251edd18.png)

and here plantuml runs without problems.
