### ISSUE TITLE
Settings label on Markdown headers with level 2 and greater causes header to disappear (Origin: bugzilla #754350)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5850]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.10* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[output.txt](https://sourceforge.net/projects/doxygen/files/attachments/bug754350_310338_output.txt/download/download)_ (ID 310338)

On 2015-08-31 10:20:36 +0000, ulit@eikon.de wrote:

    Created attachment 310338
    output of doxygen
    
    In bug 711104 it is stated that markdown headers T4 and T5 (see the example
    there) show up correctly and links to their labels work. However, a simple
    Markdown file:
    
    Top 1 {#label1}
    ===============
    Some text
    
    Sub 1 {#label2}
    ---------------
    Also some text.
    
    
    leads to the attached html output (ommitted header and footer part).

On 2015-09-01 14:14:52 +0000, Dimitri van Heesch wrote:

    The problem here is the special treatment that is given to a heading at the
    top of a page. It is treated as a page title, rather than a section!
    
    As a result the next subsection doesn't have a section as the parent (which
    is why doxygen also gives a warning).
    
    The following will work fine however:
    
    ~~ test.md ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Start the page with text not a heading
    
    Top 1 {#label1}
    ===============
    Some text
    
    Sub 1 {#label2}
    ---------------
    Also some text.
    
    ### Sub 2 {#label3}
    More text
    
    #### Sub 3 {#label4}
    And more text
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    
    I agree that this is not very nice, nor intuitive, so I'll look for a better
    solution.

On 2017-03-03 11:57:01 +0000, Tim wrote:

    To be clear:
    
    This works:
    
    ```
    # Title
    
    ## Subheading
    
    Text
    ```
    
    This hides the subheading:
    
    ```
    # Title
    
    ## Subheading {#label}
    
    Text
    ```
    
    This *does not work*; the title will be the name of the file and the
    subheading is hidden:
    
    ```
    Dummy text
    
    # Title
    
    ## Subheading {#label}
    
    Text
    ```
    
    Even more bizarrely, this will almost work, except both headings will be
    called "Heading"!
    
    ```
    # Title
    
    # Heading {#label}
    
    ## Subheading {#label}
    
    Text
    ```
    
    Something is clearly messed up here!

**Comment by albert-github** [comment]
I checked with the current doxygen version (1.9.7)
- original problem is OK now
- hides the subheading, the sub heading is now present
- with "Dummy text", subheading is present. The fact that the filename is now the title as no page  element is given here.
- the problem that "almost" works, is logical as it contains an error (which is indicated by means of a warning), the label is reused. So this is usage.


So I think the problem is solved in the mean time or it is usage.
