### ISSUE TITLE
Can't suppress @author, @date and @copyright information in the detailed file description (Origin: bugzilla #754440)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5853]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.8.10* on platform *Other*
Assigned to: Dimitri van Heesch

On 2015-09-02 09:50:03 +0000, Jeronimo Werder wrote:

    In our projects the source files include the author, date  and copyright
    information in each file header. Looking similar to:
    
/**************************************************************************//**
     * @file      foo.c
     * @author    Jeronimo Werder
     * @date      2013-10-15
     *
     * @copyright &copy Plexus Inc. 2013 - 2015 
     *            Plexus Deutschland GmbH
     *            Bratustrasse 7
     *            D-64293 Darmstadt
     *
     * @brief     A brief description of foo.c.
     *
     * @details   This is the more detailed description of the contents of the
    file
     *            foo.c and is explaining the purpose of that module. This  
     *            description is often copied to the detailed description of a 
     *            group using the \@copydetails command.
******************************************************************************/
    
    My problem is, that I can't suppress the output of the @author, @date and
    @copyright contents. These information are always shown under the detailed
    description of the file documentation. And since I'm often using the
    @copydetails command these information are also shown in the detailed
    description of a module (group). Even setting the authorsection tag to
    visible=no doesn't help for the file documentation since these information
    are a part of the detailed description:
    
      <file>
        ...
        <authorsection visible="no"/>
      </file>
    
     It would be great if there would be an easy way to suppress these
    information, so that I can treat these information for internal use only.

On 2018-06-10 11:08:08 +0000, albert wrote:

    Looks like there is a small misinterpretation regarding 'authorsection'
    versus '\author.
    
    in the documentation we see (for 'authorsection'):
    Represents the author section of a page (only used for man pages). 
    
    This is a bit unclear so I've just pushed a proposed patch to github (pull
    request 760, https://github.com/doxygen/doxygen/pull/760) to clarify a
    little bit the situation with the text (in the manual):
    
    Represents the author section of a page (only used for man pages). This is a
    separate section for man pages with a text like: Generated automatically by
    Doxygen for My Project from the source code. This should not be
    misinterpreted with the doxygen commands \author or \authors that generate
    an author paragraph inside a detailed description.
    
    
    The wish / enhancement to be able to remove '\author' etc completely from
    the output is of another order.

**Comment by albert-github** [comment]
Code has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
