### ISSUE TITLE
mouse drag doesn't work on all images and on all browsers (Origin: bugzilla #754469)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5854]
status NEEDINFO severity *normal* in component *build* for *---*
Reported in version *1.8.10* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxyfile2](https://sourceforge.net/projects/doxygen/files/attachments/bug754469_310523_doxyfile2/download/download)_ (ID 310523)

On 2015-09-02 15:03:41 +0000, Adrian wrote:

    I tried to drag the mouse on a class Collaboration diagram in FF and it
    didn't move, but dragging on a call or caller graph does move the image
    around.  No dragging of the image worked in Chrome.  Buttons in top left do
    work.
    
    DOT_IMAGE_FORMAT       = svg
    INTERACTIVE_SVG        = YES
    
    FF version: 40.0.3
    Chrome version: Version 45.0.2454.85 m

On 2015-09-02 15:34:27 +0000, Dimitri van Heesch wrote:

    Can you please attach a self-contained example (source+config file in a tar
    or zip) that allows me to reproduce the problem?

On 2015-09-02 15:47:07 +0000, Adrian wrote:

    Not at this time, but I can attach the doxyfile used to generate the
    problem.

On 2015-09-02 15:47:50 +0000, Adrian wrote:

    Created attachment 310523
    Doxygen config file used to create the problem

**Comment by albert-github** [comment]
Unfortunately no further information provided, so problem is incomplete  / not reproducible.
