### ISSUE TITLE
Rendering HTML document very slow on FF but fast on Chrome. (Origin: bugzilla #754472)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5855]
status NEEDINFO severity *minor* in component *build* for *---*
Reported in version *1.8.10* on platform *Other*
Assigned to: Dimitri van Heesch

On 2015-09-02 15:22:18 +0000, Adrian wrote:

    I opened up class reference file that was a 770k html file which referenced
    48M of svg files and 4.4M of map files.
    
    On FF, it displayed something after 3 seconds and took 12 seconds to finish
    loading.
    
    On Chrome, it displayed something immediately and took 13 seconds to finish
    loading.
    
    Not sure if anything can be done about this, but it is slightly annoying.
    
    Sorry that I can't post the files as they are for a proprietary system.

On 2015-09-02 15:27:47 +0000, Adrian wrote:

    DOT_IMAGE_FORMAT       = svg
    INTERACTIVE_SVG        = YES
    
    FF: 40.0.3
    Chrome: Version 45.0.2454.85 m

On 2015-09-02 15:33:32 +0000, Dimitri van Heesch wrote:

    I don't see how I can reproduce or fix this.

On 2015-09-02 15:39:51 +0000, Adrian wrote:

    Yeah, it would need a very large source base.  I didn't add any doxygen
    comments to the source, just ran the doxygen system on the code base.
    
    Just wanted to let you guys know that there are some performance issues.

**Comment by albert-github** [comment]
Unfortunately no further information provided, so problem is incomplete  / not reproducible.
