### ISSUE TITLE
SVG images don't show up until pressing centre control button in top left of image (Origin: bugzilla #754473)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5856]
status NEEDINFO severity *normal* in component *build* for *---*
Reported in version *1.8.10* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxyfile2](https://sourceforge.net/projects/doxygen/files/attachments/bug754473_310522_doxyfile2/download/download)_ (ID 310522)
- _[classes.cpp](https://sourceforge.net/projects/doxygen/files/attachments/bug754473_310527_classes.cpp/download/download)_ (ID 310527)

On 2015-09-02 15:27:13 +0000, Adrian wrote:

    In FF, this only happens in the Collaboration diagram.  This doesn't happen
    for the caller and calls diagrams.
    
    In Chrome, they don't ever show up until the centre button is pressed.
    
    DOT_IMAGE_FORMAT       = svg
    INTERACTIVE_SVG        = YES
    
    FF: 40.0.3
    Chrome: Version 45.0.2454.85 m

On 2015-09-02 15:31:21 +0000, Dimitri van Heesch wrote:

    Can you please attach a self-contained example (source+config file in a tar
    or zip) that allows me to reproduce the problem?

On 2015-09-02 15:45:07 +0000, Adrian wrote:

    Not at this time, but I can attach the Doxyfile.

On 2015-09-02 15:46:02 +0000, Adrian wrote:

    Created attachment 310522
    Doxygen config file used to create the problem

On 2015-09-02 16:06:17 +0000, Adrian wrote:

    Created attachment 310527
    a file to replicate problem
    
    This file will generate some documentation.  Once documentation is created,
    find documentation for function A::a().  On chrome the image doesn't show
    up, in FF it does.

On 2015-09-02 16:07:45 +0000, Adrian wrote:

    Note, I don't really know how to generate the collaboration diagrams, so I
    can't create that diagram as of yet.  However, the attached source and
    config files should get you on your way.

On 2015-11-25 17:22:35 +0000, cruff@ruffspot.net wrote:

    I've also seen this with Chrome 46.0.2490.80 on Linux, but have no issues
    with Firefox 42.0.

**Comment by albert-github** [comment]
The mentioned versions of Chrome and Firefox I don't have available anymore so I tested with:
- dot version 7.0.5
- Firefox 111.0.1 (64-bit)
- Chrome Version 112.0.5615.50 (Official Build) (64-bit)

With the 1.8.10 version I see that for the call graph there is some information (for `A::a()` in html/struct_a.html) on the top of the visible part of the image but after the "center button"  the entire  image is visible with the current doxygen version (1.9.6) the image is straight away visible. For a collaboration diagram (used `UML_LOOK = YES`) more or less the same is valid (initially for 1.8.10 nothing is visible.

I think the problem has been solved in the mean time.
