### ISSUE TITLE
Enum is missing elements when adding semicolon, functions inside element and added constructor. (Origin: bugzilla #754816)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5862]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.8.10* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[Test.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug754816_311039_Test.zip/download/download)_ (ID 311039)

On 2015-09-10 07:42:58 +0000, Marco M. wrote:

    Created attachment 311039
    Test file for the bug(s).
    
    Hello,
    
    I've found a bug when commenting a java enumeration.
    If there's an enumeration with an added semicolon at the end, the last
    element is missing in the documentation (enumeration "Test" in Zip).
    
    public enum Test {
    	/**
    	 * Test Description 1
    	 */
    	TEST_1 /**< Test Description 1.1 */,
    	/**
    	 * Test Description 2
    	 */
    	TEST_2, /**< Test Description 2.1 */
    	/**
    	 * Test Description 3
    	 * 
    	 * Not documented due to added semicolon
    	 */
    	TEST_3;  /**< Test Description 3.1 - Not added due to added semicolon. */
    }
    
    TEST_3 is missing in the HTML documentation.
    
    Additionally I've found out that doxygen ignores every enumeration when I
    override a method inside an element and provides code as initial value.
    Documented in enumeration Test_2.
    
    public enum Test_2 {
    	/**
    	 * Test Description 1
    	 */
    	TEST_1 {
    		/**
    		 * ToString Description
    		 */
    		@Override
    		public String toString() {
    			return "Test 1"; 
    		} 
    	} /**< Test Description 1.1 */,
    	/**
    	 * Test Description 2
    	 */
    	TEST_2, /**< Test Description 2.1 */
    	/**
    	 * Test Description 3
    	 */
    	TEST_3;  /**< Test Description 3.1 */
    }
    
    Furthermore in enumeration Test_3 the documentation is missing the added
    member variable, constructor, etc.
    
    public enum Test_3 {
    	/**
    	 * Test Description 1
    	 */
    	TEST_1("Test # 1") /**< Test Description 1.1 */,
    	/**
    	 * Test Description 2
    	 */
    	TEST_2("Test # 2"), /**< Test Description 2.1 */
    	/**
    	 * Test Description 3
    	 */
    	TEST_3("Test # 3");  /**< Test Description 3.1 */
    	
    	/**
    	 * Description - missing
    	 */
    	private String _desc;
    	
    	/**
    	 * Constructor - missing
    	 * @param desc Description
    	 */
    	private Test_3(String desc) {
    		_desc = desc;
    	}
    	
    	@Override
    	public String toString() { //missing
    		return _desc;
    	}
    }

**Comment by albert-github** [comment]
With the 1.8.10 version I see the problems as indicated in the first and second example, when running with the current version (1.9.3 (c0b9eafbfb53286ce31e75e2b6c976ee4d345473)) the problem is gone.
So I think these problems are solved in the mean time.

The problem mentioned in example 3 is due to the fact that `_desc` and `Test_3` are private and by default they are not shown unless the setting `EXTRACT_PRIVATE=YES` is uesed, so I think this problem is usage.
