### ISSUE TITLE
C# - Using Statements inside of Namespace Significantly Increases Build Time (Origin: bugzilla #755377)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5875]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.10* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[DoxyGenCfgCommon_ICD.cf](https://sourceforge.net/projects/doxygen/files/attachments/bug755377_311812_DoxyGenCfgCommon_ICD.cf/download/download)_ (ID 311812)

On 2015-09-22 00:11:52 +0000, p4rks.r0s4@gmail.com wrote:

    Created attachment 311812
    Configuration File
    
    I am running version 1.8.10 of Doxygen on Windows 7. My code base is written
    in C# and is ~3965 files and ~1,138,345 logical lines of code. We've been
    using Doxygen for years and it has always generated 2 separate outputs in
    ~30 minutes (possibly less).
    
    A couple of weeks ago we ran a tool on our code base whose only change was
    placing the "using" statements inside of the "namespace" declaration for all
    classes (previously they were all outside of the "namespace"). The next day
    we noticed that our nightly build was hanging on the Doxygen generation
    step. I re-ran the generation overnight with the rest of the build turned
    off and it took ~5 hours to generate 1 of the 2 outputs. When I rolled the
    code back to place the "using" statements outside of the "namespace" the
    generation progressed normally with no large delay. We see no warnings or
    errors in the log and our configuration is attached (I only removed the
    INPUT, most of our settings are default).
    
    Code Before Without Problem:
    #region Using List
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    #endregion
    
    namespace OurApplication
    {
        /// <summary>
        /// Class information
        /// </summary>
        class OurClass
        {
            /// <summary>
            /// Method information
            /// </summary>
            public void Method() { }
        }
    }
    
    Code After With Problem:
    namespace OurApplication
    {
        #region Using List
        using System;
        using System.Collections.Generic;
        using System.Linq;
        using System.Text;
        using System.Threading.Tasks;
        #endregion
    
        /// <summary>
        /// Class information
        /// </summary>
        class OurClass
        {
            /// <summary>
            /// Method information
            /// </summary>
            public void Method() { }
        }
    }

**Comment by albert-github** [comment]
It is hard to tell what might have caused this problem.
Running the example on windows with the 1.8.10 version or with the current doxygen version (1.9.7 ) I don't see a lot of differences in the time. There are some related issues that have been solved.

I think this should be set to not reproducible / invalid.
