### ISSUE TITLE
qhp toc broken (Origin: bugzilla #755943)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5880]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.10* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[index - ok - doxygen1.8.6.qhp](https://sourceforge.net/projects/doxygen/files/attachments/bug755943_312483_index - ok - doxygen1.8.6.qhp/download/download)_ (ID 312483)
- _[index.qhp.broken.doxygen1.8.10](https://sourceforge.net/projects/doxygen/files/attachments/bug755943_312485_index.qhp.broken.doxygen1.8.10/download/download)_ (ID 312485)

On 2015-10-01 13:58:34 +0000, jconraud@gmail.com wrote:

    Created attachment 312483
    index.qhp ok as generated by Doxygen 1.8.6
    
    Since several releases of Doxygen, we are unable to generate documentation
    for our software because index.qhp file is ill-formed and rejected by
    qhelpgenerator.
    
    In order to start to understand what is going on, I retrieved Doxygen code
    from git/github and found a change done in this area for fixing Bug 735145.
    
    Reverting change done for Bug 735145 put back Ok generation of documentation
    of our software.
    
    I was not able to create a small example showing the issue. What I can
    upload and which could help (I hope at least) is index.qhp as generated by
    Doxygen 1.8.6 and Ok (accepted by qhelpgenerator) and index.qhp as generated
    by Doxygen 1.8.10 (or 1.8.9 or 1.8.9.1) and Ko (rejected by qhelpgenerator)

On 2015-10-01 13:59:32 +0000, jconraud@gmail.com wrote:

    Created attachment 312485
    index.qhp broken as generated by Doxygen 1.8.10

On 2015-10-01 14:04:19 +0000, jconraud@gmail.com wrote:

    When diffing the two versions of index.qhp, seems like there is a mÃ©li/melo
    in the handling of when introducing or closing a level of section, and the
    change for Bug 735145 was in the functions handling that. It should not
    coincidence, even if, as I have not enough knowledge of this code, I have
    hard time proposing a fix.

On 2015-10-03 11:47:25 +0000, jconraud@gmail.com wrote:

    Update: by changing contents of the page files parsed by Doyxgen, I was able
    to woraround issue with index.qhp file rejected by qhelpgenerated.
    
    Changes consisted in ensuring there were not any longer duplicates of
    section/subsection/subpages labels.
    
    A warning is sent by Doxygen when such duplicates are found, but it seems
    like these duplicates not only are warning but become errors when it is
    about QHP generation.
    
    In the future I will take care of not having any longer such duplicates, and
    consider this issue as handled by doing so, but I'm sharing this information
    in case it can be useful to Doxygen project.

**Comment by albert-github** [comment]
Unfortunately there is no case with this issue only the output qhp files for the different versions (that differ substantially).

Hopefully the fix for issue #8753 (it is pull request #8754) will also fix this problem.

Setting this issue to incomplete.

**Comment by ferdymercury** [comment]
(Just remapping the broken links above)

https://sourceforge.net/projects/doxygen/files/attachments/bug755943_312483_index%20-%20ok%20-%20doxygen1.8.6.qhp/download
https://sourceforge.net/projects/doxygen/files/attachments/bug755943_312485_index.qhp.broken.doxygen1.8.10/download
