### ISSUE TITLE
Markdown reference links within \deprecated blocks aren't expanded (Origin: bugzilla #756723)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5887]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.10* on platform *Other*
Assigned to: Dimitri van Heesch

On 2015-10-16 22:59:45 +0000, David Haney wrote:

    The following code demonstrates a problem when using markdown reference
    links within a \deprecated statement:
    
    /**
     * X
     */
    class X {
    };
    
    /**
     * @deprecated [1]
     *
     * [1]
     *
     * [1]: \ref X
     */
    class Y {
    };
    
    /**
     * @deprecated [1](\ref X)
     */
    class Z {
    };
    
    In the generated output, the documentation for Z correctly reflects the link
    to X, however the documentation for Y only references X within the
    non-\deprecated block. In the \deprecated block, no substitution occurs and
    [1] is rendered in the html.

**Comment by albert-github** [comment]
In the versions 1.8.11 and 1.8.14 I see the indicated problems.
In the current master the problem is gone (probably because of the reorganization done in respect to markdown handling).
So looks to me that the problem has been solved (but  not yet released).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
