### ISSUE TITLE
Macros (@test, @todo, etc) used with PHP namespaces causes illegal command warning (Origin: bugzilla #759063)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5901]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.10* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[test.php](https://sourceforge.net/projects/doxygen/files/attachments/bug759063_319177_test.php/download/download)_ (ID 319177)
- _[StackTrace.txt](https://sourceforge.net/projects/doxygen/files/attachments/bug759063_319179_StackTrace.txt/download/download)_ (ID 319179)

On 2015-12-05 16:10:35 +0000, eckertzs1@gmail.com wrote:

    I have already written this up at:
    http://stackoverflow.com/questions/33698238/doxygen-interprets-php-
    namespace-as-command-in-test-command
    
    PHP uses \ as a namespace separator, so when Doxygen is handling the @todo
    and @test commands, the class name is interpreted as a command that does not
    exist and an error is thrown.  An example case, document a php file
    containing:
    
    <?php
    namespace TestNamespace;
    
    /** @test This is a test
     *
     *  @test This is a second test
     */
    class TestClass { }
    
    /** @test This is a test on another class
     */
    class TestClass2 { }
    
    Doxygen will output 
    
    test:2: warning: Illegal command TestClass as part of a \ref
    test:4: warning: Illegal command TestClass2 as part of a \ref
    
    to stderr.  The actual class documentations will be correct, however on the
    Test List page, the class names will not be displayed properly (only the
    namespace will be shown), see the screenshot at
    http://i.stack.imgur.com/U7MMI.png .   The links to the classes are correct.

On 2016-01-16 15:02:03 +0000, eckertzs1@gmail.com wrote:

    Created attachment 319177
    Test case reproducing the warnings
    
    Generating documentation for this file using the default generated options
    will throw the warning in this bug twice (once for each class).

On 2016-01-16 15:05:26 +0000, eckertzs1@gmail.com wrote:

    Created attachment 319179
    Stack trace at point of warning due to previously attached test case
    
    Stack trace generated at the point of the first warning for the test case,
    using gdb on doxygen build from commit e2dd835.

On 2018-05-17 17:24:18 +0000, albert wrote:

    I've just pushed a proposed patch to github (pull request 730,
    https://github.com/doxygen/doxygen/pull/730).

**Comment by albert-github** [comment]
Pull request #730 integrated.

**Comment by albert-github** [comment]
@hschletz Can you please create a new issue for this and attach a, small, self contained example (source+config file in a tar or zip) to it that allows us to reproduce the problem? So that the new issue can be handled properly.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
