### ISSUE TITLE
Incorrectly applies default values for C# properties (Origin: bugzilla #759190)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5906]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.10* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[main.cs](https://sourceforge.net/projects/doxygen/files/attachments/bug759190_316957_main.cs/download/download)_ (ID 316957)

On 2015-12-08 16:55:33 +0000, Rudy Raab wrote:

    Created attachment 316957
    Example source to reproduce bug
    
    In a C# class, if you have several properties in a row, each with a default
    value, the documentation generated by Doxygen will apply the default value
    of the first property to the second, and the second's to the third, and so
    on. The last property's default value appears to be lost in the docs, except
    if there is another property below it without a default value. Then that
    property will get the last defaulted property's default value in the docs.
    
    It's basically an offset by one of which properties get which defaults, so
    the default value of property N is applied to property N+1.
    
    Bug is confirmed in HTML and Latex docs.
    
    I have attached an example source file that reproduces this bug.

On 2015-12-09 11:22:31 +0000, albert wrote:

    Problem lies in the code part of scanner.l:
       6172 <CSAccessorDecl>"}"                     {
       6173                                           if (curlyCount)
       6174                                           {
       6175                                             curlyCount--;
       6176                                           }
       6177                                           else
       6178                                           {
       6179                                             mtype = Method;
       6180                                             virt = Normal;
       6181                                             unput(';');
       6182                                             BEGIN(FindMembers);
       6183                                           }
       6184                                         }
    
    Where at line 6181 a ';' is inserted although the statement / property
    continues. Just commenting this line does not help as in that case the
    variable 'd' is not seen as a property.
    There is possibly also a relation with:
     2841 <ReadInitializer>[;,]
    and
      3317 <FindMembers>[;,] 
    My knowledge of C# is insufficient to propose a patch.

**Comment by albert-github** [comment]
With the 1.8.10 version the problem is as indicated.
With the current doxygen version (1.9.7) the output is as expected.

I think the problem has been solved in the mean time.
