### ISSUE TITLE
Incomplete docs for SHOW_INCLUDE_FILES (Origin: bugzilla #759270)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5911]
status NEEDINFO severity *normal* in component *documentation* for *---*
Reported in version *1.8.10* on platform *Other*
Assigned to: Dimitri van Heesch

On 2015-12-09 20:08:55 +0000, Jonathan Wakely wrote:

    "If the SHOW_INCLUDE_FILES tag is set to YES then doxygen will put a list of
    the files that are included by a file in the documentation of that file."
    
    This doesn't mention that unless it is set to YES the \headerfile command
    doesn't produce any output in the documentation for a class.

On 2015-12-25 13:51:19 +0000, albert wrote:

    With the documentation of \headerfile I do see:
    
    To disable the include information altogether set SHOW_INCLUDE_FILES to NO
    
    In case this is unclear please propose a better text for \headerfile and /or
    for SHOW_INCLUDE_FILES

**Comment by albert-github** [comment]
Looks like this issue is related / the same as mentioned in https://github.com/doxygen/doxygen/issues/8639 and fixed by means of https://github.com/doxygen/doxygen/pull/8666.

I think this problem has been solved in the mean time.

**Comment by jwakely** [comment]
Yes, looks like I forgot that I'd already reported this issue once before, back in the bugzilla times. I agree it's solved by my #8666 change, and so this can be closed.
