### ISSUE TITLE
PlantUML image not generated when using !include  directive (Origin: bugzilla #759866)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5921]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.10* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[plantuml_test.tar.gz](https://sourceforge.net/projects/doxygen/files/attachments/bug759866_317882_plantuml_test.tar.gz/download/download)_ (ID 317882)

On 2015-12-25 19:19:24 +0000, Mira Kes wrote:

    Created attachment 317882
    Sample source code demonstrating the problem
    
    If a plant UML image is defined in an external file included in the document
    using
    
    @startuml 
    !include filename
    @enduml
    
    doxygen generates a .pu file containing the @startuml ... @enduml sequence
    instead of the definition in the included file.
    
    The problem is on both Linux and Windows versions of 1.8.10.
    For an image definition put inline to the doxygen processed document it
    works OK except that it swallows the first image definition line after the
    @startuml tag.
    
    There is no such problem in 1.8.9.1 for both inline and external file image
    definition.

On 2018-06-13 10:00:17 +0000, albert wrote:

    With 1.8.9.1 I also see the problem.
    
    Problem is that in the doxygen configuration file the PLANTUML_INCLUDE_PATH
    isn't set. Plantuml looks in that case in output directory.
    
    Setting "PLANTUML_INCLUDE_PATH = ." solves this problem.
    
    I think this problem is not a bug but usage.

**Comment by albert-github** [comment]
Seen the comment and the fact that this still works for 1.9.2, I think the problem is usage.
