### ISSUE TITLE
Unable to build Doxygen Manual PDF under CentOS 6.7 (Origin: bugzilla #760316)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5925]
status NEEDINFO severity *normal* in component *build* for *---*
Reported in version *1.8.11* on platform *Other*
Assigned to: Dimitri van Heesch

On 2016-01-08 11:09:28 +0000, Elijah Zarezky wrote:

    Last output lines from terminal:
    
    [100%] Generating Doxygen Manual PDF.
    This is pdfTeXk, Version 3.141592-1.40.3 (Web2C 7.5.6)
     %&-line parsing enabled.
    entering extended mode
    (./doxygen_manual.tex
    LaTeX2e <2005/12/01>
    Babel <v3.8h> and hyphenation patterns for english, usenglishmax, dumylang,
    noh
    yphenation, arabic, basque, bulgarian, coptic, welsh, czech, slovak, german,
    ng
    erman, danish, esperanto, spanish, catalan, galician, estonian, farsi,
    finnish,
     french, greek, monogreek, ancientgreek, croatian, hungarian, interlingua,
    ibyc
    us, indonesian, icelandic, italian, latin, mongolian, dutch, norsk, polish,
    por
    tuguese, pinyin, romanian, russian, slovenian, uppersorbian, serbian,
    swedish,
    turkish, ukenglish, ukrainian, loaded.
    
    make[3]: *** [doc/CMakeFiles/doxygen_pdf] Error 1
    make[3]: Leaving directory
    `/home/elijah/rpmbuild/BUILD/doxygen-1.8.11/1.8.11-i686-redhat-linux-gnu'
    make[2]: *** [doc/CMakeFiles/doxygen_pdf.dir/all] Error 2
    make[2]: Leaving directory
    `/home/elijah/rpmbuild/BUILD/doxygen-1.8.11/1.8.11-i686-redhat-linux-gnu'
    make[1]: *** [doc/CMakeFiles/docs.dir/rule] Error 2
    make[1]: Leaving directory
    `/home/elijah/rpmbuild/BUILD/doxygen-1.8.11/1.8.11-i686-redhat-linux-gnu'
    make: *** [docs] Error 2
    make: Leaving directory
    `/home/elijah/rpmbuild/BUILD/doxygen-1.8.11/1.8.11-i686-redhat-linux-gnu'
    
    So no errors from pdfTeXk, LaTeX2e or Babel, just from make... I am
    confused...
    
    CMake invoked as follows:
    
    cmake \
    	-D CMAKE_BUILD_TYPE=RelWithDebInfo \
    	-D CMAKE_INSTALL_PREFIX=%{_prefix} \
    	-D build_wizard=ON \
    	-D build_search=ON \
    	-D build_doc=ON \
    	-D use_libclang=ON \
    	-D force_qt4=ON
    
    (%{_prefix} is just standard "/usr")
    
    BTW, documentation for 1.8.10 builds fine in the same environment.

On 2016-01-24 18:58:45 +0000, albert wrote:

    In the past I had some problems generating documentation as well on a RHEL
    system. Problem was that the LaTeX distribution was to old (might have been
    Web2C 7.5.6 as well).
    After installing Tex Live 2014 I could build again the documentation.
    
    I think your LaTeX version is a bit old too, please try to install a newer
    version.

On 2017-10-11 22:51:08 +0000, Yannick DuchÃªne wrote:

    The same here, building Doxygen from trunk on Ubuntu Xenial. Make fails when
    building the PDF documentation, but there is no error message from the PDF
    related commands.
    
    I wonder if a tools may erroneously return a non-zero exit code.
    
    There is an additional issue for which I feel I have to open an new ticket.

On 2017-10-18 17:56:25 +0000, albert wrote:

    @Yannick DuchÃªne what is the LaTeX version of your distribution, see also
    my earlier comment of January 24, 2016.

On 2017-10-19 18:44:37 +0000, Yannick DuchÃªne wrote:

    Hi @Albert,
    
    The package is `texlive-latex-base` and `latex --version` says:
    
        pdfTeX 3.14159265-2.6-1.40.16 (TeX Live 2015/Debian)
    
    Itâs two years old, it does not seems so much old to me. Or is it?

On 2017-10-20 16:57:31 +0000, albert wrote:

    Version of Tex Live seems OK to me, seen also my comment from January 24,
    2016

On 2017-10-21 00:19:07 +0000, Yannick DuchÃªne wrote:

    Yes, Iâve seen the comment from 2016, but it just mentions a version
    issue. Anyway, I will later try to see if there is a newer one.

On 2017-10-21 18:03:54 +0000, albert wrote:

    As you expect that the problem is with a program that is returning a wrong
    exit code best is to place "echo $status" commands inside the Makefile in
    the latex directory as soon as the file is generated by doxygen (including
    some reference where the echo is placed in the Makefile) and after that run
    make. Maybe also  increase the verbosity level / debug level of make to see
    what happens.
    
    Other step might be to create a small example and run this and add all files
    (as e.g. a compressed tar file) as an attachment to this issue together with
    the console output from the doxygen run and the make run.

On 2017-10-21 18:36:07 +0000, Yannick DuchÃªne wrote:

    Thanks for the pointers (ex. for the debug level in Makefile which I did not
    knew). I will investigate after your pointers, I just canât promise a
    delay. Have a nice as much as you can.

**Comment by albert-github** [comment]
No recent updates of this issue and not a lot of information present to work with. Recently we have not see problems generating the documentation.

I think both problems have been solved in the mean time.
