### ISSUE TITLE
Invalid warnings regarding todos when source file name contains a '-' (Origin: bugzilla #760603)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5927]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.11* on platform *Other*
Assigned to: Dimitri van Heesch

On 2016-01-13 22:46:11 +0000, Mavik wrote:

    Using the default configuration file, the following source file, if named
    main-1.c, causes invalid doxygen warnings. The warnings do not appear if the
    source file is named main.c.
    
    main-1.c
    --------
    #include <stdio.h>
    
    //! @name Fruit types
    //! Description of fruit types.
    //! @todo Add nectarines for next revision.
    //!@{
    #define APPLE  0
    #define ORANGE 1
    #define PEAR   2
    //!@}
    
    int main(int argc, char *argv[])
    {
    	printf("Hello World!\n");
    }
    --------
    
    Console output:
    
    > doxygen -v
    1.8.11
    > doxygen
    ...
    Parsing files
    Preprocessing /main-1.c...
    Parsing file /main-1.c...
    ...
    Generating docs for page todo...
    todo:2: warning: Unexpected character `m'
    todo:2: warning: Unexpected character `a'
    todo:2: warning: Unexpected character `i'
    todo:2: warning: Unexpected character `n'
    todo:2: warning: Unexpected character `-'
    todo:2: warning: Unexpected character `1'
    todo:2: warning: Unexpected character `.'
    Generating group documentation...
    ...
    finalizing index lists...
    writing tag file...
    lookup cache used 0/65536 hits=0 misses=0
    finished...
    >

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6610

**Comment by albert-github** [comment]
Code has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
