### ISSUE TITLE
Markdown files are generated with colons in their output filenames - Invalid for Windows (Origin: bugzilla #760607)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5928]
status NEEDINFO severity *normal* in component *build* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2016-01-13 23:55:30 +0000, michael.joseph@vsolvit.com wrote:

    When I generate HTML output for my C# projects, Markdown help files are
    generated with a colon in the file output name, which is invalid filename
    character for windows.
    
    If I launch a simple http-server using Nodejs, I'm able to view the
    following URL successfully (even on a windows box):
    http://localhost:8080/md_C:_git_MySolution_MyProject_README.html
    
    However if I try to view the file via an IIS web server, the following URL
    gives me a 404 error (the difference between the 2 URL's is just the port
    number. 8080 is my NodeJs server, 80 is an IIS server):
    http://localhost:80/md_C:_git_MySolution_MyProject_README.html
    
    I have tried searching the documentation and options, but there seems to be
    no current way to work around this issue on Windows. Thanks in advance for
    any fixes applied to this issue.

On 2016-01-14 18:33:55 +0000, albert wrote:

    Please supply the used version of doxygen, is now still at unspecified.
    
    Can you please attach a self-contained example (source+config file in a tar
    or zip) that allows us to reproduce the problem?

**Comment by albert-github** [comment]
I tried to reproduce the problem with the version valid at the moment that the issue was submitted (1.8.16) and was not able to reproduce the problem (also with some older versions I could not reproduce it).

Seen the missing version and example the issue is not reproducible
