### ISSUE TITLE
\internal stops all parsing if used inside a section (Origin: bugzilla #760661)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5929]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.11* on platform *Other*
Assigned to: Dimitri van Heesch

On 2016-01-15 10:57:14 +0000, viric@viric.name wrote:

    The usage of the \internal command (and \endinternal) does not work well
    inside a \section.
    
    Having the following snippet, and using a default Doxyfile:
    
    ------------
    /**
     * \page test Test
     *
     * Test one. \internal this is internal \endinternal
     *
     * \section sec Section
     *
     * Test two. \internal this is internal \endinternal
     *
     * Test three. \internal this is internal \endinternal
     *
     */
    ----------------
    
    Expected behaviour (that of Doxygen 1.8.3.1):
    ===========
    
    It should output Test one, Test two, and Test three lines, without any
    internal text.
    
    
    Current behaviour (in 1.8.6, and also 1.8.11):
    ===========
    
    It outputs Test one, Test two, and stops there. Test three is missing.

On 2018-05-18 11:51:44 +0000, albert wrote:

    I've just pushed a proposed patch to github (pull request 732,
    https://github.com/doxygen/doxygen/pull/732).

**Comment by albert-github** [comment]
Pull request #732 integrated

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
