### ISSUE TITLE
LaTeX Error: Something's wrong--perhaps a missing \item. (Origin: bugzilla #760684)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5931]
status NEEDINFO severity *normal* in component *general* for *---*
Reported in version *1.8.11* on platform *Other*
Assigned to: Dimitri van Heesch

On 2016-01-15 18:55:53 +0000, Marco Dalla Gasperina wrote:

    This issue started appearing. The source files are C#.
    If I press Enter a few times, the process completes, but it precludes
    generating the documentation automatically.
    
    The log file contents around the error are:
    //==============================
    Chapter 6.
    (namespace_system.tex
    LaTeX Font Info:    Font shape `T1/phv/bx/n' in size <12> not available
    (Font)              Font shape `T1/phv/b/n' tried instead on input line 3.
    LaTeX Font Info:    Font shape `T1/phv/b/n' will be
    (Font)              scaled to size 10.79993pt on input line 3.
    LaTeX Font Info:    Font shape `T1/phv/bc/n' will be
    (Font)              scaled to size 10.79993pt on input line 3.
    ) (namespace_zuum_base.tex
    LaTeX Font Info:    Font shape `T1/phv/bc/n' will be
    (Font)              scaled to size 6.29996pt on input line 1.
    
    
    ! LaTeX Error: Something's wrong--perhaps a missing \item.
    
    See the LaTeX manual or LaTeX Companion for explanation.
    Type  H <return>  for immediate help.
     ...                                              
                                                      
    l.5 \end{DoxyCompactItemize}
                                
    ? 
    //==============================
    The file namespace_system.tex contains
    \hypertarget{namespace_system}{}\section{System Namespace Reference}
    \label{namespace_system}\index{System@{System}}
    \subsection*{Classes}
    \begin{DoxyCompactItemize}
    \item 
    class {\bfseries String\+Extensions}
    \end{DoxyCompactItemize}

On 2016-01-16 09:12:49 +0000, albert wrote:

    Can you please attach a self-contained example (source+config file in a tar
    or zip) that allows us to reproduce the problem?

**Comment by albert-github** [comment]
As there is no example provided it is not possible to see where the problem lies.

Setting the issue to incomplete / invalid
