### ISSUE TITLE
Missing Base Tag in HTML Output (Origin: bugzilla #761468)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5944]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.8.11* on platform *Other*
Assigned to: Dimitri van Heesch

On 2016-02-02 17:18:15 +0000, esj@rezo.net wrote:

    Doxygen uses relative URLs when generating images in the HTML output.
    This is confusing for programm that reuse Doxygen output, such as the Trac-
    Doxygen Plugin (see https://trac-hacks.org/wiki/DoxygenPlugin).
    I tested it would be sufficient to add the HTML tag named BASE, with a HREF
    attribute containing the initial URL.
    
    Would it be possible to add this in a future release ? It is a
    recommandation from the W3C not to use relative URL, and the base tag is a
    short hand to almost respect this.

**Comment by albert-github** [comment]
When looking at https://www.w3schools.com/tags/tag_base.asp

I see:
> Definition and Usage
>
> The `<base>` tag specifies the base URL and/or target for all relative URLs in a document.
>
> The `<base>` tag must have either an href or a target attribute present, or both.
> 
> There can only be one single `<base>` element in a document, and it must be inside the `<head>` element.

The example reads:
```
<head>
  <base href="https://www.w3schools.com/" target="_blank">
</head>
```
but this would be a hard coded "base" and thus it would not possible to place the resulting doxygen output somewhere else than at the indicated place and thus it would be more or less impossible to distribute the generated documentation to users that install it.


I don't this is something that is useful for doxygen.

Setting it to won't fix
