### ISSUE TITLE
Custom URL in DoxygenLayout.xml for usergroup tab does not work as expected (Origin: bugzilla #761542)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5946]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.11* on platform *Other*
Assigned to: Dimitri van Heesch

On 2016-02-04 10:33:16 +0000, John Olsson wrote:

    A default DoxygenLayout.xml generated with 1.8.11 and modified like this
    
    <doxygenlayout version="1.0">
      
      
      <navindex>
        <tab type="mainpage" visible="yes" title=""/>
        <tab type="usergroup" title="Subunits" url="@ref foobar">
          <tab type="user" url="@ref conf" title="Conf"/>
          <tab type="user" url="@ref coord" title="Coord"/>
          <tab type="user" url="@ref sync" title="Sync"/>
          <tab type="user" url="@ref common" title="Common"/>
        </tab>
        <tab type="pages" visible="yes" title="" intro=""/>
    ...
    
    (tab of type "usergroup" inserted inbetween "mainpage" and "pages")
    
    and the there is a reachable file called foobar.dox containing this
    
    /**
     * @file
     */
    
    /**
     * @page foobar Foobar
     * 
     * Lorum ipsum...
     */
    
    When I click on the "Subunits" tab the above layout results in that the
    "Related Pages" tab gets highlighted and that the contents of the Foobar
    page is shown. No sub-tabs are shown.
    
    On the other hand, if I change the DoxygenLayout.xml like this (removing the
    url attribute from the usergroup tab)
    
    <doxygenlayout version="1.0">
      
      
      <navindex>
        <tab type="mainpage" visible="yes" title=""/>
        <tab type="usergroup" title="Subunits">
          <tab type="user" url="@ref conf" title="Conf"/>
          <tab type="user" url="@ref coord" title="Coord"/>
          <tab type="user" url="@ref sync" title="Sync"/>
          <tab type="user" url="@ref common" title="Common"/>
        </tab>
        <tab type="pages" visible="yes" title="" intro=""/>
    ...
    
    I get the automatically generated "landing page" and the sub-tabs works as
    expected.
    
    
    What I want to accomplish is to have a custom "landing page" together with
    the sub-tabs.

On 2016-02-04 10:43:00 +0000, John Olsson wrote:

    And if I add a Tree View "frame" to the generated HTML files I get this tree
    layout
    
    V Some Name
      > Main Page section name
      V Subunits
        Conf
        Coord
        Sync
        Common
      > Common
      > Conf
      > Coord
        Foobar  (<-- Selected)
      > Sync
      > Todo List
      > Classes
      > Files
    
    I expected that "Subunits" would have been selected and that "Foobar" page
    was not shown in the tree view as it was synonymous with "Subunits". I would
    also have expected that the pages for "Conf", "Coord", "Sync", and "Common"
    were only visible below "Subunits" and not shown twice.

**Comment by albert-github** [comment]
With the 1.8.11 version we indeed see that the "Related Pages" get highlighted when selecting the "Subunits" (in case a url is specified)we also see that there is no dropdown menu with the "Subunits" irrespective of the presence  of on an url.
With the current doxygen version (1.9.6) there is no highlighting of the "Related pages" anymore and the "Sununits" have their dropdown menus.

I think everything now works as expected.

I think the problem has been solved in the mean time.
