### ISSUE TITLE
Single- vs. double-quotes (Origin: bugzilla #762523)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5954]
status NEEDINFO severity *minor* in component *general* for *---*
Reported in version *1.8.7* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[test.f90](https://sourceforge.net/projects/doxygen/files/attachments/bug762523_321938_test.f90/download/download)_ (ID 321938)

On 2016-02-23 11:03:34 +0000, Fabian Nick wrote:

    Created attachment 321938
    Test code reproducing the bug
    
    Hi all,
    
    With Doxygen 1.8.7 I get
    
    > Parsing files
    > Preprocessing /home/fnick/tmp/test.f90...
    > Prepassing fixed form of /home/fnick/tmp/test.f90
    > Parsing file /home/fnick/tmp/test.f90...
    > ********************************************************************
    > Error in file /home/fnick/tmp/test.f90 line: 12, state: 21
    > ********************************************************************
    
    when running Doxygen with a default config file for the attached test.f90: 
    
    However when using double quotes in line 9, everything's fine.
    
    Interestingly enough, I cannot reproduce this behaviour with Doxygen 1.8.5

On 2016-02-23 18:30:40 +0000, albert wrote:

    I tried to reproduce the problem (Linux and Windows) but neither with
    version 1.8.7 nor with the current version I was able to reproduce the
    problem.
    
    If the problem is persistent, please try the current (1.8.11) version
    otherwise please attach the complete sample project to this bug report
    (source + config file in a zip or tar).

**Comment by albert-github** [comment]
I revisited the problem and was able to reproduce the problem with the 1.8.7 version when instead of `test.f90` I used `test.F90` in other words the preprocessor was run on the problem.
I used:
```
      module test
      implicit none
      contains

         subroutine stest()
         implicit none

         character(LEN=4) :: pos
         pos = "???"
         pos = '???'
         end subroutine stest
      end module
```
and with the `-d preprocessor` I got:
```
00001       module test
00002       implicit none
00003       contains
00004
00005          subroutine stest()
00006          implicit none
00007
00008          character(LEN=4) :: pos
00009          pos = "???"
00010          pos = '?^
00011          end subroutine stest
00012       end module
00013
```
note the mangling on line 10.
With the current version of doxygen (1.9.6) I got:
```
00001       module test
00002       implicit none
00003       contains
00004
00005          subroutine stest()
00006          implicit none
00007
00008          character(LEN=4) :: pos
00009          pos = "???"
00010          pos = '???'
00011          end subroutine stest
00012       end module
00013
```
and no error.
Looks like the problem is solved as of version 1.8.12)

I think the problem has been solved in the mean time.
