### ISSUE TITLE
Broken class method links in Docbook XML output (Origin: bugzilla #762701)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5959]
status NEEDINFO severity *normal* in component *build* for *---*
Reported in version *1.8.10* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[DoxygenTest.tar](https://sourceforge.net/projects/doxygen/files/attachments/bug762701_322909_DoxygenTest.tar/download/download)_ (ID 322909)

On 2016-02-25 22:11:45 +0000, Bob McIlvride wrote:

    For /ref markdown in .dox source, links to class methods that are referenced
    by double colons ( :: ) are presumably supposed to link to <simplessect>
    items in Docbook XML output, which we would expect to create working links
    in the final PDF or HTML output from Docbook. But the links are broken
    because no IDs get inserted into the Docbook <simplesect> tags.
    
    For example:
    
    A Doxygen file .dox source text with the link:  
    @ref CAppConfig::hostname "hostname"
    
    Generates this Doxygen HTML output link text: 
    <a class="el"
    href="structCAppConfig.html#ac094e36f92efeafecb7ea36d3eacc9fb">hostname</a>
    
    Which references this target in the HTML:
    <a class="anchor" id="ac094e36f92efeafecb7ea36d3eacc9fb"></a>
    <div class="memitem">
    <div class="memproto">
          <table class="memname">
            <tr>
              <td class="memname">char* CAppConfig::hostname</td>
    		  ...
    And the link works fine.  
    
    The problem is that the Doxygen-generated Docbook XML source text generates
    this link text:
    <link
    linkend="structCAppConfig_1ac094e36f92efeafecb7ea36d3eacc9fb">hostname</link>
    
    Which should reference this target:
    <simplesect><title>char* CAppConfig::hostname</title> ... </simplesect>
    
    However, there is no ID for the <simplesect>.  
    
    The HTML output from the Docbook XML looks like this:
    <a class="link" href="" shape="rect">hostname</a>
    
    Which should reference this target:
    <h2 class="title" style="clear: both">char* CAppConfig::hostname</h2>
    
    Apparently the link is broken because the Doxygen-generated Docbook XML does
    not receive an ID for the <simplesect> tag, and the class methods do not
    receive IDs.
    
    Would it be possible to assign the ID from the <link> in the Docbook XML to
    the <h2> in the HTML output, as well as insert it into the <a href="" ...>
    string?

On 2016-02-28 15:18:56 +0000, Dimitri van Heesch wrote:

    Can you please attach a self-contained example (source+config file in a tar
    or zip) that allows me to reproduce the problem?

On 2016-03-02 19:16:50 +0000, Bob McIlvride wrote:

    Created attachment 322909
    Test of Doxygen to Docbook
    
    Here is a file with an example that illustrates the problem.  
    
    The included directories and files are as follows:
    docbook/* - Doxygen-to-Docbook output
    docbook/out/html/* - Docbook output, generated by oXygen
    html/* - Doxygen HTML output
    latex/* - Doxygen Latex output
    build.sh - script for running doxygen.exe
    config_app.c - source file to be documented
    config_app.h - source file to be documented
    DoxDBTest.dox - source file to be documented
    doxyfile
    DoxygenLayout.xml

**Comment by albert-github** [comment]
I've just pushed a proposed patch with a new implementation of the docbook generator, pull request #6487

**Comment by albert-github** [comment]
Code has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
