### ISSUE TITLE
EXPAND_AS_DEFINED is not recursive (Origin: bugzilla #763378)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5966]
status NEW severity *major* in component *general* for *---*
Reported in version *1.8.11* on platform *Other*
Assigned to: Dimitri van Heesch

On 2016-03-09 15:38:12 +0000, Ambroise Confetti wrote:

    EXPAND_AS_DEFINED is not recursive in version 1.8.11. It used to be
    recursive in version 1.5.
    
    For instance :
    
     #define F foo
     #define B bar
     #define FB F B
    
    With EXPAND_AS_DEFINED containing all F, B and FB, FB expands to "F B" in
    the doxygen output, instead of "foo bar".
    
    -----
    
    Note: I took a quick look at source code of version 1.8.4 and I'm wondering
    if the cause could be in pre.l line 1886.
    
    In version 1.5 it was:
       QCString result = expandMacro(g_defArgsStr);
    
    In version 1.8.4:
       QCString result = def->isPredefined ? def->definition :
    expandMacro(g_defArgsStr);
    
    To me it looks like recursion is stopped by the fact that the macro is in
    the EXPAND_AS_DEFINED list. But it's just a rough guess, as I am not
    familiar with doxygen source code at all. :)

**Comment by albert-github** [comment]
I also think that the analyses done is correct.

I've just pushed a proposed patch, pull request #9341

**Comment by doxygen** [comment]
This should be fixed by https://github.com/doxygen/doxygen/commit/387f508b2e41179a9f70b2914132c2bf12d07b43 (I overlooked the already open pull request). Please verify it indeed fixes the problem and keep the issue open. It will be closed automatically when a new release is made available.

**Comment by albert-github** [comment]
The test I have looked OK.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.5.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
