### ISSUE TITLE
*/ inside a multiline /// comment causes parsing problems. (Origin: bugzilla #764012)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5973]
status NEW severity *blocker* in component *general* for *---*
Reported in version *1.8.10* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[Doxyfile](https://sourceforge.net/projects/doxygen/files/attachments/bug764012_324519_Doxyfile/download/download)_ (ID 324519)
- _[projects.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug764012_324520_projects.zip/download/download)_ (ID 324520)
- _[lfc1-refman.pdf](https://sourceforge.net/projects/doxygen/files/attachments/bug764012_324521_lfc1-refman.pdf/download/download)_ (ID 324521)

On 2016-03-22 05:06:09 +0000, Leo Carreon wrote:

    Created attachment 324519
    doxygen configuration file
    
    I'm using doxygen to generate a PDF file to document my C++ library.
    
    I have some functions in their own namespace that are not being included in
    the documentation.
    
    I'm supplying three files which illustrate this problem.  These are the
    description of the three files attached to this report:
    
    1. Doxyfile - This is the doxygen configuration file that I'm using.
    2. projects.zip - This ZIP file contains the source files being scanned by
       doxygen.  Normally, these source files are underneath the directory
       /home/Devel.
    3. lfc1-refman.pdf - The PDF file generared by doxygen from the above files.
    
    How do I make doxygen include the functions in my resulting documentation?

On 2016-03-22 05:06:59 +0000, Leo Carreon wrote:

    Created attachment 324520
    The sample source files

On 2016-03-22 05:07:40 +0000, Leo Carreon wrote:

    Created attachment 324521
    The resulting PDF file generated from the two other attachments

On 2016-07-03 12:05:56 +0000, Leo Carreon wrote:

    Can I please get a reply on this issue.

On 2016-07-03 17:46:26 +0000, Dimitri van Heesch wrote:

    Just had a look. The main problem is the occurrence of */ inside a multiline
    /// comment here:
    
    ///     If the given executable file name is of the form
    "somepath/bin*/exename[.ext]", the resulting
    
    Doxygen internally translates a multiline /// comment to a /** ... */
    comment, and then the */ inside the comment will end it prematurely!

On 2016-07-04 02:39:25 +0000, Leo Carreon wrote:

    Based on the comments above, I have eliminated the */ sequence inside a
    multiline /// comment.
    
    After this change, the expected function documentations are now present.

**Comment by albert-github** [comment]
Revisited the issue and with the 1.8.10 version the problem exists and is caused by the indicated `*/`. In the current doxygen version the problem is not present and all items are visible.

I think the problem has been solved in the mean time.
