### ISSUE TITLE
Doxygen does not create links on C++ 11 style enum classes (Origin: bugzilla #764644)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5979]
status NEEDINFO severity *normal* in component *general* for *---*
Reported in version *1.8.11* on platform *Other*
Assigned to: Dimitri van Heesch

On 2016-04-05 13:48:48 +0000, remarcg@googlemail.com wrote:

    Referencing C++11 enum class members will not be resolved, e.g.
    <code>cif::move::Extent::MoveOnly</code> will be not be resolved (this
    means: no link will be created), but the (wrong) old style
    <code>cif::move::MoveOnly</code> will be resolved. I have this definition:
    
    namespace cif
    {
        namespace move
        {
            enum class Extent : uint8_t
            {
                MoveOnly,
                // more entries ...
            };
        }
    }
    
    This is already reported in 700740, and marked as fixed, but it isn't fixed
    (or the fix is not working).

On 2016-05-15 14:03:30 +0000, Dimitri van Heesch wrote:

    I've tried to reproduce with the following example and a default config
    file, but the link was resolved just fine:
    
    /** @mainpage
     *  See <code>cif::move::Extent::MoveOnly</code>
     */
    
    /** namespace cif docs */
    namespace cif
    {
      /** nested namespace move docs */
      namespace move
      {
        /** class Extent docs */
        enum class Extent : uint8_t
        {
          MoveOnly, /**< Enum value docs */
          // more entries ...
        };
      }
    }
    
    
    Can you please attach a self-contained example (source+config file in a tar
    or zip) that allows me to reproduce the problem?

**Comment by albert-github** [comment]
Unfortunately no further information provided and the test (see comment) didn't give a problem.
Setting issue to not reproducible / incomplete.
