### ISSUE TITLE
Headers don't support hyperlinks (Origin: bugzilla #765230)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5986]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.11* on platform *Other*
Assigned to: Dimitri van Heesch

On 2016-04-18 20:05:45 +0000, Jimi Damon wrote:

    If you try to create a hyperlink in a Markdown header with either Markdown
    syntax or HTML syntax, the Doxygen document is not rendered correctly.
    
    
    For instance
    
    ## Build with <a href="https://cmake.org/">CMake</a>
    
    fails to render correctly and the header shows up looking  like 
    
    Build with <a href="https://cmake.org/">CMake</a>
    
    
    
    Using Markdown links also fails as this snippet renderes the same way as
    above.
    
    ## Build with [CMake]( https://cmake.org/ )
    
    
    Note that this is supported under general Markdown as demonstrated in a
    GitHub README.md file ( https://github.com/accesio/AIOUSB , README.md )

**Comment by albert-github** [comment]
The problem is the rendering of the ATX header, the same is mentioned in #6998.

Setting this issue to duplicate
