### ISSUE TITLE
Deprecated protocol causes character-by-character warnings (Origin: bugzilla #765409)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5989]
status NEEDINFO severity *normal* in component *general* for *---*
Reported in version *1.8.11* on platform *Other*
Assigned to: Dimitri van Heesch

On 2016-04-22 04:14:58 +0000, Doug Kramer wrote:

    Running doxygen with deprecated protocols causes a warning for each
    character of each protocol name up to the trailing hyphen, as shown below.
    The generated docs look unharmed.
    
    These warnings are in v1.8.11 and not in v1.8.8
    
    SOURCE -----------------
    
    @protocol ABCDeviceListener;
    
    /**
     * A class that listens for a device
     *
     * @deprecated Use ACKDiscover instead.
     */
    ABC_EXPORT
    @interface ABCDevice : NSObject
    
    OUTPUT -----------------
    
    ...
    Generating file documentation...
    ...
    Generating docs for file 
    Generating page documentation...
    Generating docs for page deprecated...
    deprecated:2: warning: Unexpected character `A'
    deprecated:2: warning: Unexpected character `B'
    deprecated:2: warning: Unexpected character `C'
    deprecated:2: warning: Unexpected character `D'
    deprecated:2: warning: Unexpected character `e'
    deprecated:2: warning: Unexpected character `v'
    deprecated:2: warning: Unexpected character `i'
    deprecated:2: warning: Unexpected character `c'
    deprecated:2: warning: Unexpected character `e'
    deprecated:2: warning: Unexpected character `L'
    deprecated:2: warning: Unexpected character `i'
    deprecated:2: warning: Unexpected character `s'
    deprecated:2: warning: Unexpected character `t'
    deprecated:2: warning: Unexpected character `e'
    deprecated:2: warning: Unexpected character `n'
    deprecated:2: warning: Unexpected character `e'
    deprecated:2: warning: Unexpected character `r'
    deprecated:2: warning: Unexpected character `-'
    deprecated:113: warning: Unexpected character `A'
    deprecated:113: warning: Unexpected character `B'
    deprecated:113: warning: Unexpected character `C'
    deprecated:113: warning: Unexpected character `L'
    deprecated:113: warning: Unexpected character `o'
    deprecated:113: warning: Unexpected character `g'
    deprecated:113: warning: Unexpected character `D'
    deprecated:113: warning: Unexpected character `e'
    deprecated:113: warning: Unexpected character `l'
    deprecated:113: warning: Unexpected character `e'
    deprecated:113: warning: Unexpected character `g'
    deprecated:113: warning: Unexpected character `a'
    deprecated:113: warning: Unexpected character `t'
    deprecated:113: warning: Unexpected character `e'
    deprecated:113: warning: Unexpected character `-'
    Generating group documentation...
    Generating class documentation...

On 2016-04-22 17:09:15 +0000, albert wrote:

    Can you please attach a self-contained example (source+config file in a tar
    or zip) that allows us to reproduce the problem?

**Comment by albert-github** [comment]
Based on the given example (even after adding `@end` at the end of the file) I was not able to reproduce the problem.
(during some, intermediate (?) versions there have been some problems as described but the have been fixed).

I think the the issue is incomplete due to a lack of a proper example.
