### ISSUE TITLE
Ampersand not rendered correctly in HTML Help index (Origin: bugzilla #765867)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5994]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.11* on platform *Other*
Assigned to: Dimitri van Heesch

On 2016-05-01 01:15:56 +0000, Christoph Lipka wrote:

    Ampersand characters, such as in "operator &&", are not rendered correctly
    in the HTML Help index.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #8594

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.2.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
