### ISSUE TITLE
missing comments of overridden methods (Origin: bugzilla #766508)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6003]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.11* on platform *Other*
Assigned to: Dimitri van Heesch

On 2016-05-16 10:20:13 +0000, Kasia wrote:

    sorry to bother you, but I've searcher everywhere and I cannot find an
    answer to this problem
    
    I have two classes in PHP: Figure and Circle. Circle extends Figure. Figure
    has a method: draw() Circle inherits this method and overrides it. The
    draw() method is commented in the parent class, but it does not have a
    comment in the Circle class as it should inherit it.
    
    /**
     * Description of Figure  
     *
     * @author admin
     */
    class Figure{
    
        /**
         * Does something
         */
        public function draw() {
    
        }
    }
    
    /**
     * Description of Circle  
     *
     * @author admin
     */
    class Circle extends Figure{
    
    
        public function draw() {
            //overriden method
        }
    }
    
    Doxygen says: "warning: Member draw() (function) of class Circle is not
    documented."
    
    How to make doxygen copy the inhertied comment automatically? I have a huge
    system which should be documented and it will be really time consuming to
    write @copydoc A::doSth() for every overridden method, I thought doxygen
    could deal with this automatically

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6824

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
