### ISSUE TITLE
Doxygen cycles on cyclic dependency (Origin: bugzilla #766869)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6013]
status NEEDINFO severity *normal* in component *documentation* for *---*
Reported in version *1.8.11* on platform *Other*
Assigned to: Dimitri van Heesch

On 2016-05-25 13:55:52 +0000, Jeroen Van Antwerpen wrote:

    In our documentation a page A had the \subpage B, while B had the \subpage
    A.
    
    If I run doxygen over only these 2 files, it gives the error:
    
    error: page defined at line 9 of file abc.dox with label LABEL is a subpage
    of itself! Please remove this cyclic dependency.
    
    Unfortunately, if I run this over multiple (100-1000) of our files
    (including those 2) doxygen just hangs for over 3 hours.
    
    
    If you have any suggestions on how to reduce, please let me know.

On 2016-05-25 16:26:04 +0000, albert wrote:

    In the source code I see:
            err("page defined at line %d of file %s with label %s is a subpage "
                "of itself! Please remove this cyclic dependency.\n",
                pd->docLine(),pd->docFile().data(),pd->name().data());
            exit(1);
    and the exit(1) has, as far as I can see, always been there.
    
    Please investigate whether or not something else causes this problem. When
    persistent can you please attach a (small) self-contained example
    (source+config file in a tar or zip) that allows us to reproduce the
    problem?

On 2016-05-26 07:24:38 +0000, Jeroen Van Antwerpen wrote:

    The issue is that we don't get this message, while we should.
    
    If I try to reproduce on a limited number of files, I don't have that issue
    and get the message :(
    So I guess some other issue results into this error not being triggered.
    
    I'll try to reduce it as much as possible, I was just hoping that there was
    a way to get some extra debug information which would help with the
    reduction

**Comment by albert-github** [comment]
Unfortunately no response, setting to incomplete problem report.
