### ISSUE TITLE
LaTeX/PDF output needs underscores escaped in custom commands. (Origin: bugzilla #767017)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6016]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.11* on platform *Other*
Assigned to: Dimitri van Heesch

On 2016-05-30 11:26:40 +0000, Daniel G. wrote:

    When Doxygen generates TeX output, it needs to escape underscores in custom
    commands (ALIAS) to avoid "insert missing $" errors in LaTeX.
    
    The source that leeds to the LaTeX error is, e.g:
    
    @unittestcase{ABCD_EFGH_IJKL}
    
    The ALIAS that implements this command is:
    
    ALIASES += unittestcase{1}="\xrefitem unittestcases \"Unit Test Case\"
    \"Unit Test Cases\" \htmlonly <div style=\"font-weight: bold;\"
    name=\"UTTCID\">\1</div>\endhtmlonly \xmlonly <uttcid value=\"\1\"
    />\endxmlonly \latexonly UTTCID: \1 \endlatexonly"
    
    If you substitude the _ with \_ in the generated plain text part of the TeX
    file (e.g. by some sed command), LaTex compile works again.
    
    If you include an underscore in plain text (e.g. details of some method or
    in a mark-down file), LaTeX compiles fine without errors. I don't know, if
    the problem lies in the ALIAS or in the xrefitem implementation or somewhere
    else.
    
    Thanks for fixing ;-)

On 2016-06-05 08:07:47 +0000, albert wrote:

    The ALIAS unittestcase places the text as specified in the source as if it
    had been there from the beginning.
    
    The inserted text contains a \latexonly / \endlatexonly block and the
    content of this is taken as valid LaTeX code without any processing. The
    documentation states:
    Starts a block of text that will be verbatim included in the generated LATEX
    documentation only.
    
    I don't think this is a bug.

**Comment by albert-github** [comment]
As per comment from 2016-06-05, I still think this is usage
