### ISSUE TITLE
Links on image in Markdown (Origin: bugzilla #769223)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6039]
status NEW severity *normal* in component *documentation* for *---*
Reported in version *1.8.11* on platform *Other*
Assigned to: Dimitri van Heesch

On 2016-07-27 12:28:34 +0000, eolianoe@gmail.com wrote:

    When using the following README.md as main page (in order to create a link
    on a image):
      [![logo](logo.jpg)](www.example.com)
    
    The generation of the html documentation produces the following warning: 
      /path/README.md:2: warning: Unexpected html tag <img> found within <a
    href=...> context
    
    Whereas the HMTL code generated (obtained with doxygen -d Markdown):
      <a href="www.example.com"><img src="logo.jpg" alt="logo"/></a>
    is valid.
    
    Moreover, it seems to be a "valid" Markdown syntax since (for instance)
    Gitlab properly render the README.md file but it is not documented in the
    "Markdown support" section of the documentation.
    
    Is it a bug or something that is not in the Markdown extensions of Doxygen?

On 2017-08-14 08:32:03 +0000, lectem@gmail.com wrote:

    Any updates for this ?
    Using the same readme for both Github and the documentation would be nice.

On 2017-08-14 08:39:26 +0000, lectem@gmail.com wrote:

    The issue seems to lie with the fact that the parser doesn't handle images
    within <a href=""> at all, and discards the content
    
    https://github.com/doxygen/doxygen/blob/master/src/docparser.cpp#L3102

On 2017-08-14 10:00:10 +0000, albert wrote:

    Did you try (see manual paragraph 5.1.10 Images):
    ![logo](logo.jpg)(www.example.com)
    
    You might to add the logo.jpg to the HTML_EXTRA_FILES

On 2017-08-14 10:38:49 +0000, lectem@gmail.com wrote:

    I do not see this form documented on the online manual? It doesn't seem to
    be standard markdown either.
    The problem isn't the markdown generation anyway, but the parsing done
    afterward when generating the final html.
    My image link is pointing to an online resource (badge that is updated).

On 2017-08-14 10:51:55 +0000, albert wrote:

    See the manual: http://www.stack.nl/~dimitri/doxygen/manual/markdown.html

On 2017-08-14 11:21:50 +0000, lectem@gmail.com wrote:

    Sorry but I really don't see the 
    ! [logo](logo.jpg)(www.example.com) 
    syntax you are talking about. 
    
    The documentation only gives the following :
    ![Caption text](/path/to/img.jpg) 
    ![Caption text](/path/to/img.jpg "Image title") 
    ![Caption text][img def] 
    ![img def] 
    
    Again, this issue is NOT related to the markdown generation but to the Html
    parser. See eolianoe's description of the bug and the link to the source I
    provided... I've seen reports of this for html code in comments too.

On 2017-08-14 11:26:59 +0000, albert wrote:

    (www.example.com) is some extra text

On 2017-08-14 12:34:22 +0000, lectem@gmail.com wrote:

    But it doesn't achieve what we want !
    
    We only want the image to be clickable, not to have a text link next to
    it...
    
    After looking around on the net, I found that this was asked many times and
    you always answered "Take a look at the markdown doc", but this is
    ==========NOT=========== a markdown issue but a docparser issue.
    
    Now, if you want I can create another issue asking to fix the HTML parser,
    but please stop pointing to the documentation.
    If you don't want to fix the issue or add the feature, I don't mind, but at
    least state it clearly.

**Comment by kartikkumar** [comment]
Are there any updates on how to deal with this? It's quite common that the main readme on Github has logos at the top for instance, that need to be clickable. The ugly solution I've found is to wrap the block of logos in a `\cond` block, which means Doxygen doesn't throw warnings, but instead you see `\cond \endcond` in the readme on Github.

**Comment by kartikkumar** [comment]
@mosra oh thanks for pointing that out! Does that mean that you can have an image embedded in a link only using `\image` or does it work with a html `<img>` tag too? I guess I can test it out, but might save me time if you already know :)

**Comment by mosra** [comment]
Don't know, sorry, didn't have a chance to test myself yet. You have to try yourself.

**Comment by kartikkumar** [comment]
Thanks, I'll give it a go. `\image` doesn't get parsed by Github's Markdown, so it doesn't really solve the problem of showing the clickable logos on Github AND on the Doxygen mainpage unless it parses `<img>` embedded inside an `<a>` tag. I'll test it out and report back.

**Comment by kartikkumar** [comment]
Looks like it doesn't entirely work. With the following snippet, it looks fine on Github, but Doxygen doesn't parse correctly, leaving a weird trailing `/>`, as you can see in the screenshot:

`<a href="http://opensource.org/licenses/MIT"><img src="http://img.shields.io/badge/license-MIT-brightgreen.svg" alt="MIT license"></a>`

![screen shot 2019-01-03 at 11 52 51 am](https://user-images.githubusercontent.com/3645858/50634297-72d5f100-0f4e-11e9-98a9-ee497f161f42.png)

**Comment by albert-github** [comment]
@kartikkumar 

That `/>` doesn't look good.
Can you please attach a, small, self contained example (source+config file in a tar or zip) that allows us to reproduce the problem?

**Comment by doxygen** [comment]
Looks like the problem is because the image is a .svg, if I replace it with a .png, it looks ok.

**Comment by kartikkumar** [comment]
Yes, now it works! :) 

Fortunately, I found png substitutes for all the logos. 

In case anyone is interested, I've also tested it out on Travis CI (https://travis-ci.org/kartikkumar/cppbase/builds/474816134) with my custom script that watches for any Doxygen warnings in my cpp boilerplate project (https://github.com/kartikkumar/cppbase). You can see that the main readme also renders the logos on Github without any issues. 

I did have to update my set up to use 1.8.15, since the warnings are still presented in 1.8.14.

Thanks!

**Comment by mosra** [comment]
@albert-github @doxygen could the `/>` be related to (or another case of) https://github.com/doxygen/doxygen/pull/6675, which seems to fix a similar issue with SVG images?

**Comment by albert-github** [comment]
Might be the case (line 1712?) has to be tested.

**Comment by doxygen** [comment]
I'm looking into it: `HtmlDocVisitor::visitPre(DocImage *img)` has 16 different cases depending on 4 booleans: `url.isEmpty()`, `inlineImage`, `typeSVG`, and `img->hasCaption()` . Not all combinations result in proper output it seems.

**Comment by doxygen** [comment]
Just pushed https://github.com/doxygen/doxygen/commit/5d66d2ea14a173edb3d6b7ffaabd0196392fcb0f which should hopefully address this issue. Extended test 031 as well to improve test coverage.

**Comment by albert-github** [comment]
Looks like the tests with `--xhtml` now fails:
```
not ok 31 - [031_image.dox]: test the \image command
-------------------------------------
D:/Programs/Doxygen/fork/doxygen/build_windows_nmake_v2013/testing/test_output_031/html/index.xhtml:104: parser error : Opening and ending tag mismatch: p line 103 and div
.io/badge/license-MIT-brightgreen.png" alt="MIT license" class="inline"/> </div>
                                                                               ^
D:/Programs/Doxygen/fork/doxygen/build_windows_nmake_v2013/testing/test_output_031/html/index.xhtml:104: parser error : Opening and ending tag mismatch: p line 102 and div
dge/license-MIT-brightgreen.png" alt="MIT license" class="inline"/> </div></div>
                                                                               ^
D:/Programs/Doxygen/fork/doxygen/build_windows_nmake_v2013/testing/test_output_031/html/index.xhtml:112: parser error : Opening and ending tag mismatch: div line 67 and body
</body>
       ^
D:/Programs/Doxygen/fork/doxygen/build_windows_nmake_v2013/testing/test_output_031/html/index.xhtml:113: parser error : Opening and ending tag mismatch: div line 63 and html
</html>
       ^
D:/Programs/Doxygen/fork/doxygen/build_windows_nmake_v2013/testing/test_output_031/html/index.xhtml:114: parser error : Premature end of data in tag body line 17
^
D:/Programs/Doxygen/fork/doxygen/build_windows_nmake_v2013/testing/test_output_031/html/index.xhtml:114: parser error : Premature end of data in tag html line 2
^
```

**Comment by Lectem** [comment]
Nice to finally see some progress on this and not just "rtfm" !
Hope you'll get it working :)

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Comment by mosra** [comment]
@doxygen Recently I ran into an issue where I wanted to combine `@ref` (or `@link`) and `@image` (in whatever form, Markdown or HTML), basically have an image clickable, leading to another page, for the [Example Gallery](https://doc.magnum.graphics/magnum/example-index.html) in Magnum. So, something like any of these (or whichever else syntax is the least annoying to parse):

```
@ref examples-triangle "<img src=\"triangle.png\">"
@ref examples-triangle "![](triangle.png)"
[![](triangle.png)](@ref examples-triangle)
```

I know that I could hardcode the page name (doing `[![](triangle.png)](examples-triangle.html)`, but in this case I wanted the link-checking functionality of `@ref`/`@link` -- so if I rename/remove the link target, it will warn me. I admit parsing the above might be nightmarish, but is such functionality feasible?

Thank you.

**Comment by doxygen** [comment]
@mosra I think it is a very reasonable request. Can you file it as a separate issue?

**Comment by mosra** [comment]
@doxygen done, thank you: #7174
