### ISSUE TITLE
PHP: New array syntax not supported when parsing initial value (Origin: bugzilla #769414)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6041]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.11* on platform *Other*
Assigned to: Dimitri van Heesch

On 2016-08-02 10:37:18 +0000, Josef Kufner wrote:

    A new array syntax was introduced in PHP 5.4. Instead of array(1, 2, 3) we
    can now write [1, 2, 3]. However, Doxygen fails to understand this.
    
    Working example:
    
    	class SomeClass {
    		/** Some array */
    		protected $some_array = array(
    			'one' => 'One',
    			'two' => 'Two',
    			'three' => 'Three',
    		);
    	}
    
    Not working example (PHP code is equivalent):
    
    	class SomeClass {
    		/** Some array */
    		protected $some_array = [
    			'one' => 'One',
    			'two' => 'Two',
    			'three' => 'Three',
    		];
    	}
    
    In the second example Doxygen stops at the firs comma. In the first example
    Doxygen shows the whole array correctly.

On 2018-05-10 17:28:44 +0000, albert wrote:

    I've just pushed a proposed patch to github (pull request 717,
    https://github.com/doxygen/doxygen/pull/717).

**Comment by albert-github** [comment]
Pull request #717 integrated.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
