### ISSUE TITLE
Backslash plus brace confuses markdown parser in code block (Origin: bugzilla #769477)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6043]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.11* on platform *Other*
Assigned to: Dimitri van Heesch

On 2016-08-03 16:09:58 +0000, Jannis Teunissen wrote:

    Adding the following code block in a markdown file breaks the parser:
    
        {this is a test\}
    
    For example, the following page:
    
    ***************** test.md *****************
    # This is a test
    
        {I am a code block\}
    
    And I am hidden
    *******************************************
    
    Renders as:
    
    *******************************************
    This is a test
    
    {I am a code block
    *******************************************
    
    Using fenced code blocks does not help.

**Comment by albert-github** [comment]
With doxygen version 1.8.11 we get
![image](https://user-images.githubusercontent.com/5223533/121398414-9c807700-c955-11eb-9f90-7acacf2f8015.png)

with doxygen version 1.9.1 we get:
![image](https://user-images.githubusercontent.com/5223533/121398523-be79f980-c955-11eb-9e18-537bb7173c81.png)


this all looks OK to me. Note the indentation is with 4 spaces, indicating a verbatim block.

When using just less spaces in the in the 1.8.11 we get incomplete documentation, in the 1.9.1. version we also get the incomplete documentation, but also  the warning:
```
test.md:4: warning: unbalanced grouping commands
```
as the command `\}` (i.e. a doxygen command, not an escaped `}`!)  is given without a preceding doxygen `\{` command.

I think the problem has been solved in the mean time.
