### ISSUE TITLE
[enhancement] update MATHJAX_RELPATH upon upgrade to 1.8.11 (Origin: bugzilla #770847)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6058]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.8.11* on platform *Other*
Assigned to: Dimitri van Heesch

On 2016-09-04 13:20:52 +0000, Jannick wrote:

    The default MATHJAX_RELPATH was updated in 1.8.11 (from
    http://www.mathjax.org/mathjax to http://cdn.mathjax.org/mathjax/latest).
    This resulted in surprisingly not-expanded math formulas in the browser
    (html version).
    
    Suggestion: When upgrading the doxyfile to a new doxygen version AND
    MATHJAX_RELPATH was set to the default of the old doxygen version, then
    update to the new MATHJAX_RELPATH (incl. a log report).
    
    Thanks,
    J.

**Comment by albert-github** [comment]
Updating the configuration file has been improved in the mean time quite a bit and also the default reference for the `MATHJAX_RELPATH` changed as a result.

I think this issue is obsolete.
