### ISSUE TITLE
Lambda for read-only property in C# 6 (Origin: bugzilla #771283)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6064]
status NEW severity *normal* in component *general* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2016-09-12 10:53:15 +0000, Magnus Ãsterlund wrote:

    In C# 6 it is a new feature to use lambda to express a read-only property
    Eg.
    
    public string Name => _firstName + " " + _lastName
    
    Expected documentation
    **********************
    Properties
    string Name [get]
    
    
    Resulting documentation
    ***********************
    Public Attributes
    string Name => _firstName + " " + _lastName

On 2016-10-04 19:10:56 +0000, Andy Dent wrote:

    These are officially called "Expression-bodied properties" as per
    https://msdn.microsoft.com/en-gb/magazine/dn802602.aspx
    
    We are experiencing this using Doxygen to generate the Realm API docs
    
    Our internal bug https://github.com/realm/realm-dotnet/issues/854
    
    A sample of the output
    https://realm.io/docs/xamarin/0.78.0/api/class_realms_1_1_realm_object.html

**Comment by magol** [comment]
I'm the reporter of this issue

**Comment by albert-github** [comment]
@magol 
A bit of a late reaction
- with another issue I wrote 
  > Maybe also have a look at the configuration setting `MAX_INITIALIZER_LINES`

  when setting `MAX_INITIALIZER_LINES=0` the part `=> ...` is not present.
- You mentioned C# 6.0 is this the version described in? 
  ECMA-334 
  C# Language Specification
  5th Edition / December 2017

**Comment by magol** [comment]
Of course, you never print the content of a function in the documentation. For the same reason, Doxygen should never print the content after `=>` to the documentation, as this is exactly the same thing as a function. `=>` is simply an easier way to write a single-line function.  So, `MAX_INITIALIZER_LINES=0` should not be a solution for this. 

I did try to find the definition for this in the C# Language Specification, but it was hard to read. I think you can look at chapter 12.16 for an specification of `=>`

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7991

**Comment by albert-github** [comment]
Code of #7991 has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

With the 1.8.20 version I can see the described behavior, with the current master (1.9.0 (9cf80a9afa866f9347af425ba2f6189cc6480832)) the `=> ...` part is gone.

In case this does not solve the issue:
-  please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.
- describe what is still going wrong.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
