### ISSUE TITLE
Add brief text to indexing (Origin: bugzilla #771501)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6070]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.8.12* on platform *Other*
Assigned to: Dimitri van Heesch

On 2016-09-15 18:46:51 +0000, olivier@churlaud.com wrote:

    Currently, the brief text is not in the "text" field of searchdata.xml.
    
    I would like to be able to find text from there as well.

**Comment by albert-github** [comment]
I tried an example with `\file ` and some functions and in all cases I saw with the 1.8.12 (and newer versions) the brief and detailed descriptions that were expected in the `<text>` field.

So either the  problem does not occur or the used example is incomplete.


Example:  [example.tar.gz](https://github.com/doxygen/doxygen/files/7357788/example.tar.gz)
