### ISSUE TITLE
'doxygen -w' should not require existence of header.html/footer.html even if listed in an options file (Origin: bugzilla #771606)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6072]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.12* on platform *Other*
Assigned to: Dimitri van Heesch

On 2016-09-18 03:11:53 +0000, Wolfgang Bangerth wrote:

    The "doxygen -w html header.html footer.html style.cc options.dox" command
    is used to create default headers and footers that one can then edit and re-
    use once actual documentation is generated. If an options file (last
    argument) is given, my understanding is that this is taken into account when
    generating the first 3 files.
    
    Since a recent change in doxygen, this no longer reliably works if the
    options file has entries of the form
    
    HTML_HEADER            = header.html
    HTML_FOOTER            = footer.html
    
    If the header/footer.html files do not currently exist, then this leads to
    an error of the form
    
    error: tag HTML_HEADER: header file `header.html' does not exist
    
    This clearly makes no sense: whether or not the file currently exists, it
    will be overwritten anyway *because the whole point of the -w command is to
    create it*. Not requiring these files to exist also happened to be the old
    behavior of the command.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #8970

**Comment by bangerth** [comment]
Thanks, @albert-github !

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.3.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
