### ISSUE TITLE
Spanish translation doesn't compile (Origin: bugzilla #771742)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6074]
status NEEDINFO severity *normal* in component *build* for *---*
Reported in version *1.8.12* on platform *Other*
Assigned to: Dimitri van Heesch

On 2016-09-20 21:05:18 +0000, Ivan Meyer wrote:

    Doxywizard runs perfect in some language (like English, German, etc) but
    doesn't runs (builds and/or compiles) in Spanish.
    
    Index is show almost empty.

On 2016-09-20 21:13:27 +0000, Ivan Meyer wrote:

    I found this bug using Doxywizard on a C project.

On 2016-09-21 18:34:43 +0000, Dimitri van Heesch wrote:

    With "doesn't run/build/compile" I assume you are referring to the HTML
    output? and not to compiling the sources or running the binaries in order to
    generate the documentation.
    
    I think this is the same issue as Bug 771310.
    
    Can you confirm by checking if you get a similar Javascript error? and (if
    possible) try if the provided fix solves the issue.

On 2016-09-21 18:50:05 +0000, Ivan Meyer wrote:

    Yes, I am referring to the HTML output, specially to the menus.
    
    I don't know JavaScript and HTML but tomorrow I will try to implement the
    fix that you suggested.
    
    I will also test what happens with SHOW_NAMESPACES   = YES, and with 'NO'

On 2016-09-23 00:10:44 +0000, Ivan Meyer wrote:

    The bug has not to do with that. It doesn't care the value of
    SHOW_NAMESPACES.
    
    I have compared the file "menudata.jv" for English and Spanish output
    version and difference are two doble apostrophe that appears in
    
    {text:''defines'',url:'globals_defs.html'}
    
    It should be generated as
    {text:'defines',url:'globals_defs.html'}
    
    
    In the English version appears as 
    
    {text:'Macros',url:'globals_defs.html'}
    
    
    When this bug is fixed manually, the webpage is shown correctly.

**Comment by albert-github** [comment]
With the following example:
```
```
and a default settings we get (when searching for "globals_defs"), for the English language and the versions 1.8.12 and 1.9.1:
```
html_en_1_8_12/menudata.js:{text:'Macros',url:'globals_defs.html'}]}]}]}
html_en_1_9_1/menudata.js:{text:"Macros",url:"globals_defs.html"}]}]}]}
```
when doing the same for the Spanish language we get:
```
html_es_1_8_12/menudata.js:{text:''defines'',url:'globals_defs.html'}]}]}]}
html_es_1_9_1/menudata.js:{text:"defines",url:"globals_defs.html"}]}]}]}
```

we see indeed in the Spanish language version the 2 single quotes. In the 1.9.1. version all looks OK.

I think the problem has been solved in the mean time (in the repository I see on September 28, 2016 in this respect).
