### ISSUE TITLE
"Illegal member name found" warning when expanding macros in different directories (but not always) (Origin: bugzilla #771820)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6075]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.12* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxyprob1.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug771820_336070_doxyprob1.zip/download/download)_ (ID 336070)

On 2016-09-22 09:52:38 +0000, Nick Pelling wrote:

    Created attachment 336070
    Test zipfile to reproduce "Illegal member name found" doxygen issue
    
    While trying to Doxygenify a macro-heavy C project, I ran into a situation
    where a macro would expand correctly if invoked in one directory, but would
    produce "warning: Illegal member name found" and "warning: documented symbol
    `typedef enum' was not declared or defined" if invoked in a different
    directory.
    
    Confusingly, in that different directory the macro invocations fail in two
    places in the header file but succeed in a third place.
    
    To reproduce the bug, unzip the file to a temp directory (it's only three
    files), cd to the FBI800 subdirectory you've just created, and enter
    "doxygen DoxyfileFBI". You should see output that says:
    
    Building member list...
    C:/<wherever>/FBI800/fbi_source/include/timerchannel.h:33: warning: Illegal
    member name found.
    C:/<wherever>/FBI800/fbi_source/include/timerchannel.h:51: warning: Illegal
    member name found.
    
    [...]
    
    Searching for member function documentation...
    C:/<wherever>/FBI800/fbi_source/include/timerchannel.h:33: warning:
    documented symbol `typedef enum' was not declared or defined.
    C:/<wherever>/FBI800/fbi_source/include/timerchannel.h:51: warning:
    documented symbol `typedef enum' was not declared or defined.
    
    Is this a bug that's already known?
    
    Thanks very much, Nick
    
    PS: I'm using Doxygen 1.8.12 under Windows 7.

**Comment by albert-github** [comment]
The problem here lies in the fact that the included file `xmacros.h` cannot be found as include file as the `INCLUDE_PATH` is not set to (at least) `INCLUDE_PATH = fbi_platform/include` and thus the define `IsValid_Mac` was not expanded.

I think the problem is usage.
