### ISSUE TITLE
Doxygen wrongly infers that a macro invocation in a header file is a function rather than a variable declaration (Origin: bugzilla #771822)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6076]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.12* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxyprob2.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug771822_336073_doxyprob2.zip/download/download)_ (ID 336073)

On 2016-09-22 11:20:44 +0000, Nick Pelling wrote:

    Created attachment 336073
    Minimal test case for demonstrating macro/function/variable issue
    
    When Doxygen encounters a C macro invocation in a source file (but where the
    macro is defined in a header file), it makes a best guess as to what kind of
    a thing that macro is expanding to.
    
    Specifically, if Doxygen thinks that a macro invocation looks like a
    function call, it will classify it as a function call.
    
    However, if the macro actually expands to a variable (data) instantiation in
    the header file, Doxygen will be left with a situation where the macro is
    both a variable (when parsed in the header file) and a function (when parsed
    in the source file) at the same time.
    
    In the minimal test setup (attached), this conflict causes Doxygen to output
    messages such as:
    
    Generating docs for file fbi_platform/platformtask.c...
    C:/<wherever>/FBI800/fbi_platform/platformtask.c:16: warning: Member
    MyArray_Instantiate_Mac() (function) of group grp_Includes is not
    documented.
    
    [...]
    
    Generating group documentation...
    C:/<wherever>/FBI800/fbi_platform/platformtask.c:16: warning: Member
    MyArray_Instantiate_Mac() (function) of group grp_Includes is not
    documented.
    
    As a result, Doxygen does not create a properly linked documentation tree,
    because the two conflicting interpretations of the macro are not linkable.
    
    Unfortunately, it can sometimes be very useful to use C preprocessor macros
    in headers to defer instantiation (the codebase I'm working on uses this
    trick a hundred places), so this behaviour is a shortcoming of Doxygen's
    approach that can easily look like a bug from the outside. =:-o
    
    Is there any way to give Doxygen a helpful hint that a particular macro
    invocation is being used to instantiate data rather than a function?
    
    I suspect (but am not sure) that this is the same as the following bugs:
    * https://bugzilla.gnome.org/show_bug.cgi?id=736401
    * https://bugzilla.gnome.org/show_bug.cgi?id=771309
    
    PS: to reproduce, unzip the attached zipfile (containing three files), cd to
    the created FBI800 subdirectory, and enter "doxygen DoxyfileFBI"

**Comment by albert-github** [comment]
There are a number of issues here:
- the `define` is not seen at the place of usage, this can be overcome by means of setting `INCLUDE_PATH=fbi_platform/include/`
- the fact that the resulting value is not documented. In the code we see:
   ```
   /** @brief Macro instantiating a data block */
   #define MyArray_Instantiate_Mac()       const unsigned char MyArray[1] = { 0 }
   ```
   so here only the `define` itself is documented and not the resulting variable. To document the resulting variable one could do 
   ```
   /** @brief Macro instantiating a data block */
   #define MyArray_Instantiate_Mac()       const unsigned char MyArray[1] = { 0 } /**< @brief docu of the var */
   ```


I think the problems are usage.
