### ISSUE TITLE
If you place an extern after a function, Doxygen adds a false call to the extern to that function's callgraph (Origin: bugzilla #772174)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6079]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.12* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[Doxyfile](https://sourceforge.net/projects/doxygen/files/attachments/bug772174_336510_Doxyfile/download/download)_ (ID 336510)

On 2016-09-29 12:00:37 +0000, Nick Pelling wrote:

    Created attachment 336510
    The Doxygen init file used to trigger this bug
    
    File # 1:
    
        /** @file
         ** @defgroup main_group Main group
         ** @ingroup  main_group
         ** @{
         **/
/**************************************************************************//**
         * Main function.
         * @param [in]  num
         *    Parameter included to trigger callgraph generation
*****************************************************************************/
        void main(int num)
        {
        }
        extern void UnrelatedFunction(num);
        /** @} */
    
    File # 2:
    
        /** @file
         ** @ingroup main_group
         ** @{
         **/
/**************************************************************************//**
         * Unrelated function.
         * @param [in]  num
         *    Parameter included to trigger callgraph generation
*****************************************************************************/
        void UnrelatedFunction(int num)
        {
        }
        /** @} */
    
    Placing the extern to UnrelatedFunction() after the main() function body
    causes Doxygen to add a call from main() to UnrelatedFunction() in the
    generated callgraph for main().

**Comment by albert-github** [comment]
With the doxygen version 1.8.12 I see that that call graph has:
![image](https://github.com/doxygen/doxygen/assets/5223533/7378ca90-7d16-4aec-8f52-a086ae31926f)

With the 1.9.6. version the call graph doesn't show the reference to the `UnrelatedFunction`:
![image](https://github.com/doxygen/doxygen/assets/5223533/4ad236b1-b713-4a75-8de1-427bec6668f3)


I think the problem has been solved in the mean time.
