### ISSUE TITLE
*_AUTOBRIEF=YES gobbles end of paragraph from brief (Origin: bugzilla #772405)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6081]
status NEW severity *major* in component *build* for *---*
Reported in version *1.8.12* on platform *Other*
Assigned to: Dimitri van Heesch

On 2016-10-04 13:09:04 +0000, Hayo Baan wrote:

    With JAVADOC_AUTOBRIEF=YES or QT_AUTOBRIEF=YES, doxygen gobbles the end of
    paragraph marker if the first paragraph was just a single line. This is
    problematic for e.g. @mainpage entries as there the second paragraph
    immediately gets appended to the first (even WITHOUT a space in between!).
    This same gobbling of the end paragraph marker also leads to unexpected
    behaviour with e.g. @author where the second paragraph gets mixed with the
    author list instead of ending up as paragraph.
    
    Example: the following mainpage description does not start the second
    paragraph as a new paragraph, worse, it leaves no space after the period
    from the first sentence either!
    /**
     * @mainpage
     * Nice mainpage description.
     *
     * This should be the second paragraph but it isn't with *_AUTOBRIEF=YES.
     *
     * Third paragraph indeed as paragraph.
     */
    
    I also noticed this problem with e.g. @author; there the author list gets
    the content of the first details paragraph is added to it authors (again
    with no space in between).
    
    Example: in the following file description, the author list gets the first
    paragraph added:
    /**
     * @file
     * @author ME
     * @brief Nice function brief.
     *
     * First paragraph of detail description.
     */
    
    (Note: adding a blank line after the @author line works, and so does moving
    the @author line to the end)
    
    I think these examples are pretty self explanatory, but if you need more
    details, please let me know.
    
    Note: this problem may be related to
    https://bugzilla.gnome.org/show_bug.cgi?id=742616 and/or
    https://bugzilla.gnome.org/show_bug.cgi?id=344713

**Comment by albert-github** [comment]
This issue contains 2 issues:
- mainpage: I've just pushed a proposed patch, pull request #8952 
- author, in the 1.8.12 version I can reproduce the problem, in the 1.9.2 version the issue is gone. So for this part I think the problem has been solved already.

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.3.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
