### ISSUE TITLE
HTML_INDEX_NUM_ENTRIES incorrectly referred to as HTML_NUM_INDEX_ENTRIES in doc (Origin: bugzilla #772874)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6085]
status NEEDINFO severity *minor* in component *documentation* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2016-10-13 15:57:44 +0000, J. P. Abelanet wrote:

    Here is the page with the incorrect name for this option:
    
    http://www.doxygen.nl/config.html

On 2016-10-13 17:00:04 +0000, albert wrote:

    I looked at the different pages that I could find:
    - http://www.doxygen.nl/config.html#cfg_html_index_num_entries
    - http://www.stack.nl/~dimitri/doxygen/manual/config.html
    - source code
    and all these pages were OK (by head the page is generated from the source
    code!).
    
    Looking in the page:
    http://www.doxygen.nl/config.html
    I saw: latest release v1.8.3 - last page update Wed Dec 26 2012
    
    So it looks like the doxygen.nl has some old pages lying around, the main
    page of www.doxygen.nl looks OK again.

On 2016-10-16 17:41:15 +0000, Dimitri van Heesch wrote:

    doxygen.nl is a backup mirror copy of doxygen.org. Quite some time ago, I've
    moved the manual to the manual sub directory on the doxygen.org server. The
    old pages are still there on doxygen.nl however, since the mirroring process
    doesn't delete anything.
    
    Question to the submitter; where did you find a link to
    www.doxygen.nl/config.html?

On 2016-10-17 15:52:23 +0000, J. P. Abelanet wrote:

https://www.google.com/search?q=doxygen+class+list+collapsed+by+default&ie=utf-8&oe=utf-8&aq=t&rls=org.mozilla
    :en-US:official&client=firefox-a
    
    4th hit.

**Comment by albert-github** [comment]
Regarding the search link from J. P. Abelanet the 4-th hit is in a search engine a moving target and on the mentioned page I could not locate the relevant `http://www.doxygen.nl/config.html`

The reference to `http://www.doxygen.nl/config.html` (and also `http://www.doxygen.org/config.html`) now gives a "404 Page Not Found".


Seen the fact that stack.nl doesn't host doxygen stuff anymore and that the the domains of `doxygen.nl` and `doxygen.org` have (recently) moved to another provider I think that when are still references to e.g. `http://www.doxygen.nl/config.html` this is a so called "link rot" and a problem of the linking instance and not a doxygen issue..
