### ISSUE TITLE
GENERATE_LEGEND with svg graphs (Origin: bugzilla #774111)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6102]
status NEEDINFO severity *normal* in component *general* for *---*
Reported in version *1.8.11* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[Project1DllB774100-skewed.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug774111_343590_Project1DllB774100-skewed.zip/download/download)_ (ID 343590)

On 2016-11-08 16:45:37 +0000, Bob D. wrote:

    I tried to use the GENERATE_LEGEND on a couple of SVG graphs. And in another
    project that use PNG graphs, I manage to get a link underneath pointing to
    the legend. But not with interactive SVG. So, probably a bug?
    
    Cheers.

On 2016-11-14 20:58:55 +0000, Dimitri van Heesch wrote:

    Can you please attach a self-contained example (source+config file in a tar
    or zip) that allows me to reproduce the problem?

On 2017-01-16 20:42:19 +0000, Bob D. wrote:

    Created attachment 343590
    The collaboration diagrams and all doesn't provide any lnik to the legend
    there.

On 2017-08-25 12:03:35 +0000, albert wrote:

    In neither the svg version nor the png version (set through
    DOT_IMAGE_FORMAT) I see a reference to a legend. Can you point me where you
    saw the link?

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.3.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
