### ISSUE TITLE
EXTERNAL_GROUPS lose hierarchy (Origin: bugzilla #774118)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6104]
status NEEDINFO severity *normal* in component *general* for *---*
Reported in version *1.8.11* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[ExampleCppCodeB774118-skewed.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug774118_343671_ExampleCppCodeB774118-skewed.zip/download/download)_ (ID 343671)
- _[ExampleCppCodeB774118v2-skewed.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug774118_343673_ExampleCppCodeB774118v2-skewed.zip/download/download)_ (ID 343673)

On 2016-11-08 20:17:33 +0000, Bob D. wrote:

    I have two projects. One exports tags, and the second import them. There,
    that works. Thus, the second project can access to the groups of the first
    project. But the hierarchy of the first project is not kept. I expected to
    have the tags keeping the hierarchy. Instead of that, I have a flood of
    unordered external groups, making it difficult to even find the one that are
    not external in the left navigation pane.
    
    Is it possible to keep the hierarchy?

On 2016-11-14 20:59:25 +0000, Dimitri van Heesch wrote:

    Can you please attach a self-contained example (source+config file in a tar
    or zip) that allows me to reproduce the problem?

On 2017-01-17 20:22:31 +0000, Bob D. wrote:

    Created attachment 343671
    Example of a bug where a category, that should have been fetched by the
    tags, completly disappear
    
    Another bug related to the previous one. A category is missing, and another
    one as a function that shouldn't be there. foo2 appears in 2 categories.

On 2017-01-17 20:53:29 +0000, Bob D. wrote:

    Created attachment 343673
    This bug correspond more closely to the bug I reported
    
    An illustration of what I was describing in the ticket.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6650

**Comment by albert-github** [comment]
Code has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
