### ISSUE TITLE
Please add HTML classes to "Definition at..." & "Referenced by..." for CSS (Origin: bugzilla #774138)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6105]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2016-11-09 10:47:31 +0000, Tony Lewis wrote:

    I would like to use extra CSS to style the HTML lines like:
    
    Definition at line 62 of file a.cpp.
    
    and
    
    Referenced by foo().
    
    ...but I can't because these HTML elements have no classes I can use to
    identify them. Please will you add classes to allow them to be styled in
    CSS?
    
    Many thanks.

On 2016-11-13 10:27:07 +0000, albert wrote:

    I've just pushed a proposed patch to github (pull request 545)

**Comment by albert-github** [comment]
Pull request #545 has been integrated on November 28, 2016 and is in version 1.8.13.

So I think this problem is solved in the mean time.
