### ISSUE TITLE
Access to configuration variables in html (Origin: bugzilla #774166)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6106]
status NEEDINFO severity *enhancement* in component *general* for *---*
Reported in version *1.8.12* on platform *Other*
Assigned to: Dimitri van Heesch

On 2016-11-09 21:15:02 +0000, Bob D. wrote:

    I think it would be nice to access to the doxygen configuration varibles in
    the html header, through $VARIABLE. In such way, we could have configuration
    specific modification of the header.
    
    That is only a suggestion.

On 2016-11-13 10:39:18 +0000, albert wrote:

    Can you be a bit more clear about which part you are speaking about/ what
    kind of changes you propose?
    
    Can you accomplish this with an own html header / footer ?
    (see "15.1.4 Header, Footer, and Stylesheet changes" of the doxygen manual).

On 2016-11-14 15:02:26 +0000, Bob D. wrote:

    Yep, sure! Sorry, I wasn't clear enough.
    
    What I was trying to do is to access a Doxygen variable (let say for example
    SHOW_INCLUDE_FILES) in the html file (my own html header).
    By modifying the html header, I was able to add a couple of new HTML tags.
    In one of it (a hidden div), I wanted to keep a project specific information
    that I could later process in a custom javascript.
    
    In my particular situation, I share a lot of the Doxygen configuration
    across my projects, including the custom header.html. But I needed to access
    a specific project value, that I couldn't share among projects. Thus, I
    tried to add a variable PROJ_VAR in the Doxygen configuration and I tried to
    access it by $PROJ_VAR or $(PROJ_VAR) in the header html. But in the html,
    it seems that every Doxygen variable are mapped differently ($projectname
    for PROJECT_NAME or $extrastylesheet for HTML_EXTRA_STYLESHEET). Thus, the
    variable was kept plain text (it was not processes). And since the flag that
    I use in the Doxygen configuration file is unknown to Doxigen, I have a
    warning saying that the flag is ignored. If there was a mapping there, where
    the value was replaced by what I entered in the configuration for (or a
    custom XML aside for instance), it would have been convenient.
    
    I hope that it is clearer. If not, feel free to ask more explanations!

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6422

**Comment by albert-github** [comment]
An alternative pull request has been integrated into the doxygen 1.9.7 version ( #8779 ), so I think this problem has been solved in the mean time.
