### ISSUE TITLE
C++ using-declaration with nested template does not parse correctly without whitespace (Origin: bugzilla #774355)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6110]
status NEEDINFO severity *minor* in component *general* for *---*
Reported in version *1.8.8* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxygen-774355.tar.gz](https://sourceforge.net/projects/doxygen/files/attachments/bug774355_339770_doxygen-774355.tar.gz/download/download)_ (ID 339770)

On 2016-11-13 11:12:42 +0000, Glenn McIntosh wrote:

    A using-declaration with a nested template leads doxygen 1.8.8 to report a
    non declared symbol. For example:
    
    /** 2D array of doubles */
    using Matrix = std::vector<std::vector<double>>;
    
    I assume the problem is caused by the C++11 style closing '>>' without
    whitespace, causing parser problems in doxygen.
    
    Rewriting the alias as either of the following is parsed correctly by
    doxygen:
    
    using Matrix = std::vector<std::vector<double> >;
    typedef std::vector<std::vector<double>> Matrix;

On 2016-11-13 15:28:52 +0000, Dimitri van Heesch wrote:

    I haven't been able to reproduce this.
    
    Can you please attach a self-contained example (source+config file in a tar
    or zip) that allows me to reproduce the problem?

On 2016-11-13 21:15:41 +0000, Glenn McIntosh wrote:

    Created attachment 339770
    test case
    
    It was more obscure than I thought, sorry. It only happens because I have
    defined the same alias in two places, and only because they are both in the
    same namespace. It only gives a warning on the second definition.

**Comment by albert-github** [comment]
With the doxygen version 1.8.8 we get the warning:
```
matrix.h:6: warning: documented symbol `typedef math::std::vector< std::vector< double >> math::Matrix' was not declared or defined.
```
with the current doxygen version (1.9.6) we don't get this warning anymore.

I think the problem has been solved in the mean time.
