### ISSUE TITLE
#include continuation causes processing termination (Origin: bugzilla #776622)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6132]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.12* on platform *Other*
Assigned to: Dimitri van Heesch

On 2016-12-30 17:05:53 +0000, Randall S. Becker wrote:

    If a C source file has a continuation character inside a #include statement,
    processing of the file is abruptly terminated without notice.
    
    On the HPE NonStop platform, the following construct is legitimate within
    all C compilers:
    
    #include <file(section1, section2)>
    
    In many cases, there may be many sections. For readability, the following
    structure is often used:
    
    #include <file(section1, \
       section2)>
    
    The latter form causes doxygen to ignore the remainder of the file's
    content. This also happens in the case when " is used instead of the
    #include <> form.
    
    The workaround is either to remove the line continuation or include the
    entire file using the form.
    
    #include <file>

**Comment by albert-github** [comment]
To the best of my knowledge this is not a syntax that is defined in the C or C++ standard and hence not really valid code.

I think the problem is not a doxygen issue.
