### ISSUE TITLE
Incorrect warning about operator& (Origin: bugzilla #776661)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6133]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.13* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxygen.tar.gz](https://sourceforge.net/projects/doxygen/files/attachments/bug776661_342674_doxygen.tar.gz/download/download)_ (ID 342674)

On 2016-12-31 22:32:34 +0000, Peter Klotz wrote:

    Created attachment 342674
    Test case to reproduce the warning
    
    For the C++ code below doxygen incorrectly prints this warning:
    
    Test.cpp:11: warning: documented symbol `A * B::operator &' was not declared
    or defined.
    
    The generated documentation seems ok. The class and its operator are
    mentioned.
    
    The test code:
    
    -----------------
    class A;
    
    /// This is class B
    class B
    {
    public:
        /// This is operator&
        A* operator&();
    };
    
    A* B::operator&()
    {
        return nullptr;
    }
    -----------------
    
    Please find attached a complete test case containing the Doxyfile. The
    warning is printed starting with Doxygen 1.8.12 and is also present in
    1.8.13.

On 2017-06-15 13:48:23 +0000, ThÃ©ophile Bastian wrote:

    Hello,
    
    The same bug still occurs in Doxygen 1.8.13.
    
    Please note that if the prototype is replaced by
        A* operator &();
    that is, if a space is inserted between `operator` and the ampersand, the
    warning will disappear.

**Comment by albert-github** [comment]
With version 1.8.13 I could reproduce the problem.
With version 1.9.1 the problem is gone (as far as I can see with version 1.8.15).

I think the problem has been solved in the mean time.
