### ISSUE TITLE
indexing of unicode characters (Origin: bugzilla #777003)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6142]
status NEEDINFO severity *normal* in component *general* for *---*
Reported in version *1.8.12* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[physical.c](https://sourceforge.net/projects/doxygen/files/attachments/bug777003_343114_physical.c/download/download)_ (ID 343114)
- _[symbols.c](https://sourceforge.net/projects/doxygen/files/attachments/bug777003_343115_symbols.c/download/download)_ (ID 343115)
- _[Doxyfile](https://sourceforge.net/projects/doxygen/files/attachments/bug777003_343121_Doxyfile/download/download)_ (ID 343121)

On 2017-01-08 11:45:16 +0000, Jens Gustedt wrote:

    Created attachment 343114
    first source file with one module containing Phi0
    
    When global identifiers start with non-ascii unicode characters the
    assignment to an index group still seems to be messed up. This doesn't show
    for small projects but I have observed a crash of doxygen on a relatively
    large project.
    
    The first thing that seems to happen when the project size grows is that
    globals.html starts to contain lines like
    
    <h3><a id="index_\246"></a>- Î¦ -</h3><ul>
    
    where I retyped the \246 explicitly for visualization. In the original this
    is a single byte with that value.
    
    Then, when the project even grows further files with names like 
    
    globals-^N.html
    
    start to occur, where, again, I retyped the one byte ^N that my filesystem
    shows.
    
    In my project this eventually crashes doxygen saying that the file
    globals.html can't be written, which may be just because these filenames
    with control characters turn out to be the same for multiple index
    positions.
    
    Anyhow, I think the real bug is in the classification of things like Î¦ with
    an invalid character, namely \246, instead of using either a UTF8 string or
    a transcription of such a string. Probably somewhere this takes just the
    first `char` of a multibyte sequence, instead of using the proper multibyte
    to wide character conversion.
    
    I attach two source files that illustrate this behavior. This is somehow the
    minimal example that I managed to produce:
    
     - only one source file is not enough to produce the bogus html id
     - there must some threshold on the number of entries
     
    The example that has doxygen eventually crash is far too large to post here,
    and I had not much luck in sizing it down.
    
    Thanks
    Jens

On 2017-01-08 11:47:20 +0000, Jens Gustedt wrote:

    Created attachment 343115
    second source containing some other module with defines

On 2017-01-08 14:15:51 +0000, albert wrote:

    Looks like the used Doxyfile (doxygen configuration file is missing), please
    attach this file as well.
    
    Did you try also the current version (1.8.13) ?

On 2017-01-08 14:41:05 +0000, Jens Gustedt wrote:

    Created attachment 343121
    configuration file
    
    Here is the Doxyfile, don't know if it matters.
    
    No, I didn't try another version of doxygen, just the one that comes with my
    distro, Debian testing.
    
    Jens

On 2017-01-08 18:32:06 +0000, albert wrote:

    When I understand it correctly the problem is in the name of the index_ id
    and later on gets propagated to files.
    I was able to reproduce the problem regarding index_ on Windows (with 1.8.12
    and 1.8.13) with the provided Doxyfile.
    
    Looking at index.cpp here a routine letterToLabel is defined which should
    handle this. This routine call a function isId and I think in the later the
    base of the problem is as it is defined as:
    inline bool isId(int c)
    {
      return c=='_' || c>=128 || c<0 || isalnum(c);
    }
    and I think unicode characters can be > 128.
    
    In index.cpp we have in letterToLabel:
      if (isId(startLetter)) // printable ASCII character
    I think this should be replaced by:
      if (startLetter=='_' || (startLetter < 128 && isalnum(startLetter))) //
    printable ASCII character
    
    I don't want to change the isId function as this function is used on quite a
    few places and I cannot oversee the side effects, but probably this function
    needs to be adjusted to something like:
      return c=='_' || (c>0 && c<128 && isalnum(c));
    
    
    Would be good to know if this fix (in letterToLabel) also solves the
    problems regarding the files names. In case this cannot be tested is it
    possible that we obtain in one way or another access to the larger source
    code so we can check the problem regarding the file names?

On 2017-01-08 20:15:19 +0000, Jens Gustedt wrote:

    I think your understanding about the name of the index_ id is correct.
    
    Looking into the code (resp. what you show of it here) there seem to be
    several problems. The first is the prototype of isId and what can be assumed
    from it. It looks to me like a typical pre-unicode bare-char interface. int
    is probably not the right type for a unicode character, should be wint_t,
    wchar_t or something like that.
    
    For your proposed solution, are you sure that startLetter is a wide
    character and not just the first byte of the sequence?
    
    Then, for the ascii case, the test for startletter in index.cpp should just
    be isgraph(), and if wide character is assumed, it should be iswgraph().
    
    Maybe also, in my example there are some characters that you wouldn't want
    to accept for identifiers, but the Greek characters are certainly in the
    range that is intended by most programming languages. A solution that would
    accept everything that is !(iswpunct(c) || iswspace(c)) would probably be
    the easiest to maintain. (Plus the '_' ...)
    
    Jens

**Comment by albert-github** [comment]
Contrary to what was reported previously, with version 1.8.12 I see those "strange" characters with 'index_' (in globals.html. globals_defs.html and in menudata.js).
With version 1.8.13 and higher those strange characters are not shown anymore with 'index_' but replaced by .0x....'

I think the problem has been solved in the mean time.
