### ISSUE TITLE
Wrong input encoding can make doxygen crash (Origin: bugzilla #777237)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6144]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.12* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[ExampleCppCodeB777237-skewed2.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug777237_343676_ExampleCppCodeB777237-skewed2.zip/download/download)_ (ID 343676)

On 2017-01-13 21:33:09 +0000, Bob D. wrote:

    In C++, for html page generation
    
    When the wrong input encoding is selected for files, it can make doxygen
    crash. In my very specific case, I chose Windows-1252 as input encoding,
    because most of my project files are in that format. However, Boost is using
    utf-8 on some files. Thus, when it is parsing that folder, the encoding I
    provide is wrong. I should expect to have bad characters, but not a crash
    from doxygen.
    
    It crashes during the parsing/preprocessing.

On 2017-01-14 12:17:25 +0000, Dimitri van Heesch wrote:

    Hi Bob,
    
    Crashing is not good of course, but without a way to reproduce the problem
    (or at the very least a stack trace) there is not much that I can do.

On 2017-01-17 21:48:53 +0000, Bob D. wrote:

    Created attachment 343676
    Example of crashes occuring because of encoding, and some other obscur
    reason
    
    There is the required example.

On 2017-08-25 13:26:06 +0000, albert wrote:

    The file boost/type_traits/detail/common_arithmetic_type.hpp contains the
    UTF-8 characters â and â (in octal: 0342 0200 0234 and 0342 0200 0235)
    and this leads, in this case, to the fact that the iconv library terminates
    (without message, just the atexit call of doxygen gives the "Exiting ...").

**Comment by albert-github** [comment]
In the previous comment I write:

> The file boost/type_traits/detail/common_arithmetic_type.hpp contains the UTF-8 characters “ and ” (in octal: 0342 0200 0234 and 0342 0200 0235) and this leads, in this case, to the fact that the iconv library terminates (without message, just the atexit call of doxygen gives the "Exiting ...").

Problem is even a bit easier, there is a message in the `warnings.log` file saying:
`.../boost/type_traits/detail/common_arithmetic_type.hpp: failed to translate characters from Windows-1252 to UTF-8: check INPUT_ENCODING`

So the message is present but "hidden".

I think the issue can be closed as usage.
