### ISSUE TITLE
Strange navtree behavior when generating documentation from Python (Origin: bugzilla #777241)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6145]
status NEW severity *normal* in component *documentation* for *---*
Reported in version *1.8.13* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[treeviewbug.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug777241_343464_treeviewbug.zip/download/download)_ (ID 343464)

On 2017-01-14 01:02:38 +0000, mrjogo@gmail.com wrote:

    Created attachment 343464
    Dummy source and doxygen output
    
    The navtree behaves strangely when documentation is generated from a certain
    combination of python files. I have attached a zip of both a dummy project
    and the html output generated from doxygen.
    
    To see the incorrect behavior in the generated HTML, click on doxybug >
    Namespaces > Namespace List > doxybug > file3 in the nav tree. The two
    problems are that only one file is displayed (there are 4), and file3 is not
    highlighted. If you open a javascript console, you'll notice there is an
    exception when file3 is clicked.
    
    file1, file2, and file4 each contain a dummy Python function. file3 contains
    a dummy Python class. From playing around, it seems like the bug is somehow
    dependent on both the number of files (deleting one seems to fix it) and the
    position of file3, the one with the class (renaming it to file0 also seems
    to fix it).
    
    I am using Doxygen 1.8.13 built from the source tarball on Ubuntu 16.04.1.

On 2017-04-15 22:00:49 +0000, krinkodot22@hotmail.com wrote:

    *** Bug 781344 has been marked as a duplicate of this bug. ***

On 2017-04-16 07:42:23 +0000, albert wrote:

    (In reply to krinkodot22 from comment # 1)
    > *** Bug 781344 has been marked as a duplicate of this bug. ***
    
    Bug 781344 is a Nautilus buf and Bug 77241 is a doxygen bug, so I don't
    think they can be duplicates of each other the reference should have been to
    bug 777214

On 2017-04-16 07:45:27 +0000, albert wrote:

    Now I'm making some typos (so ignore text in comment # 2)
    Bug 781344 is a Nautilus bug and Bug 777241 is a doxygen bug, so I don't
    think they can be duplicates of each other the reference should have been to
    bug 777214

**Comment by albert-github** [comment]
With the 1.8.13 doxyge version I can see the described behavior:

![image](https://user-images.githubusercontent.com/5223533/173877461-cdec8316-db20-460f-8e4d-cedb528cc9e8.png)

with the doxygen version 1.9.4 the behavior looks like to be as expected:

![image](https://user-images.githubusercontent.com/5223533/173877356-0d7be084-ec75-4cf1-8076-5a65fe4d4afd.png)

I think the problem has been solved in the mean time
