### ISSUE TITLE
warning: "no matching file member found for" for functions with template parameter (Origin: bugzilla #777529)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6150]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.13* on platform *Other*
Assigned to: Dimitri van Heesch

On 2017-01-20 10:39:11 +0000, Marc Alff wrote:

    With the following code:
    -- begin
    /**
      @file sql/sql_rename_bug.cc
      Narrowed down bug in doxygen.
    */
    
    #include <set>
    
    struct handlerton;
    
    static void
    foo(std::set<handlerton*> *param);
    
    /**
      Function prototype that confuses doxygen.
      @param[in,out]  param     Ouch.
    */
    
    static void
    foo(std::set<handlerton*> *param)
    {
    }
    -- end
    
    doxygen reports the following error:
    
    /home/malff/GIT_WL7743/sql/sql_rename_bug.cc:34: warning: no matching file
    member found for
    static void foo(std::set< handlerton * > *param)
    Possible candidates:
     'static void foo(std::set< handlerton *> *param)' at line 26 of
    file/home/malff/GIT_WL7743/sql/sql_rename_
    bug.cc
    
    Expectation is no warning here, as the code is correct:
    The forward declaration matches exactly the function implementation.
    
    Reproduced with doxygen 1.8.13, but no error raised in 1.8.6
    
    Note in the doxygen warning the small discrepancy when printing the
    prototype: there is a space mismatch:
      std::set< handlerton * > *param
    versus
      std::set< handlerton *> *param
    
    Also, with the warning text printed, "file" is followed by the file name
    without spaces.

**Comment by albert-github** [comment]
With the version 1.8.13 I see the given warning.
In the 1,8,6 version the warning is not present,.
In the 1.9.2 version the warning is also not present.

The remark regarding the file and the filename without the space is in the 1.9.2 version also gone.

I think the problem has been solved in the mean time.
