### ISSUE TITLE
Error when running "make install" on binary package: cannot stat 'bin/doxytag': No such file or directory (Origin: bugzilla #778214)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6162]
status REOPENED severity *normal* in component *build* for *---*
Reported in version *1.8.13* on platform *Other*
Assigned to: Dimitri van Heesch

On 2017-02-05 19:29:01 +0000, kogorman@gmail.com wrote:

    I got the binary for Linux x86-64, and attempted to install on Ubuntu
    16.04.1 LTS, and it failed the "make install" step with the following
    result:
    
    root@plato-x:~/Downloads/doxygen-1.8.13# ./configure
      Checking for GNU install tool... using /usr/bin/install
      Created Makefile from Makefile.in...
    root@plato-x:~/Downloads/doxygen-1.8.13# make install
    /usr/bin/install -d /usr/local/bin
    /usr/bin/install -d /usr/local/doc/doxygen
    /usr/bin/install -m 755 bin/doxygen    /usr/local/bin
    /usr/bin/install -m 755 bin/doxytag    /usr/local/bin
    /usr/bin/install: cannot stat 'bin/doxytag': No such file or directory
    Makefile:13: recipe for target 'install' failed
    make: *** [install] Error 1
    
    My system info:
    root@plato-x:~/Downloads/doxygen-1.8.13# uname -a
    Linux plato-x 4.4.0-59-generic # 80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017
    x86_64 x86_64 x86_64 GNU/Linux
    
    Processors are dual Xeon with 256GB RAM

On 2017-02-05 22:42:41 +0000, AndrÃ© Klapper wrote:

    Thanks for taking the time to report this.
    What exact binary from what exact website? 
    Is the above terminal output and the above steps the complete output?

On 2017-02-05 23:08:45 +0000, kogorman@gmail.com wrote:

    The binary was in a file named doxygen-1.8.13.linux.bin.tar.gz and I
    downloaded it from http://www.stack.nl/~dimitri/doxygen/download.html
    
    The terminal output is everything except the un-tarring of the file and
    navigating to the unpacked (top) directory, but I still have that in one of
    my windows, so here's the whole thing:
    
    
    kevin@plato-x:~/Downloads$ tar xf doxygen-1.8.13.linux.bin.tar.gz 
    kevin@plato-x:~/Downloads$ cd doxygen-1.8.13/
    kevin@plato-x:~/Downloads/doxygen-1.8.13$ ls
    INSTALL  LICENSE  Makefile.in  README  VERSION  bin  configure  html
    kevin@plato-x:~/Downloads/doxygen-1.8.13$ less INSTALL 
    kevin@plato-x:~/Downloads/doxygen-1.8.13$ sudo bash
    [sudo] password for kevin: 
    root@plato-x:~/Downloads/doxygen-1.8.13# ./configure
      Checking for GNU install tool... using /usr/bin/install
      Created Makefile from Makefile.in...
    root@plato-x:~/Downloads/doxygen-1.8.13# make install
    /usr/bin/install -d /usr/local/bin
    /usr/bin/install -d /usr/local/doc/doxygen
    /usr/bin/install -m 755 bin/doxygen    /usr/local/bin
    /usr/bin/install -m 755 bin/doxytag    /usr/local/bin
    /usr/bin/install: cannot stat 'bin/doxytag': No such file or directory
    Makefile:13: recipe for target 'install' failed
    make: *** [install] Error 1
    root@plato-x:~/Downloads/doxygen-1.8.13# ls bin
    doxygen  doxyindexer  doxysearch.cgi
    root@plato-x:~/Downloads/doxygen-1.8.13# uname -a
    Linux plato-x 4.4.0-59-generic # 80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017
    x86_64 x86_64 x86_64 GNU/Linux
    root@plato-x:~/Downloads/doxygen-1.8.13#

On 2017-02-08 14:14:41 +0000, AndrÃ© Klapper wrote:

    If you skip important steps (compiling) then binaries will not be created,
    indeed. :) Hence closing this ticket as INVALID.

On 2017-02-08 15:19:59 +0000, kogorman@gmail.com wrote:

    That package was marked "binary".  What's up with compiling binary
    packages???

On 2017-02-08 15:24:03 +0000, kogorman@gmail.com wrote:

    Moreover, I went back to the package to see what would happen...  this
    happened
    
    kevin@plato-x:~/Downloads/doxygen-1.8.13$ sudo bash
    root@plato-x:~/Downloads/doxygen-1.8.13# make
    /usr/bin/install -d /usr/local/bin
    /usr/bin/install -d /usr/local/doc/doxygen
    /usr/bin/install -m 755 bin/doxygen    /usr/local/bin
    /usr/bin/install -m 755 bin/doxytag    /usr/local/bin
    /usr/bin/install: cannot stat 'bin/doxytag': No such file or directory
    Makefile:13: recipe for target 'install' failed
    make: *** [install] Error 1
    root@plato-x:~/Downloads/doxygen-1.8.13#

On 2017-02-09 11:56:48 +0000, AndrÃ© Klapper wrote:

    I am very sorry. Indeed
    http://www.stack.nl/~dimitri/doxygen/manual/install.html lists the steps you
    performed (which would have been nice to point out).

**Comment by hityc2019** [comment]
Did you solve the problem? I have the same question.

**Comment by albert-github** [comment]
@hityc2019 

- Which version of doxygen do you try to install?
- Where did you find the reference tio doxytag?

doxytag has been removed from the doxygen distribution for a while.

Note the current address of the documentation is http://www.doxygen.nl//manual/install.html

**Comment by rsarky** [comment]
Getting the same error

**Comment by albert-github** [comment]
@rsarky 
- Which version of doxygen do you try to install?
- Which operating system?
- from where did you get the installation?
- How did you copy to `/usr/bin` i.e. as which user / same user as when you tried to install? did you try to use sudo?
- During the installation did you get any (eror) messages?

**Comment by albert-github** [comment]
No further information provided and we have not seen recent reports about installation problems.

I think the problem has been solved in the mean time.
