### ISSUE TITLE
Non-static itcl instance variables listed as static (Origin: bugzilla #779046)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6171]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.13* on platform *Other*
Assigned to: Dimitri van Heesch

On 2017-02-22 04:23:28 +0000, G wrote:

    The Tcl language, via Itcl, supports both instance and class variables.
    Variables defined with the "variable" command are instance variables, while
    variables defined with the "common" command are "static" variables. For
    example,
    
    package require Itcl
    
    ##
    # Test class
    itcl::class Test {
        ## Test non-static variable
        variable v_1
    
        ## Test static variable
        common v_2 42
    
        ## Constructor to initialize non-static variable
        constructor {v} {
            set v_1 $v
        }
    }
    
    When doxygen is run on this example, both variables "v_1" and "v_2" appear
    in the "Static Public Attributes" section. Only the "v_2" variable should
    appear in this section. The "v_1" variable is an instance variable and
    should appear in the non-static section. Doxygen also does not seem to pay
    any attention to "public" or "private" specification in Itcl.

**Comment by albert-github** [comment]
• By means of commit 58ea5cf320f08ae2ec3e5fbd02d82ca0ba4477a7  the support has been removed from doxygen.
