### ISSUE TITLE
CREATE_SUBDIRS breaks SERVER_BASED_SEARCH (Origin: bugzilla #779141)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6172]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.13-GIT* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[fotobox.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug779141_372445_fotobox.zip/download/download)_ (ID 372445)

On 2017-02-23 16:41:07 +0000, Thomas Kais wrote:

    CREATE_SUBDIRS = YES
    SERVER_BASED_SEARCH = YES
    
    You need to stay on the index.php page to get results from the search.
    Searching while stay on home site works fine. Only on sub sites it's broken.
    
    For example if you start the search function from a sub site like
    SERVER/dd/da0/todo.php the search wonât work because the link to
    search.php is wrong.
    
    Requested URL:	SERVER/dd/da0/search.php?query=test
    It should be:   SERVER/search.php?query=test
    
    Source:
    <form id="FSearchBox" action="search.php" method="get"><img
    id="MSearchSelect" src="../../search/mag.png" alt=""><input type="text"
    id="MSearchField" name="query" value="Search" size="20" accesskey="S"
    onfocus="searchBox.OnSearchFieldFocus(true)"
    onblur="searchBox.OnSearchFieldFocus(false)"></form>
    
    Like it's done with the picture it should be:   action="../../search.php"
    
    Can you please fix that issue.
    
    Thank you! Regards, Thomas

On 2018-05-28 14:40:08 +0000, Thomas Kais wrote:

    Can you please give me a status report? Fixed or still broken?

On 2018-05-28 14:43:16 +0000, albert wrote:

    To easily check it:
    Can you please attach a, small, self contained example (source+config file
    in a tar or zip) that allows us to reproduce the problem?

On 2018-05-28 15:02:11 +0000, Thomas Kais wrote:

    Created attachment 372445
    example
    
    Use search from main page (/fotobox/index.php) is working. Go to a sub page
    e.g. /fotobox/d4/df8/class_foto_box.php and then search return a 404 - File
    or directory not found.
    Failed to load resource: the server responded with a status of 404 (Not
    Found)
    
    I think this is caused by CREATE_SUBDIRS = YES combined with
    SERVER_BASED_SEARCH = YES

On 2018-05-28 15:34:37 +0000, albert wrote:

    To be able to reproduce / check / fix the problem not only the output in
    needed but a small(!) source setup is required.

On 2018-05-28 16:48:17 +0000, albert wrote:

    I've just pushed a proposed patch to github (pull request 747,
    https://github.com/doxygen/doxygen/pull/747).
    
    Patch based on:
    - seen output
    - small test (cannot test server)
    - small example;
    /** \file
      * The file */
    
    /** \brief the function */
    void foo(void);

On 2018-05-29 07:56:51 +0000, Thomas Kais wrote:

    hi albert,
    thank you for your quick fix. maybe that could help! i'll test it asap. is
    it possible to get nightly windows builds?
    regards, thomas

On 2018-05-29 08:04:32 +0000, Thomas Kais wrote:

    sorry^^ I have just patched our menu.js file and your fix works!

On 2018-05-29 08:05:20 +0000, Thomas Kais wrote:

    thank you!

On 2018-05-29 08:14:05 +0000, albert wrote:

    Don't set the issue to "Resolved Fixed" as this disrupts the release
    process! (I've reopened the issue again and set to "New").
    
    Furthermore the patch is just a proposed patch and is not yet in the main
    stream of doxygen.
    
    
    As far as I know, at the moment, no overnight builds are foreseen and would
    also require systems continuously running for the, possible, builds
    (costs,).
    
    It is reasonably easy to build an executable based on the patch, either
    - download the main version of doxygen (release or current github head)
      - apply patch to this 
    - download the branch as indicated in the pull request
    from these sources do the build.
    
    In case you just patched the menu.js in your results, this means that one
    has to patch the output each time a new doxygen generation is done (!) as
    the main.js is written out by the executable.

On 2018-05-29 09:38:44 +0000, Thomas Kais wrote:

    Thanks for the note. I won't change the status of the ticket now.
    
    I think we are waiting for the official release of doxygen. I created the
    ticket over a year ago and we have been able to live with it so far.
    Everyone in the team knows how to get to a search result. Thanks again for
    the fix!

**Comment by albert-github** [comment]
Code has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
