### ISSUE TITLE
typedef documentation not generated with short comment block. (Origin: bugzilla #779171)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6174]
status NEW severity *normal* in component *documentation* for *---*
Reported in version *1.8.13* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[Doxytest.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug779171_346629_Doxytest.zip/download/download)_ (ID 346629)

On 2017-02-24 12:08:14 +0000, Jim wrote:

    Created attachment 346629
    Zip file includes minimal .h file and Doxyfile to reproduce symptom.
    
    A typedef with a multi-line comment generates documentation as expected:
    
    /** @brief     My brief 1. 
    
    */
    typedef uint16_t myType1_t;
    
    
    but if the comment is shortened to 1 or 2 lines:-
    
    /** @brief      My brief 2.
    */
    typedef uint16_t myType2_t;
    
    then, the typedef does not appear in the typedef documentation section.

On 2017-02-24 12:13:06 +0000, Jim wrote:

    Same is true for function documentation.
    
    /** @brief     My func brief 1. 
    
    */
    uint16_t MyFunc1(void);
    
    
    /** @brief      My func brief 2.
    */
    uint16_t MyFunc2(void);

On 2017-02-24 16:14:29 +0000, Jim wrote:

    The problem only appears if the @brief command is present.
    
    This works correctly:-
    
    /**      My brief 1. 
    
    */
    typedef uint16_t myType1_t;
    
    
    /**       My brief 2.
    */
    typedef uint16_t myType2_t;

**Comment by albert-github** [comment]
When we look at the example with the 1.8.13 version we see:
![image](https://user-images.githubusercontent.com/5223533/153921484-cf8cce95-6d01-488f-8b78-7a2f59ed370e.png)


When we look with the 1.9.3 (c0b9eafbfb53286ce31e75e2b6c976ee4d345473) version we see:
![image](https://user-images.githubusercontent.com/5223533/153921399-40af401a-1577-4d4f-a0cb-0efb9d8ff062.png)


Lets take some essentials from the provided Doxyfile:
```
BRIEF_MEMBER_DESC      = NO
REPEAT_BRIEF           = NO
```

The question is "is there a detailed section present in both `typedef`s? It looks like that with the first `typedef` there is a detailed section, but this is empty. In the older versions of doxygen this was, incorrectly, seen as a detailed section, but newer versions of doxygen an empty section is not see as a section. The later interpretation is better.

So the Doxyfiles tells us not to show brief documentation and as there is no detailed section there is nothing to be shown and in the 1.8.13 there was incorrectly a brief section shown for the first `typedef`.

- in the past there was a bug regarding the detailed section
- in the current version there is no, correctly, detailed section shown. In case one wants to have a detailed section one could have a look at `ALWAYS_DETAILED_SEC`
