### ISSUE TITLE
plantuml:an unwanted newline is generated after @startuml (Origin: bugzilla #779407)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6175]
status NEW severity *minor* in component *build* for *---*
Reported in version *1.8.13* on platform *Other*
Assigned to: Dimitri van Heesch

On 2017-03-01 09:55:52 +0000, swmatisa@gmail.com wrote:

    When the following valid comment with PlantUML is added in a file:
    /** 
    @startuml
    version
    @enduml
    */
    
    An unwanted newline is generated after @startuml. The content of generated
    inline_umlgraph_1.pu is:
    @startuml
    
    version
    @enduml
    
    
    This is an invalid plantUML file because "version" must be at the fist line
    after @startuml
    
    The correct content of generated inline_umlgraph_1.pu is:
    @startuml
    version
    @enduml

On 2018-06-12 17:01:02 +0000, albert wrote:

    Added the following special plantuml commands:
    author
    checkversion
    licence
    license
    sudoku [<seed>]
    testdot
    version
    
    I've just pushed a proposed patch to github (pull request 765,
    https://github.com/doxygen/doxygen/pull/765).

**Comment by albert-github** [comment]
Alternative implementation has been integrated in master.

**Comment by albert-github** [comment]
See also regression pull request #6452

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
