### ISSUE TITLE
\TODO breaks tables (Origin: bugzilla #779550)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6176]
status NEW severity *normal* in component *general* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2017-03-03 19:32:21 +0000, roberthannah89@gmail.com wrote:

    using \TODO inside a table causes subsequent rows to be booted from the
    table into a standard paragraph.

**Comment by albert-github** [comment]
This report describes a problem like the problem described in #6028.

I think this is a duplicate of #6028.
