### ISSUE TITLE
Typo in http://doxygen.nl/manual/docblocks.html (Origin: bugzilla #779650)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6177]
status NEW severity *normal* in component *documentation* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2017-03-06 13:03:33 +0000, FAR wrote:

    In the Last section ("Anatomy of a comment block") you wrote:
    
    It's formatting is inspired by plain text mail.
    
    Change "It's" to "Its" to get the correct phrase:
    
    Its formatting is inspired by plain text mail.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7536

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.18.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
