### ISSUE TITLE
ghost "references" function (Origin: bugzilla #780356)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6181]
status NEW severity *major* in component *general* for *---*
Reported in version *1.8.13* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxygenTest.tgz](https://sourceforge.net/projects/doxygen/files/attachments/bug780356_348420_doxygenTest.tgz/download/download)_ (ID 348420)

On 2017-03-21 15:46:26 +0000, jan.ruzicka@comtechmobile.com wrote:

    Created attachment 348420
    the example demonstrating ghost references
    
    âReferencesâ section of function documentation have functions that are
    not called in the documented function at all.
    In example below, function aa::a1() just returns a value, but the
    "references" section has link to aa::b1().
    
    Example: (b.cpp in attached .tgz)
    ----------------
     /** @file
      * @brief with namespace, with group
      * **/
     
     namespace aa {
     
     int a1 (void);
     int b1 (void);
     
     }
     /**
      * @defgroup grp Group1
      * @brief a group with namespace
      * @{
      * */
     int
     aa::
     a1 (void)
     {
     return 1;
     }
     int
     aa::
     b1 (void)
     {
     return 2;
     }
     /** @} */
    ----------------
    
    
    The problem seems to be related to a combination of group, namespace and
    function definition.
    
    See attached tgz. 
    The a.cpp and c.cpp behave normally as expected.
    The b.cpp links functions to each other even when they have any calls in
    their body.
    
    The difference between b.cpp and c.cpp
    Is syntax of function definition
    
        int
        aa::
        a1 (void)
            
       triggers the issue (I know that it is not usual syntax, but source code
    canât be changed at this moment)
    
    vs.
    
        int bb::a2 (void)
    
       behaves as expected.
    
    The References section seems to always include a next function within the
    group and the source file.

**Comment by albert-github** [comment]
I checked with version 1.9.13 and could observer the problem.
With version 1.8.14 the problem is gone.

I think the problem has been solved in the mean time.
