### ISSUE TITLE
(C++) Unable to parse parameter with default value of a escaped character (Origin: bugzilla #780430)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6182]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.13* on platform *Other*
Assigned to: Dimitri van Heesch

On 2017-03-23 06:29:45 +0000, Juan wrote:

    In a C++ header:
    
    Given:
       A method declaration in a C++ header file.
    When:
       A parameter contains a default string value with a escaped character
    (e.g., `"\n"`).
    Then:
       doxygen fails at parsing the parameter and generates a warning of
    parameter not found.
    
    For example:
    
    ```
    //File Benchmark.h
    /**
             Formats the results
             @param results is the vector of results
             @param shape is the shape to present the table of results
             @param contents indicates the information to include in the table
    of results
             @param delimiter is the delimiter of the table of results
             @return the formatted results from the benchmark
             */
    virtual std::string format(std::vector<Result> results, TableShape shape,
                    TableContents contents, const std::string& delimiter = "\t")
    const;
    ```
    
    The doxygen output is:
    
    `fuzzylite-master/fuzzylite/fl/Benchmark.h:385: warning: argument
    'delimiter' of command @param is not found in the argument list of
    fl::Benchmark::format(std::vector< Result > results, TableShape shape,
    TableContents contents, )`
    
    Steps to reproduce:
    (1) `git clone https://github.com/fuzzylite/fuzzylite.git .`
    (2) `doxygen Doxyfile`
    
    I can help fixing the bug if you provide some orientation as to where it
    could be.
    
    Thanks,
    
    Juan.

**Comment by albert-github** [comment]
I Checked with version 1.8.13 and I got the mentioned warning, with version 1.8.16 I didn't get the warning. The generated output with version 1.8.13 didn't look complete, the generated output with version 1.8.16 looked complete.

I think the problem has been solved in the mean time.
