### ISSUE TITLE
Nested @ingroup generates bad breadclumb list (Origin: bugzilla #780630)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6184]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.13* on platform *Other*
Assigned to: Dimitri van Heesch

On 2017-03-28 02:00:26 +0000, davigale.net@gmail.com wrote:

    I hope you will forgive me that I'm not good at English.
    
    /// @defgroup a a
    /// 
    /// @defgroup b b
    /// 
    /// @defgroup c c
    /// @ingroup  a
    /// 
    /// @defgroup d d
    /// @ingroup  b
    /// 
    /// @defgroup e e
    /// @ingroup  c d
    
    expected breadclumb list:
      a â« c | b â« d
    
    generated breadclumb list:
      a â« cb â« | d

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7535

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.18.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
