### ISSUE TITLE
Recent file menu not working (Origin: bugzilla #780648)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6186]
status NEW severity *normal* in component *doxywizard* for *---*
Reported in version *1.8.14-GIT* on platform *Other*
Assigned to: Dimitri van Heesch

On 2017-03-28 12:40:53 +0000, karsten.koop@gmx.de wrote:

    Opening a recent file via the menu does not work for me on Debian 9
    (testing), Qt 5.7.1.
    
    The reason is as follows:
    The name of the file is simply stored in the text of the QAction
    representing the menu entry. For some reason, Qt seems to automatically add
    an & to the menu entry text for the shortcut, which is returned from the
    QAction::text() call. So the string passed to QAction::setText() is not
    identically returned from QAction::text(). The relevant code is
    doxywizard.cpp:451:
    
        loadConfigFromFile(action->text());
    
    Using QAction::iconText() would be a workaround, as iconText() returns the
    text with the & stripped. Replacing doxywizard.cpp:451 with the following
    works for me:
    
        loadConfigFromFile(action->iconText());
    
    Other workaround would probably be to store the path somewhere else, e.g.
    using m_recentFiles or a property of the QAction object.

**Comment by albert-github** [comment]
I tried to reproduce the problem but didn't succeed (might be because I have a newer version of Qt).
I looked in the code but couldn't find any reference to the fact tat a text is set on an icon.

For me the issue is not reproducible.
