### ISSUE TITLE
name flag prevents warnings about undocumented function/parameter to be reported (Origin: bugzilla #780912)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6189]
status NEW severity *normal* in component *documentation* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2017-04-04 18:45:11 +0000, jpo38 wrote:

    My doxygen configuration file specifies:
    
        WARN_NO_PARAMDOC       = YES
        WARN_IF_UNDOCUMENTED   = YES
    
    Meaning that I want to get a warning when a function is not documented, or
    partially documented. Because I have the requirement to have a code fully
    documented.
    
    When I run doxygen on this code:
    
        /** Description */
        class A
        {
        public:
            void func1();
            int func2( int param1, int param2 );
        
            /** Partial description (missing a parameter)
             * \param param1 description
             * \return description
             */
            int func3( int param1, int param2 );
        
            /** Partial description (missing return value)
             * \param param1 description
             */
            int func4( int param1 );
        };
    
    I get 4 warnings:
    
        warning : Member func1() (function) of class A is not documented.
        warning : Member func2(int param1, int param2) (function) of class A is
    not documented.
        warning : The following parameters of A::func3(int param1, int param2)
    are not documented.
        warning : return type of member A::func4 is not documented
    
    Fine.
    
    Now, if someone adds `/** \name functions: */` before `func1` declaration,
    we then only get two warnings:
    
        warning : The following parameters of A::func3(int param1, int param2)
    are not documented:
        warning : return type of member A::func4 is not documented
    
     - The fact that `func1` has no documentation is not reported anymore. One
    could argue (see Bug 542885) it has a documentation inherited from `\name`
    flag, but it definitely isn't documented!
    
     - The fact  that `func2` missing arguments and return value is not reported
    anymore. Here, one couldn't honestly argue ;-), there are definitely
    undocumented parameters here and they must generate a warning.
    
    **Is there any way to keep 4 warnings be reported here (by customizing the
    doxyfile content for instance?).**
    
    For now, the only alternative I have is to temporarily replace all `\name`
    and `@name` by `name(not a doxygen flag)`, generate documentation, fix
    warnings, then, replace `name(not a doxygen flag)` by `\name` back....really
    annoying. I'm looking for a better way to handle that.

**Comment by albert-github** [comment]
With version 1.8.13:
- no `\name` we get 2 warnings about the not documented functions
- with `\name` we don't get warnings about the not documented functions

With version 1.8.15: we get with and without 2 warnings about the not documented functions

I think the problem has been solved in the mean time.
