### ISSUE TITLE
*** Error in `doxygen': realloc(): invalid pointer: 0x0000000001d45ba0 @ exit (Origin: bugzilla #781306)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6193]
status NEEDINFO severity *major* in component *build* for *---*
Reported in version *1.8.13* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[Doxyfile](https://sourceforge.net/projects/doxygen/files/attachments/bug781306_349855_Doxyfile/download/download)_ (ID 349855)
- _[FILEMAP](https://sourceforge.net/projects/doxygen/files/attachments/bug781306_349881_FILEMAP/download/download)_ (ID 349881)

On 2017-04-14 08:59:57 +0000, L A Walsh wrote:

    Just generated 1.8.13 (previous version 1.8.8 from opensuse 13.2 64-bit).
    
    It *seems* like it almost finishes, but didn't finish some ending tasks
    like dumping/closing the logfile.
    
    
    output from the end of execution...
    
     [81/82] converting xwin.cc
     [82/82] converting xwin.h
    [Fri Apr 14 01:48:26 PDT 2017] Done.
    *** Error in `doxygen': realloc(): invalid pointer: 0x0000000001d45ba0 ***
    ======= Backtrace: =========
    /lib64/libc.so.6[0x3000c7283f]
    /lib64/libc.so.6[0x3000c780ae]
    /lib64/libc.so.6[0x3000c7b1e5]
    doxygen(_ZN8QCString6LSData6resizeEPS0_i+0x3f)[0x6b39b7]
    doxygen(_ZN8QCString9StringRep6resizeEj+0x1d6)[0x6b4142]
    doxygen(_ZN8QCString6resizeEj+0x20)[0x6b36c0]
    doxygen(_ZN5Htags11loadFilemapERK8QCString+0x176)[0x6e34d8]
    doxygen(_Z14generateOutputv+0x319)[0x6b1dd7]
    doxygen(main+0x39)[0x67db8e]
    /lib64/libc.so.6(__libc_start_main+0xf5)[0x3000c21b05]
    doxygen[0x67da79]
    ======= Memory map: ========
    00400000-011dd000 r-xp 00000000 08:26 34128954
    /usr/bin/doxygen
    013dc000-013dd000 r--p 00ddc000 08:26 34128954
    /usr/bin/doxygen
    013dd000-013f6000 rw-p 00ddd000 08:26 34128954
    /usr/bin/doxygen
    013f6000-01d66000 rw-p 00000000 00:00 0
    [heap]
    3000000000-3000020000 r-xp 00000000 08:21 51193756
    /lib64/ld-2.19.so
    3000220000-3000221000 r--p 00020000 08:21 51193756
    /lib64/ld-2.19.so
    3000221000-3000222000 rw-p 00021000 08:21 51193756
    /lib64/ld-2.19.so
    3000222000-3000223000 rw-p 00000000 00:00 0 
    3000c00000-3000d9e000 r-xp 00000000 08:21 51193785
    /lib64/libc-2.19.so
    3000d9e000-3000f9d000 ---p 0019e000 08:21 51193785
    /lib64/libc-2.19.so
    3000f9d000-3000fa1000 r--p 0019d000 08:21 51193785
    /lib64/libc-2.19.so
    3000fa1000-3000fa3000 rw-p 001a1000 08:21 51193785
    /lib64/libc-2.19.so
    3000fa3000-3000fa7000 rw-p 00000000 00:00 0 
    3001000000-3001018000 r-xp 00000000 08:21 51458465
    /lib64/libpthread-2.19.so
    3001018000-3001217000 ---p 00018000 08:21 51458465
    /lib64/libpthread-2.19.so
    3001217000-3001218000 r--p 00017000 08:21 51458465
    /lib64/libpthread-2.19.so
    3001218000-3001219000 rw-p 00018000 08:21 51458465
    /lib64/libpthread-2.19.so
    3001219000-300121d000 rw-p 00000000 00:00 0 
    3001800000-3001900000 r-xp 00000000 08:21 51193789
    /lib64/libm-2.19.so
    3001900000-3001aff000 ---p 00100000 08:21 51193789
    /lib64/libm-2.19.so
    3001aff000-3001b00000 r--p 000ff000 08:21 51193789
    /lib64/libm-2.19.so
    3001b00000-3001b01000 rw-p 00100000 08:21 51193789
    /lib64/libm-2.19.so
    3001c00000-3001d8e000 r-xp 00000000 08:21 50338704
    /lib64/libstdc++.so.6.0.22
    3001d8e000-3001f8e000 ---p 0018e000 08:21 50338704
    /lib64/libstdc++.so.6.0.22
    3001f8e000-3001f98000 r--p 0018e000 08:21 50338704
    /lib64/libstdc++.so.6.0.22
    3001f98000-3001f9a000 rw-p 00198000 08:21 50338704
    /lib64/libstdc++.so.6.0.22
    3001f9a000-3001f9e000 rw-p 00000000 00:00 0 
    3049a00000-3049a17000 r-xp 00000000 08:21 50850397
    /lib64/libgcc_s.so.1
    3049a17000-3049c16000 ---p 00017000 08:21 50850397
    /lib64/libgcc_s.so.1
    3049c16000-3049c17000 r--p 00016000 08:21 50850397
    /lib64/libgcc_s.so.1
    3049c17000-3049c18000 rw-p 00017000 08:21 50850397
    /lib64/libgcc_s.so.1
    7f691df64000-7f691e6e3000 rw-p 00000000 00:00 0 
    7f691e6e5000-7f691e74c000 rw-p 00000000 00:00 0 
    7f691e750000-7f691e752000 rw-p 00000000 00:00 0 
    7f691e752000-7f691e759000 r--s 00000000 08:26 38743841
    /usr/lib64/gconv/gconv-modules.cache
    7f691e759000-7f691e798000 r--p 00000000 08:26 539994
    /usr/lib/locale/en_US.UTF-8/LC_CTYPE
    7f691e798000-7f691e799000 rw-p 00000000 00:00 0 
    7fffb7a35000-7fffb7a59000 rw-p 00000000 00:00 0
    [stack]
    7fffb7ba0000-7fffb7ba2000 r--p 00000000 00:00 0
    [vvar]
    7fffb7ba2000-7fffb7ba4000 r-xp 00000000 00:00 0
    [vdso]
    ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0
    [vsyscall]
    Aborted (core dumped)
    
    -------------------
    Stack trace:
    > gdb /usr/bin/doxygen core
    Reading symbols from /usr/bin/doxygen...done.
    [New LWP 75786]
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib64/libthread_db.so.1".
    Core was generated by `doxygen'.
    Program terminated with signal SIGABRT, Aborted.
    # 0  0x0000003000c35187 in __GI_raise (sig=sig@entry=6)
        at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
    56  ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
    (gdb) where
    # 0  0x0000003000c35187 in __GI_raise (sig=sig@entry=6)
        at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
    # 1  0x0000003000c36538 in __GI_abort () at abort.c:78
    # 2  0x0000003000c72844 in __libc_message (do_abort=do_abort@entry=2, 
        fmt=fmt@entry=0x3000d64b70 "*** Error in `%s': %s: 0x%s ***\n")
        at ../sysdeps/posix/libc_fatal.c:175
    # 3  0x0000003000c780ae in malloc_printerr (action=3, 
        str=0x3000d60e93 "realloc(): invalid pointer", ptr=<optimized out>)
        at malloc.c:4991
    # 4  0x0000003000c7b1e5 in realloc_check (oldmem=0x1d45ba0, bytes=34, 
        caller=<optimized out>) at hooks.c:336
    # 5  0x00000000006b39b7 in QCString::LSData::resize(QCString::LSData*, int)
    ()
    # 6  0x00000000006b4142 in QCString::StringRep::resize(unsigned int) ()
    # 7  0x00000000006b36c0 in QCString::resize(unsigned int) ()
    # 8  0x00000000006e34d8 in Htags::loadFilemap(QCString const&) ()
    # 9  0x00000000006b1dd7 in generateOutput() ()
    # 10 0x000000000067db8e in main ()
    (gdb) 
    
    
    Using gcc 6.3, on linux 4.10.1...
    
    not sure what else to add.
    
    Previous version generated a logfile, but this one's logfile was 0-bytes
    long.
    
    Anything else to add?

On 2017-04-14 09:01:15 +0000, L A Walsh wrote:

    Created attachment 349855
    doxy config file
    
    doxy config file

On 2017-04-14 16:56:10 +0000, albert wrote:

    From a quick look in the code it looks like the crash occurs at line 131 of
    htags.cpp (would have been nice to have the line numbers of doxygen also in
    the stack trace, i.e. having doxygen self been compiled with debug option).
    
    Question is what is the content of the file FILEMAP in a HTMML directory
    (looks like a file read).
    
    It would also be nice to see what happens when doxygen is directly started
    with gdb
    
    The stack (big) trace also looks a bit like different versions of system
    libraries (I'm not able to point to something).

On 2017-04-15 04:50:26 +0000, L A Walsh wrote:

    Created attachment 349881
    filemap
    
    filemap attached.
    
    Since it uses Cmake for generating, it's not real clear where to
    change config options or even what options are available.
    
    Does Cmake have a config-help option like configure --help"
    
    (i.e. last version suse had was based on configure, FWIW)...

On 2017-04-15 04:54:43 +0000, L A Walsh wrote:

    how does one change status back to "open"... All I see is changing it to
    'resolved', which isn't the right status...?
    Thanks...
    -l
    
    Oh... libraries... um... the c++ libraries are generated when you generate
    the gcc/g++ tool chain, so they would be newer than the base libs.
    
    Is that what you were referring to?

On 2017-04-15 08:08:41 +0000, L A Walsh wrote:

    Rebuilt w/-ggdb and run under gdb, got:
     [82/82] converting xwin.h
    [Sat Apr 15 01:03:53 PDT 2017] Done.
    *** Error in `/usr/local/bin/doxygen': realloc(): invalid pointer:
    0x0000000001b3e200 ***
    ======= Backtrace: =========
    /lib64/libc.so.6[0x3000c7283f]
    /lib64/libc.so.6[0x3000c780ae]
    /lib64/libc.so.6[0x3000c7b1e5]
    /usr/local/bin/doxygen(_ZN8QCString6LSData6resizeEPS0_i+0x3f)[0x5fff71]
    /usr/local/bin/doxygen(_ZN8QCString9StringRep6resizeEj+0x1d6)[0x6006fc]
    /usr/local/bin/doxygen(_ZN8QCString6resizeEj+0x20)[0x5ffc7a]
    /usr/local/bin/doxygen(_ZN5Htags11loadFilemapERK8QCString+0x176)[0x62fe74]
    /usr/local/bin/doxygen(_Z14generateOutputv+0x319)[0x5fe390]
    /usr/local/bin/doxygen(main+0x39)[0x5c902e]
    /lib64/libc.so.6(__libc_start_main+0xf5)[0x3000c21b05]
    /usr/local/bin/doxygen[0x5c8f19]
    ======= Memory map: ========
    00400000-00fd5000 r-xp 00000000 08:26 548770
    /usr/local/bin/doxygen
    011d4000-011d5000 r--p 00bd4000 08:26 548770
    /usr/local/bin/doxygen
    011d5000-011ed000 rw-p 00bd5000 08:26 548770
    /usr/local/bin/doxygen
    011ed000-01b5e000 rw-p 00000000 00:00 0
    [heap]
    3000000000-3000020000 r-xp 00000000 08:21 51193756
    /lib64/ld-2.19.so
    3000220000-3000221000 r--p 00020000 08:21 51193756
    /lib64/ld-2.19.so
    3000221000-3000222000 rw-p 00021000 08:21 51193756
    /lib64/ld-2.19.so
    3000222000-3000223000 rw-p 00000000 00:00 0 
    3000800000-3000815000 r-xp 00000000 08:21 50339041
    /lib64/libz.so.1.2.8
    3000815000-3000a14000 ---p 00015000 08:21 50339041
    /lib64/libz.so.1.2.8
    3000a14000-3000a15000 r--p 00014000 08:21 50339041
    /lib64/libz.so.1.2.8
    3000a15000-3000a16000 rw-p 00015000 08:21 50339041
    /lib64/libz.so.1.2.8
    3000c00000-3000d9e000 r-xp 00000000 08:21 51193785
    /lib64/libc-2.19.so
    3000d9e000-3000f9d000 ---p 0019e000 08:21 51193785
    /lib64/libc-2.19.so
    3000f9d000-3000fa1000 r--p 0019d000 08:21 51193785
    /lib64/libc-2.19.so
    3000fa1000-3000fa3000 rw-p 001a1000 08:21 51193785
    /lib64/libc-2.19.so
    3000fa3000-3000fa7000 rw-p 00000000 00:00 0 
    3001000000-3001018000 r-xp 00000000 08:21 51458465
    /lib64/libpthread-2.19.so
    3001018000-3001217000 ---p 00018000 08:21 51458465
    /lib64/libpthread-2.19.so
    3001217000-3001218000 r--p 00017000 08:21 51458465
    /lib64/libpthread-2.19.so
    3001218000-3001219000 rw-p 00018000 08:21 51458465
    /lib64/libpthread-2.19.so
    3001219000-300121d000 rw-p 00000000 00:00 0 
    3001400000-3001403000 r-xp 00000000 08:21 51458471
    /lib64/libdl-2.19.so.save
    3001403000-3001602000 ---p 00003000 08:21 51458471
    /lib64/libdl-2.19.so.save
    3001602000-3001603000 r--p 00002000 08:21 51458471
    /lib64/libdl-2.19.so.save
    3001603000-3001604000 rw-p 00003000 08:21 51458471
    /lib64/libdl-2.19.so.save
    3001800000-3001900000 r-xp 00000000 08:21 51193789
    /lib64/libm-2.19.so
    3001900000-3001aff000 ---p 00100000 08:21 51193789
    /lib64/libm-2.19.so
    3001aff000-3001b00000 r--p 000ff000 08:21 51193789
    /lib64/libm-2.19.so
    3001b00000-3001b01000 rw-p 00100000 08:21 51193789
    /lib64/libm-2.19.so
    3001c00000-3001d8e000 r-xp 00000000 08:21 50338704
    /lib64/libstdc++.so.6.0.22
    3001d8e000-3001f8e000 ---p 0018e000 08:21 50338704
    /lib64/libstdc++.so.6.0.22
    3001f8e000-3001f98000 r--p 0018e000 08:21 50338704
    /lib64/libstdc++.so.6.0.22
    3001f98000-3001f9a000 rw-p 00198000 08:21 50338704
    /lib64/libstdc++.so.6.0.22
    3001f9a000-3001f9e000 rw-p 00000000 00:00 0 
    300f600000-300f62b000 r-xp 00000000 08:21 50333816
    /lib64/libtinfo.so.5.9
    300f62b000-300f82a000 ---p 0002b000 08:21 50333816
    /lib64/libtinfo.so.5.9
    300f82a000-300f82e000 r--p 0002a000 08:21 50333816
    /lib64/libtinfo.so.5.9
    300f82e000-300f833000 rw-p 0002e000 08:21 50333816
    /lib64/libtinfo.so.5.9
    300f833000-300f834000 rw-p 00000000 00:00 0 
    3049a00000-3049a17000 r-xp 00000000 08:21 50850397
    /lib64/libgcc_s.so.1
    3049a17000-3049c16000 ---p 00017000 08:21 50850397
    /lib64/libgcc_s.so.1
    3049c16000-3049c17000 r--p 00016000 08:21 50850397
    /lib64/libgcc_s.so.1
    3049c17000-3049c18000 rw-p 00017000 08:21 50850397
    /lib64/libgcc_s.so.1
    7ffff305f000-7ffff37de000 rw-p 00000000 00:00 0 
    7ffff37e0000-7ffff3847000 rw-p 00000000 00:00 0 
    7ffff3847000-7ffff3928000 r-xp 00000000 08:26 35173929
    /usr/lib64/libclangStaticAnalyzerCore.so
    7ffff3928000-7ffff3b27000 ---p 000e1000 08:26 35173929
    /usr/lib64/libclangStaticAnalyzerCore.so
    7ffff3b27000-7ffff3b2c000 r--p 000e0000 08:26 35173929
    /usr/lib64/libclangStaticAnalyzerCore.so
    7ffff3b2c000-7ffff3b2e000 rw-p 000e5000 08:26 35173929
    /usr/lib64/libclangStaticAnalyzerCore.so
    7ffff3b2e000-7ffff3b59000 r-xp 00000000 08:26 35231230
    /usr/lib64/libLLVMMCParser.so
    7ffff3b59000-7ffff3d59000 ---p 0002b000 08:26 35231230
    /usr/lib64/libLLVMMCParser.so
    7ffff3d59000-7ffff3d5a000 r--p 0002b000 08:26 35231230
    /usr/lib64/libLLVMMCParser.so
    7ffff3d5a000-7ffff3d5b000 rw-p 0002c000 08:26 35231230
    /usr/lib64/libLLVMMCParser.so
    7ffff3d5b000-7ffff3d5d000 rw-p 00000000 00:00 0 
    7ffff3d5d000-7ffff3f21000 r-xp 00000000 08:26 35231214
    /usr/lib64/libLLVMCore.so
    7ffff3f21000-7ffff4120000 ---p 001c4000 08:26 35231214
    /usr/lib64/libLLVMCore.so
    7ffff4120000-7ffff412d000 r--p 001c3000 08:26 35231214
    /usr/lib64/libLLVMCore.so
    7ffff412d000-7ffff4130000 rw-p 001d0000 08:26 35231214
    /usr/lib64/libLLVMCore.so
    7ffff4130000-7ffff423a000 r-xp 00000000 08:26 35173928
    /usr/lib64/libclangStaticAnalyzerCheckers.so
    7ffff423a000-7ffff443a000 ---p 0010a000 08:26 35173928
    /usr/lib64/libclangStaticAnalyzerCheckers.so
    7ffff443a000-7ffff443f000 r--p 0010a000 08:26 35173928
    /usr/lib64/libclangStaticAnalyzerCheckers.so
    7ffff443f000-7ffff4441000 rw-p 0010f000 08:26 35173928
    /usr/lib64/libclangStaticAnalyzerCheckers.so
    7ffff4441000-7ffff4442000 rw-p 00000000 00:00 0 
    7ffff4442000-7ffff4482000 r-xp 00000000 08:26 35154889
    /usr/lib64/libclangASTMatchers.so
    7ffff4482000-7ffff4682000 ---p 00040000 08:26 35154889
    /usr/lib64/libclangASTMatchers.so
    7ffff4682000-7ffff4683000 r--p 00040000 08:26 35154889
    /usr/lib64/libclangASTMatchers.so
    7ffff4683000-7ffff4684000 rw-p 00041000 08:26 35154889
    /usr/lib64/libclangASTMatchers.so
    7ffff4684000-7ffff46fd000 r-xp 00000000 08:26 35154902
    /usr/lib64/libclangAnalysis.so
    7ffff46fd000-7ffff48fc000 ---p 00079000 08:26 35154902
    /usr/lib64/libclangAnalysis.so
    7ffff48fc000-7ffff48fd000 r--p 00078000 08:26 35154902
    /usr/lib64/libclangAnalysis.so
    7ffff48fd000-7ffff48fe000 rw-p 00079000 08:26 35154902
    /usr/lib64/libclangAnalysis.so
    7ffff48fe000-7ffff48ff000 rw-p 00000000 00:00 0 
    7ffff48ff000-7ffff490c000 r-xp 00000000 08:26 35173855
    /usr/lib64/libclangRewrite.so
    7ffff490c000-7ffff4b0b000 ---p 0000d000 08:26 35173855
    /usr/lib64/libclangRewrite.so
    7ffff4b0b000-7ffff4b0c000 r--p 0000c000 08:26 35173855
    /usr/lib64/libclangRewrite.so
    7ffff4b0c000-7ffff4b0d000 rw-p 0000d000 08:26 35173855
    /usr/lib64/libclangRewrite.so
    7ffff4b0d000-7ffff4b43000 r-xp 00000000 08:26 35173830
    /usr/lib64/libclangFormat.so
    7ffff4b43000-7ffff4d42000 ---p 00036000 08:26 35173830
    /usr/lib64/libclangFormat.so
    7ffff4d42000-7ffff4d43000 r--p 00035000 08:26 35173830
    /usr/lib64/libclangFormat.so
    7ffff4d43000-7ffff4d44000 rw-p 00036000 08:26 35173830
    /usr/lib64/libclangFormat.so
    7ffff4d44000-7ffff4d50000 r-xp 00000000 08:26 35231233
    /usr/lib64/libLLVMOption.so
    7ffff4d50000-7ffff4f4f000 ---p 0000c000 08:26 35231233
    /usr/lib64/libLLVMOption.so
    7ffff4f4f000-7ffff4f50000 r--p 0000b000 08:26 35231233
    /usr/lib64/libLLVMOption.so
    7ffff4f50000-7ffff4f51000 rw-p 0000c000 08:26 35231233
    /usr/lib64/libLLVMOption.so
    7ffff4f51000-7ffff4f52000 rw-p 00000000 00:00 0 
    7ffff4f52000-7ffff507c000 r-xp 00000000 08:26 35173927
    /usr/lib64/libclangSerialization.so
    7ffff507c000-7ffff527c000 ---p 0012a000 08:26 35173927
    /usr/lib64/libclangSerialization.so
    7ffff527c000-7ffff527e000 r--p 0012a000 08:26 35173927
    /usr/lib64/libclangSerialization.so
    7ffff527e000-7ffff5281000 rw-p 0012c000 08:26 35173927
    /usr/lib64/libclangSerialization.so
    7ffff5281000-7ffff532b000 r-xp 00000000 08:26 35173854
    /usr/lib64/libclangParse.so
    7ffff532b000-7ffff552a000 ---p 000aa000 08:26 35173854
    /usr/lib64/libclangParse.so
    7ffff552a000-7ffff552c000 r--p 000a9000 08:26 35173854
    /usr/lib64/libclangParse.so
    7ffff552c000-7ffff552e000 rw-p 000ab000 08:26 35173854
    /usr/lib64/libclangParse.so
    7ffff552e000-7ffff5539000 r-xp 00000000 08:26 35173823
    /usr/lib64/libclangEdit.so
    7ffff5539000-7ffff5739000 ---p 0000b000 08:26 35173823
    /usr/lib64/libclangEdit.so
    7ffff5739000-7ffff573a000 r--p 0000b000 08:26 35173823
    /usr/lib64/libclangEdit.so
    7ffff573a000-7ffff573b000 rw-p 0000c000 08:26 35173823
    /usr/lib64/libclangEdit.so
    7ffff573b000-7ffff573c000 rw-p 00000000 00:00 0 
    7ffff573c000-7ffff57ee000 r-xp 00000000 08:26 35173799
    /usr/lib64/libclangDriver.so
    7ffff57ee000-7ffff59ee000 ---p 000b2000 08:26 35173799
    /usr/lib64/libclangDriver.so
    7ffff59ee000-7ffff5a08000 r--p 000b2000 08:26 35173799
    /usr/lib64/libclangDriver.so
    7ffff5a08000-7ffff5a09000 rw-p 000cc000 08:26 35173799
    /usr/lib64/libclangDriver.so
    7ffff5a09000-7ffff5a7d000 r-xp 00000000 08:26 35231227
    /usr/lib64/libLLVMMC.so
    7ffff5a7d000-7ffff5c7c000 ---p 00074000 08:26 35231227
    /usr/lib64/libLLVMMC.so
    7ffff5c7c000-7ffff5c80000 r--p 00073000 08:26 35231227
    /usr/lib64/libLLVMMC.so
    7ffff5c80000-7ffff5c81000 rw-p 00077000 08:26 35231227
    /usr/lib64/libLLVMMC.so
    7ffff5c81000-7ffff5c82000 rw-p 00000000 00:00 0 
    7ffff5c82000-7ffff5d43000 r-xp 00000000 08:26 35231279
    /usr/lib64/libLLVMSupport.so
    7ffff5d43000-7ffff5f42000 ---p 000c1000 08:26 35231279
    /usr/lib64/libLLVMSupport.so
    7ffff5f42000-7ffff5f47000 r--p 000c0000 08:26 35231279
    /usr/lib64/libLLVMSupport.so
    7ffff5f47000-7ffff5f49000 rw-p 000c5000 08:26 35231279
    /usr/lib64/libLLVMSupport.so
    7ffff5f49000-7ffff5f4b000 rw-p 00000000 00:00 0 
    7ffff5f4b000-7ffff5f72000 r-xp 00000000 08:26 35110941
    /usr/lib64/libLLVMBitReader.so
    7ffff5f72000-7ffff6172000 ---p 00027000 08:26 35110941
    /usr/lib64/libLLVMBitReader.so
    7ffff6172000-7ffff6173000 r--p 00027000 08:26 35110941
    /usr/lib64/libLLVMBitReader.so
    7ffff6173000-7ffff6174000 rw-p 00028000 08:26 35110941
    /usr/lib64/libLLVMBitReader.so
    7ffff6174000-7ffff6175000 rw-p 00000000 00:00 0 
    7ffff6175000-7ffff631b000 r-xp 00000000 08:26 34791867
    /usr/lib64/libclangARCMigrate.so
    7ffff631b000-7ffff651b000 ---p 001a6000 08:26 34791867
    /usr/lib64/libclangARCMigrate.so
    7ffff651b000-7ffff651c000 r--p 001a6000 08:26 34791867
    /usr/lib64/libclangARCMigrate.so
    7ffff651c000-7ffff651d000 rw-p 001a7000 08:26 34791867
    /usr/lib64/libclangARCMigrate.so
    7ffff651d000-7ffff653c000 r-xp 00000000 08:26 35173931
    /usr/lib64/libclangTooling.so
    7ffff653c000-7ffff673c000 ---p 0001f000 08:26 35173931
    /usr/lib64/libclangTooling.so
    7ffff673c000-7ffff673d000 r--p 0001f000 08:26 35173931
    /usr/lib64/libclangTooling.so
    7ffff673d000-7ffff673e000 rw-p 00020000 08:26 35173931
    /usr/lib64/libclangTooling.so
    7ffff673e000-7ffff6b72000 r-xp 00000000 08:26 35173926
    /usr/lib64/libclangSema.so
    7ffff6b72000-7ffff6d71000 ---p 00434000 08:26 35173926
    /usr/lib64/libclangSema.so
    7ffff6d71000-7ffff6d76000 r--p 00433000 08:26 35173926
    /usr/lib64/libclangSema.so
    7ffff6d76000-7ffff6d7b000 rw-p 00438000 08:26 35173926
    /usr/lib64/libclangSema.so
    7ffff6d7b000-7ffff6d7c000 rw-p 00000000 00:00 0 
    7ffff6d7c000-7ffff6e03000 r-xp 00000000 08:26 35173850
    /usr/lib64/libclangLex.so
    7ffff6e03000-7ffff7002000 ---p 00087000 08:26 35173850
    /usr/lib64/libclangLex.so
    7ffff7002000-7ffff7004000 r--p 00086000 08:26 35173850
    /usr/lib64/libclangLex.so
    7ffff7004000-7ffff7005000 rw-p 00088000 08:26 35173850
    /usr/lib64/libclangLex.so
    7ffff7005000-7ffff7006000 rw-p 00000000 00:00 0 
    7ffff7006000-7ffff7018000 r-xp 00000000 08:26 35173838
    /usr/lib64/libclangIndex.so
    7ffff7018000-7ffff7217000 ---p 00012000 08:26 35173838
    /usr/lib64/libclangIndex.so
    7ffff7217000-7ffff7218000 r--p 00011000 08:26 35173838
    /usr/lib64/libclangIndex.so
    7ffff7218000-7ffff7219000 rw-p 00012000 08:26 35173838
    /usr/lib64/libclangIndex.so
    7ffff7219000-7ffff72ef000 r-xp 00000000 08:26 35173833
    /usr/lib64/libclangFrontend.so
    7ffff72ef000-7ffff74ee000 ---p 000d6000 08:26 35173833
    /usr/lib64/libclangFrontend.so
    7ffff74ee000-7ffff74f2000 r--p 000d5000 08:26 35173833
    /usr/lib64/libclangFrontend.so
    7ffff74f2000-7ffff74f4000 rw-p 000d9000 08:26 35173833
    /usr/lib64/libclangFrontend.so
    7ffff74f4000-7ffff74f5000 rw-p 00000000 00:00 0 
    7ffff74f5000-7ffff7676000 r-xp 00000000 08:26 35154904
    /usr/lib64/libclangBasic.so
    7ffff7676000-7ffff7875000 ---p 00181000 08:26 35154904
    /usr/lib64/libclangBasic.so
    7ffff7875000-7ffff78c7000 r--p 00180000 08:26 35154904
    /usr/lib64/libclangBasic.so
    7ffff78c7000-7ffff78c8000 rw-p 001d2000 08:26 35154904
    /usr/lib64/libclangBasic.so
    7ffff78c8000-7ffff7b2b000 r-xp 00000000 08:26 34814406
    /usr/lib64/libclangAST.so
    7ffff7b2b000-7ffff7d2b000 ---p 00263000 08:26 34814406
    /usr/lib64/libclangAST.so
    7ffff7d2b000-7ffff7d38000 r--p 00263000 08:26 34814406
    /usr/lib64/libclangAST.so
    7ffff7d38000-7ffff7d3b000 rw-p 00270000 08:26 34814406
    /usr/lib64/libclangAST.so
    7ffff7d3b000-7ffff7d3e000 rw-p 00000000 00:00 0 
    7ffff7d3e000-7ffff7dac000 r-xp 00000000 08:26 34633159
    /usr/lib64/libclang.so.3.5
    7ffff7dac000-7ffff7fab000 ---p 0006e000 08:26 34633159
    /usr/lib64/libclang.so.3.5
    7ffff7fab000-7ffff7fad000 r--p 0006d000 08:26 34633159
    /usr/lib64/libclang.so.3.5
    7ffff7fad000-7ffff7fae000 rw-p 0006f000 08:26 34633159
    /usr/lib64/libclang.so.3.5
    7ffff7fb2000-7ffff7fb4000 rw-p 00000000 00:00 0 
    7ffff7fb4000-7ffff7fbb000 r--s 00000000 08:26 38743841
    /usr/lib64/gconv/gconv-modules.cache
    7ffff7fbb000-7ffff7ffa000 r--p 00000000 08:26 539994
    /usr/lib/locale/en_US.UTF-8/LC_CTYPE
    7ffff7ffa000-7ffff7ffb000 rw-p 00000000 00:00 0 
    7ffff7ffb000-7ffff7ffd000 r--p 00000000 00:00 0
    [vvar]
    7ffff7ffd000-7ffff7fff000 r-xp 00000000 00:00 0
    [vdso]
    7ffffffdb000-7ffffffff000 rw-p 00000000 00:00 0
    [stack]
    ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0
    [vsyscall]
    
    Program received signal SIGABRT, Aborted.
    0x0000003000c35187 in __GI_raise (sig=sig@entry=6)
        at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
    56  ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
    Missing separate debuginfos, use: zypper install libLLVM-
    debuginfo-3.5.0-7.1.x86_64 libclang-debuginfo-3.5.0-7.1.x86_64
    libncurses5-debuginfo-5.9-52.2.3.x86_64 libz1-debuginfo-1.2.8-5.8.1.x86_64
    (gdb)  where
    # 0  0x0000003000c35187 in __GI_raise (sig=sig@entry=6)
        at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
    # 1  0x0000003000c36538 in __GI_abort () at abort.c:78
    # 2  0x0000003000c72844 in __libc_message (do_abort=do_abort@entry=2, 
        fmt=fmt@entry=0x3000d64b70 "*** Error in `%s': %s: 0x%s ***\n")
        at ../sysdeps/posix/libc_fatal.c:175
    # 3  0x0000003000c780ae in malloc_printerr (action=3, 
        str=0x3000d60e93 "realloc(): invalid pointer", ptr=<optimized out>)
        at malloc.c:4991
    # 4  0x0000003000c7b1e5 in realloc_check (oldmem=0x1b3e200, bytes=34, 
        caller=<optimized out>) at hooks.c:336
    # 5  0x00000000005fff71 in QCString::LSData::resize (d=0x1b3e200, size=26)
        at
    /home/packages/sources/doxygen-1.8.13/doxygen-1.8.13/qtools/qcstring.h:397
    # 6  0x00000000006006fc in QCString::StringRep::resize (this=0x7fffffffb460,
        newlen=26)
        at
    /home/packages/sources/doxygen-1.8.13/doxygen-1.8.13/qtools/qcstring.h:664
    # 7  0x00000000005ffc7a in QCString::resize (this=0x7fffffffb460, newlen=26)
        at
    /home/packages/sources/doxygen-1.8.13/doxygen-1.8.13/qtools/qcstring.h:227
    # 8  0x000000000062fe74 in Htags::loadFilemap (htmlDir=...)
        at
    /home/packages/sources/doxygen-1.8.13/doxygen-1.8.13/src/htags.cpp:131
    # 9  0x00000000005fe390 in generateOutput ()
        at
    /home/packages/sources/doxygen-1.8.13/doxygen-1.8.13/src/doxygen.cpp:11455
    # 10 0x00000000005c902e in main (argc=1, argv=0x7fffffffb8c8)
        at /home/packages/sources/doxygen-1.8.13/doxygen-1.8.13/src/main.cpp:38

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6984

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
