### ISSUE TITLE
URL containing file name created in markdown file, breaks markdown render (Origin: bugzilla #781412)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6194]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.8.13* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[Screenshot 2017-04-17 17.34.48.png](https://sourceforge.net/projects/doxygen/files/attachments/bug781412_349954_Screenshot 2017-04-17 17.34.48.png/download/download)_ (ID 349954)

On 2017-04-17 16:35:59 +0000, amelvin@gmail.com wrote:

    Created attachment 349954
    bug in action
    
    Filename "README.md", file
    
    Code
    ```
    V2.2 Released please see 
    +
    [Changes](https://github.com/sticilface/espmanager/blob/master/ChangeLog.md)
    + [Changes](https://github.com/sticilface/espmanager/blob/master) 
    ```
    
    The first URL renders as 
    ```
    V2.2 Released please see
    
    https://github.com/sticilface/espmanager/blob/master/changelog.md "Changes"
    Changes
    
    ```
    instead of formatting the URL correctly.  Removing the ChangeLog.md part
    causes it to be rendered correctly.   There is a file ChangeLog.md, as I'm
    trying to point users to a changes file also stored in the repository.
    
    see attached:

**Comment by albert-github** [comment]
With the 1.8.13 version we get the warning:
```
Readme.md:7: warning: unable to resolve reference to `https:' for \ref command
```

and as result:

![image](https://user-images.githubusercontent.com/5223533/130330498-15f5eb64-9d87-425e-8c90-e14664a5531a.png)


With 1.9.2 we don't get a warning and as result:

![image](https://user-images.githubusercontent.com/5223533/130330520-c22efac8-2a4a-478c-aabb-8f5d5874cb17.png)


Note that in this case the second reference points to nowhere (i.e. give a 404 error when clicking on it but this is not a doxygen problem). The first (now rendering link, points to a sensible place.

I think the problem has been solved in the mean time.
