### ISSUE TITLE
Friend functions returning decltype(auto) not inserted in the "friends" group (Origin: bugzilla #782262)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6202]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.13-GIT* on platform *Other*
Assigned to: Dimitri van Heesch

On 2017-05-06 11:53:03 +0000, raskolnikov@gnu.org wrote:

    Normally, friend functions are documented in a "friends" section (`
    <sectiondef kind="friend">` in the XML output).
    
    For an example, let's look at this file:
    https://github.com/arximboldi/immer/blob/SHA:
    f10703a66d4f0ee8d52c29a0fe28601773d9afd6/immer/flex_vector.hpp
    
    It has various `operator+` overloads. The ones that return a named type are
    correctly inserted in the `friends` section, but the ones returning
    `decltype(auto)` are not.
    
    Here is a link to the generated XML output:
    https://gist.github.com/arximboldi/c3e4d4f6024d2d3e94238a5ac6517a8a
    
    I am using Doxygen Version: 1.8.13-4+b1 (Debian Sid).

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #8675

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.2.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
