### ISSUE TITLE
Doxygen cannot be configured to show 0 members in the UML class diagram (Origin: bugzilla #782366)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6204]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.13* on platform *Other*
Assigned to: Dimitri van Heesch

On 2017-05-09 05:06:28 +0000, Fabian wrote:

    I would like to use UML like diagrams in my doxygen documentation. However,
    I want to use them to show the relationships of the classes and nothing
    else. Hence I would like to set the number of fields and member variables to
    be shown to zero.
    
    UML_LOOK = YES
    UML_LIMIT_NUM_FIELDS = 0
    
    This does not work because 0 means "show all".
    
    Even if I set UML_LIMIT_NUM_FIELDS = 1 it looks annoying because I have
    grouped my member functions in groups and it shows up to
    UML_LIMIT_NUM_FIELDS *per group* and not in total.
    
    My current workaround is not to use UML_LOOK, but I am looking for a better
    way. Maybe doxygen can be modified to accept UML_LIMIT_NUM_FIELDS = -1 for
    "show no members".

**Comment by timoffermann** [comment]
Today I was looking for exact this type of configuration for a two reasons:

- We prefer UML diagrams over non-standard looking diagrams
- We prefer at this place in the documentation the focus on the relationships and don't need the two optional compartments for attributes and operations as part of our diagrams

This would help us - the context of a larger project - to define one standard doxygen configuration (using UML) without the need of finetuning the number of fields.

Something like this:
![Screenshot from 2020-11-26 22-50-55](https://user-images.githubusercontent.com/3040731/100393421-dfbe6c80-3039-11eb-800b-6f0e69a1821f.png)

**Comment by albert-github** [comment]
Seen the linked pull request #8207 I think that the setting `DOT_UML_DETAILS=NONE` (available as of version 1.9.0 meets the requirements.

I think the problem has been solved in the mean time.
