### ISSUE TITLE
Unclear how to suppress periods from ending brief description (JAVADOC_AUTOBRIEF) (Origin: bugzilla #782373)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6205]
status NEW severity *normal* in component *documentation* for *---*
Reported in version *1.8.9.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2017-05-09 09:15:59 +0000, morinim@gmail.com wrote:

    According to Doxygen manual:
    
    1.
    > To enable this behavior you should set JAVADOC_AUTOBRIEF to YES in the
    > configuration file. If you enable this option and **want to put a dot in
    the
    > middle of a sentence without ending it, you should put a backslash and a
    space
    > after it**. Here is an example:
    >
    >  /** Brief description (e.g.\ using only a few words). Details follow. */
    
    (Doxygen Manual - Documenting the code - Examples:
    http://www.stack.nl/~dimitri/doxygen/manual/docblocks.html#docexamples)
    
    2.
    > This command writes a dot (.) to the output. **This can be useful to
    prevent
    > ending a brief description when JAVADOC_AUTOBRIEF is enabled** or to
    prevent
    > starting a numbered list when the dot follows a number at the start of a
    line.
    
    (Doxygen Manual - Special Commands - \. :
    https://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdchardot)
    
    The second method doesn't seem to work (the first one is ok).
    
    Also take a look at: http://stackoverflow.com/q/29178465/3235496

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #9314 which also solves this issue.

**Comment by albert-github** [comment]
Example: [example.tar.gz](https://github.com/user-attachments/files/17956688/example.tar.gz)

Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.13.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
