### ISSUE TITLE
Annotated function parameter generates <dt> warning in todo list (Origin: bugzilla #782437)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6208]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.10* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[bug782437.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug782437_351543_bug782437.zip/download/download)_ (ID 351543)

On 2017-05-10 13:01:36 +0000, Frank HJ Cuypers wrote:

    I have a java interface in which I annotated a function parameter with a
    @myAnnotation.
    If I also add a @todo tag to this function and then generate doxygen
    documentation including the todo list, I get a warning:
      todo:2: warning: Illegal command myAnnotation as part of a <dt> tag
    
    But the output looks OK.

On 2017-05-10 13:04:48 +0000, Frank HJ Cuypers wrote:

    Created attachment 351543
    Test case showing the issue

On 2018-05-17 11:28:29 +0000, albert wrote:

    I've just pushed a proposed patch to github (pull request 729,
    https://github.com/doxygen/doxygen/pull/729).

**Comment by albert-github** [comment]
Pull request #729 integrated.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
