### ISSUE TITLE
Generate man page includes both page name and title (Origin: bugzilla #782583)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6210]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.13* on platform *Other*
Assigned to: Dimitri van Heesch

On 2017-05-13 05:29:42 +0000, gnome.org@erewhon0.net wrote:

    If you have
    
    /** @page page_name Title
    
    do something.
    
    */
    
    The generated man page will have
    
    NAME
           page_nameTitle
            - do something.
    
    
    If you omit the title
    
    /** @page page_name
    
    Do something
    
    */
    
    then the man page looks reasonable
    
    NAME
           page_name - do something.
    
    but the HTML version will not have a title so it starts with just "do
    something."

On 2017-05-13 05:40:02 +0000, gnome.org@erewhon0.net wrote:

    page_name is used as the name of the man page file so the solution is to
    omit Title from the man page and only use it in the HTML version as the
    command "man page_name" would be expected to bring up a man page with NAME
    man_page. If you use Title there is a chance of generating a page such that
    "man foo" brings up a page for "Bar".
    
    Meanwhile in HTML-land the generated page does not have a NAME section
    heading under any circumstance so looks different from the man page. "Title"
    is written in a box at the top of page, or if Title is omitted, there's an
    empty box.

On 2017-05-14 07:04:11 +0000, gnome.org@erewhon0.net wrote:

    When the title is omitted, the HTML title of the page will be "Project Name:
    $title" where "Project Name" is the value of the PROJECT_NAME property in
    the Doxygen config file.

**Comment by MarkCallow** [comment]
This issue can be closed. The accepted PR with the fix is now cross-referenced.

No close button is appearing for me, presumably because I'm not recognized as the reporter.
