### ISSUE TITLE
c++ call graph wrong if member function defined inline (Origin: bugzilla #782713)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6211]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.13* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[files.tgz](https://sourceforge.net/projects/doxygen/files/attachments/bug782713_351995_files.tgz/download/download)_ (ID 351995)

On 2017-05-16 22:58:29 +0000, Byron Watt wrote:

    Created attachment 351995
    header file, source file, Doxyfile & .png showing a() calls func1()
    
    In the following example, doxygen thinks that the constructor a() calls
    func1().  The last function defined inside a class definition seems to think
    it calls all functions in the source file.
    
    header file:
    
      class a {
      public:
        a() {}
        void func1();
      };
    
    source file:
    
      #include "a.h"
      void a::func1()
      {
      }
    
    Doxyfile diffs:
    
      -EXTRACT_ALL            = NO
      +EXTRACT_ALL            = YES
     
      @@ -443,3 +443,3 @@
     
      -EXTRACT_PRIVATE        = NO
      +EXTRACT_PRIVATE        = YES
     
      @@ -792,3 +792,3 @@
     
      -INPUT                  =
      +INPUT                  = dox_problem
     
      @@ -2197,3 +2197,3 @@
     
      -HAVE_DOT               = NO
      +HAVE_DOT               = YES
     
      @@ -2314,3 +2314,3 @@
     
      -CALL_GRAPH             = NO
      +CALL_GRAPH             = YES
     
      @@ -2326,3 +2326,3 @@
     
      -CALLER_GRAPH           = NO
      +CALLER_GRAPH           = YES

On 2017-07-25 21:59:33 +0000, Beat Bolli wrote:

    The same thing happens with free functions outside of classes.
    
    Complete example:
    
    ---- file inline-bug.h ----
    
    /**
     * \mainpage
     *
     * # This file demonstrates a Doxygen bug when computing the call graph of
    inline functions.
     *
     * See the documentation of `f0()` and `f1()` for the error
     * description.
     *
     * The actual function signatures are unimportant.
     */
    
    /**
     * This call graph shows that `f0()` calls every function that's
     * declared below its own declaration, up to the next inline function;
     * the caller graphs of the wrongly "called" functions are also wrong.
     */
    inline void f0() {}
    
    int     g1();
    void    g2();
    
    /**
     * Same thing here; this function demonstrates that the callees of the
    previous
     * function end when another inline function is encountered.
     */
    inline std::string f1()
    {
      return "";
    }
    
    size_t  g3();
    bool    g4();
    
    /**
     * Inline functions at the end of the file are handled correctly because no
    other
     * declarations follow.
     */
    inline int f3()
    {
      return 0;
    }

**Comment by albert-github** [comment]
I ran both examples with the 1.8.13 and the current 1.9.6 version and with the 1.8.13 I see the wrong call graphs as indicated and with the 1.9.6 version all the call graphs (as should be) are gone.

I think the problem has been solved in the mean time.
