### ISSUE TITLE
Spaces in \if \endif block are ignored (Origin: bugzilla #782714)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6212]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.14-GIT* on platform *Other*
Assigned to: Dimitri van Heesch

On 2017-05-16 23:48:46 +0000, alex@rti.com wrote:

    For example:
    
    /**
     * This is a \if MY_DEFINE method \else function \endif that does many
    things.
     */
    void f();
    
    This will produce the following output when MY_DEFINE is defined:
    
    "This is a methodthat does many things."
    
    However, if MY_DEFINE is not defined, the else block honors the spaces:
    
    "This is a function that does many things."
    
    This used to work in 1.8.2 and before.

On 2018-06-18 09:58:12 +0000, albert wrote:

    This problem can be easily overcome by means of:
    /**
     * This is a
     * \if MY_DEFINE method
     * \else function
     * \endif
     * that does many things.
     */
    void f();

**Comment by alexcamposruiz** [comment]
This issue is preventing us from upgrading to the latest version of Doxygen, which contains other bug fixes we need as well.

While the suggested workaround works, we would have to apply it to hundreds of lines in our code base in order to use a newer version of Doxygen.

**Comment by albert-github** [comment]
A very mean trick might be to create an `ALIASES` like
`ALIASES                = "endif=@endif&zwj;"`

I cannot guarantee that it will work in all situations!

**Comment by alexcamposruiz** [comment]
Are there any plans to fix this issue?

We've tried both workarounds. Adding "&zwj;" works in some cases, but not all. Breaking the if/else/endif into multiple lines doesn't seem to work in most cases.

**Comment by albert-github** [comment]
Problem was still present in 1.8.14 and 1.8.17 but is gone since version 1.8.18

I think the problem has been solveed in the mean time
