### ISSUE TITLE
hhc.exe fail when a class inherit a class from an external project => doxygen return with an error code (Origin: bugzilla #783580)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6217]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.8.13* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[Doxyfile](https://sourceforge.net/projects/doxygen/files/attachments/bug783580_353439_Doxyfile/download/download)_ (ID 353439)

On 2017-06-09 07:26:37 +0000, Vivien Delmon wrote:

    Created attachment 353439
    Failing Doxyfile
    
    Step to reproduce (see attached Doxyfile):
    1. Create a file containing a class that inherits QObject
      #include <QtCore/QObject>
      class MyObject : public QObject
      {};
    2. Add qtcore tagfile with external location in the doxyfile
    TAGFILES = E:\Qt\docs\qt-5.6\qtcore\qtcore.tags=http://doc.qt.io/qt-5/
    
    3. Generate a chm
    
    Doxygen will return an error code with the following description :
    EXEC : error : failed to run html help compiler on index.hhp
    
    If I run the hhc.exe on index.hhp, I got the following output:
    "C:\Program Files (x86)\HTML Help Workshop\hhc.exe" html\index.hhp
    Microsoft HTML Help Compiler 4.74.8702
    
    Compiling e:\work\incas\doc\MyProject.chm
    
    HHC5013: Error: URL reference in the TOC cannot be resolved: "qobject.html".
    
    The following files were not compiled:
    Unable to open html\index.hhp.
    
    Adding the external location to external classes in the index.hhc fixes the
    hhc.exe compilation :
    <OBJECT type="text/sitemap"><param name="Name" value="QObject"><param
    name="Local" value="qobject.html"><param name="ImageNumber"
    value="1"></OBJECT>
    becomes:
    <OBJECT type="text/sitemap"><param name="Name" value="QObject"><param
    name="Local" value="http://doc.qt.io/qt-5/qobject.html"><param
    name="ImageNumber" value="1"></OBJECT>
    
    This issue is very similar to # 128094 but I hope that the detailed
    description will help you to fix it.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #10860

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.11.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
