### ISSUE TITLE
PERL_PATH config option: when is this needed? Still used? (Origin: bugzilla #783759)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6218]
status NEW severity *normal* in component *documentation* for *---*
Reported in version *1.8.13* on platform *Other*
Assigned to: Dimitri van Heesch

On 2017-06-13 16:32:23 +0000, kossebau@kde.org wrote:

    The doxygen configuration documentation lists "PERL_PATH" in the section
    "Configuration options related to external references" (cmp.
    http://www.stack.nl/~dimitri/doxygen/manual/config.html#cfg_perl_path ).
    
    Problem:
    It is totally unclear which users of doxygen would need to set this option
    though, and if when perl is needed as dependency at all.
    
    
    Outdated documentation?
    Grepping the doxygen sources there is no reading of such a config key
    "PERL_PATH", seems the last usage in code was removed in 2012 in commit
    https://github.com/doxygen/doxygen/commit/SHA:
    fd8b446f8ae60e7d1dc259c6f5fe38c287377d19 .
    
    
    Perl needd for doxygen creating QCH files?
    This unclearness currently adds a bigger obstacle to people using doxygen
    with KDE's new Extra-CMake-Modules macro for generating QCH files during the
    build (see https://api.kde.org/ecm/module/ECMAddQch.html), like going in
    production right now for all of the KDE Frameworks and other libraries.
    
    So while improving the doxygen documentation for everyone would be good to
    have, can you  already give a quick note on this bug report if perl (and the
    "PERL_PATH" config option) is needed when creating QCH files with doxygen?
    So we can hopefully remove the currently coded dependency on perl from the
    ECM macro?

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6967

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
