### ISSUE TITLE
QCH files: classes & their constructors get conflicting keyword handling (Origin: bugzilla #783768)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6220]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.13* on platform *Other*
Assigned to: Dimitri van Heesch

On 2017-06-13 19:10:29 +0000, kossebau@kde.org wrote:

    If both classes and their constructors are included in the generated
    documentation by doxygen, then the created QHP files contain the same
    keyword both for the class and for its constructors.
    
    Which results in unpleasant behaviour in Qt Assistant when using the Index
    feature:
    when entering a term and selecting the appearing class name, instead of
    being brought straight to the class' documentation page another dialog pops
    up, title "Choose Topic", listing two identic items ("BOOK: KEYWORD"), the
    first pointing to anchor of first constructor, the second to class page in
    general.
    
    Which is different from the behaviour for Qt classes, where for a keyword
    matching a class no such dialog is shown, instead one is straight brought to
    the  class page.
    
    Reason is that doxygen creates and stores more than one keyword per class
    name compared to Qt.
    E.g. for KAboutData from KDE Frameworks, which has three documented
    constructors
    (https://api.kde.org/frameworks/kcoreaddons/html/classKAboutData.html), four
    keywords with same name are created (ids of constructors are identic, but
    same is seen with Qt):
    --- 8< ---
          <keyword name="KAboutData" id="KAboutData" ref="classKAboutData.html"
    />
          <keyword name="KAboutData" id="KAboutData::KAboutData"
    ref="classKAboutData.html#ad437b0f36a1d120c45616333c671a059" />
          <keyword name="KAboutData" id="KAboutData::KAboutData"
    ref="classKAboutData.html#a20efda14b288568a5da5839442827e97" />
          <keyword name="KAboutData" id="KAboutData::KAboutData"
    ref="classKAboutData.html#aa58f336dc81d52d644a5b840abfe2907" />
    --- 8< ---
    
    where the QHP files from Qt for a class skip the constructor methods for
    each class and only list the class names. E.g. qtcore.qhp for QObject, which
    has one documented constructor (http://doc.qt.io/qt-5/qobject.html#QObject )
    still only has
    --- 8< ---
                <keyword name="QObject" id="QObject" ref="qobject.html"/>
    --- 8< ---
    
    
    WANTED:
    At least the option to create QHP files matching the behaviour from Qt, by
    dropping keywords for constructors.
    For improving experience with doxygen as used by
    https://api.kde.org/ecm/module/ECMAddQch.html
    
    I would be willing to come up with a patch for this.
    What name would you propose for such a config flag?
    Any recommendations/wishes for things the patch should cover otherwise?

On 2017-06-13 22:38:41 +0000, kossebau@kde.org wrote:

  Initial patch (as food for thoughts) proposed at
    https://github.com/doxygen/doxygen/pull/573

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.4.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
