### ISSUE TITLE
Generated man pages "NAME" section is wrong in 1.8.13 (Origin: bugzilla #784032)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6222]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.13* on platform *Other*
Assigned to: Dimitri van Heesch

On 2017-06-21 11:11:03 +0000, Daniele E. Domenichelli wrote:

    For this piece of code:
    
    ---
    /**
    \page foo brief description
    \section description DESCRIPTION
    Full description.
    */
    ---
    
    Doxygen 1.8.13 generates a wrong man page (the NAME section is wrong):
    
    ---
    NAME
           foobrief description
            -
    ---
    
    Using Doxygen 1.8.12 the result was correct:
    
    ---
    NAME
           foo - brief description
    ---

On 2017-07-18 03:46:37 +0000, Artur Kink wrote:

    Interestingly the page definition treats the title a bit differently than,
    for example, a group.
    
    In the man page, for a page definition, the title is appended with a - after
    the name. For a group the title is ignored.
    If the definition has a title and a \brief, then both are concatenated after
    the -, which is a bit weird.
    
    Either way this is my fault for overlooking the title print for a page
    definition. Will try to see if I can come up with a logical solution to the
    title + brief combination.

**Comment by drdanz** [comment]
This bug was fixed in doxygen 1.8.15 (or maybe 1.8.14, but I wasn't able to test it).
This issue should probably be closed.

**Comment by albert-github** [comment]
The problem was present in 1.8.13, but not in 1.8.12m, 1.8.14 and 1.8.19.

So problem looks indeed to be solved in the mean time.
