### ISSUE TITLE
Documentation for functions with certain name does not get generated. (Origin: bugzilla #786229)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6235]
status NEEDINFO severity *major* in component *general* for *---*
Reported in version *1.8.11* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[Doxyfile.t](https://sourceforge.net/projects/doxygen/files/attachments/bug786229_357509_Doxyfile.t/download/download)_ (ID 357509)
- _[doxygen-bug-report-786229.tar.gz](https://sourceforge.net/projects/doxygen/files/attachments/bug786229_357516_doxygen-bug-report-786229.tar.gz/download/download)_ (ID 357516)

On 2017-08-13 09:39:54 +0000, lelanthran@gmail.com wrote:

    Created attachment 357509
    The Doxyfile that was used to replicate this error
    
    Documentation for functions with certain name does not get generated.
    
    -------------------
    PROBLEM DESCRIPTION
    -------------------
    
    Functions with names containing uint8_t/uint16_t/uint32_t/uint64_t does
    not result in documentation being generated. The following example results
    in the documentation not being generated:
    
    ---- BeginExample ----
    #include <stdint.h>
    
    /**
     * \file
     *
     * \brief Convert unsigned values to and from byte-arrays
     *
     * ...
     *
     * \author Lelanthran Krishna Manickum
     */
    
    /**
     * \brief Convert a byte-array to an unsigned 16-bit integer
     *
     * ...
     */
    uint16_t xendian_uint16_to_bytes (uint8_t *src)
    {
       return (uint16_t)(bytes_to_uint64 (src, 2));
    }
    ---- EndExample ----
    
    Changing the name to remove the instance of the type 'uint16_t' results in
    the documentation getting generated. For example, replacing the 'uint16_t'
    in the function name with 'int16_t' results in the documentation being
    generated:
    
    ---- BeginExample ----
    #include <stdint.h>
    
    /**
     * \file
     *
     * \brief Convert unsigned values to and from byte-arrays
     *
     * ...
     *
     * \author Lelanthran Krishna Manickum
     */
    
    /**
     * \brief Convert a byte-array to an unsigned 16-bit integer
     *
     * ...
     */
    uint16_t xendian_int16_to_bytes (uint8_t *src)
    {
       return (uint16_t)(bytes_to_uint64 (src, 2));
    }
    ---- EndExample ----
    
    
    -----------
    EXTRA NOTES
    -----------
    
    1. I've determined that the problem manifests when any of the following
       strings appear in a function name:
       uint8_t uint16_t uint32_t uint64_t
    
    2. I've determined that the problem does *NOT* manifest when any of the
       following similar strings appear in a function name:
       int8_t int16_t int32_t int64_t
    
    3. I've toggled ENABLE_PREPROCESSING between "yes" and "no" with no effect
       on the problem.
    
    4. There are no warnings issued that are different between the case that
       works (int16_t) and the case that does not work (uint16_t).
    
    
    ------
    SYSTEM
    ------
    
    Output of uname -a:
    Linux lelanthran-VirtualBox 4.8.0-53-generic # 56~16.04.1-Ubuntu SMP \
    Tue May 16 01:18:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
    
    Contents of /etc/issue:
    Linux Mint 18.2 Sonya \n \l
    
    Output of doxygen --version:
    1.8.11

On 2017-08-13 11:16:08 +0000, Dimitri van Heesch wrote:

    Despite the elaborate description I wasn't able to reproduce the problem at
    my end. Can you please attach a self-contained example (source+config file
    in a tar or zip) for which you verified that it contains the problem?
    
    If possible also try with the latest version from doxygen from the official
    site (1.8.13)

On 2017-08-13 14:51:45 +0000, lelanthran@gmail.com wrote:

    Created attachment 357516
    A full compilable source file that exhibits the bug
    
    The source file within compiles with gcc. The doxygen documentation within
    the source file exhibits the bug.

On 2017-08-13 14:55:33 +0000, lelanthran@gmail.com wrote:

    I've tested with 1.8.13 from sourceforge (binary Linux X64 download) and got
    the bug.
    
    I've tested with an older VM of mine that has doxygen 1.8.7 (32bit Debian)
    and the bug is not in that version.
    
    I'm currently waiting for the 1.8.13 Windows version to download (Africa has
    slow internet :-( ) and will test on Windows Seven/64.
    
    Later I'll download the source package and if it compiles on my system, I'll
    test on that too.

On 2017-08-13 16:01:35 +0000, lelanthran@gmail.com wrote:

    The bug does not manifest on Windows Seven (64bit).

On 2017-08-16 18:53:59 +0000, lelanthran@gmail.com wrote:

    More information:
    
    1. As I've said above, I've downloaded the 1.8.13 sourceforge X86_64 binary
    for Linux and verified the strange behaviour.
    
    2. I downloaded the source for 1.8.13 and compiled (I was hoping to track
    down the source of this bug) and did not get the bug.
    
    3. Once again, I ran the 1.8.13 binary that I downloaded from sourceforge,
    and once again I got the bug.
    
    I've now got two 1.8.13 doxygen binaries on my system, with one reliably
    giving the bug and the other does not.
    
    I appreciate any pointers on where I should possibly start looking in the
    code to track down this strange behaviour.

**Comment by albert-github** [comment]
I tried it with the, Windows, 1.8.11 version but was not able to reproduce the problem.
With the 1.8.12 and 1.8.13 version I was able to reproduce the problem.
With newer versions (and also the current 1.9.6 version) the problem is gone.

I think the problem has been solved in the mean time.
