### ISSUE TITLE
Dynamic menus are broken with extended Array.prototype (Origin: bugzilla #786272)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6236]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.13* on platform *Other*
Assigned to: Dimitri van Heesch

On 2017-08-14 11:18:16 +0000, paul203948@gmail.com wrote:

    Dynamic menus do not work correctly when Array.prototype is extended.
    
    I have included Doxygen HTML output in a site with 3rd party libraries which
    extend Array.prototype. The array iteration in menu.js enumerates the
    properties added to the Array prototype. To simulate the problem, add a line
    to extend the Array prototype in menu.js:
    
      function initMenu(relPath,searchEnabled,serverSide,searchPage,search) {
        // Add the property 'foo' to the Array prototype
        Array.prototype.foo = [];
        
        function makeTree(data,relPath) {
          var result='';
          if ('children' in data) {  // <-- Iterates the object property 'foo'
            result+='<ul>';
            for (var i in data.children) {
    
    This causes an extra 'undefined' value to appear at every level of the menu.
    
    Perhaps the for loop should be changed to:
    
      for (var i=0; i<data.children.length; i++) {

On 2017-08-14 13:00:55 +0000, paul203948@gmail.com wrote:

    (In reply to paul203948 from comment # 0)
    >   function initMenu(relPath,searchEnabled,serverSide,searchPage,search) {
    >     // Add the property 'foo' to the Array prototype
    >     Array.prototype.foo = [];
    >     
    >     function makeTree(data,relPath) {
    >       var result='';
    >       if ('children' in data) {  // <-- Iterates the object property 'foo'
    >         result+='<ul>';
    >         for (var i in data.children) {
    
    Oops, the 'Iterates the object property' comment is supposed to be on the
    for loop 2 lines below, not the if statement.

**Comment by albert-github** [comment]
What the effects are on the output are of the extra prototype.
As there is no example provided to reproduce / simulate the problem is incomplete.
