### ISSUE TITLE
Unmatched single quote in C++ source breaks aliases (Origin: bugzilla #786382)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6237]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.13* on platform *Other*
Assigned to: Dimitri van Heesch

On 2017-08-16 17:29:05 +0000, Mat Sutcliffe wrote:

    C++14 added the ability to use a single quote character as a digit
    separator, making the following legal C++ code:
    
    int x = 10'000;
    
    This appears to break any aliases that appear below that line, as in the
    following example:
    
    ALIASES += "fixme=\xrefitem fixme \"Fixme\" \"Fixme List\""
    
    int x = 10'000;
    // ...some intervening lines of code...
    //! \fixme this line produces a warning
    
    Generates the warning: Found unknown command `\fixme'

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7976

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
