### ISSUE TITLE
add a configuration option to specify which files should be preprocessed (Origin: bugzilla #786417)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6239]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.14-GIT* on platform *Other*
Assigned to: Dimitri van Heesch

On 2017-08-17 11:09:20 +0000, janus@gcc.gnu.org wrote:

    Currently I don't see any way to tell doxygen which files need
    preprocessing. Instead this decision seems to be hard-coded.
    
    For example, Fortran files are only preprocessed if the have an upper-case
    extension (.F or .F90), which matches the default convention used by most
    compilers. However, one can also use preprocessing with .f or .f90 files
    (via compiler flags like -cpp/-fpp).
    
    Making that work with doxygen would require a configuration option
    ("PREPROCESS_FILE_PATTERNS" or similar), where one could specify which files
    should be preprocessed (analogous to FILE_PATTERNS, which specifies patterns
    for the source files to be considered).
    
    Best regards,
    Janus

On 2017-08-17 11:10:56 +0000, janus@gcc.gnu.org wrote:

    For some discussion, see also https://github.com/doxygen/doxygen/pull/588

**Comment by janusw** [comment]
Actually this issue can be closed from my side. The whole problem can be avoided by simply sticking to the usual conventions for Fortran file extensions, namely using uppercase (.F or .F90) for files that need to be preprocessed.

**Comment by albert-github** [comment]
I think you can close the pull request #588 yourself.

**Comment by janusw** [comment]
Right. Just did that.

**Comment by janusw** [comment]
It would be great if someone with sufficient privileges could close this issue. I cannot do it myself and I don't see any need for keeping it open.
