### ISSUE TITLE
regression with ALIASES or image latex interpretation (Origin: bugzilla #786576)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6240]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.8.13* on platform *Other*
Assigned to: Dimitri van Heesch

On 2017-08-21 17:11:58 +0000, divide@divideconcept.net wrote:

    I'm using a few ALIASES in my Doxygen file as shortcut for including images
    in specific formats both in HTML and Latex output:
    
    ALIASES                = "icon{1}=\image latex \"\1\" height=0.5cm \htmlonly
    <img src=\"\1\" style=\"max-height:20px;\"/> \endhtmlonly" \
                             "screen{3}=\image latex \"\1\" width=\3cm \htmlonly
    <img src=\"\1\" style=\"max-width:\2px;\"/> \endhtmlonly" \
                             "screen{4}=\image latex \"\1\" \"\4\" width=\3cm
    \htmlonly <img src=\"\1\" style=\"max-width:\2px;\"/><div
    class=\"caption\">\4</div> \endhtmlonly"
    
    
    It was working fine in Doxygen 1.8.11. Since I upgraded to 1.8.13, it
    doesn't work anymore. I had to change them to:
    
    ALIASES                = "icon{1}=\image latex \"\1\" height=0.5cm &nbsp;
    \htmlonly <img src=\"\1\" style=\"max-height:20px;\"/> \endhtmlonly" \
                             "screen{3}=\image latex \"\1\" width=\3cm &nbsp;
    \htmlonly <img src=\"\1\" style=\"max-width:\2px;\"/> \endhtmlonly" \
                             "screen{4}=\image latex \"\1\" \"\4\" width=\3cm
    &nbsp; \htmlonly <img src=\"\1\" style=\"max-width:\2px;\"/><div
    class=\"caption\">\4</div> \endhtmlonly"
    
    That is, including an extra and unnecessary &nbsp; in between my \image
    latex and my \htmlonly commands. Otherwise when building I get tons of
    errors related to that (misinterpretation of the \image latex command).

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #9477

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.5.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
