### ISSUE TITLE
doxygen markdown doesn't support code block and blockquote under a list item (Origin: bugzilla #786589)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6241]
status NEW severity *major* in component *general* for *---*
Reported in version *1.8.13* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxygen.tar.gz](https://sourceforge.net/projects/doxygen/files/attachments/bug786589_358104_doxygen.tar.gz/download/download)_ (ID 358104)

On 2017-08-22 03:49:39 +0000, billconan@gmail.com wrote:

    Created attachment 358104
    doxygen example
    
    The following markdown file is rendered differently by github and doxygen
    
    https://raw.githubusercontent.com/shi-yan/Swiftly/master/README.md
    
    in particular, doxygen fails to recognize blockquote or code block under a
    list item:
    
    
    2. nodejs:
    
        ```javascript
        // Load the http module to create an http server.
        var http = require('http');
        
        // Configure our HTTP server to respond with Hello World to all
    requests.
        var server = http.createServer(function (request, response) {
          response.writeHead(200, {"Content-Type": "text/plain"});
          response.end("Hello World\n");
        });
        
        // Listen on port 8000, IP defaults to 127.0.0.1
        server.listen(8000);
        
        // Put a friendly message on the terminal
        console.log("Server running at http://127.0.0.1:8000/");
        ```
        
        > Transactions:              89739 hits  
        > Availability:             100.00 %  
        > Elapsed time:               9.32 secs  
        > Data transferred:           1.03 MB  
        > Response time:              0.02 secs  
        > Transaction rate:        9628.65 trans/sec  
        > Throughput:             0.11 MB/sec  
        > Concurrency:              198.66  
        > Successful transactions:       89739  
        > Failed transactions:               0  
        > Longest transaction:            3.02  
        > Shortest transaction:           0.00
    
    
    the attachment is an example of a document generated by doxygen out of this
    markdown file. (index.html and indexpage.xml)
    
    as a comparison, here is the example output of github:
    
    https://github.com/shi-yan/Swiftly/blob/master/README.md

On 2017-08-22 06:28:46 +0000, billconan@gmail.com wrote:

    there are at least 2 problems.
    
    in markdown.cpp function isBlockQuote
    
    1. there is a check of the current indent:
    
      if (i<indent+codeBlockIndent) // could be a quotation
    
    only when this check passes, the current block is considered a blockquote,
    
    in the above repro case, the indent is zero, but i, the beginning of the
    quote is not zero.
    
    when calculating indent, the indent of ordered list seems to be ignored.
    
    
    2. according to markdown spec, if a line has 2 trailing zeros, a line break
    should be inserted, so that the block will have multiple lines.
    
    in the above example, each line has 2 trailing zeros, but doxygen completely
    ignores this.
    
    a quick fix is adding the following to function writeBlockQuote
    
        if ((end-3 >= 0) && (data[end-2]==' ') && (data[end-3]==' '))
        {
          out.addStr("<br/>");
        }

**Comment by albert-github** [comment]
A bit a pity that only the output is given and not a small example.
Fortunately in the xml files the source code of the README.md was present so it could be extracted.
In the issue it is said `according to markdown spec, if a line has 2 trailing zeros, a line break should be inserted, so that the block will have multiple lines.` and I think the word `zeros` has to be replaced here by `spaces`.

With the 1.8.13 version the handling of the blockquotes and code blocks is not correct.
In the 1.9.2 version the blockquotes and code blocks are rendered.

I think the problem has been solved in the mean time.
