### ISSUE TITLE
Private classes of Java can be accessed in HTML Documentation regardless of Doxyfile configuration (Origin: bugzilla #787164)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6252]
status NEW severity *major* in component *general* for *---*
Reported in version *1.8.14-GIT* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[BUG_attachment.tar.gz](https://sourceforge.net/projects/doxygen/files/attachments/bug787164_358966_BUG_attachment.tar.gz/download/download)_ (ID 358966)

On 2017-09-02 04:36:45 +0000, Vamsi Krishna Reddy wrote:

    Created attachment 358966
    Doxyfile and also Contains a 'data' file needed to run the .java file.
    
    Please describe the problem:
    Take this .java file which exhibits the problem:
    
    __________________________________________________________________
     
    public class LinkList<T> {
     
        private Node<T> front;
        private Node<T> rear;
         
        public void insertFront(T item){
            //add element at the beginning of the queue
            System.out.println("adding at front: "+item);
            Node<T> nd = new Node<T>();
            nd.setValue(item);
            nd.setNext(front);
            if(front != null) front.setPrev(nd);
            if(front == null) rear = nd;
            front = nd;
        }
         
        public void insertRear(T item){
            //add element at the end of the queue
            System.out.println("adding at rear: "+item);
            Node<T> nd = new Node<T>();
            nd.setValue(item);
            nd.setPrev(rear);
            if(rear != null) rear.setNext(nd);
            if(rear == null) front = nd;
             
            rear = nd;
        }
         
        public void removeFront(){
            if(front == null){
                System.out.println("Deque underflow!! unable to remove.");
                return;
            }
            //remove an item from the beginning of the queue
            Node<T> tmpFront = front.getNext();
            if(tmpFront != null) tmpFront.setPrev(null);
            if(tmpFront == null) rear = null;
            System.out.println("removed from front: "+front.getValue());
            front = tmpFront;
        }
         
        public void removeRear(){
            if(rear == null){
                System.out.println("Deque underflow!! unable to remove.");
                return;
            }
            //remove an item from the beginning of the queue
            Node<T> tmpRear = rear.getPrev();
            if(tmpRear != null) tmpRear.setNext(null);
            if(tmpRear == null) front = null;
            System.out.println("removed from rear: "+rear.getValue());
            rear = tmpRear;
        }
         
        public static void main(String a[]){
            LinkList<Integer> deque = new LinkList<Integer>();
            deque.insertFront(34);
            deque.insertFront(67);
            deque.insertFront(29);
            deque.insertFront(765);
            deque.removeFront();
            deque.removeFront();
            deque.removeFront();
            deque.insertRear(43);
            deque.insertRear(83);
            deque.insertRear(84);
            deque.insertRear(546);
            deque.insertRear(356);
            deque.removeRear();
            deque.removeRear();
            deque.removeRear();
            deque.removeRear();
            deque.removeFront();
            deque.removeFront();
            deque.removeFront();
        }
    }
     
    class Node<T>{
         
        private Node<T> prev;
        private Node<T> next;
        private T value;
         
        public Node<T> getPrev() {
            return prev;
        }
        public void setPrev(Node<T> prev) {
            this.prev = prev;
        }
        public Node<T> getNext() {
            return next;
        }
        public void setNext(Node<T> next) {
            this.next = next;
        }
        public T getValue() {
            return value;
        }
        public void setValue(T value) {
            this.value = value;
        }
    }
    
    ___________________________________________________________________
    
    
    In particular , the Doxyfile I used had:
    
    INPUT = Linklist.java
    EXTRACT_ALL = YES
    EXTRACT_PRIVATE = NO (Note this)
    EXTRACT_PACKAGE = NO
    EXTRACT_STATIC = NO
    
    I can access the Linklist class documentation on the link
    .../html/classLinkList.html but when I rename the link to
    .../html/classNode.html, I'm able to see the private class variables and
    other details, which is not expected to be so.
    
    This is with version 1.8.14.
    
    Steps to reproduce:
    See above.
    
    Actual results:
    See above.
    
    Expected results:
    I expect private classes to remain 'private' along with their variables.
    
    Does this happen every time?
    Yes.
    
    Other information:

On 2017-09-02 04:41:30 +0000, Vamsi Krishna Reddy wrote:

    To add, 'EXTRACT_ALL = NO' also involves the same bug.

**Comment by albert-github** [comment]
I tried to reproduce the problem with 1.8.13, 1.8.14 and the git master version as available on September 2, 2017 but I was not able to reproduce the problem, the file classNode.html never appeared.

When looking at the directory listing of the html directory:
![dir_list](https://user-images.githubusercontent.com/5223533/57315442-e00fb380-70f3-11e9-8989-b2206c4f7276.jpg)

we see that the classNode files have a time of 05:59:49 and all other file a later time 06:00:15, this looks like a small time difference but for such a small project it indicates that some files from older runs are present.

I think the problem is usage.
