### ISSUE TITLE
Namespace only containing enum not indexed (Origin: bugzilla #787258)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6253]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.13* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[test.cpp](https://sourceforge.net/projects/doxygen/files/attachments/bug787258_359080_test.cpp/download/download)_ (ID 359080)
- _[Doxyfile](https://sourceforge.net/projects/doxygen/files/attachments/bug787258_359081_Doxyfile/download/download)_ (ID 359081)

On 2017-09-04 14:17:29 +0000, Ladislav LÃ¡ska wrote:

    Created attachment 359080
    Minimal testcase
    
    I noticed that some of my C++ namespaces are missing in the HTML treeview
    and cannot be searched by name, although they are documented. Members of
    these namespaces are searchable and documented on a page that is called as
    the missing namespace, so it seems it is parsed fine.
    
    After some trial and error I noticed the missing namespaces have something
    in common: they do not contain any class. I made a minimal example (see
    attachment): created two namespaces, X and Y, with X containing only one
    enum (EnumX) and Y containing class ClassX. I made a new configuration using
    the doxywizard, enabling the treeview and EXTRACT_ALL, which manifests the
    issue.
    
    Note that the problem is not only with enum, I have noticed the same problem
    if the namespace contains enums, functions and variables. Also, the problem
    only occurs when the namespace in question is not global (in my example,
    that's why I have the glob namespace).
    
    I hope this can be fixed for next release, thanks!

On 2017-09-04 14:18:02 +0000, Ladislav LÃ¡ska wrote:

    Created attachment 359081
    Appropriate doxyfile

**Comment by albert-github** [comment]
With version 1.8.13 I see that the namespace X is missing, as of version 1.9.0 the namespace is present.

I think the problem has been solved in the mean time
