### ISSUE TITLE
Markdown rendering fails by @file command (Origin: bugzilla #787766)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6258]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.13* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[20170917_doxygenmarkdown.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug787766_359899_20170917_doxygenmarkdown.zip/download/download)_ (ID 359899)

On 2017-09-16 17:33:58 +0000, gageas@gageas.com wrote:

    Created attachment 359899
    example source and config
    
    Markdown file contains some kind of Doxygen command (like) string can't be
    rendered properly.
    
    Most serious case I've found is @file command.
    When Doxygen reached @file command, rendering sequence seems to be aborted.
    
    Escaping @ to @@ seems worked, but fenced code block, @@ rendered as @@
    itself.
    
    @brief command does not cause abort, but rendered at top of html page, no
    matter where it is.
    
    My Environment:
    Doxygen 1.8.13, Windows 10 x64
    
    
    Source:
    ----------
    text before fenced block
    
    ```
    @file example.md
    ```
    
    text after fenced block
    ----------
    
    
    Generate HTML:
    ----------
    text before fenced block
    
    ```
    ----------

**Comment by albert-github** [comment]
With the 1.8.14 we see:

![image](https://user-images.githubusercontent.com/5223533/130328161-cf3b6927-a2b4-4275-b199-aba09bf2f256.png)

with the 1.9.2 version we see:

![image](https://user-images.githubusercontent.com/5223533/130328171-dadd5519-7bd1-4a3f-9239-5d9189fa1b78.png)


I think the problem has been solved in the mean time.
(probably as of doxygen 1.8.15).
