### ISSUE TITLE
Navigation bars do not work on Windows (Origin: bugzilla #788198)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6261]
status NEEDINFO severity *major* in component *general* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2017-09-26 15:33:47 +0000, craigukaea@gmail.com wrote:

    In my .css
    
    .navbar-default .navbar-brand {
        color: #fff;
    }
    
    
    .adjust-right {
    margin-left: 30px !important;
    font-size: 1.15em !important;
    }
    .navbar{
     border: 0px solid # 222 !important;
     background-color: # 331d1d;
    }
    
    .navbar-default  {
        background-color: # 331d1d;
    }
     
    
    table{
        white-space:pre-wrap !important;
    }
    
    .navbar-brand > img {
        display: inline;
      height: 100%;
      padding: 3px; /* firefox bug fix */
      width: auto;
    }
    
    .navbar-brand {
      padding: 0px; /* firefox bug fix */
    }
    
    
    in my header.html
    
        <body>
            <nav class="navbar navbar-default" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <a class="navbar-brand"> <img src="$projectlogo"
    alt="CorteX Logo" height="50   " width="70"  > $projectname
    $projectnumber</a>
                    </div>
                </div>
            </nav>
            <div id="top">
                <div class="content" id="content">
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-12 panel " style="padding-bottom:
    15px;">
                                <div style="margin-bottom: 15px;">
    
    
    This works fine using Ubuntu, but the navigation bar does not appear on
    Windows.
    
    Using Windows 10.

On 2017-09-28 17:38:36 +0000, albert wrote:

    Can you please test the problem with 1.8.13 and see if the problem is gone
    or not, as no version is specified.
    
    In case the problem is not gone add a small self-contained example
    (source+config file in a zip or tar).

**Comment by albert-github** [comment]
Unfortunately no further information provided. Quite a few things have changed in the HTML Output and no problems reported, recently, in respect to navigation bars etc.

I think the issue is incomplete.
