### ISSUE TITLE
Wrong navigation tree node highlighted (Origin: bugzilla #788799)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6266]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.11* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[case.tar.gz](https://sourceforge.net/projects/doxygen/files/attachments/bug788799_361293_case.tar.gz/download/download)_ (ID 361293)

On 2017-10-10 21:59:30 +0000, Yannick DuchÃªne wrote:

    Created attachment 361293
    Case source directory archive
    
    This report comes in three parts. 1) Description of the case ans sample
    archive to reproduce it 2) What I tried to fix it 3) What I concluded.
    
    Get the attached archive and unpack it. Generate the documentation then try
    to open `docx/html/namespacemidi_1_1channel__events.html`. The
    `channel_events` node is highlighted, which is OK. Then, try to open
    `docx/html/namespacemidi_1_1manufacturers.html`: the `realtime_events` node
    is highlighted while it should be the `manufacturers` node. The tree
    contains `manufacturers` twice, and only one opens with the URI, which is
    not handy but the issue here is more that the wrong node is highlighted,
    whatever of the two is choose.
    
    I wanted to try to fix it, so started to study `navtree.js`, documenting it
    in the while. I used the `navtree.js` from GitHub not the one from my
    Doxygen 1.8.11 which comes with Ubuntu 16.04.
    
    Unfortunately, after a full and careful study of this file, I could not fix
    the issue and could only conclude the issue is finally in a data file
    generated by Doxygen, which is `navtreeindex0.js`. This file provides data
    to fill-up a breadcrumbs in `navtree.js` and this breadcrumbs is erroneous.
    In `navtreeindex0.js`, there are two entries for
    `namespacemidi_1_1manufacturers.html`, at line 160 and 161. Since
    `NAVTREEINDEX0`is an object, only the second one applies. It says
    `[0,0,0,6]` while it should be `[0,0,0,2]`. Changing 6 into 2 at line 161
    and opening `docx/html/namespacemidi_1_1manufacturers.html`, now the
    expected node is highlighted, `manufacturers`.
    
    As a side node, I will review my documented version of `navtree.js` and will
    propose a pull request, if it ever is useful (not too late but not right
    now).
    
    
    Have an happy day as much as you can

On 2017-10-11 10:02:25 +0000, albert wrote:

    You specified that you used doxygen 1.8.11 and here I see the problem (wrong
    highlighting, "realtime_events" instead of of "manufacturers". When using
    the current version of doxygen (1.8.13), the highlighting is in my opinion
    correct (going to "manufacturers").
    So at first glance the problem looks like to be solved, but when clicking
    (in 1.8.13) on "midi" the highlighting goes to "smf". A first guess, without
    investigations, is that the midi.midi confuses doxygen.

On 2017-10-11 10:33:22 +0000, Yannick DuchÃªne wrote:

    So 1.8.13 is really different. I will try to build it (not available in
    Ubuntu Xenial repositories), test the original issue too and investigate on
    the `midi.midi` issue you mentioned.

On 2017-10-12 00:08:55 +0000, Yannick DuchÃªne wrote:

    I see the same issue with Doxygen 1.8.14

**Comment by albert-github** [comment]
I ran the problem with teh 1.8.11 version and saw the problem regarding the `namespacemidi_1_1manufacturers.html` and the `midi.midi`. With the current doxygen version (1.9.4) these problems are gone.

I think the problem has been solved in the mean time.
