### ISSUE TITLE
Make install fails due to PDF documentation (Origin: bugzilla #788858)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6267]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.8.14-GIT* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[CMakeCache.txt](https://sourceforge.net/projects/doxygen/files/attachments/bug788858_361385_CMakeCache.txt/download/download)_ (ID 361385)

On 2017-10-11 23:10:49 +0000, Yannick DuchÃªne wrote:

    Created attachment 361385
    CMakeCache.txt used for build
    
    Building Doxygen from Trunk on Ubuntu Xenial (Ubuntu 16.04 32 bits), is OK.
    But during `make install`, make fails complaining it could not found a PDF
    file.
    
    There are two issues in one.
    
    Seems building the documentation is not part of the default target. If
    itâs not, then is should not be expected in the `install` target. Thatâs
    the first issue.
    
    The second issue is that `make docs` which I had to explicitly invoke, fails
    in a surprising way. It complains it encountered an error while generating
    PDF, but there is no error message from PDF tools. This seems to be the same
    as in https://bugzilla.gnome.org/show_bug.cgi?id=760316 . May be a PDF tool
    erroneously returns a non-zero exit code?
    
    This error prevent `make install` from installing all of what was
    successfully built, at least the generated HTML documentation. I had to
    comment out a line in `cmake_install.cmake` to skip PDF installation so that
    it can install everything else.
    
    If I disable documentation generation, there is no error at all, `make; make
    install` ends successfully, but not even manual pages are generated.
    
    Here are the build dependencies I installed before building:
    
     * flex
     * bison
     * libxapian-dev
     * zlib1g-dev
     * libqt4-dev
     * texlive-latex-base
     * texlive-font-utils
    
    The two last ones provides the three commands required after CMake messages.
    
    Perhaps the documentation generation options should be more precise,
    allowing to generate manual pages, HTML pages and PDF, separately.
    
    As attachment, my `CMakeCache.txt`.

**Comment by albert-github** [comment]
Regarding problem 1.
Since version 1.8.19 a more explicit and informative message is given when no pdf is available during installation.

Regarding problem 2.
Not a lot of information present to work with. Recently we have not see problems generating the documentation.

I think both problems have been solved in the mean time.
