### ISSUE TITLE
Strange side effect of using `FILTER_PATTERNS` (Origin: bugzilla #788998)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6272]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.14-GIT* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[case.tar.gz](https://sourceforge.net/projects/doxygen/files/attachments/bug788998_361594_case.tar.gz/download/download)_ (ID 361594)

On 2017-10-14 21:11:51 +0000, Yannick DuchÃªne wrote:

    Created attachment 361594
    Test case
    
    Using `FILTER_PATTERNS` surprisingly has a side effect on
    `REFERENCED_BY_RELATION` and `REFERENCES_RELATION`.
    
    In the attached archive, a test case. To run the test, one needs to have
    `doxypypy` installed, otherwise, I left the generated documentation in the
    archive.
    
    The case contains two Python modules `foo1` and `foo2`, both containing two
    functions:
    
        def test2():
            """ Test2. """
            foo()
    
        def test1():
            """ Test1. """
            pass
    
    The generated documentation for `foo1`, erroneously says `test2` and `test1`
    mutually reference eachâothers. The issues disappears if `FILTER_PATTERNS`
    is not used, so I initially suspected something was wrong with `doxypypy`.
    But when inspecting its output, Iâve seen nothing bad and when I tested
    Doxygen on its output, Iâve seen there was no issue anymore. The output
    generated by `doxypypy` is module `foo2`, and the generated documentation
    does not erroneously says anymore `test2` and `test1` mutually reference
    eachâothers.
    
    So it looks like the issue is not due to the filter output, but rather due
    to using `FILTER_PATTERNS`. I canât explain this, so I see it as an
    unexpected side effect.
    
    The issue could be avoided by not using `FILTER_PATTERNS`, but it is needed
    to get briefs as it seems `JAVADOC_AUTOBRIEF` does not work with Python
    sources. Or else, another option, is to not use `REFERENCED_BY_RELATION` and
    `REFERENCES_RELATION`.

**Comment by albert-github** [comment]
I ran the example with the doxygen version 1.8.13 and saw the problem as indicated, e.g. for the package `foo1`:

![image](https://user-images.githubusercontent.com/5223533/180790342-e18eceb7-bcfb-4370-9a53-2ad80cba98eb.png)

When running the current doxygen version (1.9.4) I see:

![image](https://user-images.githubusercontent.com/5223533/180790456-45102f5d-b2bb-402f-8329-05647b7d78aa.png)


This all looks OK to me, so I think the problem has been solved in the mean time.
