### ISSUE TITLE
c# interface with generic type parameter marked as covariant with "out" keyword is not rendered correctly (Origin: bugzilla #789089)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6276]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.13* on platform *Other*
Assigned to: Dimitri van Heesch

On 2017-10-17 11:08:15 +0000, Harmen wrote:

    I have an c# interface with a type parameter marked as covariant with the
    "out" keyword:
    
        public interface IMultiLineResponseParser<out TResponse>
    
    This is rendered by doxygen as:
    
    IMultiLineResponseParser< out out TResponse > Interface Template
    
    The "out" keyword is rendered two times.

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.3.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
