### ISSUE TITLE
c# expression-bodied property is not rendered correctly (Origin: bugzilla #789318)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6278]
status NEEDINFO severity *normal* in component *general* for *---*
Reported in version *1.8.13* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[DoxyGenBugRepro.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug789318_362060_DoxyGenBugRepro.zip/download/download)_ (ID 362060)

On 2017-10-22 11:32:09 +0000, Harmen wrote:

    I have an expression-bodied property:
    
    public static MultiValueDictionary<TKey, TValue> Empty => new
    MultiValueDictionary<TKey, TValue>();
    
    that is renderd by doxygen as:
    
    MultiValueDictionary<TKey, TValue> MultiValueDictionary< TKey, TValue
    >.Empty => new MultiValueDictionary<TKey
    
    Expected output is:
    
    MultiValueDictionary<TKey, TValue> MultiValueDictionary< TKey, TValue
    >.Empty

On 2017-10-22 13:47:14 +0000, albert wrote:

    Can you please attach a (small) self-contained example (source+config file
    in a tar or zip) that allows us to reproduce the problem?

On 2017-10-22 20:35:59 +0000, Harmen wrote:

    Created attachment 362060
    Repro
    
    Source and doxyfile to reproduce the problem

On 2017-10-22 20:38:17 +0000, Harmen wrote:

    the zip file also contains the generated documentation (docs subfolder)

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7991

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
