### ISSUE TITLE
C++ parameter from lambda not recognized (Origin: bugzilla #790320)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6286]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.13* on platform *Other*
Assigned to: Dimitri van Heesch

On 2017-11-14 11:39:38 +0000, Benoit Foucher wrote:

    The following code results in a warning from doxygen when parsed:
    
    /**
     * Doc
     * @param callback callback
     */
    void bug(std::function<void(std::vector<std::map<int, int>>)> callback)
    {
    }
    
    The warning:
    
    test.h:551: warning: argument 'callback' of command @param is not found in
    the argument list of bug()

**Comment by albert-github** [comment]
With the 1.8.13 version (and a default doxygen settings file) I get the warning as well and see in the output:

![image](https://user-images.githubusercontent.com/5223533/173805430-70af047c-e639-4c4a-b12f-ba0ec03d1594.png)

with the 1.9.4 version the warning is gone and the output looks like:

![image](https://user-images.githubusercontent.com/5223533/173805377-eb911858-4c47-418d-9d1b-20a9b6dbb1cf.png)

I think the problem has been solved in the mean time
