### ISSUE TITLE
LaTeX fails with EXTRACT_PRIVATE (Origin: bugzilla #790918)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6292]
status NEEDINFO severity *normal* in component *general* for *---*
Reported in version *1.8.13* on platform *Other*
Assigned to: Dimitri van Heesch

On 2017-11-27 20:50:19 +0000, jack_mustang@hotmail.com wrote:

    I'm on Arch x86_64
    
    These are the TeXLive packages I have installed:
    
    texlive-bin 2017.44590-9
    texlive-core 2017.45811-1
    texlive-latexextra 2017.45733-1
    
    I'm on a C++ project and I wanted to include private members on the
    documentation but if I set EXTRACT_PRIVATE to YES LaTeX fails claiming
    undefined references, though this also happens without EXTRACT_PRIVATE it
    does not crash the PDF generation.
    
    Most of the warnings are:
    
    ```
    LaTeX Warning: Reference `file' on page 7 undefined on input line 6.
    
    pdfTeX warning (dest): name{file} has been referenced but does not exist,
    replaced by a fixed one
    ```
    
    The warnings happen on hierarchy.tex, annotated.tex and files.tex.
    
    After the warnings these errors show up:
    
    ```
    Underfull \hbox (badness 10000) detected at line 89
    [][][]
    [10]
    
    Package longtable Warning: Column widths have changed
    (longtable)                in table 5.1 on input line 100.
    
    
    Package longtable Warning: Column widths have changed
    (longtable)                in table 5.2 on input line 119.
    ```
    
    The output then change to requesting an input from me which I choose X to
    kill it. Telling to continue anyway does not make a difference, I end up
    with an error and the PDF has no index.

On 2017-11-30 17:49:29 +0000, albert wrote:

    can you please attach a (small) self-contained example (source+config file
    in a tar or zip) that allows us to reproduce the problem?

**Comment by albert-github** [comment]
Unfortunately no response, setting to incomplete problem report.
