### ISSUE TITLE
Table formatting information ignored in Doxygen XML output (Origin: bugzilla #791390)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6294]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.8.13* on platform *Other*
Assigned to: Dimitri van Heesch

On 2017-12-08 13:31:40 +0000, James Ghirlando wrote:

    Table formatting, such as:
    
    "colspan"
    "rowspan"
    "align"
    
    is lost in the Doxygen XML output. The HTML/CHM output is well formatted.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7534

**Comment by albert-github** [comment]
Reworked (90fb3132ce02eb44abe3797954267fefcb8d10a8 ) code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.18.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
