### ISSUE TITLE
Lua functions no longer recognized (Origin: bugzilla #791796)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6296]
status NEEDINFO severity *normal* in component *general* for *---*
Reported in version *1.8.13* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[Doxyfile.pub](https://sourceforge.net/projects/doxygen/files/attachments/bug791796_365754_Doxyfile.pub/download/download)_ (ID 365754)

On 2017-12-19 18:07:11 +0000, Chris Merck wrote:

    Created attachment 365754
    Doxyfile used.
    
    In doxygen 1.8.2 one can successfully document lua code, using doxylua as a
    filter.
    https://www.npmjs.com/package/doxylua
    
    Note that, although I'm using doxylua, the problem exists even without
    doxylua -- doxygen simply does not find the lua functions.
    
    However, as of doxygen 1.8.13, lua support is broken. No lua functions are
    found.
    
    This issue has also been encountered by others:
    https://stackoverflow.com/questions/41293071/doxygen-for-lua
    
    Please see attached Doxyfile.

On 2017-12-20 11:34:55 +0000, albert wrote:

    please attach a (small) self-contained example (source+config file in a tar
    or zip) that allows us to reproduce the problem.
    
    As you wrote that the problem also occurs without the lua filter please have
    the example without the filter.
    
    In the mentioned stackoverflow question there was also a comment regarding
    EXTENSION_MAPPING, did you look at this ?

**Comment by albert-github** [comment]
No example is provided and also there is no feedback about the use of `EXTENSION_MAPPING`

Setting issue to incomplete.
