### ISSUE TITLE
\static command not working (Origin: bugzilla #791832)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6298]
status NEW severity *normal* in component *general* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[Doxyfile](https://sourceforge.net/projects/doxygen/files/attachments/bug791832_365827_Doxyfile/download/download)_ (ID 365827)

On 2017-12-21 01:18:43 +0000, gnome.ontherange.kitchengoblin74@antichef.net wrote:

    Created attachment 365827
    Doxyfile that was used to process the source.
    
    The @static command is not handled correctly in the following code:
    
    struct _carData
    {
      float mass;
    };
    
    /*! @class Car*/
    typedef struct _carData *Car;
    
    /*! @memberof Car*/
    static *Car _carRegistry;
    /*! @memberof Car*/
    static size_t _carRegistrySize;
    
    /*! @memberof Car*/
    float CarGetMass(Car car);
    
    /*! @static @memberof Car*/
    void CarInitRegistry();
    
    The expectation is that CarInitRegistry will appear in the documentation for
    the Car class as a static member function. It does appear in the
    documentation, but not as a static.

On 2017-12-21 22:36:18 +0000, gnome.ontherange.kitchengoblin74@antichef.net wrote:

    Actually, not even this simple case works:
    
    struct Peas
    {
    };
    
    /*! @memberof Peas @static*/
    void tada();
    
    Same results. tada is listed as a member of Peas, but not as a static one.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #8963

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.3.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
