### ISSUE TITLE
Redundant whitespace removal breaks some C++ links [with test case and Git bisect] (Origin: bugzilla #791942)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6299]
status NEW severity *normal* in component *general* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2017-12-25 12:21:34 +0000, VladimÃ­r VondruÅ¡ wrote:

    Hello,
    
    the following snippet produces no warning and gives the expected result in
    1.8.11:
    
        /**
        @brief A namespace
    
        - Link to an UDL that works: @link operator""_op @endlink
        - Link to an UDL that doesn't: @link operator""_oq @endlink
        - Link to a function that works: @ref foo(std::initializer_list< T* >)
        - Link to a function that doesn't: @ref foo(std::initializer_list<T*>)
        */
        namespace NS {
    
        /** @brief An operator */
        int operator""_op(unsigned long long);
    
        /** @brief Another operator */
        int operator "" _oq(unsigned long long);
    
        /** @brief Function */
        void foo(std::initializer_list<T*>);
    
        }
    
    However, after 1.8.11, the second and fourth link give a warning and no link
    is generated for these. I don't think the parsing should be so sensitive to
    whitespaces and since it worked before, I think this is a regression. I
    managed to bisect the change down to this commit
    https://github.com/doxygen/doxygen/commit/SHA:
    00ee930a1d73e11885197102c54fd4c8141127da and wanted to submit a PR fixing
    this, but I don't understand the code so well to be able to do that :/
    
    Thank you a lot!

On 2018-04-17 11:11:47 +0000, VladimÃ­r VondruÅ¡ wrote:

    Hi,
    
    any chance of getting this fixed? 
    
    Found another bug related to this commit. Consider the following snippet:
    
        /** @brief A templated structure */
        template<class T> struct S {};
    
        /** @brief A templated structure specialization */
        template<class T> struct S<T*> {
            /** @brief Inner struct */
            struct SS {};
        };
    
    With the above mentioned commit present, `struct SS` is appearing in the XML
    output as `<innerclass>` of `S`, which is not correct. If I revert the
    commit,
    `struct SS` is correctly appearing in the XML output as `<innerclass>` of 
    `S<T*>`. This is only if the type contains a pointer or reference in the 
    specialization. If I change it to for example this:
    
        /** @brief A templated structure specialization */
        template<class T> struct S<typename std::add_pointer<T>::type> {
            /** @brief Inner struct */
            struct SS {};
        };
    
    which, well, compiles to the same, but is ugly, then `SS` is always
    considered
    an `<innerclass>` of `S<typename std::add_pointer<T>::type>` independent of 
    this commit being reverted or not.
    
    Just for the record, original report that triggered this is here: 
    https://github.com/mosra/m.css/issues/35
    
    I have a project that depends on correct behavior of this and at the moment
    I
    have to run on a custom Doxygen version that has the above commit reverted,
    but
    that causes other problems as some links have different hashes etc. Would be
    really great if you could have a look on this.
    
    Thank you!

**Comment by mosra** [comment]
@doxygen @albert-github hello again, any chance of getting this resolved? This is a blocker preventing me to do any further work / improvements / bugfixes on Doxygen.

Thank you :pray:

**Comment by mosra** [comment]
Hello again.

Is there anything more I can do to get this fixed? The commit that introduced the bug is https://github.com/doxygen/doxygen/commit/00ee930a1d73e11885197102c54fd4c8141127da (March 2016, but there hadn't been any change affecting the code in question since then) and the above code snippets are the smallest possible repro cases that trigger it.

Because of this bug, for the [m.css Doxygen theme](https://mcss.mosra.cz/doxygen/) I have to stay on an old fork, can't use newer versions of Doxygen and thus can't help with testing them.

**Comment by doxygen** [comment]
Thanks for the reminder. I can reproduce the problem, so I'll look into it.

**Comment by doxygen** [comment]
I've pushed a possible fix: https://github.com/doxygen/doxygen/commit/449a7e2b4ff114a72be573013558bae19672ebbc

**Comment by mosra** [comment]
Thanks! I tried the commit [on my project](https://github.com/mosra/corrade) and for some reason Doxygen started to consume extreme amounts of memory, so I had to kill it. Then I applied https://github.com/doxygen/doxygen/commit/449a7e2b4ff114a72be573013558bae19672ebbc on the `Release_1_8_14` tag instead (which I know to work well) and that went through and fixed all the issues I had. So thanks a lot for the fix, this helps me on so many levels!

I'll investigate what's the memory usage problem about, will try to bisect to a particular commit, and open a separate issue about it.

**Comment by mosra** [comment]
Opened a new issue about the memory usage problem (https://github.com/doxygen/doxygen/issues/6689), hopefully it has everything needed to repro & fix.

On a related note, would it be possible to add the two above code snippets as regression tests? The whitespace removal code is complex and it would help to have it tested more, also to avoid this problem reappearing again. I can also submit these as a PR, if that helps you in any way. Thanks a lot.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
