### ISSUE TITLE
Explicit link request due to unescapable hash in markdown inline code (Origin: bugzilla #791945)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6300]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.14-GIT* on platform *Other*
Assigned to: Dimitri van Heesch

On 2017-12-25 18:32:04 +0000, Yannick DuchÃªne wrote:

    Providing I have no entity named `foo`, say I have something like this in a
    comment:
    
       /** Blah â¦ `#foo` â¦
         * â¦
         */
    
    I will get this error:
    
    > explicit link request to 'count' could not be resolved
    
    If I do this:
    
       /** Blah â¦ `\#foo` â¦
         * â¦
         */
    
    
    I still get the same error.
    
    Seems `#` works like `@ref` (as I tested it). Thatâs fine, but the issue
    is it canât be escaped when it is found in markdown inline code.
    Otherwise, there is no issue with this:
    
       /** Blah â¦ \#foo â¦
         * â¦
         */
    
    Itâs only when in appears inside of enclosing backticks it seems
    unescapable.

On 2017-12-25 18:34:14 +0000, Yannick DuchÃªne wrote:

    Oops, sorry for the inconsistent copy/past. I meant, I get this message:
    
    > explicit link request to 'foo' could not be resolved

On 2017-12-25 19:27:09 +0000, Yannick DuchÃªne wrote:

    Iâm using `AUTOLINK_SUPPORT = YES` and when I try with `AUTOLINK_SUPPORT =
    NO`, the issue does not showâup any moreâ¯; but then I loose the
    convenient linking this hash allows. By the way, Iâm unsure if
    `AUTOLINK_SUPPORT` is really intended to have an effect on #someName, since
    itâs not automatic, rather explicit, as Doxygen says itself.

On 2017-12-25 21:23:21 +0000, Yannick DuchÃªne wrote:

    Although not the same issue as initially mentioned, even with
    `AUTOLINK_SUPPORT = NO` there remains an issue. If I have something like
    `#foo` in a documentation, the it is displayed in the generated HTML as if
    it was `foo`. If I have something like `\#name` to try to escape it, itâs
    still the same. The hash is dropped. It is preserved only if I have
    something like `# foo`, but thatâs not correct for the documentation.

**Comment by albert-github** [comment]
When I test with the 1.8.154 version I see the warning with the `` `#foo` `` and the `` `\#foo` `` .
With the 1.9.6 version the warning is gone.
(With both versions the output looks OK)

I think the problem has been solved in the mean time.
