### ISSUE TITLE
ruby-compass apparently not maintained upstream anymore (Origin: bugzilla #791995)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6302]
status NEEDINFO severity *major* in component *build* for *---*
Reported in version *1.8.14* on platform *Other*
Assigned to: Dimitri van Heesch

On 2017-12-27 23:46:51 +0000, Matthias Klose wrote:

    ruby-compass apparently is not maintained upstream anymore. Please provide
    an option to build without ruby-compass.
    
    a patch proposal was posted at https://bugs.debian.org/875505

On 2017-12-28 18:49:42 +0000, albert wrote:

    I don't see a patch attached to the debian bug, furthermore I don't see any
    reference to parts where doxygen is involved / causing the problem.

**Comment by albert-github** [comment]
Seen the fact that there is no further information provided and also seen the message with the debian bug  https://bugs.debian.org/875505 i.e. message https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=875505#19.
I think that this bug can be closed as incomplete.
