### ISSUE TITLE
doxygen 1.8.14 cannot detect Clang libraries anymore (Origin: bugzilla #791996)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6303]
status NEW severity *major* in component *build* for *---*
Reported in version *1.8.14* on platform *Other*
Assigned to: Dimitri van Heesch

On 2017-12-27 23:49:38 +0000, Matthias Klose wrote:

    Trying to build doxygen 1.8.14 fails, because the clang cmake files required
    are not available. doxygen 1.8.13 and before used to ship these files.
    
    this was tested with LLVM 5.0.
    
    mkdir -p build
    cd build && cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr
    -Dbuild_wizard=ON -Dbuild_doc=ON -DPYTHON_EXECUTABLE=/usr/bin/python3
    -Duse_libclang=ON -Dbuild_search=ON /home/packages/doxygen/doxygen-1.8.14
    -- The C compiler identification is GNU 7.2.0
    -- The CXX compiler identification is GNU 7.2.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    CMake Error at CMakeLists.txt:43 (find_package):
      Could not find a package configuration file provided by "Clang" with any
    of
      the following names:
    
        ClangConfig.cmake
        clang-config.cmake
    
      Add the installation prefix of "Clang" to CMAKE_PREFIX_PATH or set
      "Clang_DIR" to a directory containing one of the above files.  If "Clang"
      provides a separate development package or SDK, be sure it has been
      installed.
    
    
    -- Configuring incomplete, errors occurred!
    See also
    "/home/packages/doxygen/doxygen-1.8.14/build/CMakeFiles/CMakeOutput.log".
    debian/rules:43: recipe for target 'configure-stamp' failed
    make: *** [configure-stamp] Error 1

On 2017-12-28 19:51:10 +0000, Dimitri van Heesch wrote:

    Hi Matthias,
    
    The homebrew "clang" detection files where not very portable across LLVM
    releases, platforms, and distributions, so I now rely on the cmake built in
    detection, i.e.
    
            find_package(LLVM CONFIG REQUIRED)
            find_package(Clang CONFIG REQUIRED)
    
    If this does not work it is a distribution/cmake issue.
    I know some Linux distros do not install LLVM in the location where cmake
    expects it...

**Comment by albert-github** [comment]
I think that this issue is obsolete in the mean time (old doxygen version, current version is 1.9.1), furthermore in the current version a number of changes have been applied to solve the issue and in the comment it is mentioned "I know some Linux distros do not install LLVM in the location where cmake expects it...".
