### ISSUE TITLE
XHTML pages are broken several ways (Origin: bugzilla #792122)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6305]
status ASSIGNED severity *normal* in component *general* for *---*
Reported in version *1.8.14* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxygenbug_xhtml.rar](https://sourceforge.net/projects/doxygen/files/attachments/bug792122_366241_doxygenbug_xhtml.rar/download/download)_ (ID 366241)

On 2018-01-02 10:46:09 +0000, Jeroen Van Antwerpen wrote:

    Upgrading from 1.8.11 to 1.8.14 gave us several issues we had to work around
    by patching the generated output. This because some important pages suddenly
    became invalid XML.
    
    Important config options:
    HTML_FILE_EXTENSION    = .xhtml
    SEARCHENGINE           = YES
    SERVER_BASED_SEARCH    = YES
    EXTERNAL_SEARCH        = YES
    
    
    
    Search.xhtml
    
    Contains:
                <input type="text" id="MSearchField" name="query" value=""
    size="20" accesskey="S" onfocus="searchBox.OnSearchFieldFocus(true)"
    onblur="searchBox.OnSearchFieldFocus(false)"/>
                </form>
              </div><div class="right"></div>
            </div>
          </li>
        </ul>
      </div>
    
    None of these ending tags are ever started.
    If we explicitly update to start them, we have 2 search boxes of which 1 is
    on a really strange place. (This one)
    
    
    menu.js
    
    Contains <form ...><input ...></form>
    Changed this to <form ...><input .../></form>
    
    With this we were able to view the main page.
    
    On several pages, we have a table in markdown, this seems to generate:
    <tr class="markdownTableBody" class="markdownTableRowEven">
    however, firefox/IE only accept
    <tr class="markdownTableBody,markdownTableRowEven">
    
    
    Lastly, the annotated.xhtml page is broken to (this one also in doxygen
    1.8.11),
    whenever someone adds complicated elements picked up by auto-brief.
    (QT_AUTOBRIEF           = YES)
    
    This is especially the case for comments starting with
    /*!
      * Text
     */
    or with
    Variant 1
    =========
    
    
    Please let me know if you extra information to reproduce this, however, note
    that this might take a while since it takes several hours to run.

On 2018-01-02 20:13:12 +0000, Dimitri van Heesch wrote:

    Hi Jeroen,
    
    Can you please attach a self contained example (source+config file in a tar
    or zip) that allows me to reproduce the problem myself?

On 2018-01-03 10:11:13 +0000, Jeroen Van Antwerpen wrote:

    Created attachment 366241
    Reproduction issue menu.js and annotated.xhtml
    
    To reproduce, you can open the files in firefox and check the console

On 2018-01-03 10:12:51 +0000, Jeroen Van Antwerpen wrote:

    Note, going to http://localhost/bug/search.xhtml?query=other will give you
    the search.xhtml problem

On 2018-03-04 12:15:42 +0000, albert wrote:

    We have here multiple problems listed in 1 report:
    - search problem (menu.js)
    - problem with markdown and tables, please provide separate example
    - problem with "Text", I was not able to reproduce it, please provide
    separate example
    - problem with "Variant 1" and "======", this has to do with the way the
    comment is processed and the moment that the markdown processing is done.
    This can be overcome by placing the \details command before the "Variant 1".
    For this last problem I've just pushed a proposed patch to github (pull
    request 674, https://github.com/doxygen/doxygen/pull/674).

On 2018-04-22 12:30:27 +0000, albert wrote:

    Code has been integrated in master on github.

On 2018-05-16 10:10:47 +0000, Marcin Kasperski wrote:

    The fix introduced some problems, see bug 796110

On 2018-05-20 13:41:54 +0000, albert wrote:

    Fix gave some problems wit h[TOC], this has been fixed in the proposed patch
    (pull request 735, https://github.com/doxygen/doxygen/pull/735).

On 2018-06-10 10:00:42 +0000, albert wrote:

    2018/06/10 New patch (pull request 735) has been integrated on github

**Comment by aquayan** [comment]
For a reproduction example for the table markdown issue, see the separate bug logged for it, with a proposed patch: https://github.com/doxygen/doxygen/issues/6310 (old issue #792373)

**Comment by albert-github** [comment]
The bug mentioned in #6410 is another xhtml error, a proposed pull request #6447 has been mode.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
