### ISSUE TITLE
Format of Qt-Creator Documentation generated through Doxygen (Origin: bugzilla #792149)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6306]
status NEW severity *major* in component *general* for *---*
Reported in version *1.8.14* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[Doxygen_Qt_Display_Issues.png](https://sourceforge.net/projects/doxygen/files/attachments/bug792149_366235_Doxygen_Qt_Display_Issues.png/download/download)_ (ID 366235)
- _[Doxyfile](https://sourceforge.net/projects/doxygen/files/attachments/bug792149_366236_Doxyfile/download/download)_ (ID 366236)
- _[ugly_doc.jpg](https://sourceforge.net/projects/doxygen/files/attachments/bug792149_368371_ugly_doc.jpg/download/download)_ (ID 368371)

On 2018-01-03 06:25:02 +0000, Stefan Walter wrote:

    Created attachment 366235
    Doxygen Qt Header Issue
    
    I'm successfully generating the QCH files for Qt-Creator, but facing two
    display issues (see attachment).
    
    1. Page Header
    As per the attached screenshot, the page has a very strange looking header.
    How can I either deactivate this header or just make it look more useful.
    
    2. Items Header
    As per the attached screenshot, there are some strange items with a huge
    font and an arrow partially displayed. How can I correct this?
    
    I am using Doxygen 1.8.14 on a CentOS 6.9 (Final) x64
    
    Thanks in Advance!

On 2018-01-03 06:30:23 +0000, Stefan Walter wrote:

    Created attachment 366236
    The Doxyfile used to generate the QCH

On 2018-02-15 12:33:44 +0000, Labrunye wrote:

    I got the same issue. I'm using doxygen 1.8.10. The qch file looks good with
    Qt Assistant 5.9.1 but is ugly with Qt Assistant 5.9.4. Note that the html
    file are ok when displayed in a browser. The problem occurs only with Qt
    Assistant 5.9.4 (I did not test 5.9.3 and 5.9.2).

On 2018-02-15 12:35:35 +0000, Labrunye wrote:

    Created attachment 368371
    bad display in qt assistant 5.9.4

On 2018-02-19 13:41:32 +0000, Labrunye wrote:

    From our tests, the bug seems to be in QtAssistant, not doxygen: the same
    qch file is working fine in Qt 5.9.1 but not Qt 5.9.4.
    But for now I did not find any related bug in the Qt bug database.

On 2018-02-19 19:36:22 +0000, albert wrote:

    Did you file a bug report with Qt.
    
    I suggest to close this issue as not a doxygen bug.

On 2018-02-19 19:41:36 +0000, Stefan Walter wrote:

    I will create a bug report in the Qt bug report system and will post here
    later the reference.
    
    I suggest to keep it open until the Qt team has confirmed that the bug is on
    their side.

On 2018-02-19 19:58:17 +0000, Stefan Walter wrote:

    Qt-Creator bug reference: https://bugreports.qt.io/browse/QTCREATORBUG-19881
    
    I will keep this bug reference updated with the progress of the above-
    mentioned bug reference with Qt.

**Comment by TorstenWK** [comment]
I have the same issue and i think i know what the problem is. If you view your generated .qch with the Assistant of Qt 5.5.1 all looks good. If you view the generated .qch with a new version, lets say from Qt 5.9.4 or the newest 5.12.0 the layout of the pages are broken. That's because the newer version are not able to display the stylesheets used for the .html pages. The newer versions of the Assistant using the QTextBrowser to display the pages, which does not support stylesheets!

![qtassistant-qtextbrowser](https://user-images.githubusercontent.com/9879001/49925036-1dab4000-feb8-11e8-841d-ddeae5b759fe.png)
![qtassistant-qtwebkit](https://user-images.githubusercontent.com/9879001/49925039-200d9a00-feb8-11e8-8693-6f1e6d82a9c0.png)

**Comment by albert-github** [comment]
From the comment at the Qt site it looks to me an incompatibility at the Qt side (https://bugreports.qt.io/browse/QTBUG-66525). They nowadays compile the Qt Assistant with QTextBrowser (like you saw as well), when you would recompile the Qt Assistant with the Qt WebKit (as Qt Assistant 5.5.1 also did) it should work again.

**Comment by albert-github** [comment]
Seen the previous comments I think this is not a doxygen bug, but the way the Qt assistant is compiled.
