### ISSUE TITLE
Table markdown produces invalid xhtml code (Origin: bugzilla #792373)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6310]
status NEW severity *major* in component *general* for *---*
Reported in version *1.8.14* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[ReproductionFiles.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug792373_366559_ReproductionFiles.zip/download/download)_ (ID 366559)

On 2018-01-09 15:56:36 +0000, Arie Quist wrote:

    Created attachment 366559
    ZIP containing the .dox, the .cfg and a bat file that starts doxygen.
    
    /*!
    \page DOXBUG_REPRODUCTIONCASE reproduction case
    
    Contents of the page
    
    Test | Attr
    ---- | ----
    abc  | someAttr
    
    Other content that is not shown
    */
    
    generates a table with two 'class' attributes per row (except for the header
    row), which results in an xhmtl parsing error:
    
    XML Parsing Error: duplicate attribute:
    <tr class="markdownTableBody" class="markdownTableRowOdd">
    ------------------------------^
    
    In FireFox, this results in no page at all displayed. In Internet Explorer,
    the page is displayed up to the error.

On 2018-01-10 13:24:43 +0000, Arie Quist wrote:

    Note: as we use table markdown quite frequently throughout our
    documentation, this regression forces us to revert our upgrade from 1.8.11
    to 1.8.14.

On 2018-01-10 13:44:03 +0000, Arie Quist wrote:

    Introduced with https://github.com/doxygen/doxygen/commit/SHA:
    7f35695022d3baa8fc8c8d1b9a9f3368a0963871
    
    Proposed fix: markdown.cpp around line 1780:
         out.addStr("  <tr class=\"markdownTable");
         if (row)
         {
    -      out.addStr("Body\"");
    +      out.addStr("Body,markdownTableRow");
           if (row % 2)
           {
    -        out.addStr(" class=\"markdownTableRowOdd\">\n");
    +        out.addStr("Odd\">\n");
           }
           else
           {
    -        out.addStr(" class=\"markdownTableRowEven\">\n");
    +        out.addStr("Even\">\n");
           }
         }
         else
         {
           out.addStr("Head\">\n");
         }

**Comment by albert-github** [comment]
Code has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
