### ISSUE TITLE
markdown plantuml use of graphviz fails in plantuml, works in code file (Origin: bugzilla #792449)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6312]
status NEW severity *major* in component *doxywizard* for *---*
Reported in version *1.8.14* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[Doxyfile_DotPlantUML](https://sourceforge.net/projects/doxygen/files/attachments/bug792449_366700_Doxyfile_DotPlantUML/download/download)_ (ID 366700)

On 2018-01-12 06:41:25 +0000, rasmusms@gmail.com wrote:

    Created attachment 366700
    doxygen file for c plantuml to work
    
    Hi
    I have a project with c and markdown files. I would like both file types to
    support plantUML. I can get one of them to work at a time, but need to
    change the path to graphviz. For c files it have to be C:/Program Files
    (x86)/Graphviz2.38/bin and for markdown it have to be C:/Program Files
    (x86)/Graphviz2.38/lib/release/lib. So it seems they do not use same dot
    entry point. One is exe and other is lib. If not correct path for c file I
    do not get images of dependencies and if for markdown "Dot executable:
    C:\program files (x86)\graphviz2.38\bin\dot file does not exist Cannot find
    graphviz. You should try @startuml testdot @enduml"

On 2018-01-31 16:32:33 +0000, Mira Kes wrote:

    I can confirm this problem.
    
    I tried some debugging and the problem is that the plantuml.jar wants the
    full name of the dot executable i.e. (on Windows) not just "dot" but
    "dot.exe" ...
    
    java -jar plantuml.jar -graphvizdot "C:\Program Files
    (x86)\Graphviz2.38\bin\dot" -testdot
    The environment variable GRAPHVIZ_DOT has been set to C:\Program Files
    (x86)\Graphviz2.38\bin\dot
    Dot executable is C:\Program Files (x86)\Graphviz2.38\bin\dot
    Error: File does not exist
    Error: only sequence diagrams will be generated
    
    java -jar plantuml.jar -graphvizdot "C:\Program Files
    (x86)\Graphviz2.38\bin\dot.exe" -testdot
    The environment variable GRAPHVIZ_DOT has been set to C:\Program Files
    (x86)\Graphviz2.38\bin\dot.exe
    Dot executable is C:\Program Files (x86)\Graphviz2.38\bin\dot.exe
    Dot version: dot - graphviz version 2.38.0 (20140413.2041)
    
    The problem is that this patch:
    https://github.com/doxygen/doxygen/commit/SHA:
    c24cb9a74ef0af854455047f29f9925d79ac0195
    
    doesn't handle the dot executable name on Windows the way the plantuml
    requires.

On 2018-06-12 13:38:29 +0000, albert wrote:

    I didn't completely get the statements the original bug, but the comment
    gave the right pointer.
    
    I hope I also corrected the title properly.
    
    I've just pushed a proposed patch to github (pull request 764,
    https://github.com/doxygen/doxygen/pull/764).

**Comment by albert-github** [comment]
Code has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
