### ISSUE TITLE
MD file headers are not rendered properly when USE_MDFILE_AS_MAINPAGE is used (Origin: bugzilla #792511)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6313]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.14* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[md_not_rendered_properly.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug792511_366791_md_not_rendered_properly.zip/download/download)_ (ID 366791)

On 2018-01-14 16:53:05 +0000, Andrey Markovytch wrote:

    Created attachment 366791
    Doxyfile configuration, README.md, screen shot of generated web page
    
    The attached README.md contains 3 headers which should be rendered with the
    same size. As you can see in the screenshot the size of the headers is
    different, also the second header is not recognized at all, it is rendered
    as text with # tag instead.
    
    Steps to reproduce : 
    1. Extract zip file
    2. Create ./Framework/Doxygen folder
    3. doxygen Doxyfile
    4. Open html generated in ./Framework/Doxygen folder

**Comment by albert-github** [comment]
With the 1.8.14 version we see that `# Getting started ` is not rendered, with the 1.9.2 version the line is rendered.

I think the problem has been solved in the mean time.
