### ISSUE TITLE
When generating XML output (with GENERATE_XML = YES), any C++ class enum within a named namespace leads to a warning (Origin: bugzilla #792676)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6314]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.12* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[Test.h](https://sourceforge.net/projects/doxygen/files/attachments/bug792676_367069_Test.h/download/download)_ (ID 367069)
- _[Doxyfile.in](https://sourceforge.net/projects/doxygen/files/attachments/bug792676_367070_Doxyfile.in/download/download)_ (ID 367070)
- _[doxygen_log.txt](https://sourceforge.net/projects/doxygen/files/attachments/bug792676_367071_doxygen_log.txt/download/download)_ (ID 367071)

On 2018-01-19 10:25:18 +0000, ÐÐ»ÐµÐºÑÐµÐ¹ ÐÐ¾Ð²Ð°Ð»ÑÐ² wrote:

    Created attachment 367069
    C++ header file containing the problematic enum's
    
    Any C++ scoped enumerations (class enums, introduced in C++11 -- see
    http://en.cppreference.com/w/cpp/language/enum) within a named (non-
    anonymous) namespace lead to warning of type
    warning: Internal inconsistency: member ... does not belong to any
    container!
    when generating XML output (i.e., with GENERATE_XML set to non-default YES).
    
    For instance, when doxygen 1.8.12 is run on the following slightly modified
    example from doxygen documentation
    (http://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdenum) (in
    Test.h, in the attachment):
    ==============
    /** \file Test.h
     * A brief file description.
     * A more elaborated file description.
     */
    namespace MyNamespace
      {
      enum class TEnum { Val1, Val2 };
    
      /*! Another enum, with inline docs */
      enum class AnotherEnum 
        { 
        V1, /*!< value 1 */
        V2  /*!< value 2 */
        };
    
      /*! \var MyNamespace::TEnum MyNamespace::Enum_Test::Val1
       * The description of the first enum value.
       */
      }
    ==============
    we get a bunch of warnings:
    
    Test.h:7: warning: Internal inconsistency: member Val1 does not belong to
    any container!
    Test.h:7: warning: Internal inconsistency: member Val1 does not belong to
    any container!
    Test.h:7: warning: Internal inconsistency: member Val2 does not belong to
    any container!
    Test.h:7: warning: Internal inconsistency: member Val2 does not belong to
    any container!
    Test.h:12: warning: Internal inconsistency: member V1 does not belong to any
    container!
    Test.h:12: warning: Internal inconsistency: member V1 does not belong to any
    container!
    Test.h:14: warning: Internal inconsistency: member V2 does not belong to any
    container!
    Test.h:14: warning: Internal inconsistency: member V2 does not belong to any
    container!
    
    The presence of doxygen documentation in the code does not matter.

On 2018-01-19 10:27:12 +0000, ÐÐ»ÐµÐºÑÐµÐ¹ ÐÐ¾Ð²Ð°Ð»ÑÐ² wrote:

    Created attachment 367070
    The doxygen configuration file
    
    All defaults with the exception of 
    GENERATE_XML = YES

On 2018-01-19 10:29:06 +0000, ÐÐ»ÐµÐºÑÐµÐ¹ ÐÐ¾Ð²Ð°Ð»ÑÐ² wrote:

    Created attachment 367071
    Doxygen output (the log  file)
    
    Shows the "internal inconsistency" warnings, of the type
    warning: Internal inconsistency: member <val_name> does not belong to any
    container!

**Comment by albert-github** [comment]
With version 1.8.12 I see the mentioned warnings, as of version 1.8.15 the warnings are gone (so also in the current 1.9.1 the warnings are gone).

I think the problem has been solved n the mean time
