### ISSUE TITLE
Spaces MAKEINDEX_CMD_NAME don't work the same as other config options (Origin: bugzilla #792690)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6315]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.13* on platform *Other*
Assigned to: Dimitri van Heesch

On 2018-01-19 17:24:00 +0000, Taylor Braun-Jones wrote:

    Config options that take a path like DOT_PATH work fine like:
    
    DOT_PATH = "/path/with a space/dot"
    
    Whereas MAKEINDEX_CMD_NAME requires:
    
    MAKEINDEX_CMD_NAME = "\"/path/with a space/makeindex\""
    
    Because the path is not quoted in the `Makefile` and `make.bat` scripts that
    are generated in the Latex output directory.

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.3.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
