### ISSUE TITLE
Unable to quote file filter command (Origin: bugzilla #792846)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6320]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.13* on platform *Other*
Assigned to: Dimitri van Heesch

On 2018-01-23 21:56:26 +0000, corey.taylor.fl@gmail.com wrote:

    While trying to configure Doxygen to run a file filter that works on both
    Windows and Linux, there doesn't seem to be a way to quote the path to the
    command.
    
    FILTER_PATTERNS        = *.glsl=""scripts/runpython" scripts/doxygen-
    glslfilter.py"
    
    The scripts/runpython needs to be quoted on Windows to allowing the forward
    slash.
    
    However, the quotes seem to be stripped away.  The command ends up with a 
    
    Executing popen(` scripts/runpython scripts/doxygen-glslfilter.py
    "C:/dev/g3d/G3D10/data-files/shader/AlphaFilter.glsl"`)
    
    The function getFileFilter() in util.cpp seems to only remove the
    surrounding quotes, so we were hoping the quotes around the path would stay.
    
        /* remove surrounding double quotes */
        if ((filterName.right(1) == "\"") && (filterName.left(1) == "\""))
        {
           filterName.remove(filterName.length() - 1, 1);
           filterName.remove(0, 1);
        }
    
    
    The call to popen in readCodeFragement() in definition.cpp does not seem to
    add this space or remove other quotes.
    
        QCString cmd=filter+" \""+fileName+"\"";
        Debug::print(Debug::ExtCmd,0,"Executing popen(`%s`)\n",qPrint(cmd));
        f = portable_popen(cmd,"r");
    
    Would it be possible to allow specifying a quoted path/command?
    
    Without this, there doesn't seem to be a way to run a script on both Windows
    and Linux from the file filter.

On 2018-05-04 12:07:02 +0000, albert wrote:

    Relevant discussion on StackExchange:
    https://stackoverflow.com/questions/48394181/is-it-possible-to-wrap-a
    -doxygen-filter-command-in-quotes.
    
    Wouldn't it be better that doxygen replaces the '/' by '\' on windows?

On 2018-05-04 12:29:33 +0000, albert wrote:

    Similar StachOverflow issue: https://stackoverflow.com/questions/49750869
    /what-is-the-qhg-location-path-relative-to-for-doxygen.
    
    For this pull request 703 has been submitted(
    https://github.com/doxygen/doxygen/pull/703).

On 2018-05-08 05:19:13 +0000, corey.taylor.fl@gmail.com wrote:

    I think that would work, thanks!

**Comment by albert-github** [comment]
Pull request #703 integrated.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Comment by FlorianWolters** [comment]
The following does **not** work with Windows 7 using Doxygen 1.8.15

FILTER_PATTERNS        = *.proto=""C:\Program Files\Python2.7\python" "C:\dev\workspace\proto2cpp-doxygen-filter.py""

Error message written to STDERR (German OS):

    Der Befehl "C:\Program" ist entweder falsch geschrieben oder konnte nicht gefunden werden.

Does a workaround exist?

**Comment by albert-github** [comment]
Please try to escape the inner double quotes or to escape the space.

**Comment by FlorianWolters** [comment]
Thanks for the fast reply. I am currently using slashes, not backslashes:

    FILTER_PATTERNS = "*.proto="C:/Program Files/Python2.7/python" "C:/dev/workspace/proto2cpp-doxygen-filter.py""

Can you give me an example how-to escape the quotes and the space?

**Comment by albert-github** [comment]
`FILTER_PATTERNS = "*.proto=\"C:/Program Files/Python2.7/python\" \"C:/dev/workspace/proto2cpp-doxygen-filter.py\""`
alternatively try:
`FILTER_PATTERNS = '*.proto="C:/Program Files/Python2.7/python" "C:/dev/workspace/proto2cpp-doxygen-filter.py"'`

**Comment by FlorianWolters** [comment]
First approach returns the same error, second approach does not execute the comand at all (and does not emit a warning). There is no problem with no spaces in path, e.g. when `python` is added to the `PATH` the following works as expected:

    FILTER_PATTERNS = "*.proto="python" "C:/dev/workspace/proto2cpp-doxygen-filter.py""

Sadly this is not solution for me, because I generate the `Doxygen` file from the build system that locates `python`. Using backslashes instead doesn't work as well. Is it possible to escape the space itself and get rid of the quotes? I've already tried many combinations.

**Comment by albert-github** [comment]
- You could try to escape the space by means of a backslash as well.
- I assume that you are using doxygen version 1.8.15 but please verify by means of `doxygen -v`
- try to run `doxygen -d extcmd Doxyfile` and show one its output.

**Comment by FlorianWolters** [comment]
- Escaping space does not work and prints the following to console: `Der Befehl "C:/Program\" ist entweder falsch geschrieben oder konnte nicht gefunden werden.`
- `doxygen -v` returns `1.8.15`
- Using `FILTER_PATTERNS = "*.proto=\"C:/Program Files/Python2.7/python\" \"C:/dev/workspace/proto2cpp-doxygen-filter.py\""` returns the following output: `Executing popen(`"C:/Program Files/Python2.7/python" "C:/dev/workspace/proto2cpp-doxygen-filter.py" "C:/dev/workspace/foo.proto"`)` This looks OK, imo. But I still get the error message `Der Befehl "C:/Program" ist entweder falsch geschrieben oder konnte nicht gefunden werden.`.

**Comment by albert-github** [comment]
What happens when you use the single quote version?
