### ISSUE TITLE
incorrect parsing of markdown tables (Origin: bugzilla #792918)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6322]
status ASSIGNED severity *normal* in component *general* for *---*
Reported in version *1.8.14* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[bug_markdown_utf8.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug792918_370928_bug_markdown_utf8.zip/download/download)_ (ID 370928)
- _[DocSample.tar](https://sourceforge.net/projects/doxygen/files/attachments/bug792918_370933_DocSample.tar/download/download)_ (ID 370933)
- _[DocSample2.tar](https://sourceforge.net/projects/doxygen/files/attachments/bug792918_370935_DocSample2.tar/download/download)_ (ID 370935)
- _[DocSample.tar](https://sourceforge.net/projects/doxygen/files/attachments/bug792918_372447_DocSample.tar/download/download)_ (ID 372447)

On 2018-01-26 08:32:58 +0000, Stefan Vigerske wrote:

    Putting the code
    
    | <em>Plants</em> &darr; |  &larr; <em>Markets</em> | 
    |:-----------------------|--------------------:|
    | Seattle                |  350 |
    
    
    into a main.md file and running doxygen main.md generates a warning
    
    main.md:12: warning: end of comment block while expecting command </em>
    
    and has all output (not just the table header) emphasized.
    
    This was still working fine with doxygen 1.8.13.

On 2018-01-26 08:45:22 +0000, Stefan Vigerske wrote:

    Probably this is related. The code
    
    
    | | \ref UG_ModelSolve_ModelClassificationOfModels_LP "LP" | \ref
    UG_ModelSolve_ModelClassificationOfModels_MIP "MIP" |
    |:---|:---:| |
    |  | | | 
    
    
    creates a warning
    
    warning: unable to resolve reference to `UG_M' for \ref command
    
    
    Somehow parts of the anchor name got cut off.
    
    This was also fine with doxygen 1.8.13.
    It seems that there is something problematic with markdown tables in doxygen
    1.8.14

On 2018-04-13 15:05:37 +0000, Yurii Shutkin wrote:

    Hello,
    
    I also have similar problem (reproduced only in 1.8.14 while 1.8.13 works
    fine).
    
    My example to reproduce: 
    
    | ÐÐ¾ÑÑ  | I/O | Ð¨Ð¸ÑÐ¸Ð½Ð° | ÐÐ°Ð·Ð½Ð°ÑÐµÐ½Ð¸Ðµ        |
    |-------|-----|--------|-------------------|
    | A[n]  | in  | width  | Ð²ÑÐ¾Ð´Ð½ÑÐµ ÑÐ¸Ð³Ð½Ð°Ð»Ñ   |
    | EN    | in  | 1      | ÑÐ¸Ð³Ð½Ð°Ð» Ð°ÐºÑÐ¸Ð²Ð°ÑÐ¸Ð¸  |
    | Z     | out | width  | Ð²ÑÑÐ¾Ð´Ð½Ð¾Ð¹ ÑÐ¸Ð³Ð½Ð°Ð»   |
    
    The problem here seems to be with utf8 chars, if I replace it with ansi, the
    problem is gone.

On 2018-04-14 08:15:33 +0000, albert wrote:

    @Yurii Shutkin, Can you please attach a, small, self contained example
    (source+config file in a tar or zip) that allows us to reproduce the
    problem?

On 2018-04-14 13:28:56 +0000, Yurii Shutkin wrote:

    Created attachment 370928
    test to reproduce bug with utf8 chars in markdown table

On 2018-04-14 14:04:49 +0000, Pasha wrote:

    @Yurii Shutkin, I'm facing this problem, too.
    
    Headers of my markdown tables get either truncated or combined together.
    
    The problem shows with Cyrillic text in UTF-8 encoding on version 1.8.14
    however everything works fine on version 1.8.13. Latin symbols seem to work
    fine on version 1.8.14.

On 2018-04-14 14:08:39 +0000, Pasha wrote:

    Created attachment 370933
    test file to reproduce incorrect parsing of markdown tables

On 2018-04-14 14:16:13 +0000, Pasha wrote:

    Created attachment 370935
    test file to reproduce incorrect parsing of markdown tables
    
    this will probably be better

On 2018-05-28 16:13:44 +0000, Pasha wrote:

    @albert, having done some research, I've found out that Latin symbols in
    UTF-8 encoding sometimes get truncated as well. So the problem is wider than
    just with Cyrillic symbols.

On 2018-05-28 16:20:33 +0000, albert wrote:

    @pasha Can you please attach a, small, self contained example (source+config
    file in a tar or zip) of the later research as well so that allows us to
    reproduce the problem as well?

On 2018-05-28 16:21:43 +0000, Stefan Vigerske wrote:

    See also the minimal examples provided in the first two comments. No
    Cyrillic there, too.

On 2018-05-28 16:25:11 +0000, albert wrote:

    @stefan, no but in your example there are some special characters / doxygen
    commands (should be OK).

On 2018-05-28 16:51:22 +0000, Pasha wrote:

    Created attachment 372447
    New sample to illustrate the problem

On 2018-05-29 09:33:11 +0000, albert wrote:

    I've just pushed a proposed patch to github (pull request 749,
    https://github.com/doxygen/doxygen/pull/749).
    
    
    
    Problem due to the fact that for the display of the header line the size of
    the separator line was used.
    Workaround (for the users of 1.8.14) is to make separator line long enough
    (take care of the fact that some characters consist of multiple bytes)

On 2018-06-10 10:02:00 +0000, albert wrote:

    Code has been integrated in master on github.

**Comment by MarkShackman** [comment]
Is there an ETA for a release with this fix? 
(Albert's workaround will necessitate a lot of updates/checks, which I'd rather not make if a release is imminent.)

**Comment by albert-github** [comment]
There is no date yet known to me.  I would advise to use the version from master for the time being.

**Comment by MarkShackman** [comment]
OK, don't think I'd be allowed to use an unreleased build in our system, so will use workaround for now. 
Thanks for speedy response - appreciated.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
