### ISSUE TITLE
If names of class and namespace type are the same, innerclass is misjudged in C#. (Origin: bugzilla #793113)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6328]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.13* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[example.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug793113_367786_example.zip/download/download)_ (ID 367786)

On 2018-02-02 04:59:16 +0000, cuspymd wrote:

    Created attachment 367786
    example/src : source codes
    example/result : xml files generated by doxygen
    
    If names of class and namespace type are the same, innerclass is misjudged
    in C#.
    
    
    - Main Doxyfile configurations
    * FILE_PATTERN="*.cs"
    * GENERATE_XML=yes
    
    - Procedure
    Run doxygen for the path 'example/src/' in attached file.
    
    - Actual Result
    The class 'Fruit::Tomato::Core' is misjudged as innerclass of the class
    'Fruit::Tomato'.
    
    - Expected Result
    The class 'Fruit::Tomato::Core' shoud be an innerclass of the namespace
    'Fruit::Tomato'.
    
    - Remarks
    Although the folder structure and naming are poorly designed in attached
    sample,
    I want doxygen to handle it correctly.

On 2018-02-02 14:11:54 +0000, albert wrote:

    This is apparently allowed in C# but according to
    https://stackoverflow.com/questions/18731415/namespace-and-class-with-the-
    same-name it is not advised to do so.
    
    As already written by cuspymd: "Although the folder structure and naming are
    poorly designed in attached sample, I want doxygen to handle it correctly.".
    
    In the example it looks like there is a discrepancy between the handling of
    Apple and Tomato, this should not be the case (symetrical code). Looks like
    a problem with detecting what is a Class and what is a Namespace. Looks like
    problem is not present when internal is renamed to ZZ_internal but is even
    more present in case internal is renamed to aa_internal (alphabetical
    handling of subdirectories).

**Comment by albert-github** [comment]
We see also in the HTML output of the 1.8.13 version:
![image](https://github.com/doxygen/doxygen/assets/5223533/f537cdc9-4383-4024-b5f3-848f666131f9)


In the current doxygen version (1.9.8) we see:
![image](https://github.com/doxygen/doxygen/assets/5223533/adf95160-8a46-4695-b787-a2389617be33)


Also in the XML output we see analogous differences.

I think the problem has been solved in the mean time.
