### ISSUE TITLE
CMake subdirectory build fails (Origin: bugzilla #793537)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6334]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.8.15-GIT* on platform *Other*
Assigned to: Dimitri van Heesch

On 2018-02-17 16:00:51 +0000, Patrick McGuire wrote:

    When attempting to build doxygen as a submodule in a CMake project, CMake
    fails on include(version).  In the below exception, the doxygen git repo has
    been synced to cpp/external/doxygen relative to the root of the top level
    CMake project.
    
    CMake Error at cpp/external/doxygen/version:1:
      Parse error.  Expected a command name, got unquoted argument with text
      "1.8.15".
    Call Stack (most recent call first):
      cpp/external/doxygen/CMakeLists.txt:31 (include)

**Comment by albert-github** [comment]
In pull request #8036 we see that the intention is to "Allow building doxygen as a subproject" (this is incorporated in doxygen version 1.9.0 and later). 

I think the problem has been solved in the mean time.
