### ISSUE TITLE
Memory leak make system crash when "searching for members imported via using declarations" (Origin: bugzilla #793983)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6342]
status NEEDINFO severity *blocker* in component *doxywizard* for *---*
Reported in version *1.8.11* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[bug_source.rar](https://sourceforge.net/projects/doxygen/files/attachments/bug793983_369174_bug_source.rar/download/download)_ (ID 369174)
- _[result.taz](https://sourceforge.net/projects/doxygen/files/attachments/bug793983_369347_result.taz/download/download)_ (ID 369347)

On 2018-03-02 09:21:05 +0000, Dennis wrote:

    Created attachment 369174
    contains the source file and configuration of doxygen.
    
    These codes caused the problem,and we remove all comments for simpilify.
    
    	template<class N,class T,class...Ts>
    	struct InitList: InitList<N,Ts...>{
    		using Base = InitList<N, Ts...>;
    		using Base::Base;
    		
    	};
    A "using Base::Base;" in the template class caused this bug.
    the Base is the class template class itself,see also attachment for more
    detail about configuration of doxygen.
    It will consumes all system memories and then cause our system became blue
    screen.

On 2018-03-02 15:28:18 +0000, albert wrote:

    You specified version 1.8.11 is this correct. Please also try with the
    current version (1.8.14).

On 2018-03-05 02:33:09 +0000, Dennis wrote:

    (In reply to albert from comment # 1)
    > You specified version 1.8.11 is this correct. Please also try with the
    > current version (1.8.14).
    
    I tried the version 1.8.14,it looks better than the version 1.8.11,however,
    it still crashed after consuming around 1.5 GB memories.

On 2018-03-05 14:44:34 +0000, albert wrote:

    Created attachment 369347
    Results with adjusted executable.
    
    I can see that the example looks like it goes into endless loop (didn't run
    it till it came out of it or crashed the machine).
    As far as I can see the recursion comes from the call to
    findUsingDeclImports  by means of the define RECURSE_ENTRYTREE.
    Question is whether or not it is correct that the "call" to
    RECURSE_ENTRYTREE is placed outside the if statement:
      if (rootNav->section()==Entry::USINGDECL_SEC &&
          (rootNav->parent()->section()&Entry::COMPOUND_MASK) // in a
    class/struct member
         )
    or should be placed inside this if statement.
    A small test gave, see attachment result.taz, that the process finished, but
    I don't know if the results are correct and if the move of the "call" to
    RECURSE_ENTRYTREE from outside to inside the if statement is correct /
    allowed.

**Comment by albert-github** [comment]
I revisited the example and with the version 1.8.17 and up the example comes to a quick and normal end. With the earlier versions it looks like it is going into an endless loop.

I think the problem has been solved in the mean time.
