### ISSUE TITLE
Extraneous whitespace in HTML help built with v1.8.14 (Origin: bugzilla #794729)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6347]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.14* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[Doxygen_issue.rar](https://sourceforge.net/projects/doxygen/files/attachments/bug794729_370194_Doxygen_issue.rar/download/download)_ (ID 370194)
- _[AcDebug.cs](https://sourceforge.net/projects/doxygen/files/attachments/bug794729_370241_AcDebug.cs/download/download)_ (ID 370241)

On 2018-03-27 14:24:56 +0000, Brian Buttolph wrote:

    Created attachment 370194
    Small example to demo the problem
    
    We're seeing large blocks of whitespace in the HTML built with v1.8.14 that
    is not present when the same project is built using v1.8.9.1. Extract the
    attached RAR archive and build it under both versions to see the difference.
    Look at the AcDebug class methods in each.
    
    Thanks,
    Brian

On 2018-03-27 16:50:50 +0000, albert wrote:

    Looks like the problem has to do with the automatic conversion of the
    different comment types used. The '///' comments are converted to '/**'
    comments e.g. around line 306 (see also the results of doxygen -d
    commentcnv). Replacing '/*!' by '/**' looks like to solves the problem,
    better would be not to use multiple documentation styles but use just once
    '/***' ... '*/' per comment block.
    
    I think this is not a bug.

On 2018-03-27 20:29:39 +0000, Brian Buttolph wrote:

    The XML in C# '///' code comments is needed for IntelliSense to function
    correctly. Doxygen advertises that it supports a subset of these "XML
    commands" and I've kept to the documented list of supported tags. I tried
    replacing the Qt style '/*!' with JavaDoc style '/**' comments in the
    example, but it broke the HTML generated by Doxygen on both 1.8.9.1 and
    1.8.14.
    
    Using two styles of documentation is required to support both IntelliSense
    and the full Doxygen feature set. Since it works correctly on 1.8.9.1, why
    is this not a bug?

On 2018-03-28 11:58:18 +0000, albert wrote:

    Created attachment 370241
    New version of acDebug.cs
    
    There is now a requirement being the fact that it should work with
    IntelliSense, the original recommendation about the "not a bug" was based on
    the available information.
    
    I did some small modifications:
    - replace /*! by /**
    - merging some comment blocks (especially the ones from \par followed by
    \code
    - small change (hope it will be acceptable in IntelliSense as well)
    regarding the list on the "Module" page.
    now I don't see large blocks of white space and no extra warning messages.
    
    My recommendations still stand.

**Comment by albert-github** [comment]
It is always problematic when using multile styles in one file. That said when looking at the output of

**1.8.9.1**
![image](https://github.com/doxygen/doxygen/assets/5223533/06432b34-60a2-4c4a-adab-7e0738e9129c)

**1.8.14**
![image](https://github.com/doxygen/doxygen/assets/5223533/d56f7c5b-3429-4e25-b2ee-4e0294ab5837)

when looking at the results of the **current, 1.9.8 doxygen** version we see:
![image](https://github.com/doxygen/doxygen/assets/5223533/ed75f0f1-811e-4779-a873-54eab4b4aff1)


This accounts also for other places.

I think the problem has been solved in the mean time.

we see with this function large extra whaite space
