### ISSUE TITLE
"unexpected token TK_EOF as the argument of ref" when target starts with a digit (Origin: bugzilla #795568)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6352]
status NEEDINFO severity *normal* in component *general* for *---*
Reported in version *1.8.14* on platform *Other*
Assigned to: Dimitri van Heesch

On 2018-04-26 09:18:50 +0000, jeberger wrote:

    I have an example whose file name starts with a number (something like
    01_example.txt) and which I include with `@example 01_example.txt`. I'm
    trying to reference this example from another part of the docs with `@ref
    01_example.txt` but this results in the following message: "warning:
    unexpected token TK_EOF as the argument of ref" and no link being created.
    
    Doxygen versions 1.8.6 and 1.8.14 on Linux.

On 2018-04-26 11:10:23 +0000, albert wrote:

    Can you please attach a, small, self contained example (source+config file
    in a tar or zip) that allows us to reproduce the problem?

**Comment by jeberger** [comment]
Why does my email appear in clear in the bug description?

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6592

**Comment by albert-github** [comment]
Code has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Comment by jeberger** [comment]
Confirmed: I can't reproduce the issue on version 1.8.15. Thanks.
