### ISSUE TITLE
add doxywizard.exe in Windows binary package (Origin: bugzilla #795873)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6354]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2018-05-07 09:45:27 +0000, Jannick wrote:

    It would be great if doxywizard.exe could be included in the Windows binary
    release zips or - if it is rarely changed - to provide a separate zip for
    it.
    
    Many thanks.

On 2018-05-07 15:59:57 +0000, albert wrote:

    To the best of my knowledge the doxywizard is in the executables
    installation package for Windows i.e. it is in the doxygen-1.8.14-setup.exe
    but it is missing in the zip files (doxygen-1.8.14.windows.bin.zip and
    doxygen-1.8.14.windows.x64.bin.zip).

On 2018-05-08 20:26:16 +0000, Jannick wrote:

    Exactly, Albert. The idea behind my suggestion is to drop the installed
    doxygen version (which is - as far as I can see - currently the only easy
    way to get doxywizard.exe on Windows systems) and then fully rely on zipped
    releases (for (1) doxywizard.exe and (2) doxygen.exe and friends).

On 2018-05-09 07:12:01 +0000, albert wrote:

    I don't think the exe variant should be dropped (nowadays, unfortunately, a
    lot of people don't know how to install from e.g. a zip file), but the zip
    file should contain the missing executables.

On 2018-05-09 08:58:28 +0000, Jannick wrote:

    Sorry, I was a bit sloppy: What I meant is that I would drop the installed
    version *on my system*, if doxywizard.exe was available in a zipped version.
    
    Of course, I agree with you that both the exe and the zip version should be
    available for download.

**Comment by albert-github** [comment]
@doxygen will this executable be added for future releases?

**Comment by albert-github** [comment]
In the 1.9.3 release the doxygen wizard executable is also available in the zip package.

So I think this problem has been solved in the mean time.

**Comment by doxygen** [comment]
indeed. I'm closing it.
