### ISSUE TITLE
Running command doxygen -g without giving config filename is giving error (Origin: bugzilla #795919)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6355]
status NEEDINFO severity *normal* in component *general* for *---*
Reported in version *1.8.14* on platform *Other*
Assigned to: Dimitri van Heesch

On 2018-05-08 10:51:13 +0000, Shashank wrote:

    Executing below command is resulting in error :
    
    C:\Program Files\doxygen\bin\doxygen.exe -g 
    error : Cannot open file doxyfile for writing.

On 2018-05-08 12:51:14 +0000, albert wrote:

    Do you have write permission on the directory you want to write to?
    Try to write another file to this directory / copy a file to this directory.
    
    Strange that "doxyfile" is written in lowercase should be "Doxyfile" (did
    you type it in? if so always use copy / paste for the exact error message).

**Comment by nickuhlenhuth** [comment]
I had the same issue, but it worked when I ran cmd as an Administrator.

**Comment by albert-github** [comment]
@nickuhlenhuth Can you elaborate a bit on the permissions of the directory where you wanted to write the `Doxyfile`, looks to me that the directory was owned by the 'Administrator'  and you first tried it is 'normal' user.

**Comment by albert-github** [comment]
Unfortunately no response, setting to incomplete problem report.
