### ISSUE TITLE
Issue with /includedoc and plantuml content file (Origin: bugzilla #795962)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6357]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.8.14* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[FilesToReproduce.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug795962_371830_FilesToReproduce.zip/download/download)_ (ID 371830)
- _[SampleDoxygenPlantUML Generation - Touchgram for iMessage Design.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug795962_372523_SampleDoxygenPlantUML Generation - Touchgram for iMessage Design.zip/download/download)_ (ID 372523)

On 2018-05-09 06:47:14 +0000, Christophe SEYLER wrote:

    Created attachment 371830
    Files to reproduce
    
    Trying to use the /includedoc command to include an external file with
    Plantuml content.
    
    The feature works well with the attached test.puml but if I tried with
    another file (attached MQTT_Updater_FSM.puml), the built generates a wrong
    output (see attached error picture.jpg).
    
    The PlantUml code is correct : if I copy-paste the content of the
    MQTT_Updater_FSM.puml directly in the comment, the diagram is correctly
    generated

On 2018-05-09 08:11:16 +0000, albert wrote:

    Can you please attach a, small, self contained example (all source+config
    files in a tar or zip) that allows us to reproduce the problem?
    
    From the picture it looks like there is a problem the way plantuml steers
    the call to dot or it cannot fid the dot executable at the indicated path.

On 2018-06-03 05:59:46 +0000, Andy Dent wrote:

    Created attachment 372523
    Sample to gen docs showing the PlantUML path bug
    
    I have just encountered this problem with 1.8.14, at least it seems to be
    the same problem, in that the PLANTUML_INCLUDE_PATH is ignored.
    
    Attached is a sample demonstrating the problem, and a workaround.
    
    The first time this is run, the error which appears is:
    
    Running PlantUML on generated file
    /Users/andydent/dev/touchgramdesign/doxygeneratedTG4IM/html/inline_umlgraph_1.pu
    Preprocessor Error: Cannot include
    /Users/andydent/dev/touchgramdesign/doxygeneratedTG4IM/html/handDrawnStyle.iuml
    Error line 2 in file:
    /Users/andydent/dev/touchgramdesign/doxygeneratedTG4IM/html/inline_umlgraph_1.pu
    Some diagram description contains errors
    error: Problems running PlantUML. Verify that the command 'java -jar
    "/Library/Java/Extensions/plantuml.jar" -h' works from the command line.
    Exit code: 1
    
    Note that the PlantUML preprocessor is attempting to include a file from the
    DESTINATION directory.
    
    This is ignoring the configuration setting 
    PLANTUML_INCLUDE_PATH  = ./iumltToCopy
    
    
    The workaround in the attached archive is to use HTML_EXTRA_FILES to specify
    the include file. That requires running Doxygen more than once, each time
    the style file is modified, as the copy phase is after DOT generation.

On 2018-06-12 07:35:24 +0000, albert wrote:

    zip file contains only 2 plantumpl files and an image.
    
    Can you please attach a, small, self contained example (all source+config
    files in a tar or zip) that allows us to reproduce the problem?

On 2018-06-12 07:42:44 +0000, Andy Dent wrote:

    I just downloaded my sample "SampleDoxygenPlantUML Generation - Touchgram
    for iMessage Design.zip" to check.
    
    It contains an entire directory:
    
    Touchgram for iMessage Design:
    	doc:
    		mainpage.md
    		scenarios.md
    	iumlToCopy:
    		handDrawnStyle.iuml
    	README.md
    	TG4iMsg DesignDoc.doxy
     
    
    I then opened TG4iMsg DesignDoc.doxy and ran Doxygen - it demonstrates the
    problem.

On 2018-06-12 07:45:46 +0000, Andy Dent wrote:

    (In reply to albert from comment # 3)
    > zip file contains only 2 plantumpl files and an image.
    
    I think you downloaded the FIRST attachment, from Christophe Seyler, not the
    attachment on my comment attachment 372523.

On 2018-06-12 07:48:38 +0000, albert wrote:

    Thanks indeed, I mixed the 2 zip files. Sorry for the confusion.

On 2018-06-12 11:58:47 +0000, albert wrote:

    @Andy:
    
    Why do you use:
    PLANTUML_INCLUDE_PATH  = ./iumltToCopy
    
    and a directory called:
    iumlToCopy

On 2018-06-12 12:03:50 +0000, albert wrote:

    @Christophe SEYLER any possibility of the, small, self contained example
    (all source+config files in a tar or zip) that allows us to reproduce the
    problem?

On 2018-06-12 13:25:58 +0000, Andy Dent wrote:

    @albert
    >Why do you use:
    >PLANTUML_INCLUDE_PATH  = ./iumltToCopy
    
    Ahh, that was left in from when I was trying to use the include path.
    
    I used a separate directory for the "include" files to keep them distinct.

On 2018-06-12 13:40:59 +0000, albert wrote:

    @Andy, I can imagine the separate directories. But with the correct
    directory name I think there is no problem.

On 2018-06-12 13:42:30 +0000, Andy Dent wrote:

    SORRY
    
    This IS embarrassing.
    
    Literally, I had to get new reading glasses, and I didn't notice the typo in
    the include path.
    
    Thanks @albert, it works! (I was busy testing it at the same time as you
    just now)

On 2018-06-12 13:45:12 +0000, albert wrote:

    A typo's can always happen and they are the hardest to find as the brain
    filters them out (took me a while as well before I saw it).

**Comment by albert-github** [comment]
Seen
- the error in the original problem (cannot find the dot executable) and the fact that there is no further response
- that the problem of the second problem (Andy Dent) was a typo

I think we can set the issue to usage.
