### ISSUE TITLE
qt-sdk build dependency not available in repository while building doxygen 1.8.14 on Ubuntu 18.04 (Origin: bugzilla #795995)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6359]
status NEEDINFO severity *normal* in component *build* for *---*
Reported in version *1.8.14* on platform *Other*
Assigned to: Dimitri van Heesch

On 2018-05-10 08:56:22 +0000, Guirish Salgaonkar wrote:

    qt-sdk dependency not available in repository while building doxygen 1.8.14
    on Ubuntu 18.04.

On 2018-05-10 09:23:23 +0000, albert wrote:

    Can you please be a bit more specific, what is missing / what is the error
    message.

On 2018-05-24 09:55:20 +0000, Guirish Salgaonkar wrote:

    Is there official support for doxygen 1.18.14 on Ubuntu 18.04?
    
    I get below error while building doxygen from source on Ubuntu 18.04.
    
    $ cmake -G 'Unix Makefiles' -Dbuild_doc=ON -Dbuild_wizard=YES ..
    -- The CXX compiler identification is GNU 7.3.0
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found PythonInterp: /usr/bin/python (found version "2.7.15") 
    -- Found FLEX: /usr/bin/flex (found version "2.6.4") 
    -- Found BISON: /usr/bin/bison (found version "3.0.4") 
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Looking for pthread_create
    -- Looking for pthread_create - not found
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE  
    -- Looking for iconv_open
    -- Looking for iconv_open - found
    -- Performing Test ICONV_COMPILES
    -- Performing Test ICONV_COMPILES - Success
    -- Found ICONV: In glibc  
    -- One (and only one) of the ICONV_ACCEPTS_... tests must pass
    -- Performing Test ICONV_ACCEPTS_NONCONST_INPUT
    -- Performing Test ICONV_ACCEPTS_NONCONST_INPUT - Success
    -- Performing Test ICONV_ACCEPTS_CONST_INPUT
    -- Performing Test ICONV_ACCEPTS_CONST_INPUT - Failed
    -- Qt5 not found, searching for Qt4 instead...
    CMake Error at /usr/share/cmake-3.10/Modules/FindQt4.cmake:1320 (message):
      Found unsuitable Qt version "" from NOTFOUND, this code requires Qt 4.x
    Call Stack (most recent call first):
      addon/doxywizard/CMakeLists.txt:25 (find_package)
    
    
    -- Configuring incomplete, errors occurred!
    See also
    "/home/test/workspace/Doxygen_1.8.14_Ubuntu18.04_s390x/doxygen/build/CMakeFiles/CMakeOutput.log".
    See also
    "/home/test/workspace/Doxygen_1.8.14_Ubuntu18.04_s390x/doxygen/build/CMakeFiles/CMakeError.log".
    Build step 'Execute shell' marked build as failure

On 2018-05-24 10:30:47 +0000, albert wrote:

    Which version of Qt has been installed on the system?
    Looks like neither Qt5 nor Qt4 can be found. If neither is present please
    install it.

**Comment by albert-github** [comment]
No further information has been provided, setting to not complete.
