### ISSUE TITLE
HIDE_UNDOC_CLASSES = YES still has an effect when EXTRACT_ALL = YES (Origin: bugzilla #796008)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6360]
status NEEDINFO severity *normal* in component *general* for *---*
Reported in version *1.8.14* on platform *Other*
Assigned to: Dimitri van Heesch

On 2018-05-10 16:24:23 +0000, Jason M. Gates wrote:

    We discovered this problem when we realized many inheritance and
    collaboration graphs were not being included in the generated HTML
    documentation.  Stepping through our Doxygen configuration file, we
    discovered that changing HIDE_UNDOC_CLASSES from YES to NO fixed the
    problem.  The documentation for HIDE_UNDOC_CLASSES states:
    
    ----------
    HIDE_UNDOC_CLASSES
    
    If the HIDE_UNDOC_CLASSES tag is set to YES, doxygen will hide all
    undocumented classes that are normally visible in the class hierarchy. If
    set to NO, these classes will be included in the various overviews. This
    option has no effect if EXTRACT_ALL is enabled.
    
    The default value is: NO.
    ----------
    
    Our Doxygen configuration contains EXTRACT_ALL = YES.  It seems either the
    documentation copied above is incorrect, or there is a bug in Doxygen such
    that HIDE_UNDOC_CLASSES does indeed have some effect even when EXTRACT_ALL =
    YES.
    
    If you need our complete Doxygen configuration or any additional
    information, please let me know.  Many thanks.

On 2018-05-10 18:08:35 +0000, albert wrote:

    A small example with The Doxyfile and source files never hurts to be able to
    reproduce the problem.
    
    So can you please attach a, small, self contained example (source+config
    file in a tar or zip) that allows us to reproduce the problem?

**Comment by albert-github** [comment]
Unfortunately no example provided, setting issue to incomplete.
