### ISSUE TITLE
@param for template param doesn't work when name starts from underscore (Origin: bugzilla #796110)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6364]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.15-GIT* on platform *Other*
Assigned to: Dimitri van Heesch

On 2018-05-14 15:53:36 +0000, Marcin Kasperski wrote:

    The curiosity I found while testing fix for bug 796094. I noticed it while
    testing this very version ( https://github.com/doxygen/doxygen/pull/724 ),
    not sure when it appeared but 1.8.13 doesn't have this problem.
    
    Synopsis
    =============
    
    In case someone writes @param instead of @tparam for template parameter,
    doxygen (in aforementioned version) usually detects what's going on and
    silently fixes the issue â¦ but not when the template parameter starts with
    underscore. In such case I get confusing warning:
    
    
    bis.hxx:5: warning: unexpected token in comment block while parsing the
    argument of command param
    
    (I get this for ThisFails below, while both ThisWorks and ThisWorksToo work
    properly)
    
    Example code
    ===============
    
    /**
       Some class
    
       @param _R Some type
    **/
    template<typename _R>
    class ThisFails;
    
    
    /**
       Some class
    
       @param R Some type
    **/
    template<typename R>
    class ThisWorks;
    
    /**
       Some class
    
       @tparam _R Some type
    **/
    template<typename _R>
    class ThisWorksToo;

On 2018-05-14 15:55:58 +0000, Marcin Kasperski wrote:

    Non-pr tip (df0d9c3d) also have this problem.

On 2018-05-14 16:13:29 +0000, Marcin Kasperski wrote:

    1.8.14 is OK (doesn't have the problem). So it's something fresh.
    
    I tried bisect-ing but naive bisect goes confused among those numerous
    branches. But roughly it seems that it's one of the changes merged at
    2018-04-22.
    
    The whole problem, as such, is not very important (after all changing @param
    to more proper @tparam fixes the issue), but I'd really prefer "warning:
    please use @tparam instead of @param for templates" to "warning: unexpected
    token" ;-)

On 2018-05-15 13:27:48 +0000, albert wrote:

    Difficult problem as it has to do with the order of processing in respect to
    Markdown.
    
    The current problems here have been introduced by the changes for the issue:
      bug_792122 - XHTML pages are broken several ways
    (pull request 674 on github).
    
    Also related to this issue is bug:
      bug_775493 - Usage of underscore's in parameter names
    
    Note: also that in version 1.8.14 there exist problems with the tparam
    command in case the names starts and ends with single or double underscores.
    I think that in general all commands where the name of a variables is used
    and the name of the variable name starts and ends with single or double
    underscores gives problems.

On 2018-05-16 10:07:51 +0000, Marcin Kasperski wrote:

    I understand, that the problem happens because parser treats _ as âstart
    italicâ marker. But IIUC, parameter names doesn't support formattingâ¦
    
    And why @param and @tparam behave differently?

On 2018-05-16 10:13:30 +0000, albert wrote:

    Indeed parameter names do not support formatting. But due to the place of
    the handling of the markdown support this is now happening.
    
    That @param and @tparam behave differently is due to the fact that they
    (incorrectly?) go through a different part of the code.
    
    Outside the Bugzilla discussion looking for a solution.

**Comment by albert-github** [comment]
With the 1.8.15 version I see the problem as indicated, with the 1.9.6 this problem is gone (and this particular problem does not show with the 1.8.4 version either).

I created a bit an extended example and this gives with the 1.8.15 version some warnings and some incorrect output.
With the 1.8.14 version there are no warnings but some of the output is not correct.
With the 1.9.6 version there are no warnings and the output looks OK as well.

(Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/11433073/example.tar.gz))

I think the problem has been solved in the mean time.
