### ISSUE TITLE
Suggestion: Replace Qt-style strings with standard C++ strings (Origin: bugzilla #796157)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6365]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.15-GIT* on platform *Other*
Assigned to: Dimitri van Heesch

On 2018-05-16 06:39:57 +0000, Christoph Lipka wrote:

    I suggest trimming down the use of Qt-style strings in the source code, in
    favour of standard C++ style strings, to attract more contributors. From my
    own experience, the heavy use of Qt-style strings is a huge stumbling block
    when trying to debug and/or understand the workings of the code (unless
    using Qt tools, I guess; I myself am using MS Visual Studio).
    
    (The other major stumbling block, again from my experience, is the parser,
    but I guess that would be a herculanean task to replace with anything easier
    to understand.)

**Comment by albert-github** [comment]
During the recent refactorings the Qt functions have been removed  / the internal parts have been replaced by standard C++ strings, So I think this has been fixed but is not yet released.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.2.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
