### ISSUE TITLE
Placing "*/" inside a doxygen comment results in bad behavior (Origin: bugzilla #796216)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6367]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.14* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxygenexample.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug796216_372158_doxygenexample.zip/download/download)_ (ID 372158)
- _[doxygenexample.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug796216_372159_doxygenexample.zip/download/download)_ (ID 372159)

On 2018-05-17 18:58:38 +0000, Keith Steiger wrote:

    Created attachment 372158
    The smallest files I could make that demonstrate the problem.
    
    In the attached header file, there is a comment that reads:
        /// \param escapedXml The XML configuration, with the string "*/"
    escaped into something harmless.
    
    That line causes the doxygen parser to misbehave, resulting in spurious
    errors:
    C:/home/kest/codegen.cpp:3: warning: documented symbol
    `Generator::Generator' was not declared or defined.
    C:/home/kest/codegen.cpp:6: warning: documented symbol `Generator::foo' was
    not declared or defined.
    
    If the string "*/" is modified, the problem goes away.
    
    The Doxyfile was generated using "doxygen -g -s" and is included only for
    completeness.

On 2018-05-17 19:01:53 +0000, Keith Steiger wrote:

    Created attachment 372159
    The smallest files I could make that demonstrate the problem.

On 2018-05-18 09:51:38 +0000, albert wrote:

    This is a very hard problem due to the fact that */ is the end comment in /*
    */ comment sequence.
    Doxygen converts multiline /// comments to /* */ comments.
    I think a work around for this is to see to it that the line with the */ is
    on a line enclosed by blank lines.

**Comment by albert-github** [comment]
I tried with the 1.8.14 version and got a warning due to the part `"*/"` that terminated the comment. With the 1.9.6 version this was gone and the output looks OK as well.

I think the problem has been solved in the mean time.
