### ISSUE TITLE
LaTeX: Class scrbook Error: undefined old font command `\tt' (Origin: bugzilla #796355)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6368]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.13* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[dont_use_deprecated_font_commands.diff](https://sourceforge.net/projects/doxygen/files/attachments/bug796355_372410_dont_use_deprecated_font_commands.diff/download/download)_ (ID 372410)
- _[testcase.tar.bz2](https://sourceforge.net/projects/doxygen/files/attachments/bug796355_372411_testcase.tar.bz2/download/download)_ (ID 372411)
- _[latex.taz](https://sourceforge.net/projects/doxygen/files/attachments/bug796355_372417_latex.taz/download/download)_ (ID 372417)

On 2018-05-23 13:19:18 +0000, AndrÃ© WÃ¶bbeking wrote:

    Hi,
    
    in 1d85e00dd12 you already fixed this for \bf, please fix \tt (and maybe
    other old font commands) too.
    
    I get \tt for @param[out]... and for URLs (http://foo.org and <a
    href="http://...>).
    
    Thanks in advance!
    
    
    Cheers,
    AndrÃ©

On 2018-05-24 11:00:19 +0000, albert wrote:

    To be able to, easily, test it:
    Can you please attach a, small, self contained example (source+config file
    in a tar or zip) that allows us to reproduce the problem?

On 2018-05-25 19:49:14 +0000, AndrÃ© WÃ¶bbeking wrote:

    Created attachment 372410
    Fix for the problem
    
    I thought it's easier to fix the code :-)
    
    But I don't know how to trigger all changed locations.

On 2018-05-25 19:54:03 +0000, AndrÃ© WÃ¶bbeking wrote:

    Created attachment 372411
    Testcase
    
    I could verify with the test case that my problems are fixed.
    
    And don't worry about the "Class srcbook Error", I just realized that I'm
    using LATEX_HEADER (not in my test case).
    
    
    Cheers,
    AndrÃ©

On 2018-05-26 09:05:45 +0000, albert wrote:

    Indeed sometimes it is hard to extract a test case and a test case for all
    is quite difficult to impossible.
    
    Regarding the test case, it is essential that the modified LATEX_HEADER /
    clear instructions how to change the files (refman.tex) to show the problem
    as the default version doesn't show the problem. In this case changing in
    refman.tex the line "\documentclass[twoside]{scrbook}" to
    "\documentclass[twoside]{scrbook}" is sufficient to show the problem
    regarding "\tt".
    
    Regarding the patch:
    - nice that you also found the left over \bf
    - why is \em changed into \textem as well. I didn't read anywhere that \em
    is deprecated. Furthermore not all "\em" have been replaced, latexgen.h.
    When changing (by hand) all the "\em" by "\textem: in struct_test.tex I get
    the error message:
    ! Undefined control sequence.
    <inserted text> ...ex]\hline \endhead  & {\textem
                                                      a} & some variable \\
    \hli...
    l.26 \end{DoxyParams}
    
    - why did you create a patch file and not a patch on github (far easier to
    integrate and it is always clear against which version the patch was made,
    should be the current head on github, as I could not see against which
    version you created your patch).
    
    How to proceed, for me it is clear what has to be done (change the stray \bf
    and the \tt into the text versions)?

On 2018-05-26 10:03:57 +0000, AndrÃ© WÃ¶bbeking wrote:

    (In reply to albert from comment # 4)
    > Indeed sometimes it is hard to extract a test case and a test case for all
    > is quite difficult to impossible.
    > 
    > Regarding the test case, it is essential that the modified LATEX_HEADER /
    > clear instructions how to change the files (refman.tex) to show the
    problem
    > as the default version doesn't show the problem. In this case changing in
    > refman.tex the line "\documentclass[twoside]{scrbook}" to
    > "\documentclass[twoside]{scrbook}" is sufficient to show the problem
    > regarding "\tt".
    
    Right (I've \documentclass[a4paper,11pt]{scrbook} but that shouldn't matter)
    
    > Regarding the patch:
    > - nice that you also found the left over \bf
    > - why is \em changed into \textem as well. I didn't read anywhere that \em
    > is deprecated.
    
    When I googled for the problem I found http://www.tex.ac.uk/FAQ-
    2letterfontcmd.html where also \em is mentioned.
    
    > Furthermore not all "\em" have been replaced, latexgen.h.
    
    Sorry, I probably only grepped for sources and not for headers?!?
    
    > When changing (by hand) all the "\em" by "\textem: in struct_test.tex I
    get
    > the error message:
    > ! Undefined control sequence.
    > <inserted text> ...ex]\hline \endhead  & {\textem
    >                                                   a} & some variable \\
    > \hli...
    > l.26 \end{DoxyParams}
    
    The "new" font commands must be followed by {} so it must be \textem{a} in
    your example.
    
    > - why did you create a patch file and not a patch on github (far easier to
    > integrate and it is always clear against which version the patch was made,
    > should be the current head on github, as I could not see against which
    > version you created your patch).
    
    Sorry, I'm still not used to :-(
     
    > How to proceed, for me it is clear what has to be done (change the stray
    \bf
    > and the \tt into the text versions)?
    
    I used git clone https://github.com/doxygen/doxygen.git yesterday so it
    should be current master.

On 2018-05-26 10:27:20 +0000, albert wrote:

    Created attachment 372417
    latex directory showing problem with book class
    
    Even with \textem{} I get when I use the book class:
    ! Undefined control sequence.
    <inserted text> ...ex]\hline \endhead  & {\textem
                                                      {a}} & some variable \\
    \h...
    l.26 \end{DoxyParams}
    
    Furthermore in the cited article it looks like \em is deprecated but only in
    the first line and the sentence with the word deprecated. There is no
    mention how to replace. I could not fine any reference that \em is
    deprecated and as show in my example \textem does not work with the book
    class (or I must have overlooked something).

On 2018-05-26 10:43:32 +0000, AndrÃ© WÃ¶bbeking wrote:

    You are right, \textem fails here too :-( Reading
    https://tex.stackexchange.com/questions/25911/what-is-the-difference-
    between-em-and-emph it seems to be \emph{} but when \em still works just
    skip that from my patch.

On 2018-05-26 11:01:58 +0000, albert wrote:

    Conclusion:
    - When I'm done with my current test (on some other issues) I'll create a
    proposed patch with only the \tt and the remaining \bf.

On 2018-05-26 12:17:16 +0000, AndrÃ© WÃ¶bbeking wrote:

    Thanks :-)

On 2018-05-26 16:17:50 +0000, albert wrote:

    I've just pushed a proposed patch to github (pull request 743,
    https://github.com/doxygen/doxygen/pull/743).

**Comment by albert-github** [comment]
Code has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
