### ISSUE TITLE
Invalid 3-byte UTF8 found in input of graph (Origin: bugzilla #796426)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6370]
status ASSIGNED severity *normal* in component *build* for *---*
Reported in version *1.8.14* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxytest.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug796426_372435_doxytest.zip/download/download)_ (ID 372435)

On 2018-05-27 15:54:06 +0000, Hayo Baan wrote:

    Created attachment 372435
    zip file with mini example that triggers the bug
    
    With attached sources and doxyfile, the included-by graph triggers a weird
    UTF-8 error: the hover description of the file that includes the header file
    is incorrectly interpreted. The strange thing is that by changing sometimes
    even a single character in the text, the bug isn't triggered...
    
    $ doxygen
    Warning: Invalid 3-byte UTF8 found in input of graph file2.h - treated as
    Latin-1. Perhaps "-Gcharset=latin1" is needed?
    Warning: Invalid 3-byte UTF8 found in input of graph file2.h - treated as
    Latin-1. Perhaps "-Gcharset=latin1" is needed?

On 2018-05-28 12:53:58 +0000, albert wrote:

    I've just pushed a proposed patch to github (pull request 745,
    https://github.com/doxygen/doxygen/pull/745).
    
    Note dot 2.38.0 silently ignored the error, 2.40.1 shows the error

On 2018-06-27 10:33:19 +0000, albert wrote:

    2018/06/24 Code has been integrated in master on github.

**Comment by t-b** [comment]
#745 fixed the bug and is merged.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Comment by HayoBaan** [comment]
Well, the warning is indeed gone, but the text shown in the hover still has the UTF-8 characters showing incorrectly e.g. `“true”` gets replaced with `âtrueâ` (c3 a2 c2 80 c2 9c 74 72  75 65 c3 a2 c2 80 c2 9d in hex).
