### ISSUE TITLE
\n in alias is not replaced by newline (Origin: bugzilla #796446)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6371]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.8.14* on platform *Other*
Assigned to: Dimitri van Heesch

On 2018-05-29 10:50:30 +0000, Christian wrote:

    Hi,
    
    with doxygen 1.8.9 this alias worked as expected:
    imageall{1}=\image html \1\n\image latex \1\n\image rtf \1
    
    It expanded to this:
    \image html MyImage.png
    \image latex MyImage.png
    \image rtf MyImage.png
    
    But with doxygen 1.8.14 I get this build result:
    C:/Test.c:23: warning: image file MyImage.png\n\image is not found in
    IMAGE_PATH: assuming external image.
    C:/Test.c:23: warning: Illegal command n as part of a \image
    C:/Test.c:23: warning: Illegal command image as part of a \image
    
    It seems that \n wasn't replaced by a newline.
    A workaround is to use ^^ instead of \n. But I think \n should still work?
    
    Best regards
    Christian

On 2018-06-05 06:44:27 +0000, Christian wrote:

    Hi,
    
    we found that the behaviour differs depending on the usage of 32 or 64 bit
    version of doxygen.
    With 64 bit version of doxygen under win 7 and win 10 (installed via
    doxygen-1.8.14-setup.exe) we get the behaviour as described.
    The 32 bit version behaves as expected. No warning occurs.
    
    Best regards
    Christian

**Comment by albert-github** [comment]
In the 1.8.14 a change in respect to the handling of the `\n` in AALIASES` has taken place.
In version 1.8.14 acts `^^` as if there is a physical newline in the code.

This is not a bug but an intended change.
