### ISSUE TITLE
Stackoverflow/recursion when generating graphical class hierarchy (Origin: bugzilla #796479)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6372]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.13* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[Doxyfile.tar.xz](https://sourceforge.net/projects/doxygen/files/attachments/bug796479_372505_Doxyfile.tar.xz/download/download/download/download/download/download/download)_ (ID 372505)
- _[reproduce.tar.gz](https://sourceforge.net/projects/doxygen/files/attachments/bug796479_372513_reproduce.tar.gz/download/download/download/download/download/download/download)_ (ID 372513)
- _[reproduce.tar.gz](https://sourceforge.net/projects/doxygen/files/attachments/bug796479_372514_reproduce.tar.gz/download/download/download/download/download/download/download)_ (ID 372514)
- _[inherit_graph_0.png](https://sourceforge.net/projects/doxygen/files/attachments/bug796479_372520_inherit_graph_0.png/download/download/download/download/download/download/download)_ (ID 372520)
- _[inherit_graph_1.png](https://sourceforge.net/projects/doxygen/files/attachments/bug796479_372521_inherit_graph_1.png/download/download/download/download/download/download/download)_ (ID 372521)

On 2018-06-01 10:24:58 +0000, nolange79@gmail.com wrote:

    Created attachment 372505
    doxygen config
    
    Hello, I cant add the sources as these are from work, doxygen ends in an
    infinite loop when generating the "graphical class hierarchy".
    I tried reducing the files involved, but the subdirectories on their own
    dont cause the issue, only certain sets (or an amount) causes the crash.
    
    Doxygen is 1.8.13-10 from debian
    OS: 4.16.0-1-amd64 # 1 SMP Debian 4.16.5-1 (2018-04-29) x86_64 GNU/Linux
    
    Generating index page...
    Generating page index...
    Generating module index...
    Generating namespace index...
    Generating namespace member index...
    Generating annotated compound index...
    Generating alphabetical compound index...
    Generating hierarchical class index...
    Generating graphical class hierarchy...
    
    Program received signal SIGSEGV, Segmentation fault.
    0x00007ffff551767e in _int_malloc (av=av@entry=0x7ffff584bc40 <main_arena>,
    bytes=bytes@entry=24) at malloc.c:3557
    3557	malloc.c: No such file or directory.
    (gdb) bt
    # 0  0x00007ffff551767e in _int_malloc (av=av@entry=0x7ffff584bc40
    <main_arena>, bytes=bytes@entry=24) at malloc.c:3557
    # 1  0x00007ffff551959c in __GI___libc_malloc (bytes=24) at malloc.c:3057
    # 2  0x00007ffff5e8ee48 in operator new(unsigned long) () from
    /usr/lib/x86_64-linux-gnu/libstdc++.so.6
    # 3  0x0000555555c905aa in QGList::append(void*) ()
    # 4  0x0000555555bf3457 in DotNode::renumberNodes(int&) ()
    # 5  0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 6  0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 7  0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 8  0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 9  0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 10 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 11 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 12 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 13 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 14 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 15 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 16 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 17 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 18 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 19 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 20 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 21 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 22 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 23 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 24 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 25 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 26 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 27 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 28 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 29 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 30 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 31 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 32 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 33 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 34 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 35 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 36 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 37 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 38 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 39 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 40 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 41 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 42 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 43 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 44 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 45 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 46 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    .
    .
    .
    # 255897 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 255898 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 255899 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 255900 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 255901 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 255902 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 255903 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 255904 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 255905 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 255906 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 255907 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 255908 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 255909 0x0000555555bf3479 in DotNode::renumberNodes(int&) ()
    # 255910 0x0000555555bf4368 in DotGfxHierarchyTable::DotGfxHierarchyTable()
    ()
    # 255911 0x00005555558759f4 in ?? ()
    # 255912 0x0000555555885690 in ?? ()
    # 255913 0x000055555588458c in ?? ()
    # 255914 0x0000555555886efb in writeIndexHierarchy(OutputList&) ()
    # 255915 0x0000555555808a2b in generateOutput() ()
    # 255916 0x00005555557bfb9e in main ()

On 2018-06-01 10:32:05 +0000, nolange79@gmail.com wrote:

    A Better trace with debugsymbols (cant seem to get any relevant locals)
    
    # 0  0x00007ffff551767e in _int_malloc (av=av@entry=0x7ffff584bc40
    <main_arena>, bytes=bytes@entry=24) at malloc.c:3557
    # 1  0x00007ffff551959c in __GI___libc_malloc (bytes=24) at malloc.c:3057
    # 2  0x00007ffff5e8ee48 in operator new(unsigned long) () from
    /usr/lib/x86_64-linux-gnu/libstdc++.so.6
    # 3  0x0000555555c905aa in QGList::append (this=0x555558ef2e90, d=<optimized
    out>) at ./qtools/qglist.cpp:366
    # 4  0x0000555555bf3457 in QListIterator<DotNode>::QListIterator (l=...,
    this=0x7fffff05f110) at ./qtools/qlist.h:129
    # 5  DotNode::renumberNodes (this=<optimized out>, number=@0x7fffffffd99c:
    255906) at ./src/dot.cpp:2192
    # 6  0x0000555555bf3479 in DotNode::renumberNodes (this=<optimized out>,
    number=@0x7fffffffd99c: 255906) at ./src/dot.cpp:2196
    # 7  0x0000555555bf3479 in DotNode::renumberNodes (this=<optimized out>,
    number=@0x7fffffffd99c: 255906) at ./src/dot.cpp:2196
    # 8  0x0000555555bf3479 in DotNode::renumberNodes (this=<optimized out>,
    number=@0x7fffffffd99c: 255906) at ./src/dot.cpp:2196
    # 9  0x0000555555bf3479 in DotNode::renumberNodes (this=<optimized out>,
    number=@0x7fffffffd99c: 255906) at ./src/dot.cpp:2196
    # 10 0x0000555555bf3479 in DotNode::renumberNodes (this=<optimized out>,
    number=@0x7fffffffd99c: 255906) at ./src/dot.cpp:2196
    # 11 0x0000555555bf3479 in DotNode::renumberNodes (this=<optimized out>,
    number=@0x7fffffffd99c: 255906) at ./src/dot.cpp:2196
    # 12 0x0000555555bf3479 in DotNode::renumberNodes (this=<optimized out>,
    number=@0x7fffffffd99c: 255906) at ./src/dot.cpp:2196
    # 13 0x0000555555bf3479 in DotNode::renumberNodes (this=<optimized out>,
    number=@0x7fffffffd99c: 255906) at ./src/dot.cpp:2196
    # 14 0x0000555555bf3479 in DotNode::renumberNodes (this=<optimized out>,
    number=@0x7fffffffd99c: 255906) at ./src/dot.cpp:2196
    # 15 0x0000555555bf3479 in DotNode::renumberNodes (this=<optimized out>,
    number=@0x7fffffffd99c: 255906) at ./src/dot.cpp:2196
    # 16 0x0000555555bf3479 in DotNode::renumberNodes (this=<optimized out>,
    number=@0x7fffffffd99c: 255906) at ./src/dot.cpp:2196
    # 17 0x0000555555bf3479 in DotNode::renumberNodes (this=<optimized out>,
    number=@0x7fffffffd99c: 255906) at ./src/dot.cpp:2196
    # 18 0x0000555555bf3479 in DotNode::renumberNodes (this=<optimized out>,
    number=@0x7fffffffd99c: 255906) at ./src/dot.cpp:2196
    # 19 0x0000555555bf3479 in DotNode::renumberNodes (this=<optimized out>,
    number=@0x7fffffffd99c: 255906) at ./src/dot.cpp:2196
    .
    .
    .
    # 255898 0x0000555555bf3479 in DotNode::renumberNodes (this=<optimized out>,
    number=@0x7fffffffd99c: 255906) at ./src/dot.cpp:2196
    # 255899 0x0000555555bf3479 in DotNode::renumberNodes (this=<optimized out>,
    number=@0x7fffffffd99c: 255906) at ./src/dot.cpp:2196
    # 255900 0x0000555555bf3479 in DotNode::renumberNodes (this=<optimized out>,
    number=@0x7fffffffd99c: 255906) at ./src/dot.cpp:2196
    # 255901 0x0000555555bf3479 in DotNode::renumberNodes (this=<optimized out>,
    number=@0x7fffffffd99c: 255906) at ./src/dot.cpp:2196
    # 255902 0x0000555555bf3479 in DotNode::renumberNodes (this=<optimized out>,
    number=@0x7fffffffd99c: 255906) at ./src/dot.cpp:2196
    # 255903 0x0000555555bf3479 in DotNode::renumberNodes (this=<optimized out>,
    number=@0x7fffffffd99c: 255906) at ./src/dot.cpp:2196
    # 255904 0x0000555555bf3479 in DotNode::renumberNodes (this=<optimized out>,
    number=@0x7fffffffd99c: 255906) at ./src/dot.cpp:2196
    # 255905 0x0000555555bf3479 in DotNode::renumberNodes (this=<optimized out>,
    number=@0x7fffffffd99c: 255906) at ./src/dot.cpp:2196
    # 255906 0x0000555555bf3479 in DotNode::renumberNodes (this=<optimized out>,
    number=@0x7fffffffd99c: 255906) at ./src/dot.cpp:2196
    # 255907 0x0000555555bf3479 in DotNode::renumberNodes (this=<optimized out>,
    number=@0x7fffffffd99c: 255906) at ./src/dot.cpp:2196
    # 255908 0x0000555555bf3479 in DotNode::renumberNodes (this=<optimized out>,
    number=@0x7fffffffd99c: 255906) at ./src/dot.cpp:2196
    # 255909 0x0000555555bf3479 in DotNode::renumberNodes (this=<optimized out>,
    number=@0x7fffffffd99c: 255906) at ./src/dot.cpp:2196
    # 255910 0x0000555555bf3479 in DotNode::renumberNodes (this=<optimized out>,
    number=@0x7fffffffd99c: 255906) at ./src/dot.cpp:2196
    # 255911 0x0000555555bf4368 in DotGfxHierarchyTable::DotGfxHierarchyTable
    (this=0x7fffffffda00) at ./src/dot.cpp:2532
    # 255912 0x00005555558759f4 in writeGraphicalClassHierarchy (ol=...) at
    ./src/index.cpp:1055
    # 255913 0x0000555555885690 in writeIndexHierarchyEntries (ol=...,
    entries=...) at ./src/index.cpp:4174
    # 255914 0x000055555588458c in writeIndexHierarchyEntries (ol=...,
    entries=...) at ./src/index.cpp:4267
    # 255915 0x0000555555886efb in writeIndexHierarchy (ol=...) at
    ./src/index.cpp:4449
    # 255916 0x0000555555808a2b in generateOutput () at ./src/doxygen.cpp:11565
    # 255917 0x00005555557bfb9e in main (argc=2, argv=0x7fffffffe198) at
    ./src/main.cpp:38

On 2018-06-01 13:57:22 +0000, albert wrote:

    What happens with the current version 1.8.14 ? If persistent, please also
    try (when possible), with the current github head.
    
    If everything persistent, please attach a, small, self contained example
    (source+config file in a tar or zip) that allows us to reproduce the
    problem?
    (wil be hard as you already wrote).

On 2018-06-01 18:27:04 +0000, nolange79@gmail.com wrote:

    Created attachment 372513
    reproducable testcase
    
    Hi,
    
    was some work finding out the involved files and crippling them as much as
    possible.
    
    You are probably aware of these pains dealing with closed code, but just to
    be sure: Please dont add this code for a test-case, but write one from
    scratch, once you figured out the cause.
    
    Happy hunting.

On 2018-06-01 18:56:52 +0000, nolange79@gmail.com wrote:

    Created attachment 372514
    reduced testcase

On 2018-06-02 08:06:10 +0000, albert wrote:

    Thanks for the example.
    I'm aware of the problems and restrictions of closed code, so I'm happy you
    found a nice small example to reproduce the problem.
    
    I quickly tested it with 1.8.12, 1.8.13, 1.8.14 and the current github head
    (on Windows) and all versions crashed, but 1.8.11 ran (all on windows).

On 2018-06-02 13:54:22 +0000, albert wrote:

    Created attachment 372520
    Graph showing recursive problem with <int>  version(?)
    
    I did some investigations and found the change that, looks like to, cause
    the problem:
    git commit: SHA: fb66cae35cd59d1026fe3c6de46ae3a2ed6f9f91 on February 2
    2016. With comment: Reimplemented node renumbering for dot graph to improve
    performance
    
    It looks like the problem is due to a recursive definition.
    Are the resulting graphs (as attached) correct? as I see a difference
    between the TElement and the int version.
    
    A quick fix is (but I'm not sure if this is correct and doesn't only hide
    the some other problems so I'm reluctant to make a pull request out of it)
    is to change the line:
          cn->renumberNodes(number);
    into
          if (cn != this) cn->renumberNodes(number);

On 2018-06-02 13:55:10 +0000, albert wrote:

    Created attachment 372521
    Graph  with <TElement>  version

On 2018-06-02 20:05:37 +0000, nolange79@gmail.com wrote:

    The full code has its full implementation in the _Internal namespace, there
    is no recursion of any kind involved. It does not appear to me that I would
    have wrecked the reduced example to introduce recursion either.
    
    The public namespace consist of templates deriving from the implementation
    (for ex. to avoid code explosion like having a single "void *"
    implementation serving every "T *" as base).
    
    the longest chain of derived classes is 3 (BufferRwc -> BufferRwcHead ->
    Internal::BufferRwcHead).
    
    Doxygen appears to pick the wrong namespace for the <int> example,
    <TElement> example is correct.
    
    So you have two issue:
    1) the infinite recursion that seems to introduced withe the commit above
    2) Wrong name lookup (resolve to BufferRwcHead instead of
    Internal::BufferRwcHead)

**Comment by nolange** [comment]
Sorry to be a pain about this issue, but how is the progress?
To me this is a blocker, and I will have to build my own (debian) package if there is no fix in the official sources.

**Comment by nolange** [comment]
is this solved with 17338710275948c23e0f0b312d004b84976f68bc ?

**Comment by albert-github** [comment]
Did you try ?

**Comment by albert-github** [comment]
I tested with 1.8.13 and 1.8.14 on windows it crashed.
When running with 1.8.15 it went through.

I think the problem has been solved in the mean time.

**Comment by nolange** [comment]
Just did, does not crash anymore.
