### ISSUE TITLE
Defining a variable named the same as a file suffix kills autolinking of those files. (Origin: bugzilla #796575)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6376]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.14* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxytest.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug796575_372666_doxytest.zip/download/download)_ (ID 372666)

On 2018-06-13 08:41:03 +0000, Hayo Baan wrote:

    Created attachment 372666
    zip file with mini example that triggers the bug
    
    When you define a variable called h in a source file, autolinking no longer
    works for header files. I have attached a mini example to illustrate this.
    When you run doxygen on it, the main page will not make the reference to
    file2.h a link. When you don't process the .c files (e.g. using
    Doxyfile.working) the link is generated. Also renaming the variable to e.g.
    xxxh or even H works, so this is purely related to the variable having the
    name of the file suffix.
    
    Some further analysis shows that the same issue exist with a variable called
    c; then .c files no longer autolink. The problem is not even limited to
    single character variable names; a variable called e.g. cxx will kill
    autolinking of .cxx files.
    
    Hopefully this is an easy fix...

**Comment by albert-github** [comment]
When I run the problem with the 1.8.14 version the `file2.h` on the mainpage is not linked, when running with 1.9.5 it is linked.

I think the problem has been solved in the mean time.

**Comment by HayoBaan** [comment]
Agreed, issue can be closed.
