### ISSUE TITLE
Doxygen has stopped working (Origin: bugzilla #796582)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6377]
status NEW severity *critical* in component *general* for *---*
Reported in version *1.8.14* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[Screenshot (15).png](https://sourceforge.net/projects/doxygen/files/attachments/bug796582_372681_Screenshot (15).png/download/download)_ (ID 372681)

On 2018-06-14 04:46:40 +0000, praveen wrote:

    i am trying to build the documentation, i am facing error like Doxygen
    stopped working.

On 2018-06-14 04:55:59 +0000, praveen wrote:

    Created attachment 372681
    Bug describes that doxygen crashed, i have tried to uninstall and install
    but i have same problem

On 2018-06-14 07:03:09 +0000, praveen wrote:

    I have tried to install the Eclox , I have stopped in the middle of
    installation, so at that onwards when i try to build documentation, i am
    facing this kind of error.
    
    I have uninstalled Doxygen multiple times and installed new one & also got
    new eclipse, but still i am facing same error.

On 2018-06-14 08:13:25 +0000, albert wrote:

    As you wrote you aborted the installation of Eclox and after this doxygen
    does not work anymore even after reinstalling doxygen.
    From the image it is unclear from where you started doxygen.
    Does doxygen work outside of eclipse (just try doxygen -v)?  If so it is
    something of eclipse.
    
    In either case it looks like some directories / settings are still present,
    deinstall doxygen, eclipse and eclox completely over the control panel.
    Delete all program and settings directories regarding the mentioned
    programs. Check the PATH settings, check registry settings. Reboot your
    system. Install doxygen and check if doxygen as such works again (so outside
    eclipse!).
    
    Note: you are doing this all at your own risk.
    
    
    I don't think this is a doxygen problem.

**Comment by martingonzalezmartinez** [comment]
I think I found the cause of this issue and it is related with having a "null" path on your environment.
Something added into Doxygen 1.8.15 can't deal with an empty PATH variable, so it crashes.

On windows, If you do this, doxygen 1.8.15 fails:

_set path=
DoxygenAbsolutePath/doxygen.exe_

It crashes.

However, simply adding a space or a semicolon to your path fixes the issue.

_set path=;
DoxygenAbsolutePath/doxygen.exe_

I just discovered this because I am working on a project where we set our PATH variable to be blank.

@doxygen Can you confirm this behaviour?

**Comment by albert-github** [comment]
Looks like the versions till (including) 1.8.11 don't crash and 1.8.12 and further do crash.
I checked on windows.
Which Os did you use?

**Comment by martingonzalezmartinez** [comment]
Sorry, I deleted my previous comment because I realised this post was older than the 1.8.15 version was released so I thought it was unrelated.

I am running on Windows 10, which worked fine with version 1.8.14 but not with 1.8.15

Just to recap, I found that this specific version (1.8.15) can't deal with an empty PATH variable (_set path=_)

However version 1.8.14 was handling it properly.

**Comment by albert-github** [comment]
Strange that for you on Windows 10 the 1.8.14 runs.
Tested on Windows 10 (just starting doxygen version without arguments so usage text is displayed):
 - 1.8.11 OK
 - 1.8.12 and newer stop without any message nor popup

that I don't get a popup might be due different settings, in my case, between Windows 7 and Windows 10.

**Comment by martingonzalezmartinez** [comment]
I was calling doxygen.exe with a doxyfile, so no without arguments.

Calling from command prompt:
- 1.8.14 crashes both with and without argument
- 1.8.15 crashes both with and without argument

Calling from makefile:
- 1.8.14 crashes without argument but WORKS with argument
- 1.8.15 crashes both with and without argument

**Comment by albert-github** [comment]
Thanks for the explanation, I always used the command line version for my tests.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7064

**Comment by martingonzalezmartinez** [comment]
Thanks for the patch. 

I am working on a software tool for a customer, which will need to be maintained/updated in the future. Are you planning to release the fix on the next releases? Thanks.

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
