### ISSUE TITLE
@cond does not stop at @endcond Fortran (Origin: bugzilla #796621)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6378]
status NEW severity *major* in component *general* for *---*
Reported in version *1.8.14* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[DoxyFortTest.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug796621_372721_DoxyFortTest.zip/download/download)_ (ID 372721)

On 2018-06-18 17:22:55 +0000, marandus@gmail.com wrote:

    !<@cond scan
        function ModelPath(AuxString, Level)    
            ...    
        end function ModelPath
    !<@endcond
    
    produces 
    
    error: Conditional section with label  scan does not have a corresponding
    \endcond command within this file. (warning treated as error, aborting now)
    *** Doxygen has finished
    
    Have tried variations of the syntax to no avail. inside the function is a
    fortran intrinsic 'scan' that Doxygen can't handle and simply exits when
    reached during parsing.

On 2018-06-18 18:03:29 +0000, albert wrote:

    I tried to reproduce the problem, but didn't succeed.
    
    Can you please attach a, small, self contained example (source+config file
    in a tar or zip) that allows us to reproduce the problem?

On 2018-06-19 11:24:30 +0000, marandus@gmail.com wrote:

    Created attachment 372721
    Self-contained test
    
    So, the problem is more complex in behavior than I previously exposed.
    
    In the example you can see two uses of 'scan' in the same function. If the
    second use, inside the conditional statement, is commented out Doxy runs and
    @cond works as expected I believe. Otherwise the error occurs.

On 2018-06-19 11:38:15 +0000, albert wrote:

    The problem here is that doxygen has some problems with the backslash in
    Fortran.
    
    When I use a backslash I use the parameter:
      CHARACTER(LEN=1), PARAMETER :: backSlash = char(92) !< the back slash (\\)
    character
    
    and concatenate this into the string.

On 2018-06-19 13:07:16 +0000, marandus@gmail.com wrote:

    (In reply to albert from comment # 3)
    > The problem here is that doxygen has some problems with the backslash in
    > Fortran.
    > 
    > When I use a backslash I use the parameter:
    >   CHARACTER(LEN=1), PARAMETER :: backSlash = char(92) !< the back slash
    (\\)
    > character
    > 
    > and concatenate this into the string.
    
    Thank you very much.
    
    Can you think of any other way to force the doxygen parser to simply not
    read the '\'? I'm not at the liberty to change the source at this moment...

On 2018-06-19 13:09:37 +0000, albert wrote:

    No I didn't find a solution, therefore I used the parameter as indicated.

On 2018-06-19 13:42:48 +0000, marandus@gmail.com wrote:

    Thank you!

On 2018-06-19 13:56:58 +0000, albert wrote:

    Looks like I found a workaround, don't use " (double quotes) but ' (single
    quotes)

On 2018-06-19 17:50:00 +0000, albert wrote:

    The previous comment was not completely correct but a bit luck (due to the '
    in doesn't.
    
    I checked the code and I've just pushed a proposed patch to github (pull
    request 773, https://github.com/doxygen/doxygen/pull/773).

**Comment by albert-github** [comment]
Pull request #773 integrated, issue can be labeled as `fixed but not released`.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
