### ISSUE TITLE
doxygen markdown engine disallow parentheses in image title (Origin: bugzilla #796673)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6380]
status NEW severity *major* in component *general* for *---*
Reported in version *1.8.15-GIT* on platform *Other*
Assigned to: Dimitri van Heesch

On 2018-06-25 19:52:56 +0000, billconan@gmail.com wrote:

    doxygen's markdown engine fails to recognize the following as an image:
    
    ![Requests per sec](benchmark_rps.png "Requests per sec (#/sec)")
    
    
    the bug is because of the use of parentheses in the image title.

On 2018-06-26 00:27:31 +0000, billconan@gmail.com wrote:

    this issue can be fixed by my change:
    
    https://github.com/shi-yan/doxygen/commit/SHA:
    2e6d0f95b3f6e2619370b756f83edb46fc8f3660

On 2018-06-26 07:23:09 +0000, albert wrote:

    Why didnÂ´t you create a pull request for the doxygen repository?

On 2018-06-26 14:31:51 +0000, billconan@gmail.com wrote:

    because my tree isn't clean. I have done a few doxygen changes that are
    unrelated. when creating a pull request, it seems to gather all my previous
    commits (including unwanted) into one pull request?

On 2018-06-26 14:33:17 +0000, billconan@gmail.com wrote:

    ok, I have to do this, https://stackoverflow.com/questions/5256021/send-a
    -pull-request-on-github-for-only-latest-commit

**Comment by albert-github** [comment]
The mentioned patch (https://github.com/shi-yan/doxygen/commit/2e6d0f95b3f6e2619370b756f83edb46fc8f3660) has never been submitted and was also a bit restrictive (it required a matching number of brackets).
So: I've just pushed a proposed patch, pull request #8690

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.3.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
