### ISSUE TITLE
Todo - broken hyperlink

### ISSUE THREAD

**Issue by micpaci** [doxygen/doxygen#6385]
When using **todo** or **ref** special commands, a broken hyperlink is generated into the documentation under Windows and Linux both.

In particular the broken hyperlink is created in the page where the special command belongs, for example:

![cattura6](https://user-images.githubusercontent.com/40996051/42454067-d88357a0-838e-11e8-8700-41f6e07bad74.PNG)

The error reported by Firefox is:

> ** Firefox can’t find the file at WORKING_PATH/MY_OUTPUT_PATH/html/dd/da0/todo.html#_todo000003**

**Comment by albert-github** [comment]
Can you please attach a, small, self contained example (source+config file in a tar or zip) that allows us to reproduce the problem?
Please also state te version doxygen you are using.

**Comment by micpaci** [comment]
Hi Albert,

thank you for reply.

I'm using Doxygen 1.8.11

Actually I found out that the issue is caused by **CREATE_SUBDIRS = YES** option, line 71 of doxyfile.

I attacched two versions of a simple example, one with the TODO link broken (CREATE_SUBDIRS = YES) and the other properly working (CREATE_SUBDIRS = NO).

I hope they may help you to fix the issue!

Best regards,

Michele

[todoBug.tar.gz](https://github.com/doxygen/doxygen/files/2179321/todoBug.tar.gz)
[todoOk.tar.gz](https://github.com/doxygen/doxygen/files/2179322/todoOk.tar.gz)

**Comment by albert-github** [comment]
With version 1.8.11 I can reproduce the problem
With version 1.8.14 the problem is gone

I think the problem has been solved in the mean time

**Comment by micpaci** [comment]
I cloned the git repo, built and installed the last doxygen version following this instructions http://www.stack.nl/~dimitri/doxygen/download.html and now the issue is gone for me too.

I previously installed doxygen with apt-get on Xubuntu 16.04 and the last available version is 1.8.11

Thank you for support!


Best regards,

Michele
