### ISSUE TITLE
PlantUML absolutly need the fullname for the dot executable, including extension, when using -graphvizdot option

### ISSUE THREAD

**Issue by pailheres** [doxygen/doxygen#6386]
When using PlantUML, i get the following generated pdf
[inline_umlgraph_2.pdf](https://github.com/doxygen/doxygen/files/2177273/inline_umlgraph_2.pdf)

I have modified a bit plantuml.cpp like this:

  if (Config_getBool(HAVE_DOT) && !dotPath.isEmpty())
  {
    pumlArgs += "-graphvizdot \"";
    pumlArgs += dotPath;
    pumlArgs += "dot";
#if defined(_WIN32) // Windows
    //because PlantUML absolutly need the fullname for the dot executable, including extension, when using -graphvizdot option
    pumlArgs += ".exe";
#endif
    pumlArgs += "\" ";
  }

and now everything generates OK. Seem to be needing ".exe" extension absolutely in the path when using the -graphvizdot in PlantUML. It was doing this with PlantUML 1.2018.0 and 1.2018.8

If running PlantUML by hand, i had the following outputs (both without and with) the .exe extension in the -graphvizdot option:

C:\Program Files (x86)\Mscgen>java -jar plantuml.jar -verbose -graphvizdot "C:\Program Files (x86)\Graphviz\bin\dot" C:\devel\firm_trunk\super\sil2\build\msvc\GENERATE_DOCS\latex\inline_umlgraph_4.pu
(0.000 - 123 Mo) 119 Mo - PlantUML Version 1.2018.08
(0.007 - 123 Mo) 118 Mo - GraphicsEnvironment.isHeadless() false
(0.023 - 123 Mo) 118 Mo - Setting current dir: .
(0.023 - 123 Mo) 118 Mo - Setting current dir: C:\devel\firm_trunk\super\sil2\build\msvc\GENERATE_DOCS\latex
(0.025 - 123 Mo) 117 Mo - Using default charset
(0.029 - 123 Mo) 117 Mo - Setting current dir: C:\devel\firm_trunk\super\sil2\build\msvc\GENERATE_DOCS\latex
(0.046 - 123 Mo) 116 Mo - Setting current dir: C:\devel\firm_trunk\super\sil2\build\msvc\GENERATE_DOCS\latex
(0.048 - 123 Mo) 116 Mo - Reading file: C:\devel\firm_trunk\super\sil2\build\msvc\GENERATE_DOCS\latex\inline_umlgraph_4.pu
(0.341 - 155 Mo) 89 Mo - Creating file: C:\devel\firm_trunk\super\sil2\build\msvc\GENERATE_DOCS\latex\inline_umlgraph_4.png
(0.566 - 155 Mo) 130 Mo - Creating image 403x225
(0.589 - 155 Mo) 122 Mo - Ok for com.sun.imageio.plugins.png.PNGMetadata
(0.679 - 155 Mo) 120 Mo - Number of image(s): 1

C:\Program Files (x86)\Mscgen>java -jar plantuml.jar -verbose -graphvizdot "C:\Program Files (x86)\Graphviz\bin\dot.exe" C:\devel\firm_trunk\super\sil2\build\msvc\GENERATE_DOCS\latex\inline_umlgraph_4.pu
(0.000 - 123 Mo) 119 Mo - PlantUML Version 1.2018.08
(0.007 - 123 Mo) 118 Mo - GraphicsEnvironment.isHeadless() false
(0.021 - 123 Mo) 118 Mo - Setting current dir: .
(0.022 - 123 Mo) 118 Mo - Setting current dir: C:\devel\firm_trunk\super\sil2\build\msvc\GENERATE_DOCS\latex
(0.023 - 123 Mo) 117 Mo - Using default charset
(0.027 - 123 Mo) 117 Mo - Setting current dir: C:\devel\firm_trunk\super\sil2\build\msvc\GENERATE_DOCS\latex
(0.042 - 123 Mo) 116 Mo - Setting current dir: C:\devel\firm_trunk\super\sil2\build\msvc\GENERATE_DOCS\latex
(0.044 - 123 Mo) 116 Mo - Reading file: C:\devel\firm_trunk\super\sil2\build\msvc\GENERATE_DOCS\latex\inline_umlgraph_4.pu
(0.309 - 155 Mo) 90 Mo - Creating file: C:\devel\firm_trunk\super\sil2\build\msvc\GENERATE_DOCS\latex\inline_umlgraph_4.png
(0.508 - 155 Mo) 75 Mo - Starting Graphviz process [C:\Program Files (x86)\Graphviz\bin\dot.exe, -Tsvg]
(0.508 - 155 Mo) 75 Mo - DotString size: 4063
(0.529 - 155 Mo) 73 Mo - Ending process ok
(0.529 - 155 Mo) 73 Mo - Ending Graphviz process
(0.560 - 155 Mo) 70 Mo - Creating image 1174x760
(0.635 - 155 Mo) 122 Mo - Ok for com.sun.imageio.plugins.png.PNGMetadata
(0.806 - 155 Mo) 113 Mo - Number of image(s): 1

**Comment by albert-github** [comment]
This problem has already been addressed by means of pull request #764.

**Comment by albert-github** [comment]
Code has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
