### ISSUE TITLE
redundant input_filter runs significantly reduce performance when FILTER_SOURCE_FILES and INLINE_SOURCES are both enabled

### ISSUE THREAD

**Issue by abathur** [doxygen/doxygen#6387]
It looks like the combination of `FILTER_SOURCE_FILES` and `INLINE_SOURCES` causes doxygen to call `readCodeFragment()` once per function, run the input filter on every call, but only grab the specified lines from the output. Under these conditions, it looks like runtimes grow rapidly for inputs with large files containing many functions.

Timing with `FILTER_SOURCE_FILES` both enabled and disabled:

```
122.366 sec: Total elapsed time: 122.366 seconds
(of which 0.000 seconds waiting for external tools to finish)
----------------------
...
Spent 109.865 seconds in Generating class documentation...
...
```

Then, disabled:

```
12.277 sec: Total elapsed time: 12.277 seconds
(of which 0.000 seconds waiting for external tools to finish)
----------------------
...
Spent 1.553 seconds in Generating class documentation...
...
```

I'm not sure how common these conditions are, but for context, the above runs only account for a fraction of a percent of our codebase. We haven't done one in a while, but AFAIR our full runs take a few hours, and this is probably to blame.

**Comment by albert-github** [comment]
It is not a very common situation, but it can certainly happen for inline sources but is more common for code snippets.

I've just pushed a proposed patch, pull request #6395.

**Comment by albert-github** [comment]
An alternative implementation has been made an integrated in master on github.
