### ISSUE TITLE
Enumeration short section empty with output optimized for C#

### ISSUE THREAD

**Issue by Thf772** [doxygen/doxygen#6392]
Using Doxygen 1.8.14 or 1.8.11 (from Xenial repos)
`OPTIMIZE_OUTPUT_JAVA` set to `YES`
Running on C# sources

In the page for a namespace documentation, the "Enumerations" section is empty in the short doc list, even though my namespace contains enumerations.

In the Detailed Description part, the "Enumeration Type Documentation" section contains the enumerations.

This happens in both HTML and LaTeX output.

![screen_doxygen](https://user-images.githubusercontent.com/18517127/42621073-0d04a65c-85bd-11e8-97dc-3a908936839f.png)

**Comment by albert-github** [comment]
Can you please attach a, small, self contained example (source+config file in a tar or zip) that allows us to reproduce the problem?

**Comment by albert-github** [comment]
Unfortunately no response, setting to incomplete problem report.
