### ISSUE TITLE
Executing doxygen 1.8.14 on Ubuntu 14.04 fails due to not found "GLIBCXX_" versions

### ISSUE THREAD

**Issue by PiJ82** [doxygen/doxygen#6393]
Hello,

I'm running a fresh installation of Ubuntu 14.04.5 LTS on a Virtual Machine.
Installed gcc version is `gcc (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4`.
`uname -a` output: `Linux me-u1404vm 4.4.0-128-generic #154~14.04.1-Ubuntu SMP Fri May 25 14:58:51 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

I downloaded the binary doxygen 1.8.14 for Ubuntu here: http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.14.linux.bin.tar.gz
The documentation for this download states it has been compiled using Ubuntu 14.04, kernel 3.13.0, gcc 4.8.2.

For the binary to run libclang.so is required as well, so I downloaded this version from the official LLVM download section - also for Ubuntu 14.04 - from here: http://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz

I ran the doxygen binary using the following command:
`$ LD_LIBRARY_PATH=/tmp/clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-14.04/lib && ./doxygen`

And I got the following error:
```
$ LD_LIBRARY_PATH=/tmp/clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-14.04/lib && ./doxygen 
./doxygen: /lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by ./doxygen)
./doxygen: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./doxygen)
./doxygen: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./doxygen)
./doxygen: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./doxygen)
```

### Further, hopefully helpful information
`ldd` on the doxygen binary yields:
```
$ ldd doxygen 
./doxygen: /lib/x86_64-linux-gnu/libtinfo.so.5: no version information available (required by ./doxygen)
./doxygen: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./doxygen)
./doxygen: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./doxygen)
./doxygen: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./doxygen)
	linux-vdso.so.1 =>  (0x00007ffd8c3e1000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007efe6fbe2000)
	libclang.so.6 => /tmp/clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-14.04/lib/libclang.so.6 (0x00007efe6be9f000)
	libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007efe6bc76000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007efe6ba5d000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007efe6b759000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007efe6b453000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007efe6b23d000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007efe6ae74000)
	/lib64/ld-linux-x86-64.so.2 (0x00007efe6fe00000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007efe6ac70000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007efe6aa68000)
```

`ldd` on `/lib/x86_64-linux-gnu/libtinfo.so.5` yields:
```
$ ldd /lib/x86_64-linux-gnu/libtinfo.so.5
	linux-vdso.so.1 =>  (0x00007ffcfdd0b000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f08d6b48000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f08d713a000)
```

To further investigate the problem I checked the doxygen binary using `strings` (Note: The full output is attached [here](https://github.com/doxygen/doxygen/files/2188170/strings_output_on_doxgen_binary.txt)):

```
$ strings doxygen | grep GLIBCXX
GLIBCXX_3.4.14
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.9
GLIBCXX_3.4.15
GLIBCXX_3.4.11
GLIBCXX_3.4
GLIBCXX_3.4.20
GLIBCXX_3.4.21
_GLIBCXX_PREDEFINED_OBJC_ARC_IS_SCALAR
__GLIBCXX_TYPE_INT_N_0
__GLIBCXX_BITSIZE_INT_N_0
[...]
```

Using `objdump` I could investigate the provided versions from `/usr/lib/x86_64-linux-gnu/libstdc++.so.6`:
```
$ objdump -x /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
2 0x00 0x08922974 GLIBCXX_3.4
3 0x00 0x02297f81 GLIBCXX_3.4.1
	GLIBCXX_3.4 
4 0x00 0x02297f82 GLIBCXX_3.4.2
	GLIBCXX_3.4.1 
5 0x00 0x02297f83 GLIBCXX_3.4.3
	GLIBCXX_3.4.2 
6 0x00 0x02297f84 GLIBCXX_3.4.4
	GLIBCXX_3.4.3 
7 0x00 0x02297f85 GLIBCXX_3.4.5
	GLIBCXX_3.4.4 
8 0x00 0x02297f86 GLIBCXX_3.4.6
	GLIBCXX_3.4.5 
9 0x00 0x02297f87 GLIBCXX_3.4.7
	GLIBCXX_3.4.6 
10 0x00 0x02297f88 GLIBCXX_3.4.8
	GLIBCXX_3.4.7 
11 0x00 0x02297f89 GLIBCXX_3.4.9
	GLIBCXX_3.4.8 
12 0x00 0x0297f860 GLIBCXX_3.4.10
	GLIBCXX_3.4.9 
13 0x00 0x0297f861 GLIBCXX_3.4.11
	GLIBCXX_3.4.10 
14 0x00 0x0297f862 GLIBCXX_3.4.12
	GLIBCXX_3.4.11 
15 0x00 0x0297f863 GLIBCXX_3.4.13
	GLIBCXX_3.4.12 
16 0x00 0x0297f864 GLIBCXX_3.4.14
	GLIBCXX_3.4.13 
17 0x00 0x0297f865 GLIBCXX_3.4.15
	GLIBCXX_3.4.14 
18 0x00 0x0297f866 GLIBCXX_3.4.16
	GLIBCXX_3.4.15 
19 0x00 0x0297f867 GLIBCXX_3.4.17
	GLIBCXX_3.4.16 
20 0x00 0x0297f868 GLIBCXX_3.4.18
	GLIBCXX_3.4.17 
21 0x00 0x0297f869 GLIBCXX_3.4.19
	GLIBCXX_3.4.18 

$ objdump -x /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep CXXABI
22 0x00 0x056bafd3 CXXABI_1.3
23 0x00 0x0bafd171 CXXABI_1.3.1
	CXXABI_1.3 
24 0x00 0x0bafd172 CXXABI_1.3.2
	CXXABI_1.3.1 
25 0x00 0x0bafd173 CXXABI_1.3.3
	CXXABI_1.3.2 
26 0x00 0x0bafd174 CXXABI_1.3.4
	CXXABI_1.3.3 
27 0x00 0x0bafd175 CXXABI_1.3.5
	CXXABI_1.3.4 
28 0x00 0x0bafd176 CXXABI_1.3.6
	CXXABI_1.3.5 
29 0x00 0x0bafd177 CXXABI_1.3.7
	CXXABI_1.3.6 
30 0x00 0x06bc6f71 CXXABI_TM_1
```

**Comment by albert-github** [comment]
Looks like the version of your gcc distribution and the version as used by doxygen are not compatible. The mentioned compiler versions should not create these differences, but please check whether or not the `/usr/lib/x86_64-linux-gnu/libstdc++.so.6` is the one that is expected and not an older gcc version (check with, I think you can run the `.so` file!,  /usr/lib/x86_64-linux-gnu/libstdc++.so.6 or /usr/lib/x86_64-linux-gnu/libstdc++.so.6 --version).

**Comment by PiJ82** [comment]
Hi @albert-github,

running `$ file /usr/lib/x86_64-linux-gnu/libstdc++.so.6` gave me:
`/usr/lib/x86_64-linux-gnu/libstdc++.so.6: symbolic link to 'libstdc++.so.6.0.19'`
So the interesting output might be this:
```
$ file /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19 
/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19: ELF 64-bit LSB  shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=6f4b9babc2e5d1c42a3f00e2d0e5895c5a957055, stripped
```

I did some digging and checked the GCC [ABI Policy and Guidelines](https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html). According to this, there was a change between gcc version 4.8.0 and gcc version 4.8.3.
* GCC 4.8.0: libstdc++.so.6.0.18
* GCC 4.8.3: libstdc++.so.6.0.19

So to my understanding the doxygen version in question was built against libstdc++.so.6.0.18, which should not be a problem when using the newer one.

I also checked the version history of the Ubuntu package libstdc++6 and it seems only two versions for Ubuntu 14.04 were shipped (maybe I'm mistaken):
```
$ apt-cache showpkg libstdc++6
Package: libstdc++6
Versions:
4.8.4-2ubuntu1~14.04.4 (/var/lib/apt/lists/de.archive.ubuntu.com_ubuntu_dists_trusty-updates_main_binary-amd64_Packages) (/var/lib/apt/lists/security.ubuntu.com_ubuntu_dists_trusty-security_main_binary-amd64_Packages) (/var/lib/dpkg/status)
 Description Language:
                 File: /var/lib/apt/lists/de.archive.ubuntu.com_ubuntu_dists_trusty_main_binary-amd64_Packages
                  MD5: 724ab84919e0e220afb960e36463914d
 Description Language: en
                 File: /var/lib/apt/lists/de.archive.ubuntu.com_ubuntu_dists_trusty_main_i18n_Translation-en
                  MD5: 724ab84919e0e220afb960e36463914d

4.8.2-19ubuntu1 (/var/lib/apt/lists/de.archive.ubuntu.com_ubuntu_dists_trusty_main_binary-amd64_Packages)
 Description Language:
                 File: /var/lib/apt/lists/de.archive.ubuntu.com_ubuntu_dists_trusty_main_binary-amd64_Packages
                  MD5: 724ab84919e0e220afb960e36463914d
 Description Language: en
                 File: /var/lib/apt/lists/de.archive.ubuntu.com_ubuntu_dists_trusty_main_i18n_Translation-en
                  MD5: 724ab84919e0e220afb960e36463914d
```

I downloaded the older package version (`4.8.2-19ubuntu1`) from the repositories and checked its content. It also includes version 6.0.19.

**Comment by albert-github** [comment]
You shouldn't use the `file` command on the `.so` but just run the `.so` file

Strange thing I saw:
- `LD_LIBRARY_PATH=/tmp/clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-14.04/lib && ./doxygen `, I think this should be at least `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/tmp/clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-14.04/lib && ./doxygen` otherwise you loose the original libraries (although it might still pick up the default libraries)
- against which version of `gcc` are the clang and llvm libraries compiled?

**Comment by PiJ82** [comment]
Running the .so doesn't work, it ends with a segfault. Also I'm not sure whether it is even possible running a *.so file?

I don't exactly know against which version of gcc the clang/llvm libraries are built.
```
$ strings clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-14.04/lib/libclang.so | grep GLIBCXX
GLIBCXX_3.4.19
GLIBCXX_3.4.9
GLIBCXX_3.4.18
GLIBCXX_3.4.17
GLIBCXX_3.4.15
GLIBCXX_3.4.14
GLIBCXX_3.4
GLIBCXX_3.4.11
_GLIBCXX_PREDEFINED_OBJC_ARC_IS_SCALAR
__GLIBCXX_BITSIZE_INT_N_0
__GLIBCXX_TYPE_INT_N_0
```
So I would guess against libstdc++.so.6.0.19 which means gcc >= 4.8.3?

**Comment by albert-github** [comment]
Doing some research I get the impression that the information on the doxygen main page is not 100% correct (I didn't build the executables so I don't know for sure).
From the site: https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html I get the impression that a gcc 5.0 or newer compiler has been used seen the lines:

```GCC 4.8.0: libstdc++.so.6.0.18
GCC 4.8.3: libstdc++.so.6.0.19
GCC 4.9.0: libstdc++.so.6.0.20
GCC 5.1.0: libstdc++.so.6.0.21
GCC 6.1.0: libstdc++.so.6.0.22
```

**Comment by PiJ82** [comment]
That's the same impression I have. Thanks for the clarification :)

**Comment by mosra** [comment]
Related question: is the Clang dependency really required? The download page says nothing about it. I'd like to use the 1.8.14 release for running tests on Travis CI, but the additional requirement of having Clang 6 installed (which is very fresh, not in many repositories yet) is preventing me from that. The previous version 1.8.13 didn't have this requirement and so I'm stuck on using that one. It's not feasible to compile Doxygen from scratch every time a Travis job is run.

Would it be possible to: 

- provide a prebuilt version that *doesn't* depend on Clang (like 1.8.13 used to be)
- or provide a prebuilt version that doesn't need *the very latest* Clang
- or, if you really think Clang is required, provide two sets of prebuilt binaries, one depending on Clang and the other not?

Thank you! :+1:

**Comment by doxygen** [comment]
@mosra clang is an build time option. It is possible to create a binary without any dependency on libclang. This is even the default when you build from sources.

For the binary package I had in mind to link *statically* against libclang.a, which I also did in the past. I see however there is still a reference to libclang.so for release 1.8.14, which is not correct. I have to investigate why this happened.

**Comment by doxygen** [comment]
@PiJ82 I upgraded to Ubuntu 16.04 LTS in the meantime. Website needs to be updated.

**Comment by mosra** [comment]
> I see however there is still a reference to libclang.so for release 1.8.14, which is not correct. I have to investigate why this happened.

That would be awesome, thank you a lot! :+1:

**Comment by doxygen** [comment]
After some tweaking I managed to create a fully static version of libclang and build doxygen against that. I made a binary package available here for testing purposes: http://ftp.stack.nl/pub/users/dimitri/test/doxygen-1.8.14.static_clang.linux.bin.tar.gz

The relevant LLVM/clang cmake build options:
- LIBCLANG_BUILD_STATIC:BOOL=ON
- BUILD_SHARED_LIBS:BOOL=OFF
- LLVM_ENABLE_PIC:BOOL=OFF
- LLVM_BUILD_LLVM_DYLIB:BOOL=OFF
- LLVM_BUILD_LLVM_C_DYLIB:BOOL=OFF

**Comment by mosra** [comment]
Thank you! Just tested pulling the archive on Travis: it doesn't complain about libclang.so anymore (yay!), but now I'm at the aforementioned glibc error too: https://travis-ci.org/mosra/m.css/jobs/408040212#L568

Travis CI is still on Ubuntu 14.04 and there's no sign of when they'll start adding support for 16.04 (not to mention 18.04), so we're kinda stuck here. I know the issues with keeping compatibility with 8 year old distirbution very well myself, but that's how it is ...

Idea: what about building the release binaries directly on Travis? You'll get a consistent sanitized environment and don't have to worry about breaking compatibility by upgrading your machine. The tests are already being built there, so it shouldn't be that much work to add also release archive building. I can offer some help with this (though at the moment I'm a bit busy).

**Comment by PiJ82** [comment]
Thank you Dimitri, thank you @mosra. Unfortunately I have the same problem with being stuck on Ubuntu 14.04 for some time, that's why I was excited to read about the support for it.

**Comment by t-b** [comment]
Isn't the glibcxx ABI thing this one -> https://askubuntu.com/a/824334?

**Comment by doxygen** [comment]
@mosra I already use Travis for building. So if Travis CI is your target would it be an idea to build doxygen from sources there as part of your own run?

i.e. add something like this to your travis config file:

    curl https://codeload.github.com/doxygen/doxygen/tar.gz/Release_1_8_14 -o doxygen.tar.gz
    tar zxvf doxygen.tar.gz
    mkdir doxygen_build
    cd doxygen_build
    cmake ../doxygen-Release_1_8_14/
    make

and then use `doxygen_build/bin/doxygen`

**Comment by mosra** [comment]
Well, that's always the possibility, if everything else fails, but I'm not really a fan of that solution. It adds extra time to each build and complicates the setup :(

I don't understand: if you already use Travis for building, why the generated binaries require a glibc that's *not* on Travis? 

Sorry for being so pushy here, but one thing I really liked about prebuilt Doxygen binaries was that one could just download them and they would run anywhere -- which, in my opinion, is covering exactly the case where one is stuck an old distribution and needs to have latest Doxygen. And this is unfortunately not possible since 1.8.14.

**Comment by jwakely** [comment]
@albert-github 

> as in that case I would also expect an undefined on CXXABI 1.3.9,

No, not necessarily. If none of the new symbols using the CXXABI symbol versions are used you won't necessarily get a dependency on that symbol version.

>  so it might even be a version between 4.9.0 and 5.1.0.

No, because they all have the same versions as 4.9.0

**Comment by Croydon** [comment]
```
After some tweaking I managed to create a fully static version of libclang and build doxygen against that. I made a binary package available here for testing purposes: http://ftp.stack.nl/pub/users/dimitri/test/doxygen-1.8.14.static_clang.linux.bin.tar.gz

The relevant LLVM/clang cmake build options:

    LIBCLANG_BUILD_STATIC:BOOL=ON
    BUILD_SHARED_LIBS:BOOL=OFF
    LLVM_ENABLE_PIC:BOOL=OFF
    LLVM_BUILD_LLVM_DYLIB:BOOL=OFF
    LLVM_BUILD_LLVM_C_DYLIB:BOOL=OFF

```

@doxygen Did these changes land in master already? If not could you please provide the changes in the doxygen build script somewhere?

I'm [packaging doxygen](https://github.com/inexorgame/conan-doxygen) for the C/C++ package manager [Conan](https://conan.io) and we are still stuck with the 1.8.13 release because of the missing libclang binary.

**Comment by Croydon** [comment]
@doxygen To be more specific: I'm asking if doxygen is linking now statically against libclang via default.

**Comment by PiJ82** [comment]
@Croydon We had the same problem regarding conan. As a hack we copied the libclang.so in question into the same folder as the doxygen executable and used patchelf to add $ORIGIN to the rpath. This works well with the correct libc versions installed. 

However, for earlier versions this issue was the result.

**Comment by Gliptal** [comment]
> After some tweaking I managed to create a fully static version of libclang and build doxygen against that. I made a binary package available here for testing purposes: http://ftp.stack.nl/pub/users/dimitri/test/doxygen-1.8.14.static_clang.linux.bin.tar.gz
> 
> The relevant LLVM/clang cmake build options:
> 
> * LIBCLANG_BUILD_STATIC:BOOL=ON
> * BUILD_SHARED_LIBS:BOOL=OFF
> * LLVM_ENABLE_PIC:BOOL=OFF
> * LLVM_BUILD_LLVM_DYLIB:BOOL=OFF
> * LLVM_BUILD_LLVM_C_DYLIB:BOOL=OFF

ftp.stack.nl seems to be down, any chance for a reupload?

**Comment by albert-github** [comment]
For what it is worth try a google regarding doxygen-1.8.14.static_clang.linux.bin.tar.gz, I got a hit
- http://ftp.kaist.ac.kr/doxygen/test/

Note this is not a site maintained by doxygen so I'm not sure about the quality of it.

**Comment by albert-github** [comment]
I don't know (I don't create the packages), but maybe something is possible with the 1.8.15 release (scheduled for the end of this year).

**Comment by doxygen** [comment]
Indeed, libclang is statically linked in now.
