### ISSUE TITLE
[C++] enum class not properly associating first enumeration

### ISSUE THREAD

**Issue by jreben** [doxygen/doxygen#6414]
The issue is that when inline documenting a strongly typed enum in c++, the first enumeration is not being tagged with the correct scope in public types, and therefore I believe it is causing it's name to not show up in enum documentation. Due to this it causes it's value documentation to show up to the next enumeration 'Second'. 
This is being tested on Windows 10.
Noticed this in a much larger project on all enums used. I think 2. Here is minimal code that reproduces this issue.
![code](https://user-images.githubusercontent.com/13380463/43338718-e4ebe5d6-919c-11e8-81c2-49df6ec1baa9.png)
![documentation](https://user-images.githubusercontent.com/13380463/43338716-e49d7c34-919c-11e8-90e8-4cf9988b8d8c.png)

**Comment by albert-github** [comment]
Can you please attach a, small, self contained example (source+config file in a tar or zip) that allows us to reproduce the problem? (an image is a bit inconvenient for cut and paste).

Please specify also use doxygen version.

**Comment by jreben** [comment]
Doxygen Version = 1.8.14

[Issue 6414.zip](https://github.com/doxygen/doxygen/files/2236882/Issue.6414.zip)

**Comment by albert-github** [comment]
problem in this case is that the comment `/*! ` which is comment to be used **before** an item, here it is used is used as documentation **after** an item. Due to this the first item 'First' does not have documentation.
The code:
```
        enum class test{
                First,          /*! This is enumeration 1 */
                Second,         /*! This is enumeration 2 */
                Third,          /*! This is enumeration 3 */
                Fourth          /*! This is enumeration 4 */
        };

```
should be changed in
```
        enum class test{
                First,          /*!< This is enumeration 1 */
                Second,         /*!< This is enumeration 2 */
                Third,          /*!< This is enumeration 3 */
                Fourth          /*!< This is enumeration 4 */
        };
```

**Comment by jreben** [comment]
Oddly enough I was pretty sure I seen examples doing it just the default way. In any case this works. Thanks will close.
