### ISSUE TITLE
markdown: surpress explicit link request

### ISSUE THREAD

**Issue by TIS-Edgar** [doxygen/doxygen#6432]
Hi,

I am trying to document the steps other need to take to expand my documentation.
For this I am writing a markdown file that contains samples of the doxygen syntax.

```
Give the file a header with a unique id e.g. ` # New page {#new_page} `   
```
This gives me the following warning when generating html:  
    warning: explicit link request to 'new_page' could not be resolved

I tried `{\#new_page}` but the warning persists and the output is not formatted as I would expect i.e. the backslash is removed.

Am I overlooking something?

**Comment by albert-github** [comment]
Can you please attach a, small, self contained example (source+config file in a tar or zip) that allows us to reproduce the problem? 
Also specify the doxygen version you are using.

**Comment by albert-github** [comment]
A bit of a hard situation. Would `&zwj;`  i.e. zero width joiner (see manual chapter: "HTML commands", section about: "The special HTML4 character entities") be usable?

This would be:

```
Give the file a header with a unique id e.g. `# New page {#&zwj;new_page}`
```

**Comment by TIS-Edgar** [comment]
That seems to do the trick. I am not sure why it works, but i get no warnings and a correctly rendered page.

Thank you very much.

**Comment by abathur** [comment]
I realized while looking for a solution to a similar problem (different context; mine is trying to document comment syntax for a C-like language) that there have been a fair number of issues/reports/SO posts and questions on the mailing list, going back several years, that all seem to have a few things in common. 

Seeing them all made me think opening yet another issue might be counter-productive.

But it did make me wonder if it's common enough to benefit from sweeping everything into a meta/tracking issue or project so there's a single point-of-reference people can subscribe to for updates, link when we spot things that seem related elsewhere, find out whether it helps or just wastes time to report more examples, and so on.

**Comment by AlexisWilke** [comment]
I have a similar issue with a simple:

    `#define VERSION_MAJOR 1`

example, and I tried the usual backslashing, still getting the error. (Ubuntu 18.04, version 1.8.13)

**Comment by ferdymercury** [comment]
I am seeing a (kind of) similar problem when documenting C++ code.
```
///  use the following code structure: `ns::ns2::,,,::Template<...`
```
is there a way to suppress in this case the explicit link request warning to the unfound Template?

**Comment by albert-github** [comment]
@ferdymercury 

"similar kind" is a bit vague ...

Please create a new issue (as this issue is already closed and to keep the discussion clean). In the new issue follow the template, and be sure that you at least have, my standard questions answered:
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.
- Please also specify the **full** doxygen version used (`doxygen -v`).
