### ISSUE TITLE
Unable to install generated help plugin in Eclipse Photon (Windows)

### ISSUE THREAD

**Issue by cmorty** [doxygen/doxygen#6434]
I'm having trouble to install the generated eclipse help plugin into eclipse based on the instructions provided for GENERATE_ECLIPSEHELP. 
What I did: 
- Create a folder named like my ECLIPSE_DOC_ID in the plugins folder.
- Copy the contents of doc/html into that folder. 
- run `eclipsec.exe -consolelog -clean`
**Result:** The help does not show up, but I also do not see any error in the log.
- move the folder from plugins to dropins
- run `eclipsec.exe -consolelog -clean`
**Result**: <code>
org.eclipse.equinox.p2.core.ProvisionException: No repository found at file:/C:/Users/mstruebe/eclipse/cpp-photon/eclipse/dropins/de.test</code>

Am I doing something wrong or is this broken with current versions of eclipse?

See also: https://stackoverflow.com/questions/51067001/how-to-install-eclipse-help-plug-in-generated-by-doxygen

**Comment by albert-github** [comment]
According to the referenced post:
- And the folder must also contain a META-INF/MANIFEST.MF file. Is this file present?
- is the setting of the setting of `ECLIPSE_DOC_ID` correct?
From the documentation:

```
# A unique identifier for the Eclipse help plugin. When installing the plugin
# the directory name containing the HTML and XML files should also have this
# name. Each documentation set should have its own identifier.
# The default value is: org.doxygen.Project.
```
