### ISSUE TITLE
Cannot Generate Layout File using -l

### ISSUE THREAD

**Issue by anirocks99** [doxygen/doxygen#6450]
As of Doxygen Version 1.8.15, I cannot use doxygen -l to create a generic xml layout file.

**Comment by albert-github** [comment]
Strange, works for me on Windows but not on Cygwin.
Workaround:
- create Doxyfile, `doxygen -g`
- run `doxygen -l `

**Comment by anirocks99** [comment]
Thanks for the help!

**Comment by albert-github** [comment]
Please reopen the issue, problem has to be fixed (probably tomorrow I'll have a fix).

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6451

**Comment by albert-github** [comment]
Code has been integrated in master on github.
