### ISSUE TITLE
Using # in links causes errors in PDF generation

### ISSUE THREAD

**Issue by promm1983** [doxygen/doxygen#6456]
The error is:
"Illegal parameter number in definition of Hy@tempa"

link example:
\[Doxygen Special Commands: \\ref](http://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdref) 
or
\<a href="http://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdref"\>Doxygen Special Commands: \\ref\</a\>

this happens especially if used inside of table.
I tried to escape # character by \ (as suggested in article: https://kba49.wordpress.com/2013/04/12/illegal-parameter-number-in-definition-of-hytempa/ ) and then pdf generation is working fine, unfortunately HTML output doesn't see escape and generate link is:

http://www.stack.nl/~dimitri/doxygen/manual/commands.html/#cmdref

which is incorrect.

**Comment by albert-github** [comment]
Can you please attach a, small, self contained example (source+config file in a tar or zip) that allows us to reproduce the problem?
Please also specify the doxygen version used.

**Comment by albert-github** [comment]
Just the source code of the example so we can straight away run it, not just a description. The example should contain, in this case, the working and the non working example.
You also mentioned: "his happens especially if used inside of table" so please have the example show this behavior as well.

**Comment by promm1983** [comment]
Everything is in attachment (both source and output). There are 4 folders:
DoxygenTest - source where PDF is not generating
DoxygenTest2 - source where PDF is generating 
DoxygenTestOutput - output for test 1 (go to the latex and find output.txt - this is log for generating PDF)
DoxygenTest2Output - output for test 2 (go to the html page and check link in example

**Comment by albert-github** [comment]
Sorry I missed the attachment.
Examples give a way to proceed.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6460

**Comment by promm1983** [comment]
I build it and run. 
Works for me, thanks. 
Will it be merged to master ?

**Comment by albert-github** [comment]
Code has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
