### ISSUE TITLE
Does not generate TOC for markdown

### ISSUE THREAD

**Issue by jgzhuang** [doxygen/doxygen#6513]
I tried with latest Doxygen to generate document from markdown file. The markdown file looks like:
<pre>
[TOC]
# Head1
## Head2 
</pre>
The Head1 and Head2 are formatted correctly: &lt;h1> and &lt;h2>. But no TOC is generated. 

If it is @section and @subsection then it works well. 

It looks like in commentscan.l, function parseCommentBlock(), when Doxygen::markdownSupport is true, it calls processMarkdown() which adds those auto tags into Doxygen::sectionDict. This is good. 
But when it runs to commentscanYYlex(), in addSection(), it tries to find the section first:
SectionInfo *si = Doxygen::sectionDict->find(g_sectionLabel); 
if si is found, it writes an warning message. In this case the section label already exists, which affects the TOC building (I did not dig further).

**Comment by albert-github** [comment]
The problem here is that a markdown header by default doesn't have an id attribute attached to it, this is possible by means of an extension (see paragraph "Header Id Attributes" of "Markdown Extension" in the chapter "Markdown").

When using:
```
[TOC]
# Head1 {#H1}
## Head2 {#H2}
```

the required header appears, this should be made clear in the documentation.

**Comment by albert-github** [comment]
I've just pushed a proposed patch with a small documentation update, pull request #6415

**Comment by jgzhuang** [comment]
Thank you for the reply Albert. I guess you meant the PR #6515 . That makes it clearer. Previously I did not realize that I need add the ID attribute.
I can confirm that with the ID attribute in the header, the TOC generation works and those headers without the ID attribute does not appear in the TOC.  
Is it common to have ID attribute for the headers in markdown files outside Doxygen? 
If not, is it possible to make it work without the ID attribute?

**Comment by jgzhuang** [comment]
In my test I did have 
TOC_INCLUDE_HEADINGS = 3

But without the ID attribute, it does not appear in the TOC. 
I got warnings like:
warning: multiple use of section label 'autotoc_md0' while adding section, (first occurrence: <filename>, line 1)
warning: multiple use of section label 'autotoc_md1' while adding section, (first occurrence: <filename>, line 1)
warning: multiple use of section label 'Head11' while adding section, (first occurrence: <filename>, line 1)
warning: multiple use of section label 'Head21' while adding section, (first occurrence: <filename>, line 1)

The markdown file looks like:

[TOC]

\# Head1 
\#\# Head2 
\# Head11 {#Head11}
\#\# Head21 {#Head21}

**Comment by albert-github** [comment]
In version 1.8.14 I don't see the problem, in the current master I see some problems as well, have to investigate...

**Comment by jgzhuang** [comment]
Oh cool. Yes I tried 1.8.14 and it seems working. 
Probably this was introduced by fixing 792122, i.e. 5bae9d9 ?

**Comment by albert-github** [comment]
Most likely. The markdown support has been placed on a more logical point, but  some code is now double. I'm testing some possibilities.

**Comment by jgzhuang** [comment]
Thanks for the quick turnaround! I just gave it a try and it works nicely as there is no "conflict" when running commentscanYYlex()  since the labels were not added in processMarkdown().

**Comment by albert-github** [comment]
Code of pull request #6516 has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
