### ISSUE TITLE
Markdown formats missing in doxygen outputs.

### ISSUE THREAD

**Issue by Slyware** [doxygen/doxygen#6524]
Hi.

The ouputs files (html, rtf, ...) don't interpret ==highlight== and ~~strikethrough~~ format tags nor html tags as <u>underline</u>. I know that they may not be in the official Markdown standard but they are largely used by a many Markdown editors or viewers _**like Github does!**_.
Unlike **bold** or *italic* format tags, the above tags are displayed as raw source text in the outputs.
Is there a way to add these tags in the Doxygen parser or to customise the preprocessor?
Thanks.
SJ

Doxygen version: 1.8.14

**Comment by albert-github** [comment]
In the current master version of doxygen some features should already be available. To see what you want can you please attach a, small, self contained example (source+config file in a tar or zip) that allows us to reproduce the problem?

**Comment by Slyware** [comment]
Hi.
Here is an example of MD source edited in Typora (with option "Highlitghing" checked).
Ok, I saw that some of these formats are Markdown extensions but they are commonly used and so usefull.
[SupportDoxygen.zip](https://github.com/doxygen/doxygen/files/2409878/SupportDoxygen.zip)
Typora rendering is here: ![image](https://user-images.githubusercontent.com/43435546/45940086-39006080-bfd7-11e8-8884-6f74168dee45.png)
Thanks a lot.
SJ

**Comment by albert-github** [comment]
Code has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
