### ISSUE TITLE
Sqlite db problem on win10/msys2

### ISSUE THREAD

**Issue by Compyx** [doxygen/doxygen#6526]
When running doxygen on my codebase in msys2 on Windows, I get an error message about an Sqlite3 "query" failing:

```
Generating SQLITE3 output...
Initializing DB schema...
failed to execute query: CREATE TABLE IF NOT EXISTS includes (
        -- #include relations.
        rowid        INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
        local        INTEGER NOT NULL,
        id_src       INTEGER NOT NULL,  -- File id of the includer.
        id_dst       INTEGER NOT NULL   -- File id of the includee.
);
CREATE UNIQUE INDEX idx_includes ON includes
        (local, id_src, id_dst);
        index idx_includes already exists
Running dot...
lookup cache used 2365/65536 hits=20092 misses=2380
finished...
```

This happens with doxygen 1.8.14 installed in msys2 via the Pacman package manager. Using the same on Linux, with doxygen 1.8.13, stuff works fine. (Ubuntu, but Debian also has no problems).

It doesn't appear to actually impact the output of doyxgen, but I'd still rather not see this error message.

**Comment by the78mole** [comment]
Das Problem taucht auch bei mir auf, trotz der Installation folgender Pakete:
sqlite, libsqlite, libsqlite-devel

**Comment by albert-github** [comment]
@the78mole This is an English issues site, so German is not understood.

**Comment by doxygen** [comment]
I expect this issue to be fixed by this commit: https://github.com/doxygen/doxygen/commit/1743f2717fbcb81472a29e4cac0d2fb018e7f5fa

Before this commit there was a check and if the database file was already there. If not an error message was produced, but then the database was still used. Now it skips the rest of the sqlite processing.

**Comment by albert-github** [comment]
Seen the comment, I think the problem has been solved in the mean time
