### ISSUE TITLE
Custom Header Issues

### ISSUE THREAD

**Issue by jajohnsonpro** [doxygen/doxygen#6527]
Applying a custom header results in doxygen not generating the jquery script inclusion reference.

**Comment by albert-github** [comment]
The description is a bit vague to reproduce. Can you please attach a, small, self contained example (source+config file in a tar or zip) that allows us to reproduce the problem?
Please also specify the doxygen version used.

**Comment by kenyeby** [comment]
I use 1.8.4 version, where to upload the zip file you need.

**Comment by jajohnsonpro** [comment]
Version 1.8.14. Note that after putting head information in the header.html it slightly worked with a few issues, but in the example i attached its commented out
. I'm assuming with custom headers this is the intended path to go? In any case i have attached the requested material.
[DoxyGen.zip](https://github.com/doxygen/doxygen/files/2430879/DoxyGen.zip)
![capture](https://user-images.githubusercontent.com/23225418/46248538-207db500-c3e0-11e8-8f09-320585cfc594.PNG)

**Comment by jajohnsonpro** [comment]
> Version 1.8.14. Note that after putting head information in the header.html it slightly worked with a few issues, but in the example i attached its commented out
> . I'm assuming with custom headers this is the intended path to go? In any case i have attached the requested material.
> [DoxyGen.zip](https://github.com/doxygen/doxygen/files/2430879/DoxyGen.zip)
> ![capture](https://user-images.githubusercontent.com/23225418/46248538-207db500-c3e0-11e8-8f09-320585cfc594.PNG)

After navigating to another page of doxygen it breaks again. I'm assuming possibly at some point in time the jquery script is being left out in the case of custom headers?

**Comment by albert-github** [comment]
I have problems generating the documentation with the data you provided. When trying to view the provided documentation it looks like:
![output](https://user-images.githubusercontent.com/5223533/46248679-bfc09d80-c41c-11e8-9f5c-657a63c7a04a.jpg)

When looking in the provided `header.html` file, this file does not look valid for doxygen to me as only just a part is taken from the header and modified, but e.g. the head is missing. Also the `<div id="top"><!-- do not remove this div, it is closed by doxygen! -->` is missing so an inconsistency exists in number of `<div>`'s.

Please check and correct the `header.html`

**Comment by jajohnsonpro** [comment]
Wait I don't quite understand so i should put a floating div with a missing closing tag in the header.html? Also shouldn't I allow doxygen to generate the head?

**Comment by albert-github** [comment]
Your `header.html` is replacing the default header of doxygen, see for the default header: `doxygen -w html headerFile footerFile styleSheetFile [configFile]`

**Comment by jajohnsonpro** [comment]
Oh i see so any custom header should include the default doxygen head and we should work from the default template. I should read more. Thanks for your time.
