### ISSUE TITLE
pdflatex: parameter table reaches into footer

### ISSUE THREAD

**Issue by mrbachmann** [doxygen/doxygen#6532]
Using doxygen 1.8.9.1 all parameter tables contain page-breaks such that they fit into the bodies of the pages.

In higher versions of doxygen (here: used the latest version 1.8.14) the page-break in parameter tables is sometimes missing, such that the table reaches into the footer of the page.

**Table reaches into the footer:**
<img width="676" alt="doxygen_pdflatex_issue_-_table_reaches_into_footer" src="https://user-images.githubusercontent.com/43732503/46263407-14dcdc00-c50f-11e8-9006-103349493fa8.png">

**Table contains a page break:**
<img width="676" alt="doxygen_pdflatex_issue_-_pagebreak_in_table" src="https://user-images.githubusercontent.com/43732503/46263408-14dcdc00-c50f-11e8-8410-c2590d377d2c.png">

The zip archive contains the doxygen output generated for a header which demonstrates the issue:

[doxygen_pdflatex_issue.zip](https://github.com/doxygen/doxygen/files/2432117/doxygen_pdflatex_issue.zip)

**Comment by ECOM-Klaus** [comment]
I have the same problem

**Comment by albert-github** [comment]
@ECOM-Klaus please give some more information at least the used doxygen version would be nice (and when not using the latest doxygen version, 1.8.16) also try this version.

**Comment by ECOM-Klaus** [comment]
Thanks for your swift response!
I use 1.8.13-10 on Ubuntu Linux 32bit. PDF generated with pdflatex.
apt-get upgrade doxygen tells me, this is newest...
I will try compiling the newest doxygen version asap.

**Comment by ECOM-Klaus** [comment]
Version 1.8.17 on 32bit linux: Problem persists: Table goes in footer.

**Comment by albert-github** [comment]
I assume you mean the current master that identifies itself with 1.8.17.

**Comment by ECOM-Klaus** [comment]
Yes

**Comment by ECOM-Klaus** [comment]
looks like this:

[Tab-in-footer.pdf](https://github.com/doxygen/doxygen/files/3784723/Tab-in-footer.pdf)

**Comment by bryan-hunt** [comment]
I'm seeing this in 1.8.18 on windows as well. Some tables break at the footer properly, some don't.

**Comment by jreybert** [comment]
I am actually struggling with the same issue, table crossing the footer, or even going outside of the bottom of the page.

This issue has not been updated since 2020. Is there anything possible to workaround this issue?

**Comment by albert-github** [comment]
As far as I know there is no workaround possible other than manually inserting pagebreaks and the like.

**Comment by jreybert** [comment]
Tell me if I am wrong, but longtable/tabu is used to split long tables across pages. If I don't care about splitting the tables, do I have any chance to not use the longtable/tabu pacakges? Which command(s) should I redefine to do so?

**Comment by albert-github** [comment]
I see you already did some digging and most of the following information will be known to you.

In the doxygen `templates/latex`  directory there is the `doxygen.sty` (which is carried over to the latex output directory as a user sees it) that creates some new environments that use the `longtabu`.
In the doxygen `src` directory there is the file `latexdocvisitor.cpp` that uses the `tabularx` and `longtabu` environments.

Note doxygen ships with its own versions of some standard latex files as the current `tabu` package is not maintained anymore and cannot run with the current versions of latex.

For this reason I've been looking into replacing the `tabu` package by the [tabularray](https://github.com/lvjr/tabularray) package but it is all in all a very complex business to do it  and I didn't find an easy way to do it.


In the pas the `TabulaC` and `TabularNc` environments have been used for some nesting of tables but this had some drawbacks as well (looks like the reset in doxygen.sty of these 2 environments is obsolete (unless they are used somewhere deep down in latex packages)

**Comment by jreybert** [comment]
Thanks for the clarification.

We already redefine some commands and environments to match our company template (BTW I will try to propose some merge requests to make these customization available without having to redefine these commands/environments].

I was hoping that tabular environment would be wrapped in something like `DoxyTabular`, and then it would have been possible to redefine this environment in our `header.tex`.

* Is it something you plan to do in a near future?
* If not, if we propose such modification, would you consider this to be merged?

**Comment by albert-github** [comment]
> I was hoping that tabular environment would be wrapped in something like `DoxyTabular`

Do you mean here the part in the latexdocvisitor.cpp?

**Comment by jreybert** [comment]
Yes.

https://github.com/doxygen/doxygen/blob/69c4eee1a45125a4b42356c63e2cf00e7366884c/src/latexdocvisitor.cpp#L1158C1-L1158C93

I think this kind of snippet
`"\\tabulinesep=1mm\n\\begin{longtabu}spread 0pt [c]{*{" << cols << "}{|X[-1]}|}`

Could be an environment defined in `doxygen.sty`. And then could be redefined.

What do you think?

**Comment by albert-github** [comment]
I think there could /should indeed be 2 environments defined here (one for the tabularx and one for the longtabu part)  and this would certainly be better for the reason you mentioned.

**Comment by albert-github** [comment]
- Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).
(Issue was closed automatically by GitHub due to the used terminology in the pull request)

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.11.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
