### ISSUE TITLE
doxygen.org website is offline

### ISSUE THREAD

**Issue by smokris** [doxygen/doxygen#6540]
`README.md`, `footer.html`, and several other files in this repo link to http://www.doxygen.org/, but that website is offline.

doxygen.org specifies the following nameservers:

    NS0.TRANSIP.NL
    NS1.TRANSIP.NET
    NS2.TRANSIP.EU

…but those nameservers don't report any results for that domain:

    $ dig doxygen.org @ns0.transip.nl
    ;; ->>HEADER<<- opcode: QUERY, status: REFUSED, id: 22431
    $ dig doxygen.org @ns0.transip.net
    ;; ->>HEADER<<- opcode: QUERY, status: REFUSED, id: 11393
    $ dig doxygen.org @ns0.transip.eu
    ;; ->>HEADER<<- opcode: QUERY, status: REFUSED, id: 48785

Is that domain permanently offline (and should the links thus be changed to http://doxygen.nl/), or is this a temporary issue?

**Comment by doxygen** [comment]
It should be a temporary thing. The domain moved to a different ISP (same that hosts doxygen.nl), but apparently something went wrong in the process. I already filed a ticket.

**Comment by albert-github** [comment]
This morning I could reach doxygen.org again.

**Comment by smokris** [comment]
Same here.  Thanks for taking care of this.
