### ISSUE TITLE
A file that doxygen cannot parse but still would like to document it

### ISSUE THREAD

**Issue by zardilior** [doxygen/doxygen#6541]
If you have a file that doxygen cannot parse but still would like to document it, you can show it as-is using `\verbinclude`, e.g.

```
/*! \file myscript.sh
 *  Look at this nice script:
 *  \verbinclude myscript.sh
 */
```
Make sure that the script is explicitly listed in the `INPUT` or that `FILE_PATTERNS` includes the `.sh` extension and the the script can be found in the path set via `EXAMPLE_PATH`.

Testing this within an `.sh` file, fails

**Comment by albert-github** [comment]
Probably you need the `EXTENSION_MAPPING` set in this case.

Can you please attach a, small, self contained example (source+config file in a tar or zip) that allows us to reproduce the problem?
Please also specify the doxygen version used.
