### ISSUE TITLE
Call graph missing due to ALIASES

### ISSUE THREAD

**Issue by Fr1337ddy** [doxygen/doxygen#6547]
I have a function Process1 for which I want to generate a call graph:

	/**
	********************************************************************************
	\file             test.c
	********************************************************************************
	*/

	/* function prototypes */
	void Process1(void);
	void init_function1 (void);
	void function1 (void);
	void function2 (void);

	/**
	********************************************************************************
	\project		  projectx
	\funcname		  Process1
	\details          Aufruf von Prozess 1
					  \callgraph
	********************************************************************************
	*/
	void Process1 (void)
	{
		init_function1();
			for (;;)
		{
			function1();
			function2();
		}
	}

	/**
	********************************************************************************
	\details          Aufruf von Init Funktion 1
	********************************************************************************
	*/
	void init_function1 (void)
	{
		;
	}

	/**
	********************************************************************************
	\details          Aufruf von Funktion 1
	********************************************************************************
	*/
	void function1 (void)
	{
		;
	}

	/**
	********************************************************************************
	\details          Aufruf von Funktion 2
	********************************************************************************
	*/
	void function2 (void)
	{
		;
	}

The keywords `\project` and `\funcname` are ALIASES defined in Doxygen GUI 1.8.14 (Windows 7) to get a similar format like e.g. `\author` The definition is like that:

    funcname=\par Name ^^
    project=\par Project ^^

My problem is that if I use the ALIASES there is no callgraph. If I do not use the ALIASES (remove them in source code) there is a callgraph. How can I fix this issue?

Source code and Doxyfile is uploaded here:
[Doxygen_Testprojekt.zip](https://github.com/doxygen/doxygen/files/2464383/Doxygen_Testprojekt.zip)

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6548

**Comment by Fr1337ddy** [comment]
Thank you for dealing with this issue so fast. Could you please provide the binaries for Windows (self-installing archive) including your fix?

**Comment by albert-github** [comment]
The fix has not been merged into master yet, it is a proposed patch.
I don't make packages so this is not feasible for me.
Best is to take the maser source tree and apply this change to it and compile this tree.

**Comment by albert-github** [comment]
Code has been integrated in master on github.

**Comment by Fr1337ddy** [comment]
Is there an .exe version of Doxygen (e.g. doxygen-1.8.14-setup.exe ) available including this fix or do I have to compile it by myself?

**Comment by albert-github** [comment]
There is no exec version available (as for as I know), you have to compile yourself.

**Comment by albert-github** [comment]
Update / regression code has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
