### ISSUE TITLE
feedback about PR #577 (new Doxyfile option: MODIFY_SPECIAL_CHARS)?

### ISSUE THREAD

**Issue by joenio** [doxygen/doxygen#6557]
I would appreciate feedback on Pull-Request https://github.com/doxygen/doxygen/pull/577, thanks.

**Comment by albert-github** [comment]
When having questions about a pull request / issue don't create a new isue but add a comment to the original pull request / issue.

**Comment by joenio** [comment]
The PR was opened 1 year and 4 months ago without no feedback, I've added comments there, more than one, without any response of you til now. I know you don't have any compromise with that but I really need any feedback about that PR.

**Comment by albert-github** [comment]
Closing as question has been reformulated at the pull request.
