### ISSUE TITLE
Duplicate class attribute in markdown table

### ISSUE THREAD

**Issue by MarkShackman** [doxygen/doxygen#6559]
In 1.8.14 (not 1.8.13), markdown table rows are generated with two 'class' statements; this is incorrect as it causes a SAXParseException when incorporated into Eclipse help.

For example, the HTML output is:
```
<table class="markdownTable">
. . . 
<tr class="markdownTableBody" class="markdownTableRowOdd">
<td> . . . </td></tr>
<tr class="markdownTableBody" class="markdownTableRowEven">
. . .
```

**Comment by albert-github** [comment]
Can you please attach a, small, self contained example (source+config file in a tar or zip) that allows us to reproduce the problem?

**Comment by MarkShackman** [comment]
Uses an unedited out-of-the-box Doxyfile.
[bug-report #6559.zip](https://github.com/doxygen/doxygen/files/2482812/bug-report.6559.zip)
Error on lines 72 & 784 of output file 'md_bug-report.html'

**Comment by albert-github** [comment]
Checked with 1.8.14 and on the lines 72 & 74 there is the double class.
In the current master the double class is gone:
```
<table class="markdownTable">
<tr class="markdownTableHead">
<th class="markdownTableHeadNone">Heading 1  </th><th class="markdownTableHeadNone">Heading 2   </th></tr>
<tr class="markdownTableRowOdd">
<td class="markdownTableBodyNone">Col1Row1  </td><td class="markdownTableBodyNone">Col2Row1   </td></tr>
<tr class="markdownTableRowEven">
<td class="markdownTableBodyNone">Col1Row2  </td><td class="markdownTableBodyNone">Col2Row2   </td></tr>
</table>
```

Problem has been fixed but not yet released (by the pull request in the earlier mentioned pull request).
Closing issue as duplicate.

**Comment by MarkShackman** [comment]
OK, thanks. 
When will 1.8.15 be released (the website docs already show this version)? (Releases used to be every few months; now it's annually and you must have dozens of duplicates reported.)

**Comment by albert-github** [comment]
I have no knowledge when the next release will take place.

**Comment by doxygen** [comment]
I have plans to make a new release somewhere between Christmas and the New Year.
