### ISSUE TITLE
Code text in manual too faint to see

### ISSUE THREAD

**Issue by lostbits** [doxygen/doxygen#6576]
Could the code examples in the manual be made darker (more distinct). In order for me to read them I copy them to an editor. They are too faint to see in the manual

**Comment by albert-github** [comment]
I never saw a problem like it.
- Is it in the HTML version or in the pdf manual
- which version of the manual / doxygen
- please give an example where this happens in your case (image?).

**Comment by albert-github** [comment]
As no reaction for over 2 years and the meant phenomenon was not observed I think this issue can closed as incomplete.
