### ISSUE TITLE
using ingroup and anchor causes tests to disappear

### ISSUE THREAD

**Issue by calumblair** [doxygen/doxygen#6594]
[test_anchor_ingroup_bug.zip](https://github.com/doxygen/doxygen/files/2543443/test_anchor_ingroup_bug.zip)
MWE attached.
header file:
```
/**
* \defgroup group1 Group 1
*/

/** \ingroup group1 
(using addtogroup here fixes the problem)
*/
int f(int);
```
code file:
```
/**
\test f() should have behaviour 1
\anchor anchor_1
\test f() should have behaviour 2
*/
int f(int)
{
	return 0;
}
```
Observed behaviour in the test list:
```
Member f (int)

    f() should have behaviour 1 
```
Expected behaviour:
```
Member f (int)

    f() should have behaviour 1 
    f() should have behaviour 2
```
I think this is specific to ingroup - If I use addtogroup the bug does not appear.
This is present in 1.8.14 and master.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6595

**Comment by albert-github** [comment]
Code has been integrated in master on github.
