### ISSUE TITLE
tparam HTML gobbles up lines after the tparam comment

### ISSUE THREAD

**Issue by LossMentality** [doxygen/doxygen#6601]
This is for doxygen generating HTML, C++, 1.8.6 on Ubuntu. I have the problem described below when viewing the HTML in both an older version of Firefox and an up-to-date Chrome browser.

I've got a standard doxygen comment block that heads up every class. I like to use:

`/// -----------------------------`

(which translates to a solid line in when looking at HTML) to divide sections of the comments.

Something like this:

`///@brief Some brief description.`
`///`
`/// Some detailed description.`
`///`
`/// ------------------------------------`
`/// @tparam T `
`/// Some template type comment.`
`///`
`/// ------------------------------------`
`/// <b> Exception Guarantees Made By This Class </b><br>`
`/// Discussion of guarantees.`

With the `tparam` section used only for class templates. Note that I always put my `tparam` comments on the line after the `@tparam` and the parameter name (do the same for `@params` for functions), but that doesn't seem to be the cause of the following issue.

When the `tparam` section is there, I get wonky HTML, with the generation looking like this:
![image](https://user-images.githubusercontent.com/25070218/48025241-d4c1d800-e110-11e8-90e4-a9359c5b44d7.png)
(basically, the final Exception Guarantees section gets pulled up into the template parameter comments).

This can be fixed by adding an **extra blank line** before the exception guarantees section:
`///@brief Some brief class description.`
`///`
`/// Some detailed class description.`
`///`
`/// ------------------------------------`
`///@tparam T `
`/// Some template type comment.`
`///`
**`///`**
`/// ------------------------------------`
`/// <b> Exception Guarantees Made By This Class </b><br>`
`/// Discussion of guarantees.`

![image](https://user-images.githubusercontent.com/25070218/48025312-0c308480-e111-11e8-9c09-6714a9a89164.png)

But I'd rather not have to add extra blank lines. The problem also goes away if I remove the "-----------" separator from before the "Exception Guarantees..." line, but I obviously would like to use this.

Here is a complete example that should recreate the problem.
`///@brief Some brief description.`
`///`
`/// Some detailed description.`
`///`
`/// ------------------------------------`
`///@tparam T `
`/// Some template type comment.`
`///`
`/// ------------------------------------`
`/// <b> Exception Guarantees Made By This Class </b><br>`
`/// Discussion of guarantees.`
`template <typename T>`
`class MyTest`
`{`
`};`

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6603

**Comment by LossMentality** [comment]
Great! Thank you!

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
