### ISSUE TITLE
doxygen cannot parse C99 source from open62541 project

### ISSUE THREAD

**Issue by stephanecharette** [doxygen/doxygen#6618]
The open62541 project combines all their source files into a single .c and .h file for other people to use in their code.  I attempted to run doxygen against this large .c and .h file, but while doxygen runs and finds the structures, it seems to fail to extract most (all?) functions.

Project source:  see https://github.com/open62541/open62541/releases which has a link to these 2 source files:

https://github.com/open62541/open62541/releases/download/0.3-rc2/open62541.c
https://github.com/open62541/open62541/releases/download/0.3-rc2/open62541.h

Steps to repro:

1) Downloaded both of those source files into an empty directory.
2) Run "doxygen -g".
3) Change INPUT= to point to the current directory with the two problematic source files.
4) Run "doxygen"
5) Open html/index.html in a browser
6) Search for any of the following basic functions in the doxygen output:
    - UA_Client_new()
    - UA_Client_connect()
    - UA_Client_delete()
    - UA_Client_readValueAttribute()
    - UA_Server_new()
    - UA_Server_run()
    - UA_Server_delete()
    - UA_ServerConfig_delete()

I tried for several hours to tweak both the Doxyfile and make changes to the open62541 source files to see if I can figure out what is preventing Doxygen from discovering the function names, but have failed to find the cause.

(I'm on Ubuntu 18.10, using Doxygen v1.8.13-10ubuntu1.)

**Comment by albert-github** [comment]
When selecting all `EXTRACT_...` possibilities I can see the functions, but this is of course just a work around.
The source is extremely large, can you please attach a, small, self contained example (source+config file in a tar or zip) that allows us to reproduce the problem?

Just a small remark:
- In the documentation I see constructs like: `:ref:` in the following update of doxygen this will lead to some problems as this will be seen as an emoji that doesn't exist. Probably a better solution would be to use the `\ref` construct or, when the next release of doxygen (1.8.15) is out to use `\:ref\:`.
- quite a few items are not documented(yet).

**Comment by stephanecharette** [comment]
I don't work on that project, I'm simply trying to use it and wanted to run doxygen against it.  So I'm not the person to contact to ask about them changing their source code.  I assume things like `:ref:` is for another tool they use to generate their documentation, so no, I don't think they'd change it and break their documentation just so Doxygen doesn't think it is an emoji.

**Comment by albert-github** [comment]
I had a look at the code.and there are 2 main points that I found:
- would be better if the `.h` file was documented as well but just `/** \file */` at the beginning will do a lot
- the usage of the documentation start is not always done according to what doxygen needs, i.e there are `/**` to document groups and for the routines themselves there is only a `/*` comment instead of a `/**` comment.

My conclusion is that there is no doxygen bug but that it is usage / the chosen documentation style of the project.

**Comment by stephanecharette** [comment]
> My conclusion is that there is no doxygen bug but that it is usage / the chosen documentation style of the project.

What are you talking about?  The project doesn't use Doxygen.  It is C source code.  Shouldn't Doxygen parse the C source code?

**Comment by albert-github** [comment]
Doxygen does parse the source code and when the right configuration parameters are set, `EXTRACT_...` or `/** \file */` is added to the `.h` file, there is output following the comments in the files.
