### ISSUE TITLE
Error in link to classes from external tagfile when generating HTML

### ISSUE THREAD

**Issue by MarkusEischeid** [doxygen/doxygen#6625]
I have an error in the generated HTML:
`<td class="entry"><span style="width:16px;display:inline-block;">&nbsp;</span><span class="icona"><span class="icon">C</span></span><a class="elRef" doxygen="C:/xampp/htdocs/doc2/out/a/a.tag:a1/" href="a1/class_a.htmlA&lt;/a&gt;&nbsp;[external]&lt;/td&gt;&lt;td class=" desc"=""></a></td>`

![doxy](https://user-images.githubusercontent.com/40861497/48710272-115cfb80-ec08-11e8-91dd-6d0f3eb51f7c.jpg)

I think the href to the external class is wrong.
I included the classes with `TAGFILES = "out/a/a.tag=a1`" and set `ALLEXTERNALS = YES`.

**Comment by albert-github** [comment]
Which version of doxygen are you using?

Can you please attach a, small, self contained example (source+config file in a tar or zip) that allows us to reproduce the problem?

**Comment by MarkusEischeid** [comment]
I'm using doxygen 1.8.14. Here is my sample:
[doc2.zip](https://github.com/doxygen/doxygen/files/2595522/doc2.zip)

**Comment by albert-github** [comment]
Which file should I look into?

The procedure I followed so far (removed doxygen.bat as it interferes with my doxygen calls. I have doxygen in the path):
- cd a
- doxygen Doxyfile.config
- cd ..\b
- doxygen Doxyfile.config
- cd ..\combined
- doxygen Doxyfile.config

maybe you can include a description of what you see / include a smal picture of the place of the problem.

**Comment by MarkusEischeid** [comment]
Ok. I have two "projects" called A and B (in folders a and b). The docs for these projects are processed into /out/a and /out/b. 
Now i want to combine the docs for these two projects into one by using a third project called "combined" (folder combined). In the "combined" project i have a reference to the tag files of a and b. The error I mentioned is in the output for "combined" in /out/combined/html/annotated.html, lines 59 and 60.

**Comment by albert-github** [comment]
With version 1.8.14 I see the mentioned problems. With the current master the problems are gone (I do remember that there was fix for this):

![combined_master](https://user-images.githubusercontent.com/5223533/48714553-35720a00-ec13-11e8-880e-e42bca0da0c7.jpg)

So I think the problem has been fixed but is not yet released.

**Comment by MarkusEischeid** [comment]
Thanks a lot!

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
