### ISSUE TITLE
Code blocks incorrectly formatted in Latex

### ISSUE THREAD

**Issue by jfitter** [doxygen/doxygen#6631]
doxygen v1.8.14
Some parts of blocks of code are incorrectly formatted by Latex. It appears that the failure to escape the % symbol is part of the problem but fixing this manually does not yield completely correct formatting.
Some lines of code are wrapped even though they do not extend beyond the page margin. It has something to do with spaces before the \mbox and removing these stops the line wrapping but results in Latex then spacing the line contents to suit itself.
This is code and should reflect the original content. It does not and so pdf generation is off the menu for now until it is fixed.
The html output (and chm) is correctly formatted.
Attached is a sample output of one page of the generated pdf.
[page43.pdf](https://github.com/doxygen/doxygen/files/2603043/page43.pdf)
Lines 154, 157, 162, and 169 are the incorrectly formatted lines. Note they all have the un-escaped %s in them, but as stated, fixing this only fixes part of the problem.
I do not yet know enough Tex to figure out the solution.

**Comment by albert-github** [comment]
I did some quick tests based on the available code in the pdf-file (as I know a lot changed between 1.8.14 and the current master also for LaTeX output) and the results are (see attachment):
- with version 1.8.14 I saw on my lines 19 and 34 some artifacts
- with the current master version these artifacts, though on line 34 there is some extra space.

The later (minor) problem has to be looked into.

**Attachment** [results.zip](https://github.com/doxygen/doxygen/files/2603831/results.zip)

- Does this solve your major problems?
- You concluded "It appears that the failure to escape the % symbol is part of the problem". How did you come to this conclusion? When looking at my line 19 it does not contain a `%` sign and when replacing the `%` by a space on line 34 the same problem is present.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6632 to solve the minor problem mentioned before (extra space).

**Comment by jfitter** [comment]
> * You concluded "It appears that the failure to escape the % symbol is part of the problem". How did you come to this conclusion? When looking at my line 19 it does not contain a `%` sign and when replacing the `%` by a space on line 34 the same problem is present.

Sorry, I made an error. Initially it appeared that the % symbol was part of the problem because it occurred on every line that was improperly formatted. Later I found more lines like this but without the % symbol. I am using MikTex whose editor is somewhat smart. When it encountered the un-escaped % it grayed out the whole block surrounding the offender and then got very confused about brace and bracket matching. This, of course, looked like a problem but turned out to have no effect.

The other problem re spacing is something I am unable to solve, but it is a real problem.
Attached are the 2 tex files. If you need more please ask.

[diag.zip](https://github.com/doxygen/doxygen/files/2605610/diag.zip)

**Comment by jfitter** [comment]
This is curious.
Attached is a stripped down version of my project - cpp, h, and doxyfile. It produces correctly formatted output. It is a very basic script and has no diagrams or graphs or images, etc.
Included is doxyfile_original. This is the script for my entire project and includes graphs and diagrams. It does not produce correctly formatted output, as described previously.

[BTTest.zip](https://github.com/doxygen/doxygen/files/2605752/BTTest.zip)

**Comment by jfitter** [comment]
After more testing, graphs and diagrams do not matter. What DOES matter is the Latex output format selection. If selected "as intermediate format for hyperlinked PDF" then the code is incorrectly formated. If selected "as intermediate format for PDF" then the code is correctly formatted (but really hard to find...).

**Comment by albert-github** [comment]
I had to do a few small changes to the files you delivered:
- emptied the PROJECT_LOGO and INPUT 
- in the `.h` file: replaced
```  *  \file       BALBLUETOOTH.H```
with
```  *  \file```
- added as first line to of the `.cpp` file
```/** \file */```

all to get a bit more output.

*doxygen 1.8.14*
In the resulting PDF using adjusted `Doxyfile_original` I see a correct output when having `PDF_HYPERLINKS = NO` (you did this through the doxywizard). 
When using `PDF_HYPERLINKS = YES` I see  the problems at:
- `.h` file line 28
- `.cpp` (adjusted) line 5

*doxygen master with proposed patch #6634*
The problems a seen with doxygen 1.8.14 are gone.

*Questions*
- Did I overlook a problem ?
- (Note: please look at the question with #6630 as well or when this is the same problem as we have been discussing here just close it)

**Comment by jfitter** [comment]
Thanks for all the effort and feedback, I will now leave this in your capable hands. It's a good product getting better.
As for unescaped %, this seems to annoy TexStudio but appears to have no effect on the generated output.

**Comment by albert-github** [comment]
Please don't close this issue as the fix has not been integrated and released yet. After it is integrated and later on in the release it will be set to closed (so information can easily be in the release notes etc.).

Please reopen this issue.

**Comment by albert-github** [comment]
Code has been integrated in master on github.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
