### ISSUE TITLE
Does doxygen support \author command in C

### ISSUE THREAD

**Issue by bookug** [doxygen/doxygen#6651]
I think \author and \email command are both very useful, but for C program I do not know how to add them in doxygen :)

**Comment by albert-github** [comment]
I don't think this is a bug but usage. A better place to ask would be https://stackexchange.com and label it with doxygen.

```
/** \file */
/**
  * \author The Writer
  *
  * email: mailto:address@example.com or <mailto:address@example.com>
  * or address@example.com
  */
void fie(void);
/**
  * \author The Writer
  * (mailto:address@example.com) or (<mailto:address@example.com>)
  * or (address@example.com)
  */
void fie1(void);
```

See also the doxygen manual: http://www.doxygen.nl/ especially:
- http://www.doxygen.nl/manual/markdown.html section about "Automatic Linking"
- http://www.doxygen.nl/manual/commands.html#cmdauthor
