### ISSUE TITLE
HTTP and FTP Doxygen download server is down

### ISSUE THREAD

**Issue by ThadHouse** [doxygen/doxygen#6654]
We've noticed our CI failing over the past week, and have noticed this is caused by the doxygen website not working correctly, and the download links being broken. Both the FTP links and the HTTP links throw a 403 exception, as do some other links on the website.

http://www.stack.nl/~dimitri/doxygen/download.html

**Comment by albert-github** [comment]
The www.stack.nl address  has been disabled as stack.nl stopped the service.

Please use the address www.doxygen.org or www.doxygen.nl

The mentioned address would be: http://www.doxygen.org/download.html or http://www.doxygen.nl/download.html

**Comment by ThadHouse** [comment]
Ok, I'll try and PR the gradle plugin that still uses the old site.

Note some links on the website, like the bug download button at the top still point to the stack.nl site. So those should be changed if possible.

**Comment by PeterJohnson** [comment]
In addition, all of the actual links on the download page still point to stack.nl.

**Comment by albert-github** [comment]
@ThadHouse  and @PeterJohnson Thanks.

**Comment by doxygen** [comment]
@PeterJohnson I've corrected the broken links. Please let me know if I missed any.

**Comment by Croydon** [comment]
@doxygen somewhat related: did you consider open sourcing the website in a git repository as well? people might feel much more motivated to report e.g. broken links or creating a quick pull request

**Comment by MarkCallow** [comment]
Yes, please open source the web site. I'd love to figure out how it is doing some of the things it is doing. The apparent source in the current doxygen repo is not the complete source used for the web site.

**Comment by albert-github** [comment]
Most of the incorrect links are already fixed or will be fixed with the next release.

It is hard to open source the web site code as it is heavily intertwined with the release generation procedure,

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.3.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
