### ISSUE TITLE
Option SOURCE_BROWSER changes the call graph of filtered files

### ISSUE THREAD

**Issue by cgouttebroze** [doxygen/doxygen#6666]
My projects have *.c files that I filter in order to remove some calls.

For instance, for project with single file main.c
```
void foo() {};
void bar() {};

int main() {
  foo();
  bar(); 
  return 0;
}
```
has its call to bar() removed by the configuration option
`INPUT_FILTER           = "sed '6s,.*,,'"`

With this Doxyfile,
[Doxyfile.txt](https://github.com/doxygen/doxygen/files/2655926/Doxyfile.txt)
I get the expected call graph without the call to bar():
![good_cgraph](https://user-images.githubusercontent.com/266365/49628669-d3245200-f9e5-11e8-9125-f309fb31aca5.png)

When I change the value of SOURCE_BROWSER to NO, the call graph becomes wrong:
![bad_cgraph](https://user-images.githubusercontent.com/266365/49628883-00253480-f9e7-11e8-9374-8616f3eb177f.png)

**Comment by albert-github** [comment]
Looks like this is intended behavior.

To be able to show the relations the configuration tag `FILTER_SOURCE_FILES` exists:

>  If the FILTER_SOURCE_FILES tag is set to YES, the input filter (if set using INPUT_FILTER) will also be used to filter the input files that are used for producing the source files to browse (i.e. when SOURCE_BROWSER is set to YES).
> The default value is: NO.

By setting `FILTER_SOURCE_FILE=YES` I think the intended behavior is obtained, see also bug 707641 i.e. issue #5289 and source code in filedef.cpp

I think the problem is usage.

**Comment by cgouttebroze** [comment]
Indeed, setting FILTER_SOURCE_FILE = YES solves the issue. Thank you for the workaround.

However, the explanation about SOURCE_BROWSER are FILTER_SOURCE_FILE are quite misleading. I expected those options to have an effect only on the browsable source code. When reading documentation, I was far away to imagine they could impact the call graphs.
