### ISSUE TITLE
want a option to override result of Doxygen

### ISSUE THREAD

**Issue by bdvstg** [doxygen/doxygen#6678]
My project is using C++
I use a preprocessor macro to declare items of a enum
but doxygen can not detect it

the code snippet is show below

    // implement enum like this, only need maintain one list
    #define IT_LIST \
        ITEM( MY_ITEM_1 ) \
        ITEM( MY_ITEM_B ) \
        ITEM( MY_ITEM_C ) \
        ITEM( MY_ITEM_4 ) \
    
    enum class Item
    {
        ITEM_UNKNOWN = -1,
    
        #define ITEM( NAME ) ITEM_ ## NAME,
            IT_LIST
        #undef ITEM
    
        ITEM_COUNT,
    };

Doxygen only detected ITEM_UNKNOWN and ITEM_COUNT
ITEM_MY_ITEM_1, ITEM_MY_ITEM_B, ITEM_MY_ITEM_C, ITEM_MY_ITEM_4 is disappear
![enum](https://user-images.githubusercontent.com/16952781/49984100-70145b80-ffa1-11e8-8619-e1e92c48f39a.PNG)

and then, I add doxygen syntax comment `\var` to manually add the item that not detected (like below)
but it doesn't work

    /**
     * @enum Item
     * @brief Item enum
     * 
     * 
     * doxygen here can not detect
     * 
     * - ITEM_MY_ITEM_1
     * - ITEM_MY_ITEM_B
     * - ITEM_MY_ITEM_C
     * - ITEM_MY_ITEM_4  
     * 
     * only show below : (and indent of this line is wrong...)
     * 
     * - ITEM_UNKNOWN
     * - ITEM_COUNT
     * 
     * @var ITEM_UNKNOWN
     * Unknow Item
     * 
     * @var ITEM_MY_ITEM_1
     * MY_ITEM_1
     * 
     * @var ITEM_MY_ITEM_B
     * MY_ITEM_B
     * 
     * @var ITEM_MY_ITEM_C
     * MY_ITEM_C
     * 
     * @var ITEM_MY_ITEM_4
     * MY_ITEM_4
     * 
     * @var ITEM_COUNT
     * Number of Items
     * 
     */

I know doxygen does not contain compiler, so it can't parse complexity syntax

maybe add an option:
let doxygen use manually comment to override the result of detected
is a good ideal ?

or is there is any option/setting/usage able solve it?

my full run-able showcase project: [enum.zip](https://github.com/doxygen/doxygen/files/2678683/enum.zip)

the output html documents: [doc_doxygen.zip](https://github.com/doxygen/doxygen/files/2678745/doc_doxygen.zip)

**Comment by albert-github** [comment]
Regarding the `enum` there are multiple issue reports (so definitely needs some attention).

Regarding the remark:

> only show below : (and indent of this line is wrong...)

the  'indent part', I had a quicjk look with the current master version and here it looks like to be solved.

**Comment by albert-github** [comment]
I reread the question.

I think you need to use the configuration setting: `MACRO_EXPANSION        = YES` at that moment I do see the requested items.
Note also place the `#define` and `#undef` outside the `enum` definition for a better result.

I think the mentioned problem is usage.

**Comment by bdvstg** [comment]
I tried, and it works!
Thanks for your helping :)
I will take more time to study settings of doxyfile
Thank you very much again :-)

**Comment by albert-github** [comment]
Nothing  to be done. I've closed the issue.
