### ISSUE TITLE
Wrong dependency detection causes cycles in graph

### ISSUE THREAD

**Issue by lucjaulmes** [doxygen/doxygen#6688]
Running doxygen (with current master 43e67dce) on the following C++ file:

    template<typename T>
    class ns1::A {
    };

    template<typename T>
    class ns2::A : public ns1::A<T> {
    };

    template<typename U>
    class ns2::C : public ns2::A<U> {
    };

generates the following graph:

![self-inheritance graph](https://i.imgur.com/C7zmXSx.png)

The dependency detection is wrong, as the parent of `ns2::A<U>` isn't itself but `ns1::A<U>`.

Note that renaming the template parameter `U` to `T` is sufficient to fix the bug and generate the correct graph:
![correct graph](https://i.imgur.com/YktIJbd.png)

Interestingly, removing the namespace `ns1` breaks discovering `A<T>` as a parent for `ns2::A`, but i'm not sure that it is related. 

This cycle previously caused segfaults, which were reported and fixed in #6325.

**Comment by albert-github** [comment]
A bit of a late reaction.
I could not reproduce the first image with the 1.8.15 version.

When I use version 1.8.15 I get the inheritance and collaboration graphs:

![image](https://user-images.githubusercontent.com/5223533/131321693-491a86e4-cb83-450c-a7b6-ae690edd48a1.png)

![image](https://user-images.githubusercontent.com/5223533/131321732-9104004b-44d4-4c40-8e66-6ec5533d1a64.png)

![image](https://user-images.githubusercontent.com/5223533/131321801-cd375446-f620-4ba3-b2cd-d8d8145c616c.png)

When I use version 1.9.2 I get:

![image](https://user-images.githubusercontent.com/5223533/131321994-f9c478af-b87a-4216-b7a1-2cdd6ddd1b77.png)

![image](https://user-images.githubusercontent.com/5223533/131322041-272837ff-33be-4f08-8daf-b06f8329292e.png)

![image](https://user-images.githubusercontent.com/5223533/131322094-980fda66-eaf3-448c-8419-c98fa29e0b80.png)


Can you please check that the new images are correct and that the results are as you expect?

**Comment by lucjaulmes** [comment]
I believe this report was made before 1.8.15 came out. There’s [about 50 commits](https://github.com/doxygen/doxygen/compare/43e67dce8c164df469e725deb94db582d9cfc69b...Release_1_8_15) between the reported version and the one you tested.

Nonetheless the graphs and your example appear correct, so if you get the same with current latest release, you can consider this bug fixed 3 years ago.

**Comment by albert-github** [comment]
Thanks for the quick reaction.

Before I tested with the 1.8.15 release and now I tested with teh mentioned commit 43e67dce8c164df469e725deb94db582d9cfc69b and result in identical images.

When your comment regarding the:
> Nonetheless the graphs and your example appear correct, so if you get the same with current latest release, you can consider this bug fixed 3 years ago.

Is about the last 3 images shown (from the 1.9.2 version) I think the problem is solved in the mean time.

**Comment by lucjaulmes** [comment]
I have 1.9.1 on my system and managed to successfully build the original code that I simplified for this bug report. So I think this bug is no more indeed.
