### ISSUE TITLE
Unbounded memory usage due to a bug in \ref const matching (with bisect and repro case)

### ISSUE THREAD

**Issue by mosra** [doxygen/doxygen#6689]
As I noted in #6299, current Doxygen master was eating all available memory on my projects. I spent some hours bisecting the issue to a particular commit (and then tearing my project apart to a particular expression that caused it). The problem happens when one of the following lines is encountered:

```
@ref foo constant
@ref foo constructor
```

The target `foo` doesn't have to exist, the `const` prefix of the word after is important. Upon encountering this, Doxygen enters some allocation loop and hoards memory until killed. This is happening since 07ae32a61e779647bace1efdbf8d15b35871fcca (PR https://github.com/doxygen/doxygen/pull/6592 by @albert-github). 

Digging further, I remembered that I opened related issues back in 2014 (https://github.com/doxygen/doxygen/issues/5669) and January 2017 (https://github.com/doxygen/doxygen/issues/6141), which were fixed in ad5dfc39bee7a1b3de16f36bc3a20565aa6438fe and 04001c8926fb0f37dfcf284b3637b182125bba75. Hopefully these three commits in total provide enough information for you to reproduce and fix it.

- - -

Besides that, looking from the project maintenance and sustainability point-of-view -- I don't want to sound mean, but if the bugfixes happened *together* with extending the test suite with reproduction cases for given bug (especially since in *every* of my bugreports [I go the extra mile and provide a minimal repro case](https://github.com/doxygen/doxygen/issues/6299) that's *meant to be included as a test*), none of this would have happened.

I understand that this project has a large history, the codebase is *huge* and it's driven by the community in their spare time, but nevertheless I think enforcing a rule of not adding bugfixes without a corresponding regression test case would be a net win. Yes, it will slow down the development process, at least initially (speaking from experience), but in the long run you'll have more robust code and less new bugs appearing (also speaking from experience). This could also indirectly help solve issues like those described in #6404.

**Comment by doxygen** [comment]
I've made a commit that should fix this issue: https://github.com/doxygen/doxygen/commit/f30a5fa78d9460550c7e921e73e11087f90b7db3

I still have to think about a good test case to capture this and related issues. In this case it was an unfortunate case that the FILEMASK that was added to the pattern had a component that matched the empty string, which prevented the lexer to make any progress.

**Comment by mosra** [comment]
Sure, but I think having at least *some* regression test is better than having none (especially for this particular corner case where it seems that I'm one of the very few users hitting it, repeatedly). A bad test can be always improved later (together with verifying that code coverage was kept).

**Comment by doxygen** [comment]
Just added a test case for it, see https://github.com/doxygen/doxygen/commit/2b4257860046b3863b7c478d7f6ad5bdfcab757b. Even spotted a small regression :wink:

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Comment by mosra** [comment]
Thank you!
