### ISSUE TITLE
XML TOC generation is not backwards-compatible with 1.8.14

### ISSUE THREAD

**Issue by mosra** [doxygen/doxygen#6692]
Since #736, done by @albert-github, the `@tableofcontents` command accepts a selection of output formats for which the TOC should be present. The defaults are wrong, in my opinion, as they are not backwards compatible with 1.8.14. In https://github.com/doxygen/doxygen/pull/625 I added a placeholder, which made the `@tableofcontents` unconditionally exposed to the XML output, but with current version none of that is present in the output anymore, unless one explicitly changes all occurences to `@tableofcontents{xml}`.

This causes a few problems:

- projects using the stable 1.8.14 will see the TOC exposed in XML, but in order to make everything work the same way in the (upcoming) 1.8.15, everything has to be updated to say `@tableofcontents{xml}`
- updating everything to say `@tableofcontents{xml}` will make things work in 1.8.15, but break for people using 1:8.14, since they will see a stray `{xml}` text in their output

If the `@tableofcontents` alone would be treated as "add a TOC for all output formats" instead of current "add a TOC for no formats", the above problems would be solved. Besides that, it feels too verbose having to specify `{xml}` every time for users that have just the XML output and nothing else.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6694

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
