### ISSUE TITLE
Minus Minus  - Unexpected conversion

### ISSUE THREAD

**Issue by mjm2017** [doxygen/doxygen#6704]
This is an old issue that is coming up again. 
https://github.com/doxygen/doxygen/issues/4759

Out put of Doxygen is as follow : 
 for(i=360,i>=0,i−−) {
that -- is not correct.

**Comment by doxygen** [comment]
I cannot reproduce this. The linked to example is still ok. Inside text -- and --- are converted to &ndash; (&amp;ndash;) and &mdash; (&amp;mdash;) in code fragments not. Please attach a self contained example (source +config file) showing the problem.

**Comment by albert-github** [comment]
Unfortunately no further information provided, setting issue to incomplete.
