### ISSUE TITLE
'Definition at line' points to end of multiple-lined definition for Python

### ISSUE THREAD

**Issue by cgbahk** [doxygen/doxygen#6706]
doxygen version tested: 1.8.14 release & recent commit (200353a)

### Symptom of the bug
When a Doxygen HTML documentation generated from python project, in case of the multiple-lined function definition, Doxygen recognizes the function's definition line as the end, but not start (which has a `def` keyword and seems more intuitive), of the definition lines.

### Side-effect
I think this issue is quite severe as this bug yields an annoying side-effect.
As multi-lined function definition is recognized as the end, Doxygen says **a previous function references the multi-lined function although it never does**. And call & caller graphs all messed up.

### Snapshots
You can reproduce this issue in from [doxygen_issue_6706.tar.gz](https://github.com/doxygen/doxygen/files/2705436/doxygen_issue_6706.tar.gz). Of course you can check a Doxyfile used.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/34672141/50377174-a6b23c00-065b-11e9-9dff-7deaa58c8dbd.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/34672141/50377181-e37e3300-065b-11e9-824f-33a701f3c499.png">

### etc
Seems like this issue is python-version of #6226

**Comment by albert-github** [comment]
Would be better if the files reproducing the problem would be attached to this issue report (as e.g. a zip file), so everything is together and not in a possible vanishing / changing repository.

**Comment by cgbahk** [comment]
@albert-github Thanks for notice. I just updated the issue

**Comment by doxygen** [comment]
I've just commit a fix for this https://github.com/doxygen/doxygen/commit/babfc33370e28963f890a5f05355aa7778700ca6

**Comment by cgbahk** [comment]
Working well now! Many thanks!
(I would not close this issue as it seems there is a reason not to do so)

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
