### ISSUE TITLE
Question: Is Doxygen GPL-2.0-only or GPL-2.0-or-later?

### ISSUE THREAD

**Issue by Croydon** [doxygen/doxygen#6712]
From the GPL 2.0 license:

>  9. The Free Software Foundation may publish revised and/or new versions of the General Public License from time to time. Such new versions will be similar in spirit to the present version, but may differ in detail to address new problems or concerns.
Each version is given a distinguishing version number. If the Program specifies a version number of this License which applies to it and "any later version", you have the option of following the terms and conditions either of that version or of any later version published by the Free Software Foundation. If the Program does not specify a version number of this License, you may choose any version ever published by the Free Software Foundation.

But I can't find anywhere the phrase "any later version", so Doxygen is GPL-2.0-only?

**Comment by doxygen** [comment]
yes it is indeed GPL-2.0 only. Never found a good reason to allow for later GPL versions as well.

**Comment by Croydon** [comment]
Thanks for clarification
