### ISSUE TITLE
Use <details> and <summary> instead of JavaScript for hideable content

### ISSUE THREAD

**Issue by KOLANICH** [doxygen/doxygen#6720]

**Comment by albert-github** [comment]
Please explain what you mean with your title line.

Can you please attach a, small, self contained example (source+config file in a tar or zip) that allows us to reproduce the problem?
Please also specify the doxygen version used.

**Comment by KOLANICH** [comment]
This is not a self-contained example, but is getter tuan nothing: https://kolanich.gitlab.io/-/UniOpt.py/-/jobs/140186316/artifacts/public/html/classecabc_1_1BeeColony.html

```html
<div id="dynsection-0" onclick="return toggleVisibility(this)" class="dynheader closed" style="cursor:pointer;">
  <img id="dynsection-0-trigger" src="closed.png" alt="+"/> Inheritance diagram for ecabc.BeeColony:</div>
<div id="dynsection-0-summary" class="dynsummary" style="display:block;">
</div>
<div id="dynsection-0-content" class="dyncontent" style="display:none;">
<div class="center"><iframe scrolling="no" frameborder="0" src="classecabc_1_1BeeColony__inherit__graph.svg" width="139" height="287"><p><b>This browser is not able to show SVG: try Firefox, Chrome, Safari, or Opera instead.</b></p></iframe>
</div>
</div>
```

should be

```html
<details>
  <summary>Inheritance diagram for ecabc.BeeColony:</summary>
<iframe scrolling="no" frameborder="0" src="classecabc_1_1BeeColony__inherit__graph.svg" width="139" height="287"><p><b>This browser is not able to show SVG: try Firefox, Chrome, Safari, or Opera instead.</b></p></iframe>
</details>
```

No JS, browser does everything itself.

>Please also specify the doxygen version used.

`1.8.14`

**Comment by albert-github** [comment]
I don't get the benefit of the HTML5 tags `<details>` and `<summary>` over the current code, 

Furthermore these tags are not supported by IE / edge  according to https://www.w3schools.com/tags/tag_details.asp and https://www.w3schools.com/tags/tag_summary.asp.
 
Also I don't understand the remark "No JS, browser does everything itself.".

**Comment by KOLANICH** [comment]
MS has opened beta of Chromium-based Edge https://www.microsoftedgeinsider.com/en-us/download . I guess old edge can be considered dead.

**Comment by Nurgak** [comment]
I'd like to bump this issue.

Currently, I am using the `<details>` tag in a Markdown document to hide some large example data from the documentation.

Doxygen (`1.9.1`) reports `Unsupported xml/html tag <details> found`. What's more, the nested `<summary>` tag contents is pushed all the way to the top of the Markdown-used-as-mainpage document, which looks completely out of place.

To recreate the issue, create the following Markdown document and parse it with Doxygen:

```html
# Title

Content

<details>
<summary>Expand me</summary>
Hidden information.
</details>
```

The output will appear as follows, the `<details>` tag is ignored and `<summary>` appears just below the main title.
```markdown
# Title
Expand me

Content

<details>
Hidden information.
</details>
```

Alternatively, would there be a way to process the `<details>` as a custom tag (via aliases perhaps), so as to avoid the `<summary>` part from moving about?

**Comment by albert-github** [comment]
In version 1.9.3 the `<details>` tag has been added (see https://github.com/doxygen/doxygen/pull/8890) and in the current master (see e.g. 1.9.6 (942ab56861e606bea4bb709ccdc49b8104785a75))  there are some improvements in respect to the usage of the `<summary>` tag withing the `<details>` tag.

I think the problem has been solved in the mean time.

**Comment by Nurgak** [comment]
@albert-github Thank you for the information.

I ended up getting Doxygen 1.9.1 from the [`python:3.11-slim`](https://github.com/docker-library/python/blob/master/3.11/slim-bullseye/Dockerfile) image.

I tried the [corentinaltepe/doxygen](https://hub.docker.com/r/corentinaltepe/doxygen) image and got 1.9.5. The `<details>` tag worked as expected.
