### ISSUE TITLE
Duplicate method documentation after editing it

### ISSUE THREAD

**Issue by ypujante** [doxygen/doxygen#6752]
I am in the process of adding doxygen documentation to the [Jamba](https://github.com/pongasoft/jamba) project.

I used the wizard to create an initial configuration file and ran it on my project. I then edited some comments to be _compliant_ with the markdown syntax. After generating the documentation again I end up with the new comment and the old comment. This seems to be coming from a cache but I am not sure what is happening. I deleted the entire previously generated html folder to no avail.

The old comment was like [this](https://github.com/pongasoft/jamba/blob/v3.0.2/src/cpp/pongasoft/VST/GUI/Params/GUIParamCxAware.h#L136)

```
  /**
   * Convenient call to register a callback for the Vst param simply by using its description. Takes care of
   * the type due to method API. Since the callback (Parameters::ChangeCallback1) is providing the param, it is not
   * returned by this api.
   *
   * Example:
   * registerCallback<int>(fParams->fMyParam, [] (GUIVstParam<int> &iParam) { iParam.getValue()...; });
   *
   * Note how the compiler requires the type (which seems that it could be inferred).
   *
   * @return false if not found or not proper type
   */
  template<typename T>
  bool registerCallback(VstParam<T> const &iParamDef,
                        Parameters::ChangeCallback1<GUIVstParam<T>> iChangeCallback,
                        bool iInvokeCallback = false);
```

which I changed to be like that (indentation for the "code" section and back ticks around false)

```
  /**
   * Convenient call to register a callback for the Vst param simply by using its description. Takes care of
   * the type due to method API. Since the callback (Parameters::ChangeCallback1) is providing the param, it is not
   * returned by this api.
   *
   * Example:
   *
   *     registerCallback<int>(fParams->fMyParam, [] (GUIVstParam<int> &iParam) { iParam.getValue()...; });
   *
   * Note how the compiler requires the type (which seems that it could be inferred).
   *
   * @return `false` if not found or not proper type
   */
  template<typename T>
  bool registerCallback(VstParam<T> const &iParamDef,
                        Parameters::ChangeCallback1<GUIVstParam<T>> iChangeCallback,
                        bool iInvokeCallback = false);
```

The generated html for this method looks like this:
```
<div class="memdoc">
<p>Convenient call to register a callback for the Vst param simply by using its description. Takes care of the type due to method API. Since the callback (<a class="el" href="classpongasoft_1_1_v_s_t_1_1_parameters.html#a2bec2ab4a6d7ce40aa27aea27b5d3281">Parameters::ChangeCallback1</a>) is providing the param, it is not returned by this api.</p>
<p>Example: </p><pre class="fragment">registerCallback&lt;int&gt;(fParams-&gt;fMyParam, [] (GUIVstParam&lt;int&gt; &amp;iParam) { iParam.getValue()...; });
</pre><p>Note how the compiler requires the type (which seems that it could be inferred).</p>
<dl class="section return"><dt>Returns</dt><dd><code>false</code> if not found or not proper type</dd></dl>
<p>Convenient call to register a callback for the Vst param simply by using its description. Takes care of the type due to method API. Since the callback (<a class="el" href="classpongasoft_1_1_v_s_t_1_1_parameters.html#a2bec2ab4a6d7ce40aa27aea27b5d3281">Parameters::ChangeCallback1</a>) is providing the param, it is not returned by this api.</p>
<p>Example: registerCallback&lt;int&gt;(fParams-&gt;fMyParam, [] (GUIVstParam&lt;int&gt; &amp;iParam) { iParam.getValue()...; });</p>
<p>Note how the compiler requires the type (which seems that it could be inferred).</p>
<dl class="section return"><dt>Returns</dt><dd>false if not found or not proper type </dd></dl>

</div>
```

You can see that there are 2 sections "Convenient call...." one with the code block enclosed in a pre statement (new comment) and one without (old comment).

I tried from a brand new folder, but it still gives me the same result.

**Comment by albert-github** [comment]
I don't get the problem. Maybe you can add a picture of the problem you are seeing.
Which version of doxygen are you using (I looked with 1.8.15)?

**Comment by ypujante** [comment]
<img width="485" alt="screen shot 2019-01-07 at 10 41 57" src="https://user-images.githubusercontent.com/357116/50786628-edfa1880-1268-11e9-89e1-2f7c0eb751b0.png">

Yes I am using 1.8.15

**Comment by ypujante** [comment]
I am on the mac and I installed the dmg if that is relevant. Let me know if there is something you want me to do to troubleshoot the problem...

**Comment by ypujante** [comment]
I found the problem and it is my fault. I just realized that there is also a [.hpp](https://github.com/pongasoft/jamba/blob/v3.0.2/src/cpp/pongasoft/VST/GUI/Params/GUIParamCxAware.hpp#L100) which has the old documentation. So it looks like doxygen is using both, the one defined in the `.h` and the one defined in the `.hpp`.

I apologize for not seeing this sooner.

**Comment by albert-github** [comment]
No problem I came also to the conclusion that it might be a double file source / double documented part (I was just going to request an example but that is not necessary anymore).
