### ISSUE TITLE
markdown output?

### ISSUE THREAD

**Issue by aster94** [doxygen/doxygen#6759]
hello,

I am on windows 10 and using doxygen 1.8.15
I know that from 1.8.0 there is support for markdown. This would be perfect for me because I would like to copy paste the doxygen output directly to github but I don't understand how should i output the `.md` files from doxygen! what am I missing? or should i make a html/xml and then use it to generate a markdown file?

Also, usually I do small projects where documenting just one class is enough, is possibile to do something similar?

**Comment by albert-github** [comment]
I don't moxygen and how complete its is so I cannot comment on it.

You can always file an enhancement requests.

**Comment by aster94** [comment]
opened #6760 thanks for the help anyway!
