### ISSUE TITLE
Error Parsing C++17-style Nested Namespaces

### ISSUE THREAD

**Issue by AndreNGLoytec** [doxygen/doxygen#6765]
I am using the Windows version of Doxygen 1.8.15.

Doxygen is having trouble parsing nested namespaces in the C++17 style, in that it does not close them correctly. For example, if I have the following code:

```
namespace First::Second::Third {
class Foo;
}

namespace One::Two::Three {
class Bar {
```

Then Doxygen will, in its class list, categorize the Bar class as being in the First::Second::One::Two::Three namespace. That is, it will erroneously parse the closing bracket on the C++17-style First::Second::Third namespace as closing only the outermost namespace ("Third"), so whatever code follows next will be in the First::Second namespace.

This is problematic in the case of forward declarations of classes that are located in a nested namespace, as in the example above.

If you need any clarifications, let me know!

**Comment by albert-github** [comment]
Looks like that version 1.8.14 did work, but 1,8.15 not anymore.
Small question for me is also should "First::Second::Third: be seen as one entity or as 3 separate nested namespaces (in 1.8.14 it is seen as 1 entity as far as I can see).

It is always nice to have a, small, self contained example (source+config file in a tar or zip) that allows us to reproduce the problem.

**Comment by AndreNGLoytec** [comment]
Here is a simple example through which the issue can be reproduced:

[DoxygenExample.zip](https://github.com/doxygen/doxygen/files/2754374/DoxygenExample.zip)

And here are screenshots depicting the output:

![example_output_1](https://user-images.githubusercontent.com/46594449/51102081-c9a8b980-17dd-11e9-9565-4432d8e0a724.png)

![example_output_2](https://user-images.githubusercontent.com/46594449/51102084-cca3aa00-17dd-11e9-91b1-b1c22592757c.png)

I hope that helps!

**Comment by Sygmei** [comment]
Had the same issue with nested namespaces, hope it gets resolved !

**Comment by albert-github** [comment]
The problem is introduced with the fix for issue #5784 (Doxygen not creating call graphs for C# methods if namespace contains the classname (Origin: bugzilla #749049)) and the resulting pull request #6565.

The problematic part in the code looks like to be the determination of the so called current root i.e. the current scoping (level), in scanner.l in the rule `<ReadBody,ReadNSBody>"}"`.
Here the namespaces are split in their components and in the different parts the scope is prepended to the name. In case of the second 'namespace set' (above `One::Two::Three`) part of the previous 'namespace set' is seen as an encompassing namespace and prepended.

**Comment by lixcode-rep** [comment]
What is new about bug fixing?

**Comment by h-2** [comment]
I can confirm, this is a regression.

**Comment by mrhatch97** [comment]
I took a stab at fixing this in #6977 as it's affecting a project of mine.

**Comment by h-2** [comment]
Since there were quite a few regression that have already been fixed, can we expect a new patch-leve release before December? That would be really great! Thank you.

**Comment by craffael** [comment]
According to #6977 this should have been fixed in 1.8.16, but I've just compiled 1.8.16 on my system and it seems that it has not yet been fixed. Is anyone else experiencing the same?

**Comment by albert-github** [comment]
@craffael did you see the problem with the example attached to this issue or in a new exampel in the later case: 
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.

**Comment by craffael** [comment]
@albert-github It turns out, that the problem I had is slightly different: A doxygen commment on a nested namespace is assigned to the wrong namespace. I opened a new issue for that: #7295

**Comment by daravi** [comment]
Hi should the `fixed but not released` label be removed from this issue?
