### ISSUE TITLE
Provide emoji enable/disable config flag

### ISSUE THREAD

**Issue by lorenzoPatras** [doxygen/doxygen#6774]
Please provide flag support in the config file to disable emoji in case someone does not want them.

**Comment by albert-github** [comment]
The emoji are only available with the `\emoji` command in the 1.8.15 version, so when one doesn't use the `\emoji` command there won't be any emoji.

Did I miss something?

Please give more details where you see that emoji give problems.

**Comment by lorenzoPatras** [comment]
Maybe my version of doxygen was not clean or something. The emoji was enabled by default. I uninstalled and reinstalled it via brew and not it works fine. Sorry for the ticket. Keep up the great job 😃
