### ISSUE TITLE
Doxygen doesn't generate Qt compressed help file

### ISSUE THREAD

**Issue by MartinDelille** [doxygen/doxygen#6777]
I tried generating a Qt compressed help file thanks to this article: http://blog.qt.io/blog/2014/08/13/qt-weekly-17-linking-qt-classes-in-documentation-generated-with-doxygen/

Unfortunately, no `qhc` file is generated as specified.

I notice this error in the output log:

```
sh: epstopdf: command not found
error: Problems running epstopdf. Check your TeX installation!
```

Is this article out of date?

**Comment by albert-github** [comment]
Which version of doxygen do you use?
Which LaTeX  distribution do you use?
The later has also been a remark on https://stackoverflow.com/questions/54239215/doxygen-doesnt-generate-qt-compressed-help-file. You probably need `epstopdf` as you have an `eps` image or a formula in your code.

**Comment by MartinDelille** [comment]
> Which version of doxygen do you use?

1.8.15 (installed via hom

> Which LaTeX distribution do you use?

I don't know.

> The later has also been a remark on https://stackoverflow.com/questions/54239215/doxygen-doesnt-generate-qt-compressed-help-file. You probably need epstopdf as you have an eps image or a formula in your code.

I'm the author of the stackoverflow question.

I tried to install textlive on OSX with brew but I had the following message:

```
Error: No available formula with the name "texlive"
Installing TeX from source is weird and gross, requires a lot of patches,
and only builds 32-bit (and thus can't use Homebrew dependencies)

We recommend using a MacTeX distribution: https://www.tug.org/mactex/

You can install it with Homebrew Cask:
  brew cask install mactex
```

So I installed mactext via brew cask.

Unfortunately I keep having the same error message.

**Comment by albert-github** [comment]
Looks like the LaTeX distribution cannot be found.
Check with `pdflatex --version` which version you have / use.
You can also give see with `doxygen -d extcmd` which external commands are started.

**Comment by MartinDelille** [comment]
`pdflatext` is not installed on my computer. Do I really need it for QHC generation?

**Comment by albert-github** [comment]
Well you at least need epstopdf (see initial error message) and this is part of the TeX installation.
So you need (part of) the TeX installation and safest is to install all executables (packages is another story). Installation is beyond my knowledge as I don't have a Mac.

**Comment by doxygen** [comment]
I don’t expect you need epstopdf for qt help, so please attach a self contained example (source + config file) that can be used to reproduce the problem.

**Comment by MartinDelille** [comment]
Ok the problem was that I set GENERATE_HTML to NO.
