### ISSUE TITLE
Extra quotes in codelines for LaTeX

### ISSUE THREAD

**Issue by DancingOnWater** [doxygen/doxygen#6778]
For codeline doxygen 1.8.15 form such line:

`\DoxyCodeLine{ list.Rows.Add(\textcolor{stringliteral}{"X:\(\backslash\)t 36"});}`

Instead
`\DoxyCodeLine{ list.Rows.Add(\textcolor{stringliteral}{X:\(\backslash\)t 36});}`

**Comment by albert-github** [comment]
Unfortunately no reaction so I tried a small example:
```
/// \file

/// the fie
///
/// \code
/// list.Rows.Add("X:\t 36");
/// \endcode
void fie();
```
and in the 1.8.15 version this gave (as it should be):
```
\DoxyCodeLine{list.Rows.Add(\textcolor{stringliteral}{"X:\(\backslash\)t 36"});}
```
In the 1.9.6 version we even get a little bit a better version:
```
\DoxyCodeLine{list.Rows.Add(\textcolor{stringliteral}{"{}X:\(\backslash\)t\ 36"{}});}
```

So I think the problem is not reproducible.
