### ISSUE TITLE
Upgrade jQuery to latest 3.x release

### ISSUE THREAD

**Issue by lewijw** [doxygen/doxygen#6795]
According to the jQuery home page, “The 1.x and 2.x branches no longer receive patches”, and our customers are aware of this and have requested that our products only include supported versions of jQuery.  Therefore, I am hoping to see a release of Doxygen using the latest jQuery (currently 3.3.1). 

I recently supplied a pull request to upgrade to a patched version of jQuery (1.7.2).  Thanks for accepting that, but unfortunately, I don't know enough about Doxygen or Javascript to help with moving to jQuery 3.

Please see this issue for a good discussion on moving to the latest version of jQuery 1.x:  #6027 

Moving to the latest version of jQuery 1 would be an improvement, but we need jQuery to be 3.x.

How likely is it that someone more familiar with Doxygen will be able to do the development required?  Or, is it desired to stay with jQuery 1 for the foreseeable future?  Issue #6027  mentions old browser support for instance.

Thanks for any reply.  I am trying to get an idea on how long we may have to wait, and how important it is to the Doxygen community.

**Comment by doxygen** [comment]
With this commit the jquery script has been updated to 3.3.1: https://github.com/doxygen/doxygen/commit/c141d67332ce9e6875d4c03c4652a88da29a6f78

**Comment by lewijw** [comment]
Thank you very much!  My tests indicate that it is working nicely, and our security scans are clean.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
