### ISSUE TITLE
Bad link to section, subsection if pointing at item past suspicious text

### ISSUE THREAD

**Issue by reylau** [doxygen/doxygen#6796]
Hello,

If a "@ref Toto" points to a section, subsection located after

<code>\@code</code>

the generated link is wrong, it uses the source file name instead of the file ouptut name. As soon as the above text is removed, the links are correctly generated.

A full example is joined: check the links in 4.2 and other locations. The configuration file and logs are also included.

Best regards

Laurent

[Documentation.zip](https://github.com/doxygen/doxygen/files/2797032/Documentation.zip)

**Comment by albert-github** [comment]
Looks like the `\@` is causing some problems inside the `<code>`. A workaround , as far as I can see, is  replacing the `\@` by `\\` or \@@`  (`\@\` gives the same problems).

**Comment by reylau** [comment]
Hello Albert,

Your two workarounds works fine with the example I have sent. I'll check if this is also the case in the original (fatter) project. I'll keep you posted.

Rgds

Laurent

⁣Envoyé par TypeApp ​

Le 25 janv. 2019 à 18:40, à 18:40, albert-github <notifications@github.com> a écrit:

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6797

**Comment by albert-github** [comment]
Code has been integrated in master on github.

**Comment by reylau** [comment]
Hello Albert,

Thank you for the updates. 

BTW, I have checked your proposed workaround, and a `@@` works fine with my full project.

Rgds

Laurent

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
