### ISSUE TITLE
Linux doxygen-1.8.15: libtinfo.so.5 => not found

### ISSUE THREAD

**Issue by mortenvp** [doxygen/doxygen#6816]
Using the pre-built Linux binary doxygen-1.8.15 we get a missing dependency for `libtinfo.so`. 

According to these guys https://github.com/cockroachdb/cockroach/pull/24513:

> ... there is no standad standalone `libtinfo` on linux, and on most linux system it is either a symlink to `libncurses`, or doesn't exist at all! ...

Fortunately the fix should be easy: 

> ... links against `libncurses` instead, which is guaranteed to exist (it's been part of the Linux Standard Base forever).

So the command mentioned by @doxygen  here https://github.com/doxygen/doxygen/issues/6317#issuecomment-452429190 should be update. To link against `libncurses`

**Comment by doxygen** [comment]
Even if I do `-lnurses` instead of `-ltinfo` the resulting binary still depends on `libtinfo.so` (and not on `libnurses.so`)

**Comment by doxygen** [comment]
It was indeed libclang and adding `-DLLVM_ENABLE_TERMINFO=OFF` does the trick to get rid of this dependency.

**Comment by mortenvp** [comment]
Great - would be excellent with a release ;)
