### ISSUE TITLE
German special characters in XML output

### ISSUE THREAD

**Issue by Wandfluh-Hydraulik-und-Elektronik** [doxygen/doxygen#6820]
When the source code contains german secial characters they should be encoded in the XML output like described in http://www.devtrain.de/artikel_296.aspx

**Comment by albert-github** [comment]
Can you please attach a, small, self contained example (source+configuration  file in a tar or zip) that allows us to reproduce the problem? i.e. a source file with the problematic characters, it is hard when not using a non german keyboard to reproduce these kind of things and also the used encoding is of importance as set in the files and the settings of t in the Doxyfile.
Don't include a link to an external resource (these might vanish and also people are not happy to click on unknown links) but include the document or a, very good readable, imag with the relevant information.

Please also specify the doxygen version used.

**Comment by doxygen** [comment]
> When the source code contains german secial characters they should be encoded in the XML output like described in http://www.devtrain.de/artikel_296.aspx

This is not correct. The XML standard only requires these characters to be escaped:


    "   &quot;
    '   &apos;
    <   &lt;
    >   &gt;
    &   &amp;

(source https://www.w3.org/TR/xml/#syntax)

Any other non-ASCII character should be UTF-8 encoded as specified by the encoding attribute in the XML header.

    <?xml version='1.0' encoding='UTF-8' standalone='no'?>

**Comment by Wandfluh-Hydraulik-und-Elektronik** [comment]
[Solved] The Microsoft C# XmlDocument.LoadXML from String works fine. XmlDocument.Load from file directly seems to be the problem. Sorry, is no Doxygen problem
