### ISSUE TITLE
Allow for callback parameters to be documented 

### ISSUE THREAD

**Issue by ruipacheco** [doxygen/doxygen#6821]
I believe my SO question explains everything: https://stackoverflow.com/questions/54483956/how-to-document-a-function-that-takes-a-callback/

**Comment by ruipacheco** [comment]
I'm writing an asynchronous library and some of my method take callbacks as parameters:

```
/// \brief Opens a connection to the remote server defined by the parameters passed in the constructor.
/// \param[in] callback Callback passed when the connection is estabelished or fails.
/// \return Any errors encountered by the library or the OS.
virtual connect(std::function<void(std::error_code ec)> callback) noexcept = 0;
```

How can document the callback's parameters in Doxygen? If not at all, is this something that can be added?

**Comment by albert-github** [comment]
The result of your example is:

![result](https://user-images.githubusercontent.com/5223533/52281189-ddb78500-295d-11e9-8fe0-31d1daa42b22.jpg)

what are you missing?

Please also answer the question about the version you used.

**Comment by ruipacheco** [comment]
My version is 
```
> doxygen --version                                                                                                                                                         
1.8.14
```

I need to document the parameters passed to the std::function object, ie, the error code.

**Comment by albert-github** [comment]
Probably best is to do it through a typedef for the `std::function<void(std::error_code ec)>` part.

**Comment by ruipacheco** [comment]
Thanks!
