### ISSUE TITLE
Message: graph_legend:39: error: Prevented to copy file <path_to_html_output>/graph_legend.png onto itself!

### ISSUE THREAD

**Issue by Knitschi** [doxygen/doxygen#6830]
The second doxygen run fails with error: graph_legend:39: error: Prevented to copy file <path_to_html_output>/graph_legend.png onto itself! 

The problem only occurred after upgrading doxygen from 1.8.14 to 1.8.15.
The problem is triggered when I run doxygen twice without deleting the previously generated files.

**Comment by albert-github** [comment]
First thing that comes into my mind is have the permissings of the HTML directoty / the png file changed in between? 
What are the permissions of the file after the first run?

Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?
Please also specify the doxygen version used.
Please also specify the Operating system you are using.

**Comment by Knitschi** [comment]
- This seems to be just a warning, but I use `WARN_AS_ERROR = YES` so for me it is an error.
- It happens with Doxygen 1.8.15. It was no problem with Doxygen 1.8.14.
- It happens on Windows 10 and on Debian 9.
- As far as I can tell, the file permissions do not seem to change after running doxygen.

I will put a small example together within the next hours.

**Comment by Knitschi** [comment]
Here is an example. Just run Doxygen twice for it. The second call will fail.

[DoxygenIssue6830.zip](https://github.com/doxygen/doxygen/files/2847801/DoxygenIssue6830.zip)

**Comment by albert-github** [comment]
I did try to reproduce it, but it didn't reproduce.
The problem might be in the setting of the `IMAGE_PATH` and the setting of `RECURSIVE` resulting in that the `html` directory is searched for images as well.
Do you have anywhere an own reference to `graph_legend.png`

Please also check the permissions of the  file `<path_to_html_output>/graph_legend.png` after the first run.

**Comment by Knitschi** [comment]
Setting `RECURSIVE = NO` removes the error.
It is strange that doxygen searches for files in the html directory even though I set `EXCLUDE = html`.
Maybe that is the problem here.

**Comment by Knitschi** [comment]
On the other hand, doxygen 1.8.14 also searches in the html directory and does not have that problem.

**Comment by albert-github** [comment]
The `IMAGE_PATH` reading does not take into account the `EXCLUDE` tag but does take into account the `RECURSIVE` tag, from the documentation:

> The EXCLUDE tag can be used to specify files and/or directories that should be excluded from the INPUT source files. This way you can easily exclude a subdirectory from a directory tree whose root is specified with the INPUT tag.

> The RECURSIVE tag can be used to specify whether or not subdirectories should be searched for input files as well.

So the real problematic is actually the combination of setting of  `IMAGE_PATH=.` and `RECURSIVE=YES`.
In your case I would advise to place the files like `CPFLogo.svg`, `header.html` etc. in a subdiretory so you can refer to this directory in the doxygen configuration file (you can even use an environment variable in the form of `$(VAR)` for this).

**Comment by albert-github** [comment]
Regarding the difference between version 1.8.14 and 1.8.15, in version 1.8.14 there was a warning:
`Source and Destination are the same!`
and the file was not copied.

But this message didn't run through the correct routines and this has been corrected for the 1.8.15 version into a warning with the message as cited as the content of the file is not considered, but only the filename and it is unclear which version of the file will be present (it is possible that there are multiple files with the same name in e.g. the `IMAGE_PATH` but with different content).

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6833, that removes the message completely.

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by Knitschi** [comment]
Thank you for the quick fix.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
