### ISSUE TITLE
1.8.15: not ok 12 - [012_cite.dox]: test the \cite command

### ISSUE THREAD

**Issue by kloczek** [doxygen/doxygen#6839]
Test 12 fails with:

<pre>not ok 12 - [012_cite.dox]: test the \cite command
-------------------------------------
Difference between generated output and reference:
--- /home/tkloczko/rpmbuild/BUILD/doxygen-1.8.15/testing/test_output_012/indexpage.xml	2019-02-14 20:02:38.397378594 +0100
+++ /home/tkloczko/rpmbuild/BUILD/doxygen-1.8.15/testing/012/indexpage.xml	2017-12-24 11:20:24.000000000 +0100
@@ -6,7 +6,7 @@
     &lt;briefdescription&gt;
     &lt;/briefdescription&gt;
     &lt;detaileddescription&gt;
-      &lt;para&gt;See knuth79 for more info. &lt;/para&gt;
+      &lt;para&gt;See &lt;ref refid=&quot;citelist_1CITEREF_knuth79&quot; kindref=&quot;member&quot;&gt;[1]&lt;/ref&gt; for more info. &lt;/para&gt;
     &lt;/detaileddescription&gt;
   &lt;/compounddef&gt;
 &lt;/doxygen&gt;

-------------------------------------
</pre>

**Comment by albert-github** [comment]
I don't see any differences in my tests. Did you add something? Do you have latex with bibtex installed?

**Comment by kloczek** [comment]
After installing latex tests passed correctly.
Maybe it would be good to add some checks in cmake files for checking is latex present in build env?
