### ISSUE TITLE
Physical newlines (^^) in ALIASES produce a mismatch between documentation and source code

### ISSUE THREAD

**Issue by Kampfzwerg42** [doxygen/doxygen#6847]
If I use ^^ in an alias and use the SOURCE_BROWSER, the line number of following symbols in the documentation refers to the real number + number of ^^ in used aliases before
The 'dirty solution' to replace ^^ by \\_linebr from #6828 works here as well

**Comment by albert-github** [comment]
Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.
Please also specify the doxygen version used.

**Comment by Kampfzwerg42** [comment]
I have created a minimalistic example which shows this problem(in Html link form documentation to source code is false) and an second bug that I have found(the first comment line in is ignored so that the first symbol stand at line 1 in source code browser)

[doc.zip](https://github.com/doxygen/doxygen/files/2899431/doc.zip)
![doxybug3](https://user-images.githubusercontent.com/29091152/53322675-603bc080-38dc-11e9-89b1-6726599fcf4d.PNG)
![doxybug2](https://user-images.githubusercontent.com/29091152/53322677-603bc080-38dc-11e9-8ce4-46cf010ead4f.PNG)
![doxybug](https://user-images.githubusercontent.com/29091152/53322678-603bc080-38dc-11e9-8d00-a795ba8693b1.PNG)

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6858 

Note: that in case `STRIP_CODE_COMMENTS` is not set and the file begins with a doxygen comment the line number in the show source code of the first definition might be wrong, but this is independent of the ALIASES / newline substitution. This minor problem has to be handled in a separate pull request.

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
