### ISSUE TITLE
Allow TODO FIXME BUG aliases

### ISSUE THREAD

**Issue by galek** [doxygen/doxygen#6867]
Hello, we use task manager in VS and when tried generate doxygen docs got what todo aliases not works.
Works correctly only: \TODO and \TODO:, but in project used only TODO:
Else VS not recognized todos

My aliases:
ALIASES += "TODO=@todo"
ALIASES += "FIXME=@bug"
ALIASES += "BUG=@bug"

Any solutions without using Cygwin?
https://stackoverflow.com/questions/1479311/getting-doxygen-and-msvc-todo-tags-to-work-together
https://stackoverflow.com/questions/8535635/can-doxygen-easily-be-configured-to-recognise-todo-and-fixme-lines

**Comment by albert-github** [comment]
Only solutions I see is:
- to use a `INPUT_FILTER` with e.g. a python script or any other script transforming `// *TODO` in `/// \todo`.
- see that VS has a setting that satisfies VS and doxygen.

In case I missed something here, please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.
Please also specify the doxygen version used.

**Comment by galek** [comment]
Doxygen 1.8.15
C# example(similiar in C++)
`//TODO: Test`

Important(!) works only with ":"

Similiar with /*TODO: test*/

More info: https://docs.microsoft.com/ru-ru/visualstudio/ide/using-the-task-list?view=vs-2017

**Comment by albert-github** [comment]
What happens when you add `\todo` or `@todo` to the list on the task lists option page?

![img1](https://user-images.githubusercontent.com/5223533/53869242-1e0b3100-3ff8-11e9-96ec-125196c60e36.jpg)

Note that for doxygen you anyway need more than the normal `//` i.e. `///`, `//!`.

**Comment by galek** [comment]
Oh, okey. Thx, will use doxygen semantics
