### ISSUE TITLE
Missing some XML compounds going from 1.8.6 to 1.8.11 or later on windows 64

### ISSUE THREAD

**Issue by vinniefalco** [doxygen/doxygen#6871]
My documentation has built perfectly on Windows and Linux using an XML output workflow. However, when I upgrade the version of Doxygen in use to 1.8.11 or later (also tested with 1.8.14 and 1.8.15), the Windows output is missing some refs. Here's an example of a function which appears in 1.8.6 but is not emitted as an xml file in 1.8.11 and later:
https://github.com/boostorg/beast/blob/develop/include/boost/beast/http/read.hpp#L212

Other functions do output. It seems like the entire file is being ignored, perhaps because of an element that Doxygen is getting confused with (although I must stress that this all works in 1.8.6 which I have been using for 2+ years).

1.8.11 and later generate correct XML output on Linux.

**Comment by albert-github** [comment]
Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.
Please also indicate (some) of the references missing (there will be quite a few differences between the XML output of 1.8.6 and 1.8.15 so it might otherwise be searching for a needle in a haystack).

**Comment by vinniefalco** [comment]
I figured out part of it. This fails:
```
template<
    class AsyncReadStream,
    class DynamicBuffer,
    bool isRequest,
    class ReadHandler>
BOOST_ASIO_INITFN_RESULT_TYPE(
    ReadHandler, void(error_code, std::size_t))
async_read_some(
    AsyncReadStream& stream,
    DynamicBuffer& buffer,
    basic_parser<isRequest>& parser,
    ReadHandler&& handler);
```

This works (note that the macro invocation is on a single line)
```
template<
    class AsyncReadStream,
    class DynamicBuffer,
    bool isRequest,
    class ReadHandler>
BOOST_ASIO_INITFN_RESULT_TYPE(ReadHandler, void(error_code, std::size_t))
async_read_some(
    AsyncReadStream& stream,
    DynamicBuffer& buffer,
    basic_parser<isRequest>& parser,
    ReadHandler&& handler);
```

I have this in my config:
```
PREDEFINED             = \
                        BOOST_ASIO_INITFN_RESULT_TYPE(t,a)=__deduced__
```

This happens only on Windows

**Comment by albert-github** [comment]
As far as I can see the problem is usage. 

Besides `PREDEFINED` the configuration parameter  `MACRO_EXPANSION` so we get at least:
```
PREDEFINED             = "BOOST_ASIO_INITFN_RESULT_TYPE(t, a)=__deduced__"
MACRO_EXPANSION=YES
```

Note I also added `"` as otherwise the `,`  wil give some problems.

See also the chapter "Preprocessing" in the manual.

**Comment by vinniefalco** [comment]
Ah, I see! That's good to know. But why is this a problem only on Windows??

**Comment by albert-github** [comment]
I have no idea why it only happens on Windows (assuming everything of the input is identical), I would expect that on all platforms the problem would occur.

**Comment by vinniefalco** [comment]
Seems to work with the quotes, so this is not really a problem - thanks!
