### ISSUE TITLE
@cond/@endcond seems to be parsed twice

### ISSUE THREAD

**Issue by thom-sch** [doxygen/doxygen#6877]
Since doxygen V.1.8.15 it seems that doxygen would parse a @cond/@endcond block twice.

This results in error messages like:

`
C:/Daten/Doxygen/Test2/Projekt1/src/Objekt-Tabelle.md:6: warning: multiple use of section label 'SDO60FD' while adding section, (first occurrence: C:/Daten/Doxygen/Test2/Projekt1/src/Objekt-Tabelle.md, line 1)

C:/Daten/Doxygen/Test2/Projekt1/src/Objekt-Tabelle.md:17: warning: multiple use of section label 'SDO60FE' while adding section, (first occurrence: C:/Daten/Doxygen/Test2/Projekt1/src/Objekt-Tabelle.md, line 1)
`

Nevertheless it seems that the documentation was created properly.

But if additionally a tag-file is created, the references are not written to the tag-file whicht results in error messages in other project using this tag-file like:

`C:/Daten/Doxygen/Test2/Projekt2/src/Modul2.cpp:6: warning: unable to resolve reference to ' SDO60FE' for \ref command`

s. added zip-file

Upto doxygen V.1.8.14 all of this works properly for me.

May be related to issue 485773?
[Test2.zip](https://github.com/doxygen/doxygen/files/2945563/Test2.zip)

Regards
Thomas

**Comment by albert-github** [comment]
I tested with version 1.8.15 and I see the messages. In the current master these messages are gone.
This problem has been reported by issue #6779 and fixed by means of pull request #6780

So I think the the problem has been fixed but not released.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
