### ISSUE TITLE
Doxygen 1.8.13 is broken with Dlang

### ISSUE THREAD

**Issue by vporton** [doxygen/doxygen#6887]
Doxygen 1.8.13 creates completely wrong documentation for [this project](https://github.com/vporton/struct-params-dlang/tree/v0.9.1).

The list of documented symbols is wrong.

The bug seems to be in parsing D sources.

**Comment by albert-github** [comment]
Although I don't think there are any relevant changes for D between 1.8.13 and 1.8.15 can you see if 1.8.15 gives better results.
The "completely wrong" is a bit vague can you indicate what is wrong and where this shows up in the generated documentation (maybe a non D programmer, like me, might be able to fix some things when it is clear what is wrong).

Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.
