### ISSUE TITLE
Doxygen fails to properly generate deprecated list for PHP source

### ISSUE THREAD

**Issue by timmyrs** [doxygen/doxygen#6888]
```
<?php
namespace MyNamespace;
class MyClass
{
	/**
	 * This is my deprecated function.
	 * @deprecated It's deprecated.
	 */
	function myDeprecatedFunction()
	{

	}
}
```

This simple PHP code results in

> deprecated:2: warning: Illegal command MyClass as part of a \ref

Furthermore, in the deprecated list itself, it will be displayed as `MyNamespace::myDeprecatedFunction`, instead of `MyClass::myDeprecatedFunction`.

This could be a regression of #5901.

**Comment by timmyrs** [comment]
Never mind, silly me just checked my Doxygen version and realized I'm behind the version it was patched in.

**Comment by timmyrs** [comment]
On a related note, it would be lovely if the latest doxygen version were on apt-get, tho I'm not sure in how much control you are of that.

**Comment by doxygen** [comment]
There are many distributions shipping doxygen. They all have their own way of packaging. It is not possible for me to support that. I suggest you contact the package maintainer of your distribution and ask for an upgrade.
