### ISSUE TITLE
One question about using doxygen

### ISSUE THREAD

**Issue by xiaoyusu** [doxygen/doxygen#6891]
while i declare one function in ".h" file named "lcc_accept", as below .
int lcc_accept(void);

And also i make a define in the same “.h” file as below.
#define accept(void)    lcc_accept(void)

so, if there any methods that i can get  api reference with this function named accept??

wish for answer...~

**Comment by albert-github** [comment]
Yes this is possible (when I interpret your question right):
- Please read about `MACRO_EXPANSION` in the manual
- see to it that your `#define` is correct, this should read: `#define lcc_accept(void) accept(void`

## For the future:
Please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.
Please also specify the doxygen version used.

**Comment by xiaoyusu** [comment]
Thanks so much!  i`ve solve this problem. It`s true related to MACRO_EXPANSION enabled and EXPAND_ONLY_PREDEF disabled.

**Comment by xiaoyusu** [comment]
Add to ask for help~ emmm ....
while in a ".h" file, if #define is before the function declare, the api reference generate as accept() succeed.

but if #define is after function declare, it can`t successful generate in accept(), but in lcc_accept().
why?

wish for answer please~

**Comment by albert-github** [comment]
By head this is standard behavior, it won't work in source code either.

## As written before:

Please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.
Please also specify the doxygen version used.
