### ISSUE TITLE
Please consider relicensing of Javascript files

### ISSUE THREAD

**Issue by StefanBruens** [doxygen/doxygen#6901]
Currently, HTML documentation generated by doxygen includes three Javascript files licensed under GPLv2.

When an upstream project chooses to distribute prebuilt documentation inside the source tarball, strictly speaking the tarball has to be labeled "<PROJECT_LICENSE> AND GPL-2.0-only", although the GPL part only applies to a very small portion of the documentation.

This may be somewhat surprising, especially when considering:
> Documents produced by doxygen are derivative works derived from the input used in their production; they are not affected by this license. 

Can the following three files relicensed under a permissive license:
- menu.js
- dynsections.js
- search.js

(There is also menudata.js, but I doubt it qualifies as copyrightable code in the first place.)

**Comment by chbi** [comment]
+1 - a not so strict license would be appreciated.

At the moment a tarball with generated HTML doxygen documentation must be considered GPL-2.0. So all license obligations (https://www.ifross.org/en/what-obligations-are-involved-distributing-software-licensed-under-gplv2) must be fulfilled for API documentation.

**Comment by lrineau** [comment]
The license of those files is actually `GPL-2.0-or-later`.

**Comment by doxygen** [comment]
I agree that the GPL restrictions should not apply to the output generated by doxygen. I've changed the license of the Javascript code to MIT now to make that clear.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.18.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Comment by adam-sawicki-a** [comment]
This seems not to be resolved completely. While JavaScript libraries generated by Doxygen 1.9.1 now mention MIT license in their header comment, HTML files still contain small code snippets that mention GPL license, e.g.:

```HTML
<!-- Generated by Doxygen 1.9.1 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search','.html');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
</div><!-- top -->
```

**Comment by doxygen** [comment]
@adam-sawicki-a Indeed. I've just changed them.
