### ISSUE TITLE
Cannot build doc of Doxygen v1.8.15 on RHEL 7.X 

### ISSUE THREAD

**Issue by samding01** [doxygen/doxygen#6904]
I tried to install Doxygen v1.8.15 on RHEL 7.4 distro (x86_64), but it failed on `make docs` 
and cannot generate `doxygen_manual.pdf`. 
Installation follows  [installation instrution](http://www.doxygen.nl/manual/install.html)

In the step of `make docs` gets following errors:

         [ 98%] Generating Latex and HTML documentation.
         This is pdfTeX, Version 3.1415926-2.5-1.40.14 (TeX Live 2013)
          restricted \write18 enabled.
          entering extended mode
          (./_formulas.tex
          LaTeX2e <2011/06/27>
          Babel <v3.8m> and hyphenation patterns for english, dumylang, nohyphenation, lo
          aded.

           error: Problems running latex. Check your installation or look for typos in _formulas.tex and        check _formulas.log!
            [ 98%] Built target run_doxygen
           Scanning dependencies of target doxygen_pdf
           [100%] Generating Doxygen Manual PDF.
            This is pdfTeX, Version 3.1415926-2.5-1.40.14 (TeX Live 2013)
             \write18 enabled.
            entering extended mode
            (./doxygen_manual.tex
            LaTeX2e <2011/06/27>
            Babel <v3.8m> and hyphenation patterns for english, dumylang, nohyphenation, lo
            aded.

            make[3]: *** [doc/CMakeFiles/doxygen_pdf] Error 1
            make[2]: *** [doc/CMakeFiles/doxygen_pdf.dir/all] Error 2
            make[1]: *** [doc/CMakeFiles/docs.dir/rule] Error 2
            make: *** [docs] Error 2

The [_formulas.log](https://github.com/samding01/doxygen/blob/master/_formulas.log) does not shows errors except that 

      No file _formulas.aux.
      \openout1 = `_formulas.aux'.

Can you help me to find the what the problem is here?
By the way, build/installation on ubuntu 16.04 is good, no such problem

Thanks,

**Comment by albert-github** [comment]
I see that you are using `This is pdfTeX, Version 3.1415926-2.5-1.40.14 (TeX Live 2013)` this looks a bit old to me. I think a newer version is required, but be aware that this should be a version from before mid December 2018 as the versions after this date have a problem with the `tabu` package.

- Which version of LaTex / Tex Live  is installed on ubuntu 16.04 ?
- Is there a log file present? if so can you attach it to this issue?

**Comment by samding01** [comment]
@albert-github Thanks for response.
On ubuntu 16.04, latex is 

     # latex -v
      pdfTeX 3.14159265-2.6-1.40.16 (TeX Live 2015/Debian)
       kpathsea version 6.2.1
       Copyright 2015 Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).

**Comment by albert-github** [comment]
Please let us know if the given solution (update) works / is satisfactory for you so the issue can be closed.

**Comment by samding01** [comment]
@albert-github  check the `latex/doxygen_manual.log`, first found that it needs `listofitems.sty`,
so I downloaded it and then

       cp *.sty /usr/share/texmf/tex/latex/  
        mktexlsr

Now `latex/doxygen_manual.log` shows it needs `listofitems.tex` :

      \etb@tempcnta=\count150
       ) (/usr/share/texlive/texmf-local/texmf-compat/tex/latex/listofitems.sty
       ! I can't find file `listofitems.tex'.
       l.1 \input listofitems.tex

       (Press Enter to retry, or Control-D to exit)
       Please type another input file name
       ! Emergency stop.
       l.1 \input listofitems.tex

how and where I need to put this `tex` file?

**Comment by albert-github** [comment]
Best is to check on the ubuntu system where they are.
How they have to be placed I don't know but I assume when installing the relevant package (and not just the `*.sty`) it should work.

I checked on Windows: MikTeX and see:
```
C:\Program Files\MiKTeX 2.9\tex\generic\listofitems
C:\Program Files\MiKTeX 2.9\tex\generic\listofitems\listofitems.tex
C:\Program Files\MiKTeX 2.9\tex\latex\listofitems
C:\Program Files\MiKTeX 2.9\tex\latex\listofitems\listofitems.sty
```
under Cygwin I see:
```
User-PC:/usr/share/texmf-dist$ find . -name listofitem\*
./doc/generic/listofitems
./doc/generic/listofitems/listofitems-en.pdf
./doc/generic/listofitems/listofitems-en.tex
./doc/generic/listofitems/listofitems-fr.pdf
./doc/generic/listofitems/listofitems-fr.tex
./tex/generic/listofitems
./tex/generic/listofitems/listofitems.sty
./tex/generic/listofitems/listofitems.tex
```

**Comment by samding01** [comment]
Put `listofitems.tex` to  `latex/ ` solved the issue. Then further solved a few issues of  missing `*.sty`. 
Now found a new problem, see attached ` doxygen_manual.log`
[doxygen_manual.log](https://github.com/doxygen/doxygen/files/3023919/doxygen_manual.log).
It shows 
```
! Missing \cr inserted.
<inserted text>
                \cr
l.80 \end{longtabu}
...
==> Fatal error occurred, no output PDF file produced!

```
Any idea or hint to solve it?
Thanks,

**Comment by albert-github** [comment]
Best is to upgrade to Tex Live 2018 (or at least to 2015 as this is working on ubuntu), as otherwise you probably will keep having compatibility problems.

**Comment by samding01** [comment]
@albert-github `latex` is current the latest version in the repository of RHEL 7.x.
Do you know where is  the source package ? Is [here](https://github.com/TeX-Live/texlive-source)?

**Comment by albert-github** [comment]
RHEL packages tend to be lagging a little bit (I don't know which version they ship currently by default, but current version is 1.8.15).

I don't know where the official source package is but best is to look at the Tex Live site (e.g. https://www.tug.org/texlive/ or https://www.tug.org/texlive/acquire-netinstall.html)

**Comment by samding01** [comment]
@albert-github It got failed when building `texlive`.  Tried to build `pdftex` https://github.com/tex-mirror/pdftex that is installed as the previous version. But still had the errors in `make docs`

One question: I run the `Doxygen` unit test all passed, how much /what  impact is `make docs` for the usages of `doxygen`?

**Comment by albert-github** [comment]
The unit tests just use LaTeX for some formulas as it only generated XML output. The `make docs` generates HTML and LaTeX / pdf output. for the LaTeX / pdf  a much broader part of LaTeX is used (a.o. tables)

**Comment by Elnee** [comment]
I described how to fix that.
Take a look: [link](https://medium.com/@elnee/how-to-fix-doxygen-latex-errors-with-doxyparams-broken-tabu-package-3bca6ccefe7e)

**Comment by albert-github** [comment]
@Elnee 
- what did you describe?
- links to external sources are not that good as
  - as they might not be persistent
  - might contain virusses (I don't imply that this is the case but nowadays one has to be careful)
  
Please include the text in your comment.

**Comment by Elnee** [comment]
@albert-github 
Okay, I'm sorry. But I don't think you can catch a virus on medium.
That solution is for Arch Linux. But it's pretty much the same across distributions or different operation systems. Difference is only where the `tabu.sty` keeps.
Copy-paste:

* Download that file: https://github.com/tabu-fixed/tabu/blob/master/tabu.sty
* Now navigate to **/usr/share/texmf-dist/tex/latex/tabu/**
* Rename existing `tabu.sty` to `tabu.sty.backup`
* Copy downloaded `tabu.sty` with fixes to that directory

That's all.

**Comment by samding01** [comment]
@Elnee 
Following your suggestion, it still gets error (does not generate `doxygen_manual.pdf` on RHEL 7.x.
Here is output:

```
....
[ 98%] Generating Latex and HTML documentation.
This is pdfTeX, Version 3.1415926-2.5-1.40.14 (TeX Live 2013)
 restricted \write18 enabled.
entering extended mode
(./_formulas.tex
LaTeX2e <2011/06/27>
Babel <v3.8m> and hyphenation patterns for english, dumylang, nohyphenation, lo
aded.

error: Problems running latex. Check your installation or look for typos in _formulas.tex and check _formulas.log!
dvips: DVI file can't be opened: _formulas.dvi: No such file or directory
error: Problems running dvips. Check your installation!
[ 98%] Built target run_doxygen
Scanning dependencies of target doxygen_pdf
[100%] Generating Doxygen Manual PDF.
This is pdfTeX, Version 3.1415926-2.5-1.40.14 (TeX Live 2013)
 \write18 enabled.
entering extended mode
(./doxygen_manual.tex
LaTeX2e <2011/06/27>
Babel <v3.8m> and hyphenation patterns for english, dumylang, nohyphenation, lo
aded.

make[3]: *** [doc/CMakeFiles/doxygen_pdf] Error 1
make[2]: *** [doc/CMakeFiles/doxygen_pdf.dir/all] Error 2
make[1]: *** [doc/CMakeFiles/docs.dir/rule] Error 2
make: *** [docs] Error 2

```

**Comment by albert-github** [comment]
@samding01 the patch from @Elnee is only something for versions of LaTeX after mid of December 2018.
As far as I can see you have a TexLive version of 2013 and here I think it is a bit old and as indicated before this should be updated.

**Comment by albert-github** [comment]
Seen the remarks about versions of LaTeX and the problems there were with a.o. the tabu package in 1.8.16 some hings were changed.
Seen the fact that we are talking here about older versions of LaTeX and doxygen and the fact that there have not been recent reports about problems building doxygen on RHEL / Ubuntu I think the problems have been solved in the mean time.
