### ISSUE TITLE
Build function missing parameters with doxygen

### ISSUE THREAD

**Issue by xiaoyusu** [doxygen/doxygen#6907]
If i declare in a .h file like this:
`int functionA(x ,y) functionB(x, y);`
Doxygen will only read functionA. And at the list of modules in .chm, there will only show like this:
`int functionA(x, y) functionB(x`

why build like this, and if any solutions?

**Comment by albert-github** [comment]
What kind of syntax is this (I never saw it before, so I'm very curious.

Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.
Please also specify the doxygen version used.

**Comment by xiaoyusu** [comment]
for example:
https://github.com/lattera/glibc/blob/master/libio/stdio.h
354,355,356 line

**Comment by albert-github** [comment]
At the mentioned lines I see:
```
extern int snprintf (char *__restrict __s, size_t __maxlen,
		     const char *__restrict __format, ...)
     __THROWNL __attribute__ ((__format__ (__printf__, 3, 4)));
```
I cannot map this to:
```
int functionA(x ,y) functionB(x, y);
```
unless you mean the `__attribute__ ((__format__ (__printf__, 3, 4)))` part , for this I refer to the manual the chapter about preprocessing to 'remove' the non standard attribute.

**Note**
Please  attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? *Please don't add external links as they might not be persistent*.
Please also specify the doxygen version used.

**Comment by xiaoyusu** [comment]
en, its sure like your example. The functionB should be a compile option like __attribute__(x) or __printflike(x,x).  It may solved by this methods you advise.  I have a try , tks so much

**Comment by albert-github** [comment]
Like written in the question #6891 and again in this issue always:
- Attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.
- Also specify the doxygen version used.
