### ISSUE TITLE
Unmet dependencies

### ISSUE THREAD

**Issue by Juniortheone** [doxygen/doxygen#6910]
I was installing doxygen but this was the error message I got;
`The following packages have unmet dependencies: doxygen:Depends:libclang1-3.6 (>= 3.2) but it is not going to be installed E: Unable to correct problems,you have held broken packages.
I did some searching and found out that it is not from doxygen but libclang instead.I tried finding a solution to no avail. Any help?`

**Comment by albert-github** [comment]
Which version of doxygen do you try to install / build?
Which system do you try to install / build doxygen?
Did you install clang ?
Otherwise try to build without clang, with `-Duse_libclang=OFF`. But this should be the default.

**Comment by albert-github** [comment]
Would have been nice to leave a message about the reason of the problem, so others could learn from it.
