### ISSUE TITLE
Extra closing </div> on code fragments in HTML output.

### ISSUE THREAD

**Issue by Izmno** [doxygen/doxygen#6911]
Code fragments produced by inline sources (INLINE_SOURCES = YES) in HTML output have an extra closing </div>. Subsequent members are therefore not part of the 'contents' and 'doc-contents' div. 

(If relevant, bug was encountered using python code with Doxypypy preprocessor)

**Comment by albert-github** [comment]
Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.
Please also specify the doxygen version used.

**Comment by Izmno** [comment]
Excuse me, i was using an older version. The issue has long been resolved. 
My apologies.

**Comment by albert-github** [comment]
No problem.

Regarding the tag consistency a lot has been improved.
