### ISSUE TITLE
Option syntax for commands is unclear

### ISSUE THREAD

**Issue by cdgh19** [doxygen/doxygen#6920]
It just took me a couple of hours to figure out the correct syntax for adding the lineno option to the example command: `\example{lineno} ex.cpp`. One of the problems was that for example all of

- `\example {lineno} ex.cpp`
- `\example lineno ex.cpp`
- `\example [lineno] ex.cpp`
- `\example[lineno] ex.cpp`
- `\example[{lineno}] ex.cpp`

give the error message 
> warning: included file lineno is not found. Check your EXAMPLE_PATH.

This is inconsistent with the option syntax for other commands such as \param, where `\param [in] b description` is perfectly fine with the space between \param and [in].

Another cause of confusion was the use of braces within optional arguments, e.g. the curly braces in [\example](http://www.doxygen.nl/manual/commands.html#cmdexample) or the round braces in [\param](http://www.doxygen.nl/manual/commands.html#cmdparam). In both cases the optional arguments are just a single word, so I would have expected sharp <> braces instead.

Unfortunately the documentation is not very clear on the correct syntax for adding options to commands (or I just did not find the corresponding part of the documentation). Therefore I think a paragraph should be added to the top of the [commands documentation](http://www.doxygen.nl/manual/commands.html) explaining the correct syntax for using optional arguments.

In particular for the example command it might be useful to extend the example to use the lineno option.

**Comment by albert-github** [comment]
For `\param` you wrote 'round braces' but you probably mean 'square brackets'.

There is a distinction between `[in]` (and `[out]` and `[in,out]` an `{lineno}`. The `[in]` etc. is an optional attribute / argument to the command and the `{lineno}` is an option to the command.

When looking a `\tableofcontents` we see that here there are more options for the command possible all inside the curly brackets. With `\tableofcontents` it is clearly indicated like `'{'` that the curly brackets are necessary, so this ca be improved. Sometimes it is hard to see whether or not spaces can or cannot be present (for options it could be more clearly indicated).

Small examples of usage never hurt.

**Comment by cdgh19** [comment]
What I meant with 'round braces' and 'curly braces' is the following: in the documentation the example command is listed as `\example[{lineno}] <file-name>` with the curly brackets in `[{lineno}]` and the param command is listed as `\param [(dir)] <parameter-name> { parameter description }` with the additional  round brackets in `[(dir)]`. Are the round brackets in `[(dir)]` necessary, and if they are indeed necessary, what is their meaning? According to the top of the [Special commands](http://www.doxygen.nl/manual/commands.html) page in the documentation,

> If (round) braces are used the argument extends until the end of the line on which the command was found. 

but this rule does not seem to apply in this case. (I'm trying to give you the point of view from someone who very recently started using doxygen, and this part of the documentation is quite confusing to me.)

Thanks for clarifying the distinction between optional arguments and options to the commands. In my opinion this should definitely be stated in the documentation, where currently only optional arguments are explained and options to the commands are not mentioned at all.

Looking at the tableofcontents command also helped a lot with understanding the syntax.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6935

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Comment by b1100111** [comment]
I have doxygen v1.9.1 for windows and the lineno option seems broken on that.  I tried every combination and permutation it seems for hours.

\example{lineno} app.cpp

yields nothing but

\example app.cpp

works.

**Comment by albert-github** [comment]
I don't see any problem when running 1.9.1 with `\example{lineno}` compared to `\example`. I tried the default example as provided with doxygen in the documentation.
The information provided looks OK but maybe there is somewhere a small culprit.

When you see an issue please open a **new** issue and:
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.
