### ISSUE TITLE
doxygenGUI 1.8.15 has no SHOW_DIRECTORIES  configuration？

### ISSUE THREAD

**Issue by NicolasYL** [doxygen/doxygen#6921]
![image](https://user-images.githubusercontent.com/47812418/55849930-feca6b00-5b84-11e9-9f5e-bd183e0cfd3e.png)

Can someone tell me how to set  **SHOW_DIRECTORIES  = YES**?
thanks.
I use doxygenGUI in win10,not unix.

**Comment by albert-github** [comment]
Which version did you use on unix?
In the changelog of Release 1.8.1 (release date 19-05-2012) : 
> Changed the way indexes (Class,File,Namespace,Groups) are rendered:
> 
> There are now shown in a uniform way in the HTML output as a tree. Trees can be expanded and collapsed interactively (this makes USE_INLINE_TREES obsolete).
> 
> The class list now also shows namespaces and nested classes. The file list now also shows directories (this makes SHOW_DIRECTORIES obsolete).
> 
> Member sections are now each rendered in a separate table. This makes the HTML_ALIGN_MEMBERS option obsolete.
> 
> Note: If you use a custom header for the HTML output (HTML_HEADER) make sure you add the following:
> 
> <script type="text/javascript" src="$relpath$jquery.js"></script>
> <script type="text/javascript" src="$relpath$dynsections.js"></script>
> 
> Otherwise the interactivity of the trees does not work. 

So I think the problem is usage.

**Comment by NicolasYL** [comment]
> Which version did you use on unix?
> In the changelog of Release 1.8.1 (release date 19-05-2012) :
> 
> > Changed the way indexes (Class,File,Namespace,Groups) are rendered:
> > There are now shown in a uniform way in the HTML output as a tree. Trees can be expanded and collapsed interactively (this makes USE_INLINE_TREES obsolete).
> > The class list now also shows namespaces and nested classes. The file list now also shows directories (this makes SHOW_DIRECTORIES obsolete).
> > Member sections are now each rendered in a separate table. This makes the HTML_ALIGN_MEMBERS option obsolete.
> > Note: If you use a custom header for the HTML output (HTML_HEADER) make sure you add the following:
> > <script type="text/javascript" src="$relpath$jquery.js"></script>
> > <script type="text/javascript" src="$relpath$dynsections.js"></script>
> > Otherwise the interactivity of the trees does not work.
> 
> So I think the problem is usage.

Thank you for the reply!
**I use this in win10, not linux.  1.8.15 Doxygen GUI**
I mean i want this:
![image](https://user-images.githubusercontent.com/47812418/55863789-d2771480-5bad-11e9-8c80-50765290f589.png)
but actually  this:
![image](https://user-images.githubusercontent.com/47812418/55863846-f0dd1000-5bad-11e9-8b71-768dea0d95c2.png)

I can not find where to set **SHOW_DIRECTORIES**  in **windows**
here is my setting
![image](https://user-images.githubusercontent.com/47812418/55864112-677a0d80-5bae-11e9-8a71-2dbc1f38a716.png)
I try to **append  SHOW_DIRECTORIES  =YES in Doxyfile**,but it  doesn't seem to work.

**Comment by albert-github** [comment]
As written before, `SHOW_DIRECTORIES` does not exist anymore since version 1.8.1 .
When you have `SHOW_DIRECTORIES` in your Doxyfile you will get a message like:

> warning: Tag `SHOW_DIRECTORIES' at line 2523 of file `-' has become obsolete.
>          To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"

Are all your mentioned files in 1 directory or distributed over different sub-directories?

**Comment by NicolasYL** [comment]
> As written before, `SHOW_DIRECTORIES` does not exist anymore since version 1.8.1 .
> When you have `SHOW_DIRECTORIES` in your Doxyfile you will get a message like:
> 
> > warning: Tag `SHOW_DIRECTORIES' at line 2523 of file `-' has become obsolete.
> > To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
> 
> Are all your mentioned files in 1 directory or distributed over different sub-directories?
**different sub-directories**
how can i solve this problem?thank you!

**Comment by albert-github** [comment]
Ca you please run `doxygen -x` in the directory `D:\doxygen` and attach the result to this issue (or alternatively attach the file `D:\doxygen\Doxyfile` to this issue)?

**Comment by NicolasYL** [comment]
> Can you please run `doxygen -x` in the directory `D:\doxygen` and attach the result to this issue (or alternatively attach the file `D:\doxygen\Doxyfile` to this issue)?

![image](https://user-images.githubusercontent.com/47812418/55872833-8f726c80-5bc0-11e9-82ae-0f2e9a92d891.png)
well,i notice this warning,and then?

**Comment by albert-github** [comment]
Would always be nice to have a difference like this as text and not as an image:
- text is better readable
- text is easy to cut and paste to use in one's own tests

Regarding the `SHOW_DIRECTORIES` remove it from your Doxyfile as indicated.

I think the problematic setting here is `FULL_PATH_NAMES=NO`, should probably have the value `YES`.
Also have a look at the setting of `STRIP_FROM_PATH`.

**Comment by NicolasYL** [comment]
> STRIP_FROM_PATH

thanks a lot,  finally，It works!
![image](https://user-images.githubusercontent.com/47812418/55923384-e404fe80-5c37-11e9-959b-1ac1a748329e.png)
**I set FULL_PATH_NAMES=YES,and set  the STRIP_FROM_PATH is empty**
thanks for your reply again!
