### ISSUE TITLE
Hint: jQuery 3.4.0 was released

### ISSUE THREAD

**Issue by jschleus** [doxygen/doxygen#6930]
Not a real issue but a hint that jQuery 3.4.0 was released:

Excerpt from https://blog.jquery.com/2019/04/10/jquery-3-4-0-released/ :

> It’s been a while since our last release, but we expect this to be the last minor release in the 3.x branch, and then we will move on to the overhaul that will be jQuery 4.0. But before we get to 4.0, we’re excited to share the bug fixes and improvements included in jQuery 3.4.0.

The current Doxygen release 1.8.15 uses still jQuery 1.7.2 (the 1.x and 2.x branches no longer receive paches) while master uses 3.3.1 (see #6795).

**Comment by jschleus** [comment]
A small addition: Since the above mentioned release notes described also a minor vulnerability fix ("Object.prototype pollution"  when using `jQuery.extend(true, {}, ...)`) I have tried on a test system to replace the  jquery-3.3.1.min.js part (first two lines of the Doxygen  jquery.js) by the jquery-3.4.0.min.js file downloaded by https://code.jquery.com/jquery-3.4.0.min.js. At least at first glance it seems to work (but with the same performance problems while loading some bigger HTML pages reported in issue #6934) .

**Comment by ojousima** [comment]
Current (Doxygen 1.8.20) JQuery version is 3.4.1, so this probably could be closed?

Related, JQuery 3.4.1 has 2 vulnerabilities https://snyk.io/test/npm/jquery/3.4.1 and JQuery should be updated to 3.5.x. 
Related issue #7361, implementing the enchantment would fix this and future updates.

**Comment by albert-github** [comment]
We now use jQuery v3.6.0 so I think this problem has been solved in the mean time.
