### ISSUE TITLE
Slow web page loading of larger Doxygen HTML output files with jQuery 3.3.1

### ISSUE THREAD

**Issue by jschleus** [doxygen/doxygen#6934]
As administrator of a FOSS server I checked some offered  Doxygen output pages and noticed some unusually long load times. For some pages, the loading process did not even end within 10 minutes. The main web pages are rendered and displayed fast  but the "quick index" bar at the top and the tree-view part at the left are still missing and the browser component leads to a permanent 100% CPU load on the client system.

Here the optionally relevant differences to the default Doxyfile:

```
OPTIMIZE_OUTPUT_FOR_C  = YES
EXTRACT_ALL            = YES
EXTRACT_PRIVATE        = YES
EXTRACT_STATIC         = YES
WARN_IF_UNDOCUMENTED   = NO
RECURSIVE              = YES
SOURCE_BROWSER         = YES
REFERENCED_BY_RELATION = YES
REFERENCES_RELATION    = YES
GENERATE_TREEVIEW      = YES
TREEVIEW_WIDTH         = 160
GENERATE_LATEX         = NO
```
and especially for the `snd` package

```
 EXCLUDE                = old-music5.f
```

Since the server uses Doxygen master that uses now `jQuery 3.3.1`  (see #6795) I had the idea to replace on a nearly identical test system the file "jquery.js" (containing different merged minified JavaScripts) by the version used within the current Doxygen release 1.8.15 (`jQuery 1.7.2`).
And voilà, the loading times improved dramatically.

Here for an impression some exemplary rough page loading times for Linux Chromium and Firefox in seconds.

| Chrom. | Chrom. | Firefox | Firefox |   |    |    |
| ---: | ---: | ---: | ---: |  --: |  ---: | :--- |
| jQuery  3.3.1 |   jQuery 1.7.2 |  jQuery 3.3.1 |  jQuery 1.7.2 |    Bytes | Lines | URL  |
|        4 |        2 |       9 |       2 |   651568 |   663 | https://fossies.org/dox/rose-0.9.10.230/sageInterface_8h_source.html |
|       32 |        4 |      85 |       2 |  1605415 |   287 | https://fossies.org/dox/rose-0.9.10.230/cmdline_8cpp_source.html |
|      110 |        3 |     320 |       3 |  1647315 |   603 | https://fossies.org/dox/rose-0.9.10.230/FortranParserActionPrint_8c_source.html |
|      565 |        8 |   > 600 |       3 |  2938014 |  1030 | https://fossies.org/dox/rose-0.9.10.230/projects_2typeforge_2src_2json_8hpp_source.html |
|    > 600 |       47 |   > 600 |      13 | 11393391 |  2624 | https://fossies.org/dox/snd-19.3/xg_8c_source.html |

Comment from a layman: If the problem occurs the effect seems to increase "exponentially" (maybe related to the JavaScript complexity of the tree-view part). And with  `jQuery 1.7.2` in use Firefox seems a liitle bit faster, but with `jQuery 3.3.1` Chromium. 

P.S.: If you click on one of the links above `jQuery 3.3.1` is in use. And the mentioned `rose` package is relatively frequently replaced by new releases so that links may redirect to a page showing a link to the actual according Doxygen file at the bottom.

**Comment by doxygen** [comment]
Looks like the newer version of the jquery powertip plugin is causing the slowdown. The more tooltips on a page, the slowing it gets. I've filed an issue for it, see reference above.

**Comment by doxygen** [comment]
In [this commit](https://github.com/doxygen/doxygen/commit/7b745c4b8182430d3eacde1cb1520730fee1b01e) I've included a modified version of the powertip plugin that has the same performance as the old version (and updated jquery to 3.4.1) . Let me know if you still see performance issues.

**Comment by jschleus** [comment]
Thanks, that are great news and makes Doxygen for some affected projects usable again.

So I installed the current Doxygen master, forced new Doxygen runs for the current packages `rose-0.9.11.14` and `snd-19.4` and tested the above URLs (using each the shown redirect links to the current version) and both Firefox as also Chromium loaded the page within few seconds (Firefox a little bit faster).

Also the "record holder" https://fossies.org/dox/snd-19.4/xg_8c_source.html loads again within 12 secs (Firefox) respectively 35 secs (Chromium). Although in this case the improved "old" loading times may still try the patience of many users.

A hint for other testers: Clear your browser cache before testing (at least remove Doxygen's `jquery.js` file).

**Comment by albert-github** [comment]
Seen the last comment I think the problem has been solved in the mean time.
