### ISSUE TITLE
Tcl : separate continued lines joined in source listing

### ISSUE THREAD

**Issue by hannupeltonen** [doxygen/doxygen#6941]
Doxygen 1.8.16

A Tcl source line that ends with a backslash and the next line are sometimes joined in the generated source browser window. As a result, documentation links to the source file lines ("Definition at line N of file X.") point to wrong lines.

Tcl source file:
<pre>
set x \
  [list \
     a \
    ]
</pre>

Configuration file:
<pre>
SOURCE_BROWSER         = YES
</pre>

Result:

![image](https://user-images.githubusercontent.com/49939182/56643334-1f64eb80-6682-11e9-8725-874276ef522d.png)

**Comment by albert-github** [comment]
It is always good to attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.

As in this case either some documentation has to be added or `EXTRACT_ALL` has to be set as well.

**Comment by hannupeltonen** [comment]
Here is the zip file with the example "x.tcl" and "Doxyfile".

[doxygen-bug.zip](https://github.com/doxygen/doxygen/files/3111432/doxygen-bug.zip)

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #6942

**Comment by hannupeltonen** [comment]
Seems to work fine now. Thank's for the amazingly quick fix!

**Comment by hannupeltonen** [comment]
I just realized that I accidentally used bad wording. I did not mean "quick fix" in its disparaging sense. I simply want to thank you for fixing the problem so quickly.

**Comment by albert-github** [comment]
@hannupeltonen no offense was taken at all from your comment, it was regarded as a thank you by me and as confirmation that it did work for you.

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
