### ISSUE TITLE
@ingroup causes entire comment to become part of @brief

### ISSUE THREAD

**Issue by jwakely** [doxygen/doxygen#6952]
The docs for `@brief` say "A brief description ends when a blank line or another sectioning command is encountered." This doesn't seem to always be true.

Given this source, the `@brief` does not end at the blank line:
````
/// @defgroup foo Foo

/**
 * @brief E-flat walks into a bar.
 * @ingroup foo
 *
 * The bartender says, “Sorry, we don't serve minors.”
 */
struct Bar { };
````

The html output includes the full description in the `@brief` description, without even a space character between the `@brief` text and the rest of the text:
````
<div class="contents">

<p>E-flat walks into a bar.The bartender says, “Sorry, we don't serve minors.”  
 <a href="structBar.html#details">More...</a></p>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>E-flat walks into a bar.</p>
<p>The bartender says, “Sorry, we don't serve minors.” </p>
</div><hr/>The documentation for this struct was generated from the following file:<ul>
<li>test.cc</li>
</ul>
</div><!-- contents -->
````

Inserting a blank line between the `@brief` and `@ingroup` fixes it (or moving the `@ingroup` after the rest of the description).

The same thing happens with `@class`:
````
/**
 * @brief E-flat walks into a bar.
 * @class Bar
 *
 * The bartender says, “Sorry, we don't serve minors.”
 */
````

It seems that the `@ingroup` and `@class` commands consume the following blank line, so that the parser thinks the rest of the description is part of the `@brief`.

**Comment by albert-github** [comment]
Looks to me as a duplicate of #6945

**Comment by jwakely** [comment]
Yes indeed, sorry I missed it.

**Comment by albert-github** [comment]
It pointed to another command as well: `\ingroup` so I added it to my comment in the original issue together with `\weakgroup`.
In case there are more 'candidates' don't hesitate to leave a new comment.
