### ISSUE TITLE
If CREATE_SUBDIRS = YES all dot-images are recreated

### ISSUE THREAD

**Issue by cmorty** [doxygen/doxygen#6959]
Version: 1.8.15 Windows
Output: SVG

`CREATE_SUBDIRS = NO` work fine (or at least only about 10% if the dot-images are recreated, although nothing has changed)

**Comment by albert-github** [comment]
What do you want to tell us here, is this a comment to the issue #6958? In case the later, add this in the question or as a separate comment to the issue #6958, otherwise explain what you intend with this issue / what the problem is.

**Comment by cmorty** [comment]
Ok, I was able to reproduce this perfectly turning `CREATE_SUBDIRS` on and off. Now it works like a charm Same folder and everything (`git diff`` is happy). (The only thing I did was update msys to build doxygen) -> Closing. Sorry for the noisr.
