### ISSUE TITLE
Any plans to make new release?

### ISSUE THREAD

**Issue by kloczek** [doxygen/doxygen#6972]
In ~5 months have been committed many changes.
IMO it would be good to have soon new release with new code base :)

**Comment by Boddlnagg** [comment]
Yes, please! Especially https://github.com/doxygen/doxygen/issues/6882 is a blocker for us ...

**Comment by doxygen** [comment]
In the coming holiday period I'll make a new release...

**Comment by albert-github** [comment]
In the mean time there were some releases....

**Comment by kloczek** [comment]
Yep. Closing.
