### ISSUE TITLE
CLANG_ASSISTED_PARSING & example{lineno}

### ISSUE THREAD

**Issue by Mizux** [doxygen/doxygen#6993]
# Description
```
$ doxygen -v
1.8.13
```

When using `CLANG_ASSISTED_PARSING = YES` on the following code
```cpp
/** @example{lineno} foo.cpp
 * A small description.
*/
```

# Observed
Example page (`html/example.html`):
```
# Examples
Here is a list of all examples:
* lineno (point to file:///.../html/lineno-example.html)
```
if I clic the link (`lineno-example.html`) I got the page of the example containing:
```
# lineno
} foo.cc A small description.
```

# Expected
Like when using  `CLANG_ASSISTED_PARSING = NO` example are correctly parsed etc...

# Workaround
disable the option, but now my example don't have the line number column....

note: I tried to build doxygen from source with `cmake -H. -Bbuild -Duse_libclang:BOOL=ON -DCMAKE_PREFIX_PATH=/usr/share/llvm-4.0` but Ubuntu (< 18.10) seems to have a broken install of ClangConfig.cmake....

**Comment by albert-github** [comment]
Looks like a complete description but as small details can make the difference:
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.
- Please also specify the doxygen version used.

**Comment by Mizux** [comment]
@albert-github on my way to provide a pet project...

**Comment by albert-github** [comment]
Although no pet project yet, 
I had a quick look at the issue but I think the main problem might be the fact that `@example` has no `lineno` option in version 1.8.13. This option was first introduced in version 1.8.15.

**Comment by Mizux** [comment]
@albert-github dumb question: Is it possible to have some dox comment per doxygen version kind of:
```cpp
/** 
 * @IF_VERSION_LESS_THAN 1.8.15
 * @example foo.cpp
 * @ELSE
 * @example{lineno} foo.cpp
 * @ENDIF 
*/
```

**Comment by albert-github** [comment]
I was looking at the "dumb: question but it is not such a "dumb" question.
With a lot of tricks there would be some possibilities but no directly in doxygen but in the starting environment, one should define some enabled section (``ENABLED_SECTIONS`) or with different  include files `@INCLUDE` and add these to the Doxyfile. 
I didn't try it and will be tricky.
