### ISSUE TITLE
Regression on HTML display in Firefox (and IE11)

### ISSUE THREAD

**Issue by albert-github** [doxygen/doxygen#6994]
When we have a very simple example (is also valid for complex examples as found by e.g. Fossies.org):
- directory with a `Doxyfile` containing just the statement `GENERATE_TREEVIEW=YES`

and we run on this the current doxygen master version we get in Firefox (and IE 11):

![wrong](https://user-images.githubusercontent.com/5223533/57862712-18e91000-77f9-11e9-9fcf-ecb9e2d66190.jpg)

so without the footer but with a scroll bar at the right hand side. We would have expected:

![OK](https://user-images.githubusercontent.com/5223533/57862782-34ecb180-77f9-11e9-891e-1dfe3da5a5d0.jpg)

This result we  obtain straight away with e.g. Google chrome. Firefox and Chrome were tested on Windows and Linux.

When doing a small resize the scroll bar disappears and the footer is shown again.

When replacing the `jquery.js` with the `jquery.js` version from doxygen 1.8.15 the results are OK again as well. 

 So I added in menu.js:
```
  $('#main-menu').resize();
```
after
```
  $('#main-menu').smartmenus();
```
and this works, but there might be some drawbacks (not observed yet) like longer loading time / flashing display due to `resize()` and maybe (not found by me) better solutions by rearranging the code building the window.

**Comment by jschleus** [comment]
To further narrow down the problem: If one replace the jquery.js core library itself (version 3.31) in the Doxygen jquery.js file by the version 2.2.4 (or older) the problem vanishes but it appears again if one use the next higher version 3.0.0. So a change between these releases could be partly responsible. The version of the jquery.js core library in  doxygen 1.8.15 is still 1.7.2.

**Comment by albert-github** [comment]
With the doxygen 1.8.16 version we get the wrong resuls a described.

With the current, 1.9.8, version the results are OK (though we get a warning about `warning: No files to be processed, please check your settings, in particular INPUT, FILE_PATTERNS, and RECURSIVE` which is correct but irrelevant here.

I think the problem has been solved in the mean time
