### ISSUE TITLE
Regression on re-entrant sqlcode 

### ISSUE THREAD

**Issue by albert-github** [doxygen/doxygen#7003]
When we have a small example (using default Doxyfile:

> \```sql
> SELECT a.id, a.name, b.id, b.name FROM foos AS a JOIN foos AS b ON a.parent = b.id;
> \```

and create doxygen with:
```
cd build
make
touch ../src/sqlcode.l
make LEX_FLAGS=-d
```
the situation before the re-entrant code possibility was integrated was that we got the debug output for the sql code fragment after the integration the code does not appear anymore.
(Might it be that the `yy_flex_debug` setting is not stored properly in the `struct yyguts_t` ?).

Problem was discovered after the integration of the pull request #7001 wheer the missing printlex statements were added and we now got in a "normal" (so without `LEX_FLAGS=-d`) executable the line:
```
--finished lexical analyzer: sqlcode.l
```

The example: [example.zip](https://github.com/doxygen/doxygen/files/3206974/example.zip)

This problem might also apply to the other re-entrant lexers (though I didn't notice it there yet).

(@groleo please have a look too).

(I did a quick search, maybe https://stackoverflow.com/questions/48850242/thread-safe-reentrant-bison-flex gives some extra information at the end of the answer)

**Comment by groleo** [comment]
oh, i haven't tested with the debug flag enabled. I'll test and fix it.
Thanks a lot for testing and reporting.
