### ISSUE TITLE
C++: Forwarding (templated) constructor yields '@param argument not found' error

### ISSUE THREAD

**Issue by q-p** [doxygen/doxygen#7008]
The following example yields an unexpected warning:
`Test.cpp:10: warning: argument 'foo' of command @param is not found in the argument list of Derived::Base(class Foo)`
even though this argument exists and is documented in `Base::Base(...)`.

The error did not occur with doxygen 1.8.13.

This uses constructor-forwarding (which is a C++11 feature) to inherit the (templated) constructor of the base-class; the error seems to be reported of the context of the derived class (as the error mentions `Derived::Base`).

```c++
/*
Running doxygen 1.8.15 on this file (default config) yields:
Test.cpp:10: warning: argument 'foo' of command @param is not found in the argument list of Derived::Base(class Foo)
*/

/// My base class.
struct Base
{
  /// Constructor.
  /**
   * @tparam Foo Template arg.
   * @param foo Argument.
   */
  template<class Foo>
  explicit Base(const Foo &foo)
  { }
};

/// My derived class.
struct Derived : Base
{
  // forward constructor(s)
  using Base::Base;
};
```

**Comment by albert-github** [comment]
With the doxygen version 1.8.15 we see the warning as indicated, with the current doxygen version (1.9.8) this warning is gone.

I think this problem has been solved in the mean time.
