### ISSUE TITLE
strange parsing issue with groups

### ISSUE THREAD

**Issue by ndee02** [doxygen/doxygen#7013]
I encountered a strange parsing issue related to groups. It seems that doxygen behaves differently whether you put a command in the same line you start a doxygen comment or not.
The particular example I could isolate is about groups and generation of call graphs.
Closing a group like this is fine:
```
/**
  * \}
  */
```
But closing it like this is bad:
```
/** \}
*/
```

Bug closing a group like this will cause not only ommission of the call graph of a particular function, but also not haveing it showing up in any other call graph.

See line 18 in attached example file group.bug.c:
[group_bug.zip](https://github.com/doxygen/doxygen/files/3229258/group_bug.zip)

Edit: used Doxygen 1.8.15 64bit Windows

**Comment by albert-github** [comment]
In the doxygen 1.8.15 version I see missing call graphs and missing parts of call graphs.
In doxygen version1.9.3 I see the complete set of complete call graphs.

I think the problem has been solved in the mean time.

**Comment by ndee02** [comment]
Confirmed, bug seems to be fixed since version 1.8.17. Thanks for revisiting this ticket!
