### ISSUE TITLE
Warning about missing item in INCLUDE_PATH

### ISSUE THREAD

**Issue by albert-github** [doxygen/doxygen#7021]
Doxygen version 1.8.15 and current master (June 2, 2019)

Test case: [example.zip](https://github.com/doxygen/doxygen/files/3244751/example.zip)

When having 2 include files and the second file is included inside curly brackets we can get the message like:
```
Include_2.h:9: warning: include file stdio.h not found, perhaps you forgot to add its directory to INCLUDE_PATH?
```
First include file (`Include.h`):
```
#ifndef Include_header
#define Include_header

#include <stdio.h>

namespace my_space
{
  #include <Include_2.h>
}
#endif // Include_header
```

Second include file `Include_2.h`:
```
#ifndef Include_2_h
#define Include_2_h

#if defined(__cplusplus) || defined(c_plusplus)
extern "C" {
#endif


#include <stdio.h>

#if defined(__cplusplus) || defined(c_plusplus)
}
#endif

#endif
```

some small notes:
- problem is caused by the inclusion inside the namespace
- similar problems might occur when setting `__cplusplus` or `c_plusplus`
- just adding `stdio.h` (in this case when detected by processing the first file (`Include.h`) won't work as the problem will reappear when the processing order is different.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7022

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Comment by sparist** [comment]
I am still seeing this in 1.8.17.

**Comment by albert-github** [comment]
I See the issue with version 1.8.15 (the version against which the this issue was posted), but in the versions 1.8.16 and 1.8.17 I don't see the warning anymore.

@spartist 
- What do You see? 
- Best is to create a new issue with a reference to this issue and please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.
