### ISSUE TITLE
multiple @param sections when function implemented twice

### ISSUE THREAD

**Issue by jacob-keller** [doxygen/doxygen#7040]
Doxygen 1.8.15 warns about multiple @param documentation sections when we have a function that has two implementations in separate files. (only one gets used, depending on flags at compile time).

i.e. `header.h` has a function declaration:
```
void my_function(int a);
```
`implementation_a.c` has a function definition

```
/**
 * my_function
 * @brief a function
 * @param a: a parameter
 *
 * Long description
 */
void my_function(int a)
{
 ...
}
```

`implementation_b.c` has a different function definition
```
/**
 * my_function
 * @brief a function
 * @param a: a parameter
 *
 * Long description
 */
void my_function(int a)
{
 ...
}
```

This warning occurs likely because it's treating these two as "one" function, when it's really the fact that we have two ways of compiling that load different files.

We could move the doxygen comment to the header file, but all of our function comments are at site of implementation currently.

I suppose we could find a way to avoid scanning both copies at the same time.. I'm not 100% sure how to do that.

Is there some other way to avoid this warning?

**Comment by albert-github** [comment]
When you select at compile time just one of the files you can probably do:
- make 2 doxygen runs as well where you only include the used files through the INPUT tag
- run doxygen once but use the INPUT tag which selects one set of the files or use the EXCLUDE tag to exclude as set of files.

**Comment by jacob-keller** [comment]
Running two builds with an EXCLUDE tag works well for me.
