### ISSUE TITLE
bodyfile, bodystart, bodyend not found 

### ISSUE THREAD

**Issue by erez-o** [doxygen/doxygen#7067]
Hi, 

`bodyfile`, `bodystart`, `bodyend` do not appear in generated xml file.

For example, function `InitEXRImage` that is defined at https://github.com/erez-o/tinyexr/blob/master/tinyexr.h/#L302 and body on the same file at https://github.com/erez-o/tinyexr/blob/master/tinyexr.h/#L12671.

Doxygen xml produces a location tag without body:
```xml
<location file="tinyexr.h" line="302" column="13" declfile="tinyexr.h" declline="302" declcolumn="13"/>
```
 
Possibly has to do with function being `extern`?

To reproduce:
- repo is https://github.com/erez-o/tinyexr/
- xml output at https://doxiz.com/api/doxygen-xml/tinyexr/master/0/
- cfg output at https://doxiz.com/api/doxygen-cfg/tinyexr/master/0/
- doxygen from 2.5 months ago, https://github.com/doxygen/doxygen/tree/16d025c8a08b485f5d43ade0986d716bd6aa06f8

Many thanks

**Comment by albert-github** [comment]
As the references to the repository might not be persistent so can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.

**Comment by erez-o** [comment]
Attaching files:

[tinyexr.zip](https://github.com/doxygen/doxygen/files/3307579/tinyexr.zip)

[tinyexr.cfg.txt](https://github.com/doxygen/doxygen/files/3307585/tinyexr.cfg.txt)

[tinyexr.xml.txt](https://github.com/doxygen/doxygen/files/3307588/tinyexr.xml.txt)

The cfg & xml are .txt because github doesn't allow cfg/xml file formats.

**Comment by albert-github** [comment]
Looking at the file `tinyexpr.h` we see that there is a `#ifdef TINYEXR_IMPLEMENTATION` but no setting of `TINYEXR_IMPLEMENTATION`
I think that setting:
```
PREDEFINED = TINYEXR_IMPLEMENTATION=1
```
solves the issue.

I think the problem is usage
