### ISSUE TITLE
tables can't be recreated from generated xml data

### ISSUE THREAD

**Issue by erez-o** [doxygen/doxygen#7069]
Hi, 

Generated xml data seems to not conserve whitespace extracted from the comments. This affects multiple markdown style comments like tables, definition lists, etc.

Attaching an example of how a table written in comments appears in the xml:

an example comment (taken from class `out_of_range`) in the attached repository in path `single_include/nlohmann/json.hpp`, line 399

```
name / id                       | example message | description
------------------------------- | --------------- | -------------------------
json.exception.out_of_range.401 | array index 3 is out of range | The provided array index @a i is larger than @a size-1.
json.exception.out_of_range.402 | array index '-' (3) is out of range | The special array index `-` in a JSON Pointer never describes a valid element of the array, but the index past the end. That is, it can only be used to add elements at this position, but not to read it.
json.exception.out_of_range.403 | key 'foo' not found | The provided key was not found in the JSON object.
json.exception.out_of_range.404 | unresolved reference token 'foo' | A reference token in a JSON Pointer could not be resolved.
json.exception.out_of_range.405 | JSON pointer has no parent | The JSON Patch operations 'remove' and 'add' can not be applied to the root element of the JSON value.
json.exception.out_of_range.406 | number overflow parsing '10E1000' | A parsed number could not be stored as without changing it to NaN or INF.
json.exception.out_of_range.407 | number overflow serializing '9223372036854775808' | UBJSON and BSON only support integer numbers up to 9223372036854775807. |
json.exception.out_of_range.408 | excessive array size: 8658170730974374167 | The size (following `#`) of an UBJSON array or object exceeds the maximal capacity. |
json.exception.out_of_range.409 | BSON key cannot contain code point U+0000 (at byte 2) | Key identifiers to be serialized to BSON cannot contain code point U+0000, since the key is stored as zero-terminated c-string |
```

and in the generated xml:
```
<para>
name / id | example message | description ------------------------------- | --------------- | ------------------------- json.exception.out_of_range.401 | array index 3 is out of range | The provided array index
<emphasis>i</emphasis>
is larger than
<emphasis>size-1</emphasis>
. json.exception.out_of_range.402 | array index '-' (3) is out of range | The special array index `-` in a JSON Pointer never describes a valid element of the array, but the index past the end. That is, it can only be used to add elements at this position, but not to read it. json.exception.out_of_range.403 | key 'foo' not found | The provided key was not found in the JSON object. json.exception.out_of_range.404 | unresolved reference token 'foo' | A reference token in a JSON Pointer could not be resolved. json.exception.out_of_range.405 | JSON pointer has no parent | The JSON Patch operations 'remove' and 'add' can not be applied to the root element of the JSON value. json.exception.out_of_range.406 | number overflow parsing '10E1000' | A parsed number could not be stored as without changing it to NaN or INF. json.exception.out_of_range.407 | number overflow serializing '9223372036854775808' | UBJSON and BSON only support integer numbers up to 9223372036854775807. | json.exception.out_of_range.408 | excessive array size: 8658170730974374167 | The size (following `#`) of an UBJSON array or object exceeds the maximal capacity. | json.exception.out_of_range.409 | BSON key cannot contain code point U+0000 (at byte 2) | Key identifiers to be serialized to BSON cannot contain code point U+0000, since the key is stored as zero-terminated c-string |
</para>
```

In the above example, `\n` was not conserved, and multiple `space` charachters turned to one (name / id).

Attaching files
[json-3.6.1.zip](https://github.com/doxygen/doxygen/files/3308915/json-3.6.1.zip)
[json_v3.6.1.cfg.txt](https://github.com/doxygen/doxygen/files/3308916/json_v3.6.1.cfg.txt)
[json_v3.6.1.xml.txt](https://github.com/doxygen/doxygen/files/3308917/json_v3.6.1.xml.txt)

Many thanks

**Comment by albert-github** [comment]
I enabled the HTML version as well (always a good way to check) and saw that the table was not rendered at all.
Looking into the `json_v3.6.1.cfg.txt` I see that `MARKDOWN_SUPPORT=NO` setting the `MARKDOWN_SUPPORT=YES` solves the problem in HTML and probably in XML as well.

Any special reason why to set `MARKDOWN_SUPPORT=NO` ? When there is a reason for it the table has the be reformulated into a table with the `<table>` `<tr>`etc. HTML tags (see documentation).

I think the problem is usage.

**Comment by erez-o** [comment]
Hi, 

1. As you thought, when `MARKDOWN_SUPPORT=YES` the tables appear in the xml as `<table>`, `<tr>` etc.

2. When changing to `MARKDOWN_SUPPORT=YES`, several headings stop appearing. Attaching the xml file with `MARKDOWN_SUPPORT=YES`, same package as before. Please compare the xml from before and this new one, and search for `<para>#### Behavior</para>`

3. With regards to usage, I think that there isn't a standard markdown anymore. There are so many flavors of markdown and extensions, commonmark, RestructuredText etc. that people can write in different formats. 
    For example, in python which is officially supported by doxygen, people write quite exclusively in rst and there's no way to extract the original comments (with whitespace) because both `MARKDOWN_SUPPORT=NO` and `MARKDOWN_SUPPORT=YES` dirties the rst code comments.

4. Because of (3), I think that when `MARKDOWN_SUPPORT=NO` the extracted comments should be as raw as possible, and conserve whitespace. I think this will also fit the doxygen docs, or at least as I understood them ( http://www.doxygen.nl/manual/markdown.html, heading `Debugging of problems`, "Anything that does not fit the Markdown syntax is simply passed on as-is" )

Many thanks again

[json_v3.6.1.xml.new.txt](https://github.com/doxygen/doxygen/files/3311994/json_v3.6.1.xml.new.txt)

**Comment by albert-github** [comment]
2. there are in the current master version some problems with the headers. A proposed pull request has already been made (by head #7012).
3. indeed it is a pity that there is no real standard for markdown. Note though that restructured text is completely different from markdown (and currently not supported by doxygen, there are no plans either at least as far as I know)

**Comment by erez-o** [comment]
Thanks for your response, 

Regarding (3), having the option to extract raw comments and preserve whitespace, allows future committers to support their own parser (other flavored markdown, rst etc). Without it, it can't be done because the original whitepsace aren't reproducible.

Thx again.
