### ISSUE TITLE
Python comments not parsed as markdown in the xml

### ISSUE THREAD

**Issue by erez-o** [doxygen/doxygen#7072]
All Python markdown comments appear unformatted as `<verbatim>` in the xml. 

No difference if `MARKDOWN_SUPPORT=YES` or `NO`. 

It does seem that whitespace is preserved in both cases. I also tried the table example given in #7069.

1. I think that if `MARKDOWN_SUPPORT=YES` you should activate markdown for python as well.

2. Related to #7069 - there may be an easy fix - if  `MARKDOWN_SUPPORT=NO`, regardless of the language, output `<verbatim>` with whitespace preserved like you currently do for python.

Attaching files

Many thanks

[try.cfg.txt](https://github.com/doxygen/doxygen/files/3319475/try.cfg.txt)
[try.xml.txt](https://github.com/doxygen/doxygen/files/3319476/try.xml.txt)
[try.zip](https://github.com/doxygen/doxygen/files/3319480/try.zip)

**Comment by albert-github** [comment]
This is by design that all `"""` comments appear as verbatim possibility.
The solution for this to use `"""!`

I think the proposed patch "Using Python docstrings" (#7575) explains this a bit better

So I think this is usage
