### ISSUE TITLE
fatal error: 'CoreServices/CoreServices.h' file not found

### ISSUE THREAD

**Issue by engeir** [doxygen/doxygen#7090]
When installing [doxygen](http://doxygen.nl/download.html#gitrepos) using `git` and then `make` on Mac I get --- after running `make` --- the error
~~~~
/Users/eirikenger/doxygen/qtools/qthread_unix.cpp:48:10: fatal error: 'CoreServices/CoreServices.h' file not found
#include <CoreServices/CoreServices.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~
When doing `locate /CoreServices.h` in terminal I get
~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Versions/A/Headers/CoreServices.h
~~~~~
Any idea why this error occur and how to fix it?

**Comment by albert-github** [comment]
- Please specify the mac version you are using
- which commands are you using to build?
   - `git ...` (to get repository)
   - `cd doxygen` (to go to the right directory)
    - `mkdir build`
    - `cd build`
    - `cmake -G "Unix Makefiles" -Dbuild_doc=ON -Dbuild_wizard=ON ..`
    - `make`

**Comment by engeir** [comment]
I'm running macOS Mojave v10.14.5.

I tried building with
~~~~~
git clone https://github.com/doxygen/doxygen.git
cd doxygen
mkdir build
cd build
cmake -G "Unix Makefiles" ..
make
~~~
~~~
which is when I got the error.

**Comment by albert-github** [comment]
I myself have no experience with a Mac, but my guess is that some (system / compiler) files have not been installed.

I did search for:
```
fatal error: 'CoreServices/CoreServices.h' file not found
```
and got quite a few hits, maybe something give a hint here (as said I myself have no experience with a Mac so it is hard to comment).

**Comment by doxygen** [comment]
I'm still running on MacOSX 'El capitan' myself, but sounds like an XCode
installation issue.
Maybe one of these help?
h <https://github.com/rjeczalik/notify/issues/165>
ttps://github.com/rjeczalik/notify/issues/165
<https://github.com/rjeczalik/notify/issues/165>
https://github.com/ethereum/go-ethereum/issues/17940
https://github.com/r-lib/fs/issues/150

Regards,
  Dimitri

**Comment by engeir** [comment]
Thanks, [this](https://github.com/ethereum/go-ethereum/issues/17940#issuecomment-434970303) fixed it for me.
