### ISSUE TITLE
Doxygen does not generate error/warning message for unbalanced group markers "@{"..."@}"

### ISSUE THREAD

**Issue by reylau** [doxygen/doxygen#7102]
Hello Albert,

I have joined a fully working example.

Using groups, I am building a hierarchy to classify functions. In the header of ModuleInterface1_1(), I have inserted a group start marker "@{". It is not balanced with any group end marker "@}", but Doxygen does not generate any warning/error message. Why?

It is important that Doxygen generates a message to avoid such error, which result in undesired side-effects, as seen below.

Because of this unbalanced marker, every function behind ModuleInterface1_1() is included in the "Module Interface > Module Interface 1" group, and for those functions which should be 
in fact in other groups, these are also reported there! 

E.g. ModuleInterface2() is included in "Module Interface > Module Interface 1" and in "Module Interface > Module Interface 2"; 
PrivateModuleFunction2() is included in "Module Interface 1" and in "Module Implementation > Private Module Functions", etc.

Best regards

Laurent
[Documentation - LED Bug.zip](https://github.com/doxygen/doxygen/files/3359873/Documentation.-.LED.Bug.zip)

**Comment by albert-github** [comment]
This is a program issue tracker and there are more developers around who might now feel excluded.

You ran with version 1.8.14 what happens with the current 1.8.15 version or even better with the current master version?

The attached example is missing `header.html` so I straight away get:

> error: tag HTML_HEADER: header file `header.html' does not exist

It is sometimes better to include a picture of the current state and the requested state, though in this case a requested state is unknown (the question is where should the `@}` be placed, or should the `@{` be omitted).

From the description I get that the current state is:
![current](https://user-images.githubusercontent.com/5223533/60678232-1cf1ef80-9e84-11e9-8ccb-ffcf589fac9c.jpg)


and that the guessed requested stated would be (I removed the `@{` from `src\Led.c`);
![requested](https://user-images.githubusercontent.com/5223533/60678260-33984680-9e84-11e9-8456-bb38ff58264c.jpg)

So actually the current state is the only thing that can be given, but it would be good to have a warning about the `@{`.

@reylau  Are the above current / requested states correct? 

A secondary question is "is it from the **doxygen** point of view possible that the `@{` and `@}` are in different files"? (@doxygen ?)

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7105

**Comment by reylau** [comment]
Hello everyone,

I am sorry if someone felt excluded, this was not my intention, but so far only Albert has answered me in all the interactions I had about Doxygen...

My only point is simple. Currently, if there is a missing end group marker @}, as in the example I have sent, Doxygen does not generate any warning / error.

Desired: Doxygen should generate a warning / error if there is a missing end group marker to help the user in correctly documenting his code. In the particular example, that would have helped me to immediately discover the incompletely defined group and take the appropriate decision (either add the missing end group marker or remove the group starter).

So you have guessed the states correctly.

BR

Laurent

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
