### ISSUE TITLE
Doxygen generates random file names for each build

### ISSUE THREAD

**Issue by fatihbahceci** [doxygen/doxygen#7103]
Doxy Version 1.8.15

Hello is there an option for static file names. 
Doxygen generates random file names for each build like dir_cc8550c7b87c6e83a228203ed7f09416.html. Therefore, unnecessary changes and commits occur in "git repo".

**Comment by albert-github** [comment]
Cross posted from: https://stackoverflow.com/questions/56899135/doxygen-generates-random-file-names-for-each-build

Why would one store generated results in a repository? The generated name shold be constant unless the names of the original directory on disk changes.

- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.
- Please also specify the doxygen version used.

**Comment by fatihbahceci** [comment]
Sory my bad. I realized that it only happens when the folder structure changed.
