### ISSUE TITLE
Doxygen commands not recognized if verbatim block within a note

### ISSUE THREAD

**Issue by reylau** [doxygen/doxygen#7130]
I have joined an example.

There are two groups, defined in the example. The input / outputs are stored within "Cases".
[Doxygen Bug.zip](https://github.com/doxygen/doxygen/files/3407020/Doxygen.Bug.zip)

Group 1 uses a `@verbatim` block within a `@note` block. The preceding `@warning` and the `@note` start are not properly understood (looks that those are interpreted as code), the text after the note ("Note 2") is fine.

Group 2 is the same case but without the `@verbatim` block within the `@note` block. Everything works as I would expect.

Is that normal?

**Comment by albert-github** [comment]
Is this one replacing #7129?

Note please don't use the constructs like `\@verbatim` but use `` `@verbatim` `` (preferred) or use **\verbatim**

**Comment by reylau** [comment]
Well I am not sure if this is the same root cause, even though it looks similar.

**Comment by reylau** [comment]
I do not understand your previous comment. Does it relate to our discussion here on GitHub or is it related to the use of that tag in the source code?

**Comment by albert-github** [comment]
It is related to the discussion / question on github. you consequently write in your description, in words, a backslash , a commercial at sign, the doxygen command . This results in a bold text wit a mention to a user, I corrected it in the questions. As you probably can see a the top of the question that it was edited by me.

**Comment by albert-github** [comment]
You used version 1.8.14 and it looks to me that in version 1.8.15 the problem has been solved:

![output_1_8_15](https://user-images.githubusercontent.com/5223533/61472978-c7d6d300-a985-11e9-8de3-6adf816823b9.jpg)

**Comment by reylau** [comment]
I confirm, thank you!
