### ISSUE TITLE
Bad parse of variable when it has deprecated annotation

### ISSUE THREAD

**Issue by jpascualsana** [doxygen/doxygen#7138]
Hi,

On the generated XML files for Retroshare project I found a bad parsing. On [this line](https://github.com/RetroShare/RetroShare/blob/master/libretroshare/src/gossipdiscovery/p3gossipdiscovery.h#L39) the variables are defined as:

```c++
using PGPID RS_DEPRECATED_FOR(RsPgpId)  = RsPgpId;
using SSLID RS_DEPRECATED_FOR(RsPeerId) = RsPeerId;
```

Where the resulting XML is:

```xml
<memberdef kind="typedef" id="p3gossipdiscovery_8h_1a6be3a190b47f7623fac9e537acee1b55" prot="public" static="no">
        <type><ref refid="p3gossipdiscovery_8h_1a6be3a190b47f7623fac9e537acee1b55" kindref="member">RsPeerId</ref></type>
```

The memberdef id is the same as the type/ref.refid id causing a recursion loop when I try to get the original type of the variable.

Opened issue on Retroshare repo: https://github.com/RetroShare/RetroShare/issues/1602

**Comment by albert-github** [comment]
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.
- Please also specify the doxygen version used.

**Comment by albert-github** [comment]
Unfortunately no further information about code / doxygen configuration file.

Probably using the settings:
```
PREDEFINED = RS_DEPRECATED_FOR(x)=
MACRO_EXPANSION = YES
```
might solve the problem.

Setting issue to incomplete / not reproducible.
