### ISSUE TITLE
DoxygenLayout does not support UTF8 BOM format

### ISSUE THREAD

**Issue by reylau** [doxygen/doxygen#7140]
Hello,

I have joined a working example.

If you save DoxygenLayout.xml with the Notepad with a "UTF8" format, Doxygen fails to analyze the file.

Case 1: using an ANSI encoding
Case 2: using an UTF8 encoding. The layout instructions are ignored.

Notice that all the other files customedoxytgen.css, doxyfile, footer.html and header.html support UTF8 BOM!
[Doxygen Bug.zip](https://github.com/doxygen/doxygen/files/3432456/Doxygen.Bug.zip)

Laurent

**Comment by albert-github** [comment]
I saw the problem in the Capture.PNG files (in the blue bar at the top), but took some time to see the difference.
In future:
- please add in such cases a small description or better images with a small description
- please add procedure to generate (in this case both) cases (I'll add a small script I created to your other question #7129) this script is typical for my environment (the rm command) but can easily be adapted.

**Comment by reylau** [comment]
If you compare the logs, you see that in log1 there is no error/warning., but in log 2 doxygen reports two errors (at the end of the log):
error: fatal: at line 1 column 1 of DoxygenLayout.xml: error while parsing element
error: fatal: at line 1 column 1 of DoxygenLayout.xml: error while parsing prolog

If you compare capture 1 and capture 2 you see that the layout instructions were ignored, the navigation tabs have not been renamed.

BTW, in the configuration, I provided both layout file versions.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7144

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
