### ISSUE TITLE
note block not generated properly if there are blanks after it 

### ISSUE THREAD

**Issue by reylau** [doxygen/doxygen#7143]
I have joined a working example.

I have two `@note` blocks with the same contents but the first one has no blanks after the `@note` tag, whereas the second one has some blanks. See "PageTest.md".

In the output, the first note includes the list items, the second does not (check the vertical note bar in "02 Output.PNG").

Blanks should not cause a different output!

Laurent

PS: I am not fully sure but I believe that I have also tried with `@warning` and it behaves similarly
[Doxygen Bug 3.zip](https://github.com/doxygen/doxygen/files/3436481/Doxygen.Bug.3.zip)

**Comment by albert-github** [comment]
You already mentioned that one of the `@note` had extra spaces at the end of the line.
The markdown definition (https://daringfireball.net/projects/markdown/syntax#p) gives:

> When you do want to insert a <br /> break tag using Markdown, you end a line with two or more spaces, then type return.

Furthermore doxygen states for the `@note`:

> \note { text }

Where the `{...}` means:

> If {curly} braces are used the argument extends until the next paragraph. Paragraphs are delimited by a blank line or by a section indicator.

So I think the behavior is correct.

**Comment by reylau** [comment]
Ok I agree with your analysis.... but I am a starting to be rather frustrated with Doxygen, it is too sensitive to the input syntax and is not helping you very much in detecting tricky cases.

In this particular example, both cases look __exactly__ the same but the result is __different__. This means that if you want to be sure of the generated documentation, you __always__ need to check the output. This is __not__ practical for large projects, i.e. I am not going to rebuild documentation every time I make a modification in the SW documentation, just to verify that the documentation is in the form I'd like!

I'd argue that an empty note, like case  2, should generate a warning, since an empty note is of no real use. This would help the user realize he has inadvertently put spaces after the note.

Laurent

**Comment by albert-github** [comment]
I can imagine that it might be a bit frustrating that code that looks alike doesn't do the same thing. In this case it are spaces at the end of a line and conform the markdown definition these are translated to a newline, so not a lot doxygen can do (except for ignoring this part of the specification).

I have no idea why this definition landed in the markdown definition, especially for code documentation this is quite strange, but likewise strange to me people who put spaces at the end of a line (I removed quite a few).

With the `vi` editor  one can remove all spaces at  the end easy: `:%s/[ \t]*$//`
in `vi` it is also easy to see the spaces at the end by means of `:set list` which shows the end of a line by means of a `$`. 
Similar functionality will probably be present in other editors as well.

**Comment by reylau** [comment]
Well you are not always able to choose the editor since in my case I have to adapt to the design IDE targetting the particular HW (I write a lot of embedded FW) the customer wants to use.

If you do not use the IDE editor, you end up not being able to use the integrated features. E.g. I am currently using an Eclipse-based IDE and if a use for example vi (as an external editor) I cannot benefit from the integreated editor features, like directly jumping to some object definition, or being put on the line where the compiler has found an error. Unfortunately, the integrated editor is not always great and easily allows you to do what you suggest. Using a combination of editors may be dangerous because resources may become out-of-synch.

Multiple spaces are possible. For example if you had some line using alignement spaces (not using tabs), that you later split over two lines... I would add that human being are making mistakes, so the tools should help them find and correct those, else we could also argue why would compiler issue warnings or error messages?

Anyway, my only suggestion is that after a `@note`, `@warning`... command, if there are multiple spaces, Doxygen should issue a warning. This could be detected after markdown has processed the paragraph, if the note, warning, ... is empty a warning is issued.

If you do not intend to consider my suggestion, just close the case.

**Comment by reylau** [comment]
Hello Albert,

I have some news on this issue. Inadvertently, I have found a new issue related to this subject. If you put the exact same example within a list, the result is different. Check "12 New Output.PNG". 

The first two notes were already discussed. 

The second group is a list including the two notes. I have removed the bullets within the notes and the result is what we expect.

However, the third group is the exact same case than the two initial notes but included within a list. In that case, the last note block is not consistent! Why?
[Doxygen Bug 7143.zip](https://github.com/doxygen/doxygen/files/3447185/Doxygen.Bug.7143.zip)

Laurent

**Comment by albert-github** [comment]
I see 6 `\note` blocks in the mentioned image and I do see some inconsistency.

When looking back at the markdown definition:
> When you do want to insert a break tag using Markdown, you end a line with two or more spaces, then type return.

I think this is regarding the output and not the input and thus should not end the `\note` and thus:
- the blocks 2 and 4 are incorrect, the indicator should be before empty line and the text / items as well.
- When looking at block 6 here we are missing an empty line.

Looks like I missed especially the part about the indicator here.

**Master version run**
I now ran the example with the current master (5050a4787b1d55b04bfb6537c0e23ee4de44397b) and I got the following result:

![master](https://user-images.githubusercontent.com/5223533/62138346-cc857a80-b2e7-11e9-8083-1f3c44bcdffe.jpg)

When looking at this, my interpretation is:
- block 1, 3 and 5 are as expected
- block 2 is correct regarding the indicator and the empty line, but there is a problem with the list items (looks like first item is not recognized as list item hence the remaining `+`)
- block 4 is now correct
- block 6 here the same accounts as block 2.

@doxygen is this interpretation correct?

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7163

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
