### ISSUE TITLE
doxygen not documenting member in struct, only type

### ISSUE THREAD

**Issue by hannorein** [doxygen/doxygen#7145]
I'm having trouble getting doxygen (1.8.15) to document a member of a c struct which is an enum:

```
struct struct_a{
    int member_a;
    enum ENUM_TYPE {
        ENUM_A = 1,
        ENUM_B = 2
    } member_b;
};
```

Doxygen lists `member_a` as a public member. Is also lists `ENUM_TYPE` as a public type. But it never mentions `member_b` as a public member. An anonymous struct, i.e. 

```
struct struct_a{
    int member_a;
    enum {
        ENUM_A = 1,
        ENUM_B = 2
    } member_b;
};
```

leads to the same issue. Here doxygen documents the anonymous enum type, but not `member_b` which makes it kind of useless.  I don't want to define the enum type outside the struct because it is only used once.

Is this a bug or am I missing something?

**Comment by doxygen** [comment]
You must be missing something. I get this output with your first example and a default configuration file:

![image](https://user-images.githubusercontent.com/1300762/61996183-c4340200-b091-11e9-89af-c51a9fd759b7.png)

So please attach a self-contained example (source+config file in a zip) for which you verified it contains the problem.

**Comment by albert-github** [comment]
Cross posted from https://stackoverflow.com/questions/57227954/enum-in-struct-doxygen-not-documenting-member-only-type

**Comment by hannorein** [comment]
Thanks. That might help me track down the issue. 

If I run everything locally, then you are right and this works and everything appears correctly. But not if I run the same on readthedocs. But this means the issue could be anywhere along the doxygen/breathe/sphinx chain, i.e. not specifically related to doxygen.

**Comment by hannorein** [comment]
I'll close this issue for now. Thanks again.
