### ISSUE TITLE
Incorrect markdown processing of list w/n warning

### ISSUE THREAD

**Issue by reylau** [doxygen/doxygen#7150]
I have joined an example.

I am creating 4 lists, within a `@warning` block.

The first variant defines the 1st bullet on the same line than the warning tag, the resulting list is not properly processed.

The other variants are properly processed.

I assume that this issue is also present in other types of blocks, e.g. `@note`, `@remark`, ...
[Doxygen Bug xxxx.zip](https://github.com/doxygen/doxygen/files/3452093/Doxygen.Bug.xxxx.zip)

**Comment by albert-github** [comment]
The manual states (http://www.doxygen.nl/manual/lists.html):
> By putting a number of column-aligned minus (-) signs at the start of a line, a bullet list will automatically be generated.
Instead of the minus sign also plus (+) or asterisk (*) can be used.

and http://www.doxygen.nl/manual/markdown.html#md_lists:
> Simple bullet lists can be made by starting a line with -, +, or *. 
In case of the `@warning` the `+` is not at the start of the line as a command precedes it.

So in my opinion the result is correct and this is usage, or did I miss something?

**Comment by reylau** [comment]
I understand your point of view. 

However to me, a warning (like a note, remark, ...) defines a special container, which stores a paragraph. That container has a specific title and formatting (the left colored vertical bar) associated to the keyword. But the warning keyword itself is not part of the contents. Therefore, the first character of the contents is the "+ text", which perfectly respects the markdown definition of a list item.

I you consider the definition of `@warning` from the manual, you have:
`\warning { warning message }`
Starts a paragraph where one or more warning messages may be entered. The paragraph will be indented. The text of the paragraph has no special internal structure. __All visual enhancement commands may be used inside the paragraph.__ ...

+ I understand the `{ warning message }` as the paragraph contents, which does not include the `@warning` keyword;
+ The text I have highligthed above also underlines why I believe a list starting on the first row should work fine.

Laurent
