### ISSUE TITLE
No way to create a link inside \code?

### ISSUE THREAD

**Issue by reddwarf69** [doxygen/doxygen#7162]
In doxygen 1.8.15, when doing
```
    /**
     * Lala
     *
     * Long lala.
     *
     * @param la lalala
     * @code
     * void handler(
     *     const error_code& ec
     *     const credentials& id
     * );
     * @endcode
     */
```
A link is generated for error_code, but not for credentials.
http://doxygen.nl/manual/autolink.html explains that 
> All words in the documentation that correspond to a documented class and contain at least one non-lower case character will automatically be replaced by a link to the page containing the documentation of the class. ... To link to an all lower case symbol, use \ref.

So I have tried
`const @ref credentials credentials & id`,
I have also tried
`const [credentials](@ref credentials)& id`
and
`const [credentials](credentials)& id`

but none of them works.

Bug? Or how I'm supposed to make it work?

**Comment by albert-github** [comment]
To be able to give an answer / see whether or not it is a  bug we need to be able to reproduce it. Without further information this is not possible (we cannot even see a link to error_code).

- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.

**Comment by albert-github** [comment]
Unfortunately no further information but when making `error_code` and `credentials` are made available they are shown as links.
Things like `@ref credentials credentials` cannot work inside a code section as in the code section doxygen commands are not evaluated.

Setting issue as incomplete / usage.
