### ISSUE TITLE
Why occurs [read] behind function name?

### ISSUE THREAD

**Issue by xiaoyusu** [doxygen/doxygen#7168]
For example, i declare a struct named :
`struct if_name *if_name(void)` 

but in the document generated by doxygen, there bellow:
`struct if_name *if_name(void) [read]`

why there occur [read]?

**Comment by albert-github** [comment]
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.
- Please also specify the doxygen version used.

**Comment by xiaoyusu** [comment]
you can create a new .h and copy codes as bellow:
`/** @defgroup test Test
*/


/** @ingroup test
this api is xxxx
*/
struct if_name* if_name(void);`

and generate a document in .chm.

**Comment by albert-github** [comment]
Du e to some presistent testing I found that with version 1.8.3.1 (January 20, 2013) there is still a `read` after `struct if_name *if_name(void)`. 
With version 1.8.4 this is gone.

So I think the problem has been solved in the mean time.

I reproduced the problem with the code specifies (`aa.h`) and a default Doxyfile with just the following changes:
```
GENERATE_HTMLHELP      = YES
HHC_LOCATION           = "C:\Program Files (x86)\HTML Help Workshop\hhc.exe"
```

So please in future always:
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent. (so we know for sure we are talking about the same problem!)
- Please also specify the doxygen version used.

**Comment by xiaoyusu** [comment]
what`s them meaning of [read] here?

**Comment by xiaoyusu** [comment]
the version i use maybe 1.5.7.1, if there are some methods that i can avoid this problem?

**Comment by albert-github** [comment]
As mentioned in my comment before the "read" has been removed since 1.8.4. A quick scan of the change log didn't  show me the reason why it was removed, but it shouldn't be there.
Version 1.5.7.1 is from October 5, 2008.
I don't see any other possibility then that you would modify the code of the version you use, but far better is to use the current version.

**Conclusion**
Upgrade to the current version.
