### ISSUE TITLE
Javascript files included with \include lost syntax highlight

### ISSUE THREAD

**Issue by ralphyon** [doxygen/doxygen#7170]
Found during an upgrade from 1.6.x to 1.8.15 : our \include'd javascript source files are not highlit anymore. This can be fixed be reverting the commenting-out of these statements in utils.h:

```cpp
  updateLanguageMapping(".as",       "javascript"); // not officially supported
  updateLanguageMapping(".js",       "javascript"); // not officially supported
```

**Comment by ralphyon** [comment]
Issue was introduced in 1.8.12 with this commit : https://github.com/doxygen/doxygen/commit/d168f8bfef6aac5a71eccad36dced78d55765ae1

**Comment by albert-github** [comment]
I think you can accomplish this too with:
```
EXTENSION_MAPPING = js=javascript as=javascript
FILE_PATTERNS         += *.as *.js
```

**Comment by ralphyon** [comment]
Yes, your suggestion also works, thanks! Is this the intended behavior, then?

**Comment by doxygen** [comment]
@ralphyon yes it is intended. Since doxygen is often used recurively on a whole source tree and doesn't fully support javascript, it happened that some javascript files were unintentionally also processed causing wrong output and confused users.
