### ISSUE TITLE
warning: Found ';' while parsing initializer list!

### ISSUE THREAD

**Issue by astoebe** [doxygen/doxygen#7175]
Version 1.8.16

a CPP file just containing one line:
  int a;
emits the warning:
"documentation.cpp:192: warning: Found ';' while parsing initializer list! (doxygen could be confused by a macro call without semicolon)"

**Comment by albert-github** [comment]
I tried to reproduce the problem with a cpp file as indicated and a default Doxyfile with just the change `EXTRACT_ALL = YES` but could not reproduce the problem.

- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.

**Comment by astoebe** [comment]
Hi Albert,

I’ve checked my doxfile and fond the problem in:
INPUT_FILTER           = "python2 buildtools/convertProtoDoxygen/proto2cpp.py"

With  the latest version of that filter everything is ok.

Thank you for the quick reply.

Best regards
Bernd

Von: albert-github [mailto:notifications@github.com]
Gesendet: Freitag, 9. August 2019 11:23
An: doxygen/doxygen
Cc: Stoeferle, Bernd; Author
Betreff: Re: [doxygen/doxygen] warning: Found ';' while parsing initializer list! (#7175)


I tried to reproduce the problem with a cpp file as indicated and a default Doxyfile with just the change EXTRACT_ALL = YES but could not reproduce the problem.
·         Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

**Comment by albert-github** [comment]
Out of curiosity what kind of filer is this and why do you use it?

**Comment by astoebe** [comment]
To convert google.com/protocol-buffers files syntax  in “normal” c++ syntax for documentation

Von: albert-github [mailto:notifications@github.com]
Gesendet: Freitag, 9. August 2019 15:25
An: doxygen/doxygen
Cc: Stoeferle, Bernd; Author
Betreff: Re: [doxygen/doxygen] warning: Found ';' while parsing initializer list! (#7175)


Out of curiosity what kind of filer is this and why do you use it?
