### ISSUE TITLE
How to hide some unnecessary information in doc?

### ISSUE THREAD

**Issue by xiaoyusu** [doxygen/doxygen#7180]
some unnecessary information in doc generated by doxygen as bellow, want to know how can i hide them?

![image](https://user-images.githubusercontent.com/24693541/62843418-40625280-bcec-11e9-83bd-0c7c9b72ff67.png)

**Comment by albert-github** [comment]
Question is unclear about which information is unnecessary.

- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.
- Please also specify the doxygen version used.

**Comment by albert-github** [comment]
Unfortunately no further information provided, setting issue to incomplete.
