### ISSUE TITLE
generate .chm in chinese with messy code

### ISSUE THREAD

**Issue by xiaoyusu** [doxygen/doxygen#7181]
i upgrade doxygen to the newest version , but after that there are messy codes in .chm generated like bellow :

![image](https://user-images.githubusercontent.com/24693541/62848127-8f1fe480-bd0c-11e9-8de7-7e3492958a8e.png)

before upgrade, there is no problem. and after upgrade there is also normal in function or structure etc description. But in the catalog, such as module, header files......  key words like this occured wrong.  Please tell me why, and how can i do to modify

**Comment by albert-github** [comment]
-  Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.
- Please also specify the doxygen version used. you mention newest so this is 1.8.16?
- Please specify the version used before the upgrade

**Comment by albert-github** [comment]
Unfortunately no reaction, it is impossible to tell what is the cause of the problem. It looks like directory names, but it is impossible to tell without an example.

Setting issue to incomplete / not reproducible.
