### ISSUE TITLE
generating tagfiles only now reports on unresolved references

### ISSUE THREAD

**Issue by svigerske** [doxygen/doxygen#7188]
We use multiple Doxyfile's to generate different parts of documentation and glue them together with tagfiles. There can be references from each part of the documentation to another, i.e., circular references.
Before doxygen 1.8.16, I could disable GENERATE_HTML and GENERATE_LATEX and use GENERATE_TAGFILE to first generate the tagfile for each documentation part, and then do a second run with GENERATE_HTML enabled and TAGFILES provided.

With doxygen 1.8.16 I now get warnings about unresolved references when only trying to generate tagfiles.

Example [tagfiles.zip](https://github.com/doxygen/doxygen/files/3496291/tagfiles.zip) demonstrates the issue.
When running `doxygen Doxyfile1`, I get
```
input1.dox:3: warning: unable to resolve reference to 'INPUT2' for \ref command
```
And when running `doxygen Doxyfile2`, I get
```
input2.dox:3: warning: unable to resolve reference to 'INPUT1' for \ref command
```

Could one restore the previous behavior of not reporting warnings on unresolved references when producing a tagfile only?

**Comment by svigerske** [comment]
Further, setting `WARNINGS = NO` doesn't help to turn these off.

**Comment by albert-github** [comment]
In your question you wrote:
> Before doxygen 1.8.15

and
> With doxygen 1.8.15

- Did you mean 1.8.16 (as the `Doxyfile1` and `Doxyfile2` are also from 1.8.16)?

The fact that warnings are emitted is correct (for 1.8.16) as the reference could not be generated, the fact that `WARNINGS=NO` doesn't work looks a bit strange but the warning is seen as a sort of error, but by setting `WARN_IF_DOC_ERROR=NO` the warning can be suppressed (but you might loose quite a few other messages as well).

**Comment by svigerske** [comment]
> In your question you wrote:
> 
> > Before doxygen 1.8.15
> 
> and
> 
> > With doxygen 1.8.15
> 
>     * Did you mean 1.8.16 (as the `Doxyfile1` and `Doxyfile2` are also from 1.8.16)?
> 
> 
> The fact that warnings are emitted is correct (for 1.8.16) as the reference could not be generated, the fact that `WARNINGS=NO` doesn't work looks a bit strange but the warning is seen as a sort of error, but by setting `WARN_IF_DOC_ERROR=NO` the warning can be suppressed (but you might loose quite a few other messages as well).

Yes, sorry, I meant 1.8.16. I edited the initial post.

Setting `WARN_IF_DOC_ERROR=NO` could be a usable workaround. I would still get the warnings when I generate the actual HTML docu in the 2nd sweep.

I could still argue that the warnings don't have to be generated as for tagfiles there is no need to generate references, as far as I understand.

**Comment by albert-github** [comment]
I rechecked the problem with the versions 1.8.14, 18.16 and the current doxygen version (1.9.6)
- with 1.8.14 and 1.9.6 no warnings and tag files look the same (just improvements for the newer versions are included)
- with 1.8.16 I get warnings, though tag files are identical to the files from 1.8.14
   ```
   input1.dox:3: warning: unable to resolve reference to 'INPUT2' for \ref command
   input2.dox:3: warning: unable to resolve reference to 'INPUT1' for \ref command
   ```

I think the problem has been solved in the mean time

**Comment by svigerske** [comment]
Yes, seems so. Thank you.
