### ISSUE TITLE
trailing space generates linebreak

### ISSUE THREAD

**Issue by svigerske** [doxygen/doxygen#7191]
When I have some spaces at the end of a line in the input, then this creates a linebreak in the output, while having no spaces doesn't do that.
Example [trailingspace.zip](https://github.com/doxygen/doxygen/files/3496890/trailingspace.zip) reproduces this issue with doxygen 1.8.15 (uses `<p>`) and 1.8.16 (uses `<br/>`). With 1.8.13, there were no linebreaks.

**Comment by albert-github** [comment]
This is intended behavior based on markdown processing.

You mentioned the extra spaces at the end of the line.
The markdown definition (https://daringfireball.net/projects/markdown/syntax#p) gives:

>    When you do want to insert a
>    break tag using Markdown, you end a line with two or more spaces, then type return.


So this is in my opinion usage

**Comment by svigerske** [comment]
Hmm, ok, if daringfireball says so...

We can of course remove all trailing spaces and try to be more disciplined in the future.
Thanks.
