### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [doxygen/doxygen#7195]
I would like to point out that identifiers like “[`_DOCHANDLER_H`](https://github.com/doxygen/doxygen/blob/154e877cc2e8b10091d7e0068b6f6d5793cd29f3/addon/doxmlparser/src/dochandler.h#L16 "Update candidate")” and “[`_SEARCHINDEX_H`](https://github.com/doxygen/doxygen/blob/f241f6c736a5fb59728cfe1af7d1d4d3f384e9a6/src/searchindex.h#L18 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by albert-github** [comment]
The doxmlparser has been rewritten (from a C++ implementation to a puthon implementation), so the file dochandler.h does not exist anymore.
The guard in searchindex.h has been renamed from `_SEARCHINDEX_H` to the compliant name `SEARCHINDEX_H`.

I think the problem has been solved in the mean time

**Comment by elfring** [comment]
Thanks for [an adjustment of an affected include guard](https://github.com/doxygen/doxygen/commit/03cfc3d6eb95d2454c6d155c1ce8cb3d3bad3621#diff-8ea4884872830a3f335256f0a1e013a5b1df53d4f61b925574ebae62c48d40b4L18 "Refactoring: Modernise client side part of searchindex").

[Were any update candidates left over](https://github.com/doxygen/doxygen/blob/98c67549bc3cd855873e0ef5eeab7c6410699d78/libmd5/md5_loc.h#L1 "Update candidate")?

**Comment by albert-github** [comment]
Later I realized that there are a few other places as well (one indicated by the little bit cryptic "Were any update candidates left over?"), will look into this later. With the issue I only looked into the mentioned problems.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #8664

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.2.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
