### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [doxygen/doxygen#7198]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [getDefs](https://github.com/doxygen/doxygen/blob/970436b1acbfdc8a3b727eb1fd08992d8a5687f9/src/util.cpp#L4190 "getDefs function")
- [Token](https://github.com/doxygen/doxygen/blob/154e877cc2e8b10091d7e0068b6f6d5793cd29f3/vhdlparser/Token.cc#L86 "Destructor for Token")
- [VhdlParserTokenManager::setErrorHandler](https://github.com/doxygen/doxygen/blob/154e877cc2e8b10091d7e0068b6f6d5793cd29f3/vhdlparser/VhdlParserTokenManager.h#L131 "VhdlParserTokenManager::setErrorHandler function")

**Comment by albert-github** [comment]
The construct in getDefs does not exist anymore.
The files Token.cc and VhdlParserTokenManager.h are generated files by means of JavaCC (doxygen has no influence on it).

I think the problem has been solved in the mean time.

**Comment by elfring** [comment]
[Were any update candidates left over](https://github.com/doxygen/doxygen/blob/592aaa4f17d73ec8c475df0f44efaea8cc4d575c/vhdlparser/VhdlParser.h#L17 "Update candidate: JJCalls destructor")?

**Comment by albert-github** [comment]
The fileVhdlParser.h contains generated files by means of JavaCC (doxygen has no influence on it).

**Comment by elfring** [comment]
Would you like to achieve any improvements for source code which will be generated (by JavaCC)?
