### ISSUE TITLE
@code ignores doc comments

### ISSUE THREAD

**Issue by graph** [doxygen/doxygen#7219]
```
@code{.cpp}

/** works fast and etc.. with great spice.

    ok
*/
void yay();

@endcode
```

The doc-comment will not be included in the html output generation. Is this intended? if so is there a way to have this? For example writing documentation about how to format doc comments I need to show an example.

**Comment by albert-github** [comment]
The issueis a bit unclear to me.

- what do you want to accomplish?
- did you have a look at commands like `\example`, `\include\, \snippet`?

Most important:
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.
- Please also specify the doxygen version used.

**Comment by graph** [comment]
source file: hello.md

```
@mainpage

@code{.cpp}
/** Hello world */
@endcode
```

Just do `doxygen -g` and specify the file in input to be processed. You won't find the text "hello world". I just want to include a small snippet. The commands you mentioned require a file to be specified. My goal is to show an example of a doc comment.

**Comment by albert-github** [comment]
- Please also specify the doxygen version used (`doxygen -v`)

**Comment by graph** [comment]
`doxygen -v`

```
1.8.16
```

**Comment by albert-github** [comment]
I looked at the problem and you are using doxygen special comments.
In the documentation is stated (and this is also valid for `@code` comments):
> STRIP_CODE_COMMENTS Setting the STRIP_CODE_COMMENTS tag to YES will instruct doxygen to hide any special comment blocks from generated source code fragments. Normal C, C++ and Fortran comments will always remain visible.
The default value is: YES.

So you have to set:
`STRIP_CODE_COMMENTS = NO`

So I think this issue us usage.

**Comment by graph** [comment]
I see, yes setting to `NO` works. Thanks for replying so quickly. If this is intended maybe add to documentation that this is effected by STRIP_CODE_COMMENTS. For my current usecase doing this is fine as I have no code in the project and it's purely documentation in .md files.
