### ISSUE TITLE
Links as the first words of @param description in C# docs are sometimes moved to the next line

### ISSUE THREAD

**Issue by yulian-gaponenko** [doxygen/doxygen#7226]
1.8.16

**Comment by albert-github** [comment]
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.

**Comment by yulian-gaponenko** [comment]
Yeah, sorry, I accidentally created the issue before I added details.

However, while I was created a small example, I figured out that the issue was on my end :)

The issue can be removed.
