### ISSUE TITLE
Strange hyphenation marks in function parameter tables in pdf output

### ISSUE THREAD

**Issue by hoditohod** [doxygen/doxygen#7229]
Doxygen (or latex???) generates useless hyphenations in function parameter tables and adds funny looking curly arrows. The curly arrows also appear in markdown tables.

![Clipboard02](https://user-images.githubusercontent.com/8727184/63773713-05f7d880-c8dc-11e9-991f-4705698b391f.png)

The table takes 1/3 page width, so there's no point in hyphenating, and I would like to get rid of the little arrow as well.

Do you know how can I achieve this? I looked in the doxyfile and the latex template files, but I didn't find anything related to this.

Ubuntu 16.04  
Doxygen 1.8.11
Latex 3.14159265-2.6-1.40.16

**Comment by albert-github** [comment]
Does the problem also occur with the current version (1.8.16), 1.8.11 is a bit old (December 2015).

- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.

**Comment by hoditohod** [comment]
Sorry, I simply can't manage to get time for this. 🙁

Since the issue is not known by the developers and happens on a fairly old Doxygen+Latex release (or my specific setup), I close the issue.

As quick workaround I disabled all hyphenation for the whole document in header.tex with this line: `\usepackage[none]{hyphenat}`

**Comment by albert-github** [comment]
It is not written that the problem is unknown by the developers, we only need a small case that signals the problem (in 1.8.11; when tested in 1.8.16 would be a bonus).
