### ISSUE TITLE
Using @var annotation inside of method, causes method to not be documented

### ISSUE THREAD

**Issue by timmyRS** [doxygen/doxygen#7233]
When writing PHP against an IDE such as PhpStorm, sometimes I use `@var` to ensure it that a variable is of a certain type, for example when using SplObjectStorage, like in the following script.

```PHP
<?php
class Example
{
	function func_1(): bool
	{
		return true;
	}

	/**
	 * Function #2
	 *
	 * @return boolean
	 */
	function func_2(): bool
	{
		return true;
	}

	/**
	 * Function #3
	 *
	 * @return boolean
	 */
	function func_3(): bool
	{
		global $obj_store;
		$bool = $obj_store[0];
		return $bool;
	}

	/**
	 * Function #4
	 *
	 * @return boolean
	 */
	function func_4(): bool
	{
		global $obj_store;
		/**
		 * @var SplBool $bool
		 */
		$bool = $obj_store[0];
		return $bool;
	}
}

$obj_store = new \SplObjectStorage();
$obj_store->attach(new \SplBool(true));
```

However, running this against doxygen 1.8.16 produces

> Example.php:39: warning: documented symbol 'Example::func_4' was not declared or defined.

and a classExample.html which documents func_1 through 3, but not 4:

![image](https://user-images.githubusercontent.com/11009697/63826796-0e462700-c961-11e9-902b-2507121360ef.png)

**Comment by doxygen** [comment]
The problem is that doxygen combines the comment in front of the function with the one inside the body. So like you documented this:

```php
	/**
	 * Function #4
	 *
	 * @return boolean
         * @var SplBool $bool
	 */
	function func_4(): bool
	{
		global $obj_store;
		$bool = $obj_store[0];
		return $bool;
	}
```

The `@var` command then turns the whole comment block into a comment for variable bool, leaving `func_4` undocumented. 

The conclusion is that you use doxygen in the wrong way, i.e. you cannot document local variables inside the body of a function with `@var`. Doxygen is meant for API documentation, a local variable is not part of your API. I suggest to use a `@return` command instead to describe what `func4` returns.

**Comment by timmyRS** [comment]
My example is just to illustrate the issue. In a more complex, real world situation, I'd have have an SplObjectStorage containing multiple instances of a custom class of mine, and I'd like to access properties and methods on them, but for all PhpStorm knows, it could be anything and not have those properties and methods, which causes it to complain, so I add the `@var` annotation. It would be nice to have some sort of facility to make both PhpStorm and Doxygen happy.

**Comment by timmyRS** [comment]
I have now opted to use PHP's `assert` statement, which lets PhpStorm know the object's type and avoids doxygen not documenting the method. However, this does have some performance impact as PHP now has to assert every object's type in my SplObjectStorage before doing the actual work every time. I still feel like this is a bug with doxygen.
