### ISSUE TITLE
Feature request: show what directory a class was defined in.

### ISSUE THREAD

**Issue by lfrankel** [doxygen/doxygen#7238]
We've started using Doxygen only fairly recently, for a project that's several decades old at this point. We do not tend to use namespaces, but we do have files grouped into various directories. These are compiled into separate libraries and then linked in.

So for us, where a class is makes a big difference, because it affects what symbols it can reference. The directory is also a good indicator of what the class is for, generally speaking, and so functions very similarly to a namespace.

It would be extremely useful if we could 
1. see what directory a class came from, on its documentation page
2. see a grouping of class by directory, in the same manner as the groupings by module or namespace.

The project is large and old, so manually adding namespaces or Doxygen module groupings isn't a viable option for us.

**Comment by albert-github** [comment]
Regarding point 1) maybe the configuration setting `SHOW_USED_FILES` can give the required information.

Maybe you should also look at the tag possibilities of doxygen, maybe this leads to some separation / information you require.

**Comment by lfrankel** [comment]
> Regarding point 1) maybe the configuration setting `SHOW_USED_FILES` can give the required information.

`SHOW_USED_FILES` is already set. For a class `GoElement` declared in `compile/src/fgo/GoElement.h`, the text at the bottom of the `GoElement` documentation page simply says 

>The documentation for this class was generated from the following file:
> - GoElement.h

Ideally, I'd like to have it say `fgo/GoElement.h` instead.

The working directory is `<repo>/compile/doxygen`, and the input directory is`../src`.

> Maybe you should also look at the tag possibilities of doxygen, maybe this leads to some separation / information you require.

Possibly, but that's not a great solution for us given how much code there is. I could write a script to add `@addtogroup` tags to files automatically, but it would be very hard for me to convince my boss to approve me spending time on that. It would also go out of date if and when files are moved between directories.

**Comment by albert-github** [comment]
Did you set `STRIP+FROM_PATH` / `STRIP_FROM_INC_PATH` ?

Regarding the tag possibility I gave and your remark "not a great solution for us given how much code" I don't understand. doxygen has to be run for each library each (generating its own documentation plus the tag file) and once for the main documentation making use of the tag file. This can be very well automated. But as said I don't know whether or not this will result in a solution for your specific problem.

**Comment by lfrankel** [comment]
OH! I see!
> Did you set `STRIP_FROM_PATH` / `STRIP_FROM_INC_PATH` ?

Actually no, but when looking for that I found `FULL_PATH_NAMES`, which was NOT set, and that does explain the problem. 

> Regarding the tag possibility I gave and your remark "not a great solution for us given how much code" I don't understand. doxygen has to be run for each library each (generating its own documentation plus the tag file) and once for the main documentation making use of the tag file. This can be very well automated. But as said I don't know whether or not this will result in a solution for your specific problem.

My mistake! I realise now you're talking about http://www.doxygen.nl/manual/external.html , right? Originally, I thought by "tag" you just just grouping keywords like in http://www.doxygen.nl/manual/grouping.html .

Thank you for the help. It looks like Doxygen already doe the stuff I want, I just didn't know how to do it :)

**Comment by albert-github** [comment]
Indeed I meant the the tag facility as mentioned in http://www.doxygen.nl/manual/external.html, I should have mentioned a configuration parameter / or have given the reference to the documentation.
