### ISSUE TITLE
Add support for C++20 modules

### ISSUE THREAD

**Issue by ghost** [doxygen/doxygen#7261]
C++20 now has modules so it is assumed that most code will eventually migrate to them. I think this is a great time to make documentation generated by Doxygen more coherent because the code itself now has more logical structure.

From syntax perspective this seems like another type of documentable entity:
```c++
/// \brief My awesome module
/// \details This is my awesome module that has stuff that does awesome things.
export module My.Awesome.Module;
```

But on generation side we'd need a list of modules and when you click on a module in a list, you should get list of exports. Suddenly everything is nicely organized.

**Comment by albert-github** [comment]
Can you please give a reference to the definition of modules?

**Comment by Lyberta** [comment]
Sure, the formal reference is [here](http://eel.is/c++draft/#module).

**Comment by albert-github** [comment]
I actually meant a reference to the official standard or to the working draft of the committee like http://www.open-std.org/jtc1/sc22/wg21/and https://github.com/cplusplus/draft

**Comment by Lyberta** [comment]
The PDF version of latest draft is [here](https://wg21.link/n4830).

**Comment by albert-github** [comment]
Superseded by issue #9116 (as that issue has an example), setting this issue to duplicate.
