### ISSUE TITLE
Tilde in preprocessor macro disappears in latex

### ISSUE THREAD

**Issue by kjorand** [doxygen/doxygen#7271]
For example:
`#define TIMER_1_ID_COMP_AB TIMSK &= ~( (1<<OCIE1A) | (1<<OCIE1B) ) ///< Disables interrupt`
works just fine (the ~ is shown in the doc), but

`/**`
` * This macro [...]`
`*/`
`#define SYNC_SEC		SFIOR &= ~(1<<PSR2);	\`
`TCNT2 = 0x00;			\`
`i_sec = 0;`

Doesn't: the tilde ~ disappears in the latex documentation (which is ... kind of a problem, since in C, at least, it is a bitwise no... )

EDIT: it seems to be in hangpara or DoxyCode, since the ~ still appears in the .tex file before being compilated:
`\begin{DoxyCode}{0}`
`\DoxyCodeLine{SFIOR \&= ~(1<<PSR2);    \(\backslash\)}`

**Comment by albert-github** [comment]
I can reproduce the problem with a default Doxyfile and the shown code.
Just placing a backslash before the `~` (in the DoxyCodeLine) shows the `~` but it is elevated like an accent which is not the way it should be here. To be investigated a bit further.

For future:
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.
- Please also specify the doxygen version used.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7272

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.17.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
