### ISSUE TITLE
dot called even when HAVE_DOT is NO

### ISSUE THREAD

**Issue by cjo1958** [doxygen/doxygen#7273]
I am trying to migrate from doxygen V1.7.6.1 to the latest version.  We don't have Graphviz installed so we have HAVE_DOT set to NO.  Despite this doxygen still attempts to call dot.
It seems in the HtmlDocVisitor::visit function if DocVerbatim is Dot then calls to dot are made without checking the HAVE_DOT value.
The error below is reported

sh: 1: dot: not found
error: Problems running dot: exit code=127, command='dot', arguments='"/home/dds/cj/OSPL-13187/ospli/ospl_docs/docs/cs_api/html/inline_dotgraph_1.dot" -Tpng -o "/home/dds/cj/OSPL-13187/ospli/ospl_docs/docs/cs_api/html/dot_inline_dotgraph_1.png"'

I have tested this by adding if (Config_GetBool (HAVE_DOT) ) and the error above does not occur

We did not have the problem with V1.7.6.1

**Comment by albert-github** [comment]
I assume you are talking about doxygen version 1.8.16 and the code line `case DocVerbatim::Dot:` in the routine `void HtmlDocVisitor::visit(DocVerbatim *s)` in `htmldocvisitor.cpp`.
The intention of `HAVE_DOT` is to signal whether certain diagrams (call graphs etc) can be generated. 
In this case the user, probably, explicitly requests a dot graph. 

I think similar problems might occur when using e.g. `\msc` or `startuml` without the appropriate packages installed. 

@doxygen what strategy to follow here?

To be sure about the setup and doxygen commands used:
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.

**Comment by cjo1958** [comment]
yes version 1.8.16

attached is a tar file containing a very small example which reproduces the problem.  As I said before this worked fine with 1.7.6.1

[test.zip](https://github.com/doxygen/doxygen/files/3632132/test.zip)

**Comment by doxygen** [comment]
> @doxygen what strategy to follow here?

I would say that if the configuration file specifies that a certain tool is not available (e.g. `HAVE_DOT=NO`) then doxygen should assume it is not installed and not ever invoke it, even if the code has explicit commands for it. A warning should be given in case a graph cannot be produced (e.g. `HAVE_DOT=NO` in combination with `\dot`).

For other tools we may still need to introduce switches (e.g. `bibtex` comes to mind).

**Comment by tobylane** [comment]
Is there a fix or solution for this? It's still happening. https://github.com/tobylane/CorsixTH/runs/3039196330?check_suite_focus=true#step:12:17

**Comment by albert-github** [comment]
@tobylane 
- which version of doxygen are you using?
- I don't think yet, it is not easy as it is not just that the graphs are not generated but also the texts in the documentation have to be adjusted. Furthermore there are also other parts (e.g. PlantUML that use GraphViz / dot internally)
- what is the doxygen configuration file you use?
- link to a build shows that an attempt is made to call dot but fails with collaboration / inheritance graphs and include graphs (maybe I missed some)
- is there a special reason why you run without dot? GraphViz / dot is quite easy to install in GitHub Actions, see e.g. the workflow doxygen uses: https://github.com/doxygen/doxygen/blob/master/.github/workflows/build_cmake.yml

**Comment by tobylane** [comment]
1.8.17, the latest in that version of Ubuntu. I was hoping to run without 1.9 and dot for the sake of other users, though perhaps setting HAVE_DOT = YES in Actions may be acceptable if NO did work.

But this only started happening when I took out that section of the doxy config, despite the deleted sections matching the defaults in the description. I re-add the Dot related section in https://github.com/tobylane/CorsixTH/commit/2ac6915be3974e707e812cc937971fbee0f99e9b and still have the errors in https://github.com/tobylane/CorsixTH/runs/3039321681?check_suite_focus=true#step:12:17

**Comment by albert-github** [comment]
Taking out sections of the Doxyfile means just that the defaults are used.

**Comment by tobylane** [comment]
That diff shows that nothing should have changed, as all the settings match the default. Is the answer that 1.8 doesn't fully respect have_dot = no, and I need 1.9?

**Comment by albert-github** [comment]
- always use the full version (so 1.8.17 and 1.9.1 and other information from `doxygen -v`) as just 1.8 can mean 1.8.1 but also 1.8.20 and they are significantly different.

- the original problem is for using with the `\dot` command, your problem looks a a bit a more general problem, so:
  - Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

**Comment by tobylane** [comment]
I fixed it by adding HAVE_DOT = NO to the right file.

I don't understand the error messages enough to pick out a small portion. Thanks for your prompt help, sorry I can't identify it down.

**Comment by albert-github** [comment]
Regarding the commands `\dot` and `\dotfile` I've just pushed a proposed patch, pull request #8663

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.2.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
