### ISSUE TITLE
C++ - Crash using all system memory on using parent constructor with same name

### ISSUE THREAD

**Issue by Horrih** [doxygen/doxygen#7277]
The issue here is using the parent constructor with the syntax using Parent::Parent;
Here the parent has the same class name but in another namespace.

However in this case, doxygen gets stuck on _Searching for member function documentation..._ . The system memory skyrockets by 200MB each second until it crashes
Changing the class name fixes the issue

I have read the common issue : _Doxygen does not work properly if there are multiple classes, structs or unions with the same name in your code. It should not crash however, rather it should ignore all of the classes with the same name except one._ 

Since in my case it crashes, I felt like I needed to report it anyway

Useful data:
- attached : Doxyfile and main.cpp
[doxy.zip](https://github.com/doxygen/doxygen/files/3650840/doxy.zip)
- doxygen --version  1.8.15
- Doxyfile generated with doxygen -g Doxyfile. Not modified
- Example compiles with g++ main.cpp 
- g++ --version g++ (GCC) 8.2.1 20180905 (Red Hat 8.2.1-3)

**Comment by doxygen** [comment]
Please verify that the referenced commit fixes the problem.

**Comment by Horrih** [comment]
Tested on our project on which we uncovered the issue
👍 works flawlessly now
Good job fixing it so fast

**Comment by albert-github** [comment]
Please don't close the issue as this will be done at the moment of a release

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.17.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
