### ISSUE TITLE
Markdown commands ignored in htmlonly section

### ISSUE THREAD

**Issue by kjorand** [doxygen/doxygen#7278]
The markdown commands seem to be ignored in `htmlonly` section (example: ~~scratch~~ *emphasis* ...) although it isn't when just outside that section (outside, it works just fine).

Version: last : 1.8.16
Default Doxyfile
```
\htmlonly
example: ~~scratch~~ *emphasis*
\endhtmlonly
example: ~~scratch~~ *emphasis*
```

**Comment by albert-github** [comment]
According to the documentation:
> Starts a block of text that will be verbatim included in the generated HTML documentation only. The block ends with a \endhtmlonly command.

In other words the part between `\htmlonly` and `\endhtmlonly` is not interpreted at all.

I think the problem is usage.

**Comment by kjorand** [comment]
Ohh I'm really sorry, yes it is, then!
It would be nice having the possibility to format the text using markdown in HTML only (just as it works in latexonly ).
Should I close?

**Comment by albert-github** [comment]
I don't completely get the in `\latexonly` part, do you mean that when inserting LaTeX commands in the `\latexonly` part you get the formatted text, this is expected or do you insert markdown here (with some additional packages)?
When giving HTML commands in the `\htmlonly` part you will get formatted text as well.

I think you can lose this issue.

**Comment by kjorand** [comment]
I mean that when using the 
```
\latexonly
~~Scratch~~ or *emphasis*
\endlatexonly
```
markdown formating works perfectly

**Comment by albert-github** [comment]
This behavior I cannot reproduce (with doxygen 1.8.16 nor with the master version).
When using the `~~Scratch~~ or *emphasis*` directly I see the strikethrough of the Scratch and the emphasized emphasis in HTML and LaTeX.
The `~~Scratch~~ or *emphasis*` enclosed in `htmlonly` and `\endhtmlonly` results in '~~Scratch~~ or *emphasis*'.
The enclosed version in `\latexonly` and `\endlatexonly` results in '  Scratch   or *emphasis*' (note the extra 2 whitespace as a tilde in LaTeX is seen as a, hard, space).
I don't see any translation here (using: MiKTeX-pdfTeX 2.9.6839 (1.40.19) (MiKTeX 2.9.6840 64-bit).
