### ISSUE TITLE
Online manual link in doxywizard broken - 404 not found

### ISSUE THREAD

**Issue by AnderBomb** [doxygen/doxygen#7294]
Running doxywizard on Debian Buster (doxygen-gui/stable,now 1.8.13-10 amd64),
pressing F1 opens a browser window at http://www.doxygen.nl/manual.html . This returns a 404 response. Should point to http://www.doxygen.nl/manual/index.html

**Comment by albert-github** [comment]
1.18.13 is an older version (December 2016) and the structure has changed slightly, current version looks like to be pointing to the right version.

@doxygen maybe a link on the website is possible.

**Comment by albert-github** [comment]
This problem has been solved in doxygen release 1.8.15 (December 27, 2018).

I think the problem is solved in the mean time.
