### ISSUE TITLE
C++: Warning for missing return type in deleted or defaulted methods

### ISSUE THREAD

**Issue by rempke** [doxygen/doxygen#7299]
```
/// Class with defaulted assignment operators.
class A
{
public:
  /// Default assignment.
  A &operator=(const A &) = default;
  /// Default move assignment.
  A &operator=(A &&) = default;
};

/// Class with deleted assignment operators.
class B
{
public:
  /// No assignment.
  B &operator=(const B &) = delete;
  /// No move assignment.
  B &operator=(B &&) = delete;
};
```
leads to
```
DoxygenTest.hpp:5: warning: return type of member A::operator= is not documented
DoxygenTest.hpp:7: warning: return type of member A::operator= is not documented
DoxygenTest.hpp:14: warning: return type of member B::operator= is not documented
DoxygenTest.hpp:16: warning: return type of member B::operator= is not documented
```
I would have expected that no warnings would appear. At least for the deleted methods it makes no sense to document the return type, and for the defaulted methods it seems to me like overkill to insist on documenting it.

**Comment by albert-github** [comment]
In the current version I don't see any warnings (but also no description of the operators (wit a default Doxyfile).

- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.
- Please also specify the doxygen version used.

**Comment by rempke** [comment]
[Here](https://github.com/doxygen/doxygen/files/3697129/example.zip) is a minimum example. The only change from a default configuration is `WARN_NO_PARAMDOC = YES`. In the initial example I forgot to mark the members public to have them processed with default configuration.

I used doxygen version 1.8.15.

**Comment by albert-github** [comment]
I added the `public:` in the original post.
Wouldn't it be better understandable and correct (as the warnings do suggest already) when in `class B` not an `A` was used but a `B`?

I tested with 1.8.15 and saw the 4 messages.
When using version 1.8.16 (and the current too master)  the messages about the 'deleted' (`class B`) were gone, the messages about 'default' (`class A`) were still present.

**Comment by rempke** [comment]
Thanks for updating. Yes, indeed! Should of course be B in class B, was a copy'n'paste error. But that actually does not change doxygens behaviour.

Great to hear half of the problem is already fixed, I will update soon. What about the 'defaulted' methods? Since it is not warning about missing argument documentation, I think it should also not warn about a missing return value here.

**Comment by albert-github** [comment]
The fact that the 'delete' don't have a warning anymore is based on issue #6607 / pull request #6918.

When we add a normal function to `class A` (or `class B`) like:
```
  /// Normal function
  int normal_fie(int);
```

We get the warning:
```
.../DoxygenTest.hpp:11: warning: return type of member A::normal_fie is not documented
```

The same procedure is followed for the 'default' functions / operators.

I think the issue as a matter of interpretation / usage.

**Comment by albert-github** [comment]
The complete business about when a warning is given or not is very complex.
It depends on whether or not an entity has any documentation, `EXTRACT_...`, `WARN...`, ...
