### ISSUE TITLE
Parts of the document and code are displayed on one page

### ISSUE THREAD

**Issue by NeilZhy** [doxygen/doxygen#7316]
Save parts of the code document at the top of the code page

**Comment by albert-github** [comment]
It is complemetely unclear what you want, please explain and:
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.
- Please also specify the doxygen version used.

**Comment by NeilZhy** [comment]
Thanks.
The latest questions are as follows：
[https://github.com/doxygen/doxygen/issues/7317](url)

**Comment by albert-github** [comment]
What is the meaning of the comment? 
Does it mean that the mentioned issues are the same as the problem you have and thus this issue is a duplicate?
