### ISSUE TITLE
Grouping error

### ISSUE THREAD

**Issue by Thomas-Frank** [doxygen/doxygen#7324]
The html-output of doxygen is broken for the last group of methods before a 'protected'-section, that does not start with a new group. Example (doxygen 1.8.16 apllied with default config):
```c++
/**
 * @brief The class
 */
class Test
{
public:
	/// @name Group1
	//@{
	/// 1st Method in public Group 1
	void Mthd1a();

	/// 2nd Method in public Group 1
	void Mthd1b();
	//@}

	/// @name Group2
	//@{
	/// 1st Method in public Group 2
	void Mthd2a();

	/// 2nd Method in public Group 2
	void Mthd2b();
	//@}

protected:
	/// 1st Method in protected Group 3
	void Mthd3a();

	/// 2nd Method in protected Group 3
	void Mthd3b();
};
```
The protected methods become members of 'Group2'. The 'Protected Member Functions'-section is skipped and the header of 'Group2' is formatted the way a 'Protected Member Functions'-header would get formatted. All is ok, as soon as you wrap the protected methods into a 'Group3'.

**Comment by albert-github** [comment]
You are using `//@{` but you should use `///@{` (correction made for 1.8.16.
I didn't yet test your problem, but does this solve your problem.

**Comment by albert-github** [comment]
As written in my initial quick comment the pre 1.8.16 versions of doxygen had the problem that they accepted some doxygen commands, like `@{`, in normal `//` C / Cpp comment. This has been corrected in version 1.8.16. Also due to the way of handling `//` and `///` it is necessary to have a non doxygen comment line after `@{`.
The resulting code should look like:
```
/**
 * @brief The class
 */
class Test
{
public:
        /// @name Group1
        ///@{

        /// 1st Method in public Group 1
        void Mthd1a();

        /// 2nd Method in public Group 1
        void Mthd1b();
        ///@}

        /// @name Group2
        ///@{

        /// 1st Method in public Group 2
        void Mthd2a();

        /// 2nd Method in public Group 2
        void Mthd2b();
        ///@}

protected:
        /// 1st Method in protected Group 3
        void Mthd3a();

        /// 2nd Method in protected Group 3
        void Mthd3b();
};
```

**Comment by Thomas-Frank** [comment]
Thanks for the quick reply! With your corrections applied, everything looks ok indeed. Replacing all ``//@`` with ``///@`` in my code is ok, while the additional newline to me is kind of a pity from an ethical point of view. But it seems to be unnecessary as long as the first comment afterwards uses the ``/** ... */`` syntax. Is this by accident or can I rely on this behaviour through the next doxgen versions?

**Comment by albert-github** [comment]
> But it seems to be unnecessary as long as the first comment afterwards uses the /** ... */ syntax. Is this by accident or can I rely on this behaviour through the next doxgen versions?

I would not rely on on, the preprocessor might decide to join the `///` and `/**` in later versions of doxygen (no plans for it though, but it can always be a side effect).
