### ISSUE TITLE
@brief not working when part of @include{doc} file

### ISSUE THREAD

**Issue by skierkit** [doxygen/doxygen#7337]
I use TCL and javadoc style (@) for special commands. The @brief statement doesn't work when put inside my include file, called with "@include{doc} myfile"

In the log, I get:
warning: Found unknown command `\brief'

I'm not sure if that matters and is just wrong in the warning print, but I used @brief, not \brief.

**Comment by albert-github** [comment]
Regarding the warning (about `\brief`) and the input `@brief` for doxygen there is no difference.
When you would have used `\brief` instead of `@brief` you would have gotten the same warning.

**Comment by skierkit** [comment]
I am using Doxygen 1.8.15. Let me put together a small example.

**Comment by skierkit** [comment]
[github_7337_testcase.tar.gz](https://github.com/doxygen/doxygen/files/3744497/github_7337_testcase.tar.gz)

**Comment by albert-github** [comment]
• By means of commit 58ea5cf320f08ae2ec3e5fbd02d82ca0ba4477a7  the support has been removed from doxygen.
