### ISSUE TITLE
What about nightly or pre-release builds?

### ISSUE THREAD

**Issue by oktonion** [doxygen/doxygen#7343]
Hello.

Current release cycle of doxygen is like once a year and it seems like an eternity. What about the idea to do once-a-month pre-release builds via CI and github releases for testing purposes and early adopters?

Also why are there no binaries of doxygen on github releases? Since you moved there it seems odd to me to not use github release system.

**Comment by albert-github** [comment]
See the comment https://github.com/doxygen/doxygen/issues/7343#issuecomment-950353934 I think we can consider this as being solved in the mean time.
