### ISSUE TITLE
Conditionally skip copying jquery ?

### ISSUE THREAD

**Issue by simevo** [doxygen/doxygen#7367]
I found this old patch in the Debian package of doxygen, it was misapplied, I "fixed it":
https://salsa.debian.org/debian/doxygen/blob/master/debian/patches/doxygen-jquery.patch

but does it make sense at all ?
do you want to incorporate it in your sources ?

**Comment by albert-github** [comment]
I'm not sure but wouldn't this give problems with:
- templates/html/header.html
- templates/html/htmlbase.tpl

where it is used unconditionally.

Same might be the case when using `USE_MATHJAX` and `dynsections.js`, but I don't know how much they use `jquery.js` (for `USE_MATHJAX` maybe for setup).

**Comment by simevo** [comment]
indeed it's included **and** used for example in `htmlbase.tpl`:
```
<script type="text/javascript">
  $(document).ready(initResizable);
</script>
```

I can understand (and appreciate) the original intention (reduce the footprint of the generated docs, avoid embedding unnecessary JavaScript libraries) but it is likely to break things.

So I'm inclined towards removing this patch altogether. More drastic but effective approach is #7363 :smiling_imp: 
Go ahead and close this issue if you agree

**Comment by simevo** [comment]
I have "updated" the patch here:
https://salsa.debian.org/debian/doxygen/blob/master/debian/patches/doxygen-jquery.patch

like this:
--- doxygen.orig/src/htmlgen.cpp
+++ doxygen/src/htmlgen.cpp
@@ -775,7 +775,10 @@ void HtmlGenerator::init()
   {
     mgr.copyResourceAs("fixed_tabs.css",dname,"tabs.css");
   }
-  mgr.copyResource("jquery.js",dname);
+  if (Config_getBool(GENERATE_TREEVIEW) || Config_getBool(SEARCHENGINE))
+  {
+    mgr.copyResource("jquery.js",dname);
+  }
   if (Config_getBool(INTERACTIVE_SVG))
   {
     mgr.copyResource("svgpan.js",dname);

But according to upstream:
https://github.com/doxygen/doxygen/issues/7367
this updated patch does not make much sense.

I have tested it with the simplest possible doxygen project (attached).
Running doxygen with the patch above runs fine with the default Doxyfile (generated with doxygen -g).
When I turn off the SEARCHENGINE option (GENERATE_TREEVIEW is already OFF), clean up and regenerate the html docs, indeed html/jquery.js is absent as expected.

But the generated docs are broken, they look different and they cause JavaScript errors in the Chromium console:

GET file:///tmp/tmp.sgSjjEtEsw/html/jquery.js net::ERR_FILE_NOT_FOUND
index.html:34 Uncaught ReferenceError: $ is not defined
    at index.html:34

So I am going to disable this patch altogether.

Paolo
