### ISSUE TITLE
Method parameters documented inline are not present in documentation when using @copydoc

### ISSUE THREAD

**Issue by laurent-radoux** [doxygen/doxygen#7386]
Hi,

I'm using Doxygen version 1.8.16 and it appears that method parameters that are documented inline are not present in the documentation of methods that use the `@copydoc` special command.

Here is a sample code showing the intended behaviour using constructors as an example:
```
/*! @brief Parent class
*/
class A_Inline
{
public:
   /*!
      @brief Constructor
   */
   A_Inline(int p /*!< test */);
};

/*! @brief Child class
*/
class B_Inline : public A_Inline
{
public:
   /*!
      @copydoc A_Inline::A_Inline
   */
   B_Inline(int p);
};
```

The expected output would be that the whole documentation of `A_Inline`'s constructor, with the parameter, is copied, although I have the following output:
![PrtScr capture_2](https://user-images.githubusercontent.com/50481138/68460952-658e3080-0209-11ea-810d-6b7524e4baa6.png)
![PrtScr capture](https://user-images.githubusercontent.com/50481138/68460957-6b841180-0209-11ea-89c4-e65cec78e33d.png)

Here is an archived containing everything required to reproduce this issue:
[inline_param_documentation_copydoc.zip](https://github.com/doxygen/doxygen/files/3823595/inline_param_documentation_copydoc.zip)

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #9908

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).
