### ISSUE TITLE
Doxywizard v1.8.13 - Update of expert output pane does not update

### ISSUE THREAD

**Issue by ad5xj** [doxygen/doxygen#7398]
v 1.8.13 of Doxywizard on Linux Mint 19.2 Cinnamon

After clicking the run button on the run tab, output display is blocked as if the output is in blocking mode waiting for some interrupt or event. After a long period, some of the output is displayed. There are intermittent periods of partial update to the display until completely finished. 

This is dramatically different from the previous versions which showed a more or less "real" update of the output. I prefer to see what is happening when it happens and not delayed as this version seems to do.

**Comment by albert-github** [comment]
- Version 1.8.13 is from December 2016, the current version is 1.8.16, can you try this version?
- you mentioned "This is dramatically different from the previous versions ..." which version do you refer to?

**Comment by ad5xj** [comment]
This version came from the Mint repo. I would have to download and install later versions directly.

However, I can say that 1.5 did not have this problem. It displayed more or less in near "real time".

**Comment by albert-github** [comment]
Would be good when you could test it with 1.8.16.
With 1.5 do you mean 1.5.x or 1.8.5?

**Comment by albert-github** [comment]
Unfortunately no further information about the problem and it is also not reproducible.
(current version of doxygen is 1.9.6)
