### ISSUE TITLE
Inconsistent handling in nested classes

### ISSUE THREAD

**Issue by albert-github** [doxygen/doxygen#7405]
When we have a construct like:
```
class Iface
{
  public:
    Iface();
    ~Iface();
};

class Iface::Private
{
  public:
    Private();
    ~Private();
};

class Q_DECL_HIDDEN Iface::Private_Hidden
{
  public:
    Private_Hidden();
    ~Private_Hidden();
};
```

We see as output:
![img1_class](https://user-images.githubusercontent.com/5223533/69008256-d1c70d80-0948-11ea-85c1-e281d24e1323.jpg)

and:
![img2_files](https://user-images.githubusercontent.com/5223533/69008262-d986b200-0948-11ea-9212-bb8063c69504.jpg)

It is a bit strange that `~Private_Hidden` is seen as a destructor in `Iface` whilst `Private_Hidden` is seen as a Member Function.

Expected would be that both are handled in the same way.
The deeper problem is that doxygen gets confused by the `Q_DECL_HIDDEN `, it is easy to overcome the problem by setting in the `Doxyfile`:
```
MACRO_EXPANSION=YES
PREDEFINED = Q_DECL_HIDDEN=
```

Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/3855601/example.tar.gz)

**Comment by doxygen** [comment]
@albert-github Without the macro definition this is also invalid code for a compiler. So this is a limitation in doxygen which I don't think is not possible to fix in general. The suggested workaround is the right one.

To illustrate my point, one could even define the class like this

```c
class Q_DECL_HIDDEN Iface DOUBLE_COLON Private_Hidden
CURLY_OPEN
  public COLON
    Private_Hidden EMPTY_PARAM_LIST SEMICOLON
    TILDE Private_Hidden EMPTY_PARAM_LIST SEMICOLON
CURLY_CLOSE SEMI_COLON
```

in which case doxygen would just see a list of identifiers.

**Comment by albert-github** [comment]
I agree that the definition is the right way to solve the problem and i was hoping that when not having the define there might have been a "simple" solution to have the constructor and destructor be handled in a parallel way as the destructor is properly seen (but probably only due to the fact it has `~`).
