### ISSUE TITLE
Latex generation ignores ALPHABETICAL_INDEX setting in macOS Doxywizard 1.8.16

### ISSUE THREAD

**Issue by Paraphraser** [doxygen/doxygen#7424]
With ALPHABETICAL_INDEX disabled:

<img width="890" alt="Screen Shot 2019-12-01 at 12 13 54" src="https://user-images.githubusercontent.com/34226495/69908103-ec17e580-1436-11ea-8073-98c4493de688.png">

and confirmed by Show Configuration:

```
#---------------------------------------------------------------------------
# Configuration options related to the alphabetical class index
#---------------------------------------------------------------------------
ALPHABETICAL_INDEX     = NO
COLS_IN_ALPHA_INDEX    = 5
IGNORE_PREFIX          =
```

The Latex makefile still produces an index:

```
LATEX_CMD=pdflatex

all: refman.pdf

pdf: refman.pdf

refman.pdf: clean refman.tex
	$(LATEX_CMD) refman
	makeindex refman.idx		««««««««
	$(LATEX_CMD) refman
	latex_count=8 ; \
	while egrep -s 'Rerun (LaTeX|to get cross-references right)' refman.log && [ $$latex_count -gt 0 ] ;\
	    do \
	      echo "Rerunning latex...." ;\
	      $(LATEX_CMD) refman ;\
	      latex_count=`expr $$latex_count - 1` ;\
	    done
	makeindex refman.idx		««««««««
	$(LATEX_CMD) refman


clean:
	rm -f *.ps *.dvi *.aux *.toc *.idx *.ind *.ilg *.log *.out *.brf *.blg *.bbl refman.pdf
```

Workaround is to set nonsense command returning no output in MAKEINDEX_CMD_NAME:

```
#---------------------------------------------------------------------------
# Configuration options related to the LaTeX output
#---------------------------------------------------------------------------
GENERATE_LATEX         = YES
LATEX_OUTPUT           = latex
LATEX_CMD_NAME         =
MAKEINDEX_CMD_NAME     = "ls >/dev/null"		««««««««
LATEX_MAKEINDEX_CMD    =
```

which results in:

```
LATEX_CMD=pdflatex

all: refman.pdf

pdf: refman.pdf

refman.pdf: clean refman.tex
	$(LATEX_CMD) refman
	ls >/dev/null refman.idx 		««««««««
	$(LATEX_CMD) refman
	latex_count=8 ; \
	while egrep -s 'Rerun (LaTeX|to get cross-references right)' refman.log && [ $$latex_count -gt 0 ] ;\
	    do \
	      echo "Rerunning latex...." ;\
	      $(LATEX_CMD) refman ;\
	      latex_count=`expr $$latex_count - 1` ;\
	    done
	ls >/dev/null refman.idx 		««««««««
	$(LATEX_CMD) refman


clean:
	rm -f *.ps *.dvi *.aux *.toc *.idx *.ind *.ilg *.log *.out *.brf *.blg *.bbl refman.pdf
```

and the (desired-by-me) omission of the index.

**Comment by albert-github** [comment]
I think the mentioned version number 1.18.6 was a typo and should have been 1.8.16

I think there is a misunderstanding about which indexes are meant.
The `ALPHABETICAL_INDEX` is meant for the use with a.o. the "File index", "Class index"  pages etc. and this can be disabled by means of the mentioned configuration setting (Note also the setting `LATEX_HIDE_INDICES`, has not the effect you request).

As far as I can see you mean the "Index" at the end of the LaTeX  document, and this is not related to the `ALPHABETICAL_INDEX`.

@doxygen What to do with the "Index" at the end of a LaTeX document (and maybe other formats, I didn't check them) in case `ALPHABETICAL_INDEX` / `LATEX_HIDE_INDICES` has been disabled. Should there be a distinction between items from e.g. "Class index" etc. and explicit anchors?

**Comment by albert-github** [comment]
As already indicated in the previous comment the `ALPHABETICAL_INDEX` and `LATEX_HIDE_INDICES` only work for compounds and not on the "standard" index at end of the LaTeX output.

A solution is to create your own "footer.tex"  (for the default latex header and footer generate them by means of `doxygen.exe -w latex headerFile footerFile styleSheetFile`, modify the `footerFile` and set in the settings file: `LATEX_FOOTER = LATEX_FOOTER`.

I think the problem is usage.
