### ISSUE TITLE
doxygen manpages not built on faceless host

### ISSUE THREAD

**Issue by birnbacs** [doxygen/doxygen#7429]
I compiled 1.8.15 doxygen on a FreeBSD server without X11. I therefore deselected all build options except doxygen and search. Building was real quick :-) However, the doxy manpages did not get installed, which is a bit of a nuisance. 

On a different system I activated more options and the manpages got built -- along with tons of X11-related stuff, which took several hours. It seems to me the manpages should get installed in any case and they should not require graphics support. In fact I am not sure if not many doxygen options could be activated without requiring graphics libraries.

I also could not find a way to make doxygen process its own sources to generate manpages (this came as a surprise but maybe it's just me.)

**Comment by albert-github** [comment]
- When I understand it correctly you installed a binary package of doxygen 1.8.15 on FreeBSD or is it a source version?
- I assume you are talking about the file:
  - man/doxygen.1
  - man/doxyindexer.1
  - /man/doxysearch.1
  - man/doxywizard.1

- Which commands did you use? and which choices did you have (especially when it is a binary distribution)?
- The graphical stuff is, by head, only needed for the doxywizard.
- Do you have any idea which option got you the manual pages, most likely when installing the documentation.

Small side note: The current version is 1.8.16 (but might not yet been available for FreeBSD in binary form).

**Comment by birnbacs** [comment]
- I am using source version 1.8.15_2,2. According to freshports.org this is the most recent port available for FreeBSD. There is no binary distributed software on the host.

- the files you name are correct. On my other system they show up as /usr/local/man/man1/doxygen.1.gz etc.

- for compiling I used portmaster, which is a fairly simple frontend for make. When I select only 'doxygen' and 'search' no other software is prompted for installation. Here is the configuration I use:
`[develop@web1 /usr/ports/devel/doxygen]$ make showconfig
===> The following configuration options are available for doxygen-1.8.15_2,2:
     DOCS=off: Build and/or install documentation
     GRAPHVIZ=off: Graphviz graph drawing support
     LATEX=off: LaTeX support
     QT5=off: Install Doxywizard GUI with Qt5
     SEARCH=on: Build external search tools (doxysearch and doxyindexer)
===> Use 'make config' to modify these settings
`

- the system that (eventually) built the manpages is configured thus:
`[develop@ixie /usr/ports/devel/doxygen]$ make showconfig
===> The following configuration options are available for doxygen-1.8.14_1,2:
     DOCS=on: Build and/or install documentation
     GRAPHVIZ=on: Graphviz graph drawing support
     LATEX=on: LaTeX support
     SEARCH=on: Build external search tools (doxysearch and doxyindexer)
====> Options available for the radio DOXYWIZARD: you can only select none or one of them
     QT4=off: Install Doxywizard GUI with Qt4
     QT5=off: Install Doxywizard GUI with Qt5
===> Use 'make config' to modify these settings`

- I confess that I got quite lost setting the options. As soon as anything besides 'doxygen' and 'search' is selected, a myriad of packages follows in the slipstream and I could not figure out which one has the huge requirements. Building with docs took about 5 hours on a 2-core AMD à 2.1 GHz.

**Comment by birnbacs** [comment]
Here is the recursive configuration on both systems. blackbox is the slower system with all bells and whistles, web1 is the newer and faster one without doxygen documentation.

[doxy_blackbox.txt](https://github.com/doxygen/doxygen/files/3931471/doxy_blackbox.txt)
[doxy_web1.txt](https://github.com/doxygen/doxygen/files/3931472/doxy_web1.txt)

**Comment by albert-github** [comment]
I don't know what has been changed for 1.8.15_2,2 for FreeBSD (and I don't see a quick reference to the the relevant source package).
I'm not familiar with postmaster (for doxygen nowadays cmake is used).
Some big packages are the QT package (for doxywizard) and the LaTeX package. The Latex Package is required to build the PDF documentation for the doxygen package and also when one wants themselves have PDF documentation from ones own sources.
So maybe setting DOCS to yes and LATEX to no might work in your case, but, in my opinion, any sensible *nix type system should have LaTeX installed.

**Comment by birnbacs** [comment]
Thanks for your insights. I meanwhile found out that X11 can be excluded from build with `OPTIONS_UNSET=X11` in file `/etc/make.conf`. Portmaster is not to worry about, it is essentially a shell wrapper with some ASCII-art around the `make configure, make, make install, make clean` commands. 

I also found out that a required package called pango can currently not be built without X11, which is a problem in itself. 

Besides all this, is LaTEX really required to build doxygen manpages? And should not doxygen be able to generate its own manpages by processing its own source files?

**Comment by albert-github** [comment]
LaTeX is not required for man pages, but due that it looks like one can only get the man pages in case on includes docs (and docs does need LaTeX for formulas and the doxygen_manual.pdf) it is a dependency.
You can find the man pages in the sources on the `doc` directory, so you could directly copy them from this place to the destination (and I wouldn't bother with compression, files are very small).

**Comment by birnbacs** [comment]
Thanks Albert, that was good advice. I found the missing manpages under `/usr/ports/devel/doxygen/work/doxygen-1.8.15/doc/*.1` and this solves my problem. Thanks for the great work on doxygen!

**Comment by albert-github** [comment]
I think that this problem is specific to the way FreeBSD does its installation and is not a doxygen problem.
In case the current doxygen version (1.9.3) still gives problems we should pay closer attention to the problem.
Setting the problem to not a doxygen problem (i.e. usage)
