### ISSUE TITLE
/includedoc does Not Work as expected

### ISSUE THREAD

**Issue by usbman01** [doxygen/doxygen#7430]
I am using doxygen in a project which requires tables and lists. Since it is quite a amount of text I tried to split it up in several files and let `includedoc` do the job.
It seems that no tags can be used within that include files. Also markup seems not working there. The only thing which seems to work is HTML. 
Not a big thing I can create tables with HTML too but then there is the problem that `<li>` and `</li>` is not supported.

**Comment by albert-github** [comment]
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.
- Please also specify the doxygen version used.

**Comment by albert-github** [comment]
Since 2019 a lot of problems with `\includedoc` have been fixed and due to the missing example it is not possible to see what the problem is.

Marking the issue as incomplete.
