### ISSUE TITLE
Markdown auto-generated TOC section names are read from external tag files

### ISSUE THREAD

**Issue by marerk** [doxygen/doxygen#7437]
When reading an external tags file, the section names generated from Markdown files for TOC ("autotoc_md<n>") are included. This pollutes the namespace, causing section titles in main project Markdown files to reuse the ones from the external documentation.

Faulty version: 1.8.16 (and likely many older ones)

To reproduce
---------------
### In project External:
1. Have a Markdown page with sections (without explicit anchor names)
2. Configure GENERATE_TAGFILE to a value
3. Generate
### In project Local:
1. Have a Markdown page with sections (without explicit anchor names)
2. Configure TAGFILES to include the tag file from project External
3. Generate

### Effect
Section titles in project Local will reuse the titles from page in project External

Proposed solution
--------------------
Change src/tagreader.cpp to ignore section names starting with "autotoc_md".

**Comment by albert-github** [comment]
Thus might be related to #7248 (and the proposed pull request #7250).

Would be nice to have a test case from you si:
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.

**Comment by marerk** [comment]
You're right, it's the same problem as #7248. Also the proposed solution in #7250 seems better. Feel free to mark this as a duplicate.

Anyway, here's a minimalistic example to trigger the problem.

[doxygen_bug_external_autotoc_md.zip.zip](https://github.com/doxygen/doxygen/files/3954464/doxygen_bug_external_autotoc_md.zip.zip)
