### ISSUE TITLE
Markdown links reference wrong file in html

### ISSUE THREAD

**Issue by JohnAdriaan** [doxygen/doxygen#7466]
Ref: doxygen 1.8.17

If I create and process a `Test.md` file, doxygen produces two `.html` files:
* `md__test.html` - which is an HTML-ised version of the original file;
* `_test_8md.html` - a file that seems to be simply a header with "Test.md File Reference"

If I use Markdown syntax in `README.md` to reference this file:
`[Test](Test.md)`

the resultant HTML for `README` gives a hyperlink labelled "Test". Unfortunately, it's linked to the _second_ of the above two `Test.md` files, rather than the expected first.

**Comment by albert-github** [comment]
- As you explicitly mention 1.8.17 now (what is good to mention it!), did you observe the same problem with older versions?
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.

**Comment by JohnAdriaan** [comment]
I tried this first on 1.8.16, and upgraded hoping that it would fix it. Alas...

Please find attached an example ZIPped project [DOxyGen.zip](https://github.com/doxygen/doxygen/files/4007245/DOxyGen.zip) that exhibits the problem.

I used the same `Docs/DoxyFile` as in my project, although slightly anonymised. I assume it's some combination of flags that causes the problem!

**Comment by albert-github** [comment]
I did a quick test with the proposed patch #7032 and it looks like this is solving the issue.

**Comment by albert-github** [comment]
As indicated in the comment (https://github.com/doxygen/doxygen/issues/7466#issuecomment-569436600) the mentioned patch fixes the problem and this patch has been integrated in the version 1.8.18.

I think the problem has been solved in the mean time.
