### ISSUE TITLE
Perlmod generation issue with multiple grouped functions (member groups)

### ISSUE THREAD

**Issue by DGA45** [doxygen/doxygen#7490]
We are using member grouping to group functions according to their usage/category. 
For example (ANSI-C code):
```
/**
** @addtogroup comp_APVIEW_HAL_dynamic
* @{
*/

/**
* @name Scheduled by APVIEW Component
* @{
*/

/******************************************************************************/
/** @brief  Enter the APView protocol (slewrate, baudrate, ...)

@return     bTRUE if the APView protocol is successfully entered
@post       For APVIEWDEF_IS_SERIAL=0, physical layer must be configured as per specification
******************************************************************************/
byte APVIEWHALbEnter (void);

...

/** @} */

/**
* @name Scheduled by RTOS
* @{
*/

void APVIEWManage(void);
...
/** @} */

```

In the corresponding DoxyDox.pm file, the group is then containing multiple members with the same "user-defined" hash key:
```
      name => 'comp_APVIEW_HAL_dynamic',
      title => 'Dynamic behaviour interface',
      files => [
      ],
      classes => [
      ],
      namespaces => [
      ],
      pages => [
      ],
      groups => [
      ],
      user-defined => {
        header => 'Scheduled by APVIEW Component',
        members => [
          {
            kind => 'function',
            name => 'APVIEWHALbEnter',
            ...
          }
        ]
      },
      user-defined => {
        header => 'Scheduled by RTOS',
        members => [
          {
            kind => 'function',
            name => 'APVIEWManage,
            ...
          }
        ]
      },
      functions => {
      ...
```
So, when importing the DoxyDocs.pm file in Perl, we have only the latest "user-defined" definition in the parsed tree, and we are missing several ANSI-C entities from our source code.

**Comment by albert-github** [comment]
For what purpose do you use the perlmod output (just to get a feeling).

- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.
- Please also specify the doxygen version used.

**Comment by DGA45** [comment]
We are currently using Doxygen to document the design of our embedded software (architecture + detailed design).
However, since Doxygen is parsing the source code pretty well, I wanted to use its C-object database to automate a few things, like:
- computation of C structure padding: we have ECU diagnostics tools dumping ECU memory as raw bytes and then displaying interpreted fields using a XML description of the C structure. However, since the compiler is adding padding between some fields, we have to manually update our XML description file, which is painful...
- automatic expansion of C structure: the same ECU diagnostics tools are using the map file generated by the compiler to get memory addresses of the variables. However, if we want to read only one field of a structure, the map file does not give you its address.
Other things could be imagined to improve our documentation or automate our verifications (computation of some code metrics for example), etc...

I have attached a small example which reproduces the 3 issues I created up to now (doxygen v1.8.17):
[Doxy issues example.zip](https://github.com/doxygen/doxygen/files/4035994/Doxy.issues.example.zip)

**Comment by albert-github** [comment]
I'm still wondering a little bit why you use the perlmod output of doxygen and not e.g. the HTML, LaTeX, xml .. output. Are you using perl to show all the documentation?
Doxygen has the possibility to parse perl code as well by means of the filter "doxygen-filter-perl" from https://github.com/jordan2175/doxygen-filter-perl

**Comment by DGA45** [comment]
We are parsing ANSI-C code and generating the design documentation in CHM for our SW Developers.
This is working fine and produces very clean and complete documentation.

I want now to use the PerlMod output (in addition to CHM) in order to automate some of our activities thru Perl scripts.
The reason is that the $doxydocs variable generated by PerlMod is very straightforward to use in comparison to parsing the thousands of HTML/XML files :(
