### ISSUE TITLE
Doxygen doesn't process snippets inside markdown tables

### ISSUE THREAD

**Issue by dvdsosa** [doxygen/doxygen#7493]
### Issue

After documentation is built, snippets inside markdown tables are not processed, while it works ok outside md tables.

### Example
In the following code:

```
/*!
 * \page page1 Example
 *
 * | ID    | Defined in:                              |
 * |------ | -----------------------------------------|
 * | row 1 | Untouched, zero at out of reset.         |
 * | row 2 | \snippet port.c Priority SYSTICK_PRI     |
 *
 */
```
`\snippet` is not working because doxygen is adding `<\td> </tr>` to snippet block_id as doxygen outputs states:

> block marked with [Priority SYSTICK_PRI<\/td>  <\/tr>] for \snippet should appear twice in file port.c, found it 0 times

I've not found any workaround, even writing [Priority SYSTICK_PRI<\/td>  <\/tr>] in the file port.c.

This is happening in doxygen -v 1.8.17, while it worked ok in -v 1.8.13.

### Related

This bug is related to the one already solved: [https://github.com/doxygen/doxygen/issues/7113#issue-466258683](https://github.com/doxygen/doxygen/issues/7113#issue-466258683)

I have not found this issue before in here. I appreciate if developers could have a look at it.

Sourcecode: [snippetBUG.zip](https://github.com/doxygen/doxygen/files/4035212/snippetBUG.zip)

**Comment by albert-github** [comment]
Problem does not occur in 1.8.16 either.
The problem is introduced with pull request #7231 to solve issue #7228.
The `\snippet` reads everything till the end of the line. The markdown line from the example:
```
Systick (RTOS time base)           | xPortSysTickHandler | port.c                | 0         | \snippet port.c Priority SYSTICK_PRI
```
was, before this fix, converted in:
```
<tr class="markdownTableRowOdd">
    <td class="markdownTableBodyNone"> Systick (RTOS time base)
</td>
    <td class="markdownTableBodyNone"> xPortSysTickHandler
</td>
    <td class="markdownTableBodyNone"> port.c
</td>
    <td class="markdownTableBodyCenter"> 0
</td>
    <td class="markdownTableBodyNone"> \snippet port.c Priority SYSTICK_PRI
</td>
  </tr>
```
but now it is converted into:
```
<tr class="markdownTableRowOdd">    <td class="markdownTableBodyNone"> Systick (RTOS time base)</td>    <td class="markdownTableBodyNone"> xPortSysTickHandler</td>    <td class="markdownTableBodyNone"> port.c</td>    <td class="markdownTableBodyCenter"> 0</td>    <td class="markdownTableBodyNone"> \snippet port.c Priority SYSTICK_PRI</td>  </tr>
```

I see 2 possible solutions:
- revert the change (but how can we keep the line numbers a bit correct?)
- redefine the end of line so that an end of a "cell" in a table is also seen as an end of line (so probably check for, `<td>` `</td>` `<th>` `</th>` `<tr>` `</tr>` `</table>` beside a real end of line).

My preference would be the extra test on end of a "cell", but I don't know whether or not there would any cases preventing this extra test.
@doxygen advise?

**Comment by albert-github** [comment]
A new issue popped-up with similar problems.
@doxygen which implementation to choose?

**Comment by doxygen** [comment]
I have another idea. We could introduce an internal line continuation command (e.g. `\_linecont`) such that the new line that follows it is not counted. Then we could covert the table like this

```html
<tr class="markdownTableRowOdd">
    <td class="markdownTableBodyNone"> Systick (RTOS time base)\_linecont
</td>
    <td class="markdownTableBodyNone"> xPortSysTickHandler\_linecont
</td>
    <td class="markdownTableBodyNone"> port.c\_linecont
</td>
    <td class="markdownTableBodyCenter"> 0\_linecont
</td>
    <td class="markdownTableBodyNone"> \snippet port.c Priority SYSTICK_PRI\_linecont
</td>
  </tr>
```
and only have to treat the `\_linecont` command to also end any command that runs until the end of the line.

**Comment by albert-github** [comment]
Interesting idea, but I don't see the real difference with my proposed version 3.
As advantages of the `\_linecont` I see:
- possibility to have a better readable markdown output (when reverting the original change). Though for a table do we want cell definitions split over more than 1 line? (same do we want row definitions split over more than 1 line?
- possibility to use it on more places

As disadvantages of the `\_linecont` I see:
- implementation of a new internal command with all its side effects during the implementation, the proposed version 3. works.

**Comment by CJKay** [comment]
This also occurs with other commands, like @copybrief:

```
warning: @copybrief or @copydoc target 'assert</td>' not found
```

**Comment by albert-github** [comment]
@CJKay 
- can you test it with the current version 1.8.20 (better would be to test it even with the current master)? A lot has changed in this respect already.
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

**Comment by albert-github** [comment]
I rechecked the original problem with the current doxygen version (1.9.6) and here the problem does not occur anymore.
Regarding the problem as mentioned by @CJKay there is, unfortunately, no further information supplied so cannot be tested (a quick and short test showed with the 1.8.17 version did work though).

I think the problem has been solved in the mean time.

**Comment by CJKay** [comment]
Hi @albert-github, sorry for not getting back to you. I moved off the impacted project shortly after so cannot provide any further information.
