### ISSUE TITLE
plantuml not working with doxygen

### ISSUE THREAD

**Issue by apetronilhogit** [doxygen/doxygen#7500]
If I include plantuml code in the doxygen comments the file is not included in the final document.
I have tested with Doxygen wizard and in Eclipse with eclox.
/**
 *  @file       main.c
 *  @brief      Main program module.
 *
 *  @details    Main program module, first initializes all the modules, and than will loop indefinitely executing the rest of the code.

@startuml{main.png} "Main Diagram" width=5cm
[*] --> main__Initialize
main__Initialize : initializes all the modules
main__Initialize --> for
for: main program loop
for --> for
@enduml
*/

Doxygen Version 1.8.17
Plantuml 1.2019.13

**Comment by albert-github** [comment]
Doxygen gets confused by the different commenting style, when using:
```
/**
 *  @file       main.c
 *  @brief      Main program module.
 *
 *  @details    Main program module, first initializes all the modules, and than will loop indefinitely executing the rest of the code.
 *
 *  @startuml{main.png} "Main Diagram" width=5cm
 *  [*] --> main__Initialize
 *  main__Initialize : initializes all the modules
 *  main__Initialize --> for
 *  for: main program loop
 *  for --> for
 *  @enduml
*/
```

I think this problem is usage.

**Comment by apetronilhogit** [comment]
It used to work like this in previous versions.
But this solved the problem. 
Thanks.
