### ISSUE TITLE
How to use @endcode in fenced code block?

### ISSUE THREAD

**Issue by emmenlau** [doxygen/doxygen#7533]
We find in doxygen 1.8.17 that `@endcode` ends fenced code blocks, is that correct? This is an issue for our documentation.

We document our coding style guide in doxygen. The style guide embeds doxygen documentation in fenced code blocks in markdown. I know this is complex, but generally it works very well. So we write in markdown:
```
## Example class documentation
~~~{.cpp}
class Stack {
    /** @brief Constructs the object
     * @code
     * Stack vStack(5);
     * @endcode
     */
    Stack(const int aValue = 0);
}
~~~
```
Everything works great! Except that `@endcode` breaks the fenced code block.

Is it possible change doxygen to support `@code/@endcode` blocks within fenced code blocks in markdown? This would be great!

Or are we doing something suboptimal or wrong?

**Comment by albert-github** [comment]
Internally the fenced code blocks are translated to `@code` commands as can bee seen when running `doxygen -d markdown`, which gives:
```
---- input -------
@page md_aa Example class documentation
~~~{.cpp}
class Stack {
    /** @brief Constructs the object
     * @code
     * Stack vStack(5);
     * @endcode
     */
    Stack(const int aValue = 0);
}
~~~


---- output -----
@page md_aa Example class documentation
@code{cpp}
class Stack {
    /** @brief Constructs the object
     * @code
     * Stack vStack(5);
     * @endcode
     */
    Stack(const int aValue = 0);
}
@endcode
```
next phase is the comment scanner and this looks OK:
```
-----------
CommentScanner: D:/speeltuin/issue_7533/aa.md:1
input=[
@page md_aa Example class documentation
@code{cpp}
class Stack {
    /** @brief Constructs the object
     * @code
     * Stack vStack(5);
     * @endcode
     */
    Stack(const int aValue = 0);
}
@endcode


 ]
-----------
CommentScanner: D:/speeltuin/issue_7533/aa.md:1
output=[
brief=[line=-1
]
docs=[line=2
@code{cpp}
class Stack {
    /** @brief Constructs the object
     * @code
     * Stack vStack(5);
     * @endcode
     */
    Stack(const int aValue = 0);
}
@endcode]
inbody=[line=-1
]
]
===========
```
but after the next phase (doctokenizer) the message  `warning: unexpected command endcode` is given.

It might be that we need some sort of stack in the doctokinizer, but this again will give problems in case of there are no matching `@code` / `@endcode` pairs.
Difficult problem ...

Note: problem exists with older versions as well.

**Comment by emmenlau** [comment]
Thanks a lot @albert-github for the super quick response!

Do I understand correctly that mapping the fenced code blocks to `@code` commands also means that the following would be valid doxygen markup:
```
@code
// some code here
~~~
```
If yes, then it may generally improve the consistency of doxygen markdown to change this behavior?

**Comment by albert-github** [comment]
No the doxygen markdown parser is a little bit more intelligent.

As a side note you can always see the generated code after the markdown phase by means of `doxygen -d markdown`

**Comment by albert-github** [comment]
@emmenlau 
Thanjs for pinging
With which version did you try last?

I tried with the 1.9.0 version and got the warning as indicated, with the current doxygen version (1.9.6) I didn't get a warning and the output looked OK to me:
![image](https://user-images.githubusercontent.com/5223533/225974962-c8ccafb5-d4b1-4106-8e6a-6bc0fd840d15.png)


So I think the problem has been solved in the mean time.
