### ISSUE TITLE
Copybrief fails when used in markdown table (v1.8.17)

### ISSUE THREAD

**Issue by dm413** [doxygen/doxygen#7542]
In doxygen version 1.8.17, the copybrief command fails when used inside a markdown table.
This error does not occur with version 1.8.16.
I'm running on Windows 10.

For example, if your markdown file contains:

```
Function             | Use
---------------------|---------------------------
::TestFunction2()    | \copybrief TestFunction2()
```

Doxygen reports:
    `warning: @copybrief or @copydoc target 'TestFunction2()</td>' not found.`

Notice the `</td>` that has been incorrectly appended to the function name in that message.

This error does not occur if the referenced function has no parameters. You can work around the problem by appending `&nbsp;` after the copybrief reference. Another work around is to explicitly specify the parameters such as:

`    \copybrief TestFunction2(int)`

Attached is a small example that demonstrates the problem and the workarounds.
[DoxygenCopybriefTest.zip](https://github.com/doxygen/doxygen/files/4113704/DoxygenCopybriefTest.zip)

**Comment by albert-github** [comment]
The problem as reported here has the same background as issue #7035 
With #7493 an analysis has been made and also a number of possible implementation solutions.

@doxygen which implementation to choose?

**Comment by albert-github** [comment]
Ran the given problem with 1.8.16, 1.8.17 and the current doxygen version 1.9.6 

As indicated with the 1.8.17 version we get the warning, with the 1.8.16 and 1.9.6 version this warning is not present and the resulyt of `\copybrief` is properly shown.

I think the problem has been solved in the mean time.
