### ISSUE TITLE
Support PlantUML diagrams inside plantuml code blocks

### ISSUE THREAD

**Issue by TheDallenger** [doxygen/doxygen#7543]
Many makdown renderes that supports PlantUML, requires the PlantUML code to be inside a clode block/fence to work. Like this (execpt the '!'):
! ~~~plantuml
@startuml
class Test
@enduml
! ~~~

But doxygen will show this like a regular code block without language syntax, and does not render the diagram:
~~~
@startuml
class Test
@enduml
~~~

The result is that normal markdown renderes and doxygen are incompatible regarding PlantUML diagrams.

**Comment by albert-github** [comment]
Looks like this issue has a proposed pull request #6953 already.

**Comment by TheDallenger** [comment]
Thank you for your response, and sorry for not discovering the pull request myself.

**Comment by albert-github** [comment]
There is no need to close the issue as it signals the need of other people for the use of this feature and also prevents others to open new issues as long as the proposed pull request is not released.

**Comment by mwerner96** [comment]
> Looks like this issue has a proposed pull request #6953 already.

Hi, ist there any chance this PR will be integrated soon? It looks like the PR is stale, even though it would be a great feature to have.

**Comment by albert-github** [comment]
There has been a new pull request (#9196 superseding but identical to #6953) that has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release)

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.4.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
