### ISSUE TITLE
[Question] How to add `Files` item in search engine?

### ISSUE THREAD

**Issue by 625781186** [doxygen/doxygen#7554]
I see it in other people's documents ：

![image](https://user-images.githubusercontent.com/30521429/73486427-1870c380-43e0-11ea-8c58-84c8ef70fb12.png)

But my project doesn't have it : 

![image](https://user-images.githubusercontent.com/30521429/73486591-6dacd500-43e0-11ea-9255-c66148896898.png)

**So is it automatic or do I have to do it myself?**
I found extsearch but I'm not sure.
http://www.doxygen.nl/manual/extsearch.html

**Comment by albert-github** [comment]
This will be done automatically as soon as a file has **file** documentation, i.e. documentation describing the file contents.
I used the example from your issue #7555 and here the file 'out.py' has no file documentation, just documentation for the "namespace" (the first comment block starting with "## @brief Module implementing a LED widget.") and the classes / methods.
To have file documentation you probably have to add here a comment block with `\file` or set `EXTRACT_ALL=YES` as done by Fossies.
