### ISSUE TITLE
[want help] doxygen for python can't jump to line.

### ISSUE THREAD

**Issue by 625781186** [doxygen/doxygen#7555]
### Env: 
    Doxygen version 1.8.17
### Describe:
click line num but can't scroll to line.

![image](https://user-images.githubusercontent.com/30521429/73519942-5bad4f80-443d-11ea-8c1a-16cda2794e25.png)

### Repetition error:
[download source](https://github.com/625781186/test_py_doxygen/archive/repetition_error.zip)

**Comment by albert-github** [comment]
When using the output as provided and going to the indicated function I can clicjk on the '137' and I will jump to the right line in the source browser (`test_py_doxygen-repetition_error/html/out_8py_source.html#l00137`) or did I miss something in the description?

- Which browser did you use?
- Does this problem only happen here or also on similar places
- Does the problem also happen when you click on 'out.py'

**Comment by 625781186** [comment]
> When using the output as provided and going to the indicated function I can clicjk on the '137' and I will jump to the right line in the source browser (`test_py_doxygen-repetition_error/html/out_8py_source.html#l00137`) or did I miss something in the description?
> 
> * Which browser did you use?
> * Does this problem only happen here or also on similar places
> * Does the problem also happen when you click on 'out.py'

1. I use `chrime` ; 

I recorded two gif : 
1. Don't work ;
![error1](https://user-images.githubusercontent.com/30521429/73545200-d7c38980-4475-11ea-985c-2442b3e298a2.gif)


2. First success, second failure

![error2](https://user-images.githubusercontent.com/30521429/73545268-f88bdf00-4475-11ea-87f5-6fda6f150b0f.gif)

**Comment by albert-github** [comment]
As I cannot read what is on the pop-up windows it is hard to understand what is going on.

You wrote that you use `chrime` but I assume this is just a typo and should be `chrome` 

I tested it with `chrome` and didn't find a problem, though from the past I know that there were some issues with protection settings in `chrome`  and it was necessary to use the option `--allow-file-access-from-files` when starting `chrome` (I didn't need it with the version I used: Version 79.0.3945.130 (Official Build) (64-bit))

Can you test it with another browser as well?

**Comment by 625781186** [comment]
> As I cannot read what is on the pop-up windows it is hard to understand what is going on.
> 
> You wrote that you use `chrime` but I assume this is just a typo and should be `chrome`
> 
> I tested it with `chrome` and didn't find a problem, though from the past I know that there were some issues with protection settings in `chrome` and it was necessary to use the option `--allow-file-access-from-files` when starting `chrome` (I didn't need it with the version I used: Version 79.0.3945.130 (Official Build) (64-bit))
> 
> Can you test it with another browser as well?

You are right.
It's work every time when I use `IE browse`r or use `--allow-file-access-from-files` in `chrome`.
