### ISSUE TITLE
unreproducible pdf files in latex examples

### ISSUE THREAD

**Issue by simevo** [doxygen/doxygen#7561]
I am struggling to make doxygen itself build reproducibly in Debian, which is currently failing with 1.8.16:
https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/diffoscope-results/doxygen.html

One of the issues (nevermind the others, I think I have addressed them all) is that a `CreationDate` field is written to the pdf files as this one: `doxygen/html/examples/diagrams/latex/class_a__coll__graph.pdf`which is influenced by the build time and date and not by `SOURCE_DATE_EPOCH`

To reproduce:
```
cd doxygen/examples
mkdir -p ../html/examples/diagrams
doxygen diagrams.cfg
strings ../html/examples/diagrams/latex/*.pdf | grep CreationDate
```
this returns something like:
```
   /CreationDate (D:20200201190259+01'00)
   /CreationDate (D:20200201190259+01'00)
   /CreationDate (D:20200201190259+01'00)
   /CreationDate (D:20200201190259+01'00)
   /CreationDate (D:20200201190259+01'00)
   /CreationDate (D:20200201190259+01'00)
   /CreationDate (D:20200201190259+01'00)
   /CreationDate (D:20200201190259+01'00)
   /CreationDate (D:20200201190259+01'00)
   /CreationDate (D:20200201190259+01'00)
   /CreationDate (D:20200201190259+01'00)
   /CreationDate (D:20200201190259+01'00)
   /CreationDate (D:20200201190259+01'00)
   /CreationDate (D:20200201190259+01'00)
   /CreationDate (D:20200201190259+01'00)
   /CreationDate (D:20200201190259+01'00)
   /CreationDate (D:20200201190259+01'00)
```
have you got any idea what component inserts these and how I make it set them equal to `SOURCE_DATE_EPOCH` ?

I'd rather fix the underlying issue than prepending `faketime @$SOURCE_DATE_EPOCH` to all lines in `examples\CMakeLists.txt`

**Comment by albert-github** [comment]
Some observations:

I see your issue as well but it is (for me) different on Windows and Cygwin but different `dot` versions are used here as well.
I've created a smaller example (based on the diagram example from doxygen): [example.tar.gz](https://github.com/doxygen/doxygen/files/4144132/example.tar.gz)


Windows
---------
- dot - graphviz version 2.38.0 (20140413.2041)
- in latex/class_a__coll__graph.pdf
  ```
  13 0 obj
  << /Creator (cairo 1.8.10 (http://cairographics.org))
   /Producer (cairo 1.8.10 (http://cairographics.org))
  >>
  endobj
  ```

Cygwin
--------
- dot - graphviz version 2.40.1 (20161225.0304)
- in latex/class_a__coll__graph.pdf
  ```
  12 0 obj
  << /Producer (cairo 1.16.0 (https://cairographics.org))
   /CreationDate (D:20200202130726+01'00)
  >>
  endobj
  ```

So looks a bit like the `cairo` version used in the `dot` program causes the issue.
I looked in the cairo source code (https://github.com/freedesktop/cairo) and saw that in the cairo version 1.16 this information was added (October 1, 2016). I don't see a generic way to suppress it though.

**Comment by simevo** [comment]
Thanks for the comments. I have found the cairo commit you reference:
https://github.com/freedesktop/cairo/commit/5bfadd5530623d3b12fadf8cd22f95cec4132b65
https://gitlab.freedesktop.org/cairo/cairo/commit/5bfadd5530623d3b12fadf8cd22f95cec4132b65

This simple cairo sample outputs a PDF file ([basket_pdf.zip](https://github.com/doxygen/doxygen/files/4146473/basket_pdf.zip)) and it adds the metadata by default without explicitly invoking `cairo_pdf_surface_set_metadata`.

An option would be to address this "fixing" dot (as it was done with inkscape: https://gitlab.com/inkscape/inkscape/-/merge_requests/219/diffs), but I feel that from dot's POV it's perfectly reasonable to add metadata to the generated PDF files. So I'll try to solve this for reproducible builds in some other way (I am thinking about stripping metedata with [mat2](https://0xacab.org/jvoisin/mat2)).

Anyway closing here.
