### ISSUE TITLE
External Links in Inheritance Diagrams open in the Image Frame.

### ISSUE THREAD

**Issue by sawatts** [doxygen/doxygen#7583]
### External Links in Inheritance Diagrams open in the Image Frame.

Documentation is generated as HTML for a number of projects and published to an internal host in adjacent folders.  Each documentation set includes a tag file, allowing new documentation sets to be cross-linked.

Inheritance diagrams with UML style are included, and contain links to the pages for their elements, which may be in the same document set or one of the others on the same host.

Links to pages within the same document set replace the current page in the browser with any other link.

Links to pages in other document sets are opened *within* the frame containing the diagram.  The link is otherwise correct, and opening it in a new tab or window is a workaround.

This is probably not unique to inheritance diagrams.

- Source type: C++
- Doxygen: 1.8.15
- GraphViz: 2.38.0
- Generated On: Linux x86_64, RHEL 6.2

**Comment by albert-github** [comment]
- What happens when you use the current version of doxygen (1.8.157) ?
- which browser (and version) are you using?
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent. Probably there needs also to be a small description on which links to click on (including images to make it more clear).

**Comment by sawatts** [comment]
- The version of _Doxygen_ is controlled by our infrastructure team and outside my control.
- Browsers - I have retested on all browsers on my desktop and they exhibit the same behaviour:
  -  Google Chrome 80.3987.116 on Windows 10 Enterprise (1709) (x64)
  -  Internet Explorer 11.1685.16299.0 (on same)
  -  Microsoft Edge 41.16299.1480.0 / Microsoft EdgeHTML 16.16299 (on same)

The host system is (probably) a Linux RHEL running Apache.

Attached is a tarball of a sample set of three projects:

[doxygen-7583-1.tar.gz](https://github.com/doxygen/doxygen/files/4235920/doxygen-7583-1.tar.gz)

There are three projects described in this archive - _alpha_, _beta_, _gamma_.  Each project contains the equivalent set of files:
- `${PROJECT}/doxygen-${PROJECT}.log` - _Doxygen_'s log output from the build.
- `${PROJECT}/src/${PROJECT}.h` - The project's single header file.
- `${PROJECT}/Doxyfile.${PROJECT}-api` - The _Doxyfile_ passed to _Doxygen_.
- `${PROJECT}/${PROJECT}-api.tar.gz` - The generated documentation set.

Each project defines a single class in the global namespace, which form a three-level inheritance hierarchy `alpha` <|-- `beta` <|-- `gamma`.

I have not included our build framework files in this - as these use a combination of _make_ and _cmake_ and reference out to external custom modules required to cover our project build needs, which are not relevant to generating the documentation other than forming the _Doxyfile_ and invoking `doxygen`.

The doc tarballs should be extracted under the same directory, giving `alpha`, `beta`, and `gamma` subdirectories, for the cross-linking to work.

In each documentation set, the inheritance and collaboration diagrams show the base and derived classes for the single class defined in that project.  These diagram elements contain hyperlinks to the appropriate page in the other documentation set.

**Page in Project Gamma for class gamma, showing inheritance diagram expanded:**

![doxygen-7583-1](https://user-images.githubusercontent.com/23358267/75034609-748dab80-54a5-11ea-910b-5b4dc8bf6780.png)

**After clicking on the hyperlink for class alpha in the inheritance diagram shown above:**

![doxygen-7583-2](https://user-images.githubusercontent.com/23358267/75034614-7bb4b980-54a5-11ea-9eb4-00b5da1bc704.png)

**Build Details**

The published documentation sets include the "tag" file as `${PROJECT}.tag` in their top directory (eg. `alpha/alpha.tag`).

The build framework looks for these tag files in the publish directory, and adds them to the configuration in the _Doxyfile_ to provide cross-linking.  All tag file found, other than self, are provided to the build.

Therefore the documentation sets included in the tarball are the result of the second batch build - were the publishing area already had doc sets for each project to provide full cross-linking.

One nice thing with this - which was unexpected but very useful - is that we get to see classes which _inherit_ from a project's class, not just its bases.  However I don't think this affects the issue.

**Comment by albert-github** [comment]
It looks to me that it is attempted to place the page where the alpha / beta refer to in the inheritance gamma image try to squeeze the entire page in the place of the image.
The configuration possibility tag `EXT_LINKS_IN_WINDOW` exists:

> If the EXT_LINKS_IN_WINDOW option is set to YES, doxygen will open links to external symbols imported via tag files in a separate window. 
> 
> The default value is: NO.
> 
> This tag requires that the tag GENERATE_HTML is set to YES.
> 

I think when setting `EXT_LINKS_IN_WINDOW` it will solve the problem.

**Comment by sawatts** [comment]
I will add that to our configuration as a workaround.  However opening the page in an image frame is still not good behaviour - links in the same doc set open correctly in the current window.

**Comment by albert-github** [comment]
Makes sense as the user doesn't know about the "sub frame" used for an image.

I've just pushed a proposed patch, pull request #7612

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.18.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
