### ISSUE TITLE
Custom Latex Stylesheet Not Working

### ISSUE THREAD

**Issue by codesniffer13** [doxygen/doxygen#7584]
I want to change the color of table headers in PDF files generated from latex, so I'm trying to override the definition of `tableheadbgcolor`.

Relevant section of Doxyfile.dox:
```
GENERATE_LATEX         = YES
...
LATEX_EXTRA_STYLESHEET = latex_custom_stylesheet.sty
```

Custom Latex Stylesheet content (latex_custom_stylesheet.sty):
```
\definecolor{red}{rgb}{1.0,0.0,0.0}

% Color used for table heading
\renewcommand{\tableheadbgcolor}{red}
```

This has no effect in the generated PDF.
I confirmed the custom latest stylesheet file (latex_custom_stylesheet.sty) is copied to the "latex" directory (along with the doxygen.sty and other .tex files) as expected.  So seems like it's just not getting picked up?

Incidentally, if I place the stylesheet commands in the custom Latex Header file it works as expected.

**Comment by albert-github** [comment]
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.
- Please also specify the doxygen version used.
- Which version of LaTeX do you use?

**Comment by codesniffer13** [comment]
Doxygen v1.8.16
Linux (Ubuntu 18.04)

```
$ latex --version
pdfTeX 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian)
kpathsea version 6.2.3
Copyright 2017 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.34; using libpng 1.6.34
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with poppler version 0.62.0
```


As I narrowed the project for a repro here it looks like the problem occurs when a custom latex header file is specified.  Works fine if the header is not specified (latex footer doesn't affect it)

[doxygen_issue_7584.zip](https://github.com/doxygen/doxygen/files/4200384/doxygen_issue_7584.zip)
.

**Comment by albert-github** [comment]
Indeed when you define your own `LATEX_HEADER  = latexHeader.tex` you are responsible for its contents and doxygen won't touch it (and cannot touch it as it does not know its contents).

So I don't this is a doxygen bug.

**Comment by codesniffer13** [comment]
I don't know enough about latex to suggest if this is typical usage or not, but from the names of the fields & their descriptions in doxyfile.dox it seemed like LATEX_HEADER handled various things of the page header, while the custom stylesheet is also picked up and parsed for style items.  Inline with doxygen already having multiple latex content files and stylesheet files:

```
latex$ ls *.tex
index.tex  _page1.tex  refman.tex

latex$ ls *.sty
doxygen.sty  longtable_doxygen.sty  tabu_doxygen.sty
```

But if this is the expected behavior perhaps a note in doxyfile.dox, eg:
```
--- ./Doxyfile.dox	2020-02-13 13:52:41.582131470 -0500
+++ ./Doxyfile.dox.7584	2020-03-05 12:15:36.338719068 -0500
@@ -1755,6 +1755,9 @@
 # section "Doxygen usage" for information on how to let doxygen write the
 # default header to a separate file.
 #
+# Note: If a header is specified then LATEX_EXTRA_STYLESHEET is ignored.
+# A custom header should include any necessary stylesheet content.
+#
 # Note: Only use a user-defined header if you know what you are doing! The
 # following commands have a special meaning inside the header: $title,
 # $datetime, $date, $doxygenversion, $projectname, $projectnumber,
@@ -1783,6 +1786,10 @@
 # Note: The order of the extra style sheet files is of importance (e.g. the last
 # style sheet in the list overrules the setting of the previous ones in the
 # list).
+#
+# Note: If LATEX_HEADER is specified then this tag is ignored.  Place custom
+# stylesheet content in the custom header.
+#
 # This tag requires that the tag GENERATE_LATEX is set to YES.
 
 LATEX_EXTRA_STYLESHEET = 
```
