### ISSUE TITLE
Missing \usepackage{ifthen} since 1.8.16

### ISSUE THREAD

**Issue by tobihan** [doxygen/doxygen#7609]
It seems that after the fix for #6769 it can happen that doxygen generates tex files that are missing \usepackage{ifthen}, which give latex (texlive 2019) errors such as

    ! Undefined control sequence.
    \DoxyCode ...}{0ex plus 0ex minus 0ex}\ifthenelse 
                                                  {\equal {#1}{0}} { {\lccod...

The reason seems to be that \usepackage{ifthen} was removed from doc/doxygen_manual.tex in commit 3f5d4ac . 

We are seeing this problem with the documentation of ppl (see https://bugs.debian.org/943451). The ppl files don't use the command ifthenelse anywhere, so I think Doxygen should include ifthen itself.

I included a test case [ifthen_example.tar.gz](https://github.com/doxygen/doxygen/files/4240403/ifthen_example.tar.gz) with only the files from ppl that are needed to reproduce this. The problem occurs when running the commands

    doxygen user.doxyconf-latex
    cd user.latex-dir/
    TEXINPUTS=$(pwd)/..:$(TEXINPUTS) pdflatex refman

**Comment by doxygen** [comment]
@tobihan With [this commit](https://github.com/albert-github/doxygen/commit/3f5d4ac5006ac05151a4e06dc00d1c048f3fe6cd) the inclusion of the `ifthen` package has moved from `doxygen.sty` to `refman.tex`. Since you use a custom LaTeX header you need to add this package also to this custom header, i.e. add

```
\usepackage{ifthen}
```

to `user.tex`. This should fix the problem.

**Comment by tobihan** [comment]
The point is that \ifthenelse is not used in user.tex so it should not be required to add the package here. If doxygen requires the package, it should include it itself.

Are you saying that everyone using a custom header has to to do this change to follow some doxygen internals?

**Comment by doxygen** [comment]
@tobihan In general I agree that packages should be self-contained, but there was some issue that prevented that in this case.
@albert-github do you remember why this change was made?

**Comment by albert-github** [comment]
Yes I do remember as we needed the array package from a special date and it had to be checked whether or not this was present.
People using their own `LATEX_HEADER` have to adjust their header file as otherwise they will run into problems with `tabu` package.
The current `refman.tex` starts with
```
%% moved from doxygen.sty due to workaround for LaTex 2019 version and unmaintained tabu package
\usepackage{ifthen}
\ifx\requestedLaTeXdate\undefined
\usepackage{array}
\else
\usepackage{array}[=2016-10-06]
\fi
```

**Comment by tobihan** [comment]
Just because the package ifthen is required in refman.tex, why did it have to be removed from doc/doxygen_manual.tex?

**Comment by albert-github** [comment]
So it won't be double mentioned as double package might lead to confusion in the future.

**Comment by tobihan** [comment]
Ah no what I actually meant was the removal of \RequirePackage{ifthen} from  templates/latex/doxygen.sty. This seems to be the problem here.

**Comment by albert-github** [comment]
This implied in the fact that when having it in doxygen.sty and refman.tex it would be double.
