### ISSUE TITLE
Incorrect horizontal vs. vertical scroll bar in tree view

### ISSUE THREAD

**Issue by lelegard** [doxygen/doxygen#7620]
Hello

There is presentation difference in the left-pane tree view of HTML output between versions 1.8.15 and 1.8.16 onward. The new presentation seems buggy because it is both ugly and inconvenient to use.

The screenshots below are used from [this project](https://github.com/tsduck/tsduck) (and its [Doxyfile](https://github.com/tsduck/tsduck/blob/master/build/Doxyfile)).

Up to version 1.8.15, the left pane extended down to the bottom of the screen. When the tree view was expanded, a vertical scroll bar appeared in the left pane so that you could browse the index tree view in the left-pane without changing the main page.

Starting with version 1.8.16, the left pane is truncated to its content, which is quite ugly. An horizontal scroll bar is present. When you expand the tree view, there is no longer any vertical scroll bar in the left pane. Thus, when you scroll the left pane, the complete page is scrolled and you lose what you were reading in the main page.

Up to version 1.8.15:
![dox1 8 15](https://user-images.githubusercontent.com/5641922/75468675-e4140700-598d-11ea-9532-ad9e8e0fd6d1.png)

Starting with version 1.8.16:
![dox1 8 16](https://user-images.githubusercontent.com/5641922/75468717-f1c98c80-598d-11ea-90ca-079555bdd7ab.png)

**Comment by albert-github** [comment]
Did you try with the current version 1.8.17 too.

Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent. Complete projects are not very useful either as they take a long time to generate.

**Comment by albert-github** [comment]
The project has itso own:
```
HTML_HEADER            = doxy-header.html                                                                                           HTML_FOOTER            = doxy-footer.html                                                                                           HTML_EXTRA_STYLESHEET  = doxy-style.css              
```
and when not using these solves the problem.
When looking at the footer file I see that some essential information misses, see the line in the default generated footer file (might be more necessary):
```
<!-- id is needed for treeview function! -->
```
The generation of the default files can be done by means of :
```
doxygen -w html headerFile footerFile styleSheetFile [configFile]
```

I think this problem is usage and the header, footer and stylesheet should be updated to the current version.

**Comment by lelegard** [comment]
Hi @albert-github 

Thank you. You were right. To get back a correct behaviour, the only think I had to add in the footer was an empty `<div>` like this:
~~~
<div id="nav-path" class="navpath"/>
~~~

What is curious is that there is zero difference in the default headers and footers between 1.8.15 and 1.8.16 but the appearance was broken after 1.8.16 only. Maybe there is a side effect in the body only.

More generally, this exhibits a problem with the possibility to define `HTML_HEADER` and `HTML_FOOTER`. A project will typically redefine them in order to customize the content or appearance only (here, I just wanted to get rid of the mention "Generated by Doxygen" [*] in the footer).

So, if you give the possibility to replace the default footer, it should only contain non-essential and replaceable aesthetic features, not functional features which break the body when missing from the footer.

This is especially true when those functional features change from one doxygen version to another.

[*] Sorry guys. As a developer, I do like Doxygen a lot, but the end user who reads the doc does not care about the software which generated it. What would you think if any time you run `ls`, `mkdir` or `doxygen`, you get "Generated by GCC"?
