### ISSUE TITLE
"not documented" warning for private nested class implemented in different file

### ISSUE THREAD

**Issue by RedDwarf69** [doxygen/doxygen#7627]
Running doxygen 1.8.15 with the contents of the attached zip file results in a

`doxygen_test/la_impl.hpp:8: warning: Compound very_important::A::B is not documented.`

warning.

Since the nested class B is private there shouldn't be a warning. The problem doesn't seem to be there if the implementation is in the same file than the class declaration.

[doxygen_test.zip](https://github.com/doxygen/doxygen/files/4286775/doxygen_test.zip)

**Comment by albert-github** [comment]
I ran the example with version 1.8.15 and got the warning as indicated.
When running with the current release, 1.8.17, the warning is gone.

I think the problem has been solved in the mean time.

Note: when setting `EXTRACT_PRIVATE` the warning reappears, but this is correct as the, private, component is not documented.
