### ISSUE TITLE
Automatic link generation in C: link to header file in other project fails (points to current project instead) when HTML location is not specified.

### ISSUE THREAD

**Issue by ecshsun** [doxygen/doxygen#7629]
I have two projects, A and B.

Project B uses TAGFILES to enable automatic link generation to entities documented in project A.

This works fine for most entities, but not for files.

Project A contains the documented file "foo.h". This is confirmed to be present in the tag file of project A.
Project B refers to "foo.h" in a documentation section, and a link is generated in the HTML output.

So far, so good. **However**, the link generated in the HTML output of project B points to `/home/myuser/project_B/foo_8h.html`, which does **not** exist. It should point to `/home/myuser/project_A/foo_8h.html`, which does exist.

Doxygen version is 1.8.13.
OS is Ubuntu 18.04.

**Comment by albert-github** [comment]
- What happens with the current doxygen version (1.8.17) ?
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.

**Comment by ecshsun** [comment]
I discovered that setting the TAGFILES according to this pattern gives correct links:

    TAGFILES = file=loc

Whereas:

    TAGFILES = file

will create dead links to the current project.

I would have expected no link at all in the latter case.

# Doxygen Issue #7629

[doxygen-issue-#7629.zip](https://github.com/doxygen/doxygen/files/4298472/doxygen-issue-.7629.zip)

Automatic link generation in C: link to header file in other project fails (points to current project instead) when HTML location is not specified.

## Instructions

1. Generate documentation for proj-a:

	cd proj-a
	doxygen

2. Generate documentation for proj-b:

	cd proj-b
	doxygen

3. Open `proj-b/html/bar_8h.html` and check the auto-link to `foo.h`.

**Comment by albert-github** [comment]
In the `Doxyfile` of `proj-b` you have written:
```
TAGFILES               = ../proj-a/proj-a-tags.xml
```
though it is not clear for doxygen from where it has to retrieve the linked documentation (as doxygen does not interpret the 'tagfile, as the tag file can be at a different place than the generated documentation), it should read:
```
TAGFILES               = ../proj-a/proj-a-tags.xml=../../proj-a/html
```
This works for doxygen 1.8.13 and for 1.8.17.

I think the problem is usage.

**Comment by ecshsun** [comment]
Yes, that is true (as I did point out), but in this case of admittedly erroneous usage (i.e. missing HTML location) you would expect Doxygen to:
- **not** produce a spurious link to proj-b/html/...
- issue a warning.

**Comment by albert-github** [comment]
When doxygen doesn't find the part after the `=` it assumes that the results of the tags are in the current `HTML_OUTPUT` (in combination with `OUTPUT_DIRECTORY`) directory.

From the documentation chapter "Linking to external documentation " (http://doxygen.nl/manual/external.html):
> A tag file typically only contains a relative location of the documentation from the point where doxygen was run.
So when you include a tag file in other project you have to specify where the external documentation is located in relation this project. You can do this in the configuration file by assigning the (relative) location to the tag files specified after the TAGFILES configuration option. If you use a relative path it should be relative with respect to the directory where the HTML output of your project is generated; so a relative path from the HTML output directory of a project to the HTML output of the other project that is linked to.

**Comment by ecshsun** [comment]
OK, a bit cryptic I would say, but thank you for your clarification and effort spent! Closing...
