### ISSUE TITLE
Spaces in the end of some special commands will result in extra newline in RTF output 

### ISSUE THREAD

**Issue by MorningBiteFan** [doxygen/doxygen#7638]
if have more than 1 space in the end of special commands like "param","author","note",

when output the doc in RTF ,will result in extra newline (as if we use `\n` or `<br>`)that  we dont want.

for example('s' for space)
`//! @note AAAA`
or
`//! @note AAAAs`

output format like:
**note**
&emsp;&emsp;AAAA

but if we use more than 1 space like
`//! @note AAAAss`
or 
`//! @note AAAAssssssss`

output format will change like:
**note**
&emsp;&emsp;AAAA
&emsp;&emsp;newline

is there any way to ignore the space in the end  to prevent the newline?

**Comment by albert-github** [comment]
This is expected behavior it is markdown syntax, 2 or more spaces at the the end of a line signal a new line.

I think this issue is usage.

**Comment by MorningBiteFan** [comment]
> This is expected behavior it is markdown syntax, 2 or more spaces at the the end of a line signal a new line.
> 
> I think this issue is usage.

You are right!
I found  "MARKDOWN_SUPPORT" checkbox in "project" expert topics,and uncheck it,then it works.

Thanks!!!!

**Comment by albert-github** [comment]
I would not set `MARKDOWN_SUPPORT=NO` (unchecked) as markdown support has a lot of advantages in using other nice layouting features. I would remove the space at the end of the lines.
