### ISSUE TITLE
[v1.8.17] PHP: AUTOLINK_SUPPORT thinks $param is a class name

### ISSUE THREAD

**Issue by yoosefi** [doxygen/doxygen#7641]
![image](https://user-images.githubusercontent.com/2010434/76675052-f89df500-6572-11ea-85aa-ae7032485400.png)

I have a class named `Factory` in my source, and in an unrelated class I have a `get()` method with a param named `$factory`

`AUTOLINK_SUPPORT` treats `$factory` as if it were a reference to the `Factory` class.

This is incorrect.

**Comment by albert-github** [comment]
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.
- Please also specify the doxygen version used
