### ISSUE TITLE
It can show  file  suffix  in  treeview classes item?

### ISSUE THREAD

**Issue by 625781186** [doxygen/doxygen#7644]
Like this : 

![image](https://user-images.githubusercontent.com/30521429/76762292-f8e4fd00-67cb-11ea-86e3-3946a188bb00.png)

**Comment by albert-github** [comment]
You are pointing to the class list and the class name is not necessarily equal to the the filename and furthermore a file can contain multiple classes.

What would be the intention of this ?

Did you have a look at the "File list"?

**Comment by 625781186** [comment]
Sorry, I seem to have asked a silly question.
You are riht , I show look at  "File list"  .
