### ISSUE TITLE
Request: use <img> tags instead of <object> tags for SVG images

### ISSUE THREAD

**Issue by tttapa** [doxygen/doxygen#7672]
Starting from Doxygen 1.8.17, SVG images in MarkDown are converted into HTML `<object>` tags. In version 1.8.16, `<img>` tags were used.

The problem with `<object>` tags is that the [GitHub Actions badges](https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository) don't support them.

For example, the following MarkDown code is converted into these HTML tags:

```md
[![Build Status](https://github.com/tttapa/Control-Surface/workflows/CI%20Tests/badge.svg)](https://github.com/tttapa/Control-Surface/actions)
```
**Doxygen 1.8.16**
```html
<a href="https://github.com/tttapa/Control-Surface/actions"><img src="https://github.com/tttapa/Control-Surface/workflows/CI%20Tests/badge.svg" alt="Build Status" class="inline"></a>
```
**Doxygen 1.8.17**
```html
<a href="https://github.com/tttapa/Control-Surface/actions"><object type="image/svg+xml" data="https://github.com/tttapa/Control-Surface/workflows/CI%20Tests/badge.svg" style="pointer-events: none;">Build Status</object></a>
```

As you can see [here](https://tttapa.github.io/Control-Surface-doc/1.1.1/Doxygen/index.html), the Doxygen 1.8.16 version displays the image correctly, while the Doxygen 1.8.17 version [here](https://tttapa.github.io/Control-Surface-doc/Doxygen/index.html) displays a large empty rectangle.

I believe this is a problem with how GitHub's servers are configured, and not a problem with Doxygen per se, but I opened a [thread on the GitHub Community Forum](https://github.community/t5/GitHub-Actions/Actions-Badge-not-working-on-GitHub-Pages-HTTP-406-Not/m-p/50325#M7795), and they told me the following:
> Github action has provided the basic usage of badge. The issue is caused by how Doxygen generate the html file, please raise an ticket here in Doxygen issue list.

Would it be possible to go back to `<img>` tags for SVG images, or to add an option in the Doxyfile?

Thanks, 
Pieter

**Comment by albert-github** [comment]
On the pages mentioned by you I don't seen in the empty rectangle, but this might be because everything is still stored on github.
So please add images to show the problem (Please don't add external links as they might not be persistent.).

When I try the problem locally (just a markdown file with the mentioned line) I can reproduce the problem, with 1.8.17 and the current master I get:
![Err_1_8_17](https://user-images.githubusercontent.com/5223533/77847173-5eb58980-71bb-11ea-9ba2-6a009058cd21.jpg)

With version 1.8.16 I get:
![OK_1_8_16](https://user-images.githubusercontent.com/5223533/77847175-62491080-71bb-11ea-93c3-a72f234dc002.jpg)

Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/4398660/example.tar.gz)

The problem looks like to be caused by:
```
Commit: 169545c73335cf4a45a2d7a21a40cc2fb17c3aaf [169545c]
Date: Saturday, December 14, 2019 3:30:39 PM

Fix logic bug in SVG detection
```
where:
```
  if (fnd!=-1) fnd=len;
```
is changed into
```
  if (fnd==-1) fnd=len;
```
which looks to me a correct change.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7673

**Comment by tttapa** [comment]
Thanks for the reply, the reason why it didn't show up in the link is because I tried some things to get it fixed, I didn't really think it through :).

Here's an image of the problem in Chrome (Doxygen 1.8.17):  
![Screenshot from 2020-03-29 14-22-26](https://user-images.githubusercontent.com/21296729/77849021-f1a8f080-71c8-11ea-8c6f-d1e64f3f144f.png)

And here's the output from Doxygen 1.8.16:  
![Screenshot from 2020-03-29 14-22-15](https://user-images.githubusercontent.com/21296729/77849026-f8376800-71c8-11ea-88a2-b1f89b22febb.png)

In Firefox, I get the same result as the image you posted.

It does indeed look like a correct change, but I think the problem is that SVG images are handled differently than other images.  
The `<object>` tag used by Doxygen seems to be the reason that the GitHub badge doesn't display correctly.  

I'm not an expert by any means, but I also have some doubts about how safe it is to use `<object>` tags for external SVG images, since they could contain JavaScript that can be used for cross-site scripting attacks.

For example, the following MarkDown code and "malicious" SVG image result in the JavaScript code being executed on the Doxygen-generated HTML page:

```markdown
![XSS](xss.svg)
```
```svg
<svg 
    version="1.1"
    baseProfile="full"
    xmlns="http://www.w3.org/2000/svg"
    width="160" height="160">
    <text x="12" y="16" font-family="Verdana" font-size="16">XSS</text>
    <script>
        alert("XSS");
    </script>
</svg>
```

**Comment by tttapa** [comment]
> I've just pushed a proposed patch, pull request #7673

That fixes it for me, thanks a lot!

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.18.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Comment by ReenigneArcher** [comment]
Is there a way to force object tags instead of img tags? SVGs can have clickable elements inside the SVG to open a URL for example, but this is only supported by object tags.

**Comment by albert-github** [comment]
We are talking here about SVG images.
We have to distinguish the following situations:
1. local images, in this case the markdown type of link is translated into a `<object>` tag as are the `\image` commands
2. images loaded  from an external source, signaled e.g. by means of `https:// ....`, these images are translated into an `<img>` tag (markdown type of link as well as `\image` commands`).

I think this behavior is correct as one doesn't want to have the possibility to execute links that one cannot, properly, control.

**Comment by ReenigneArcher** [comment]
> I think this behavior is correct as one doesn't want to have the possibility to execute links that one cannot, properly, control.

I think it's incorrect. Even if I use an https image, I can still have control of the content. Or if I want to use badges from shields.io they support objects that have multiple links.

Could an option be added to make specific https images as "safe"?

**Comment by albert-github** [comment]
With markdown type of links I don't see a possibility, with the doxygen command (`\image`) it would be possible.
@doxygen what do you think?

**Comment by ReenigneArcher** [comment]
Okay, I would need it for markdown type of links since GitHub doesn't render `<object>` tags I am forced to use `<img>` there.

I can just include some JS that converts everything over to object tags I guess.
