### ISSUE TITLE
forward declaration of template classes

### ISSUE THREAD

**Issue by erez-o** [doxygen/doxygen#7698]
Hi, 

I've noticed a problem with forward declarations of class templates.

The definition line points to the forward declaration line and not the actual declaration where the code body resides. The code body is missing in the xml.

Forward declarations of non-template classes work without problems.

Attaching a small code example.

[fwd_declarations.zip](https://github.com/doxygen/doxygen/files/4468389/fwd_declarations.zip)
[output_dir.zip](https://github.com/doxygen/doxygen/files/4468392/output_dir.zip)

The ini file is inside fwd_declarations.zip

Thanks

**Comment by albert-github** [comment]
Which version of doxygen did you use (the configuration file suggests 1.8.16, the output suggests (an older version of) the master).
Please show the output of `doxygen -x`

**Comment by albert-github** [comment]
With the current master version of doxyen: 1.8.18 (184ea443799cd27a1e3cd3989c03c183297df890) I see the problem as well in HTML.
The template class refers to line 7 (the place of the forward declaration; the implementation is at line 47)
The non-template class refers to line 38 (the place of the implementation; the forward declaration is at line 5).

**Comment by erez-o** [comment]
Thanks, sorry, forgot to mention doxygen version.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.19.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
