### ISSUE TITLE
Doxygen refuses to generate documentation for a class

### ISSUE THREAD

**Issue by lfcarreon1** [doxygen/doxygen#7710]
Attached is a ZIP file containing two C++ include files with doxygen markup. When I use a default Doxygen configuration file which includes the two files, doxygen refuses to generate the documentation of the class defined in one of the files.  A module documentation is generated alright but no class and member function documentation.  According to the doxygen FAQ, it should be documenting the class and member functions with the existing markup.  Can someone please explain why?
[config.zip](https://github.com/doxygen/doxygen/files/4498287/config.zip)

**Comment by lfcarreon1** [comment]
BTW, I'm using Doxygen 1.8.15 from Fedora 31.

**Comment by albert-github** [comment]
With version 1.8.15 I see in the top blue part:
![top_1_8_15](https://user-images.githubusercontent.com/5223533/79684030-9188f580-822e-11ea-9df3-186e28561c54.jpg)

with version 1.8.16 and following i.e. 1.8.17 and the current version 1.8.18 I see:
![top_1_8_16](https://user-images.githubusercontent.com/5223533/79684038-a5ccf280-822e-11ea-9466-f569ba9ea2dd.jpg)


I think the problem has been solved in the mean time.
