### ISSUE TITLE
Parsing C++ string default arguments fails

### ISSUE THREAD

**Issue by paroj** [doxygen/doxygen#7714]
e.g.
```cpp
/** @addtogroup Test
*  @{
*/

/**
@param str
@param delims
@param maxSplits
*/
void tokenise(const char* str, const char* delims = "\"", int maxSplits = 0);

/**
@param buf
@param maxCount
@param delim
*/
void readLine(char* buf, int maxCount, const char* delim = "\n");

/** @} */
```
->
```
test.cpp:5: warning: argument 'delims' of command @param is not found in the argument list of tokenise(const char *str)
test.cpp:5: warning: argument 'maxSplits' of command @param is not found in the argument list of tokenise(const char *str)
test.cpp:12: warning: argument 'delim' of command @param is not found in the argument list of readLine(char *buf, int maxCount)
```
and neither shows up in the HTML docs.

**Comment by doxygen** [comment]
I failed to reproduce this with the information given. Could you please attach a complete example (source+config file in a tar or zip) and mention the version of doxygen you are using?

**Comment by paroj** [comment]
sorry, I copied out the wrong escape char (was `\n` now is `\"`). Updated the sample accordingly.

I generate the config as `doxyfile -g` and set the snippet as `INPUT = test.cpp`. 

```
$ doxygen -v
1.8.13
```

**Comment by albert-github** [comment]
With version 1.8.13 I see the warnings as indicated and when looking at the output:

![res_1_8_13](https://user-images.githubusercontent.com/5223533/79849737-2d4b6a80-83c3-11ea-8ef5-6738a5090cbf.jpg)

We see that under "Functions" the initial values are a bit mangled, and that with the "Function Documentation" some arguments are missing.

When running version 1.8.18 we see no warnings and the result is:

![res_1_8_18](https://user-images.githubusercontent.com/5223533/79849864-5835be80-83c3-11ea-9820-73bda8dfd9cb.jpg)

where also the parts under "Functions" and "Function Doxumentation" look OK.

I think the problem has been solved in the mean time (probably as of version 1.8.15).
