### ISSUE TITLE
INLINE_SOURCES and LATEX_HEADER

### ISSUE THREAD

**Issue by dbpodrasky** [doxygen/doxygen#7717]
When supplying a latex header file and setting INLINE_SOURCES = YES refman.tex fails to compile with undefined control sequence errors. This workflow was fine in previous versions; currently using 1.8.17. May be related to \+?

**Comment by albert-github** [comment]
It is hard to tell what is wrong, but most likely you have to update your `LATEX_HEADER` from your old version (which version?) to a headrr suitable for 1.8.17 (quite a bit has been changed, e.g. in 1.8.16 updates were done so the tabu package, for tables, can still be used).

- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.
- Please also specify the old doxygen version used that worked.
- Which command did you use to generate the pdf (should be a `make` in the latex directory).

**Comment by dbpodrasky** [comment]
Perfect! This worked. Doxygen 1.8.14 was used to generate the original header, so probably a lot has happened between then and 1.8.17! Generating a new header.tex file using:

doxygen -w latex header.tex footer.tex style.sty

created a new, generic header.tex file that is now working with the INLINE_SOURCES = YES tag.

Thanks for the quick response!

**Comment by albert-github** [comment]
Note: the current version of doxygen is 1.8.18, but no changes in the LaTeX header / footer .

**Comment by dbpodrasky** [comment]
It seems that 1.8.18 is not on macports yet.

**Comment by albert-github** [comment]
That is very well possible, the version is only 10 days old.
