### ISSUE TITLE
Error when building with cmake: Could NOT find FLEX

### ISSUE THREAD

**Issue by EVARATE** [doxygen/doxygen#7720]
I tried installing doxygen as described [here](http://www.doxygen.nl/download.html). When executing the ```cmake -G "Unix Makefiles" ..``` command, this is the console output with the error message:

```
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.17") 
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find FLEX (missing: FLEX_EXECUTABLE)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindFLEX.cmake:217 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:98 (find_package)


-- Configuring incomplete, errors occurred!
See also "/media/mo/Applications/doxygen/build/CMakeFiles/CMakeOutput.log".
```
Here is the logfile:
[CMakeOutput.log](https://github.com/doxygen/doxygen/files/4518571/CMakeOutput.log)

**Comment by albert-github** [comment]
`flex` is essential  for the make process of doxygen, see the doxygen manual: http://doxygen.nl/manual/install.html#install_src_unix where it is mentioned (a.o.):
> The GNU tools flex, bison, libiconv and GNU make, and strip


Do you have `flex` installed?

**Comment by sahin52** [comment]
You are either trying to install on Windows like this, which you shouldn't, because this is for Linux, or you don't have Flex installed:
```
sudo apt-get update
sudo apt-get install flex
```

**Comment by albert-github** [comment]
Seen the time between the original message and now I think we can say that OP has solved the issue.
I think the problem will have been that flex was not installed.

Setting the issue to usage.
