### ISSUE TITLE
Commented out comment still read

### ISSUE THREAD

**Issue by Reissner** [doxygen/doxygen#7723]
I have commented out some code like that 
```
// /**
//  * Nur für Betrieb ohne Programm: schaltet Leistung von Poti durch #ain1 
//  * und schaltet LED ein. 
//  */
// DigitalIn   IO_LED_On(p22);
```
still obtaining an error as the link `#ai1` cannot be satisfied. 
I think, the blank in the first line is swallowed and so all that is interpreted as valid documentation. 

I would expect only `///` without intermediate blanks to be interpreted as api docs.

**Comment by albert-github** [comment]
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.
- Please also specify the doxygen version used.

**Comment by albert-github** [comment]
Tried to reproduce the problem based on the available information, but was not able to.

Setting issue to incomplete / invalid.
