### ISSUE TITLE
Doxygen thinks a page is a sub-page of itself

### ISSUE THREAD

**Issue by mbasaglia** [doxygen/doxygen#7724]
On newer versions of doxygen I get this error:

```
error: page defined at line 2 of file (filename).dox with label (page label) is a direct subpage of itself! Please remove this cyclic dependency.
```

But the page isn't a sub-page of itself.

The issue doesn't occur on version 1.8.13 but it does show up in version 1.8.17

This is a minimal example that triggers it, the bug seems sensitive to white space:
```
/**
    \page parent Parent

\subpage child

\page child Child

Hello...

*/
```

**Comment by albert-github** [comment]
As you wrote "This is a minimal example that triggers it, the bug seems sensitive to white space" is a good idea to attach a file showing the problem as during copy and paste the spacing might get lost.
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.

**Comment by albert-github** [comment]
The handling of markdown pages has changed between version 1.8.13 and the current version considerably.
In markdown, saying it in a short way, a line starting with at least 4 spaces is shown as a code line, in this case we see the line:
```
    \page parent Parent
```
and this line starts with 4 spaces, so it is seen as a code line.

So this is in my opinion usage of markdown.

**Comment by mbasaglia** [comment]
to reproduce I was able to just use `doxygen -g` and have the contents as from my first message in a dox file, anyway here's a tarball: [doxytest.tar.gz](https://github.com/doxygen/doxygen/files/4530138/doxytest.tar.gz)

**Comment by mbasaglia** [comment]
> In markdown, saying it in a short way, a line starting with at least 4 spaces is shown as a code line

does that apply to code comments too? 

```c++
class foo {
    /**
       Is this code?
    */
    void bar();
}
```

**Comment by albert-github** [comment]
It all depends where the comments are, in the mentioned case it wouldn't be as an easy test shows.
