### ISSUE TITLE
warning "return type of member echart_serie_free is not documented" if macro is before void

### ISSUE THREAD

**Issue by vtorri** [doxygen/doxygen#7729]
doxygen 1.8.17 or 1.8.18 : 

C:/Documents/msys2/home/vincent.torri/gitroot_64/echart/src/lib/echart_data.h:142: warning: return type of member echart_serie_value_push is not documented

with, the following declaration : 

EAPI void echart_serie_value_push(Echart_Serie *s, double y);

EAPI is a macro set to, for example, __declspec(dllexport) on Windows (or other value for suncc or gcc on unix)

i have this warning only with all the functions which return no value (only with "EAPI void")

is there something that I should do in Doxyfile ?

**Comment by albert-github** [comment]
I tried to reproduce the problem, but didn't succeed, so some information might be missing.
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.

Please also read-up on the preprocessing (http://doxygen.nl/manual/preprocessing.html) here also something is written about `__declspec(dllexport)`.

**Comment by vtorri** [comment]
this preprocessing documentation has indeed helped solving the issue

thank you
