### ISSUE TITLE
Warning: multiple use of section label 'md_README'

### ISSUE THREAD

**Issue by kingfisher63** [doxygen/doxygen#7731]
I have a project (let's call it project1) that uses the README.md file as the main page and generates a tags file:

    INPUT                  = . README.md
    USE_MDFILE_AS_MAINPAGE = README.md
    GENERATE_TAGFILE       = project1.tags

Starting with version 1.8.18 Doxygen automatically generates an anchor for the main page and records this in the tags file (docanchor):

    <compound kind="page">
      <name>index</name>
      <title>project1</title>
      <filename>index.html</filename>
      <docanchor file="index.html">md_README</docanchor>
    </compound>

I have another project (let's call it project2) that uses the same pattern and references the tags file from project1:

    INPUT                  = . README.md
    USE_MDFILE_AS_MAINPAGE = README.md
    TAGFILES               = project1.tags=../project1/docs
    GENERATE_TAGFILE       = project2.tags

Now Doxygen emits a warning when building the documentation for project2:

*warning: multiple use of section label 'md_README' while adding anchor, (first occurrence: index.html)*

Making the auto generated anchor unique in some way should prevent this (for example by including the project name).

This seems to be a side effect of #7511.

**Comment by albert-github** [comment]
I tested with the 1.8.19 version and here we get the warning, as indicated:
```
README.md:2: warning: multiple use of section label 'md_README' while adding anchor, (first occurrence: index.html)
```

with version 1.9.2 this message is gone.

I think the problem has been solved in the mean time.

**Comment by kingfisher63** [comment]
Confirmed. This issue can be closed. Thank you for solving this!
