### ISSUE TITLE
why is happen??

### ISSUE THREAD

**Issue by mey1k** [doxygen/doxygen#7737]
Patching output file 47/93
Patching output file 48/93
error: Failed to rename file D:/AOI/aoi/doc/Doxygen/latex/class_common_1_1_algo.tex to D:/AOI/aoi/doc/Doxygen/latex/class_common_1_1_algo.tex.tmp!
lookup cache used 1186/65536 hits=9484 misses=1334
finished...
*** Doxygen has finished

**Comment by doxygen** [comment]
Hard to tell what is going on by just looking at this output. Most likely the .tex file wasn't written, so it cannot be renamed. If it is not a "disk full" issue then please attach a self contained example (source+config file in zip) so that we can reproduce the problem.
