### ISSUE TITLE
Three-way comparison operator

### ISSUE THREAD

**Issue by lfcarreon1** [doxygen/doxygen#7747]
When doxygen encounters "operator<=>", it leaves out the "<=>" in the generated documentation.

I expect the generated documentation to show "operator<=>".

I'm currently using Doxygen 1.8.17 included with Fedora 32.

**Comment by albert-github** [comment]
Unfortunately not enough information,missing a small example (as the template also requested also), so
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.

As reference:
> **Describe the bug**
> Describe what you see that (you think) is wrong.
> 
> **Expected behavior**
> Describe what you would have expected or think is correct.
> 
> **Screenshots**
> If useful, add screenshots to help explain your problem.
> 
> **To Reproduce**
> Attach a self contained example that allows us to reproduce the problem.
> Such an example typically exist of some source code (can be dummy code) and a doxygen configuration file used (you can strip it using `doxygen -s -u`). After you verified the example demonstrates the problem, put it in a zip (or tarball) and attach it to the bug report. Try to avoid linking to external sources, since they might disappear in the future.
> 
> **Version**
> Mention the version of doxygen used (output of `doxygen --version`) and the platform on which you run doxygen (e.g. Windows 10, 64 bit). If you run doxygen under Linux please also mention the name and version of the distribution used (output of `lsb_release -a`) and mention if you compiled doxygen yourself or that you use a binary that comes with the distribution or from the doxygen website.  
> 
> **Stack trace**
> If you encounter a crash and can build doxygen from sources yourself with debug info (`-DCMAKE_BUILD_TYPE=Debug`), a stack trace can be very helpful (especially if it is not possible to capture the problem in a small example that can be shared).
> 
> **Additional context**
> Add any other context about the problem here.
>

**Comment by albert-github** [comment]
Based on a, limited, search in the Internet, I see that this is a new feature for the C++20 standard and called Three way operator or spaceship operator.

I created a small, limited, non normative, and possibly incorrect example: [example.tar.gz](https://github.com/doxygen/doxygen/files/4574316/example.tar.gz)

A better / larger example is appreciated!

**Comment by albert-github** [comment]
Based on the limited available information as indicated in my previous comment, I've just pushed a proposed patch, pull request #7748

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.19.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
