### ISSUE TITLE
A warning while running Doxygen

### ISSUE THREAD

**Issue by KITTUKRISHNA5** [doxygen/doxygen#7749]
pdfTeX warning (dest): name{mcs__tparamadapt_8h_source_l00054} has been referen
ced but does not exist, replaced by a fixed one

could you explain the reason why

**Comment by albert-github** [comment]
Even when you cannot provide your source code, the current information if by far insufficient what could be wrong. Please follow the template and provide a simple example showing the problem!

**Comment by albert-github** [comment]
Unfortunately no further information, setting the issue to incomplete.
