### ISSUE TITLE
SVG formula all with zero width

### ISSUE THREAD

**Issue by matpack** [doxygen/doxygen#7753]
We recently switched to v1.8.18 on kubuntu 20.04.
We select HTML_FORMULA_FORMAT = svg with FORMULA_TRANSPARENT = YES and generate  a HTML documentation for a large project. For the first generation of the docu the result is perfect. However, when rebuilding the documentation, after some textual changes, *all* formula disappear in the browser. We could track down the issue by inspecting the html sources. Here is a snippet from one of the html files:

1st build: 
[...] 
&lt;img class="formulaDsp" alt="\[ B_a(z) = \dfrac{z-a}{\overline{a}z-1} \]" src="form_18.svg" width="102" height="29"/&gt;
[...]

2nd build:
[..]
&lt;img class="formulaDsp" alt="\[ B_a(z) = \dfrac{z-a}{\overline{a}z-1} \]" src="form_18.svg" width="0" height="29"/&gt;
[...]

The width attribute is set to zero. This happens for all 5000+ formula in our documentation. The bug is repeatable: After *all* generated output is cleared and a new build is done, all formula are back again. Then re-building the docu a second time generates all html files with 0-width SVGs.

When using the PNG formula format there is no bug. However here we have the issue, that transparency does't work anymore for PNG formula in v1.8.18  (which is a second bug).

Perhaps this is related to the wrong console message 
   "Generating image form_189.png for formula"
printed also when SVG formula are generated (bug # three).

**Comment by albert-github** [comment]
I saw the problem with the png format as well.

Despite the excellent pointing to the problematic result, it would also have been nice to have had a small, self contained example (source+configuration file in a tar or zip) that would have allowed us to reproduce the problem. (I added a small example with the proposed pull request #7754).

Did you also consider to use MathJax to render formulas for HTML (`USE_MATHJAX=YES` and at least, in your case, `MATHJAX_EXTENSIONS     = TeX/AMSmath TeX/AMSsymbols`) ?

I've just pushed a proposed patch, pull request #7754

**Comment by albert-github** [comment]
In respect to the second and third bug you mentioned can create small, self contained examples (source+configuration file in a tar or zip) that allows us to reproduce the problem? (maybe for the third bug also with the complete console output you see). Best is to create separate issues for this.

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by matpack** [comment]
Thank you for the fast fix - works perfectly. Answering your question: MathJax is no option, because it does not support advanced Latex features, e.g. tikz and algorithm2e packages, as indicated by our current package definition: 
EXTRA_PACKAGES = {multirow} {amsmath} {amssymb}\let\mathcup\cup {musixtex} [algoruled]{algorithm2e} {tikz}\usetikzlibrary{calc}\usetikzlibrary{matrix}\usetikzlibrary{quotes}\usetikzlibrary{angles}\usetikzlibrary{decorations.fractals}

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.19.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
