### ISSUE TITLE
Certificate error when accessing website with HTTPS

### ISSUE THREAD

**Issue by jacklovell** [doxygen/doxygen#7755]
**Describe the bug**
When visiting https://www.doxygen.org I am presented with an SSL certificate error, `SSL_ERROR_BAD_CERT_DOMAIN`.

**Expected behavior**
The doxygen website should display, the same as when connecting via HTTP.

**Screenshots**
![doxygen-certificate-error](https://user-images.githubusercontent.com/4849151/81170555-ccab5880-8f92-11ea-9205-a3a093f43f0e.png)

**To Reproduce**
Visit any of the doxygen web domains using HTTPS rather than HTTP.

**Version**
Website accessed 2020-05-06 12:00 BST.

**Stack trace**
N/A

**Additional context**
Firefox 76 introduced an HTTPS-only option, and in future will likely block HTTP-only sites by default. This will break access to the doxygen website for many users.

**Comment by lrineau** [comment]
The issue with that certificate is that its CN (Common Name) is: `da01.webxtra.net`, and the only Alt Names is `www.da01.webxtra.net`. It should be `doxygen.org` and `www.doxygen.org`.

**Comment by jacklovell** [comment]
`doxygen.nl` and `www.doxygen.nl` should also be added as Alt Names, as these domains seem to share the same certificate.

**Comment by doxygen** [comment]
Indeed, I checked with my ISP and found a way to correct this.
