### ISSUE TITLE
How to add whole html.files folder into HTML_EXTRA_FILES?  

### ISSUE THREAD

**Issue by yuanshifeng** [doxygen/doxygen#7757]
**Describe the bug**
I can't find a method to add a folder to output for html files.

**Expected behavior**
Is there any method can add a whole folder into output for html ext files use?

**Screenshots**
If useful, add screenshots to help explain your problem.

**To Reproduce**
Attach a self contained example that allows us to reproduce the problem.
Such an example typically exist of some source code (can be dummy code) and a doxygen configuration file used (you can strip it using `doxygen -s -u`). After you verified the example demonstrates the problem, put it in a zip (or tarball) and attach it to the bug report. Try to avoid linking to external sources, since they might disappear in the future.

**Version**
Mention the version of doxygen used (output of `doxygen --version`) and the platform on which you run doxygen (e.g. Windows 10, 64 bit). If you run doxygen under Linux please also mention the name and version of the distribution used (output of `lsb_release -a`) and mention if you compiled doxygen yourself or that you use a binary that comes with the distribution or from the doxygen website.  

**Stack trace**
If you encounter a crash and can build doxygen from sources yourself with debug info (`-DCMAKE_BUILD_TYPE=Debug`), a stack trace can be very helpful (especially if it is not possible to capture the problem in a small example that can be shared).

**Additional context**

**Comment by albert-github** [comment]
It is a bit unclear what you want to do, please provide the information as requested in the template for:
**Screenshots**
**To Reproduce**
**Version**
**Additional context**

You can add files to the base folder of the `HTML_OUTPUT` by means of `HTML_EXTRA_FILES` it is not possible to add the content of a complete directory or place it in a sub directory. For the later you need some commands outside of doxygen.

**Comment by yuanshifeng** [comment]
To Reproduce

**Comment by albert-github** [comment]
It is meant that you give a better description and example of what you want to do.

**Comment by yuanshifeng** [comment]
I want to generate a .chm by doxygen. 
There is a xxx.html file that is added into EXAMPLE_PATH.
But the xxx.html file is exported from Word, so it has a relate xxx.files folder that contains image files which is used in xxx.html.(such as /xxx.files/image001.png). 
The question is that I only can add image001.png to the output, but no /xxx.files/ path. So the xxx.html can't show the image.
How can I let the xxx.html find /xxx.files/image001.png in .chm?

**Comment by albert-github** [comment]
Isn't the underlying problem here the same problem as given in #7758 only that here you explicitly state that you want to include a complete directory through `HTML_EXTRA_FILES`. The later is at the moment not possible.
