### ISSUE TITLE
[Question] Some comments on python . 

### ISSUE THREAD

**Issue by 625781186** [doxygen/doxygen#7759]
## 1. 
`@property` as a member variable rather than a function.
Can it be done now?

![image](https://user-images.githubusercontent.com/30521429/81253620-91289100-905b-11ea-9cf9-6600e4e6be56.png)

## 2. 
I want `_` to generate `protect` and `__` to generate `private` , 

But now `_` also generate `private`  .

Is there any way to do that ?

![image](https://user-images.githubusercontent.com/30521429/81253687-b0272300-905b-11ea-9129-b58c6764f058.png)

## 3. 
How to Ignore some comments : 

### 3.1
I have some code like this for the IDE to fold, but now that it's recognized as an instruction, how do I ignore it?

![image](https://user-images.githubusercontent.com/30521429/81253776-f2e8fb00-905b-11ea-9a53-5965ef300e1f.png)

![image](https://user-images.githubusercontent.com/30521429/81253782-f7151880-905b-11ea-840f-7d6a9d069657.png)

### 3.2. The same, 

![image](https://user-images.githubusercontent.com/30521429/81253910-465b4900-905c-11ea-9eee-3859a3ae8f83.png)

![image](https://user-images.githubusercontent.com/30521429/81253932-54a96500-905c-11ea-8bde-90bc9adc176a.png)

## 4 . 
This comment generates `two arrows`. 

Are these details mentioned anywhere in the document?

I can't seem to find them. 

Can you tell me where it is? Thanks!

![image](https://user-images.githubusercontent.com/30521429/81253866-2b88d480-905c-11ea-9d2d-cb2fb874789d.png)

**Comment by albert-github** [comment]
1. @property as a member variable rather than a function.
    Please show an example where this goes wrong:
    - attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.
    - Please also specify the doxygen version used.
2. I want _ to generate protect and __ to generate private
   Python has no knowledge about private it is a loose ad-hoc rule (followed by a number of people), so it is hard for doxygen to follow this rule. Doxygen has commands like `private` probably this wil bring something.
3. `##` is handled as (continuation) comment in doxygen, so here is not realy anything that can be done, only thing might be might be
    - instruct the IDE to use a single `#`
    - use a `FILTER_PATTERNS` in doxygen that can filter out these lines
4. This comment generates `two arrows`.
    This looks indeed a bit strange, please show an example where this goes wrong:
    - attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.
    - Please also specify the doxygen version used.

**Comment by 625781186** [comment]
@albert-github 
### About 1 : 
I may not have described it clearly enough .
I hope when python use decorator `@property` above function  , don't generate  it to function.

![image](https://user-images.githubusercontent.com/30521429/81285313-ebdcdf80-9091-11ea-9aa2-a0d52092698a.png)


### About 2 :
I think it's best to add a configuration option to implement it.
Actually, `_` in python class can be subclassed and rewritten, but `__` can't, 
so it's confusing to classify them as private. Do you think?

### About 4  (resolved): 
I know what happend : 
![image](https://user-images.githubusercontent.com/30521429/81284217-686ebe80-9090-11ea-9d91-e3a362088ab8.png)

I have two arrows in my comment so that this happens.

![image](https://user-images.githubusercontent.com/30521429/81284238-6efd3600-9090-11ea-9ac8-38659d96fea8.png)

**Comment by albert-github** [comment]
- 1. Still an example would be useful (not just an image, but a small example showing the problem) also a reference to a PEP might be useful.
- 2. Probably best to white an enhancement request for it.
- 4. So usage.

**Comment by 625781186** [comment]
@albert-github 
This is demo . https://github.com/625781186/doxy_py_discuss/archive/01.zip

## About 2 : 
    Probably best to white an enhancement request for it.

`white` mean `Create a separate enhancement request or `cancel this request` ?

**Comment by albert-github** [comment]
- Sorry about the typo: white should have been write.
- Regarding the attachment better to have it as part of the issue and not on your account (when this would disappear probably also the zip file would disappear and we cannot access it anymore), I already added it as part of the issue.
- the issue with `@property` is about decorators and they are currently not supported in doxygen for python.
