### ISSUE TITLE
Q_INVOKABLE void return type reported as not documented

### ISSUE THREAD

**Issue by spdw** [doxygen/doxygen#7760]
In issue #7411 a fix was applied that solved many of our undocumented warnings. For our Qt specific function signatures it still does not work as expected.

Based on my comment https://github.com/doxygen/doxygen/issues/7411#issuecomment-625118481 and the response from @albert-github I have created this ticket.

When activating
```
WARN_NO_PARAMDOC       = yes
```
in the Doxyfile, the following code
```
#include <QWidget>
/**
 * @brief Test class.
 */
class Window : public QWidget
{
    Q_OBJECT
public:
    /**
     * @brief Function is documented.
     */
    Q_INVOKABLE void invokableMethod();
};
```
leads to the warning
```
test.h:12: warning: return type of member Window::invokableMethod is not documented
```
When using the workaround with doxygen predefined macro
```
MACRO_EXPANSION = YES
PREDEFINED = Q_INVOKABLE =
```
the warning is gone but also `Q_INVOKABLE` is removed from the documentation.

Please add support to have the `Q_INVOKABLE` in the documentation in combination with the Doxygen configuration WARN_NO_PARAMDOC.

In https://github.com/doxygen/doxygen/blob/master/src/memberdef.cpp#L4074 I assume
```
bool isVoidReturn = returnType=="void";
```
could be changed to
```
bool isVoidReturn = (returnType=="void") || (returnType.right(5)==" void");
```
to match the signature of "Q_INVOKABLE void". This would not match for return types like `void *fie(void)` which has a closing round bracket at the end of the return type string.

**Comment by albert-github** [comment]
I do remember that it was quite difficult to get this "right", but there are apparently still exceptions.

I think the suggested fix is OK:
```
bool isVoidReturn = (returnType=="void") || (returnType.right(5)==" void");
```
the first test gets the bare `void` and the second test all other `void` functions though ignoring ignoring `void *` and e.g. `..._void`

Furthermore the line:
```
QCString returnType = removeReturnTypeKeywords(typeString());
```
can be replaced with
```
QCString returnType = typeString();
```
as the `volatile void` etc. are also correctly caught by the ` void` and thus the function
```
static QCString removeReturnTypeKeywords(const QCString &s)
```
can be removed.

@doxygen did I overlook a corner case?

**Comment by yo-jim** [comment]
In 1.8.18, it is also still reporting java 'synchronized void' as undocumented.

**Comment by doxygen** [comment]
> @doxygen did I overlook a corner case?

I can't think of one and indeed then also `removeReturnTypeKeywords` can be removed. 
Other complex cases where void is part of a non-void return type, like

    std::function< void() > foo()

would also continue to be handled correctly.
