### ISSUE TITLE
Square brackets inside backticks cause unexpected side effects

### ISSUE THREAD

**Issue by Krinkle** [doxygen/doxygen#7763]
**Describe the bug**
When mentioning something like `$foo['bar']` in a doc comment, it is preferred to render that as code (as I did here), both for styling/readability, but also to avoid other unintended side-effects such as automatic linking of the variable name, other interpration of would-be Markdown syntax.

The problem is that it seems Doxygen's Markdown parser is currently ignoring any sequences of text between backticks if there are square brackets within them, and these backticks are then wrongly processed in relation to the next sequence. Thus rendering as "code" all regular prose between two pieces of actual code.

**Expected behavior**
For, this:

```
Remember to set `$wgProfiler['outputDir']` as well.
```

To render as:
> Remember to set `$wgProfiler['outputDir']` as well.

**To Reproduce**

```
 *   - with the XHProf gui. It expects that `wgProfileroutputDir` is
 *   - with the XHProf gui. It expects that `wgProfiler'outputDir'` is.
 *   - with the XHProf gui. It expects that `wgProfiler['outputDir']` is
 *   - with the XHProf gui. It expects that `$wgProfiler['outputDir']` is
```

**Version**
* Doxygen 1.8.18, as installed via the binary download for Linux (`doxygen-1.8.18.linux.bin.tar.gz`)
* Debian Linux 10 (buster).

**Screenshots**

I tried both 1.8.13 (as provided via [Debian Buster's distribution](https://packages.debian.org/buster/doxygen)), and the latest binary.

| Doxygen 1.8.13
|--
| <img width="743" alt="capture-issue" src="https://user-images.githubusercontent.com/156867/81335522-a7584080-909f-11ea-9cce-589c891fa2ad.png">

The first two work as expected. The last two fail. Specificallym, the text tween the 3rd and 4th variable is wrongly rendered as if it was code, and the opening backtick on line three, and closing backtick on line 4 are left as-is.

| Doxygen 1.8.18
|--
| <img width="1093" alt="capture-issue-dot18" src="https://user-images.githubusercontent.com/156867/81337986-ca84ef00-90a3-11ea-8565-f69ab5a657db.png">

In the latest it seems to have also started to ignore quotes within backticks. The second line is now also left as-is, with the text between multiple lines wrongly rendering as code.

**Comment by albert-github** [comment]
Would have been nice when the code had been available as a compressed tar / zip as well like: [example.tar.gz](https://github.com/doxygen/doxygen/files/4598072/example.tar.gz)

It is always interesting to look at the results of `doxygen -d markdown`, here we see (1.8.18 version):
```
   - with the XHProf gui. It expects that <tt>wgProfileroutputDir</tt> is
   - with the XHProf gui. It expects that &lsquo;wgProfiler'outputDir&rsquo;<tt>is.
   - with the XHProf gui. It expects that</tt>wgProfiler['outputDir']<tt>is
   - with the XHProf gui. It expects that</tt>$wgProfiler['outputDir']` is
```
Where the combination of backtick `` ` `` followed by text followed by single quote `'` is seen as a quotation (in some languages this is the usual way of creating quotes, in other other conventions are used).

The solution I see at the moment is to use `*apos;` instead of `` ` ``:
```
 *   - with the XHProf gui. It expects that `wgProfileroutputDir` is
 *   - with the XHProf gui. It expects that `wgProfiler&apos;outputDir&apos;` is.
 *   - with the XHProf gui. It expects that `wgProfiler[&apos;outputDir&apos;]` is
 *   - with the XHProf gui. It expects that `$wgProfiler[&apos;outputDir&apos;]` is
```

**Comment by Krinkle** [comment]
@albert-github Which information would you like me to provide?

**Comment by albert-github** [comment]
- Normally something like what I posted in example.tar.gz would be good (easier to see what really is going on).

**Comment by Krinkle** [comment]
Right, yeah, I understood that :) Thanks for making this one.
