### ISSUE TITLE
error when use make and make install commands line

### ISSUE THREAD

**Issue by Azaretdodo** [doxygen/doxygen#7767]
Hello,

error when use make and make install commands line : 

![HereMyErrorAboutMakeCommandLineAndMakeInstallCommandLine](https://user-images.githubusercontent.com/30596513/81493215-f1f3db80-929e-11ea-97a3-8e3db762f528.jpg)

Thank you in advance to repair the problems,

Regards.

Azaretdodo.

**Comment by albert-github** [comment]
- **Version** ?
  Mention the version of doxygen used (output of `doxygen --version`) and the platform on which you run doxygen (e.g. Windows 10, 64 bit). If you run doxygen under Linux please also mention the name and version of the distribution used (output of `lsb_release -a`) and mention if you compiled doxygen yourself or that you use a binary that comes with the distribution or from the doxygen website.  
- which commands did you issue?
- what is the reason / why `make` stopped with `Error 2` after building `libqtools.a`?
- what happens when you don't use `-j 6`, as with `-j ..` the output might be a be deceptive.

**Comment by Azaretdodo** [comment]
I Don't know the doxygen version too the lsb release command line fail but I know the system It is a fedora 31 server 64 byte (bsd system free) !

For the make error that look feel be a permission error on a python scripts maybe :

![WhereItIsAndDoxygenVersionAndShowAboutTheLinuxVersionBroken](https://user-images.githubusercontent.com/30596513/81496776-66884380-92ba-11ea-963e-dad0591b0fec.jpg)

![DoxygenMakeError](https://user-images.githubusercontent.com/30596513/81496779-6a1bca80-92ba-11ea-8ea4-e934bf0edd43.jpg)

Thank you in advance to repair my problems,

Regards.


Azaretdodo.

**Comment by Azaretdodo** [comment]
sorry I have forgot this line !

![IFOrgotThisLineByPrintscreen](https://user-images.githubusercontent.com/30596513/81496833-e0203180-92ba-11ea-9dee-6e8c38197c1f.jpg)

Thank you in advance to bring your help,

Regards.


Azaretdodo.

**Comment by albert-github** [comment]
- Looks you already have half a build, so best is to restart from scratch:
  - rm -rf build
  - mkdir build
  - cd build
  - cmake ..
  - make

  please sow **all** output of the command window and don't use images but place it in a file and attach the file to the comment (is much easier to read and interpret).
- regarding the version, you must have gotten the doxygen source code from some place where also the version should have been mentioned (from where did you retrieve the source code?), but in the doxygen root directory there should be a file `VERSION` that can give you some information as well.

**Comment by Azaretdodo** [comment]
The version is 1.8.19,

I have remove the build directory but It look happening the same error : 

![SameError](https://user-images.githubusercontent.com/30596513/81497450-dc8ea980-92be-11ea-9917-58aab5385dbe.jpg)

The github is here :

/home/dorianrosse/Vulkan-Hpp/glfw/doxygen/

The Vulkan Hpp github hasn't bring glfw and doxygen I have added by myself,

Thank you in advance for all your help,

Regards.


Azaretdodo.

**Comment by albert-github** [comment]
Before I wrote (with small typo):
> please show **all** output of the command window and don't use images but place it in a file and attach the file to the comment (is much easier to read and interpret).

I think that `Vulkan Hpp` and `glfw` are in this stage irrelevant. 
- From where did you get `doxygen`?
- How did you place `doxygen` on your machine?
- when in the doxygen root directory what is the result of `ls -ls src/scan_states.py` ?

**Comment by Azaretdodo** [comment]
sorry but on my linux system I can't copy paste !

I can paste to the system Truth but I can't copy from the cli for paste anywhere !

also 'ls -ls scan_states' give this answer :

![LScommandlineSCanStatesPythonScripts](https://user-images.githubusercontent.com/30596513/81502521-be38a600-92de-11ea-9a31-c8ba01410bc1.jpg)

Sorry for my copy paste unable,

Thank you in advance for your help,

Regards.


Azaretdodo.

**Comment by Azaretdodo** [comment]
I have got doxygen from your github where we talk,

I have used git clone command line with your github link,

Thank you in advance for your help,

Regards.


Azaretdodo.

Envoyé d’Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by albert-github** [comment]
Even on Linux one can normally cut and paste, furthermore one can redirect the output to a file and use this file to attach it to the comment (see also the bar at the bottom of each comment).

The `ls` and retrieval procedure looks OK, so the only thing you can do is follow the request I made in the comment https://github.com/doxygen/doxygen/issues/7767#issuecomment-626307433 redirect the output to a file (stdout and stderr!) and attach the file to the comment.

**Comment by Azaretdodo** [comment]
I have ever tried usb mode but I think I can't use USB mode again I will tried when I will have the time,

I think I will use the typing mode because USB mode is broken!

Why do you need the output?

You can't do from printscreen?

I hope success,

Regards.


Azaretdodo.
Envoyé d’Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by albert-github** [comment]
Why use a file and not an image, well an image:
- is not searchable
- only contains the part that is on the screen and not the full output
- image is less good readable
- ...

I don't know what an USB mode has to do with cut and past / this problem.
When cut and past is not possible in a terminal window you probably need to set the right options of the terminal window.

Below a screenshot from Cygwin (not directly your Linux, but proably gives an idea), after clicking the icon in the top left of the terminal window I got a pop-up and selected from it options and got:

![opt](https://user-images.githubusercontent.com/5223533/81504877-0ca07180-92ec-11ea-8e9b-dfbecc3ec92c.jpg)

**Comment by Azaretdodo** [comment]
I use a navigator I don't use ssh access I was tried to set up a ssh access finaly I have ever success on Ubuntu the ssh access but on my fedora system I have yet success the ssh access,

Don't worry I will type errors by typing on my keyboard,

See you more later on this disscuss my cat is on my legs,

Regards.


Azaretdodo.

Envoyé d’Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by Azaretdodo** [comment]
Hello I am back !

I copy past by typing by the hand :

'''cmake ..
-- The javacc executable not found, using existing files
-- Configuring done
-- Generating done
-- Buld files have been written to: /home/dorianrosse/Vulkan-Hpp/glfw/doxygen/build
make
[ 1%]Built target md5
[2%] Built target lodepng
[2%]Generating ../generated_src/mscgen_lexer.l.h
/bin/sh: ../../src/scna_states.py: Permission denied
make[2]: *** [libmscgen/CMakesFiles/mscgen.dir/build.make:94:: generated_src/mscgen_lexer.l.h] Error 126
make[2]: *** Suppresion du fichier << generated_src/mscgen_lexer.l.h >>
make[1]: *** [CMakesFiles/MakeFile2:440: libmscgen/CMakesFiles/mscgen.dir/all] Error 2
make install
[ 1%]Built target md5
[2%] Built target lodepng
[2%]Generating ../generated_src/mscgen_lexer.l.h
/bin/sh: ../../src/scna_states.py: Permission denied
make[2]: *** [libmscgen/CMakesFiles/mscgen.dir/build.make:94:: generated_src/mscgen_lexer.l.h] Error 126
make[2]: *** Suppresion du fichier << generated_src/mscgen_lexer.l.h >>
make[1]: *** [CMakesFiles/MakeFile2:440: libmscgen/CMakesFiles/mscgen.dir/all] Error 2'''

I have checked and the errors are the same between the make and the make install,

Thank you in advance to repair the problems,

Regards.


Azaretdodo.

**Comment by doxygen** [comment]
This is a strange line:
```
/bin/sh: ../../src/scna_states.py: Permission denied
```
If one looks at the CMakeLists.txt this command should be invoked with `python` in front of it... 

```
        COMMAND ${PYTHON_EXECUTABLE} ${CMAKE_SOURCE_DIR}/src/scan_states.py ${CMAKE_SOURCE_DIR}/src/${lex_file}.l > ${GENERATED_SRC}/${lex_file}.
```
So somehow `${PYTHON_EXECUTABLE}` is an empty string on this system.

**Comment by albert-github** [comment]
That line diwas in my attention as well, but to be able what went wrong we need a clean (!!) cmake build.
The type lines (with typo's):

> cmake ..
> -- The javacc executable not found, using existing files
> -- Configuring done
> -- Generating done
> -- Buld files have been written to: /home/dorianrosse/Vulkan-Hpp/glfw/doxygen/build

clearly indicates a previous `cmake` build. Please exactly follow the steps from https://github.com/doxygen/doxygen/issues/7767#issuecomment-626307433, the `rm` is essential:
-    rm -rf build
-    mkdir build
-    cd build
-    cmake ..
-    make

**Comment by Azaretdodo** [comment]
I have bad typed this is the file we are see the rights

This look like these scan_states.py

Envoyé d’Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by doxygen** [comment]
@Azaretdodo can you please do the tasks asked, otherwise you are just wasting our precious time.

**Comment by Azaretdodo** [comment]
I have ever remove the build directory for repeat command line and that happen same errors

I will repeat like you ask but I think the error went outside this problems,

Thank you in advance to keep on the problem,

Regards.


Azaretdodo.

Envoyé d’Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by doxygen** [comment]
I will close this issue then. If you can figure out how to do copy & paste and give us the information needed we can have a look.

**Comment by Azaretdodo** [comment]
Where do you see a problem?

Each person have right to do any errors

Now my mother is on the only personal laptop

I have too homework,

Thank you in advance to keep on the problem for repair the problem,

Regards.


Azaretdodo.

Envoyé d’Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by Azaretdodo** [comment]
Hello,


I copy paste by the hand I will do this slowly but I Don't know why you take myself as a noob because I copy paste maybe with error but you can feel copy paste by the hand is boring !

'''
make
Scanning dependencies of target md5
[1%] Building C object libmd5/CMakesFiles/md5.dir/md5.c.o
[1%] Linking C static Library ../lib/libmd5.a
[1%] Built target md5
Sanning dependencies of target lodepng
[2%] Building CXX object liblodepng/CMakesFiles/lodepng.dir/lodepng.cpp.o
[2%] Linking CXX static Library ../lib/liblodepng.a
[2%] Built target lodepng
[2%] Generating ../generated_src/mscgen_dexer.l.h
/bin/sh: ../../src/scan_states.py: Permission denied
make[2]: *** [libmscgen/CMakesFiles/mscgen.dir/build.make:94: generated_src/mscgen_lexer.l.h] Error 126
make[2]: *** SUppression du fichier << generated_src/mscgen_lexer.l.h >>
make[1]: *** [CMakesFiles/Makefile2:440: libmscgen/CMakesFiles/mscgen.dir/all] Error 2
make: *** [Makefile:183: all] Error 2
'''

I have read if I havn't type bad letter instead right letter !

Thank you in advance to help myself repair your program,

Regards.


Azaretdodo.
________________________________
De : Dimitri van Heesch <notifications@github.com>
Envoyé : lundi 11 mai 2020 14:37
À : doxygen/doxygen <doxygen@noreply.github.com>
Cc : Azaretdodo <dorianbrice@hotmail.fr>; Mention <mention@noreply.github.com>
Objet : Re: [doxygen/doxygen] error when use make and make install commands line (#7767)


I will close this issue then. If you can figure out how to do copy & paste and give us the information needed we can have a look.

**Comment by albert-github** [comment]
Well please follow the the recipe given from the **beginning** so including the results from `cmake`. Not just the `make` part and don't leave out parts, we don't ask for these results without reason and a lot of experience. We are willing to help but our time is scarce and valuable as well, so we need the, in our eyes, **right** and **essential** information to see what went wrong. So please give the output of these steps:
- rm -rf build
- mkdir build
- cd build
- cmake ..

an **not just** the output from the `make` step:
- make

The copy / paste by hand is not a nice job, but as you don't know how to copy / past it is essential.

**Comment by Azaretdodo** [comment]
I was remove build folder before use make command line Finaly because the build begin by no think,

Thank you in advance to repair the problem,

Regards.


Azaretdodo.

Envoyé d’Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by albert-github** [comment]
The removal of the build folder has to be done before the `cmake` and the `cmake ..` has to be run as this will probably give already a lot of useful information to us.

**Comment by Azaretdodo** [comment]
I was do this before yes

Thank you to help on the problem,

Not give a problem anything you think I havn't did

I have did before yes,

Thank you to keep on the problem,

Regards.


Azaretdodo.
Envoyé d’Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by albert-github** [comment]
We don't need the comments, we need the output.

**Comment by Azaretdodo** [comment]
I have ever give the output,

If you want keep your github become useful or just trust your customer when he explain anything,

Regards.


Azaretdodo.

Envoyé d’Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by doxygen** [comment]
@Azaretdodo  Since you only seem to want to waste our time, and I see you do the same on other projects I've decided to block you. You have the dubious honor to be the first user I've ever blocked. Now please go back to school and learn how to behave.

**Comment by hachi-27** [comment]
Hey @doxygen 
He was right the same problem is occurring with me too.
```
himanshugupta@Himanshus-MacBook-Air ~/doxygen/build % sudo make
[  0%] Building C object libmd5/CMakeFiles/md5.dir/md5.c.o
[  0%] Linking C static library ../lib/libmd5.a
[  0%] Built target md5
[  0%] Building CXX object liblodepng/CMakeFiles/lodepng.dir/lodepng.cpp.o
[  1%] Linking CXX static library ../lib/liblodepng.a
[  1%] Built target lodepng
[  2%] Generating ../generated_src/mscgen_lexer.l.h
/bin/sh: ../../src/scan_states.py: Permission denied
make[2]: *** [generated_src/mscgen_lexer.l.h] Error 126
make[2]: *** Deleting file `generated_src/mscgen_lexer.l.h'
make[1]: *** [libmscgen/CMakeFiles/mscgen.dir/all] Error 2
make: *** [all] Error 2
```
 I have tried all the previous steps you mentioned which are to remove the build dir and then rebuild it but nothing is working out.
 I am using macOS Big Sur with Cmake 3.21 and have python 3.9 installed as default.

**Comment by albert-github** [comment]
I assume you cloned (and recently updated) the doxygen repository and want to build the master branch.
- what is the `cmake` command you used ?
- what is the output of the `cmake` command ?
- why do you use `sudo make` and not just `make` ?

Some the tests (execute consecutive):
- `cd ~/doxygen/build/generated_src`
- What are the permissions (i.e. `ls -ls`) of the file `scan_states.py` i.e `ls -ls ../../src/scan_states.py`?
- what happens when you type `python ../../src/scan_states.py ../../libmscgen/mscgen_lexer.l`?

**Comment by hachi-27** [comment]
Yes exactly.
CMake command used: `sudo cmake -G "Unix Makefiles" ..`
Output: 
```
-- The C compiler identification is AppleClang 13.0.0.13000029
-- The CXX compiler identification is AppleClang 13.0.0.13000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Python3: /usr/local/Frameworks/Python.framework/Versions/3.9/bin/python3.9 (found version "3.9.7") found components: Interpreter
-- Found FLEX: /usr/bin/flex (found version "2.6.4")
-- Found BISON: /usr/local/opt/bison/bin/bison (found version "3.8.2")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Looking for iconv_open
-- Looking for iconv_open - not found
-- Performing Test ICONV_COMPILES
-- Performing Test ICONV_COMPILES - Success
-- Found Iconv: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/lib/libiconv.tbd
-- One (and only one) of the ICONV_ACCEPTS_... tests must pass
-- Performing Test ICONV_ACCEPTS_NONCONST_INPUT
-- Performing Test ICONV_ACCEPTS_NONCONST_INPUT - Success
-- Performing Test ICONV_ACCEPTS_CONST_INPUT
-- Performing Test ICONV_ACCEPTS_CONST_INPUT - Failed
-- The javacc executable not found, using existing files
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/himanshugupta/doxygen/build
```

- I used sudo make because I thought sudo will solve the issue but it didn't.
- permissions `-rw-r--r--  1 himanshugupta  staff  1591 Oct  4 23:06 ../../src/scan_states.py`
- When I type `python ../../src/scan_states.py ../../libmscgen/mscgen_lexer.l`
```
static const char *stateToString(int state)
{
  switch(state)
  {
    case INITIAL: return "INITIAL";
    case IN_COMMENT: return "IN_COMMENT";
    case BODY: return "BODY";
  }
  return "Unknown";
}
```

**Comment by albert-github** [comment]
Strange problem.

Looks all reasonable and I understand why you tried the `sudo` (but `sudo` is not necessary, just, sometimes, when you want to install doxygen)
Only thing different from what I see is that the protection of the `scan_states.py` I have is `-rw-rw-r--` and you have `-rw-r--r--` but I don't think this should matter.
Can you execute:
- `cd ~/doxygen/build`
- `grep "scan_states.py" ./libmscgen/CMakeFiles/mscgen.dir/build.make | grep msc`
  the second line (starting with `cd`) gives here a command that is executed. Can you execute these commands ? and also report the command?

**Comment by hachi-27** [comment]
When I execute `grep "scan_states.py" ./libmscgen/CMakeFiles/mscgen.dir/build.make | grep msc` I get this 
```
cd /Users/himanshugupta/doxygen/build/libmscgen && ../../src/scan_states.py/Users/himanshugupta/doxygen/libmscgen/mscgen_lexer.l > /Users/himanshugupta/doxygen/build/generated_src/mscgen_lexer.l.h
```
What do I do now?

**Comment by albert-github** [comment]
This is already very interesting!!
On my system I see that python is called with the `scan_states.py` file, it looks like the in your cmake results in one way or another the variable `PYTHON_EXECUTABLE` is empty.

Small tests
- goto your base directory `cd ~/doxygen/`
- in the file `CMakeLists.txt` after the line
   ```
   find_package(PythonInterp REQUIRED)
   ```
   place the line
   ```
   message(WARNING "Doxygen uses the Python executable: ${PYTHON_EXECUTABLE}")
   ```

The protections of the `scan_states.py` state that it is just a read/write file and not an executable file, but it has a "shebang" in it so it could be execute when the protections are right (just set the protections to 775) and rerun (as a workaround).

**Comment by albert-github** [comment]
Also try as a test:
- `cd ~/doxygen/build/generated_src`
- `/usr/local/Frameworks/Python.framework/Versions/3.9/bin/python3.9 ../../src/scan_states.py ../../libmscgen/mscgen_lexer.l`

**Comment by hachi-27** [comment]
Hey thanks, it worked. 
Yes, it was the issue of the python executable. I fixed it.

**Comment by albert-github** [comment]
@hachi-27 
Can you maybe spend 1 or 2 sentences on what you had to fix / what was wrong, so other users with the same problem could learn from it.

**Comment by hachi-27** [comment]
Sure.
It was nothing major.
I had multiple versions of python installed. So the system was getting
confused so I had to resolve just that.
And then it worked.
