### ISSUE TITLE
Doxygen 1.8.18: Markdown tables not working in ALIASES anymore?

### ISSUE THREAD

**Issue by effaremment** [doxygen/doxygen#7787]
I'm migrating a large set of docs from Doxygen 1.8.14 to Doxygen 1.8.18
I'm using ALIASES to generate tables in my docs.

I cannot succeed to generate tables with doxygen 1.8.18, whereas it was working fine with 1.8.14

[table-markdown-doxy1.8.18.tar.gz](https://github.com/doxygen/doxygen/files/4651399/table-markdown-doxy1.8.18.tar.gz)
Here's what I get :
![image](https://user-images.githubusercontent.com/2772432/82343837-9c80a280-99f3-11ea-8982-b029f6bb9dad.png)
The first table is defined in line in a .dox file, while the second one is defined as an ALIASES.

I'm attaching a small sample (.dox file and Doxyfile)

I'm running on
Welcome to Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-96-generic x86_64)

And the version of Doxygen is 1.8.18:
$ doxygen --version
1.8.18
$

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7788

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).
The total solution also contains some more changes, especially to make it more consistent and also to have `^^` work in case `MARKDOWN_SUPPORT=NO` is used.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.19.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
