### ISSUE TITLE
Linking to pdf file

### ISSUE THREAD

**Issue by MLapaj1** [doxygen/doxygen#7789]
I am trying to insert a link to a pdf file in a C language header .h file, using Doxygen 1.8.17

According to doxygen documentation @link and @endlink commands can be used for automatic links generation.

The line of code below does indeeed generate a link to a file, but the said .pdf file is being converted into HTML file and is completly unreadable:
` /** @link IEC60730_B_Clock_Test_for_CM0_rev3_0.pdf link to pdf @endlink */
`
![image](https://user-images.githubusercontent.com/65705825/82537816-f34cc000-9b4a-11ea-8b83-d8bc94c25b82.png)

I did keep in mind to add the .pdf file to INPUT as well as EXTRA_HTML_FILES in doxyfile configuration.

Is there any way I can make doxygen link to the actual .pdf file and not it's html conversion?

**Comment by albert-github** [comment]
Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.

I think you need something like:
```
<a href="linkURL">link text</a>
```
so
```
<a href="IEC60730_B_Clock_Test_for_CM0_rev3_0.pdf"> link to pdf</a>
```
(In case the pdf is a local file, don't forget to place it in the html directory)
