### ISSUE TITLE
Doxygen-comment in C in Markdown disappears

### ISSUE THREAD

**Issue by wataash** [doxygen/doxygen#7793]
**Update:** as in comments, this issue can be avoided by adding `STRIP_CODE_COMMENTS = NO` in Doxyfile.

**Describe the bug**

When I wrote Doxygen coding style in Markdown in my project,

    
    # Doxygen markup coding style
    
    Doxygen style in C must be like this:
    
    ```c
    /**
     * good
     */
    int a;
    
    /** good */
    int b:
    
    /// bad
    int c;
    
    int d; /**< good */
    int e; /*!< bad */
    ```

These Doxygen-style comments all disappears in HTML:

![image](https://user-images.githubusercontent.com/4846670/82720431-8d00a280-9cee-11ea-9786-c1db2a993d97.png)

**Expected behavior**

They survive.

![image](https://user-images.githubusercontent.com/4846670/82720468-d9e47900-9cee-11ea-8d08-3773699d520c.png)

**To Reproduce**

    mkdir test/

    cat > test/test.md << 'EOS'
    # Doxygen markup coding style
 
    Doxygen style in C must be like this:

    ```c
    /**
    * good
    */
    int a;

    /** good */
    int b:

    /// bad
    int c;

    int d; /**< good */
    int e; /*!< bad */
    ```
    EOS

    cat > test/Doxyfile << EOS
    GENERATE_HTML = YES
    GENERATE_XML = YES
    INPUT=$PWD/test/test.md
    XML_OUTPUT=$PWD/test/out/
    HTML_OUTPUT=$PWD/test/html/
    HTML_FILE_EXTENSION=.xhtml
    EOS

    doxygen test/Doxyfile
    open test/html/md_test_test.xhtml

**Version**

git-master (ff5ba4a40)

**Comment by albert-github** [comment]
We have here some code that has to be rendered according to the C syntax, this is comparable to using `SOURCE_BROWSER` for a `.c` file. In the source browser doxygen type comments are removed as well unless the configuration setting `STRIP_CODE_COMMENTS ` is used, its documentation:

> Setting the STRIP_CODE_COMMENTS tag to YES will instruct doxygen to hide any special comment blocks from generated source code fragments. Normal C, C++ and Fortran comments will always remain visible.
The default value is: YES.

So the result is, in my opinion, correct and it its a usage problem.

**Comment by wataash** [comment]
Thanks, that's right...
Sorry for skipping adding reproduce procedure... I've added it.
