### ISSUE TITLE
warning: Found ';' while parsing initializer list! (doxygen could be confused by a macro call without semicolon)

### ISSUE THREAD

**Issue by svarshavchik** [doxygen/doxygen#7799]
**Describe the bug**
Doxygen 1.8.18 emits this warning and does not document a C++ function with a C++20 constraint definition.

The sample file has only create2() documented, with a malformed chunks of create() attached to it.

test.cpp compiles cleanly with gcc 10.1.1, using:

g++ -std=c++20

**Expected behavior**

Both create() and create2() documented individually.

**To Reproduce**
doxygen -g with EXTRACT_ALL=YES, HTML_DYNAMIC_MENUS=NO, look at the documentation for test.cpp

**Additional context**
Welcome to C++20!

[Doxyfile.txt](https://github.com/doxygen/doxygen/files/4672816/Doxyfile.txt)
[test.cpp.txt](https://github.com/doxygen/doxygen/files/4672817/test.cpp.txt)

**Comment by albert-github** [comment]
In the doxygen version 1.8.18 we see the warning as indicated.
In the current version (1.9.4 (5d15657a55555e6181a7830a5c723af75e7577e2)) the warning is gone.

I think the problem has been solved in the mean time.

**Comment by Juan-jqtouch** [comment]
@albert-github https://stackdev.space/questions/can-you-please-explain-the-meaning-of-this-list-of-initializers

**Comment by albert-github** [comment]
@Juan-jqtouch 

- What do you mean?
- Where do you see a problem?
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem?
   Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).
- Please also specify the full doxygen version used (doxygen -v).
