### ISSUE TITLE
EXCLUDE_SYMBOLS        = "#define *"   is not working as expected 

### ISSUE THREAD

**Issue by KITTUKRISHNA5** [doxygen/doxygen#7808]
Doxygen Version 1.8.11 using 

as I have used config option  ENABLE_PREPROCESSING	= YES
and also defined some needful macros list using  
PREDEFINED			 += "MC_LIMPHOME_ENABLE=1" \

NOTE: The look of predefines in my source file is like 
#define MC_IBUF_SIZE (2u) /*want to ignore */

all preprocessor directives in the source file (which was parsed by doxygen ) are shown in the final generated pdf document 
But that is too much I got on pdf report I just don't need some macros display on the final generated pdf report 

So I have used Exclude symbols option but its not working 
I have not consider the option //@cond and //@endcond due to limit code annotations inside source files 

Kindly correct me if I miss something

**Comment by albert-github** [comment]
Doxygen version 1.8.11 is a bit old (December 30, 2015) the c8urrent doxygen version is 1.8.18
It is a bit clear what you mean with `EXCLUDE_SYMBOLS = "#define *" is not working as expected `, the `EXCLUDE_SYMBOLS ` is not for removing #define, but for symbols i.e. variable names, fubction names, class names etc. 

- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.
- Possibly indicate with some images what you would like to omit in your output.

**Comment by KITTUKRISHNA5** [comment]
ok here I am sending the zip file which has doxcfg file and .c file 

[zip.zip](https://github.com/doxygen/doxygen/files/4695154/zip.zip)

**Comment by KITTUKRISHNA5** [comment]
from line 42 
/// @cond
/** buffer data */
#define BEGIN_DATA_FOR_TASKFAST
/// @endcond

I have used ///@cond and ///@endcond 
but I don't think that's the best option to exclude only macros 

Could you tell me how to skip unnecessary macros just by using some configuration options only

**Comment by albert-github** [comment]
The given zip file had some flaw, but I was able to work around it. The flaws were:
```
error: @INCLUDE = ../../../../tex/doxygen/mc_Config.doxcfg: not found!
```
and
```
warning: source ../../code/src/asil is not a readable file or directory... skipping.
warning: source ../../code/inc/asil is not a readable file or directory... skipping.

warning: source ../../code/src/mc_ibuf.c is not a readable file or directory... skipping.
warning: source ../../code/inc/mc_ibuf.h is not a readable file or directory... skipping.
warning: source ../../code/inc/mc_tibuf.h is not a readable file or directory... skipping.
```

I created the example: [example.tar.gz](https://github.com/doxygen/doxygen/files/4695254/example.tar.gz)

And in the Doxyfile you can see that I used:
```
EXCLUDE_SYMBOLS        = BEGIN_DATA_FOR_TASKFAST_EXCL
EXCLUDE_SYMBOLS       += "#define*"
```
the
```
EXCLUDE_SYMBOLS       += "#define*"
```
has no effect as indicated before. The
```
EXCLUDE_SYMBOLS        = BEGIN_DATA_FOR_TASKFAST_EXCL
```
removes the symbol / define  `BEGIN_DATA_FOR_TASKFAST_EXCL` from the documentation.

From the documentation:
> The EXCLUDE_SYMBOLS tag can be used to specify one or more symbol names (namespaces,
classes, functions, etc.) that should be excluded from the output. The symbol name can be a fully
qualified name, a word, or if the wildcard * is used, a substring. Examples: ANamespace, AClass, A -
Class::ANamespace, ANamespace::*Test

**Comment by KITTUKRISHNA5** [comment]
Thank you Albert I really appreciate your help and time spend on my problem 
But the way you suggested requires manual effort by writing down all the defines in the doxcfg file 

like below 
EXCLUDE_SYMBOLS        += "BEGIN_DATA_FOR_TASKFAST_EXCL"\
						  "BEGIN_DATA_FOR_TASKFAST"\
						  "MC_IBUF_SIZE"\
						  "END_DATA_FOR_TASKFAST"\
						  "BEGIN_CODE_FOR_INIT_TASKSLOW"\
						  "END_CODE_FOR_INIT_TASKSLOW"\
						  "BEGIN_CODE_FOR_INIT_TASKFAST"\
						  "END_CODE_FOR_INIT_TASKFAST"\
						  "BEGIN_CODE_FOR_TASKSLOW"\
						  "END_CODE_FOR_TASKSLOW"\
						  "BEGIN_CODE_FOR_TASKFAST"\
						  "END_CODE_FOR_TASKFAST"\
						  "BEGIN_CODE_FOR_TASKSLOW"\
						  "END_CODE_FOR_TASKSLOW"

so if there is any other possibility that I can simply ignore #defines please do let me know 

and in the attached file below
[mc_ibuf.pdf](https://github.com/doxygen/doxygen/files/4695656/mc_ibuf.pdf)
in the page 3of9

3.1 Module_mc_ibuf
Files
 file mc_ibuf.c
 file mc_ibuf.h
 file mc_tibuf.h

if i click on mc_ibuf.c or other files it is not referencing files i was trying to expect a behaviour that if i click on mc_ibuf.c file it will open file itself that too this action should not be a part of .tex file which i am using for some manual documentation part is this possible please let me know

**Comment by albert-github** [comment]
Regarding the defines, maybe use wildcards, otherwise there is, to the best of my knowledge, no other way than to list them all.

Regarding the links, I have not enough information to see why this happens, but did you set `SOURCE_BROWSER` and / or `LATEX_SOURCE_CODE`?

**Comment by KITTUKRISHNA5** [comment]
no I did not set 
I will set them and come back

**Comment by KITTUKRISHNA5** [comment]
I have used both config options

GENERATE_LATEX         = YES

SOURCE_BROWSER		   = YES 

LATEX_SOURCE_CODE	= YES

but still the generated pdf files file section file names doesn't have reference to actual files included in doxcfg file

**Comment by albert-github** [comment]
An example with the required files (source, where the implementation part is removed so only function definitions with their starting `{` and ending `}` remain, and doxygen configuration) would be nice so we can try to reproduce the problem.

**Comment by KITTUKRISHNA5** [comment]
[zip.zip](https://github.com/doxygen/doxygen/files/4696514/zip.zip)

Here is the zip file as requested 
Have also attached a .tex file which used to generate some manual sections of documentation is it possible that i can also automate the Locconst section which is 2nd section in pdf report i haver shared please let me know
Thank you

**Comment by albert-github** [comment]
From the given zip file (with the same problems regarding the missing files as reported before) I can generate with doxygen a pdf file in the latex directory (21 pages).

It is not 100% clear what the intention is of `mc_ibuf.tex`, is this a replacement for the default `refman.tex` ? For me it is a bit incomplete
- no documentclass specifies
- files
  `\input{../../../../tex/general/zfheader}`
  `\input{../../../../tex/general/doxygen_add}`
  are missing

I can imagine some problems when not all files are that are references are not included, but as far as I can see this is not a doxygen problem as it concerns your own "template".

**Comment by KITTUKRISHNA5** [comment]
mc_ibuf.tex Is used to feed final report with some sections which cannot be parsed automatically from source file so we put that manual information inside mc_ibuf.tex and make it part of doxygen run
I still did not get answer how to reference a file name in red colour shown up in pdf file such that if I click on the file name it should open the actual file 

new issue: I have a small structure inside a big structure in my source file 
the small structure is documented in othre file which i have already  incuded in @include section in the config file of doxygen
I can able to parse information about big structure using doxygen code annotations  in the main source file but for the documentation of the small structure what config options I need to use because as I can see my final generated pdf file make the small structure in red colour but when I click on it that's not doing the page referencing I mean going to the place in the pdf document where the definitions of the small structure is present please help on this too

**Comment by albert-github** [comment]
> I still did not get answer how to reference a file name in red colour shown up in pdf file such that if I click on the file name it should open the actual file

When you you use `SOURCE_BROWSER` you could reference the file generated by doxygen `..._source....tex` (and this file should be included as well). When really accessing the original file you should `<a href==...` as this will be be translated by doxygen to a link. It is up to pdf / settings how it will be opened. but I think the `...source...` construct will be better.

> new issue

Better not use one issue for multiple topics, create a new issue (with example etc.) or ask on https://stackexchange.comwhich is actually a better place as issue here are more for bugs etc.

**Comment by KITTUKRISHNA5** [comment]
Thank you Albert could you resend the link the link you have send is not working

**Comment by albert-github** [comment]
It were just 2 words concatenated, the link should have been: https://stackexchange.com or probably better https://stackoverflow.com/
