### ISSUE TITLE
Param tags within groups gives latex errors 

### ISSUE THREAD

**Issue by the78mole** [doxygen/doxygen#7816]
**Describe the bug**
When param tags are used within groups, latex still produces errors. Like "Missing Number treated as zero".

**Expected behavior**
No errors :-)

**Screenshots**
![image](https://user-images.githubusercontent.com/7723396/83315883-164e3280-a223-11ea-9d7a-cb023a1a9c47.png)

**To Reproduce**
Clone e.g. the [FreeRTOS repository](https://github.com/FreeRTOS/FreeRTOS-Kernel), generate a default Doxyfile with `RECURSIVE = YES`, run doxygen, then run make in latex folder. This should raise the error.

**Version**
doxygen 1.8.18 (and master), Windows 10, MSYS2

**Stack trace**
...

**Additional context**
Already fixed the bug in my doxygen fork by switching from tabu to longtable and adding an explicit parameter 0 for additional columns.
https://github.com/the78mole/doxygen/commit/af912068c4763ed31724724e951bdd0dad1eabe8

**Comment by albert-github** [comment]
The Free RTOS repository is a moving target and as such not really suited as an example, so:
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.


Regarding the proposed patch as part of another patch, please remove it from that patch (#7815) and create a separate patch out of it (In my opinion it is a bad idea to mix unrelated patches).

**Comment by the78mole** [comment]
I tried to remove it, but I can not find a way how to do it. I made my pull request on master with the first commit and then, when I pushed the second, it somehow moved to the newest master. Don't know, how to revert it.

**Comment by albert-github** [comment]
Easiest way for you will be to just undo the changes and push again.

I always create a branch to push my changes, so that I can separate the different changes (but git is not very user friendly and its working is very hard to understand, I didn't really master).

**Comment by albert-github** [comment]
When we look at the warnings as emitted by doxygen we see (a.o):
```
.../FreeRTOS-Kernel/include/message_buffer.h:303: warning: end of comment block while expecting command </pre>
.../FreeRTOS-Kernel/include/message_buffer.h:407: warning: end of comment block while expecting command </pre>
.../FreeRTOS-Kernel/include/message_buffer.h:407: warning: end of comment block while expecting command </pre>
.../FreeRTOS-Kernel/include/task.h:2307: warning: end of comment block while expecting command </pre>
.../FreeRTOS-Kernel/include/task.h:2307: warning: end of comment block while expecting command </pre>

```
indicating a bit of a problem in the usage of the `<pre>` tag. (I got  this "hint" as when looking in the problematic tex file I saw just above it 2 non closed `\begin{DoxyPre}` statements)

Investigating these the correction is as follows:
```
diff --git a/include/message_buffer.h b/include/message_buffer.h
index b20c09e81..adc15fe84 100644
--- a/include/message_buffer.h
+++ b/include/message_buffer.h
@@ -215,7 +215,7 @@ size_t xMessageBufferSend( MessageBufferHandle_t xMessageBuffer,
                            const void *pvTxData,
                            size_t xDataLengthBytes,
                            TickType_t xTicksToWait );
-<pre>
+</pre>
  *
  * Sends a discrete message to the message buffer.  The message can be any
  * length that fits within the buffer's free space, and is copied into the
@@ -314,7 +314,7 @@ size_t xMessageBufferSendFromISR( MessageBufferHandle_t xMessageBuffer,
                                   const void *pvTxData,
                                   size_t xDataLengthBytes,
                                   BaseType_t *pxHigherPriorityTaskWoken );
-<pre>
+</pre>
  *
  * Interrupt safe version of the API function that sends a discrete message to
  * the message buffer.  The message can be any length that fits within the
diff --git a/include/task.h b/include/task.h
index 3eaf6eecb..31aee0cd6 100644
--- a/include/task.h
+++ b/include/task.h
@@ -2234,8 +2234,8 @@ BaseType_t xTaskGenericNotifyWait( UBaseType_t uxIndexToWaitOn, uint32_t ulBitsT

 /**
  * task. h
- * <PRE>void vTaskNotifyGiveIndexedFromISR( TaskHandle_t xTaskHandle, UBaseType_t uxIndexToNotify, BaseType_t *pxHigherPriorityTaskWoken );
- * <PRE>void vTaskNotifyGiveFromISR( TaskHandle_t xTaskHandle, BaseType_t *pxHigherPriorityTaskWoken );
+ * <PRE>void vTaskNotifyGiveIndexedFromISR( TaskHandle_t xTaskHandle, UBaseType_t uxIndexToNotify, BaseType_t *pxHigherPriorityTaskWoken );</PRE>
+ * <PRE>void vTaskNotifyGiveFromISR( TaskHandle_t xTaskHandle, BaseType_t *pxHigherPriorityTaskWoken );</PRE>
  *
  * A version of xTaskNotifyGiveIndexed() that can be called from an interrupt
  * service routine (ISR).
```

So in my opinion the problem is usage.
