### ISSUE TITLE
Odd Warn Behavior with Unnamed size_t param

### ISSUE THREAD

**Issue by birm** [doxygen/doxygen#7818]
**Describe the bug**
Consider this code snippet:
```c++
  /**
   * Initialize parameters before factorization.  This function must be called
   * before a new factorization.  For this initialization, the input parameters
   * are unnecessary; we are only setting the current element index to 0.
   *
   * @param * (dataset) Input matrix to be factorized.
   * @param * (rank) Rank of factorization.
   */
  void Initialize(const MatType& /* dataset */, const size_t /* rank */)
  {
    // Initialize the current score counters.
    currentUserIndex = 0;
    currentItemIndex = 0;
  }
```

This is does not produce a warning on 1.8.13, but does on 1.8.17
However, the following fixes all warnings associated in 1.8.17 (deb, and self compiled) as well as 1.8.19* (self compiled; 1705a1442dfa83d6c442bb45ed0d6e76f135ee5a)

```c++
  /**
   * Initialize parameters before factorization.  This function must be called
   * before a new factorization.  For this initialization, the input parameters
   * are unnecessary; we are only setting the current element index to 0.
   *
   * @param * (dataset) Input matrix to be factorized.
   * @param size_t (rank) Rank of factorization.
   */
  void Initialize(const MatType& /* dataset */, const size_t /* rank */)
  {
    // Initialize the current score counters.
    currentUserIndex = 0;
    currentItemIndex = 0;
  }
```

So, as far as I can tell, it's only concerned with size_t params, which it thinks are called size_t.

**Expected behavior**
As the above is strange behavior, I would expect warnings for either both or none of the unnamed params 

**Additional context**
It would also be nice to have a canonical way to document a param which is unused in the implementation.
This touches lightly upon some of #6926

**Comment by albert-github** [comment]
When looking at the 2 examples
With doxygen version 1.8.17 we get for the first example the warning:
```
aa.cpp:11: warning: The following parameter of Initialize_err(const MatType &, const size_t) is not documented:
  parameter 'size_t'
```
which is incorrect as `size_t` is not a parameter but part of the type. Also the fix (second example) is in principle not OK as here it looks like the name of the variable is `size_t`.

With the current doxygen version (1.9.7) we get for the second example the warning:
```
aa.cpp:20: warning: argument 'size_t' of command @param is not found in the argument list of Initialize_ok(const MatType &, const size_t)
```
This is correct as `size_t` is not the name of the variable but the type.
The first example is OK as it should be.

I think the problem has been solved in the mean time.

**Comment by birm** [comment]
Thanks for following up, this is good to know! It's amazing what will be passively fixed in 3 years of development!
