### ISSUE TITLE
Doxygen parsing capacity is limited 

### ISSUE THREAD

**Issue by KITTUKRISHNA5** [doxygen/doxygen#7838]
Problem: Doxygen cannot parsing a structure documentation inside .c file(and cannot create a corresponding .tex file) but parsing correctly from a separate .h file 

Assumptions: Does the structures inside .c file where generally the functions are documented are not visible to doxygen parser?

Workflow: doxygen run >parsing from files>create a pdf

The final generated file is missing the structure documentation inside .c file but all other structures inside a separate .h files are documented and find their place in generated .pdf file 
Why missing?

What I tried: I have tried giving those structure names (which I thought missing in the documentation) in the .tex file automated part as \input{structt_Ref2_Control} then I am getting an omake error saying "The .tex (relevant for missing structure) file is missing"
[ibuf.zip](https://github.com/doxygen/doxygen/files/4751371/ibuf.zip)

**Comment by KITTUKRISHNA5** [comment]
Sorry I missed out doxygen version it is 1.8.11

**Comment by florent-lamiraux** [comment]
You may add `*.c` in the definition of `FILE_PATTERNS` in your `Doxyfile`, and add the directory where your file is to the definition of `INPUT`.

**Comment by KITTUKRISHNA5** [comment]
i have changed the configuration option which you have suggested but still doxygen cannot able to create .tex files for missing structure
 question: if you check my doxygen config file i have already given path to the exact files which covers the location too but why still missing 
and 
if i want to see some files in the automated files section in .pdf file is it enough to mention those files in INPUT= section ?? and those files neccesarily have doxy comments in it to shown up in .pdf file????

**Comment by florent-lamiraux** [comment]
I am sorry, I cannot run doxygen on your .zip archive/
```
/tmp/ibuf$ doxygen stackhelp.doxcfg
error: @INCLUDE = ../../../../tex/doxygen/mc_Config.doxcfg: not found!
```

**Comment by KITTUKRISHNA5** [comment]
[ibuf.zip](https://github.com/doxygen/doxygen/files/4751797/ibuf.zip)
here i have added the file you need to run

**Comment by florent-lamiraux** [comment]
I get the same error.
Please make a self-contained archive with a README telling which command I am supposed to run.
Inflate this archive somewhere on your file system and check that the instructions work. Then I can try to find the problem.

**Comment by KITTUKRISHNA5** [comment]
i am afraid that did not catch you correctly what you want me to  do

**Comment by albert-github** [comment]
@KITTUKRISHNA5 
The problem with the case you resent is the same as with your other questions!
- we don't have the file `../../../../tex/doxygen/mc_Config.doxcfg` as used in the `@INCLUDE` tag and the second zip file contains the `mc_Config.doxcfg` but as the directory structure is flat it cannot be found.
- In the INPUT tag you write:
   ```
  INPUT += ../../code/src/mc_ibuf.c \
                 ../../code/inc/mc_ibuf.h \
                 ../../code/inc/mc_tibuf.h
   ```
   but the zip file contains a flat structure and contains the files `stackhelp.c` and `stackhelp.h` 
- similar issue for `EXAMPLE_PATH`

So follow what @florent-lamiraux intended, use your own zip file unpack it in a new directory and run doxygen here and be sure that the relative paths as used in your **cannot** be found so best to extract on `/tmp` or in case of windows on another disk than you normally work.

Also as mentioned before upgrade your version of doxygen as 1.8.11 is from December 2015.

**Comment by KITTUKRISHNA5** [comment]
I have shortened the code part in the files and rename it to stackhelp.c,.h files so you can consider those files as some generic files and run doxygen 
My client will not allow me to do doxygen update for now so I cannot update that now

**Comment by albert-github** [comment]
I don't see what you are missing.

Do one step back an only use doxygen and no extra tex files etc.
- please run just doxygen on the file stackhelp.c
- run make in the latex directory
- present us the resulting latex and html directories in zip file or a compressed tar file.
- inspect the resulting pdf file and indicate what you are missing preferably by means of images.

**Comment by KITTUKRISHNA5** [comment]
Hi Albert und florent-lamiraux 
Good Morning 
Let us keep this very simple 

I have a project with .c and .h files and I have a doxygen 1.8.11 installed and I also have .tex manually written file and a make file 

So every time I run my make file which has commands to created a pdf target 

To create the target file with makefile execution I have given two dependencies
1.Tex file (Manually written)
2.Doxygen output (by running doxygen on .c and .h files for parsing with .doxcfg file )

 Here things are clear that pdf is made with documentation of functions and other stuff of .c and .h files 

 The structure documentation inside .h files are parsed by doxygen and shown up in pdf report

NOTE::: I also written doxygen special comments for structure  inside .c file which were not shown up in pdf report

and also the created Latex folder does not consist the .tex file for those missing structrues but for the structures inside the .h file the doxygen created corresponding .tex files inside Latex folder 

I have attached a zip with the generated Latex folder content not all but some tex files 
please refer to group__module__mc__ibuf.tex fie 
I also woul need to know how the .tex files inside Latex folder made???
if I know that I would figure out why the missing structures don't have .tex files inside Latex folder
[latex1.zip](https://github.com/doxygen/doxygen/files/4762724/latex1.zip)

which LaTeX version are you using, just type pdflatex --version
i dont know where exactly i can run the above command

**Comment by albert-github** [comment]
> I also woul need to know how the .tex files inside Latex folder made???

It is made by the doxygen program by parsing and processing the input files and outputting the results in LaTeX format. Look in the documentation and source code of doxygen for more information.

> which LaTeX version are you using, just type `pdflatex --version`

Just type the the command  on a command line / in a terminal window or see in the log file n the generated latex directory.

> 1.Tex file (Manually written)

Of no real interest, sole responsibility of the user. This was why I was asking for the results of just the doxygen run.

> latex1.zip

As this is only a part of the output nothing can be done with it by us for detecting problems
- only provide full examples with input and output
- provide images indicating where the problems are or a  good description of what is missing just "please refer to group__module__mc__ibuf.tex fie" doesn't work

**Comment by KITTUKRISHNA5** [comment]
[ibuf.zip](https://github.com/doxygen/doxygen/files/4763725/ibuf.zip)
Here ia m sending complete file structure the make file the .c ,.h files doxcfg file and others 

if you successfully generated a pdf under section automated.... 
I am expecting under structures section the other two structs which are defined and documented in .c file 

I know why they are not shown (if you see .tex file i have commeneted out them in /input{missing structure files..})
because of the reason there is no .tex files created corresponding to missing structures inside .c file
I commented then in the .tex file

**Comment by KITTUKRISHNA5** [comment]
in the common.mk file I used below rule to build the target required (along with .tex file) for making pdf report::::

latex/modules.tex : $(TARGETFILE,B).doxcfg
	$(DOXYGEN_EXEC) $(.SOURCE)

**Comment by KITTUKRISHNA5** [comment]
Hi Again 
If I make those structures(missing structures) part of mc.tibuf.h file instead keeping inside mc,ibuf.c file 
actually it working 
I mean doxygen could parse the structure documentation perfectly and creating .tex file for the structures 

please look into it as I really need to maintain those structures inside .c file itself but not in .h files

**Comment by albert-github** [comment]
I cannot look into it when I don't have a good case and information about where to look for the problems.

**Comment by KITTUKRISHNA5** [comment]
ok thanks

**Comment by KITTUKRISHNA5** [comment]
I have provided all the information now already
May I know what else you need to answer my question

**Comment by albert-github** [comment]
It is well possible that you provided all the information already, but I think I still miss the information of what is exactly missing in the result. The problem I have is that the information is a bit fragmented. So lets skip the above.

Create 2 projects:
- Project 1
   - create the .c and .h files in this project and have the documentation of the structure is in the `.c` file (so the "wrong" situation)
   - create a Doxyfile that runs this project and generated HTML and latex output
   - run after the doxygen run the `make` command in the latex directory
- Project 2
   - create same project as for Project 1 but now place the documentation of the structure in the `.h` file
   - create a Doxyfile that runs this project and generated HTML and latex output
   - run after the doxygen run the make command in the latex directory
- don't put, from the doxygen point of few, irrelevant files in these projects (like own generated `.tex` files), we want to look at the bare doxygen results
- compare the results from Project 1 and Project 2 and indicate exactly where some information in your opinion is missing (either by means of an image or by giving page number in the resulting pdf, function and description what is missing).
- pack the complete Project 1 and Project 2 in a zip  or compressed tar file and share this.

Best would also be that you upgrade your version of doxygen (or at least place the doxygen executable etc. in a separate directory and use this executable. The doxygen distribution, see https://www.doxygen.nl/download.html, "paragraph" 'A binary distribution for Windows. All versions of Windows since Vista are supported.' also contains zip files with just the required executable.) and see what the results are. For this nod administrator privileges etc are necessary.

**Comment by KITTUKRISHNA5** [comment]
Thanks for the reply here I am attaching one zip which has both project 1 and project 2 inside it 
[Project.zip](https://github.com/doxygen/doxygen/files/4776002/Project.zip)
NOTE: in both the folders i have added  the pdf report and inside the report i have added a floating comment what exactly wrong please find

sorry for the late reply with attachments

**Comment by albert-github** [comment]
Looks quite a bit what I want to have, but

- make has not been run in the Project1/latex directory (and Project2/latex directory)
- the `mc_ibuf.doxcfg` still contains some statements specific for your system for reproducibility it is essential that I get a case that I can run without problems, to get it a bit running:
  - I have to comment out:
    - @INCLUDE = ../../../../tex/doxygen/mc_Config.doxcfg
  - I have to replace the `INPUT` tag by
    - INPUT = CODE/mc_ibuf.c
    - INPUT += CODE/mc_tibuf.h

- apparently the `../../../../tex/doxygen/mc_Config.doxcfg` contains some essential statements to reproduce the output, I identified already:
  - OPTIMIZE_OUTPUT_FOR_C = YES
  - USE_MATHJAX = YES
  - there are certainly more ...

- I checked the provided pdf files, these were not the ones I wanted to have but the floating notes give a good indication of what is missing, it looks like it is coming from the file: `group__module__mc__ibuf.tex`.
- I checked with the 1.8.11 version the output I could obtain based on the doxygen settings provided and here I don't see any difference between the files `Project1\latex\group__module__mc__ibuf.tex` and `Project2\latex\group__module__mc__ibuf.tex`
  - So it essential that you provide the file: `../../../../tex/doxygen/mc_Config.doxcfg`

**Comment by KITTUKRISHNA5** [comment]
Hello Good Morning Albert
so when you mention you didn't see any difference between the files 
Project1\latex\group__module__mc__ibuf.tex and Project2\latex\group__module__mc__ibuf.tex
do you mean you can see the missing documentation present in those files as /input sections with xxx.tex given to it??

based on the fact I know that the missing structure related .tex files are not created I have commented out the input of giving those files inside mcibuf.tex file as /input section 

so pretty much it will not shown any details about the missing structures 
the fact Doxygen cannot created .tex files it is forcefully pushed me to comment out/delete those sections of giving those inlusions inside mcibuf.tex file (which is having the commands to generate the automated part of the documentation)

any way im attaching the configuration files for you please find:

[zip.zip](https://github.com/doxygen/doxygen/files/4778039/zip.zip)

**Comment by albert-github** [comment]
This file is very informative though there are still some includes missing:
- `@INCLUDE = mc_HtmlConfig.doxcfg`
- `@INCLUDE = mc_LatexConfig.doxcfg`
- `@INCLUDE = mc_warning_config.doxcfg`

and another setting that could not be fulfilled:
- `@INCLUDE_PATH = $(CC_WORKING_VIEW)/frdcc_motorcontrol/tex/doxygen/`

though this is for the current problem of no problem as by commenting out these statement I was able to reproduce the problem with a bare doxygen.

Running through the different doxygen configuration settings it looks like the setting of `SUBGROUPING` is the problem, when setting:
```
SUBGROUPING            = NO
```
it looks to me that everything is OK.

- Can you confirm that when setting `SUBGROUPING=NO` solves your problem (best to place this line at the end of `mc_ibuf.doxcfg`?

**Comment by KITTUKRISHNA5** [comment]
No sorry it is not solving my problem 
The problem(relevant structure documentation is missing due to no creation of relevant .tex files) is still exist even after I followed your suggestion keeping SUBGROUPING            = NO at the end of the .doxcfg file

**Comment by albert-github** [comment]
Sorry, looks like I misinterpreted my output, rerun tests, got now the idea that setting
```
EXTRACT_LOCAL_CLASSES  = YES
```
should solve the problem.
