### ISSUE TITLE
Function attributes mistaken for return type in C

### ISSUE THREAD

**Issue by darnir** [doxygen/doxygen#7842]
**Describe the bug**

When a function is declared with a leading attribute, Doxygen treats the attribute as a return type instead and warns about missing documentation

**Expected behavior**
Doxygen should skip the \_\_attribute\_\_() or any such typedefs and read only the return type

**Screenshots**
If useful, add screenshots to help explain your problem.

**To Reproduce**
```
#define VISIBLE __attribute__((__visibility__("default")))

VISIBLE void foo_init(void);
```
This causes Doxygen to report:
> return type of member foo_init is not documented

However, the following code segment works fine:
```
#define VISIBLE __attribute__((__visibility__("default")))

void foo_init(void) VISIBLE;
```

**Version**
1.8.18 on Arch Linux

**Comment by albert-github** [comment]
`__attribute__` is not a standard keyword but a GNU extension and doxygen is not recognizing it as such. You have the "define" is away. See the chapter about "Preprocessing" (https://www.doxygen.nl/manual/preprocessing.html).

I think this problem is usage
