### ISSUE TITLE
Enhancement: Support Python PEP 526

### ISSUE THREAD

**Issue by str55** [doxygen/doxygen#7853]
It would be great if doxygen would support [PEP 526](https://www.python.org/dev/peps/pep-0526/) so that I could easily indicate the type of attributes in my classes. Right now, if I try to do that, it ignores the attribute. This would be very similar to [PEP 484](https://www.python.org/dev/peps/pep-0484/) which is well-supported. 
**Example**
```python
class A(object):
    def __init__(self):
        #this attribute will be ignored by doxygen
        self.my_attribute: str = 'hello world'

    # this method will be nicely formatted by doxygen
    def multiply_by_two(num: float) -> float:
        return (2 * num)
```

**Comment by flit** [comment]
This looks like a duplicate of #7320.

**Comment by str55** [comment]
> This looks like a duplicate of #7320.

Ah yes, I didn't see that when I was looking for this issue. I'll close this one.
