### ISSUE TITLE
Doxygen fails to recognize documentation surrounding #defines

### ISSUE THREAD

**Issue by dherrada** [doxygen/doxygen#7858]
I've got documentation surrounding 2 #define macro definitions. Basically, it recognizes the piece of documentation for the second macro, but it thinks it's for the first, and it recognizes anything after the first define as belonging to the first define, so the second define won't work no matter what I've tried. I've also tried swapping the order of the defines, and the same thing happens, so the first one takes the second one's documentation, and the second one says it isn't defined.

I would expect it to use the documentation ahead of each one and use it for that one.

Adafruit_Thermal.cpp lines:204-216
```

/*!
  @def printDensity
  Printing density, default: 100% (? can go higher, text is darker but fuzzy)
 */
#define printDensity 10

/*!
  @def printBreakTime
  Printing break time. Default: 500 uS
*/
#define printBreakTime 2

```

Output:
```
/home/dherrada/adafruit/arduino_actions/repos/Adafruit-Thermal-Printer-Library/Adafruit_Thermal.cpp:215: warning: Member printBreakTime (macro definition) of file Adafruit_Thermal.cpp is not documented.
```

Files:
[Doxyfile.txt](https://github.com/doxygen/doxygen/files/4793154/Doxyfile.txt) 
I don't have it called Doxyfile.txt, GitHub wouldn't let me upload it with no extension

[Adafruit_Thermal.txt](https://github.com/doxygen/doxygen/files/4793168/Adafruit_Thermal.txt)
Same thing here. Github wouldn't let me upload a .cpp

Doxygen version: `1.8.13`
I also manually built `1.8.19` and it did the same thing

Running on Ubuntu

**Comment by albert-github** [comment]
The output is a bit perturbed by the fact that the `.h` file is not present and we get a lot of lines like:
```
Adafruit_Thermal.cpp:648: warning: documented symbol 'void Adafruit_Thermal::setCharSpacing' was not declared or defined.
```

When placing the defines outside the function `void Adafruit_Thermal::begin` the output is correct.  It looks like it has to with inbody  documentation of the defines (in my opinion a bit strange to have the defines documented for general use when they inside a function).

Note:
> I don't have it called Doxyfile.txt, GitHub wouldn't let me upload it with no extension

That is why I always advise to: have source+configuration file in a tar or zip

**Comment by dherrada** [comment]
@albert-github Hey, sorry about that. Here's the zip.
[thermal_zip.zip](https://github.com/doxygen/doxygen/files/4793542/thermal_zip.zip)

**Comment by dherrada** [comment]
@albert-github Actually, putting them on top of begin worked. Thank you very much!
