### ISSUE TITLE
Functions documented within a macro do not appear in generated HTML

### ISSUE THREAD

**Issue by chrisdembia** [doxygen/doxygen#7887]
**Describe the bug**

Functions documented within a macro do not appear, despite using Doxyfile settings that previously caused such functions to be documented.

With the following input:

Bounds.h:
```cpp
#ifndef BOUNDS_H
#define BOUNDS_H

#define DECLARE_PROPERTY(pname, T, comment)                                 \
    /** @cond */                                                            \
    /** Internal function for <b> pname </b> property.                   */ \
    void hidden_function_##pname();                                         \
    /** @endcond */                                                         \
    /** @name Properties (single-value)                                  */ \
    /** @{                                                               */ \
    /** comment                                                          */ \
    Q_PROPERTY(T, pname)                                                    \
    /** @}                                                               */ \
    /** @name Property-related functions                                 */ \
    /** @{                                                               */ \
    /** Get the value of the <b> pname </b> property.                    */ \
    const T& get_##pname() const;                                           \
    /** @}                                                               */

/** This works fine. */
class BoundsGood {
public:
    /** Constructor.
    Line two. */
    BoundsGood();
    DECLARE_PROPERTY(lower_bound, double, "Value of lower bound.");
    DECLARE_PROPERTY(upper_bound, double, "Value of upper bound.");
};
```

```
# Difference with default Doxyfile 1.8.18
QUIET                  = YES
INPUT                  = Bounds.h
MACRO_EXPANSION        = YES
EXPAND_ONLY_PREDEF     = YES
EXPAND_AS_DEFINED      = DECLARE_PROPERTY
```

**Expected behavior**

I expected the same behavior as in previous versions of Doxygen, including 1.8.18, where the functions within the macro are documented.

**Screenshots**

**Expected** (doxygen 1.8.18):
<img width="328" alt="image" src="https://user-images.githubusercontent.com/846001/86160129-2aa27b00-bac0-11ea-94ba-b3a2db207774.png">

---
**Actual** (doxygen master 3e9d9386950cc67d155a920cf8483c4d5bdcec3c):
<img width="335" alt="image" src="https://user-images.githubusercontent.com/846001/86160169-3beb8780-bac0-11ea-8fb2-5064e4512ea6.png">

**To Reproduce**
[doxygen_bug_macrodocs.zip](https://github.com/doxygen/doxygen/files/4853659/doxygen_bug_macrodocs.zip)

**Version**
1.8.19 (3e9d9386950cc67d155a920cf8483c4d5bdcec3c) macOS Catalina 10.15.5.

**Comment by albert-github** [comment]
The issue looks like to be introduced with the patch #7742 (for the issue #7734):

I did some further research and it look to me that the syntax as used:
```
Q_PROPERTY(T, pname) 
```
is not correct, according to the Qt documentation (https://doc.qt.io/archives/qt-4.8/properties.html, ) it should be:

> Q_PROPERTY(type name
>            (READ getFunction [WRITE setFunction] |
>             MEMBER memberName [(READ getFunction | WRITE setFunction)])
>            [RESET resetFunction]
>            [NOTIFY notifySignal]
>            [REVISION int]
>            [DESIGNABLE bool]
>            [SCRIPTABLE bool]
>            [STORED bool]
>            [USER bool]
>            [CONSTANT]
>            [FINAL])

Qt5 documentation (https://doc.qt.io/qt-5/properties.html):
> Q_PROPERTY(type name
>            (READ getFunction [WRITE setFunction] |
>             MEMBER memberName [(READ getFunction | WRITE setFunction)])
>            [RESET resetFunction]
>            [NOTIFY notifySignal]
>            [REVISION int]
>            [DESIGNABLE bool]
>            [SCRIPTABLE bool]
>            [STORED bool]
>            [USER bool]
>            [CONSTANT]
>            [FINAL])
>            [REQUIRED]

and for Qt3 (https://doc.qt.io/archives/3.3/properties.html):

> Q_PROPERTY( type name READ getFunction [WRITE setFunction]
>             [RESET resetFunction] [DESIGNABLE bool] 
>             [SCRIPTABLE bool] [STORED bool] )
> 

so at least something like:
```
Q_PROPERTY(T pname READ get_fie) 
```
so without the `,` and with `READ ....`.

I don't know why Qt doesn't flag the problem during compilation (might be due to the fact that some data is lost during the creation of the issue, but this is just a wild guess), but as far as I can see the presented issue is an usage problem.

**Comment by chrisdembia** [comment]
Ah! Thank you :). Using the `Q_PROPERTY(T pname READ get_fie)` syntax fixes the issue.

> I don't know why Qt doesn't flag the problem during compilation (might be due to the fact that some data is lost during the creation of the issue, but this is just a wild guess), but as far as I can see the presented issue is an usage problem.

I'm not actually using Qt; I'm just leveraging the macro to obtain the desired documentation.

**Comment by pedestrianlove** [comment]
I have a similar problem with 1.8.18 too.
Given a header file:
```c
/** @file
 * Error codes and functions for detecting and assessing them.
 */

/**
 * A macro to implement error id enum and error string array.
 */
#define FOREACH_ERROR(ERROR)	\
/**@def FOREACH_ERROR(ERROR)
 * @par This one is from the upper part:
 * A provided network address was not valid.
 *
 * This might be a formatting problem, or it might mean that a DNS lookup failed.
 */\
  ERROR(STUMPLESS_ADDRESS_FAILURE, 0)	\
/** A required function parameter was NULL or empty. */\
  ERROR(STUMPLESS_ARGUMENT_EMPTY, 1)	\
/** A provided argument was too big, for example, to fit into a buffer target. */\
  ERROR(STUMPLESS_ARGUMENT_TOO_BIG, 2)	\
/**
 * A duplicate of an already existing element was detected in an entry.
 *
 * @since release v1.6.0.
 */\
  ERROR(STUMPLESS_DUPLICATE_ELEMENT, 3)	\
/**
 * No element with the specified characteristics was found.
 *
 * @since release v1.6.0.
 */\
  ERROR(STUMPLESS_ELEMENT_NOT_FOUND, 4)	\
/** Could not open a file. */\
  ERROR(STUMPLESS_FILE_OPEN_FAILURE, 5)	\
/** Could not write to a file. */\
  ERROR(STUMPLESS_FILE_WRITE_FAILURE, 6)	\
/** A provided index was not in a valid range. */\
  ERROR(STUMPLESS_INDEX_OUT_OF_BOUNDS, 7)	\
/** A provided facility code did not conform to RFC 5424. */\
  ERROR(STUMPLESS_INVALID_FACILITY, 8)	\
/** A target or entry ID was not valid. */\
  ERROR(STUMPLESS_INVALID_ID, 9)	\
/**
 * A provided severity code did not conform to RFC 5424.
 *
 * @since release v1.6.0.
 */\
  ERROR(STUMPLESS_INVALID_SEVERITY, 10)	\
/** A memory allocation or reallocation failed. */\
  ERROR(STUMPLESS_MEMORY_ALLOCATION_FAILURE, 11)	\
/** The given layer 3 protocol is not supported by this implementation. */\
  ERROR(STUMPLESS_NETWORK_PROTOCOL_UNSUPPORTED, 12)	\
/**
 * No param with the specified characteristics was found.
 *
 * @since release v1.6.0.
 */\
  ERROR(STUMPLESS_PARAM_NOT_FOUND, 13)	\
/** Could not bind to a socket. */\
  ERROR(STUMPLESS_SOCKET_BIND_FAILURE, 14)	\
/** Could not connect to a socket. */\
  ERROR(STUMPLESS_SOCKET_CONNECT_FAILURE, 15)	\
/** Could not create a socket. */\
  ERROR(STUMPLESS_SOCKET_FAILURE, 16)	\
/** Could not send to a socket. */\
  ERROR(STUMPLESS_SOCKET_SEND_FAILURE, 17)	\
/** Could not write to a stream. */\
  ERROR(STUMPLESS_STREAM_WRITE_FAILURE, 18)	\
/** The requested operation is not valid on the given target type. */\
  ERROR(STUMPLESS_TARGET_INCOMPATIBLE, 19)	\
/** The target type provided is unsupported by this implementation. */\
  ERROR(STUMPLESS_TARGET_UNSUPPORTED, 20)	\
/** The given layer 4 protocol is not supported by this implementation. */\
  ERROR(STUMPLESS_TRANSPORT_PROTOCOL_UNSUPPORTED, 21)	\
/** Could not close the Windows Event Log. */\
  ERROR(STUMPLESS_WINDOWS_EVENT_LOG_CLOSE_FAILURE, 22)	\
/** Could not open the Windows Event Log. */\
  ERROR(STUMPLESS_WINDOWS_EVENT_LOG_OPEN_FAILURE, 23)	\

#define GENERATE_ENUM(ENUM, INDEX) ENUM = INDEX,
#define GENERATE_STRING(STRING, INDEX) #STRING,

/**
 * An (enum) identifier of the types of errors that might be encountered.
 *
 * Note that the same error may be encountered in different contexts with a
 * different ultimate cause. To completely diagnose a problem, you will need
 * to look at more than just the error id.
 *
 * @note The real implementation of enum values is now moved under `FOREACH_ERROR(ERROR)` macro.
 */
enum stumpless_error_id {
  /**@enum stumpless_error_id
   * BLAH BLAH BLAH */
  FOREACH_ERROR(GENERATE_ENUM)
};
 

/**@def FOREACH_ERROR(ERROR)
 * @par This one is from bottom:
 * A provided network address was not valid.
 *
 * This might be a formatting problem, or it might mean that a DNS lookup failed.
 */

```
![image](https://user-images.githubusercontent.com/37164678/88862951-26d75500-d234-11ea-9509-de30d2959f06.png)

You can see that most of the comments within the macro have been lost.

Is there any workaround with this one now?

**Comment by pedestrianlove** [comment]
Plus, if you delete the items to only 10(0-9) in the macro, like this:
```c
/** @file
 * A testing file.
 */

/**@def FOREACH_ERROR(ERROR)
 * Comments above the definition.
 */
#define FOREACH_ERROR(ERROR)	\
/**@def FOREACH_ERROR(ERROR)
 * @par This one is from the upper part:
 * Upper part test.
 */\
  ERROR(STUMPLESS_ADDRESS_FAILURE, 0)	\
/** A required function parameter was NULL or empty. */\
  ERROR(STUMPLESS_ARGUMENT_EMPTY, 1)	\
/** A provided argument was too big, for example, to fit into a buffer target. */\
  ERROR(STUMPLESS_ARGUMENT_TOO_BIG, 2)	\
/**
 * A duplicate of an already existing element was detected in an entry.
 *
 * @since release v1.6.0.
 */\
  ERROR(STUMPLESS_DUPLICATE_ELEMENT, 3)	\
/**
 * No element with the specified characteristics was found.
 *
 * @since release v1.6.0.
 */\
  ERROR(STUMPLESS_ELEMENT_NOT_FOUND, 4)	\
/** Could not open a file. */\
  ERROR(STUMPLESS_FILE_OPEN_FAILURE, 5)	\
/** Could not write to a file. */\
  ERROR(STUMPLESS_FILE_WRITE_FAILURE, 6)	\
/** A provided index was not in a valid range. */\
  ERROR(STUMPLESS_INDEX_OUT_OF_BOUNDS, 7)	\
/** A provided facility code did not conform to RFC 5424. */\
  ERROR(STUMPLESS_INVALID_FACILITY, 8)	\

#define GENERATE_ENUM(ENUM, INDEX) ENUM = INDEX,
#define GENERATE_STRING(STRING, INDEX) #STRING,


/**@def FOREACH_ERROR(ERROR)
 * @par This one is from the end of file:
 * A test from bottom.
 */
```
You will see:
![image](https://user-images.githubusercontent.com/37164678/88864957-15dd1280-d239-11ea-85b4-b54ddd31467a.png)

which is weird.

**Comment by doxygen** [comment]
@pedestrianlove Can you attach a self-contained example that allows us to reproduce the problem? Please also mention what "weird" means to you (i.e. what did you expect?). And if the very same code worked before, please mention the version of doxygen that you used.

**Comment by pedestrianlove** [comment]
@doxygen Ok, I added the required details into my comments.

You should be able to reproduce these 2 problems with the config below:
[Doxyfile.txt](https://github.com/doxygen/doxygen/files/5001606/Doxyfile.txt)


the header file in case you need it(the second case version):
[error.txt](https://github.com/doxygen/doxygen/files/5001601/error.txt)

The version I'm using and where these problems occur is 1.8.18.

**Comment by doxygen** [comment]
@pedestrianlove and to track when this was introduced it helps to known for which version of doxygen this worked correctly. Can you add that as well?

**Comment by pedestrianlove** [comment]
@doxygen  Sorry, I do not know whether this worked before. I just looked at the documentation and it didn't say that this shouldn't work(at least I haven't seen), so I decided to file this as a possible bug.

**Comment by pedestrianlove** [comment]
@doxygen Update, after I turned on the macro expansion option, it worked like a charm. So no more problem on my side now.
