### ISSUE TITLE
Macro Expansion broken

### ISSUE THREAD

**Issue by eseiler** [doxygen/doxygen#7890]
Hey doxygen team,

there were some issues related to macros in the last few days, but they didn't seem to be applicable to this case.
Sorry, if this was already reported!

**Describe the bug**
Predefined macros do not get extended any more.

**Expected behavior**
Predefined macros should get extended :)

**Screenshots**
Before:
![old_doxygen](https://user-images.githubusercontent.com/12967715/86270524-a89f7880-bbcb-11ea-89ab-d563405826ea.png)

After:
![doxygen_new](https://user-images.githubusercontent.com/12967715/86270539-ad642c80-bbcb-11ea-8eec-51c7ba31b62f.png)

**To Reproduce**
[example.tar.gz](https://github.com/doxygen/doxygen/files/4859216/example.tar.gz)

The difference to the default Doxyfile:
```
ENABLE_PREPROCESSING   = YES
MACRO_EXPANSION        = YES
EXPAND_ONLY_PREDEF     = YES
PREDEFINED             = "DOXYGEN_ONLY(x)= x"
```

The source:
```cpp
//!\brief This is a struct.
struct S
{
    //!\brief Documentation for doxygen.
    DOXYGEN_ONLY(int some_function() {});
}
```

**Version**
Works with d5916c06fba9667911a19cf658e7c5ab54daf72c
Broken with 3e9d9386950cc67d155a920cf8483c4d5bdcec3c
Commits in between did not compile for me

**Additional context**
Our actual use case is to document constructors/functions that are inherited from a CRTP base class.
E.g. [Example 1](https://github.com/seqan/seqan3/blob/8c2d524207be3ff8029801551e78c8a5b0fa0777/include/seqan3/alphabet/quality/qualified.hpp#L92-L99) resulting in [this documentation](https://docs.seqan.de/seqan/3-master-dev/classseqan3_1_1qualified.html#ad334b36ce356cd359a2d9eafa2787059) 
Or
[Example 2](https://github.com/seqan/seqan3/blob/8c2d524207be3ff8029801551e78c8a5b0fa0777/include/seqan3/alignment/matrix/detail/two_dimensional_matrix_iterator_base.hpp#L182) resulting in [this documentation](https://docs.seqan.de/seqan/3-master-dev/classseqan3_1_1detail_1_1two__dimensional__matrix__iterator__base.html#a963b094ebcf72fde897c422bd098c6f1).

**Comment by eseiler** [comment]
Another (and easier) use case is 

```cpp
//!\brief This is a struct.
struct S
{
    #if DOXYGEN_ONLY(1)0
    //!\brief Documentation for doxygen.
    int some_function() {}
    #endif
}
```

Results in properly documented function in https://github.com/doxygen/doxygen/commit/d5916c06fba9667911a19cf658e7c5ab54daf72c
and no documented function in https://github.com/doxygen/doxygen/commit/3e9d9386950cc67d155a920cf8483c4d5bdcec3c

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7891 

Note: I didn't get the syntax: `#if DOXYGEN_ONLY(1)0` unless this should expand to `10` with the given setup.

Note: also the CGAL project had problems that are solved now.

**Comment by eseiler** [comment]
> I've just pushed a proposed patch, pull request #7891
> 
> Note: I didn't get the syntax: `#if DOXYGEN_ONLY(1)0` unless this should expand to `10` with the given setup.
> 
> Note: also the CGAL project had problems that are solved now.

Thank you for the fix, works perfectly!

As for the example,
for our code base we define
```
#ifndef DOXYGEN_ONLY
#define DOXYGEN_ONLY(x)
#endif
```
-> the macro extends to nothing.

For doxygen, we define
```
DOXYGEN_ONLY(x)= x
```
-> just expand to write the arguments passed to the macro.

---

```cpp
//!\brief This is a struct.
struct S
{
    #if DOXYGEN_ONLY(1)0
    //!\brief Documentation for doxygen.
    void some_function() {}
    #endif
}
```

When compiling, it will expand to `#if 0`, so the block is thrown out.
When building documentation, it will expand to `#if 10` == `#if 1`, so doxygen will consider the code.

**Comment by albert-github** [comment]
Nice trick though wouldn't a `#ifdef` or `#ifndef` be better understandable?

**Comment by albert-github** [comment]
Code has been integrated in master on github (closing issue as it only occurred in the master version).

**Comment by eseiler** [comment]
> Nice trick though wouldn't a `#ifdef` or `#ifndef` be better understandable?

For this specific example, yes; but you can also use the macro to name and document a variable that is not used in the function (happens sometimes within base clases, where you just want to `//!\copydoc` the documentation in the derived class).

```cpp
/*!\brief A function.
 * \param a_string A very useful parameter that is used in the definition of the derived class.
 */
void some_function(std::string const & DOXYGEN_ONLY(a_string))
{}
```
