### ISSUE TITLE
Incorrect search box on server-side search results page

### ISSUE THREAD

**Issue by tttapa** [doxygen/doxygen#7892]
**Describe the bug**  
When `SERVER_BASED_SEARCH = YES`, a second, non-working search field appears on the HTML page with the search results. The style also looks out of place.

**Expected behavior**  
A single, working search field.

**Screenshots**  
![old-server-results](https://user-images.githubusercontent.com/21296729/86408507-68b5bf80-bcb7-11ea-8b77-468cc7f8e321.png)

**To Reproduce**  
1. `doxygen -g`
2. Set `SERVER_BASED_SEARCH = YES`
3. `doxygen`
4. Start PHP+web server, hosting the `html` folder generated by Doxygen
5. Open the hosted web page in the browser and search for a keyword using the search bar in the top right
6. Observe the second search field on the search results page

Full output and Docker-Compose file for server attached:  
[**Doxygen-7891.zip**](https://github.com/doxygen/doxygen/files/4866642/Doxygen-7891.zip)

**Version**  
Doxygen cfda7da009ca4ca094946ac090bc493f8ac43351 (compiled from source), Ubuntu 20.04

***

HTML of the two search boxes:
```html
<div id="top">
    <!-- scripts and title removed -->
    <div id="main-nav">
        <ul class="sm sm-dox" id="main-menu" data-smartmenus-id="15937231311479534">
            <!-- Other menu buttons removed -->
            <li style="float:right">
                <div id="MSearchBox" class="MSearchBoxInactive">
                    <div class="left">
                        <form id="FSearchBox" action="search.php" method="get"><img id="MSearchSelect"
                                src="search/mag.png" alt=""><input type="text" id="MSearchField" name="query"
                                value="Search" size="20" accesskey="S" onfocus="searchBox.OnSearchFieldFocus(true)"
                                onblur="searchBox.OnSearchFieldFocus(false)"></form>
                    </div>
                    <div class="right"></div>
                </div>
            </li>
        </ul>
    </div>
    <input type="text" id="MSearchField" name="query" value="Class" size="20" accesskey="S"
        onfocus="searchBox.OnSearchFieldFocus(true)" onblur="searchBox.OnSearchFieldFocus(false)">

</div>
```
Apart from the default value, the two search boxes are identical, they even share an ID, which shouldn't happen.

***

I don't use the server-side search myself, so it's not really an issue for me personally. I came across it while testing my changes in #7888.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.19.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
