### ISSUE TITLE
propably the TCL parser - in Release_1_8_18-213-gc545a3d4

### ISSUE THREAD

**Issue by aotto1968** [doxygen/doxygen#7909]

**Comment by albert-github** [comment]
Some notes:

- which version of doxygen are you talking about?
   - By means of commit 58ea5cf the support for TCL has been removed from doxygen. And is thus not present in the released version of doxygen anymore
   - the ID c545a3d4 is unknown to me
- there is no information present anymore in the issue (why did you edit out the, incomplete, stack trace)

- when a crash like this appears doxygen has no possibility to tell anymore where it crashed, but the assumption of the tcl parser looks valid. It looks like some code is included in writing out the HTML documentation. Some information can be obtained from the console messages (unless you set `QUIET=YES`) about where doxygen is in the process.
