### ISSUE TITLE
Doxygen Treats C# Inline-Bodied Properties as Member Variables

### ISSUE THREAD

**Issue by justin-millman** [doxygen/doxygen#7914]
**Describe the bug**
C# allows you to implement a read-only property with the `=>` inline syntax; for example,
```csharp
namespace Example {
    public class Foo {
        public int Property => 10;
    }
}
```
This is equivalent to
```csharp
namespace Example {
    public class Foo {
        public int Property { get { return 10; } }
    }
}
```
but can be more concise in certain situations. Doxygen misparses properties of this form as member variables and renders them as such, rather than as properties with only a getter.

**Expected behavior**
Doxygen should recognize this syntax as a read-only property and generate documentation equivalent to that which is generates in the equivalence shown above.

**Version**
Doxygen version 1.8.18 (commit hash a1b07ad0e92e4526c9ba1711d39f06b58c2a7459) on a Windows 10 machine

**Additional context**
I wrote myself a short Python script to serve as a `.cs` filter for Doxygen. It finds these properties and replaces them with the getter-only equivalence, which allows me to get the output I desire. I don't know if the regular expression I generated is truly exhaustive or if there are any false-positives, but so far I haven't had any issues. I've attached the Python script here (as a `LOG` file to satisfy GitHub).

[ReadonlyPropertyFilter.log](https://github.com/doxygen/doxygen/files/4944081/ReadonlyPropertyFilter.log)

**Comment by justin-millman** [comment]
Here is a minimal example using a default-generated Doxyfile. The relevant content can all be found at `Example/Example`.

[Example.tar.gz](https://github.com/doxygen/doxygen/files/4944117/Example.tar.gz)

**Comment by justin-millman** [comment]
This is a duplicate of #7550, #6278, and #6064. Apologies for that . . . but I do think this should be fixed.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7991
