### ISSUE TITLE
How to enhance the memory limits for tex documentation to generate a larger PDF file

### ISSUE THREAD

**Issue by KITTUKRISHNA5** [doxygen/doxygen#7915]
I am using Doxygen version 1.8.11 and  pdfTeX, Version 3.1415926-2.3-1.40.12 (MiKTeX 2.9) (preloaded format=pdflatex 2012.5.23)

I tried generating a pdf document using some code annotations inside .c and .h files and from a .tex file

my .tex file seems to have a problem with the huge content (many number of equations and .jpg files,which need to be shown in the final generated pdf file) and it is causing an error 

<fig/y01.pdf, id=4, 361.35pt x 252.945pt> <use fig/y01.pdf>
Z:\frdcc_motorcontrol\tex\mcs_limitintq\mcs_limitintq.tex:86: TeX capacity exce
eded, sorry [input stack size=5000]
Z:\frdcc_motorcontrol\tex\mcs_limitintq\mcs_limitintq.tex:86:  ==> Fatal error
occurred, no output PDF file produced!
Transcript written on mcs_limitintq.log.

To fix this what I need to do which files I need to modify without compromising with the huge data.

Could you please help me with this how to fix and I found online some steps to fix but I don't know how to fix this really 
NOTE: As I am sure there is no problem with the syntax and this is due to larger content I am not sharing any files here.

Thank you .

**Comment by albert-github** [comment]
The problem you mention is not a doxygen problem but a limitation of your LateX  installation. Searching for e.g. "TeX capacity exceeded, sorry" will give you some pointers how to increase the stack size.

Furthermore the mentioned versions of doxygen 1.8.11 (December 2015) and MiKTeX Version 3.1415926-2.3-1.40.12 (from 2012) are a bit old. The current version of e.g. doxygen is 1.8.18. Advise it to upgrade also the doxygen and MiKTeX versions.

**Comment by KITTUKRISHNA5** [comment]
Thank you for the reply
