### ISSUE TITLE
Question about Comments

### ISSUE THREAD

**Issue by heartacker** [doxygen/doxygen#7928]
hi, doxy,
I have a question about the comments because of [https://github.com/microsoft/vscode-cpptools/issues/5836](https://github.com/microsoft/vscode-cpptools/issues/5836)

Is it standard to follow a colon `:` after a parameter?
like:
```c
/*!
* @brief UART uninitialize
*
* @param[in] UARTx: UART type pointer, x value can be 0 to 2
*                         - UART0
*                         - UART1
*                         - UART2
* @return none
*/
void UART_DeInit(UART_Type *UARTx)
{
    DEVICE_ASSERT(IS_UART_PERIPH(UARTx));

}
```
it seem that it‘s also ok.
![image](https://user-images.githubusercontent.com/1876302/88663206-c8b05200-d10d-11ea-8144-b2d8e21e00a5.png)

thanks

**Comment by albert-github** [comment]
No this is, in my opinion, not standard.

**Comment by doxygen** [comment]
Indeed it is not needed or standard, but because some people have a tendency to add a colon after the parameter name doxygen accepts this notation as well (and doesn't put the colon in the documentation).

**Comment by heartacker** [comment]
> Indeed it is not needed or standard, but because some people have a tendency to add a colon after the parameter name doxygen accepts this notation as well (and doesn't put the colon in the documentation).

Thank you for your answer. some people use a colon instead of a space. This may cause some additional problems.
