### ISSUE TITLE
Custom command does not render correctly in HTML

### ISSUE THREAD

**Issue by diegodiasm** [doxygen/doxygen#7929]
The following definition of `\includefile` used to render correctly in HTML with doxygen 1.8.13 but it does not render correctly with the doxygen 1.8.18 release (I had already noticed this issue in the 1.8.16 release, but I didn't open an issue at the time). Any idea what might be causing the issue?

```
ALIASES = "caprights{1}=\pre requires capability rights: {\1}" \
          "includefile{1}=\par Include File\n \code #include <\1> \endcode" \
          "utcb{1}=\param \1  UTCB to be used for this operation, usually the UTCB of the calling thread."
```

Here is a screenshot of the output with **doxygen 1.8.13**
![doxygen-13](https://user-images.githubusercontent.com/10603456/88796555-255d4c80-d1a2-11ea-9b73-d802997726f7.png)

Here is a screenshot of the output with **doxygen 1.8.18**
![doxygen-18](https://user-images.githubusercontent.com/10603456/88796567-2bebc400-d1a2-11ea-9796-f26cddd9e956.png)

Here are the path to the doxygen configuration file and header using the custom command `\includefile`:

https://github.com/kernkonzept/l4re-core/blob/master/l4sys/include/scheduler.h
https://github.com/kernkonzept/mk/blob/master/doc/source/l4re.cfg

I am not aware of other configuration files which might be relevant to reproduce this issue. I can provide more details on request.

**Comment by albert-github** [comment]
- Please don't use external references as they might not persistent (the ones you gave to github are not persistent as they are part of a project for which stil changes take place), so can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?

**Comment by albert-github** [comment]
I did some quick investigations as I saw that in the `ALIASES` the usage of `\n` which was possible in older versions of doxygen but changes as of version 1.8.14. You have to use `^^` in `ALIASES` in case you want to insert a new line (Note: the documentation is mentioning the `^^` but the complete text is not 100% correct, this has been corrected in the master version).

You will also have gotten some warnings like:
```
warning: Illegal command \n as part of a title section
warning: Illegal command @code as part of a title section
warning: Illegal command \endcode as part of a title section
```

So I see the problem you have as usage.

**Comment by diegodiasm** [comment]
The use of ^^ instead of \n in the aliases definition solves the problem. I just looked the updated documentation `doc/custcmd.doc` and the the change from 'can' to 'cannot' should prevent other users from having the same issue.
I will therefore close the issue.

Thanks! :-)
