### ISSUE TITLE
why is the \parsedate error in Tex build 

### ISSUE THREAD

**Issue by KITTUKRISHNA5** [doxygen/doxygen#7930]
I tried using OMAKE to build my tex files when i do that i got below error usually when i run them alone the execution is running fine but when i made the makefile part of my OMAKE build i am getting this error :

**_U:/frdcc_motorcontrol/project/psm_mk/tex/mc_calc_max_torque/mc_calc_max_torque.
tex:20: Argument of \parsedate has an extra }
?
Runaway argument?
\empty
U:/frdcc_motorcontrol/project/psm_mk/tex/mc_calc_max_torque/mc_calc_max_torque.
tex:20: Paragraph ended before \parsedate was complete_**

could you please give me a little insight on this, Actually i tried to give you more details but i cannot trace why exactly this happening.
[new 1.txt](https://github.com/doxygen/doxygen/files/4994987/new.1.txt)

**Comment by albert-github** [comment]
What happens when you run just make in the latex directory?

**Comment by KITTUKRISHNA5** [comment]
What happens when you run just make in the latex directory generated by doxygen?:: It runs i have attached the log file for you
Which tex version :::  3.1415926-2.3-1.40.12 (MiKTeX 2.9) (preloaded format=pdflatex 2012.5.23)  30 JUL 2020 11:15
entering extended mode
which doxygen version::: 1.8.11
what is omake?::: It is a clear case tool to build 

I actually using a older version but there is a compliance from the management to use these versions. And if my problem is unknown and irrelevant you can close the issue
Thanks for your timely support whenever in need.
[cc_omake.pdf](https://github.com/doxygen/doxygen/files/4999115/cc_omake.pdf)

[log.txt](https://github.com/doxygen/doxygen/files/4999112/log.txt)

**Comment by albert-github** [comment]
On:
> What happens when you run just make in the latex directory generated by doxygen?

you state:
> It runs i have attached the log file for you

Though when looking into the log file I see only errors like:
> 'pdflatex' is not recognized as an internal or external command,
operable program or batch file.

So it looks like something is wrong with your PATH, i.e. the the LaTeX distribution (in this case MiKTeX cannot be found).

**Comment by albert-github** [comment]
As the word `parsedate` is in the doxygen source code of the 1.8.11 version of doxygen  and no further information is provided (small source example showing the problem), the only assumption that can be made is that the `parsedate` is injected locally by a local header / footer or a `\latexonly` command.

I think this problem can be set to incomplete
