### ISSUE TITLE
syntax error on conditional directive spanning multiple lines (can't reopen #3824, but it's the same)

### ISSUE THREAD

**Issue by doxyusingmaik** [doxygen/doxygen#7931]
**Problem**
with doxygen 1.8.13 the following part of /usr/include/string.h can/will cause error
"/usr/include/string.h:164: warning: preprocessing issue while doing constant expression evaluation: syntax error"

_____________________ cut _______________________
#if (defined __USE_XOPEN_EXTENDED || defined __USE_XOPEN2K8 
|| __GLIBC_USE (LIB_EXT2))
_____________________ cut _______________________

**Expected behavior**
Preprocessor Statements split over multiple lines by using '\' symbol shall always be handled as if written in a single line

**To Reproduce**
// will be added soon, I'm on the wrong terminal now. Please give me some hours. //

**Version**
$ doxygen --version
1.8.13

$lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

**Additional context**
Can not see, why this only happens to some computers. All have
doxygen -v
"1.8.13"
"gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)"
and "build-essential/bionic,now 12.4ubuntu1 amd64 [installed]"
all using the same doxy project setup with
ENABLE_PREPROCESSING = YES
PREDEFINED = DOXYGEN_SHOULD_SKIP_THIS
MACRO_EXPANSION = YES
EXPAND_ONLY_PREDEF = YES
EXCLUDE_PATTERNS = /export/

**Comment by doxygen** [comment]
Without line continuation the example you provided is not valid for the C preprocessor.

My compiler will say:
```c
test.cpp:1:60: error: expected ')' in preprocessor expression
#if (defined __USE_XOPEN_EXTENDED || defined __USE_XOPEN2K8
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
```
If I turn it into a more complete example like this:

```c
/** @file */

#define __GLIBC_USE(x) 1
#if (defined __USE_XOPEN_EXTENDED || defined __USE_XOPEN2K8 \
|| __GLIBC_USE (LIB_EXT2))

/** a function */
void foo();

#endif
```
then both the compiler and doxygen have no problem.

**Comment by doxyusingmaik** [comment]
Hi Dimitri,
please excuse me, the Wiki markup eat up a character of my former text two times. I see, this did completely mislead you. I'm sorry! It's my mistake (and my crazy edge browser of corporate terminal, incapable of showing the "Preview" of github wiki). I intentionally got no Internet access on the Linux machines :-(.

The expected behaviour statement should read:
"Preprocessor Statements split over multiple lines by using BACKSLASH symbol shall always be handled as if written in a single line."

The content of the problematic string.h I posted, has been a bit too short and also got the backslah eaten. Should read (hope the markup will keep the BACKSLASH after __USE_XOPEN2K8) now:
`
#if (defined __USE_XOPEN_EXTENDED || defined __USE_XOPEN2K8	\
     || __GLIBC_USE (LIB_EXT2))
/* Duplicate S, returning an identical malloc'd string.  */
extern char *strdup (const char *__s)
     __THROW __attribute_malloc__ __nonnull ((1));
#endif
`
It's from the original GNU/Linux source files. No chance to finally change it, because it's used on a bunch of build systems too.

Hexdump of this region is showing the correct continuation (5c  0a):
`
00001710  29 3b 0a 23 65 6e 64 69  66 0a 0a 23 69 66 20 28  |);.#endif..#if (|
00001720  64 65 66 69 6e 65 64 20  5f 5f 55 53 45 5f 58 4f  |defined __USE_XO|
00001730  50 45 4e 5f 45 58 54 45  4e 44 45 44 20 7c 7c 20  |PEN_EXTENDED || |
00001740  64 65 66 69 6e 65 64 20  5f 5f 55 53 45 5f 58 4f  |defined __USE_XO|
00001750  50 45 4e 32 4b 38 09 5c  0a 20 20 20 20 20 7c 7c  |PEN2K8.\.     |||
00001760  20 5f 5f 47 4c 49 42 43  5f 55 53 45 20 28 4c 49  | __GLIBC_USE (LI|
00001770  42 5f 45 58 54 32 29 29  0a 2f 2a 20 44 75 70 6c  |B_EXT2))./* Dupl|
00001780  69 63 61 74 65 20 53 2c  20 72 65 74 75 72 6e 69  |icate S, returni|
00001790  6e 67 20 61 6e 20 69 64  65 6e 74 69 63 61 6c 20  |ng an identical |
000017a0  6d 61 6c 6c 6f 63 27 64  20 73 74 72 69 6e 67 2e  |malloc'd string.|
000017b0  20 20 2a 2f 0a 65 78 74  65 72 6e 20 63 68 61 72  |  */.extern char|
000017c0  20 2a 73 74 72 64 75 70  20 28 63 6f 6e 73 74 20  | *strdup (const |
000017d0  63 68 61 72 20 2a 5f 5f  73 29 0a 20 20 20 20 20  |char *__s).     |
000017e0  5f 5f 54 48 52 4f 57 20  5f 5f 61 74 74 72 69 62  |__THROW __attrib|
000017f0  75 74 65 5f 6d 61 6c 6c  6f 63 5f 5f 20 5f 5f 6e  |ute_malloc__ __n|
00001800  6f 6e 6e 75 6c 6c 20 28  28 31 29 29 3b 0a 23 65  |onnull ((1));.#e|
00001810  6e 64 69 66 0a 0a 2f 2a  20 52 65 74 75 72 6e 20  |ndif../* Return |
`
Btw, this is the 1st occurence of a line continuation in a macro in this file.

Aside this, your answer is pointing me to a fault in my workaround test. This better should be:
PREDEFINED = __GLIBC_USE(x)=1
... hopefully tested ... 
no, still throws the same error message on my computers.

From your answer, I understand, doxygen should indeed work with this kind of continued statements. While I'm trying to prepare a stripped-down sample, **could you please advice me**, which tool or component could cause my observation? Some terminal setting or global config file?
There could/must be such, because one computer is doing fine, while two others showing the issue. all 3 have exactly the same versions of Ubuntu, doxygen, latex, gcc, build-essential packages.

I will continue the stripped-down proof on thursday.

**Comment by doxyusingmaik** [comment]
The more I try to focus on the root cause, the more I come to the idea, perhaps the error message is only a result of a former problem somewhere else in the parsed source files.

@Dimitri, could you imagine the message "warning: preprocessing issue while doing constant expression evaluation: syntax error" is also thrown if, i.e. an @endcond or curly brace is missing or similar? Should I better focus on those?

My real project is using a meta make system and the sources are multiple MB each file, thus the strip-down is not done within two hours. I underestimated this task a bit. A reproducible example will not be ready before next week :-(
Shall I better close this issue until I can offer an working example? Would be okay for me, if you want it.

Cheers,
Maik

**Comment by doxygen** [comment]
@doxyusingmaik The preprocessor warning you get is only triggered while doxygen's built-in C preprocessor is evaluating an expression (i.e. the part after a `#if`). You can let doxygen dump the result before and after preprocessing using the `-d commentcnv -d preprocessor` options. This might help to track down the problem, i.e. maybe your meta make system produces something strange.
