### ISSUE TITLE
When can we expect the next doxygen release?

### ISSUE THREAD

**Issue by duncan-roe** [doxygen/doxygen#7941]
There are currently 35 *fixed but not released* issues. My particular interest is #7901: if there won't be a release for some time then I could recommend, for [Slackware 15.0](https://www.linuxquestions.org/questions/slackware-14/requests-for-current-14-2-15-0-a-4175620463/), to build man pages for [libnetfilter_queue](https://netfilter.org/projects/libnetfilter_queue/downloads.html) using 1.8.18 even though they look a bit odd.

**Comment by doxygen** [comment]
The new release has arrived!
