### ISSUE TITLE
missing "--" in "section" headline 

### ISSUE THREAD

**Issue by aotto1968** [doxygen/doxygen#7944]
**Describe the bug**
the command:
\section otto command-line: --otto
will be in html:
command-line: –otto

double "--" will l be mapped into "–"

**Expected behavior**
I want to have the "--" because I want to describe a "command-line-option" which start with "--"

**Screenshots**
-> done: If useful, add screenshots to help explain your problem.

**To Reproduce**
-> done Attach a self contained example that allows us to reproduce the problem.
Such an example typically exist of some source code (can be dummy code) and a doxygen configuration file used (you can strip it using `doxygen -s -u`). After you verified the example demonstrates the problem, put it in a zip (or tarball) and attach it to the bug report. Try to avoid linking to external sources, since they might disappear in the future.

**Version**
1.8.19 (c545a3d4865e14b645f3c02301c89a1b59ff83e1)

![bug2](https://user-images.githubusercontent.com/27886664/89335946-fd398600-d698-11ea-80b8-bdce9d5374de.png)
[doxygen_bug2.tar.gz](https://github.com/doxygen/doxygen/files/5024167/doxygen_bug2.tar.gz)

**Comment by albert-github** [comment]
I think this is usage. When using `MARKDOWN_SUPPORT=YES` the `--` is translated into `&ndash;` being the &ndash;
The way to prevent this: use the command `\--`
From the documentation:

> 24.193 \\--
>
> This command writes two dashes (--) to the output. This allows writing two consecutive dashes to the output instead
> of one n-dash character (–).

**Comment by aotto1968** [comment]
This would be to easy. I don't use just plant text, I use a macro to define the "--" argument

```
\subsection  \DocNS{ConfigApiNaming}               CONFIG NAMING DETAILS
\configsection{Name, \--name}
\copydoc \capi{ConfigS::dispname}
```

example "--name" in the macro "configsection"

```
ALIASES             += "configsection{2}=\subsubsection \DocNS{\NSC{\1}} command-line: \2 ^^ \
\b get: \rConfApi{ConfigGet\1,\ConfigGet\1} ^^ \                                                                   
\b set: \rConfApi{ConfigSet\1,\ConfigSet\1} ^^ \
<BR> ^^ \
"
```

the result is still the same.

**Comment by albert-github** [comment]
Backslashes are always a problem.
Did you try either of:
- `\configsection{Name, \\--name}`
- `\configsection{Name, @--name}`

as well?

**Comment by aotto1968** [comment]
ok thanks - you can close this issue - it was the "user" and not the software :-)
