### ISSUE TITLE
Adding tags to refer to currently parsed source file

### ISSUE THREAD

**Issue by thom-sch** [doxygen/doxygen#7963]
I'd like to ask for an enhancement of Doxygen like issue #7946 and perhaps #7945, too.

I'm  working on documenting Delphi source codes using a set of ALIASES;
if you like you can find it under https://sys-thos.de/DelphiDox/

One of the main goals was to have included the Delphi source code snippets
as well as the C++ *.hpp snippets (generated by Delphi for C++ builder).
So most of the ALIASES have a parameter which refers to the
currently parsed source file, as an example ALIAS DClass:

  \DClass{2} with
  - \1 = class name to document
  - \2 = current source file's name

There are some more ALIASES like this, and each of them get the source file's name as parameter.

Things would be much easier if there would be tags as mentioned in #7946 like:
  - __FILENAME__: file name only, with extension
  - __FILE__: file name only, without extension
  - __FILEDIR__: file's directory
  - __FILEPATH__: complete file path

In this case parameter \2 of ALIAS \DClass could be omitted in all ALIASES resulting in better readability
and avoiding to repeat the source file's name in every other ALIAS.

Another thing is the behaviour of special command \dontinclude:

It seems that this is valid only inside the comment block \dontinclude
is present; opening the next comment block another \dontinclude command seems to
be necessary to open the file again.

It would be nice \dontinclude would be valid until the another file shall be
included by \dontinclude.
In my case it would be able to once define the include file via \dontinclude and then 
sequentinally include the mentioned code snippets of the entities as they appears in the source file.

And third an ultimate feature would be the ability of defining source code local
aliases with a new special command

  \alias mylocalalias="...what ever I want..." 🥇 

Regards from Meerbusch
Thomas Schneider

**Comment by albert-github** [comment]
Thanks for the report.

1. Don't link to outside sources (like https://sys-thos.de/DelphiDox/) as they may not be persistent, but include the relevant information in the question (as an attachment). In this case the description that follows looks like to be clear enough. 
2. You mention in your issue 3 requests, please create for each request a separate issue. This is necessary as it is very unlikely that all 3 requests will be handled at the same time and thus it would lead  to only partial solved issues etc.

**Comment by thom-sch** [comment]
Thanks for quick answer - of course you're right, I should have had to split my questions into three issues... 

I think my first request is close to issue #7946 so I'll add it there as an additional comment. Is this ok?

For the others I'll open new issues.

And a note to the external link: It was only mentioned for if you are interested in how I try to document Delphi sources resp. as the reason for my enhancement request.

Regards from Meerbusch
Thomas Schneider

**Comment by albert-github** [comment]
1. Regarding the first issue, yes I think it is much better to add it there as a comment
2. New issues for the other issue, perfect.

**Comment by thom-sch** [comment]
@albert-github : since I've opened new issues for my requests feel free to close this one.

Regards from Meerbusch
Thomas Schneider
