### ISSUE TITLE
Relocatable binaries (--prefix=)

### ISSUE THREAD

**Issue by bmhm** [doxygen/doxygen#7969]
**Describe the bug**

The following command will not work:
`PREFIX=$HOME/.local/apps/doxygen make install --prefix=$HOME/.local/apps/doxygen`

This is useful if the user does not have root access.

**Expected behavior**

make install will install into the dir given with "prefix".

**Screenshots**

n/a

**To Reproduce**

`make install --prefix=$HOME/.local/apps/doxygen`
or
`PREFIX=$HOME/.local/apps/doxygen make install`

**Version**

git master as of 2020-08-19 and any previous version

**Stack trace**

n/a

**Additional context**

* https://www.gnu.org/software/gnulib/manual/html_node/Supporting-Relocation.html
* https://softwareengineering.stackexchange.com/questions/314327/what-is-a-relocatable-binary

**Comment by bmhm** [comment]
Actually, `make DESTDIR=$PWD/installdir install` works just fine.

**Comment by albert-github** [comment]
I myself never used the --prefix / PREFIX so far, but from a quick search in the cmake documentation I found `DESTDIR` (https://cmake.org/cmake/help/v3.18/variable/CMAKE_INSTALL_PREFIX.html), maybe this helps (it does not look 100% optimal to me though)

**Comment by Bagira80** [comment]
While cmaking you need to set `CMAKE_INSTALL_PREFIX` to the location you later want to install to. Then a simple `make install` will install it there.

With the `DESTDIR` mechanism you can prepend another path to the configured install location. (However, it does not replace the configured install prefix!)

(See my comment here: https://github.com/doxygen/doxygen/pull/7992#issuecomment-684829354)

**Comment by Bagira80** [comment]
Maybe this is of interested, too: https://stackoverflow.com/a/11307770/3115457

**Comment by bmhm** [comment]
TY. I can create a PR for the docs if you like. I only do java and bash (mostly) and do not have experience with cmake.

But what I found out: using the strings Viber's there are references to the original install path. I don't think they should be there...

Just using another install dir does not make it relocatable.

**Comment by Bagira80** [comment]
I am sorry, I cannot really follow? (Besides, I am just a normal contributor and not involved with Doxygen.)

What is it that you want to achieve with relocatable binaries?

Normally, I only know the term "relocatable" with memory-locations and being able to run an executable under different memory-locations. This is normally achieved by using the compiler flags [`-fPIC`/`-fpie`](https://gcc.gnu.org/onlinedocs/gcc/Code-Gen-Options.html#Code-Gen-Options). CMake has [options](https://cmake.org/cmake/help/git-master/prop_tgt/POSITION_INDEPENDENT_CODE.html#prop_tgt:POSITION_INDEPENDENT_CODE) for choosing the correct flags, too.

If you however want to build and install Doxygen yourself and to another location than the default one, then you have to set the `CMAKE_INSTALL_PREFIX` option properly while cmaking. `make install` will then install to that location.

If you are a package-maintainer and want to create e.g. Debian packages from the built artifacts then you probably want to use something like `DESTDIR=/tmp/my_package_dir make install` after cmaking. (That is equivalent to installing normally to the directory configured with `CMAKE_INSTALL_PREFIX` and then moving that entire directory, including the prefix, into `/tmp/my_package_dir`.) Then you could do your packaging-magic and create packages from that directory, which will be able to install your build artifacts to the location you configured with `CMAKE_INSTALL_PREFIX` before.

If you are no package-maintainer and still want to create a package that installs your build artifacts at the location configured with `CMAKE_INSTALL_PREFIX`, then you need the fix from #7992 and you can just do `make package` which will give you a single package that you can install.

All these different ways of "installing" Doxygen should leave the [`RUNPATH`/`RPATH`](https://medium.com/@nehckl0/creating-relocatable-linux-executables-by-setting-rpath-with-origin-45de573a2e98) as configured with `CMAKE_INSTALL_PREFIX`. (At least this is valid for Linux. On Windows I do not know how it works.)

I hope that helps.

PS: What do you mean by "strings Viber's"?

**Comment by bmhm** [comment]
I'm mixing up two issues here.

1. Install path, check. Solved. Thanks.

2nd: relocatable binaries, but in the file system. Do they work if I move the binary? If I run `strings doxygen`, it will find strings like `/home/me/git/doxygen/`. 🤔

PS
> using the `strings` binary

Auto correction. German keyboard

**Comment by Bagira80** [comment]
If I run `strings doxygen | grep '/home'` I find several absolute paths to the source-files I used to built Doxygen with. However, that really should not matter except if you are concerned about someone being able to guess who built that binary.

If you move the `doxygen` executable and run `ldd doxygen` you should probably see that all required shared libraries are still found. And running that executable should probably still work.

So in general `doxygen` should be relocatable.

**Comment by bmhm** [comment]
Thanks, then consider this answered!
