### ISSUE TITLE
Configuring Doxygen from the command line as shown in the FAQ no longer works if Doxyfile is too long.

### ISSUE THREAD

**Issue by gsrohde** [doxygen/doxygen#7975]
**Describe the bug**

The example
```
( cat Doxyfile ; echo "PROJECT_NUMBER=1.0" ) | doxygen -
```
no longer works (as of version 1.8.19) if Doxyfile is more than 4096 characters long.

**Expected behavior**

The main HTML page should display "My Project 1.0" at the top, but the number is missing.

**To Reproduce**

Make a Doxyfile with this content:
```
INPUT = ../src/modules.h
OUTPUT_DIRECTORY = minimal
################# (4043 or more of these) ############# 
```
Then (assuming `../src/modules.h` exists) run
```
( cat Doxyfile ; echo "PROJECT_NUMBER=1.0" ) | doxygen -
```
and view `minimal/html/index.html`.

**Version**

I used version 1.8.19 on a Mac that was installed from the DMG file.  Version 1.8.18 works fine.

**Additional context**

If the size of Doxyfile is decreased by 19 characters (so that
```
( cat Doxyfile2 ; echo "PROJECT_NUMBER=1.0" ) | wc -c
```
returns 4096), the output is correct.  If it is decreased by only 18 characters, the number in the header line is truncated to read "My Project 1." (the zero is missing).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.20.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Comment by supriyaKrishnamurthy** [comment]
I am using the latest version but it is not working form me

**Comment by albert-github** [comment]
@supriyaKrishnamurthy probably refer to your issue  #8001. That issue is lacking necessary information and should be added with that issue.
