### ISSUE TITLE
Meta description

### ISSUE THREAD

**Issue by vaind** [doxygen/doxygen#7980]
**Describe the bug**
Is there a way to specify/configure generation of `<meta name="description" content="...">` for each generated page? Looking for this to include a good description to show in search engines.

**Expected behavior**
After the configuration is updated, each page source code would contain the appropriate meta tag (description)

**Comment by albert-github** [comment]
Doxygen has already some meta information in the html pages:
```
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.9.0"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
```
When on wants other `meta`  one has to possibility to define one's own `HTML_HEADER`  and place them in there.

Best is always to give an example (besides a more formal description as you already did) of what your want to have as probably some information should be flexible and other information is more static.

**Comment by vaind** [comment]
Thanks for the quick response. I'm looking for a way to have a unique description for each generated page. It looks like HTML_HEADER is a single file that would be the same across all pages, right?

**Comment by albert-github** [comment]
Partly, there is some flexibility in it like `$title` etc.

**Comment by vaind** [comment]
I'll give it a go and update here if I can get it to work or have some more specific improvement suggestions.

**Comment by albert-github** [comment]
@vaind Is this issue still valid? If so any new insights?

**Comment by vaind** [comment]
Didn't get to try what you suggested, always got higher priority stuff to do. Closing the issue
