### ISSUE TITLE
(Question) Can you modify the color of the dialogue box arrow?

### ISSUE THREAD

**Issue by Makogan** [doxygen/doxygen#7985]
I am customizing the HTML but got stuck trying to modify this arrow:

![image](https://user-images.githubusercontent.com/17284362/91681418-638cb980-eb1c-11ea-9da9-73278a7f8c50.png)

I asked around but other people could not help me either so I came here. Sorry to abuse the issue system to ask a question, I didn't know what else to do.

Doxygen is great! thank you in advance and for the tool.

(I am talking about the big arrow that points up)

**Comment by albert-github** [comment]
A good place to ask questions as well is https://stackoverflow.com/questions/ask.

In the past (a couple of years ago) I've been struggling with the similar problems.

Looks like I added my own `tabs.css` in `HTML_EXTRA_STYLESHEET` with a.o.:
```
.sm-dox a span.sub-arrow, .sm-dox a:hover span.sub-arrow
{
     border-color:blue transparent transparent transparent
}
.sm-dox ul a:hover span.sub-arrow, .sm-dox ul a span.sub-arrow
{
  border-color:transparent transparent transparent green;
}
.sm-dox>li>ul:after
{
  border-color:transparent transparent red transparent
}                                                                             
```

for the example here I made the relevant color 'red' (and blue, green).

**Comment by Makogan** [comment]
Thank you so much, works like a charm!
