### ISSUE TITLE
Can't edit config file from command-line

### ISSUE THREAD

**Issue by supriyaKrishnamurthy** [doxygen/doxygen#8001]
**Describe the bug**
There is no option to edit particular configuration of Doxyfile from windows command line. @doxygen Please help me.Please

**Comment by albert-github** [comment]
What is the exact problem?
How did you create the original doxygen configuration file?

You can use a normal text editor to update a doxygen configuration file.

**Comment by supriyaKrishnamurthy** [comment]
The Doxygen version that I am using is  1.8.20 . I have configured my doxyfile using the Doxygen wizard.  Now I Have requirement to  edit certain options of the Doxyfile through Command line.Assume, the option to create HTML file was initially set to **N0** in doxywizard and I have saved the configuration.Now while running the doxygen through command line I just want to edit that particular option and set it t **Yes** . But I dint find any command in the manual to do that.

Someone in the stackoverflow suggested to try this command to override the existing options in the config file.But it is not working for me
( type Doxyfile & echo PROJECT_NUMBER=1.0 ) | doxygen.exe -

**Comment by albert-github** [comment]
Doxygen has no command line edit commands for the doxygen configuration file. The procedure as specified is correct and works for me on Windows. On *nix type system the meaning of the `type` is a bit different and the command `cat` has to be used. Same accounts for `&` that has to be `&&`.

- what is not working, do you get errors / warnings?
- what is the exact outcome of `doxygen -v` for you
- what is the result for `( type Doxyfile & echo PROJECT_NUMBER=1.0 ) | doxygen.exe -x -`, so with the `-x` option!
- show also the results you got in case you use the `( type Doxyfile & echo PROJECT_NUMBER=1.0 ) | doxygen.exe -` with your settings, but now just the results for `( type Doxyfile & echo PROJECT_NUMBER=1.0 ) | doxygen.exe -x -`

**Comment by thom-sch** [comment]
@supriyaKrishnamurthy 
May be this is a solution for you?:

- create your doxygen configuruation file with doxywizard.exe
- save the file on a location and a nam of your choice, say "doxytemplate.dox"
- create another configuration file "doxyfile" in your project's working directory with the following content:

> @INCLUDE_PATH = \path\to\your\doxytemplate
> @INCLUDE = doxytemplate.dox
> \# overwrite the suggested configuration entries, for example:
> GENERATE_HTML          = YES  

- execute doxygen with this configuration file

Regards from Meerbusch
Thomas

**Comment by supriyaKrishnamurthy** [comment]
Thank you @thom-sch . Il try this out :)

**Comment by albert-github** [comment]
No further information has been provided, so given explanations [probably have solved the problem.
