### ISSUE TITLE
Callgraph not getting generated

### ISSUE THREAD

**Issue by disa6302** [doxygen/doxygen#8010]
**Describe the bug**
I have added the following to my doxyfile to generate callgraphs for every function in the header file in a C project: 
```
HAVE_DOT               = YES
EXTRACT_ALL            = YES
EXTRACT_PRIVATE        = YES
EXTRACT_STATIC         = YES
CALL_GRAPH             = YES
CALLER_GRAPH           = YES
DISABLE_INDEX          = YES 
GENERATE_TREEVIEW      = YES
RECURSIVE              = YES
```

**Expected behavior**
I should be able to see the callgraphs in index.html. 

**Screenshots**
If useful, add screenshots to help explain your problem.

**To Reproduce**
```
#---------------------------------------------------------------------------
# Project related configuration options
#---------------------------------------------------------------------------
PROJECT_NAME           = "Sample project"
OUTPUT_DIRECTORY       = doc
INPUT                  = ../src/include Introduction.md
OPTIMIZE_OUTPUT_FOR_C  = YES
FILE_PATTERNS          = *.h
RECURSIVE              = YES
EXAMPLE_PATTERNS       = *
HTML_COLORSTYLE_HUE    = 220
HTML_COLORSTYLE_SAT    = 150
HTML_TIMESTAMP         = YES
HTML_DYNAMIC_MENUS     = NO
DISABLE_INDEX          = YES
GENERATE_TREEVIEW      = YES
ENUM_VALUES_PER_LINE   = 4
TREEVIEW_WIDTH         = 250
GENERATE_LATEX         = NO
ENABLE_PREPROCESSING   = YES
MACRO_EXPANSION        = YES
EXPAND_ONLY_PREDEF     = NO
SEARCH_INCLUDES        = YES
INCLUDE_FILE_PATTERNS  = *.h
CLASS_DIAGRAMS         = YES
HIDE_UNDOC_RELATIONS   = YES
DOT_NUM_THREADS        = 0
DOT_FONTNAME           = Helvetica
DOT_FONTSIZE           = 10
CLASS_GRAPH            = YES
COLLABORATION_GRAPH    = YES
GROUP_GRAPHS           = YES
UML_LOOK               = YES
UML_LIMIT_NUM_FIELDS   = 10
TEMPLATE_RELATIONS     = YES
INCLUDE_GRAPH          = YES
INCLUDED_BY_GRAPH      = YES
CALLER_GRAPH           = YES
GRAPHICAL_HIERARCHY    = YES
DIRECTORY_GRAPH        = YES
DOT_IMAGE_FORMAT       = png
DOT_GRAPH_MAX_NODES    = 50
MAX_DOT_GRAPH_DEPTH    = 0
DOT_TRANSPARENT        = NO
DOT_MULTI_TARGETS      = NO
GENERATE_LEGEND        = YES
DOT_CLEANUP            = YES
HAVE_DOT               = YES
EXTRACT_ALL            = YES
EXTRACT_PRIVATE        = YES
EXTRACT_STATIC         = YES
CALL_GRAPH             = YES
```
**Version**
Doxygen version: 1.8.17 (installed with `brew install`)
MacOS version: 10.14.6

I also installed `graphviz` with `brew install graphviz`

Note: I have not made any changes to the public header file to include callgraphs. Can you also let me know if adding `\callgraph` is necessary?

**Comment by albert-github** [comment]
The `\callgraph` is not necessary as you already set `CALL_GRAPH`. 
The doxygen configuration settings look OK, but
- why do you expect to seen in `index.html` the call graphs ?
- what do you mean with "I have not made any changes to the public header file to include callgraphs."?
- do you get any warnings
- it is hard to reproduce without source code:
   - Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

**Comment by disa6302** [comment]
@albert-github , 

1. why do you expect to seen in index.html the call graphs ?
A. Because that is how I can see if my configurations are working. I run doxygen and check index.html to see if the doc looks as expected.

2. what do you mean with "I have not made any changes to the public header file to include callgraphs."?
A. I mean, I did not use the `\callgraph` directive in the header files I am trying to generate the call graphs for.

3. do you get any warnings
A. Yes. I have attached the warning I get in the zip folder. However, even after fixing the warning, I cannot see the callgraph.


4. it is hard / impossible to reproduce without source code:
A. I have attached the zip file here.  I have also attached a screenshot of how my page looks after running the config file.

[test_doxy.zip](https://github.com/doxygen/doxygen/files/5178060/test_doxy.zip)
<img width="1291" alt="Screen Shot 2020-09-05 at 5 17 06 AM" src="https://user-images.githubusercontent.com/22107309/92305090-c0cba500-ef38-11ea-965d-4fcfff5de92c.png">


Let me know if you need any other information.

**Comment by albert-github** [comment]
As you can see only the file `test.h` is processed. This is due to the fact that you specified as `INPUT=include` and on this directory only the file `test.h` is present.  Furthermore you set `FILE_PATTERNS          = *.h` so only `'h` files are processed. I think you should either set `FILE_PATTERNS          = *.h *.cp` or `FILE_PATTERNS          = `.
In the `test.h` only the prototypes are present, so doxygen has no idea about who calls who and thus no call graph

**Comment by disa6302** [comment]
That works! Thanks @albert-github . One thing I would also like is to not add references to *.c files in doxygen. What I mean is, I would like *.c files to only be used as part of call_graph generation, but I do not want the html page to contain any references to them. Do you think this is possible to do?

**Comment by albert-github** [comment]
To the best of my knowledge this is not possible.

**Comment by disa6302** [comment]
Ok. Thank you @albert-github .
