### ISSUE TITLE
How to customize comment style

### ISSUE THREAD

**Issue by Kohit** [doxygen/doxygen#8018]
I have a project using a different comment style(formatted by GreatCode), which not supported by doxygen, the comment style looks like below
```
// ========================
//    text
// ========================
void function();
```
and
```
int var;      // text
```
It's too difficult to change the project comment style into a standard style.  
I'm thinking of changing the doxygen's source code to support this style, but not sure where to start.

**Comment by albert-github** [comment]
Doxygen makes a difference between the standard comment type (here `//`) and the comments intended for documentation (like `///`, `//!`, `//!<`). Changing doxygen for this is, in my opinion, not an option.

Doxygen has the possibility of filters. By writing your own filter which changes your comments into the appropriate documentation style comments.
For the comment styles see the chapter "Documenting the code" ( https://www.doxygen.nl/manual/docblocks.html). 
For the filters see the configuration setting `INPUT_FILTER` (https://www.doxygen.nl/manual/config.html#cfg_input_filter) and `FILTER_PATTERNS` (https://www.doxygen.nl/manual/config.html#cfg_filter_patterns).
