### ISSUE TITLE
Different results on 64 and 32 bit

### ISSUE THREAD

**Issue by ellert** [doxygen/doxygen#8022]
This is a forwarding of downstream Fedora bug https://bugzilla.redhat.com/show_bug.cgi?id=1814356

Starting with doxygen 1.8.17, different results are generated on 32 bit and 64 bit architectures.
See the downstream bug report for a reproducer.

A git bisect between 1.8.16 and 1.8.17 using the reproducer in the downstream report identifies commit ae0a5ec2 as the one introducing the regression.

This regression is terribly annoying, since Fedora’s official build system koji checks that architecture independent subpackages contains the same set of files when built on different architectures. This regression means that documentation built using doxygen no longer can be put into architecture independent packages.

**Comment by doxygen** [comment]
@ellert You say "starting with doxygen 1.8.17"; does this mean this problem is also/still present in new releases (e.g. 1.8.20) or did you only check 1.8.17?

**Comment by ellert** [comment]
Yes it is still present in 1.8.20.

**Comment by doxygen** [comment]
I'm able to reproduce the problem. It seems to happen on 64 bit Linux only so far. The 64bit version on MacOSX is producing the same output as the 32bit Linux version. Valgrind didn't show any wrong, so it needs further investigation...

**Comment by albert-github** [comment]
Just as a small extension to " It seems to happen on 64 bit Linux only so far. ", I see the same problem on Windows as well, the number of inheritance graphs is different.

**Comment by doxygen** [comment]
Please verify if the commit I just pushed fixes the problem.

**Comment by albert-github** [comment]
I tested on Windows and the both version give the same result.
I now see 2 inheritance graphs, one for block" and one for "gr::fcdproplus:fcd_impl" but I see no inheritance graph for "hier_block2" is this expected?

**Comment by doxygen** [comment]
@albert-github I think the validity of the output is indeed something that needs to be checked. The output was dependent on the order of processing, which it should not be. With the fix the order is at least deterministic, but may still not be correct.

**Comment by ellert** [comment]
> Please verify if the commit I just pushed fixes the problem.

The commit fixes the issue. Thank you for the quick response.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
