### ISSUE TITLE
Empty boxes in call graph

### ISSUE THREAD

**Issue by disa6302** [doxygen/doxygen#8031]
**Describe the bug**

I have added doxygen generation as part of travis script that runs doxygen generation within alpine docker. I install doxygen and graphviz in the docker and the call graphs do get generated, but there is no text within the callgraph boxes. I have a attached a screenshot for your reference. 

**Expected behavior**
Callgraphs should be generated correctly. 

**Screenshots**
<img width="1018" alt="Screen Shot 2020-09-14 at 2 37 31 PM" src="https://user-images.githubusercontent.com/22107309/93140760-d7d86880-f697-11ea-89d1-ccff81f5e5c0.png">

**Version**
1.8.17

**Comment by doxygen** [comment]
This is not a doxygen specific issue. Your docker image doesn't have any fonts available for graphviz/dot to use. See https://github.com/maddiefletcher/graphviz-docker/issues/1 for a related issue and possible solution.

Note that you can set `DOT_CLEANUP` to `NO` in the Doxyfile to keep the generated dot files so you can debug the issue more easily. Once running the `dot` tool on the files manually, it should also work from within doxygen.

**Comment by disa6302** [comment]
Great! Thanks! Will try it out.

**Comment by philippludwig** [comment]
> This is not a doxygen specific issue. Your docker image doesn't have any fonts available for graphviz/dot to use. See [maddiefletcher/graphviz-docker#1](https://github.com/maddiefletcher/graphviz-docker/issues/1) for a related issue and possible solution.
> 
> Note that you can set `DOT_CLEANUP` to `NO` in the Doxyfile to keep the generated dot files so you can debug the issue more easily. Once running the `dot` tool on the files manually, it should also work from within doxygen.

Sadly the proposed solution in the linked issue – to install `font-bitstream-type1` and `ghostscript-fonts` – does not fix this problem.

**Comment by albert-github** [comment]
@philippludwig 

It is hard to tell what is going wrong in your case.
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.
- Please specify the **full** doxygen version used (`doxygen -v`).
- which version of `dot` are you using (`dot -V`?

**Comment by philippludwig** [comment]
@albert-github Thanks for your reply.

I used the docker image `alpine:latest` to install the packages, like OP. To be honest, I just switched to `debian:latest`, because they have the dependencies figured out. Installing doxygen and graphviz pulls a bunch of packages like fontconfig, which I guess is missing in alpine.

**Comment by albert-github** [comment]
@philippludwig do I understand it correctly that with `debian:latest` the problem does not occur?

**Comment by philippludwig** [comment]
Yes.
