### ISSUE TITLE
Non-member three-way comparison operator not being documented

### ISSUE THREAD

**Issue by lfcarreon1** [doxygen/doxygen#8032]
Using doxygen 1.8.20, it seems that a member three-way comparison operator is now being documented correctly but not the non-member one.  No documentation appears for the non-member three-way comparison operator.

It is expected that non-member three-way comparison operator appears in the list of functions for a group.

To reproduce this issue, I am attaching a ZIP file containing a Doxyfile and include files required by the Doxyfile.

I'm using doxygen 1.8.20 running on Fedora 32 64-bit.

[doxygen.zip](https://github.com/doxygen/doxygen/files/5223528/doxygen.zip)

**Comment by albert-github** [comment]
With the operator:
```
LFC1_DECIMAL_API std::partial_ordering operator<=>(decimal32 lhs, decimal32 rhs) noexcept;
```
at line 309 of `decimal32.hpp` with comment block starting at line 295 I'm missing the line:
```
///    @ingroup LFC1_DECIMAL
```
which is present for all other non member operators.

After inserting this line (be careful as in the comment a lot of <tab>s are used and they might disrupt the processing), I see the mentioned operator.

**Comment by lfcarreon1** [comment]
Thank you for your reply.  Your reply has actually fixed my issue.  My mistake because I had to move the code from being a member function to a non-member function and forgot to add @ingroup.
