### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by PaulisBeetle** [doxygen/doxygen#8044]
My OS is macOS Mojave and Doxygen is 1.8.20. After updating the bison, cmake still can't be executed successfully. It seems that iconv_open can't be found.

-- The C compiler identification is AppleClang 10.0.1.10010046
-- The CXX compiler identification is AppleClang 10.0.1.10010046
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /Users/sierlock/anaconda3/bin/python (found version "3.7.3") 
-- Found FLEX: /usr/bin/flex (found version "2.5.35") 
-- Found BISON: /opt/local/bin/bison (found version "3.7.2") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Looking for iconv_open
-- Looking for iconv_open - not found
-- Performing Test ICONV_COMPILES
-- Performing Test ICONV_COMPILES - Success
-- Found Iconv: /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libiconv.tbd  
-- One (and only one) of the ICONV_ACCEPTS_... tests must pass
-- Performing Test ICONV_ACCEPTS_NONCONST_INPUT
-- Performing Test ICONV_ACCEPTS_NONCONST_INPUT - Success
-- Performing Test ICONV_ACCEPTS_CONST_INPUT
-- Performing Test ICONV_ACCEPTS_CONST_INPUT - Failed
-- The javacc executable not found, using existing files
-- Configuring done
-- Generating done

**Comment by albert-github** [comment]
You mention:
> It seems that iconv_open can't be found.

but I don't see any error message in your output. I see, for me as non Mac user, a bit a strange name for the `libiconv` i.e. `libiconv.tbd`.
- What is the symbol for `iconv_open` that is searched for?
- What is the symbol for `iconv_open` in the `libiconv`?

**Comment by PaulisBeetle** [comment]
Thanks for your reply! I have installed Doxygen successfully through home-brew.

**Comment by albert-github** [comment]
Problem remains though that either there is an still unidentified problem in the finding of the iconv library or or on your system (or a combination of it).

**Comment by doxygen** [comment]
@PaulisBeetle I don't really see the problem. Based on the output you showed (which is very similar to the output I get), I don't see cmake failing; i.e. it ends with "generating done", not with an error.

Note that cmake does various tests to see what is possible on the system you are using. Some tests may fail, but that does not necessarily mean the system is not usable.

For reference here is the output I get:
```
-- The C compiler identification is AppleClang 12.0.0.12000032
-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.16") 
-- Found FLEX: /usr/local/opt/flex/bin/flex (found version "2.6.4") 
-- Found BISON: /usr/local/opt/bison/bin/bison (found version "3.7.1") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Looking for iconv_open
-- Looking for iconv_open - not found
-- Performing Test ICONV_COMPILES
-- Performing Test ICONV_COMPILES - Success
-- Found Iconv: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib/libiconv.tbd  
-- One (and only one) of the ICONV_ACCEPTS_... tests must pass
-- Performing Test ICONV_ACCEPTS_NONCONST_INPUT
-- Performing Test ICONV_ACCEPTS_NONCONST_INPUT - Success
-- Performing Test ICONV_ACCEPTS_CONST_INPUT
-- Performing Test ICONV_ACCEPTS_CONST_INPUT - Failed
-- The javacc executable: /usr/local/bin/javacc
-- Configuring done
-- Generating done
```

**Comment by PaulisBeetle** [comment]
Thanks for your comment. It indeed doesn't matter so far.
