### ISSUE TITLE
LaTeX template file completion

### ISSUE THREAD

**Issue by ghost** [doxygen/doxygen#8062]
https://github.com/doxygen/doxygen/blob/e58fb0a46f73f37d16859f43fda1eb5ba4a15c5d/templates/latex/latexfiles.tpl#L1-L1

**Comment by albert-github** [comment]
At the moment the `tpl` files are not used, they have been, an attempt, of a  start of more flexible way to generate the LaTeX output. The log messages says:
```
Date:   Thu Jan 1 21:04:54 2015 +0100

    Started with generating LaTeX output via the template engine
```

The same message is in `latexmodules.tpl` and `latexnamespaces.tpl`.
The other template files have to be checked for completeness (a.o. for TOC package, longtable / tabu package etc.).

@jaroslavaskar The title a a bit non saying and was likely to be seen as spam, I adjusted it slightly, Furthermore the issue report is quite short and not directly understandable, a bit more information would have been of interest.

**Comment by albert-github** [comment]
This issue is obsolete as of 0b0ec2e (in doxygen 1.9.8) wirg reasoning:
```
 Remove experimental template engine option

Motivation:
- Incomplete and lagging behind for years
- Too much effort to maintain
- Hard to get the same/reasonable performance
```

So actually problem is solved in the mean time.
