### ISSUE TITLE
Md5 hash does not match for two different runs (2)

### ISSUE THREAD

**Issue by albert-github** [doxygen/doxygen#8071]
This issue addresses a similar problem as mentioned in #7706 but not to make the entire discussion to confusing and the fact that a similar problem was already solved there I created a new issue for this case.

When we have a number of source (`.cpp`) files with inside these files a similar / identical class definition we get the messages about:
```
error: md5 hash does not match for two different runs ...
```

It looks to me that the original filename is not taken into account in the file name of the image.
(tested with the current master 1.9.0 (0d8c2bb9743f4ee862c740a6eedb228f28cd9725))

The following example contains a stripped down version of the source files but also the original files (`.org`): [example.tar.gz](https://github.com/doxygen/doxygen/files/5319198/example.tar.gz)

(The problem was seen in the clamav package on Fossies)

In the 1.8.15 version we don't get any messages but here references in the images point every time to the the same routine although it should be to a routine in a different file (so silently ignored). From 1.8.16 we get the warnings.

**Comment by doxygen** [comment]
Problem is that doxygen assumes that classes have unique names (when looking at the fully qualified name, so the same names is ok in different namespaces). This is normally the case because if you would compile and link the source code, the linker will ignore one of the implementations. See also https://stackoverflow.com/questions/10671956/same-class-name-in-different-c-files for a discussion about this topic.

If we would support multiple classes with the same name in doxygen, then linking to them will become ambiguous.

So one the solution should be to fix the code and wrap the classes in (anonymous) namespaces.
If the original code put the source files in different binaries (shared libraries for instance) then the solution is to make a separate doxygen project for each binary.

**Comment by albert-github** [comment]
I do agree that there is the problem of ambiguity and that the real solution would be to create 2 different doxygen projects, though Fossies does just a brute force approach (and putting everything on one big heap as Fossies doesn't know anything about the internal structure of the project).

A nice solution would indeed be that doxygen could wrap the classes in (anonymous) namespaces (I don't think this can be proposed to the clamav package owner) but this would probably very difficult and would give problems on other places.
Maybe it is possible to give a little bit a better / user friendly message than:
```
error: md5 hash does not match for two different runs of .../html/class_clam_a_v_state_a86ca6992fe2dfbe5b997f3881c69e46a_cgraph.dot !
```
something like:
```
error: multiple definition of 'class clamAVState'.
```
when possible even with the name of the source files where it occurs, but this would probably be even more difficult).

**Comment by doxygen** [comment]
@albert-github Improving the warning sounds like a good idea indeed. I think the warning could be generated already while building up the list of a classes (i.e. in `addClassToContext`). At that point it should not be too hard to mention the location of the original class and the new one. Note that the `addClassToContext` function is used both in `buildClassList` and in `buildClassDocList`. The latter is for `@class` commands, so there the class should actually exist and no warning should be generated.

**Comment by albert-github** [comment]
I see that this issue was closed with release 1.9.0 as it still had the `wontfix` label, but seen the last comment wouldn't it still be possible to issue the better warning?

**Comment by TStein1984** [comment]
I had the same issue and was trying to find out to solve the md5 problems for many days. After some days work I found five of six double class names. It would be a very big help if the warning has more informations about the class names, which are twice in the project and in the same namespace. Especially for large projects with a huge amount of developer it would be a great support.

**Comment by albert-github** [comment]
@TStein1984

"I had the same issue" is always a bit vague, in this case it is a bit explained in the accompanying text.
Always mention the version of doxygen you used (it happens that an issue is fixed in a newer version but the issue is not yet closed) and when not using the latest version also try to test with the latest version. (I tried with the current development version (1.9.2 (07d04c093b3070118a9d24b2c346a65c3f16da6b)) and the problem is stil unchanged).
Also attaching a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem would be of help (in this case it is clear what the problem is so probably not that relevant). And please don't add external links as they might not be persistent.

**Comment by ofarrill** [comment]
I don't think this is fully thought thru as cross platform code might have equal class names with platform specific implementations for different targets.

**Comment by albert-github** [comment]
I don't think this is relevant here as in case of cross platform code the definition / declaration and the invocation will use the same syntax.

Can you give an example where you would expect the problem:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).
- Please also specify the **full** doxygen version used (`doxygen -v`).
