### ISSUE TITLE
How do add (multiple files without extension) directory in INPUT field of doxygen configuration file??

### ISSUE THREAD

**Issue by jalsamulsa** [doxygen/doxygen#8105]
In my configuration file in the INPUT tag I added one directory. Inside that there are many files are there without extension. After running the configuration file I'm not getting information related to that files. I want to know how to add directory(containing without extension files)  in doxygen configuration file.
When the files are explicitly listed the information is given as the `EXTENSION_MAPPING` understands `no_extension` but as the `FILE_PATTERNS` doesn't it is not possible to get them through the directory name.

This issue is based on and the discussion there: https://stackoverflow.com/questions/64366070/how-to-add-files-without-extension-in-doxygen-configuration-filee-g-iostream-li

Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/5384571/example.tar.gz)

**Comment by jalsamulsa** [comment]
thank you @albert-github , it's working fine

**Comment by albert-github** [comment]
As the text in the manual was not 100% clear I've just pushed a proposed patch, pull request #8109 with a small explanation.

**Comment by doxygen** [comment]
Note that instead of using `*` you could also include part of the path e.g. `*/inc/*` or specify each file individually as input file.

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
