### ISSUE TITLE
Constant from scoped enumeration is mapped to the wrong scope

### ISSUE THREAD

**Issue by diegodiasm** [doxygen/doxygen#8106]
Doxygen seems to map constants from a scoped enumeration as global constants. The following simple scenario allows the problem to be observed, but it may not be the minimal example to reproduce the issue.

- File `dma_space` constains  a namespace `L4Re` and a class `Dma_space`. The scoped constant
  `Space_attrib::Phys_space` is defined in this class.

- File `dma_space.h` defines scoped constants, and copies their documentation from those defined in `dma_space`.

- When generating the documentation, doxygen is unabled to find `L4Re::Dma_space::Space_attrib::Phys_space`,
  but is able to find `L4Re::Dma_space::Phys_space`

I would have expected the constant `L4Re::Dma_space::Space_attrib::Phys_space` to be found by doxygen when generating the documentation, and the attempt to copy documentation from `L4Re::Dma_space::Phys_space` to trigger an error/warning with the not found target message.

**To Reproduce**

Attach is a simplified snippet which allows the problem to be reproduced.

[mwe_doxygen.zip](https://github.com/doxygen/doxygen/files/5385340/mwe_doxygen.zip)

**Version**
Tested on doxygen 1.8.13; 1.8.16; 1.8.18, 1.8.20

Thanks for your help,
Diego Dias

**Comment by doxygen** [comment]
> I would have expected the constant L4Re::Dma_space::Space_attrib::Phys_space to be found by doxygen when generating the documentation, and the attempt to copy documentation from L4Re::Dma_space::Phys_space to trigger an error/warning with the not found target message.

If you use a normal (unscoped) enum the enum values end up in the parent scope and that is also where doxygen will look.
To get the behavior you are looking for you need to use scoped (or strong) enums introduced with C++11, i.e. `enum class Space_attrib` instead of `enum Space_attrib`. See also https://coders-corner.net/2017/08/13/scoped-vs-unscoped-enum/
 
So I don't think this is a bug in doxygen.

**Comment by diegodiasm** [comment]
Thanks for the explanation and the link. I agree this is not an issue, and I am closing the issue.
