### ISSUE TITLE
Insertion of unusual/bad anchors when processing markdown

### ISSUE THREAD

**Issue by bryan-hunt** [doxygen/doxygen#8113]
**Describe the bug**
I'm not sure if this is a duplicate of one of the issues identified in #8078 but it seems different enough to merit its own report. I have noticed two issues where doxygen seems to be inserting malformed/inappropriate anchors when processing markdown. I have details below with usage and resulting outputs (I have had to modify the output as one of the issues is that offending anchors are exporting local system information).

**Version**
1.8.20 (Windows 64)

**Expected behavior**
* Pagedocs using markdown should not result in doxygen inserting an anchor with the absolute file path of the source markdown file
* Using markdown anchors should not result in file path artifacts in the output (HTML, LaTEX, etc)

**Details**

The first issue is that when using markdown page docs by specifying they belong to a group results in an anchor inserted into the output HTML with the absolute file path of the source markdown file (escaped with underscores). I have not discovered a workaround for this issue

Using the ingroup command in the markdown file
```
@ingroup GROUP_LABEL
```

Produces the following output in the HTML at the start of memberdef.pagedocs
```
<h3><a id="md_ABSOLUTE_SYSTEM_PATH_TO_SOURCE_FILE"></a>GROUP_LABEL</h3><div class="textblock">...
```

The second case where a bad anchor is produced is when the markdown anchor id form is used in headings

If one used an anchor id in the markdown (other than #index or #mainpage which produce the correct output)
```
Some Heading Topic {#page_id}
==========================
```

The result is the following output in the HTML file
```
</div><!--header-->
<div class="contents">
<div class="textblock"><p><a class="anchor" id="md_ABSOLUTE_PATH_TO_THE_SOURCE_FILE_TO_THE_FIRST_DOT"></a>REMAINING_FILE_PATH_AFTER_THE_FIRST_DOT</p>...
```

The subpage commands still function using the page_id and the treeview is produced correctly so navigation works just fine. The only issue is the output. This output is also seen when the LaTEX output is converted to PDF.

The workaround for this issue is to change the markdown from the above to this form:
```
Some Heading Topic
===========================================
@page page_id Some Heading Topic
```

**Comment by albert-github** [comment]
I did a quick test but didn't find an absolute path, so:
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.  Note: you can build your test tree on a dummy directory so you don't reveal local system information.

As far as I can see this has nothing to do with the mentioned issue #8087.
That there is a relative path in an anchor can be explained by the fact that a file can exists in multiple directories and one wants to be able to jump to the right part. It might have been nice, for some, that such a generated anchor was a bit encoded.
