### ISSUE TITLE
Whitespace/Separator required to recognise custom command argument

### ISSUE THREAD

**Issue by asihera** [doxygen/doxygen#8137]
Hello,

Very seemingly simple problem.

In Doxyfile:

`  ALIASES += cmd{2}="\1\2"`

Then in source I do:

`  @cmd{x,y}`

and I get

`  x\2`

However,

`  ALIASES += cmd{2}="\1 \2"`

(note whitespace) produces:

`  x y`

with a whitespace in between.

Why is it that expansions of custom command arguments have to be something-separated? I want to concatenate the arguments of a custom command and I can't.

Incidentally, putting a command argument after a nested expansion doesn't work either. E.g.:

`  ALIASES += cmd{1}="@mycommand{x,y}\1"`

Will not expand \1. It just copies "\1" verbatim to the output.

Haven't tried the latest version but I have tested versions between 1.8.9 and 1.8.18 and they all behave the same.

Kind Regards,

**Comment by albert-github** [comment]
Looks indeed like the `ALIASES` substitution doesn't find the second `\` properly to replace this as well.
(I tested it with the current master (1.9.0 (c5ce7512ad6482a3e928d99ddbb0cc68044b58dc))

Would have been nice when we had straight away a, small, self contained example (source+configuration file in a tar or zip) that allowed us to reproduce the problem (don't add it as external links as they might not be persistent. ) 

So here is the example: [example.tar.gz](https://github.com/doxygen/doxygen/files/5454024/example.tar.gz)

**Comment by asihera** [comment]
I had an example.

[Command-Args-Substition.tar.gz](https://github.com/doxygen/doxygen/files/5454065/Command-Args-Substition.tar.gz)

Not much different from yours but demonstrates the problem, I think.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #8138

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by asihera** [comment]
Thanks for taking a look at this.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
