### ISSUE TITLE
extern variable is being referenced in documentation incorrectly (Origin: bugzilla #121547)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#814]
status REOPENED severity *normal* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[DoxTest.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug121547_19768_DoxTest.zip/download/download)_ (ID 19768)

On 2003-09-05 14:55:42 +0000, John Sivak wrote:

    I've got 1 file that declares and assigns a variable const char *pczMagic.
    A second file uses "extern const char *pczMagic;" to declare the variable.
    
    In the generated docuemntation the file that defined the pczMagic 
    (SOCO_ADD.cpp) contains a link that points to the file 
    (SOCODocStorage.cpp) that used the "extern" declaration.  I don't think 
    this is the desired behavior.
    
    I have a sample of the files + doxygen config that duplicates the problem.

On 2003-09-05 14:58:15 +0000, John Sivak wrote:

    Created attachment 19768
    ZIP file containing C++ source and doxygen config file configured to
    replicate bug

On 2005-01-02 13:38:23 +0000, Dimitri van Heesch wrote:

    I haven't been able to reproduce this problem with version 1.4.0, so I
    assume it
    is fixed now.

On 2005-01-03 15:32:58 +0000, John Sivak wrote:

    Nope, 1.4 doesn't fix it.
    
    The hyperlink in the "blue box" under heading "Variable Documentation"
    points to
    the wrong file (still links to SOCODocStorage.cpp when it should link to
    SOCO_ADD.cpp docs).
    
    The definition hyperlinks are correct though. 

On 2011-03-28 17:57:06 +0000, Manuel L. Pereira GarcÃ­a wrote:

    I have found that it is present on version 1.7.2, both on Windows and UNIX-
    like OS (Ubuntu and Debian).

On 2013-04-27 17:02:21 +0000, albert wrote:

    I tested the problem with version 1.8.3.1, the wrong link is gone but in the
    documentation of the file SOCODocStorage.cpp there is the reference to the
    file SOCO_ADD.cpp but it is not clear that the variable in file
    SOCODocStorage.cpp is extern.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #7792

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.19.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
