### ISSUE TITLE
copydoc in excluded namespace broken after d03e8d9

### ISSUE THREAD

**Issue by eseiler** [doxygen/doxygen#8143]
**Describe the bug**
Consider
```cpp
namespace detail
{

//!\brief An example struct.
struct S
{
    //!\brief An example function.
    void foo();

    //!\copydoc foo()
    void bar();
};

}
```
and a Doxyfile containing `EXCLUDE_SYMBOLS = detail` .

This will result in a warning: `example/example.hpp:10: warning: @copybrief or @copydoc target 'foo()' not found`

**Expected behavior**
Before mentioned commit, it worked. It did not try to look up symbols within an excluded namespace.
The example works again after either removing the namespace or the EXCLUDE_SYMBOLS.

**To Reproduce**
[example.tar.gz](https://github.com/doxygen/doxygen/files/5464288/example.tar.gz)

**Version**
Happens on current master, first faulty commit according to `git bisect` is d03e8d9411ab3e983fc3413c147fba1a5e5c9dad

**Comment by albert-github** [comment]
I'm not sure whether this is a bug now or whether it was a bug in the past.
You explicitly say `EXCLUDE_SYMBOL=detail` so the `namespace detail` has the symbol `detail` and thus should be excluded.
I tend to it that it was a bug in the past.

**Comment by albert-github** [comment]
Though rethinking about it I think it is a bug anyway, the namespace should not be shown (and it is not shown) but warnings regarding thing that happen inside the namespace detail / concern the excluded symbol shouldn't be shown as is done now (the warning now is incorrect).

**Comment by doxygen** [comment]
@eseiler I've pushed a possible fix for this (see https://github.com/doxygen/doxygen/commit/42d60bd97de0d1fbf85fdc9117e8dd46a026db1b). Please verify if it works.

**Comment by eseiler** [comment]
Thank you, this issue is fixed.
