### ISSUE TITLE
copydoc broken in private sections

### ISSUE THREAD

**Issue by eseiler** [doxygen/doxygen#8148]
**Describe the bug**
I reckon this is similar to #8143.

Consider
```cpp
//!\brief My favorite class.
class S
{
    //!\brief Some private function.
    void foo();
};

//!\brief Another class.
class T
{
    //!\copydoc S::foo()
    void bar();
};
```

With `EXTRACT_PRIVATE        = No` (the default), this results in `/run/shm/example/example.hpp:11: warning: @copybrief or @copydoc target 'S::foo()' not found`.
My understanding is that the copydoc shouldn't produce a warning since `bar` is also private and hence won't be extracted.
`EXTRACT_PRIVATE        = Yes` works as expected as in that it produces no warning, but also shows the private entities in the documentation/

**Expected behavior**
No warning.

**To Reproduce**
[example.tar.gz](https://github.com/doxygen/doxygen/files/5470531/example.tar.gz)

**Version**
Current master, likely the same version as reported in #8143.

**Comment by albert-github** [comment]
Looks like a similar problem but now for class / struct.
Version 1.8.20 looks like to be OK.

**Comment by doxygen** [comment]
@eseiler I see I needed to exclude more symbols from tooltip creation indeed. The new commit should address this.

**Comment by eseiler** [comment]
Thank you, no more warnings in my builds :)

**Comment by albert-github** [comment]
Since this problem is not appearing in any official release and is fixed before the next release I'll close the issue.
