### ISSUE TITLE
Unable to document template function arguments (Origin: bugzilla #121580)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#815]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.3.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2003-09-06 03:06:31 +0000, Ivan Godard wrote:

    A template function will not let you document the template arguments (as
    opposed to the function arguments).
    
    Thus:
    
    /**   A template.
          \param  T   a type
          */
    template<typename T>
    void Foo(T t){}
    
    gets you:
    Warning: argument `T' of command @param is not found in the argument list of
    Foo(T t)

On 2018-03-23 18:37:21 +0000, albert wrote:

    This is in my opinion not a bug but usage. The "data type" is T and the
    argument is (lowercase) t. With the \param the argument is documented.

**Comment by albert-github** [comment]
In version 1.3 there was no command to really document a template parameter, in version 1.5.5. the command `\tparam` was added.

As already noted the `\param` needs the argument name `t`.

So partly usage and solved in the mean time.
