### ISSUE TITLE
A template declaration loses its doc (Origin: bugzilla #121582)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#817]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.3.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2003-09-06 03:26:49 +0000, Ivan Godard wrote:

    A declaration:
    
    /// A template
    template<typename T>
    class Foo;
    
    doesn't get included in the output. However, subsequent specializations:
    
    ///  a specialization
    class Foo<int> {...};
    
    do get included.
    
    It is common in metaprogramming to have templates without general
    implementations, only a few specializations, and you want to be able to
    document the template itself as distinct to its specializations

On 2005-01-02 13:50:42 +0000, Dimitri van Heesch wrote:

    Doxygen indeed does not support documenting template class declarations,
    only
    definitions. I'll mark this as an enhancement. As a workaround you could
    use:
    
    /// A template
    template<typename T>
    class Foo DECL_ONLY;
    
    ///  a specialization
    class Foo<int> {};
    
    in combination with the following configuration settings (and #defining
    DECL_ONLY as empty in the code).
    
    ENABLE_PREPROCESSING   = YES
    MACRO_EXPANSION        = YES
    EXPAND_ONLY_PREDEF     = YES
    PREDEFINED             = DECL_ONLY={}

**Comment by albert-github** [comment]
As far as I can see the declaration is not present with version 1.3.1 but is present with 1.8.15,

I think the problem has been solved in the mean time.
