### ISSUE TITLE
Invalid inheritance

### ISSUE THREAD

**Issue by sloriot** [doxygen/doxygen#8172]
**Describe the bug**
When parsing 
```
/// This is struct D (broken)
template <class AA>
struct D : public AA::B
{
};
```
doxygen outputs that `D` inherits from `B` while it should be `AA:B`

**Screenshots**
![Screenshot from 2020-11-12 10-55-41](https://user-images.githubusercontent.com/1224632/98924989-c368ee80-24d5-11eb-9959-bfcdf8c7e4a4.png)
[br.tar.gz](https://github.com/doxygen/doxygen/files/5529690/br.tar.gz)

**To Reproduce**
cf attached tar.gz

**Version**
1.9.0 (efb3eb758f443ba8aebda3665b725a4e0dd1196d*)

**Comment by albert-github** [comment]
In `classdef.cpp` we see in the routine currently:
```
        QCString displayName = insertTemplateSpecifierInScope(
            cd->displayName(),bcd.templSpecifiers);

        if (cd->isLinkable())
        {
          ol.writeObjectLink(cd->getReference(),
                             cd->getOutputFileBase(),
                             cd->anchor(),
                             displayName);
        }
        else
        {
          ol.docify(displayName);
        }
```
when changing this into:
```
        if (cd->isLinkable())
        {
          QCString displayName = insertTemplateSpecifierInScope(
              cd->displayName(),bcd.templSpecifiers);
          ol.writeObjectLink(cd->getReference(),
                             cd->getOutputFileBase(),
                             cd->anchor(),
                             displayName);
        }
        else
        {
          QCString displayName = insertTemplateSpecifierInScope(
              cd->name(),bcd.templSpecifiers);
          ol.docify(displayName);
        }
```
as I'm not sure about side effects, so I didn't make a PR out of it.

@doxygen what do you think?

**Comment by albert-github** [comment]
Rechecked issue and it looks like the inheritance relation is now correctly show. Also the underlying CGAL issue  CGAL/cgal#5154 has been confirmed to be solved.

I think the problem has been solved in the mean time
