### ISSUE TITLE
Using README.md from my main repo as mainpage in Doxygen fails to build

### ISSUE THREAD

**Issue by qknight** [doxygen/doxygen#8182]
**Describe the bug**
I have a Doxyfile which includes a README.md from my project repository which should be used as documentation.

When I build the documentation I get this:

`myproject/README1.md:10: error: unable to resolve reference to 'lib/spdlog/README.md' for \ref command (warning treated as error, aborting now)`

Note: /lib is not part of the INPUT directive thus this file can't be parsed from doxygen - I think. The lib folder contains third party libraries as spdlog/sarge/... and similar.

Note: I'll upload a Doxyfile and example in a few moments.

**Expected behavior**
**I'd hoped that Doxygen just could grab the README.md from the source I'm about to create the API documentation of to not have to duplicate descriptions.**

My README.md basically describes the project, contains a manual how to build the project and mentions some general explanations where the source is hosted and who it belongs authors/license.

**To Reproduce**

**Version**
1.8.17 on Ubuntu 20.20

**Additional context**

Related to https://github.com/doxygen/doxygen/issues/7151

[doxygen-readme.md-example.tar.gz](https://github.com/doxygen/doxygen/files/5565797/doxygen-readme.md-example.tar.gz)

**Comment by qknight** [comment]
I've added an example here:
https://github.com/qknight/doxygen-issue-example

/home/joschie/Projects/doxygen-readme.md-example/src/README.md:9: error: unable to resolve reference to 'lib/spdlog/README.md' for \ref command (warning treated as error, aborting now)

Please note, I don't want to document the lib/ third-party source codes in doxygen.

**Comment by albert-github** [comment]
As the `[lib/spdlog/README.md](lib/spdlog/README.md)` creates a link you have to add the `lib/spdlog/README.md` to the `INPUT` settings so that doxygen can find the referenced file.

Maybe you should also have a look at:
- `\include{doc}`
- `\snippet{doc}`

and set the `EXAMPLE_PATH`

**Comment by albert-github** [comment]
https://github.com/doxygen/doxygen/issues/8182#issuecomment-729661088

Please don't add an example at https://github.com/qknight/doxygen-issue-example (as this still may not be persistent) but attached it as a self contained example (source+configuration file in a tar or zip) .

**Comment by albert-github** [comment]
In your Doxyfile we see:
```
INPUT                  = src \
                         lib
```
and
```
EXCLUDE                = lib/
```
but this means that the `lib` in the `INPUT` setting has no effect as this will be filtered out due to the setting in the `EXCLUDE`.

The best solution in your case will probably be to remove the `lib` from the `EXCLUDE` setting and add `lib/spdlog/README.md` to the `INPUT setting.

I think the problem is usage.

Note I already added the example to the issue in my previous comment (https://github.com/doxygen/doxygen/issues/8182#issuecomment-729662307).

**Comment by qknight** [comment]
I actually don't care about lib/spdlog/README.md at all. I do not want to have that in my doxygen documentation.

The original motivation was to be able to click that link in bitbucket so one can simply click the link to get to the other document. However, I just noticed that this does not work either. Maybe I should just remove that reference then!

Thanks for your help. Btw: The EXCLUDE from above was an experiment I tried and was a left-over. The reason why I chose a GIT repo as example source over an tar.gz is that you can simply create a PR, clone the code without effort and so on.
