### ISSUE TITLE
INPUT should be recursive

### ISSUE THREAD

**Issue by mcandre** [doxygen/doxygen#8188]
Asking users to explicitly spell out the full directory tree for a medium to large project is cumbersome and error-prone. Let's make `INPUT` recursive, using computers for what they do best: rote automation.

**Comment by albert-github** [comment]
What is the difference in this from the doxygen configuration setting `RECURSIVE=YES` ?

**Comment by albert-github** [comment]
Unfortunately no further information, so either the suggestion `RECURSIVE=YES` solves the issue and thus usage or the issue is incomplete.
