### ISSUE TITLE
Markdown Code Fences Do Not Nest With Lists

### ISSUE THREAD

**Issue by awschult002** [doxygen/doxygen#8189]
**Describe the bug**
When using doxygen 1.8.20 to render markdown, there appears no way to properly render code blocks nested within a list. Instead the list is either rendered as all code, or as some code, then a list of single element lists that are not associated with the previous items.

**Expected behavior**
Other markdown parsers allow the use of code fences at the same indentation level as a list item, to indicate that the code block is part of the list.

**Screenshots**
If useful, add screenshots to help explain your problem.

** To Reproduce **
place the following in a markdown file
```
# testing markdown code nesting #

create a list
1. item number one
    - sub item requires code for explanation
    ```
    some code for stuff
    ```
    - sub item requires code for explanation
    ```
    some code for stuff
    ```
    - sub item requires code for explanation
    ```
    some code for stuff
    ```

```
> This should end up looking like the following

# testing markdown code nesting #

create a list
1. item number one
    - sub item requires code for explanation
    ```
    some code for stuff
    ```
    - sub item requires code for explanation
    ```
    some code for stuff
    ```
    - sub item requires code for explanation
    ```
    some code for stuff
    ```
-----
> but this is the best doxygen can do.
# testing markdown code nesting #

create a list
1. item number one
    - sub item requires code for explanation
```
    some code for stuff
```
    - sub item requires code for explanation
```
    some code for stuff
```
    - sub item requires code for explanation
```
    some code for stuff
```

**Comment by albert-github** [comment]
- Which version of doxygen did you use?

When reducing the spacing in front of the lines from 4 to 2 or 3  I get the desired effect.

**Comment by awschult002** [comment]
I just tried it with both 3 and 2 spaces on both the comment fences and the list, and I did not receive the desired effect. Although it is much closer. What I got was the first sub item in the list as being rendered as a sub item; then a proper code block; then a new list with a single bullet item; then a code block. The sub-items are not being rendered as part of the same list. Below is what I see.


1. item number one
    - sub item requires code for explanation
   ```
    some code for stuff
   ```
 - sub item requires code for explanation
   ```
    some code for stuff
   ```
 - sub item requires code for explanation
   ```
    some code for stuff
   ```


> p.s. I updated the issue description with my version number of 1.8.20

**Comment by albert-github** [comment]
When I have the input:
~~~
# second testing markdown code nesting #

create a list
1. item number one
   - sub item requires code for explanation
   ```
   some code for stuff
   ```
   - sub item requires code for explanation
   ```
   some code for stuff
   ```
   - sub item requires code for explanation
   ```
   some code for stuff
   ```
~~~
and default doxgen settings, I get:

![res_3](https://user-images.githubusercontent.com/5223533/99813497-0a935700-2b48-11eb-9f95-03cf2039562f.png)

Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/5574229/example.tar.gz)

**Comment by awschult002** [comment]
OH!!!! I see. I had a blank line in between my listed item and the code block.

```
    1. list
       - list item

       ```
             code block
       ```

       - list item 2

       ``` 
          code block 2
       ```
```


-----

removing the blank line so that the code fence directly follows the sub-item works perfectly!
Thank you!
