### ISSUE TITLE
Wrong directory separator in Windows

### ISSUE THREAD

**Issue by mcandre** [doxygen/doxygen#8195]
**Describe the bug**

When doxygen tries to construct a dependency plot in Windows, then the wrong directory separator is used.

```console
CUSTOMBUILD : error : Problems running dot: exit code=1, command='dot', arguments='"C:/vagrant/html/dir_8a0776572ba2252f65a895457421e228_dep.dot" -Tpng -o "C:/vagrant/html/dir_8a0776572ba2252f65a895457421e228_dep.png"' [C:\vagrant\doc.vcxproj]
   (warning treated as error, aborting now)
```

Ignoring the fact that the dot file should really be housed in an OS-relative temp directory, we can see that the slashes here are forward, when they should be backward. If you're going to use forward slashes, make sure to use a WSL / Cygwin / MSYS / Git Bash / MinGW path, not a `C:` root.

**Expected behavior**

doxygen provides appropriate directory paths to graphviz and dot, for each of the following environments:

* native Windows, AKA COMSPEC, Command Prompt, PowerShell
* WSL AKA bash on Ubuntu on Windows
* Cygwin
* MSYS
* Git Bash
* MinGW

**To Reproduce**

Run doxygen in Git Bash.

**Version**

1.8.20

**Comment by mcandre** [comment]
Update: For what it's worth, the dot error appeared to go away once `dot -c` was initialized.

**Comment by albert-github** [comment]
So when I understand you correctly the problem is not a doxygen problem but an installation problem of Graphviz / dot.

To the best of my knowledge Graphviz / dot can work with the forward slashes on Windows.
