### ISSUE TITLE
LLVM doxygen failed to be built

### ISSUE THREAD

**Issue by erez-o** [doxygen/doxygen#8202]
**Describe the bug**

Trying to make doxygen with clang and llvm:

```cmake
# installing llvm, https://github.com/llvm/llvm-project/releases/tag/llvmorg-11.0.0
cd llvm-project
mkdir build
cd build
cmake -DLLVM_ENABLE_PROJECTS=clang -G "Unix Makefiles" ../llvm

# installing doxygen, version https://github.com/doxygen/doxygen/tree/cbf83033232f8c76836bd8f086bfad146ed74e00:
cd /home/erez
cd doxygen
mkdir build
cd build
cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/erez/llvm-project/build/lib/cmake -Duse_libclang=ON ..
make
```

During make I recieve the following error:
```
[ 63%] Building CXX object src/CMakeFiles/doxymain.dir/__/generated_src/ce_parse.cpp.o
[ 64%] Building CXX object src/CMakeFiles/doxymain.dir/__/generated_src/resources.cpp.o
[ 64%] Building CXX object src/CMakeFiles/doxymain.dir/arguments.cpp.o
[ 64%] Building CXX object src/CMakeFiles/doxymain.dir/cite.cpp.o
[ 65%] Building CXX object src/CMakeFiles/doxymain.dir/clangparser.cpp.o
/home/erez/doxygen/src/clangparser.cpp:6:27: fatal error: clang-c/Index.h: No such file or directory
 #include <clang-c/Index.h>
                           ^
compilation terminated.
src/CMakeFiles/doxymain.dir/build.make:935: recipe for target 'src/CMakeFiles/doxymain.dir/clangparser.cpp.o' failed
make[2]: *** [src/CMakeFiles/doxymain.dir/clangparser.cpp.o] Error 1
CMakeFiles/Makefile2:740: recipe for target 'src/CMakeFiles/doxymain.dir/all' failed
make[1]: *** [src/CMakeFiles/doxymain.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```

Any help would be great.

**Comment by albert-github** [comment]
You mentioned cbf83033232f8c76836bd8f086bfad146ed74e00 as doxygen version, this is a version from July 8, 2020.
Can you try it with a more recent version (preferably master)?

**Comment by erez-o** [comment]
I updated doxygen to latest and received the same error. I edited the above script and received the following error:

```
[ 99%] Linking CXX static library ../lib/libdoxymain.a
[ 99%] Built target doxymain
Scanning dependencies of target doxygen
[ 99%] Building CXX object src/CMakeFiles/doxygen.dir/main.cpp.o
[100%] Linking CXX executable ../bin/doxygen
/usr/bin/ld: cannot find -lLLVM
collect2: error: ld returned 1 exit status
src/CMakeFiles/doxygen.dir/build.make:104: recipe for target 'bin/doxygen' failed
make[2]: *** [bin/doxygen] Error 1
CMakeFiles/Makefile2:671: recipe for target 'src/CMakeFiles/doxygen.dir/all' failed
make[1]: *** [src/CMakeFiles/doxygen.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```

The edited script I ran was:
```sh
# installing llvm, https://github.com/llvm/llvm-project/releases/tag/llvmorg-11.0.0
cd llvm-project
mkdir build
cd build
cmake -DLLVM_ENABLE_PROJECTS=clang -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" ../llvm
make
sudo make install

# checking built correctly:
clang --version                 # Outputs 11.0.0
llvm-config --version           # Output 11.0.0

# installing doxygen, latest version https://github.com/doxygen/doxygen/tree/6de91dc5e32e6d97a557fe6910a6cbf1d453ad9c:
cd /home/erez
cd doxygen
mkdir build
cd build
cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -Duse_libclang=ON ..
make
```

Running on debian 9.6 if it makes a difference.

Maybe there's a problem in the cmake flags in my script?

**Comment by albert-github** [comment]
In the cmake step to create doxygen I used (for readability I split the lines, normally this is just 1 line):
```
cmake -G "NMake Makefiles"
-Duse_libclang=ON -Dstatic_libclang=ON 
-DLLVM_DIR=E:\Programs\LLVM\11.0\llvm-project\build_windows_nmake_v2017_64\lib\cmake\llvm
-DClang_DIR=E:\Programs\LLVM\11.0\llvm-project\build_windows_nmake_v2017_64\lib\cmake\clang
"-DCMAKE_CXX_FLAGS=-I E:\Programs\LLVM\11.0\llvm-project\clang\include -I E:\Programs\LLVM\11.0\llvm-project\build_windows_nmake_v2017_64\tools\clang\include"
..
``` 

In my, incomplete, notes I see for LLVM:
```
cmake -DLLVM_ENABLE_PROJECTS=clang;clang-tools-extra -g "Visual Studio 16 2019" -A x64 -Thost=x64 ..\llvm 
devenv.exe .\LLVM.sln
```
Note also the project `clang-tools-extra` is enabled.

I'm using CMake version 3.16.1

Maybe also #7594 might shine a light on it as well.

**Comment by erez-o** [comment]
Thanks, 
I passed make, needed both `clang-tools-extra` and `-Dstatic_libclang=ON `, but the resulting doxygen can't run:
```
# running doxygen returns the following error:

doxygen: error while loading shared libraries: libclang.so.11: cannot open shared object file: No such file or directory
```

Might be due to debian, cmake, gcc, or any number of other dependency not sufficiently updated.

I'll delay my installation attempts for now, maybe other users attempting installation on debian will give better clarity in the future. Closing issue.

**Comment by albert-github** [comment]
Apparently the static linking is not really static yet, did you use also the  `-DLLVM_DIR=...` and `-DClang_DIR=...` You could also try to place the `libclang.so.11` from your distribution in your path

**Comment by erez-o** [comment]
Thanks for the help,

I don't think `-DLLVM_DIR=...` and `-DClang_DIR=...` are the cause. I tried playing with it, and see https://stackoverflow.com/questions/64053447/doxygen-build-failing-for-1-8-20-on-ubuntu-with-clang

He reported the following worked for him (llvm-10, not 11):
```
apt install llvm-10 clang-10 libclang-10-dev
```

```
cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -Duse_libclang=ON ..
```

I stopped trying to install because my current debian installation does not meet the ["known to work" requirements of LLVM](https://llvm.org/docs/GettingStarted.html#software)

I'll revisit  the installation in the future when I can update my debian to a newer version.

If it's possible, please add to doxygen docs an installation guide that is known to work and pass all doxygen tests for linux stable, and what's doxygen minimum version requirement of LLVM and Clang.
