### ISSUE TITLE
Option to warn on undocumented public API member

### ISSUE THREAD

**Issue by mcandre** [doxygen/doxygen#8229]
Please offer a setting to warn when public API elements lack Doxygen comments, so that developers can enjoy greater certainty that their API is properly, fully documented.

**Comment by albert-github** [comment]
It is a bit hard to tell what is going wrong at your side / what you are missing in your case as there is no example and no used Doxyfile, so:
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.  
- Please also specify the full doxygen version used (`doxygen -v`).

An important question is also:
- When is a function "properly, fully documented"
