### ISSUE TITLE
Unable to document JavaScript

### ISSUE THREAD

**Issue by mcandre** [doxygen/doxygen#8235]
I explicitly enabled the `*.js` file extension, which is not in the default list, and then ran `doxygen Doxyfile`. But the resulting HTML pages fail to present my documentation, it's a blank page with just the title there.

As a workaround, I am using jsdoc.

**Comment by albert-github** [comment]
It is a bit hard to tell what is going wrong in your case as there is no example and no used Doxyfile, so:
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.  
- Please also specify the full doxygen version used (`doxygen -v`).

Most likely cause is that you did adjust `FILE_PATTERNS` but forgot to set the `EXTENSION_MAPPING` with `EXTENSION_MAPPING = js=javascript`.

**Comment by albert-github** [comment]
See also the comment: https://github.com/doxygen/doxygen/issues/7780#issuecomment-857718374

So I think the problem is usage.

**Comment by Mahdipourlotfi** [comment]
@albert-github  👍
**EXTENSION_MAPPING = js=javascript   work for me
on laravel**

**Comment by mcandre** [comment]
Can extension mapping please fix the default language for JS files?

**Comment by albert-github** [comment]
> Can extension mapping please fix the default language for JS files?

What do you mean ?


- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.
- Please also specify the full doxygen version used (doxygen -v).

**Comment by mcandre** [comment]
It's nearly 2025 and Doxygen can't recognize JavaScript files by extension out of the box.
