### ISSUE TITLE
Using symbolic link for output directory

### ISSUE THREAD

**Issue by GingkoFr** [doxygen/doxygen#8236]
Hello,

**Describe the bug**
Would it be possible to have Doxygen properly following symbolic links when used for providing the location of the output directory? (for example the "Doxygen_files" one).

When I do this (generally using a RELATIVE symlink), I very often find Doxygen apparently following the symlink, but actually creating data in a completely unexpected place on my hard disk.

**Expected behavior**
I'd like to have the "Doxygen_files" directory seemingly located in the source directory (as expected by the eventual users of my Subversion system), but actually located elsewhere on the disk, or also for having multiple copies of my source project all referring to the same output file despite they are using the same Doxyfile file.

Question: if I make a RELATIVE symbolic link and if Doxygen try to follow it, is the starting point really the actual location of the symbolic link, as very much expected?

**To Reproduce**
In my last run, for example, I had the source file located into (with some name changes):
```
D:\Devel\Projects\MainProjectName\ProjectInstance
```
and the output directory (using just "." in Doxyfile) seemingly located into:
```
D:\Devel\Projects\MainProjectName\ProjectInstance\Doxygen_files
```
which is is symlinked to:
```
D:\Devel\Projects\MainProjectName\Doxygen\MainProjectName
```
but I actually found the result into:
```
D:\Devel\Projects\Doxygen_files
```
Edit : I just found that the output directory in my Doxyfile file was replaced from "." to "../..", which is something that I never wrote and never expected. Is it possible to hardly lock the output location to "."?

**Version**
Doxygen 1.8.20, Windows 10 professional x64, 20H2 version (French edition)

**Additional context**
It happened sometimes also that I found Doxygen replacing by itself the symbolically linked location by the actual folder location into the Doxyfile file.
This is something that I very much NOT want.
I use symbolic links for a reason, and I sometimes want to distribute the Doxyfile file along with my source files, and I don't want other users seeing the actual structure of my filesystem.

And of course, I don't think there is a mistake in the symbolic itself. If I double click the symbolic link in Windows Explorer, I effectively reach the expected directory.

**Comment by albert-github** [comment]
You wrote:
>  I just found that the output directory in my Doxyfile file was replaced from "." to "../..", which is something that I never wrote and never expected. Is it possible to hardly lock the output location to "."?

- Where did you see this replacement?
- Please share your Doxyfile

**Comment by GingkoFr** [comment]
I saw this in Doxywizard.

Actually, it is possible that I was confused by the Doxywizard settings "Use current settings at startup", which I understood as "Open last file at startup", but it seems it was not the case, apparently Doxywizard saves it elsewhere, so I frequently didn't recover the expected settings.

"Use current settings at startup" is not the same thing, as it happens quite often that the file to open was modified externally (for example by some automatic synchronisation).
Would it be possible to also have a "Open last file at startup" as an alternative choice as "Use current settings at startup"?

Regards …

**Comment by albert-github** [comment]
Where in the doxywizard did you see it? Which commands did you specify beforehand?

I've looked recently quite a bit into the doxywizard, but not with the "Use current settings at startup", maybe here some enhancement in the description is necessary or a new option like "Open last file at startup". Though this new option would be contradiction the "Use current settings at startup" as at that moment there would be 2 incompatible ways of starting and the question would be which one should take precedence. 
When starting the doxywizard one can specify the wanted doxygen settings file, this acts already as "Open last file at startup".

**Comment by GingkoFr** [comment]
I saw it here :
![doxywizard](https://user-images.githubusercontent.com/18695746/101519916-09558d00-3984-11eb-8a6c-309d68bfa526.gif)

I don't see where is the contradiction if you add "Open last file at startup".
In that case, you would have three choices:

1. Use current settings at startup
2. Open last file at startup
3. Do nothing (use default settings) at startup.

If you use current settings, you don't open any file, and if you open last file, you initialize from the defaults first and you don't recover any settings from any other place than the file that you open. There is no matter about thinking of precedence.

Currently, if I want to recover from a file, I have to open it manually. I don't see anything which could act as "Open last file at startup".

Gingko

**Comment by albert-github** [comment]
Strange those `../..` at that place, but to be able to give an answer: Which commands did you specify beforehand? i.e.
- How did you start your doxywizard?
- is the "working directory" OK (can't tell as is is "blacked" out)
- which clicks and input did you give 

- what is in the resulting doxygen configuration file you run?

As you don't want to provide all the details about the project etc. you should create a small test project that shows the problems so we can see all data in an unfiltered way.

**Comment by GingkoFr** [comment]
Actually it is possible that I put "../.." there a long time ago, saving it as "current settings" and then forget it by thinking that I was recovering data from last file each time whereas it was not the case. :-(

So you should better forget it for now until it would eventually reappear, I which case I will not forget to come back.

**Comment by albert-github** [comment]
So for the time being we can see this issue as usage.
