### ISSUE TITLE
How can I disable line number in source browser?

### ISSUE THREAD

**Issue by jjkke88** [doxygen/doxygen#8240]
**Describe the bug**
I just want to only show source code withour line number, because in generated chm file if I want to copy source code, the line number would be copy together.

**Expected behavior**
![image](https://user-images.githubusercontent.com/5785746/101718131-92cba300-3adb-11eb-8366-5820a34a8c53.png)

**Version**
doxygen 1.8.16

**Comment by albert-github** [comment]
The line numbers in the source browser are, for HTML, governed by means of the CSS class `class="lineno"`. You can find the definition of this class in the `doxygen.css` in your HTML directory as:
```
span.lineno {
        padding-right: 4px;
        text-align: right;
        border-right: 2px solid #0F0;
        background-color: #E8E8E8;
        white-space: pre;
}
```

by creating an extra HTML stylesheet like mystyle.css with content:
```
span.lineno {
        display: none;
}
```
and in your doxygen configuration file (Doxyfile) you can point to this file like:
```
HTML_EXTRA_STYLESHEET=mystyle.css
```

**Comment by jjkke88** [comment]
Thanks， it works！
