### ISSUE TITLE
Macro stopped working in 1.8.19

### ISSUE THREAD

**Issue by Mario-Klebsch** [doxygen/doxygen#8251]
Hello,

after upgrading from doxygen version 1.8.18 to 1.8.19, several of my source files are not parsed as they used to be, anymore. I stripped the problem down to a simple demonstration. It uses a macro named foo. The macro is used twice. The first invocation of the macro is not expanded as expected and as in the previous versions, but the 2nd invokation works as expected. Instead of creating a sect2, a para with verbose content is created. :-(

The problem disappers, when I use fewer spaces between the macro and the argument.
I only use XML documentation.

Here is the diff betwenn version 1.9.18 and 1.9.19:

`*** doc-1.8.18/bug_8cpp.xml    2020-12-14 21:29:54.673033274 +0100`
`--- doc-1.8.19/bug_8cpp.xml    2020-12-14 21:29:54.687033338 +0100`
`***************`
`*** 1,5 ****`
`  <?xml version='1.0' encoding='UTF-8' standalone='no'?>`
`! <doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.18">`
`    <compounddef id="bug_8cpp" kind="file" language="C++">`
`      <compoundname>bug.cpp</compoundname>`
`        <sectiondef kind="func">`
`--- 1,5 ----`
`  <?xml version='1.0' encoding='UTF-8' standalone='no'?>`
`! <doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.19" xml:lang="en-US">`
`    <compounddef id="bug_8cpp" kind="file" language="C++">`
`      <compoundname>bug.cpp</compoundname>`
`        <sectiondef kind="func">`
`***************`
`*** 13,22 ****`
`          <detaileddescription>`
`  <sect1 id="bug_8cpp_1sect1">`
`  <title>sect1</title>`
`! <sect2 id="bug_8cpp_1foo">`
`! <title>foo</title>`
`! <para>does not work </para>`
`! </sect2>`
`  <sect2 id="bug_8cpp_1foo">`
`  <title>foo</title>`
`  <para>works </para>`
`--- 13,20 ----`
`          <detaileddescription>`
`  <sect1 id="bug_8cpp_1sect1">`
`  <title>sect1</title>`
`! <para><verbatim>does not work`
`! </verbatim> </para>`
`  <sect2 id="bug_8cpp_1foo">`
`  <title>foo</title>`
`  <para>works </para>`

[bug.zip](https://github.com/doxygen/doxygen/files/5691476/bug.zip)

**Comment by doxygen** [comment]
@Mario-Klebsch Please verify if the referenced commit fixes the problem for you.

**Comment by Mario-Klebsch** [comment]
Hello,

thank you very much for investigating my problem. The fix does cure my problem. :-)

73, Mario

**Comment by albert-github** [comment]
Please don't close the issue as this will be done at the moment of an official release

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
