### ISSUE TITLE
doxmlparser - INamespace doesn't contain IClass information.

### ISSUE THREAD

**Issue by Bambofy** [doxygen/doxygen#8255]
**Describe the bug**
Using the doxmlparser addon (C++) i can get a list of IClass and INamespace however i cannot see how to connect the two.

**Expected behavior**
INamespace could have a list of IClasses inside the namespace or IClass could have a list of INamespaces

**Version**
https://github.com/doxygen/doxygen/tree/7b2e841b3a3d7d787458f236e2447c890cfbf590

**Comment by albert-github** [comment]
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

**Comment by Bambofy** [comment]
Hi, i have just discovered that INamespace contains nestedMembers member which has the compounds i am looking for.

**Comment by albert-github** [comment]
So in fact problem solved and the problem is usage.
