### ISSUE TITLE
Gitlab pages can't update generated docs automatically when new commit run CI/CD jobs

### ISSUE THREAD

**Issue by NingYi0401** [doxygen/doxygen#8272]
**Describe the bug**
Hi, in my own and gitlab paged examples/doxygen [lrespository](https://gitlab.com/pages/doxygen) repositories , when I commit a new change and push it into master, CI/CD will run job successful, but after deploying the html file folder, the docs in the gitlab.io can't be changed by the new commit. Even I modify the Doxyfile project number and run doxygen in gitlab server, the docs generated can't be changed as well.

**Expected behavior**
Every time i push a new commit, CI/CD will run automatically( which has runned correctly ),and then the websites(github.io) will generate the new APIs and update doxygen html in websites automatically ( which has not been done correctly)

**Screenshots**
![图片](https://user-images.githubusercontent.com/24950429/102972993-fa9bd800-4536-11eb-81dc-d94a40916dd1.png)
![图片](https://user-images.githubusercontent.com/24950429/102973059-143d1f80-4537-11eb-9704-dc430b86d387.png)
![图片](https://user-images.githubusercontent.com/24950429/102973093-2454ff00-4537-11eb-877b-23f5050ae178.png)

**To Reproduce**
[gitlab repository can be fork](https://gitlab.com/pages/doxygen)

**Version**
I find the bug in gitlab CI/CD, every time i will apt-get update && apt-get doxygen

**Additional context**
Someone opens this issue in gitlab respository, but nobody answers, I can't find any more informations in the internet, please help me to solve this problem.You can run the respository easily, change any C source code or any Doxygen setting and push it to master, you can find the gitlab pages cannot be changed even you run the CI/CD job successsfully. Thanks again.

**Comment by albert-github** [comment]
You will have to separate here 2 possible problems:
- is it a doxygen problem
- is it a gitlab (upload) problem.

Regarding the "Is it a doxygen problem":
- which version of doxygen are you using
- when running doxygen locally on the sources of the project (as would be don by the CI / CD) are the results OK?

**Comment by NingYi0401** [comment]
I hope I can help you by giving more informations below. My English is not good, plz don't be unhappy if my explaination is wrong.

1. I check the gitlab CI/CD pages build log, when I run apt-get doxygen, the server will install doxygen(1.8.18-r0)
2. I test my local project's doxygen exe(win 10 arm64 version), it's 1.8.20, it can run easily with right local html output.
3. I fork your offical project and clone into my local workround, the version of doxygen is 1.8.9.1, I change my local file and run doxygen locally, the result is right as well. When I push the doxygen output into gitlab, then the websits will be right.
4. And more infomation maybe help, I use hexo to generate my blog in gitllab.io at the same time, that respository can build CI/CD task and generate my html correctly.
5. I can provide my CI/CD tast log for you, some lines may catch my attention, it says:"Notice: Output directory 'documentation' does not exist. I have created it for you." It seems like my exist file folded can't be found by doxygen, but it can be moved into public, that's so strange..

Please get in touch with me, Thanks very much.

**Comment by NingYi0401** [comment]
[Build log](https://gitlab.com/pages/doxygen/-/jobs/34823531)

**Comment by albert-github** [comment]
1. The CI/CD page on gives as version 1.8.13-r0 (not 1.8.18-r0), but this is irrelevant here.  It says
    > Uploading artifacts to coordinator... ok            id=34823531 responseStatus=201 Created token=xPbfWvdB

    looks like the "coordinator" has to do something.
2. So the local HTML output looks OK
3. A bit of an old version (1.8.9.1) when you forked the repository, maybe you need to update your local copy. Looks a bit like you are running the default installed version of doxygen on your system. The output look like to be OK, so no real problem.
4. hexo? unknown
5. You can, most probably, overcome this warning by by issuing a `mkdir documentation` befor starting doxygen

As the documentation as generated locally is OK it looks like the problem lies outside of doxygen and more on the uploading on gitlab side / gitlab showing side.

I don't think this is a doxygen problem.

**Comment by NingYi0401** [comment]
Ok, I know what you mean now, that's a good advice"I don't think this is a doxygen problem." Thanks a lot anyway. Please close the issue.

For the other people may search this question ,I want add 2 more things below:

1. mkdir -p doxygen/documentation/html as soon as you install doxygen before you run doxygen Doxyfile is not useful, the log may also show the file folder does't exist.
2. Gitlab repository's owner / collaborators seem like working for gitlab,they don't update that example repository anymore which causes this question for me. I can't get touch with them as well.

Anyway, thank you very much. I don't start a new issue in github very much. You are a nice guy, thanks for your help. Good luck!

**Comment by albert-github** [comment]
Regarding point 1. This should not happen, are you sure you didn't run the `mkdir -p` command inside the `doxygen` directory and thus creating here the tree `doxygen/documentation/html` instead of the intended `documentation/html`. Note also that the `html` is not necessary, it is done automatically (based on (`HTLM_OUTPUT`) the mentioned warning is about the directory mentioned in `OUTPUT_DIRECTORY`

**Comment by NingYi0401** [comment]
@albert-github Hi，bro. I don't know whether should I report my latest progress here. But I still think I should add an answer for this question.

Finnal I found the reason causes this question.

- Gitlab uses docker to run doxygen
- Docker's default relative path is the filepath stores .git
- But in doxyfile the relative path is where itself is stored

Which means OUTPUT_PATH = documentation this command may cause different result in my local host and gitlab server.
I run this doxyfile and will make an folder named documentation in the path ./doxygen/( doxyfile in the same path ./doxygen/doxyfile in the meanwhile ).But when it comes to the docker, the path means it will create the folder ./documentation/html and so on. So I must make it works in ./doxygen/documentation/ and mv ./doxygen/documentation/html into public/, so I have to set OUTPUT_PATH = ./doxygen/documentation, and INPUT = . instead of INPUT = ../ 

After changing the settings in doxyfile, I can genernate the index.html correctly in the end. Although I can't use the Doxyfile locally.. But it's still a good ending for me, becasue I can achieve my objective now.

Thanks you all again. Happy New year~

**Comment by albert-github** [comment]
> Although I can't use the Doxyfile locally...

- You could probably use an environment variable for this in `OUTPUT_DIRECTORY` and set this environment variable properly in the different environments.
