### ISSUE TITLE
Literal code with `@example.com` in Markdown interpreted as an instruction

### ISSUE THREAD

**Issue by vanrein** [doxygen/doxygen#8278]
**Describe the bug**
My Markdown documentation mentions the customary example domain names `john@example.com` or `@example.com`.  However, in spite of this being backquoted for literal processing, the AT and the domain name are treated as an instruction by Doxygen.  Document processing breaks off at this point!

How can I use the typical example domain names in literal code examples without having them interpreted?  We also setup containers with these names pre-installed for our demos, so they are not so easily replaced.

**Expected behavior**
Since the Markdown encoding for literal code was used, I would expect it to not be interpreted by Doxygen.

I tried double backticks, double AT, backslash before AT, but nothing works.  I even tried `ALIASES = example="@example"` to overrule it, but to no avail.

**To Reproduce**
Markdown document: https://gitlab.com/arpa2/arpa2common/-/blob/a2b736cf6fae3c2587c1b403045d466c600d811a/IDENTITY.MD
Included in Doxygen with `FILE_PATTERNS = *.h *.MD`.
Doxygen file: https://gitlab.com/arpa2/arpa2common/-/blob/v2_id_acl/doc/arpa2common.doxygen
Run from the repository root as `doxygen doc/arpa2common.doxygen`.

**Version**
1.8.13 on Debian stable, amd64.

**Additional context**
Running doxygen in a `chroot` build environment.  No hints that this causes the problem, it is a logical problem.

**Comment by albert-github** [comment]
Please always attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent. 
The references given here are hard to get and are not persistent.

The doxygen 1.8.13 version is a bit an older version 29 December 2016 and the current version is 1.8.20

When looking at the output of 1.8.13 the output is truncated at the mentioned point. When running with doxygen 1.8.20 the output looks OK to me.

I think the problem has been solved in the mean time.

Note that in the settings there is also the `ALIASES` setting `example=@example`, a bit unclear why this is used (has no effect on the output though)

Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/5744311/example.tar.gz)

**Comment by vanrein** [comment]
Yes, I can see that an isolated example is more workable.  Apologies.
[doxytest.zip](https://github.com/doxygen/doxygen/files/5744319/doxytest.zip)

This is a default generated `Doxyfile` and small `demo.md`.

In the output, `html/md_demo.html` breaks off and `html/examples.html` continues, or at least it tries to.  This is expected behaviour in the normal running text, but I need some way to avoid it in the literal code.

Thanks!

**Comment by albert-github** [comment]
- Looks like the zip file is empty
- Did you test your example with the 1.8.20 version?

**Comment by vanrein** [comment]
1. The zip works for me when I download it again.  Normally don't use it, so I don't know if there could be portability issues.
 2. I tried 1.8.20 in parallel.  Yes indeed, it solves the issue.  Thanks for pointing at it!

For me, this solves the problem.  I suppose I can close the issue then.  Thank you, Albert, that was really quick!

**Comment by albert-github** [comment]
I think I know what the problem is my automatic download fails as is says that it contains malware (I cannot download my own example either), when using wget it is OK (your example and mine).

**Comment by doxygen** [comment]
Seems like something that has been fixed since 1.8.15, by reversing the order of markdown processing and the comment command processing (commentscan).

**Comment by vanrein** [comment]
Hi,

> Seems like something that has been fixed since 1.8.15, by reversing the order of markdown processing and the comment command processing (commentscan).

...and Debian stable comes with 1.8.13.  Yes, that must be it.  I added it to our source build system and am happy now.

Hartelijk dank, heren, geweldige steun.  Zo krijgen we de wereld nog wel eens helemaal over op open source :)

-Rick (internetwide.org)
