### ISSUE TITLE
Error on ALIAS declaration without quotes

### ISSUE THREAD

**Issue by thom-sch** [doxygen/doxygen#8282]
**Describe the bug**
doxygen reports an error message like

> error: Illegal ALIASES format 'b'. Use "name=value" or "name{n}=value", where n is the number of arguments

if declaration contains a comma "," and is not surrounded with double quotes.

**To Reproduce**
Create a configuration file with 2 lines

> ALIASES                += test=a,b
> ALIASES                += "test=x,y"

The first line will generate the above error executing it on command line.

If you load this into doxywizard both(!) lines generate this error.
The reason seems to be:
1 doxywizard seems to remove the quotes in the second line on loading/before calling doxygen.
2 Additionally on loading this file doywizard doesn't recognize the first line correctly splitting it into 2 lines after the comma "," (may be the same behavior as doxygen does), s. attached screenshot.

**Version**
Doxygen version used: 1.9.0 (71777ff3973331bd9453870593a762e184ba9f78)

Also tested with doxygen V.1.8.15, V.1.8.18, V.1.8.19, V.1.8.20 with same result

Version 1.8.14 seems to be ok!

[Test11_quotes.zip](https://github.com/doxygen/doxygen/files/5748001/Test11_quotes.zip)

Regards from Meerbusch
Thomas Schneider

**Comment by albert-github** [comment]
Looks like there are different problem as with the doxywizard it looks like the `,` was longer supported than with doxygen itself.

The "problem" was introduced with #6563 (and also something has been done in #7603).
I think that at that moment the problem with an `,` inside an `ALIASES` with quotes has been overlooked, the syntax `test=a,b` will not work (nor will it in the future). 

The handling of the `,` has to be corrected, in the usage by doxywizard, but also for commands like `doxygen -x` and `doxygen -g`.
 
It also looks like that `condensed show configuration` doesn't work for `ALIASES` in the doxywizard.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #8284

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.1.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
