### ISSUE TITLE
Doxygen crash on Windows when INLINE_SIMPLE_STRUCTS=YES

### ISSUE THREAD

**Issue by billziss-gh** [doxygen/doxygen#8291]
**Describe the bug**

Doxygen crashes on Windows with an Access Violation (0xc0000005) when INLINE_SIMPLE_STRUCTS=YES.

**Expected behavior**

Doxygen should not crash.

**To Reproduce**

Please try the attached zip file which reproduces the problem:

- When INLINE_SIMPLE_STRUCTS=YES Doxygen crashes.
- When INLINE_SIMPLE_STRUCTS=NO Doxygen produces the expected output.

[test.zip](https://github.com/doxygen/doxygen/files/5753332/test.zip)

**Version**

- Doxygen: 1.9.0
- Platform: Windows 10 20H2 64-bit

**Comment by doxygen** [comment]
@billziss-gh Can you please verify if the proposed fix solves the issue? If you don't want to build doxygen yourself, you could try one of the executables available here https://github.com/doxygen/doxygen/actions/runs/452335949 under Artifacts.

**Comment by billziss-gh** [comment]
@doxygen I tried the "Windows Latest MSVC Release" and it appears to resolve the issue. I no longer observe any crash in the larger project where this problem originated.

I will do some additional testing tomorrow morning, but this appears to be resolved. **Thank you for the quick turnaround.**

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.1.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Comment by billziss-gh** [comment]
I can confirm that version 1.9.1 of Doxygen resolved this issue.

Thank you.
