### ISSUE TITLE
Unexpected Warning "end of file while inside a group" when nesting Module and Member groups

### ISSUE THREAD

**Issue by rstahn** [doxygen/doxygen#8310]
**Describe the issue**
Both Doxygen 1.8.20 and 1.9.0 produce a warning "end of file while inside a group" for a simple file containing both a module group and a member group:
```
//! @file

//! @addtogroup Config_Defines
//! @{

//! @name GPIO_Input_A
//@{

//! Input A uses pin B4
#define HAL_GPIO_CFG_DI_A_PORT              B
#define HAL_GPIO_CFG_DI_A_PIN               4
#define HAL_GPIO_CFG_DI_A_PUPD              HAL_GPIO_PUPD_PULLUP

//@}

//! @}
```

Similar to #8267 I struggle to identify the root cause of the warning.
The warning disappears, when the `@name` is removed from the member group.

**To Reproduce**
I have attached a minimal example reproducing the warning: [grouping_warning.zip](https://github.com/doxygen/doxygen/files/5775574/grouping_warning.zip)

**Version**
Reproducable with doxygen 1.8.20 and 1.9.0

**Comment by albert-github** [comment]
It is indeed a bit strange that you get a warning.
The lines `//@{` and `//@}` should not be taken into consideration at all (In the past this happened though, this changes in 1.8.16).
When changing the lines `//@{` and `//@}` into `//!@{` and `//!@}` the message disappears.

Still it look like to me a bogus warning that should not be present at all.

**Comment by rstahn** [comment]
> The lines //@{ and //@} should not be taken into consideration at all 
Oh, okay. Apparently I have got this from an outdated Doxygen documentation on the web.
I should pay more attention on using the latest documentation (instead of using the first web search result)...

> When changing the lines //@{ and //@} into //!@{ and //!@} the message disappears.
Is there a difference between `//!@{` and `//! @{` (note the whitespace) regarding grouping?
Or is it the same mechanism for both module groups and member groups?

**Comment by albert-github** [comment]
There is no difference between `//!@{` and `//! @{`.

**Comment by rstahn** [comment]
Okay, thanks. Then I have overinterpreted the [grouping examples](https://www.doxygen.nl/manual/grouping.html) while trying to fix the warning. ;-)

**Comment by albert-github** [comment]
After reading again the documentation of `@name`:
> \name [(header)]
> 
> This command turns a comment block into a header definition of a member group. The comment block should be
followed by a `///@{ ... ///@}` block containing the members of the group.

It is clear that that the `///@{` and `///@}` (or alternatively `//!@{` and `//!@}`) is missing. 
So, in my opinion, the problem is (contrary to my earlier comment "Still it look like to me a bogus warning that should not be present at all.") not a bug but usage.

**Comment by rstahn** [comment]
I agree - although it is probably hard to relate a misplaced `@name` command with the warning issued at the end of the file.
It would be helpful for the user if Doxygen could issue a more specific warning for such cases.
