### ISSUE TITLE
"Return Type" of define is accumulated

### ISSUE THREAD

**Issue by lukaspj** [doxygen/doxygen#8358]
**Describe the bug**
The type of defines seems to accumulate over multiple "define" definitions:
![image](https://user-images.githubusercontent.com/2369614/105849560-d5403500-5fe0-11eb-8f2c-76c8d9e6d5b8.png)

The definition of `DefineConsoleType` can be found here:
https://github.com/TorqueGameEngines/Torque3D/blob/800ddd8778aa703e185998c48c3e7c625739259f/Engine/source/console/dynamicTypes.h#L257-L261

**Expected behavior**
Would expect the type to be empty in all the rows.

**To Reproduce**
Here is the simplest MWE I could come up with:
https://gist.github.com/lukaspj/c4f524ce7da7d2211a96a86a72973252

Example output:
[doxygen.zip](https://github.com/doxygen/doxygen/files/5874763/doxygen.zip)

Should give something like this:
![image](https://user-images.githubusercontent.com/2369614/105876594-69b99000-5fff-11eb-90c7-32526eb61650.png)

**Version**
Doxygen: 1.8.17 (fetched via apt-get) and 1.9.1 (downloaded from website)
Running inside a Docker container with Ubuntu 20.04 as base

**Additional context**
I don't mind poking around in Doxygen myself and see if I can solve it myself, but I'm not familiar with the code-base and could really use some guidance. Also my time is limited, so I might not be able to solve it.

**Comment by lukaspj** [comment]
This may be because it's seen as a function and not as a `define` judging from the XML output:
```xml
      <memberdef kind="function" id="group__console__system_1gab88aacbf0c46ae5a1a89cbbd877dffe3" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type></type>
        <definition>DefineConsoleType</definition>
        <argsstring>(TypeBool, bool) DefineConsoleType(TypeBoolVector</argsstring>
        <name>DefineConsoleType</name>
        <param>
          <type>TypeBool</type>
        </param>
        <param>
          <type>bool</type>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="Engine/source/console/consoleTypes.h" line="64" column="1"/>
      </memberdef>
```

**Comment by albert-github** [comment]
The current doxygen version version is 1.9.1.
- the table presented in your issue how is this generated (I didn't see any html files as `GENERATE_HTML=NO`)?
- the xml snippet, from which file is this?
- you wrote "Would expect the type to be empty in all the rows.", why? I see some, in my opinion, strange `EXCLUDE_SYMBOLS`:
  ```
  EXCLUDE_SYMBOLS        = bool \
                         "F32 *" \
                         float \
                         "S8 *" \
                         "Sample *" \
                         "U8 *" \
                         "ValueType *" \
                         "void **"
  ```
  but a type is not directly a symbol.

**Comment by lukaspj** [comment]
I updated with a better MWE.

To answer your questions:
1. I will try and see if updating helps
2. Sorry, the Doxyfile was a little bit off, new MWE should be better
3. The XML snippet was from the XML output, but it's easier to look at in the new MWE
4. I would expect the type to be empty because why would a `define` have a type? It's just a macro.

**Comment by lukaspj** [comment]
Tested it in 1.9.1 and it is still an issue

**Comment by albert-github** [comment]
The provided MWE in a gist (in future please provide the example as a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent. ) is not valid C / Cpp code and thus doxygen gets confused.

When adding a proper define **and** setting `MACRO_EXPANSION        = YES` I think, part of . the problems might be solved.
Another option is, when `MACRO_EXPANSION        = NO`, to add a semicolon at the end of all "calls" to COnsoleType` / `DefineConsoleType` etc.

**Comment by lukaspj** [comment]
Fair point, the following header file can be used as well as a MWE:
```cpp
#define DefineConsoleType(type, nativeType) nativeType type;

DefineConsoleType(TypeS32, int)
DefineConsoleType(TypeU32, unsigned int)
DefineConsoleType(TypeS16, short)
DefineConsoleType(TypeU16, unsigned short)
DefineConsoleType(TypeBool, bool)
```

MWE packaged here with output:
[doxygen.zip](https://github.com/doxygen/doxygen/files/5875982/doxygen.zip)

Screenshot:
![image](https://user-images.githubusercontent.com/2369614/105903429-258ab780-6020-11eb-931b-ac1ec7c0278a.png)

**Comment by lukaspj** [comment]
I agree that MACRO_EXPANSION will probably solve the issue, however that will cause the generated documentation to blow up in my specific example (it uses macros for code-generation a lot).
Adding a semi-colon at the end seems to fix it as well, but this still seems like something Doxygen _should_ support (I'm not sure whether it's even possible to support it though)

**Comment by lukaspj** [comment]
This is not a blocker for me btw, I can work-around the issue or ignore those defines completely, just thought I would report the bug as I didn't find any documentation of this as a known error.

**Comment by albert-github** [comment]
Another idea:
```
MACRO_EXPANSION        = YES
EXPAND_ONLY_PREDEF     = YES
PREDEFINED             = "DefineConsoleType(x,y)=DefineConsoleType(x,y);"
```
and make `PREDEFINED` for all relevant function calls.

**Comment by lukaspj** [comment]
Sorry for the long turn-around on this.

I can confirm that using the `EXPAND_ONLY_PREDEF` and `PREDEFINED` is the best solution for this issue. At least for me.
