### ISSUE TITLE
Generate link to relevant line of source code

### ISSUE THREAD

**Issue by tdegeus** [doxygen/doxygen#8385]
I have documented my code with doxygen. The generated docs consist of:

*   a page with the documentation as I put between `/** ... */`, and 
*   a page with the source-code itself (without the documentation between `/** ... */`). 

Now my question is: Is there a way to generate links such that one can reach the page with the source code opened on the relevant line directly from the documentation?

-------------

To show visually what I would like to obtain:

1.  I would like to have a button "Go to source" (shown in red, decorated with an arrow just for here).

    [![enter image description here][1]][1]

2.  Which would land me on the right line of the source code (possibly with a highlight, as shown here).

    [![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/e032m.png
  [2]: https://i.stack.imgur.com/RCkiz.png

------

Reference: https://stackoverflow.com/q/66209616/2646505

**Comment by albert-github** [comment]
Is it necessary to have the link in the top right of the "blue" bar? or would a textual reference be sufficient?

**Comment by tdegeus** [comment]
A textual reference would be fine!

**Comment by albert-github** [comment]
So for just the selected items and not like with `SOURCE_BROWSER=YES` for all items.

**Comment by tdegeus** [comment]
Ah, now I understand what you mean, sorry... Indeed, it would be great if this would be an option that one can switch on for **all** items. Now, how the layout should be is another matter (I thought you meant that).

**Comment by tdegeus** [comment]
That is indeed exactly what I meant. Sorry for not finding this option!

**Comment by tdegeus** [comment]
For me the `SOURCE_BROWSER=YES` does exactly what I want, so I'll close this issue. Thanks for your help!

**Comment by 10tailesSeer** [comment]
I can't understand how `source_browser`  helped you :((. I have that option turned on, but i can't figure how to create such a link without specifying line

**Comment by albert-github** [comment]
@10tailesSeer 
Looks a bit you are looking for something different than intended in this issue, it is better to start a new discussion / issue for your problem. This new discussion / issue should also include (from there standard requests(:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).
- Please also specify the **full** doxygen version used (`doxygen -v`).
