### ISSUE TITLE
Latex cannot able to accept .txt files as its contents

### ISSUE THREAD

**Issue by KITTUKRISHNA5** [doxygen/doxygen#8391]
Why latex cannot able to parse .txt format files into it to prepare a pdf file with the contents of that .txt file present in the generated .pdf file

\verbatiminput{../../foo.txt}

is not working inside the .tex file (Latex file)

Please find me a way to include the .txt file inside the Latex file so that the generated .pdf file contains the information of the .txt file inside it.

Note: I dont need any other formats but the .txt format into consideration

**Comment by albert-github** [comment]
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.  
- Please also specify the full doxygen version used (`doxygen -v`).

**Comment by KITTUKRISHNA5** [comment]
**The below lines are in my Latex file:**

\usepackage{verbatim}
\begin{small}          % \tiny  5pt \small  9pt  \large  12pt  \Large  14pt \huge  20pt   \Huge
      \verbatiminput{ForAppl_Description}
\end{small}

**The Doxygen version i am using is:**
Doxygen version 1.8.11
Copyright Dimitri van Heesch 1997-2015

**Comment by albert-github** [comment]
How did you generate the LaTeX file.

As with your previous questions with this information it is not possible to reproduce your problem. Furthermore 
- in the 1.8.11 version of doxygen I don't see anywhere the term `\verbatiminput` so probably added by yourself

**Comment by KITTUKRISHNA5** [comment]
I am sorry in this scenario i am only using a Latex file but not any doxygen configuration file 
Hence this question is entirely related to Latex

**Comment by albert-github** [comment]
So the question is not a doxygen problem and should probably be more appropriate at https://tex.stackexchange.com/
