### ISSUE TITLE
Skip (don't recreate) existing unchanged files

### ISSUE THREAD

**Issue by ynikitenko** [doxygen/doxygen#8401]
This is not a bug, but a feature request. I use `doxygen` in a Makefile to generate documentation for ROOT (which is rather large).
It takes a lot of time, especially during notebooks conversion like

> [NbConvertApp] Converting notebook ~/rootdoc/notebooks/TMVAMulticlass.C.ipynb to notebook

I'd like to have ability to rerun `doxygen` and not to generate files that exist and are unchanged.

This was largely discussed on Stackoverflow (e.g. [Why does doxygen always reprocess every file?](https://stackoverflow.com/questions/28628348/why-does-doxygen-always-reprocess-every-file)), but I didn't find any request here (the closest is probably https://github.com/doxygen/doxygen/issues/8390). People reply that it's a fundamental design of doxygen, but maybe it could be solved?

**Comment by albert-github** [comment]
It would be possible that e.g. a reference in `file1` is not resolved at first but later by adding a `file2` this reference is resolved, so `file1` didn't change but its result will change. This dependency between the files is unknown .

This is fundamentally impossible in doxygen.

**Comment by ynikitenko** [comment]
Sorry, my understanding of doxygen is very poor. Can't it store some hashsums to see that the source files were unchanged? If they were not, then all reference therein should also be unchanged...

**Comment by albert-github** [comment]
It is not the reference in the `file1` that changes but the resulting reference in the output of `file1` and this resulting reference is depending on `file2`, so a hash wouldn't help.
