### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by tdegeus** [doxygen/doxygen#8404]
It would be great to have an officially supported (and integrated) dark theme!

**Comment by albert-github** [comment]
A theme is, of course, a matter of taste and the theme provided by doxygen is just a suggestion.
The HTML theme is steered by means of the settings `HTML_STYLESHEET`, `HTML_EXTRA_STYLESHEET`, `HTML_COLORSTYLE_HUE`, `HTML_COLORSTYLE_SAT, `HTML_COLORSTYLE_GAMMA` and can be set by the user (see the documentation: Customizing the output -> Overall Color i.e. https://www.doxygen.nl/manual/customize.html#minor_tweaks_colors and https://www.doxygen.nl/manual/config.html#cfg_html_extra_stylesheet).

A first setting could be invert all colors (and maybe adding a body / some background colors).
Similar getting new Hue, Sat and Gamma values.
I'm not 100% sure if all images automatically will be OK, might be that here some extra effort is required.

Did you see anything unexpected ?

**Comment by tdegeus** [comment]
Thanks for the suggestions, I will try to use them to get something dark! 

I do understand that there are as many styles as there are users (in this case documentation readers). And thus, it is probably a minefield to maintain or package different styles. At the same time, I do think that having one bright and one dark default style does not seem unreasonable. I.e. the user can still create whatever style it likes, and there could still be \infty themes that are not shipped with doxygen. But it would at least give the most basic of choices in the 'default' environment.

**Comment by doxygen** [comment]
@tdegeus I agree this is not an unreasonable request given that many desktop environments nowadays also have these themes. I wanted to wait with adding new styles until I finished the work on the Django style template engine (which would make it easier to further fine tune the output), but this probably takes too long. If you (or someone else) has something that can be used as a starting point then that would already help so please share.

**Comment by tdegeus** [comment]
Thanks @doxygen ! Should I have something sharable I will.

**Comment by arwedus** [comment]
I've been looking for some theme that imitates the look of readthedocs, to no avail. Probably there are lots of nice custom themes out there, but not publicly available e.g. on github :(. I've found a doxygen bootstrap theme once, but that was unmaintained and broken. @tdegeus if you created a little github repo for this theme, @doxygen could link it on doxygen.nl (e.g. add a "skins / HTML themes" section to https://www.doxygen.nl/helpers.html ).

It has become quite popular to use Doxygen as a back-end and Sphinx+breathe as a front-end just for nicer looks. I've tried the combination and find it to complicate things. Unless you actually want to use the concept of Sphinx for your documentation, it's probably preferable to just tune the Doxygen to the desired look.

**Comment by jothepro** [comment]
I've written a theme for myself that supports dark mode and is heavily customizable. @tdegeus maybe you want to give it a try? I'm looking forward to your feedback! 😊
https://jothepro.github.io/doxygen-awesome-css

**Comment by albert-github** [comment]
Doxygen has support for dark themes now in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
Note: the option has been renamed to `HTML_COLORSTYLE` instead of `HTML_DARKMODE`.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.5.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Comment by tdegeus** [comment]
It is really amazing that the dark theme is here! Is (will) there (be) an option to switch between light/dark, as there is for example in this external project : https://github.com/jothepro/doxygen-awesome-css ?

**Comment by albert-github** [comment]
Have a look at the setting of HTML_COLORSTYLE, this can have the following settings:
- LIGHT Always generate light output., 
- DARK Always generate dark output., 
AUTO_LIGHT Automatically set the mode according to the user preference, use light mode if no preference is set
(the default).,
- AUTO_DARK Automatically set the mode according to the user preference, use dark mode if
no preference is set. 
- TOGGLE Allow to user to switch between light and dark mode via a button..

So I think you are looking for the `TOGGLE` where there will be a toggle button ("sun") in the top right corner like:

![image](https://user-images.githubusercontent.com/5223533/189673863-1130bbd9-6396-4497-b5c3-a06c8c76027b.png)

**Comment by tdegeus** [comment]
Great, it work nicely locally, thanks. However, it does seem to have an issue on my GH pages : https://tdegeus.github.io/GMatElastoPlasticQPot/ . When I click the button nothing happens

**Comment by albert-github** [comment]
Strange as when I try your pages it switches between light and dark mode (under Firefox).
- Which browser did you use?
- caching effect?

**Comment by tdegeus** [comment]
Cleaning the cache resolved the issue. Sorry for the scatter.

**Comment by obfuscated** [comment]
Can you please clarify where is the preference stored for the AUTO_LIGHT and AUTO_DARK modes?
I've set it to AUTO_LIGHT and it generated a dark documentation and I don't remember setting a doxygen preference for this.

Is it possible to select the default for the TOGGLE mode? Currently it is dark for me the first time I load the documentation, but I would prefer if the default is light and I can toggle to dark.

**Comment by albert-github** [comment]
@obfuscated This is a browser  preference, the documentation states:

> HTML_COLORSTYLE The HTML_COLORSTYLE tag can be used to specify if the generated HTML output should
be rendered with a dark or light theme.
Possible values are: LIGHT always generate light mode output, DARK always generate dark mode output,
AUTO_LIGHT automatically set the mode according to the user preference, use light mode if no preference
is set (the default), AUTO_DARK automatically set the mode according to the user preference, use dark mode
if no preference is set and TOGGLE allow to user to switch between light and dark mode via a button.
>
> The default value is: AUTO_LIGHT.


Maybe the line:
> use light mode if no preference is set

should have read:
> use light mode if no browser preference is set

**Comment by obfuscated** [comment]
@albert-github Yes, the second version is better. But if you can link to some documentation what is this browser preference it will be best. Is the default TOGGLE behaviour following this preference, too?

**Comment by albert-github** [comment]
The setting of the browser preference is outside the scope of doxygen as it is browser dependent.
By head I think by default the `TOGGLE` will follow the browser preference.

**Comment by obfuscated** [comment]
> The setting of the browser preference is outside the scope of doxygen as it is browser dependent.

This doesn't seem to be true. Doxygen is generating html according to some spec and it is using some feature from the spec to define light and dark themes and then select a default. Documenting what is this feature in the spec would probably be helpful.

Closing the tab and reopening it in firefox seems to reset it the toggle.

**Comment by doxygen** [comment]
@obfuscated Sounds you like to know how dark mode works in general. A good intro can be found here: https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/. The AUTO modes in doxygen follow the browser/OS preference (which a fallback to dark or light depending on the choice).
