### ISSUE TITLE
ignore "retval void"

### ISSUE THREAD

**Issue by Bacchushlg** [doxygen/doxygen#8406]
I use the STM32 libraries.
They create code with doxygen-conform comments except for one detail: the create comment lines for void retvals.
This actually creates warnings from doxygen (documented empty return type).

It would be fine to ignore such cases by demand through a flag.

**Comment by albert-github** [comment]
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.  
- Please also specify the full doxygen version used (`doxygen -v`).

**Comment by Bacchushlg** [comment]
simple example:

/**
  * @brief System Clock Configuration
  * @retval None
  */
void SystemClock_Config(void)
{
}

Doxygen warning:
documented empty return type of SystemClock_Config

Doxygen version is 1.9.1

**Comment by albert-github** [comment]
I think this is a correct warning, you are documenting a return value of a function that doesn't have a return value (doxygen is ignorant about the meaning of e.g. a word like "None").

You could add to your `Doxyfile`:
```
ALIASES = myretval="\par <b>Return values</b> ^^"
```

and change in your code:
```
@retval None
```
into
```
@myretval None
```


Note: with your example and a default `Doxyfile` I don't get a warning, so some other setting is probably involved as well.

**Comment by Bacchushlg** [comment]
Genial. This is what I needed (the Alias version). Works perfectly.
Do you have a similar solution for this?

```
/**
  * @brief  Setup the microcontroller system.
  * @param  None
  * @retval None
  */

void SystemInit(void)
{
}
```
I get: 
argument 'None' of command @param is not found in the argument list of SystemInit(void)

**Comment by albert-github** [comment]
Probably a same type of sort of alias::
```
ALIASES = myparam="\par <b>Param</b> ^^"
```

Disclaimer: I didn't try.

**Comment by Bacchushlg** [comment]
My problem here: the code including header is created from the framework, and re-created each time I re-run the wizzard. So no chance to change the header contents. 
This was the advantage of your first solution: add an alias. 
But in this case, the entry is just "@param  None", and I cannot alias "param".

But it's really a minor problem - let's forget about this.

**Comment by albert-github** [comment]
What kind of problems do you have with creating an alias for `@param`?

**Comment by Bacchushlg** [comment]
An alias for param would affect all param entries that I created.
So, none of them would be documented.
Or am I wrong?

**Comment by albert-github** [comment]
It would indeed have an effect on all `@param` usages, and placing each usage of a `@param` a separate block with with an own **Parameters** heading and just one parameter or the word "None".

The actual problem lies, in my opinion, probably with the framework that should not emit documentation lines in case of a void function (for the return value) or for a parameter when there is no parameter. These things are already clear from the definition of the function.

Note that for cpp functions the usage of void as argument placeholder is not encouraged / necessary.

**Comment by Bacchushlg** [comment]
I completely agree that this is a problem of the framework.
I already tried to make them change the affected comments - but its not handled as major problem (which I can understand).
But anyway: my major problem was the initial one - and it is solved by your solution.
