### ISSUE TITLE
Heirarchy of subgroups in LaTex, RTF is wrong (Origin: bugzilla #123963)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#842]
status NEW severity *major* in component *general* for *---*
Reported in version *1.5.3-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[hide-indices-small-toc-1.4.3.patch](https://sourceforge.net/projects/doxygen/files/attachments/bug123963_49223_hide-indices-small-toc-1.4.3.patch/download/download)_ (ID 49223)

On 2003-10-06 16:39:44 +0000, Nara Won wrote:

    I made subgroups and HTML output made nice tree for the heirarchy of 
    subgroups.
    
    But LaTex and RTF output have wrong heirarchy of subgroups or flattened 
    the subgroups so the outputs have wrong chapters.

On 2005-07-15 11:37:15 +0000, Michael McTernan wrote:

    Created attachment 49223
    Patch to prevent flattened index in LaTeX contents

On 2005-07-15 11:41:05 +0000, Michael McTernan wrote:

    I found something that sounds to be the same and posted the following with a
    patch to doxygen-develop on 7/7/2005.  I've also added the patch to this
    bug.
    
    Original message to doxygen-develop:
    
    I've been generating some beautiful LaTeX documentation but have found that
    the
    table of contents that LaTeX adds is sometimes a little big and flat!  
    
    For example, if LATEX_HIDE_INDICES=NO, the generated table of contents
    duplicates the section indices, and additionally flattens out module
    documentation.  The following is test input that illustrates this:
    
    /** \defgroup Group0 This is group 0.
     @{ */
    /** \defgroup Group1 This is group 1.
    @{ */
    /** \defgroup Group2 This is group 2.
    @{ */
    /** \defgroup Group3 This is group 3.
    @{ */
    
    int main();
    
    /** @} */
    /** @} */
    /** @} */
    /** @} */
    
    With this, the modules index (page 5 if this is the only input file) looks
    like
    the following:
    
    Chapter 1
    Module Index
    1.1 Modules
    Here is a list of all modules:
    This is group 0. . . . . . . . . . . . . . . . . . . 3
       This is group 1 . . . . . . . . . . . . . . . . . 4
          This is group 2. . . . . . . . . . . . . . . . 5
             This is group 3 . . . . . . . . . . . . . . 6
    
    Perfect!  But the main index (page 3) appears as the following:
    
    Contents
    1 Module Index 1
       This is group 0. . . . . . . . . . . . . . . . . . 3
       This is group 1. . . . . . . . . . . . . . . . . . 4
       This is group 2. . . . . . . . . . . . . . . . . . 5
       This is group 3. . . . . . . . . . . . . . . . . . 6   
    2 Module Documentation 3
    
    The hierarchy is lost on LaTeX, and these items are reproduced on page 3
    under
    the Module Index in any case :)  The following patch makes the LaTeX
    generated
    \tableofcontents limited to the top level headings only, such that only the
    main
    sections are bought out and the contents appears as the following:
    
    Contents
    1 Module Index 1
    2 Module Documentation 3
    
    This also has the benefit of reducing the size of this document if the
    indices
    are very large.  I've done this with the LaTeX command
    "\setcounter{tocdepth}{0}".
    

On 2007-10-15 19:40:31 +0000, Dimitri van Heesch wrote:

    This bug's version was set to "latest". Since this is a moving target, I
    changed it to 1.5.3-SVN. If you believe this has already been fixed, then
    please change the status accordingly.

On 2014-01-29 06:24:42 +0000, Aman Talwar wrote:

    Hi,
    I have been trying to find a way to retain the hierarchy of groups (defgroup
    defined within a defgroup) in the PDF generated using the LaTex files
    (generated using Doxygen). For example, if I use:
    
    /** @defgroup group3 The Third Group 
    * This is the third group 
    * @{ */
    
    /** @defgroup group4 The Fourth Group 
    * @ingroup group3 
    * Group 4 is a subgroup of group 3 */
    
    /** @} */
    
    I expect the "The Fourth Group" to appear under the "The Third Group" in the
    PDF. For example, under the "Module Documentation" chapter of the generated
    PDF, I expect to see:
    2.1 The Third Group 
    2.1.2 The Fourth Group
    
    However, what I observed is that both the groups appears at the same
    hierarchy under "Module Documentation". For example:
    
    2.1 The Third Group 
    2.2 The Fouth Group
    
    It is important to note that the required hierarchy is maintained well in
    HTML and CHM file formats.
    
    I have also tried the patch discussed in the thread. The patched version of
    Doxygen does NOT fix the issue. I strongly feel that a fix to the issue is
    required, as the PDF generated by Doxygen is confusing and not much useful.

On 2016-09-28 20:32:21 +0000, max wrote:

    Hi Everyone
    
    I tried the newest Doxygen 1.8.12. It has still the problem, that the
    nesting of group is not working. Can someone tell, when this will be solved.
    
    Thanks and best regards
    Max

**Comment by sebastienmasson** [comment]
I definitively agree to say this issue should have considered with the highest priority.  
I am using Doxygen 1.9.4 (2021) and the bug is still present, almost 20 years after it has been introduced.

**Comment by gauthiergodart** [comment]
Hi,
First, thank you for your fantastic job in providing such a useful tool to the community.
Using Doxygen version 1.9.4, this issue is still present. The situation is the same as described by Aman Talwar in 2014. Any chance to get a fix on this?
Thanks in advance

**Comment by sebastienmasson** [comment]
Thank your for this digest Dimitri.

I have had a look at the generated Latex output from a project of mine, and I would like to supply you with my observations with Doxygen 1.9.4.  Hoping this can help with the issue.

Please let me know if you need further information about one, or another, topic below.




### When generating several outputs (requires another issue?):
*  It seems the navtree has no effect on the __pages__.  In my opinion, this leads to another issue (that might require to open another ticket): assuming a user wishes to generate html and latex outputs, they needs to manage the structure/hierarchy of the document twice (first, using the navtree into the layout file, for the html output; and, second, using the pages and sub-pages tags, for generating the latex output)

### About the "navtree" into the layout file:
* The "navtree", into the layout file, is partially used for the latex output;
* Only the "module" entry appears to be used, all other sections (as they relate to __pages__, not to __groups__?) seem to be ignored;
* The "title" of the "module" entry is used to define a new latex section within the chapter "module index" (which is not what I would expect when setting up a title for the "module" entry)

The output looks like this actually:
(Let's assuming the module index and documentation are chapters 5 and 6 respectively)
5. Module index
5.1. <title as set into the layout file>
6. Modules documentation

### About the hierarchy of the "module index"(and the "module documentation" chapters:
* It seems the visitor works fine as the module index properly shows the entire hiearchy.
* Every __group__ is used to generate one  .tex file
* Every "group dot tex" file starts with a "doxysection"
* The main tex file (refman.tex) defines a chapter "module documentation", then it calls "\input{}" for every "group dot tex" file
==> This makes the "module index" hierarchy is fine
==> This makes the "module documentation" is flattened

5. Module index
5.1. <title as set into the layout file>
5.1.1. Group 0
5.1.1.1. Group 0-0
5.1.1.2. Group 0-1
5.1.1.3. Group 0-2
5.1.2. Group 1
5.1.2.1. Group 1-0
5.1.2.2. Group 1-1

6. Modules documentation (latex \chapter)
6.1 Group 0 (latex \input)
6.2. Group1 (latex \input)
6.3. Group 0-0 (latex \input)
6.4. Group 1-0 (latex \input)
6.5 ...

**Comment by mtc-mlx** [comment]
@gauthiergodart @sebastienmasson Could you compile and test with #9936? Note that DocBook is likely broken in my branch due to the page-generating changes.

**Comment by albert-github** [comment]
I checked the hierarchy problem as mentioned here and it looks that in docbook and rtf the problem is also fixed (by means of #9936).

I think the issue is fixed but not released.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.7.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
