### ISSUE TITLE
Documentation coverage information

### ISSUE THREAD

**Issue by mcraveiro** [doxygen/doxygen#8455]
Hi doxygen developers,

thanks very much for an amazing tool. I have a question that I am sure must have been asked before but I'm afraid I cannot find it in the issues. I'd like to obtain some stats regarding "documentation coverage". I know this is possible with external tools [1] - in particular, see [2] and [3] - but I was wondering if a built-in way of generating these sorts of reports directly from Doxygen hasn't been introduced.

Many thanks for your time.

[1] [SO: Measuring Documentation Coverage with Doxygen](https://stackoverflow.com/questions/16938760/measuring-documentation-coverage-with-doxygen)
[2] [doxy-coverage](https://github.com/alobbs/doxy-coverage)
[3] [coverxygen](https://github.com/psycofdj/coverxygen)

**Comment by albert-github** [comment]
Some remarks:
- The problem with documentation coverage is: when is something covered.
- Documentation coverage is project / user dependent
- When covered it doesn't say anything about the quality.

That said doxygen has no direct ways for the documentation coverage, in the documentation source tree there are some **examples** on how to extract some metrics, see the addons directorry.

**Comment by mcraveiro** [comment]
Thanks very much for the prompt response @albert-github. I'll have a look at the examples.
