### ISSUE TITLE
/usr/include/c++/4.8.2/bits/stl_algo.h:218:23: error: no match for call to ‘(MemberLists::get(MemberListType)::__lambda4) (std::unique_ptr<MemberList>&)’

### ISSUE THREAD

**Issue by abhishekk06** [doxygen/doxygen#8464]
Hitting compilation error when I trying to build Doxygen as per the manual.

https://www.doxygen.nl/manual/install.html

**Comment by albert-github** [comment]
Without knowing what and where you are compiling it is hard to tell. Furthermore it looks like you are using gcc 4.8.2, this version is old (looks like from 2013) so it is advised to upgrade the compiler.

- Which version did you try to compile? (full git Id please)
- Which platform did you use?
- Which compiler and version (looks like gcc 4.8.2) did you use?
- What is the used CMake command?
- What messages did you get from CMake and the build (make).
