### ISSUE TITLE
1.9.1 version dmg installation file cannot not be used in Mac OS Mojave v. 10.14.6.

### ISSUE THREAD

**Issue by zhxinyu** [doxygen/doxygen#8472]
**Describe the bug**
Describe what you see that (you think) is wrong.

The newly 1.9.1 version of Doxygen does not seem to work in Mac OS Mojave v. 10.14.6. 

**1.** dmg file simply cannot open in Mac OS Mojave v. 10.14.6.
**2.** If I use the following code to install, it can be installed successfully
```
git clone https://github.com/doxygen/doxygen.git
cd doxygen
After that you can use
mkdir build
cd build
cmake -G "Unix Makefiles" ..
make

make install

```
and use ``` Doxygen Doxygen_configure_file``` to generate documentation via command line tool. **But**, there is no source code display. (not showing source code even if I turn several browser source configuration to YES. 

I finally solve this issue by installing 1.8.20 dmg file. Hope this issue could be solved in 1.9.X version.

**Comment by albert-github** [comment]
The problem regarding the missing source code when generating the documentation has been solved by means of https://github.com/doxygen/doxygen/commit/97415f7b4504d2be65338464731d7bbb4aa4d993

**Comment by albert-github** [comment]
@zhxinyu Can the doxygen version 1.9.2 be installed / does it work?

**Comment by albert-github** [comment]
As no response and the current doxygen version is 1.12.0 I think that the problems mentioned are solved in the mean time
