### ISSUE TITLE
The browser based search doesn't handle underscores correctly

### ISSUE THREAD

**Issue by sl42** [doxygen/doxygen#8485]
Since two or three weeks I experience a strange behaviour of the HTML based search engine of Doxygen. The search engine can't find underscores any more.

Here is a small example: I have a class named '`C_ClassWithUnderScore`' located in the files `class_with_underscore.h` and `class_with_underscore.cpp`. If I type in just a plain '`C`' everything is fine:

![image](https://user-images.githubusercontent.com/25041107/113913331-7cf59280-97dc-11eb-8acd-ab43c57fe6a2.png)

If I type in then a '`_`' character, the search engine says now '`No Matches`'. 
![image](https://user-images.githubusercontent.com/25041107/113913653-de1d6600-97dc-11eb-9b7b-7d0d2d610775.png)

I expected to see the class '`C_ClassWithUnderScore`'
![image](https://user-images.githubusercontent.com/25041107/113913832-17ee6c80-97dd-11eb-8a3a-e219e88adca0.png)

It seems that this is not a class related problem but a general one. It also happens if I am searching for files. Example:
![image](https://user-images.githubusercontent.com/25041107/113914036-58e68100-97dd-11eb-9665-5bbc6420db86.png)

![image](https://user-images.githubusercontent.com/25041107/113914133-761b4f80-97dd-11eb-9b0c-c5ecc759fe7f.png)

The problem is absolutely reproducable. I attached the simple example I used to show this problem.

The version I used is a self built Win64 binary.

`doxygen -V`
`1.9.2 (b2ead3a228cc44b8d3b67a4e71723f30031fa273*)`

Is there a workaround to get around this problem?

Thank you in advance for your help!

Best regards

[web_browser_search_underscore_problem.zip](https://github.com/doxygen/doxygen/files/6273615/web_browser_search_underscore_problem.zip)

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #8486

**Comment by sl42** [comment]
I tested it with the latest bbafda6 build. The search function works now as expected.
Thank you very much for fixing it so quickly.

Best regards

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.2.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
