### ISSUE TITLE
Improvement Suggestion

### ISSUE THREAD

**Issue by PaulieTes** [doxygen/doxygen#8492]
Hi,

I develop code for several different microprocessors and subsystems. It would be a nice feature if Doxygen had a \hardware command that could be used to inform readers what hardware the code is written for. I currently include the hardware description with the \brief command. It might be better however, to have an actual command for the type of hardware. The users or readers could search for this command and immediately see where the code is supposed to run. 

Just a thought.

Regards,
Paul

**Comment by albert-github** [comment]
- Can't you define your own command by means of an `ALIASES`? 
- Can you give an example of how it looks now / the command your are using now?
  - So can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the request? Please don't add external links as they might not be persistent.  
  - Please also specify the full doxygen version used (`doxygen -v`).
- For your purpose I'm not sure that the `\brief` command is the best choice.

**Comment by PaulieTes** [comment]
I can use an Alias I suppose, but it's not as clear in the code as using @hardware would be. 
What I am suggesting might be like what is below

 * @version		1.00
 *
 * @copyright		(c) 2021 by Paul A. Teseny
 *
 * @hardware		TI CC3200 Launchpad
 *

**Comment by albert-github** [comment]
Would be nice to have the required output as well, but I think you can use something like:
```
ALIASES = version="<b>Version</b>"
ALIASES += hardware="\par Hardware ^^"
```
and
```
/**
 * Some function
 *
 * @version 1.0
 *
 * @copyright   (c) 2021 by Paul A. Teseny
 *
 * @hardware    TI CC3200 Launchpad
 */
void fie();
```
which would lead to:

![image](https://user-images.githubusercontent.com/5223533/114296348-296c9880-9aab-11eb-8365-cc6f60f59bc9.png)

So I don't see what isn't clear.

**Comment by albert-github** [comment]
I think the proposed solution satisfies the required improvement and can be marked as usage.
