### ISSUE TITLE
Concepts do not respect groups in tree view

### ISSUE THREAD

**Issue by eseiler** [doxygen/doxygen#8498]
**Describe the bug**
Related to https://github.com/doxygen/doxygen/issues/2732
Usually, if some entity is in added to a group, the entity is also attached to the group in the tree view.
This does not seem to be the case with concepts.
This also causes some trouble if you DoxygenLayout.xml does not handle concepts yet, as it jump to the root in the tree view.

**Expected behavior**
Stay in group.

**Screenshots**
Clicking on something that is not a concept:
![stay](https://user-images.githubusercontent.com/12967715/114545907-d2a6c080-9c5c-11eb-835e-7a9b7264146f.png)
Clicking on something a concept (jumps to the concept part of the tree instead of staying in the modules part):
![no_stay](https://user-images.githubusercontent.com/12967715/114545911-d3d7ed80-9c5c-11eb-9b18-d16d4d487ff5.png)

**To Reproduce**
[example.tar.gz](https://github.com/doxygen/doxygen/files/6303376/example.tar.gz)

**Version**
`1.9.2 (e9185650216f3c3fa97759caf67ee79db66cb5e1)`

**Comment by albert-github** [comment]
You wrote:
> This also causes some trouble if you DoxygenLayout.xml does not handle concepts yet, as it jump to the root in the tree view.

You mean that you have an old DoxygenLayout.xml in your run directory?
Most likely cause is that in that case there are no concepts in that file and for the attribute `visible` the default value of `no` will be taken, but also the warning form the documentation:
> Warning
>     at the moment you should not remove elements from the layout file as a way to hide information. Doing so can cause broken links in the generated output!

should be taken into consideration.

**Comment by eseiler** [comment]
> You mean that you have an old DoxygenLayout.xml in your run directory?
> Most likely cause is that in that case there are no concepts in that file and for the attribute `visible` the default value of `no` will be taken, but also the warning form the documentation:

Yes, in the actual project we need to make concepts visible at least within groups to be able to see them. And there it will just jump to the root on click, because there is no file (?) concepts layout configured.

In the example it's the default Layout, and it still jumps somewhere else.

**Comment by doxygen** [comment]
@eseiler I've just pushed a fix for this. Please verify if it works for you.

**Comment by eseiler** [comment]
Thank you, works perfectly!

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.2.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
