### ISSUE TITLE
[Regression] Namespaces no longer appear in Module lists

### ISSUE THREAD

**Issue by Schulteatq** [doxygen/doxygen#8507]
**Describe the bug**
Since version 1.9.0, module pages no longer list namespaces that belong to that module (`\ingroup`). Classes and Functions still appear.

**Expected behavior**
The module page lists all namespace, classes, and functions, each underneath their corresponding section.

**Screenshots**
broken behavior:
![broken (version 1.9.0)](https://user-images.githubusercontent.com/6652808/115363030-61b65a00-a1c2-11eb-9c4b-aed6d771c3cb.png)

expected behavior:
![expected (version 1.8.16)](https://user-images.githubusercontent.com/6652808/115363125-7abf0b00-a1c2-11eb-9e08-d7d4f3dc6d3e.png)

**To Reproduce**
[missing namespace in module.zip](https://github.com/doxygen/doxygen/files/6341958/missing.namespace.in.module.zip)

**Version**
- broken in 1.9.0 and 1.9.1.
- works as expected in 1.8.16

**Comment by albert-github** [comment]
With version 1.8.16 and 1.9.1 I see the behaviors as indicated in the issue.

With the current master I see again the documentation as it was in the 1.8.16 version.

So the problem has been fixed but not yet released.

**Comment by Schulteatq** [comment]
Then I'm looking forward to the next release. :)
Thank you for the quick reply and all your work you put into Doxygen!

**Comment by r-neal-kelly** [comment]
Ah, I'm glad this will be fixed in the next release. I'm a new-comer to Doxygen and I love your program! Thanks :-)

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.2.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Comment by r-neal-kelly** [comment]
I can confirm this is fixed in v1.9.2. You're doing great work, thanks for the update!
