### ISSUE TITLE
[HTML] Generate relative links

### ISSUE THREAD

**Issue by Leonetienne** [doxygen/doxygen#8531]
I need Doxygen to generate relative links in such a way that i can use doxygen as a subdirectory on an existing web page.
Like, `www.myproject.com/doxygen`

At the moment this breaks everything because Doxygen expects all its assets to by lying in `/`.

I spent about an hour scouring the documentation and config file, but did find anything useful regarding that.

**Comment by albert-github** [comment]
It is a bit unclear where you encounter problems.
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.  
- Please also specify the full doxygen version used (`doxygen -v`).

**Comment by Leonetienne** [comment]
Well, i be damned.
It works in the minimal working example setup, but not in my actual project.

I will compare my actual project and the MWE in the coming days. Especially the config file.

**Comment by albert-github** [comment]
Just attach the output of `doxygen -x Doxyfile` to is issue and also specify the full doxygen version used (`doxygen -v`).

**Comment by Leonetienne** [comment]
Thanks for your help! But i seem to have found the "issue", if one could actually call it that.

My project is called "tornado".
My webservers file structure is this:
```
build  <- root-serving-directory of the webserver
   \
    index.html <-- selection-menu. here lie multiple projects. not just tornado.
    tornado <-- build-traget directory for doxygen
    \
      index.html
      ....
```

Turns out that `http://localhost:8080/tornado` does indeed not work, but `http://localhost:8080/tornado/` does. Notice the terminating `/`.
Guess i'll put this in the htaccess then! Thanks!
