### ISSUE TITLE
C++ namespace swallows everything in Modules lists

### ISSUE THREAD

**Issue by higaski** [doxygen/doxygen#8536]
**Describe the bug**
Putting anything inside a namespace prevents doxygen from generating documentation for it in the Modules view although all EXTRACT_* options are set to YES.

**Expected behavior**
Classes, functions and so on should appear in the Module view when added to a specific group. (In this case group "N")

**Screenshots**
![empty_namespace](https://user-images.githubusercontent.com/13762516/117434930-8e41d400-af2d-11eb-8d74-2895da5d15d4.png)

**To Reproduce**
[DoxygenBug.zip](https://github.com/doxygen/doxygen/files/6440785/DoxygenBug.zip)

**Version**
1.9.1

**Additional context**
Probably related to #8507?

**Comment by albert-github** [comment]
- Are we talking here about the file  group__n.html ?

With the version 1.9.1 I get a similar image as in the issue:
![image](https://user-images.githubusercontent.com/5223533/117436150-f1803600-af2e-11eb-8f4e-40d6da0fbd0d.png)


With the current master I see:
![image](https://user-images.githubusercontent.com/5223533/117436057-d57c9480-af2e-11eb-85fe-bd0de83e3dab.png)

- is this the expected result (I think so).

**Comment by higaski** [comment]
Thank you for the fast response. Yes I'm talking about group__n.html
The current master seems to have fixed the issue.

**Comment by albert-github** [comment]
Thanks, so this issue is fixed but not released.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.2.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
