### ISSUE TITLE
tag </programlisting> was inserted before </highlight> parsing c to xml

### ISSUE THREAD

**Issue by sdrgroup** [doxygen/doxygen#8546]
**Describe the bug**
When I parse a c file,rtracker_service.c, the output file tracker__service_8c.xml is error. 

**Expected behavior**
Describe what you would have expected or think is correct.

**Screenshots**
![image](https://user-images.githubusercontent.com/12608702/117827854-eb2de900-b2a3-11eb-847e-f5ed161b949e.png)

**To Reproduce**
[tracker_service.zip](https://github.com/doxygen/doxygen/files/6459682/tracker_service.zip)

**Version**
1.9.1
ubuntu 20.04

**Stack trace**
If you encounter a crash and can build doxygen from sources yourself with debug info (`-DCMAKE_BUILD_TYPE=Debug`), a stack trace can be very helpful (especially if it is not possible to capture the problem in a small example that can be shared).

**Additional context**

**Comment by albert-github** [comment]
With the version 1.9.1 I see at the end of the file tracker__service_8c.xml:
```
<codeline lineno="4080"><highlight class="normal"><sp/><sp/><sp/><sp/>send_add_event(pTask);</highlight></codeline>
<codeline lineno="4081"><highlight class="normal"></highlight></codeline>
<codeline lineno="4082"><highlight class="normal"><sp/><sp/><sp/><sp/></highlight><highlight class="keywordflow">return</highlight><highlight class="normal"><sp/>0;</highlight></codeline>
<codeline lineno="4083"><highlight class="normal">}</highlight></codeline>
<codeline lineno="4084"><highlight class="normal"></highlight></codeline>
<codeline lineno="4085"><highlight class="normal">    </programlisting>
</highlight></codeline>
    <location file="tracker_service.c"/>
  </compounddef>
</doxygen>
```
with the current master:
```
<codeline lineno="4080"><highlight class="normal"></highlight></codeline>
<codeline lineno="4081"><highlight class="normal"><sp/><sp/><sp/><sp/>send_add_event(pTask);</highlight></codeline>
<codeline lineno="4082"><highlight class="normal"></highlight></codeline>
<codeline lineno="4083"><highlight class="normal"><sp/><sp/><sp/><sp/></highlight><highlight class="keywordflow">return</highlight><highlight class="normal"><sp/>0;</highlight></codeline>
<codeline lineno="4084"><highlight class="normal">}</highlight></codeline>
<codeline lineno="4085"><highlight class="normal"></highlight></codeline>
    </programlisting>
    <location file="tracker_service.c"/>
  </compounddef>
</doxygen>
```

I think this problem is fixed but not released by means of the second problem mentioned in issue #8518 by means of the pull request #8524 (cpp and c share the same code scanner).
