### ISSUE TITLE
Latest release tag

### ISSUE THREAD

**Issue by Andreas-Schniertshauer** [doxygen/doxygen#8559]
Is it possible to add a latest release tag as e.g. in https://github.com/jgm/pandoc/releases

**Comment by albert-github** [comment]
- What would be a use case for this?

**Comment by Andreas-Schniertshauer** [comment]
One use case is e.g. to download it in a batch.

**Comment by albert-github** [comment]
Since December 24, 2022 the releases 1.9.0 and newer are available through the main page of GitHub:

![image](https://user-images.githubusercontent.com/5223533/209544963-3fb74da6-ab34-4116-873e-fafefe7897e9.png)


I think this problem is solved in the mean time.
