### ISSUE TITLE
Problem with french characters in HTML files

### ISSUE THREAD

**Issue by ameu00** [doxygen/doxygen#8561]
Hello, 

**BUG :**
Special french characters such as é, è, à, ç... are represented like this : 
![image](https://user-images.githubusercontent.com/74060599/118890280-b4d51700-b8fe-11eb-83d0-2d531944b3ef.png)

**Expected behavior**
"caractère réceptionné"

**To reproduce**
I extract documentation using Doxywizard with comments including special french characters.

**Version**
Latest release

It is very annoying, you find them very often in french words.
I tried to use UTF-8 encoding and ISO-8859-1 too, but it still doesn't work... any existing solution, or is it a real issue ?

**Comment by albert-github** [comment]
I tried a few things was not able to reproduce the problem, so an example is required.
You mention "latest version", this is a moving target an exact version is requited (`doxygen --version` or `doxywizard --version`)

Concluding:
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.  
- Please also specify the full doxygen version used (`doxygen -v`).

**Comment by albert-github** [comment]
Unfortunately no further information and problem was not reproducible with a small example ([example.tar.gz](https://github.com/doxygen/doxygen/files/10851337/example.tar.gz)) , setting issue to incomplete.
