### ISSUE TITLE
Blank index.html

### ISSUE THREAD

**Issue by R3D9477** [doxygen/doxygen#8572]
**Describe the bug**
Blank index.html, there is no any documentation.

**Expected behavior**
Documentation generated form comments.

**Screenshots**
![Screenshot_20210527_172552](https://user-images.githubusercontent.com/15020827/119845169-b5c70380-bf11-11eb-8d8b-e9bb519e9540.png)

**To Reproduce**
* install doxygen 1.8.17
* create simple source file main.cpp with following content:

```
/**
 * @brief entry point of application
 * @return non-zero value is code of the error
 */
int main() {
    return 0;
}
```
* run: doxygen -g
* run: doxygen Doxyfile
* see output log, the main.cpp is found:
```
...
Parsing files
Preprocessing /home/user/Desktop/doxytest/main.cpp...
Parsing file /home/user/Desktop/doxytest/main.cpp...
Building group list...
Building directory list.
...
```
* look at the generated `html/index.html`

**Version**
* KDE Neon 5.21
* package: 1.8.17-0ubuntu2

what I'm doing wrong?
Thanks!

**Comment by albert-github** [comment]
Doxygen is sometimes a bit peculiar regarding some files.
Add to main.cppp the line:
```
/** \file */ 
```

**Comment by R3D9477** [comment]
> Doxygen is sometimes a bit peculiar regarding some files.
> Add to main.cppp the line:
> 
> ```
> /** \file */ 
> ```

Thank you!
It works!
