### ISSUE TITLE
Links to enum values are incorrect when using modules.

### ISSUE THREAD

**Issue by bmaerten** [doxygen/doxygen#8600]
**Describe the bug**

Links to enum values are incorrect when using modules.

**Expected behavior**

The documentation of the enum values is within one of the group files, i.e., `group__.html`.
When referencing a value of the enum from within a class documentation the link refers to the file namespace documentation file.
It should point to the group file where the actual value is documented.

**To Reproduce**

Use the attached example which reproduces the issue.
Within the Modules section navigate to `foo/create/ICreator`.
The class documentation contains a reference to the enum value `foo::ChangeStatus::Finished` for which the documentation
is within `foo/edit/ChangeStatus`.

The link in ICreator refers to 'namespacefoo.html#ga50dcea7cd14b7292fa108290f109d226a8f3d10eb21bd36347c258679eba9e92b'.
The correct link is 'group__foo__edit.html#ga50dcea7cd14b7292fa108290f109d226a8f3d10eb21bd36347c258679eba9e92b'.

The sample project also generates a tag file. There the mentioned anchor refers to the correct html file.

**Version**
Noticed in version 1.8.18 but also in 1.9.1 (Linux 64-bit).

Doxygen 1.8.18 was tested on openSUSE and Fedora 34 using a doxygen binary compiled from source. 
Doxygen  1.9.1 was tested on Fedora 34 using a doxygen binary compiled from source. 

[doxissue.zip](https://github.com/doxygen/doxygen/files/6654634/doxissue.zip)

**Comment by albert-github** [comment]
@bmaerten  Please verify that the referenced commit (8fa90fa1b62a03c07d70f5e94ac16de8512ee564) fixes the problem.

**Comment by bmaerten** [comment]
@albert-github The fix works very well for me. Thanks!

**Comment by albert-github** [comment]
Thanks for checking.

Please don't close the issue as this will be done at the moment of an official release.

**Comment by bmaerten** [comment]
Sorry about that. Should have checked policy for resolving issues.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.2.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
