### ISSUE TITLE
PipeWire: wireplumber: has a dependency on doxygen >=1.9.0, but doxygen (>= 1.9.1) can't be compiled on ubuntu 18.04

### ISSUE THREAD

**Issue by souravdas142** [doxygen/doxygen#8612]
I am packaging PipeWire for debian/ubuntu and their derivatives. For more : https://pipewire-debian.github.io. SEEKS HELP

**Describe the bug**
PipeWire, [wireplumber](https://gitlab.freedesktop.org/pipewire/wireplumber) has a dependency on doxygen >=1.9.0, but master can't be compiled on ubuntu 18.04 with llvm-10. Not only master but from doxygen >=1.9.1 compilation stuck on 64% or 96%. Thought doxygen 1.9.0 is compilling successfully without error. Though the `wireplumber` can be compiled without `doc` support, so there is no need of doxygen or wireplumber must be built with doxygen (<< 1.9.1). But If in near future  wireplumber bumps version of doxygen in recent version, There will be no solution to build docs for wireplumber with doxygen. May be #8474  is the same issue. I think it should be fixed for ubuntu 18.04 as still 2years left from its EOL. 

**Expected behavior**
should compile properly without hanging or stucking

**To Reproduce**
1. clone the debian doxygen PKG source `git --depth 1 --branch debian/1.9.1-2 --single-branch https://salsa.debian.org/debian/doxygen.git` on ubuntu 18.04 
2. Make sure you installed all dependencies for the doxygen on ubuntu 18.04
3. edit `doxygen/debian/control` file and decrease the versions for `llvm-11-dev`, `libclang-11-dev`, `clang-11` to  `10` as ubuntu 18.04 doesn't has by default version `11`.
4. try to build the package with `dpkg-buildpackage -b -rfakeroot -uc -us` 
5. You can see the compilation stops/stucks/hangs at 64% or 96%

**Version**
The issue persist on all doxygen version >=1.9.1

Attaching launchpad build log [doxygen_1.9.1-5~ubuntu18.04_BUILDING.txt.gz](https://launchpadlibrarian.net/544842306/buildlog_ubuntu-bionic-amd64.doxygen_1.9.1-5~ubuntu18.04_BUILDING.txt.gz)

**Comment by albert-github** [comment]
The question here is this a doxygen problem or an Ubuntu problem?

- What happens when you get the doxygen sources from the doxygen github repository instead of the debian doxygen PKG source and compile here the 1.9.1 version (and / or the current master version)?
- in the  launchpad build log you attached I cannot find a compilation  error, the only thing I see is:
  > cd /<<PKGBUILDDIR>>/build/src && /usr/bin/c++  -DYY_BUF_SIZE=262144 -DYY_READ_BUF_SIZE=262144 -I/<<PKGBUILDDIR>>/qtools -I/<<PKGBUILDDIR>>/libmd5 -I/<<PKGBUILDDIR>>/liblodepng -I/<<PKGBUILDDIR>>/libmscgen -I/<<PKGBUILDDIR>>/libversion -I/<<PKGBUILDDIR>>/vhdlparser -I/<<PKGBUILDDIR>>/src -I/<<PKGBUILDDIR>>/build/generated_src -I/usr/lib/llvm-10/include  -Wdate-time -D_FORTIFY_SOURCE=2 -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -fvisibility=hidden -fvisibility-inlines-hidden   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Wall -Wextra -Wshadow -Wnon-virtual-dtor -Wcast-align -Wunused -Woverloaded-virtual -Wpedantic -Wdouble-promotion -Wformat=2 -Wno-unused-parameter -Wno-sign-conversion -Wno-format-nonliteral -Wno-implicit-fallthrough -std=gnu++14 -o CMakeFiles/doxymain.dir/xmlgen.cpp.o -c /<<PKGBUILDDIR>>/src/xmlgen.cpp
  > E: Build killed with signal TERM after 150 minutes of inactivity

  but this doesn't look to me like a doxygen error but more like a sytem errror.
- in the mentioned launchpad build log file I see that the GNU compiler is used:
  > -- The C compiler identification is GNU 7.5.0
  > -- The CXX compiler identification is GNU 7.5.0

Did I miss something in the description?

**Comment by souravdas142** [comment]
Sorry for the late. 1.9.1 is built successfully. Still need to check `master`, but have no time, will be checking tomorrow. I think I get the problem with debian package. Please don't close the issue, I'll be updating with all solutions  for future purpose.

**Comment by albert-github** [comment]
Thanks for the update.
In the GitHub Actions also an Ubuntu system is used and when I'm not mistaken it is also version 18.04. This system also uses GCC 7.5.0 and we don't see here any problems. 
It looks like the Ubuntu tool chain does something specific, as I don't have a local Ubuntu system it is had to tell.
I looked in the `CMakeCache.txt` of my Cygwin system (currently using GCC 10.2.0, I don't remember whether or not I once used 7.5.0) and here I see:
```
//Flags used by the CXX compiler during all build types.
CMAKE_CXX_FLAGS:STRING=

//Flags used by the CXX compiler during DEBUG builds.
CMAKE_CXX_FLAGS_DEBUG:STRING=-g

//Flags used by the CXX compiler during MINSIZEREL builds.
CMAKE_CXX_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG

//Flags used by the CXX compiler during RELEASE builds.
CMAKE_CXX_FLAGS_RELEASE:STRING=-O3 -DNDEBUG

//Flags used by the CXX compiler during RELWITHDEBINFO builds.
CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG
```

so maybe Ubuntu uses by default the setting `RELWITHDEBINFO ` or does some specific setting.


(Note: a new comment triggers an automatic email to me, just an edit doesn't trigger an email so I might miss it, like I nearly did your update 2).

**Comment by souravdas142** [comment]
under `debian` dir of doxygen package, `rule` file has a line `CXXFLAGS := $(shell dpkg-buildflags --get CPPFLAGS; dpkg-buildflags --get CXXFLAGS)` , specifically `dpkg-buildflags --get CXXFLAGS` generates `-g -O2 -fdebug-prefix-map=/home/sdas=. -fstack-protector-strong -Wformat -Werror=format-security`, So
>so maybe Ubuntu uses by default the setting `RELWITHDEBINFO` or does some specific setting.


may be. :man_shrugging:  I'm clueless on that.

without any optimization its successfully building see again the lauchpad build log : [doxygen_1.9.1-7~ubuntu18.04_BUILDING.txt.gz](https://launchpadlibrarian.net/545158316/buildlog_ubuntu-bionic-amd64.doxygen_1.9.1-7~ubuntu18.04_BUILDING.txt.gz)

**Note -** Still not getting  enough time to check wtih gcc > 7.5.0 with option `-O2` may be tomorrow I could be check,

**Comment by souravdas142** [comment]
@albert-github         

 **Some Update -**

doxygen is compiling under ubuntu 18.04 successfully with `-O2` option on all gcc >= 8 upto gcc 11 except gcc 9.
with gcc9, The similar situation occurred as while compiling with 7.5.0 . :man_shrugging: just Don't know why.  If you want to debug, may be solving for gcc 7.5.0  also solve for gcc 9. And I think all logs for gcc 7.5.0 already given. Or if you not want to debug, Its ok, I still can compile with gcc 7.5.0 without `-O2` option, so I think without optimisation, it does not break anything or give any poor performance ?  whats your opinion ?

**Comment by albert-github** [comment]
Thanks for the update

Are we talking here about 1.9.1 or master?
- When we talk about **1.9.1** and master is working I don't think anything has to be done (one can always compile without `-O2`, I don't know what happens with `-O` / `-O1` / `-O3`, different optimizations might results in different problems).
- When the situation is also a problem for **master**, then the situation for GCC 9 is a bit worrying, GCC 9 is not the newest version (GCC 10 and 11 are present), will be a bit hard to debug though for me as I don't have an Ubuntu system (maybe the problem also occurs on Cygwin and here is a 9.3.0 available).

**Comment by souravdas142** [comment]
> Are we talking here about 1.9.1 or master?

both, you can say for all >=1.9.1 on ubutnu 18.04. To be more specific on ubuntu 20.04 has by default gcc 9.3.0 and have no problem with `-O2` option. This issue was created for ubuntu 18.04 with combination of gcc 7.5.0 right ? So may be one can successfully compile doxygen ( >= 1.9.1) with 2nd degree optimisation with gcc 7.5.0 on ubuntu 20.04 or later. May be its a disro specific problem. and I think we should leave it.


> When the situation is also a problem for master, then the situation for GCC 9 is a bit worrying, GCC 9 is not the newest version (GCC 10 and 11 are present), will be a bit hard to debug though for me as I don't have an Ubuntu system (maybe the problem also occurs on Cygwin and here is a 9.3.0 available).

yeah its hard but you should keep support for all distro that doesn't reach to their EOL, and should be built doxygen on them with the default available dependencies.

**Comment by doxygen** [comment]
If the compiler gets stuck while compiling, it is a compiler (or system/resource) issue, not a doxygen problem in my opinion. 

We compile and test doxygen on Ubuntu 18.04 via Github Actions on both debug and release mode without problems (see for instance https://github.com/doxygen/doxygen/runs/2924871498).

**Comment by souravdas142** [comment]
Yeah I agree with you. with increasing optimisation level the resource will be use at higher point. But we shouldn't forget with the same optimisation level under gcc > 8 ~ 11 (except 9) is building easily with success and also not to forget the issue not only reproducible in my machine but it also produce in launchpad 
>  https://github.com/doxygen/doxygen/issues/8612#issue-927039615 Attaching launchpad build log [doxygen_1.9.1-5~ubuntu18.04_BUILDING.txt.gz](https://launchpadlibrarian.net/544842306/buildlog_ubuntu-bionic-amd64.doxygen_1.9.1-5~ubuntu18.04_BUILDING.txt.gz)
 
By the way, can you confirm in GA its build with `-O2` option ?
> We compile and test doxygen on Ubuntu 18.04 via Github Actions on both debug and release mode without problems (see for instance https://github.com/doxygen/doxygen/runs/2924871498).

I Can't find. without optimisation its also building in here  with ubuntu 18.04 under gcc 7.5.0
