### ISSUE TITLE
No member methods in documentation with inheritance from specialization of template

### ISSUE THREAD

**Issue by igormironchik** [doxygen/doxygen#8629]
**Describe the bug**

I have empty template.

```cpp
template< typename T, bool FLAG >
class API {};
```

and some specializations.

```cpp
template< typename T >
class API< T, true >
{
public:
    //! Documented method.
    void doSomething() {}
};
```

This template is a base class for.

```cpp
class Stuff
    :    public API< Stuff, true >
{
public:
    //! Documented method.
    void doStuff();
};
```

In the generated documentation I see only `doStuff()` method and don't see `doSomething()`.

**Expected behavior**

I should see both methods: `doStuff()` and `doSomething()` in the documentation of class `Stuff`.

**To Reproduce**

[doxygen.zip](https://github.com/doxygen/doxygen/files/6734583/doxygen.zip)

**Version**

Doxygen version 1.8.17 on Kubuntu 20.04.2

**Comment by doxygen** [comment]
@igormironchik Doxygen's parsing capabilities are currently not powerful enough to do proper deduction in order to select the correct template specialization. This is a very hard problem to solve in general (e.g. without creating a full compiler).

As a workaround, you can help doxygen a bit, by introducing a type name:

```cpp
//! API.
template< typename T, bool FLAG >
class API {};

//! Base API for Stuff.
template< typename T >
class API< T, true >
{
public:
    //! Documented method.
    void doSomething() {}
};

//! type alias to help doxygen
template< typename T >
using APIStuff = API< T, true >;

//! Stuff.
class Stuff
    :    public APIStuff<Stuff>
{
public:
    //! Documented method.
    void doStuff();
};
```
One could argue this also helps to make the code a bit more readable/maintainable.

**Comment by igormironchik** [comment]
Song sounded beautiful, but...

In my real code I have:

```cpp
//! Auxiliary API.
template< typename PARENT, typename SELF, typename ARGPTR,
	bool RETPARENT >
class API {
};

//
// Specialization for Command.
//

//! Auxiliary API.
template< typename PARENT, typename ARGPTR >
class API< PARENT, Command, ARGPTR, false >;

//
// Common specialization.
//

//! Auxiliary API.
template< typename PARENT, typename SELF, typename ARGPTR >
class API< PARENT, SELF, ARGPTR, false >;

//
// Specialization for CmdLine.
//

//! Auxiliary API.
template< typename PARENT, typename SELF, typename ARGPTR >
class API< PARENT, SELF, ARGPTR, true >;
```

I tried something like this:

```cpp
//
// CmdLine
//

template< typename PARENT, typename SELF, typename ARGPTR >
using CmdLineAPI = class details::API< PARENT, SELF, ARGPTR, true >;

using ArgPtrToAPI = std::unique_ptr< ArgIface, details::Deleter< ArgIface > >;

/*!
	CmdLine is class that holds all rguments and parse
	command line arguments in the correspondence with holded
	arguments.
*/
class CmdLine final
	:	public CmdLineAPI< CmdLine, CmdLine, ArgPtrToAPI >
```

And in documentation I got:

![Screenshot_20210817_140835](https://user-images.githubusercontent.com/11455533/129715894-e5097a32-fb5b-436e-8687-abec8df5f2ac.png)

There is no inheritance diagram even...

**Comment by doxygen** [comment]
@igormironchik You didn't provide a complete example so I hard to tell what is wrong, but I think doxygen is confused by the redundant "class" keyword within the using statement. Try without it.

**Comment by igormironchik** [comment]
> but I think doxygen is confused by the redundant "class" keyword within the using statement

Yes, you are right. I just found this redundant `class` keyword. Checked without it, and voila...

![Screenshot_20210817_143917](https://user-images.githubusercontent.com/11455533/129719455-5e67786c-3285-454f-939b-c21238abe89a.png)

Thanks a lot.

**Comment by igormironchik** [comment]
You can close this issue if you wish. Workaround works. And there is no need to implement full compiler of C++ in doxygen.

**Comment by doxygen** [comment]
I've just pushed a [commit](https://github.com/doxygen/doxygen/commit/b86138e74851a0cf12cfb873532c1d7f3a8cedf8) to make doxygen more robust for the class keyword. With this I will close this report.
