### ISSUE TITLE
external html file not found (or empty) (Origin: bugzilla #125317)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#864]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.3.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2003-10-23 15:15:41 +0000, adupont@positron.qc.ca wrote:

    When providing an external tag file to a project, the related html files 
    are empty. Because the external html files are located in a different 
    folder. It will be nice to include the output path of external html in the 
    tag file. It will be used to generate the right URL of external html file. 
    
    Presently, the file name (.html) of a external tag is correct, but the 
    page is empty.
    
    Alain Dupont

**Comment by albert-github** [comment]
When looking at the Doxyfile of doxygen version 1.3.3  it reads:

```
# The TAGFILES option can be used to specify one or more tagfiles.
# Optionally an initial location of the external documentation
# can be added for each tagfile. The format of a tag file without
# this location is as follows:
#   TAGFILES = file1 file2 ...
# Adding location for the tag files is done as follows:
#   TAGFILES = file1=loc1 "file2 = loc2" ...
# where "loc1" and "loc2" can be relative or absolute paths or
# URLs. If a location is present for each tag, the installdox tool
# does not have to be run to correct the links.
# Note that each tag file must have a unique name
# (where the name does NOT include the path)
# If a tag file is not located in the directory in which doxygen
# is run, you must also specify the path to the tagfile here.
```

So it is already possible to specify the place of the original documentation. This is not in the tag file but even a bit more flexible (I think).  The mechanism is in the 1.8.14 present as well.

So in my opinion this is usage / interpretation.
