### ISSUE TITLE
Unwanted space in front of each line in python examples.

### ISSUE THREAD

**Issue by markok314** [doxygen/doxygen#8640]
**Describe the bug**
When html with python example code is created, each line starts with one space to create visual appealing offset from
the line number margin. However, when copy-pasting this code to editor, the space is annoying.

**Expected behavior**
Margin between line number and code text should be defined in css.

**Screenshots**
![image](https://user-images.githubusercontent.com/3070254/124263708-e19e6000-db33-11eb-8873-49442326ebe9.png)

**To Reproduce**
Unzip the attached tar file to empty directory and run Doxygen there.
[space.tar.gz](https://github.com/doxygen/doxygen/files/6754235/space.tar.gz)

**Version**
Windows, Linux, 1.18.15, 1.9.1

**Additional context**
Fix includes two changes:
1. _src/htmlgen.cpp_, in _HtmlCodeGenerator::writeLineNumber_, remove

    `m_t << "&#160;";`

2. Add **margin-right** to _templates/html/doxygen.css_:
<pre>
    span.lineno {
        padding-right: 4px;
        <b>margin-right: 12px;</b>
    ...
</pre>

**Comment by albert-github** [comment]
For cut and paste this indeed gives some problems (the extra space will land in the cut and paste).
I think the `margin-right: 12px;` should be `margin-right: 9px;` (this can especially be seen when a logical line doesn't fit on a physical line);
Original:
![image](https://user-images.githubusercontent.com/5223533/124270518-99377000-db3c-11eb-9a1e-95b43a7e7a98.png)

with 12px
![image](https://user-images.githubusercontent.com/5223533/124270683-d26fe000-db3c-11eb-912b-f65a7168bd27.png)

with 9px:
![image](https://user-images.githubusercontent.com/5223533/124270618-bb30f280-db3c-11eb-925d-d2d8f60c3ff4.png)


- can you make a pull request for it?

**Comment by markok314** [comment]
I agree, 9px is better. Pull request created with 9px margin.

**Comment by albert-github** [comment]
Your code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.2.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
