### ISSUE TITLE
invalid argument for command iline

### ISSUE THREAD

**Issue by eseiler** [doxygen/doxygen#8642]
**Describe the bug**
After https://github.com/doxygen/doxygen/pull/8632, I'm getting warnings when using `\if`.

```cpp
/*!\brief Some struct
 * \if DEV
 * Some conditional stuff
 * \endif
 */
struct S{};

/*!\brief Some other struct
 * \if DEV Some conditional stuff \endif
 */
struct T{};
```

This will emit:
```text
/run/shm/example/example.hpp:2: warning: invalid argument for command iline
/run/shm/example/example.hpp:9: warning: invalid argument for command iline
/run/shm/example/example.hpp:2: warning: invalid argument for command iline
/run/shm/example/example.hpp:9: warning: invalid argument for command iline
```

This is independent of whether `DEV` is added to `ENABLED_SECTIONS` or not.
Except for the warning, the behaviour is otherwise the same, i.e. the `if` is evaluated correctly and the resulting documentation does not change.

**Expected behavior**
No warning, or, if syntactical error, point to what is wrong.

**To Reproduce**
[example.tar.gz](https://github.com/doxygen/doxygen/files/6754578/example.tar.gz)

**Version**
fc67a8291551fcd1a752eb89d18c80603a51627a
Any version before https://github.com/doxygen/doxygen/pull/8632 will work.

**Comment by albert-github** [comment]
Looks like a mean interaction between the `\brief` command and the, internal `\iline` command (the `\iline` is necessary to get proper line numbers in warnings in case the `\if ` command is used).

Adding an empty line before the `\if` command is a workaround for the problem.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #8644

**Comment by albert-github** [comment]
Code has been integrated in master on github, closing issue as it was only present in master.
