### ISSUE TITLE
Azure DevOps extension not working

### ISSUE THREAD

**Issue by sachintanwar2206** [doxygen/doxygen#8646]
Hi,

Hope you are doing well!

I am not able to use the Doxygen Azure DevOps extension for my project.

I am not sure about how to install 2 required tools (Doxygen and PdfLatex) that you mentioned in the extension description.

Also, it would be great if you can provide a video tutorial showing how to set up the Doxygen extension with Azure-DevOps.

Error file: [error.txt](https://github.com/doxygen/doxygen/files/6758669/error.txt)

**Comment by albert-github** [comment]
You wrote:
> I am not able to use the Doxygen Azure DevOps extension for my project.
>
> I am not sure about how to install 2 required tools (Doxygen and PdfLatex) that you mentioned in the extension description.

So I don't think this is a direct doxygen problem, more an Azure (DevOps) problem. Please inquire there.

**Comment by sachintanwar2206** [comment]
@albert-github 
They are saying that it is extension's issue and i should contact you instead.

**Comment by albert-github** [comment]
- The extension is not coming from doxygen, where did you get it?
- Most likely you have to contact the persons who wrote / are responsible for the extension.

**Comment by sachintanwar2206** [comment]
@albert-github do you have any suggested extension for me?

**Comment by albert-github** [comment]
Unfortunately not.

Best to google for e.g. "azure devops doxygen extension" or ask a question on one of the stackoverflow / stackexchange sites.

**Comment by doxygen** [comment]
I'm marking this issue as "invalid" as it is not a doxygen issue, but a 3rd party extension issue.
