### ISSUE TITLE
doxygen with php make ugly array parameter output

### ISSUE THREAD

**Issue by paule32** [doxygen/doxygen#8649]
Hello,
I tried doxygen 1,9 2021 to document php files.
but i ran into trouble with array parameter.
for avoid cross posting, look here:

https://stackoverflow.com/questions/68241186/doxygen-for-php-dont-handle-default-parameter-array?noredirect=1#comment120609963_68241186

**Comment by paule32** [comment]
new news:
I found a workaround:

public static function rgb2hex(
		int   $red   = 0,
		int   $green = 0,
		int   $blue  = 0,
		array $default = array('r' => 0, 'g' => 0, 'b' => 0)   # <-- here: array instead [ ] !
	) : array {

it would be nice, when "array( ... )"  is support with $arr = [ ];
Oh men, what a day ....

**Comment by albert-github** [comment]
The information at stackexchange might not be persistent, so:
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.  
- Please also specify the full doxygen version used (`doxygen -v`).

Note: You mention version doxygen 1.9 2021, which version is this ? I only know at the moment, for the 1.9 series, the doxygen versions 1.9.0 and 1.9.1 and further the current master (1.9.2 (7fa3837cf2d93164df2cf2fc6697a27fea524d07), with the master the git ID, as reported by doxygen -v, should always be specified).

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #8673

**Comment by albert-github** [comment]
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.2.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
