### ISSUE TITLE
Doxygen returning error level 0 when file or directory in not readable

### ISSUE THREAD

**Issue by v-rakkun** [doxygen/doxygen#8669]
**Describe the bug**
I have added not existence directory to doxygen. I'm seeing error like below
***error: source <DIRECTORY_PATH> is not a readable file or directory... skipping.***

**Expected behavior**
Expecting to abort the doxygen when there is an error or error level should be non zero.

**To Reproduce**
Add any non existence directory to doxygen and run doxygen.

**Version**
1.8.18

**Comment by albert-github** [comment]
In the version 1.9.1 we get the warning like:
```
warning: tag INPUT: input source <directory_path>  does not exist
warning: source <directory_path> is not a readable file or directory... skipping.
```

One has the possibility to set the setting `WARN_AS_ERROR`:
> WARN_AS_ERROR 
> 
> If the WARN_AS_ERROR tag is set to YES then doxygen will immediately stop when a warning
is encountered. If the WARN_AS_ERROR tag is set to FAIL_ON_WARNINGS then doxygen will continue
running as if WARN_AS_ERROR tag is set to NO, but at the end of the doxygen process doxygen will return
with a non-zero status.
> Possible values are: NO, YES and FAIL_ON_WARNINGS.
> The default value is: NO.

Note: `FAIL_ON_WARNINGS` has been introduced in doxygen 1.9.0

Note: with `FAIL_ON_WARNINGS` will see any type of warning as error and set the error flag.

I think this is not a bug.

**Comment by v-rakkun** [comment]
I installed 1.9.1 version and used WARN_AS_ERROR set to YES and FAIL_ON_WARNINGS in different scenarios. But, seeing return code is zero.

**Comment by albert-github** [comment]
Strange I get:
```
$ /usr/bin/doxygen.exe -v  ; echo $?
1.9.1 (9801202c59180f97025dea15456711e480b64dab*)
0
$ /usr/bin/doxygen.exe  ; echo $?
warning: tag INPUT: input source 'src_error' does not exist
warning: source 'src_error' is not a readable file or directory... skipping.
1
```
My Doxyfile
```
QUIET=YES
INPUT = src_error
WARN_AS_ERROR = FAIL_ON_WARNINGS
```

and the directory `src_error` does not exist.

So this looks all OK to me.

**Comment by v-rakkun** [comment]
It's working fine.

Thank you for the clear information :-)
