### ISSUE TITLE
Link with image in Markdown can be invisible

### ISSUE THREAD

**Issue by igormironchik** [doxygen/doxygen#8672]
**Describe the bug**

Links with images in Markdown writes like:

```
[![Build](https://github.com/igormironchik/args-parser/workflows/build/badge.svg)](https://github.com/igormironchik/args-parser/actions)
```

And Doxygen generates from this link in HTML like:

```
<a href="https://github.com/igormironchik/args-parser/actions"><object type="image/svg+xml" data="https://github.com/igormironchik/args-parser/workflows/build/badge.svg" style="pointer-events: none;">Build</object></a>
```

And this image is invisible. But when I changed `<object type=""....>` to `<img src="...">` link became visible.

**Expected behavior**

Link should be visible without any modifications of generated HTML.

**Version**

Doxygen version 1.8.17 on Kubuntu 20.04.2.

**Comment by albert-github** [comment]
When running doxygen 1.8.17 I see:

![image](https://user-images.githubusercontent.com/5223533/125659857-50845cd5-b637-41a8-a7bb-3f10c3946c8d.png)

When running with the current released version (1.9.1) I see:
![image](https://user-images.githubusercontent.com/5223533/125659968-663d52ae-8400-440f-9277-1effa72c3534.png)

and the HTML code:
```
<div class="textblock"><p><a href="https://github.com/igormironchik/args-parser/actions"><img src="https://github.com/igormironchik/args-parser/workflows/build/badge.svg" alt="Build" style="pointer-events: none;" class="inline"/></a> </p>
</div></div>
```
so with `img`.

I think th problem has been solved in the mean time.
