### ISSUE TITLE
Doxygen for rust

### ISSUE THREAD

**Issue by PradeepKiruvale** [doxygen/doxygen#8686]
Hi,

Is it possible to create documentation (callgraphs) for rust source code using doxygen?. Please guide me.

Thanks,
Pradeep

**Comment by albert-github** [comment]
Rust is not supported by doxygen out of the box.
Possible solutions would be:
- create a filter that converts rthe rust code to a language that doxygen does understand
- create some settings in the `MACRO_EXPANSION` / `PREDEFINED` so doxygen can have a go (the Hello world example looked like pretty C-ish)

You probably would be better of asking in the right group at  stackexchange

**Comment by PradeepKiruvale** [comment]
Thanks for the quick reply. I will check in Stackexchange.
