### ISSUE TITLE
@mainpage dont show in HTML mode

### ISSUE THREAD

**Issue by paule32** [doxygen/doxygen#8703]
Hello,
I have this mainpage constructs:  https://dpaste.com/F3RVBN8NH
I have add the docindex.php to the INPUT files in config file.
But when I start doxygen, to create mainpage documentation, I fail.
The documentation pages will be display, except the mainpage.

Ans last but not least, I get the error in german language mode:

doxygen devdoc.cfg
warning: The selected output language "german" has not been updated
since release 1.8.15.  As a result some sentences may appear in English.

**Comment by albert-github** [comment]
Please don't use external links, it is unknown where they point to and man not be persistent.
The reason for a missing mainpage are many but without more information it impossible to say, so:
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.  
- Please also specify the full doxygen version used (`doxygen -v`).

**Comment by doxygen** [comment]
Please do what Albert asks. It looks like the GPL text contains Markdown commands, which causes the parsing to fail:

    warning: reached end of file while inside a '~~~' block!

Please fix these (give the text 4 spaces indentation, or use `@verbatim...@endverbatim`) and try again.

**Comment by albert-github** [comment]
- unfortunately no further information provided
- links does not work anymore 

Setting issue to incomplete.
