### ISSUE TITLE
No detailed functions, even with @file

### ISSUE THREAD

**Issue by rogermiranda1000** [doxygen/doxygen#8707]
**Describe the bug**
Setting @param in a function doesn't show the params (I think it should appear in "Detailed Description", but there's only the file description).
You can look the [configuration](https://rogermiranda1000.com/libwolfram20/dconfig), the [output file](https://rogermiranda1000.com/libwolfram20/classWAEngine.html), and the files [.cpp](https://github.com/rogermiranda1000/libwolfram20/blob/feature/documentation/Wolfram/WAEngine.cpp) and [.h](https://github.com/rogermiranda1000/libwolfram20/blob/feature/documentation/Wolfram/WAEngine.h)

**Expected behavior**
As far as I know, with all I have it should appear a "Detailed Description" with all the functions

**Screenshots**
You can go to the links on the description and see it for yourself.

**To Reproduce**
You can go to my [project files](https://github.com/rogermiranda1000/libwolfram20/tree/feature/documentation/Wolfram) and run `doxygen` with my [config](https://rogermiranda1000.com/libwolfram20/dconfig).

**Version**
1.9.2
Ubuntu Server 21.04
I compilated doxygen from the GitHub repository, as shown in [GIT repository](https://www.doxygen.nl/download.html)

**Stack trace**
None, but still the output is a bit strange... it says `/home/rogermiranda1000/libwolfram20/Wolfram/WAEngine.h:51: warning: parameters of member WAEngine::WAEngine are not (all) documented`, but they are all documented... Changing the documentation from the .cpp to the .h leads to the same (and I have read that duplicating documentation in both .cpp and .h it's bad, so I haven't tried to put on both).

**Additional context**
Besides more than 5 hours trying to fix it, nothing to say.

**Comment by doxygen** [comment]
The [last commit](58264d82ea58b22c66c86e321280d887914a2ef0) has an unfortunate regression that you ran into. I make [a fix](49df009132b7fc3abb086e5c1298065298d484c4) for it, so please try again.

**Comment by rogermiranda1000** [comment]
> please try again.

Same as before. The version is the same (1.9.2) am I doing it right?

**Comment by rogermiranda1000** [comment]
Nvm I was looking on "Detailed Description" and not on the function itself. Thanks!

**Comment by albert-github** [comment]
@rogermiranda1000 
When specifying the doxygen version used please use the complete output of `doxygen -v` as when compiling from git this also gives the git hash and for the master version this gives relevant extra information. 

I just saw that this morning there was a new fix, maybe you can test this as well.

**Comment by rogermiranda1000** [comment]
@albert-github 
> When specifying the doxygen version used please use the complete output of `doxygen -v`
OK, now I can see that the hash changes.

> I just saw that this morning there was a new fix, maybe you can test this as well.
Everything seems the same to me, but I'll use the newest version if there's a fix.
