### ISSUE TITLE
Fail installing doxygen in a container with an azure pipeline (or locally) : "cmake" issue.

### ISSUE THREAD

**Issue by esaintmi** [doxygen/doxygen#8716]
I'm using a dockerfile in an azure pipeline, to build and push a doxygen container:
![image](https://user-images.githubusercontent.com/64020636/129199227-4542d5a1-6bae-44ec-91a8-da99358cc83a.png)

It was working just fine untill yesterday, the build is now failing. No change were performed in my azure repository since a long time, the pipeline was just relaunched. The problem seems to be during the make process (step 5 of the dockerfile according to the logs):
![image](https://user-images.githubusercontent.com/64020636/129205521-190eec0f-a2a3-4c54-b23f-8ee5a74082f5.png)

I have reproduced the same error locally in a debian 9 docker container, performing the below steps one by one:
![image](https://user-images.githubusercontent.com/64020636/129200592-d4f12511-d08b-4d4b-b554-33636bdb7d05.png)

Then I managed to make it work by downloading a specific release of doxygen (1.9.1 from january 2021), instead of using  "git clone https://github.com/doxygen/doxygen.git"   ,modifying the dockerfile as below:
![image](https://user-images.githubusercontent.com/64020636/129200009-2ee36750-87d5-49b3-8fc7-839b36e024c5.png)

So it seems that the content I get from     git clone https://github.com/doxygen/doxygen.git    does not compile anymore.

Any reason ?
Does the command     git clone https://github.com/doxygen/doxygen.git     download the latest stable version of 1.9.1 ? 
Any way to download the latest stable version automatically ?

Regards,

Edouard.

Edit :
Last successful pipeline (and build and push) was 28th of July.
Pipeline failed starting yesterday.
Can this be due to the cmake version installed in the container ?
![image](https://user-images.githubusercontent.com/64020636/129209641-06a42607-752f-42a2-93fc-f392b1e71047.png)
Installed cmake version is 3.7.2

**Comment by esaintmi** [comment]
FYI : last successful pipeline (and build and push) was 28th of July.
        Pipeline failed starting yesterday.

**Comment by esaintmi** [comment]
Thanks,
Make version is 4.1

Here are the error logs:

[ 58%] Building CXX object src/CMakeFiles/doxymain.dir/classlist.cpp.o
[ 58%] Building CXX object src/CMakeFiles/doxymain.dir/cmdmapper.cpp.o
[ 59%] Building CXX object src/CMakeFiles/doxymain.dir/conceptdef.cpp.o
[ 59%] Building CXX object src/CMakeFiles/doxymain.dir/condparser.cpp.o
[ 60%] Building CXX object src/CMakeFiles/doxymain.dir/context.cpp.o
In file included from /tmp/doxygen/src/context.h:20:0,
                 from /tmp/doxygen/src/context.cpp:19:
/tmp/doxygen/src/template.h:238:20: error: enclosing class of constexpr non-static member function 'bool TemplateVariant::isValid() const' is not a literal type
     constexpr bool isValid()    const { return m_variant.valid(); }
                    ^~~~~~~
/tmp/doxygen/src/template.h:92:7: note: 'TemplateVariant' is not literal because:
 class TemplateVariant
       ^~~~~~~~~~~~~~~
/tmp/doxygen/src/template.h:92:7: note:   'TemplateVariant' has a non-trivial destructor
/tmp/doxygen/src/template.h:240:20: error: enclosing class of constexpr non-static member function 'bool TemplateVariant::isBool() const' is not a literal type
     constexpr bool isBool()     const { return m_variant.is<bool>(); }
                    ^~~~~~
/tmp/doxygen/src/template.h:242:20: error: enclosing class of constexpr non-static member function 'bool TemplateVariant::isInt() const' is not a literal type
     constexpr bool isInt()      const { return m_variant.is<int>(); }
                    ^~~~~
/tmp/doxygen/src/template.h:244:20: error: enclosing class of constexpr non-static member function 'bool TemplateVariant::isString() const' is not a literal type
     constexpr bool isString()   const { return m_variant.is<QCString>(); }
                    ^~~~~~~~
/tmp/doxygen/src/template.h:246:20: error: enclosing class of constexpr non-static member function 'bool TemplateVariant::isStruct() const' is not a literal type
     constexpr bool isStruct()   const { return m_variant.is<TemplateStructIntf*>(); }
                    ^~~~~~~~
/tmp/doxygen/src/template.h:248:20: error: enclosing class of constexpr non-static member function 'bool TemplateVariant::isList() const' is not a literal type
     constexpr bool isList()     const { return m_variant.is<TemplateListIntf*>(); }
                    ^~~~~~
/tmp/doxygen/src/template.h:250:20: error: enclosing class of constexpr non-static member function 'bool TemplateVariant::isFunction() const' is not a literal type
     constexpr bool isFunction() const { return m_variant.is<FunctionDelegate>(); }
                    ^~~~~~~~~~
/tmp/doxygen/src/template.h:293:20: error: enclosing class of constexpr non-static member function 'bool TemplateVariant::raw() const' is not a literal type
     constexpr bool raw() const { return m_raw; }
                    ^~~
/tmp/doxygen/src/template.h:308:20: error: enclosing class of constexpr non-static member function 'TemplateVariant::Type TemplateVariant::type() const' is not a literal type
     constexpr Type type() const { return static_cast<Type>(m_variant.index()); }
                    ^~~~
/tmp/doxygen/src/template.h:311:27: error: enclosing class of constexpr non-static member function 'const char* TemplateVariant::typeAsString() const' is not a literal type
     constexpr const char *typeAsString() const
                           ^~~~~~~~~~~~
make[2]: *** [src/CMakeFiles/doxymain.dir/context.cpp.o] Error 1
src/CMakeFiles/doxymain.dir/build.make:1086: recipe for target 'src/CMakeFiles/doxymain.dir/context.cpp.o' failed
make[1]: *** [src/CMakeFiles/doxymain.dir/all] Error 2
make: *** [all] Error 2
CMakeFiles/Makefile2:612: recipe for target 'src/CMakeFiles/doxymain.dir/all' failed
Makefile:160: recipe for target 'all' failed
The command '/bin/sh -c cd /tmp && git clone https://github.com/doxygen/doxygen.git  && cd doxygen  && mkdir build && cd build  && cmake -G "Unix Makefiles" ..  && make  && make install' returned a non-zero code: 2
##[error]The command '/bin/sh -c cd /tmp && git clone https://github.com/doxygen/doxygen.git  && cd doxygen  && mkdir build && cd build  && cmake -G "Unix Makefiles" ..  && make  && make install' returned a non-zero code: 2
##[error]The process '/usr/bin/docker' failed with exit code 2
Finishing: Build and push an image to container registry

**Comment by albert-github** [comment]
It is nice to know the make version but I was mentioning the compiler version. I assume the used compiler is GCC, but no idea which version (i.e. `gcc ..version`).

**Comment by albert-github** [comment]
I think the problem here is that the 6.4 version is to old for doxygen and doesn't have some needed compilation features.
(I know that GitHub Actions uses 7.5.0 but that 7.4.0 does work as well).

**Comment by esaintmi** [comment]
Thanks a lot for your explanation Albert.
Regards,
Edouard.

**Comment by esaintmi** [comment]
Last question.
The last release 1.9.1 is from January 2021. There is no newer release since ?

**Comment by albert-github** [comment]
From the information I have, the idea is that quite soon a new release will be made (in think this might happen in August).

Setting this issue to usage - not a doxygen problem

**Comment by doxygen** [comment]
Apparently this is a C++14 feature that gcc didn't support properly, and the issue was fixed in gcc 7.2, see https://gcc.gnu.org/git/?p=gcc.git&a=commit;h=0634d9fe36e8ced1c6046759f9ce1d2655c8d731 (fix is from may 2017)

**Comment by esaintmi** [comment]
Thanks Dimitri.
