### ISSUE TITLE
Matching function prototypes when variables have and don't have namespace prefix.

### ISSUE THREAD

**Issue by etpalmer63** [doxygen/doxygen#8717]
**Describe the bug**
In a header file, the function prototype is declared using a namespace prefix. i.e. `SpaceTwo::CustomVar` . In the source code,
the function is declared without the prefix on `CustomVar`, however the namespace has been enacted via `using namespace SpaceTwo;` When processing Doxygen treats the two as completely separate functions.

**Expected behavior**
I believe Doxygen should treat the function in the source code as the matching file member to the prototype in the header. 

**Screenshots**
If useful, add screenshots to help explain your problem.

**To Reproduce**
Extract zipped files (header.h, source.cpp, doxygen.conf) in a directory and run `doxygen doxygen.conf`. 
[bug_ex_ep.tar.gz](https://github.com/doxygen/doxygen/files/6984151/bug_ex_ep.tar.gz)
**Version**
I'm using version 1.8.17 on Ubuntu 20.04. I used `sudo apt install doxygen`  to install. 

**Additional context**

**Comment by etpalmer63** [comment]
This second example is closer to my use case. It has the namespace declaration in the header file with the prototype, and the prefix on the function when it is called from the source. In this case, Doxygen gives an warning message and then produces no documentation from `source.cpp`. 

As above, it would be nice if Doxygen could match the function with its prototype so that both comments are collected together.

Included here are the files to recreate the bug. 

[bug_ex2_ep.tar.gz](https://github.com/doxygen/doxygen/files/6984196/bug_ex2_ep.tar.gz)

Thank you!

**Comment by doxygen** [comment]
@etpalmer63 The problem is that doxygen has no information that `SpaceTwo` is a namespace that contains type `CustomVar`. Your compiler will have the same issue with the example provided.

If I add a dummy source file with
```cpp
namespace SpaceTwo { class CustomVar {}; }
```
doxygen will find the match between definition and declaration.

**Comment by etpalmer63** [comment]
Thank you very much for your advice!
