### ISSUE TITLE
@code nested in a list item closes the list (HTML)

### ISSUE THREAD

**Issue by eepp** [doxygen/doxygen#8733]
**Describe the bug**

When you put a `@code` section within a list item, the HTML output shows a code section which is not nested and the list is closed afterwards such that the next list item is the first of a new list.

**Expected behavior**

The code section is nested within the list item like any other element.

**Screenshots**

This is a screenshot of the HTML rendering of the attached reproducer:

![image](https://user-images.githubusercontent.com/1816705/130709270-ca57d7a3-2d79-4a5f-831d-9d919e757bc5.png)

As you can see, the code section is not nested within the list item and the following list item is the first of a new list.

**To Reproduce**

Unzip the attachment ([doxygen-bug-nested-code.zip](https://github.com/doxygen/doxygen/files/7042890/doxygen-bug-nested-code.zip)) and run:

```
$ doxygen Doxyfile
```

Open `output/html/index.html`.

**Version**

Doxygen 1.9.1

```
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
```

**Comment by albert-github** [comment]
With doxygen 1.9.1 we get the image as shown in the issue.
In doxygen 1.9.2  we get:

![image](https://user-images.githubusercontent.com/5223533/130745134-a2a16d98-3000-410a-8a62-b6176e33c49b.png)

This looks OK to me, so I think the problem has been solved in the mean time.
