### ISSUE TITLE
Buggy qch genereated for wxWidgets

### ISSUE THREAD

**Issue by playgithub** [doxygen/doxygen#8760]
**Describe the bug**
For qch, function descriptions can not be shown
For html, it's ok

**Expected behavior**

Function descriptions show normally

**Screenshots**

![wx_doc](https://user-images.githubusercontent.com/3665590/132105176-26f03e2a-453f-4a37-9b35-3441278e5ac4.png)

**To Reproduce**

```shell
$ git clone --depth 1 https://github.com/wxWidgets/wxWidgets.git
$ cd wxWidgets/docs/doxygen/
$ WX_SKIP_DOXYGEN_VERSION_CHECK=1 ./regen.sh qch
(add `out/wx.qch` to `qt assistant` and view some docs of member functions of wx classes)

```

**Version**

Doxygen: 1.9.1
wxWidgets: header version, commit id: 303d899cc0
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        21.1.1
Codename:       Pahvo

**Stack trace**

N/A

**Additional context**

N/A

**Comment by albert-github** [comment]
It is a bit hard to reproduce the problem as it is:
- quite a large example
- the given link exists is not persistent, i.e. it changes over time
- no qhp file is generated as `ghp` has not been specified as argument for the `regen.sh`
- some extra steps are done (adding extra files to to the `<files>` section), is this necessary?  Doesn't the doxygen setting `HTML_EXTRA_FILES` work?
- which `setLabel` are you referring to? I think from `wxWindow` but in a quick plain test this looks OK to me.

I did a quick test with a plain `Doxyfile` (i.e. no extra files), generating qhp and in the result I see the `setLabel` documentation. 
- which version of qthelpgenerator / assistant did you use? 
- recently a few changes have been made for the `qch` generation in the doxygen master, what is the result with the current master?
- what is the result when you run a plain doxygen on the sources

**Comment by playgithub** [comment]
> It is a bit hard to reproduce the problem as it is:
> 
> * quite a large example

Yes,  but it doesn't take too much time to build the doc.

> * the given link exists is not persistent, i.e. it changes over time

Yes, for it is a large repo, so add `--depth 1` for `git clone`, it doesn't matter, the problem can still be reproduced.
Alternatively
```shell
$ git clone https://github.com/wxWidgets/wxWidgets.git
$ git checkout 303d899cc0
```

> * no qhp file is generated as `ghp` has not been specified as argument for the `regen.sh`

Sorry for typo, should be
```shell
$ WX_SKIP_DOXYGEN_VERSION_CHECK=1 ./regen.sh qch
```

> * some extra steps are done (adding extra files to to the `<files>` section), is this necessary?  Doesn't the doxygen setting `HTML_EXTRA_FILES` work?

I don't know the details, `$ WX_SKIP_DOXYGEN_VERSION_CHECK=1 ./regen.sh qch` will generate `wx.qch` in folder `out`, and it is supposed to be correct.

> * which `setLabel` are you referring to? I think from `wxWindow` but in a quick plain test this looks OK to me.
> 
> I did a quick test with a plain `Doxyfile` (i.e. no extra files), generating qhp and in the result I see the `setLabel` documentation.

`setLabel` in screenshot is just a example, every member function doesn't show descriptions.

> * which version of qthelpgenerator / assistant did you use?

qthelpgenerator: not found
```shell
$ whereis qthelpgenerator
qthelpgenerator:
```
assistant: 5.15.2

> * recently a few changes have been made for the `qch` generation in the doxygen master, what is the result with the current master?

Not tested

> * what is the result when you run a plain doxygen on the sources

I'm not familiar with `doxygen`.

> * Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

[wxWidgets.zip](https://github.com/doxygen/doxygen/files/7111374/wxWidgets.zip)

**Comment by albert-github** [comment]
I think it would be good to check with the wxWidgets maintainers, I think they should update their systems regarding the documentation generation (they are still using doxygen version 1.8.8 from August 21, 2014).

Regarding the not found `qthelpgenerator` this was a typo on my side should have been `qhelpgenerator`, but this will most likely also be 5.15.2 as the assistant is 5.15.2

**Comment by playgithub** [comment]
> I think it would be good to check with the wxWidgets maintainers, I think they should update their systems regarding the documentation generation (they are still using doxygen version 1.8.8 from August 21, 2014).

I think so, I posted a ticket there before this
https://trac.wxwidgets.org/ticket/19259#ticket
But they asked me to issue a bug here

**Comment by albert-github** [comment]
It might be a ping-pong between doxygen and wxWidgets, but they should upgrade their specific files as they are most likely not compatible with the doxygen version you used.

**Comment by playgithub** [comment]
Thanks, I'll try to fix it.

**Comment by playgithub** [comment]
> one of the things I can quickly see is e.g. that in the newer doxygen the `\n` in `ALIASES` doesn't work and has to be replaced with `^^`.

I have tried this, but the result is the same.

**Comment by albert-github** [comment]
I didn't expect that this would solve the problem.

Another question when you look in the about box of the assistant which browser do you see there?
I see: QTextBrowser

![image](https://user-images.githubusercontent.com/5223533/132351969-7df47268-16c0-4f01-9ce9-30441de7c9dd.png)

(this doesn't give nice results though).

**Comment by playgithub** [comment]
2 cases

## Succeeded Case: Start `Qt Assistant` standalone

![image](https://user-images.githubusercontent.com/3665590/132353642-db834b85-6de8-474c-86aa-76abbadb56bb.png)

As far as I can see, everything works properly except a trival problem as below

![image](https://user-images.githubusercontent.com/3665590/132354662-66cef7ce-bcb5-4c40-b70d-760bf16b36b8.png)

## Failed Case: Start `Qt Assistant` from inside `Qt Creator`

No way to see the about dialog, but it should use a different web browser engine , see **More Info** below

As described in the post above:
* no function descritions
* a funciton link to function descrition doesn't work
* no inheritance diagram

## More Info

After a fresh installation of Linux, `Qt Assistant` can not be started standalone but can be started from inside `Qt Creator`.
After installing `qt5-webkit` on Manjaro, `Qt Assistant` can be started standalone.
So `Qt Assistant` uses different web browser engines in the two cases.

**Comment by albert-github** [comment]
Regarding the both cases, do you see the missing information? or is it missing in one of the cases (i.e. used Browser).

**Comment by playgithub** [comment]
> Regarding the both cases, do you see the missing information? or is it missing in one of the cases (i.e. used Browser).

In the standalone case, nothing is missing, and links work properly.
In the Qt Creator case, inheritance diagrams and function descritions are missing, and links don't work properly.

**Comment by albert-github** [comment]
So the documentation from e.g. setLabel isn't present in the case of the Qt Creator? Is this using as Browser the Qt WebKit or the QTextBrowser?

**Comment by playgithub** [comment]
> So the documentation from e.g. setLabel isn't present in the case of the Qt Creator?

Yes

> Is this using as Browser the Qt WebKit or the QTextBrowser? The assistant will use here the same Browser as the Qt Creator.

`Qt Assistant` in `Qt Creator`  mode don't use `Qt WebKit`, for it can be used without `qt5-webkit` installed.
In another case, `Qt Assistant` in standalone mode use `Qt WebKit`, for it can't be used without `qt5-webkit` installed.

**Comment by albert-github** [comment]
The result is a bit strange to me / contradicting my results as I only have an assistant version with the QTextBrowser and I do see here the documentation.
I'll have to run some tests to see whether the used header and footer files might be a problem (I know that there were some errors in the older header footer files).

**Comment by playgithub** [comment]
In Qt Creator, there are 3 options for viewer backend for qt assistant.
![ViewerBackend](https://user-images.githubusercontent.com/3665590/132362401-080c39fb-57e4-4059-8f09-d8bd1f5d8856.png)

Summary for each option

* litehtml
  * no function descritions
  * a funciton link to function descrition doesn't work
  * no inheritance diagram
* QtWebEngine
  Totally normal
* QtTextBrowser
  Everything is ok except formatting fails as in the screenshot below  
  ![QTextBrowser](https://user-images.githubusercontent.com/3665590/132363371-a7aeabb6-4804-4ce8-88c6-f5939f9b5807.png)

**Comment by playgithub** [comment]
Is it true that the choice of viewer backend depends on the content of qch file?

**Comment by albert-github** [comment]
Thanks for this overview, now my results make sense again as well.
- The problem with the `litehtml` is probably that it doesn't really support the js as used by doxygen 
- The problem with the `QTextBrowser` is probably similar to the problem with the `litehtml`, but maybe some constructs are possible to show some elements
- The results of the `QtWebEngine` are OK

Thus actually the problem of this issue is solved by using the right Browser.


Regarding the question:
> Is there any option for doxygen to generate qch that is compatible with viewer backend of litehtml or QtTextBrowser?

I don't think this will be easily to accomplish as it would mean that the js handling has to be accomplished in some other way.
I'm not sure that all CSS can be used 1-to-1 as well.

**Comment by playgithub** [comment]
Thanks very much
