### ISSUE TITLE
Markdown runs on <PRE> if class attribute is specified

### ISSUE THREAD

**Issue by elfprince13** [doxygen/doxygen#8785]
**Describe the bug**
`<PRE>` tags are supposed to be ignored by Markdown, to preserve ASCII art; however, [`<PRE class="markdeep">`](https://casual-effects.com/markdeep/#doxygen) is hit by the Markdown parser, thus breaking ASCII art.

**Expected behavior**
ASCII art should be preserved.

**To Reproduce**
Default configuration, see "Describe the bug".

**Version**
Doxygen version 1.9.2 (but compiled from source release to run on Ubuntu 18.04)

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

**Comment by albert-github** [comment]
According to the https://spec.commonmark.org/0.30/#html-block it is true tat `<pre>` blocks should be treated as raw-HTML (and nit interpreted) and according to the original specs from https://daringfireball.net/projects/markdown/syntax#html there are some extra restrictions.


- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #8786

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.3.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
