### ISSUE TITLE
Doxygen 1.9+ can insert same base class twice in xml

### ISSUE THREAD

**Issue by 1vanK** [doxygen/doxygen#8805]
Worked version: 1.8.17
Broken version: 1.9.1, 1.9.2

![1](https://user-images.githubusercontent.com/13021826/135303038-8217ee74-f0fb-4d12-82ea-404c965ff47d.png)

Generated xmls: [bug.zip](https://github.com/doxygen/doxygen/files/7253266/bug.zip)
(compare `class_urho3_d_1_1_db_connection.xml` files)

Repo: https://github.com/urho3d/Urho3D

No idea how to reproduce in small example

**Comment by albert-github** [comment]
This does not look nice, problem is that it is hard to generate the code as there is no small example and also no used Doxyfile added. 
Using the Doxyfile.in and some fiddling around I was able to reproduce the problem with the curent version (1.9,2) and also with the current master: 1.9.3 (234637167bd5d39d32bf51f755d58253441f123a)). It looks a bit like that twice the base class `Object` is added, this is confirmed also by the HTML output:

![image](https://user-images.githubusercontent.com/5223533/135312988-a94478ea-01c3-4028-9d5f-1a7665ffa31f.png)

@doxygen is it possible that in the `Doxygen:ClassLinkedMap` or its elements an item is added twice ?

Attached the Doxyfile I used: [doxyfle.tar.gz](https://github.com/doxygen/doxygen/files/7253730/doxyfle.tar.gz)

Procedure used:
- clone https://github.com/urho3d/Urho3D
- cd Urho3D/Docs
- place the attached Doxyfile in this directory
- doxygen Doxyfile


As a small note:
@1vanK It is a bit strange to me that fixed paths like:
```
STRIP_FROM_PATH        = C:/projects/urho3d/ \
                         /home/travis/build/urho3d/Urho3D/
```
are used in a `Doxyfile.in`

**Comment by albert-github** [comment]
When looking at the files:
- ../Source/Urho3D/Database/ODBC/ODBCConnection.h
- ../Source/Urho3D/Database/SQLite/SQLiteConnection.h

I find in both files:
```
class URHO3D_API DbConnection : public Object
```
so it loos to me that the package should either be build with an ODBC connector or with an SQLite connection.

To reproduce the problem it is sufficient to set the `INPUT` in the `Doxyfile` to:
```
INPUT =  ../Source/Urho3D/Database/ODBC/ODBCConnection.h
INPUT +=  ../Source/Urho3D/Database/SQLite/SQLiteConnection.h
```

- @1vanK is this assumption correct?

**Comment by albert-github** [comment]
In that case also the documentation should reflect this, now the used source code for the documentation is, due to that both ODBC and SQLite are used, non valid source code.
Doxygen is quite tolerant regarding non valid source code, but some artifacts like these can occur.

**Comment by 1vanK** [comment]
Thanks
