### ISSUE TITLE
Class hierarchy diagram is not correct, if inherited from Python built-in class ABC

### ISSUE THREAD

**Issue by bertramrichter** [doxygen/doxygen#8854]
**Describe the bug**
In a Python project, the class hierarchy overview shows a wrong inheritance graph, if the Python built-in class `abc.ABC` (abstract base classes) is used as the root. Some seemingly random class is shown as the root of the inheritance tree and a circular inheritance dependency is shown, the inheritance from `ABC` is not shown. This only happens in `Classes -> Class Hierarchy`, the inheritance graphs for the individual classes in their documentation pages are always correct.

**Expected behavior**
Expected is that all classes inherit from `ABC` in the class hierarchy overview graph.

**Screenshots**
Correct without `ABC`:
![image](https://user-images.githubusercontent.com/93182600/138828093-39643e3e-b3ea-413f-a9a1-03e8182a3766.png)

Wrong with `ABC`:
![image](https://user-images.githubusercontent.com/93182600/138828261-d693acb0-939b-4e3f-a51a-cc33697e2890.png)

Correct, with mixed (with and without `ABC`):
![image](https://user-images.githubusercontent.com/93182600/138828454-6c379f19-dafe-4cdf-908c-f27c21c97ff8.png)

**To Reproduce**
Attached is a MWE of the problem: [doxygen_problem_with_ABC.zip](https://github.com/doxygen/doxygen/files/7415948/doxygen_problem_with_ABC.zip), which includes the source code, and the generated documentation, which leads to the examples shown above. 

**Version**
I am currently using version 1.9.3 on Linux Mint 20.1 and 19.3, built from the instructions on the downloads page. But this this behavior is present in previous doxygen versions too.

Big thank you for the exciting framework.

Kindly Yours
Bertram Richter

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.3.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
