### ISSUE TITLE
C# see langword

### ISSUE THREAD

**Issue by lukemason76** [doxygen/doxygen#8885]
In my log I have multiple entries like the following:
```
warning: unable to resolve link to `string' for \link command
```
The error links to the following doc tag
```
/// <summary>
/// The User provided <see langword="string"/> fragment of the Cost Center name
/// <para>Combined with <see cref="WildcardPlacement"/> to narrow down the chosen <see cref="CostCenter"/></para>
/// </summary>
```

Checking the generated docs, the word 'string' in the `<see langword="string"/>` construct is missing, but then a broken link is formed from that point to the end of the parapgraph

**Expected Results**
I would expect the output doco to include the word 'string', with a style (typically blue) to make it stand out.  There shouldn't be a link in this issue.

**Screenshots**
**Error Log**
![image](https://user-images.githubusercontent.com/20507935/140847944-c2b37c5c-a561-48fb-a0ef-9bef64239de0.png)
**Generated doc**
![image](https://user-images.githubusercontent.com/20507935/140848223-076dd1ec-5793-46a7-829d-c6018d381d54.png)

**To Reproduce**
Create a c# .net 5 console app.  
Install the nuget doxygen package
Add documents tags to code
Check doxygen output for errors like warning: unable to resolve link to `string' for \link command

**Version**
Using the latest version of the nuget package.  That believes its 1.8.14

*Additional context**
Has there been a reversion of the fix from 2018?

**Comment by albert-github** [comment]
I can see that there has been a fix in 2018 which entered in the  1.8.15 version (see #6345), I cannot tell whether or not this has also an effect on your problem, but as far as I can tell from the little information I have it does. I tried with the 1.8.14 version and got the wrong text and some warnings. With the 1.9.2 version these warnings are gone and the output looks OK to me (same with version 1.8.15).

The 1.8.14 version is a bit older and it highly recommended to update to the current doxygen version.

- So please always attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

I think the problem has been solved in the mean time.
