### ISSUE TITLE
Extra ".html" attached to some url links when linking to external library

### ISSUE THREAD

**Issue by etpalmer63** [doxygen/doxygen#8889]
**Describe the bug**
When using a TAGFILE to link a project library to an external library, some of the links include an extra ".html" at the end of the url address. This causes the link to fail.

**Expected behavior**
The link should have one less ".html" in the url. 

**Screenshots**
In the screen shot you can see when I hover my pointer over the clickable image, the target url is incorrect. 
![Screenshot from 2021-11-11 11-32-45](https://user-images.githubusercontent.com/24531086/141334769-0bf6dffd-2007-4a82-9f69-668c90c8bfd9.png)

**To Reproduce**
I included an example that reproduces the problem. In this example, the `ProjLib` wants to link to `ExtLib` Doxygen docs. The directories and files are included in the tarball.
[DoxyBug.tar.gz](https://github.com/doxygen/doxygen/files/7521908/DoxyBug.tar.gz)

The website associated with this example is in two locations: 
1. ExtLib -- https://etpalmer63.github.io/Testing/AMReX__MultiFab_8H.html
2. ProjLib -- https://etpalmer63.github.io/Testing2/hydro__ebmol_8H.html

**Version**
I first noticed the issue with Doxygen ver. 1.8.13. I upgraded to ver 1.9.2 and the issue persisted. Both were on Ubuntu 20.04

**Additional context**
Although, in my example the error occurs on the clickable image. I have also found that it can occur in other places, such as on the include links in the upper left.

**Comment by albert-github** [comment]
This problem has been fixed on numerous places in the past, but apparently this one was missed.

I've just pushed a proposed patch, pull request #8891

**Comment by etpalmer63** [comment]
Awesome! Thanks!

**Comment by albert-github** [comment]
I fixed the problem for the images, but you mentioned:
> Although, in my example the error occurs on the clickable image. I have also found that it can occur in other places, such as on the include links in the upper left.


Can you please give an example of this?

**Comment by etpalmer63** [comment]
I'll work on putting together another example.

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by albert-github** [comment]
Found another case so I've just pushed a new proposed patch, pull request #8893

**Comment by albert-github** [comment]
Also the code of the second pull request has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.3.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
