### ISSUE TITLE
[bisected]Directory dependency graph has stopped working

### ISSUE THREAD

**Issue by duncan-roe** [doxygen/doxygen#8895]
The last revision displaying the dependency graph was 1.8.10. `git bisect` reports `first bad commit: [4bd50c9f0dc1d7b1413a6bda587b8a5999cd7a19] Moved creation of inline class documentation to separate template file`.
The attached diagrams come from the attached sample project. From the main page, click Files->a.c->top (top is in one of the grey bars).
![1 8 10](https://user-images.githubusercontent.com/2820715/142077574-89bb3a32-c778-440b-a650-319109f15a46.png)
![no_graph](https://user-images.githubusercontent.com/2820715/142077596-ca46df9d-58ea-4048-b82f-59dda11ee437.png)
[sample_project.tar.gz](https://github.com/doxygen/doxygen/files/7550340/sample_project.tar.gz)

**Comment by albert-github** [comment]
In the documentation it is stated:
> DIRECTORY_GRAPH If the DIRECTORY_GRAPH tag is set to YES then doxygen will show the dependencies
a directory has on other directories in a graphical way. The dependency relations are determined by the
#include relations between the files in the directories.

In the given example there are no `#include`'s used.

So I think the fact that the graph is missing is correct and was not correct in the 1.8.10 version.

**Comment by duncan-roe** [comment]
[sample_project2.tar.gz](https://github.com/doxygen/doxygen/files/7566857/sample_project2.tar.gz) has a `#include` but there is still no dependency graph

**Comment by albert-github** [comment]
A very strange problem indeed.
It looks like that there are 2 things to be considered:
- the dependency is only valid when the included file is from outside the tree
- the mentioned include file has to be an `INPUT` file (looks like `INCLUDE_PATH` doesn't function).

Looks like that especially the first restriction does hit us here, in case `#include`'s are used.

My example: [example.tar.gz](https://github.com/doxygen/doxygen/files/7570550/example.tar.gz)

**Comment by duncan-roe** [comment]
The top/bottom part of the diagram is the same and interacts the same as that at 1.8.10.
What is the point of the restrictions that stopped displaying it?

**Comment by duncan-roe** [comment]
> In the documentation it is stated:
> 
> > DIRECTORY_GRAPH If the DIRECTORY_GRAPH tag is set to YES then doxygen will show the dependencies
> > a directory has on other directories in a graphical way. The dependency relations are determined by the
> > #include relations between the files in the directories.
> 
> In the given example there are no `#include`'s used.
> 
> So I think the fact that the graph is missing is correct and was not correct in the 1.8.10 version.

If you set DIRECTORY_GRAPH=YES I submit you want to see the directory graph whenever one is available.

I don't agree that the quoted documentation implies **no** graph if no dependencies. Without the graph, navigation back to where you came from can become difficult (there is the browser 'back' button but that loses history of where you've been). And having the graph disappear when you click on some part of it is just bizarre.

**Comment by duncan-roe** [comment]
At 1.8.9.1 if you click on _inc_ then the graph shows _inc_ and nothing else. To see the others, you need to use the browser 'back' button. I suppose I would prefer to leave the graph as was and only move the highlighting to _inc_, but would that be easy?

**Comment by albert-github** [comment]
The 
> I don't agree that the quoted documentation implies no graph if no dependencies, but I concede it's arguable. 

might indeed be a bit arguable. The intention is that when no "#include" then no graph (the exact formulation I leave for the language purists and lawyers 😉 ).

The suggestion in https://github.com/doxygen/doxygen/issues/8895#issuecomment-981037305 is nice but won't be easy, just a change in highlighting is not possible, to implement. For the number of child levels `DIR_GRAPH_MAX_DEPTH` has been introduced but for the number of parent directories nothing is available.

**Comment by doxygen** [comment]
@duncan-roe I've made some changes that should make the directory reappear in case a directory has a parent. For the case where you follow a link to a directory without parent, I suggest you submit a new issue that we can treat as an enhancement request.

**Comment by duncan-roe** [comment]
Yes directory graph has reappeared. Also I notice entries under **Files** and **Directories** have reappeared (disappeared at 1.8.11 IIRC). This at least gives a way to get (back) to a child directory.
Will check out 1.8.9.1 treatment of multiple children before submitting Feature Request

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.3.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Comment by duncan-roe** [comment]
Confirm fixed at 1.9.3
