### ISSUE TITLE
Overload of function template can cause docs to be repeated

### ISSUE THREAD

**Issue by lawmurray** [doxygen/doxygen#8903]
**Describe the bug**

In the situation that:

(a) there is a function template declaration, and
(b) there is an overload of that function template, but also with an inline definition

then it seems Doxygen repeats the documentation of the second overload at the end of the first overload (see screenshot below). The presence of an inline definition for the second overload seems critical to reproduce this issue. If one removes the definition (i.e. the part in the curly braces) then this does not occur.

**Expected behavior**
The documentation should not be repeated.

**Screenshots**
![doxygen](https://user-images.githubusercontent.com/2579923/142743796-d9d8124c-b019-42c5-b1f9-d87aa7ed522b.png)

**To Reproduce**
[example.tar.gz](https://github.com/doxygen/doxygen/files/7575497/example.tar.gz)

This contains a header file `test.hpp` with a minimal example, as well as the default `Doxyfile` generated from `doxygen -g`, just with `INPUT = test.hpp` added.

**Version**
1.9.3 on Linux, openSUSE Leap 15.3. I've installed the latest doxygen from source here, rather than using the version included in the distribution.

**Comment by albert-github** [comment]
Perfect to test it against the current master but please always mention the full version (`doxygen -v`) as "latest" is a moving target. I see your output also with the current doxygen master version (1.9.3 (a473d3bc71f1e50b7e88d13836b7bb6168d72089).

**Comment by doxygen** [comment]
Please verify if the referenced commit fixes the problem.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.3.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
