### ISSUE TITLE
html file names are different from original path (underscores), is this configurable?

### ISSUE THREAD

**Issue by emmenlau** [doxygen/doxygen#8913]
**Describe the bug**
This is a feature request, not a bug. We like doxygen a lot and use it extensively. One use case is a bit special: Some of the html files are further converted to PDF and become end user documentation. There is a small problem in that the file names of the html (and therefore pdf) files are not identical to the original path names. An example shows this:

Example original path: `<project>/analysis/2019-11-08--11-39-42/results.md`
Corresponding html name: `<project>/doc/md_analysis_2019_11_08__11_39_42_results.html`

The problem comes with the dashes '`-`' being replaced by underscore '`_`'. Afterwards the pdf file name can not be easily discovered with search, and its much harder to relate them to the original source file. Since the folder structure is dictated by other peoples experiment names, we do not have 100% control over these path names.

**Expected behavior**
It would be great if the change of file names would be configurable, for example with something like a variable
```
// Which characters in the path name should be replaced by underscore,
// to ensure file system and web-server friendly output file names:
DOXYGEN_FIXUP_FILE_PATH_CHARACTERS="/\\-[]();"
```

I've searched with google for 45 minutes and could not find any solution or related requests. I've also explicitly searched through the issues on Github and could not find anything directly related (only some issues about bugs with file names).

Thanks a lot for consideration!

**Comment by albert-github** [comment]
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.
- Please also specify the **full** doxygen version used (`doxygen -v`).

**Comment by emmenlau** [comment]
Thanks @albert-github , your question made me do further checks that may be helpful. Attached more information:

The problem is observed with `doxygen 1.9.2 (caa4e3de211fbbef2c3adf58a6bd4c86d0eb7cb8)`. With this version, attached example creates a file named `html/md_test_with_dashes_other_page.html` based on source file `test-with-dashes/other-page.md` (dashes are replaced with underscore).

I also found that `doxygen 1.8.17` from Ubuntu 20.04 x86_64 does not behave the same. It will instead create a file `html/md_test-with-dashes_other-page.html` that works much better for me.

Would it be possible to allow configuration of this behavior?

Here the test example:
[doxygentest-8913.tar.gz](https://github.com/doxygen/doxygen/files/7608933/doxygentest-8913.tar.gz)

**Comment by albert-github** [comment]
I check hart the reason behind this change is. 

This was an intentional change / design descision (in doxygen 1.9.0).
The base was the issue #8156 and the pull request #8157:
```
Commit: eaf691cc82cb2c819bf61a48265d334464f2d831 [eaf691c]
Date: Tuesday, November 3, 2020 8:15:27 PM
issue #8156 Markdown anchors do not work with special symbols

Replace the respective characters by an underscore.
```
and optimized by means of the commit (c48c5eb ):
```
Commit: c48c5eb3c68a9b5f3f82d1d186a6695ed1d30db5 [c48c5eb]
Date: Thursday, November 5, 2020 7:25:15 PM
Optimized the escape function and made it more generic
```

So not really something that can (or will) be done about this.

**Comment by emmenlau** [comment]
Thanks a lot for checking the root of the issue! I understand at least a part of it.

What I can not fully grasp is what negative effects would be caused if one where to allow further characters in `isId()`? See https://github.com/doxygen/doxygen/blob/32268b373048a2f6314074fc1465e356201e84e2/src/util.h#L174

It seems `isId()` is meant to be rather restrictive, and probably for good reason. But it does not say much about these reasons. Do you happen to know? Why should all other characters be illegal? Why for example dash (`-`)?

**Comment by albert-github** [comment]
The `isId` might be a bit restrictive for this special cases but it is used in other cases as well, where more restrictive names are required, so the choice has been made for the restrictive names here as well (and users, normally, don't need to know / construct the file name when browsing etc.).

**Comment by emmenlau** [comment]
Ok, I will close this issue and accept that the effort of changing the behavior outweighs the gain it would have for me.

In case someone else needs this, it's sufficiently simple to reconstruct the original file names based on a lookup table that mimics doxygens behavior (just replacing characters by underscore in the same way that `isId()` suggests. It's only a "best effort" and may fail in  the future, but may be good enough for many use cases.
