### ISSUE TITLE
Adding docs to extension methods in c#

### ISSUE THREAD

**Issue by danieltranca** [doxygen/doxygen#8917]
**Describe the bug**
I want to add extension methods to a c# project

**Expected behavior**
Docs contain the text included in the summary of the extension methods

**Information missing**
The text included in the summary of the extension methods

**Version**
![image](https://user-images.githubusercontent.com/80676873/143623550-3724554e-11e1-41e2-8860-3532ce7c7dd1.png)

**Example**
[Doxygen.Test.zip](https://github.com/doxygen/doxygen/files/7611644/Doxygen.Test.zip)

**Comment by albert-github** [comment]
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.
- Please indicate which information is missing.

**Comment by danieltranca** [comment]
@albert-github added everything

**Comment by albert-github** [comment]
Well, I didn't find `Please indicate which information is missing.`

I had a look at `Foo.cs` and I guess you meant the information about `public static void DoExtensionStuff(this Foo foo)`.
This is a `static` function so to see the information you have to set `EXTRACT_STATIC=YES`.

Does this solve the problem? or did I overlook something, when I overlooked something please indicate what you expected to see as well.

**Comment by danieltranca** [comment]
@albert-github yes, that did it. This is not a bug.
