### ISSUE TITLE
Parser does not recognise __section("name")

### ISSUE THREAD

**Issue by elijahbailey** [doxygen/doxygen#8936]
Hi,

I need to document some code for microcontroller. 
Some const must be stored in flash memory. To get ist right you have to specify a "section" in memory e.g.

const char __section("stringtexts") variableName[] = "the text to be stored"
const char __section("stringtexts") anotherVariableName[] = "another text to be stored"

Now __section("string texts") is recognized as function. And the second line is ignored. CLANG option set results is notifying duplicates definitions of the function.

if it is not a bug, can you please provide a hint on how to tell the parser taking "__section" not as a function?

regards

**Comment by albert-github** [comment]
This is not standard C / C++ code, but an extension specifically for the microcontroller you use.
It is similar to handle as e.g. `__declspec(dllexport)`, see https://www.doxygen.nl/manual/preprocessing.html

So I think this problem is usage.

**Comment by elijahbailey** [comment]
Hi,

thanks, looks like I made two mistakes.

1. missing the configuration settings, sorry.
2. put @var into the comment which conflicts with the following definition of the variable

So I did the configuration, removed the @var and voila it works as expected.

regards
