### ISSUE TITLE
Cross documentation references to user defined sections recognised but not hyperlinked (Origin: bugzilla #127618)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#894]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.3.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2003-11-21 17:16:46 +0000, ralph@dibase.co.uk wrote:

    When using tag files and references to user defined sections in other 
    (external) documentation sets, such sections are recognised by Doxygen in 
    that it does not produce any diangnostic (but will if the section name is 
    incorrect, for example). Hoever these are not converted to active 
    hyperlinks to the said external section in teh resultant documentation.
    
    This feature did work previously in Doxygen version 1.2.18.
    
    Doxygen version: 1.3.4
    Documentation type: HTML
    Circumstances: In @mainpage section
    
    Example: 
    
    In referring documentation set:
    /*!
    @mainpage
    
    @section testpoxrend_overview Overview
    
    ...
    
    @ref poxutil_overview "poxutil"
    
    ...
    
    */
    
    In external documentation set:
    
    /*!
    @mainpage
    
    @section poxutil_overview Overview
    
    ...
    
    */

On 2004-10-08 18:21:45 +0000, Dimitri van Heesch wrote:

    *** Bug 154700 has been marked as a duplicate of this bug. ***

**Comment by albert-github** [comment]
With version 1.3.4 there is no link present.
With version 1.8.15 the link is present (using the same Doxyfiles, tag files are slightly different)

I think the problem has been solved in the mean time.
