### ISSUE TITLE
Feature request: Remove #undef macros from docs in C++.

### ISSUE THREAD

**Issue by stickM4N** [doxygen/doxygen#8943]
When `#undef SOMETHING` is used in C++ macros are shown in the docs. Im my humble opinion they should be not documented.... or even better, managed by a setting in the Doxyfile.

**Comment by albert-github** [comment]
The information contained in the description is a bit meager, where do you see what? So
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.
- Please also specify the **full** doxygen version used (`doxygen -v`).

The `#undef` in the code are placed in the code by the developer of the particular code, probably with good reason so the user of the code should normally be informed as well (as he is informed bout `#define`s as well). The issue with the `#undef` / `#define` is of course that by means of the usage they might only be locally  present, here they are more or less "static" / "internal" to the source file, or undoing older settings, this is not reflected in the code and certainly should be written in the documentation.

**Comment by Clement-Jean** [comment]
I also would prefer for it to not be documented. One example of that is when i'm declaring macros to only shorten my code a bit. Here is an example:

```c
#define N binary_search_tree_node
#define T binary_search_tree

void binary_search_tree_free(T* self);

#undef T
#undef N
```

right now, I'm able to expand these type aliases in the doc with `EXPAND_AS_DEFINED = T N` but the type aliases themselves are still in the macro section of my doc which is not useful for documentation readers.

doxygen version: 1.9.5
