### ISSUE TITLE
external links between chm file are no longer working (Origin: bugzilla #127882)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#901]
status NEW severity *normal* in component *build* for *---*
Reported in version *1.3.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2003-11-25 11:21:34 +0000, lionel_409@hotmail.com wrote:

    I recently moved from doxygen 1.2.10 to doxygen 1.3.4 (I know I am a bit 
    late!!).
    I use doxygen to generate 5 components documentations and there are 
    references between these documents.
    In my config file, I use the following syntax : toto.tag=toto.chm:: 
    because of the too big size of the page, it is really quicker to consult 
    the documentation in chm.
    
    Anyway, in doxygen 1.2.10 , the external link to the class classTiti was 
    the following : toto.chm://classTiti.html and in doxygen 1.3.4, it is now 
    $(DOCUMENATION_PATH)/toto.chm://classTiti.html . The consequence is that 
    even if I have my chm files in the same folder as it was needed before, it 
    no longer works :((
    
    Is it a known problem and do I need to fallback to a former version of 
    doxygen or is it a bug?
    
    Thanks in advance,
    Lionel

**Comment by albert-github** [comment]
The tests I performed with the 1.3.4 version didn't show a problem and also with the 1.9.3 version there was no problem.
The test was limited due to the missing example.

So problem is not complete.
