### ISSUE TITLE
Feature request: DoxImageKind - add 'xml' member, or remove constraint entirely

### ISSUE THREAD

**Issue by canton7** [doxygen/doxygen#9012]
I'm using Doxygen's XML output to generate a Word version of the documentation, which works well.

`\image` provides a little niggle however: it's format-specific, and the user needs to provide one of `html`, `latex`, `docbook` or `rtf`. However, there's no `xml` option, so I need to pick e.g. `html`, and tell users that if they use `\image html ...`, the image will appear in both HTML and Word output.

My request is either:

1. Add an additional `xml` member, to let users say that the image is relevant to the `xml` format (whatever that might mean in practice)
2. Remove the constraint entirely, allowing users to specify any string (within reason)

Thanks!

**Comment by albert-github** [comment]
Which version of doxygen are you using?
Why are you using the XML version to generate a word document and not the rtf version?

In the release notes of the 1.9.3 version I see: Add the xml output format to the image command as generic format [view]
and a small test reveals that it does work like:
```
\image xml ....
```

**Comment by canton7** [comment]
You're right, that slipped in without me noticing. My bad, thanks!
