### ISSUE TITLE
Explicit link request warning within sample code C++ snippet

### ISSUE THREAD

**Issue by ferdymercury** [doxygen/doxygen#9036]
**Describe the bug**
Explicit link request warning is issued in sample C++ code snippets within a Doxygen comment, which are not wanted to be parsed to links.

**Expected behavior**
There is a way to escape this sample C++ code so that it does not generate a warning. E.g. by escaping the colons or something similar.

**Screenshots**
`TGeoCone.cxx:28: warning: explicit link request to 'Template' could not be resolved
`
**To Reproduce**
[mismatch.zip](https://github.com/doxygen/doxygen/files/7871262/mismatch.zip)

**Version**
`1.9.4 (1e51265d8b86fa476743b5cbad653b917b7171b0)`

**Additional context**
https://github.com/doxygen/doxygen/issues/6432#issuecomment-1013189499

**Comment by albert-github** [comment]
Not sure where the problem lies but I expect that it is in he line:
```
`ns1::ns2::,,,::Template<`
```
in that case it is possible:
```
`ns1::ns2::,,,::%Template<`
```

**Comment by ferdymercury** [comment]
Yes, that was the problematic line. Thanks, using the percentage sign solves it!
