### ISSUE TITLE
copydoc failing for template instantiation in C++

### ISSUE THREAD

**Issue by ferdymercury** [doxygen/doxygen#9039]
**Describe the bug**
`warning: @copybrief or @copydoc target 'WriteObject(const T*,const char*,Option_t*,Int_t)' not found`

is issued when trying to copydoc from a template declaration to a template specialization in C++. Even if I try to specify the arguments by hand when using copydoc, not only just the function name.

**Expected behavior**
It would be nice if there was a way to copy documentation from a template to a template instantiation / specialization. Maybe via a templatecopydoc command?

**To Reproduce**
[mismatch.zip](https://github.com/doxygen/doxygen/files/7874793/mismatch.zip)

**Version**
1.9.4 (1e51265d8b86fa476743b5cbad653b917b7171b0)

**Additional context**
https://stackoverflow.com/questions/32332537/can-i-use-copydoc-with-function-or-template-parameters
Probably very similar issue: https://github.com/doxygen/doxygen/issues/8159

**Comment by ferdymercury** [comment]
I think this was a typo of mine when using copydoc, sorry. Closing.

**Comment by albert-github** [comment]
What was the typo?

**Comment by ferdymercury** [comment]
I was using copydoc `WriteTObject` but the template name was `template<T> WriteObject`, without the T in the name.
