### ISSUE TITLE
Invalid handling of backslahes in <pre> fragments (Origin: bugzilla #128063)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#904]
status REOPENED severity *normal* in component *general* for *---*
Reported in version *1.3.x* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxtest.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug128063_250523_doxtest.zip/download/download)_ (ID 250523)

On 2003-11-27 15:50:08 +0000, p.horn@micropool.ch wrote:

    A single backslash in a <pre> fragment causes the rest of the line to be
    ignored. The backslash must be doubled to work properly.

On 2013-04-01 12:41:46 +0000, albert wrote:

    Tried to reproduce the problem with version 1.8.3.1, 1.3.1 and 1.2.18 with
    the following source file:
    /**
      * docu of f
      *
      * <pre>
      * Pre section with now \ single backslash
      * and at end of line \
      * rest of pre section
      * </pre>
      */
    void f()
    {
    }
    
    but without success.
    
    Cannot reproduce problem.

On 2013-04-01 13:23:15 +0000, Dimitri van Heesch wrote:

    Please reopen this bug if you can attach a self-contained example
    (source+config file in a tar or zip) that allows reproduction of the
    problem.

On 2013-07-31 08:45:23 +0000, p.horn@micropool.ch wrote:

    Created attachment 250523
    Testcase for Bug 128063
    
    Archive contains source and generated output

On 2013-07-31 08:46:51 +0000, p.horn@micropool.ch wrote:

    After some digging I was able to the code which triggers the bug.

On 2013-08-01 16:52:10 +0000, albert wrote:

    Thank you for the answer.
    
    In the <pre> section the \ followed by the characters until the first space
    are seen as a command.
    Apparently the \commands are processed when inside a <pre> section, I could
    not find any conformation in the documentation about this though.
    
    The problem can be overcome by using a \verbatim block (resulting in a boxed
    and colored section in the output).
    Another option is to escape the \ by another backslash, but this is not nice
    for ASCII art.

**Comment by albert-github** [comment]
I think the mentioned problem is a usage problem.
