### ISSUE TITLE
Images created by custom filter in image path are not found, because search is done before generation

### ISSUE THREAD

**Issue by ferdymercury** [doxygen/doxygen#9044]
**Describe the bug**
I have a custom Doxygen filter (a small script) that creates, when parsing some C++ files, on-the-fly png images and stores them into IMAGE_PATH. However, these files are not found by doxygen, because it searches for files in the image path at the very beginning.
My workaround right now is to run doxygen twice, this way the second time the images are already there and are found correctly.

**Expected behavior**
When using custom filters, it would be nice to have a INI file option to activate the detection whether 'anything new' was added to the IMAGE_PATH or EXAMPLE_PATH on each preprocessed file. So that there is no need to run twice.

Or maybe adding the new filenames directly from our script to the running instance of doxygen somehow?

**Screenshots**
```
Parsing layout file DoxygenLayout.xml...
Searching for include files...
Searching for example files...
Searching for files in directory /tmp/rootdoc/macros
Searching for images...
Searching for files in directory /tmp/rootdoc/images
...
Preprocessing /opt/root_src/core/base/src/TAttFill.cxx...
Info in <TCanvas::Print>: png file /tmp/rootdoc/images/pict1_TAttFill_001.png has been created
Info in <TCanvas::Print>: png file /tmp/rootdoc/images/pict1_TAttFill_002.png has been created
Info in <TCanvas::Print>: png file /tmp/rootdoc/images/pict1_TAttFill_003.png has been created
Parsing file /opt/root_src/core/base/src/TAttFill.cxx...
Generating docs for compound TAttFill...
/opt/root_src/core/base/src/TAttFill.cxx:53: warning: image file pict1_TAttFill_001.png is not found in IMAGE_PATH: assuming external image.
/opt/root_src/core/base/src/TAttFill.cxx:100: warning: image file pict1_TAttFill_002.png is not found in IMAGE_PATH: assuming external image.
/opt/root_src/core/base/src/TAttFill.cxx:169: warning: image file pict1_TAttFill_003.png is not found in IMAGE_PATH: assuming external image.
```
When run a second time, the `is not found in IMAGE_PATH: assuming external image.` warnings disappear.

**To Reproduce**
I could not create a small reproducer, as the custom filter generating the png images runs the ROOT software.

**Version**
Doxygen version used: 1.9.4 (1e51265d8b86fa476743b5cbad653b917b7171b0)
Self-compiled, Ubuntu18

**Comment by albert-github** [comment]
I think the problem is due to the way doxygen searches all the files.
First it searches all available image files, dot files, example files input (source) files etc. in `searchInputFiles` and after this it starts processing the input files. As the mentioned images are generated in the processing phase and hence not yet known. When running a second time the files are already present and so they can be found (even though they might be overwritten).

@doxygen 
would it be an idea to search the image files (and other non direct input files, i.e files from `IMAGE_PATH`, `DOTFILE_DIRS`, `MSCFILE_DIRS` and `DIAFILE_DIRS`) after the "Parse source files" part in `parseInput`? So generated image type of files are found as well?

**Comment by ferdymercury** [comment]
https://github.com/doxygen/doxygen/blob/ab9dc4c7f542ad3509d2c7a51a7b719e66a8b0d8/src/docparser.cpp#L287-L289

One workaround could be to add a small snippet before line 289:
```
if(!fd) {
   //Attempt a search on-the-fly in case the image was generated after the directory was parsed, e.g. due to a filter
   fd = OpenFile(fileName);
}
```

**Comment by albert-github** [comment]
- What is the `OpenFile` function?

I think that it would be better to fundamentally solve the problem as indicated by moving the search code till after the preprocessing phase / the phase where filters are used.
The `imageNameLinkedMap`is not only used in `doxparser.cpp` but also in `markdown.cpp`, `doxbookvisitor.cpp` and `xmlvisitor.cpp` (and of course `doxygen.cpp` where it is filled). The workaround will give problems when copying the file in `xmldocvisitor.cpp` / `docbookvisitor.cpp` as the file is not found here (and no warning will be emitted).

**Comment by ferdymercury** [comment]
> * What is the `OpenFile` function?
> 
> 
> I think that it would be better to fundamentally solve the problem as indicated by moving the search code till after the preprocessing phase / the phase where filters are used. The `imageNameLinkedMap`is not only used in `doxparser.cpp` but also in `markdown.cpp`, `doxbookvisitor.cpp` and `xmlvisitor.cpp` (and of course `doxygen.cpp` where it is filled). The workaround will give problems when copying the file in `xmldocvisitor.cpp` / `docbookvisitor.cpp` as the file is not found here (and no warning will be emitted).

Oh, you are right, it's being used in many places, so the workaround I suggested is actually not a good idea.

**Comment by ferdymercury** [comment]
> would it be an idea to search the image files (and other non direct input files, i.e files from `IMAGE_PATH`, `DOTFILE_DIRS`, `MSCFILE_DIRS` and `DIAFILE_DIRS`) after the "Parse source files" part in `parseInput`? So generated image type of files are found as well?

@doxygen what's your opinion on this strategy? (Thanks!)

**Comment by ferdymercury** [comment]
@doxygen any feedback on this? Thanks.

**Comment by doxygen** [comment]
@ferdymercury I think in this specific case it would work to move the searching of image files until after the preprocessing/parsing step without unwanted side-effects. In general (for instance if the filter creates new source files that need to be parsed) a two step approach may be unavoidable.

**Comment by doxygen** [comment]
@ferdymercury no indeed. As I said, for images, it should work to move the searching until after the preprocessing/parsing of the code.

**Comment by ferdymercury** [comment]
Yes, our filter do not create new source files, so that should work to move it afterwards. Thanks.

**Comment by ferdymercury** [comment]
Thanks for the investigation!
Maybe a new flag could be defined in the Doxyfile that forces doxygen to update the list of images after the postprocessing? So to say, to enable a two-step process. (even if the performance is worse).

**Comment by ferdymercury** [comment]
This is not really possible for our application, as running doxygen takes about 3 hours...

**Comment by ferdymercury** [comment]
- A good amount of time is lost in the custom filter.
- We already did a speedup of the process by using DOT_MULTI_TARGET and parallel processing, as well as some improvements in the filter, and managed to get it down from 6 hours to 3 hours.
- But a significant amount of time is actually spent generating the images, because it depends on calling the software, opening a GUI window and generating a png or pdf, etc.
- The project contains about 20k source files (see https://github.com/root-project/root)
- The number of images created is 925. I.e. we get the console flooded with 925 warnings.
- So that should be about 5%
- Yes, whenever there is an \image command within the .cpp source file doxygen comments, the filter creates an image out of it
- Yes, I could run the images first separately, but that would still cause significant delays, as I would be opening the GUI twice for each of these 925 files, etc. And the warnings would still appear in the console in the first run...

**Comment by albert-github** [comment]
- Is the filter doing something different from generating the images?
- In the separate phase, before the real doxygen run, the images could be generated only from those 925 files (or less when multiple images are generated by one source file)
- In the doxygen run it is not necessary to generate the images again, so this would mean that the filter can be removed from the doxygen run or reduced.

So in this way the time should be identical or even less (as the filter only has to be executed 925 times instead of 20k times).

**Comment by ferdymercury** [comment]
The filter is more complicated, as it creates either an image, or a Python notebook, or a CXX snippet within the html documentation, etc, depending on the special command used.

https://github.com/root-project/root/blob/master/documentation/doxygen/filter.cxx

**Comment by albert-github** [comment]
I assume you refer to the lines:
```
   if (EndsWith(gFileName,".cxx")) gSource = true;
   if (EndsWith(gFileName,".h"))   gHeader = true;
   if (EndsWith(gFileName,".py"))  gPython = true;
```
So couldn't you run  the filter separately over the 925 `.cpp` files and in the doxygen run only over the files files with the extension `.h` and `.py` (as far as I can see the `gFileName` is the name of the file to be filtered), in other words not a general filter by  extension, see `the setting `FILTER_PATTERNS`).
(or is it even more complicated?)

**Comment by ferdymercury** [comment]
Sounds like an option, thanks, but we will have to think if we want to add this extra complexity in our build system, or rather just live with the warnings.

Side question: would it be a useful idea if Doxygen implemented a feature where the custom filter signaled doxygen (via its return value of int main, or something similar) whether the image list has to be updated after this file has been processed ?

**Comment by albert-github** [comment]
Nothing is for free ....
Note you also call ExecuteCommand for e.g. `rm` or `mv` constructs but this can probably be accomplised in a cheaper way by e.g. https://github.com/gulrak/filesystem or C++ calls (see e.g. https://en.cppreference.com/w/cpp/io/c/remove).

Regarding the side question: This would in my opinion not be an option, as now it are images and later it are ... and also the return value is used to signal whether or not an error was seen by the filter (i.e. the `$status` of the process)

**Comment by ferdymercury** [comment]
I understand.
Well, rm or mv are not the problem even if they could be optimized... the real time consumer is calling to "root" and creating the graphical canvases that generate the image.

I was thinking that maybe we can add a 'touch' command in the beginning that creates fake empty images before running doxygen, to prevent the warnings.

**Comment by albert-github** [comment]
A touch would probably also work, but is in my opinion also a bit artificial and how would this work on Windows? (the later would probably need a special command maybe https://stackoverflow.com/questions/30011267/create-an-empty-file-on-the-commandline-in-windows-like-the-linux-touch-command gives some inspiration).

**Comment by ferdymercury** [comment]
We only build the documentation on Linux, so that should not be a problem.
The documentation build shell scripts are anyway Linux-only, see e.g. https://github.com/ferdymercury/root/blob/cmakedoxy/documentation/doxygen/makeCollaborationDiagrams.sh

**Comment by albert-github** [comment]
OK but customers / users ... (they would have to invest some effort in rewriting those shell scripts though)

btw cmake has also a touch command (see https://cmake.org/cmake/help/latest/command/file.html)
