### ISSUE TITLE
warning: no uniquely matching class member found (when nested preprocessor macro declaring function)

### ISSUE THREAD

**Issue by ferdymercury** [doxygen/doxygen#9049]
**Describe the bug**
When running doxygen for the ROOT (C++) package, we get 181 warnings (one for every class) of the following type:
```
Searching for member function documentation...
(...)
warning: no uniquely matching class member found for 
  void MyClassName::Streamer(TBuffer &R__b)
```
and the function does not appear in the HTML output. The function is correctly defined from the C++ point of view, and e.g. Clang or QtCreator IDE locates it correctly and uniquely when CTRL clicking on its name. Compilation with gcc runs smoothly.

It should be mentioned that the function declaration in the header (.h) is done via a (nested) preprocessor C macro with arguments (first macro `ClassDef` calls a second one `_ClassDefOutline_` that finally declares the function `Streamer`). Thus, we set `MACRO_EXPANSION` to `YES` in the Doxyfile. Whereas the function implementation is the one that contains the brief documentation, and is implemented in the source (.cxx) file.

I have tried setting EXPAND_ONLY_PREDEF to YES and then adding the macro name to EXPAND_AS_DEFINED, but to no avail. We also tried converting the macro to 'empty' using the PREDEFINED variable, but same result.

To be more specific, the macros in question are:
```
#define ClassDef(name,id)                            \
   _ClassDefOutline_(name,id,virtual,)               
```

And then:
```
#define _ClassDefOutline_(name,id, virtual_keyword, overrd) \
   virtual_keyword void Streamer(TBuffer& R__b) overrd;
```

The class header TArrayC.h would contain something like:
```
class TArrayC {
public:
ClassDef(TArrayC,1)
};
```

and the TArrayC.cxx has:
```
////////////////////////////////////////////////////////////////////////////////
/// Stream a TArrayC object.

void TArrayC::Streamer(TBuffer &b)
{
}
```
**Expected behavior**
No warning is issued, and the function appears correctly in the HTML output.

**Screenshots**
Find attached the full output log with the 181 warnings (search for ::Streamer). 
[consoleOutput.txt.zip](https://github.com/doxygen/doxygen/files/7890928/consoleOutput.txt.zip)

Here how Doxygen sees the macros:
![image](https://user-images.githubusercontent.com/10653970/150099990-87bcc200-21ad-4f87-b0c1-2f9b710f2829.png)
![image](https://user-images.githubusercontent.com/10653970/150100111-3064cbc9-18aa-4ce7-9bce-a0bf2fe7aba4.png)

**To Reproduce**
I created a minimal reproducer, download [root-docu.zip](https://github.com/doxygen/doxygen/files/7891175/root-docu.zip)
Extract it, go to subfolder documentation/doxygen and run doxygen from there.

**Version**
1.9.4 (99482978eb791a6159c4e409c42ec95acbbd2c1d)

**Additional context**
There are other errors being printed out when running doxygen, but those are understood and being fixed now. It's just the Streamer one that is confusing

**Comment by albert-github** [comment]
Doxygen is a bit picky about handling include files. I think you have to set:
```
SEARCH_INCLUDES        = YES

INCLUDE_PATH           = ../../core/base/inc
INCLUDE_PATH          += ../../core/cont/inc
```
at the moment you have:
SEARCH_INCLUDES        = NO

INCLUDE_PATH           =
```

Btw. Minimal example ....

**Comment by ferdymercury** [comment]
Thanks very much for this solution! It works very well.
