### ISSUE TITLE
Objective C method / property attribute decoration confuses parsing

### ISSUE THREAD

**Issue by will-work** [doxygen/doxygen#9055]
Doxygen 1.9.2 (installed with executable), running on macOS Big Sur, MacBook Pro 2020 M1.

When a property or method declaration in an ObjC h file is decorated with the DEPRECATED_MSG_ATTRIBUTE attribute, Doxygen incorrectly parses the line:
- a property is interpreted as a method with name 'DEPRECATED_MSG_ATTRIBUTE'
- a method is misnamed 'DEPRECATED_MSG_ATTRIBUTE'

The expectation is that parsing ignores the attribute decoration entirely.

Example, containing one h file and Doxyfile:

[Doxygen_bug.zip](https://github.com/doxygen/doxygen/files/7905452/Doxygen_bug.zip)

Many thanks for your consideration.

**Comment by albert-github** [comment]
Looks like related to https://github.com/doxygen/doxygen/issues/5940

In the example the deprecated is now implemented by means of the usage of the `@deprecated` doxygen command, better would be that the `DEPRECATED_MSG_ATTRIBUTE` is implemented.

In the current situation I think that a workaround is to define `DEPRECATED_MSG_ATTRIBUTE(x)=` in the `PREDEFINED` setting.

**Comment by will-work** [comment]
Apologies, that was unintentional, I should have paid attention to the button text.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #9060 that ignores the `DEPRECATED_MSG_ATTRIBUTE` and `DEPRECATED_ATTRIBUTE`.

The underlying, complex, problem of making `DEPRECATED_MSG_ATTRIBUTE` automatically into a `@deprecated` entry, still has to be addressed, see also #5940

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by will-work** [comment]
Thank you Dimitri, I will check.
