### ISSUE TITLE
Problem with endcond within C preprocessor macro

### ISSUE THREAD

**Issue by ferdymercury** [doxygen/doxygen#9056]
**Describe the bug**
Consider the following C++ code snippet:
```
#define ClassImp(name) /** \cond HIDDEN_SYMBOLS */ void myHiddenFunction(); /** \endcond */

/// b
/// a
TString ExpandValue(const char *value) {;}

ClassImp(TEnv)
```
Doxygen issues a warning:
```
TEnv.cxx:7: warning: Conditional section with label 'HIDDEN_SYMBOLS' does not have a corresponding \endcond command within this file.
TEnv.cxx:8: warning: Reached end of file while still inside a (nested) comment. Nesting level 1 (probable line reference: 7)
```
And a weird effect: if I delete line 4 from this snippet, the warning magically disappears.

**Expected behavior**
No warning is raised.

**Screenshots**
```
Parsing files
Preprocessing TEnv.cxx...
TEnv.cxx:7: warning: Conditional section with label 'HIDDEN_SYMBOLS' does not have a corresponding \endcond command within this file.
TEnv.cxx:8: warning: Reached end of file while still inside a (nested) comment. Nesting level 1 (probable line reference: 7)
Parsing file TEnv.cxx...
Building macro definition list...
```

**To Reproduce**
[mismatch.zip](https://github.com/doxygen/doxygen/files/7909265/mismatch.zip)

**Version**
1.9.4 (99482978eb791a6159c4e409c42ec95acbbd2c1d*)

**Additional context**
Maybe a duplicate of https://github.com/doxygen/doxygen/issues/7873
https://github.com/doxygen/doxygen/pull/7876
https://github.com/doxygen/doxygen/issues/7887

**Comment by ferdymercury** [comment]
I confirm that the warning disappears if I add https://github.com/doxygen/doxygen/pull/7876/files#diff-c36b9991bc7e5506ac9fb5614fda4c61a5eea707e7873ff87beb367188993522R756 to line 841 in current Master.

**Comment by albert-github** [comment]
As the issue is the same  / similar as mentioned in #7873 and has a proposed pull request there (#7876) I set this bug to duplicate.
(Thanks for the pointer to the already existing proposed pull request)

**Comment by albert-github** [comment]
Pull request #7876 has been integrated in the master version of doxygen.

**Comment by ferdymercury** [comment]
Amazing, thanks so much for the prompt response, as always :)

**Comment by ferdymercury** [comment]
Should it be marked as 'fixed but not released' ?

**Comment by albert-github** [comment]
As it is set to `duplicate` it is not necessary to set it to `fixed but not released` (issues with these types of labels will be closed at the next release).
