### ISSUE TITLE
Allow external mscgen

### ISSUE THREAD

**Issue by tmpgnh** [doxygen/doxygen#9057]
**Describe the bug**
Prior to 1.9 I could use an external alternative to the -- now inlined -- MSC generator, and make use of a much extended chart syntax.

**Expected behavior**
With a configuration option I would like to tell doxygen to try using an external program for MSCs -- the now obsoleted MSCGEN_PATH would be a perfect fit.

**Version**
I'm using 1.9.1 on Debian/bullseye and onwards, and Ubuntu/Hirsute.

I try to provide a patch in a PR.

**Comment by albert-github** [comment]
I think this problem might be related to #7994

**Comment by albert-github** [comment]
Ps. Please don't use "Linked pull requests " as this would disrupt the doxygen workflow when the pull request would be integrated.

**Comment by tmpgnh** [comment]
> Ps. Please don't use "Linked pull requests " as this would disrupt the doxygen workflow when the pull request would be integrated.

Sorry; should I try to remove the link (I guess the 'fixxes NN' in the commit message)?

**Comment by albert-github** [comment]
Yes please.

See for a workflow / formulation I always use e.g. https://github.com/doxygen/doxygen/issues/9027#issuecomment-1012412610 and when the proposed pull request is integrated in the master I always try to set the fixed label and use a text like in https://github.com/doxygen/doxygen/issues/9027#issuecomment-1013646990

**Comment by tmpgnh** [comment]
Propose patch in https://github.com/tmpgnh/doxygen/pull/1

**Comment by albert-github** [comment]
@tmpgnh When you have a finished patch you should make a pull request to the doxygen repository.

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.7.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
