### ISSUE TITLE
Error generating "index.hhc" for linking to external class hierarchy (Origin: bugzilla #128094)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#906]
status NEW severity *major* in component *build* for *---*
Reported in version *1.3.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2003-11-28 07:57:58 +0000, somnath@techsoftpl.com wrote:

    Hello,
    
    I am using tag file to link to a different external ".chm" file and it 
    works fine in the generated HTML files. But when creating "index.hhc" 
    file for the "Class Hierarchy", links for the external classes are NOT 
    pre-pended with the name of the CHM file (i.e., only âfile_name.html â 
    instead of âsample.chm::/file_name.htmlâ). As a result, when an external
    class is selected under Class Hierarchy on the content pane, an 
    error "This page cannot be displayed" is generated because the referenced 
    file is in the external ".chm" file.
    
    Regards,
    Somnath

**Comment by albert-github** [comment]
Due to a missing example this issue is not reproducible / it is not complete.
Recent versions of doxygen have no problems as indicated.

Setting issue as not complete.
