### ISSUE TITLE
Incorrect namespace for related function

### ISSUE THREAD

**Issue by SignalWhisperer** [doxygen/doxygen#9083]
**Describe the bug**
In C++, a related free-standing function is put in the wrong namespace and shown in the same namespace as a class member instead of in the actual namespace it's in.

**Expected behavior**
The free-standing function should be placed in the namespace it actually resides in, while still being marked as a related function.

**Screenshots**
`gamma()` is a free-standing function in the `foo` namespace but shows up in the `foo::bar` class namespace when viewing all member functions.
![image](https://user-images.githubusercontent.com/772200/151567326-832ab3df-fddb-44c4-9ba1-0625c5f82f47.png)

`gamma()` is properly shown as a related function of the `foo::bar` class.
![image](https://user-images.githubusercontent.com/772200/151569177-f49a348b-2201-44dd-9e51-2814b98d3f6f.png)

**To Reproduce**
`Doxyfile`:
```doxygen
PROJECT_NAME = "My Project"
```

`main.cpp`:
```c++
namespace foo {
    struct bar {
        /// Alpha function
        void alpha();
        /// Beta function
        void beta();
    };

    /// Gamma function
    /// @relates bar
    void gamma();
}

int main(int, char**) {}
```

Generate with: `doxygen Doxyfile`

In the screenshot is: `/html/functions_func.html`

**Version**
doxygen 1.9.3, downloaded in binary form (Linux) from the Doxygen website.

**Comment by jwakely** [comment]
Isn't this exactly what the documentation says should happen?

https://www.doxygen.nl/manual/commands.html#cmdrelates

> This command can be used in the documentation of a non-member function \<name>. It puts the function inside the 'related function' section of the class documentation. This command is useful for documenting non-friend functions that are nevertheless strongly coupled to a certain class. It prevents the need of having to document a file, but only works for functions.

**Comment by SignalWhisperer** [comment]
I believe you are correct. I should have RTFM first, sorry. Time to raise the issue back to Asio.

The command I would want to use in this case would be `\relatesalso`.
