### ISSUE TITLE
How to generate a function index?

### ISSUE THREAD

**Issue by paddor** [doxygen/doxygen#9107]
I'm generating documentation from a C library. I see a page of structs, but no page of functions. I'd have to go to the list of files and then click on the specific file to see all its functions.

Ideally I'd see all functions with the same prefix as the struct I'm looking at. E. g. on the page for `struct XY_MyThing` (typedef'd to `XY_MyThing`) I'd not only see all its field, but also see a list of functions like `XY_MyThing_init(XY_MyThing *thing)` and `XY_MyThing_setFoo(XY_MyThing *thing, const char *foo)`.

I can't find an option for this in the FAQ nor in the generated Doxyfile.

**Comment by albert-github** [comment]
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.
- Please also specify the **full** doxygen version used (`doxygen -v`).

**Comment by albert-github** [comment]
Problem might be. but without example it is all a bit guessing:
- missing documentation for the structs or an encompassing part (try `EXTRACT_ALL=YES`)

You could wrap up an example with just one struct in it and your used Doxyfile and show this as an example (after, of course, locally testing it).

**Comment by paddor** [comment]
I do have `EXTRACT_ALL=YES` set. The structs are documented just fine. But there's no function index. I'd like to have an index of all functions.

**Comment by albert-github** [comment]
Example please so we can se what you are missing.

**Comment by paddor** [comment]
@ferdymercury Thanks for the help but that page only lists functions starting with "a". Yes, I do have ALPHABETICAL_INDEX enabled.

**Comment by albert-github** [comment]
@paddor to be able to help you properly we **need** a small example (at least the Doxyfile and some images showing what you see and what you would expect, also a complete example would be beneficial as well):
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

**Comment by paddor** [comment]
I'd appreciate it if you could just tell me whether Doxygen has this feature or not. I'm starting to think that it's lacking this very basic feature. It's a **function index of all function**.

**Comment by albert-github** [comment]
I think that this is available:

![image](https://user-images.githubusercontent.com/5223533/154041964-2abf000d-75b6-47b5-b6eb-30da873a4617.png)

this image is taken for the documentation of the doxygen internal docs.

Or as showing the functions:
![image](https://user-images.githubusercontent.com/5223533/154042289-5e08bffa-d776-4a52-b609-5f622af4c8f7.png)

Maybe there is something else that you define as a function index of all function, in that case you have to explain and show what you mean.

**Comment by ferdymercury** [comment]
Maybe the problem is that, ¿in older versions of doxygen?, the global function index only shows those starting with letter 'a', there is no global overview. For example, in https://itk.org/Doxygen/html/functions_func.html it only lists letter 'a', not the global overview, even if you haven't specified letter 'a' to be shown?

> @ferdymercury Thanks for the help but that page only lists functions starting with "a". Yes, I do have ALPHABETICAL_INDEX enabled.

If you want to the full overview, instead of just split by letter, go to:

https://itk.org/Doxygen/html/globals_func.html

instead of 

https://itk.org/Doxygen/html/functions_func.html

**Comment by albert-github** [comment]
I didn't yet dig deeper, but your Doxyfile contains some error:
```
ABBREVIATE_BRIEF       = "The $name class" \
ALWAYS_DETAILED_SEC    = NO
...
FILE_PATTERNS          = *.c \
RECURSIVE              = YES
```
(saw this by using `doxygen -x Doxyfile` which gives:
```
# Difference with default Doxyfile 1.9.3 (c0b9eafbfb53286ce31e75e2b6c976ee4d345473)
ABBREVIATE_BRIEF       = "The $name class" \
                         ALWAYS_DETAILED_SEC \
                         = \
                         NO
OPTIMIZE_OUTPUT_FOR_C  = YES
TYPEDEF_HIDES_STRUCT   = YES
EXTRACT_ALL            = YES
EXTRACT_PRIVATE        = YES
CASE_SENSE_NAMES       = YES
INPUT                  = include \
                         src
FILE_PATTERNS          = *.c \
                         RECURSIVE \
                         = \
                         YES
MATHJAX_RELPATH        = https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/
HAVE_DOT               = YES
```
)

Maybe you should correct this first.

**Comment by albert-github** [comment]
I looked at the results of the https://github.com/open62541/open62541project with an adjusted Doxyfile
```
QUIET=YES
ABBREVIATE_BRIEF       = "The $name class" \
ALWAYS_DETAILED_SEC = NO
OPTIMIZE_OUTPUT_FOR_C  = YES
TYPEDEF_HIDES_STRUCT   = YES
EXTRACT_ALL            = YES
EXTRACT_PRIVATE        = YES
CASE_SENSE_NAMES       = YES
INPUT                  = include \
                         src
FILE_PATTERNS          = *.c *.h
RECURSIVE = YES
MATHJAX_RELPATH        = https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/
HAVE_DOT               = YES

```
and I see that the information looks all to be present but hard to reach.
In the code I found 2 magic numbers:
```
#define MAX_ITEMS_BEFORE_MULTIPAGE_INDEX 200
#define MAX_ITEMS_BEFORE_QUICK_INDEX 30
```
and especially the `MAX_ITEMS_BEFORE_MULTIPAGE_INDEX` limits here the undestandability (in my opinion).


@doxygen 
- shouldn't these magic numbers no been made available through a setting in the configuration file?
- shouldn't these limits (and their implications) be documented?

**Comment by albert-github** [comment]
Why not use `doxygen -x Doxyfile` so that only the relevant parts remain?

**Comment by paddor** [comment]
I didn't know that option. Here's it:
```
# Difference with default Doxyfile 1.9.3 (c0b9eafbfb53286ce31e75e2b6c976ee4d345473)
OPTIMIZE_OUTPUT_FOR_C  = YES
EXTRACT_ALL            = YES
EXTRACT_PRIVATE        = YES
EXTRACT_STATIC         = YES
INPUT                  = include \
                         src
RECURSIVE              = YES
```

I just set these manually again after generating a new Doxyfile using Doxygen 1.9.3. Maybe they're not perfect. But the result is still the same.

I'll try with those two `#define` numbers increased.

**Comment by albert-github** [comment]
I assume that you mean 2 things:
- no call signatures, this would be an enhancement, 
- no function list on the data structure pages, which page exactly?
  Isn't the following what you mean?
  
  ![image](https://user-images.githubusercontent.com/5223533/154109591-dd8bd5ed-bab8-4cde-85f5-6dda93c5a8ab.png)

**Comment by mma666** [comment]
Hi @paddor ,

I'm new to Doxygen and was curious about your question. So i did some experiments with that library. I think you can find what you are looking for in:  Files>Globals>Functions>...

Here is my difference table:
```
# Difference with default Doxyfile 1.8.17
OPTIMIZE_OUTPUT_FOR_C  = YES
EXTRACT_ALL            = YES
EXTRACT_PRIVATE        = YES
EXTRACT_PRIV_VIRTUAL   = YES
EXTRACT_STATIC         = YES
RECURSIVE              = YES
```

Hope it helps.

**Comment by ferdymercury** [comment]
Maybe related: https://github.com/doxygen/doxygen/issues/4111

**Comment by ferdymercury** [comment]
And another one: https://github.com/doxygen/doxygen/issues/5812

**Comment by 8dcc** [comment]
> I think that this is available:
> 
> [image]
> 
> this image is taken for the documentation of the doxygen internal docs (form a recent master version).
> 
> Or as showing the functions: [image]
> 
> Maybe there is something else that you define as a function index of all function, in that case you have to explain and show what you mean.

This is what I get when I go to that same page when generating the docs with `doxygen 1.9.6` on Linux:

![image](https://user-images.githubusercontent.com/29655971/231242358-c01a4c1a-a91d-47ad-8a1e-f57d45dfe8e5.png)

Not sure if this is a feature, or if this can be changed, but each page shows only the functions that start with their letter, and `globals.html` (screenshot) has only the functions that start with the first letter.

**Comment by ingo-h** [comment]
As already shown by others a function index is available. But I get the same problem as @paddor. I have to re-engineer a somewhat bigger program and started documenting it with doxygen. To see how it works I use two simple free functions with nearly no dependencies. Doxygen passes without any warning. But when looking at the Files list there is no **Globals** sub menu where I should find the function index.
![](file:///tmp/Screenshot_2024-01-17_21-27-11.png)

But the functions are available an properly documented:
![](file:///tmp/Screenshot_2024-01-17_21-41-06.png)

**Comment by ingo-h** [comment]
@albert-github asked for a small, self contained example to verify this. To understand whats going on I have made one. But surprisingly that works as expected. But to have a common test base here is it. All is done in one directory:

    $ cat hello.hpp
    #ifndef HELLO_HPP
    #define HELLO_HPP
    /*!
     * \file
     * \brief Declaration of a free function.
     */

    #include <string>

    /*!
     * \brief Free function to output "hello world".
     */
    std::string hello();

    #endif // HELLO_HPP
.

    $ cat hello.cpp
    /*!
     * \file
     * \brief Definition of a free function.
     */

    #include "hello.hpp"

    /*!
     * This very simple free function is to demonstrate an issue with doxygen.
     */
    std::string hello() {
        return "hello world";
    }
.

    $ cat hello_main.cpp
    /*!
     * \file
     * \brief main() entry point.
     */

    #include "hello.hpp"
    #include <iostream>

    /*!
     * \brief Main function to output "hello world".
     *
     * This is the main entry point of the program to output "hello world".
     */
    int main() {
        std::cout << hello() << '\n';
        return 0;
    }

My settings:

    $ doxygen -x
    # Difference with default Doxyfile 1.9.4
    PROJECT_NAME           = "doxygen issue"
    PROJECT_NUMBER         = 4111.1
    PROJECT_BRIEF          = "Simple project to show issue 4111 on doxygen."
    GENERATE_LATEX         = NO

And this is what I want to get in my project:

![image](https://github.com/doxygen/doxygen/assets/29997944/f1bf357e-8943-4102-90ab-c4d162b32ece)

I will look at it.

**Comment by ingo-h** [comment]
The problem is located.

Only functions within the default namespace are seen. If I put `hello()` into another namespace e.g. `myns::hello()` then doxygen does not find it. With my library I **must** use namespaces. I will now have a look at the documentation if this is handled.

Here is the verification. With 4 added lines and one modified to the code of the test program above I put the function into `namespace myns {}`.

    $ cat hello.hpp
    #ifndef HELLO_HPP
    #define HELLO_HPP
    /*!
     * \file
     * \brief Declaration of a free function.
     */

    #include <string>

    namespace myns {

    /*!
     * \brief Free function to output "hello world".
     */
    std::string hello();

    } // namespace myns

    #endif // HELLO_HPP
.

    $ cat hello.cpp
    /*!
     * \file
     * \brief Definition of a free function.
     */

    #include "hello.hpp"

    namespace myns {

    /*!
     * This very simple free function is to demonstrate an issue with doxygen.
     */
    std::string hello() {
        return "hello world";
    }

    } // namespace myns
.

    $ cat hello_main.cpp
    /*!
     * \file
     * \brief main() entry point.
     */

    #include "hello.hpp"
    #include <iostream>

    /*!
     * \brief Main function to output "hello world".
     *
     * This is the main entry point of the program to output "hello world".
     */
    int main() {
        std::cout << myns::hello() << '\n';
        return 0;
    }

**Comment by ingo-h** [comment]
OK, documenting the namespace will give an additional `namespace`tab in the online (html) documentation where I find the functions belonging to the namespace. But what file they are located? The `files`tab only list functions in the default namespace and the `namespace`tab only list functions in namespaces with names.

My understanding of a structured design is to list with namespaces **all** namespaces, means also the default namespace. And with files should **all** functions be listed that are contained in a file, no matter what namespace they belong to. Could this be a feature request?
