### ISSUE TITLE
doxygen confused with C++ visibility attribute

### ISSUE THREAD

**Issue by ferdymercury** [doxygen/doxygen#9142]
**Describe the bug**
We get a warning when using a C++ visibility attribute:

`streamer/rootclingTCling.h:32: warning: Found ';' while parsing initializer list! (doxygen could be confused by a macro call without semicolon)`

**Expected behavior**
No warning is raised.

**Screenshots**
```
#ifndef R__DLLIMPORT
// I.e. we are imported.
# if _WIN32
#  define R__DLLIMPORT __declspec(dllimport)
# else
#  define R__DLLIMPORT __attribute__ ((visibility ("default")))
# endif
#endif

extern "C" {
   R__DLLIMPORT const char ** *TROOT__GetExtraInterpreterArgs();
   R__DLLIMPORT const char *TROOT__GetIncludeDir();
   R__DLLIMPORT const char *TROOT__GetEtcDir();
   R__DLLIMPORT cling::Interpreter *TCling__GetInterpreter();
}
```

**To Reproduce**
[streamer.zip](https://github.com/doxygen/doxygen/files/8112715/streamer.zip)

**Version**
1.9.4 (15dae504a167d838873053cc96417d8beae78df7*)

**Additional context**
https://gcc.gnu.org/wiki/Visibility

**Comment by albert-github** [comment]
I think this is usage.
When we run the example with `doxygen -d preprocessor` we get:
```
00028 extern "C" {
00029     __attribute__ ((visibility ("default")))  const char ** *TROOT__GetExtraInterpreterArgs();
00030     __attribute__ ((visibility ("default")))  const char *TROOT__GetIncludeDir();
00031     __attribute__ ((visibility ("default")))  const char *TROOT__GetEtcDir();
00032     __attribute__ ((visibility ("default")))  cling::Interpreter *TCling__GetInterpreter();
00033 }
```
and `__attribute__` (or __dclspec` is not something defined in the C++ standard.. When setting:
```
PREDEFINED = __attribute__(x)=
```
in the `Doxyfile` we get:
```
00028 extern "C" {
00029       const char ** *TROOT__GetExtraInterpreterArgs();
00030       const char *TROOT__GetIncludeDir();
00031       const char *TROOT__GetEtcDir();
00032       cling::Interpreter *TCling__GetInterpreter();
00033 }
```

So I think the problem is usage.

See also https://www.doxygen.nl/manual/preprocessing.html

**Comment by ferdymercury** [comment]
Sorry for the noise, and thanks for the clarification.
