### ISSUE TITLE
wrong value of <innergroup> atribute in XML output (Origin: bugzilla #128964)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#915]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.3.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2003-12-10 11:21:23 +0000, dryzhov@module.ru wrote:

    This bug occurs in XML output.
    Now in tag <innergroup> attribute refid has a value of base file name for 
    parent group:
    
    <compounddef kind="group">
        <compoundname> ParentCompoundName </compoundname>
        <innergroup refid="group__ParentCompoundName"> InnerGroupTitle 
    </innergroup>
    </compounddef>
    
    So the value of refid atrribute does't contain any useful information.
    It would be more useful for attribute refid to contain name of the file 
    with inner group declararation:
    
    <compounddef kind="group">
        <compoundname> ParentCompoundName </compoundname>
        <innergroup refid="group__InnerGroupCompoundName1"> InnerGroupTitle1 
    </innergroup>
    </compounddef>
    
    To fix this bug change code string in function generateXMLForGroup in file 
    xmlgen.cpp:
    
    t << "    <innergroup refid=\"" << gd->getOutputFileBase()
    by string
    t << "    <innergroup refid=\"" << sgd->getOutputFileBase()

**Comment by albert-github** [comment]
In the code of version 1.3.5 I see the statement:
`t << "    <innergroup refid=\"" << gd->getOutputFileBase()`
in version 1.3.6  (and still present in newer versions) it is replaced by:
`t << "    <innergroup refid=\"" << sgd->getOutputFileBase()`

So I think the problem has been resolved in the mean time.
