### ISSUE TITLE
ALIASES won't expand newlines between verbatim tags for XML output

### ISSUE THREAD

**Issue by lcsmuller** [doxygen/doxygen#9168]
**Describe the bug**
When declaring the following Doxyfile aliases, the first one containing `^^` inside of verbatim and the second one without verbatim (for output control):
```
ALIASES = "test_with_verbatim=\verbatim hello^^world \endverbatim^^" \
          "test_without_verbatim=hello^^world^^"
```
and using them with following C header file:
```c
/**
* @test_with_verbatim
* @test_without_verbatim
*/
struct foo {
    int a;
};
```
this is the resulting expansion (run with `doxygen -d commentcnv`):
```
/** 
 * \verbatim hello\\_linebr world \endverbatim\\_linebr 
 * hello\\_linebr world\\_linebr 
 */
struct foo {
    int a;
};
```
and this is the resulting XML output:
```xml
<detaileddescription>
<para><verbatim>hello\
 world </verbatim> hello world </para>
</detaileddescription>
```

**Expected behavior**
expand `^^` to actual newlines between verbatim tags, or have the backslash expansion documented
```diff
<detaileddescription>
- <para><verbatim>hello\
+ <para><verbatim>hello
world </verbatim> hello world </para>
</detaileddescription>
```

**Screenshots**

**To Reproduce**
[doxygen_issue.zip](https://github.com/doxygen/doxygen/files/8146974/doxygen_issue.zip)

Perform a controlled expansion of ALIASES
```
doxygen -d commentcnv > out.txt
```
this will output a `out.txt` containing the raw alias expansion, and a `xml/structfoo.xml` file containing the XML output of interest.

**Version**
Doxygen 1.8.17
Running on Linux Mint 20 (ulyana)

**Stack trace**

**Additional context**
The newline expansion differs between a `^^` written inside and outside verbatim tags, for that reason if this is intentional behavior I think it would make sense to have it be documented so integrations such as Breathe can be aware of it and replace `\` with a newline themselves.

**Comment by albert-github** [comment]
In the 1.8.17 version I see:
HTML:
![image](https://user-images.githubusercontent.com/5223533/155851095-c60d8f54-b5fc-429f-bf2e-6bd7957de778.png)

and XML:
```
    <detaileddescription>
<para><verbatim>hello\
 world </verbatim> hello world </para>
    </detaileddescription>
```

So here there is the extra baclkslash (`\`)

In the 1.9.3 version I see:
HTML:
![image](https://user-images.githubusercontent.com/5223533/155851164-d6ec3402-b059-4bc8-a14e-80b5afb837fd.png)

XML
```
    <detaileddescription>
<para><verbatim>hello
 world </verbatim> hello world </para>
    </detaileddescription>
```
so no backslash anymore.

I think the problem has been solved in the mean time.

**Comment by lcsmuller** [comment]
Thanks for the swift response! So this particular issue seems to be fixed, I will fetch the latest version and update with another issue if something else arises.
