### ISSUE TITLE
Doxygen cannot resolve link to HTML anchor page

### ISSUE THREAD

**Issue by lcarlier** [doxygen/doxygen#9200]
**Describe the bug**
Doxygen cannot resolve link to HTML anchor page in the same document.
![image](https://user-images.githubusercontent.com/5570374/157910517-1e257188-dba3-4fa2-a80e-2f957d10793d.png)

**Expected behavior**
The link should be generated
![image](https://user-images.githubusercontent.com/5570374/157910867-0dae39a5-b32c-4dc9-8f4a-c68cba31e567.png)

**Screenshots**
/home/lcarlier/Projects/bugDoxygen/README.md:6: warning: unable to resolve reference to 'user-content-as' for \ref command
/home/lcarlier/Projects/bugDoxygen/README.md:6: warning: unable to resolve reference to 'user-content-as' for \ref command

**To Reproduce**
Untar the attached tar ball and execute doxygen using the contained doxyfile.
[bugDoxygen.tar.gz](https://github.com/doxygen/doxygen/files/8233783/bugDoxygen.tar.gz)

**Version**
This is a regression.
The patch introducing the problem is 3a4db857340aeff18dcd57291e036809a0273449
The parent version is working fine.

**Stack trace**
NA

**Additional context**
I was trying to find a fix but it isn't clear to me what could be the right solution. I thought of adding the section manually via SectionManager::instance().add but the name of the output HTML isn't known inside markdown.cpp so I'm not sure whether that would be the right thing to do.

Looking at the updated documentation, it seems that some inconsistencies have been introduced.

This is the patch I was trying but it isn't working
```
diff --git a/src/markdown.cpp b/src/markdown.cpp
index bacefc85..f8ddeeb5 100644
--- a/src/markdown.cpp
+++ b/src/markdown.cpp
@@ -52,6 +52,7 @@
 #include "regex.h"
 #include "fileinfo.h"
 #include "utf8.h"
+#include "pagedef.h"
 
 enum class ExplicitPageResult
 {
@@ -1225,7 +1226,8 @@ int Markdown::processLink(const char *data,int,int size)
         m_out.addStr(" \"");
         m_out.addStr(substitute(content.simplifyWhiteSpace(),"\"","&quot;"));
         m_out.addStr("\"");
-
+        SectionManager::instance().add(&link.data()[1],
+                                       m_fileName,-1,title,SectionType::Anchor,0,"");
       }
       else
       {
```

**Comment by albert-github** [comment]
I see a second one missing as well, i.e. with an explicit link:
```
* [A second section](#user-content-as)
```

**Comment by albert-github** [comment]
I tried the "patch" but this gives some new problems when we have the file `README.md` as:
```
# Welcome to Bug readme
## <a name="user-content-as"></a> Problem with the link
The link in the table of contect isn't correctly generated and a warning appears saying it can't resolve \\ref for user-content-as

I would expect the link to be correct generated

## Table of content
* [A section][as]
* [A second section](#user-content-as)

[as]: #user-content-as


## Header 1

## Header 2 {#label_header_2}

[Link to header 1](#header-1)

[Link to header 2](#label_header_2)
```
we get the warning:
```
.../README.md:16: warning: multiple use of section label 'label_header_2' while adding section, (first occurrence: .../README.md)
```

Furthermore `[Link to header 1](#header-1)` will show as a link and this is incorrect as discussed at #8956

**Comment by lcarlier** [comment]
The patch isn't working indeed. It is a failed attempt.

I'm not sure this is the right solution though. We would need a way to know whether the `#link` corresponds to a class or an internal page link.

**Comment by albert-github** [comment]
Indeed, I'm looking into the problem (might take a little while though).

**Comment by lcarlier** [comment]
I just though if this quick and dirty fix...

https://github.com/doxygen/doxygen/pull/9201

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #9204

**Comment by lcarlier** [comment]
I'll test this probably Thursday or Friday

**Comment by lcarlier** [comment]
Fixed by https://github.com/doxygen/doxygen/pull/9204

Thanks a lot.

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.4.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Comment by rpadaki** [comment]
As far as I can tell, this is not actually fixed? On 1.9.4 I tried building the original reproduction here, and I get the same warning. It's clear when setting `WARN_AS_ERROR = YES`.

**Comment by albert-github** [comment]
@rpadaki  It is seen.
I again ran the original problem with version 1.9.3 (I didn't set `WARN_AS_ERROR` but I set `QUIET=YES`) an got the message:
```
README.md:8: warning: unable to resolve reference to 'user-content-as' for \ref command
```
with the 1.9.4 version I didn't get this warning.
- can you run `doxygen -v`
- on which OS are you running
- can you share the complete project (i.e. the input and the resulting output) in a, compressed, tar or zip file. (so we can do a comparison)

**Comment by rpadaki** [comment]
Yay! I'm on macOS, and `doxygen -v` shows `1.9.4`.

I slightly misspoke -- the project from the issue description is fine, but setting the readme from your comment above (https://github.com/doxygen/doxygen/issues/9200#issuecomment-1065347202) causes the failure.

Here's a tar file with the Readme and Doxyfile to reproduce, along with the html generated by my run: [repro.tar.gz](https://github.com/doxygen/doxygen/files/8781271/repro.tar.gz).

-----------

The key issue I've been running into is that I want a Markdown file in which `[Section](#Section)` properly links to the target `## Section` in GitHub, but also allows Doxygen to build without warnings. It'd be nice, though not essential, for Doxygen to also properly handle those links properly.

**Comment by albert-github** [comment]
The problem of the `header-1` is that for "Section" without an explicit anchor the, display, code creates its own anchor.
Doxygen doesn't do this as the `Section` might be in different files or multiple times in the same file and thus is is not possible to create an unique and persistent anchor.
I also haven't seen an (in)formal definition / standard that would describe this issue (section anchors are not part of any markdown standard I'm aware of)

When we look at the following snippet
```
This is a test

# The first chapter
## Section

# The second chapter
## Section

# The third chapter
[Section](#Section)
```

- Where should the link point to?
- How should the individual `Section`s be addressed?
- What would happen when an extra chapter was inserted between the first and second chapter?

**Comment by rpadaki** [comment]
What you say makes sense -- as far as I know, GitHub-flavored markdown never explicitly explains how these fragment identifiers are generated.

If there's no way to make Doxygen go through the same decision-making process, I'm left with the options of either breaking links on GitHub or ignoring these Doxygen warnings?

What's interesting is that in an Ubuntu 20.04 Docker container, Doxygen v1.8.17 builds this example with no warnings. Obviously, the `#header-1` link doesn't do anything. I guess it's probably desirable to warn in that case, though.

My best bet, then, is to try and get creative with adding HTML tags surrounding my section headings until I can get something that works in both cases. Thanks for your help.

**Comment by albert-github** [comment]
You wrote:
> GitHub-flavored markdown never explicitly explains how these fragment identifiers are generated.

and

> If there's no way to make Doxygen go through the same decision-making process,

How would doxygen be able to go through the the same decision-making process when GitHub doesn't explain how they are generated?

The fact that doxygen 1.8.17 doesn't gave a warning can be considered as a bug in that version that has been fixed.

I think that best is indeed to use  HTML tags as in that way you can steer the anchor creating as well as the reference to the anchors with `<H...>` and <A ..>` tags.

Maybe an idea that you post an issue with GitHub  with code like:
```
# The first chapter
## Section

# The second chapter
## Section

# The third chapter
[Section](#Section)
```
and ask them how they would reference the `Section` in the `First chapter` and in the `Second chapter` and ask them also to describe the identifier generation mechanism. This might give some insight and something to work with.

**Comment by lcarlier** [comment]
I confirm that on my side version 1.9.4 fixes the bug

Thank you very much.
