### ISSUE TITLE
Doxygen issue with a special function FUNC(..)

### ISSUE THREAD

**Issue by cata2208** [doxygen/doxygen#9209]
Hi,

I have defined my function and wrote a short doxygen comment like this: 

/** **********************************************************************
@brief           Callback function 
@pre             none
@post            none
@param           none
@return          void

 **************************************************************************** */
FUNC(void, APPL_CODE) TSNotif (void)
{
}

As a result in *.chm file the TSNotif function is not recognized, only the FUNC. please see the attached picture
![FUNC](https://user-images.githubusercontent.com/101633602/158352876-85c40b3a-8db9-4e22-b6cb-c13f40cdea9b.PNG)

Can you please help me to solve this probem?

Thanks,
Catalin Bogdan

**Comment by albert-github** [comment]
Most likely a problem with your preprocessing settings, but to be able to help we need:
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.
- Please also specify the **full** doxygen version used (`doxygen -v`).

**Comment by cata2208** [comment]
[github_FUNC.zip](https://github.com/doxygen/doxygen/files/8253869/github_FUNC.zip)

I'm using:

- Doxygen 1.9.2
- graphviz_2.38
- hhc_1.3
- plantuml_1.2021

**Comment by albert-github** [comment]
I don't see a definition of `FUNC` in the provided `SwComp_SrcC.c`, just the code you mentioned plus some `include` statements of which only the `SwComp_SrcC.h` is provided in the example.
We need to know the definition of `FUNC` which probably will be something like
```
#define FUNC(x,y) x
```
(maybe in `Platform_Types.h` or `glob_defs.h` or ...)

**Comment by cata2208** [comment]
Definition was included in a file outside of *.zip:
/** \brief abstraction for function declaration and definition
 **
 ** This macro abstracts the declaration and definition of functions
 ** and ensures the correct syntax of function declaration as
 ** required by the specific compiler.
 **
 ** \param[in] rettype return type of the function
 ** \param[in] memclass classification of the function itself */
#define FUNC(rettype, memclass) memclass rettype

#define APPL_CODE

**Comment by albert-github** [comment]
One of the known files, which one?

**Comment by cata2208** [comment]
The solution is not working. If it is working for you, please send me the config file!

**Comment by albert-github** [comment]
I gave 2 solutions:
1. set `EXPAND_ONLY_PREDEF     = NO` in the `Doxyfile.doxy`, which requires the code as given in https://github.com/doxygen/doxygen/issues/9209#issuecomment-1068057648 is available in e.g. `SwComp_SrcC.h`. [sol_1.tar.gz](https://github.com/doxygen/doxygen/files/8260265/sol_1.tar.gz)

2. set `PREDEFINED             = "FUNC(x,y)=y x"` and `PREDEFINED            += APPL_CODE=` in  the `Doxyfile.doxy` (maybe you tried this solution but there was a small typo in the original comment I wrote `APPLE_CODE` instead of `APPL_CODE`). [sol_2.tar.gz](https://github.com/doxygen/doxygen/files/8260267/sol_2.tar.gz)


So which version is not working for you?

**Comment by dhunter-git** [comment]
https://github.com/doxygen/doxygen/issues/9209#issuecomment-1068870822

I try this 2 solutions.

1 is not working
but 2 is working.

It's not perfect, but I'm happy with this result.
