### ISSUE TITLE
Undocumented external namespaces from .tags files are shown in output Namespace index

### ISSUE THREAD

**Issue by oblivioncth** [doxygen/doxygen#9241]
No one seems to have any comment about this on stackoverflow so I'm filling a report since I believe this to be a bug; however, this is my first time using Doxygen so I'm not sure.

**Describe the bug**
The output documentation for my project shows namespaces from external tag files (Qt documentation) within the Namespace view as if they were my own namespaces. They appear without a hyperlink and no description, and there is definitely no documentation for them within my project, nor are there members added to them within my code.

**Expected behavior**
Namespaces within external documentation that are included via .tags files don't appear in my output documentation unless I explicitly add documentation for those namespaces via the \namespace command.

Perhaps what I'm experiencing is intended behavior, but I'm not sure why that would be.

**Screenshots**
![OGecB](https://user-images.githubusercontent.com/24661585/161124361-24c3a6ac-7ebb-490b-a6c1-b6b35e461ccc.png)

The only namespace here that is actually in my project is 'Qx'.

**To Reproduce**
[Doxy_External_Namespace_Issue_MRE.zip](https://github.com/doxygen/doxygen/files/8392139/Doxy_External_Namespace_Issue_MRE.zip)

The tags in question are from the docs of Qt 6.2.3 and are provided with the above example.

**Version**
Latest stable release from site:
1.9.3 (c0b9eafbfb53286ce31e75e2b6c976ee4d345473) 
Windows x64

**Additional context**
It's possible that the Qt tags are ill-formed since they are generated by QDoc (i.e. could be a bug with that), though personally (without knowing all of the ins-and-outs of Doxygen) I would also somewhat expect external tags to not be capable of producing documentation like this under any circumstances so I'd be a little surprised if that was the case.

Possibly a regression of #5258, but I don't believe these namespaces are nested under anything not shown in the above output.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #9245

**Comment by oblivioncth** [comment]
Thanks for making the change so quickly.

Once it's merged I'll download the related artifact and confirm the fix.

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.4.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Comment by oblivioncth** [comment]
Tested artifacts of 5d15657a55555e6181a7830a5c723af75e7577e2 and can confirm that the behavior is now as I originally expected.

Thanks again.
