### ISSUE TITLE
Python: documented symbol XYZ was not declared or defined

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [doxygen/doxygen#9259]
I got this error because of a "private" and local variable in a Python function.
```
Searching for member function documentation... 
/home/user/tab-cloud/_transfer/buhtzology/src/buhtzology/bandas.py:277: error: documented symbol 'buhtzology::bandas::_DONOTWORK' was not declared or defined.
```

That is the minimal python code to reproduce the error.
```Python
def foobar():
    """Foobar
    """
    WORKS = []

    _DONOTWORK = []

    return True
```

My doxygen-Version (git revision from today) and config:
```
# Difference with default Doxyfile 1.9.4 (bfda103d7ebdbe2d25eb7f5f580771129c2be4df)
PROJECT_NAME           = Buhtzology
OPTIMIZE_OUTPUT_JAVA   = YES
EXTRACT_ALL            = YES
EXTRACT_STATIC         = YES
EXTRACT_LOCAL_METHODS  = YES
SORT_MEMBER_DOCS       = NO
WARN_AS_ERROR          = YES
INPUT                  = ../src/buhtzology
FILE_PATTERNS          =
RECURSIVE              = YES
EXCLUDE                = _*.py
EXCLUDE_PATTERNS       = _*.py \
                         *\__pycache__\*
EXAMPLE_PATTERNS       =
FILTER_PATTERNS        = *.py=./py_filter
HTML_TIMESTAMP         = YES
GENERATE_TREEVIEW      = YES
MATHJAX_RELPATH        = https://cdn.jsdelivr.net/npm/mathjax@3
GENERATE_LATEX         = NO
HAVE_DOT               = YES
UML_LOOK               = YES
DOT_UML_DETAILS        = YES
```

**Comment by albert-github** [comment]
I tried to reproduce the problem but with the information given I could not reproduce the problem, but I had to exclude the line
```
*.py=./py_filter
```
as I don't have that filter file.

- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
I will provide example data later.

`py_filter` comes from [DoxyPyPy](https://github.com/Feneric/doxypypy).
There is also an still open Issue from 2014 that could be relevant: https://github.com/Feneric/doxypypy/issues/13

**Comment by albert-github** [comment]
Without the `py_filter` I cannot reproduce the problem and I don't like installing extra packages for it.

Did you try to run your example with and without the usage of the `py_filter`?
Was there a difference?
In case there is a difference just run the `py_filter` over the 3 `.py` files, catch their output and create a zip or compressed tar file from it, something like:
```
cd killme
python3 -m doxypypy.doxypypy -a -c src/setup.py > src/setup.py.new
python3 -m doxypypy.doxypypy -a -c  src/buhtzology/bandas.py > src/buhtzology/bandas.py.new
python3 -m doxypypy.doxypypy -a -c  src/buhtzology/__init__.py > src/buhtzology/__init__.py.new
tar czf example.tar.gz src/setup.py.new src/buhtzology/bandas.py.new src/buhtzology/__init__.py.new
```

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
The diff is that it works well without `py_filter`.
[example.tar.gz](https://github.com/doxygen/doxygen/files/8502190/example.tar.gz)

I still do not understand all detailes about what Doxypypy does and why it is needed and why doxygen can't do this by its own.

Because of that I am not able to decide if I need doxypypy or not. What are the pros and cons. There is an open Issue about that question: https://github.com/Feneric/doxypypy/issues/91

**Comment by albert-github** [comment]
In other words the problem is not from doxygen but in `Doxypypy` that is not part of doxygen.
The problem should be reported against `Doxypypy`. 

From the differences you provided in example.tar.gz compared to killme.zip:
```
diff org\src\buhtzology\bandas.py filtered\src\buhtzology\bandas.py.new
1,2c1,2
< ## \file
<
---
> ## @brief This is foobar.
> #
4,5d3
<     """This is foobar.
<     """
7a6,8
>     ## @var _DOESNTWORK
>     # @hideinitializer
>     # @protected
```
it looks, e.g., like something special is done with e.g.  `_DOESNTWORK`, i.e. it is commented so that doxygen can show some results about it.

The fact that doxygen does not do some of the things are:
- time limitations and not enough depth python knowledge 
- unclear python specifications, not specified in python and some (de facto) standard used
- it might be that a problem is recognized and there is already a pull request or a problem might have already been solved in the past
