### ISSUE TITLE
Not able to compile with MSYS2/mingw (file too big)

### ISSUE THREAD

**Issue by MKHen** [doxygen/doxygen#9269]
**Describe the bug**
When compiling under Windows MSYS2 gcc/x86_64-w64-mingw32 I am getting the following error:
Assembler messages:
Fatal error: CMakeFiles/doxymain.dir/docparser.cpp.obj: file too big
...
Assembler messages:
Fatal error: CMakeFiles/doxymain.dir/context.cpp.obj: file too big

**Version**
I used the files from the master.

**Additional context**
When compiling with -Os all works well.
I've used set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wa,-mbig-obj") and checked it in the outcomming makefiles.
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0

**Comment by albert-github** [comment]
Analogous to the Cygwin implementation in `CMakeLists.txt` you will probably need to add heer:
```
   set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -Og")

   if (CMAKE_BUILD_TYPE STREQUAL  "")
     set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O1")
   endif()
```

As you can see we had similar problems on Cygwin, but due to missing test environment for `MSYS2/mingw` we didn't yet add it.

Please report back when this solves the issue for you.

**Comment by MKHen** [comment]
I was able to compile it with the CMAKE_CXX_FLAGS set to -O1 or even Os.

Sadly I cannot tell you the sha of the files. Just downloaded an renamed them.

As cmake command I just used the one from the homepage:
mkdir build
cd build
cmake -G "Unix Makefiles" ..
make (sometimes make -j12)

CMAKE_SYSTEM_NAME is Windows.

I've just downloaded and tried with 9258d25. Behaviour is the same as described.

**Additional:**
Ever thought of inserting
find_program(CCACHE_FOUND ccache)
if(CCACHE_FOUND)
    set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE ccache)
endif(CCACHE_FOUND)

**Comment by albert-github** [comment]
An additional question (due to lack of knowledge of the MSYS2/MinGW possibilities):
- did you compile from a Windows command  window or a MSYS2/MinGW shell?

**Comment by albert-github** [comment]
Thank you for the very quick feedback,
I've changed it (didn't carefully enough read your answer regarding upper / lowercase name in https://github.com/doxygen/doxygen/issues/9269#issuecomment-1096085400) and pushed it to GitHub.

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub.
Since this problem is not appearing in any official release and is fixed before the next release I'll close the issue.

**Comment by MKHen** [comment]
Thank a lot.

Do you receive the coffee if I hit the Donate button on www.doxygen.nL?

**Comment by albert-github** [comment]
I'm just trying to improve doxygen, solve problems, answer questions without any obligations on either side.

**Comment by MKHen** [comment]
Then I would like to thank you very much for your commitment.
