### ISSUE TITLE
Spawn PREDEFINED macros over several lines

### ISSUE THREAD

**Issue by MKHen** [doxygen/doxygen#9275]
Hi.
Is it possible to spawn a PREDEFINED macro over several lines after preprocessing?

**Comment by albert-github** [comment]
What do you mean and what did you try?
Actually such a question belongs on https://stackoverflow.com/ 
I think this is possible, but I don't have enough information of what you want.

Furthermore:
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.
- Please also specify the **full** doxygen version used (`doxygen -v`).

**Comment by MKHen** [comment]
Went out of scope. I used a Python script to achieve a solution. Maybe delete the post.

**Comment by albert-github** [comment]
You wrote:
> Went out of scope. I used a Python script to achieve a solution.

Meaning that you created a workaround that works in your specific case, but that your root problem is still present?
From a doxygen perspective it would be good to know whether or not there is a problem in doxygen that needs to be fixed, so please:
-    Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.
-    Please also specify the full doxygen version used (`doxygen -v`).

**Comment by MKHen** [comment]
The Definiton of FATAL is out of scope. This was my try a PREDEFINED:
PREDEFINED             = "FATAL(NO, name)=\
						 /** addtogroup name\
						  *  @li 1. \
						  */"\
