### ISSUE TITLE
function pulled from base class with "using" loses its parameters

### ISSUE THREAD

**Issue by sherm1** [doxygen/doxygen#9282]
Drake has a class `SystemBase` that defines `DeclareCacheEntry()`. Users mostly work with the derived class `System` which contains
```c++
protected:
    using SystemBase::DeclareCacheEntry;
```

The Doxygen documentation for System::DeclareCacheEntry shows no parameters
![image](https://user-images.githubusercontent.com/4088016/164086499-c3562a62-d3a0-4479-a437-150fd628207c.png)

but the SystemBase::DeclareCacheEntry documentation correctly shows three parameters:
![image](https://user-images.githubusercontent.com/4088016/164086673-92b056ac-4297-4b11-bbc3-644311d51a5b.png)

This is C++ code. In case it's relevant, there are three overloads of DeclareCacheEntry() in SystemBase and only the first one is wrong in the System documentation. [Here](https://github.com/RobotLocomotion/drake/blob/master/systems/framework/system_base.h#L752) is a link to the declarations in SystemBase.

This occurred with Doxygen 1.8.15.

**Comment by albert-github** [comment]
The doxygen 1.8.15 version is already a bit older ((December 2018), the current doxygen version is 1.9.3
- what happens with the current doxygen version?

The link to the code might not be persistent (probably won't be as it is linking to a master version on github) an it is a big project, so:
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

**Comment by albert-github** [comment]
I did some tests with the minimal information that is present, resulting in the example: [example.tar.gz](https://github.com/doxygen/doxygen/files/8519738/example.tar.gz)

The result with the 1.8.15 version is:
![image](https://user-images.githubusercontent.com/5223533/164185592-15e23af8-786a-415d-9b9e-f55f2793a133.png)

![image](https://user-images.githubusercontent.com/5223533/164185666-1cdc327a-135e-47bb-b393-7f426deaba0b.png)

![image](https://user-images.githubusercontent.com/5223533/164185741-08c274db-f9d7-4c68-aa8d-6e7f19b8bda7.png)


and with the windows doxygen 1.9.3 (c0b9eafbfb53286ce31e75e2b6c976ee4d345473) version:

![image](https://user-images.githubusercontent.com/5223533/164185961-30431cdb-c36a-4362-9d08-375dfe16e515.png)

![image](https://user-images.githubusercontent.com/5223533/164186012-390722ca-224a-424b-9bce-62dee12608d1.png)

![image](https://user-images.githubusercontent.com/5223533/164186069-8648eca3-2083-4bd1-a0df-2140d5fadb89.png)


So I think the problem has been solved in the mean time.

**Comment by sherm1** [comment]
Thank you @albert-github! I'll close this as already fixed.
