### ISSUE TITLE
Clicking external link within search results with EXT_LINKS_IN_WINDOW=YES opens the link in the search results box

### ISSUE THREAD

**Issue by oblivioncth** [doxygen/doxygen#9284]
**Describe the bug**
If `EXT_LINKS_IN_WINDOW=YES`, when clicking on an external link in the search results window, the page the link points to is loaded within the confines of the search results box, instead of opening in a new browser tab/window. Needless to say the resultant display is essentially unusable.

This is with default search engine settings.

**Expected behavior**
Clicking an external link in the search results drop-down while this option is enabled opens the page in a new tab/window like it would if the link was anywhere else.

**Screenshots**
Search results:
![doxy-search-results](https://user-images.githubusercontent.com/24661585/164164312-b3c70b02-fe80-4b67-836e-efde700a3017.png)

After clicking 'QBitArray' (first link under first heading):
![doxy-external-in-search](https://user-images.githubusercontent.com/24661585/164164360-59ae3e0f-dc22-49e4-af5c-e6fbd1649451.PNG)

**To Reproduce**
[Doxygen_EXT_LINKS_IN_WINDOW_search_window_issue_MRE.zip](https://github.com/doxygen/doxygen/files/8518801/Doxygen_EXT_LINKS_IN_WINDOW_search_window_issue_MRE.zip)

Makes use of one tag file from Qt 6.2.3.

**Version**
Latest stable release from site:
1.9.3 (c0b9eafbfb53286ce31e75e2b6c976ee4d345473)
Windows x64

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #9285

**Comment by oblivioncth** [comment]
Thanks again for the quick response.

As with my other issue, I'll test the eventual merge and repot back.

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by oblivioncth** [comment]
I tried out the artifact from the merge and can confirm that the fix works as I specified under 'Expected Behavior' (wow the Release optimizations really make a difference with this tool).

Thanks for the fix.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.4.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
