### ISSUE TITLE
New release?🤔 

### ISSUE THREAD

**Issue by kloczek** [doxygen/doxygen#9287]
https://github.com/doxygen/doxygen/compare/Release_1_9_3...master shows that it is already +400 commits since laste release.
It is almost the same like https://github.com/doxygen/doxygen/compare/Release_1_9_2...Release_1_9_3
I think that it would be good to omake new release 😛

**Comment by doxygen** [comment]
I agree, I'll see if can make a new release somewhere in the coming weeks.

**Comment by kloczek** [comment]
Thank you 😄

**Comment by kloczek** [comment]
I see still some stream of new commits so looks like still something needs to be done before release.
Am I right? 🤔

**Comment by doxygen** [comment]
Yes

![image](https://user-images.githubusercontent.com/1300762/166155860-978c304b-09d2-49c7-baa6-648fae7e8aad.png)

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.4.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Comment by arwedus** [comment]
thanks for the new release! 🙂 👍🏼

**Comment by kloczek** [comment]
Just tested new version and looks like build fails when is used latest gcc 12.0.1.
```console
[ 19%] Building CXX object src/CMakeFiles/doxycfg.dir/message.cpp.o
cd /home/tkloczko/rpmbuild/BUILD/doxygen-1.9.4/x86_64-redhat-linux-gnu/src && /usr/bin/g++ -DYY_BUF_SIZE=262144 -DYY_READ_BUF_SIZE=262144 -I/home/tkloczko/rpmbuild/BUILD/doxygen-1.9.4/filesystem -I/home/tkloczko/rpmbuild/BUILD/doxygen-1.9.4/libmd5 -I/home/tkloczko/rpmbuild/BUILD/doxygen-1.9.4/liblodepng -I/home/tkloczko/rpmbuild/BUILD/doxygen-1.9.4/libmscgen -I/home/tkloczko/rpmbuild/BUILD/doxygen-1.9.4/libversion -I/home/tkloczko/rpmbuild/BUILD/doxygen-1.9.4/libxml -I/home/tkloczko/rpmbuild/BUILD/doxygen-1.9.4/vhdlparser -I/home/tkloczko/rpmbuild/BUILD/doxygen-1.9.4/src -I/home/tkloczko/rpmbuild/BUILD/doxygen-1.9.4/x86_64-redhat-linux-gnu/generated_src -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -DNDEBUG -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wextra -Wshadow -Wnon-virtual-dtor -Wcast-align -Wunused -Woverloaded-virtual -Wpedantic -Wdouble-promotion -Wformat=2 -Wno-unused-parameter -Wno-sign-conversion -Wno-format-nonliteral -Wno-implicit-fallthrough -std=gnu++17 -MD -MT src/CMakeFiles/doxycfg.dir/message.cpp.o -MF CMakeFiles/doxycfg.dir/message.cpp.o.d -o CMakeFiles/doxycfg.dir/message.cpp.o -c /home/tkloczko/rpmbuild/BUILD/doxygen-1.9.4/src/message.cpp
In file included from /home/tkloczko/rpmbuild/BUILD/doxygen-1.9.4/src/doxygen.h:24,
                 from /home/tkloczko/rpmbuild/BUILD/doxygen-1.9.4/src/message.cpp:21:
/home/tkloczko/rpmbuild/BUILD/doxygen-1.9.4/src/cache.h: In member function ‘V* Cache<K, V>::insert(const K&, V&&)’:
/home/tkloczko/rpmbuild/BUILD/doxygen-1.9.4/src/cache.h:53:14: error: ‘exchange’ is not a member of ‘std’
   53 |         std::exchange(it->second->second,value);
      |              ^~~~~~~~
make[2]: *** [src/CMakeFiles/doxycfg.dir/build.make:173: src/CMakeFiles/doxycfg.dir/message.cpp.o] Error 1
make[2]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/doxygen-1.9.4/x86_64-redhat-linux-gnu'
make[1]: *** [CMakeFiles/Makefile2:522: src/CMakeFiles/doxycfg.dir/all] Error 2
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/doxygen-1.9.4/x86_64-redhat-linux-gnu'
make: *** [Makefile:169: all] Error 2
```

**Comment by kloczek** [comment]
BTW is i tpossible in the furure change taggig convention from current `Release_<version_with_underscores>` to just `<version.with.dots>`? It would allow easier integration of the automation which automatically is trying to package new versions of the software.

**Comment by albert-github** [comment]
Regarding the tagging: would this mean:
- `Release_<version.with.underscores>`

or
- `Release.<version.with.underscores>`

**Comment by kloczek** [comment]
If you will look across all tags you may find that all those tags
```console
[tkloczko@devel-g2v doxygen]$ git tag | grep -c Release
345
[tkloczko@devel-g2v doxygen]$ git tag | grep -v Release
[tkloczko@devel-g2v doxygen]$
```
So adding that `Release_` prefix is a bit pointless 😄 and only is cusing that autogenerated from git tag tar ball inside has base directory `doxygen-Release_version.with.underscores>/`
Ypu can see that in last such tar ball https://github.com/doxygen/doxygen/archive/Release_1_9_4.tar.gz

**Comment by albert-github** [comment]
Some remarks:
- constexp.y This is known and has to with the yacc versions that can be used 
- VhdlParser_adj.cc this is generated code by means of JavaCC
- generated_src/*.cpp is generated code

Regarding the `*.l` files I've just pushed a proposed patch, pull request #9316

**Comment by kloczek** [comment]
Do you want me to test that PR?

**Comment by doxygen** [comment]
@kloczek I've just merged it. I also commited https://github.com/doxygen/doxygen/commit/8b0922feca77fc15fe168560914e443c94abb2f0 which should help with the last warning. So please test the current master.
