### ISSUE TITLE
A markdown output generator

### ISSUE THREAD

**Issue by jric** [doxygen/doxygen#9350]
**Describe the bug**
This is an enhancement request.  I would like to be able to keep my documentation in one place, in the source code.  Therefore, I would like to auto-generate my README.md.  I would like an option for doxygen to create a markdown file.

**Expected behavior**
There should be an available configuration, GENERATE_MD, that when set to YES will simply dump markdown as markdown, rather than converting it to other formats like HTML, XML, RFT, etc.

**Additional context**
I may begin working on a merge request to support this with the new configuration and output generator.  I am posting to see if there is alignment from the community on having such an option.

**Comment by jric** [comment]
I have also asked [this question on StackOverflow](https://stackoverflow.com/questions/72340136/use-doxygen-to-create-readme-md).

**Comment by albert-github** [comment]
Looks like to be a duplicate of #6760

**Comment by jric** [comment]
Absolutely right.  Somehow I didn't find that when I searched the issues.
