### ISSUE TITLE
Current git master does not honor `PROJECT_NUMBER` in LaTeX

### ISSUE THREAD

**Issue by mcondarelli** [doxygen/doxygen#9367]
**Describe the bug**
The line containing `PROJECT_NUMBER` disappeared.

**Expected behavior**
Consistent behavior.

**Screenshots**
![image](https://user-images.githubusercontent.com/870849/171990571-28d34a0d-f0de-40dd-96d9-ce27f708c9c0.png)

**To Reproduce**
Attached self contained example reproduces the problem.

**Version**
Reference version 1.9.1 is Debian Sid standard from package.
Version 1.9.5 is self compiled (also on up-to-date Debian Sid machine) from git (commit 8a9c41ee3dad073cf20090732de06e6e4fca05ae (HEAD -> master, origin/master, origin/HEAD))

[example.tar.gz](https://github.com/doxygen/doxygen/files/8837275/example.tar.gz)

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #9369

**Comment by mcondarelli** [comment]
Thanks @albert-github 
what are "normal turnaround times" to get such pull requests integrated?
I mean: does it make sense to integrate your changes into a local branch or is it better to wait for a "proper commit"?
TiA!

**Comment by albert-github** [comment]
> what are "normal turnaround times" to get such pull requests integrated?

This is hard to tell.

There is a workaround for your case:
- `doxygen -w latex header.tex footer.tex style.sty`
- modify `header.tex` to just incorporate the 3 lines from the `header.tex` from the pull request (as you have the `PROJECT_NUMBER` set no need to incorporate the lines from latexgen.cpp
- edit Doxyfile and add `LATEX_HEADER=headeer.tex`

**Comment by mcondarelli** [comment]
Many Thanks @albert-github,
I **think** it will be better, in my case, to directly fetch your pull request directly and to do so for any further fixes.
Rationale behind this (please check my reasoning, you have a much better insight than me on the subject!) is:
- Current stable (1.9.1) is not really good for our needs.
- I see there are several things that will need extensive rework in switch 1.9.1 -> 1.9.4+ (essentially in Markdown handling).
- I need to minimize work *on documentation* (it will be a team effort) versus work on Doxygen setup (personal task).
- I should try to minimize "startling behavior" for coworkers.
Does this make sense?
Do you have any advice?

TiA!

**Comment by albert-github** [comment]
I think the condition:
> I should try to minimize "startling behavior" for coworkers

is quite important here.
I think incorporating the proposed pull request  #9369 or at least the changes in `header.tex` on the `template/latex` directory would be the best thing to do as long as the proposed pull request #9369 has not been integrated.
(also when just  changing the `header.tex` you have to recompile as at that moment the `header.tex` will be pulled into your executable, you will see a line about building resources.cpp during the build)

**Comment by mcondarelli** [comment]
Agreed @albert-github.
Many thanks again.
If you happen to have tentative patches also for the other problems please notify me.
I will be more than happy to test them even before the "pull request" stage.
I cannot thank you enough ;)
Regards
Mauro Condarelli (aka: mc5686 at mclink dot it)

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.5.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
