### ISSUE TITLE
Doxygen stops processing a file when it founds a particular string in a sprintf function

### ISSUE THREAD

**Issue by estebanzimanyi** [doxygen/doxygen#9401]
I have a C function that outputs a bounding box in MF-JSON format

```
/**
 * @brief Write into the buffer the spatiotemporal bounding box represented in
 * MF-JSON format
 */
static size_t
stbox_mfjson_buf(char *output, const STBOX *bbox, bool hasz, int precision)
{
  assert (precision <= OUT_MAX_DOUBLE_PRECISION);
  char *ptr = output;
  // ptr += sprintf(ptr, "\"stBoundedBy\":{\"bbox\":[["); <----------------- Problematic line
  ptr += lwprint_double(bbox->xmin, precision, ptr);
  ptr += sprintf(ptr, ",");
  ptr += lwprint_double(bbox->ymin, precision, ptr);
  ...
  return (ptr - output);
}
```

When I uncomment the line marked as problematic above it outputs the documentation of the above function but the subsequent functions in the file are no longer shown. With the commented line above, all the functions appear in the documentation.

**Comment by albert-github** [comment]
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.
- Please also specify the **full** doxygen version used (`doxygen -v`).

**Comment by albert-github** [comment]
With the doxygen version 1.9.2 I was able to reproduce the problem, with the doxygen version 1.9.3 th eproblem was gone (al functions shown).

I think the problem has been solved i the mean time.

Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/8901842/example.tar.gz)

**Comment by estebanzimanyi** [comment]
Could you please tell me how to install that version of doxygen ? I am using a standard Linux distribution
```
esteban@LAPTOP-5B1T0K7D:~/src/MobilityDB/build$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
...

```
I have installed doxygen from binary packages with the traditional
```
sudo apt-get install doxygen
```
Should I complile from sources ?
https://www.doxygen.nl/manual/install.html

**Comment by albert-github** [comment]
I'm not sure which version of doxygen Ubuntu ships by default, but experience tells me that this probably will be a bit an older version (you can see the version of doxygen by means of `doxygen -v`).
There are the following possibilitoes for you:
- download from https://www.doxygen.nl/download.html the file [doxygen-1.9.4.linux.bin.tar.gz](https://www.doxygen.nl/files/doxygen-1.9.4.linux.bin.tar.gz).
  > Compiled using Ubuntu 20.04 and statically linked against libclang version 12. This archive includes the HTML version of the manual, and the GUI frontend dynamically linked against Qt5. 
- compile from sources

**Comment by estebanzimanyi** [comment]
On Wed, Jun 15, 2022 at 9:45 AM albert-github ***@***.***>
wrote:

> I'm not sure which version of doxygen Ubuntu ships by default, but
> experience tells me that this probably will be a bit an older version (you
> can see the version of doxygen by means of doxygen -v).
>
***@***.***:~$ doxygen -v
1.8.17

> There are the following possibilitoes for you:
>
>    - download from https://www.doxygen.nl/download.html the file
>    doxygen-1.9.4.linux.bin.tar.gz
>    <https://www.doxygen.nl/files/doxygen-1.9.4.linux.bin.tar.gz>.
>
>    Compiled using Ubuntu 20.04 and statically linked against libclang
>    version 12. This archive includes the HTML version of the manual, and the
>    GUI frontend dynamically linked against Qt5.
>
>
> Many thanks ! It worked.

Esteban
