### ISSUE TITLE
\inmodule alternative in doxygen

### ISSUE THREAD

**Issue by BLumia** [doxygen/doxygen#9405]
Hi,

I'm currently looking for migrating from `qdoc` to `doxygen`, one of the feature provided by `qdoc` is the `\inmodule` command, which can create a module group that lists all the classes inside the same group.

The closest thing I saw according to the doxygen documentation is the `\addtogroup` command, which will create a page for the given group name, so my first approach is creating an alias so the code doesn't need to be touched. But turns out it accepts two arguments to work, followed by a lot of unwanted stuff in the same documentation comment block.

So, my questions are:

1. Is there an alternative that functionally equals to `qdoc`'s `\inmodule`?
2. If not, can there be a macro or similar concept to represent the file/class/symbol that is currently processing that can be used in an alias?
   - Expecting something like `inmodule=@addtogroup ##CLASSNAME##` or `inmodule=@addtogroup ##FILENAME##`.
3. Can users add custom commands via some scripting/plugin system?
   - So I can add custom command with custom logic, for example I can implement the exactly same logic as `\inmodule`.

I'm not sure if I came to the wrong place so let me know if I need to go somewhere else to ask these questions.

**Comment by BLumia** [comment]
See the attachment for an example. I'm using CMake to generate related Doxyfile configuration and generate the documentation. The steps to get the documentation generated are:

```
$ mkdir build && cd build
$ cmake ../
$ make doxygen
```

Generated documentation will be located at `build/docs`, the generation of QHP could be removed since it's not affected the result of the generated documentation, only HTML will be fine.

After documentation get generated, you can check out Modules > QtDBus and see the result. I intended to get a list of classes that are in the same module. The source files are copied from the `qtbase` source code, my project are using the same syntax to do the documentation since it's currently still using `qdoc`. Since there are a lot of source files in my actual/real project, I wish I could avoid modifying existing documentation in the source files as much as possible.

Let me know if you need any additional information. Thanks!

[doxygen-test.zip](https://github.com/doxygen/doxygen/files/8917627/doxygen-test.zip)

**Comment by albert-github** [comment]
As a small note:
> the generation of QHP could be removed since it's not affected the result of the generated documentation, only HTML will be fine.

When you want to use the QHP documentation I would advise to use the current doxygen version (1.9.4) or the current master as in the 1.9.4 version a number of improvements have taken place compared to the 1.9.1 version also in respect to the QHP results (in general it is always better to use the current version).

**Comment by BLumia** [comment]
I guess `qdoc` need a proper set of source files to work, `qdoc` won't generate a usable html doc for the test project I provided above. For the behavior of `\inmodule`, you can see the [QDoc's documentation](https://doc.qt.io/qt-5/19-qdoc-commands-grouping.html#inmodule), and it needs to be use together with [`\generatelist`](https://doc.qt.io/qt-5/12-0-qdoc-commands-miscellaneous.html#generatelist-command) to get a list of C++ classes in the given module/group (which I also didn't find an alternative command in doxygen).

"Listing all classes under a curtain module" is not a deal breaker for me to migrate to doxygen, but it's still would be great to know if I can achieve this in a doxygen way :)

> I would advise to use the current doxygen version (1.9.4) or the current master as in the 1.9.4 version a number of improvements have taken place compared to the 1.9.1 version also in respect to the QHP results

Thanks for the tip!

**Comment by albert-github** [comment]
A one to one conversion will probably not be possible and I see also when running doxygen over the provided example that it gives quite a few warnings.
The biggest categories are
- warnings due to the fact that something is documented but the definition is missing
- commands `\value`  that are unknown to doxygen. 

Probably a number of lists etc. are automatically generated in doxygen already (just try, and also see what `GENERATE_TREEVIEW=YES` shows  / can do for your).

I think also that best is:
- to create a complete project so that doxygen can create some output without warnings
- at first set the unknown commands to a "sensible" alternative when something is directly present, otherwise make it an empty command or a command with dedicated text or `<br>`.
- to experiment a bit with the `*group` and `\{` / `\}` commands and see what happens.

**Comment by BLumia** [comment]
> when running doxygen over the provided example that it gives quite a few warnings...

Yeah, that's sort of expected since it's just two source files that include the `\inmodules` command copied from `qtbase`, and it's enough to get the modules catalog and related pages generated.

> and also see what GENERATE_TREEVIEW=YES shows / can do for your

`GENERATE_TREEVIEW` seems is not what I am looking for since I'd like to have a dedicated page to list the classes of a given module. `\generatelist` is a `qdoc`-ish solution, but maybe I need to re-consider the "try to avoid modifying existing documentation" idea since it seems it also can be good to make use of the `\addtogroup` command instead of make it as an alias of `\inmodule`.

> to create a complete project so that doxygen can create some output without warnings

I guess I'll need to test doxygen directly with my full project and see what can be improved from the result.

> at first set the unknown commands to a "sensible" alternative when something is directly present, otherwise make it an empty command or a command with dedicated text or `<br>`.

Now I think doing `inmodule=@addtogroup` is not a good idea, since in `qdoc` it need to be used together with `\generatelist`, so I guess creating alias to make it ignore the command could be a better solution.

I also did added some other alias for `qdoc` compact:

```
ALIASES                = target="\anchor"
ALIASES               += section1="\section"
ALIASES               += l{1}="\ref \1"
ALIASES               += b{1}="\b \1"
```

It's not complete but still hope it could be somewhat helpful for people who plan to migrate from `qdoc` to `doxygen`.

I'll close this one for now. Thanks for the help <3
