### ISSUE TITLE
\xrefitem and markdown interaction

### ISSUE THREAD

**Issue by evg656e** [doxygen/doxygen#9406]
**Describe the bug**
Using markdown (hyperlinks, in particular) inside \xrefitem results to raw (escaped) HTML text in output.

**Expected behavior**

Expected `@xrefitem rel "Related" "Related List" [QHash](https://doc.qt.io/qt-6.2/qhash.html)` and `@xrefitem rel "Related" "Related List" <a href="https://doc.qt.io/qt-6.2/qhash.html">QHash</a>` get the same result.

**Screenshots**

Input:
![image](https://user-images.githubusercontent.com/28028005/174068316-c68a0018-a7d7-483d-ad77-ae0bb7183c55.png)

Output:
![image](https://user-images.githubusercontent.com/28028005/174068496-b8120a49-ed52-41bc-a8df-955cc41d54e2.png)

**To Reproduce**

Create following comments and render to HTML:
```cpp
/// @xrefitem rel "Related" "Related List" [QHash](https://doc.qt.io/qt-6.2/qhash.html)
/// @xrefitem rel "Related" "Related List" <a href="https://doc.qt.io/qt-6.2/qhash.html">QHash</a>
```

**Version**
1.9.4 (5d15657a55555e6181a7830a5c723af75e7577e2)
Windows 10, 64 bit

**Stack trace**

**Additional context**

**Comment by albert-github** [comment]
I tried to reproduce the problem, but it all looks OK to me, so:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.
- Please also provide the output of the command `doxygen -d preprocessor -d commentscan -d markdown`

**Comment by evg656e** [comment]
Sorry for bother, seems there was unreproducible local problem. Should have done an isolated example first.
