### ISSUE TITLE
unable to resolve reference in markdown file

### ISSUE THREAD

**Issue by tdegeus** [doxygen/doxygen#9412]
A minimal reproducer has a markdown file `README.md`
```md
# Foo

## Contents

<!-- MarkdownTOC -->

- [Overview](#overview)

<!-- /MarkdownTOC -->

## Overview

Bar
```
and a `Doxyfile`
```
DOXYGEN_USE_MDFILE_AS_MAINPAGE = "README.md"
```

Now
```
$ doxygen
...
Generating docs for page md_README...
.../README.md:7: warning: unable to resolve reference to 'overview' for \ref command
...
```
when I run with `doxygen 1.9.3` . It works fine with `doxygen 1.9.2`

**Comment by albert-github** [comment]
With the 1.9.2 version there was no warning but the link where the it should point to (`#overview`) does not exist as there is with the line:
```
## Overview
```
no anchor set.
The situation in the version 1.9.2 (not giving a warning was a bug in doxygen.
See also #9021 for a discussion on labels in markdown files.

The situation was not correct in 1.9.2 and this has been solved in doxygen 1.9.3

**Comment by tdegeus** [comment]
Thanks for the clarification @albert-github . The thing is, it is not entirely illegal markdown : https://stackoverflow.com/a/16426829/2646505

**Comment by albert-github** [comment]
On Github this is an automatic extension to available  standard definition (see the original: https://daringfireball.net/projects/markdown/syntax and the common markdown specification: https://spec.commonmark.org/). Doxygen has also some extensions (see the doxygen manual).

I think that Github markdown will run into problems in case:
```
# Specification of the first item

some text

## formal definition

# Specification of the second item

some text

## formal definition
```
problem will be how to reference the second "formal definition" and also when a new item plus definition is inserted between the first and the second item (the now second item will get a new reference).

**Comment by tdegeus** [comment]
I agree it is not fail-safe... It's just a very rapid way without additional book-keeping. 

I don't really know what to suggest. I can only describe the origin of this question: I am a big fan of doxygen's error one warning option to keep my docs accurate, and I happen to use an extension to make a 'rough' table of contents of the markdown file. Now it seems that the two things can no longer play together.
