### ISSUE TITLE
fixed format source with wide lines

### ISSUE THREAD

**Issue by pak80** [doxygen/doxygen#9415]
I've got some fixed format Fortran source (i.e. with the blank initial columns, which is presumably being detected ok) but which nevertheless uses very wide lines (I tell the compiler to allow this, and it compiles fine).

However, the wide lines (when they go past 72 chars) seem to get truncated and confuse doxygen; not always giving an error, but causing mangled or truncated output, and sometimes cutting short processing of that file. The worst case seems to be when an array definition opens a bracket but the closing one is lost due to the truncation, with the following line being appended/used in (presumably) an attempt to continue:

This means the later subroutines do not always get documented, although the one that caused the error might sometimes appear but with a mangled definition.

Is it possible to have an option turn this truncation off? (or just remove it, since doxygen doesn't need to enforce compiler restrictions).

Edit: sorry, forgot to put "Fortran" in the title and now I can't change it.

**Comment by albert-github** [comment]
The Fortran standard specifies that the characters after columns 72 are to be considered as comment. Some compilers give the possibility use longer lines though doxygen follows the standard.
Extended lines would be considered as an extension in doxygen and this would require a new setting in the doxygen settings file.

**Comment by albert-github** [comment]
With the given example I don't get a warning at all, though I can see that a subroutine is missing.
- Did you get a warning and if so which warnings(s)?

Doxygen tries first to convert the fixed format Fortran to free formatted  Fortran before it starts to process the code, the result  you can see with `doxygen -d fortranfixed2free`. Doxygen is not a compiler s it is not perfect in finding errors.

**Comment by pak80** [comment]
I think I have a crude solution that works (or seems to); although I suppose there might be side-effects I haven't noticed. 

I edit src/fortranscanner.l, (from v1.9.3) and change line 77 from

const int fixedCommentAfter = 72;

to

const int fixedCommentAfter = 144;

where 144 is a suitable large-enough-for-me number, and recompile. 

The resulting doxygen seems to work fine - at least on my code; and even seems to fix a number of other issues with broken call/caller graphs (but which were, I suppose, a result of non-obvious line truncations anyway).

**Comment by albert-github** [comment]
I can imagine that the value of 144 is OK for you and thus for your case, but is not OK for people that use strict Fortran or those people that have longer lines. I'll have to have a look at the possibility of the settings variable in the doxygen settings file. 
Note that the length also is present in the file fortrancode.l

I'll also have to look why I don't get a warning.

**Comment by pak80** [comment]
OK, thanks for looking at this. Obviously I'm happy enough for now since I've tweaked those lengths (in fortranscanner.l:77 and fortrancode.l:66) to suit me, & recompiled, since the output now looks correct. 

Thanks again,

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.5.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
