### ISSUE TITLE
Java: multiple docstrings are concatenated.

### ISSUE THREAD

**Issue by Stewori** [doxygen/doxygen#9419]
**Describe the bug**
Processing Java code
```
public class Test
{
  /**Text1*/
  //public someAbandonedMethod() {}

  /**Text2*/
  public method() {}
}
```
results in the following xml snippet:
```
      <memberdef kind="function" id="classTest_1afb335f28bcc375f719c45753826efa41" prot="public" static="no" const="no" explicit="no" inline="yes" virt="non-virtual">
        <type></type>
        <definition>Test.method</definition>
        <argsstring>()</argsstring>
        <name>method</name>
        <qualifiedname>Test.method</qualifiedname>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
<para>Text1 Text2 </para>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="Test.java" line="7" column="10" bodyfile="Test.java" bodystart="7" bodyend="7"/>
      </memberdef>
```
Note that the two docstrings are concatenated which is at least unexpected behaviour.

**Expected behavior**
I expect that the docstring of the abandoned method is ignored and one would get the following xml output:
```
      <memberdef kind="function" id="classTest_1afb335f28bcc375f719c45753826efa41" prot="public" static="no" const="no" explicit="no" inline="yes" virt="non-virtual">
        <type></type>
        <definition>Test.method</definition>
        <argsstring>()</argsstring>
        <name>method</name>
        <qualifiedname>Test.method</qualifiedname>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
<para>Text1</para>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="Test.java" line="7" column="10" bodyfile="Test.java" bodystart="7" bodyend="7"/>
      </memberdef>
```
To be more precise, I expect that for every member only the *single* doccomment block *right before* the member is considered.

**To Reproduce**
Find a Java file and doxygen config attached. The issue is demonstrated like mentioned above.
After running doxygen on the example, the files in the subfolder ``xml`` contain the snippet shown above.
[issue_multiple_docstrings.zip](https://github.com/doxygen/doxygen/files/8980541/issue_multiple_docstrings.zip)

**Version**
Tested with doxygen release 1.9.3.1:
```
/blah/doxygen/build/bin/doxygen -v
1.9.3.1
```
Unfortunately, I am currently not able to build newer doxygen versions.

`lsb_release -a`:
```
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	LinuxMint
Description:	Linux Mint 18 Sarah
Release:	18
Codename:	sarah
```

**Additional context**
TBH I did not check for duplicates. Please excuse if this is a known issue.
Also, as mentioned above, I am currently not able to build recent doxygen versions. Please excuse if the issue is already fixed.

**Comment by albert-github** [comment]
I think this is expected as between the different comment blocks there is no actual code between the 2 doxygen comment blocks due to the fact that code is here commented out.

I think this problem is not a bug but expected and thus usage.

**Comment by Stewori** [comment]
Javadoc disagrees with your opinion: 
[Test.html.zip](https://github.com/doxygen/doxygen/files/8984852/Test.html.zip)
And I would make the point that I never saw an API documentation of a single member split into two separate doc comments by intention. I rather saw repeatedly, also in the Java standard library, the pattern presented here, where an abandoned member is commented out.
I guess it is part of the Javadoc specification that only a single comment block belongs to a specific member but I did not look it up. I can try if that helps.

P.S. I noticed a mistake in my Java example: the methods lack return types. However adding return types does not change the xml in a relevant way.
```
public class Test
{
  /**Text1*/
  //public someAbandonedMethod() {}

  /**Text2*/
  public method() {}
}
```

**Comment by albert-github** [comment]
I think it is indeed no good practice to split API documentation-
Doxygen is not JavaDoc but implements quite a few feature of it.
We also have to take into account that doxygen translates `///` type of comments into `/**`, so that comments like_

``` 
/// line 1
/// line 2
/// line 3

/// line 11
/// line 12
/// line 13
```

into something like:
```
/** line 1
  * line 2
  * line 3 */

/** line 11
  * line 12
  * line 13 */
```

One can of course argue about the fact that there is another type of comment / "normal" comment (`//`) in between and this could cancel doxygen comment that is already present-

**Comment by Stewori** [comment]
The `///` comments are not much harmful for processing non-Doxygen-aware comments as they are usually not used by javadoc authors. Also, it is trivial to get rid of them using a filter. In contrast, the pattern presented in the OP does occur due to a frequent use case.

**Comment by Stewori** [comment]
Oh, it occurs to me you are saying that avoiding the doc comment concatenation would corrupt Doxygen's support for `///`-style comments because they are supported by preprocessing them into `/**...*/` blocks.

To allow fixing the concatenation issue requires doxygen to adjust `///` conversion into:
```
/// line 1
/// line 2
/// line 3

/// line 11
/// line 12
/// line 13
```
becomes
```
/** line 1
  * line 2
  * line 3
  *
  * line 11
  * line 12
  * line 13 */
```

But you feel that is a too deep change.

**Comment by albert-github** [comment]
To be honest the change you gave regarding the `///` I didn't consider yet.
Would be a nice change, though I just gave a general example.
You say it is a common use case in Java to comment out the code but leave the JavaDoc / doxygen code present, my personal opinion is that when you "invalidate" the code (here by placing `//`) you should also invalidate documentation generating comments.

@doxygen what is your opinion about the general issue?

**Comment by Stewori** [comment]
Well, "common"... at least in the code I am dealing with it occurs too frequently to ignore it.

> my personal opinion is that when you "invalidate" the code (here by placing //) you should also invalidate documentation generating comments.

I can agree with that, but this doesn't help when inheriting a code base where people just worked it that way. There is not simple way to detect and fix these issues. Since there can be arbitrary comments in between, it can't be done by a simple regex (maybe it can, I didn't try too hard yet). So my first attempt is to check whether there is interest to fix it for Doxygen in general, also given that it is an incompatibility with javadoc.

**Comment by albert-github** [comment]
Indeed inherited code bases can give some problems.

Regarding the regular expression this is indeed a hard one as one has to take into account that the  `//` comment sign can be part of a string and here one again has to be careful with e.g. escaped sequences like `\//`, so with a regular expression the chance that it backfires is quite well present. One could probably write a small (python) program and use this as filter for doxygen, but this is also quite a bit of work and one also has to take the problems as described for regular expressions into account.
