### ISSUE TITLE
[Regression] Search field focus clearing broken and odd ".html" label

### ISSUE THREAD

**Issue by Krinkle** [doxygen/doxygen#9440]
**To Reproduce**

After focussing search field and clicking outside of it, the label is no longer "Search" but is now `.html`.

Also, the previoue behaviour where the word "Search" is removed when clicked, is no longer working. Now the text "Search" stays behind and has to be manually removed.

**Expected behavior**

It says the same.

**Screenshots**

<img width="249" alt="Screenshot 2022-07-09 at 16 36 45" src="https://user-images.githubusercontent.com/156867/178125921-bd27a476-3aee-473d-98a0-92c33a81e4a1.png">

**Version**

Doxygen 1.9.4, from Homebrew, on macOS.

**Additional context**

This is a regression, as it does not affect Doxygen 1.9.1.

The code was recently changed in https://github.com/doxygen/doxygen/commit/be61d64e75e1b9df5ad463130bbea69a8657db9a, which might have introduced the bug. I don't see an obvious mistake though. It removed a `false` argument in the `new SearchBox` call. That appears correct as there are now only 4 instead of 5 arguments, passed, and those appear to be passed in the correct places with the correct meaning. Yet, upon debugging in Firefox devtools, the `.html` extension value ends up as `this.searchLabel`.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.5.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
