### ISSUE TITLE
enum classes with [[nodiscard]] attribute emit warning when inside a namespace

### ISSUE THREAD

**Issue by keksmaster** [doxygen/doxygen#9455]
The following code snippet

```c++
namespace N1
{
namespace N2
{
/**
* @brief An enum
*/
enum class [[nodiscard]] MyEnum
{
  Val1,
  Val2,
  Val3
};
}
}
```
emits a warning like this:
"_<path>/MyEnum.h:10: warning: documented symbol `enum nodiscard N1::N2::N1::N2::MyEnum' was not declared or defined._"

Note that the namespaces do appear twice in the warning.

Interestingly, when exporting the symbol with dll_export, the warning does not appear.

**Comment by albert-github** [comment]
With the information given, a default settings file (`Doxyfile) and the current doxygen version (1.9.4 (5d15657a55555e6181a7830a5c723af75e7577e2)) I was not able to reproduce the problem.
When running with the 1.8.13 version (December 29, 2016, so quite old) I got the warning:
```
warning: documented symbol `enum nodiscard N1::N2::N1::N2::MyEnum' was not declared or defined.
```
(with the versions as off 1.8.14 I didn't get the warning anymore).

So I think the problem has been solved in the mean time.
