### ISSUE TITLE
jQuery.Deferred exception: 'null' is not an object

### ISSUE THREAD

**Issue by winniehar** [doxygen/doxygen#9458]
Hi all,
I am trying to convert the HTML files generated from Doxygen to PDF using wkhtmltopdf, but encountered below error.

Loading pages (1/6)
Warning: file:///C:/Users/whar/Downloads/Mik/html/jquery.js:2 jQuery.Deferred exception: 'null' is not an object
Warning: undefined:0 TypeError: 'null' is not an object
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done

I am using Doxygen 1.9.4 and wkhtmltopdf 0.12.6 (with patched qt)

Can someone help please? Thanks in advance.

**Comment by albert-github** [comment]
Cross posing from https://stackoverflow.com/questions/73027798/wkhtmltopdf-jquery-deferred-exception-null-is-not-an-object
See the comments there for remarks regarding the used tool and the remarks regarding:
Why do you want to use an html to pdf converter and not the possibility in doxygen to create LaTeX output and run pdflatex on this (by means of a make procedure in the resulting latex directory)?

The problem doesn't look like a doxygen problem.

**Comment by winniehar** [comment]
Hello Albert. That is because the PDF generated from LaTeX is not quite what the end user is looking for and the end user prefers the HTML look but in PDF format. Plus I am not sure why when I run pdflatex on refman.tex, the page number on index page is missing and there are some missing table borders. (sorry for mixing up the issues, please let me know if I should create separate issues for the below.

![image](https://user-images.githubusercontent.com/96389972/179807889-02367122-04af-42d7-8d2a-d45b42085e16.png)

![image](https://user-images.githubusercontent.com/96389972/179807701-22313d0b-56ef-4155-bc4a-8df3c2cccaae.png)

**Comment by albert-github** [comment]
On the latex directory you should nor run `pdflatex` but `make` the later is either a script (Windows) or a `Makefile` and sees to it that references are resolved.
Regarding the wishes of the customer there is nothing I think doxygen really can do, maybe you should looks also into the possibilities of the `CHM` and `QHP` output also the docbook and xml output might be of interest as here one can shape the output oneself.

**Comment by winniehar** [comment]
thanks Albert!
