### ISSUE TITLE
fatal: Cannot open 'doxygen/graph_legend.dox': No such file or directory 

### ISSUE THREAD

**Issue by FrankHJCuypers** [doxygen/doxygen#9476]
When upgrading doxygen from version 1.8.16 to version 1.9.4, I get the " fatal: Cannot open 'doxygen/graph_legend.dox': No such file or directory" bug again.
This is the same bug as #5878 (Bugzilla bug #755786).
It seems that the graph_legend file is renamed to doxygen/graph_legend.dox, except in the handling of the FILE_VERSION_FILTER.

Behavior is as reported for #5878, including the way of reproducing it.

**Comment by albert-github** [comment]
In the example of #5878 I don't see a file `graph_legend.dox`, so what are you exactly trying to run?

- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

**Comment by albert-github** [comment]
Thought it might be the internal "graph_legend" name so ran the mentioned project and got the warning.

I've just pushed a proposed patch, pull request #9478

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.5.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
