### ISSUE TITLE
HIDE_UNDOC_MEMBERS=YES not respected in/after named group

### ISSUE THREAD

**Issue by usiems** [doxygen/doxygen#9480]
**Describe the bug**
We have a product (MeVisLab) where we use doxygen to document C++ methods than can be used from Python scripting (basically most Qt QObject "slots"). We have a filter that copies the headers and removes the documentation from all methods that can't be used and set HIDE_UNDOC_MEMBERS=YES in our config file.

Now, with a newer doxygen version, we noticed that all undocumented members in a named group (or anything behind it) are listed for a class. This was something that still worked with doxygen 1.8.9. The wrong behavior was observed with 1.9.2 and 1.9.4

I have a minimal example attached with basically two header files (plus one dummy header):

- mlabMLModule.h has no named documentation groups, everything is as it should be
- mlabMLModule2.h uses a named documentation group around the single documented method, here a lot of undocumented members are listed in the generated html file.

**Expected behavior**
Undocumented methods/members should not be shown.

**To Reproduce**

- Unzip the files in the attached file: [doxygen-hide-undoc-bug.zip](https://github.com/doxygen/doxygen/files/9220178/doxygen-hide-undoc-bug.zip)
- Notice that source/mlabMLModule.h and source/mlabMLModule2.h only differ in the fact that mlabMLModule2.h has a named documentation group around a single documented method
- On Windows double-click the doxygen.bat.
- Inspect the generated HTML in doxygen/html/index.html (open class list). Notice the difference between MLABMLModule.h and MLABMLModule2.h. Especially notice that the members before the named group are not listed, only those after.

**Version**
doxygen 1.9.4 on Windows 10, 64 bit.  

**Additional context**
Doxygen applied to C/C++ code.

**Comment by albert-github** [comment]
The problem is most likely in the `//@{` and `//@}`, in the past this was OK but this is just regular comment and not seen by doxygen (anymore) as the code has been made more consistent (in respect to analyzing only doxygen type of comment).

I think the source should look like
```
  //! \name Scripting
  ///@{

  //! Returns scripting access to the underlying ML module
  //! This is only supported for ML modules that have a registered CPPObjectWrapper.
  virtual QObject* object();

  ///@}
```

I think the problem is usage.

**Comment by usiems** [comment]
Indeed, this fixes the problem. Thank you. We will adapt our code.
