### ISSUE TITLE
ALPHABETICAL_INDEX should also display function in the index  (Origin: bugzilla #132103)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#949]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.3.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2004-01-21 14:31:44 +0000, luc.andre@9online.fr wrote:

    On class members are visible in the "functions index"
    It would be great to have straight functions (not member of a class) in 
    the index page.
    
    Thanks,
    
    Luc

**Comment by albert-github** [comment]
In the 1.3.5 version there was an item "Alphabetical list" and this showed the classes. In the 1.9.6 version this item does nott exist anymore.

I think this problem is obsolete / solved in the mean time.
