### ISSUE TITLE
Doxygen 1.9.4: compilation issue on OSx64

### ISSUE THREAD

**Issue by VincentRouvreau** [doxygen/doxygen#9557]
**Describe the bug**
Compilation issue for the conda package of doxygen 1.9.4 on OSx

**Expected behavior**
Should compile

**Screenshots**
```txt
[ 61%] Building CXX object src/CMakeFiles/doxymain.dir/dir.cpp.o
In file included from /Users/runner/miniforge3/conda-bld/doxygen_1661930643770/work/src/dir.cpp:18:
/Users/runner/miniforge3/conda-bld/doxygen_1661930643770/work/filesystem/filesystem.hpp:4508:24: error: use of undeclared identifier 'UTIME_OMIT'
    times[0].tv_nsec = UTIME_OMIT;
                       ^
/Users/runner/miniforge3/conda-bld/doxygen_1661930643770/work/filesystem/filesystem.hpp:4511:11: error: no member named 'utimensat' in the global namespace
    if (::utimensat(AT_FDCWD, p.c_str(), times, AT_SYMLINK_NOFOLLOW) != 0) {
        ~~^
/Users/runner/miniforge3/conda-bld/doxygen_1661930643770/work/filesystem/filesystem.hpp:4511:21: error: use of undeclared identifier 'AT_FDCWD'
    if (::utimensat(AT_FDCWD, p.c_str(), times, AT_SYMLINK_NOFOLLOW) != 0) {
                    ^
/Users/runner/miniforge3/conda-bld/doxygen_1661930643770/work/filesystem/filesystem.hpp:4511:49: error: use of undeclared identifier 'AT_SYMLINK_NOFOLLOW'
    if (::utimensat(AT_FDCWD, p.c_str(), times, AT_SYMLINK_NOFOLLOW) != 0) {
                                                ^
4 errors generated.
make[2]: *** [src/CMakeFiles/doxymain.dir/build.make:865: src/CMakeFiles/doxymain.dir/dir.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:512: src/CMakeFiles/doxymain.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```
(I can provide the [full logs](https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_build/results?buildId=560866&view=logs&jobId=58ac6aab-c4bc-5de2-2894-98e408cc8ec9) if necessary)

**To Reproduce**
[build script is available here](https://github.com/VincentRouvreau/doxygen-feedstock/blob/doxygen_version_1_9_4/recipe/build.sh)

**Version**
 https://www.doxygen.nl/files/doxygen-1.9.4.src.tar.gz

**Stack trace**
N/A

**Additional context**
N/A

**Comment by albert-github** [comment]
- Please don't add log files as links but add them to the issue (the links might not be persistent).
- From the link you added to conda-forge do I understand it correct that it is an upstream issue at conda-forge? or is it that the MacOs version 13 still exhibits the problem? What happens when you change the line:
  ```
  #if __MAC_OS_X_VERSION_MIN_REQUIRED < 101300
  ```
  into
  ```
  #if __MAC_OS_X_VERSION_MIN_REQUIRED < 101300
  ```

**Comment by VincentRouvreau** [comment]
> * Please don't add log files as links but add them to the issue (the links might not be persistent).
> 
>     * From the link you added to conda-forge do I understand it correct that it is an upstream issue at conda-forge? or is it that the MacOs version 13 still exhibits the problem? What happens when you change the line:
>       ```
>       #if __MAC_OS_X_VERSION_MIN_REQUIRED < 101300
>       ```
>       
>       
>           
>             
>           
>       
>             
>           
>       
>           
>         
>       into
>       ```
>       #if __MAC_OS_X_VERSION_MIN_REQUIRED < 101400
>       ```

I tried your fix on a custom doxygen version (1.9.4 + the patch you are proposing - cf. https://github.com/conda-forge/doxygen-feedstock/pull/36 ), but it didn't work. Same error.
FYI, it has been fixed with these [compilation flags](https://github.com/conda-forge/doxygen-feedstock/pull/34/commits/de766aa7855ddb7916d09d9c4b3ff3b0eff8db1f). Hope it can help to understand, maybe not an issue on your side.

**Comment by albert-github** [comment]
Pity it didn't work, it was a wild guess from my side loosely based on your issue https://github.com/conda-forge/doxygen-feedstock/pull/34 (no experience with Mac-Os on my side).
The change in compilation flags I don't understand, but maybe good to report them with the upstream issue https://github.com/gulrak/filesystem/issues/155 as well

**Comment by albert-github** [comment]
@isuruf 
Thanks for the comment.
Do I understand you correctly that this is not a gulrak/filesystem issue and thus not a doxygen issue either, but an error outside  gulrak/filesystem and thus doxygen or is there some CMAKE variable that we have to set / can set additionally so the preprocessor works correctly?
