### ISSUE TITLE
Regression: LaTeX run fails

### ISSUE THREAD

**Issue by markus2330** [doxygen/doxygen#9567]
**Describe the bug**

With Doxygen in Debian sid the  LaTeX run fails, see https://github.com/ElektraInitiative/libelektra/issues/4455

**Expected behavior**

As it is in Doxygen 1.9.1: that the build succeeds.

**To Reproduce**

We provide Docker files, see https://github.com/ElektraInitiative/libelektra/pull/4456 how we fixed the problem, i.e., the Dockerfile before this merge request can be used to reproduce the problem.

Probably also following works (untested):
```
git clone https://github.com/ElektraInitiative/libelektra.git
cd libelektra
mkdir build  && cd build
cmake -DBUILD_PDF=ON -DBUILD_FULL=OFF -DBUILD_SHARED=OFF -DBUILD_STATIC=OFF -DBUILD_TESTING=OFF ..
cmake --build . -- -j5
```
(Commands copied from https://www.libelektra.org/getstarted/guide)

**Version**

Debian sid had Doxygen 1.9.4-2 at time of writing.

**Comment by albert-github** [comment]
The question as is is a bit unclear. As far as I understand you have some problems building the LaTeX / pdf output with doxygen 1.9.4 and it did work with doxygen 1.9.1.
The libelektra is a moving target so:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

**Comment by atmaxinger** [comment]
Attached you'll find a self contained example. You can run the `run.sh` file to reproduce the issue.

It works fine on Debian Bullseye, but fails on Debian Sid.

```
! Missing $ inserted.
<inserted text> 
                $
l.790 \end{DoxyRetVals}
```

However, if we generate the latex sources on Debian Bullseye and then use `pdflatex` to compile them on Debian Sid, the issue still persists, so it might actually also be a problem with the `pdflatex` version shipped in Sid.

[elektra-sample.zip](https://github.com/doxygen/doxygen/files/9484356/elektra-sample.zip)

**Comment by albert-github** [comment]
I tried the sample under Cygwin (no access to a Debian system) and here everything runs smoothly, so I think indeed that there might be a problem with the Debian Sid distribution of pdflatex.

It would be interesting to know what is in the file from where the error comes, i.e. `group__keyname.tex`

Some further remarks:
- `cp elektraSpecialCharacters.sty out/latex` is in my opinion not necessary, have a look at `LATEX_EXTRA_FILES`
- it is a bit strange to hardwire the settings of `LATEX_CMD_NAME` and `MAKEINDEX_CMD_NAME`, especially the `LATEX_CMD_NAME` command is a bit strange as also `USE_PDFLATEX` is set.

**Comment by atmaxinger** [comment]
The `group__keyname.text` file is generated in the folder `out/latex`.

As for your remarks, those things are just in here for the minimal runnable example, we do those things you mentioned correctly in the actual build process.

**Comment by albert-github** [comment]
The problem I saw in the original example from the repository:
```
LATEX_CMD_NAME         = @LATEX_COMPILER@
MAKEINDEX_CMD_NAME     = @MAKEINDEX_COMPILER@
LATEX_EXTRA_FILES      =
```
which indicates to me that this is not the case (note my remarks should have been geared a bit more to the repository as well, for the small sample it is OK as it is).

The file `group__keyname.tex` is indeed in the `out/latex` and I can see what it is in it on my system. I thought, a bit to quick, that on Debian Sid there might  be something different in there but after thinking this is very unlikely as it is generated code.

**Comment by albert-github** [comment]
Seen the description / remarks in https://www.debian.org/releases/sid/index.en.html:

> The unstable distribution ("sid")
>
> The code name for Debian's development distribution is "sid", aliased to "unstable". Most of the development work that is done in Debian, is uploaded to this distribution. This distribution will never get released; instead, packages from it will propagate into testing and then into a real release.


and the fact that on Debian Bullseye it runs correctly I think that we can conclude that this is not a doxygen problem (signaled by doxygen as `usage`).

**Comment by markus2330** [comment]
Ok, we will further investigate if it is the fault of LaTeX..

**Comment by markus2330** [comment]
Thanks for the tips with LATEX_EXTRA_FILES and LATEX_CMD_NAME, we will look into it!
