### ISSUE TITLE
Can't figure out how to get Doxygen to ignore Unreal Engine macro with multiple parenthesis in it?

### ISSUE THREAD

**Issue by dbarrett49** [doxygen/doxygen#9600]
I am generating some documentation for my Unreal Engine plugin using doxygen. I noticed that certain classes were not showing up at all in my generated documentation. Luckily I was able to track down the issue as all of the classes that didn't show up had a very specific macro present.

```
/**
* @brief This is my cool class that I want to show documentation for
*/
UCLASS(Blueprintable, ClassGroup = (Custom), meta = (BlueprintSpawnableComponent))
class UMyComponent : public USceneComponent
```

I tried adding this to the Predefined section of the Preprocessor like below but, still I had no luck. I'm assuming Doxygen is probably freaking out with the multiple parenthesis present? I have this UCLASS macro present in all of my classes so I'm not sure what exactly would cause it to fail on this particular one.
![image](https://user-images.githubusercontent.com/71447814/189963665-3cb5e447-fb1b-4b5d-ad1d-0f437ea7c78c.png)

Doxygen outputs the following warning associated with each of the files:
`warning: Found ';' while parsing initializer list! (doxygen could be confused by a macro call without semicolon)`

**Comment by albert-github** [comment]
Images are a bad idea to specify settings, but one thing one sees is already is:
- `MACRO_EXPANSION` is not set
- the `PREDEFIEND` macro definition has a strange form should be more like `UCLASS(x,y,x)` like normal defines.

it is hard to tell anything more.
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.
- Please also specify the **full** doxygen version used (`doxygen -v`).


small note in respect to the settings as you use the doxywizard. There will also be a Doxyfile that you saved to your disk (this is the one that is needed ). In Run tab you can also see the used settings (and the differences from the default settings when using the condensed form).

**Comment by dbarrett49** [comment]
- Yeah, I've tried MACRO_EXPANSION both true and false. Still doesn't work.
- I don't really have control over what the macro definition is. It is defined by Unreal Engine itself and is required above the class declaration. 
- If I add something like `UCLASS(x,y,z)` as the predefined it makes even less files show up. I thought it was based on exact match which is why I set the predefine to match exactly.

Doxygen version 1.9.5 (2f6875a5ca481a69a6f32650c77a667f87d25e88)

[Example.zip](https://github.com/doxygen/doxygen/files/9559982/Example.zip)

**Comment by dbarrett49** [comment]
Yes, `UCLASS(x,y,z)=` does get it to show up but, when I use that now I lose a lot of my other files that have like an empty `UCLASS()` they don't get documented now. I also tried adding `UCLASS()=` to the Predefined list

**Comment by albert-github** [comment]
Example please of where it now goes wrong.
Probably the solution lies in defining a filter for this.

**Comment by dbarrett49** [comment]
Yes! I applied a filter and that solved the issue. I apologize I am still a noob when it comes to doxygen. Luckily someone already has an unreal engine filter that I found elsewhere on github.

https://github.com/normalvector/ue4_doxygen_source_filter

**Comment by vtellier** [comment]
> Yes, `UCLASS(x,y,z)=` does get it to show up but, when I use that now I lose a lot of my other files that have like an empty `UCLASS()` they don't get documented now. I also tried adding `UCLASS()=` to the Predefined list

`UCLASS` as well as other UE macro are variadic macros as they are declared using `__VA_ARGS__`.

In my case, the macro giving me troubles was `PURE_VIRTUAL()` which is declared with

```.cpp
#define PURE_VIRTUAL(func, __VA_ARGS__) =0;
```

As in my code I have different usages of this macro, sometimes with one argument, sometimes with two, I tried to add these two signatures to the configuration:

```
PREDEFINED             = PURE_VIRTUAL(x)= \
                         PURE_VIRTUAL(x,y)=
```

This did **not** work.
The solution that worked for me was the following:

```
PREDEFINED             = PURE_VIRTUAL(...)=
```
