### ISSUE TITLE
Doxygen fails with long output directory name

### ISSUE THREAD

**Issue by georg-emg** [doxygen/doxygen#9611]
For complicated class names, Doxygen generated html file names that are something like 134 characters long , which leaves aroung 126 characters for the directory name before the Windows file name length of 260 characters is reached. This can be a problem for IDEs and build systems that use a deep directory structure for build artifacts. Using CMake in conjuction with Visual Studi might, for example, generate an output directoy name like *C:\Users\ChristinaAguilera\Source\Repos\long-repo-name\long-dir-name\out\build\Windows\x64\Debug\long-target-name\Doxygen\html*.

It would be nice if Doxygen could make use of the long file name feature that was introduced Windows 10. This requires prefixing the path names with `\\?\` before passing them to Win32 APIs like *CreateFileW*.

Here is a sample project that will fail on Windows 11 when using Doxygen 1.9.4:

[long-file-names.zip](https://github.com/doxygen/doxygen/files/9643904/long-file-names.zip)

**Comment by albert-github** [comment]
For this purpose doxygen has the setting `SHORT_NAMES` which will shorten the names of the files, of course you can always run into problems again when the initial file path is too long.

The solution you gave is, probably, working for Windows when calling functions like `CreateFileW` directly, but in most cases doxygen calls functions like `fopen` but the problem on Linux would remain.

I think the problem is usage.

**Comment by georg-emg** [comment]
That will create obscure, unreproducible file names that cannot be linked to, because they change every time Doxygen is run.

**Comment by albert-github** [comment]
This is, might be, the case when something in the structure changes or when the run is with multi threading, though it is not really the intention of doxygen of linking to some internal part of the documentation. 

@doxygen what do you think about `SHORT_NAMES`:
- `YES` as it is now
- `NO` as it is now
- `MD5` use the md5 sum of the string

**Comment by doxygen** [comment]
@albert-github I think it would be better to fix the Win32 API calls such that long names are allowed, rather than adding yet another option.

**Comment by albert-github** [comment]
Wouldn't the same problem exist on Linux? 

Checked the `fopen` calls and this looks feasible as they all run through `Portable`.
The `open` calls are in `formula.cpp` and `qhp.cpp` and here the change of running into problems is less as the files look like to be directly on the `HTML_OUTPUT` directory.
How about `std::ofstream` and maybe others?

**Comment by georg-emg** [comment]
Under Linux, paths are usually limited to 4096 characters, which is enough for any use case. Under Windows, paths used to be limited to 256 characters, but since Windows 10, this limit has been raised to a whopping 32767 characters. Unfortunately, these file names are not automatically supported, you need to prefix the path with `\\?\`.

*fopen* and *std::fstream* can both open long file paths if prefixed with \\?\. However, the following restrictions apply:

Paths prefixed with \\?\ do not do any path parsing, which means:

1. no relative file paths
2. no special handling of "." and ".."

Essentially, the path needs to be made absulote by hand, then converted using GetFullPathNameW (*not* GetFullPathNameA), and then prefixed with `\\?\`.
