### ISSUE TITLE
Configuration for PlantUML in Doxygen

### ISSUE THREAD

**Issue by iaggarw** [doxygen/doxygen#9634]
Is there documentation for setting up PlantUML in Doxygen? The PlantUML <s>download</s> documentation takes you to the doxygen documentation, but the Doxygen documentation does not show anything discrete. When opening a Doxyfile, you need to set a PLANTUML_JAR_PATH and a cfg file if you have one correct? 

Is there a specific way to setup the PlantUML jar to run in Doxygen? 

```
# When using plantuml, the PLANTUML_JAR_PATH tag should be used to specify the
# path where java can find the plantuml.jar file. If left blank, it is assumed
# PlantUML is not used or called during a preprocessing step. Doxygen will
# generate a warning when it encounters a \startuml command in this case and
# will not generate output for the diagram.

PLANTUML_JAR_PATH      = ./embedded-applications/Doxygen

# When using plantuml, the PLANTUML_CFG_FILE tag can be used to specify a
# configuration file for plantuml.

PLANTUML_CFG_FILE      =

# When using plantuml, the specified paths are searched for files specified by
# the !include statement in a plantuml block.

PLANTUML_INCLUDE_PATH  =
```

![image](https://user-images.githubusercontent.com/42700112/195157155-353e4fed-4fd3-4a3d-a182-6fff4d0f8661.png)

**Comment by albert-github** [comment]
- Which version of doxygen are you using

You wrote:
> The PlantUML download takes you to the doxygen documentation

- which  download is this?

Plantuml is a possibility in doxygen to render certain type of images based on a readable description.
There are a number of important things to consider:
- command `\startuml` .. `\enduml` for the definition of the readable text of the image to be rendered
- settings:
  - `PLANTUML_JAR_PATH` the reference to the jr file to be used (note that you also need Java to be available through your path)
  - `PLANTUML_CFG_FILE` an optional file with settings for plantuml, see the palntuml for possible settings



As doxygen doesn't render itself the plantuml text to an image the user is referred to the official plantuml site for the documentation of the features of plantum (see https://plantuml.com/)

**Comment by iaggarw** [comment]
Sorry when I said "download" I meant documentation. The link is here: https://plantuml.com/doxygen



I am currently using Doxygen version 1.9.1.

In regards to using '\startuml' and '\enduml', I was originally using them inside a plantuml code block. Removing the code block removes the uml coding but an image does not appear. 

Also, after going through FAQ and PlantUML guides, I could not find a place that explains how to generate a config file. Originally I did not have this file, but if this is the reason why plantuml is not running, then I will need one. Do you have any knowledge on this?

**Comment by iaggarw** [comment]
Hi, I am leaving a zipped file here which has the Doxyfile, plantuml jar, and an example UML that was in a Markdown file. I was not able to run `doxygen -q -d extcmd Doxyfile` because `-q` is apparently not defined.
[example.zip](https://github.com/doxygen/doxygen/files/9801757/example.zip)

**Comment by albert-github** [comment]
- It is correct that the `-q` is not supported, it was introduced in the 1.9.2 version of doxygen. The intention of the `-q` is the same as setting `QUIET=YES` in the Doxyfile. Note that the current doxygen version is 1.9.5
- you just gave an `uml.txt` with some, correct, Plantuml code that can be used in doxygen, when you use this code in a normal doxygen comment block all should work. (Note: contrary to e.g. `\dotfile` there is no `\plantumlfile`)

**Comment by albert-github** [comment]
You will have to have somewhere in your code something like, say for the function `fie` (analogous for `class` `namespace` `file` ...):
```
/**
  \brief the brief description of the function
  \details the detailed description of the function

@startuml
OutsideUnits -> LoggingManager : Clinical Event A
LoggingManager -> NVDataService : Clinical and Engineering Data Gathered and Buffered and Sent to NV Data Queue
OutsideUnits -> LoggingManager : Engineering Event B
LoggingManager -> NVDataService : Clinical and Engineering Data Gathered and Buffered and Sent to NV Data Queue
NVDataService -> LoggingManager : Callback for Clinical Event A
OutsideUnits -> LoggingManager : Engineering Event C
LoggingManager -> NVDataService : Clinical and Engineering Data Gathered and Buffered and Sent to NV Data Queue
NVDataService -> LoggingManager : Callback for Clinical Event B
NVDataService -> LoggingManager : Callback for Clinical Event C
@enduml

*/
void fie();
```
**Best** is (like requested before):
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

so a problem where you use doxygen in your code and also want to show the uml figures, so we can see what you are missing...

**Comment by iaggarw** [comment]
Its being used in a markdown instead of a source file, how does that make this different?

**Comment by albert-github** [comment]
That doesn't make a difference.

Best is (like requested before):

    Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.


The version with ` ```{plantuml} ... ```  ` works in the version 1.9.5 but not in the version 1.9.1

**Comment by iaggarw** [comment]
Alright, here is a zipped folder, built to replicate what my filing system looks like. I have updated to Doxygen 1.9.5, however nothing changed.
[example2.zip](https://github.com/doxygen/doxygen/files/9803257/example2.zip)

**Comment by albert-github** [comment]
I tried your example2 with doxygen 1.9.5 and had just 1 small problem,  I had to set:
```
PLANTUML_JAR_PATH      = .
```
instead of
```
PLANTUML_JAR_PATH      = ./embedded-applications/Doxygen
```
(I also adjusted the `DOT_PATH` to reflect my local installation)

Lets try some steps on your example2:
- cd example2\Doxygen
- rmdir /s doxygen_output
- doxygen -v
- doxygen -q -d extcmd

Please report back what you see in the command window

**Comment by iaggarw** [comment]
So here is the output from the console:
```
$: doxygen -v
1.9.5 (2f6875a5ca481a69a6f32650c77a667f87d25e88)
$: doxygen -q -d extcmd
Executing external command `java -Djava.awt.headless=true -jar ".\plantuml.jar" -o "C:/Users/AGGARIX2/OneDrive - Abbott/Desktop/example2/Doxygen/doxygen_output/html" -charset UTF-8 -tpng "C:/Users/AGGARIX2/OneDrive - Abbott/Desktop/example2/Doxygen/doxygen_output/html/inline_umlgraph_pnghtml.pu" `
Executing external command `"C:\Program Files\Graphviz\bin\dot.exe" "C:/Users/AGGARIX2/OneDrive - Abbott/Desktop/example2/Doxygen/doxygen_output/html/graph_legend.dot" -Tpng -o "C:/Users/AGGARIX2/OneDrive - Abbott/Desktop/example2/Doxygen/doxygen_output/html/graph_legend.png"`
```

**Comment by albert-github** [comment]
So you now see the image as expected?

**Comment by iaggarw** [comment]
I do. I updated the path in my own repo, and it works. Thank you!
