### ISSUE TITLE
Is there a way to customize the file list on the left?

### ISSUE THREAD

**Issue by niuzijia** [doxygen/doxygen#9641]
As shown in the figure, the file list on the left is automatically generated, and the list structure is confusing. Is there any other way to customize the list organization structure?

![image](https://user-images.githubusercontent.com/68538774/196072696-f730197b-6f1d-4685-b2f3-026e0ca342cd.png)

Just like in reStructuredText, define the following code to generate the corresponding organizational structure
```
.. toctree::
    :maxdepth: 2
    :hidden:
    :caption: Getting Started

    course
    installation
    quickstart
    connect_to_workbook
    syntax_overview
    datastructures
    addin
    vba
    udfs
    matplotlib
    jupyternotebooks
    command_line
    deployment
    onedrive_sharepoint
    troubleshooting

```

![image](https://user-images.githubusercontent.com/68538774/196073076-c7d7246b-5cc8-4232-851b-b62b26eff5fc.png)

**Version**
1.9.3 windows

**Comment by albert-github** [comment]
Did you have a look at the paragraph "Changing the layout of pages" (https://www.doxygen.nl/manual/customize.html#layout) ?

**Comment by niuzijia** [comment]
> paragraph "Changing the layout of page

Sorry, I see it now, I will read it carefully, thanks for your answer
