### ISSUE TITLE
doxygen.org and doxygen.nl are down

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#9652]
Last night, doxygen.org became victim of a targeted DDoS attack. As a result, my web hosting provider has taken down my websites and removed me as a customer ☹️ 
I'm looking for a solution. Sorry for the inconvenience.

**Comment by KungFuDonkey** [comment]
For anyone using pipelines that rely on doxygen, or you need to download doxygen you can still download it from [sourceforge](https://sourceforge.net/p/doxygen/activity/?page=0&limit=100#6308f7b22727e7f6799ce2be)

**Comment by doxygen** [comment]
The site should be reachable again. I now use Cloudflare's services to add an extra layer of protection.
