### ISSUE TITLE
Problem with "copybrief" etc using both C and JAVA code together

### ISSUE THREAD

**Issue by aotto1968** [doxygen/doxygen#9659]
Hi, the following problem occurs if **JAVA** and **C** code used together and the name of an object "`MqStatusIsEF`" is identical.
The goal is to transfer the doc from the **C** code into the **JAVA** code but **JAVA** complain with

> `MqStatusIsEF.java:19: warning: Found recursive @copybrief or @copydoc relation for argument 'MqStatusIsEF'.`

just to be clear, both the **JAVA** and the **C** code is processed:

```
Reading .../MqStatusIsEF.java...
Parsing file .../MqStatusIsEF.java...
Preprocessing ...msgque_mq.h...
Parsing file .../msgque_mq.h...
```
The HTML search button also find both `MqStatusIfEF`

```
MqStatusIsEF
  javamsgque.mqmsgque.MqStatusIsEF
  MqStatusIsEF(): msgque_mq.h
```

1. the JAVA code from `MqStatusIsEF.java`
```
  package javamsgque.mqmsgque;
  import javamsgque.mqmsgque.MqMsgque;

  /// \ingroup MqMsgque_Enum_JAVA_API
  /// \brief \copybrief MqStatusIsEF
  /// copyAPI{StatusIsEF} 
  /// refdoc{StatusIsEF}
  /// \anchor \JNINS{MqStatusIsEF}
  public class MqStatusIsEF {
    static private enum MqStatusIsE {
      INITIAL(0),
      DUP(1<<0),
      THREAD(1<<1),
      FORK(1<<2),
      SPAWN(1<<3);
      public final int value;
      MqStatusIsE(int value) {this.value = value;}
    }
    private final int flag;
    private MqStatusIsEF(int flg) {this.flag = flg;}
    public int get() { return flag; }
    static public MqStatusIsEF set(int val) {
      return MqMsgque.StatusIsEF_FromInt(val);
    }
  }
```

2. the C code from `msgque_mq.h`
```
/// \brief Information about how the \e context was created
///
/// \snippet msgque_mq.h MqStatusIsEF
///
/// \sa \RDocNsA{ConfigGetStatusIs}, \RDocNsA{StatusIsEF_ToString}
// [MqStatusIsEF]
__parser__(enum-is-flag)
enum MqStatusIsEF {
  MQ_STATUS_IS_INITIAL = 0,	    ///< context is the \e first context
  MQ_STATUS_IS_DUP     = 1<<0,	    ///< context is created as a duplicate of an other context
  MQ_STATUS_IS_THREAD  = 1<<1,	    ///< context is created as a thread
  MQ_STATUS_IS_FORK    = 1<<2,	    ///< context is created as a fork
  MQ_STATUS_IS_SPAWN   = 1<<3,	    ///< context is created as a spawn
};
// [MqStatusIsEF]
```

I miss a prefix for the code reference `MqStatusIsEF` to force **JAVA** or **C** lookup.

example:  `\copybrief C.MqStatusIsEF`

**Comment by albert-github** [comment]
Some code is available, but the settings used and the used version are missing:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.
- Please also specify the **full** doxygen version used (`doxygen -v`).

**Comment by albert-github** [comment]
With the just the scarce and missing information it is hard /not possible to reproduce the problem.

In my attempt I can see that with the current doxygen version (1.10.0) and with the version 1.9.5 (the newest version at the moment of writing the issue) there were no warnings, with the 1.9.4 version I got some warnings like:
```
warning: Found recursive @copybrief or @copydoc relation for argument 'MqStatusIsEF'
```

So problem looks to be solved in the mean time
