### ISSUE TITLE
doxygen does not interpret Python docstrings when typed next to SLURM directives

### ISSUE THREAD

**Issue by Jmontoliol** [doxygen/doxygen#9672]
Good morning,

I would like to report what seems to be a bug related to doxygen.

The thing is that I want to document a Python script using Python docstrings, enclosed between """! .... """ These Python docstrings are typed next to the shebang line and a set of lines that include SLURM directives (necessary to submit the script through "sbatch"). 

The problem is that "doxygen" does not interpret the documentation, so, when it generates the html documentation, the information contained in the docstrings does not appear.

This is how the code looks:

![image](https://user-images.githubusercontent.com/117977086/201299580-dfb57e5f-335c-4ab3-8d77-37e864f8ab25.png)

And the doxygen html documentation:

![image](https://user-images.githubusercontent.com/117977086/201299845-52a1b81c-2a1a-4312-9491-bacb7231c3a6.png)

You can see that the filename "03_y_x_subdomain_coord.py" appears in black, so I can't click on it, and no content is included.

However, if I type the Python docstrings before the SLURM directives, doxygen interprets them well (but in this case SLURM does not interpret the directives).

This is the situation:

![image](https://user-images.githubusercontent.com/117977086/201300480-5f0db0c0-bc5a-4c1e-b71c-bda84884bf30.png)

And the doxygen html documentation:

![image](https://user-images.githubusercontent.com/117977086/201300589-db808b15-b5c6-4878-bab0-2e471b05f288.png)

So, for some unknown reason, "doxygen" is not able to interpret Python docstrings (enclosed between """! ... """) when they are typed next to SLURM directives.

Finally, just tell you that when you use Python docstrings enclosed in the native doxygen manner (that is, enclosed between ## .... ##) then, "doxygen" interprets correctly the docstrings, even if they are typed next to the SLURM directives.

This is how the code looks when using native way of enclosing docstrings:

![image](https://user-images.githubusercontent.com/117977086/201302241-875b5bea-85b0-4d93-b722-caf744ea6dd0.png)

For all these reasons, I think that maybe there is a bug in doxygen about the interpretation of Python docstrings (enclosed in Pythonic way, """! .... """) when they are typed after SLURM directives.

doxygen used version is: 1.9.5

Hope to have explained well the problem.

Regards,

Joan

**Comment by albert-github** [comment]
It is always a bad idea to provide code, just, in the form of images as it is only with a lot of effort possible (and risk of typos)  to create something to work with, so
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #9673

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.6.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
