### ISSUE TITLE
Create dot files WITHOUT generating images from them

### ISSUE THREAD

**Issue by Omri93h** [doxygen/doxygen#9680]
So i'm working on a project where I need doxygen to generate dot files only -> then I'm opening them in python with pydotplus, 
changing views, colors, marking specific nodes -> and then saving them.

I can't find a configuration for NOT generating images - as the default value for "DOT_IMAGE_FORMAT" is png.

Is there any way to skip image generating BUT STILL CREATE THE DOT FILES ?

**Comment by albert-github** [comment]
There is no direct way to create `.dot` files but not to execute `dot`.
Did you have a look at the setting `DOT_CLEANUP=NO`  this will run `dot` but also leave the `.dot` files.

Would this be an alternative for you?

**Comment by albert-github** [comment]
It has been indicated that there is no way get the dot files and not to run dot. The process can be sped up a bit by creating an executable (script) that does nothing but has the name `dot` and for Windows `dot.exe`. Note that this might also influence the generation of plantuml results!
As indicated the dot files van be retained by means of `DOT_CLEANUP=NO`.

When you don't want have a reference in the resulting output but still want to have the dot files you have to run doxygen twice.

I don't think this is a doxygen problem.
