### ISSUE TITLE
BUGS with new release 1.9.5 ø OpenSuse

### ISSUE THREAD

**Issue by aotto1968** [doxygen/doxygen#9686]
> doxygen -v
1.9.5

> **general problem if an `alias` or an `command` or a `layout` is last token in line**
```
/// \snippet MkBufferS_mk.c MkBufferGetType1
```
```
kernel_mk.h:6767: warning: block marked with [MkBufferGetType1 \ifile "/dev/shm/dev1usr/gen/libmkkernel.doc" \iline 466] for \snippet should appear twice in file MkBufferS_mk.c, found it 0 times
```

```
  /// \brief \b demonize the current process and save the resulting PID into the \e pidfile …
  ///
  /// \param[in] obj   ...
  /// \param[in] pidfile        file to save the process identifier, can be used to kill the process later
  /// \return_MkErrorE
  ///
  /// \b Example:
  /// \dontinclude sys_mq.c
  /// \skip sys_memory
  /// \skip static enum MkErrorE SysDaemonize
  /// \until MK_ERROR_NOT_SUPPORTED
  /// \until } 
  enum MkErrorE (*SysDaemonize) (
    MK_OBJ const          obj,
    MK_CST                pidfile
  );
```
kernel_mk.h:3216: warning: MkLalS::SysDaemonize has @param documentation sections but no arguments ???

```
The \e runtime provide the following features:
\li the \e default-error -> \RDocNs{MkErrorC}
\li the runtime local storage (\e RLS) for various internal features
\li application wide configuration data like \e debug \e logfile or \e silent
```
kernel_mk.h:11616: warning: Illegal command \ifile found as part of a \e command
→ last `\e silent` in line

**Comment by albert-github** [comment]
Do you have 2 problems here ?

As with the previous issue https://github.com/doxygen/doxygen/issues/9659 (on which no further information followed though):

Some code is available but not enough to reproduce the problem:
-    Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

**Comment by albert-github** [comment]
The mentioned problems are not reproducible with the given 1.9.5 version without an example.
Setting issue to not reproducible.
