### ISSUE TITLE
enhancement: INLINE_SOURCES should have a suboption for disabling for prototypes (Origin: bugzilla #133506)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#969]
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.5.3-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2004-02-05 13:37:29 +0000, enrico.schnepel@bankgesellschaft.de wrote:

    The option INLINE_SOURCES should have a suboption which makes it possible 
    to disable the insertion of sources (and call graphs; maybe with a second 
    option) for prototype definitions.

**Comment by albert-github** [comment]
It is unclear what is meant here, when having as an example:
```
/// \file


/// fie proto
void pr_1();

/// fie proto
void pr_2();

/// full fie
void fie()
{
  pr_1();
  pr_2();
}
```
which results in:
![image](https://github.com/doxygen/doxygen/assets/5223533/2ea1249e-4a8c-4b85-8fc5-917ffc4e443e)

with the 1.5.3 version as well as with the current (1.9.8) doxygen version.
