### ISSUE TITLE
Minor correction to documentation

### ISSUE THREAD

**Issue by randolf** [doxygen/doxygen#9697]
There's a minor typing error on this page of the manual:  https://www.doxygen.nl/manual/commands.html#cmdimage

The words "caption s" should be written as "caption is" (in the 7th paragraph).

Note:  I couldn't find the file "commands.html" anywhere in this GIT repository, otherwise I would have just created a pull request -- if there's a different GIT repository for the documentation, I'll gladly create a pull request there.

Thanks.

**Comment by albert-github** [comment]
Thanks for reporting
The file `commands.html` as well as `commands.tex` are not in the repository as they are derived information. The files are derived from `docs/commands.doc` (just a plain ASCII file) and converted by doxygen.

I've just pushed a proposed patch, pull request #9698

**Comment by randolf** [comment]
Thanks!

**Comment by randolf** [comment]
I marked this as "Closed" because there's a Pull Request for it now.

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).
