### ISSUE TITLE
Cannot find searchbox

### ISSUE THREAD

**Issue by echoeslove** [doxygen/doxygen#9705]
**Describe the bug**
I cannot find searchbox.

**Expected behavior**
Need to display searchbox like this.
<img width="1465" alt="截屏2022-12-01 上午10 22 42" src="https://user-images.githubusercontent.com/26243048/204950639-ff0218a8-f812-4564-883e-4f155ea05bf9.png">

**Screenshots**
Here's my output index.html, cannot find serachbox.
<img width="1669" alt="截屏2022-12-01 上午10 16 00" src="https://user-images.githubusercontent.com/26243048/204949836-60f0402b-31f0-4386-9b94-bd9ddf5842ac.png">

**Version**
Doxygen version is the latest versrion 1.9.5

**Additional context**
here's my doxyfile config
```
# Difference with default Doxyfile 1.9.5 (2f6875a5ca481a69a6f32650c77a667f87d25e88)
PROJECT_NAME           = "My Project 2"
OUTPUT_DIRECTORY       = /Users/chenmingjie/DoxygenWorkspace/cpp
EXTRACT_ALL            = YES
EXTRACT_PRIVATE        = YES
EXTRACT_PACKAGE        = YES
EXTRACT_STATIC         = YES
INPUT                  = /Users/chenmingjie/Downloads/TinyWebServer-master
RECURSIVE              = YES
SOURCE_BROWSER         = YES
GENERATE_HTMLHELP      = YES
SERVER_BASED_SEARCH    = YES
EXTERNAL_SEARCH        = YES
GENERATE_LATEX         = NO
HAVE_DOT               = YES
CALL_GRAPH             = YES
CALLER_GRAPH           = YES
DOT_PATH               = /usr/local/Cellar/graphviz/7.0.2/bin
```

**Comment by albert-github** [comment]
You have
```
GENERATE_HTMLHELP = YES
```
and this gives the configuartion warnings:
```
error: When enabling GENERATE_HTMLHELP the SEARCHENGINE option should be disabled. I'll adjust it for you.
error: When enabling GENERATE_HTMLHELP the HTML_DYNAMIC_MENUS option should be disabled. I'll adjust it for you.
error: When enabling 'GENERATE_HTMLHELP' the 'HTML_COLORSTYLE' option should be either 'LIGHT' or 'DARK' but has value 'AUTO_LIGHT'. I'll adjust it for you to 'LIGHT'.
```

This is all due to the limited possibilities of the HTML help (the chm output). Possibly you didn't intend to use it so setting `GENERATE_HTMLHELP=NO` solves your issue. If it was intended then you need 2 runs on separate directories, one for the normal HTML output and one for the HTML help output.

Note: I also made the `Doxyfile` shown in the issue a bit smaller (just showing the differences with the default 1.9.5 version (`doxygen -x Doxyfile`)

I think the problem is usage.

**Comment by echoeslove** [comment]
> You have
> 
> ```
> GENERATE_HTMLHELP = YES
> ```
> 
> and this gives the configuartion warnings:
> 
> ```
> error: When enabling GENERATE_HTMLHELP the SEARCHENGINE option should be disabled. I'll adjust it for you.
> error: When enabling GENERATE_HTMLHELP the HTML_DYNAMIC_MENUS option should be disabled. I'll adjust it for you.
> error: When enabling 'GENERATE_HTMLHELP' the 'HTML_COLORSTYLE' option should be either 'LIGHT' or 'DARK' but has value 'AUTO_LIGHT'. I'll adjust it for you to 'LIGHT'.
> ```
> 
> This is all due to the limited possibilities of the HTML help (the chm output). Possibly you didn't intend to use it so setting `GENERATE_HTMLHELP=NO` solves your issue. If it was intended then you need 2 runs on separate directories, one for the normal HTML output and one for the HTML help output.
> 
> Note: I also made the `Doxyfile` shown in the issue a bit smaller (just showing the differences with the default 1.9.5 version (`doxygen -x Doxyfile`)
> 
> I think the problem is usage.

Thx, the problem is solved.
