### ISSUE TITLE
"Referenced by" and "References" links to functions (Origin: bugzilla #133515)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#971]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.3-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2004-02-05 14:55:47 +0000, enrico.schnepel@bankgesellschaft.de wrote:

    The links of "Referenced by" and "References" lists should go to the 
    function itself and not to the sourcefile of corresponding .c-file.

**Comment by albert-github** [comment]
By default the link is to the source code (when the source code is present).
In version 1.4.7 the setting `REFERENCES_LINK_SOURCE` (default `YES`) is introduced and by setting this to `NO` the desired effect is accomplished.
(Note: the issue states that it is against 1.5.3-svn but seen the date of the issue this is not possible, at that moment 1.3.5 was the current version).

I think the problem has been solved in the mean time.
