### ISSUE TITLE
Doxygen links fails due to TLS issues in SourceForge

### ISSUE THREAD

**Issue by aminya** [doxygen/doxygen#9732]
**Describe the bug**

The download links for Windows Doxygen fail randomly due to TLS issues in SourceForge

Related to the same issue in setup-cpp
https://github.com/aminya/setup-cpp/issues/101

**Expected behavior**
Reliable download links

**Screenshots**
N/A

**To Reproduce**

I have linked some reproduction in 
https://github.com/aminya/setup-cpp/issues/101

This is mostly random and is fixed by retrying the download a couple of times

**Version**
All versions (e.g. 1.9.4)

**Stack trace**

For example, if we use Chocolatey to download Doxygen
```
Chocolatey v1.1.0
Installing the following packages:
doxygen.install
By installing, you accept licenses for the packages.

Progress: Downloading doxygen.install 1.9.4... 19%
Progress: Downloading doxygen.install 1.9.4... 57%
Progress: Downloading doxygen.install 1.9.4... 95%
Progress: Downloading doxygen.install 1.9.4... 100%

doxygen.install v1.9.4 [Approved]
doxygen.install package files install completed. Performing other installation steps.
Downloading doxygen.install
from 'https://sourceforge.net/projects/doxygen/files/rel-1.9.4/doxygen-1.9.4-setup.exe/download'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://sourceforge.net/projects/doxygen/files/rel-1.9.4/doxygen-1.9.4-setup.exe/download'. Exception calling "GetResponse" with "0" argument(s): "The request was aborted: Could not create SSL/TLS secure channel."
This package is likely not broken for licensed users - see https://docs.chocolatey.org/en-us/features/private-cdn.
The install of doxygen.install was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\doxygen.install\tools\chocolateyInstall.ps1'.
See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
- doxygen.install (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\doxygen.install\tools\chocolateyInstall.ps1'.
See log for details.
Error: Error: Command failed with exit code 404: choco install -y doxygen.install --version=1.9.4
```

**Additional context**

**Comment by albert-github** [comment]
- the distributions on SourceForge are there for historical reasons and the availability is not controlled by doxygen
- Chocolatey is not controlled by doxygen, so depending on what externally is implemented
- the latest released version of doxygen is available through https://www.doxygen.nl/download.html

So I don't think this is really a doxygen problem, though @doxygen should we have a look into the possibilities of "Releases" on GitHub as a parallel place to store executables etc.?

**Comment by doxygen** [comment]
@albert-github I've now created a python script to automate the process of creating a release and uploading the assets to GitHub. Just tried it on release 1.9.5, see https://github.com/doxygen/doxygen/releases/tag/Release_1_9_5
