### ISSUE TITLE
Doxygen produces invalid output for many C# interpolated strings

### ISSUE THREAD

**Issue by gvsoft3750** [doxygen/doxygen#9756]
**Describe the bug**
doxygen v1.9.6 fixed an issue with doxygen not generating class information in the presence of certain interpolated strings in C# (see: https://github.com/doxygen/doxygen/issues/9736).

However, v1.9.6 now has other, new issues with interpolated strings.  Specifically, doxygen produces output for non-existent Functions and Variables for certain interpolated strings.  The behavior is hard to pin down, because sometimes removing or commenting out code that is unrelated to the issue can affect whether or not the invalid output is generated.

In addition, there are no normal functions or variables documented in the "File Reference" pages, while they do appear on the "Class Reference" pages.  Is this normal/expected for C# code?

**Expected behavior**
doxygen should not produce Function or Variable documentation for text found within interpolated strings.

**Screenshots**
![image](https://user-images.githubusercontent.com/98843223/210101830-529aaae4-49cf-471d-90d3-86c4f9dda34c.png)

**To Reproduce**
The following zip file contains a C# source file that produces the output shown in the screenshot above:
[doxygentest.zip](https://github.com/doxygen/doxygen/files/10325906/doxygentest.zip)

For example:
`sql.AppendLine($"INSERT INTO {returnValue.TableName} ({columnListJoined}) ");`

produces the following output for the non-existent function:

$ 	SETIENTITY_INSERT [{tableName}]

**Version**
doxygen v1.9.6
Windows 10, 64-bit

**Stack trace**
None

**Additional context**
None

Thanks,
Dennis Jones

**Comment by albert-github** [comment]
Looks a bit like that the interpolated string fixes as done in #9738 (for issue #9736) are not sufficient and that this is next one to consider (FindMembers,FindMemberName  parts).

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #9759

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.7.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
