### ISSUE TITLE
forward declaration of default template parameters forgotten (Origin: bugzilla #134211)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#976]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.3.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2004-02-12 13:04:10 +0000, Guillaume Melquiond wrote:

    Doxygen forgets what the default template parameters are if they are
    declared before the actual class definition. In the following code snippet,
    F is correctly handled and its inheritance diagram contains Z<void> and
    Z<void>. However E is not correctly handled: its diagram contains Z<void>
    and Z<T2> (Doxygen has forgotten that T2 defaults to T1).
    
    template< class T > struct Z;
    template< class T1, class T2 = T1 > struct A; // forward declaration
    template< class T1, class T2 = T1 > struct B: Z< T1 >, Z< T2 > {};
    template< class T1, class T2 > struct A: Z< T1 >, Z< T2 > {};
    struct E: A< void > {};
    struct F: B< void > {};

**Comment by albert-github** [comment]
With the versions 1.3.5. and 1.3.56 and a default doxygen settings file and only setting `EXTRACT_ALL=YES` nothing is shown. In version 1.8.20 an inheritance graph is shown for `B` but not for `A`. In the current master (1.9.0 (fa65bb38f81457d00f9c900bb57eb68bea59b1b4)), both are shown (probably due to #8177).

I think the problem is fixed but not released.

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
