### ISSUE TITLE
Python docstring: brief and detailed description not correctly separated by blank line

### ISSUE THREAD

**Issue by thom-sch** [doxygen/doxygen#9763]
**Describe the bug**
Documenting class methods with a docstring brief and detailed description are not correctly separated by a blank line: brief description is ok, but detailed description apears as verbatim - regardless of using `"""!` or setting PYTHON_DOCSTRING to NO.
--> see MethodA in the example
This behaves only to method documentation, class documentation is ok! 
--> see ClassA in the example
Using multiline brief description is ok (see MethodB), and explcitely using \\details (MethodC) is ok, too, as well as putting the documentation above the Methods using two hashes `##`

**Expected behavior**
Blank line should separate brief and details section as in C/C++

**To Reproduce**
see attached example
[Test20_python_doc.zip](https://github.com/doxygen/doxygen/files/10332644/Test20_python_doc.zip)

**Version**
Latest Doxygen V.1.9.6

**Additional context**
The behavior seems not to depend on setting of othe configuration flags like JAVADOC_AUTOBRIEF or QT_AUTOBRIEF

Regards from Meerbusch
Thomas

**Comment by albert-github** [comment]
Difficult problem as this has to do with the extra indentation in the docstring. The fact that `MethodB` does work is probably due to the recalculation of the indentation.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #9767 

@thom-sch please test the the patch on your real project.

**Comment by thom-sch** [comment]
Thanks for fixing, works well on my project. 👍 

Regards from Meerbusch
Thomas

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.7.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
