### ISSUE TITLE
Doxygen doesn't correctly treat nested \if statements

### ISSUE THREAD

**Issue by StefanBattmer** [doxygen/doxygen#9779]
**Describe the bug**
Parts of the documentation of the top level \if statement (enabled vis ENABLED_SECTIONS in the doxyfile) end up in the documentation. This is correct but parts from the \else statement end up being in the output as well. I did test this with 1.9.6 and even 1.8.10. Same result. 

**Expected behavior**
Only the enabled stuff should end up being documented

**Screenshots**
![IncorrectOutput](https://user-images.githubusercontent.com/33477553/211494851-ca117e75-0d06-41c6-a428-f910e82c0501.JPG)

**To Reproduce**
I attached a version reproducing the effect. Removing *BUILD_WITH_A* from the ENABLED_SECTIONS results in correct output. This might be related to the fact that then only the \else branch is touched.

**Version**
1.9.6 but also 1.8.10

[DoxygenIssue.zip](https://github.com/doxygen/doxygen/files/10380447/DoxygenIssue.zip)

**Comment by albert-github** [comment]
Problem is also present when using `\elseif`.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #9789

**Comment by StefanBattmer** [comment]
@albert-github: Just to make sure: Shall we test this on our end now? I am just asking because the Build of the pull request wasn't successful.

**Comment by albert-github** [comment]
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by StefanBattmer** [comment]
@albert-github: I can confirm that this patch does the job! Thanks!

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.7.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
