### ISSUE TITLE
"Detected potential recursive class relation" occurs in example cpp files that have the same inherited class

### ISSUE THREAD

**Issue by st-masa** [doxygen/doxygen#9782]
**Describe the bug**

Two examples that include the same inherited class definition causes "Detected potential recursive class relation".
( [recursiveClass.zip](https://github.com/doxygen/doxygen/files/10383330/recursiveClass.zip) )

```
recursiveClass/examples/example2.cpp:12: error: Detected potential recursive class relation between class Inherited and base class common::Base!
```

Only example2.cpp causes the error message.

As a workaound, when these classes are placed inside anonymous namespace, this error will not be emitted. 

**Expected behavior**
* No error/warning message is diplayed for these inherited classes.

**To Reproduce**

1. Extract the attachment [recursiveClass.zip](https://github.com/doxygen/doxygen/files/10383330/recursiveClass.zip)
2. Create document

**Version**
1.9.6 on Windows 10 (64 bit) and MacOSX.

**Additional context**

The commit f502b19 may be affecting this behavior.

**Comment by st-masa** [comment]
This warning does not occur since version 1.9.8. Is there any fix for this issue?

**Comment by albert-github** [comment]
@st-masa 
It looks like that this specific  warning is gone. So I think this issue is solved in the mean time.
