### ISSUE TITLE
Doxygen complains about return type not documented for a function that returns void.

### ISSUE THREAD

**Issue by sommerluk** [doxygen/doxygen#9787]
**Describe the bug**
Doxygen complains about return type not documented for a function that returns void.

In the example project, simple run doxygen without further arguments in the project’s directory.
The current doxygen output is:
```
/home/username/doxygen_minimal_example/settranslation.h:10: warning: return type of member setTranslation is not documented
```

**Expected behavior**
For functions that return void, Doxygen does not complain about missing documentation for return type for functions that return void.

**To Reproduce**
In the example project, simple run doxygen without further arguments in the project’s directory.
[doxygen_minimal_example.tar.gz](https://github.com/doxygen/doxygen/files/10405079/doxygen_minimal_example.tar.gz)

**Version**
Tested locally on doxygen 1.9.1, using the distribution’s binaries.
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

Same on the CI system (Docker image debian:testing and doxygen version 1.9.4)

**Comment by albert-github** [comment]
The problem here is the fact that `MACRO_EXPANSION` is not set (by default it is set to NO) and this the preprocessor sees:
```
void IMPORTEXPORT setTranslation();
```
instead of 
```
void    setTranslation();
```
and thus doxygen thinks a return type is necessary.


So setting `MACRO_EXPANSION=YES` solves the issue.

Problem can be see by issuing `-d preprocessor` with doxygen.

Note the 1.9.1 version is already a bit older (January 8, 2020), the current version is 1.9.6

I think the problem is usage.

**Comment by sommerluk** [comment]
Okay, I see. Indeed, the error message disappears when using `MACRO_EXPANSION=YES`.

Now, the real macro definition in my original source code was something that breaks down to either Q_DECL_IMPORT or Q_DECL_EXPORT. See the attached, slightly extended minimal example. There, I still get the same error message. Apparently, because it does not parse `qtglobal.h`. Can I convince Doxygen to do so?

[doxygen_minimal_example.tar.gz](https://github.com/doxygen/doxygen/files/10419087/doxygen_minimal_example.tar.gz)

Or would it be more appropriate to use 
```
PREDEFINED             = Q_DECL_IMPORT= \
                         Q_DECL_EXPORT
```
instead?

**Comment by albert-github** [comment]
I think you have here the possibilities:
- the `PREDEFINED` as you already suggested
- the `INCLUDE_PATH` and set this so the the `qtglobal.h` can be found

I think the choice is is up to the project and a bit of depending on whether the `INCLUDE_PATH` is giving extra problems or not.

**Comment by sommerluk** [comment]
Indeed, `INCLUDE_PATH` seems to need more work. So I’ll stick with `PREDEFINED`.

Thanks _a lot_ for the help!
