### ISSUE TITLE
typedef of function pointer is wrongly parsed in symbolMap

### ISSUE THREAD

**Issue by st-masa** [doxygen/doxygen#9788]
**Describe the bug**

When function pointer is defined like this, the last argument will be stored in Doxygen::symbolMap.

```
typedef void ( stdcall *func_ptr )( int one, float two, double three );
```

And when namespace `three` is defined, enum symbol under `three` is not linked as autolink.

While if `()` and `stdcall *func_ptr` are not space-separated, that is linked successfully.
```
typedef void (stdcall *func_ptr)( int one, float two, void* three );
```

In the attachment [typedefSample.zip](https://github.com/doxygen/doxygen/files/10419438/typedefSample.zip):
* typedef.h
  * It has typedef definitions which has `three` as the last argument.
* header.h
  * namespece `three` is defined, that is the same as last argument name of typedef func_ptr.
  * Enum `three::SampleEnum` and class `three::Sample` are defined under namespace `three`.

**Expected behavior**
* `three::SampleEnum` is linked even though `typedef.h` has definiton shown above.

**To Reproduce**

1. Enable the following printf in SymbolResolver::Private::substTypedef() (symbolresolver.cpp L1450) and build doxygen.
```
  printf("substTypedef(%s,%s)=%s\n",scope?qPrint(scope->name()):"<global>",
                                    qPrint(name),qPrint(result));
```

2. Extract the attachment [typedefSample.zip](https://github.com/doxygen/doxygen/files/10419438/typedefSample.zip) and create document.

Debug log above says as follows and three::SampleEnum is NOT linked:

```
substTypedef(three,three)=float double
substTypedef(<globalScope>,three)=float double
substTypedef(<globalScope>,three)=float double
```

When func_ptr2 is commented out, debug log says as follows and three::SampleEnum is successfully linked:

```
substTypedef(three,three)=three
substTypedef(<globalScope>,three)=three
```

**Version**
1.9.5 and 1.9.6 on Windows 10 (64 bit) and MacOSX.
Not occurs in 1.9.4.

**Comment by albert-github** [comment]
Looks like that the difference is introduced with:
```
Commit: b290399fab92df45376103d7c094f053f24495fa [b290399]
Date: Tuesday, May 24, 2022 8:12:07 AM
Commit Date: Friday, June 3, 2022 9:38:54 PM
Refactoring: reimplement getDefs using symbol resolver
```

**Comment by doxygen** [comment]
I think the root of the problem is the use of the non-standard `stdcall` 'keyword'.

If I add this to the config file
```
PREDEFINED             = stdcall=
```
it works fine again.

**Comment by albert-github** [comment]
So when considering the problem the problem is really a usage problem as the non standard keyword `stdcall` is used (and should be handled as described in https://www.doxygen.nl/manual/preprocessing.html (for `__declspec`).


Setting issue to usage.

**Comment by st-masa** [comment]
Thank you for advising and sorry for late response.
Yes, I could take measures by suppressing non-standard keyword.

https://www.doxygen.nl/manual/preprocessing.html
> When nothing is done, doxygen will be confused and see __declspec as some sort of function. To help doxygen one typically uses the following preprocessor settings:

Accoding to above, I understood this is "confused" behavior.
Hopefully we could easily find this kind of misinterpretation by a warning or something.
