### ISSUE TITLE
Problem with subgrouping (Origin: bugzilla #134315)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#983]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.3.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2004-02-13 12:24:21 +0000, cyril.bes@philips.com wrote:

    In one of my header file i have a list of #define.
    If i group some of them and generate the HTML ouput
    they do not appear as a subgroup of the DEFINE group.
    Note that my variable SUBGROUPING is set to YES.

On 2005-11-03 17:13:28 +0000, Johann Stampler wrote:

    This is still true for Version 1.4.5. In my output the list of #define
    appears
    in the "Data Structures" section.

**Comment by albert-github** [comment]
It is unclear how the files / comments are exactly build and therefore not reproducible.
