### ISSUE TITLE
Suggestion: Ignore top-level cv-qualifiers in function parameter lists

### ISSUE THREAD

**Issue by lamm45** [doxygen/doxygen#9836]
In C++ (and probably in C also),
```c++
void fun(cv int x) {}
```
actually declares a function of type `void(int)` regardless of the "value" of the cv-qualifier (`const`, `volatile`, `const volatile` or none). This makes sense, and from the point of view of the caller, the cv-qualifier has no effect. It is an implementation detail. Unlike parameter names (which of course don't change the function type either), the cv-qualifier doesn't really add any value to the documentation and generally does not need to be known by the user of the function.

Currently (as of version 1.9.7), doxygen shows cv-qualifiers as they are written in the parameter list of the function declaration. If the function definition is elsewhere, then by including the cv-qualifiers only in the definition will give the desired (in my opinion, at least) doxygen output. However, for inline functions there is no workaround. For example:
```c++
struct S {
    int incr(const int x) {
        return x + 1;
    }
};
```
This will give the following doxygen output:
![Screenshot_20230205_154417](https://user-images.githubusercontent.com/96844552/216844847-f250ce33-decc-4383-a611-51e90be8d81e.png)
where the constness is unnecessarily (in my opinion) shown. I suggest that the cv-qualifier would not be shown.

Obviously, non-top-level cv-qualifiers affect how the function can be used and thus are not implementation details:
```c++
void g(char* c) {}
void g(const char* c) {}
```
are two different functions (but `void g(char* const c) {}` would be a redefinition of the first one).

**Comment by lamm45** [comment]
In your example, the constness affects the object x *refes to*, not x itself. Therefore, it is not a top-level cv-qualifier. The situation is analogous to the two `g` functions that I presented. A reference that is itself const would be `int& const x`. However, this is illegal syntax, because a reference cannot be re-bound to another object in any case, so `const` would be redundant (and confusing).

To illustrate, let me define ten functions `f1 ... f10`:
```c++
void f1(int x)               { }
void f2(const int x)         { }
void f3(int* x)              { }
void f4(int* const x)        { }
void f5(const int* x)        { }
void f6(const int* const x)  { }
void f7(int& x)              { }
void f8(int& const)          { }
void f9(const int& x)        { }
void f10(const int& const)   { }
```

If I try to compile this file with `g++ -Wall -Wextra funtypes.cpp`, I get the following diagnostic messages:
```
funtypes.cpp: In function ‘void f1(int)’:
funtypes.cpp:1:13: warning: unused parameter ‘x’ [-Wunused-parameter]
    1 | void f1(int x)               { }
      |         ~~~~^
funtypes.cpp: In function ‘void f2(int)’:
funtypes.cpp:2:19: warning: unused parameter ‘x’ [-Wunused-parameter]
    2 | void f2(const int x)         { }
      |         ~~~~~~~~~~^
funtypes.cpp: In function ‘void f3(int*)’:
funtypes.cpp:3:14: warning: unused parameter ‘x’ [-Wunused-parameter]
    3 | void f3(int* x)              { }
      |         ~~~~~^
funtypes.cpp: In function ‘void f4(int*)’:
funtypes.cpp:4:20: warning: unused parameter ‘x’ [-Wunused-parameter]
    4 | void f4(int* const x)        { }
      |         ~~~~~~~~~~~^
funtypes.cpp: In function ‘void f5(const int*)’:
funtypes.cpp:5:20: warning: unused parameter ‘x’ [-Wunused-parameter]
    5 | void f5(const int* x)        { }
      |         ~~~~~~~~~~~^
funtypes.cpp: In function ‘void f6(const int*)’:
funtypes.cpp:6:26: warning: unused parameter ‘x’ [-Wunused-parameter]
    6 | void f6(const int* const x)  { }
      |         ~~~~~~~~~~~~~~~~~^
funtypes.cpp: In function ‘void f7(int&)’:
funtypes.cpp:7:14: warning: unused parameter ‘x’ [-Wunused-parameter]
    7 | void f7(int& x)              { }
      |         ~~~~~^
funtypes.cpp: At global scope:
funtypes.cpp:8:14: error: ‘const’ qualifiers cannot be applied to ‘int&’
    8 | void f8(int& const)          { }
      |              ^~~~~
funtypes.cpp: In function ‘void f9(const int&)’:
funtypes.cpp:9:20: warning: unused parameter ‘x’ [-Wunused-parameter]
    9 | void f9(const int& x)        { }
      |         ~~~~~~~~~~~^
funtypes.cpp: At global scope:
funtypes.cpp:10:21: error: ‘const’ qualifiers cannot be applied to ‘const int&’
   10 | void f10(const int& const)   { }
      |                     ^~~~~
```

Notice how the second warning message begins with `In function ‘void f2(int)’`. The constness in `f2` is not shown. Thus, the first and the second function are the same (except that they have different names). Likewise, `f3` and `f4` are the same, and so are `f5` and `f6`. Presumably, `f7` and `f8` would be the same, if the latter were valid syntax. The same applies for `f9` and `f10`.

Here are some further explanations: https://stackoverflow.com/a/24030008

**Comment by albert-github** [comment]
I agree that with the gcc compiler the warning message doesn't show the `const` for e.g. `f2` indicating that the `const` is in the interpretation of the compiler, rightfully, not necessary. The compiler shows its interpretation of the function.

Doxygen is not a compiler and does not really interpret the meaning of the different qualifiers in a language sense, hence for doxygen the words like `const` etc. are still necessary for the description.
