### ISSUE TITLE
Long lines in markdown tables

### ISSUE THREAD

**Issue by Gemini67** [doxygen/doxygen#9871]
It should be possible to write the text for a cell in a markdown table in multiple lines. What is needed is some kind of special character/sequence which means: Continue parsing on the next line, without starting a new cell/row/anything.

**Expected behavior**
Cell contents can be written on multiple lines.

**To Reproduce**
Write a cell text on multiple lines: The new line and everything below is formatted as pure text.

**Version**
1.8.5

**Additional context**
There are multiple questions on StackOverflow asking for the same.

**Comment by albert-github** [comment]
Doxygen version 1.8.5 is very old (August 23, 2013) the current version of doxygen is 1.9.6 so it is definitely advised to update.

Regarding the markdown problem, I don't think there is such a character. This is more general question so it might be better to post a question at https://stackoverflow.com and label it with `markdown`

Best is to use HTML like tables.

**Comment by Gemini67** [comment]
It may be old, but that is what I am allowed to use currently.
As I mentioned: There are already multiple questions for exactly that problem on StackOverflow, and none of them have a satisfactory answer.
HTML tables would still create a new line in the table ( <td>...</td>), which is not what I want.

Please consider to add such a feature (maybe a simple \ at the end of the line?).

**Comment by albert-github** [comment]
> HTML tables would still create a new line in the table ( <td>...</td>), which is not what I want. 

I don't get this.

When I have:
```
<table>
<tr><th>X</th><th>Y</th><th>Z</th></tr>
<tr><td>X</td><td>Y</td><td>Z</td></tr>
<tr><td>X</td><td>Y and now continued
at the next line</td><td>Z</td></tr>
<tr><td>X</td><td>Y</td><td>Z</td></tr>
</table>
```

this results in the 1.8.5 and the current version (1.9.6) in:
![image](https://user-images.githubusercontent.com/5223533/220866218-fefde416-fd61-4b5d-917d-c8086202aedc.png)

So when you have a problem with the table please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

I still would advise to switch to 1.9.6 as a lot of changes have been made and a lot of bugs have been fixed and new features have been introduced.
