### ISSUE TITLE
typedefs with same name from different namespaces not resolved correctly (Origin: bugzilla #134719)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#988]
status NEW severity *normal* in component *general* for *---*
Reported in version *1.3.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2004-02-18 10:55:28 +0000, tim.vanholder@anubex.com wrote:

    If two different namespaces have a typedef of the same name, doxygen
    ignores all except one of them.
    
    Given the following two namespaces:
    
    namespace A {
    
      typedef float foo_t;
    
      static inline void
      bar_A(foo_t& fooval)
      {
      foo_t hi_dad;
        fooval += 2;
      }
    
    }
    
    namespace B {
    
      typedef int foo_t;
    
      static inline void
      bar_B(foo_t& fooval)
      {
      foo_t hi_mom;
        fooval *= 2;
      }
    
    }
    
    These have nothing in common, other than the foo_t name for a typedef.
    However, if doxygen is run (using EXTRACT_ALL=YES, SOURCE_BROWSER=YES, and
    INLINE_SOURCE=YES), a few anomalies are noticed:
    
    - B's foo_t has no 'Referenced By' entries (A's foo_t does), and bar_B has
      no 'References' entries (bar_A does).
      Presumably related to this, the uses of foo_t in bar_B are not links in
      the source browser.
    - The foo_t in bar_B's code gets linked to A's foo_t for the inline code
      listing.  Oddly enough, bar_B does NOT get listed in the 'Referenced By'
      section of the A::foo_t entry.
    
    Note: in the source I originally noticed this behaviour in, the bar_B
    function (well, its equivalent anyway) DID have a 'References' entry, but
    it listed A::foo_t.
    
    Other types with the same name in multiple namespaces are handled just
    fine,  as evidenced by the results for the above after changing foo_t to a
    struct (although in that case the inline code does not contain a link for
    the occurrences of foo_t, which might be another bug).

On 2007-09-09 18:50:50 +0000, Lee Winder wrote:

    This also occurs with classes with the same name in different namespaces (or
    nested namespaces), even if (as templates) they have different template
    parameters.
    
    For example (qick pseudo code)
    
    namespace container {
    
    /*! 
    * @addtogroup Containers
    * @{
    */
    /*!
    * -- Documentation --
    */
    template< typename T, class Alloc = alloc::simple_alloc >
    class array
    {
      //...
    };
    
    /** @} */ // end of Containers
    }
    
    namespace container {
    namespace fixed {
    
    /*! 
    * @addtogroup Fixed_Containers
    * @{
    */
    /*!
    * -- Documentation --
    */
    template<typename T, size_t N>
    class array
    {
      //...
    };
    
    /** @} */ // end of Containers
    }}
    
    In the generated documentation, the same class (array< T, Alloc >) is
    displayed in both documentation groups, rather than the each different
    classes.  Interestingly no warnings or errors are generated when building
    the documentation.
    
    I have gotten around this by calling the second class farray, but I really
    don't like altering the code based to make the documentation tool work! :)
    
    This is occuring in v. 1.5.3

On 2007-10-15 07:10:43 +0000, Christoph Schulz wrote:

    Both test cases work for me without problems (doxygen 1.5.3 for Windows).

**Comment by albert-github** [comment]
The problems as reported in the original issue I can reproduce with the 1.3.6 version but with the curent doxygen version (1.12.0) these provlems are gone.

The problems as reported in the first comment I cannot reproduce with the 1.5.3 version, like also noted in the second comment  (nor are the reproducible with the current doxygen version).

So I think the original problem is solved in the mean time and the second problem is not reproducible.
