### ISSUE TITLE
Performance issues when HAVE_DOT is YES to make `\dot` work, and `CLASS_GRAPH=GRAPH` is also used

### ISSUE THREAD

**Issue by krolli** [doxygen/doxygen#9883]
In our code-base, we have been relying on `\dot` command working despite setting `HAVE_DOT=NO`. This has become problem as soon as https://github.com/doxygen/doxygen/issues/7273 has been resolved, as all uses of `\dot` command are now ignored.

After switching to `HAVE_DOT=YES`, uses of `\dot` work, but we have noticed an order-of-magnitude slowdown in doxygen performance. We disabled all graphs that we don't use but were enabled by default, leaving us with only `CLASS_GRAPH=GRAPH`, which helped performance a little bit, but it is still about 6x slower compared to just setting `HAVE_DOT=NO`.

We also verified that `CLASS_GRAPH=TEXT` gives us the same generation time as `HAVE_DOT=NO` to make sure there is nothing else that is causing significant amount of graphs to be generated.

Ultimately, we prefer built-in class graph generator over dot-based one, so we would like to have option to use that even though `HAVE_DOT=YES` is set.

We will probably be using `CLASS_GRAPH=TEXT` while iterating on documentation to keep things fast, and use `CLASS_GRAPH=GRAPH` on CI servers producing documentation over night. Though slowdown is an issue on CI as well, it's not as much of a problem as it is for documentation authors.

I don't know what would be the best solution to this problem in regards to overall doxygen architecture and design goals. One thing that would work perfectly well for us would be adding another possible value for `CLASS_GRAPH`, let's call it `BUILTIN_GRAPH`, which would force use of built-in class graph generator even when `HAVE_DOT=YES` is set. It should also be backwards compatible and not affect any existing configs using one of the previous values.

**Comment by albert-github** [comment]
- Which version of doxygen are you using?
- You mention a factor 6 but what are some absolute times? Do we speak about second, minutes, hours?
- What is the used setting of `DOT_NUM_THREADS`?
- What is the used setting of `DOT_IMAGE_FORMAT`?
- Do you clean the output directory between doxygen runs (not advised in your case as it will also remove the `.md5` files and `.png` / `.svg` resulting image files, they signal that an unchanged graph file doesn't need to be regenerated. In case of the internal images this might also be a big speedup as the internal files are always regenerated).

**Comment by krolli** [comment]
> Which version of doxygen are you using?

I measured performance impact of these settings on 1.9.1 (last version before `\dot` relies on `HAVE_DOT=YES` to work) and 1.9.6.

> You mention a factor 6 but what are some absolute times? Do we speak about second, minutes, hours?

We build multiple projects and absolute values depend on each one. 6x comes from the smallest project, where it was easy to switch around different settings and see their impact:
- `HAVE_DOT=NO CLASS_GRAPH=GRAPH` - 5.3s
- `HAVE_DOT=YES CLASS_GRAPH=TEXT` - 4.2s
- `HAVE_DOT=YES CLASS_GRAPH=GRAPH` - 28.6s

Larger projects take over 10 minutes, so it will take me some time to do measurements on those. I will post them in another message when I have them.

> What is the used setting of `DOT_NUM_THREADS`?

We leave this on default by not specifying it in our config, so according to generated default config, it should be `DOT_NUM_THREADS=0`, thus using all CPU cores. Measurements done on 8-core machine.

> What is the used setting of `DOT_IMAGE_FORMAT`?

`DOT_IMAGE_FORMAT=svg`. Also tried with `png`, but I didn't observe any significant difference.

> Do you clean the output directory between doxygen runs (not advised in your case as it will also remove the `.md5` files and `.png` / `.svg` resulting image files, they signal that an unchanged graph file doesn't need to be regenerated. In case of the internal images this might also be a big speedup as the internal files are always regenerated).

Hmm, we do clean it. I remember in the past it was often confusing when some generated HTML file was left behind from previous version, as it was showing stale information. While it shouldn't have been reachable through normal links, stale links on other places could easily lead to it, so at least CI server has to do clean builds.

I just tested without cleaning up the directory, adding following result to list above:
- `HAVE_DOT=YES CLASS_GRAPH=GRAPH incremental` - 4.1s

That is certainly big improvement and would be a lot easier to work with. What is the recommended way to avoid having to clean whole output directory between runs, so that we don't end up with stale files in there but also don't throw away build cache?

**Comment by albert-github** [comment]
The stale / old files can indeed be a bit of a nuisance due to postings of the links but should not influence the doxygen results (like you wrote) when at least the user starts from the index.html.
Indeed on the CI server best is to clean the entire directory so you have a clean result.
Best strategy: there is not really one but one could remove all files except the `.md`, `.svg` and `.map` files, it would possibly only leave some "image" files (probably not a lot only when some class structure really changed). Depending on how often the users run doxygen and the amount of stale "image" files it might be advisable to clean occasionally the entire directory. Another possibility would be just to remove the `.html` files.


Note: I also think the the setting `INTERACTIVE_SVG` might be of interest , especially for large structures.

(no need for the longer run, numbers give already a bit of an insight and the "normal" runtime from 10 minutes to e.g. 40 - 60 minutes is quite a bit)

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #9884

**Comment by krolli** [comment]
Thanks for the change!

I did more detailed measurements in the meantime. It seems I've underestimated characteristics of the projects for which we generate documentation for. I only have access to projects using C++ and C# parsers, so I can't comment on other languages, but it seems that C++ does not suffer from this as much as C# does, probably due to C++ processing cost dominating documentation build time.

- small C#: 847.54kB of source code, most of it class and function declarations without bodies (just bindings to native code)
- large C++: 6.26MB of header files (source files not included in documentation)
- large C#: 13.82MB of source code

Cases measured:
1. `HAVE_DOT=NO CLASS_GRAPH=GRAPH`
2. `HAVE_DOT=YES CLASS_GRAPH=TEXT`
3. `HAVE_DOT=YES CLASS_GRAPH=GRAPH`
4. `HAVE_DOT=YES CLASS_GRAPH=GRAPH` incremental run


|           | case 1  | case 2 | case 3 | case 4 |
| --------- | ------- | ------ | ------ | ------ |
| small C#  |   5.3s  |   4.2s |  28.6s |   4.1s |
| large C++ | 777.9s  | 780.2s | 860.4s | 780.7s |
| large C#  |  43.2s  |  32.8s | 250.4s |  32.4s |

It probably hurts people using C# (and maybe other languages) more than those using C++, though their build times are generally a lot shorter since language is simpler.

**Comment by albert-github** [comment]
• Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.7.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
