### ISSUE TITLE
strange error message for "copydoc "from known TAG file target.

### ISSUE THREAD

**Issue by aotto1968** [doxygen/doxygen#9886]
**Describe the bug**
→ get error message during doc build
→ `.../LcSettingC_lc.doc:789: warning: unexpected token TK_COMMAND_BS as the argument of \ifile`

**Expected behavior**
1. the message come from `\copydoc MkObjectC_Introspection_C_API` but this is in line 787
2. the `MkObjectC_Introspection_C_API` come from a TAG file (an other project) but reading DOC from an other project is NOT possible. I think this produce the strange message. The problem is the strange message, I get sometimes the "\ifile" issue messages → this is a new feature and probably not fully implemented.

**Screenshots**
If useful, add screenshots to help explain your problem.

**To Reproduce**
doc section…
```
785 // ==================================================================================
786 /// \addtogroup LcSettingC_Introspection_C_API 
787 /// \copydoc MkObjectC_Introspection_C_API
788 /// \{
789 // BEGIN-LcSettingC-Introspection-S - created by 'c_Native.tcl -i NHI1_HOME/theLink/liblcconfig/.liblcconfig.meta' - DO NOT change
790 #ifndef PARSE_C_HEADER_TO_META
791 
792 /**
793 \fn static mk_inline LC_CFS LcSettingInstances(void);
794 // reference for original
795 **/
796 #endif
797 // END-LcSettingC-Introspection-S - created by 'c_Native.tcl -i NHI1_HOME/theLink/liblcconfig/.liblcconfig.meta' - DO NOT change
798 // BEGIN-LcSettingC-Introspection-O - created by 'c_Native.tcl -i NHI1_HOME/theLink/liblcconfig/.liblcconfig.meta' - DO NOT change
799 #ifndef PARSE_C_HEADER_TO_META
800 
801 /**
802 \fn static mk_inline LC_CFS LcSettingNext(LC_CFS cfs);
803 // reference for original
804 **/
805 
806 /**
807 \fn static mk_inline LC_CFS LcSettingPrev(LC_CFS cfs);
808 // reference for original
809 **/
810 #endif
811 // END-LcSettingC-Introspection-O - created by 'c_Native.tcl -i NHI1_HOME/theLink/liblcconfig/.liblcconfig.meta' - DO NOT change
812 /// \}
```

**Version**
1.9.6  

**Additional context**

**Comment by albert-github** [comment]
Based on the small snippet of code it is not possible to reproduce the problem, always:
- attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

**Comment by albert-github** [comment]
> the `MkObjectC_Introspection_C_API` come from a TAG file

The tag file will only contain a reference to the other project and not the documentation so a `\copybrief` will not be able copy the documentation in any way.

I think the issue is a combination of usage and incomplete.
