### ISSUE TITLE
[C++] Class attributes (namely as macros) on a nested/inner class that's defined outside the outer class breaks member documentation search

### ISSUE THREAD

**Issue by oblivioncth** [doxygen/doxygen#9892]
**Describe the bug**
Using a macro as a class attribute on an inner class that is defined outside the class it is nested in causes Doxygen to no longer be able to find that classes member documentation. The macro's definition doesn't matter.

For example:

```
# foo.h

#define EXPORT

class EXPORT Foo
{
public:
    class Bar;    
    Foo();
};

class EXPORT Foo::Bar
{
public:
    Bar();
};
```
along with the appropriate class and constructor documentation in `foo.cpp` results in:

> warning: no matching class member found for
>   Foo::Bar()
> Possible candidates:
>   'Foo::Bar()' at line 24 of file foo.h
> ...
> warning: Member Bar() (function) of class Foo is not documented.

Doxygen seems to be aware of the association, but isn't confident enough to tie the definition and declaration together since it lists it as a candidate (given it's the only candidate I'd have thought it would choose it since there isn't ambiguity).

Furthermore, if the macro is replaced with content that it is likely aliasing, e.g.
`class __declspec(dllexport) Foo::Bar`

then a Doxygen mistakes it for a initializer list:
`warning: Found ';' while parsing initializer list! (doxygen could be confused by a macro call without semicolon)`

I never plan to do that and only use macros for this, but figured it was worth mentioning.

The following MRE directly demonstrates this issue, along with showing that it affects more than the constructor and doesn't affect inner classes that are defined in-line or inner classes without anything between `class` and their name.

**Expected behavior**
Doxygen correctly recognizes the documentation of nested class members regardless of how the class is defined and regardless of attributes.

**To Reproduce**
[Doxygen_Outside_Definition_Macro_Issue_MRE.zip](https://github.com/doxygen/doxygen/files/10889332/Doxygen_Outside_Definition_Macro_Issue_MRE.zip)

**Version**
Latest stable release from site:
1.9.6
Windows x64

**Additional Context**
I'd be happy to know if there was a workaround for this (I suppose other than moving the inner class' definition inside the outer class) in the meanwhile as no tweaks I tried, like also putting the macro on the inner class forward declaration inside the outer class, worked.

**Comment by albert-github** [comment]
What happens when you set `MACRO_EXPANSION=YES` ?
As far as I can see the warnings are gone.

I think the problem is usage.

**Comment by oblivioncth** [comment]
I had MACRO_EXPANSION on in the original project, but also am using EXPAND_ONLY_PREDEF.

So it seems to get around I this I need to do:
```
MACRO_EXPANSION        = YES
EXPAND_AS_DEFINED      = EXPORT
PREDEFINED             = __declspec(x)=
```
or simply:
```
MACRO_EXPANSION        = YES
EXPAND_AS_DEFINED      = EXPORT=
```

A bit unfortunate since 'EXPORT' is different in every project and I originally had this fully genericized, but not a big deal.

[The preprocessing page](https://www.doxygen.nl/manual/preprocessing.html), which I somehow didn't find when searching for this originally, does note this, but I'm surprised by the fact that guiding Doxygen in this manner wasn't needed until I reached a project with a nested class defined like this (i.e. how it works fine with the other class layouts in the MRE).

I suppose this is just an expected limitation of Doxygen's parser?
