### ISSUE TITLE
create report that indicates the logical linking of functions in a C code

### ISSUE THREAD

**Issue by danielebanfiwamblee** [doxygen/doxygen#9895]
In some critical applications (such as code for aeronautical products) it is required that the link between functions be highlighted, in order to demonstrate that there are no self-calling functions (to avoid loops).

I wonder if with doxygen it is possible to generate this information, for example

Function abc , called from function zzz, calls function ccc and vvv

Thank you / Daniele

**Comment by albert-github** [comment]
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.
- Please also specify the **full** doxygen version used (`doxygen -v`).

An explicit report like this doesn't exist in doxygen.
Detecting of recursive functions is a very hard problem, especially when having function calls through pointers (and these will be missed by doxygen).

You could have have look here at the `CALL_GRAPH` / `CALLER_GRAPH` / `REFERENCED_BY_RELATION` / `REFERENCES_RELATION` settings,
You could also have a look at the xml output (setting `GENERATE_XML`) and process the result.

**Comment by danielebanfiwamblee** [comment]
Ok noted, I'm investigate on CALL_GRAPH / CALLER_GRAPH / REFERENCED_BY_RELATION / REFERENCES_RELATION

Thanks / Daniele

**Comment by danielebanfiwamblee** [comment]
Ok , I've try and for me I think is enough for Level D aereonautical device.

Here a picture of call function path in my source code:

![_vAnalizeNMEA](https://user-images.githubusercontent.com/30384934/223089127-142faea1-2ba3-4d12-a53f-e9375f32686f.png)
