### ISSUE TITLE
Doxygen WARN_LOGFILE needs to create folder

### ISSUE THREAD

**Issue by Ryanf55** [doxygen/doxygen#9935]
Hey there, if this log file has a foldername in it, but the folder does not exist, this call is not creating the folder. Then, the log error message appears, and then my CI instance looking for the log output in that folder does not find it.

_Originally posted by @Ryanf55 in https://github.com/doxygen/doxygen/pull/9792#discussion_r1142685381_

Creating this issue to show an error condition that is swallowed by Doxygen. I would expect folders to created. 

Example:

Set  the following options:
```
WARN_LOGFILE  = foo/bar/errors.log
WARN_AS_ERROR = FAIL_ON_WARNINGS_PRINT
```
 without the `foo/bar` folder existing. It fails to open the file, and then errors are redirected to stdout. 

When I then use [doxygen-junit](https://github.com/johnthagen/doxygen-junit) to parse the doxygen results, the log doesn't exist and it fails. 

This was recently added in https://github.com/doxygen/doxygen/pull/9792. 

Perhaps it can be fixed before the next release? I really love this feature. Combined with Junit parsing, I can now have my CI results show up directly in Gitlab.

**Comment by albert-github** [comment]
When using the settings from https://github.com/doxygen/doxygen/issues/9935#issuecomment-1477880324 we get the warning:
```
error: Cannot open 'foo/bar/errors.log' for writing, redirecting 'WARN_LOGFILE' output to 'stderr'
```
so it is clearly indicated that the file could not be opened, though it would be nice to have that possibility.


I've just pushed a proposed patch, pull request #9939, this is just for a single level new directory for a multilevel directory it would be better to have the `mkpath`  method ad defined in the proposed pull request #8444

**Comment by doxygen** [comment]
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.7.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Comment by Ryanf55** [comment]
yea,it worked for me. Before the release, it would be lovely to fix up the documentation for this feature. It is extremely confusing to understand the description.

**Comment by albert-github** [comment]
@Ryanf55 What do you suggest?
