### ISSUE TITLE
@copybrief or @copydoc target not found when adding namespace

### ISSUE THREAD

**Issue by tdegeus** [doxygen/doxygen#9940]
**Describe the bug**

For this example

```cpp
namespace detail {

/**
 * @brief My class
 */
template <class ShapeType>
class Bar {
public:
    /**
     * @brief Number of particles.
     * @return Unsigned int
     */
    size_t N() const;

protected:
    size_type m_N; ///< @copybrief Bar::N
};

} // namespace detail

namespace Line1d {

/**
 * Foo
 */
class System_Cuspy_Laplace : public detail::Bar<double> {

};

} // namespace Line1d
```

with 
```
INPUT = main.hpp
WARN_IF_UNDOCUMENTED = YES
```
ran with 
```
doxygen
```

I get 
```
main.hpp:16: warning: @copybrief or @copydoc target 'Bar::N' not found
```

It works fine:
- If I have only one namespace.
- If there is no template.

**Expected behavior**

The `@copybrief` should just copy the brief of that class.

**Screenshots**

not relevant

**To Reproduce**

See above

**Version**

```
$ doxygen --version
1.9.5
```
Ran on macOS 13.2.1

**Stack trace**

not relevant

**Additional context**

not relevant

**Comment by albert-github** [comment]
With the 1.9.5 version of doxygen I can reproduce the problem, it looks to me though that that documentation is correct but that  but that the warning should not have been emitted.

With the current version (1.9.6) of doxygen I don't see the warning anymore.

I think the problem has been solved in the mean time.

**Comment by tdegeus** [comment]
Thanks @albert-github . I somehow I missed that the latest update was blocked on conda-forge. After updating the feedstock I can now confirm that the issue is gone in v1.9.6. Thanks!
