### ISSUE TITLE
How to exclude a macro string: EXCLUDE_SYMBOLS does not solve the problem

### ISSUE THREAD

**Issue by estebanzimanyi** [doxygen/doxygen#9973]
To enable building both on Linux and on Windows the external functions need a macro that depending on the target platform is either empty for Linux or is as follows for Windows
```
#define PGDLLEXPORT __declspec (dllexport)
```
The functions are thus defined as follows, e.g.,
```
PGDLLEXPORT Datum Geoset_as_ewkt (PG_FUNCTION_ARGS);
PG_FUNCTION_INFO_V1(Geoset_as_ewkt);
/**
 * @brief Return the Extended Well-Known Text (EWKT) representation of a geoset.
 */
Datum
Geoset_as_ewkt(PG_FUNCTION_ARGS)
{
  ...
}
```
I would like to remove the string "PGDLLEXPORT" in the signatures of the function and thus put in the Doxyfile
```
EXCLUDE_SYMBOLS        = "PG_FUNCTION_INFO_V1", "PGDLLEXPORT"
```
However, while `PG_FUNCTION_INFO_V1` symbol indeed is not shown in the documentation, the string `PGDLLEXPORT` is still there and is shown as follows in the generated documentation
```
Functions
-------------------
PGDLLEXPORT Datum | Geoset_as_ewkt (PG_FUNCTION_ARGS)
  | Return the Extended Well-Known Text (EWKT) representation of a geoset. More...
```
I downloaded the latest version.
```
$ doxygen --version
1.9.6 (4586b5cfaa3d46d51f6a51882951d15644c49edf)
```

**Comment by albert-github** [comment]
Based on the small code fragments it is not possible to reproduce the problem (a.o. seen the fact that it is unknown where e.g. the `#define`s are located), so:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.


Maybe you should also have a look at the settings `MACRO_EXPANSION` and `PREDEFIEND`

**Comment by estebanzimanyi** [comment]
Many thanks for your prompt reply !
Here is a zip containg a small file and my Doxyfile that shows the issue. Please let me know whether you need something else.
[doxygen_test.zip](https://github.com/doxygen/doxygen/files/11200672/doxygen_test.zip)

**Comment by albert-github** [comment]
The `PG_FUNCTION_INFO_V1`  is a function and as such handled through `EXCLUDE_SYMBOLS`.
Though neither `PGDLLEXPORT ` nor `PG_FUNCTION_ARGS` are functions but just "words", you have to redefine these by means of `PREDEFINED` like
```
PREDEFINED += PG_FUNCTION_ARGS
PREDEFINED += PGDLLEXPORT 
```
when I do this the words are gone from the documentation.

I think the problem is usage.

**Comment by estebanzimanyi** [comment]
Thanks again for your answer. I did as you instructed above setting in the Doxyfile
```
PREDEFINED += PG_FUNCTION_ARGS
PREDEFINED += PGDLLEXPORT
```
then run
```
$ doxygen doxygen_test.c
...
writing tag file...
Running plantuml with JAVA...
lookup cache used 1002/65536 hits=3740 misses=1019
finished...
```
and still shows the macros as shown in the followin screenshot

![image](https://user-images.githubusercontent.com/26899974/231185399-1bcd5099-e598-4fda-a238-95ab5fe94b11.png)

Am I doing something wrong ?

**Comment by estebanzimanyi** [comment]
Many many thanks ! That solved the issue !
