### ISSUE TITLE
Consecutive numbers are not searched.

### ISSUE THREAD

**Issue by hackingframework** [doxygen/doxygen#9977]
While documenting a C++ project with Doxygen, I also used the server discovery feature.
The web server environment is nginx, php7.4-fpm. I have enabled the following options

SEARCHENGINE = YES
SERVER_BASED_SEARCH = YES
EXTERNAL_SEARCH = NO

However, words like a list of numbers (e.g. 12345678) are not searched, as shown below.

Search Results
Sorry, no documents matching your query.

Is this a feature issue? Or is there a separate configuration option?

OS/Version: Windows 64bit 1.9.6

**Comment by albert-github** [comment]
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

**Comment by albert-github** [comment]
> However, words like a list of numbers (e.g. 12345678) are not searched, as shown below.

Nothing is shown

No example is provided, so problem is not reproducible
